### ISSUE TITLE
Add notifications dropdown to the nav-bar (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#10]
<img width="1680" alt="screen shot 2017-04-22 at 10 51 31 pm" src="https://cloud.githubusercontent.com/assets/2404372/25306619/4dca19f6-27ae-11e7-8457-fdb63aaff149.png">

We need a similar dropdown to display notifications.

**What is expected ?**
- Notifications dropdown as a separate [component](https://guides.emberjs.com/v2.12.0/getting-started/core-concepts/#toc_components) added to the nav-bar.
- UI Only for now. 

**References:**
- https://guides.emberjs.com/v2.12.0/components/defining-a-component/
- https://semantic-ui.com/collections/menu.html

**Comment by anweshknayak** [comment]
@niranjan94 can I take this up ?

**Comment by niranjan94** [comment]
@anweshknayak sure. Once you set up this project locally and run it, you can work on this issue.

**Comment by anweshknayak** [comment]
@niranjan94 http://simonwade.me/assets/ember-demos/#/ember-notify is this okay ?

**Comment by niranjan94** [comment]
@anweshknayak please see the screenshot attached along with the issue. We need something like that to display notifications such as when a new session proposal comes in for an event, or when any interesting event is live near by etc ... It needs to be shown on the navbar.

**Comment by niranjan94** [comment]
Similar to facebook notifications dropdown.

**Comment by niranjan94** [comment]
@anweshknayak any progress on this ? Need an help ?

**Comment by anweshknayak** [comment]
@niranjan94 Hey I am currently occupied with exams.

**Comment by abhishek71994** [comment]
Hi @niranjan94 I have the app running on my localhost.. Can I work on this for a day or two? I need some time to understand thing because I dont know how the app works.

**Comment by niranjan94** [comment]
@abhishek71994 yes. sure ... you can

**Comment by abhishek71994** [comment]
Whats the user ID and Password? as I understand that its only during a session that the notification component is supposed to be shown?

**Comment by niranjan94** [comment]
The same username/password you use on https://open-event-dev.herokuapp.com

**Comment by abhishek71994** [comment]
Are you reachable somewhere because I might have a lot of questions. IRC or somewhere?

**Comment by niranjan94** [comment]
You can reach me on Gitter -> https://gitter.im/niranjan94 ... You can also post your queries on https://gitter.im/fossasia/open-event-frontend

**Comment by sumedh123** [comment]
@abhishek1995s Are you working on this one? @niranjan94 Can I take this up?

**Comment by niranjan94** [comment]
@sumedh123 I think @abhishek71994 is already working on this. A PR (#31) is also open regarding this.

**Comment by abhishek71994** [comment]
yes @sumedh123 I am working on this issue

**Comment by CosmicCoder96** [comment]
@niranjan94 Feedback on the UI please.
![image](https://cloud.githubusercontent.com/assets/17252805/26252395/4dde11e0-3cda-11e7-98c5-0af40043f2a1.png)

**Comment by niranjan94** [comment]
@CosmicCoder96 

- We don't want a 'mark as read' for each notification. Clicking on it means it is marked as read.
- We need a common 'Mark all as read' option at the top. 
- We require notification count display on the icon in the navbar.
- In case you're not already using, use [Semantic UI's list](https://semantic-ui.com/elements/list.html) for the notifications list display. 
- Each notification item should have three components. Header, description and time.

**Comment by CosmicCoder96** [comment]
@niranjan94 Thanks for the feedback ! 

> We don't want a 'mark as read' for each notification. Clicking on it means it is marked as read.
That's what I was trying to ask on gitter 😅, I will make a common mark all as read.
>In case you're not already using, use Semantic UI's list for the notifications list display.
Yes,I'm using lists with header and description.
