### ISSUE TITLE
Rename forgot-password route to reset-password route

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1006]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

Currently the name of the route is forget-password where as the api expects it to be `reset-password` as is evident from this screenshot of a password recovery email generated by the open-event-server 
![image](https://user-images.githubusercontent.com/17252805/35487236-56d11148-049f-11e8-9410-c73cac768f3e.png)

This will serve as the first step towards making the token based password reset functional.

**Comment by ritikamotwani** [comment]
I would like to work on this issue.
