### ISSUE TITLE
Create UI for view route for sessions

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1028]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/36136898-9ded36c2-10b8-11e8-9522-d39cadde4021.png)

Url would be `/events/my-sessions/<session-id>`

**Comment by ritikamotwani** [comment]
I would like to work on this.

**Comment by CosmicCoder96** [comment]
@ritikamotwani go ahead, please refer to https://semantic-ui.com/ for styling and avoid adding any css of your own to make this page ! Thank you.
