### ISSUE TITLE
The connect with us tabs are not properly aligned

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#1034]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The tabs are not properly aligned.
**Expected behavior:**
The icons and the tabs should be properly aligned. 
**Screenshot:**
![screen shot 2018-02-16 at 10 13 51 pm](https://user-images.githubusercontent.com/31013104/36318724-bba70bf6-1366-11e8-9d8b-4ece6f2ada37.png)

I'm working on this.

**Comment by ashupednekar** [comment]
@harsh-jindal Are you still working on this? If not, then I'd like to...

**Comment by harsh-jindal** [comment]
@ashupednekar I'm working on this

**Comment by CosmicCoder96** [comment]
closing as per discussion in #1055
