### ISSUE TITLE
No back to top feature on the main page

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#1035]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
There is no back to top option on the main page. 
**Expected behavior:**
There should be a back to top option on the main page.

I'm working on this.

**Comment by geekyd** [comment]
@harsh-jindal Thanks for opening an issue. Can you please elaborate more about the issue you are facing?

**Comment by harsh-jindal** [comment]
@geekyd There is no back to top option on the main page.Like there should be top arrow on the right bottom on the screen clicking on which we can directly go to the top of the page so we do not have to scroll till the top of the page.

**Comment by sumedh123** [comment]
@geekyd What do you think about this issue? This can be done but I don't think this is on priority right now? Opinions?

**Comment by harsh-jindal** [comment]
@sumedh123 Shall I work on this issue or leave it for later?

**Comment by sumedh123** [comment]
@geekyd Opinions on this one?

**Comment by ritikamotwani** [comment]
@pradeepgangwar @srv-twry is this feature even needed or can this issue be closed?

**Comment by srv-twry** [comment]
Absolutely not a priority right now. Closing it. We can reopen later if needed.
