### ISSUE TITLE
Login through google/facebook auth not working.

### ISSUE THREAD

**Issue by rupav** [fossasia/open-event-frontend#1041]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Expected behavior:**

Login through google/facebook authentication. 

**Steps to reproduce:**

https://open-event-frontend.herokuapp.com/login
Login though google/facebook . 
 ** I am working on it **

**Comment by rupav** [comment]
Someone else can claim this issue.

**Comment by ParthS007** [comment]
I want to work on this. @CosmicCoder96 @geekyd How should I proceed on this? Thanks

**Comment by harsh-98** [comment]
@rupav have u added `client id` in case of facebook and in case of google  `client id`  and `client secret` . And also u have to give the redirect url of the heroku application. @ParthS007 I think this is not a valid issue. @geekyd can u confirm?

**Comment by rupav** [comment]
@harsh-98 I have dropped this issue, because I am having my college exams, actually I wasn't able to login through Google/Facebook/Twitter that day, that's why opened the issue. If it's working fine now, let me know I will close this issue.

**Comment by harsh-98** [comment]
Yup, it is working.
