### ISSUE TITLE
Show password functionality should be added

### ISSUE THREAD

**Issue by rupav** [fossasia/open-event-frontend#1042]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

No `see password` functionality when registering
**Expected behavior:**

`show password` option available for both `password` and `confirm password` option.
**Steps to reproduce:**

https://open-event-frontend.herokuapp.com/register
![screenshot 2018-02-19 20 54 10](https://user-images.githubusercontent.com/20624380/36385023-514df032-15b7-11e8-829f-10152762653c.png)

** I will work upon it **

**Comment by CosmicCoder96** [comment]
@rupav I don't think this functionality is required, show password is a trend associated with mobile devices in general, none of the leading service providers provide an option to display the confirmed password. In fact that's the whole point of the confirm password field as the user cannot see what he has typed, there might be a typo which in turn is rectified by making him enter the password in the confirm password field.

**Comment by rupav** [comment]
Your point makes sense, @CosmicCoder96 , understood :+1:
