### ISSUE TITLE
Custom Dates accordion doesn't expand on clicking custom dates on explore route

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1046]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

Custom Dates accordion doesn't expand on clicking custom dates on explore route
**Expected behavior:**

![image](https://user-images.githubusercontent.com/17252805/36645909-b8470ade-1a95-11e8-8ab0-42c52f4608c3.png)
Clicking on it should make the text fields appear so that the user can enter the custom date range.

**Comment by ritikamotwani** [comment]
@CosmicCoder96 @mariobehling I would like to work on this.

**Comment by ParthS007** [comment]
I want to work on this , Can I proceed as I am new to this project ? @CosmicCoder96 @geekyd

**Comment by sumedh123** [comment]
@ParthS007 I think @ritikamotwani is working on this one. You can pick up some other beginner friendly issues :)
