### ISSUE TITLE
Footer link should contain proper text similar to eventyay

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-frontend#1056]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Presently, there is Lorem Ipsum text in footer links.
**Expected behavior:**
There should be proper text present in `Location`, `Privacy`, `Contact Us` & `Help` section similar to event yay.

**Steps to reproduce:**
Please click on any footer link.

I want to work on this Issue.

**Comment by ParthS007** [comment]
@geekyd @CosmicCoder96  Please give suggestions.Thanks :+1:

**Comment by CosmicCoder96** [comment]
@ParthS007 The texts for these sections is not hard coded. It is managed via the *Content->Pages* section in the admin dashboard. So to make the text proper all that is required is, to go to the admin section and enter the desired text :)
![image](https://user-images.githubusercontent.com/17252805/37243952-daea75aa-24a7-11e8-9923-d8eeea51c8e6.png)

Thus no change is required in terms of code.  During production it would be entered by the admins, and ideally the admins of the development server should have entered the proper text :)
