### ISSUE TITLE
The Edit Session Proposal button in the route to view a session doesn't work

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-frontend#1060]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
In the route to view a session the Edit Session Proposal button doesn't work.
![image](https://user-images.githubusercontent.com/22127980/37245572-3208e570-24c0-11e8-8e93-b0a1d70165d8.png)

**Expected behavior:**
The button when clicked should redirect to the form to edit the proposal.

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by ritikamotwani** [comment]
@geekyd @CosmicCoder96 I had a doubt in this issue. I made the changes that whenever the button is clicked it redirects to the edit form /e/{event_identifier}/cfs/new-session but as there is no session id specified it redirects to some other session of that same event(may be the first session created for that event). Should there be a new route with a form to edit sessions or is there something I am missing out? Can you please help.

**Comment by ritikamotwani** [comment]
@geekyd @CosmicCoder96 please help :smile:

**Comment by geekyd** [comment]
@ritikamotwani We need to take the same approach as eventyay. We must create new dynamic route with `id`. Compare it with eventyay.com.
