### ISSUE TITLE
Improve the UI of the login page

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#1064]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The current UI of login page is good but it can be improved.
![screen shot 2018-03-15 at 9 06 29 pm](https://user-images.githubusercontent.com/31013104/37473588-7450a062-2894-11e8-8aa4-51cc649f376c.png)

**Expected behavior:**
Instead of having the login using social accounts on the side we should have it in the login box itself.

**Would you like to work on the issue?**

YES

**Comment by codedsun** [comment]
@mayank8318 Can i work on this issue?

**Comment by codedsun** [comment]
@harsh-jindal Can I work on this issue?
