### ISSUE TITLE
Continue button is not clickable on add-order page

### ISSUE THREAD

**Issue by harsh-98** [fossasia/open-event-frontend#1070]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Continue button is not clickable when even the quantity select is greater than zero.

**Expected behavior:**
Continue button should be click when quantity is greater than zero.

**Steps to reproduce:**

**Related code:**
https://github.com/fossasia/open-event-frontend/blob/development/app/controllers/events/view/tickets/add-order.js#L8

**Would you like to work on the issue?**

YES

**Comment by CosmicCoder96** [comment]
Is a sub issue which will get covered in #750
