### ISSUE TITLE
Decrease the width of the menu list and add icons for menu list (when logged in)

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#1072]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The menu list when when logged in is to wide and menu list items lack icons.
![screen shot 2018-03-24 at 3 00 54 pm](https://user-images.githubusercontent.com/31013104/37862526-15fd826e-2f74-11e8-9a1f-824c1663a90c.png)

**Expected behavior:**
The width of the menu list should be decreased and menu icons should be added

**Would you like to work on the issue?**
YES

**Comment by mayank8318** [comment]
@niranjan94 Can I take this up?

**Comment by niranjan94** [comment]
@mayank8318 this ticket is not a priority right now. Would be nicer to work on missing features & bugfixes right now.

**Comment by mayank8318** [comment]
@niranjan94 Oh okay. Any existing issue that is a priority, so that I can work on it?

**Comment by parammittal16** [comment]
@niranjan94 Can I work on this issue Now ?

**Comment by sk9331657** [comment]
@srv-twry  Can I work on this??

**Comment by srv-twry** [comment]
Yeah, go ahead please.

**Comment by mariobehling** [comment]
There is no reason to decrease the width here. Other websites also follow the same approach as the existing implementation. Right now we are not clear if we want to add icons here neither as we are not sure if it clutters the UI. So, closing this for now. Once our basics are solved we can come back to minor details. Would be great if you could help to solve the major bugs of the system.
