### ISSUE TITLE
Implementation of frontend of payment system is missing?

### ISSUE THREAD

**Issue by harsh-98** [fossasia/open-event-frontend#1079]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Would you like to work on the issue?**

YES

**Comment by niranjan94** [comment]
@harsh-98 please be more specific in the issue. _Payment system_ is very generic. Also, server-support is also needed. So, take a look at what all is already implemented in the server and list out what else is needed to make this possible on the frontend.

**Comment by harsh-98** [comment]
@niranjan when the user has filled the type and number of ticket he will be taken to a payment portal. I was working on its frontend so i thought of opening this issue,

**Comment by CosmicCoder96** [comment]
Being handled as a part of parent issue https://github.com/fossasia/open-event-frontend/issues/750
