### ISSUE TITLE
Enhance connect us column UI in the footer

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1087]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The current alignment of the icons and text in the connect us column of the footer can be enhanced.
![screenshot from 2018-04-19 16-33-35](https://user-images.githubusercontent.com/22395998/38988033-66a8e62e-43ef-11e8-86d6-65532cf20286.png)

**Expected behavior:**
These could be arranged in a button panel as in sony's :
![screenshot from 2018-04-19 16-35-47](https://user-images.githubusercontent.com/22395998/38988148-bdc85fa2-43ef-11e8-9edc-77d863b9304a.png)
 
Or apple's :
![screenshot from 2018-04-19 16-36-58](https://user-images.githubusercontent.com/22395998/38988175-dd298ec0-43ef-11e8-9a4e-72456ffc838f.png)

**Steps to reproduce:**
Scroll down

**Would you like to work on the issue?**
Yes

@niranjan94 Should this be changed?

**Comment by niranjan94** [comment]
@mayank8318 not required at this moment. We are targeting functionality over UI enhancements at this point.
