### ISSUE TITLE
Action buttons on pending sessions route don't work 

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-frontend#1094]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The Action buttons on pending sessions route don't work.
![out](https://user-images.githubusercontent.com/21277837/39636026-a902f778-4fdc-11e8-816b-0b5e9363f7c1.gif)

**Expected behavior:**
They should work and should be used either to accept or reject session proposals.

**Steps to reproduce:**
Follow the GIF.

**System information:** 
```
Your operating system
```
Ubuntu 16.04

```
output of `node -v`
```
v8.2.1

```
output of `npm ls ember-cli`
```
open-event-frontend@1.0.0 /media/srv_twry/work/Projects/Community-Projects/Fossasia/open-event-frontend
`-- ember-cli@3.1.2 

**Would you like to work on the issue?**
Yes

cc @niranjan94 @geekyd @CosmicCoder96

**Comment by CosmicCoder96** [comment]
@srv-twry Any progress on this?

**Comment by srv-twry** [comment]
@CosmicCoder96 No, I haven't started working on it. It can be taken by anyone else.

**Comment by pradeepgangwar** [comment]
@srv-twry Is there anything blocking this issue to be worked upon? If not, I would like to work on this.

**Comment by srv-twry** [comment]
@pradeepgangwar Actually right now, when you update the status of a session to "accept/reject", the server will always send confirmation emails to the speakers as well as the organizer. We don't want that.

We want to be able to specify whether we want to send the mail or not. I have opened a PR, in the server for it.
It adds a new field in the schema called `send-email`. When you update the status of the session to accepted/rejected and send-email to true, then only emails will be sent. If send-email is false or null or not specified in the schema then it won't send any mail.
Waiting for the PR to be reviewed and merged :)

**Comment by srv-twry** [comment]
@pradeepgangwar You can proceed with this now :)
