### ISSUE TITLE
Tests are failing for the application

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#1100]
Some tests are failing on the application currently. This is affecting all incoming pull requests as contributors/reviewers are not sure if the PR is causing a test fail or it was an already failing test.

The test suite needs to be fixed on priority.

**Comment by pradeepgangwar** [comment]
@niranjan94 I think for now we should avoid using node v10 in travis. I think in test suite for node v10 some dependencies are not compatible.
![screenshot-2018-5-6 job 3953 2 - fossasia open-event-frontend - travis ci](https://user-images.githubusercontent.com/21259802/39672112-a003bd72-5141-11e8-9e00-a3066f4a0d8c.png)

**Comment by niranjan94** [comment]
@pradeepgangwar sure. You can remove it.
