### ISSUE TITLE
Add acceptance tests for /settings route when visiting without login

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1103]
**Current behavior:**
Acceptance tests for /settings route without login are missing.

**Would you like to work on the issue?**
Yes I am working on this. Will soon open a PR.

**Comment by niranjan94** [comment]
@pradeepgangwar please help fix existing tests before adding new ones
https://github.com/fossasia/open-event-frontend/issues/1100

**Comment by pradeepgangwar** [comment]
@niranjan94 Yes, I was going through travis errors. I will comment there if I figure out something.
