### ISSUE TITLE
Use "ui link cards" to display all the events

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1110]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Presently only `ui card` is used. 

**Expected behavior:**
Use `ui link card` to provide a floating feedback effect when the user hovers over the event cards.

**Related code:**
https://semantic-ui.com/views/card.html

**Would you like to work on the issue?**
Yes

**Comment by niranjan94** [comment]
Comment at https://github.com/fossasia/open-event-frontend/pull/1117#issuecomment-388541325
