### ISSUE TITLE
Make Notification panel buttons functional

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1112]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

Currently the static text *view session* is displayed for all the notifications' action button.
![image](https://user-images.githubusercontent.com/17252805/39889960-fc4c105c-54b6-11e8-8984-28152db40a89.png)

**Expected behavior:**

- Display dynamic buttons or remove them if no action is possible
- Make the buttons functional

browse eventyay.com or open event legacy deployment  to see the general behaviour.

**Comment by pradeepgangwar** [comment]
I would like to work on this.

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 I found that a notification model contain following information. 
```
  title      : attr('string'),
  message    : attr('string'),
  isRead     : attr('boolean', { defaultValue: false }),
  receivedAt : attr('moment'),

  user: belongsTo('user')
```
But since notifications can range from "Change of password" to "Information about a session/event", so I have a doubt that how are we going to keep button dynamic since no field in model tells us type of notification.

Let me know if I am missing something here.

**Comment by CosmicCoder96** [comment]
@pradeepgangwar I think the code for the button is supposed to be served as text by the server itself, and frontend just gives it the styling. So just remove this button for now, it makes no sense.

**Comment by niranjan94** [comment]
@CosmicCoder96 yes. You are correct. The server provides a HTML response. FE should be ready to display it accordingly. We should be adding required classes to the plain button the server sends. 

But, this is not the right way to go about. The server should ideally be sending something like,

```js
{
  title: 'Export of session ...',
  state: 'error',
  message: 'The following error occurred ...',
  primaryAction: {
	action: 'view',
    type: 'session',
 	id: 12344
  },
  receivedAt: '2018-05-14T04:58:06Z'
}
```

And FE should handle how it wants to display the action.

**Comment by CosmicCoder96** [comment]
@niranjan94 I will open up an issue on the server for this 👍

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 @niranjan94 server is sending something like this after the issue created on server was resolved.
```
"attributes": {
        "title": "New session proposal for abc",
        "message": " abc event",
        "action": "New Session Proposal",
        "is-read": false,
        "received-at": "2018-05-19T18:13:43.500342+00:00"
      }
```

Is this enough for what we want to have with this button.

**Comment by niranjan94** [comment]
Not enough data. We need more. For example, from this, how would the frontend know what session to goto ? . The response should be something like this,

```json
{
    "title": "New session proposal for abc",
    "message": "abc event",
    "actions": [
      {
        "type": "view",
        "subject": "session",
        "id": 1324
      },
      {
        "type": "delete",
        "subject": "session",
        "id": 1324
      }
	],
    "is-read": false,
    "received-at": "2018-05-19T18:13:43.500342+00:00"
}
```

Where `actions` is an array contain all the actions a user should be able to perform in the order of priority. (i.e. the first action element of the array is to be considered the primary action and so on - FE should display/behave accordingly.)

@CosmicCoder96 please create a BE issue for the same.

**Comment by CosmicCoder96** [comment]
@pradeepgangwar @niranjan94 https://github.com/fossasia/open-event-server/issues/4843

**Comment by srv-twry** [comment]
> Not enough data. We need more. For example, from this, how would the frontend know what session to goto ? .

@niranjan94 The `message` field received from the server also contains the buttons that need to be rendered. Those buttons already have the href attribute set with the URL.
We don't need to do anything else in the frontend.

**Comment by srv-twry** [comment]
Implemented completely.
