### ISSUE TITLE
Second ticket onwards "Maximum Order" stops working

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1118]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
If the user adds more than one ticket the `maximum order` for second ticket onwards remains a fixed 10 and is not updated.

**Expected behavior:**
It should update normally

**Steps to reproduce:**
1) Go to `Create Event`
2) Add a ticket (change max orders from the settings)
3) Add another ticket and now try to change max order for it
4) Close the settings option for the second ticket and now reopen it.
5) You will see that the change wasn't reflected

**Would you like to work on the issue?**
Yes

**Comment by mayank8318** [comment]
@niranjan94 @CosmicCoder96 The problem arises because the `ticket-input.hbs` has ids for the elements and since this view is created for each ticket more than one elements end up with the same id.
![screenshot from 2018-05-12 14-30-18](https://user-images.githubusercontent.com/22395998/39955706-832474b2-55f1-11e8-9fef-ca7a495cfee6.png)

![screenshot from 2018-05-12 14-30-51](https://user-images.githubusercontent.com/22395998/39955707-8a6a4f44-55f1-11e8-8ecb-4f8f9f138bf5.png)

From what I could understand from the code and [https://blog.fossasia.org/how-the-form-mixin-enhances-validations-in-open-event-frontend/](https://blog.fossasia.org/how-the-form-mixin-enhances-validations-in-open-event-frontend/) the ids are required for validation. Is this right and if so then how do you suggest I should go about solving this problem.
![screenshot from 2018-05-12 14-31-13](https://user-images.githubusercontent.com/22395998/39955731-dd09ed54-55f1-11e8-9767-45e82f45c0fc.png)

**Comment by niranjan94** [comment]
The validator will also work with `name` attribute. Use that instead

**Comment by niranjan94** [comment]
@mayank8318 

> Fields are matched by either the id, name, or data-validate property (in that order) matching the identifier specified in the settings object.

_From https://semantic-ui.com/behaviors/form.html_
