### ISSUE TITLE
Events not getting created through heroku server

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1119]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
On creating new event it show "Unexpected error occurred". This happens when using heroku deployment of open event server.

**Expected behavior:**
Event should get created.

**Comment by ritikamotwani** [comment]
@pradeepgangwar I think this is the issue of the server. It shows 500 as the error status. Even if you create a new user this error comes. I think this issue should be opened on open event server.

**Comment by pradeepgangwar** [comment]
@ritikamotwani ok, I think I should move this to server then. Thanks.

**Comment by pradeepgangwar** [comment]
We need to use the dev server - https://open-event-api-dev.herokuapp.com/
