### ISSUE TITLE
Search functionality not implemented - Quick Filter

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1125]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Search functionality hasn't been implemented in the quick filter.

**Expected behavior:**
Search functionality should be implemented

**Steps to reproduce:**
Open the frontend and try to search. Nothing happens.

**Related code:**
quick-filter.hbs
```hbs
{{input type='text' placeholder=(t 'Search for events')}}
{{#unless device.isMobile }}
  {{input type='text' placeholder=(t 'Location')}}
  {{#ui-dropdown class='search selection' selected=filterDate forceSelection=false}}
    {{input type='hidden' id='filter_date' value=filterDate}}
    <i class="dropdown icon"></i>
    <div class="default text">{{t 'All Dates'}}</div>
    <div class="menu">
      <div class="item" data-value="all-dates">{{t 'All Dates'}}</div>
      <div class="item" data-value="today">{{t 'Today'}}</div>
      <div class="item" data-value="tomorrow">{{t 'Tomorrow'}}</div>
      <div class="item" data-value="this-week">{{t 'This Week'}}</div>
      <div class="item" data-value="this-weekend">{{t 'This Weekend'}}</div>
      <div class="item" data-value="next-week">{{t 'Next Week'}}</div>
      <div class="item" data-value="this-month">{{t 'This Month'}}</div>
    </div>
  {{/ui-dropdown}}
{{/unless}}
<button class="ui blue button large" type="button">{{t 'Search'}}</button>
```
quick-filter.js
```javascript
import Component from '@ember/component';

export default Component.extend({
  classNames: ['ui', 'action', 'input', 'fluid']
});

```

**System information:** 

```
Ubuntu 18.04
```

**Would you like to work on the issue?**
Yes

@CosmicCoder96 @niranjan94 Is this a valid issue and can I work on it?

**Comment by mayank8318** [comment]
@CosmicCoder96 Okay

**Comment by kushthedude** [comment]
@CosmicCoder96 Quick Filter Search is working now, Therefore closing it
