### ISSUE TITLE
Add add-order to ticket route(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#114]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add add-order as sub route of tickets.

![screenshot from 2017-06-02 13-42-33](https://cloud.githubusercontent.com/assets/12807846/26717008/5c327744-4799-11e7-80b1-8f1686d0b1d9.png)

- Located at `tickets/add-order`

Please have a look at #97, before starting the work on the issue.

**Comment by utkarshnath** [comment]
plz assign this to me
