### ISSUE TITLE
Netlify uses the mater branch server for deployment

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1142]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Netlify uses master branch server for deployment which has some bugs that have been fixed in the development branch. As a result, it is difficult to test and review PRs.

Currently in use `https://open-event-api.herokuapp.com/`
Should use - `https://open-event-api-dev.herokuapp.com/`

**Would you like to work on the issue?**

CC - @CosmicCoder96 @niranjan94 @geekyd

**Comment by niranjan94** [comment]
@mayank8318 done.
