### ISSUE TITLE
Make withdraw proposal button in /my-sessions route functional

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1143]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently withdraw proposal button in my sessions do not function.
![screenshot from 2018-05-19 17-31-50](https://user-images.githubusercontent.com/21259802/40268446-e413a29a-5b8a-11e8-9ce4-f6ecc5e6854d.png)

**Expected behavior:**
Button should be functional.

**Would you like to work on the issue?**
Yes I am working on this.

**Comment by ritikamotwani** [comment]
@pradeepgangwar I had already opened an issue for this https://github.com/fossasia/open-event-frontend/issues/1060. Will work on it after the PR for the editing routes gets approved :smile:
