### ISSUE TITLE
Tests fail because of "Cannot read property 'afterContentPaint' of null"

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1144]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Some tests are failing because of "Cannot read property 'afterContentPaint' of null".
This seems to be an ongoing issue with no proper fix https://github.com/dollarshaveclub/ember-router-scroll/issues/72

**Expected behavior:**
The tests should run properly.

**Steps to reproduce:**
Run `Ember test`

**Would you like to work on the issue?**
I will try to update dependencies and see if it works otherwise I will wait for a solution in the parent repository https://github.com/dollarshaveclub/ember-router-scroll/issues/72

**Comment by srv-twry** [comment]
@mayank8318 Any update on this ?

**Comment by niranjan94** [comment]
Seems to be resolved by https://github.com/fossasia/open-event-frontend/commit/f678cb17ebcaf33b7aa75c4497a89316a43ffeb3 

https://travis-ci.org/fossasia/open-event-frontend/builds/391272394
