### ISSUE TITLE
Add access codes to tickets route(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#115]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add access as sub route of tickets.
![screenshot from 2017-06-02 13-43-24](https://cloud.githubusercontent.com/assets/12807846/26717058/8c6818ec-4799-11e7-8daa-43b3bfcee822.png)

- Located at `tickets/access-codes`

Please have a look at #97, before starting the work on the issue.

**Comment by sumedh123** [comment]
@niranjan94 Please assign.

**Comment by sumedh123** [comment]
@niranjan94 Do I also need to create the new page of creation of access code which appears on clicking the button?

**Comment by geekyd** [comment]
@sumedh123 Just create a button we will add the form for creation of access code later.
