### ISSUE TITLE
Show an alert when the user email is unverified.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1151]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Expected behavior:**

![image](https://user-images.githubusercontent.com/17252805/40303722-40a4bb88-5cf4-11e8-8e65-2505f6bfaf61.png)

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 This needs to be shown on home page or all the pages?

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 I tried solving this and at first try I could come up with this. Please check the UI and let me know on which pages it is to be applied.

![screenshot from 2018-05-29 19-31-39](https://user-images.githubusercontent.com/21259802/40663723-f2c5f254-6376-11e8-8676-3eba1da8fc70.png)

**Comment by CosmicCoder96** [comment]
@pradeepgangwar The implementation needs to be exactly as on legacy, you may try making an unverified account there, and you will get to see the behaviour exactly, the message sometimes changes according to the page you are on, and doesn't appear in pages which don't require a verified account to access. While trying to publish the event the  account needs to be verified and this message adjusts accordingly. Regarding UI, I think A colour coded `Warning Message` component of semantic UI would be better than this one.
