### ISSUE TITLE
Deleted users are same as active users admin/users/deleted

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1157]
**Describe the bug**
Deleted users are same as active users in admin dashboard http://localhost:4200/admin/users/deleted
**To Reproduce**
1. Go to Admin dashboard
2. Click on Users Tab -> Deleted Users
Deleted users are same as active users

**Expected behavior**
It should give us the deleted users only.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bhaveshAn** [comment]
@CosmicCoder96 @poush Please confirm the validation of issue.

**Comment by pradeepgangwar** [comment]
@bhaveshAn Yes this issue is valid, I am working on this.
