### ISSUE TITLE
Add discounts to tickets route(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#116]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add discounts as sub route of tickets.

![screenshot from 2017-06-02 13-46-51](https://cloud.githubusercontent.com/assets/12807846/26717185/1034546a-479a-11e7-8c33-2bba01d4703b.png)

- Located at `tickets/discounts`

Please have a look at #97, before starting the work on the issue.

**Comment by CosmicCoder96** [comment]
@anu-007
Please claim the issue before working on it , thanks :)

**Comment by anu-007** [comment]
@CosmicCoder96 ok I will take care of this in future and ask first before working on an issue also I thought working on multiple issues at a time would increase the pace of development, and therefore reduce the idle time when waiting for a PR to get reviewed.Thanks!!
