### ISSUE TITLE
Add attendees to tickets route.(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#117]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add attendees as sub route of tickets.
![screenshot from 2017-06-02 13-49-26](https://cloud.githubusercontent.com/assets/12807846/26717245/530c620a-479a-11e7-908c-99d958fadedc.png)

- Located at `tickets/attendees`

Please have a look at #97, before starting the work on the issue.

**Comment by anu-007** [comment]
I like to work on this.thanks!!
