### ISSUE TITLE
Gender dropdown instead of textbox

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1173]
**Describe the bug**
There is an input field instead of a Gender dropdown like in the previous version

**To Reproduce**
1. Go to an event
2. Click on sessions, create a session
3. Scroll down to Gender

**Expected behavior**
There should be a dropdown menu

**Screenshots**

![image](https://user-images.githubusercontent.com/2415206/40542401-4d669dbc-6020-11e8-8cbd-e9fc5246a9df.png)

**Comment by codedsun** [comment]
@Kreijstal I want to work on this issue

**Comment by codedsun** [comment]
@mayank8318 ?

**Comment by Kreijstal** [comment]
I'm updating it with info Niranjan has said 
![image](https://user-images.githubusercontent.com/2415206/40594960-5d5ee800-6232-11e8-977c-a8cbbea9f7b0.png)

**Comment by sk9331657** [comment]
@srv-twry @niranjan94  Can I implement this now??

**Comment by mohitm15** [comment]
I want to take this issue?

**Comment by mohitm15** [comment]
Sorry for the delay as I was quite occupied for last 3 days. Surely interested to resolve this issue...

**Comment by mohitm15** [comment]
@srv-twry Can you briefly tell where is this issue present when one enters into the website

**Comment by ritikamotwani** [comment]
@mohitm15 sure, go ahead

**Comment by kushthedude** [comment]
Can i work on this issue?
@ritikamotwani @srv-twry

**Comment by CosmicCoder96** [comment]
A sub-issue of https://github.com/fossasia/open-event-frontend/issues/1860
