### ISSUE TITLE
Convert tabs on events/<event_id> to dropdown for mobile screen

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#118]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![screenshot from 2017-06-02 20-32-27](https://cloud.githubusercontent.com/assets/12807846/26731811/e14eb31e-47d2-11e7-913b-e1e97f93c6c0.png)

**Expected behavior:**
![screenshot from 2017-06-02 20-35-11](https://cloud.githubusercontent.com/assets/12807846/26731844/018af7a0-47d3-11e7-8eb3-665355856664.png)

Currently the tabs in events/<events_id> route is not optimised for mobile devices, we should convert the tabs to dropdown like public event page, for optimisation of space.

@niranjan94 What do you think?

**Comment by niranjan94** [comment]
@geekyd sure. Go ahead.
