### ISSUE TITLE
Admin Settings - Super Admin Email ID input section not present

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1184]
**Describe the bug**
Admin Settings - Super Admin Email ID input section not present

**To Reproduce**

1. Go to route `/admin/settings/`
2. Scroll down to App Secret Key
3. After that Super Admin Email ID input section not present

**Expected behavior**
There should be Super Admin Email ID input section as in v1.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 16.04 LTS
 - Browser Firefox

**Additional context**

**V1**
![v1-settings](https://user-images.githubusercontent.com/22936570/40579541-1b90f396-6147-11e8-9ab9-0190240271ae.png)

**V2**
![screenshot from 2018-05-27 00-32-48](https://user-images.githubusercontent.com/22936570/40579543-1f9cee68-6147-11e8-9a86-2c508a6c1962.png)

**Comment by CosmicCoder96** [comment]
This removal was deliberate  in the new frontend, closing this.
