### ISSUE TITLE
For label not defined in /admin/reports/system-logs/notification-logs

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1185]
**Describe the bug**

For label not defined in /admin/reports/system-logs/notification-logs
**To Reproduce**

1. Go to route `/admin/reports/system-logs/notification-logs`
2. See error: For label not defined.

**Expected behavior**

Should be giving the For which user this notification is sent.

**Screenshots**
**V2**
![screenshot from 2018-05-27 00-57-14_1](https://user-images.githubusercontent.com/22936570/40579626-8a2af67e-6149-11e8-9298-de5b4ca7216c.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 16.04 LTS
 - Browser: Firfox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ritikamotwani** [comment]
@bhaveshAn I am getting information in the for column.
![image](https://user-images.githubusercontent.com/22127980/42413302-41edca22-823b-11e8-8fc5-13f33c7b7ad7.png)
