### ISSUE TITLE
Add System Image for all the Event Topic (Category) 

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1186]
**Is your feature request related to a problem? Please describe.**

Add System Image for all the Event Topic (Category) 

Same Issue at Server  : [https://github.com/fossasia/open-event-server/issues/4778](https://github.com/fossasia/open-event-server/issues/4778)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**V1**

![screenshot from 2018-05-27 02-05-39](https://user-images.githubusercontent.com/22936570/40580038-c3e4d1a0-6153-11e8-9496-fbe66fa0f25d.png)

**Comment by ritikamotwani** [comment]
@bhaveshAn is this feature completed entirely on the server?

**Comment by bhaveshAn** [comment]
@ritikamotwani Resizing the uploaded system-image to a fixed size has to be done.

**Comment by shreyanshdwivedi** [comment]
@bhaveshAn any update?

**Comment by kushthedude** [comment]
@CosmicCoder96 @ritikamotwani Do we need to add system images or should be left blank?

**Comment by mariobehling** [comment]
This is nice, but we now define it out of scope for the current development.
