### ISSUE TITLE
Add Featured speakers to the public event page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#12]
<img width="1680" alt="screen shot 2017-04-23 at 10 07 59 pm" src="https://cloud.githubusercontent.com/assets/2404372/25315460/b8e5fd6c-2872-11e7-91b0-05706312c4f8.png">

Add the features speaker UI to the public event page as shown above.

**What is expected ?**
- Featured speakers with each speaker as a [component](https://guides.emberjs.com/v2.12.0/getting-started/core-concepts/#toc_components) added to the public event page.
- UI Only for now. Dummy data to be used. 

**References:**
- https://guides.emberjs.com/v2.12.0/components/defining-a-component/
- https://semantic-ui.com/views/card.html
- https://semantic-ui.com/collections/grid.html

**Comment by CosmicCoder96** [comment]
@niranjan94 I would like to work on this.

**Comment by niranjan94** [comment]
@CosmicCoder96 it would be better if this is done after #13 . Ideally, we want both featured speakers and normal speakers to share a `speaker` component and a featured-style display should be toggle-able via a parameter (such as `isFeatured = true`)

**Comment by CosmicCoder96** [comment]
@niranjan94 Sounds good 👍

**Comment by geekyd** [comment]
@niranjan94 I want to work on this issue. Please assign this issue to me.
