### ISSUE TITLE
Sales/event is not yet with the backend connected

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1204]
**Describe the bug**
in /admin/sales/events/ the routes that exist are just default routes but are still not connected with the API

**To Reproduce**
1. Go to '/admin/sales/events'
2. See events, they're still 'default'

I want to work on this.

**Comment by maxlorenz** [comment]
Same for all other `/admin` routes

**Comment by YogeshSharma0201** [comment]
working on this

**Comment by shreyanshdwivedi** [comment]
@YogeshSharma0201 this issue is child issue of https://github.com/fossasia/open-event-frontend/issues/1373.
I'm already working on this. The PR is yet blocked because there are some discrepancies in `admin/sales` route which is being discussed with @CosmicCoder96

**Comment by ritikamotwani** [comment]
Fixed : https://github.com/fossasia/open-event-frontend/pull/1929
