### ISSUE TITLE
Speaker's Country should be a drop-down menu

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-frontend#1220]
**Is your feature request related to a problem? Please describe.**

Currently the Speaker's form accepts any string input

**Describe the solution you'd like**

It should be a drop-down menu with a fixed set of possible inputs.

**Not in v1, hence can be tackled later.**

**Comment by shreyanshdwivedi** [comment]
@srv-twry I would like to work on this. Can you tell me whether you need same dropdown in the event registration form or a different one? Like, same countries or some additional?

**Comment by shreyanshdwivedi** [comment]
@sk9331657 I've already started working on this yesterday. :smile:

**Comment by sk9331657** [comment]
> @sk9331657 I've already started working on this yesterday.

Ok :+1:  . I will take other issue.
