### ISSUE TITLE
Add URL validations in the URL fields 

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-frontend#1225]
**Is your feature request related to a problem? Please describe.**

Right now the input box allows entering wrong urls in the Links and Social media entries in the Wizard step 1.
Similar case in `Ticket URL` box

**Describe the solution you'd like**

Validate the url similar to the way it is done in other places. 

**Note**
Not in v1 also, hence might be dealt later.

**Comment by mishuvs** [comment]
@srv-twry Can I work on it?

**Comment by srv-twry** [comment]
Yes, please go ahead

**Comment by mishuvs** [comment]
@pradeepgangwar @ritikamotwani @srv-twry @niranjan94 I tried referring to other URL validation issues, but this one will probably use dynamic validation. Can I please get a little help here. This seems to not work.
```
socialLinks: {
          identifier : 'social_links',
          rules      : [
            {
              type   : 'regExp',
              value  : protocolLessValidUrlPattern,
              prompt : this.l10n.t('Please enter a valid url')
            }
          ]
        },
```

**Comment by mayank8318** [comment]
@mishuvs but how are you checking if its the right URL for the right field, like Facebook url for Facebook field etc

**Comment by srv-twry** [comment]
Closing this now. Implemented in wizard, session-speaker form and admin social links form.
