### ISSUE TITLE
Propose & implement solution for overflowing buttons on mobile devices

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#124]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
- location `events/<id>/sessions`

![screenshot from 2017-06-04 05-07-39](https://cloud.githubusercontent.com/assets/12807846/26757716/c94f545a-48e3-11e7-9857-5f37205d1291.png)

**Expected behavior:**
The buttons must not overflow the parent Div.
Please propose a solution for this problem that can be used throughout the application.

**Comment by anu-007** [comment]
@geekyd for this we can define a custom class like .ui.stackable.basic.buttons and with the help of media query to make them stackable, i have used it in PR [122](https://github.com/fossasia/open-event-frontend/pull/122/files), PR [120](https://github.com/fossasia/open-event-frontend/pull/120/files) ( see app/styles/pages/events.scss )and they are working fine we can use it throughout the application.Thanks!!

**Comment by CosmicCoder96** [comment]
@anu-007 Please share a screenshot :) @niranjan94 What do you think?

**Comment by geekyd** [comment]
@CosmicCoder96 @anu-007 I think we should add a component that wraps buttons and handles the layout for mobile devices something like what we are trying to achieve with https://github.com/fossasia/open-event-frontend/pull/119. As we have a lot of button groups it will be good to use a separate component for handling the layout.

**Comment by CosmicCoder96** [comment]
@niranjan94 I was leaning towards a common component too, there are a lot of button groups on various routes.

**Comment by anu-007** [comment]
@geekyd @CosmicCoder96 defining separate components for buttons would be a good idea.By the way here are the screenshots 
![alt text](https://github.com/anu-007/assets/blob/master/Screenshot%20from%202017-06-04%2015-54-59.png?raw=true "desktop")
![alt text](https://github.com/anu-007/assets/blob/master/Screenshot%20from%202017-06-04%2015-55-33.png?raw=true "mobile")

**Comment by CosmicCoder96** [comment]
@anu-007 This can be achieved via simply using `<div class="ui {{if device.isMobile 'vertical'}} basic buttons">` as I have done in PR #123 
If the goal was to display them vertically for mobile that is. But it makes the whole page too long, so it will be best if there were a button to expand and hide these vertical buttons too.

**Comment by geekyd** [comment]
@anu-007 Although this is a possible solution, it is not optimised for mobile devices as it will take up more space than required and increase the size of the page. We need a better solution for that, one solution can be adding a dropdown something that we already have for side-menu.

**Comment by geekyd** [comment]
@niranjan94 @CosmicCoder96 @anu-007 I work on this issue. Thanks!

**Comment by geekyd** [comment]
@niranjan94 @CosmicCoder96 @anu-007 After merging https://github.com/fossasia/open-event-frontend/pull/222, the buttons on the `events/event_id/sessions` were changed to `tabbed-navigation`, which already is a good solution for handing tabs. Please check https://open-event-frontend.herokuapp.com/events/963d3ba5/sessions.

If we are going to split the routes into dynamic routes then we will not have to handle the grouped buttons at all. What do you think?

**Comment by niranjan94** [comment]
Yep. That will also be split into dynamic routes.

**Comment by geekyd** [comment]
Okay so I think working on the responsive buttons will be redundant as we will be going for dynamic routes. What do you say?

**Comment by niranjan94** [comment]
@geekyd hmmm makes sense :)
