### ISSUE TITLE
Hide hidden tickets from public route regardless of who is logged in

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1242]
**Describe the bug**
Currently hidden tickets are visible to organizer on public route. If organizer is logged in he/she also should not see hidden tickets.

**Comment by niranjan94** [comment]
@pradeepgangwar the adapter is not a route a level. It is at a model level. 

This can be easily implemented. You can just override the `headers` computed property within the adapter for the ticket model (do it only for this model). And don't add the the `Authorization` header if the current route it a public route.
