### ISSUE TITLE
TLE in unverified-user-message.hbs

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1247]
**Describe the bug**
We get a Template Linting Error in `unverified-user-message.hbs` because an action is being assigned to an icon. This is causing a test failure - 
```sh
open-event-frontend/templates/components/unverified-user-message.hbs
  4:26  error  Interaction added to non-interactive element  invalid-interactive

===== 1 Template Linting Error
```

**To Reproduce**
1. Run `ember test`

**Expected behavior**
There shouldn't be an error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by pradeepgangwar** [comment]
@mayank8318 Are you working on this? If not, I would like to fix this.

**Comment by mayank8318** [comment]
@pradeepgangwar Please go ahead :)
