### ISSUE TITLE
Add password sub-route to settings route(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#126]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
Add UI for password sub-route in settings route.

![screenshot from 2017-06-04 05-20-29](https://cloud.githubusercontent.com/assets/12807846/26759428/41ab041c-491b-11e7-9da5-fc194e78ac8d.png)

- Located at `settings/password`
- Reference URL https://eventyay.com/settings/password/

**Comment by CosmicCoder96** [comment]
I'm working on this.
