### ISSUE TITLE
Build is failing due to lint issues

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1269]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17252805/41291981-7c9a7330-6e51-11e8-8fcf-5eecb33a95dc.png)

**Comment by niranjan94** [comment]
Resolved via https://github.com/fossasia/open-event-frontend/commit/f8fbe6b5061a994baab1fc094bf1886a0902d01f
