### ISSUE TITLE
Add email-preferences sub-route to settings route(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#127]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
Add UI for email-preferences sub-route in settings route.

![screenshot from 2017-06-04 05-20-10](https://cloud.githubusercontent.com/assets/12807846/26759471/23deace4-491c-11e7-9ebc-7df58ef4dec6.png)

- Located at `settings/email-preferences`
- Reference URL https://eventyay.com/settings/email-preferences/

**Comment by geekyd** [comment]
Working on this

**Comment by niranjan94** [comment]
@geekyd for this, please create some events under your name and see what all this UI includes
