### ISSUE TITLE
Integrate Event and Speaker Image Sizes APIs

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1273]
**Is your feature request related to a problem? Please describe.**

Currently, there is API for updating the Image Sizes for Event and Speaker.

Integrating APIs is required.

**Describe the solution you'd like**

Integrating APIs is required.
APIs http://open-event-api.herokuapp.com/#image-size-event-image-size-details
and http://open-event-api.herokuapp.com/#image-size-speaker-image-size-details

**Describe alternatives you've considered**

**Additional context**

V1

![screenshot from 2018-06-01 18-33-09](https://user-images.githubusercontent.com/22936570/40878588-cfb6f7e4-66b0-11e8-9891-40563ec9266a.png)
![screenshot from 2018-06-01 18-33-00](https://user-images.githubusercontent.com/22936570/40878589-d0110f5e-66b0-11e8-9469-9608d6e95847.png)

**Others can claim**

**Comment by ritikamotwani** [comment]
@bhaveshAn the form for the system images and the UI already exists but whenever I go to the route admin/settings/images I get an internal server error!
![image](https://user-images.githubusercontent.com/22127980/41483277-1ff3f06e-70f6-11e8-93fe-2eb22c7649e9.png)

**Comment by bhaveshAn** [comment]
It means just API integration is required.

`/v1/event-image-sizes`
`/v1/speaker-image-sizes`
