### ISSUE TITLE
Implement UI and Integrate APIs of event-type and topics statistics

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1274]
**Is your feature request related to a problem? Please describe.**

Currently, Event Type and Topics Statistics APIs have been implemented in the server.
Not present here at frontend.

**Describe the solution you'd like**

Implement UI and Integrate http://open-event-api.herokuapp.com/#admin-statistics-event-types-statistics-details-get
and http://open-event-api.herokuapp.com/#admin-statistics-event-topics-statistics-details-get

**Describe alternatives you've considered**

**Additional context**

![screenshot from 2018-06-09 18-25-23](https://user-images.githubusercontent.com/22936570/41457006-ee1b4d86-709f-11e8-94c5-9682ac791938.png)
![screenshot from 2018-06-09 18-25-15](https://user-images.githubusercontent.com/22936570/41457007-ee984854-709f-11e8-84d8-4dc1c46f30f2.png)

**Others can claim**

**Comment by ritikamotwani** [comment]
@bhaveshAn I tried finding the UI for displaying statistics of the event types and topics in version1 but couldn't. Could you tell the route?

**Comment by bhaveshAn** [comment]
@ritikamotwani 
This is not present in V1. Will be added in V2. May be you can try (if willing to do) in the route which Pradeep has made for event types and topics 
It will be easy to follow that way as id and name is mentioned in response as well as in that UI when view and edit buttons present.
As response is 
```
id:
count:
name:
```
@niranjan94 Thoughts please, about route and UI.

**Comment by bhaveshAn** [comment]
Sure!

**Comment by iamareebjamal** [comment]
Not a priority
