### ISSUE TITLE
Speaker-Session not being linked

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1277]
**Describe the bug**
When we create a new session, the session and the speaker are created in the database but aren't linked to each other. This is happening because of wrong post request. A manual postman request works fine on the server.

**To Reproduce**
1.Create a session
2. Speaker details aren't included

**Expected behavior**
The link should be formed properly

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by mayank8318** [comment]
@niranjan94 @SaptakS We are doing this `this.get('model.speaker.sessions').pushObject(this.get('model.session'));` in the controller before saving the record. But the relationship isn't being added(confirmed by logging and checking the POST request payload). The ember-data doc suggests that this is the right way of doing it. I also asked a question on StackOverflow(https://stackoverflow.com/questions/50887309/ember-many-to-many-relationship-data-not-being-updated) and one of the comments said that we need a custom serializer to add the `hasMany` relationship, which I checked and we already have one. What are we missing here?
CC- @pradeepgangwar

**Comment by pradeepgangwar** [comment]
I also asked this on ember community slack channel, but nothing worked out. I thing there is something missing.

**Comment by niranjan94** [comment]
Try setting the event relation on the session and saving. Similar to how we do it for a lot of resources on the wizard.

**Comment by mayank8318** [comment]
@niranjan94 Tried that but it still doesn't work
