### ISSUE TITLE
Events shouldn't be published if the user is not user e-mail is not confirmed

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1279]
**Describe the bug**
Events shouldn't be published if the user e-mail is not confirmed 
**To Reproduce**
Attempt to log-in as user that is not confirmed

**Expected behavior**

Basically, if a user is not confirmed it shouldn't allow them to publish events, but they can still create events.

**Comment by srv-twry** [comment]
This should also be done on the backend. I mean the server should also raise an error. So create a corresponding issue in the server also. I am 75% sure, that we already have it in the server but you might want to check it to be 100% sure.

**Comment by Kreijstal** [comment]
ok let's look

**Comment by srv-twry** [comment]
@pradeepgangwar I think he claimed the responsibility in the meeting so IMO it's better to let him handle it :)

**Comment by Kreijstal** [comment]
Also, I just confirmed it, it's a real bug. Working on it.

**Comment by Kreijstal** [comment]
@open-event-bot move to fossasia/open-event-server
