### ISSUE TITLE
Assertion Failed: You cannot add a record of modelClass 'undefined' to the 'event.tax' relationship (only 'tax' allowed)

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1282]
**Describe the bug**

When I am on the wizard, and I  want to continue over the next step I get this message.

It has to do something about the model not being defined correctly for event.tax

**To Reproduce**
1. Go to /create
2. Fill some data
3. Try to go forward

**Expected behavior**

well, it should just go on, or at least give a more meaningful error message

**Screenshots**
![image](https://user-images.githubusercontent.com/2415206/41509838-4d10064a-725a-11e8-8798-79d19715d1f7.png)

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Are you able to face it ?

**Comment by prateekj117** [comment]
@uds5501 I don't think this problem still persists in the system. I am also not facing the similar event-copyright error.

**Comment by kushthedude** [comment]
Closing since unable to face on local 
cc: @CosmicCoder96
