### ISSUE TITLE
Notification gives eventyay link on session details of an event

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1284]
**Describe the bug**

Notification gives eventyay link on session details of an event

**To Reproduce**
1. Go to 'Notification on upper right'
2. Hover on Notification of a session links to `eventyay.com/events/<event_id>/sessions/<session_id>`
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![hover1](https://user-images.githubusercontent.com/22936570/41537980-9feb9f0a-7327-11e8-98ce-6f29e0718cb2.png)

**Comment by ritikamotwani** [comment]
@bhaveshAn this issue is already open https://github.com/fossasia/open-event-frontend/issues/1112

**Comment by bhaveshAn** [comment]
Yes this issue will be solved alongwith #1112 

hence Closing.
