### ISSUE TITLE
Error in Event Creation Wizard

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1285]
**Describe the bug**
While creating an event, when the user clicks the forward button, an error message "Oops something went wrong is shown" and the wizard doesn't move ahead. On checking the database tables, the user can see that the event was created successfully.

**To Reproduce**
1. Go to create event
2. Click on "Forward" button
3. See the error

**Expected behavior**
Event creation should proceed as expected.

**Screenshots**
![screenshot from 2018-06-18 20-51-41](https://user-images.githubusercontent.com/22395998/41549748-74124b5a-7344-11e8-87fe-b4c8d7e5ca76.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by pradeepgangwar** [comment]
I am working on this.

**Comment by mayank8318** [comment]
@pradeepgangwar sure go ahead ☺

**Comment by mayank8318** [comment]
Solved by #1302
