### ISSUE TITLE
Add speakers to the public event page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#13]
<img width="1680" alt="screen shot 2017-04-23 at 10 08 10 pm" src="https://cloud.githubusercontent.com/assets/2404372/25315490/3b8eb02e-2873-11e7-9b9b-6a698b9c97e0.png">

Add speakers UI to the public event page as shown above.

**What is expected ?**
- speakers list with each speaker as a [component](https://guides.emberjs.com/v2.12.0/getting-started/core-concepts/#toc_components) added to the public event page.
- UI Only for now. Dummy data to be used. 

**References:**
- https://guides.emberjs.com/v2.13.0/components/defining-a-component/
- https://semantic-ui.com/elements/image.html
- https://semantic-ui.com/collections/grid.html

**Comment by geekyd** [comment]
@niranjan94 I would like to work on this. please assign me to the issue.
