### ISSUE TITLE
Implement search bar (public pages)

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-frontend#1322]
**Is your feature request related to a problem? Please describe.**

The search bar on the start page is not implemented. A [PR](https://github.com/fossasia/open-event-server/pull/4938) for the server adds the search capabilities with a new parameter.

**Describe the solution you'd like**
Clicking the search bar icon or pressing enter should display only the events that contain the entered term.

**Additional context**
The search bar should initiate a new request to `/v1/search/events?name=eventname`:

parameter | format | description
--- | --- | ---
name | (optional, string, ``) | Filter by event name
description | (optional, string, ``) | Filter by event description
location-name | (optional, string, ``) | Filter by location name
organizer-name | (optional, string, ``) | Filter by organizer name
organizer-description | (optional, string, ``) | Filter by organizer description

**Comment by mayank8318** [comment]
@maxlorenz I would like to work on this

**Comment by mayank8318** [comment]
@maxlorenz I am getting this error -> 
```sh
File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/werkzeug/local.py", line 166, in top
    return self._local.stack[-1]
RecursionError: maximum recursion depth exceeded while calling a Python object
```
Do I need to change my recursion limit?

**Comment by mayank8318** [comment]
Ok I solved the earlier issue but now I am getting this ->
```sh
  File "/home/mayank/anaconda3/envs/openevent3/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
```

**Comment by iamareebjamal** [comment]
Done already
