### ISSUE TITLE
Add filter bar

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/open-event-frontend#1324]
**Is your feature request related to a problem? Please describe.**
As in v1, every list and table should have a filter bar to quickly find wanted elements

**Describe the solution you'd like**

Add a filter bar that uses request params to fetch a filtered dataset using [flask-rest-jsonapi](http://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html)

**Describe alternatives you've considered**

**Additional context**

**Comment by shubhamguptaji** [comment]
on what basis elements should be filtered?

**Comment by YogeshSharma0201** [comment]
working on this

**Comment by CosmicCoder96** [comment]
Filter bars are functional now. #1934
