### ISSUE TITLE
Validations on new speaker form fail silently

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1326]
**Describe the bug**

**To Reproduce**
1. Go to call for speakers and start submitting a proposal as a new speaker.
2. Enter an invalid url (no `https` or `http` deems a URL as invalid)
3. Try to submit
![image](https://user-images.githubusercontent.com/17252805/41920504-2b9330f6-7961-11e8-91b2-9c09fa5dd8f8.png)
This behavior is because server declares it as an unprocessable  entity on account of the Invalid URL. And the request silently fails. 

**Expected behavior**

There should be validation on the frontend which lets the user know what they are entering wrong.

**Comment by mayank8318** [comment]
I think #1225 is the parent issue for this
