### ISSUE TITLE
Improvement UI event/sessions

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-frontend#133]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently buttons have overflown and the divider is unnecessarily added in the parent route

<img width="1279" alt="screen shot 2017-06-04 at 4 12 49 pm" src="https://cloud.githubusercontent.com/assets/12716067/26760898/3e823294-4941-11e7-90d5-51b9602c2ffb.png">

**Expected behavior:**

<img width="1271" alt="screen shot 2017-06-04 at 4 16 16 pm" src="https://cloud.githubusercontent.com/assets/12716067/26760897/3dd4b664-4941-11e7-9b80-0889a91a5e91.png">

@niranjan94 should I work on this , this occurred in PR #100

**Comment by niranjan94** [comment]
@utkarshnath please fix this. Thanks. I didn't notice it during the PR review.
