### ISSUE TITLE
Event topic cannot be changed from Iot2

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-frontend#1331]
**Describe the bug**
While creating an event, Iot2 is the only event topic present. There should be either more topics or we should be able to name our own event topic

**To Reproduce**
1. Go to open event frontend website
2. Click on creating an event
3. Scroll down to event topic section
4. Only Iot2 present as event topic and can't be changed

**Comment by CosmicCoder96** [comment]
@dreadpool2 The mechanism to add event topics already exists, an admin can create/delete them from his dashboard. Currently no one has added them :) This doesn't require any code related changes, hence closing it.
