### ISSUE TITLE
Empty sponsor item gets created when 'Add Sponsors' clicked and sponsor creation aborted

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-frontend#1343]
**Describe the bug**

In Overview -> Event Sponsors section, when 'Add Sponsor' is clicked, it routes to Wizard step 2. And then if back button is pressed to go back to the Overview screen, an empty sponsor record is added. 

**To Reproduce**
1. Go to Events Overview -> Event Sponsors section
2. Click on 'Add Sponsors' -> It will redirect to Event wizard step 2
3. Don't add the sponsor but go back to the Overview screen
4. An empty Sponsor field would be found

**Expected behavior**

No sponsor item should be created unless a Sponsor is added

**Screenshots**

![screenshot from 2018-07-03 23-40-17](https://user-images.githubusercontent.com/35009811/42237126-85548cfc-7f1a-11e8-97f5-c2754fd540cf.png)

**Comment by CosmicCoder96** [comment]
Can't reproduce it and it shouldn't be happening, because it redirects to the event's edit wizard step 2, and unless an empty sponsor gets saved it won't be present in the event overview.
