### ISSUE TITLE
API integration for Activity in route /admin/reports/system-logs/activity-logs

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1351]
**Is your feature request related to a problem? Please describe.**

API `/v1/activities` integration for Activity in route `/admin/reports/system-logs/activity-logs`

**Describe the solution you'd like**

Frontend v/s backend
 ```
(Frontend) Actor ==== actor (backend)
(Frontend) Time ==== time (backend)
(Frontend) Actions ==== action (backend)
```

**Describe alternatives you've considered**

**Additional context**

![screenshot from 2018-07-05 12-16-48](https://user-images.githubusercontent.com/22936570/42306715-b061f0ea-804d-11e8-90cd-e6f3ea4992e9.png)

**Others can claim**

**Comment by CosmicCoder96** [comment]
@bhaveshAn I am pretty sure this is already integrated.

**Comment by bhaveshAn** [comment]
@CosmicCoder96 What about Mails and Notifications ?
