### ISSUE TITLE
API integration for Mails in route /admin/reports/system-logs/mail-logs

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1352]
**Is your feature request related to a problem? Please describe.**

API `/v1/mails` integration for Mails in route `/admin/reports/system-logs/mail-logs`

**Describe the solution you'd like**

Frontend v/s backend
 ```
(Frontend) To ==== recipient (backend)
(Frontend) Time ==== time (backend)
(Frontend) Actions ==== action (backend)
(Frontend) Message ==== message (backend)
```

**Describe alternatives you've considered**

**Additional context**

![screenshot from 2018-07-05 12-27-46](https://user-images.githubusercontent.com/22936570/42307076-f43c8bb2-804e-11e8-8ddc-e9eab6bc5589.png)

API `/v1/mails`
```
{
  "data": {
    "attributes": {
      "action": "example",
      "message": "example",
      "subject": "example",
      "recipient": "example@example.com",
      "time": "2016-12-08T11:49:12.147941+00:00"
    },
    "type": "mail",
    "id": "1",
    "links": {
      "self": "/v1/mails/1"
    }
  },
  "jsonapi": {
    "version": "1.0"
  },
  "links": {
    "self": "/v1/mails/1"
  }
}

```

**Others can claim**

**Comment by CosmicCoder96** [comment]
@bhaveshAn Why are you opening these issues without checking, this is already implemented too. 
https://github.com/fossasia/open-event-frontend/commit/f6874f37054b816b5820d5d98b790559640e942b#diff-c550ca1aac16860445eb98800bd7d6e7
