### ISSUE TITLE
User should be logged in before ordering tickets

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1355]
**Describe the bug**
Currently server returns 401 error when unregistered user tries to order ticket. We should not allow unregistered user to order tickets.

**Expected behavior**
Show login/signup modal to unregistered user if he/she tries to order tickets without logging in.

**Comment by CosmicCoder96** [comment]
@pradeepgangwar Shouldn't we follow the same strategy as with event creation? i.e. if the user is not logged in, redirect him to the login *page* instead of a *modal*, and once he has logged in, redirect him back to the orders page.

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 For event creation we wrap `/create` route in `AuthenticatedRouteMixin` which ensures that user is logged in before accessing `/create` route. But since we are ordering tickets from `/e/{event_id}` which is a public page. So we can not use `AuthenticatedRouteMixin` but we can still directly redirect him to login page instead of modal. This will not redirect him back to same page for now, we have some PR #1313 and #1309 open to handle that. So we can do either thing i.e. redirect to login directly or open a modal which shows two options to login or signup and an error message.

Let me know which is the preferred way. Redirecting back to same page will be done if wither of the two PR mentioned above merges. :smile:

**Comment by CosmicCoder96** [comment]
@pradeepgangwar I see, proceed ahead with opening a modal approach in that case.
