### ISSUE TITLE
Refactor code to follow guidelines

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#137]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently we have some templates which do not follow the guidelines specified [here](https://github.com/fossasia/open-event-frontend/blob/development/docs/style-guide.md) eg. templates/componenets/events/view/export/api-response.hbs which uses double quotes instead of single quotes inside helper.

**Expected behavior:**
All the templates must follow the style guide.

Please find all such files and refactor the code to follow the style-guide.

**Comment by harshitagupta30** [comment]
can I work on this?

**Comment by geekyd** [comment]
Make sure to check all the files.
