### ISSUE TITLE
Public schedule page on frontend and web app should look similar

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-frontend#1370]
**Is your feature request related to a problem? Please describe.**
Public schedule page on frontend and web app should look similar.

**Describe the solution you'd like**
The web app does not use any library for the schedule, whereas frontend uses the library for the dynamic scheduler. Can the public page for schedule use the web app scheduler?

**Additional context**
Discussion is required on this @niranjan94 @CosmicCoder96 @geekyd @mayank8318 @pradeepgangwar @ritikamotwani @srv-twry @maxlorenz @Kreijstal

**Comment by pradeepgangwar** [comment]
I think we need a library in frontend so that organizer can change schedule using drag and drop. Maybe we can change webapp scheduler to use the library used in frontend? 
Others please share your opinion.

**Comment by mayank8318** [comment]
The webapp displays a static schedule so it doesn't need a library but frontend on the other hand needs to support editing the schedule as well. So IMO frontend should be given the priority and the webapp should be adjusted accordingly

**Comment by agbilotia1998** [comment]
@pradeepgangwar @mayank8318 if we have a look at schedule page on the web app - https://sched.eventyay.com/GoogleIO2017/schedule.html. It has the list view and calendar view, so is the scheduler library providing both the options?

**Comment by CosmicCoder96** [comment]
I think you guys should proceed with fullcalendar.io, as it already has an ember wrapper. Porting the static scheduler, will require a much larger effort, and the end result may not be as refined.
* This is based on my knowledge of the discussions I had last year, not sure if you discussed about any better alternatives in the meetings this session.

**Comment by pradeepgangwar** [comment]
@agbilotia1998 As mentioned by @CosmicCoder96 [fullcalendar.io](https://fullcalendar.io/) provides both the list view and calendar view. So I think we can use it. It provides drag and drop support also which will be helpful for frontend.

**Comment by agbilotia1998** [comment]
@maxlorenz can you please follow up here?

**Comment by agbilotia1998** [comment]
@maxlorenz since everyone here suggested implementing the fullcalendar.io library, you may follow up from here.

**Comment by maxlorenz** [comment]
will do

**Comment by CosmicCoder96** [comment]
Scheduler was implemented in https://github.com/fossasia/open-event-frontend/pull/1692
