### ISSUE TITLE
Add admin-sales models

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1373]
**Is your feature request related to a problem? Please describe.**

We need to implement the sales models on ember-js because they haven't been implemented yet

This is necessary in order to continue the development of open-event, the admin sales must be bound with the backend. And that's why we need the admin-sales models to be implemented.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar @CosmicCoder96 I would like to implement admin sales model. Can you please tell me if the PR referenced above was right approach to solve this? If yes, then I'll implement the whole admin sales model.

**Comment by shreyanshdwivedi** [comment]
@ritikamotwani @CosmicCoder96  can you please help me out. I want to integrate all the leftover admin APIs.

**Comment by shreyanshdwivedi** [comment]
I'm working on it. Will take few days to complete :)

**Comment by ritikamotwani** [comment]
Fixed by: https://github.com/fossasia/open-event-frontend/pull/1929
