### ISSUE TITLE
Link my-tickets and settings route to respective  buttons in nav-bar

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#138]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Nothing happens when the user click My tickets from the nav-bar.

**Expected behavior:**
The user should be redirected to my-tickets route after clicking the My tickets button.

![screenshot from 2017-06-05 01-00-45](https://cloud.githubusercontent.com/assets/12807846/26765004/e52f1b0e-498f-11e7-957e-0201d56065f2.png)

Link the My tickets button with my-tickets route.

**Comment by CosmicCoder96** [comment]
I'm working on this.
