### ISSUE TITLE
Display the event location on a map and show the event address in the public event page

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#14]
<img width="1680" alt="screen shot 2017-04-23 at 10 08 45 pm" src="https://cloud.githubusercontent.com/assets/2404372/25315498/6a7b77dc-2873-11e7-8ca7-def73b19fa96.png">

**What is expected ?**
- Map and address as a single [component](https://guides.emberjs.com/v2.12.0/getting-started/core-concepts/#toc_components) added to the public event page (the component should accept attributes that can allow us to either render just the map or just the address or both side by side.
- The width of it should be fluid. (that is, it should take up the width of it's parent)
- Data provided by the API should be used. (`latitude`, `longitude`, `locationName`)

**References:**
- https://guides.emberjs.com/v2.12.0/components/defining-a-component/
- https://semantic-ui.com/collections/grid.html
- https://github.com/asennikov/ember-g-map

**Comment by anu-007** [comment]
I like to work on this.
