### ISSUE TITLE
fix the tickets route UI, pointer menu  is overflowing

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#142]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26780685/7ce32a30-4a08-11e7-8201-935bf41080f4.png)

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26780712/9bf4bbdc-4a08-11e7-89ca-b9ef98081cdd.png)

**Related code:**
After mergin PR #134 the `ui grid` in view.hbs was replaced with `ui segment` because of which
this occured.

**Comment by utkarshnath** [comment]
@CosmicCoder96 this issue is resolved in #121 (you can check [here](https://young-wildwood-91762.herokuapp.com)) , in #134 the ui grid was removed as it was causing problem to many sub routes
