### ISSUE TITLE
Add support for third party auth

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-frontend#1423]
**Is your feature request related to a problem? Please describe.**

The support for third party auth needs to be added in the frontend.

- [x] facebook
- [ ] google+

**Comment by Anupam-dagar** [comment]
I would like to work on adding google auth.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I am going to resume working on it from today.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 can I use google library client for oauth.

**Comment by sk9331657** [comment]
@srv-twry  Can I work on this ??

**Comment by srv-twry** [comment]
Yes go ahead.

**Comment by sk9331657** [comment]
@srv-twry  Thanks

**Comment by Hudda** [comment]
@sk9331657 I have implemented the google signin feature in backened and a opened a PR for the same if you are not working on this, can I opened PR here as I have implemented the frontend part too.
