### ISSUE TITLE
Error on visiting Admin->Sessions

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1425]
**Describe the bug**
An error page is displayed on visiting Admin-> Sessions route.

**To Reproduce**
1. Go to Admin section
2. Click on Sessions tab
3. See error

**Expected behavior**
It should work properly

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by ritikamotwani** [comment]
![image](https://user-images.githubusercontent.com/22127980/42824527-a1366bfa-89fd-11e8-96cd-499c9f253f45.png)
It's working for me

**Comment by mayank8318** [comment]
@ritikamotwani Is `My-Sessions` route also working?

**Comment by ritikamotwani** [comment]
@mayank8318 yes it is.

**Comment by srv-twry** [comment]
![image](https://user-images.githubusercontent.com/21277837/42967972-89e20f04-8bbf-11e8-88be-56a88576f299.png)

Works fine for me. Closing this one.
