### ISSUE TITLE
Implement FB login - Step 1

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-frontend#1429]
**Is your feature request related to a problem? Please describe.**
Link the Facebook login button with the `/oauth/<provider>` API added in the server. This returns the redirect_url which will be then used to log in with FB.

**Describe alternatives you've considered**
\-

**Additional context**
Parent #1423

**Comment by srv-twry** [comment]
@mayank8318 It sends the redirect url in the first step. I have updated the issue :)
