### ISSUE TITLE
Add draft to events route.(UI only)

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#143]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add Draft as sub route of events.

![alt text](https://github.com/anu-007/assets/blob/master/Screenshot%20from%202017-06-05%2016-01-33.png?raw=true "Logo Title Text 1")

located at events/draft

**Comment by anu-007** [comment]
I like to work on this.thanks!!

**Comment by geekyd** [comment]
@anu-007 Please take a look at ui-table for this. We will be using it for all the tables. See how events-table is implemented for `events/live`

**Comment by niranjan94** [comment]
We will be reusing the same template as live. Only the data will change.
