### ISSUE TITLE
Add restore button to deleted events

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-frontend#1483]
**Describe the bug**

Events once deleted should have a restore button.

**To Reproduce**
1. Go to admin/events
2. Click on delete
3. See error

**Expected behavior**

Once deleted events should have a restore button which when clicked should restore that event.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium

**Comment by CosmicCoder96** [comment]
fixed in #2091
