### ISSUE TITLE
Show event license info at the bottom of the public event page

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#15]
<img width="1680" alt="screen shot 2017-04-23 at 10 16 21 pm" src="https://cloud.githubusercontent.com/assets/2404372/25315529/0c875c1c-2874-11e7-9312-eace117f3493.png">

**What is expected ?**
- Show license info as shown
- Data provided by the API has to be used (`licenceDetails`)

**Comment by harshitagupta30** [comment]
@niranjan94 Can I work on this issue?
