### ISSUE TITLE
Use closure actions instead of sendAction in the project.

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-frontend#1519]
**Is your feature request related to a problem? Please describe.**

Right now we are using sendAction in various components. We should use closure actions in the project.
Not a huge problem but can be done after handling major issues.

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi Can you take this up?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 yeah sure. I have given it a look and got to know about the problem. I'll work on it

**Comment by prateekj117** [comment]
@srv-twry May I work on this.

**Comment by prateekj117** [comment]
@CosmicCoder96 May I work on this?

**Comment by kushthedude** [comment]
@shreyanshdwivedi Are you still on it ?

**Comment by prateekj117** [comment]
@kushthedude I have already asked.

**Comment by iamareebjamal** [comment]
I don't have any knowledge of the frontend

**Comment by shreyanshdwivedi** [comment]
@prateekj117 go ahead !!

**Comment by kushthedude** [comment]
@prateekj117 Updates ?

**Comment by prateekj117** [comment]
@kushthedude Busy on some other issue, feel free to take this up.

**Comment by kushthedude** [comment]
Cool @prateekj117

**Comment by kushthedude** [comment]
@shreyanshdwivedi I had been looking in components but , I looked 10-15 files with no closure action. , Are you sure they are still in our app ?

**Comment by DaKeiser** [comment]
@kushthedude can I take this issue ?

**Comment by kushthedude** [comment]
Sure, go ahead.

**Comment by creatorpiyush** [comment]
Can I take this issue if no one is working on it?

**Comment by iamareebjamal** [comment]
#4347 is already open, so just fix it

**Comment by anjali1102** [comment]
Can I claim this issue? If no one working on it?

**Comment by iamareebjamal** [comment]
Yes

**Comment by anjali1102** [comment]
thanks

**Comment by hitesh9116** [comment]
can work on this issue. This will be my first contribution to open source.

**Comment by hitesh9116** [comment]
Can I work on this issue. This is my first time on an open source platform.

**Comment by Srijita007** [comment]
Is this issue still open? Can I work on it if no one is already working on this?

**Comment by shivambhai** [comment]
can i work on this issue its my first time to open source , please give me a chance

**Comment by hitesh9116** [comment]
@iamareebjamal  please reply

**Comment by ARKEOLOGIST** [comment]
Deployed a fix for some of the files. Should reduce the magnitude of the issue.

**Comment by SAP-20** [comment]
Can i work on this to get first hand on experience in open source??

**Comment by samik-rathore** [comment]
I would like to work on this issue, if no one is already on it.

**Comment by aaryan078** [comment]
i am working on this issue

**Comment by Bhagya195** [comment]
Can I work on this issue to get experience it's my first time working on open source??

**Comment by maze-runnar** [comment]
@ranjitkshah please check where else` sendAction` is used and do the required. we need to close this.

**Comment by maze-runnar** [comment]
@ranjitkshah can we close this now?
