### ISSUE TITLE
Add user admin page  at /admin (UI only)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#153]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out 
- Located at `/admin`

![image](https://cloud.githubusercontent.com/assets/17252805/26819836/47bc7b3e-4abe-11e7-9efe-330c42cc0a86.png)

- eleven tabs (hence eleven routes). This issue is for index route only. Please open other issues for other routes.
    - Admin - `/admin`
    - events - `/admin/events/`
    - sales - `/admin/sales`
    - sessions - `/admin/sessions`
    - Users - `/admin/users/`
    - permissions - `/admin/permissions`
    - messages - `/admin/messages`
    - Reports - `/admin/reports/`
    - settings - `/admin/settings`
    - Modules - `/admin/modules`
    - content - `/admin/contents`

While working on additional issues for the sub-routes of admin, please don't make the entire tab structure for navigating these routes, it will be taken care of it in this issue itself.

**Comment by CosmicCoder96** [comment]
I'm working on this.

**Comment by geekyd** [comment]
@CosmicCoder96 Also add other related issues so that everyone can start working on them.
