### ISSUE TITLE
Edit session proposal form is missing the file-upload widget

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-frontend#1536]
**Describe the bug**
Edit session proposal form doesn't contain the widget for file-upload.

**To Reproduce**
1. Go to 'Sessions tab in organizer dashboard'
2. Click on  'Edit button' for any session.
3. Scroll down to 'slides field'

**Expected behavior**
Widget to upload file should be present.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [Firefox]
 - Version [61.0.1]

**Comment by srv-twry** [comment]
@shreyanshdwivedi You can work on #1519 :)
