### ISSUE TITLE
Adding admin/sales route(UI only).

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#154]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

A admin/sales route.

![adminsales](https://cloud.githubusercontent.com/assets/17925669/26829407/23c79266-4ae3-11e7-832e-9c631600f89c.png)

There are also subroutes. Will be dealt as separate issues.

**Comment by sumedh123** [comment]
@geekyd Please assign.

**Comment by CosmicCoder96** [comment]
@sumedh123 While working on this please don't make the entire tabs, just the content of the sales page, I will be taking care of that in #153  while making the index page :)
