### ISSUE TITLE
Increase code coverage by adding more tests for components and helpers

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1554]
As we add more functionalities we should add more tests for components and helpers.

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi Yes there are many components and helpers for which tests can be added. This is a parent issue. You can see the test files and run the coverage tests to know which parts are missing tests.

**Comment by kushthedude** [comment]
@pradeepgangwar How do i run coverage tests ?
