### ISSUE TITLE
Add a proper button for Pay Now to pay for the tickets through stripe

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-frontend#1569]
**To Reproduce**
1. Go to e/event_identifier then order tickets
2. Click on order
3. Scroll down and fill info and choose stripe as payment option.

**Expected behavior**

Add a proper UI to the Pay now button.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium

**Comment by visuvasi** [comment]
--force claim

**Comment by visuvasi** [comment]
@fossasia/open-event-frontend-admin claim

**Comment by visuvasi** [comment]
@ritikamotwani claim

**Comment by sarnava1** [comment]
@ritikamotwani I am claiming this and working on it.

**Comment by agrawalarpit14** [comment]
@ritikamotwani I would like to work on this

**Comment by Anupam-dagar** [comment]
@ritikamotwani what is the correct url, I am getting a 404 on localhost/e/event_identifier

**Comment by pradeepgangwar** [comment]
@Anupam-dagar Correct url will be `/e/{event_identifier}` where event identifier is the id of the event created by you. Then to access the orders page make sure you have enabled the payment option and have proper keys set up for paypal. You should see the paynow button for paypal then.

**Comment by sk9331657** [comment]
@ritikamotwani  @pradeepgangwar  I am claiming this.

**Comment by sk9331657** [comment]
@srv-twry  For this I have to modify stripe selector ui or pay no button

**Comment by shreyanshdwivedi** [comment]
@ritikamotwani  @pradeepgangwar I've made required styling change. Please verify if this style is fine?
![screenshot from 2019-01-03 18-04-25](https://user-images.githubusercontent.com/25428397/50638034-450a9f80-0f82-11e9-9713-f872facef8da.png)

**Comment by sk9331657** [comment]
> @ritikamotwani @pradeepgangwar I've made required styling change. Please verify if this style is fine?
> Basically, I just added the class of `Pay Now` button of `Order form` to the stripe checkout `Pay with card` button.
> If you both are fine with the style, I'll proceed to open a PR for this issue. Do suggest me if any kind of style change is required :))
> ![screenshot from 2019-01-03 18-04-25](https://user-images.githubusercontent.com/25428397/50638034-450a9f80-0f82-11e9-9713-f872facef8da.png)

@shreyanshdwivedi Please ask maintainers before taking up the issue. I have already claimed the issue.

**Comment by shreyanshdwivedi** [comment]
@sk9331657 it has been 10 days since you claimed the issue. And as no progress was made in 10 days by you, I think anyone was free to take this issue. 10 days are sufficiently enough time to solve this :sweat_smile:

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi @sk9331657 Sorry for late reply. But I would like to inform you that both of you are referring to wrong button.

**Comment by pradeepgangwar** [comment]
Actually the button that we are talking of comes when user selects stripe as the payment option and proceeds next.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar I think there is a bit of confusion here. Please confirm which button you are referring to -
**_Step 1 -_** 
![screenshot_2019-01-04 new order -40db264b-69d2-42c6-8716-6fd3091085b6 orders open event](https://user-images.githubusercontent.com/25428397/50685140-0f2af100-103e-11e9-9de0-f47967604ff4.png)

**_Step 2 -_**
![screenshot_2019-01-04 placed order -40db264b-69d2-42c6-8716-6fd3091085b6 orders open event](https://user-images.githubusercontent.com/25428397/50685154-1d790d00-103e-11e9-8431-603b9214ad65.png)

**_Step 3 -_**
![screenshot from 2019-01-04 16-24-59](https://user-images.githubusercontent.com/25428397/50685170-2a95fc00-103e-11e9-9f55-dc8fe0f24018.png)

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi as said earlier the step after we choose to pay via stripe I.e. we are referring to button in step 2.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar I've opened the PR for button in Step 2 itself :wink:
Please refer to my PR https://github.com/fossasia/open-event-frontend/pull/1781

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi actually we need original button that is provided via stripe. Please read the stripe documentation and see if you can attach that button as we get for paypal.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar Okay. I'll try to embed the button provided by Stripe. :smile:

**Comment by pradeepgangwar** [comment]
Cool. If that is not possible please let me know we can proceed with this for now.
