### ISSUE TITLE
Add admin/events page (UI only)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#157]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/26840908-6fc9029a-4b05-11e7-8ce7-066485fb43af.png)
Located at `admin/events`
Please go through the details of #153 before starting to work on this.

**Comment by utkarshnath** [comment]
@CosmicCoder96 plz assign this to me

**Comment by CosmicCoder96** [comment]
@utkarshnath Please work on #158 first, you just claimed it. Let others work on this simultaneously to save time, thanks !

**Comment by utkarshnath** [comment]
@CosmicCoder96 as there are eleven tabs I thought each one of us can take two issues each, but ok I'll finish #158 first. 👍

**Comment by CosmicCoder96** [comment]
@utkarshnath I agree, but currently there are 10 exisiting PRs open and all have them have some requested changes, jumping on to new issues without making the requested changes, will create a backlog and slow down the process overall, also these 11 tabs have significant content inside them. It's best to take them one at a time. Thanks!
