### ISSUE TITLE
Add admin/users page (UI only)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#158]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
 
![image](https://user-images.githubusercontent.com/17252805/26840974-b2c3730a-4b05-11e7-82f3-7c72156ef7d0.png)
Located at `admin/users`

Please go through the details of #153 before starting to work on this.

**Comment by utkarshnath** [comment]
@CosmicCoder96  plz assign this to me
