### ISSUE TITLE
Implement Scheduler on FE

### ISSUE THREAD

**Issue by schedutron** [fossasia/open-event-frontend#1580]
**Is your feature request related to a problem? Please describe.**

Currently, FE lacks a functional scheduler for scheduling sessions within an event.

**Describe the solution you'd like**

Scheduler should be implemented which allows event organizers to organize event sessions conveniently.

**Additional context**
Related issue: #1370

**Comment by schedutron** [comment]
Please mark this as a parent issue :)

**Comment by ritikamotwani** [comment]
Solved: https://github.com/fossasia/open-event-frontend/pull/1692
