### ISSUE TITLE
Add admin/permissions page (UI only)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#159]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/26841022-e0410f2c-4b05-11e7-8f56-f17ca48cb9a7.png)
located at `admin/permissions`

Please go through the details of #153 before starting to work on this.

**Comment by harshitagupta30** [comment]
I would like to work on this

**Comment by CosmicCoder96** [comment]
@harshitagupta30 Hi, can you please make the requested changes to both  your existing PRs first, then you can start working on this ! Thanks !

**Comment by harshitagupta30** [comment]
Hi! @CosmicCoder96 I have made all the requested changes on both the PR you can review it and let me know if more changes required. Thanks :+1:

**Comment by CosmicCoder96** [comment]
@harshitagupta30 Please go ahead, thanks !
