### ISSUE TITLE
Ember-notify displaying multiple notifications

### ISSUE THREAD

**Issue by abhi40308** [fossasia/open-event-frontend#1595]
**Describe the bug**
Ember notify displays multiple instances of a notification at the same time.

**To Reproduce**
1. Go to 'https://open-event-frontend.herokuapp.com/register'
2. Type any username and password
3. Click 'Register'. After once error notification appears, click again for a few times and the screen gets occupied by multiple notifications.

**Expected behavior**
There should be only one instance of notification at a time.

**Screenshots**
![screen shot 2018-08-07 at 12 47 58 am](https://user-images.githubusercontent.com/26903230/43748605-152ec35c-9a0e-11e8-94c0-8711d5c586a4.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS High Sierra]
 - Browser [chrome]

**Additional context**
Currently there seems to be no way provided in ember-notify to solve this problem (actually the pr in ember-notify repo to tackle this issue is stalled from a long time : [link](https://github.com/aexmachina/ember-notify/pull/105). To remove this, some other notification plugin have to be used. Would be happy if anyone can tell some alternate way of achieving this with ember-notify only.

**Comment by srv-twry** [comment]
Unrelated: Don't use the heroku instance. it is not up to date. Use fossasia.github.io/open-event-frontend/  for testing.

**Comment by rajvaibhavdubey** [comment]
The error only appears on the heroku instance not on fossasia.github.io/open-event-frontend/ .

**Comment by abhi40308** [comment]
@rajvaibhavdubey  Actually that is a basic problem with ember-notify. It can be reproduced at various points wherever ember-notify is being used. Above was just one such example. For example in the github.io instance:
1. Login to open event.
2. GO to notifications, (here: https://fossasia.github.io/open-event-frontend/notifications.)
3. Click "Mark all read". Keep clicking.
Preview:
![screen shot 2018-08-08 at 1 32 58 am](https://user-images.githubusercontent.com/26903230/43799538-70c9c520-9aab-11e8-80f1-1d7a33747713.png)

**Comment by CosmicCoder96** [comment]
@rajvaibhavdubey This issue will be fixed as soon as https://github.com/aexmachina/ember-notify/pull/105 gets merged. It's not breaking the app right now, so the best course would be to wait for the merge as there are still other high priority issues right now.
