### ISSUE TITLE
Add admin/sessions page (UI only)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#160]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/26841668-e9ff6354-4b07-11e7-84dc-f87f7fe444c8.png)
located at `admin/sessions`

Please go through the details of #153 before starting to work on this.

**Comment by utkarshnath** [comment]
plz assign this to me
