### ISSUE TITLE
Add check for whether email is registered to direct to Log In or SignUp

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-frontend#1613]
**Is your feature request related to a problem? Please describe.**

EventBrite has a Get Started screen which accordingly redirects to Log In or Sign Up screen after checking if an email is registered.

**Describe the solution you'd like**

Add a similar screen to Open Event.

**Would you like to work on this**

Yes

**Comment by CosmicCoder96** [comment]
We don't need it right now as the focus is on getting all the features working completely and removing bugs in the ones already implemented.
