### ISSUE TITLE
On orders page: order summary table, left most column is smashed in towards the left side.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1615]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17252805/43995194-5e8f365a-9dc7-11e8-96d4-9d5260e5b3c5.png)

**Comment by Jaggu-123** [comment]
Sir, I am having difficulty in finding this issue, so can you suggest me the path where can I found this issue.
