### ISSUE TITLE
Add placeholder text for the schedule route

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1618]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17252805/43995302-fbabcd08-9dc8-11e8-974c-862058ef5624.png)
An empty screen is displayed when there is no schedule available for an event

**Comment by srv-twry** [comment]
Accidental reference. Sorry about it.

**Comment by mishuvs** [comment]
Taking this

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I would like to take up this issue. Just to clarify, do you want the time schedule above the event name ("Halloween" in the above example) to be added in the white space?

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi No, just a helper text saying,
"Schedule for the event is currently not available"

**Comment by HarendraSingh22** [comment]
Can I take up this issue?

**Comment by ritikamotwani** [comment]
@HarendraSingh22 , sure.

**Comment by pranav1698** [comment]
Hey @ritikamotwani, @CosmicCoder96 I am taking this issue and starrting to work on it
