### ISSUE TITLE
Improve the social media icons display

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/open-event-frontend#1656]
**Describe the bug**

The Social media icons / tabs are very close and look congested.

**To Reproduce**
1. Go to 'https://open-event-frontend.herokuapp.com/login'
2. See error

**Expected behavior**

Some space can be added in between the icons/tabs to make them look cleaner
**Screenshots**

![open even login](https://user-images.githubusercontent.com/33062425/45453267-fcdb1f00-b6fd-11e8-8350-9b70f8a13be4.png)

**Comment by rajvaibhavdubey** [comment]
I am working on this.

**Comment by ritikamotwani** [comment]
@rajvaibhavdubey have you installed the code locally and then ran the project? As the UI is different currently.

**Comment by sk9331657** [comment]
@rajvaibhavdubey  Are u working on it??

**Comment by ritikamotwani** [comment]
![image](https://user-images.githubusercontent.com/22127980/45589591-f212cb00-b945-11e8-9224-150abb003561.png)
This is the current UI for the login page.
Closing this issue.

**Comment by sk9331657** [comment]
> ![image](https://user-images.githubusercontent.com/22127980/45589591-f212cb00-b945-11e8-9224-150abb003561.png)
> This is the current UI for the login page.
> Closing this issue.

@ritikamotwani  Is fb login working ??

**Comment by ritikamotwani** [comment]
Yes, that is the reason why it was decided to keep that button for the time. If you would like to work on an issue go ahead with twitter/google plus and add those buttons to the UI with their implementation.

**Comment by sk9331657** [comment]
> Yes, that is the reason why it was decided to keep that button for the time. If you would like to work on an issue go ahead with twitter/google plus and add those buttons to the UI with their implementation.

@ritikamotwani  Actually I have set up the front end locally but I am using open-event-dev API for the backend. first of all FB login is not working and second, my email is not getting verified. What can be the issue
