### ISSUE TITLE
Add show/hide password button in login form

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/open-event-frontend#1681]
**Is your feature request related to a problem? Please describe.**

Show/hide Password button in login form

**Describe the solution you'd like**

When User presses the button , the password becomes visible

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar I have worked on this issue and have almost completed coding part. Attached is the gif of the solution. My only concern is that `eye slash` icon is not rendering. It shows `eye` icon instead. I found out that this happens a lot in case of semantic ui. Can you help me?
![showhidepassword](https://user-images.githubusercontent.com/25428397/49684754-fcd09c80-fafd-11e8-98a2-6c4ee7066a52.gif)

**Comment by pradeepgangwar** [comment]
@shreyanshdwivedi Let me look into this. Can you create a PR with whatever you have done so far?
