### ISSUE TITLE
There is no background image in small screens

### ISSUE THREAD

**Issue by sarnava1** [fossasia/open-event-frontend#1683]
**Describe the bug**

There is no background image in small screens
**To Reproduce**
1. Go to localhost:4200 after running the open-event-server 
2. Check for responsiveness in small screens and you will find no background images in small screens

**Expected behavior**

There should be background images in small screens too
**Screenshots**

![nobginsmallscreens](https://user-images.githubusercontent.com/25319565/46586650-2ee26580-ca9f-11e8-985b-96ff6b365c6f.png)

**Desktop (please complete the following information):**
 - OS:Ubuntu 
 
**Additional context**

I will like to work in this issue.

**Comment by niranjan94** [comment]
@sarnava1 which background image are you talking about ? 

If it is the below, then it is by intention.

<img width="1680" alt="screenshot 2018-10-13 at 10 58 21 pm" src="https://user-images.githubusercontent.com/2404372/46908152-ff6aa780-cf3b-11e8-9dc7-a090c035a19f.png">

**Comment by sarnava1** [comment]
The home screen @niranjan94 .

**Comment by CosmicCoder96** [comment]
The absence of background image is intentional in small screens.

**Comment by sarnava1** [comment]
@niranjan94 @CosmicCoder96 If that was intentional then it is fine andthen there is no issue with it. Thank you.
