### ISSUE TITLE
The style of links do not change when hovered over it

### ISSUE THREAD

**Issue by sarnava1** [fossasia/open-event-frontend#1684]
**Describe the bug**

The Forget your password and New to site? links do not change their style when hovered over them. Ideally it get darker or some css should change when we hover over them for better experience.
**To Reproduce**
1. Go to Login page
2. Hover over the above mentioned links

**Expected behavior**

The styles of the links should change when hovered over
**Screenshots**

![linknostylewhenhover](https://user-images.githubusercontent.com/25319565/46586733-32c2b780-caa0-11e8-997e-4c2d8c58e2ee.png)

**Additional context**

I will like to work on this issue.

**Comment by manaswinidas** [comment]
I'm interested

**Comment by sarnava1** [comment]
@manaswinidas I am working on it.

**Comment by sarnava1** [comment]
Due to some issues I could not open a PR. I will do that soon. You may look into other issues which are open. Thank you.

**Comment by sk9331657** [comment]
@sarnava1 Are you still working on this issue?

**Comment by sarnava1** [comment]
Hello @sk9331657 due to ongoing sem and lab exams I am not able to open a PR but will work on it as soon as the exams ends. 
Thank you.

**Comment by sarnava1** [comment]
@shreyanshdwivedi my exams have finished and I will open a PR by the weekend. Thank you.

**Comment by shreyanshdwivedi** [comment]
As you told, you are having problem with setup. I'm working on this. @sarnava1

**Comment by sarnava1** [comment]
@shreyanshdwivedi  Nice that you did the work but I would be happier if you could help me with the local installation because I had already completed the work but could not give the screenshots as I was not able to see the changes. Anyways, thank you.
