### ISSUE TITLE
Location field on home page gets disabled with background-image icon_error.png

### ISSUE THREAD

**Issue by satyasashi** [fossasia/open-event-frontend#1686]
**Describe the bug**
When visited home page [localhost:4200], in the form fields, Location Field is disabled, with background-image "icon_error.png".

**To Reproduce**
1. Go to 'localhost:4200/'
2. See the second field on home screen under the Banner 'Location'
3. You can see the Field is disabled and got background image="icon_error.png" with place_holder = "Sorry! something went wrong."

**Expected behavior**
To show the empty fields and let the user enter the keywords.

**Screenshots**
![fend_firefox_bug](https://user-images.githubusercontent.com/17382345/46762795-b88b7080-ccf5-11e8-8559-c6120c312c21.png)
![fend_chromium_bug](https://user-images.githubusercontent.com/17382345/46762823-cd680400-ccf5-11e8-8bba-cef060b7f8ba.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [Chromium, Firefox]

**Additional context**
It shows up in both Firefox and Chromium browsers. Issue seems to be under 'components/quick-filter.hbs'

**Comment by niranjan94** [comment]
Hi. This only happens when you don't use a proper api key for the google places autocomplete widget which renders there. Not exactly an issue.

See https://github.com/fossasia/open-event-frontend/blob/development/app/components/widgets/forms/places-autocomplete.js for more info.
