### ISSUE TITLE
Update end date of event automatically when start date is selected.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1690]
When a start date is selected initially, on step 1 of event creation wizard, end date should become equal to a date one day after the start date, currently, it remains today's date and needs to be changed manually.
![image](https://user-images.githubusercontent.com/17252805/46984511-761db700-d09a-11e8-850d-ec65e0203181.png)

**Comment by eefreddy** [comment]
Hey! I'd like to take a crack at this issue 😁Thanks!

**Comment by CosmicCoder96** [comment]
@eefreddy Sure go ahead 👍 😄

**Comment by CosmicCoder96** [comment]
@eefreddy Any updated on this?

**Comment by Anupam-dagar** [comment]
I would like to work on it. Since it's my first issue on open event frontend, I would require 3-4 days to complete this.
