### ISSUE TITLE
Add meta tags and ogp tags for better SEO

### ISSUE THREAD

**Issue by sarnava1** [fossasia/open-event-frontend#1697]
**Describe the bug**

We should add meta tags and ogp tags in the index.html for better SEO

**Expected behavior**

Meta tags and OGP tags help for better SEO and can help us improve the rank of our page

**Comment by shreyanshdwivedi** [comment]
@sarnava1 if you are busy with some work, I'll like resolve this. Its being too late since you opened the issue.
