### ISSUE TITLE
Add gitter link to Connect with us section in the footer

### ISSUE THREAD

**Issue by sarnava1** [fossasia/open-event-frontend#1738]
**Is your feature request related to a problem? Please describe.**

We must add gitter link of open-event-frontend to the Connect with us section in the footer.

**Additional context**

I am working on this problem.

**Comment by mohitacecode** [comment]
can i take this issue?

**Comment by sarnava1** [comment]
@mohitacecode I am solving this. Meanwhile you can take up other issues

**Comment by mohitacecode** [comment]
ok go ahead ;)

**Comment by CosmicCoder96** [comment]
@sarnava1 All the social link properties in the footer are dynamic and returned using the *settings* API End Point of Open Event Server. We don't intend to hardcode them in the footer.

**Comment by sarnava1** [comment]
ok @CosmicCoder96
