### ISSUE TITLE
footer too long below 768px breakpoint

### ISSUE THREAD

**Issue by pg07codes** [fossasia/open-event-frontend#1750]
Below the 768px breakpoint the footer becomes too long which is not a good UI design strategy, i would suggest making it 2 columns instead of one .

![foss](https://user-images.githubusercontent.com/34238240/50324488-31ccee00-0505-11e9-8ecb-11636994b426.gif)

## will you work on it ?
- (edit) NO.  Any one interested can fix it if the reviewers think it is needed.

**Comment by Akshay1910** [comment]
I would like to work on this issue

**Comment by pg07codes** [comment]
@sk9331657 you may.

**Comment by punisher1151** [comment]
@pg07codes
 @CosmicCoder96 
Can I work on it bec it seems pg07codes couldn't  I 'll try to complete it soon

**Comment by CosmicCoder96** [comment]
Not a priority right now.
