### ISSUE TITLE
Creation of New Order Fails 

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1751]
**Describe the bug**

When the user selects the available tickets for an event and proceeds to place an order, the creation fails. The server raises a **422: Unprocessable Entity**. 

The **422** is caused due to the missing **attendees** relationship in the POST request data sent to the server. However, intriguingly, the error disappears, if the *order* relationship defined in the **attendee** model defined as `order: belongsTo: ('order')` is removed.

Upon removal of the relationship from the model, Ember automatically starts including attendees in the POST request.

**Comment by CosmicCoder96** [comment]
While PR #1752  may serve as a temporary fix, we require some help in identifying the root cause of this behavior. 
@niranjan94 @pradeepgangwar @ritikamotwani @Anupam-dagar @shreyanshdwivedi

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I'll try figuring it out.

**Comment by CosmicCoder96** [comment]
Order creations seems stable so far in the test run. Can be reopened later if issues are encountered.
