### ISSUE TITLE
Connect Section Missing In Footer

### ISSUE THREAD

**Issue by sk9331657** [fossasia/open-event-frontend#1753]
**Describe the bug**

**To Reproduce**
1. Go to http://127.0.0.1:4200/
2. Go to Footer
3.See Missing Connect Section

**Expected behavior**

Links Should be present

**Screenshots**

**Comment by pradeepgangwar** [comment]
@sk9331657 Links will be available when you add the respective links from the admin section. This is invalid issue.

**Comment by pradeepgangwar** [comment]
go to `/admin/content` to add the links. You can close this issue or let me know in case you have any doubt.

**Comment by sk9331657** [comment]
@pradeepgangwar  Got  it now.
