### ISSUE TITLE
Create Acceptance test for explore route

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#1774]
Create an acceptance test which tests the following:
 - User ~clicks on browse events button on the home page~ visits expore route
-  Resulting transition should result in the current URL set to `/explore`

**Reference**
See the acceptance test for the notifications route  in 
_open-event-frontend/tests/acceptance/notifications-test.js_

**Comment by CosmicCoder96** [comment]
@Dharmesh-Poddar Please proceed.

**Comment by CosmicCoder96** [comment]
@Dharmesh-Poddar Any progress on this?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 if @Dharmesh-Poddar is busy with something else, I will like to work on this :))

**Comment by Dharmesh-Poddar** [comment]
@shreyanshdwivedi  please proceed..

**Comment by vsvipul** [comment]
@shreyanshdwivedi i would like to work on this if you are not anymore. May I?

**Comment by shreyanshdwivedi** [comment]
@vsvipul if you are able to fix it on your local and all the tests passes, feel free to open a PR.I'll close mine
