### ISSUE TITLE
Implement sharing of events on facebook and twitter

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/open-event-frontend#1782]
**Is your feature request related to a problem? Please describe.**

A feature to share the events with your friends on social media.

**Would You like to work on this**
Yes

**Comment by CosmicCoder96** [comment]
It's already present.
![image](https://user-images.githubusercontent.com/17252805/52073217-f7ee0d80-25c1-11e9-9b66-792ece4eb62d.png)
