### ISSUE TITLE
Show HTML instead of HTML Code on Sessions Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1795]
Example is: https://eventyay.com/e/3689bc98/sessions/s/all

![screenshot from 2019-01-14 21-18-11](https://user-images.githubusercontent.com/1583873/51138657-fabad580-1841-11e9-9dae-7b925d1b47f0.png)

**Comment by rajvaibhavdubey** [comment]
I would like to work on this. :smile:
