### ISSUE TITLE
Getting Here link directs to bottom of page instead of top of map

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1797]
Expected "Getting Here" link directs to top of map.

Please also test "Getting Here" link for subpages. It does not direct to map area from subpages neither.

![screenshot from 2019-01-14 21-21-32](https://user-images.githubusercontent.com/1583873/51138844-87659380-1842-11e9-9209-1b9bd637106e.png)

**Comment by sk9331657** [comment]
@mariobehling  Claiming this.

**Comment by uds5501** [comment]
@sk9331657 if you are not working on this can i give it a try?

**Comment by kushthedude** [comment]
@mariobehling @CosmicCoder96 I think this is duplicate of #275

**Comment by kushthedude** [comment]
Duplicate of #275
