### ISSUE TITLE
Instead of showing "Discount" column show actual discount below previous price

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1800]
The legacy version showed the original price striked through and the discount price below in the same column. Please implement it in the same way again instead of a column.

![screenshot from 2019-01-14 21-26-06](https://user-images.githubusercontent.com/1583873/51139083-2ee2c600-1843-11e9-8e79-3e977171ae95.png)

**Comment by shreyanshdwivedi** [comment]
I'll like to work on it
