### ISSUE TITLE
Storage is not defined in Admin Settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1803]
Where is the storage defined? It is not visible in admin settings at https://eventyay.com/admin/settings. There should be the option to define the storage location.

![screenshot from 2019-01-14 21-40-44](https://user-images.githubusercontent.com/1583873/51139805-29867b00-1845-11e9-82ef-45f9b5afb1ef.png)

**Comment by Haider8** [comment]
@CosmicCoder96 i can't find the storage settings in admin panel, can you please confirm this issue if it is still valid
