### ISSUE TITLE
Blog link is missing in admin and footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1805]
Please add the blog link in admin and footer (https://eventyay.com/admin/content).

![screenshot from 2019-01-14 21-48-41](https://user-images.githubusercontent.com/1583873/51140207-40799d00-1846-11e9-8a5c-4f7e25f4bb0a.png)

**Comment by CosmicCoder96** [comment]
@mariobehling 
![image](https://user-images.githubusercontent.com/17252805/51495257-b48fe400-1df6-11e9-8845-ea3fb9a607e0.png)
On legacy, the blog link was named as 'support' : ref: https://legacy.eventyay.com
We can rename the support link to blog on the frontend, else will have to add an additional field on the server.

**Comment by prateekj117** [comment]
@CosmicCoder96 May I work on this issue?
