### ISSUE TITLE
Languages are missing and empty languages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1806]
In https://eventyay.com/admin/content/translations other languages are missing.

Nevertheless unavailable languages are also showing up on the bottom dropdown, but they don't work and it jumps back to English immediately.

![screenshot from 2019-01-14 21-50-34](https://user-images.githubusercontent.com/1583873/51140374-a9611500-1846-11e9-8268-4da3de54d028.png)

**Comment by sk9331657** [comment]
@mariobehling  claiming this.
