### ISSUE TITLE
Admin Dashboard: Number of Emails not correct

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1808]
The admin dashboard does not show the correct number of emails sent.

![screenshot from 2019-01-14 21-54-38](https://user-images.githubusercontent.com/1583873/51140537-12488d00-1847-11e9-9d7e-96056226da64.png)

**Comment by Haider8** [comment]
I would like to work on this issue.

**Comment by uds5501** [comment]
Can't triage, Kindly elaborate the steps to recreate the bug
@mariobehling 
![image](https://user-images.githubusercontent.com/21087061/51772120-380c4680-2111-11e9-899e-caad6c0fd35e.png)

**Comment by uds5501** [comment]
I am working on this issue
