### ISSUE TITLE
Events Dashboard: Numbered and bullet lists wasting space

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1809]
In the event dashboard the numbers and bullet points are unnecessary in the table and are wasting space. Please delete them.

![screenshot from 2019-01-14 21-57-44](https://user-images.githubusercontent.com/1583873/51140719-8edb6b80-1847-11e9-9b5d-f77d65da2421.png)

**Comment by shreyanshdwivedi** [comment]
I'll like to work on this.
