### ISSUE TITLE
Fix the column width issue in tickets/attendees

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#181]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Screenshots : 
Current : 
![attendees](https://user-images.githubusercontent.com/17925669/26879953-80879442-4bb0-11e7-8095-2db8841efbca.png)

Expected : 
The buttons should occupy whole width of screen.

**Comment by sumedh123** [comment]
Working on a fix.

**Comment by geekyd** [comment]
@sumedh123 This is not really required, all the buttons will have similar behaviour by #124

**Comment by sumedh123** [comment]
Sorry I dint see it. My bad.

**Comment by sumedh123** [comment]
@geekyd Shall I get this closed?

**Comment by geekyd** [comment]
@sumedh123 Yes, you can take up #124. Thanks!
