### ISSUE TITLE
On tables edit icon is on top. View icon should be on top.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1811]
The edit icon is on top as the most prominent icon in tables and dashboards. Please change the icon listing and show the "View" icon on the top of every view.

![screenshot from 2019-01-14 22-02-01](https://user-images.githubusercontent.com/1583873/51140964-2c369f80-1848-11e9-97c5-607f6ebc6d16.png)

**Comment by shreyanshdwivedi** [comment]
I'll like to take this up. Will open a PR real soon
