### ISSUE TITLE
Speakers Event Dashboard: Speakers Icon Image missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1816]
In order to understand if the speaker has an image it was easy to see if the speaker has an image through the icon. The icon is no longer there. Please add it in front of the speaker name.

Compare: https://eventyay.com/events/3689bc98/scheduler

![screenshot from 2019-01-14 22-34-37](https://user-images.githubusercontent.com/1583873/51142608-c00a6a80-184c-11e9-85c0-8e62fde13f2c.png)

**Comment by Dharmesh-Poddar** [comment]
@mariobehling  @CosmicCoder96  can I work on it..

**Comment by CosmicCoder96** [comment]
@Dharmesh-Poddar Go Ahead

**Comment by Dharmesh-Poddar** [comment]
![screenshot from 2019-01-17 20-26-53](https://user-images.githubusercontent.com/32756751/51327158-b3795280-1a96-11e9-9dcd-4e2eb0768d47.png)

I have set this project locally before but this time I am getting this issue @CosmicCoder96  please have a look...

**Comment by Dharmesh-Poddar** [comment]
![open event1](https://user-images.githubusercontent.com/32756751/51424715-eab34500-1bf7-11e9-8aec-351aaa8b2564.png)
![open event 2](https://user-images.githubusercontent.com/32756751/51424716-ebe47200-1bf7-11e9-81b4-31a4d80a0b0e.png)

@CosmicCoder96 I have set this project locally before but this time I am getting this error ..
