### ISSUE TITLE
Speakers: View and Edit page not there

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1817]
Trying to access speakers through the speakers overview page of an event results in an empty speakers view or speakers edit page.

Reproduce by going to e.g. https://eventyay.com/events/3689bc98/speakers/all and click on edit or view button of a speaker.

![screenshot from 2019-01-14 22-36-57](https://user-images.githubusercontent.com/1583873/51142761-124b8b80-184d-11e9-8048-e69f66a8067e.png)

**Comment by CosmicCoder96** [comment]
Was related to porting legacy data, fixed at evenyay.com now.
