### ISSUE TITLE
Sessions Page overshooting on right side on smaller screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1818]
On laptop screens the width of the page is not working properly as it is overshooting on the right hand side, e.g. on https://eventyay.com/events/3689bc98/sessions/all
![screenshot from 2019-01-14 22-40-31](https://user-images.githubusercontent.com/1583873/51142937-871ec580-184d-11e9-9b2d-a64e8b5ce800.png)

**Comment by ms10398** [comment]
I would like to work on this issue @mariobehling

**Comment by shubham3211** [comment]
@ms10398 are you working on this issue ? 
 Can I claim it.

**Comment by ms10398** [comment]
You can go ahead @shubham3211

**Comment by shubham3211** [comment]
I am working on this.

**Comment by kushthedude** [comment]
@shubham3211 Are you still on it?

**Comment by shubham3211** [comment]
@kushthedude go ahead :+1:

**Comment by kushthedude** [comment]
Can you please tell me how to reproduce the error as i am unable to do it. @shubham3211 
<img width="963" alt="screenshot 2019-03-03 at 11 45 52 am" src="https://user-images.githubusercontent.com/44091822/53691733-16564d00-3daa-11e9-8f7e-707dfb6f1a38.png">

**Comment by kushthedude** [comment]
@shubham3211 ??

**Comment by shubham3211** [comment]
I think the issue has been resolved.

**Comment by kushthedude** [comment]
@CosmicCoder96 Can you close the issue as we are not able to reproduce it.
