### ISSUE TITLE
Footer: Sitemap Link not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1820]
There is no sitemap link and sitemap.

![screenshot from 2019-01-14 23-06-57](https://user-images.githubusercontent.com/1583873/51144376-2beed200-1851-11e9-8ec2-e428aaf18e14.png)

**Comment by rajvaibhavdubey** [comment]
@mariobehling I'm claiming this.

**Comment by CosmicCoder96** [comment]
duplicate of #152
