### ISSUE TITLE
Footer: Locations are not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1822]
Locations of events are not showing up on footer.

Expected: Top locations of events should show up and link to the filter result page.

![screenshot from 2019-01-14 23-09-28](https://user-images.githubusercontent.com/1583873/51144527-90aa2c80-1851-11e9-9bab-7a54a98df90a.png)

**Comment by sk9331657** [comment]
@mariobehling  This is server error , I suppose , as local development shows locations, whereas eventyay doesn't shows locations.

**Comment by sk9331657** [comment]
![screenshot from 2019-01-15 22-30-32](https://user-images.githubusercontent.com/17084322/51196475-32468200-1915-11e9-8bc1-00a56428f9fc.png)

**Comment by CosmicCoder96** [comment]
Added.
