### ISSUE TITLE
Footer: Nearby events are not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1823]
The footer should show real nearby events, but there are only placeholders.

![screenshot from 2019-01-14 23-10-51](https://user-images.githubusercontent.com/1583873/51144564-b7686300-1851-11e9-936c-d52821233d49.png)

**Comment by sk9331657** [comment]
@mariobehling  Claming this.

**Comment by Dishebh** [comment]
Is the issue still valid? If yes, can I take it?

**Comment by iamareebjamal** [comment]
How will you show nearby events?

**Comment by Dishebh** [comment]
> How will you show nearby events?

I was thinking of showing all the events related to what are now just placeholders. Something like, if we click on FOSSASIA, then the query passed will be `event_name=fossasia`. I know, nothing related to the nearby events, though.

**Comment by iamareebjamal** [comment]
> then the query passed will be event_name=fossasia

Where will the query be passed? Is there an API for similar events?

**Comment by Dishebh** [comment]
> > then the query passed will be event_name=fossasia
> 
> Where will the query be passed? Is there an API for similar events?

I was talking about the query passed in the search bar😅, like when you search for the fossasia in the main search bar present in the homepage, you can see that the page responds to the query of `event_name=fossasia`.

**Comment by iamareebjamal** [comment]
Then it's not nearby events

**Comment by mariobehling** [comment]
No longer valid due to design change
