### ISSUE TITLE
Sessions and Speaker Export not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1824]
The export of sessions or speakers fails, e.g. at https://eventyay.com/events/3689bc98/sessions/all

![screenshot from 2019-01-15 00-15-40](https://user-images.githubusercontent.com/1583873/51147510-c69fde80-185a-11e9-9ad6-3bc46a345d04.png)

**Comment by CosmicCoder96** [comment]
Resolved, was being caused due to misconfiguration of temporary storage directory.
