### ISSUE TITLE
Cookies Policy page not found

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#1825]
**Describe the bug**

**To Reproduce**
Post installation,
1. Navigate to the [https://www.eventyay.com](https://www.eventyay.com) where you're prompted to read a policy pertaining to cookies.
2. Click on the link for more infomration
3. It outputs a message saying that [http://next.cookie-policy.eventyay.com/](url) is not found

**Expected behavior**
I suggest that it should link to a page which has details regarding all the information the cookie stores.

**Desktop:**
 - OS: [OS agnostic]
 - Browser [Browser agnostic]

**Smartphone:**
 - OS: [OS agnostic]
 - Browser [Browser agnostic]

**Comment by CosmicCoder96** [comment]
@saicharan, thanks for reporting, actually any of the large static pages with frequently changing content are defined on the Admin dashboard, have set it up for eventyay.com now. So closing this.
![image](https://user-images.githubusercontent.com/17252805/51492284-4514f700-1dec-11e9-81a7-90728d8d15ff.png)

**Comment by CosmicCoder96** [comment]
Fixed now.
