### ISSUE TITLE
Payment Form needs to have clearer Currency info, e.g. SG$

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1828]
Currently users cannot exactly see always what currency is listed, e.g. $ is the same for USD and SGD. Please add the nomination US, SG and other in front, e.g. SG$.

**Comment by agarwalrounak** [comment]
I would like to work on this.

**Comment by CosmicCoder96** [comment]
@sk9331657 This shouldn't be repeated in the future, @agarwalrounak claimed it first.
