### ISSUE TITLE
Event Page: Timezone incorrect

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1829]
On the event pages the timezones are not listed correctly. E.g. in the FOSSASIA Summit wizard timezone is specified as Asia/Singapore, but on the event page it shows CET. See https://eventyay.com/e/3689bc98

![screenshot from 2019-01-15 12-14-18](https://user-images.githubusercontent.com/1583873/51177200-42337700-18bf-11e9-8cac-98818487cdfd.png)

**Comment by agarwalrounak** [comment]
I would like to work on this.

**Comment by leoking-crey** [comment]
Thanks for reporting this @mariobehling .I will start working on this

**Comment by leoking-crey** [comment]
@agarwalrounak with all due respect, I think it needs to be assigned to you by the author before you start working on it

**Comment by rajvaibhavdubey** [comment]
@mariobehling Timezone is working fine for me.

**Comment by mariobehling** [comment]
Instead of showing the timezone e.g. +08 the frontend should show the actual timezone e.g. SGT.

![screenshot from 2019-01-24 19-56-00](https://user-images.githubusercontent.com/1583873/51701618-2132fa80-2012-11e9-91d1-be0a68cd0146.png)

**Comment by mariobehling** [comment]
The time and date of the event on the public page must be identical with the time and date in the wizard. This is not the case, e.g. check FOSSASIA Summit.

![screenshot from 2019-01-24 19-57-32](https://user-images.githubusercontent.com/1583873/51701765-73741b80-2012-11e9-8ad0-d1843ad93771.png)

**Comment by jaynilshah** [comment]
@mariobehling  @CosmicCoder96 
The problem seems with the moment library
![screenshot from 2019-02-15 19-29-38](https://user-images.githubusercontent.com/36128751/52861910-dd876880-3159-11e9-9aed-91cbbada26fe.png)
Also Singapore appears twice in the dropdown list.
Can some temporary function be created to solve this until moment library is updated?
![screenshot from 2019-02-15 19-29-55](https://user-images.githubusercontent.com/36128751/52861995-18899c00-315a-11e9-9ea0-2ea491845be0.png)

**Comment by kushthedude** [comment]
@CosmicCoder96 Is this issue still open?

**Comment by uds5501** [comment]
@CosmicCoder96 @mariobehling this should not be a valid issue because looking into `momen-js/timezone` code, this is a correct abbreviation.


https://github.com/moment/moment-timezone/blob/d0bcdcad01acece5df6988603e8cec146d78bd12/data/packed/2018g.json#L223-L228

**Comment by kushthedude** [comment]
@uds5501 but what if we make change to moment.js for our requirements

**Comment by uds5501** [comment]
@kushthedude read this

https://github.com/fossasia/open-event-frontend/issues/2218#issuecomment-466725575
