### ISSUE TITLE
Stripe payments not working: Invalid

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1830]
Error Message is "invalid redirect uri".

![screenshot from 2019-01-15 12-24-49](https://user-images.githubusercontent.com/1583873/51177927-58423700-18c1-11e9-996b-597d0b23fac4.png)

**Comment by sk9331657** [comment]
@mariobehling  I will like to work on this.

**Comment by pradeepgangwar** [comment]
@mariobehling @CosmicCoder96 This is not the bug on FE side. For this we need to add this redirect URI on our app that we are using for live website.

**Comment by pradeepgangwar** [comment]
Sure @mariobehling I will be in touch with @CosmicCoder96 .

**Comment by pradeepgangwar** [comment]
For information of other contributors . This is an admin level issue and does not require code change in FE repository

**Comment by CosmicCoder96** [comment]
Resolved by configuring the application in sprite dashboard.
