### ISSUE TITLE
User Profile image(icon) missing 

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#1839]
**Describe the bug**
The profile icon is missing as displayed below.

**To Reproduce**
1. Login with credentials on open-event-server
2. The Display icon for a user is missing

**Expected behavior**
User's picture should be visible.

**Screenshots**
![screenshot from 2019-01-16 09-35-14](https://user-images.githubusercontent.com/25197147/51214422-de06c680-1943-11e9-8102-7153cf00bf58.png)

**Comment by ambujraj** [comment]
@mrsaicharan1 I would take this issue

**Comment by CosmicCoder96** [comment]
Resolved, was happening due to incorrect storage directory environment variable. Please reopen if it repeats. Try re-uploading the image and it should work.
