### ISSUE TITLE
Ticket Page shows current time/date instead of event time/date

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1847]
Expected: The page where the user buys the ticket should show the date/time of the event in the right-hand box.

![screenshot from 2019-01-16 09-58-15](https://user-images.githubusercontent.com/1583873/51237751-6e113400-1975-11e9-807d-4367aca1c97c.png)

**Comment by sk9331657** [comment]
@mariobehling  I want to work on this.

**Comment by sk9331657** [comment]
@uds5501  I have already claimes.
