### ISSUE TITLE
Event Session Tab: Search Functionality Not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1855]
In the sessions tab the search functionality is not working, e.g. here: https://eventyay.com/events/3689bc98/sessions/all

![screenshot from 2019-01-16 23-55-27](https://user-images.githubusercontent.com/1583873/51284285-45c41c80-19eb-11e9-84d2-1addc9832cef.png)

**Comment by Haider8** [comment]
I would like to work in this issue.

**Comment by CosmicCoder96** [comment]
Fixed in #1934
