### ISSUE TITLE
Session Export CSV does not include all data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1856]
The Session Export should export all data sets that are available e.g. including:
* Submission time
* All speakers
* Proposed length
* Type (Workshop, Talk)
* Level (e.g. Intermediate)
* Status (e.g. pending, accepted etc.)

![screenshot from 2019-01-17 00-04-14](https://user-images.githubusercontent.com/1583873/51284380-a3f0ff80-19eb-11e9-9a1c-3b37c6ad36ad.png)

**Comment by CosmicCoder96** [comment]
moved to server https://github.com/fossasia/open-event-server/issues/5519
