### ISSUE TITLE
Speaker Form: Make "Speaking Experience" into Paragraph and "Gender" as dropdown

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1860]
* The speaking experience form element should be offering a paragraph.
* The Gender should be a dropdown with the option to enter "Other" and specify that.

![screenshot from 2019-01-17 00-46-58](https://user-images.githubusercontent.com/1583873/51286044-99d1ff80-19f1-11e9-92bd-67567c5fba9e.png)

**Comment by Sangatdas** [comment]
Will work on this issue.

**Comment by sk9331657** [comment]
@Sangatdas  Can I work on this issue??

**Comment by harsh-jindal** [comment]
@sk9331657 Can I work on this issue?

**Comment by harsh-jindal** [comment]
@sk9331657 Im working on this.

**Comment by shreyanshdwivedi** [comment]
@harsh-jindal any update? I would like to take this up

**Comment by harsh-jindal** [comment]
@shreyanshdwivedi You can take this up.

**Comment by kushthedude** [comment]
@shreyanshdwivedi Still on it ?

**Comment by kushthedude** [comment]
@shreyanshdwivedi Still on it ?

 ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude go ahead. But open a PR once it is completed.

**Comment by kushthedude** [comment]
Cool 👍
