### ISSUE TITLE
Not possible to make "Accepted Speakers" into "Confirmed Speakers"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1861]
In the "Accepted Speakers" tab the option to be "Confirmed" and show up in the confirmed tab. The confirmed button should have a light "Blueish" kind of way.

![screenshot from 2019-01-17 01-28-23](https://user-images.githubusercontent.com/1583873/51287378-714d0400-19f7-11e9-82d7-fbfab25e21b8.png)

**Comment by shreyanshdwivedi** [comment]
I'll work on it

**Comment by ritikamotwani** [comment]
I am working on this.
