### ISSUE TITLE
Sessions show up in 4days schedule even though they are not added yet

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1863]
Unscheduled sessions show up in the schedule. They were not added and show up without reason.

Compare: https://eventyay.com/events/3689bc98/scheduler

![screenshot from 2019-01-17 01-38-07](https://user-images.githubusercontent.com/1583873/51287621-a9087b80-19f8-11e9-9c4d-dc5443abd2a7.png)

**Comment by CosmicCoder96** [comment]
This should be fixed now, unscheduled sessions should have `starts-at` and `ends-at` values as null. Was a legacy data issue, DB has been appropriately refactored. Please reopen if it repeats for any other event.
