### ISSUE TITLE
Schedule: 1 day view switch Rooms and Time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1864]
Similar to Google Calendar the Rooms should be on the header row 1 and the time should be on the column 1. Compare: https://eventyay.com/events/3689bc98/scheduler
![screenshot from 2019-01-17 01-40-51](https://user-images.githubusercontent.com/1583873/51287708-22a06980-19f9-11e9-834b-e1a4a5a4e1f0.png)

**Comment by divyabaid16** [comment]
@mariobehling the link you mentioned is not working. 

![selection_045](https://user-images.githubusercontent.com/32747809/51440317-de101900-1ceb-11e9-9273-8fb6561c33cc.png)

**Comment by YogeshSharma0201** [comment]
Working on this.
