### ISSUE TITLE
Payment Review Page Not Clear

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1867]
The payment review page is actually the same page as the previous page with the only difference of the payment button. Please take inspiration from the final payment page of Amazon and make the last page in the payment process similar to Amazon.

![screenshot from 2019-01-17 02-12-12](https://user-images.githubusercontent.com/1583873/51288663-862c9600-19fd-11e9-871c-58db2feaa212.png)

**Comment by uds5501** [comment]
Looking into it
