### ISSUE TITLE
Simplify Payment Page: Move ticket holder person box and add box to enable billing information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1868]
On the payment page the following changes should be made (see image below. It should be like that.):
* move the ticket holder box to ask whether the ticket holder is the same person as the buys just below the heading
* below the heading "billing information" add a box "Enable Billing Information" 
   * standard should be disabled and in that case don't show the billing info fileds
   * if enabled show the fields to fill in additional data

![screenshot from 2019-01-17 02-15-40](https://user-images.githubusercontent.com/1583873/51289180-7f068780-19ff-11e9-9eaa-cbbe2ec444df.png)

**Comment by sk9331657** [comment]
@mariobehling  Will like to solve this.

**Comment by manpoffc** [comment]
@sk9331657 are you working on this?

**Comment by sk9331657** [comment]
@manpoffc  Yup.
