### ISSUE TITLE
Payment Page: Make "Payment Method" into its own section on order page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1872]
There should be a sections "Payment Method" similar to above sections e.g. Billing Information. Also:
* add text: Please choose your payment method.
* Change "Stripe" to "Credit Card"

![screenshot from 2019-01-17 10-38-01](https://user-images.githubusercontent.com/1583873/51309347-73897f80-1a44-11e9-99e9-c1a457f01d41.png)

**Comment by ujjwalll** [comment]
Done.
