### ISSUE TITLE
Event Dashboard: Speaker's data and design incorrect or missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1882]
Please see screenshot below. There are a number of issues, e.g. Submitted number is missing.

Please ensure each data is in one line and type and numbers have the same distance. Also ensure all numbers are correct and showing up.

This issue only appears if the user has an event with data setup at https://eventyay.com/events/live

![screenshot from 2019-01-18 00-24-43](https://user-images.githubusercontent.com/1583873/51355465-8ab58500-1ab7-11e9-986c-a90143b42168.png)

**Comment by uds5501** [comment]
Looking into it
