### ISSUE TITLE
Fix dashboard view to be more appropriate

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1883]
* Fix date to show starting and end data. Maked date in one row and the time directly below the date. Reduce width of the column.
* Expand the width of the column "Tickets" and reduce the column width of other column respectively. The goal is that each ticket name and the ticket numbers fit in one row also when ticket names are long.
* Ensure the view works on mobile views

Compare: https://eventyay.com/events/live

![screenshot from 2019-01-18 00-32-53](https://user-images.githubusercontent.com/1583873/51355842-9bb2c600-1ab8-11e9-90ef-78da6329039c.png)

**Comment by uds5501** [comment]
@mariobehling  I would like to work on it

**Comment by sk9331657** [comment]
@uds5501  Are u working on this.

**Comment by uds5501** [comment]
@sk9331657 I am working
