### ISSUE TITLE
Session Proposal missing from the profile!

### ISSUE THREAD

**Issue by miphilomath** [fossasia/open-event-frontend#1885]
**Describe the bug**
Session proposal from my profile is missing which was there till yesterday. Now the "My Session" tab shows, "No session proposals found for the events".

**Additional context**
Talk title: "IRC: the saviour!"
Talk status: "Pending" 

Along with the session proposals, all the profile information is lost/not visible on the dashboard.

**Comment by CosmicCoder96** [comment]
@miphilomath Thank you for reporting the issue, did you by any chance register again? Because we can see the session on our dashboard.

**Comment by miphilomath** [comment]
Not at all. My profile picture and other details were missing as well, which I updated again. 

Also, eventyay takes abc@xyz.com and a.bc@xyz.com as separate email address, even though few email provides consider both of them as same.

**Comment by CosmicCoder96** [comment]
Moved to https://github.com/fossasia/open-event-server/issues/5567
