### ISSUE TITLE
Admin Dashboard: User Search not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1887]
The search for users does not provide any results.

https://eventyay.com/admin/users/all

![screenshot from 2019-01-18 09-35-32](https://user-images.githubusercontent.com/1583873/51374838-7f3c7b00-1b04-11e9-9b07-3f5e98fb4f87.png)

**Comment by shubham3211** [comment]
I would like to work on this.

**Comment by CosmicCoder96** [comment]
Fixed in #1934
