### ISSUE TITLE
Organizer Session Edit Form Missing Option to Add/Remove Speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1888]
The session edit form does not show speakers and therefore we cannot remove them. Also cannot add any.

![screenshot from 2019-01-18 10-38-59](https://user-images.githubusercontent.com/1583873/51378366-66849300-1b0d-11e9-8182-6d4c7a9983e1.png)

**Comment by championballer** [comment]
Claiming this.
