### ISSUE TITLE
Organizer Session/Speaker Create form does not show Speakers or Sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1889]
When an organizer creates a sessions (or speaker) they have the option of adding an existing speaker. The list of existing speakers is not complete. The existing list is a long list. Instead it should be a dropdown menu in order to handle long lists easier.

![screenshot from 2019-01-18 10-40-55](https://user-images.githubusercontent.com/1583873/51378585-dd219080-1b0d-11e9-929f-9824076683ca.png)

**Comment by harsh-jindal** [comment]
@mariobehling I'm claiming this

**Comment by CosmicCoder96** [comment]
functionality added in #1963
