### ISSUE TITLE
Invitation to Organizer without Account or not logged in user results in Email with link to 404 page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1898]
Expected: If an organizer is invited who does not have an account they should receive a link with to a sign up page. If the user has an email that is signed up already the user should see a message "please login".

![screenshot from 2019-01-19 01-52-23](https://user-images.githubusercontent.com/1583873/51419731-0cc3ad80-1b8d-11e9-91d6-1603fdb14671.png)

**Comment by YogeshSharma0201** [comment]
@mariobehling  Claiming this.

**Comment by CosmicCoder96** [comment]
Parent issue: #2094

**Comment by CosmicCoder96** [comment]
fixed in ##2095
