### ISSUE TITLE
Process to invite co-organizers broken

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1900]
The process to invite a co-organizer is broken:
* The co-organizers do not show up in accepted area
* The invite generates a 404 page
* Acceptance is not possible

**Comment by divyabaid16** [comment]
I'm working on this issue.

**Comment by CosmicCoder96** [comment]
parent issue #2094

**Comment by CosmicCoder96** [comment]
Fixed in #2095
