### ISSUE TITLE
Start page events not showing City and Country Location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1901]
Many events on the start page only show the street address, but not the city and country. 

![screenshot from 2019-01-19 02-08-50](https://user-images.githubusercontent.com/1583873/51420038-4f868500-1b8f-11e9-8948-2ad510264308.png)

**Comment by sk9331657** [comment]
Claiming it.

**Comment by CosmicCoder96** [comment]
@sk9331657 No, don't take more than two issues at a time, first do the changes on your PRs.

**Comment by sk9331657** [comment]
@CosmicCoder96  I have updated other pr , so claiming this.

**Comment by sk9331657** [comment]
@mariobehling  There is no such individual parmeter for City and location , instead they are combined to single string , as I have checked now.

**Comment by CosmicCoder96** [comment]
@mariobehling 
Please enter countries using this if missing, legacy data probably used a different version of google maps API.
![image](https://user-images.githubusercontent.com/17252805/51728393-124c5680-20ab-11e9-9151-d347841237a0.png)

I fixed it for the fossasia summit.
