### ISSUE TITLE
Ticket Page does not provide Order Invoice and Ticket Download

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1902]
Expected: PDF Documents should be provided with the links.

Tickets are neither produced for newly ordered tickets.

![screenshot from 2019-01-19 02-23-52](https://user-images.githubusercontent.com/1583873/51420317-5e6e3700-1b91-11e9-8c43-15e9a464c75c.png)

**Comment by championballer** [comment]
Claiming this.

**Comment by Haider8** [comment]
@CosmicCoder96 I would like to work on this issue

**Comment by Haider8** [comment]
I cannot reproduce this issue, can you please tell if it still exists

**Comment by CosmicCoder96** [comment]
Has been resolved.
