### ISSUE TITLE
Entering Promotional Code and Hitting Enter directs to wrong URL

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1903]
The URL when a user hits enter is for example: https://eventyay.com/e/3689bc98?promotional_code=SGMEETUP instead of https://eventyay.com/e/3689bc98?code=SGMEETUP.

![screenshot from 2019-01-19 04-19-12](https://user-images.githubusercontent.com/1583873/51421650-8e253b00-1ba1-11e9-9793-ca0c6719c811.png)

**Comment by sk9331657** [comment]
Claiming it.

**Comment by CosmicCoder96** [comment]
@sk9331657 No, you already have three open PRs. First do the changes on them.

**Comment by sk9331657** [comment]
@CosmicCoder96  CAn I claim now?
