### ISSUE TITLE
Child Issue : Added Option 100, 250 and All in Search Events

### ISSUE THREAD

**Issue by sk9331657** [fossasia/open-event-frontend#1906]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Working on it.

**Comment by CosmicCoder96** [comment]
I believe @iamareebjamal asked you to create a child issue for the search component, also all the filter  options 100,250,ALL can be added in a single issue, no need for a separate one.
