### ISSUE TITLE
Hide ticketing section if not enabled

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#1907]
**Describe the bug**

Hide ticketing section if not enabled. This throws an exception if the the ticketing is enabled.

**To Reproduce**
1. Disable ticketing from system
2. Go to create event

**Expected behavior**
Ticketing should be hidden if the it is disabled from the admin panel.

**Comment by sakshee-19** [comment]
@geekyd  I am working on it.

**Comment by sk9331657** [comment]
@sakshee-19  Are u working on it??

**Comment by sakshee-19** [comment]
@sk9331657 Yes, I am working on it.

**Comment by sk9331657** [comment]
@sakshee-19  Can I work on this ??

**Comment by sk9331657** [comment]
> @sakshee-19 any updates?

@geekyd  Can I work on this??

**Comment by sakshee-19** [comment]
@geekyd @sk9331657 Sorry for the troubles, but I am stuck at one point. @sk9331657 you can take it.

**Comment by shreyanshdwivedi** [comment]
I'm taking this up. Will submit a PR soon :)
