### ISSUE TITLE
Discount code shows error and invalid for non-logged in users

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1910]
Discount code works, but it does not show for not-logged in users.

![whatsapp image 2019-01-19 at 11 55 55](https://user-images.githubusercontent.com/1583873/51425879-61454800-1be2-11e9-9a4e-8b9af91f42ce.jpeg)

**Comment by harsh-jindal** [comment]
@mariobehling Claiming this

**Comment by CosmicCoder96** [comment]
Moved to the server.
https://github.com/fossasia/open-event-server/issues/5526
