### ISSUE TITLE
Multiple error message

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#1911]
**Describe the bug**
Error message is appearing multiple times.

**Expected behavior**
Error message should appear only once.

**Screenshots**
![errormessage](https://user-images.githubusercontent.com/19900978/51425926-0246f980-1c09-11e9-819c-348f61f323bb.png)

I am working on this

**Comment by mariobehling** [comment]
Correct one message should suffice.

**Comment by kushthedude** [comment]
@uds5501 
if you are not workin on it , i would like to give it a look

**Comment by shubham3211** [comment]
@kushthedude I would work on this issue if https://github.com/aexmachina/ember-notify/pull/105 gets merged.

**Comment by kushthedude** [comment]
@CosmicCoder96 cant we move to ember cli notification from ember notify?

**Comment by kushthedude** [comment]
@shubham3211 @uds5501 @CosmicCoder96 I have seen the similar issue in Badgeyay repo and can proceed with the change of package , As ember notify dont give us a unique id and the PR has not been merged untill now , I think moving to a different package could be a good option . Please give your views .

**Comment by CosmicCoder96** [comment]
No, exceptions should be caught at specific instances.
