### ISSUE TITLE
Session Showing Invalid Date

### ISSUE THREAD

**Issue by sk9331657** [fossasia/open-event-frontend#1912]
**Is your feature request related to a problem? Please describe.**

I am finding this bug on eventyay. 
I will try to recreate bug on local event and make solution for this.

**Additional context**

![screenshot from 2019-01-19 23-46-37](https://user-images.githubusercontent.com/17084322/51430664-89fe2980-1c44-11e9-9a65-ff8e58eb9c02.png)

**Comment by mariobehling** [comment]
> Is your feature request related to a problem? Please describe.

> Describe the solution you'd like

> Describe alternatives you've considered

> Additional context

What is this about?

What is the solution?

**Comment by khansultan1** [comment]
anyone looking into it or should I go ahead?

**Comment by uds5501** [comment]
@khansultan1 I am working on it

**Comment by CosmicCoder96** [comment]
fixed in #1971
