### ISSUE TITLE
Ember Build Failing due to payment dictionary

### ISSUE THREAD

**Issue by sk9331657** [fossasia/open-event-frontend#1914]
**Describe the bug**

![screenshot from 2019-01-20 13-51-41](https://user-images.githubusercontent.com/17084322/51436915-cae55500-1cbb-11e9-8f2f-659b18ec3a62.png)

Working on it.

**Comment by CosmicCoder96** [comment]
There is no build error, maybe it's local to yours. Try syncing the branch with the repository.
