### ISSUE TITLE
Public Speakers Page: Large Images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1916]
The images on the public speakers page are very large. They are in PNG and it is great that this is of good quality, but the page is several MB big now. Please change it to smaller sized images.

Compare: https://eventyay.com/e/3689bc98/speakers

![screenshot from 2019-01-20 07-56-43](https://user-images.githubusercontent.com/1583873/51437803-61f1e300-1ca3-11e9-8498-14f111837841.png)

**Comment by sk9331657** [comment]
@mariobehling  Claiming this.
