### ISSUE TITLE
Not showing India in the payment countries and paypal option set to false

### ISSUE THREAD

**Issue by creyente1897** [fossasia/open-event-frontend#1922]
**Describe the bug**
In the create event page, the payment countries is not showing India while it is showing in the 'Add Tax Information' Section , also the paypal is set to false in app/utils/dictionary/payment.js  

**To Reproduce**
1. Go to 'Create Event' page
2. Click on 'Add Paid tickets'
3. Click on 'Select Country' dropdown
4. Scroll Down 'I' lettered countries

**Expected behavior**
Should show India in 'Select Country' dropdown and paypal option should be set to 'true'
**Screenshots**
![image](https://user-images.githubusercontent.com/33548141/51459711-76a3a900-1d7f-11e9-94d0-f68055716e36.png)

Add Tax Information Section

![image](https://user-images.githubusercontent.com/33548141/51459749-95a23b00-1d7f-11e9-8b4b-29fae28713cb.png)

Working on it

**Comment by creyente1897** [comment]
:label: bug

**Comment by sk9331657** [comment]
@mariobehling  Claiming this.

**Comment by creyente1897** [comment]
i am working on it

**Comment by sk9331657** [comment]
@creyente1897  You should claim first before start solving the issue. Read the guide here : https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by sk9331657** [comment]
@creyente1897  I am already working on this. You can work on other issue .

**Comment by creyente1897** [comment]
@sk9331657 with all due respect sir i have written down in the issue that i am working on it.
![image](https://user-images.githubusercontent.com/33548141/51483281-b63db580-1dbe-11e9-8db4-7b04390770f4.png)

**Comment by sk9331657** [comment]
@creyente1897  My mistake .Go on solving the issue , in case of any help , ping me.

**Comment by creyente1897** [comment]
@sk9331657 Yes sir, I will and thank you.
