### ISSUE TITLE
Event Dashboard: Revision Info seems hardcoded

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1923]
The revision information on the dashboard always shows 6 revisions no matter if more revisions are made. Please show the actual revision information.

![screenshot from 2019-01-21 09-50-06](https://user-images.githubusercontent.com/1583873/51463056-895bb500-1d62-11e9-822c-3370d5145ec2.png)

**Comment by amanjain25** [comment]
I would like to work on this issue

**Comment by amanjain25** [comment]
@mariobehling could you please tell what does this revision mean here? Is it the number of times event has been edited or something else?

**Comment by mariobehling** [comment]
Yes.

**Comment by uds5501** [comment]
@amanjain25 if you are not working on it, can I have a look?

**Comment by uds5501** [comment]
@mariobehling The deployed version of eventyay does not have this error. Kindly close this issue.
![image](https://user-images.githubusercontent.com/21087061/51838027-2900e080-232b-11e9-96fd-08d571e64c7e.png)

**Comment by shreyanshdwivedi** [comment]
The revision info is indeed hardcoded. I can reproduce this issue locally. But is revision info supported by server? If not, I would like to take up this issue.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I think, for now we should comment out `No. of revisions` till we get backend ready to implement it. Your thoughts?

**Comment by kushthedude** [comment]
Duplicate of #2191
