### ISSUE TITLE
Add Featured Event Section to Startpage

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1925]
The start page currently shows latest events always. Please add a section above the current section "Featured Events".

![screenshot from 2019-01-21 09-21-32](https://user-images.githubusercontent.com/1583873/51464285-7c8c9080-1d65-11e9-8824-9651dd25282b.png)

In the admin section events tab add the option "Featured" into the table. So admins can control the featured events at https://eventyay.com/admin/events/live

![screenshot from 2019-01-21 10-16-04](https://user-images.githubusercontent.com/1583873/51464363-aba30200-1d65-11e9-9d63-511e61c853f2.png)

See here:
![screenshot from 2019-01-21 10-17-54](https://user-images.githubusercontent.com/1583873/51464436-d8571980-1d65-11e9-9396-5d4a538cf41d.png)

**Comment by amanjain25** [comment]
Working on this.

**Comment by uds5501** [comment]
@amanjain25 are you working on this?

**Comment by CosmicCoder96** [comment]
@uds5501 Read marshmallow docs: https://flask-marshmallow.readthedocs.io/en/latest/
Also, familiarise yourself with the concept of migration files, browse through other pull requests on the server which required changes on the database itself.

**Comment by CosmicCoder96** [comment]
@uds5501 Open both server and frontend PRs for this ASAP.

**Comment by uds5501** [comment]
@CosmicCoder96 on it
