### ISSUE TITLE
Events Dashboard: Show Speakers Total, Pending, Accepted, Rejected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1936]
In the list of speakers on the events dashboards (https://eventyay.com/events/live), please show speakers in the table:
* Total
* Accepted
* Confirmed
* Pending
* Rejected

![screenshot from 2019-01-21 23-52-27](https://user-images.githubusercontent.com/1583873/51502739-aaaab880-1dd7-11e9-8990-defbc6a39dc5.png)

**Comment by sk9331657** [comment]
@mariobehling  Working on it.

**Comment by harsh-jindal** [comment]
@ritikamotwani Can I work on this?

**Comment by uds5501** [comment]
@harsh-jindal Can I please take over this issue if you are not investing your time in this?

**Comment by harsh-jindal** [comment]
@uds5501 You can go ahead with this.

**Comment by shreyanshdwivedi** [comment]
@uds5501 I would like to work on it. Are you still working on it?

**Comment by uds5501** [comment]
@shreyanshdwivedi Sure, go ahead

**Comment by uds5501** [comment]
@shreyanshdwivedi I think I have some time and a way to solve this, shall I give it another try if you have not invested much time in it?
