### ISSUE TITLE
Create event: No success message or page is shown upon publishing

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#1938]
**Describe the bug**
There is no way for the user to know if he/she has successfully created an event. 
**To Reproduce**
1. Go to 'Create event page' .
2. Click on 'Publish' after filling out the details.
3. See the bug

**Expected behavior**
There should be some message or the page upon successfully publishing the event. It can also redirect the user on the newly created event.

I would like to work on this issue

**Comment by CosmicCoder96** [comment]
@Haider8 Pop up appears. Flow is as expected.
