### ISSUE TITLE
Billing Information: Add fields and change order of fields

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1939]
Change it to the following order and add fields as shown below:

* Name or Company -> make this one required
* Tax Number -> make this one optional
* Street Address
* City
* State/Province -> this one optional
* Zip Code
* Select country -> move country to bottom

![screenshot from 2019-01-22 09-07-04](https://user-images.githubusercontent.com/1583873/51520852-1c5d2380-1e25-11e9-81ec-bb0984de087b.png)

**Comment by shreyanshdwivedi** [comment]
I'll like to work on it

**Comment by mohitm15** [comment]
I 'll like to take this issue

**Comment by shreyanshdwivedi** [comment]
@mohitm15 I've already opened a PR for this. You can try some other issue :)
