### ISSUE TITLE
Organizers Speakers Tabs: Show State of Sessions in front

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1942]
Please add a badge directly in front of the sessions in the speakers tab on e.g. https://eventyay.com/events/3689bc98/speakers/accepted

![screenshot from 2019-01-22 10-30-26](https://user-images.githubusercontent.com/1583873/51525562-e45bdd80-1e30-11e9-9f8f-4e5dedc2034d.png)

**Comment by sk9331657** [comment]
@mariobehling  Claiming this.

**Comment by ritikamotwani** [comment]
I would like to work on this.
