### ISSUE TITLE
Cannot save profile as valid Facebook and Linkedin URLs are not accepted

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1944]
Most versions of Facebook and Linkedin URLs are not accepted in the speakers form.

![screenshot from 2019-01-22 11-43-01](https://user-images.githubusercontent.com/1583873/51530371-14a87980-1e3b-11e9-867c-1b3e5898493c.png)

**Comment by creyente1897** [comment]
@mariobehling can i work on it.
