### ISSUE TITLE
Session Detail Page: Event Menu Bar (Overview, Tickets, Sessions, Speakers etc.) is missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1950]
The event menu bar is missing above the session detail page.

![screenshot from 2019-01-23 11-09-31](https://user-images.githubusercontent.com/1583873/51599275-7f22ed80-1eff-11e9-9a7f-8aabe5fdf574.png)

**Comment by harsh-jindal** [comment]
@mariobehling I'm claiming this

**Comment by harsh-jindal** [comment]
Someone else can take this up
