### ISSUE TITLE
Speaker > Speaker session showing invalid date

### ISSUE THREAD

**Issue by khansultan1** [fossasia/open-event-frontend#1951]
**Describe the bug**

**To Reproduce**
1. Go to 'Session'
2. Click on 'Any speaker'
3. Scroll down to 'Speaker description'

**Expected behavior**

**Screenshots**

![issue](https://user-images.githubusercontent.com/6906715/51603570-2881d780-1f30-11e9-9fad-bb419eb034df.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows:10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 50+

**Comment by uds5501** [comment]
@mariobehling this issue seems related to #1912
