### ISSUE TITLE
Session Edit: Option to Add More Speakers Missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1956]
The edit speakers area does not have a way to add or remove additional speakers for organizers. (e.g. https://eventyay.com/events/3689bc98/sessions/edit/5116)

![screenshot from 2019-01-23 17-52-20](https://user-images.githubusercontent.com/1583873/51622836-bf05c700-1f37-11e9-9970-82338b53fe54.png)

**Comment by CosmicCoder96** [comment]
Functionality added in #1963
