### ISSUE TITLE
Redirect user to event page with discount code after login, if user has originally entered it as a not logged in user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1969]
When the user enters a link to an event page with a discount and then is requested to login, the user should be directed back to that event page including with the discount after login. This is currently not the case.

**Comment by apoorvkhare07** [comment]
Hey @mariobehling, is this issue still up for taking ?

**Comment by CosmicCoder96** [comment]
Fixed in #1970
