### ISSUE TITLE
My Tickets: Clicking on Ticket Image results in Moving to Top instead of Ticket Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1978]
Clicking on the image of a ticket should direct a user to the ticket page itself (just like other areas of that ticket field).

Compare: https://eventyay.com/my-tickets/upcoming

![screenshot from 2019-01-26 10-45-49](https://user-images.githubusercontent.com/1583873/51785429-f2bf3780-2157-11e9-8fa9-02762acd5548.png)

**Comment by uds5501** [comment]
@mariobehling Looking into it
