### ISSUE TITLE
My Tickets: Tickets of Past Events Not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1980]
Past events are missing on "my tickets" page.

Compare: https://eventyay.com/my-tickets/past

![screenshot from 2019-01-26 10-51-13](https://user-images.githubusercontent.com/1583873/51785464-69f4cb80-2158-11e9-9f8a-4fd8df010657.png)

**Comment by shubham3211** [comment]
I am working on this issue.

**Comment by shubham3211** [comment]
@mariobehling past events tickets are visible on Past Events.

**Comment by CosmicCoder96** [comment]
Fixed, was a legacy data format issue.
