### ISSUE TITLE
Users who placed a ticket, but not finalized the process are shown the ticket payment page at the start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1982]
If a users starts the process to buy a ticket but then does not finalize buying it, the start page suddenly shows the "placed" order on the main page, e.g. https://eventyay.com.

![screenshot from 2019-01-26 19-24-48](https://user-images.githubusercontent.com/1583873/51791257-71d85e00-21a0-11e9-8a31-584e4c1a39c0.png)

**Comment by mariobehling** [comment]
Actually the bug exists on most pages. Suddenly the form appears on all kinds of pages.

![screenshot from 2019-01-26 19-30-35](https://user-images.githubusercontent.com/1583873/51791287-00e57600-21a1-11e9-9552-b70909201a09.png)

**Comment by CosmicCoder96** [comment]
@mariobehling Seems like a browser bug, maybe too many redirects in a short span while testing, can't reproduce it.
