### ISSUE TITLE
Non Accepted sessions showing in event scheduler

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#1985]
**Describe the bug**

If an organiser begins to start scheduling his unscheduled sessions, he/she can see "pending" and "rejected" sessions showing up in unscheduled sessions as well.

**To Reproduce**
1. Go to Manage events
2. Chose your event
3. Go to scheduler

**Expected behavior**

Only accepted sessions should've been listed in the Unscheduled sessions to avoid confusion
**Screenshots**

**The Unscheduled Sessions :**
![unscheduledsessions](https://user-images.githubusercontent.com/21087061/51792674-b1bc3700-21da-11e9-95c0-520b059680d2.png)
**The actual confirmed sessions:**
![acceptedones](https://user-images.githubusercontent.com/21087061/51792691-e16b3f00-21da-11e9-8a47-73fe08a56e77.png)

As you may have already noticed, **diff sess** and **track REcord** aren't valid sessions. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] 71.0.3578.98

**Comment by jaynilshah** [comment]
@mariobehling @uds5501  working on it

**Comment by jaynilshah** [comment]
@uds5501 Should the confirmed  and accepted unsheduled sessions both be shown or just the accepted ones?
