### ISSUE TITLE
Completed Ticket Page shows original ticket price instead of actual paid ticket price, e.g. when using a discount code

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1987]
The Completed Ticket Page shows original ticket price instead of actual paid ticket price, e.g. when using a discount code.

Compare: https://eventyay.com/events/3689bc98/tickets/attendees/completed

![screenshot from 2019-01-26 22-19-53](https://user-images.githubusercontent.com/1583873/51792922-a0623300-21b8-11e9-9487-4ce79ebad180.png)

**Comment by akshaygupta533** [comment]
I would like to work on this.

**Comment by harsh-jindal** [comment]
@akshaygupta533 Are you working on this?

**Comment by akshaygupta533** [comment]
Completely forgot about this. You can take it up if you want.

**Comment by harsh-jindal** [comment]
@Anupam-dagar You can take up this issue.
