### ISSUE TITLE
Do Not Require New User to Confirm Email to buy a ticket

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1988]
When new users get a ticket, do not require to verify the account. Expected behavior: Users go to ticket page (e.g. discount ticket page), they are signing up and after the sign up process are redirected to the ticket page (e.g. discount ticket page). There should not be a requirement to confirm the account by email.

(Of course it would be better the user is just automatically signed up when they buy the ticket. Then they get a confirmation email after they bought the ticket with a link to "set a password". My understanding is, that this is difficult to make quickly. So, the above would be the best short term solution.)

**Comment by CosmicCoder96** [comment]
Will not be required after #1994 is resolved.
