### ISSUE TITLE
Public Event Page: If user chooses "All rights reserved" broken image shows up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1991]
Public Event Page: If user chooses "All rights reserved" broken image shows up on the public page.

![screenshot from 2019-01-27 06-16-05](https://user-images.githubusercontent.com/1583873/51796923-2606d280-21fb-11e9-89c8-c6b851ceec70.png)

**Comment by uds5501** [comment]
@mariobehling Claiming this
