### ISSUE TITLE
Take out or speed up JS effects on menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1992]
Opening the user submenu is slower than on version 1. There is an effect, that is slightly slower. Please take out the effect or reduce the opening time as much as possible. We want the submenu to open as fast as possible.

![screenshot from 2019-01-27 06-27-27](https://user-images.githubusercontent.com/1583873/51797000-d1fced80-21fc-11e9-9c58-86d183fbd6ed.png)

**Comment by sk9331657** [comment]
@mariobehling  Claiming this.
