### ISSUE TITLE
Event Dashboard: Improve view of events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1993]
The new event dashboard needs some improvements (https://next.eventyay.com/events/live). Make it look more similar to the version 1 please e.g.:
* Align on top
* Make tickets and its info in one row.
* Distribute columns more efficiently

![screenshot from 2019-01-27 06-34-57](https://user-images.githubusercontent.com/1583873/51797085-eab9d300-21fd-11e9-9f17-0cf1b6941a7f.png)

**Comment by harsh-jindal** [comment]
@CosmicCoder96 I'm claiming this

**Comment by jaynilshah** [comment]
Can I work on this @CosmicCoder96 
Are you working on this @harsh-jindal ?

**Comment by harsh-jindal** [comment]
Yes @jaynilshah Im almost done with it.Will be making a PR soon.
