### ISSUE TITLE
Frontend: Implement Ticketing Process as in Eventyay Version 1

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1994]
In Eventyay V1 and Eventbrite users can get tickets without logging in. If they already enter their email and pay through a registered way (e.g. credit card, paypal), they don't have to login. New users will automatically receive an email after they buy a ticket. In that email is the account information. Existing users will have their ticket automatically added to their account even if they did not log in. 

Please research the process on Eventyay V1 and Eventbrite and change the process in Eventyay version 2 accordingly.

**Comment by CosmicCoder96** [comment]
Corresponding server issue: https://github.com/fossasia/open-event-server/issues/5546

**Comment by CosmicCoder96** [comment]
Will be handled in three phases:
- Phase 1: Make frontend ready for accepting non-registered users as buyers (#2000)
- Phase 2: Handle users who are already registered but are not logged in. (#2001)
- Phase 3: Implement a captcha based verification to secure the frontend when a non-verified user is trying to create an order. (#2002)

**Comment by mariobehling** [comment]
Currently implemented in a good way. Therefore closing this.
