### ISSUE TITLE
node_modules appears empty, you may need to run `yarn install`

### ISSUE THREAD

**Issue by imrrahul** [fossasia/open-event-frontend#1995]
**Describe the bug**
I have a query regarding the installation of fossasia event -frontend installation in local machine , I am getting an error whenever i run the command  "ember serve"
that node_modules appears empty, you may need to run `yarn install`. Please help.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser chrome

**Additional context**

**Comment by CosmicCoder96** [comment]
It's already mentioned in the installation docs.
