### ISSUE TITLE
Update of Address in Terms page

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-frontend#1996]
**Describe the bug**
Currently the address is outdated on the terms page.
```
FOSSASIA is located at:

FOSSASIA
Xoai Building
93 Mau Than Street
Xuan Khan, Ninh Kieu
920000 Can Tho
Vietnam
```
**Expected behavior**
To update to the address as stated at bottom of  https://fossasia.org/

**Comment by creyente1897** [comment]
@cweitat claiming this

**Comment by creyente1897** [comment]
@cweitat claiming this

**Comment by rajshah9914** [comment]
@cweitat , progress?? I would like to contribute to this issue and send a PR soon..

**Comment by cweitat** [comment]
@creyente1897 are you done? else @rajshah9914 will do this

**Comment by rajshah9914** [comment]
Do I need to change address at all locations, like on home page, terms and conditions , privacy policies and so..and I also would like to ask that these features only open on the hosted site, but not on the local host. No footer in the local host that is present on the actual site.
![localhost](https://user-images.githubusercontent.com/34474021/51889830-9579ef00-23c0-11e9-8efa-9775ca84893d.png)
![hosted](https://user-images.githubusercontent.com/34474021/51889831-9579ef00-23c0-11e9-989f-23fe653c9f02.png)
Please clear, do I need to make the whole footer block??

**Comment by mohitm15** [comment]
@creyente1897 I would like to take this issue??

**Comment by mohitm15** [comment]
@creyente1897  need to change with this one attached in this picture?? http://server.myspace-shack.com/d23/d23236b0-44ed-4401-b31b-c0d491b5cff8.png  .
:blush: Just wanted to conform..

**Comment by mohitm15** [comment]
Also it will be more helpful to specify the terms page elaborately??

**Comment by mohitm15** [comment]
I had inspected the bug but unable to find the HTML file of term on the repository.

**Comment by CosmicCoder96** [comment]
@mohitm15 It's just data entry in the admin section. However this issue is not relevant right now, because nextgen is not live yet, administrators will enter it when it is, hence the issue has been labeled later, I will be claiming it to prevent further confusion.

**Comment by mohitm15** [comment]
@mohitm15 Actually I am new to open source...and didn't find any good first issue? It will be good if you suggest to me :grey_exclamation:

**Comment by CosmicCoder96** [comment]
@mohitm15 https://github.com/fossasia/open-event-frontend/labels/bug

**Comment by mohitm15** [comment]
@CosmicCoder96 Okay I will find and thank you :smile:

**Comment by mohitm15** [comment]
@cweitat Can I now work on it. Clarify where to change the address.
![Screenshot from 2019-03-26 23-03-37](https://user-images.githubusercontent.com/35539313/55019659-58765580-501b-11e9-9952-55bdb1d3431f.png)
Please confirm this and direct me about the html file. I didn't found it on open event frontend
