### ISSUE TITLE
Phase 1: Order flow: Make frontend ready for accepting non registered users as buyers

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2000]
- Modify the pop up asking non-logged in users to log in or sign up, to instead ask for an email.
- Functionality to handle pre-registered users who are simply not logged in will be handled in a separate issue. (#2001)
- Enable order now button for unverified users.
- Generate a random password, and along with the entered user create a new user on the server.
- Fetch user id from the server, and authenticate the session with him.
- Post successful authentication, persist the session with the new user itself.
- Ensure, that after persisting the current user in the session, the initial session which is about to get invalidated does not cause the app to redirect new user to home page. Keep him on the order page itself.
- Move the `placeOrder` action into the controller of the route where all the controlling logic *should* reside.
**Parent issue:** #1994

**Comment by shreyanshdwivedi** [comment]
Please let me know, if I can help you with this. It will be a ood learning opportunity :)

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi Sure :), this requires a lot of testing, definitely their will be bugs you can follow up on.
