### ISSUE TITLE
Organizer Session Page: "Send With Email" - provide preview pop before sending

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2008]
The option to send an update to the speaker (accepted, rejected) sends an email directly to the speaker without the organizer having an option to review the email that gets send. Please provide an option to edit the system email before sending.

**Comment by Anupam-dagar** [comment]
I would like to work on this issue.

**Comment by mohitm15** [comment]
@Anupam-dagar should I worked on it

**Comment by mariobehling** [comment]
Closing this in favor of https://github.com/fossasia/open-event-frontend/issues/4604.
