### ISSUE TITLE
Deleted events tickets are visible on my-tickets/upcoming

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2012]
**Describe the bug**
Deleted events tickets are visible on my-tickets/upcoming

**Expected behavior**
Deleted events tickets should be visible  on my-tickets/past

**Screenshots**
![deletedevents](https://user-images.githubusercontent.com/19900978/51862273-47cf9900-2364-11e9-931f-e3457a9adffc.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mariobehling** [comment]
Deleted event tickets should not be visible by the user anymore as they are - deleted.
