### ISSUE TITLE
Event sub-topic showing character reference on the create event page.

### ISSUE THREAD

**Issue by creyente1897** [fossasia/open-event-frontend#2022]
**Describe the bug**
Event sub-topic showing &amp; which is a character reference for Startups & Small Business on the create event page.

**To Reproduce**
1. Go to 'Create Event Page'
2. Scroll down to 'Event Topic'
3. Click on 'Business & Professional'
4. Scroll down to 'Event Sub-topic'
5. Click on 'Startups & Small Business'
6. See error

**Expected behavior**
Should show as Startups & Small Business instead of Startups &amp; Small Business
**Screenshots**
![image](https://user-images.githubusercontent.com/33548141/51928743-9d677c80-241c-11e9-9d58-394ec581b628.png)

**This issue is open for anyone who wants to work on it**

**Comment by pranav1698** [comment]
@creyente1897 issue is valid, you can start working on it

**Comment by creyente1897** [comment]
@pranav1698 Sir this issue is open for anyone who wants to work on it

**Comment by rajshah9914** [comment]
I would like to work on this..

**Comment by creyente1897** [comment]
@rajshah9914 Go ahead

**Comment by rajshah9914** [comment]
The code changes are possible in server side .. I have made the changes , now how should I submit PR here on frontend side if changes are present on open-event server code..@creyente1897 , @pranav1698 , can you guide me at this point....

**Comment by pranav1698** [comment]
Well, if you are getting the results for the required changes, you can open a PR here
Mentors and other contributions will review and give their comments

**Comment by rajshah9914** [comment]
Ok, Thanks @pranav1698 ..

**Comment by creyente1897** [comment]
@rajshah9914  have you made the pr

**Comment by rajshah9914** [comment]
@creyente1897 Not yet, but about to make one..

**Comment by creyente1897** [comment]
@rajshah9914 can you please make a pr soon or else someone else can do this.

**Comment by rajshah9914** [comment]
@creyente1897 , sorry for delays, but my code runs and shows unexpected error due to which I am not able to move ahead.. Even I am not able to login into my account there..if you can help, that would be great..
![screenshot from 2019-02-05 13-39-22](https://user-images.githubusercontent.com/34474021/52260334-bc4d9d80-294b-11e9-9cab-ec43892ab7fc.png)
This all happened after I fetched and merged my code after some lagging commits as shown on my repo. Even I tried to set up the whole codebase again, but error was the same.

**Comment by creyente1897** [comment]
@rajshah9914 can you tell me the changes that you did.

**Comment by shreyanshdwivedi** [comment]
As this issue is inactive for a week, I am working on it :)
