### ISSUE TITLE
Additional session dropdown fields displaying no options

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2023]
**Describe the bug**

Any extra field asked for a new session results in a `No results found` given that the field type is drop-down.
**To Reproduce**
1. Add any drop-down type field in customize registration form
2. Now go to Create Session from event management
3. Scroll down to the new drop-down field

**Expected behavior**

Any new drop-down should be returning a list of valid options.

**Screenshots**

The Drop down options:  
![sessionerror](https://user-images.githubusercontent.com/21087061/51933560-97c36400-2427-11e9-83ce-ab22a224f098.png)
The customized registration: 
![sessionsettings](https://user-images.githubusercontent.com/21087061/51933597-a9a50700-2427-11e9-902c-0c285505a417.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Google Chrome 
 - Version [e.g. 22]  71.0.3578.98

**Additional context**

Open for all

**Comment by ritikamotwani** [comment]
I am working on this issue.
