### ISSUE TITLE
Fix bug in image in events sponsors in overview

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2036]
**Describe the bug**
When you save a sponsor without logo no default logo is shown. 
**To Reproduce**
1. Go to 'Overview'
3. Scroll down to 'Event sponsors'

**Expected behavior**

When you save a sponsor without logo a default logo should be shown. 
**Screenshots**

![screenshot 2019-01-31 at 1 07 09 am](https://user-images.githubusercontent.com/31013104/52007870-716bfa00-24f5-11e9-9c8d-067a5d9325d1.png)

**Additional context**

I'm working on this.

**Comment by Anupam-dagar** [comment]
@harsh-jindal I would like to work on it.

**Comment by harsh-jindal** [comment]
@Anupam-dagar I'm working on this.
