### ISSUE TITLE
Cancelled orders do not show up under Cancelled tab in Orders tab of tickets

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2037]
**Describe the bug**

Cancelled orders do not show up under Cancelled tab in Orders tab of tickets
**To Reproduce**
1. Go to 'Tickets'
2. Click on 'Orders'
3. Scroll down to 'Cancelled Orders'

**Expected behavior**

Cancelled orders should show up under Cancelled tab in Orders tab of tickets
**Screenshots**

**Additional context**

I'm working on this.

**Comment by uds5501** [comment]
Can I have a look @harsh-jindal ?

**Comment by harsh-jindal** [comment]
@uds5501 I'm working on it.
