### ISSUE TITLE
Report feedback on new orders flow for non registered users

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2047]
Phase 1, 2 of restructuring the orders flow which allows non logged in users to place an order is now complete, please report any feedback and bugs related to that in this thread.

Test link: https://next.eventyay.com

Parent issue #1994 

The discussions on Phase 1 and Phase 2 can be found at #2000, #2001

**Comment by CosmicCoder96** [comment]
Please refrain from opening new issues related to order flow, and discuss them in this thread first.

Also, if you run out e-mails while testing emails, for convenience you can get unlimited email inboxes at https://temp-mail.org/

**Comment by uds5501** [comment]
@CosmicCoder96 One query, does the new workflow involve automatic registration of a new user upon buying ticket anonymously?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I noticed that the buyer's info is not being saved. Even the purchase time of event is not being rendered on frontend. If this is a bug, I will like to solve this
![screenshot_2019-02-12 all orders tickets apk19 events open event 1](https://user-images.githubusercontent.com/25428397/52655671-b858e700-2f1a-11e9-8bcc-a76818d734a7.png)

**Comment by uds5501** [comment]
@shreyanshdwivedi True, the completion-time is not being saved at all. (the database is not storing it at least) Please see if the order schema has included it.

**Comment by shreyanshdwivedi** [comment]
The `order` schema has these fields. I'll open an issue and start working on this
```
completed_at = fields.DateTime(dump_only=True)
created_at = fields.DateTime(dump_only=True)
```

**Comment by uds5501** [comment]
@shreyanshdwivedi I've had a word regarding this with @CosmicCoder96 before. Can you try completing a payment via PayPal maybe?

**Comment by shreyanshdwivedi** [comment]
Are you already working on this? Actually implementing payment part will require a lot of time and my mid sem exams are near, so it'll be difficult for me to invest time in it :sweat_smile:

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96  When someone orders a ticket and keeps `Enable Billing` unchecked it shouldn't display on the `Completed Order` page

![screenshot_2019-02-18 completed order -9ef780d3-b26d-4b16-bbf0-af5d71eaada8 orders open event](https://user-images.githubusercontent.com/25428397/52917592-5bdb3a80-3313-11e9-914f-4517033b60ea.png)

`Billing Info` must be hidden in this case. I think this involves backend as the tickets can be viewed later too, so handling in real time will not be a good option.

**Comment by uds5501** [comment]
@shreyanshdwivedi if we could use the backend in this, that'd be a great help. Even I need this enable billing information in the redesigning of the order pages. 
ATM, it is just a component property, which I can't manipulate from another form. It would be lovely if it were a more accessible attribute.

**Comment by shreyanshdwivedi** [comment]
Ah, I found out the comment in which @CosmicCoder96 already mentioned this issue. https://github.com/fossasia/open-event-frontend/pull/2182#pullrequestreview-201943077

@CosmicCoder96 can I proceed by adding `isBillingEnabled` to the backend?
