### ISSUE TITLE
Add Order section of tickets not parsing correct currency

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2048]
**Describe the bug**

The add order of the ticket section is not parsing the correct currency in which the event has been set up

**To Reproduce**
1. Go to a event with currency setup other than USD
2. Click on Add Order
3. See error

**Expected behavior**

They should parse the currency correctly. In this case, the currency symbol must have been INR

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/52045645-f9d8b200-256a-11e9-9b4b-df23e69327ff.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04LTS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Open for all

**Comment by jaynilshah** [comment]
modifying it
@uds5501
