### ISSUE TITLE
Event sessions not showing confirmed sessions

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2053]
**Describe the bug**

The Sessions tab in an event is not showing the `confirmed` status events.

**To Reproduce**
1. Go to any event
2. Click on Sessions'
3. See error

**Expected behavior**

Currently `accepted` state sessions are been showed in the Sessions tab, it should be changed to show `confirmed` events instead

**Screenshots**

![accepted](https://user-images.githubusercontent.com/21087061/52053287-fc450700-257e-11e9-9d69-9cdbe672ec6e.png)

![actual](https://user-images.githubusercontent.com/21087061/52053320-0f57d700-257f-11e9-830c-9c71c4071334.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome
**Additional context**

working on this issue

**Comment by Puranjay25** [comment]
I am new to this repo. Can you help me out with one issue. 
I am not getting the list of events . Rather it's showing that "Ther are no upcoming events".
So where can I see the events like "It's complicated" one

**Comment by Puranjay25** [comment]
@uds5501

**Comment by uds5501** [comment]
@Puranjay25 I guess you should try and look out for another issue because this one has already a PR which means it has been worked upon.

Besides, for your query, you can get the list of events in "Manage Events" section and browse through the tabs to see your event (if you have created one)

Or you can go to the admin/events and see the events there

**Comment by Puranjay25** [comment]
How to reach to admin page? Means how to access that?
