### ISSUE TITLE
Verification Email not sent

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/open-event-frontend#2054]
**Describe the bug**

When  a new user is registered a verification email is not being send.

**Expected behavior**

A verification email should be sent to the email id.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CosmicCoder96** [comment]
If you set up the server locally, then you need to use your own SMTP server settings for sending out the e-mail.
The mailing works on the production deployment at https://next.eventyay.com
