### ISSUE TITLE
In create session if required field is not filled, then scroll to that field

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2058]
**Describe the bug**
In create session if  track is not filled, then there is no scroll

**Screenshots**
![track](https://user-images.githubusercontent.com/19900978/52055032-411f6c80-2584-11e9-894c-19a7355d67ef.gif)

**Additional context**
I am working on this issue.

**Comment by Puranjay25** [comment]
@shubham3211  I am new to this repo. In localhost I am not able to view these event details as the "browse events" section is not showing any events in my localhost.
Can you help me with this?

**Comment by shubham3211** [comment]
@Puranjay25  I have created the event locally.

**Comment by Anupam-dagar** [comment]
@shubham3211 for me, a loader appears which keeps on loading with a error message "oops something went wrong"

**Comment by kushthedude** [comment]
@CosmicCoder96 I would like to solve it please assign me
