### ISSUE TITLE
Add ui for admin/content/system-images

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#207]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add ui for system-images in admin/content route.
![screenshot from 2017-06-10 18-45-17](https://user-images.githubusercontent.com/12807846/27003043-f699d4b6-4e0c-11e7-9c6d-0e6a0923f560.png)

- Located at `admin/content/system-images`
- Every category has sub categories. 
- When the any category is clicked, show all the subcategories with the images on right panel.

**Comment by sumedh123** [comment]
@geekyd Please assign.

**Comment by sumedh123** [comment]
@niranjan94 Would the left side rail be dependent on api?

**Comment by niranjan94** [comment]
Use the data from the internal dictionary for now

**Comment by sumedh123** [comment]
@niranjan94 I haven't changed the wizard/basic-details-step file. Still it is failing my tests

**Comment by niranjan94** [comment]
Added comment on PR.
