### ISSUE TITLE
Email not shown when buying multiple tickets.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2070]
**Describe the bug**

When multiple tickets are bought, only one of them shows the email used to buy the ticket.

**To Reproduce**
1. Buy more than 1 ticket.
2. Go to tickets of the event.
3. See the missing email in the ticket.

**Expected behavior**

It should show the email of the user who booked the ticket.
**Screenshots**

![all - attendees - tickets - test - events - open event 01-02-2019 01-14-58](https://user-images.githubusercontent.com/21174572/52080871-d8091a80-25be-11e9-8360-1f14256e4259.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Gnome 16.04
 - Browser google chrome
 - Version 71.0.3578.98

**Additional context**

This issue is open to be worked upon

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar I'm unable to reproduce it 
![screenshot_2019-02-01 all attendees tickets apk19 events open event](https://user-images.githubusercontent.com/25428397/52082649-61bae700-25c3-11e9-91a0-f44d5bdef62e.png)

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar I'm unable to reproduce it. Can someone else please verify this?
![screenshot_2019-02-01 all attendees tickets apk19 events open event 1](https://user-images.githubusercontent.com/25428397/52082879-f887a380-25c3-11e9-9357-1d8a61af40d4.png)
