### ISSUE TITLE
Sales tab in Admin panel showing wrong tickets info

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#2073]
**Describe the bug**
Sales tab shows dummy tickets info in admin panel.

**To Reproduce**
1. Go to 'Admin panel'
2. Click on 'Sales tab'
3. See error

**Additional context**
Working on this issue

**Comment by uds5501** [comment]
@mrsaicharan1 I guess it's a part of the issue #696 , this issue should probably be closed in favour of that one? @CosmicCoder96

**Comment by uds5501** [comment]
@CosmicCoder96 @mrsaicharan1 
It doesn't show any dummy data anymore 
![image](https://user-images.githubusercontent.com/21087061/53113197-05fed080-3567-11e9-8d64-09ec8d8aed48.png)

**Comment by mrsaicharan1** [comment]
In which PR was it solved again?

**Comment by uds5501** [comment]
@mrsaicharan1 Probably one of the recent integrations by @YogeshSharma0201

**Comment by kushthedude** [comment]
@mrsaicharan1 I think its resolved you may close it
