### ISSUE TITLE
Date not visible properly

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2074]
**Describe the bug**
Date not visible properly

**Expected behavior**
Date should be visible properly

**Screenshots**
![date](https://user-images.githubusercontent.com/19900978/52085721-30deb000-25cb-11e9-877e-8ca9deaa5204.png)

**Additional context**
I am working on it

**Comment by mohitm15** [comment]
I Want  to work on this Issue

**Comment by shubham3211** [comment]
@mohitm15 go ahead , the date and time should appear in one line.

**Comment by Anupam-dagar** [comment]
I would like to work on this issue.
