### ISSUE TITLE
Not able to set event start time

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2077]
**Describe the bug**

When creating a new event and filling up start time, the time doesn't set properly. For example a time of 09:35 is not being set instead 00:35 is getting set.
**To Reproduce**
1. Go to event creation page
2. set start time to hours and minutes
3. you will see hours get reset

**Expected behavior**

The time should be set properly
**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21174572/52103775-6dcb9680-260d-11e9-91e0-fe0c4dae279b.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I would like to work on this issue

**Comment by kushthedude** [comment]
@Anupam-dagar Can i work on this?

**Comment by Anupam-dagar** [comment]
@kushthedude sure

**Comment by shreyanshdwivedi** [comment]
Working on this

**Comment by kushthedude** [comment]
@shreyanshdwivedi Can i reclaim it?

**Comment by shreyanshdwivedi** [comment]
@kushthedude sure. Go ahead

**Comment by kushthedude** [comment]
Working on it.

**Comment by prateekj117** [comment]
@kushthedude Taking this over due to inactiveness.

**Comment by kushthedude** [comment]
@prateekj117 go on

**Comment by iamareebjamal** [comment]
@prateekj117 What's the status? Please take on one issue at a time and complete it in one day at max

**Comment by prateekj117** [comment]
@iamareebjamal Was not able to solve this one. Couldn't find what the problem was exactly. Anyone else is free to take this one up.

**Comment by kushthedude** [comment]
@iamareebjamal @CosmicCoder96 I have had a quick tweak for the above issue #2387  , Which could fix it thereafter only , As the error is in `Ember-UI-Time-Selector` , For the period until we find a proper solution we can use it .

**Comment by CosmicCoder96** [comment]
Fixed after removing validations.

**Comment by prateekj117** [comment]
@CosmicCoder96 @kushthedude I am still facing this issue.

**Comment by kushthedude** [comment]
@CosmicCoder96 The following error was not due to the validations, It was the error in our `UI Time Selector` which is not yet optimized for the Time, As the `end` attribute which we are using in `Time Picker` makes it set Hours to `00` again, We can have two options here -: 
- `Remove the End Validator in Time Selector Widget` 
- `Use different Time Selector for our webapp`

**Comment by kushthedude** [comment]
@niranjan94 Can you please have a look here too ?

**Comment by mrsaicharan1** [comment]
@Anupam-dagar This is functional now. I can confirm this.

**Comment by kushthedude** [comment]
@mrsaicharan1 Please try this on event wizard step-1.

**Comment by kushthedude** [comment]
Still, present in the `Event Wizard`
