### ISSUE TITLE
No Tax Information being shown on public tickets

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2082]
**Describe the bug**

Even after setting up tax information for an event, we can't see it being shown up on the event's ticket page or anywhere later in ticket process.

**To Reproduce**
1. Set taxes in an event
2. Go to event page
3. Scroll down to Tickets

**Expected behavior**

A separate Tax Information must be shown which shows the tax rate and related information

**Screenshots**

![taxinfo](https://user-images.githubusercontent.com/21087061/52135319-8a96b700-266b-11e9-80f3-f33fa3bcb95a.png)
![ticketwithouttax](https://user-images.githubusercontent.com/21087061/52135327-908c9800-266b-11e9-9d98-c392eda61e72.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Can be worked upon by anyone

**Comment by Anupam-dagar** [comment]
I would like to take up this issue

**Comment by uds5501** [comment]
@Anupam-dagar Sure, go ahead

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar are you working on this? If you are busy somewhere else, I would like to take this up

**Comment by Anupam-dagar** [comment]
Yes I am working on this. I'll submit a PR in an hour.

**Comment by prateekj117** [comment]
@CosmicCoder96 @mrsaicharan1 I would like to take this up.

**Comment by uds5501** [comment]
@prateekj117 actually I was looking into it, if I require any help, will let you know!

**Comment by uds5501** [comment]
@mariobehling , this is how they are handling it on their public ticket page
![image](https://user-images.githubusercontent.com/21087061/58930434-fa7f9000-8778-11e9-84fd-664fa27eb742.png)

and this is how checkout is handled
![image](https://user-images.githubusercontent.com/21087061/58930485-3dd9fe80-8779-11e9-887b-24e517001dd2.png)

I will redesign both in our project and push the new pr accordingly

**Comment by uds5501** [comment]
This is how Eventbrite is handling it on their public ticket page, will be implementing this in a new PR
![image](https://user-images.githubusercontent.com/21087061/58930434-fa7f9000-8778-11e9-84fd-664fa27eb742.png)

**Comment by uds5501** [comment]
Labelling later because current PR implementation takes extra network request. Will discuss it with @CosmicCoder96 and then work further on it.

**Comment by mariobehling** [comment]
@uds5501 There is an additional challenge in that issue. The ticket display must show tax a) either included in the price (in the EU, many Asian countries etc.) or b) added to the tax (in the US). Users have the option to decide on the way things are displayed in the "Add Tax Information" popup. Please take this into account when implementing.

![Screenshot from 2019-06-14 09-59-23](https://user-images.githubusercontent.com/1583873/59493581-7a99aa00-8e8b-11e9-8270-4c86aebdc667.png)
