### ISSUE TITLE
Invalid date showing in Tickets

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2084]
**Describe the bug**

All the dates on the Ticket Card of Tickets/Upcoming Events are showing Invalid Date

**To Reproduce**
1. Book any ticket
2. Go to MyTickets
3. See error

**Expected behavior**

I believe the footer of the ticket card must be formatted in the following way:

`{currency_symbol}{price}/Free order#____ {Date}`

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/52145568-516c4000-2687-11e9-995f-dc581d2d7620.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

I am working on it

**Comment by uds5501** [comment]
@CosmicCoder96 @mariobehling I had a query regarding this invalid date, do we need to show the ticket completion date or the event's start date ?

**Comment by uds5501** [comment]
@niranjan94 Had a quick doubt
If we modify the order model in ember and remove the attribute `'readOnly : True'` and then add in `controllers/orders/new.js` the following lines `order.set('completedAt', moment())`.

Shouldn't that automatically connect our completed_at from server model to our frontend model?
I could use some guidance in this integration

**Comment by CosmicCoder96** [comment]
> I had a query regarding this invalid date, do we need to show the ticket completion date or the event's start date ?

Ticket Completion.

**Comment by CosmicCoder96** [comment]
An invalid date is shown only for orders who are not yet completed.
