### ISSUE TITLE
Setting NOT saved

### ISSUE THREAD

**Issue by Puranjay25** [fossasia/open-event-frontend#2097]
**Describe the bug**

When enabling tickets for event creation in admin/modules, settings are not being saved. It rather shows an error "An unexpected error has occured. Settings not saved"
**To Reproduce**
1. Go to 'admin/modules'
2. Click on 'Ticketing'
3. Click on 'Save'

**Screenshots**
![screenshot from 2019-02-03 14-35-42](https://user-images.githubusercontent.com/20750726/52174924-1b32db80-27c1-11e9-80f2-c9e4d0defb79.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by uds5501** [comment]
@Puranjay25 I can't replicate this error. It's working perfectly in my system

**Comment by Puranjay25** [comment]
@uds5501  
So for me what might be the issue?

**Comment by niranjan94** [comment]
@Puranjay25 could be something on your side. Have you setup the server correctly ? (Closing this issue for now)

**Comment by Puranjay25** [comment]
@niranjan94 yes, I did
