### ISSUE TITLE
Split admin/users into proper pages

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#210]
Should have been done in #158 . But since it got missed out, opening this.

This page should be of the form

`/admin/users` - All users
`/admin/users/active` - Active events
`/admin/users/deleted` - Deleted users

All pages should be done via [dynamic route segments](https://guides.emberjs.com/v2.13.0/routing/defining-your-routes/#toc_dynamic-segments) similar to #156

**Comment by anu-007** [comment]
I like to work on it.thanks
