### ISSUE TITLE
Cannot save the event details on editing.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2103]
**Describe the bug**

On editing the details of the event, saving details is not working. None of the `Forward`, `Draft` and `Publish` buttons are working. There are console errors.

**To Reproduce**
1. Go to edit details of event
2. Click on publish, forward or save draft button
3. Nothing happens

**Expected behavior**

The event should get saved.
**Screenshots**

![screenshot from 2019-02-04 16-30-45](https://user-images.githubusercontent.com/21174572/52204551-7c7aad80-289a-11e9-9267-5779c01c1d2f.png)

**Additional context**

**Comment by uds5501** [comment]
@Anupam-dagar Can I have a look at this?

**Comment by Anupam-dagar** [comment]
@uds5501 sure
