### ISSUE TITLE
Notify user when link is copied under Call for speakers and Share event

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2108]
**Describe the bug**

Currently as the link is copied the user is not notified.
**To Reproduce**
1. Go to 'Create event'
2. Click on 'Sessions and Speakers'
3. Scroll down to 'Call for speakers'

**Expected behavior**

Notify user when link is copied under Call for speakers and share event.
**Screenshots**

![screenshot 2019-02-04 at 11 31 38 pm](https://user-images.githubusercontent.com/31013104/52227422-7bb33d00-28d5-11e9-91ac-2a99fe3afc58.png)

**Additional context**

I'm working on it.

**Comment by shreyanshdwivedi** [comment]
@harsh-jindal I think you should extend thiss issue and notify user when event sharing link is copied too!
![screenshot_2019-02-06 open event](https://user-images.githubusercontent.com/25428397/52328475-cc31b400-2a15-11e9-9871-d1f98d0b09c6.png)

**Comment by CosmicCoder96** [comment]
@harsh-jindal yes, please don't open separate issues for each copy button.

**Comment by harsh-jindal** [comment]
@CosmicCoder96 @shreyanshdwivedi  Will make the changes for all "copy" button in this issue.

**Comment by Haider8** [comment]
@harsh-jindal can i try to fix this issue now ?

**Comment by shreyanshdwivedi** [comment]
@harsh-jindal any update?

**Comment by Haider8** [comment]
@shreyanshdwivedi can i work on this now?

**Comment by harsh-jindal** [comment]
@shreyanshdwivedi @Haider8 The issue is to add delay property for popup on click which is not possible in semantic ui. Other than that issue is fixed. I have already made a PR for it.
