### ISSUE TITLE
Twitter, linkedin links should be available on speaker image on hover.

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2115]
**Describe the solution you'd like**
Twitter, linkedin links should be available on speaker image on hover.
![speaker11](https://user-images.githubusercontent.com/19900978/52309958-b8f7f780-29c7-11e9-8269-c6cf50e4c831.png)

**Additional context**
I am working on this issue.

**Comment by CosmicCoder96** [comment]
not required for now.
