### ISSUE TITLE
Name of speaker should be available on top of popup box

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2117]
**Describe the solution you'd like**
Name of speaker should be available on top of popup box

**Describe alternatives you've considered**
![speaker05](https://user-images.githubusercontent.com/19900978/52310402-4851da80-29c9-11e9-848c-40fb1052e35a.png)

![speaker11](https://user-images.githubusercontent.com/19900978/52310413-543d9c80-29c9-11e9-9090-c091ad28e154.png)

**Additional context**
I am working on this issue.

**Comment by CosmicCoder96** [comment]
Not required.
