### ISSUE TITLE
name of social media icons should not be displayed , icons are sufficient

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2120]
**Describe the bug**
name of social media icons should not be displayed , icons are sufficient

**Screenshots**
![social-speaker](https://user-images.githubusercontent.com/19900978/52312840-2446c700-29d2-11e9-823a-3aa4c15148f4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by uds5501** [comment]
Claiming this issue

**Comment by shubham3211** [comment]
@uds5501 I am working on this issue.
