### ISSUE TITLE
The location search in explore route is changed to undefined when enter is pressed 

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2127]
**Describe the bug**

**To Reproduce**
1. Go to '/explore'
2. Enter location in 'Enter Location' search bar
3. Press Enter

**Expected behavior**

The location bar should store value searched

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25428397/52328930-529ac580-2a17-11e9-9d35-82fb1d18f595.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Mozilla
 - Version [e.g. 22] 18.04

**Additional context**

I'm working on it

**Comment by ritikamotwani** [comment]
That's because you have not substituted a google maps API key in your .env file, reopen if it also exists on next.eventyay.com
![image](https://user-images.githubusercontent.com/22127980/52330472-87108080-2a1b-11e9-9bd3-ad3bfb40f12d.png)
