### ISSUE TITLE
Twitter OAuth front end implementation

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#2140]
**Is your feature request related to a problem? Please describe.**
The Twitter login implementation has been done by Flask-Dance on the backend. Now, it needs to be linked to the frontend through an ember link/button.

**Describe the solution you'd like**
The expected implementation should be like this:
1. *Login with Twitter* button should  redirect the user to the twitter Oauth login page. `/twitter_login/twitter`
2. After logging in with your Twitter credentials, it should lead to a callback url `/twitter_login/twitter/authorized` which should be redirected to the page where normal users are redirected to upon login.

**Additional context**
@shreyanshdwivedi Can you take this up?

**Comment by shreyanshdwivedi** [comment]
Working on it :)

**Comment by uds5501** [comment]
@shreyanshdwivedi @CosmicCoder96 @mrsaicharan1  For Github OAuth we will need a client_id and client_secret credential columns in admin/settings if we are to implement the Github Login feature. Shall I open an issue for the same in this repo?

**Comment by mrsaicharan1** [comment]
Sure go ahead.

**Comment by shreyanshdwivedi** [comment]
Waiting for https://github.com/fossasia/open-event-server/pull/5580 to get merged.

**Comment by mariobehling** [comment]
Priority low: Delay
