### ISSUE TITLE
enhancement: split events/<event-id>/sessions into proper pages

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#215]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

split all the sub routes under `events/<event-id>/sessions` into proper pages using dynamic segments.

![image](https://user-images.githubusercontent.com/20153241/27014774-2d096604-4f1d-11e7-9bbd-acdc235c09ec.png)

`events/<event-id>/sessions`
`events/<event-id>/sessions/pending`
`events/<event-id>/sessions/accepted`
`events/<event-id>/sessions/confirmed`
`events/<event-id>/sessions/rejected`

All pages should be done via dynamic route segments similar to #156  , #214 .

**Comment by anu-007** [comment]
I like to work on this.

**Comment by niranjan94** [comment]
@anu-007 thanks ... But a small correction in the routes

`events/<event-id>/sessions` - All sessions
`events/<event-id>/sessions/pending`
`events/<event-id>/sessions/accepted`
`events/<event-id>/sessions/confirmed`
`events/<event-id>/sessions/rejected`

**Comment by anu-007** [comment]
@niranjan94 should I remove the current table and use ui-model-table here.
