### ISSUE TITLE
Users not visible

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2150]
**Describe the bug**
Users not visible

**Expected behavior**
users should be visible

**Screenshots**
![users](https://user-images.githubusercontent.com/19900978/52432245-fc6d7580-2b2f-11e9-98e3-c75c6770635f.png)

**Additional context**
I am working on this issue.

**Comment by uds5501** [comment]
@shubham3211 Can't replicate this issue
