### ISSUE TITLE
Adding Github Token section in Admin/Settings | System

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2153]
**Is your feature request related to a problem? Please describe.**

No, it's regarding the implementation of additional login implementations. To implement Github OAuth, we need to let the client to provide Github client id and secret.

**Describe the solution you'd like**

I would simply like addition of Github Tokens field to the System in Admin/Settings
Something like this 
![image](https://user-images.githubusercontent.com/21087061/52440606-99d2a480-2b44-11e9-8eea-244d6d1dc362.png)

**Describe alternatives you've considered**

None, to implement a github OAuth, we will need these exclusive tokens

**Additional context**

Working on it

**Comment by mariobehling** [comment]
Out of scope at the moment.
