### ISSUE TITLE
Deleted events tickets are visible

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2154]
**Describe the bug**
Deleted events tickets are visible

**Expected behavior**
Deleted events tickets should not be visible

**Screenshots**
![deletedtickets](https://user-images.githubusercontent.com/19900978/52443601-25036880-2b4c-11e9-86eb-4983091cb00a.png)

**Additional context**
I am working on this.

**Comment by uds5501** [comment]
@shubham3211 Why should they not be visible though? They signify completed transactions by a customer. If the event has been deleted, that doesn't signify that the transaction was not made for that particular ticket

**Comment by shubham3211** [comment]
@uds5501 @mariobehling said that Deleted event tickets should not be visible by the user anymore as they are - deleted.
 https://github.com/fossasia/open-event-frontend/issues/2012

**Comment by uds5501** [comment]
@shubham3211 I think he was referring to "Deleted Event Ticket" not "Deleted Event's Ticket"
Could use some clarification here @mariobehling

**Comment by shubham3211** [comment]
@uds5501 can you elaborate , "Deleted Event Ticket" not "Deleted Event's Ticket"

**Comment by CosmicCoder96** [comment]
> I think he was referring to "Deleted Event Ticket" not "Deleted Event's Ticket"

Correct.
