### ISSUE TITLE
Routes not working in user tickets

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2156]
**Describe the bug**
Upcoming Events and past events showing same events.

**Screenshots**
![peek 2019-02-08 02-05](https://user-images.githubusercontent.com/19900978/52441449-9b04d100-2b46-11e9-8b4b-5100792115f6.gif)

**Additional context**
I am working on this issue.

**Comment by uds5501** [comment]
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/21087061/52441575-0353b280-2b47-11e9-990b-7c03c73893a2.gif)
The Routes Work fine

**Comment by CosmicCoder96** [comment]
why do you have a saved events tab in your my tickets route? That tab was removed atleast a 100 commits before? Is your branch in sync?

**Comment by shubham3211** [comment]
@CosmicCoder96  it is updated.

**Comment by CosmicCoder96** [comment]
@shubham3211

![image](https://user-images.githubusercontent.com/17252805/52516391-3db37180-2c65-11e9-84b6-8cbcf1370f21.png)



![image](https://user-images.githubusercontent.com/17252805/52516390-368c6380-2c65-11e9-864d-cc4e613f1d87.png)


Quite clearly, it is **not**. How do you not see the difference in the number of tabs in the route when I explicitly pointed it out.
