### ISSUE TITLE
Admin Dashboard showing incorrect information

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2160]
**Describe the bug**

Admin dashboard is showing no 'Confirmed' Session and The number of published / draft events displayed are wrong (it is including the deleted events in the count too)

**Expected behavior**

The admin dashboard should be presenting correct information

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/52445122-40707280-2b50-11e9-95f2-a58068666543.png)

Only 4 live events : 
![image](https://user-images.githubusercontent.com/21087061/52445151-5120e880-2b50-11e9-8ae1-4823f69fed70.png)

**Additional context**

Working on this

**Comment by ritikamotwani** [comment]
@uds5501 the admin statistics end point directly gives the values for the number of different types of events and sessions. If it is incorrect open an issue in the server for it. Further the number of confirmed sessions aren't shown in v1 so leave it for now.
