### ISSUE TITLE
No option for Singup/ SignIn using Google accounts

### ISSUE THREAD

**Issue by imrrahul** [fossasia/open-event-frontend#2163]
**Is your feature request related to a problem? Please describe.**
Sometimes it is very problematic for someone to enter all login/signup credentials and very irritating for people like me , but if there is some button like singup/sign in using Google accounts , Then it will be very easy for users to login or signup.But Open event lacks this feature.
**Describe the solution you'd like**
I would advice to put a direct signup and sign in button using google authentication.
**Describe alternatives you've considered**
To provide a button through which anyone can signup and signin easily and will increase the number of  open-event users.
**Additional context**
I would like to work on this issue.

**Comment by uds5501** [comment]
@imrrahul Google OAuth is being currently integrated in the backend

**Comment by imrrahul** [comment]
@uds5501 can we add this in frontend part for user convenience?

**Comment by uds5501** [comment]
@imrrahul Best practice would be collaborating with the server implementer. If he/she agrees to hand over the frontend integration, then surely go ahead.
