### ISSUE TITLE
No events are showing

### ISSUE THREAD

**Issue by imrrahul** [fossasia/open-event-frontend#2164]
**Describe the bug**
Events are not coming , it shows '404 not found' and Oops, the page you are
looking for does not
exist

**Expected behavior**
It should show the available page which contains list of events
**Screenshots**
![screenshot from 2019-02-08 22-30-42](https://user-images.githubusercontent.com/37583853/52493482-93e6cd00-2bf1-11e9-8751-aff16a53938d.png)

 

**Additional context**
I would like to work on this issue

**Comment by CosmicCoder96** [comment]
That URL is invalid, how did you end up on it?

**Comment by uds5501** [comment]
@CosmicCoder96 It's given right there in the footer :
![image](https://user-images.githubusercontent.com/21087061/52519980-dc51c980-2c89-11e9-9c0c-40bf7777251f.png)
Also, for the matter, none of them are working

**Comment by imrrahul** [comment]
@CosmicCoder96 It is there given in the footer as siad by @uds5501  and it is also not working on https://next.eventyay.com

**Comment by ritikamotwani** [comment]
I am working o this.
