### ISSUE TITLE
Hindi language option is not working

### ISSUE THREAD

**Issue by imrrahul** [fossasia/open-event-frontend#2165]
**Describe the bug**
On selecting the user interface language of the site as hindi , then the whole content of the site is not coming up in hindi ,i.e., it is still showing texts in english.
**Expected behavior**
it should show all texts in hindi if hindi as interface/site language is selected.
**Screenshots**
![screenshot from 2019-02-08 22-37-12](https://user-images.githubusercontent.com/37583853/52493871-8e3db700-2bf2-11e9-9681-2384e6d726d6.png)

**Additional context**
I would like to work on this issue.

**Comment by CosmicCoder96** [comment]
You need to run `node scripts/l10n.js generate` to generate translation JSON files, it works on the production deployment at next.eventyay.com

**Comment by imrrahul** [comment]
@CosmicCoder96 thanks for the information
