### ISSUE TITLE
Scroll Problem

### ISSUE THREAD

**Issue by jaynilshah** [fossasia/open-event-frontend#2166]
**Describe the bug**

Clicking on any option twice scrolls the page to the bottom
**To Reproduce**
1. Click on any event
2. Click on the tickets/getting-here option twice.

![screencast from friday 08 february 2019 10_43_34 ist](https://user-images.githubusercontent.com/36128751/52494737-ba5a3780-2bf4-11e9-8c06-f4499aab6c0f.gif)

**Expected behavior**

It should stay at the selected option.

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Browser: Chrome
 

**Additional context**

working on it

**Comment by uds5501** [comment]
@jaynilshah already described in #275 please close this.
