### ISSUE TITLE
Maximum Ticket Limits not being used

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2168]
**Describe the bug**

The admin panel offers a feature of setting maximum ticket price in Admin/Settings | Ticket Fees section, at this moment it is not really being used to check whether the set value of ticket price is below the maximum bar or not.

**To Reproduce**
- Follow the GIF

**Expected behavior**

If the set value of ticket is above the maximum set value, it should be returning an error instead

**GIF**

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/21087061/52518690-950d0e00-2c74-11e9-88b4-a9ed15798c05.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Up for grabs!

**Comment by CosmicCoder96** [comment]
That's not ticket price in admin settings, it's ticket fee. That eventyay may charge from organizer in the future.
