### ISSUE TITLE
Map is not working

### ISSUE THREAD

**Issue by alphamuth** [fossasia/open-event-frontend#2171]
**Describe the bug**
Map is not working as it is very important for user to confirm the location by seeing the map above the search bar that this is the location they are searching for, but on searching the name of location nothing happens with map.It remains as it is.

**Expected behavior**
It should show the searched location on map just above the search bar.

**Screenshots**
![screenshot from 2019-02-09 21-56-38](https://user-images.githubusercontent.com/37583853/52523312-06b97c00-2cb6-11e9-80c9-2655805fe5fb.png)
**Additional context**
I would like to work on this issue.

**Comment by fliptrail** [comment]
@imrrahul Are you still on it or can I take over?

**Comment by imrrahul** [comment]
@fliptrail yes I am working on it ....

**Comment by JaiParakh** [comment]
@imrrahul can i solve this or u are still on it?

**Comment by imrrahul** [comment]
Go ahead!!

**Comment by kushthedude** [comment]
@JaiParakh Can i overtake?

**Comment by JaiParakh** [comment]
> @JaiParakh Can i overtake?

Yeah, go ahead.

**Comment by kushthedude** [comment]
Workin on it

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 How do I pass the Maps keys? I couldn't find a way to test the fix.

**Comment by kushthedude** [comment]
@mrsaicharan1 When you are getting keys for maps api you get an option to select for maps too , that key is only used for maps too in the .env file
