### ISSUE TITLE
Clicking on tags in event-card in /explore doesn't filter the events

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2172]
**Describe the bug**

In `/explore` route, the events aren't filtered when clicked on `event-type` in `event-card`.

**To Reproduce**
1. Go to `/explore`
2. Click on `event-type` in `event-card`
3. See error

**Expected behavior**

The events should filter as in the live version

**Screenshots**

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/25428397/52524974-f65ecc80-2cc8-11e9-9669-e690ba919152.gif)

In above gif `Conference`, `FamilyEducation` and `Education` are event types, which does not filter the events on click

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Mozilla

**Additional context**

Working on this

**Comment by kushthedude** [comment]
@shreyanshdwivedi Did your PR solve this issue?

**Comment by shreyanshdwivedi** [comment]
@kushthedude yep, it works fine for me. Though the mentors suggested few changes on PR and I was unable to incorporate them. Waiting for their reply. Let me tag them once more

**Comment by kushthedude** [comment]
@shreyanshdwivedi Cool.
