### ISSUE TITLE
Add Twitter, GitHub and Instagram as applications in settings

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2184]
**Is your feature request related to a problem? Please describe.**

As Twitter, GitHub and Instagram OAuth is being integrated, it is expected to have these applications to connect, in settings.

**Describe the solution you'd like**

Adding Twitter, Github and Instagram to `/settings/applications/` just like facebook

**Additional context**

Working on it

**Comment by shreyanshdwivedi** [comment]
Waiting for https://github.com/fossasia/open-event-server/pull/5600 and https://github.com/fossasia/open-event-server/pull/5590 to get merged

**Comment by kushthedude** [comment]
@CosmicCoder96 @shreyanshdwivedi Can we consider LinkedIn Oauth as LinkedIn is the most authentic platform presently ?

**Comment by mariobehling** [comment]
At the moment external services are out of scope and will not be implemented further.
