### ISSUE TITLE
Buyer info and purchase timestamp not being saved for orders

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2189]
**Describe the bug**

When ticket is ordered, the buyer's info and purchase timestamp is not being saved for orders

**To Reproduce**
1. Purchase a ticket
2. Go to `events/<identifier>/tickets/orders/all`
3. Click on `Orders`

**Expected behavior**

The buyer's name and order date should be saved

**Screenshots**

![screenshot_2019-02-12 all orders tickets apk19 events open event 1](https://user-images.githubusercontent.com/25428397/52656923-6e253500-2f1d-11e9-87c1-642c7cb1eb34.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Mozilla

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
@uds5501 Can you link the duplicate issue which you opened and explain the discussion we had regarding setting up paypal?

**Comment by uds5501** [comment]
The earlier created issue : #2084 
The discussion and yet to be triaged fix : #2128
