### ISSUE TITLE
Implement Event Revisions

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2191]
Each time an event is updated, it's past values are stored as revisions on the backend.
The number of revisions ~are~ should be accessible at the event dashboard.
![image](https://user-images.githubusercontent.com/17252805/52691372-9fdce100-2f9b-11e9-89dd-5cbfed34ddd9.png)

Upon clicking them, a popup appears which allows browsing of event at various stages.

![image](https://user-images.githubusercontent.com/17252805/52691417-bbe08280-2f9b-11e9-8ae1-6c1b7a6e407f.png)
![image](https://user-images.githubusercontent.com/17252805/52691434-c569ea80-2f9b-11e9-86e6-a5e443a181c3.png)

**Comment by uds5501** [comment]
@CosmicCoder96 How are we planning to store the version data?

**Comment by mariobehling** [comment]
Let's define this out of scope for now. Therefore closing it.
