### ISSUE TITLE
Create UI for events revision dialog

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2192]
![image](https://user-images.githubusercontent.com/17252805/52691192-0281ad00-2f9b-11e9-806c-b9ac4c6f904a.png)

It should be a modal, as on legacy which should open up on clicking.
**This issue's scope is just the UI of the modal.**

Parent issue #2191

**Comment by ritikamotwani** [comment]
I would like to work on this.

**Comment by Anupam-dagar** [comment]
@ritikamotwani can I work on this issue?
