### ISSUE TITLE
Discount Codes' time frame not being considered while applying it

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2194]
**Describe the bug**

ATM, any discount code's validity time frame is not being considered while applying it. In short, if my discount code is valid from 24 Feb to 2 March '19, I can still manage to apply it on 14 Feb.

**To Reproduce**
1. Setup a discount code with a time frame
2. Go to the tickets
3. Apply Promocode

**Expected behavior**

Any out of time-frame discount code should not be valid.

**Screenshots**

![give](https://user-images.githubusercontent.com/21087061/52749539-81b0c880-300f-11e9-8848-87127de59da7.png)
![validfrom](https://user-images.githubusercontent.com/21087061/52749540-81b0c880-300f-11e9-8f65-cd5b66c48701.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Looking into it

**Comment by CosmicCoder96** [comment]
Can you also open an issue on the server for this, the server should deny it too.

**Comment by uds5501** [comment]
@CosmicCoder96 Doing so

**Comment by uds5501** [comment]
Closing this in favor of fossasia/open-event-server#5611
