### ISSUE TITLE
Unregistered users should be given an appropriate error during login 

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#2195]
**Describe the bug**
When we try to login with an unregistered email, it throws an error saying that the credentials are incorrect. 

**To Reproduce**
1. Go to 'Login'
2. Put in a new email address and password
3. See error

**Expected behavior**

It should throw an error saying that there is no user registered like that.

**Comment by uds5501** [comment]
@mrsaicharan1 Is it up for grabs or are you working on this?

**Comment by mrsaicharan1** [comment]
I'm working on this :)

**Comment by iamareebjamal** [comment]
No, it's by design. We should not make it easy for hackers by letting them know about the database and make their brute force attack efficient.

**Comment by iamareebjamal** [comment]
Read OWASP guidelines on how to display authentication errors
