### ISSUE TITLE
Editing discount code not possible

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2197]
**Describe the bug**

The edit discount code page is not loading properly

**Expected behavior**

It should load normally like the create discount page

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/52815087-baaa7500-30c3-11e9-9f98-c8c2b50250c5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Up for grabs!

**Comment by uds5501** [comment]
Error Trace : 
![screenshot from 2019-02-15 01-49-23](https://user-images.githubusercontent.com/21087061/52815232-27257400-30c4-11e9-9ca2-61e1d4ee3d67.png)

**Comment by neel1998** [comment]
I world like to contribute...But i am new to open source....Can someone guide ?

**Comment by CosmicCoder96** [comment]
It was caused by your PR #2102
