### ISSUE TITLE
Issue with CSS (overflow) in event public page

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-frontend#22]
![screen shot 2017-05-01 at 12 36 31 am](https://cloud.githubusercontent.com/assets/4047597/25567284/e2c4cc2c-2e07-11e7-9cb0-521d971934bc.png)

**Current behavior:**
Page at http://nextgen.eventyay.com/e/42cf5943 has issues with CSS where both the left (navigation) and right (tweets) segments overflow (no scroll) on a 1440x900p resolution.

**Expected behavior:**
Limit width of center section such as both left (navigation) and right (tweets) section are visible without overflow.

**Comment by CosmicCoder96** [comment]
@sumedh123
Please claim the issue before solving it, so someone else doesn't end up working on the same :)
