### ISSUE TITLE
Not able to enable "Donations" in admin settings.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2203]
**Describe the bug**

When trying to enable `Donations` present in `modules` of `admin` settings, `An unexpected error has occurred. Settings not saved.` error occurs.

**To Reproduce**
1. Go to `/admin/modules/`
2. Enable `Donations`
3. Click on `save`

**Expected behavior**

Donations should be enabled.

**Screenshots**

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/21174572/52918044-9a272880-3318-11e9-9c45-c230913ebec9.gif)

**Additional context**

I am working on this issue.

**Comment by uds5501** [comment]
@Anupam-dagar This is a server side error, and is related to `PATCH` request failure. @mrsaicharan1 has already opened an issue regarding the same in the server repository (see fossasia/open-event-server#5618 )

**Comment by Anupam-dagar** [comment]
Thanks for the information @uds5501 :+1:
