### ISSUE TITLE
Manage events page not responsive.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2209]
**Describe the bug**

The table present in manage events is not responsive
**To Reproduce**
1. Go to `events/live`
2. Switch to responsive mode in browser.
3. See error

**Expected behavior**

The table should be responsive so that mobile users can also see it clearly.
**Screenshots**

![screenshot from 2019-02-19 17-16-24](https://user-images.githubusercontent.com/21174572/53012954-7116ad00-346a-11e9-9536-3cdd708e814f.png)

**Additional context**

I would like to work on this issue.

**Comment by Haider8** [comment]
@Anupam-dagar Can i try to fix this issue now

**Comment by Anupam-dagar** [comment]
Hey, I am in middle of fixing it. My exams came up. Please check another
issue, I would like to complete this one.
