### ISSUE TITLE
Add UI for admin/messages

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#221]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/27055161-29b9fdb4-4fe1-11e7-8ddc-cbf7996f8f6a.png)
Located at `admin/messages`

**Comment by utkarshnath** [comment]
@CosmicCoder96 Plz assign me this
