### ISSUE TITLE
Create account gives unclear message for invalid email

### ISSUE THREAD

**Issue by divyam-goel** [fossasia/open-event-frontend#2215]
**Describe the bug**
While creating account if we enter an invalid email address then the message returned is: An unexpected error occurred. A more helpful message should be shown which helps user understand his/her mistake.

**To Reproduce**
1. Go to '.../register'
2. Enter any invalid email address and hit Register
3. See error

**Expected behavior**
A more helpful message like "Invalid Email address. Please try again with a valid email address." should be returned.

**Screenshots**
![error](https://user-images.githubusercontent.com/32808710/53182887-5c7c1580-3620-11e9-9d4f-8c42c4d804ed.png)

**Desktop:**
 - OS: Ubuntu 16.04
 - Browser chrome

**Comment by kushthedude** [comment]
I would like to take this issue. @divyam-goel

**Comment by divyam-goel** [comment]
Yeah, sure. Go ahead :)

**Comment by Anupam-dagar** [comment]
@kushthedude since there was no WIP PR opened, I took a look at this issue and opened a PR for the same.

**Comment by kushthedude** [comment]
@Anupam-dagar No problem was a bit busy due to college fest
