### ISSUE TITLE
Singapore appears twice in timezone

### ISSUE THREAD

**Issue by jaynilshah** [fossasia/open-event-frontend#2218]
**Describe the bug**

Singapore appears twice in timezone while creating event

**To Reproduce**
1. Go to Create Event
2. Timezone 

**Expected behavior**

Only once Singapore should appear

**Screenshots**

![screenshot from 2019-02-22 13-45-27](https://user-images.githubusercontent.com/36128751/53229522-6fd3c300-36aa-11e9-8d82-1cd1720198f9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
It's a standard list from the moment library, we don't want to manipulate or filter it.

**Comment by jaynilshah** [comment]
@CosmicCoder96 Both the Singapore shows the same timezone of SGT and that too +08 instead of SGT.
View this too #1829
