### ISSUE TITLE
Search in manage events page doesn't work.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2220]
**Describe the bug**

The search on manage events page doesn't work.
**To Reproduce**
1. Go to `events/live`
2. Use the search bar.
3. See the behaviour

**Expected behavior**

The search bar should work.
**Screenshots**

![screenshot from 2019-02-22 22-13-03](https://user-images.githubusercontent.com/21174572/53257064-48531980-36ef-11e9-9542-6d442ee43710.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@Anupam-dagar Can you please tell exact steps to reproduce as on my machine the search bar is working correctly?

**Comment by uds5501** [comment]
@Anupam-dagar Since this issue had not been worked on for more than 2 weeks now, can I please takeover?
