### ISSUE TITLE
Parse correct currency in tickets overview  

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2223]
**Describe the bug**
Currency in tickets overview is not parsed correctly

**To Reproduce**
1. Go to 'Overview'
3. Scroll down to 'Tickets'

**Expected behavior**

Parse correct currency in tickets overview  
**Screenshots**

![screenshot 2019-02-23 at 2 22 54 am](https://user-images.githubusercontent.com/31013104/53270531-fbcd0580-3711-11e9-95f5-4b2bb980bb6b.png)

**Additional context**

I'm working on it.

**Comment by kushthedude** [comment]
@CosmicCoder96 Is this issue still open as the PR referenced to it has been closed without getting merger?

**Comment by CosmicCoder96** [comment]
check the comments on the PR.

**Comment by shreyanshdwivedi** [comment]
@kushthedude it has been more than 20 days since you are working on this issue. Please let others know if you are not able to solve this so that someone else can take it forward

**Comment by kushthedude** [comment]
@shreyanshdwivedi I will try to check test one last time if i dont come up with some solution by today , i will let you know 👍

**Comment by CosmicCoder96** [comment]
Fixed in https://github.com/fossasia/open-event-frontend/pull/2376
