### ISSUE TITLE
deleted event sale stats are being counted in Ticket Summary

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2231]
**Describe the bug**

Looking at Admin|sales by Events Ticket summary statistics, it is takingthe deleted events ticket sales into account which shouldn't be done

**To Reproduce**
1. Go to Admin/Sales
2. Click on By Event
3. See error

**Expected behavior**

Only non deleted event stats should be taken into account

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/53287606-7c3c4680-37a4-11e9-9e55-d23a77c983bd.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04LTS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

I would like to work on it

**Comment by uds5501** [comment]
@CosmicCoder96 Could you please clarify if this is intended or not i.e. counting deleted event stats in `sales` column

**Comment by CosmicCoder96** [comment]
I believe sales are sales, they should be there in the admin dashboard, even if the organizer decides to delete the event.

**Comment by uds5501** [comment]
@CosmicCoder96 Alright, understood
