### ISSUE TITLE
Footer section recommendations

### ISSUE THREAD

**Issue by thanostx** [fossasia/open-event-frontend#2232]
**Is your feature request related to a problem? Please describe.**

No. There are mostly enhancements.

**Describe the solution you'd like**

Some of the content on footer is hardcoded on the templates and doesn't provide any context in a on-premise deployment. My proposals are:

1. Use `settings.appName` variable to replace "eventyay" text.
https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/footer-main.hbs#L5

![screenshot_2019-02-24 gnome events](https://user-images.githubusercontent.com/1238816/53297574-fdd5b800-3828-11e9-8551-9efcd013caa5.png)

2. Hide or drop the content of **"Nearby Events"** section as the URLs don't point to any page/section [1]. A more sophisticated solution here, would be to create a dynamic list based on the event locations [2].

[1] https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/footer-main.hbs#L25
[2] https://open-event-api-dev.herokuapp.com/#event-locations

![screenshot_2019-02-24 gnome events 1](https://user-images.githubusercontent.com/1238816/53297576-ff06e500-3828-11e9-96da-60fb477d7bfd.png)

3. Hide **"Connect with us"** section by default and show it only when the user adds a link.

**Comment by shreyanshdwivedi** [comment]
@thanostx can I work on this?

**Comment by thanostx** [comment]
@shreyanshdwivedi I'm not sure if I'm "authorized" to give you an approval.
But if you ask me, I didn't start working on it, so please feel free to take it.

I assume maintainers will have the last call if this enhancement worth a merge.

**Comment by CosmicCoder96** [comment]
@thanostx Thanks for reporting this issue :) 
@Anupam-dagar Please proceed.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I guess u wanted to tag me 😅

**Comment by CosmicCoder96** [comment]
yeah, sorry @shreyanshdwivedi go ahead :smile:

**Comment by Parth910** [comment]
@shreyanshdwivedi, if you are not working on it then I would like to work on it. Are you working on this?

**Comment by shreyanshdwivedi** [comment]
@Parth910 I've already made changes on my local. Fixing a few things. I'll open a PR soon

**Comment by kushthedude** [comment]
@shreyanshdwivedi Since there is no WIP Pr opened , Can i proceed with this?

**Comment by kushthedude** [comment]
@shreyanshdwivedi ??

**Comment by kushthedude** [comment]
Working on it.

**Comment by kushthedude** [comment]
@shreyanshdwivedi Can you please tell what the enhancement number second wants to state?

**Comment by shreyanshdwivedi** [comment]
@kushthedude `Nearby Events` don't show dynamic list of events. It is hard coded. This needs to be fixed

**Comment by thanostx** [comment]
Just for future reference, the second request duplicates this issue here https://github.com/fossasia/open-event-frontend/issues/1823

**Comment by kushthedude** [comment]
No issue

**Comment by kushthedude** [comment]
@CosmicCoder96 regarding the dynamic ‘Nearby Events’  , as this needs user location and a constraint on number of events to be displayed on basis on distance . Should I push a PR with only two changes ? As the featured events and event location functionality , i am planning to do it in GSOC , Or should i wait untill location functionality is implemented ?

**Comment by maze-runnar** [comment]
@kushthedude , i am stuck a bit while working on it at one place, can you please help me with any reference that how to return current city using ember-cli-geo

**Comment by mariobehling** [comment]
Closing this as the design has been changed.
