### ISSUE TITLE
Map API not working in create event and show event section.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2237]
**Describe the bug**

**To Reproduce**
1. Go to 'Create Event'
2. Click on 'Location'
3. Scroll down to 'Location characteristics'
4. Open JavaScript Console.
4. See error on the webpage and error description on console.

**Expected behaviour**
A clear pinpoint of location should be shown properly on the map in the right blank space

**Screenshots**
![](https://im.ezgif.com/tmp/ezgif-1-cc99fa156b0a.gif)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Chrome
 - Version 72.0.3626.119

**Additional context**
-There are many issue related to this in past ,I request mentors to refer them to it.
-I would like to work on it.

**Comment by kushthedude** [comment]
@CosmicCoder96 Please review this issue.

**Comment by CosmicCoder96** [comment]
While following the steps for local installation, https://github.com/fossasia/open-event-frontend/blob/development/docs/installation/local.md#steps 
.env.example is copied into .env
.env file has a placeholder variable for api key for google maps, it needs to be passed in order for the map to function.

**Comment by kushthedude** [comment]
Thanks @CosmicCoder96
