### ISSUE TITLE
Fields for username and password in mail settings could be optional

### ISSUE THREAD

**Issue by thanostx** [fossasia/open-event-frontend#2238]
**Is your feature request related to a problem? Please describe.**

At the moment frontend requires both username and password fields when setting up an email host. This is not always the case and varies among different deployments and mail server configurations.

One example is GNOME Open Event instance, https://events.gnome.org, where the underlying mail server doesn't require AUTH from the client.

**Describe the solution you'd like**

The solution that i propose is to make username and password fields optional and not a hard requirement.

**Comment by shreyanshdwivedi** [comment]
@thanostx if you are not working on this, I would like to work on it

**Comment by thanostx** [comment]
No work from my side.

Feel free to take this.

**Comment by Anupam-dagar** [comment]
Hey @shreyanshdwivedi, if you are not working on it then I would like to work on it, I got the fix for it in the codebase.

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar yeah sure. Please proceed. I'm a bit busy in a hackathon :+1:

**Comment by Anupam-dagar** [comment]
@shreyanshdwivedi Thanks :smile: All the best for your hackathon. :tada:
