### ISSUE TITLE
Make 'Enter Location' Dropdown instead of textbox.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2244]
**Is your feature request related to a problem? Please describe.**

On the index page,Enter location menu is a textbox.
My idea is if we make a dropdown of countries.

**Describe the solution you'd like**

Make a dropdown of countries instead of textbox where we need to type the name.

**Additional context**

<img width="1440" alt="screenshot 2019-03-02 at 2 01 03 pm" src="https://user-images.githubusercontent.com/44091822/53679596-6ecb1300-3cf4-11e9-80a2-39d56eed2a14.png">

**Comment by kushthedude** [comment]
@CosmicCoder96 Can you please review this enhancement?

**Comment by Anupam-dagar** [comment]
@kushthedude there is already an autocomplete for that field. You need to setup google maps api key.

**Comment by kushthedude** [comment]
Oops closing the issue.
