### ISSUE TITLE
Change default frontend url in the Mail Settings.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2246]
**Describe the bug**

The current frontend url in mail settings default to `eventyay.com`, it will be better to default it to hostname of the current hosted instance.

**To Reproduce**
1. Go to `/admin/settings`
2. Scroll down to mail settings
3. See error

**Expected behavior**

It should default to current hostname.
**Screenshots**

![screenshot from 2019-03-02 15-05-31](https://user-images.githubusercontent.com/21174572/53680177-b1ddb400-3cfd-11e9-8412-fc72ef3f4ee7.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@Anupam-dagar Can i claim this if you have not done significant amount of work for this issue ?

**Comment by Anupam-dagar** [comment]
@kushthedude I am in middle of fixing it. Please claim other issue.

**Comment by kushthedude** [comment]
Sure no problem

**Comment by kushthedude** [comment]
@Anupam-dagar , Shouldn't this issue be moved to server side?

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 is following the feasible approach:
1. Change default value of the frontend url field on the server to blank string.
2. in the frontend if the value is blank we fill it with the hostname value else the user can fill its own value.

**Comment by uds5501** [comment]
@Anupam-dagar If there is no default frontend url , the email function would break. Also, changing it to `localhost:4200` is not possible because the field validators won't allow it.

**Comment by CosmicCoder96** [comment]
we will rather handle it on the server, FE just reads from there.
