### ISSUE TITLE
Unresponsive search bar on HomePage

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2247]
**Describe the bug**

When we shrink the screen size other filter attributes of the bar disappears but 'Clear Filter' button is still there.
**To Reproduce**
1. Go to 'http://127.0.0.1:4200/'
2. Try to change the size of browser window
3. See error

**Expected behavior**

-When the screen size gets small,The clear filter button should also get disables.
-Add Other attributes too when screen size shrinks.
**Screenshots**

<img width="915" alt="screenshot 2019-03-02 at 4 53 37 pm" src="https://user-images.githubusercontent.com/44091822/53681193-eb1d2080-3d0b-11e9-803b-768bb653bfe8.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version 72.0.3626.119

**Additional context**

**Comment by kushthedude** [comment]
@CosmicCoder96 If this is a valid issue,I would like to proceed.

**Comment by CosmicCoder96** [comment]
This behavior was intentional afaik, also not a priority right now.

**Comment by kushthedude** [comment]
Cool , no problem
