### ISSUE TITLE
Add TimeZone in 'Create an Event' on GMT basis

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2248]
**Is your feature request related to a problem? Please describe.**
-When you create an event , TimeZones of different country are on alphabatical basis.
-It would be better if they are based on GMT,As every individual could search for particular timezone.
-Rather than searching for which city or his country has been included in the dropdown.

**Describe the solution you'd like**
-TimeZones should be classified on basis of GMT.

**PS: I would like to work on this enhancement.**

**Additional context**

<img width="957" alt="screenshot 2019-03-02 at 10 32 48 pm" src="https://user-images.githubusercontent.com/44091822/53685070-cf317300-3d3b-11e9-8bc1-553f77f73306.png">

**Comment by kushthedude** [comment]
@Anupam-dagar ,
Can you please let me know if this is a valid enhancement or not.

**Comment by Anupam-dagar** [comment]
CC: @CosmicCoder96

**Comment by kushthedude** [comment]
Oops😅, my mistake.

**Comment by CosmicCoder96** [comment]
yeah go ahead.

**Comment by harsh-jindal** [comment]
@kushthedude Can I work on it?

**Comment by kushthedude** [comment]
@harsh-jindal i have already solved the issue there is some build error i will open WIP after my midsem

**Comment by shreyanshdwivedi** [comment]
@kushthedude any update?

**Comment by kushthedude** [comment]
@shreyanshdwivedi I am encountering an error in exporting the package see if you could help,I made changes in date-time dictionary.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/44091822/54597149-10c05e80-4a5c-11e9-933c-316f9f7b1ccf.png">
The 9th line is giving some error in console and due to it the frontend is not opening.

**Comment by kushthedude** [comment]
@CosmicCoder96 Any fix?

**Comment by kushthedude** [comment]
@CosmicCoder96 Should i close the issue too?

**Comment by ritikamotwani** [comment]
Yes.
