### ISSUE TITLE
Implement sales amount standardisation

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2253]
**Is your feature request related to a problem? Please describe.**

In admin/sales section one can see every entry in the tables to have a default currency of 'US' dollar and when the event has a currency of something other than USD, it is simply using the amount without converting it into an appropriate equivalent of USD
examples : 
![image](https://user-images.githubusercontent.com/21087061/53723304-7eca2a80-3e8d-11e9-96ad-6fb5c9aebdfa.png)
Here both events are in INR and Australian Dollars respectively but the amount is being shown in USD without any modification

**Describe the solution you'd like**

I would like to implement a standardisation of values on server or front end level such that the event's currency is converted to `USD` automatically.

**Additional context**

I would be working on it

**Comment by kushthedude** [comment]
@uds5501 ,Isn't the issue #2225 and #2223 related to the same?

**Comment by uds5501** [comment]
@kushthedude No. not at all. they are about currency parsing. I am talking about the fact that `INR 50` != `USD 50`.

**Comment by kushthedude** [comment]
@uds5501 Sorry for my misunderstanding 😄

**Comment by kushthedude** [comment]
@uds5501 Are we good to close ?

**Comment by uds5501** [comment]
@kushthedude  I guess.
