### ISSUE TITLE
Implement search event by name in explore events.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2254]
**Is your feature request related to a problem? Please describe.**

Currently there is no option to search an event by name in event explorer at `/explore`, a user may require to search events by its name.

*Describe the solution you'd like**

Implement a search bar to search events by name.

## Screenshot
![screenshot from 2019-03-04 19-03-40](https://user-images.githubusercontent.com/21174572/53736761-b3031280-3eb0-11e9-9be5-e91ffd90c306.png)

**Additional context**

I am working on it.

**Comment by ritikamotwani** [comment]
@Anupam-dagar , the search event by name is not required in the explore route(Check v1).
But you can work on implementing the search bar for events https://github.com/fossasia/open-event-frontend/issues/1322
![image](https://user-images.githubusercontent.com/22127980/54578172-a8608580-4a39-11e9-97bd-8c96f148c31e.png)
