### ISSUE TITLE
Deleted events stays in cache until refreshed

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2259]
**Describe the bug**

-Whenever you delete an event,A tooltip appears showing event is deleted.
-Event stays in cache until the page is refreshed.
**To Reproduce**

1.)Go to '/Events/Live'
2.)Try to delete an event.
3.)Refresh the page .
4.)See error

**Expected behavior**

When a event is deleted , The page should be refreshed to remove the event from the list.
**Screenshots**

![kushprince](https://user-images.githubusercontent.com/44091822/53860658-b4931e80-4007-11e9-9403-e7bdbb9775fb.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 75.0.0.2

**Comment by CosmicCoder96** [comment]
@uds5501 can you reproduce this issue?

**Comment by uds5501** [comment]
@CosmicCoder96 Nope, it's working fine for me

**Comment by kushthedude** [comment]
No issues i will close it and will see into my machine for error.
