### ISSUE TITLE
bug : only scheduled sessions being shown in my-sessions

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2262]
**Describe the bug**

At the moment, only published events are being shown in my-sessions making it impossible for an user to access his/her other sessions.

**To Reproduce**
1. Go to My-sessions
2. See error
![image](https://user-images.githubusercontent.com/21087061/53884511-b974c400-4041-11e9-92fb-ccfa5e35640e.png)

**Expected behavior**

I am planning to add a new tab which can show user's all session proposals and rename the existing ones so that they signify the scheduled status.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubutnu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
okay what is _published_ sessions? Sessions are either accepted or rejected and can only be submitted to an event which is published?

**Comment by uds5501** [comment]
@CosmicCoder96 My bad, published was a wrong choice of word. I meant to talk about *Scheduled* sessions (The ones which have been scheduled by the organizer)

**Comment by CosmicCoder96** [comment]
@uds5501 okay, please go ahead to fix that then.

**Comment by uds5501** [comment]
@CosmicCoder96 Okay, I shall re-open a PR within a few minutes
