### ISSUE TITLE
Date not visible properly on tickets/attendees , tickets/orders page

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2265]
**Describe the bug**
Date not visible properly on tickets/attendees , tickets/orders page

**Expected behavior**
If date is invalid it should not be visible

**Screenshots**
![attendedate](https://user-images.githubusercontent.com/19900978/53926126-5702de80-40a8-11e9-966c-c1e82461f2ac.png)
![ordersata](https://user-images.githubusercontent.com/19900978/53926136-5ec28300-40a8-11e9-8bbf-d5c641738ec4.png)

**Additional context**
I am working on this issue

**Comment by CosmicCoder96** [comment]
not a date issue per se happens only on local environment because no actual payment is made, else works fine.
