### ISSUE TITLE
User events are not visible

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2270]
**Describe the bug**
User events are not visible

**To Reproduce**
![userevents](https://user-images.githubusercontent.com/19900978/53960876-5cdedb00-410d-11e9-8524-164721ccab74.gif)

**Expected behavior**
The events should be visible 

**Additional context**
I am working on it

**Comment by shubham3211** [comment]
Can someone tell if this is a valid issue ? Even if the events are visible live, draft, past won't work as there is no filter https://github.com/fossasia/open-event-frontend/blob/development/app/routes/admin/users/view/events/list.js

**Comment by CosmicCoder96** [comment]
Yes, go ahead and add them.
