### ISSUE TITLE
Add spacing between buttons and tickets in create event page.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2275]
**Describe the bug**

Currently the buttons are sticked with tickets box, the UI will be better if we can add a little space after the ticket box.

**To Reproduce**
1. Go to `/create`
2. Scroll down to `tickets`
3. See error

**Expected behavior**

There should be a space after tickets box and buttons.
**Screenshots**

![screenshot from 2019-03-08 14-21-29](https://user-images.githubusercontent.com/21174572/54017966-8e0ee800-41ad-11e9-9ab9-322ec190a0d3.png)

**Additional context**

I am working on it.

**Comment by CosmicCoder96** [comment]
Was a design choice, see discussion here:
https://github.com/fossasia/open-event-frontend/pull/756
