### ISSUE TITLE
Add an edit button in /events route

### ISSUE THREAD

**Issue by YogeshSharma0201** [fossasia/open-event-frontend#2278]
**Is your feature request related to a problem? Please describe.**
There should be an 'edit' button alongside 'delete' button
 
![Screenshot_20190310_003713](https://user-images.githubusercontent.com/21025052/54076043-ac1f3a00-42cc-11e9-94f6-8047676b9bb9.png)

**Comment by CosmicCoder96** [comment]
There is already an events overview tab available on this page, using which any step of the edit wizard can be reached. Not required.
