### ISSUE TITLE
No need of button(for mobile) "clear filters" because there is no filters in Mobile view

### ISSUE THREAD

**Issue by Parth910** [fossasia/open-event-frontend#2282]
**Screenshots**
![bug](https://user-images.githubusercontent.com/31615065/54084182-97d25000-4353-11e9-9952-82314f572ee9.png)

**Additional context**
I am working on this.

**Comment by kushthedude** [comment]
@Parth910 this is same as #2247  and its not the priority take some high priority issue right now

**Comment by Parth910** [comment]
ok

**Comment by kushthedude** [comment]
You can close the issue
