### ISSUE TITLE
Translating the website to french doesn't work

### ISSUE THREAD

**Issue by souka1** [fossasia/open-event-frontend#2284]
**Describe the bug**
translating the website to french doesn't work.

**To Reproduce**
1. Go to bottom of the page
2. Click on "english"  button
3. choose french
4. the page wouldn't be translated to french

**Comment by CosmicCoder96** [comment]
Please see discussion here : https://github.com/fossasia/open-event-frontend/issues/2165

**Comment by souka1** [comment]
> Please see discussion here : #2165

it doesn't work even when it's in the production mode.
