### ISSUE TITLE
"With Email" option hidden for first sessions

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2286]
**Describe the bug**

The "With Email" option is hiding under the table (it's the best way I can describe it, seriously) 

**To Reproduce**
1. Go to Event/Sessions
2. Click on Accept option of first session
3. See error

**Expected behavior**

It should not hide but instead overlap the search-bar

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/54092825-072d5b80-43b7-11e9-90ed-744d7cb4bb13.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari]Chrome

**Additional context**

Up for grabs!

**Comment by kushthedude** [comment]
Working on it

**Comment by ritikamotwani** [comment]
Can't reproduce the issue.
![image](https://user-images.githubusercontent.com/22127980/54579148-21ada780-4a3d-11e9-9f92-56e3b3569bd7.png)
