### ISSUE TITLE
View action linking sessions to edit route

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2293]
**Describe the bug**

View action on manage-event link is showing edit session dialogue instead of the view dialogue
**To Reproduce**
1. Go to Manage Events
2. Click on View Button
3. See error

**Expected behavior**

It should show the session details instead of this behaviour

**Screenshots**

![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/21087061/54227578-43cb9500-4526-11e9-8a02-a2e08cfb5388.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
yeah this was more or less intentional. why would an event organizer see a session under my sessions if some third user created it?
