### ISSUE TITLE
Credentials were incorrect error message

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2296]
**Is your feature request related to a problem? Please describe.**
Error message always shows credentials were incorrect no matter how many times the user enters an incorrect password.

**Describe the solution you'd like**
If the user enters an incorrect password multiple times, "Forget your password" should get highlighted.

**Additional context**
Working on it.

**Comment by mohitm15** [comment]
Should I take over this issue @prateekj117 ??

**Comment by prateekj117** [comment]
@mohitm15 No, will work on this.

**Comment by prateekj117** [comment]
@mohitm15 Go ahead.

**Comment by mohitm15** [comment]
@prateekj117 Sure

**Comment by kushthedude** [comment]
@mohitm15 If you have not made some significant progress can i please push my PR , If you dont mind ?  😅

**Comment by mohitm15** [comment]
@kushthedude NO  .. I was busy in BTP. Soon push a PR ??... Plenty of issues are there bro!! :smiling_imp: 

> @mohitm15 If you have not made some significant progress can i please push my PR , If you dont mind ?

**Comment by kushthedude** [comment]
Due to inactivity on this i solved the issue but forgot to push my branch , No problem but there are plenty of issues for you too , If you have not done work on it .

**Comment by prateekj117** [comment]
@kushthedude It's a really bad practice to work on the PR in spite of the fact that someone else has claimed the issue. It leads to a waste of time of two people working on the same issue. Plus it leads to confusion. As the issue was claimed by @mohitm15, I would suggest him to work on it.

**Comment by kushthedude** [comment]
Cool

**Comment by kushthedude** [comment]
Refer To:- https://github.com/fossasia/open-event-frontend/pull/2501#issuecomment-480705729
