### ISSUE TITLE
Remove Google + from 'Share this event' dialog

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2299]
**Describe the bug**

Google plus is shutting down in April 2019 and it is no longer available. 
**To Reproduce**
1. Go to 'Index --> Upcoming events'
2. Click on 'Share event icon' at the bottom of the event card.
3. Then click on 'google plus icon' to share event

**Screenshots**

![image](https://user-images.githubusercontent.com/43299408/54391891-3d771d80-46cc-11e9-8bc9-9f1f9029092f.png)

The above page opens up if we try to share the event on Google plus.
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I am working on it

**Comment by uds5501** [comment]
@Haider8 It's working perfectly fine for me
![image](https://user-images.githubusercontent.com/21087061/54472783-86c28c80-47f4-11e9-86fa-b97d5e1909db.png)

**Comment by Haider8** [comment]
@uds5501 Yes because you already have an account there. But since google plus will shut down on April 2, i don't think it is needed in 'share event'. What are your thoughts ?

**Comment by uds5501** [comment]
@Haider8 In that case, do remove this option :)
