### ISSUE TITLE
Add Gemnasium button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#23]
Add Gemnasium button to Readme.md

**Comment by niranjan94** [comment]
@mariobehling gatekeeper is already handling dependencies and I have found it to be much better than greenkeeper for js projects. It automatically makes PR for new updates to dependencies.

**Comment by niranjan94** [comment]
And also, with greenkeeper there is no issue of API keys or account linking. And since greenkeeper automatically makes a new PR for dependency updates, all our unit tests also run on that as usual and we can ensure that the update doesn't break anything on our side either.

**Comment by niranjan94** [comment]
Past PRs made by Greenkeeper here:
https://github.com/fossasia/open-event-frontend/pull/18
https://github.com/fossasia/open-event-frontend/pull/11
https://github.com/fossasia/open-event-frontend/pull/6
