### ISSUE TITLE
Make all the form validation variables camel case, by adding identifier attribute where missing

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#230]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently all the form validation variables are in snake case
**Expected behavior:**
They should be in camel case in accordance with the style guide.

**Comment by geekyd** [comment]
@CosmicCoder96 @niranjan94 Aren't we going to use snake case for IDs & names in the templates anymore?

**Comment by CosmicCoder96** [comment]
@geekyd The names and IDs within the templates _will_ be in snake case, this issue is for just the js files where in we have used snake case for variables as this is what the form mixin defaults to when the `identifier` attribute is missing. I will add identifier wherever it is missing so then they can be in camelCase.
