### ISSUE TITLE
Event Type,Event Topic,Event subtopic, License cannot be made null once set

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2302]
**Describe the bug**

Event Type,Event Topic,Event subtopic, License cannot be made null once set
**To Reproduce**
1. Go to 'Basic Details'
3. Scroll down to 'Event topic'

**Expected behavior**

There should be an option "none" which sets these fields to null.
**Screenshots**

![Screenshot 2019-03-15 at 6 43 09 PM](https://user-images.githubusercontent.com/31013104/54429172-5b876100-4752-11e9-9250-d4c9aea49369.png)

**Additional context**

I'm working on it.

**Comment by kushthedude** [comment]
@harsh-jindal specifying a category of event is must so there is no need to make these fields null 😄

**Comment by harsh-jindal** [comment]
@kushthedude Event Type is not a required field.

**Comment by maze-runnar** [comment]
working on it.

**Comment by iamareebjamal** [comment]
Please finalize #4942 first

**Comment by mariobehling** [comment]
Use of License of Event Data & Content on Wizard step 2 is still missing to finalize this issue.
