### ISSUE TITLE
'Confirm delete' button overlaps with the form on User Profile

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2303]
**Describe the bug**

On some screens (around tablet size) 'confirm delete' button on the user profile form overlaps with the form which should not happen

**To Reproduce**
1. Go to 'user profile page'
2. Set the width around the size of tablet
3. See error

**Screenshots**

![button-overlaps](https://user-images.githubusercontent.com/43299408/54435046-9a6ae600-4755-11e9-8c7d-31277280a606.png)

**Additional context**

Working on it

**Comment by mohitm15** [comment]
I would like to take this issue
@Haider8
