### ISSUE TITLE
No provision for organiser to restore session or speaker 

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2305]
**Is your feature request related to a problem? Please describe.**

No. It's simply a feature request to enable restoration of session and speakers on both admin and organiser levels. Besides, an organizer should also be able to see his deleted sessions and speakers but there is no such tab for the same.

**Describe the solution you'd like**

I would like to implement it similar to event restoration at admin level
![image](https://user-images.githubusercontent.com/21087061/54473223-c7250900-47fa-11e9-8df5-3953d4984869.png)

**Additional context**

I would love to work on it if it's a matter of medium or high priority

**Comment by ritikamotwani** [comment]
No, this feature is not required. As per version1, the admin can restore only the users and events.
