### ISSUE TITLE
Delete Session button opens delete event modal

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2306]
**Describe the bug**

Clicking on deleting a user's session open's delete event modal

**To Reproduce**
1. Go to your session/edit 
2. Click on Delete session
3. See error
![Screenshot from 2019-03-16 16-29-15](https://user-images.githubusercontent.com/21087061/54474302-52a59680-4809-11e9-87e4-f2feb661dbca.png)

**Expected behavior**

It should open a 'delete session' modal, if it exists.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by uds5501** [comment]
My bad. it was indeed delete event option for the organizer

**Comment by ritikamotwani** [comment]
@uds5501 , that is the delete event button. It's not for the session. Why would there be a button to delete the session while you're editing it. 
The delete session button is the the sessions table.
