### ISSUE TITLE
Cookie policy link on the landing page is broken

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2311]
**Describe the bug**

The cookie policy link (http://next.cookie-policy.eventyay.com) is broken.

**To Reproduce**
1. Go to 'landing page'.
2. Click on 'click here' link on the message shown at the top.
3. See error.

**Screenshots**
![cookie-policy-link](https://user-images.githubusercontent.com/43299408/54473266-5b8f6b80-47fb-11e9-9e88-e38a7e6587ee.png)
![broken-cookie-link](https://user-images.githubusercontent.com/43299408/54473629-52ed6400-4800-11e9-8d5d-6b33ac686455.png)

**Expected behavior**

It should have taken to the correct link, that is, https://eventyay.com/cookie-policy/

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
fixed now.
