### ISSUE TITLE
Warning to verify Email 

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2312]
**Describe the bug**
There should be a global warning after a user registers, if not global, there should be a message in the login form which comes after registering to verify the Email Id. For now, the email verification warning only shows in the user's profile. As unverified Users are not allowed to create an event, I think it should be global.

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@CosmicCoder96 Your views on this?

**Comment by kushthedude** [comment]
Global warning would look ugly on the webpage but still let the mentors decide.

**Comment by prateekj117** [comment]
@kushthedude I think it's needed as unverified users are not allowed to create an event. Rather than telling them after entering one page of information, they should have a warning already.

**Comment by CosmicCoder96** [comment]
we'll iterate on this later on. It is already displayed on relevant pages, where there is a need for the user to be verified.

**Comment by prateekj117** [comment]
@CosmicCoder96 It's not displayed on Create Event Page.

**Comment by iamareebjamal** [comment]
Simply disable the form and display "You need to verify the email before you can create the event". It'd be very annoying and unintuitive to go and fill all the information to get a message later that your email is unverified and losing all progress.

**Comment by kushthedude** [comment]
@prateekj117 Can i take this issue if you have not done significant progress in this?

**Comment by prateekj117** [comment]
@kushthedude No, working on it.
