### ISSUE TITLE
when screen is reduced to mobile or tablet size

### ISSUE THREAD

**Issue by Aakash-DD** [fossasia/open-event-frontend#2314]
**Describe the bug**

when screen width is decreased then top div (image) disappears 

**Expected behaviour**

when screen width is decreased then top div (image) should not disappear

**Original behaviour**
![Screenshot from 2019-03-18 14-50-20](https://user-images.githubusercontent.com/33255535/54520002-ad67fb00-498d-11e9-9d23-8db0650751b8.png)

 
**Screenshots of issue**

![Screenshot from 2019-03-18 14-50-55](https://user-images.githubusercontent.com/33255535/54519843-7691e500-498d-11e9-98af-9934f825a384.png)

**Comment by uds5501** [comment]
@Aakash-DD this is not an issue, this is deliberate . Kindly close this issue .

**Comment by kushthedude** [comment]
@Aakash-DD This issue is an enhancement which is not a priority now and has been deliberately done as stated by @uds5501 .

**Comment by ritikamotwani** [comment]
@Aakash-DD , this is not an issue.
