### ISSUE TITLE
Discrepancies in Admin Sales

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2316]
**Describe the bug**

Currently there are a lot of bugs - 
 - `By Event`, `Discounted Events` and `Fees` can have `paymentCurrency` of the events. Currently its hard-coded to `US $`.
 - In above mentioned tabs, `Total` doesn't make any sense as different events can have different currencies.

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Sales'
3. See error

**Expected behavior**

Sales of a particular event must have its own predefined currency and `Total` row should be removed till other alternative is finalised.

**Screenshots**

_By Events_
![Screenshot_2019-03-18 Overview Sales Administration Open Event](https://user-images.githubusercontent.com/25428397/54551380-0064a100-49d4-11e9-9162-5b823389ba6a.png)

_Fees_
![Screenshot_2019-03-18 Fees Sales Administration Open Event(1)](https://user-images.githubusercontent.com/25428397/54551692-90a2e600-49d4-11e9-933e-671784a86ad8.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04, Mozilla Firefox

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi great catch. Remove the totals row from the frontend for now (only comment it) and open an issue on the server.
