### ISSUE TITLE
Admin Sales: Ticket Count in Fee Summary is wrong

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2318]
**Describe the bug**

Currently, the number of `Tickets` shown in `Fees` is wrong. It shows the amount of sales made by `Completed`, `Pending` and `Expired` tickets.

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Sales'
3. Scroll down to 'Fees'

**Expected behavior**

The column should have number of tickets sold.

**Screenshots**

![Screenshot_2019-03-18 Fees Sales Administration Open Event(1)](https://user-images.githubusercontent.com/25428397/54554057-89320b80-49d9-11e9-8f81-95eea8b8ecfe.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Mozilla Firefox

**Additional context**

I'm working on it.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 can you please check if this issue is relevant or not. 
If `Tickets` is meant to show this info only, it should be renamed to `Ticket Sales`

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi naming is fine, and fee should appear only for completed Orders, tickets corresponding to them should be shown.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 `Revenue` column already has amount of `Completed Order`.

**Comment by shreyanshdwivedi** [comment]
@uds5501 @mariobehling @CosmicCoder96 I think this issue needs following implementation. `Tickets` needs to be renamed to `Ticket Sales` and have values of sales of `Completed Orders`. `Fees` column has % of service charge. And `Revenue` must contain -
```
( Ticket Sales * Fees )/100
```
Please provide your input so that I can fix it.

**Comment by uds5501** [comment]
@shreyanshdwivedi After looking into it after a while, actually the `Revenue` currently being used is in perspective of the organizer and I am not sure if we would like to change that.

Currently it addresses the equation:
```
Ticket Sales * ((1- Fees)/100)
``` 
If we do want to let it stay like this, we need to keep in mind that Current Ticket Fees also has a "Maximum Fees" attached to a Country-Currency combination which is not being addressed in the situation.

Maybe try reconstructing the Revenue to :

```
Ticket Sales - min(Ticket Sales * Fees / 100 , Maximum Revenue)
```

What are your thoughts on this?

**Comment by shreyanshdwivedi** [comment]
@uds5501 I agree. Revenue column should apply second formula. And then, I think `Ticket Sales` column must have the amount of sales from Completed orders only.
I'll open a PR for the same.
