### ISSUE TITLE
Fix Bug in Admin Event Date and Status

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2319]
**Describe the bug**

Currently there are two separate columns for start date and end date. Also there is no badge in status.
**To Reproduce**
1. Go to 'Admin'
2. Click on 'Event'

**Expected behavior**

Start and End Date should be clubbed under Date. We could have green, red and yellow badges for live, deleted and draft.
**Screenshots**

![Screenshot 2019-03-19 at 9 46 53 AM](https://user-images.githubusercontent.com/31013104/54576747-f7072300-4a2b-11e9-8412-3a86d4f151ca.png)

**Additional context**

I'm working on it.

**Comment by ritikamotwani** [comment]
@harsh-jindal , how is this a bug? It's an intended feature, which would help to sort events on the basis of start dates as well as the end dates.

**Comment by harsh-jindal** [comment]
@ritikamotwani I was thinking on making it similar to how it is in Manage events.

**Comment by ritikamotwani** [comment]
@harsh-jindal , no it shouldn't be like manage events.
Please check version1

**Comment by harsh-jindal** [comment]
@ritikamotwani Okay.
