### ISSUE TITLE
Add /admin/settings/analytics route

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#232]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Adding ananlytics page located at 'admin/settings/analytics route'.
![analytics](https://user-images.githubusercontent.com/17925669/27172023-59180e42-51d1-11e7-98c4-188a9f9583f7.png)

**Comment by sumedh123** [comment]
@geekyd Please assign.

**Comment by niranjan94** [comment]
@sumedh123 this page is already done in #216. Please see everyone else's PRs and issues too. Please.

**Comment by sumedh123** [comment]
@niranjan94 I ll keep in mind.
