### ISSUE TITLE
Align Amount and Percent in Enter Discount on the same line

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2322]
**Describe the bug**

Currently Amount and Percent in Enter Discount are on different line and clicking on one of it we get an input filed below it. It looks odd not having an input field under percent.
**To Reproduce**
1. Go to 'Tickets'
2. Click on 'Discount Code'
3. Scroll down to 'Amount/Percent in Enter Discount'

**Expected behavior**

Amount and Percent in Enter Discount should be on the same line. 
**Screenshots**

![Screenshot 2019-03-19 at 12 03 23 PM](https://user-images.githubusercontent.com/31013104/54581496-984ba480-4a3f-11e9-9a6d-b6f7dd569897.png)

**Additional context**

I'm working on it.

**Comment by ritikamotwani** [comment]
Not required
