### ISSUE TITLE
Add edit option in event view page.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2328]
**Is your feature request related to a problem? Please describe.**

Currently if an admin views the event, there is no option to edit the event from there, admin needs to go back to events list and click edit from there.
**Describe the solution you'd like**

Add edit button in view events page.
**Describe alternatives you've considered**

![Screenshot from 2019-03-19 16-15-13](https://user-images.githubusercontent.com/21174572/54600837-a7444e00-4a63-11e9-8fc8-6a9c0d4cea8a.png)
**Additional context**

I am working on this issue.

**Comment by ritikamotwani** [comment]
@Anupam-dagar it's an event overview page. Clicking on basic events will take you to the event edit page.
