### ISSUE TITLE
Number of confirmed sessions not listed

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2341]
**Describe the bug**
Number of confirmed sessions not listed

**Expected behavior**
Number of confirmed sessions should be listed

**Screenshots**
![s](https://user-images.githubusercontent.com/19900978/54668464-f5fdf080-4b14-11e9-8eb0-8114a215daaa.png)

**Additional context**
I am working on this issue

**Comment by ritikamotwani** [comment]
Not required.
![image](https://user-images.githubusercontent.com/22127980/54669229-d58d6080-4b2b-11e9-8f0c-00abd6b7915c.png)
