### ISSUE TITLE
Social links are missing in footer section.

### ISSUE THREAD

**Issue by vinaysomawat** [fossasia/open-event-frontend#2343]
**Describe the bug**
Social links are missing in the footer section on the main page.

**To Reproduce**
1. Go to 'Main page'
2. Click on nothing
3. Scroll down to 'footer'

**Expected behavior**
Social links should be present in footer section.

**Screenshots**
![Screenshot from 2019-03-20 13-47-28](https://user-images.githubusercontent.com/30196269/54669431-5db53b00-4b17-11e9-875d-43a9cf510084.png)

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 16.04.6 
 - Browser: Firefox Web browser
 - Version: 65.0.1(64 bit)

**Smartphone (please complete the following information):**

**Additional context**
No

**Comment by CosmicCoder96** [comment]
They need to be configured in admin settings.
