### ISSUE TITLE
No validation on phone number in contact info

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2345]
**Describe the bug**

There is no validation on phone number, user can enter number of any length and alphabets in the input.
**To Reproduce**
1. Go to 'Settings' in the user dropdown.
2. Click on 'Contact Info' tab.
3. Enter phone number of any length and also alphabets.
4. See error.

**Expected behavior**

It shouldn't accept the invalid inputs from the user.

**Screenshots**

![phone-number-valid](https://user-images.githubusercontent.com/43299408/54676911-cefcea00-4b27-11e9-957d-4609879c8e35.png)

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
@Anupam-dagar Proceed.
