### ISSUE TITLE
Duplicate speaker images in session-item

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2361]
**Describe the bug**

Currently, for one speaker, images occur two times in `session-item` on `public` route

**To Reproduce**
1. Go to `Event Public` page
2. Click on `Sessions`
3. Click on `accepted` or `confirmed` session item.

**Expected behavior**

If one speaker is present, image must appear only once.

**Screenshots**

![Screenshot_2019-03-21 Sessions APK19 Open Event(2)](https://user-images.githubusercontent.com/25428397/54751663-ab0dd700-4c01-11e9-9f2b-309bd26b178a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Mozilla Firefox

**Additional context**

Working on it

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 can you please review if this issue is valid for enhancement. I want to make changes like this -
![Screenshot_2019-03-21 Sessions APK19 Open Event(3)](https://user-images.githubusercontent.com/25428397/54752469-44d68380-4c04-11e9-925f-cec4f9c01781.png)

**Comment by shubham3211** [comment]
@shreyanshdwivedi I don't think it is an error.
http://sched.eventyay.com/FOSSASIASummit/schedule.html

**Comment by shreyanshdwivedi** [comment]
@shubham3211 please refer to the image attached in the description. Also, the link you provided hides speaker image in the `session-item` when it is expanded. In this way, the `session-item` only contains one image of a single speaker.
![Screenshot_2019-03-21 FOSSASIA Summit](https://user-images.githubusercontent.com/25428397/54752785-4b192f80-4c05-11e9-974d-7bbfbebf549e.png)

**Comment by shubham3211** [comment]
I think it should be done in this way, when the user click on the session the image on the top should disappear and image should be above speaker description.

**Comment by shreyanshdwivedi** [comment]
I think it is nice suggestion. @CosmicCoder96 thoughts?

**Comment by CosmicCoder96** [comment]
> I think it should be done in this way, when the user click on the session the image on the top should disappear and image should be above speaker description.

@shreyanshdwivedi go ahead with this approach.
