### ISSUE TITLE
Share event close button lying outside the card

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2363]
**Describe the bug**

On large screens, close button for share event card lies outside the share event card.

**To Reproduce**
1. Go to 'Upcoming Events' on the landing page.
2. Click on 'Share event' icon on the bottom of event card.
3. See error

**Expected behavior**

Close button should always lie inside the card, just like on some smaller screens.
![expected-behaviour](https://user-images.githubusercontent.com/43299408/54804154-8749a000-4c98-11e9-9cf4-b67cf302502a.png)

**Screenshots**

![share-event-close-btn](https://user-images.githubusercontent.com/43299408/54804167-8fa1db00-4c98-11e9-8206-0766aedb2388.png)

**Additional context**

Working on it.

**Comment by ritikamotwani** [comment]
This is a design choice for every modal, not a bug.

**Comment by Haider8** [comment]
@ritikamotwani it doesn't look good in my opinion :) 
![Screenshot_2019-03-22_13-56-10](https://user-images.githubusercontent.com/43299408/54809801-58d4c080-4caa-11e9-878f-a89c3d35d97b.png)

Here also, it is lying inside the card
