### ISSUE TITLE
minor typo in event types

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2365]
**Describe the bug**

The event type hashtag in the event card has wrong spelling : Startups "Amp" Small Business

**Expected behavior**

The typo should be fixed

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/54829626-d1ed0b80-4cdc-11e9-97b9-ece031a1c791.png)

**Additional context**

Open for any beginner!

**Comment by Haider8** [comment]
@uds5501 okay, i will fix this

**Comment by uds5501** [comment]
@Haider8 Go ahead!

**Comment by Haider8** [comment]
@uds5501  Since special characters like ```!, $, &``` etc.  will not work in hashtags, the ```&``` symbol in ```Startups & Small Business``` have been escaped automatically to ```Amp```. The fix that i can think of is to remove the ```&``` and make it ```And```. What are your thoughts.

**Comment by uds5501** [comment]
@Haider8 No, don't remove the `Amp`, maybe try using sanitize helper instead?

**Comment by Haider8** [comment]
@uds5501 No, i was talking about ```&``` symbol.

**Comment by uds5501** [comment]
@Haider8 Alright, I see your point. We can't use special characters in hashtags. In that case, see if you can substitute the `&` as `And` for the hashtag particularly. 
@CosmicCoder96 could use some insights if this method is worth following

**Comment by kushthedude** [comment]
@uds5501 A simple 'And' at the place of 'Amp' Should be enough?

**Comment by Haider8** [comment]
@uds5501 I think there is a need to change in server also. Can you please confirm?

**Comment by CosmicCoder96** [comment]
fixed in https://github.com/fossasia/open-event-server/pull/5709
