### ISSUE TITLE
Event end time error

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2366]
**Describe the bug**

Not able to set end time prior to start time

**To Reproduce**

1. Go to 'http://127.0.0.1:4200/create'
2. Set a start time and date
3. Change the end date.
4. Try to set end time before start time.
5. See error

**Expected behavior**

User should be able to set end time as per his flexibility.

**Screenshots**

<img width="1316" alt="Screenshot 2019-03-23 at 12 52 35 AM" src="https://user-images.githubusercontent.com/44091822/54848044-28bb0b00-4d06-11e9-8594-0c39138af344.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 72.0.36

**Additional Context:**

Would like to work on it.

**Comment by uds5501** [comment]
@kushthedude  It's more of a subissue under #2077 .
The calendar is malfunctioning big time, but as far as your issue is concerned, according to the documentation of `ember-semantic-ui-calendar`'s date-range (which is being used in start and end date) , we can only set an end date AFTER the start date while in the time-range, the end time can be set after the start time only. 
In short, these time input and date input categories have no coherence per se but in terms of suggestions, @CosmicCoder96  we can make the time input fields independent identities to induce user time flexibility

**Comment by kushthedude** [comment]
@uds5501 i think i got a fix for #2077 which will make the calendar time work for now .

**Comment by uds5501** [comment]
@kushthedude push the PR soon then

**Comment by kushthedude** [comment]
@uds5501 i will push the PR asa soon as i reach my college

**Comment by CosmicCoder96** [comment]
Fixed after removing validations.

**Comment by shreyanshdwivedi** [comment]
@kushthedude can you please state the error faced by you?

**Comment by kushthedude** [comment]
> @kushthedude can you please state the error faced by you?

@shreyanshdwivedi see the issue description and screenshot

**Comment by shreyanshdwivedi** [comment]
You mentioned that user is unable to set end time before start time. Is that an issue? I think user should not be allowed to add end time before start time

**Comment by mrsaicharan1** [comment]
I agree with this.

**Comment by kushthedude** [comment]
Nope, Set a start time and start date; Change the end date and see the end
time you are restricted to set end time before start time but you are on
different days . Thats the bug @shreyanshdwivedu @mrsaicharan1

**Comment by mrsaicharan1** [comment]
> Nope, Set a start time and start date; Change the end date and see the end time you are restricted to set end time before start time but you are on different days . Thats the bug @shreyanshdwivedu @mrsaicharan1 On Sun, 21 Jul, 2019, 14:26 Saicharan Reddy, <notifications@github.com> wrote:
> […](#)

I've tried what you've mentioned here but I haven't experienced any issue. Let's close this for now & reopen if anyone else experiences this.

**Comment by mrsaicharan1** [comment]
event dates which are not being set
Ex:
start: 23/7 5:00 PM 
end: 24/7 4:30 PM
