### ISSUE TITLE
set cfs default start date to today for development ease

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2367]
**Is your feature request related to a problem? Please describe.**

No, I would like to set the default start date of a CFS form to Today for development preferences and I believe that It'd be great if an organiser has an option to set CFS date from form creation date itself instead of the event's starting time.

**Describe the solution you'd like**

Just set the default start-date to today's date

**Additional context**

I would like to work on it if mentor's approve

**Comment by uds5501** [comment]
What are your views in it @ritikamotwani @CosmicCoder96

**Comment by CosmicCoder96** [comment]
No, the organizers may unintentionally end up opening the CFS, when they are not ready to open the CFS.
