### ISSUE TITLE
Wrong standard size of available area in 'Logo Size' section

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2384]
**Describe the bug**

Wrong standard size of available area is shown in the 'Logo Size' section in Admin's image settings.

**To Reproduce**
1. Go to 'Admin' section.
2. Click on 'Settings' tab.
3. Go to 'Images' tab.
3. Scroll down to 'Logo Size (Event Wizard)' section.
4. See error.

**Expected behavior**

Should have shown standard size as seen in the input fields of that section. That is, like in the other sections.

**Screenshots**

![wrong-standard-size](https://user-images.githubusercontent.com/43299408/54933922-9902a000-4f43-11e9-8142-e460a2d382a1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
Sponsor logos are not squares.
