### ISSUE TITLE
Unresponsive UI under tickets section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2386]
**Describe the bug**

When the screen size is <767px  , The UI of tickets section fails and user interface fails.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Event Overview'
2. Click on 'Tickets'
3. Resize the screen

**Expected behaviour**

UI should not fail and should be responsive for enhanced user experience.

**Screenshots**

<img width="796" alt="Screenshot 2019-03-25 at 9 40 08 PM" src="https://user-images.githubusercontent.com/44091822/54935599-9eadb500-4f46-11e9-9c6c-3df893e54bf9.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0

**Additional context**

If this is a valid issue i would like to give it a try

**Comment by kushthedude** [comment]
@uds5501 Can you check it out

**Comment by CosmicCoder96** [comment]
@kushthedude Before you make a PR do propose a solution that you think would be fit to display horizontal tables on a vertical screen and share a deployment link of it, maybe we can use it all across the app then :)
