### ISSUE TITLE
UI issue in buttons on creating event

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2394]
**Expected behavior**
I think buttons should stack according to size of display screen.

**Screenshots**
![Screenshot from 2019-03-26 19-26-36](https://user-images.githubusercontent.com/31065687/55003065-a7ad8d80-4ffd-11e9-9eb5-e341eb6fe647.png)

**Additional context**
Working on it.

**Comment by mohitm15** [comment]
@prateekj117 should i take this issue?

**Comment by prateekj117** [comment]
@mohitm15 Working on it.
