### ISSUE TITLE
Google Sign-in is not integrated 

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2395]
> **Describe the bug**
> 
> The google-sign in is not working while login through your google account at eventyay.
> 
> **Steps To Reproduce**
> 
> Steps to reproduce the behaviour:
> 
> 1. Go to https://eventyay.com
> 2. Click on 'Login'
> 3. Sign in with Google accounts
> 4. Select the account
> 5. See the error
> 
> **Expected behaviour**
> 
> User should be logged in through google account
> 
> **Screenshots**
> 
> 
![imageedit__6708216153](https://user-images.githubusercontent.com/35539313/55006771-4b9a3780-5004-11e9-8c72-eb1652a0046a.gif)

> 
> **Desktop (please complete the following information):**
> 
> * OS:Ubuntu 16.04
> * Browser: Google Chrome
>  
> 
> **Additional context**
> 
> Review it. If found valid , I will like to work on it

**Comment by CosmicCoder96** [comment]
You are using the legacy version. Wrong repo.

**Comment by mohitm15** [comment]
Okay
