### ISSUE TITLE
Clicking on 'Call For Speakers' section should redirect to 'Call For Speakers' section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2397]
**Is your feature request related to a problem? Please describe.**

No , Just an enhancement:
- When Call for Speakers is open for an event . It is displayed on the index page of WebApp.
- When you click on the event card you should get redirected to the 'call for speaker'   section of that given amount

**Describe the solution you'd like**

Clicking on the event card should redirect to 'Call For Speakers' Section.

**Describe alternatives you've considered**

No alternatives considered.

**Additional context**

![Call](https://user-images.githubusercontent.com/44091822/55029205-84033b00-502f-11e9-9b4c-c1b3a985b4f8.gif)

**Comment by CosmicCoder96** [comment]
No it just means that the given event has CFS open. People can browse it with that in mind.
