### ISSUE TITLE
Unresponsive UI of Tickets Table

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2398]
**Describe the bug**

When the 'info section' of a event is decreased in size , Event name, ticket type and many details disappear and UI worsens

**To Reproduce**

1. Go to 'Click on any event card'
2. Click on 'Info in side bar'
3. Resize the window

**Expected behavior**

UI should be intact

**Screenshots**

![UI](https://user-images.githubusercontent.com/44091822/55030639-d2660900-5032-11e9-92f7-520eaadab4d6.gif)

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser: Chrome
 - Version: 73.0

**Smartphone (please complete the following information):**
 - Device: Every Smartphone with screen size upto 6.5 inches
 - OS: All
 - Browser All

**Additional context**

I think Many Tables need a workaround for UI.

**Comment by kushthedude** [comment]
@CosmicCoder96 I was using the site on the phone using Chrome Simulation , Many tables in the WebApp needs a workaround as they are not modified for a small screen.

**Comment by CosmicCoder96** [comment]
This is responsive,  horizontal tables can't remain intact on vertical screens.

**Comment by kushthedude** [comment]
Should not this be something to be worked , like if user try to acces on phone all he can see is the ugly columns?

**Comment by harsh-jindal** [comment]
@CosmicCoder96 @kushthedude  I think tables with less than 4 columns can be shown horizontally as it would provide better user interface.

**Comment by kushthedude** [comment]
@harsh-jindal I think responsiveness of Mobile UI is included in GSOC and the solution you provided actually worsens UI in some phones as table extends the confined boundary .

**Comment by harsh-jindal** [comment]
@kushthedude Cool I'll close #2413 . Let this issue be resolved during GSOC period.

**Comment by kushthedude** [comment]
@harsh-jindal Great but just making table class unstackable is not valid fix 😅

**Comment by harsh-jindal** [comment]
@kushthedude Yeah.. I know that, I thought it would work where the number of columns were less than four. Will have to come up with better implementations anyways for the remaining tables. So will fix it that time.
