### ISSUE TITLE
Fix responsiveness of filter options on home page.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2399]
**Describe the bug**

The filter options on home page isn't responsive. The search bar gets cut for smaller screens.

**To Reproduce**
1. Go to '/'
2. Switch to responsive mode.
3. See error

**Expected behavior**

I suggest moving search bar and buttons in different lines for mobile screens.
**Screenshots**

![Screenshot from 2019-03-27 09-51-31](https://user-images.githubusercontent.com/21174572/55050429-9e143c00-5076-11e9-8373-69bc8cd3e975.png)

![Screenshot from 2019-03-27 09-51-16](https://user-images.githubusercontent.com/21174572/55050442-b1270c00-5076-11e9-9e0b-e895f3a3bd7f.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@Anupam-dagar have a look at #2247

**Comment by Anupam-dagar** [comment]
@kushthedude Your issue and my issue are for sure referencing the same component but not the same issue.

**Comment by kushthedude** [comment]
I think responsiveness is left out intentionally :)

**Comment by uds5501** [comment]
@Anupam-dagar Are you working on this or can I try my hand on this one?

**Comment by mohitm15** [comment]
@Anupam-dagar not only search bar is getting cut but also the content is coming out of the boundary of the card. Should I create issue for that and start working on that part??

**Comment by kushthedude** [comment]
@mohitm15 @uds5501 Refer this   
https://github.com/fossasia/open-event-frontend/issues/2247#issuecomment-469095512

**Comment by prateekj117** [comment]
@uds5501 If you haven't done much work on it, I would like to take it up.

**Comment by uds5501** [comment]
@prateekj117 Go ahead
