### ISSUE TITLE
422 Payload error on ordering a free ticket

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2400]
**Describe the bug**

A 422 Empty payload error is raised whenever trying to order a free ticket
(Error: Ember Data Request PATCH http://127.0.0.1:5000/v1/orders/33696a48-fad5-4eb9-8d68-96a65cc3aabd returned a 422 Payload (Empty Content-Type) [object Object] Oops something went wrong. Please try again)

**To Reproduce**
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/21087061/55051276-614a4400-507a-11e9-81c9-1cdece20da88.gif)

**Expected behavior**

This error should not occur

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by kushthedude** [comment]
@uds5501 Will you please check into it as i am not able to see this error?

**Comment by kushthedude** [comment]
See into this
![issue](https://user-images.githubusercontent.com/44091822/55058819-2b658980-5093-11e9-94b8-ec25cc52c225.gif)

**Comment by uds5501** [comment]
@kushthedude there has been a database migration recently done by me. Update your database and try again

**Comment by kushthedude** [comment]
@uds5501 I tried it after updating database and its workin perfectly fine.

**Comment by CosmicCoder96** [comment]
@uds5501 I know why this is happening, but what's interesting is nothing has changed on the server. It's a failed validation for the amount to be greater than zero. I wonder what changed on the frontend.

**Comment by uds5501** [comment]
@CosmicCoder96 Actually. One thing has, after the recent migration, the `amount` is supposed to be non-null but the patch request for a free ticket is passing a request with no amount parameter. I tried adding it but nothing changed

**Comment by CosmicCoder96** [comment]
Let's follow the discussion here. https://github.com/fossasia/open-event-server/issues/5724
