### ISSUE TITLE
Admin/sales statistics not being rendered

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2402]
**Describe the bug**

**To Reproduce**
1. Go to Admin/Sales
2. Click on Locations
3. See error

**Expected behavior**

The non rendered stats should display a zero instead

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/55053993-2947fe80-5084-11e9-9dee-85b4c6218a4a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by kushthedude** [comment]
@uds5501 This is due to the currency parser it will get included in #2376 as the issue created here is due to the 'currency-symbol' attribute , And i am lookin for a once and for all fix for it :) , You may close it

**Comment by uds5501** [comment]
@kushthedude this is not exactly basic currency parsing as I have given my argument in the PR itself :)
