### ISSUE TITLE
Can't restore a deleted event

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2406]
**Describe the bug**

On restoring a deleted event, `an unexpected error has occured appears`. The console shows a `422 Unprocessable Entity` error. I have synced my server and upgraded the migrations.

**To Reproduce**
1. Go to '/admin/events/deleted'
2. Click on 'restore event'
3. See error

**Expected behavior**

Event should get restored.
**Screenshots**

**Additional context**

**Comment by uds5501** [comment]
@Anupam-dagar Event Restoration is working fine for me. Any particulars which were in your event which you would like to share?

**Comment by kushthedude** [comment]
Workin fine for me too :)

**Comment by CosmicCoder96** [comment]
Working fine here, recheck and close if you can't repeat it.

**Comment by CosmicCoder96** [comment]
Tested it, event restored successfully.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I am going to setup the server again, I guess somewhere migrations problem happened.
