### ISSUE TITLE
CFS event-card on index should link to event's cfs page

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2407]
**Describe the bug**

The event-cards under Call for speakers should directly link to event's call for speaker page instead of the main page.

**To Reproduce**
1. Go to Index
2. Click on any CFS event
3. See error

**Expected behavior**

The car should link to the CFS page of the event

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it!

**Comment by kushthedude** [comment]
see #2397 they are same . :0

**Comment by uds5501** [comment]
...okay, closing it now
