### ISSUE TITLE
Number Of Speakers not getting updated under tickets overview

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2408]
**Describe the bug**

Number Of Speaker shown under tickets overview is not appropriate and its not getting updated as soon as some speaker is getting confirmed.

**To Reproduce**

1. Go to 'Manage Events'
2. Click on 'View Event'
3. Scroll down to 'See under general info'

**Expected behavior**

Number of speakers should get updated.

**Screenshots**

<img width="613" alt="Screenshot 2019-03-27 at 4 15 44 PM" src="https://user-images.githubusercontent.com/44091822/55070287-f0bc1b00-50ab-11e9-911f-302cd321b822.png">

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser: Chrome
 - Version: 73.0

**Comment by uds5501** [comment]
@kushthedude this will be resolved after #2381 is merged :)

**Comment by CosmicCoder96** [comment]
2381 is merged.
