### ISSUE TITLE
Add tooltip to event overview when in mobile view

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2409]
**Describe the bug**

Currently in mobile view the user has no info on the icons on the top.
**To Reproduce**
1. Go to 'Event overview'

**Expected behavior**

Add tooltip to event overview when in mobile view
**Screenshots**

![Screenshot 2019-03-27 at 6 19 50 PM](https://user-images.githubusercontent.com/31013104/55077255-464cf380-50bd-11e9-808f-13ba181e9eb9.png)

**Additional context**

I'm working on this.

**Comment by CosmicCoder96** [comment]
Not required.
