### ISSUE TITLE
Link the respective count of events/sessions to their corresponding type in Admin 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2411]
**Describe the bug**

Currently only number of various types of events/sessions is shown.
**To Reproduce**
1. Go to 'Admin'

**Expected behavior**

It would be better if the user can click on for example the number of draft events and be taken to that page.
**Screenshots**

![Screenshot 2019-03-27 at 8 32 10 PM](https://user-images.githubusercontent.com/31013104/55087274-db58e800-50cf-11e9-945e-1cba0b66e40f.png)

**Additional context**

I'm working on it.

**Comment by ritikamotwani** [comment]
Not a priority right now.
Please check version1
