### ISSUE TITLE
Incorrect amount of Tickets under 'Fees section'

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2412]
**Describe the bug**

Incorrect number of tickets are displayed under fee summary section.

**To Reproduce**

1. Go to 'Admin/Sales/Fees'
2. Scroll down to 'Tickets'

**Expected behavior**

It should show correct number of tickets

**Screenshots**

<img width="978" alt="Screenshot 2019-03-27 at 10 26 17 PM" src="https://user-images.githubusercontent.com/44091822/55096434-e6b40f80-50df-11e9-8c16-210706e34a22.png">

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser: Chrome
 - Version: 73.0

**Comment by kushthedude** [comment]
@uds5501 Can you please verify the issue 😅 ?

**Comment by uds5501** [comment]
@kushthedude  as discussed and stated by @shreyanshdwivedi , it's ticket sales and has already been resolved, kindly update your repository :)

**Comment by kushthedude** [comment]
Oops

**Comment by kushthedude** [comment]
@uds5501 I updated the repo but still its here

**Comment by shreyanshdwivedi** [comment]
@kushthedude there is already a PR open for this - https://github.com/fossasia/open-event-frontend/pull/2369

**Comment by kushthedude** [comment]
@shreyanshdwivedi Not a issue
