### ISSUE TITLE
Add class unstackable to table of Manage Roles and Tickets in Overview in mobile view

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2413]
**Describe the bug**

Currently the table in Manage Roles and Tickets stacks vertically in mobile view but it can viewed horizontally as the number of columns are less.
**To Reproduce**
1. Go to 'Overview'
2. 'Decrease browser screen size'

**Expected behavior**

Add class unstackable to table of Manage Roles and Tickets in Overview in mobile view
**Screenshots**

![Screenshot 2019-03-27 at 11 45 05 PM](https://user-images.githubusercontent.com/31013104/55101591-72cb3480-50ea-11e9-8117-e8db49406a21.png)

![Screenshot 2019-03-27 at 11 45 18 PM](https://user-images.githubusercontent.com/31013104/55101594-73fc6180-50ea-11e9-9bcc-471cc352ce91.png)

**Additional context**

I'm working on it.

**Comment by kushthedude** [comment]
See #2398 .
