### ISSUE TITLE
Enhance navbar to include signup instead of create event when user hasn't logged in.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2415]
**Is your feature request related to a problem? Please describe.**

Currently the navbar include create event event when the user isn't logged in. There is no sign up button in the navbar. This might be design choice but I guess it can be changed. On looking on the other similar websites eventbrite and meetup, I saw all of them list signup in the navbar along with login. Also currently reaching signup is a 2 step process i.e clicking on login and then going to signup. This will make it easy for new users to signup. Create event button will stay as is on the welcome banner.

**Describe the solution you'd like**

Show signup button instead of create event when the user hasn't logged in.
When the user logs in, the signup button will be replaced with create event button.

## Screenshots
![Screenshot from 2019-03-28 01-50-27](https://user-images.githubusercontent.com/21174572/55110235-9f3c7c00-50fd-11e9-860c-4527e8ea6db1.png)

**Additional context**

I am working on this issue.

**Comment by CosmicCoder96** [comment]
No major changes in the core UI yet which are not present in the legacy. People are more likely to create at create event and use the system when the button is right there.
