### ISSUE TITLE
Uneven Spaces Between the buttons 

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2417]
**Describe the bug**
 
 Spaces between the four buttons mentioned in the screenshot is not uniform shown under tickets overview.
 
 **To Reproduce**
 
 
 1. Go to 'Manage Events'
 2. Click on 'View Event'
 3. Scroll to right top corner'
 
 **Expected behavior**
 
 All buttons should be aligned properly

 
 **Screenshots**
 ![Screenshot from 2019-03-28 02-34-45](https://user-images.githubusercontent.com/35539313/55112511-bfbb0500-5102-11e9-8923-a353327f5056.png)

- - -
### zoom image

![isu1](https://user-images.githubusercontent.com/35539313/55112542-d4979880-5102-11e9-8639-7ce3ffcc385b.png)
 
 **Desktop (please complete the following information):**
 
 * OS: Ubuntu 16.04
 * Browser: Chrome
 * Version: 73.0

  **Additional Information**
      I am working on this issue

**Comment by CosmicCoder96** [comment]
intentional. The groups of buttons are categorized as Viewing, Editing, Deleting actions.

**Comment by mohitm15** [comment]
@CosmicCoder96 I am talking that the space between preview and (unpublish+copy) is not the same as that of (unpublish+copy) and delete

**Comment by mohitm15** [comment]
@CosmicCoder96 what are your views??

**Comment by mohitm15** [comment]
@CosmicCoder96 Should I reopen this? and work on it

**Comment by ritikamotwani** [comment]
@mohitm15 this is not a priority at the moment. The spacing is kept similar to version1.
Please browse through other issues.

**Comment by mohitm15** [comment]
@CosmicCoder96  okay

**Comment by ritikamotwani** [comment]
@mohitm15 no need to create it.
We'll reopen the issue if required.

**Comment by mohitm15** [comment]
@ritika sure and don't forget to label it 😅

**Comment by mohitm15** [comment]
@ritikamotwani Should I reopen it??
