### ISSUE TITLE
Wrong message on explore route when there is no event

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2427]
**Describe the bug**

```No events found for selected filters``` is shown when there is no event, and **neither any filters applied**. 

**To Reproduce**
1. Go to 'Browse Events' page
2. See error (make sure you don't have any events)

**Expected behavior**

Should show something like this ```No Upcoming Events Found``` or ```No Events Found```.

**Screenshots**

![explore-events](https://user-images.githubusercontent.com/43299408/55168215-6dc4be80-5198-11e9-9aa0-fe71b2e9b27b.png)

**Additional context**

Working on it

**Comment by Haider8** [comment]
@shreyanshdwivedi @mrsaicharan1 What should i write in the condition if i want to know there is any event or not. Please help :)

**Comment by mohitm15** [comment]
Should I work on this issue?

**Comment by Haider8** [comment]
No, i am working on it

**Comment by ritikamotwani** [comment]
Let's not over complicate things -- this is a very trivial case, and not factually incorrect.
