### ISSUE TITLE
 No drop-down for protocol in website input field in call for speaker form

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2428]
**Describe the bug**

This field has validation, which require the users to enter the protocol manually whether it is ```https``` or ```http```. Therefore, ```example.com``` will not be accepted and ```https://example.com``` will be accepted. Instead of this we can give the users a drop-down for specifying the protocol, which will be easier for them.

**To Reproduce**
1. Go to 'Call for Speakers' form.
2. Scroll down to 'Website' field.
3. See error

**Expected behavior**

![cfs-website-field-fix](https://user-images.githubusercontent.com/43299408/55238938-b0030400-525b-11e9-9930-ec7e9fe4ccc1.png)

**Screenshots**

![cfs-website-field-1](https://user-images.githubusercontent.com/43299408/55238976-be512000-525b-11e9-8a46-4c21311d6d6a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu]
 - Browser [e.g. chrome]

**Additional context**

Working on it

**Comment by uds5501** [comment]
@Haider8 does the validation test pass on `www.example.com`?

**Comment by Haider8** [comment]
@uds5501 No
![Screenshot_2019-04-02_04-32-56](https://user-images.githubusercontent.com/43299408/55365063-b6fe7080-5500-11e9-8c81-e0a9bfb5b0e4.png)

**Comment by Haider8** [comment]
@uds5501 Can we change the validation rules in order to support ```http```, ```https``` and ```www``` and drop ```dropdown``` in that case?

**Comment by kushthedude** [comment]
@Haider8 Still on it?

**Comment by kushthedude** [comment]
@Haider8 ?

**Comment by harsh-jindal** [comment]
@Haider8 You can add this for social media links too in the speaker.

**Comment by prateekj117** [comment]
@Haider8 Any progress on this issue?

**Comment by kushthedude** [comment]
@prateekj117 its been a week i asked him about the progress , i think he is not active .

**Comment by kushthedude** [comment]
@CosmicCoder96 should i takeover?

**Comment by uds5501** [comment]
@kushthedude go ahead then

**Comment by Haider8** [comment]
I was working on it. Was busy

**Comment by kushthedude** [comment]
No problem go ahead

**Comment by Anupam-dagar** [comment]
Hey @Haider8 By yesterday night there wasn't a PR opened for this and no comments for you so I decided to resolve it out. I saw your comment now only. Can you take over another issue for now.

**Comment by kushthedude** [comment]
@Anupam-dagar atleast you should have informed here before opening a PR related to this issue as i was already in the queue and today you just open a PR from nowhere , that should not prevail , as someone might have already solved it and due to some issues he couldnt push the PR
