### ISSUE TITLE
Add UI for admin/sales/marketer

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#243]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-06-17 10-29-22](https://user-images.githubusercontent.com/12807846/27250265-dcbb8266-5347-11e7-8c43-3648a5882a77.png)

**Comment by harshitagupta30** [comment]
I am working on this.
