### ISSUE TITLE
Unresponsive event card image

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2431]
**Describe the bug**

  On resizing the window, the image of the event card disappears. Two screenshots are attached below.

**To Reproduce**
1. Go to 'Open event'
2. Click on 'Browse events.'
3. Resize the window'

**Expected behavior**

 It should display the image of the event card.

**Screenshots**

When fullscreen:
![Screenshot from 2019-03-31 01-20-19](https://user-images.githubusercontent.com/35539313/55280998-b5dc1080-5353-11e9-9a85-b46a3ad098f3.png)
When screen size is minimized:
![isu2](https://user-images.githubusercontent.com/35539313/55281033-3bf85700-5354-11e9-82e2-744cc63e8d83.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser : Chrome]
 - Version : 71.0.3578.98 (64-bit)

**Additional context**

Please review this.If found valid ,like to work on it.

**Comment by kushthedude** [comment]
Displaying image with all the events details on such a small screen would make the UI look very compact and ugly hence it is recommended.

**Comment by uds5501** [comment]
@mohitm15 Kindly refer to the following lines of code:

```hbs

{{#unless isWide}}
      <a class="image" href="{{href-to 'public' event.identifier}}">
        {{widgets/safe-image src=(if event.thumbnailImageUrl event.thumbnailImageUrl event.originalImageUrl)}}
      </a>
{{/unless}}
```
this specifically mentions that the images should be displayed in the card only if the screen is wide enough for support. Also, as @kushthedude states, it would make the UI feel pretty squashed.

**Comment by CosmicCoder96** [comment]
Images on small screens are hidden intentionally.
