### ISSUE TITLE
Wrong default text on create event

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2432]
**Describe the bug**

 The default value in the time textfield while creating the event is '<b>invalid date</b>'

**To Reproduce**
1. Go to 'Open Event'
2. Click on 'create event'
3. Scroll down to 'starts and ends section'

**Expected behavior**

The default value should be '<b>invalid time</b>'

**Screenshots**

![3](https://user-images.githubusercontent.com/35539313/55281369-7b757200-5359-11e9-8788-ebfce5b1857e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser : Chrome
 - Version : 71.0.3578.98 (64-bit)

**Additional context**

Working on it :+1:

**Comment by uds5501** [comment]
@mohitm15 Bug non reproduce-able.

![image](https://user-images.githubusercontent.com/21087061/55349032-46425e80-54d6-11e9-9c4a-a9641e972faa.png)
