### ISSUE TITLE
Clear Filter gets highlighted on No Param Passes

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2433]
**Describe the bug**

When there are no parameters in search bar on startup page and After clicking search , Clear Filter gets highlighted .

**To Reproduce**

1. Go to 'Start-Up Page'
2. Click on 'Search'

**Expected behavior**

Unless some parameter is passed ,Clear-Filter should not get highlighted.

**Screenshots**

<img width="1085" alt="Screenshot 2019-03-31 at 5 15 44 AM" src="https://user-images.githubusercontent.com/44091822/55282906-18dd9f80-5374-11e9-80f5-b2d3d20c1299.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Comment by mohitm15** [comment]
@kushthedude I think this has been already working. If you click on search bar without any parameter is passes, clear filter buttons <b>did not </b> get highlighted. It gets highlighted only after you pass a parameter and search for it.
![ezgif com-optimize](https://user-images.githubusercontent.com/35539313/55289751-3fd5b900-53e8-11e9-9dc7-d13ddb936b40.gif)

**Comment by kushthedude** [comment]
@mohitm15 Refer #2434

**Comment by Neelrayal** [comment]
Can I work on this issue?

**Comment by kushthedude** [comment]
Go on

**Comment by ridhishjain** [comment]
@kushthedude Can I work on this issue?

**Comment by ridhishjain** [comment]
@kushthedude what about review?

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by iamareebjamal** [comment]
Yes
