### ISSUE TITLE
Admin page: Not showing last-accessed for users in local time

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2436]
**Describe the bug**

Last-Accessed for users is shown in GMT and not in the local time which is incorrect.

**To Reproduce**
1. Go to 'Admin' page.
2. Click on 'Users' tab.
3. See error.

**Expected behavior**

Should show last-accessed in local time.

**Screenshots**

For example, see the last-accessed column for ```super-admin```, time is ```8:11 AM``` but it should have shown ```1:41 PM``` as the ```super-admin``` is seeing from India.

![last-accessed](https://user-images.githubusercontent.com/43299408/55287941-a4cfe580-53cd-11e9-8122-fb46224baf25.png)

![cf9f61ca-375f-4bca-bf50-b1cb3d07bad1](https://user-images.githubusercontent.com/43299408/55287991-64bd3280-53ce-11e9-915b-7955d0d4e57f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu]
 - Browser [e.g. chrome]

**Additional context**

Working on it

**Comment by Haider8** [comment]
@CosmicCoder96 In the file ```app/routes/admin/users/list.js```, i made the changes on lines ```37``` and ```62``` by setting this line to ```val  : moment().subtract(1, 'Y').toISOString(true)```. The value is true for utcOffset. I have read about this [here](https://momentjs.com/docs/#/displaying/as-iso-string/). 

But the problem is not solved by this. Can you please point out what am i missing here.

**Comment by Draco9421** [comment]
i am working on this.
