### ISSUE TITLE
Add UI for admin/sales/fees

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#244]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-06-17 10-31-33](https://user-images.githubusercontent.com/12807846/27250275-32bdd858-5348-11e7-8258-ed48030f9a41.png)

**Comment by CosmicCoder96** [comment]
I'm working on this.

**Comment by CosmicCoder96** [comment]
@niranjan94 @geekyd @sumedh123 While solving #179 The row for `total` was left out. Was that intentional?

**Comment by geekyd** [comment]
@CosmicCoder96 I do not think so. Please open a separate issue for that & proceed with this. Thanks
