### ISSUE TITLE
Wrong button spacing in events page

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2440]
**Describe the bug**
Buttons are not correctly spaced.

**Screenshots**

![Screenshot from 2019-03-31 22-39-08](https://user-images.githubusercontent.com/31065687/55292260-0ca22280-5406-11e9-9baa-32ed733327bb.png)

**Additional context**
Working on it.

**Comment by mohitm15** [comment]
@prateekj117 this is intentional

**Comment by prateekj117** [comment]
@mohitm15 Are you sure? I don't get why it would be intentional.

**Comment by mohitm15** [comment]
> @mohitm15 Are you sure? I don't get why it would be intentional.

REFER: https://github.com/fossasia/open-event-frontend/issues/2417

**Comment by ritikamotwani** [comment]
@prateekj117 this is not a priority right now.
The spacings are kept same as version1.
Please browse through other issues.
