### ISSUE TITLE
Icon not visible on hovering button 

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2448]
**Describe the bug**

While hovering the login with facebook button, the facebook icon is neligibly visible

**To Reproduce**
1. Go to 'login'
2. Hover on' Login with Facebook'
3. See error

**Expected behavior**

the icon should be visible while hovering over the button

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35539313/55331869-d326f100-54b1-11e9-9765-38af05658724.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser : chrome
 - Version : 71.0.3578.98 

**Additional context**

Working on it, please review the issue

**Comment by mohitm15** [comment]
@mariobehling Can I add a custom CSS file because its working fine.

**Comment by ritikamotwani** [comment]
@mohitm15 , no you cannot add a custom CSS file for a change this trivial.

**Comment by CosmicCoder96** [comment]
This button is being commented out for now.

**Comment by mohitm15** [comment]
@CosmicCoder96 okay
