### ISSUE TITLE
Inactive users shows deleted users

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-frontend#2455]
**Describe the bug**

When logged in as an admin, in the users tab under inactive users, deleted user is shown in place of inactive user

**To Reproduce**
1. Go to Admin > Users
2. Click on inactive users
3. Scroll down

**Expected behavior**

only inactive users must be shown

**Screenshot**

![inactive shows deleted](https://user-images.githubusercontent.com/19776278/55316598-64836c80-548c-11e9-99fb-8f72e2a52dfe.png)

that inactive user is a deleted user
![inactive shows deleted 2](https://user-images.githubusercontent.com/19776278/55316602-664d3000-548c-11e9-92ba-6c4b4920b993.png)

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

working on it

**Comment by shreyanshdwivedi** [comment]
Thanks @prabhupant
I'm working on it :)

**Comment by prateekj117** [comment]
@shreyanshdwivedi If you haven't spent much time on it, may I work on this issue?

**Comment by shreyanshdwivedi** [comment]
@prateekj117 @uds5501 I'll be updating it by tonight.

**Comment by pradeepgangwar** [comment]
Correctly fixed by #2554
