### ISSUE TITLE
Selecting a null value from drop down table

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2458]
**Describe the bug**

Displays an option for a null value in the drop-down table if no speaker is created before and we are adding a new speaker.

**To Reproduce**
1. Go to 'Create event'
2. Click on 'Create session'
3. Scroll down to 'Choose a speaker '

**Expected behavior**

 It should not provide null value in the drop-down table if no speaker is selected before.

**Screenshots/GIF**

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/35539313/55422925-75220880-559a-11e9-93a6-c35acf8d56e9.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser : Chrome
 - Version : 71.038

**Additional context**

Working on it, reviews required

**Comment by mohitm15** [comment]
@CosmicCoder96 Please review it

**Comment by shreyanshdwivedi** [comment]
@mohitm15 any update?

**Comment by mohitm15** [comment]
@shreyanshdwivedi busy during last 2-3 days but started working on it. Soon push a PR 😃

**Comment by uds5501** [comment]
@mohitm15 I have a solution ready on my local, if you allow, I can take over and immediately push the PR!

**Comment by mohitm15** [comment]
I had to made changes locally but waiting for mentor's review @uds5501

**Comment by shreyanshdwivedi** [comment]
@mohitm15 mentor's review for what? Atleast tag a mentor if you have any query. It has been 13 days since you open this issue, please push a PR

**Comment by uds5501** [comment]
@mohitm15 if you aren't planning to push a PR, mind if I do?

**Comment by kushthedude** [comment]
I think there is already a issue for this

**Comment by CosmicCoder96** [comment]
Fixed in https://github.com/fossasia/open-event-frontend/pull/2874
