### ISSUE TITLE
Active users shows inactive users too

### ISSUE THREAD

**Issue by prabhupant** [fossasia/open-event-frontend#2460]
**Describe the bug**

in the active users section under the users tab in admin, inactive users are also shown with the active users

**To Reproduce**

**Expected behavior**

only active users should be shown

**Screenshot**

![active shows inactive](https://user-images.githubusercontent.com/19776278/55318356-3869ea80-5490-11e9-9ade-aec8dd7ba19a.png)

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

working on it

**Comment by mohitm15** [comment]
@prabhupant Can you clarify steps to reproduce it

**Comment by uds5501** [comment]
@prabhupant This has been resolved in #2459

**Comment by uds5501** [comment]
@CosmicCoder96 Please close this?
