### ISSUE TITLE
Typo in 'Order Summary' and wrong reference for 'Events Link'

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2464]
**Is your feature request related to a problem? Please describe.**

A typo and non understandable language for Events Link Reference.
**Describe the solution you'd like**

Correct the Typo

**Additional context**

![image](https://user-images.githubusercontent.com/44091822/55471310-1060bf80-5627-11e9-84bf-541ef0d0cb1f.png)

**Comment by mohitm15** [comment]
I think it is written correct @kushthedude

**Comment by kushthedude** [comment]
Whats the spelling of registration @mohitm15

**Comment by mohitm15** [comment]
Oh ..I was checking whether sentence is meaningful or not ..😁
Go for it..

**Comment by kushthedude** [comment]
Lol 😆
