### ISSUE TITLE
Different currency symbols in sales amount while previewing an event

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2468]
**Describe the bug**

Different currency symbols appeared in the sales amount in `overview` section and in viewing `tickets` section. In the gif below (US$ in first window and then ₹ in second window).

**To Reproduce**
1. Go to 'Create event and publish it'
2. Click on 'Overview section'
3. Scroll down to 'sales amount currency symbol'
4. Click on 'Tickets section'
5. Scroll down to 'sales amount currency symbol'
6. See error

**Expected behavior**

 Currency symbols should be the same.

**Screenshots/GIF**

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/35539313/55475986-fd53ec80-5632-11e9-9bbb-c216f5336993.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser:  chrome
 - Version : 71.0398

**Additional context**

Review this issue
Working on it

**Comment by shreyanshdwivedi** [comment]
@mohitm15 I think there is already an issue open for this - https://github.com/fossasia/open-event-frontend/issues/2444

**Comment by kushthedude** [comment]
Its a long due issue @mohitm15 which is handled in #2444 , You may close it
