### ISSUE TITLE
Login success should redirect to the last page user wanted to access.

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2470]
**Describe the bug**
Say a logged out user click on create event, user is redirected to login page, which on success redirects to home page.

**Expected behavior**
Login success should redirect to the last page user wanted to access.

**Additional context**
Working on it.

**Comment by kushthedude** [comment]
Don't you think its similar to #2396  , But a more general implementation !

**Comment by CosmicCoder96** [comment]
Duplicate of #2396 - will be fixed when it is solved.
