### ISSUE TITLE
Implementation of Exact Message with Specific Pop-up , Whenever a attendee checks-in or checks-out .

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2471]
**Is your feature request related to a problem? Please describe.**

- No , not related to a problem , but an enhancement if mentors would like to consider.
- Whenever an attendee checkouts , There should specific pop-up like "Attendee Checkout Successfully" which should be in red dialogue box.
- Whenever an attendee is checked in Dialogue box should say "Attendee checked-in successfully" 

**Describe the solution you'd like**

Implementing this enhancement .

**Additional context**

![image](https://user-images.githubusercontent.com/44091822/55519299-db8b5180-5694-11e9-8540-c677012431b6.png)
Something Like This

**Comment by kushthedude** [comment]
@CosmicCoder96 @iamareebjamal , Your feedback ?

**Comment by CosmicCoder96** [comment]
Proceed -- and box should be green to denote success, not red.
