### ISSUE TITLE
Disable the fields and the buttons if the user is unverified

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2474]
**Is your feature request related to a problem? Please describe.**

No, but a feature that is worth consideration.
Currently a user may create an event and upon submission, maybe greeted with an error that he/she can't create an event and lose all the data. 

I propose that we show a "You are unverified and unverified users can't publish an event" and disable the fields and the save draft and forward buttons accordingly.

![image](https://user-images.githubusercontent.com/21087061/55620649-07075c80-57b9-11e9-8a4b-5736034d201d.png)
 
**Additional context**

I would like to work on it

**Comment by uds5501** [comment]
@CosmicCoder96 Please let me know if it's a valid enhancement for the project or not?

**Comment by CosmicCoder96** [comment]
Just disabling the buttons is enough.

**Comment by uds5501** [comment]
Understood, pushing a PR!

**Comment by prateekj117** [comment]
@uds5501 May I work on this issue if you haven't spent much time on it.

**Comment by uds5501** [comment]
@prateekj117 I have made the local changes already and will be pushing a PR soon, actually a bit caught up in college work and mid sems

**Comment by prateekj117** [comment]
@uds5501 No issue. :+1:
