### ISSUE TITLE
Change notification icon from mail to bell.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2475]
**Describe the bug**

Currently the notification icon has a `mail` as its icon which is more appropriate for messages rather than notifications. `bell` icon is more suitable for notifications.

**To Reproduce**
1. Go to '/'
2. See error

**Expected behavior**

The notification icon should be bell icon.

**Screenshots**

![Screenshot from 2019-04-05 20-41-28](https://user-images.githubusercontent.com/21174572/55637823-8742b780-57e3-11e9-9b7a-cb8da4304308.png)
**Additional context**

I am working on this issue.

**Comment by kushthedude** [comment]
Refer to https://github.com/fossasia/open-event-frontend/pull/2476#issuecomment-491972121

**Comment by liveHarshit** [comment]
@kushthedude It should re-open now according to @mariobehling and @iamareebjamal as discussed in the meeting. 
https://github.com/fossasia/open-event-organizer-android/pull/1920#pullrequestreview-278763417
