### ISSUE TITLE
Implement toggle password in settings.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2477]
**Describe the bug**

In settings `Password` section, there isn't any option to toggle show password similar to one present in `Login` and `Signup`.

**To Reproduce**
1. Go to '/settings/password'
2. See error

**Expected behavior**

There should be a toggle button to toggle visibility of password for all the 3 fields.

**Screenshots**

![Screenshot from 2019-04-05 20-50-10](https://user-images.githubusercontent.com/21174572/55638403-b574c700-57e4-11e9-941a-c3254c7c86b4.png)

**Additional context**

I am working on this issue.

**Comment by mohitm15** [comment]
@Anupam-dagar you can also add toggle eye icon instead of button

**Comment by Anupam-dagar** [comment]
@mohitm15 Button is added on purpose, I don't think adding 3 eye icons is a good idea, also all 3 icons will function the same way. In regards to the eye icon instead of text in current button, it doesn't fits well, since an eye icon adjacent to save button will be confusing to users so as to what it functions, people will get to know about it only after clicking it.

**Comment by mohitm15** [comment]
@Anupam-dagar Okay ..no problem
 But mention here too that you had opened a PR for that. I think you write the issue no incorrectly in the PR
:smiley_cat:

**Comment by Anupam-dagar** [comment]
@mohitm15 Thanks for pointing it out, I had missed a space in the issue no mentioned in PR.
