### ISSUE TITLE
No. of Sent Mails on Admin Dashboard incorrect

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2481]
The admin dashboard on the test site shows a negative number of emails sent.

Compare: https://next.eventyay.com/admin

![Screenshot from 2019-04-06 20-16-13](https://user-images.githubusercontent.com/1583873/55669466-5ed1c080-58aa-11e9-977e-82d61b339d04.png)

**Comment by mohitm15** [comment]
@mariobehling should I work on this issue???

**Comment by kushthedude** [comment]
Should not this be okay cause , its test server and the functionality is working well on actual frontend 😕

**Comment by kushthedude** [comment]
@CosmicCoder96 How do i replicate this issue on my local?

**Comment by CosmicCoder96** [comment]
@kushthedude it was because of some unrefactored legacy data, it is fixed now.
![image](https://user-images.githubusercontent.com/17252805/58512284-4ce80c00-81cf-11e9-9c8d-4ea0ebb56e31.png)
