### ISSUE TITLE
Refresh Dashboard once event has been deleted

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2483]
When a user deletes their own event the dashboard still shows the event even though it has been deleted. 

Expected: The dashboard page should refresh after the event is deleted to reflect the status on the site.

Compare: https://next.eventyay.com/events/live

**Comment by kushthedude** [comment]
@mariobehling i think i made this issue and made a PR too in #2259 but people said it is not reproducible should i reopen the PR ?
@CosmicCoder96
