### ISSUE TITLE
The eye toggle function should be reversed

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2484]
**Is your feature request related to a problem? Please describe.**

No, not a bug but a feature request , Like in google login box , When password is unhidden Eye is shown and when password is hidden Eye with dash is shown . 

**Describe the solution you'd like**

I would like to make it implement for open event too

**Describe alternatives you've considered**

No alternatives are available for this 

**Additional context**

![image](https://user-images.githubusercontent.com/44091822/55670562-b587cc00-58a3-11e9-8900-90392e461c7d.png)
![image](https://user-images.githubusercontent.com/44091822/55670565-b9b3e980-58a3-11e9-8a88-6ae138a56030.png)

**Comment by kushthedude** [comment]
I am on it

**Comment by mohitm15** [comment]
@kushthedude  I think this is working fine. 
When you want to see the password , you click the open eye.
When you want to hide the same , you click the closed eye.
It is different from google sign in

**Comment by mohitm15** [comment]
> @kushthedude I think this is working fine.
> When you want to see the password , you click the open eye.
> When you want to hide the same , you click the closed eye.
> It is different from google sign in
> ![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/35539313/55670862-fb925f00-58a6-11e9-97dd-834a134395c6.gif)
There are more issues to work upon bro!!

**Comment by kushthedude** [comment]
Thats what i am saying to implement like google - sign in ,Not different from it bro

**Comment by Anupam-dagar** [comment]
@kushthedude This was a design choice from my side. I put up an open eye signifying that you click on it to show password and an slash eye signifying that you click on it to hide password.
Still if this has to be implemented, I guess its better to wait for mentors review.
CC: @CosmicCoder96 @ritikamotwani

**Comment by mohitm15** [comment]
@Anupam-dagar Agreed with you. That's what I am saying earlier :smile:

**Comment by kushthedude** [comment]
@CosmicCoder96 What you think about it should it be done like google or left?

**Comment by CosmicCoder96** [comment]
It’s fine the way it is for now - I don’t like the way eye icon is implemented anyway. I will be changing it soon.

**Comment by kushthedude** [comment]
@CosmicCoder96 cool 😆
