### ISSUE TITLE
Comment out "login with Facebook" which is not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2509]
The FB login is not working. Also we have not tested and established the flow of how to add FB to an existing account. Please comment out the login with FB functionality for now.

Only allow login with Email for now.

**Comment by harsh-jindal** [comment]
@mariobehling I am working on it.

**Comment by mohitm15** [comment]
@harsh-jindal sir if you are busy ,should I push PR , l had already made changes😃

**Comment by iamareebjamal** [comment]
@mariobehling Now, it is implemented completely, but not reflected on the production server. I don't have access to the FB app to make necessary changes. So we can comment it out, or just add app settings and it will start working
