### ISSUE TITLE
No margin between image pickers once images are picked

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2513]
**Describe the bug**

Once the images have been uploaded, there is virtually no space between the images in the creation form in mobile view

**To Reproduce**
1. Go to /create
2.  Upload images
3. See error

**Expected behavior**

There should be space between both the images

**Screenshots**

![Screenshot from 2019-04-07 20-07-19](https://user-images.githubusercontent.com/21087061/55685294-06fe8c80-5972-11e9-875a-d5e0c960844d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Galaxy S5
 - Browser [e.g. stock browser, safari] chrome

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
Use a different approach to tackle this without changing the image upload widget.

**Comment by uds5501** [comment]
@CosmicCoder96 okay, on it
