### ISSUE TITLE
Remove ticket table if there is no ticket in the event

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2516]
**Describe the bug**

Currently, we have a ticket table in the Tickets section of event-overview. which renders an empty table when event has no tickets.

**To Reproduce**
1. Create an event with no tickets
2. Go to event overview
3. Scroll down to Tickets

**Expected behavior**

If there are no tickets to show, simply pass a message stating "There are no tickets for this event"

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/55688218-cdd71400-5993-11e9-9cac-486c765d0f69.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04 LTS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by kushthedude** [comment]
Why dont we leave this @uds5501 as if you are thinking for tickets , than sponsors need to be made optional too . ?

**Comment by uds5501** [comment]
@kushthedude Look at the sponsors table. It has already been handled. Besides, an empty table with only the headers makes no sense either :)
