### ISSUE TITLE
Minor bug in 'Links and Social Media' for event

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2519]
**Describe the bug**

Whenever a external event url is added for a event it is not getting shown in event overview section.

**To Reproduce**

Steps to reproduce the behaviour:

1. Add an 'External Event URL'
2. Go to 'Event Overview'
3. Scroll down to 'General Info'

**Expected behaviour**

All links should be shown .

**Screenshots**

*Event Details*
![image](https://user-images.githubusercontent.com/44091822/55690904-28cd3300-59b5-11e9-9408-1daf3c83330b.png)

*Overview Section*
![image](https://user-images.githubusercontent.com/44091822/55690905-2c60ba00-59b5-11e9-8e97-68988e573c1f.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

Working On It

**Comment by kushthedude** [comment]
On it

**Comment by uds5501** [comment]
@kushthedude It is meant to be like that. That space is for additional social media links only , the "external event link" is accommodated in the main event page itself

**Comment by kushthedude** [comment]
@uds5501 but on the event page other social links are also handled and i dont think it would be left intentional, just imagine a admin has to go all the way to event pagefor external link and he can see other links in overview . Doesnt makes sense 🙄

**Comment by ritikamotwani** [comment]
@kushthedude check the working of v1.
![image](https://user-images.githubusercontent.com/22127980/55701135-96ed1680-5a04-11e9-8d85-3a84a83b2a0a.png)
![image](https://user-images.githubusercontent.com/22127980/55701142-9c4a6100-5a04-11e9-9e81-54e783c64cd4.png)
Not required for now.
