### ISSUE TITLE
Addition of ‘Mark As Unread’ in notification panel

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2524]
**Is your feature request related to a problem? Please describe.**

Not related to a problem , just an enhancement if mentors will approve.
Currently there is only ‘Mark As Read’ option available in notification panel ,I would like to add ‘Mark As Unread’ option in panel too so that user can remind himself for some work or some undue notification.

**Describe the solution you'd like**

Addition of ‘Mark As Unread

**Additional context**

I would like to work upon it.

**Comment by kushthedude** [comment]
@CosmicCoder96 Your thoughts on it ?

**Comment by ritikamotwani** [comment]
This is not required.
