### ISSUE TITLE
Event placeholder image too pixelated

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#2525]
**Describe the bug**
The default placeholder image for an event is of a low resolution and gets blurred when we navigate to the event page

**Screenshots**
![Screenshot from 2019-04-08 16-00-45](https://user-images.githubusercontent.com/25197147/55699843-55e80880-59ea-11e9-871a-e24e4966b938.png)

**To Reproduce**
1. Go to any event
2. See the blurry image.

**Expected behavior**
Would recommend a high definition image so that it would look a little more appealing.

**Additional context**
Working on it

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Any suggestions for a new placeholder?

**Comment by mohitm15** [comment]
@mrsaicharan1 maybe this is not a priority..it can be changed anytime 😃

**Comment by mrsaicharan1** [comment]
Agreed
