### ISSUE TITLE
Whitespace missing between textfield and buttons on basic details page

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2528]
**Describe the bug**

Whitespace missing between textfield and buttons on basic details page under the ticketing system

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create event''
2. Scroll down to 'Ticketing section'
3. See error

**Expected behaviour**

 A line break should be present there.

**Screenshots**

![Screenshot 2019-04-08 12:15:40](https://user-images.githubusercontent.com/35539313/55705576-b6804100-59fc-11e9-9ec8-345abb3a9671.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04
 - Browser Chrome
 - Version 71.0398

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
It has been discussed before -- dont' need it.

**Comment by mohitm15** [comment]
@CosmicCoder96 Just consider the changes
