### ISSUE TITLE
Phone number in contact info field of settings accepting text data

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2531]
**Describe the bug**

Currently the phone number field in contact info section of settings accepts text input also. Phone numbers should only be digits.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/settings/contact-info'
2. Add textual phone number
3. See error

**Expected behaviour**

Phone number field should accept only numerical data.

**Screenshots**

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/21174572/55706710-7f5f5f00-59ff-11e9-924a-fece7b91bc91.gif)

**Additional context**

I am working on it. Will submit the patch by tonight.

**Comment by CosmicCoder96** [comment]
@Anupam-dagar this issue has been opened before, still is.

**Comment by Anupam-dagar** [comment]
My bad, I'll keep a note of it.

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I found this https://github.com/fossasia/open-event-frontend/issues/2345, but it is closed. Please reopen that issue.
