### ISSUE TITLE
Aligning the options to preview, edit event boxes horizontally in mobile view

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2541]
**Is your feature request related to a problem? Please describe.**

The icons of the boxes shown in the previewing the event are shown vertically taking a lot space in the mobile view.

**Describe the solution you'd like**

To align them horizontally

**Describe alternatives you've considered**

We can also use drop down menu for this thing

**Screenshot**
https://photos.app.goo.gl/4a4H58WeBhqxJPv98

**Additional context**

Share your views, I would like to work on it.

**Comment by mohitm15** [comment]
@CosmicCoder96 what are your thoughts??

**Comment by CosmicCoder96** [comment]
@mohitm15 make them horizontal only for the mobile view. No dropdowns.

**Comment by mohitm15** [comment]
@CosmicCoder96 sure l will make them horizontally

**Comment by kushthedude** [comment]
There should not he multiple PR and multiple issues for such a trivial change

**Comment by uds5501** [comment]
@mohitm15 mind if I take over?

**Comment by kushthedude** [comment]
@uds5501 he has already did this change in one place, i think it would be better if @mohitm15 do it all across the app 😅 .
