### ISSUE TITLE
When scrolling to a target , The target name should get highlighted .

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2544]
**Describe the bug**

In the sidebar when user clicks on Scrollable objects and button doesn't highlights their heading

**To Reproduce**

Steps to reproduce the behaviour:

1. View any event
2. Click on *Scrollable object like Tickets or Getting Here* .
3. They dont get highlighted and info is highlighted rather.

**Expected behaviour**

They should be highlighted as 'info'
**Screenshot**

![image](https://user-images.githubusercontent.com/44091822/55802447-e3644f00-5af5-11e9-824b-dcffd5f50b87.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Additional context**
I am on it

**Comment by uds5501** [comment]
@kushthedude they are being highlighted correctly. I don't see the error there

**Comment by kushthedude** [comment]
@uds5501 try to click on getting here , you will see info is highlighted not the getting here

**Comment by IshaGupta18** [comment]
@kushthedude I am taking a shot at this one!

**Comment by kushthedude** [comment]
@IshaGupta18 go ahead

**Comment by IshaGupta18** [comment]
I am facing a couple of problems while setting up the repo, whom can I contact to resolve those problems?

**Comment by kushthedude** [comment]
@IshaGupta18 Send your query in gitter channel

**Comment by uds5501** [comment]
@IshaGupta18 Please join the open-event-frontend and open-event-server gitter channels for any query.

**Comment by IshaGupta18** [comment]
Okay, thanks a lot both!

**Comment by geetchoudhary** [comment]
@kushthedude , Can I work on this? I see that almost six weeks have passed since it has been assigned to @IshaGupta18.

**Comment by kushthedude** [comment]
Sure go on

**Comment by snitin315** [comment]
I am workin on this issue.
