### ISSUE TITLE
Add admin/sales/locations (UI only).

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#255]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Screenshot: 
![locations](https://user-images.githubusercontent.com/17925669/27259056-0dd6aef8-5428-11e7-8c24-1d2b5f3dc266.png)

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 Please assign.

**Comment by niranjan94** [comment]
Will be assigned once the system images PR is resolved.
