### ISSUE TITLE
Cant submit proposal through CFS , Infinite loader appear 

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2552]
**Describe the bug**

When 'Track Field' is left empty in 'call for speaker', an infinite loader appears

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Call For Speaker'
2. Submit a session with track field empty
3. See error

**Expected behaviour**

It should say, Unexpected error occurred or scroll to that field.

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/55842655-0b819b80-5b52-11e9-82cf-7ad0f644c451.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari 
 - Version: 12.0.2

**Additional context**

Working on it

**Comment by kushthedude** [comment]
@shreyanshdwivedi I think it's not only due to the empty track field, But Case is also same with track field filled

**Comment by uds5501** [comment]
@kushthedude taking this one.

**Comment by hpdang** [comment]
experienced similar problem, on chrome, Ubuntu 18.04.1

**Comment by kushthedude** [comment]
@CosmicCoder96 I would like to give it one more try. Will push the PR by tonight.
