### ISSUE TITLE
Inconsistency in slides text while viewing session.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2558]
**Describe the bug**

While submitting a session, a user can either upload the slides or provide a link to the slides.
In both the cases the text shown under slides is `Download`, this text is helpful for viewer to know about the slides but one will on first impression think that slides will get downloaded on clicking it which is not true.

Change the text to `Link to Slides` when user has provided a link for the slides and keep it `Download` when user has uploaded the slides.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my-sessions/s/<session-id>'
2. Scroll down to 'slides'
3. See error

**Expected behaviour**

`Link to Slides` when user has provided a link for the slides and `Download` when user has uploaded the slides.

**Screenshots**

![Screenshot from 2019-04-10 11-25-38](https://user-images.githubusercontent.com/21174572/55854825-71d2e200-5b83-11e9-8b3f-5b675d834d75.png)

**Additional context**

I am working on it.

**Comment by CosmicCoder96** [comment]
https://github.com/fossasia/open-event-frontend/pull/2565#issuecomment-482017397
