### ISSUE TITLE
In 'Guest Order Form' clicking on sign-in makes a unnecessary scroll

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2568]
**Describe the bug**

Order a ticket as a guest, and enter the email of a pre-existing user and then click on sign-in.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Any Events Ticket'
2. Order Some tickets
3. Enter Email of a preexisting user, click on sign-in without filling the password field.

**Expected behaviour**

No scroll should be there
**Screenshots**

<a href="https://imgflip.com/gif/2ya62s"><img src="https://i.imgflip.com/2ya62s.gif" title="made at imgflip.com"/></a>

**Desktop (please complete the following information):**
 - OS:MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Comment by kushthedude** [comment]
@CosmicCoder96 I was looking into it and I am unable to find the culprit causing this scroll.

**Comment by uds5501** [comment]
@kushthedude I can confirm that this behaviour happens at literally any form that requires validation if that field fails to confirm the validation rule

**Comment by kushthedude** [comment]
@uds5501 i think its due to some package which we are using to scroll and due to this the side bar scroll is buggy too in various browsers . I think using another package could be a option but i am not sure changing a package is appreciable.

**Comment by uds5501** [comment]
I think I found the error. 
In `app/mixins/form.js`

```js
  autoScrollToErrors : true,
  autoScrollSpeed    : 200,

```

@kushthedude If you allow, I would like to go on and fix this one

**Comment by kushthedude** [comment]
Damn i didnt look into mixins , cool push the PR dude

**Comment by uds5501** [comment]
@kushthedude Thanks

**Comment by kushthedude** [comment]
@uds5501 but there is an issue in it

**Comment by uds5501** [comment]
@kushthedude Yes, how do we know if it has been passed via a modal or an controller form

**Comment by kushthedude** [comment]
If you just change this value , then there are many other forms in which invalid authentication , scroll back to the error field , so need to find some other way i think

**Comment by kushthedude** [comment]
Lets think some other way @uds5501

**Comment by uds5501** [comment]
@kushthedude I got it. I will push a PR and explain there!

**Comment by kushthedude** [comment]
Go on
