### ISSUE TITLE
Non uniform colours of buttons in the application.

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#257]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The colours of buttons are different and not uniform across the application 
eg. In settings route the save buttons are blue in  colour while in admin the buttons are teal.
 **Settings**
![screenshot from 2017-06-18 14-31-38](https://user-images.githubusercontent.com/12807846/27259544-f5fa23e0-5432-11e7-8b84-f4d92d8b8f2c.png)
**Admin**
![screenshot from 2017-06-18 14-31-58](https://user-images.githubusercontent.com/12807846/27259545-f5fe54b0-5432-11e7-9bed-739e8c4c3d11.png)

**Expected behavior:**
The colour scheme for the buttons should be uniform across the application.

@niranjan94 Please suggest a colour scheme that would, be uniform across the application.

**Comment by utkarshnath** [comment]
@geekyd @niranjan94 plz assign me this

**Comment by niranjan94** [comment]
Go for teal for all save buttons.

**Comment by geekyd** [comment]
@utkarshnath Before taking new Issues please get #200 merged. Thanks

**Comment by utkarshnath** [comment]
@geekyd patches sent for #200

**Comment by CosmicCoder96** [comment]
@utkarshnath Please proceed.
