### ISSUE TITLE
Don't allow user to edit session details after the event has passed or the session is approved.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2570]
**Describe the bug**

Currently the user can edit the session after the session getting approved. The user can also edit the session after the event has been passed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'my sessions'
2. Click on 'edit session'
3. See error

**Expected behaviour**

User shouldn't be allowed to edit the session after session getting approved or the event has passed.
**Screenshots**

**Additional context**

I am working on this.

**Comment by ritikamotwani** [comment]
In our use case, the opposite of this proposed change is a requirement. When a session is approved, people are always given feedback regarding that. They continue to improve their session. They often upload the session slides at the last moment or keep changing them. 
After the event has passed, speakers who were a no-show may need to be removed from the session, or the speaker may want to correct their slides, if attendees request them.
