### ISSUE TITLE
Cannot edit deleted users

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2573]
**Describe the bug**
Edit button is there in deleted users

**Expected behaviour**
Cannot edit deleted users

**Screenshots**
![u](https://user-images.githubusercontent.com/19900978/55942410-f5630080-5c61-11e9-81cc-a6a56a312792.png)

**Additional context**
I am working on it

**Comment by ritikamotwani** [comment]
The edit button should not be there in deleted users, instead of the edited button it should have a button to restore the user.
Remove the edit button if the user is deleted.
