### ISSUE TITLE
Phone number not validated

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2574]
**Describe the bug**
Phone number not validated on speaker create page

**Expected behaviour**
Phone number should be validated

**Screenshots**
![ps](https://user-images.githubusercontent.com/19900978/55942631-73270c00-5c62-11e9-8308-df965321e681.png)

**Additional context**
I am working on this

**Comment by kushthedude** [comment]
@shubham3211 I think there was some PR related to it
