### ISSUE TITLE
Deleted user status should be deleted

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2575]
**Describe the bug**
Deleted user status should be deleted

**Expected behaviour**
Deleted user status should be deleted

**Screenshots**
![u1](https://user-images.githubusercontent.com/19900978/55944328-fdbd3a80-5c65-11e9-8bdd-9209130e4740.png)

**Additional context**
I am working on it

**Comment by shreyanshdwivedi** [comment]
@shubham3211 there is already an issue for this. https://github.com/fossasia/open-event-frontend/issues/2550
Please close this issue :)
