### ISSUE TITLE
When user changes his email , A confirm E-mail pop-up should appear .

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2577]
**Is your feature request related to a problem? Please describe.**

No, Just a minor enhancement, when a user changes his email, A confirm email popup should appear or there should be a button to change his email, Where there is validation for old email.
 
**Screenshot**
![image](https://user-images.githubusercontent.com/44091822/55950516-bf7a4800-5c72-11e9-9397-91beba6adf0a.png)

**Additional context**

If considered appropriate I would work on it

**Comment by kushthedude** [comment]
@CosmicCoder96 What are your thoughts on it ?

**Comment by ritikamotwani** [comment]
No, not required for now.
