### ISSUE TITLE
Body overflow in Create Event Section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2579]
**Describe the bug**

On the Create Event form there is body overflow.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Create Event'
2. See error

**Expected behaviour**

There should be no overflow

**Screenshots*

![image](https://user-images.githubusercontent.com/44091822/55951264-75926180-5c74-11e9-94ae-ed3f66d8919d.png)

**Desktop (please complete the following information):**

 - OS:MacOS Mojave
 - Browser: Safari
 - Version: 23.0

**Additional context**

Work on it

**Comment by kushthedude** [comment]
@CosmicCoder96 This error is caused due to some recently merged PR, What should be done, Should I solve it or Find the changes which are causing it

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Can you reproduce it?

**Comment by CosmicCoder96** [comment]
@kushthedude
Which PR caused this ? Can you pinpoint it. Consider it a high priority.
Event wizard was working fine AFAIK

**Comment by kushthedude** [comment]
@CosmicCoder96 lookin into it 👍

**Comment by ritikamotwani** [comment]
@kushthedude , I can't reproduce the issue.
Can you please confirm?

**Comment by kushthedude** [comment]
@ritikamotwani As i mentioned this overflow is present on safari and not in chrome .

**Comment by kushthedude** [comment]
@CosmicCoder96 After trying it on other Mac , I came across that it's a browser specific issue which exist only on Mac safari , What should be done ?

**Comment by kushthedude** [comment]
Duplicate of #2669
