### ISSUE TITLE
Unverified User can't create event , After changing permissions

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2580]
**Describe the bug**

After changing permissions from `Admin/Permission`, When I allow an unverified user to publish an event , The user cant publish event

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Admin/Permission'
2. Permit Unverified user to create and publish event
3. Go to event creation

**Expected behaviour**

Settings should get updated as the Admin changes permissions

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/55952749-fb63dc00-5c77-11e9-83ad-fda720d09567.png)
![image](https://user-images.githubusercontent.com/44091822/55952755-fdc63600-5c77-11e9-84c2-d651366f9239.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Comment by uds5501** [comment]
@kushthedude Can't replicate

**Comment by kushthedude** [comment]
Yeah it was my wrong it was caused due to location empty
