### ISSUE TITLE
Implement pagination for My Tickets section

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2584]
**Is your feature request related to a problem? Please describe.**

Currently, pagination is not implemented in `My Tickets` section. When tickets are queried only 20 tickets are returned at max.

**Describe the solution you'd like**

I will like to implement pagination for `My Tickets` section

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi Implement it like I have done it for events on the home page. (Lazy-infinity-loading)
Reference: next.eventyay.com

**Comment by prateekj117** [comment]
@shreyanshdwivedi May I work on this issue?

**Comment by prateekj117** [comment]
@shreyanshdwivedi Any update on this?

**Comment by shreyanshdwivedi** [comment]
@prateekj117 I was busy with something else. I'll push a PR soon, maybe by tonight

**Comment by mariobehling** [comment]
This is out of scope as we are using pagination and this would be more of an advanced feature. However, we would need to check if this is really necessary. Right now we need to focus on actually fixing the bugs and getting the actual functionalities working. Therefore closing this.

**Comment by kushthedude** [comment]
@shreyanshdwivedi Will you still be implementing `Infinity-Loader` ?

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 mentioned that he'll be working on it in his scrum.

**Comment by kushthedude** [comment]
👍
