### ISSUE TITLE
Deleted sessions are not visible on event session page

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2586]
**Describe the bug**
Deleted sessions are not visible on event session page like the admin session page

**Expected behaviour**
Deleted sessions should be visible on event session page like the admin session page

**Screenshots**
![e](https://user-images.githubusercontent.com/19900978/55977660-f8cfa980-5cac-11e9-8a21-1a1030bd414e.png)
![a](https://user-images.githubusercontent.com/19900978/55977668-fff6b780-5cac-11e9-8ba6-074e6b624818.png)

**Additional context**
I am working on it.

**Comment by shubham3211** [comment]
@CosmicCoder96  Is this a valid issue?

**Comment by ritikamotwani** [comment]
No, it's not required.
Check version1.
