### ISSUE TITLE
UI for the user profile page

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2591]
**Is your feature request related to a problem? Please describe.**

The UI seems to be very cohesive between the image upload instruction and User name.

**Describe the solution you'd like**

- To minimize the image upload instruction which introduces a line break between.

**Describe alternatives you've considered**

- To enchance the UI for user name ,family name and email.
 
**Screenshot**
![Screenshot 2019-04-12 02:24:07](https://user-images.githubusercontent.com/35539313/55992658-b321d980-5cca-11e9-8fce-ce55cc470397.png)

**Additional context**

Share views, like to work on it

**Comment by mohitm15** [comment]
@CosmicCoder96 What are your views??

**Comment by mohitm15** [comment]
@CosmicCoder96 
But with using the `ui hidden divider` the username and family name are coming in capital irrespective of what written in text field
![Screenshot 2019-04-14 00:02:10](https://user-images.githubusercontent.com/35539313/56083887-872c6280-5e48-11e9-83bf-0a66da3829f8.png)

**Comment by uds5501** [comment]
@mohitm15 use : 
`<div class="ui hidden divider">
</div>`
Instead of `<br>`

**Comment by mohitm15** [comment]
@uds5501 l had used the same 😅😅... l

**Comment by mohitm15** [comment]
div tag

**Comment by mohitm15** [comment]
@CosmicCoder96 review this now
