### ISSUE TITLE
Improve UI of user ticket list 

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2595]
**Describe the bug**
Improve UI of user ticket list 

**Screenshots**
![userTicket](https://user-images.githubusercontent.com/19900978/55995455-29760a00-5cd2-11e9-852d-fc5eec4bf0c9.png)

**Additional context**
I am working on it

**Comment by mohitm15** [comment]
@shubham3211 what improvements does it requires??
