### ISSUE TITLE
Aligning the options horizontally in sponsors section

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2597]
**Is your feature request related to a problem? Please describe.**
 
Aligning the options horizontally in the sponsors section as they are vertical and taking a lot of space in mobile view. Similar to #2541 but in sponsors section

**Describe the solution you'd like**

Make them horizontal

**Describe alternatives you've considered**
 drop-down table but not preferred as earlier discussed in #2541 .

![Screenshot 2019-04-12 03:47:18](https://user-images.githubusercontent.com/35539313/55997441-22ea9100-5cd8-11e9-8655-77a36fa760d9.png)

**Additional context**

working on it.

**Comment by CosmicCoder96** [comment]
Don't open a new issue for each table. Do it all across the app in one PR.
