### ISSUE TITLE
Add UI for admin/sales/organizers

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#260]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
![screenshot from 2017-06-18 15-38-26](https://user-images.githubusercontent.com/12807846/27259932-59da744c-543c-11e7-9758-51dc3a135cec.png)

**Comment by utkarshnath** [comment]
@geekyd plz assign this to me
