### ISSUE TITLE
Overlapped components of scheduler page in mobile view

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2600]
**Describe the bug**

the various components like buttons, tables are not in organized structure i.e. not properly aligned and overlapping each other

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create and publish event'
2. Click on 'Schedules'
3. See error

**Expected behaviour**

 Should be aligned properly.

**Screenshots**

![Screenshot 2019-04-12 04:28:54](https://user-images.githubusercontent.com/35539313/55998474-00f30d80-5cdc-11e9-9ad3-9bcce375a755.png)

**Smartphone (please complete the following information):**
 - Device: Galaxy S5

**Additional context**

Working on it.

**Comment by mohitm15** [comment]
Just once check whether it is browser dependent or not.

**Comment by kushthedude** [comment]
@mohitm15 the scheduler needs a complete makeover so any pr or issue related to scheduler is vague

**Comment by CosmicCoder96** [comment]
@kushthedude Who told you that? @mohitm15 Proceed -- use only semantic UI classes.

**Comment by kushthedude** [comment]
@CosmicCoder96 I was lookin into roadmap and , The scheduler needs to be redesigned as more or less google calendar type , thats why said it .

**Comment by CosmicCoder96** [comment]
@kushthedude Leave the moderation of issues to the mentors. Thanks!

**Comment by mohitm15** [comment]
@CosmicCoder96 sure I will proceed.
@kushthedude thanks for your views.

**Comment by kushthedude** [comment]
@mohitm15 Should i takeover ?

**Comment by mohitm15** [comment]
@kushthedude sorry bro but I'm working on it


_Sent from my VIBE K6 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kushthedude** [comment]
No issue buddy , Go on

**Comment by kushthedude** [comment]
Taking this due to inactivity
