### ISSUE TITLE
Location Field Should be implemented like name .

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2602]
**Is your feature request related to a problem? Please describe.**

The Location which is a required field is implemented wrongly in Basic detail form , As name is required when user clicks submit , It scrolls back to name ,Similar should be implemented for Location .

**Describe the solution you'd like**

Implement Location field similar to name field

**Additional context**

I am working on it

**Comment by kushthedude** [comment]
@ritikamotwani @CosmicCoder96 I observed when we dont fill location button is absent to submit , I propose to implement location field like name like when its empty and we try to submit , We get redirected to the field with a tooltip

**Comment by ritikamotwani** [comment]
No, it's not required. Discussions regarding the location field are ongoing. First of all it is not a required field if you want to save your event and not publish it. And also we intend to hold online events which won't require a location. So any kind of refactoring would be out of scope for this issue. Hence closing it.

**Comment by kushthedude** [comment]
No problem will close the pr too
