### ISSUE TITLE
UI issues in Sessions state section

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2603]
**Describe the bug**

There are few discrepancies in `Sessions` state section -
_`Admin > Sessions`_
- ~~The `Accepted` and `Pending` state have same label color~~
 - ~~There is no filter for `Confirmed` sessions~~
 - The deleted sessions  is not having `Deleted` state.
 - ~~There is delete icon in the `Deleted Sessions`~~
 - The `All` filter is not showing deleted sessions. Wherever `All` filter is used, deleted attributes are also shown, e.g. `Users` etc

_`Manage Events > Sessions`_
 - ~~The `Accepted` and `Pending` state have same label color~~
 - ~~There is no filter for `Deleted` sessions~~
 - ~~The `Speakers` section also have same label color for `Accepted` and `Pending` state~~

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Admin > Sessions`
2. See error

**Expected behaviour**

These UI bugs must be fixed

**Screenshots**

_Admin > Sessions_
![Screenshot_2019-04-12 Deleted Sessions Administration Open Event](https://user-images.githubusercontent.com/25428397/56031961-7bed1000-5d3e-11e9-91c0-61261075e361.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser [e.g. chrome, safari] Mozilla Firefox

**Additional context**

Working on it

**Comment by uds5501** [comment]
@shreyanshdwivedi I think we can leave accepted session's colour as is because it was not there in v1.0?

**Comment by ritikamotwani** [comment]
Have you compared the two versions?

**Comment by shreyanshdwivedi** [comment]
@ritikamotwani @uds5501 I'm unable to open CFS for event on next.eventyay.com but as can be seen in the screenshot attached, we are using green colored tick to change the state of session from `Pending` to `Accepted` and blue colored tick for `Accepted` to `Confirmed. Considering this in mind, I though to change the `Accepted` to green and `Confirmed` to blue.
Your views on this?

**Comment by shreyanshdwivedi** [comment]
@ritikamotwani I've updated the list of bugs to be solved. Can you verify once if these needs fixing?

**Comment by shreyanshdwivedi** [comment]
@ritikamotwani @CosmicCoder96 can you please verify the issue now? I'll update my PR accordingly

**Comment by uds5501** [comment]
@shreyanshdwivedi The updated list looks good. Push a PR and the discussion can take place there.

**Comment by ritikamotwani** [comment]
@shreyanshdwivedi , there should be a deleted icon in the deleted sessions for permanently deleting the record. Check legacy.
