### ISSUE TITLE
Only one of the options should be selected in ticket description

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2604]
**Describe the bug**
Only one of the options should be selected in ticket description 

**To Reproduce**
1. Go to 'Create Event'
2. Click on 'Free Ticket'
3. Scroll down to 'Ticket Description'
4. Both options can be selected

**Expected behaviour**
Only one of the option should be selected.

**Screenshots**
![Screenshot from 2019-04-12 16-11-47](https://user-images.githubusercontent.com/31065687/56032214-2fee9b00-5d3f-11e9-8255-34ce852f7c6e.png)

**Additional context**
Working on it.

**Comment by ritikamotwani** [comment]
Check the behavior on legacy.
The visibility of tickets and their description are exclusive to each other.
