### ISSUE TITLE
Provide http/https in front of website/social link url in edit/view speaker page

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2608]
**Describe the bug**

Currently it is just an text field.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Speakers'
2. Click on 'Edit Speaker'

**Expected behaviour**

We should provide http/https option as it is given in other places.
**Screenshots**

![Screenshot 2019-04-12 at 7 44 48 PM](https://user-images.githubusercontent.com/31013104/56043920-c335c980-5d5b-11e9-9acb-663840eaebf8.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@harsh-jindal this issue is already opened and someone is working on it

**Comment by kushthedude** [comment]
Please see #2428

**Comment by harsh-jindal** [comment]
@kushthedude Cool I'll close this issue. Lot of issues, hard to find if something is already opened.
