### ISSUE TITLE
Add UI for admin/sales/status

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#261]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-06-18 15-40-51](https://user-images.githubusercontent.com/12807846/27259950-af0bbbf6-543c-11e7-87a6-3cf7f3ea3577.png)

**Comment by harshitagupta30** [comment]
I would like to work on this. @geekyd Please assign :+1:
