### ISSUE TITLE
Submitted sessions are showing no count

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2610]
**Describe the bug**

Currently, in admin/events table, the submitted sessions are showing no count.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event
2. Go to admin/event
3. See error

**Expected behaviour**

It should show the proper count of the same

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/56052622-8b388180-5d6f-11e9-8d17-bedb1cecb6e3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] chrome

**Additional context**

I am working on it

**Comment by prateekj117** [comment]
@uds5501 May I work on this issue?

**Comment by uds5501** [comment]
@prateekj117 I already am working on it :)
