### ISSUE TITLE
Add badge to state in admin events

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2612]
**Describe the bug**

Currently theres is no badge at state in admin events.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Admin'
2. Click on 'Events'

**Expected behaviour**

Add badge to state in admin events. This will enhance the UI.
**Screenshots**

![Screenshot 2019-04-12 at 11 24 18 PM](https://user-images.githubusercontent.com/31013104/56056549-20407800-5d7a-11e9-8bc0-9a522241a2a6.png)

**Additional context**

I am working on it.

**Comment by ritikamotwani** [comment]
Not required.
It's not in v1
