### ISSUE TITLE
Add slider to different tokens in System Settings in Admin

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2613]
**Describe the bug**

Currently all the tokens are shown for various social media.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Admin'
2. Click on 'Settings'
3. Scroll down to 'system'

**Expected behaviour**

It would be better if a slider is provided for the tokens.
**Screenshots**

![Screenshot 2019-04-12 at 11 29 06 PM](https://user-images.githubusercontent.com/31013104/56056876-09e6ec00-5d7b-11e9-9fff-b112d14058cb.png)

**Additional context**

I am working on it.

**Comment by ritikamotwani** [comment]
The slider would solve no purpose as leaving those settings blank is not recommended.
