### ISSUE TITLE
cursor should be pointer when user hover over completed

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2614]
**Describe the bug**
When user click on completed he is redirected to orders/all so the cursor should be a pointer.

**Expected behaviour**
cursor should be pointer when user hover over 'completed'

**Screenshots**
![c](https://user-images.githubusercontent.com/19900978/56058126-30f2ed00-5d7e-11e9-85af-a0427a5e950f.png)

**Additional context**
I am working on it

**Comment by shubham3211** [comment]
@CosmicCoder96 I think the link should be removed as the user can click on view orders to see the orders.

**Comment by shreyanshdwivedi** [comment]
@shubham3211 please update the PR associated with the issue
