### ISSUE TITLE
Heroku cannot overwrite directory '/app/tmp/cache/node/cache/bower_components' with non-directory

### ISSUE THREAD

**Issue by gofreddo** [fossasia/open-event-frontend#2616]
**Describe the bug**
When I git push heroku master it gets to:

remote: -----> Caching build
remote:        - node_modules
remote:        - bower_components
remote: cp: cannot overwrite directory '/app/tmp/cache/node/cache/bower_components' with non-directory

**Comment by CosmicCoder96** [comment]
Hi @gofreddo Thanks for reporting.
This should fix it.
```js
heroku config:set NODEMODULESCACHE=false
git commit -am 'rebuild' --allow-empty
git push heroku master
```
Reference: https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

Do revert if it still persists. Thanks!
