### ISSUE TITLE
404 error on refreshing edit speaker details page.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2618]
**Describe the bug**

On refreshing the page while editing the speakers details, the page gives a 404 error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/e/`<event-id>`/cfs/edit/1'
2. Refresh the page
3. See error

**Expected behaviour**

Page shouldn't throw 404 error.

**Additional context**

I am working on this issue.

**Comment by uds5501** [comment]
`e//cfs/edit/1`? I think that should be throwing a 404 or was it a typo? @Anupam-dagar

**Comment by Anupam-dagar** [comment]
> `e//cfs/edit/1`? I think that should be throwing a 404 or was it a typo? @Anupam-dagar

I entered it in markdown comment syntax. Fixed. Thanks for pointing it out.

**Comment by CosmicCoder96** [comment]
Fixed in #3333
