### ISSUE TITLE
Name input accepting special characters

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2620]
**Describe the bug**

Currently Name inputs are accepting special characters which should not be the case 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to User Profile
2. Type any alphanumeric name
3. Submit it

**Expected behaviour**

It should not accept the names containing special characters.

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/56075552-f28f1980-5de1-11e9-8cf9-38f01c9754ac.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome
 
**Additional context**

I would like to work on it!

**Comment by uds5501** [comment]
@pradeepgangwar @CosmicCoder96 @ritikamotwani Before working on it, I would like to confirm if this validation would be necessary

**Comment by CosmicCoder96** [comment]
Leave it for now, will rethink it later.
https://www.w3.org/International/questions/qa-personal-names 
Too much overhead.
