### ISSUE TITLE
Tax Rate should not be negative or more than hundred

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2624]
**Describe the bug**
As Tax rate is given in percent, tax rate field should not allow negative or more than 100 values.

**Expected behavior**
Tax Rate field does not allow negative or more than 100 Value. 

**Screenshots**
![Screenshot from 2019-04-13 12-38-03](https://user-images.githubusercontent.com/31065687/56076010-05591c80-5de9-11e9-8da5-ba2ce9f9c41c.png)

**Additional context**
Working on it.

**Comment by kushthedude** [comment]
@prateekj117 Change the name of issue its misleading
