### ISSUE TITLE
Event information box is not visible in mobile view

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2625]
**Describe the bug**

Event information box is not visible in mobile view while it is visible in desktop view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create and publish event'
2. Click on orders and place order
3. Confirm the order 
4. Switch to mobile view
5. See error

**Expected behaviour**

 Should be visible in mobile view too.

**Screenshots/GIF**
Desktop view:
![Screenshot 2019-04-13 08:40:19](https://user-images.githubusercontent.com/35539313/56076069-e7d88280-5de9-11e9-85a0-910dad36c64c.png)

Mobile view:
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/35539313/56076074-f4f57180-5de9-11e9-9faf-185e8784a10f.gif)

 **Desktop (please complete the following information):**
  - OS: [e.g. iOS] Ubuntu 16.04
  - Browser [e.g. chrome, safari] Chrome
  - Version : 71.0398
**Smartphone (please complete the following information):**
 - Device: iPhone X

**Additional context**

Working on it.

**Comment by uds5501** [comment]
@mohitm15 It has been designed when I redesigned it. So, I don't think that would be necessary. Although do take @CosmicCoder96 views, It can always be redesigned again!

**Comment by mohitm15** [comment]
@CosmicCoder96 What are your views??

**Comment by kushthedude** [comment]
@mohitm15 See on top Event Information is displayed but there is no Margin to reduce the items

**Comment by mohitm15** [comment]
> @mohitm15 See on top Event Information is displayed but there is no Margin to reduce the items

Agreed !!

**Comment by kushthedude** [comment]
Close the issue than 😅

**Comment by mohitm15** [comment]
However, I am trying to make the title box visible and soon push PR :smile_cat:

**Comment by CosmicCoder96** [comment]
It was intentional.
