### ISSUE TITLE
Make the Dropdowns bold if they have been previously selected

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2626]
**Describe the bug**

The Event type, topic and sub-topic should be in bold if they have been selected before so that they can remove the ambiguity whether they have been selected or not

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Edit event route
2. Scroll down to selected event types
3. See error

**Expected behaviour**

They should be written normally as in Event Licenses

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/56076122-8fee4b80-5dea-11e9-9570-10a0d11f285c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it!

**Comment by mohitm15** [comment]
@uds5501 are you talking for the drop -down table for these textfields??

**Comment by uds5501** [comment]
@mohitm15 dropdown tables?

**Comment by mohitm15** [comment]
@uds5501 the functionality of text field is fine but I have a doubt in the drop-down table?? As soon as you click on text field the watermarked text disappears which is fine and also if you select any value from the drop-down table, the selected options get bold too,  then what changes you are telling?

**Comment by uds5501** [comment]
@mohitm15 To make my point clear, I am just looking to make Event Type, topic and subtopic's UI to be exactly like Licenses where I don't need to select another option to make it bold
