### ISSUE TITLE
Clicking on add links should redirect to links part of the basic detail page

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2627]
**Describe the bug**
On the event page, on clicking option to add links, it should open that part of the basic detail page. 

**Expected behaviour**
Direct links and social media feed is present on clicking the button.

**Screenshots**
![Screenshot from 2019-04-13 12-47-46](https://user-images.githubusercontent.com/31065687/56076168-46523080-5deb-11e9-8c0a-b856a2e0eec1.png)

**Additional context**
Working on it.

**Comment by uds5501** [comment]
@prateekj117  Just to clarify, do you mean opening that section of the page?

**Comment by prateekj117** [comment]
@uds5501 Yes.
