### ISSUE TITLE
Functionality to add multiple organizers for an Event 

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2628]
**Describe the bug**
As an Event can have more than one organizer, we should add an option to have multiple organizers for an event.  

**Additional context**
Working on it.

**Comment by uds5501** [comment]
@prateekj117 IMO, there is already a feature for having multiple co organizers and  the organiser can get the option to pass his organizer status to another co organiser.  So, maybe we should just keep the organiser unique otherwise Co-organiser role will not really have any sense

**Comment by CosmicCoder96** [comment]
There is an entire section called manage roles, you can make various organziers, coorganzers from there.

**Comment by prateekj117** [comment]
@CosmicCoder96 I know but shouldn't it be there on the Basic Details Page as well.
