### ISSUE TITLE
Implement Speaker column similar to Session section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2630]
**Describe the bug**

Currently, Speaker only shows no of speakers, I propose to implement it like Session section

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Admin/Events/All'
2. See error

**Expected behaviour**

The table should provide all the specific details as session column.

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/56076899-abaa1f80-5df3-11e9-8360-dcfd4cd44590.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Additional context**

I am on it

**Comment by uds5501** [comment]
@kushthedude  just use the events/dashboard speaker component that I made and re route it to admin/events. That should do

**Comment by kushthedude** [comment]
Lemme try it
