### ISSUE TITLE
Incorrect cover heading for sessions page in mobile view

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2631]
**Describe the bug**

Incorrect cover heading for sessions page in mobile view. The title is Sessions but it was showing Tickets

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create and publish'
2. Click on 'Overview : sessions '
3. Click on Tickets page
4. Switch to mobile view
5. Return back to sessions page
6. See error

**Expected behaviour**

Title should be changed to sessions as we return back to its page

**Screenshots**

![Screenshot 2019-04-13 13:57:54](https://user-images.githubusercontent.com/35539313/56076994-89fd6800-5df4-11e9-974d-18e8284a9c25.png)

**Smartphone (please complete the following information):**
 - Device: iphone X

**Additional context**

Working on it

**Comment by mohitm15** [comment]
@CosmicCoder96 this thing also happening when you overview the event in mobile view .so I will fix the same too

**Comment by kushthedude** [comment]
Not reproducable

**Comment by kushthedude** [comment]
![image](https://user-images.githubusercontent.com/44091822/56077808-106a7780-5dfe-11e9-8252-f363adf4886c.png)

**Comment by mohitm15** [comment]
@kushthedude I think you misinterpreted it. What I am saying is that if you first went to sessions section and then go to ticket section, now you return to sessions page again the title remains the same and needs to be changed.

**Comment by mohitm15** [comment]
> Not reproducable

This is vague

**Comment by kushthedude** [comment]
Not reproducible

> @kushthedude I think you misinterpreted it. What I am saying is that if you first went to sessions section and then go to ticket section, now you return to sessions page again the title remains the same and needs to be changed.

**Comment by kushthedude** [comment]
@uds5501 Can you please confirm it ?

**Comment by uds5501** [comment]
> @kushthedude I think you misinterpreted it. What I am saying is that if you first went to sessions section and then go to ticket section, now you return to sessions page again the title remains the same and needs to be changed.

@mohitm15 I did this exact same thing but I could not reproduce this error.
Did you try clearing the cookies and perform this sequence again?
And if there is any other reproduce able pattern, kindly do let me know

**Comment by CosmicCoder96** [comment]
Reopen if someone can verify it.
