### ISSUE TITLE
Alignment of the submit button at center in mobile view

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2633]
**Is your feature request related to a problem? Please describe.**

Currently, the save button is at left side on profile update and contact info page.

**Describe the solution you'd like**

To enhance UI, align to center in mobile view like in desktop view

**Screenshots**
1.
![Screenshot 2019-04-13 14:32:26](https://user-images.githubusercontent.com/35539313/56077436-d6977200-5df9-11e9-8643-5ee60b2d4d3e.png)
2.
![Screenshot 2019-04-13 14:34:17](https://user-images.githubusercontent.com/35539313/56077440-f038b980-5df9-11e9-999a-816e2747d1d0.png)

 
**Additional context**

I am on it

**Comment by mohitm15** [comment]
@CosmicCoder96 what are your reviews

**Comment by ritikamotwani** [comment]
No, it's not required.
