### ISSUE TITLE
Add search to country dropdown

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2634]
**Describe the bug**

Currently the user has to scroll through various countries to select his country.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Buy ticket'
2. Click on 'Enable ticketing Info'
3. Scroll down to 'Country'

**Expected behaviour**

Make the dropdown a search dropdown
**Screenshots**

![Screenshot 2019-04-13 at 2 49 12 PM](https://user-images.githubusercontent.com/31013104/56077595-c1bbde00-5dfb-11e9-9323-508bccd03d70.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@harsh-jindal I think this dropdown is the standard dropdown of Moment.js, Modifying it would not be appropriate I think. Still take a review from @CosmicCoder96

**Comment by CosmicCoder96** [comment]
@harsh-jindal You can add the search class, also the list of countries is not derived from moment.js, moment.js is for time-related thing.

**Comment by kushthedude** [comment]
@CosmicCoder96 Sorry, My bad
