### ISSUE TITLE
Notify user when he enters same old password as new password

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2636]
**Is your feature request related to a problem? Please describe.**

When a user changes his old password, Notify the user that he has entered the same old password as new password

**Describe the solution you'd like**

Notify user he has entered the same old password as new password

**Additional context**

![image](https://user-images.githubusercontent.com/44091822/56079180-7c54dc00-5e0e-11e9-9a75-613a46b3ccc5.png)

**Comment by kushthedude** [comment]
@CosmicCoder96 @ritikamotwani Should the validation be done ?

**Comment by CosmicCoder96** [comment]
@kushthedude proceed.

**Comment by CosmicCoder96** [comment]
@kushthedude Also open an issue for the same on the server. API should reject it too.

**Comment by mohitm15** [comment]
@kushthedude Can I take over this as I had made changes locally ..just need to push

**Comment by kushthedude** [comment]
@mohitm15 how did you solved it from frontend , it needs changes from api too ?

**Comment by kushthedude** [comment]
See https://github.com/fossasia/open-event-server/issues/5794

**Comment by mohitm15** [comment]
@kushthedude yes , thanks for mentioning

_Sent from my VIBE K6 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kushthedude** [comment]
@shreyanshdwivedi Did your PR got merge ? so that it can be done on frontend too

**Comment by shreyanshdwivedi** [comment]
@kushthedude yes, my PR on server is merged. Refer https://github.com/fossasia/open-event-server/pull/5821

**Comment by prateekj117** [comment]
@kushthedude Any update on this? In case you haven't done much work on it, can I take this one up?

**Comment by kushthedude** [comment]
@prateekj117 Sorry for my delay, I saw the comment from @shreyanshdwivedi today itself will be pushing a PR soon

**Comment by kushthedude** [comment]
Closing in favor of https://github.com/fossasia/open-event-server/pull/5821 
@CosmicCoder96 If you think this should be done in the form of tooltip too, I may work on it , Closing the issue for now
