### ISSUE TITLE
No url validation on sponsor websites

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2639]
**Describe the bug**

Currently, the sponsor website links are not being validated at all

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Sponsor addition 
2. Write any gibberish in sponsor url
3. See error

**Expected behaviour**

The sponsor url should be checked if the url is correct or not

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/56081390-7bca3e80-5e2a-11e9-9b86-2ccfb066b5df.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by kushthedude** [comment]
@CosmicCoder96 @uds5501 I think this needs to be reopened , As i am still able to replicate it
