### ISSUE TITLE
No alert message when user enters same current and new password.

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2646]
**Describe the bug**

When a user enters the same current password to the new password field, it does not warn regarding that both the password are same. Instead, it saves the old password.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'settings'
2. Click on 'password'
3. Enter your current password in all the 3 fields.
4. See error.

**Expected behaviour**

  It should alert the user that both the password are same.
 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : chrome
 - Version [: 71.0398

**Additional context**

Working on it

**Comment by kushthedude** [comment]
I think opened this issue please dont increase the issue count

**Comment by kushthedude** [comment]
See #2636 , I request you please dont create issues which already exist
