### ISSUE TITLE
Showing alert message while activating access code and vice-versa

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2648]
**Is your feature request related to a problem? Please describe.**

Showing alert message box while activating or deactivating the access code like implemented for discount code.

**Describe the solution you'd like**

  Currently a simple update alert get appeared. Wanted to add a message dialog box which will be popped just like in activating/deactivating discount code.

**Describe alternatives you've considered**

Update the message itself which appears at the bottom

**Current status**
![Screenshot 2019-04-14 22:34:38](https://user-images.githubusercontent.com/35539313/56096441-d2f11180-5f05-11e9-8eb9-7fea6308cd22.png)

**Propose to change like this**

![Screenshot 2019-04-14 22:39:11](https://user-images.githubusercontent.com/35539313/56096464-26635f80-5f06-11e9-9e1b-36e46359dff0.png)

**Additional context**

Working on it

**Comment by mohitm15** [comment]
@CosmicCoder96 @ritikamotwani your reviews??

**Comment by kushthedude** [comment]
It should be like this only , every table you see have a option to delete and edit , and adding a addition popup after the user clicks delete would modify or change the design, thats why i think it should be left as it is ,
Still take you reviews from mentors

**Comment by ritikamotwani** [comment]
@mohitm15 this is not required for now.
The buttons have a uniform design in the app.
