### ISSUE TITLE
Ticket sales end doesn't change on event date change.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2649]
**Describe the bug**

Currently while creating an event, ticket sales end date is set to the start date of the event. But if the event dates get changed then the ticket sales end date still remains the same. It might happen the event is over but the sales is open till late time after the event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event
2. Change the event start date.
3. Go to the event page ticket section.

**Expected behaviour**

Ticket sales end date should change accordingly with the event date changes.

**Screenshots**

![Screenshot from 2019-04-15 13-27-20](https://user-images.githubusercontent.com/21174572/56115947-3b7dd400-5f82-11e9-9a45-b878bccbfa6a.png)

**Additional context**

I am working on this.

**Comment by uds5501** [comment]
@Anupam-dagar Can I take over?

**Comment by Anupam-dagar** [comment]
@uds5501 I'll continue working on it.
