### ISSUE TITLE
Show event end date on the event page.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2650]
**Describe the bug**

Currently only the start date of the event is shown on the event page. An event can be of single day or of 3 days. It will be better for the user to know the end date of the event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/e/event-id'
2. See error

**Expected behaviour**

Event end date should be shown to the user.

**Screenshots**

![Screenshot from 2019-04-15 13-32-03](https://user-images.githubusercontent.com/21174572/56116427-6288d580-5f83-11e9-9710-ba687d99fffd.png)

**Additional context**

I am working on this

**Comment by ritikamotwani** [comment]
No, it's not required.
It's neither on legacy nor on eventbrite.

**Comment by Anupam-dagar** [comment]
@ritikamotwani The end date is there on eventbrite
https://www.eventbrite.com/e/angelhack-2019-bangalore-tickets-58778720736
![Screenshot from 2019-04-16 23-35-30](https://user-images.githubusercontent.com/21174572/56233324-7413cf80-60a0-11e9-904b-484ece249cf2.png)
