### ISSUE TITLE
Show event has passed label on the events which are over.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2651]
**Describe the bug**

Currently if the event is over then during filtering of event in the browse events, there is no way to distinguish other than checking dates for a user to know if the event is over or not. A label with text `event has passed` will be better for the user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/explore'
2. Filter for an event which is over.
3. See error

**Expected behaviour**

A label should be shown if the event is over.
**Screenshots**

![Screenshot from 2019-04-15 13-46-28](https://user-images.githubusercontent.com/21174572/56117176-2a829200-5f85-11e9-8d35-5a81a2bfff76.png)

**Additional context**

I am working on this.

**Comment by ritikamotwani** [comment]
No, not required.
Not on legacy or eventbrite.
