### ISSUE TITLE
Download Tickets Button should send JWT Auth Headers 

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#2652]
**Describe the bug**
Related  Discussion: https://github.com/fossasia/open-event-server/pull/5790
Currently, the tickets are prone to a vulnerability issue where any person with the tickets link is able to access it. Thereby, we're refactoring the ticket flow to prevent this. We have implemented the access-control check on the server. In addition, the `Download Tickets` button must route to the ticket-url and  send JWT authorization headers so that the route can handle the request properly.
 
**Expected behaviour**
Needs to send JWT auth headers along with the request.

**Additional context**
Working on it.

**Comment by CosmicCoder96** [comment]
https://github.com/fossasia/open-event-server/pull/5790#pullrequestreview-226648856
