### ISSUE TITLE
Show past events in browse events.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2657]
**Describe the bug**

Currently once the event is over, it isn't shown anywhere else except the user who created it and the admin. It is better for a user to know which events happened in the past.

**Expected behaviour**

A past events tab which shows all the past events.
**Additional context**

I am working on this.

**Comment by CosmicCoder96** [comment]
Don't need it, a feature-set identical to legacy is the priority
