### ISSUE TITLE
Wrong UI of vertical menu on bottom of event page. 

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2660]
**Describe the bug**
In the Event Detail Page, when we scroll to the bottom, the vertical menu shifts to the bottom of the Page.  

**Expected behaviour**
The vertical menu should not shift.

**Screenshots**
![Screenshot from 2019-04-15 17-47-21](https://user-images.githubusercontent.com/31065687/56134328-ff5f6900-5fab-11e9-96de-9de3a3665a71.png)

**Additional context**
Working on it.

**Comment by kushthedude** [comment]
Not reproducible, Indeed the sidebar remains attached to the top whenever you scroll down to the bottom and I think its an enhancement, The error shown in your screenshot is not reproducible

**Comment by prateekj117** [comment]
@uds5501 Can you please also test it?

**Comment by uds5501** [comment]
@prateekj117 I can't recreate it either :sweat_smile:

**Comment by mohitm15** [comment]
@prateekj117 Non-reproducible too here!
