### ISSUE TITLE
Message to upgrade caniuse-lite when starting the server

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2661]
**Describe the bug**
Whenever the server is started, it shows an error to upgrade caniuse-lite 

**Expected behaviour**
No such error should be displayed.

**Screenshots**
![Screenshot from 2019-04-15 17-48-20](https://user-images.githubusercontent.com/31065687/56134518-5e24e280-5fac-11e9-907b-416ed31036e4.png)

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@CosmicCoder96 I just need to upgrade the dependency in this case, right?

**Comment by kushthedude** [comment]
@prateekj117 Still on it buddy ?

**Comment by prateekj117** [comment]
@CosmicCoder96 We can close this now.

**Comment by kushthedude** [comment]
@CosmicCoder96 I am still experiencing it

**Comment by kushthedude** [comment]
I get it , Its covered in PR made by @niranjan94

**Comment by prateekj117** [comment]
@kushthedude Ya, so we can close the issue now?
