### ISSUE TITLE
Session should not be clickable if it has no speaker

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-frontend#2668]
**Describe the bug**
Session is clickable even if it has no speaker

**Expected behaviour**
Session should not be clickable if it has no speaker

**Screenshots**
![session](https://user-images.githubusercontent.com/19900978/56160670-69483480-5fe5-11e9-9acb-e63d21d2a50e.gif)

**Additional context**
I am working on it

**Comment by uds5501** [comment]
@shubham3211 if you  have not devoted much time on this, can I take over?

**Comment by shubham3211** [comment]
@uds5501 I am working on it, I will submit a pr by today.
