### ISSUE TITLE
Various Bugs in Safari .

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2669]
**Describe the bug**

Many issues are there in MacOS Safari which are not present in other browser, Some of which are -:
- Any link given in input by user is not getting saved .
- User cant add Social Links , External Event URL , TicketURL .
- Unnecessary Body Overflow in Event creation Wizard as stated in #2579 

**To Reproduce**

Steps to reproduce the behaviour:

- Try to add any link given by user and see it will not get saved .
- Go to event creation wizard and check the overflow

**Expected behaviour**

Solve all such browser specific issues

**Desktop (please complete the following information):**

 - OS: MacOS Mojave
 - Browser: Safari
 - Version: 23.0

**Additional context**

Would like to work on it

**Comment by kushthedude** [comment]
@CosmicCoder96 As stated in the issue all this issues are genuine and has been verified by @pradeepgangwar too . 
I have been trying to figure out what is the issue happening in safari which is creating such bugs , Please guide me if you have something

**Comment by kushthedude** [comment]
@mariobehling @CosmicCoder96 I think we should tag the issue with high priority, since we have made ‘next.eventyay.com’ into production and now this bugs exists on the ‘eventyay.com’ , we cant overlook body overflow, links issue in safari and others too in safari , as safari is also one of the most used browser

**Comment by kushthedude** [comment]
@CosmicCoder96 @pradeepgangwar What about it?

**Comment by mrsaicharan1** [comment]
This is not a priority right now, as discussed in the meeting.

**Comment by kushthedude** [comment]
With eventyay getting stable and more smoother, I think this is the right time to pick up this issue and fix it once and for all.

**Comment by iamareebjamal** [comment]
Please reopen if you want to work on it. It is getting difficult for people to look at which issues to work on.

**Comment by iamareebjamal** [comment]
Please reopen if you want to work on it. It is getting difficult for people to look at which issues to work on.
