### ISSUE TITLE
Avoid Top progress bar which shows for lazy loading 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2670]
When more items on the page are loaded the top blue bar also shows loading again. This makes the site appear even slower.

![Screenshot from 2019-04-16 13-19-49](https://user-images.githubusercontent.com/1583873/56186787-d04c0480-604a-11e9-9816-dc94fb81a940.png)

**Comment by mohitm15** [comment]
@mariobehling what should be the expected behaviour according to you??

**Comment by uds5501** [comment]
@mariobehling looking into it

**Comment by kushthedude** [comment]
@mariobehling I checked it out and yup thats persisting when the items are loaded , a refresh happens again . @uds5501 If you are not taking it up , May i take it ?

**Comment by uds5501** [comment]
@kushthedude Actually I am working on it

**Comment by kushthedude** [comment]
Cool

**Comment by uds5501** [comment]
@kushthedude this error is not reproduce able on my system. so if you can rectify it, please go ahead and work on it :)

**Comment by kushthedude** [comment]
@uds5501 check on next.eventyay.com once

**Comment by uds5501** [comment]
@kushthedude the issue exists on next.eventyay.com but not on my local repo

**Comment by kushthedude** [comment]
So should i take it @uds5501

**Comment by uds5501** [comment]
@kushthedude go ahead

**Comment by uds5501** [comment]
@CosmicCoder96 Now that lazy loading has been taken out of play from index, does this issue still needs to be addressed?

**Comment by kushthedude** [comment]
@uds5501 there are several more places where this issue is still happening .

**Comment by uds5501** [comment]
@kushthedude where else are we using lazy loading?

**Comment by kushthedude** [comment]
Not about lazy loading but there several places where tables get loaded after getting load once

**Comment by mariobehling** [comment]
Process has already been improved.
