### ISSUE TITLE
Add a flag infront of the country code in the dropdown of order-form

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-frontend#2672]
**Describe the bug**
A country flag should be present with it's name in the dropdown to select your country in the order-form as in session-speaker-form.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the orders form.

**Screenshots**
Implementation to be like:
![image](https://user-images.githubusercontent.com/22127980/56189425-879c4780-605a-11e9-912a-bdc772faa257.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**

I would like to work on this.

**Comment by uds5501** [comment]
@ritikamotwani can I take this up?
