### ISSUE TITLE
Pagination missing from Admin Sales Tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2676]
The admin sales tab does not have pagination (https://next.eventyay.com/admin/sales). Expected: When there are a lot of events the different sub menu tabs should be paginated. It would not be possible to load thousand of events.

**Comment by kushthedude** [comment]
I think some one is already on it #2167

**Comment by CosmicCoder96** [comment]
duplicate of https://github.com/fossasia/open-event-frontend/issues/2794
