### ISSUE TITLE
Admin: System Notification Mail Tab showing server error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2677]
In the Admin section https://next.eventyay.com/admin/reports/system-logs/activity-logs clicking on the mail tab in the: System Notifications shows an "500 Internal Server Error".

![Screenshot from 2019-04-16 15-02-53](https://user-images.githubusercontent.com/1583873/56192580-e5c82b00-6058-11e9-9445-7717e2a7896f.png)

**Comment by kushthedude** [comment]
Its working
<img width="1235" alt="Screenshot 2019-04-16 at 1 38 19 PM" src="https://user-images.githubusercontent.com/44091822/56192876-fecadf00-604c-11e9-960d-17eaa46dbccc.png">

**Comment by uds5501** [comment]
@CosmicCoder96 This must have been taken care of when you fixed the rogue emails. Please close this.

**Comment by mariobehling** [comment]
Was
