### ISSUE TITLE
Admin: In the Logs show newest entries first and show 100 entries as standard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2679]
In the Admin Section in the Logs (https://next.eventyay.com/admin/reports/system-logs/activity-logs) show newest entries first and show 100 entries as standard. Currently it shows the oldest entries first.

![Screenshot from 2019-04-16 15-05-30](https://user-images.githubusercontent.com/1583873/56192744-40618700-6059-11e9-8efa-873fa562e6fc.png)

**Comment by shreyanshdwivedi** [comment]
I'll like to work on it

**Comment by uds5501** [comment]
@shreyanshdwivedi If you haven't spent much time on it, I would love to take over!

**Comment by shreyanshdwivedi** [comment]
@uds5501 I completely forgot about this. Will push a PR by tonight
