### ISSUE TITLE
Add scroll to Add event topic in Admin to avoid overflow.

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2689]
**Describe the bug**

Currently if we keep adding event topics the div keeps adding it to the bottom. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Admin'
2. Click on 'Content'
3. Scroll down to 'Events'

**Expected behaviour**

The div length should be fixed and it should be scrollable after it.
**Screenshots**

![Screenshot 2019-04-16 at 8 09 26 PM](https://user-images.githubusercontent.com/31013104/56219201-f2ae4400-6083-11e9-92e3-94b95cccf37a.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@harsh-jindal Still on it or should i make a try ?

**Comment by harsh-jindal** [comment]
@kushthedude You can go ahead.

**Comment by maze-runnar** [comment]
i am working on this.

**Comment by kushthedude** [comment]
@iamareebjamal @prateekj117 I think it would be better to remove this custom rendered table and use `Ember Tables` instead here too . Give your inputs ?

**Comment by iamareebjamal** [comment]
Very low priority

**Comment by kushthedude** [comment]
A PR is already opened for that change. What should be done now?

**Comment by iamareebjamal** [comment]
If it works, merge it

**Comment by Dishebh** [comment]
Can I work on the issue, if it is still valid?

**Comment by iamareebjamal** [comment]
Are you deliberately looking for low priority issues? Please take high priority ones. The issue literally has a label saying it is low priority

**Comment by mariobehling** [comment]
Such areas will be addressed as part of other issues.
