### ISSUE TITLE
Fix Bug in System Images in Admin

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2690]
**Describe the bug**

Currently a black page appears if there are no system images.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Admin'
2. Click on 'Content'
3. Scroll down to 'System Images'

**Expected behaviour**

A text saying "No system images available" should be displayed.
**Screenshots**

![Screenshot 2019-04-16 at 8 14 04 PM](https://user-images.githubusercontent.com/31013104/56219479-6f412280-6084-11e9-8836-2f6ebd81e44e.png)

**Additional context**

I am working on it.

**Comment by kushthedude** [comment]
@harsh-jindal Rather than adding no system image , You should add some sample images .

**Comment by harsh-jindal** [comment]
@kushthedude System Image is for Event Subtopics. When you add a subtopic to Event topic system image is created. So if you have not added any event subtopic for a event topic. "No system images or No event subtopics" should be displayed as a message.

**Comment by kushthedude** [comment]
Oh i though you were referring to `Travel & Outdoor ` Section , My bad
