### ISSUE TITLE
Empty space in Event Details Page after License Info

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2694]
**Describe the bug**
An empty space is present in Mobile view in the Event Detail Page.

**Expected behaviour**
Empty space should not be there.

**Screenshots**
![Screenshot from 2019-04-16 21-02-16](https://user-images.githubusercontent.com/31065687/56224107-a6b3cd00-608c-11e9-812b-9bbca4ec2736.png)

**Additional context**

Working on it.

**Comment by kushthedude** [comment]
@prateekj117 I can still experience it 
![image](https://user-images.githubusercontent.com/44091822/59267929-18f9f580-8c69-11e9-8e4b-e4e90486f6e1.png)
Can you have a look ?

**Comment by prateekj117** [comment]
@kushthedude Ok, will have a look into it.
