### ISSUE TITLE
Date filtering option not available in Mobile Mode

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2703]
**Describe the bug**
Date filtering option UI disappears in Mobile Mode in the Index Page 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'localhost:4200'
2. Turn to Mobile view
3. Scroll down to 'Search option bar'

**Expected behaviour**
Date filtering option should be available for Mobile View as well.

**Screenshots**
![Screenshot from 2019-04-17 14-30-38](https://user-images.githubusercontent.com/31065687/56275195-d232c800-611d-11e9-9db5-17bef8a85472.png)

**Additional context**
Working on it.

**Comment by kushthedude** [comment]
Replica of a closed issue , Not needed now close it

**Comment by kushthedude** [comment]
Please see #2247

**Comment by prateekj117** [comment]
@iamareebjamal @CosmicCoder96 @ritikamotwani Seems like an important as well as easy issue to me, so won't take that much of time, your views on this?

**Comment by uds5501** [comment]
@prateekj117 kindly see mentor's opinion

https://github.com/fossasia/open-event-frontend/issues/2247#issuecomment-469095512

**Comment by ritikamotwani** [comment]
@prateekj117 , it's not required.
It's a design choice.
