### ISSUE TITLE
Username changing along with Ticket Buyer Name

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2707]
**Describe the bug**

When ordering a ticket, the ticket buyer name is changing along with the user name on top

**To Reproduce**
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/21087061/56287987-66f7ee80-613b-11e9-9cb6-532db87d3cfe.gif)

**Expected behaviour**

The User name shouldn't be changing at all

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu16.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by kushthedude** [comment]
Try to refresh it will not occur

**Comment by uds5501** [comment]
@kushthedude this shouldn't happen in the first place :sweat_smile:

**Comment by kushthedude** [comment]
I had been observing this issue but as soon as i go to homepage after order the username changes automatically , But cool go ahead 👍
