### ISSUE TITLE
Ticket Buyer Name not getting shown

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2709]
**Describe the bug**

After ordering ticket if you go and check ticket from `My Tickets` , No buyer name is provided.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'My Tickets'
2. Click on 'Any Ticket'
3. Check the `Ticket Buyer` Name

**Expected behaviour**

Solve the error

**Screenshots**

<img width="1288" alt="Screenshot 2019-04-17 at 8 06 05 PM" src="https://user-images.githubusercontent.com/44091822/56296968-16898c80-614d-11e9-986f-24419b4203c4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari
 - Version: 23.0.3

**Additional context**

Solving it

**Comment by prateekj117** [comment]
@kushthedude Any update on this? In case you haven't done much work on it, can I take this one up?

**Comment by prateekj117** [comment]
@CosmicCoder96 @iamareebjamal Can I take this up?

**Comment by kushthedude** [comment]
Im still on it

**Comment by iamareebjamal** [comment]
7 days are enough for getting a chance. No contributor should be left with no task. @kushthedude You have taken up a lot of issues, please share either this one or others with contributors with currently no issues to solve

**Comment by kushthedude** [comment]
Proceed.

**Comment by kushthedude** [comment]
@iamareebjamal Actually , I was busy with some other work ,
@prateekj117 you can look into other issues opened by me and i have not done work on them like #2544 , #2723 , and there are plenty of other .

**Comment by kushthedude** [comment]
@prateekj117 Can you reproduce it?

**Comment by prateekj117** [comment]
@kushthedude Not facing this issue. Are you still able to reproduce it?

**Comment by kushthedude** [comment]
@prateekj117 See #2945
