### ISSUE TITLE
Ticket column heading are confusing in Mobile view

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2718]
**Describe the bug**
In column names in large screen view becomes confusing in Mobile view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://localhost:4200/e/{event_id}'
2. Scroll down to 'Tickets'
3. See error

**Expected behaviour**
Open for discussion.

**Screenshots**
![Screenshot from 2019-04-18 15-02-21](https://user-images.githubusercontent.com/31065687/56351717-5f901e00-61eb-11e9-945d-aba9ae922ea0.png)

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@CosmicCoder96 @ritikamotwani What according to you should be the desired behavior. In my opinion, this whole block shouldn't be present in Mobile View.

**Comment by prateekj117** [comment]
@CosmicCoder96 Any update on this?

**Comment by CosmicCoder96** [comment]
@prateekj117 not a priority for now. The tables in the entire app need to be refactored. We will have to think more about it and get more feedback from other mentors before proceeding.

**Comment by kushthedude** [comment]
Duplicate of #2927
