### ISSUE TITLE
Missing required asterisk label in the location field

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2719]
**Describe the bug**

 Required asterisk label in the location field is missing in the basic details form.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create event'
2. See error

**Expected behaviour**

 Include the required label.

**Screenshots**

![Screenshot 2019-04-18 15:07:42](https://user-images.githubusercontent.com/35539313/56352472-f1e4f180-61ec-11e9-9314-cf2183395a01.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser :chrome
 - Version : 71.0398

**Additional context**

working on it

**Comment by kushthedude** [comment]
No changes in location field yet @mohitm15

**Comment by kushthedude** [comment]
see #2602

**Comment by uds5501** [comment]
@mohitm15 It's not a required field. If some one doesn't want to publish an event yet, they would draft it and location field isn't necessary at that time :)

**Comment by CosmicCoder96** [comment]
⬆️ comments are correct.
