### ISSUE TITLE
Allow Event Creator to edit the heading of first Social Link

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2721]
**Describe the bug**
Event Creator is not allowed to edit the heading of first social link, while allowed to edit the heading of other social links. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'localhost:4200/create'
2. Scroll down to 'Links and Social Media'
3. See error

**Expected behaviour**
User should be able to edit heading of the first external link. In fact, maybe select from a list of Social Media so that their icons can be predefined as well.

**Screenshots**
Screenshot of how different names looks on display:
![Screenshot from 2019-04-18 15-28-12](https://user-images.githubusercontent.com/31065687/56353715-9ec06e00-61ef-11e9-9921-0e46f95ac335.png)
First social link heading field not editable by the user: 
![Screenshot from 2019-04-18 15-29-19](https://user-images.githubusercontent.com/31065687/56353752-b7308880-61ef-11e9-85ba-5ab2a81e6162.png)

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@CosmicCoder96 @ritikamotwani What should be the expected behavior according to you? My opinion is to provide a dropdown to select from a list of Social Media.

**Comment by kushthedude** [comment]
@prateekj117 Its based on `EventYay V.1` No change should be made into it

**Comment by CosmicCoder96** [comment]
@prateekj117 It can be an enhancement later down the line, right now we are not intent on this.

**Comment by iamareebjamal** [comment]
Not needed for now
