### ISSUE TITLE
Adding placeholders as label in both search boxes on managing events page

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2727]
**Is your feature request related to a problem? Please describe.**

Adding `search event here` as watermark(placeholder) in both the search boxes as currently nothing is mentioned here and a new user only come to know after giving input to them on the manage event page.

**Describe the solution you'd like**

To add placeholder on both search boxes like the given in the search box on the same page.

**Describe alternatives you've considered**

To add a label in front of both the search box.

**Screenshots**
![Screenshot 2019-04-18 17:47:58](https://user-images.githubusercontent.com/35539313/56394361-bc73ee80-6254-11e9-9f15-e134b28246d9.png)

**Additional context**

working on it

**Comment by mohitm15** [comment]
@CosmicCoder96 What are your thoughts?

**Comment by ritikamotwani** [comment]
No, not required for now.
