### ISSUE TITLE
Typo in discount code page

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2729]
**Describe the bug**

Typo in the discount page button

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'publish event'
2. Click on 'tickets.'
3. Scroll down to 'discount codes'

**Expected behaviour**

 button text should be similar to access code

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Browser chrome
 - Version: 71.0398

**Additional context**

Working on it.

**Comment by CosmicCoder96** [comment]
Not a typo.
