### ISSUE TITLE
Payee information is not visible in mobile view

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2731]
**Describe the bug**

Payee information is not visible in mobile view while same is visible in desktop view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create event'
2. Click on 'tickets'
3. Place order successfully
4. Go to completed order in mobile view.
5. Compare with desktop view
6. See error

**Expected behaviour**
Should be visible in mobile view.

**Screenshots**

Desktop view:
![Screenshot 2019-04-19 05:29:03](https://user-images.githubusercontent.com/35539313/56398006-26e05b00-6264-11e9-83b9-d5c8984fb329.png)

Mobile view:
Not visible (Payee info.)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version 71.0398

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
Deliberate.
