### ISSUE TITLE
Incorrect ticket price is shown on view attendees page

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2732]
**Describe the bug**

 On the ticket price column, the total price for the order is shown in place of the individual ticket price.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Create and publish event'
2. Click on 'tickets<<add order'
3. Place order successfully'
4. Go back to tickets<<attendees.
5. See error

**Expected behaviour**

On the ticket price column, individual ticket price should be visible.

**Screenshots**

![Screenshot 2019-04-19 06:14:30](https://user-images.githubusercontent.com/35539313/56399444-93128d00-626b-11e9-962a-d19c891c4369.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version : 71.0398

**Additional context**

Working on it.

**Comment by uds5501** [comment]
@mohitm15 Just change the Ticket Price column to "Order Amount" because that is what it signifies IMO.

CC: @CosmicCoder96

**Comment by mohitm15** [comment]
@uds5501 @CosmicCoder96 Okay :+1:

**Comment by mohitm15** [comment]
> @mohitm15 Just change the Ticket Price column to "Order Amount" because that is what it signifies IMO.
> 
> CC: @CosmicCoder96

@CosmicCoder96 what are your views?

**Comment by kushthedude** [comment]
Checkin onto it

**Comment by iamareebjamal** [comment]
It is now calculated on server and it doesn't make sense to separate ticket price. How to distribute discounted money? How to distribute tax? In future, discount code will be applied to individual tickets, then it'll be more complex to handle. It is fine as it is
