### ISSUE TITLE
No drop-down for gender option in speaker form

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2733]
**Describe the bug**

Although gender option ask to select a value from the option but no drop-down table is present.
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'manage event'
2. Click on 'view'
3. Click on speakers and create it.
4. Scroll down to gender option
5. See error

**Expected behaviour**

A drop-down should be made available.

**Screenshots**

![Screenshot 2019-04-19 06:41:49](https://user-images.githubusercontent.com/35539313/56399936-b854ca80-626e-11e9-9030-f80ee22ab0c7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser :chrome
 - Version : 71.0398

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
This issue has been already opened. Duplicate.

**Comment by mohitm15** [comment]
@CosmicCoder96 So should I work on that issue.

**Comment by mohitm15** [comment]
> > This issue has been already opened. Duplicate.
> 
> @CosmicCoder96 Can you refer that issue because I did not find any similar issue.

@CosmicCoder96 Any updates sir otherwise we can reopen the issue.
