### ISSUE TITLE
Having more than two sponsors shows same id error in sponsor-step

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2737]
**Describe the bug**
If an event has more than two sponsors, console error shows id already on use.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Create Event'
2. Add more than two sponsors.
3. Publish/Draft the Event.
4. Come back to edit the sponsor's page in the event.
5. See the error.

**Expected behaviour**
Should not show any such error.

**Screenshots**
![Screenshot from 2019-04-19 11-18-41](https://user-images.githubusercontent.com/31065687/56409184-87d45700-6295-11e9-90ef-347f09b9b538.png)

**Additional context**
Working on it.

**Comment by prateekj117** [comment]
@CosmicCoder96 @ritikamotwani I tried to debug it by searching which elements have id 'sponsor_url' and I think it is due to inputId being the same in all sponsors.
![Screenshot from 2019-04-19 11-24-10](https://user-images.githubusercontent.com/31065687/56409254-d4b82d80-6295-11e9-9314-aba71f705f4f.png)

**Comment by ritikamotwani** [comment]
Handled by https://github.com/fossasia/open-event-frontend/pull/2742/files
