### ISSUE TITLE
Implement Social Link in Event Wizard as EventYay V.1

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2745]
**Is your feature request related to a problem? Please describe.**

Currently Social link only offers a hardcoded `External Event Link` but in V.1 there were two extra column for Facebook and Twitter . 

**Describe the solution you'd like**

I propose to add two extra column for Twitter And Instagram in addition to Hard Coded `Event Link`

**Screenshot**

<img width="715" alt="Screenshot 2019-04-19 at 4 09 54 PM" src="https://user-images.githubusercontent.com/44091822/56420905-9a628680-62bd-11e9-974c-f7638241dc3d.png">

**Additional context**

Would like to work

**Comment by kushthedude** [comment]
@uds5501 @CosmicCoder96 What you think about it ?

**Comment by uds5501** [comment]
@kushthedude IMO, It's kind of redundant . We should let user handle a twitter and facebook field on his/her own convenience. besides, an additional twitter field alongside the existing ones can be confusing

**Comment by kushthedude** [comment]
Yeah was thinkin same , closing it
