### ISSUE TITLE
Past Events being shown under "Upcoming Events"

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2749]
**Describe the bug**

In the Upcoming events section, the past events are also being shown

**Expected behaviour**

They should not appear

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/56433352-31dfcd80-62ee-11e9-9e40-b8ef9247c434.png)

**Additional context**

Looking into it

**Comment by kushthedude** [comment]
Why did you close it ?

**Comment by uds5501** [comment]
@kushthedude Because they are actually ongoing events. Which is allowed to be shown conditionally

**Comment by kushthedude** [comment]
Cool
