### ISSUE TITLE
Misbehaving vertical menu at event detail page

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-frontend#275]
I'm submitting a
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Menu items - **Info**, **Tickets**, **Speakers** are not configured correctly for clicks. On clicks it just scrolls the content with some fixed length independent of which item is clicked

**Expected behavior:**
On clicks content should get scrolled to the respective section

**Steps to reproduce:**
Click on the one of them (**Info**, **Tickets**, **Speakers**) repetitively. It will just scroll the content.

**Comment by sumedh123** [comment]
@mejariamol It scrolls correctly. Can you please elaborate what you want there?

**Comment by mejariamol** [comment]
>Click on the one of them (Info, Tickets, Speakers) repetitively. It will just scroll the content.

Keep clicking **Tickets** for example, it will keep scrolling the content to the end

**Comment by CosmicCoder96** [comment]
@mejariamol It's scrolling fine for me as well, can you post a gif?

**Comment by mejariamol** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/13533840/27284087-e6261f7c-5514-11e7-850f-7584697eb34f.gif)

**Comment by sumedh123** [comment]
@mejariamol What's your firefox version? In my firefox it works fine.

**Comment by mejariamol** [comment]
>What's your firefox version?
54.0

**Comment by sumedh123** [comment]
@CosmicCoder96 @mejariamol This is unusual behaviour. @CosmicCoder96 can you check in your browser if you have firefox?

**Comment by geekyd** [comment]
@sumedh123 I can confirm that this issue exists for Firefox browser. My version is 54.0

**Comment by sumedh123** [comment]
@geekyd Mine is also 54.0

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 Scrolling has some issue in firefox. I guess it's the addon which is causing problem. I can see one more issue in firefox that once you scroll to a down part, you cannot scroll back to the part above it.

**Comment by sumedh123** [comment]
Check this out : https://github.com/jasonkriss/ember-scroll-to/issues/29

**Comment by CosmicCoder96** [comment]
@sumedh123 yes, the issue exists on firefox for me, absent on chrome.

**Comment by kushthedude** [comment]
@CosmicCoder96 Regarding this issue , this issue is browser specific as only happening on chrome and firefox , Can we use other scroller package for ember ?

**Comment by CosmicCoder96** [comment]
@kushthedude yes, an alternative package would be a good choice.

**Comment by kushthedude** [comment]
Should i look into it?

**Comment by prateekj117** [comment]
@CosmicCoder96 It's happening in Chrome for me.

**Comment by kushthedude** [comment]
Looking into it
