### ISSUE TITLE
Reset Password screen goes not responding

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2753]
**Describe the bug**

`Reset Password ` screen goes not responding until refresh is clicked .

**To Reproduce**

Steps to reproduce the behaviour:

- Go to `Guest Order Form`.
- Enter Email of `Existing User`.
- Click `Reset Password`.
- See Error

**Expected behaviour**

Solve the issue

**Screenshots**

<img width="1273" alt="Screenshot 2019-04-20 at 3 16 50 AM" src="https://user-images.githubusercontent.com/44091822/56445679-1db2c500-631c-11e9-97e7-ae995dfc0fe5.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome,Safari

**Additional context**

Would like to if reproducible

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi @pradeepgangwar Can you please check if its reproducible ?

**Comment by mohitm15** [comment]
@kushthedude it is non-reproducible.

**Comment by uds5501** [comment]
@kushthedude Reproducible :+1:

**Comment by kushthedude** [comment]
Thanks @uds5501 will look into it

**Comment by prateekj117** [comment]
@kushthedude Any update on this? In case you haven't done much work on it, can I take this one up?

**Comment by prateekj117** [comment]
@CosmicCoder96 @iamareebjamal Can I take this up?

**Comment by kushthedude** [comment]
Im still on it
