### ISSUE TITLE
Addition of `Cancel Order` button in `Order Checkout` Page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2759]
**Is your feature request related to a problem? Please describe.**

Currently in the `Order Checkout` page there is no `Cancel Order` Button

**Describe the solution you'd like**

Add a `Cancel` Button which routes to `Events Page`

**Additional context**

Working on it

**Comment by prateekj117** [comment]
@kushthedude Any update on this? In case you haven't done much work on it, can I take this one up?

**Comment by kushthedude** [comment]
@CosmicCoder96 , Regarding this I don't think just adding a `Cancel Order` button which leads us to event details will work, Like when a `Guest User` creates an order, we create his records immediately but if that user clicks on `Cancel Order` , His data should also get destroyed from the Database .
How do I identify the user is coming from `Guest Order Form`?
@ritikamotwani @pradeepgangwar Please provide your valuable feedback too.

**Comment by mrsaicharan1** [comment]
@kushthedude I'll be taking this due to inactivity.

**Comment by mariobehling** [comment]
As the ticket process has been adapted in a number of ways we can keep the way it is implemented for now and I am closing this issue therefore.
