### ISSUE TITLE
UI enhancement in `/profile`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2760]
**Is your feature request related to a problem? Please describe.**

- I suggest to give a line-break between `Photo Instruction` and `First Name`
- Complete name should be in one line

 **Screenshot**
<img width="1271" alt="Screenshot 2019-04-20 at 3 49 47 PM" src="https://user-images.githubusercontent.com/44091822/56456077-d3196300-6384-11e9-82f2-bfd41a7ab2e1.png">

**Additional context**

On it

**Comment by mohitm15** [comment]
Similar to #2591 @kushthedude

**Comment by kushthedude** [comment]
@mohitm15 If the name is long enough it will automatically get into next line 
<img width="1440" alt="Screenshot 2019-04-20 at 4 27 26 PM" src="https://user-images.githubusercontent.com/44091822/56456389-373e2600-6389-11e9-8832-67603b4e6551.png">

**Comment by mohitm15** [comment]
> @mohitm15 If the name is long enough it will automatically get into next line
> <img alt="Screenshot 2019-04-20 at 4 27 26 PM" width="1440" src="https://user-images.githubusercontent.com/44091822/56456389-373e2600-6389-11e9-8832-67603b4e6551.png">

But here it is not going into next line

**Comment by kushthedude** [comment]
Didnt you see family name automatically got shifted to next line . And i
dont think a person will name himsef more than 26 letters 😆

**Comment by mohitm15** [comment]
But the creator wants something to be distinguished between name or family name, that's why created another field for family name. Otherwise, what is the need of that, you can simply write your full name in the name field , no matter how long it is.

Ok lets leave it to the mentors @CosmicCoder96 @ritikamotwani
