### ISSUE TITLE
Complete event card is not clickable

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-frontend#277]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
On home page, event item card used is not clickable in whole portion. Making it less user friendly.

**Expected behavior:**
It should be clickable in whole portion. 

**Steps to reproduce:**
Click below event title not working

**Comment by mejariamol** [comment]
If it is left not-clickable purpose fully then please decrease padding of the lower content as it is suggesting for click

**Comment by sumedh123** [comment]
@mejariamol One way is to underline the event.

**Comment by mejariamol** [comment]
@sumedh123 No. don't underline. I would rather suggest make complete portion of the item card clickable. Also please decrease padding of the lower part below the event title.

**Comment by niranjan94** [comment]
The padding is there to accommodate two lines of location name (there many cases like that) without causing one card be taller than the other. 

As for clicking, the whole card (except the section with the tags and share button) needs to be click able and open the event on click
