### ISSUE TITLE
400 being encountered after accepting a role-invite

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2771]
**Describe the bug**

When a user accepts a role-invite, he/she encounters a 400 error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Role-invite while the user is logged in
2. Enter the invite token
3. See error

**Expected behaviour**

It should've worked without any error

**GIF**

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/21087061/56514713-ab2c2a00-6553-11e9-97c8-c020c7223639.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Working on it

**Comment by uds5501** [comment]
The error trace : 
![Screenshot from 2019-04-22 23-09-42](https://user-images.githubusercontent.com/21087061/56514886-1fff6400-6554-11e9-9b0b-cd2afba40858.png)

**Comment by uds5501** [comment]
@pradeepgangwar @CosmicCoder96 @ritikamotwani @iamareebjamal 
The role-invite I accepted was of `Moderator` but since he won't have co-organisers access, he won't be able to access the event's details.

How about we also pass a "Role" name in the `role-invite/accept-invite` and if the accepted role is of other than organiser / co-organiser we simply re route them to the public page of the event?

**Comment by kushthedude** [comment]
@uds5501 Is it still present ?

**Comment by uds5501** [comment]
@kushthedude Yes it does. But to get this done, I need to wait for mentor's reply

**Comment by iamareebjamal** [comment]
@uds5501 Go ahead

**Comment by uds5501** [comment]
@iamareebjamal Perfect! I will get this done as soon I take down two issues in hand, won't take long!

**Comment by hpdang** [comment]
![Screenshot from 2019-06-10 10-49-50](https://user-images.githubusercontent.com/1658742/59184055-8fb1c880-8b6d-11e9-9db6-3b6df41047cb.png)
