### ISSUE TITLE
Inconsistency in facebook icon in connect with facebook button

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2779]
**Describe the bug**

In the `connect with facebook` button present in application settings, the icon isn't visible in normal state. It is slightly visible in hover state.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/settings/applications'
2. See error

**Expected behaviour**

The icon should be visible in normal state too.

**Screenshots**

![Screenshot from 2019-04-23 15-26-39](https://user-images.githubusercontent.com/21174572/56572191-35b86c00-65dc-11e9-9009-5690c52ca7f0.png)

**Additional context**

I am working on this issue.

**Comment by kushthedude** [comment]
@Anupam-dagar Please update your repo as the following part is already commented from the complete app

**Comment by mohitm15** [comment]
@Anupam-dagar similar to #2448
