### ISSUE TITLE
Only load third party services after opt-in by the user

### ISSUE THREAD

**Issue by benzea** [fossasia/open-event-frontend#2783]
**Describe the bug**

For privacy reasons it is desirable to only load third party content (e.g. Facebook. Google Maps, Twitter), if the user has opted in. A simple solution would be to provide options to globally disable these features.

However, many users might still like these integrations. As such, hiding them behind some (client side) javascript so that the third party services are only accessed after the user has confirmed with a click of a button (or has enabled it in their user profile) seems more desirable.

Note that I am not sure in how far the current version is affected; this report originated from seeing both Google Maps and Twitter embedded on events.gnome.org which is still using the legacy code at this point.

**Comment by benzea** [comment]
The vital thing here is that there is not a single HTTP request to those services unless the user has chosen that such a request should happen.

**Comment by kushthedude** [comment]
@CosmicCoder96 Do we need such implementation?

**Comment by mariobehling** [comment]
It is already specified in other issues, that we should get rid of using third party services and rather load libraries locally. So, lets focus efforts there.
