### ISSUE TITLE
Addition of `Mark As Read` or `Cross Icon` in notification dropdown

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2788]
**Is your feature request related to a problem? Please describe.**

Currently in the `Notification Dropdown`, There is only `Mark All As Read` option available, 
I propose to add `Cross Icon ` with every notification to mark an individual notification as Read.

**Describe the solution you'd like**

Add a `Cross icon` or `Mark as Read` text in notification dropdown.

**Comment by CosmicCoder96** [comment]
Not required for now.
