### ISSUE TITLE
Fix the overflow of the tags in event card

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#279]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![eventoverflow](https://user-images.githubusercontent.com/17925669/27286539-325d3e58-551e-11e7-9fa5-e419ca65d92f.png)

**Expected behavior:**
The tags should not overflow.

**Comment by sumedh123** [comment]
@geekyd @niranjan94 I ll get it fixed. Please assign.

**Comment by geekyd** [comment]
@sumedh123 This is a duplicate issue. Please check https://github.com/fossasia/open-event-frontend/issues/228
PR: https://github.com/fossasia/open-event-frontend/pull/236
