### ISSUE TITLE
Admin Sales Tab Not Showing all Events and Missing Pagination

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2794]
The admin sales tab at https://next.eventyay.com/admin/sales only shows two events and does not have pagination implemented.

![Screenshot from 2019-04-24 23-18-28](https://user-images.githubusercontent.com/1583873/56671493-57524a00-66e7-11e9-89e3-feb3551232b2.png)

**Comment by kushthedude** [comment]
@YogeshSharma0201 What about your PR regarding the pagination ?

**Comment by kushthedude** [comment]
@CosmicCoder96 Its been more than 2 months since the PR related to Admin Sales pagination is in WIP state what should be done ?

**Comment by kushthedude** [comment]
Since the PR related to it closed , I will be working on in now

**Comment by iamareebjamal** [comment]
Same as #5163 and fixed in #5243
