### ISSUE TITLE
Admin Event Tab / All Events Tab missing Session Information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2795]
The admin events tab and events tab are e.g. at https://next.eventyay.com/admin/events/past are missing session information. It shows "0" for different statuses.

![Screenshot from 2019-04-24 23-48-18](https://user-images.githubusercontent.com/1583873/56673990-d21d6400-66eb-11e9-9d89-03f19b978d9d.png)

**Comment by kushthedude** [comment]
Lookin into it

**Comment by kushthedude** [comment]
@CosmicCoder96 @iamareebjamal shouldnt this be handled on server ?

**Comment by kushthedude** [comment]
@mrsaicharan1 Should not this be handled on server?

**Comment by mrsaicharan1** [comment]
This is a combined issue. Will take up the FE and the server side implementation of this.

**Comment by kushthedude** [comment]
@mrsaicharan1 Since the value recorded for submitted should be the total of everything , And This needs to be changed on server

**Comment by kushthedude** [comment]
Can you open the issue and fix it up on Server
