### ISSUE TITLE
Ambiguity in 'Events/Overview' Sales Section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2796]
**Describe the bug**

Sales total shown in `Event/Overview` is different in Overview and Each Ticket section.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to `Events/Overview` 
2. See error
3. Refer to Screenshot

**Expected behaviour**

Ambiguity should not be there

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/56674706-1272e700-66d8-11e9-9c41-5e4c946423ec.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari
 - Version: 23.0.3

**Additional context**

Looking into the cause

**Comment by kushthedude** [comment]
@CosmicCoder96 I think its server issue , Please transfer it

**Comment by shreyanshdwivedi** [comment]
@kushthedude can you still verify if this exists? Try for a new event and new orders as our order flow changed alot after you reported this issue

**Comment by uds5501** [comment]
@shreyanshdwivedi @kushthedude This issue doesn't seem to be existing anymore. Tried several orders here, seems to be working fine:

![Screenshot from 2019-07-17 15-55-41](https://user-images.githubusercontent.com/21087061/61368498-9db0e280-a8ab-11e9-80fd-b17dd1f35311.png)

**Comment by kushthedude** [comment]
> @shreyanshdwivedi @kushthedude This issue doesn't seem to be existing anymore. Tried several orders here, seems to be working fine:
> 
> ![Screenshot from 2019-07-17 15-55-41](https://user-images.githubusercontent.com/21087061/61368498-9db0e280-a8ab-11e9-80fd-b17dd1f35311.png)

Will check back today.

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi  It's still there, See this

![image](https://user-images.githubusercontent.com/44091822/61432630-a3abcf80-a94e-11e9-8809-9b24cdb9bae0.png)

I think in the `Ticket Summary` section its showing order value in spite of individual ticket subtotal.

**Comment by uds5501** [comment]
@kushthedude Regarding this, something caught my eye. How come this event has `Free` tickets in placed orders section? I am assuming that it's gonna cost `INR 0` yet it has placed orders which shouldn't be there coz the free orders just get to completed state AFAIK. Is there a particular ambiguity in this ticket? Because otherwise all the calculation actually checks out

**Comment by shreyanshdwivedi** [comment]
@kushthedude any update on this issue?

**Comment by kushthedude** [comment]
@shreyanshdwivedi I will test this issue again, Will close if found nothing.

**Comment by kushthedude** [comment]
> @kushthedude any update on this issue?

Still Present, Not able to debug it
The ss is of my latest event
![image](https://user-images.githubusercontent.com/44091822/63218241-957ee800-c174-11e9-8b93-872fbf8fd101.png)
