### ISSUE TITLE
UI issue in `Add Order Form`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2797]
**Describe the bug**

When you see the `Ticket Quantity ` Dropdown in `Add Order` section there is UI issue in it

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Event/Ticket'
2. Click on 'Add Order'
3. Scroll down to 'Ticket Quantity'

**Expected behaviour**

The dropdown should not be bounded by the ticket table

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/56674943-9cbb4b00-66d8-11e9-8a59-46b51c06532a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Additional context**

Up For Grabs!!

**Comment by kayyjayy007** [comment]
I want to work on this issue. Please assign this to me.

**Comment by kushthedude** [comment]
> I want to work on this issue. Please assign this to me.

Go ahead

**Comment by amreshk005** [comment]
@kushthedude If this still open can I work on it?

**Comment by kushthedude** [comment]
Sure
