### ISSUE TITLE
Invalid date shown in `Event/Tickets/Orders/All'

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2802]
**Describe the bug**

Invalid date is shown at the place of `Order Completion ` 

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'Events/Tickets/Order'
2. See error

**Expected behaviour**

An actual date and time should be shown .

**Screenshots**

<img width="1310" alt="Screenshot 2019-04-25 at 4 14 59 AM" src="https://user-images.githubusercontent.com/44091822/56698813-d3ad5300-6710-11e9-989b-d3718974f119.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.4

**Additional context**

Lookin into it

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi I think the following error is not present after the refactor , Can you please check if its still there ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude I don't find any ticket with `Invalid date Invalid date` on my local

**Comment by uds5501** [comment]
@kushthedude it's working fine here
![image](https://user-images.githubusercontent.com/21087061/59054575-99a7a300-88b1-11e9-9ce1-c06b8e230d27.png)

**Comment by kushthedude** [comment]
Yeah Same, Closing it henceforth !
