### ISSUE TITLE
UI issue in Sessions Table

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2804]
**Describe the bug**

1.)When there is new proposal and when you need to confirm the dialogue opened is half hidden.
2.)There is no column title for `Cell Actions`.
3.)Sessions view Property doesn't exist , Hence view and edit redirect to same page

**To Reproduce**

Steps to reproduce the behaviour:
1. Create a new proposal
2. Go to Sessions table to accept the proposal
3. See error , `With Email option` is hidden
 
**Expected behaviour**

Fix the UI

**Screenshots**

<img width="1440" alt="Screenshot 2019-04-25 at 4 46 23 AM" src="https://user-images.githubusercontent.com/44091822/56699976-7ec00b80-6715-11e9-8e5e-230b4ae81525.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.3

**Additional context**

On It

**Comment by ritikamotwani** [comment]
1. There is no column title for Cell Actions.
2. Sessions view Property doesn't exist , Hence view and edit redirect to same page

No need to change these two things.
Just change the first point in your issue in the the PR.

**Comment by kushthedude** [comment]
@ritikamotwani , View Session was redirecting to route Edit , i have fixed that and now it redirects to `MySession.view` , What is the point in making the route same for both edit and view ?

**Comment by ritikamotwani** [comment]
@kushthedude no both will go to the same route.
Just fix the hidden part of confirm session rest nothing is required.

**Comment by kushthedude** [comment]
@ritikamotwani , But in admin section both redirects to different route , Can you please confirm me once 😅 ?
