### ISSUE TITLE
Addition of colour labels to `Event State`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2815]
**Is your feature request related to a problem? Please describe.**

Currently there is no label for `Event State` under `Admin/Events`

**Describe the solution you'd like**

Add `Labels` as added in `Session State`

**Screenshot**
<img width="1100" alt="Screenshot 2019-04-27 at 7 57 05 AM" src="https://user-images.githubusercontent.com/44091822/56843712-15c9c680-68c2-11e9-977e-244289919045.png">

**Comment by uds5501** [comment]
@kushthedude not required. the states are handled in the tabs itself

**Comment by kushthedude** [comment]
Dont you think stating a event state with just published isn’t looking mice , since in session tabs a label indicating state has been implemented , same could look and depict a great UI for events table . 
Still we can always for @CosmicCoder96 review on it😄

**Comment by ritikamotwani** [comment]
No, it's not required.
