### ISSUE TITLE
Show `End Date` in `Event Cards`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2817]
**Is your feature request related to a problem? Please describe.**

Not related to a problem but an enhancement which can be considered on the line . Currently the event cards only feature the `Event Start Date & Time` , I propose to add `Event End Date & Time` too

**Describe alternatives you've considered**

Add `EndsAt` attribute in `Event Cards`

**Comment by mohitm15** [comment]
similar to #2650

**Comment by kushthedude** [comment]
@mohitm15 It was on event detail and i am planning to add on event-card , If @CosmicCoder96 say i will close it 😄

**Comment by mohitm15** [comment]
@kushthedude Ok pal :+1:

**Comment by ritikamotwani** [comment]
@kushthedude this is not required. Close the PR as well.

**Comment by kushthedude** [comment]
@ritikamotwani Sure
