### ISSUE TITLE
Unfinished Ticket Orders should show up as "Open Orders" in My Ticket Tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2821]
Unfinished Ticket Orders should show up as "Open Orders" in My Ticket Tab at https://next.eventyay.com/my-tickets/upcoming

![Screenshot from 2019-04-27 16-20-24](https://user-images.githubusercontent.com/1583873/56847012-ad520800-6908-11e9-9ca6-e4202e4edd1f.png)

**Comment by shreyanshdwivedi** [comment]
Looking into it
