### ISSUE TITLE
Import Tab: Event Import showing up even though no event was imported into the account

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2822]
Import Tab: Event Import showing up even though no event was imported into the account https://next.eventyay.com/events/import . This even happens on new accounts.

![Screenshot from 2019-04-27 16-23-44](https://user-images.githubusercontent.com/1583873/56847044-f0ac7680-6908-11e9-985b-db445372107c.png)

**Comment by kushthedude** [comment]
@mariobehling it was just a text message given

**Comment by uds5501** [comment]
@kushthedude that sounds good
