### ISSUE TITLE
Improving UI in Order Form and Payment Method

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2826]
**Describe the bug**

- If a paid ticked is introduced, make sure at least one payment option is introduced
- In an order page, if no payment option is there, remove the payment order section

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/56853186-e35fae00-6941-11e9-88bc-083b87816a83.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

Open for all

**Comment by kushthedude** [comment]
@uds5501 Name of issue seems vague as compared to description , Please change the name to `Improving UI in Order Form and Payment Method ` , If you think so 😅

**Comment by uds5501** [comment]
@kushthedude you are right, changed the title accordingly
