### ISSUE TITLE
Cell Sorting not working and UI Enhancements in Section in `Admin/Messages` 

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2829]
**Describe the bug**

`Cell Sorting` is not functional in `Admin/Messages`

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Admin/Messages'
2. Click on 'Sort Icon'
3. See error

**Expected behaviour**

Fix the bug

**Screenshots**

<img width="1140" alt="Screenshot 2019-04-28 at 8 01 01 AM" src="https://user-images.githubusercontent.com/44091822/56857482-ce0f7180-698b-11e9-90cd-4a2caa9c3f2a.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.4

**Additional context**

Looking into it

**Comment by prateekj117** [comment]
@kushthedude I would work on this.

**Comment by kushthedude** [comment]
@prateekj117 Sure, But ask @shreyanshdwivedi once, as in the previous meeting he said he will see it.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 mentioned in last weekly meeting that he'll work on it

**Comment by prateekj117** [comment]
@shreyanshdwivedi Oh, Ok.

**Comment by uds5501** [comment]
@CosmicCoder96 @shreyanshdwivedi `Recipient` sort is failing because there is no such field in the database. It's only a hybrid property.

**Comment by uds5501** [comment]
Refactoring to Ember tables. hence closing.
