### ISSUE TITLE
UI enhancement for the nav-bar

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2830]
**Is your feature request related to a problem? Please describe.**
 An enhancement to add icons for the settings and profile section similar to the logout section.

**Describe the solution you'd like**
Added the respective icons to enhance the UI

**Screenshots**
![Screenshot 2019-04-28 08:06:23](https://user-images.githubusercontent.com/35539313/56857557-9d7c0780-698c-11e9-9ae3-a4ced05521ac.png)

**Additional context**
Working on it

**Comment by ritikamotwani** [comment]
No, this is not required.
