### ISSUE TITLE
No field for phone number for Speaker in `Speaker Edit`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2832]
**Describe the bug**

When you see speaker column in `Events/Speakers`, there is the column for the phone but in edit form, there is no field for phone

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Events/Speakers'
2. See error

**Expected behaviour**

Add Speaker Phone Field or remove phone column

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/56865227-35a7da00-69e9-11e9-8968-77b23d72913e.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 73.0.4

**Comment by ritikamotwani** [comment]
@kushthedude , the session-speaker form is a custom form. The organizer can or cannot keep the phone number as a compulsory field. 
This is not required .
Please close the issue and the PR.

**Comment by kushthedude** [comment]
@ritikamotwani  , i know this fact but the point was ,the speaker table has well designated column for Phone and if phone was to be kept as an optional than that column should be removed. What you think about it?

**Comment by ritikamotwani** [comment]
Yeah there has to be a column but the the field has to be decided by the organizer.
