### ISSUE TITLE
Does not create event even when start-date before end-date for dates having little difference

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2834]
**Describe the bug**

For dates with small difference, for example, ```start-date``` is 3 April 2019 and ```end-date``` is 4 April 2019 with both having time 00:00, it still shows the error message that ```start-date``` should be smaller then ```end-date```.

**To Reproduce**
1. Go to 'Create Event' page.
2. Fill form with dates mentioned above in bug description.
3. Click on 'Publish'.
4. See error.

**Expected behavior**

Should have created the event.

**Additional context**

Working on it

**Comment by kushthedude** [comment]
Closed by #2833
