### ISSUE TITLE
Disable Discount Code creation if there are no tickets added

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2835]
**Is your feature request related to a problem? Please describe.**

`Discount Codes` are created if there are no tickets for event too .

**Describe the solution you'd like**

 Disable `Code Creation` when there are no tickets**Describe alternatives you've considered**

**Additional context**

Working upon it

**Comment by shreyanshdwivedi** [comment]
@kushthedude are you still working on it?

**Comment by vishakhanihore** [comment]
@shreyanshdwivedi Can I work on it ?

**Comment by shreyanshdwivedi** [comment]
Go ahead @vishakhanihore

**Comment by kushthedude** [comment]
Ticket are required to publish event hence closing it.
