### ISSUE TITLE
Standardize font and fix image on payment page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2839]
* The font on the payment page had different sizes. 
* The payment image on the bottom left is squeezed.

Expected:
* Please use the same font size/style in the different boxes. The bottom left box should use the same size as others.
* Show the bottom left image correctly
* Take out spaces in front of colon e.g. "From : Thursday, March 19th 2020, 9:30 AM (+08) 
To : Sunday, March 22nd 2020, 5:00 PM (+08)" -> "From: Thursday, March 19th 2020, 9:30 AM (+08) To: Sunday, March 22nd 2020, 5:00 PM (+08)"

![Screenshot from 2019-05-01 10-14-40](https://user-images.githubusercontent.com/1583873/57003796-b9d1ab80-6bfb-11e9-8738-b919d313ae54.png)

**Comment by uds5501** [comment]
Looking into it

**Comment by uds5501** [comment]
@CosmicCoder96 Please close this

**Comment by CosmicCoder96** [comment]
closed in https://github.com/fossasia/open-event-frontend/pull/2841
