### ISSUE TITLE
Menu overflow on admin page for tablet screen

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#284]
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The menu options `modules` & `content` are overflowing on the admin page for tablet portrait & Small tablet landscape which can be seen in images
![image](https://user-images.githubusercontent.com/12701036/27311388-291944d0-557e-11e7-94f2-4e6147657548.png)
![image](https://user-images.githubusercontent.com/12701036/27311398-3b247424-557e-11e7-847c-6b587a5db436.png)

**Expected behavior:**
The menu should not overflow for any device.

I would like to work on this. 
@geekyd Please assign. :+1:

**Comment by niranjan94** [comment]
For tabs, make the menu scrollable

**Comment by harshitagupta30** [comment]
@niranjan94 Can you please guide me how to proceed for making the menu scrollable because I tried many ways but could not find the right way and exact solution. It would be very great if you can help me out. Thanks a lot :+1:

**Comment by niranjan94** [comment]
Just adding an `overflow-x: auto` to the column containing the tabs would make it scrollable when needed.

**Comment by harshitagupta30** [comment]
@niranjan94 Thanks a lot!
