### ISSUE TITLE
`Submit Button` does not work in `Create Session`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2842]
**Describe the bug**

`Submit Button` is not working under `Create Session`

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Events/Session'
2. Click on `Create Session` above the table
3. Fill the details and click on `Submit`

**Expected behaviour**

`Submit` should work as expected

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/57016492-0f2bae00-6c38-11e9-8fc1-9ea712fa8d0e.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.4

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Can you guys please check once, As of now its working fine for me now.

**Comment by uds5501** [comment]
@kushthedude I can still replicate this error :/

**Comment by kushthedude** [comment]
@uds5501 Will look into tomorrow , and will solve it if I find it 😄

**Comment by mohitm15** [comment]
@kushthedude Any updates?

**Comment by kushthedude** [comment]
@mohitm15 I cant reproduce , If you can reproduce , please ask @uds5501 if it still exists

**Comment by ritikamotwani** [comment]
@uds5501 , it's working fine for me.
Could you please check again?

**Comment by uds5501** [comment]
@ritikamotwani it's working fine via CFS, but I can't add a session using the add-session form in event\session tab. Is that working as well?

**Comment by ritikamotwani** [comment]
I didn't check it for cfs but checked it for events/{event_identifier}/sessions/create form.

**Comment by uds5501** [comment]
@ritikamotwani Then I will close this issue for now and reset my browser, maybe it would work
