### ISSUE TITLE
Extra Blank Speaker in `Create Session`.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2843]
**Describe the bug**

When you create a session and Choose the `Speaker ` from the dropdown , There is a blank drop-down.

**To Reproduce**

1. Go to 'Create Session'
2. Click on 'Select Speaker'

**Expected behavior**

Fix the bug

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/57016709-48185280-6c39-11e9-9df0-603456e645f7.png)

**Desktop (please complete the following information):**
 - OS:MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.4

**Comment by mohitm15** [comment]
@kushthedude this covers in #2458.

**Comment by CosmicCoder96** [comment]
Fixed in https://github.com/fossasia/open-event-frontend/pull/2874
