### ISSUE TITLE
Typo in languages drop-down

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2845]
**Describe the bug**

Typo in the languages dropdown

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to home page
2. Click on 'languages'
3. See error

**Expected behaviour**

Fix the typo

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Browser : chrome
 - Version : 71.0398

**Additional context**

Working

**Comment by uds5501** [comment]
@CosmicCoder96 @mariobehling Please add 'beginner friendly' tag on this issue

**Comment by kushthedude** [comment]
@uds5501 No use of the tag , A pr has already been opened on it
