### ISSUE TITLE
 Languages added in the drop down are not sorted

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2847]
**Describe the bug**

The languages added latest in the drop down of languages are not sorted as some of them were added latest.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Home page'
2. Click on 'English button'
3. See error

**Expected behaviour**

Should be in sorted order

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Chrome
 - Version : 71.0398

**Additional context**

Working on it

**Comment by ritikamotwani** [comment]
Not required for now.
