### ISSUE TITLE
Only access external services on pages that really need them

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2849]
Many pages access external services like maps.gstatic.com, Google usercontent, twitter platform, license.net on pages that don't display any related info. Actually only very few pages should require external services.

Please check different pages and get rid of calls to external pages on pages that don't need any info from those services.

![Screenshot from 2019-05-02 15-36-11](https://user-images.githubusercontent.com/1583873/57061724-8755aa80-6cf0-11e9-9877-c54bb2e61d24.png)

**Comment by iamareebjamal** [comment]
Twitter, etc got loaded on pages which required it. Fonts and analytics have been fixed in #5333
