### ISSUE TITLE
Tickets that are unpaid are showing up as placed. Expected: Should show up as "Pending" and Expire after 1 day

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2852]
Tickets that are unpaid are showing up as placed. Expected: Should show up as "Pending" and Expire after 1 day.

This issue shows in
* Organizer Ticket Page
* My Tickets Page: https://eventyay.com/my-tickets/upcoming

![Screenshot from 2019-05-03 16-48-22](https://user-images.githubusercontent.com/1583873/57127527-48dcf000-6dc3-11e9-9d56-e3f835ade6de.png)

**Comment by kushthedude** [comment]
@shreyanshdwivedi Can you take care of this as well in you PR regarding open orders?

**Comment by shreyanshdwivedi** [comment]
@kushthedude this issue requires proper implementation as the unpaid tickets are required to expire after 1 days. So, I'll suggest that we should keep both the PRs separate. 
I'm a bit busy this week so if you want you can take it up and open a separate PR for this issue.

**Comment by kushthedude** [comment]
@shreyanshdwivedi Cool i will look into it

**Comment by mariobehling** [comment]
Expected is:
1. Ticket orders that use online payment methods (credit card, paypal) should be labeled as "pending" until they are paid and expire after 1 day.
2. Ticket orders that use offline payment methods (bank, cheque) should be labeled as "Placed" once the user has hit the button "order". These user need to pay offline. This is only the case if the organizer has specified offline payment.

**Comment by kushthedude** [comment]
Noted @mariobehling , Will do as expected 😄

**Comment by uds5501** [comment]
@kushthedude We can make this a scheduled task handled at server side. How about I take this up on server side?

**Comment by kushthedude** [comment]
@uds5501 not sure what @mariobehling and @CosmicCoder96 want, but if they agree. You may go on server side and i will take care here

**Comment by uds5501** [comment]
@kushthedude can I take over?

**Comment by kushthedude** [comment]
@uds5501 did half work , will be pushing soon ,😅

**Comment by uds5501** [comment]
Oh, can I take care of the state change part on the backend?

**Comment by kushthedude** [comment]
> Oh, can I take care of the state change part on the backend? @kushthedude

Just a question, Is there really need to handle it on backend , Cant we do all on frontend ?

**Comment by uds5501** [comment]
> Just a question, Is there really need to handle it on backend , Cant we do all on frontend ?

@kushthedude How will you set the status to `expired` automatically after a day on the frontend?

**Comment by kushthedude** [comment]
Cool , 👍 Go on

**Comment by uds5501** [comment]
@kushthedude your PR is awaited

**Comment by kushthedude** [comment]
@uds5501 did your pr got merge?

**Comment by uds5501** [comment]
@kushthedude The PR will get merged, already approved. But it won't affect your PRs though, so you may push em whenever you feel like it :smile:

**Comment by kushthedude** [comment]
Cool ,

**Comment by uds5501** [comment]
@kushthedude The PR has been merged at the server side, please push your PR here

**Comment by kushthedude** [comment]
Half of work is done , but i wont be able to push the pr today .

**Comment by CosmicCoder96** [comment]
Irrelevant now, default status has been changed to pending.
