### ISSUE TITLE
Ticket Orders that are Paid should show up on top of My Tickets Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2853]
The tickets that are paid should show up on the top. Any other tickets "Placed" or "Pending" should show up below.

![Screenshot from 2019-05-03 16-49-29](https://user-images.githubusercontent.com/1583873/57127610-8e99b880-6dc3-11e9-91f8-1bb0f2f803a4.png)

**Comment by shreyanshdwivedi** [comment]
@mariobehling we are changing the UI of `My Tickets` section according to https://github.com/fossasia/open-event-frontend/issues/2821. A PR is also opened on the issue which will itself separate the completed and open tickets. Then this issue will be irrelevant

**Comment by shreyanshdwivedi** [comment]
As the issue related to UI of `My Tickets` is closed now (https://github.com/fossasia/open-event-frontend/issues/2821), I'll be working on this in upcoming few days

**Comment by shreyanshdwivedi** [comment]
@mariobehling can you please recheck if this issue persists or not? Since the PR https://github.com/fossasia/open-event-frontend/pull/2823 got merged, the completed and pending tickets are already separated. I think this issue needs to be closed now
