### ISSUE TITLE
Cannot edit FOSSASIA 2020 event: Error Message - ticket sales-ends-at should be before event ends-at

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2855]
Cannot edit FOSSASIA 2020 event: Error Message - ticket sales-ends-at should be before event ends-at.

Ticket sales dates are ending before the actual event ends. So error message is wrong.

![Screenshot from 2019-05-03 17-26-23](https://user-images.githubusercontent.com/1583873/57129374-c35c3e80-6dc8-11e9-85ae-846af419f30d.png)

**Comment by mohitm15** [comment]
Should I take this
