### ISSUE TITLE
Invoice Company Data in Wizard Step 1 not saved permanenty

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2856]
Invoice Data in Wizard Step 1 is missing when accessing Wizard again. It also does not show up on invoice, e.g. https://eventyay.com/events/a315169f/edit/basic-details

![Screenshot from 2019-05-03 17-28-21](https://user-images.githubusercontent.com/1583873/57129457-05858000-6dc9-11e9-93f9-f4ef021e4ee4.png)

**Comment by kushthedude** [comment]
Looking into it

**Comment by uds5501** [comment]
@mariobehling This is working fine.

A sample SS from current rollout of eventyay:
![image](https://user-images.githubusercontent.com/21087061/57221588-6d340900-701d-11e9-9a8f-52a422aab507.png)

**Comment by kushthedude** [comment]
> @mariobehling This is working fine.
> 
> A sample SS from current rollout of eventyay:
> ![image](https://user-images.githubusercontent.com/21087061/57221588-6d340900-701d-11e9-9a8f-52a422aab507.png)

+1 Same here on my local

**Comment by CosmicCoder96** [comment]
Fixed now. Was an issue with legacy data.
