### ISSUE TITLE
Maximum Number of Tickets should be greater than Minimum

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2857]
**Describe the bug**

When you change the additional setting of a ticket and set max and min tickets per order, the following error occurs

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Event Wizard' of `Existing Event`
2. Click on 'Ticket Setting'
3. Set Minimum Tickets Greater than maximum

**Expected behaviour**

Fix the bug

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/57150423-e9dfa100-6deb-11e9-980b-e23dbc1b6ce6.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.4

**Comment by mohitm15** [comment]
@kushthedude This is vague issue pal. Check below
![Screenshot 2019-05-04 19:53:45](https://user-images.githubusercontent.com/35539313/57180462-6a62d800-6ea6-11e9-96c6-9f737f5ba0bb.png)

**Comment by kushthedude** [comment]
@mohitm15 What you say about this 
![image](https://user-images.githubusercontent.com/44091822/57180575-992d7e00-6ea7-11e9-8119-76e2003bbc44.png)
![image](https://user-images.githubusercontent.com/44091822/57180576-9cc10500-6ea7-11e9-83bf-b21439e5fb71.png)

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Can anyone of you check the following bug by editing an `Existing Event` ?

**Comment by mohitm15** [comment]
@kushthedude If you even do it for 'Existing element', it is non-reproducible. What is the meaning to set min-max orders first correctly and then editing it incorrectly? :laughing: :

**Comment by kushthedude** [comment]
Let others check , btw what if i dont set it initially and then set it , i
think you didnt get the concept of existing event .

**Comment by uds5501** [comment]
@kushthedude it's working fine in old events too.
![image](https://user-images.githubusercontent.com/21087061/57183040-dce2b080-6ec4-11e9-8892-93f6005bdb97.png)


![image](https://user-images.githubusercontent.com/21087061/57183040-dce2b080-6ec4-11e9-8892-93f6005bdb97.png)

**Comment by kushthedude** [comment]
What about the ss i have shown than🤔 , i am afraid its Mac specific bug

**Comment by uds5501** [comment]
@kushthedude I used the exact specs you set there in an existing event. Yet it was working fine

**Comment by CosmicCoder96** [comment]
Can't reproduce it on safari.
