### ISSUE TITLE
Add Omise Payment Gateway for Thailand

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2859]
Omise is important for our Thai event. Please add it.

More: https://www.omise.co/

**Comment by kushthedude** [comment]
@mariobehling , @CosmicCoder96 is taking care if it and the issue has been transferred to server

**Comment by mariobehling** [comment]
We need both frontend and backend and we need several people to start working on it. We cannot leave everything to @CosmicCoder96. 

Frontend part 1. Please add it to:
* Wizard Step 1
* Payment Gateways when buying tickets

Frontend part 2. Please add it to:
* Admin UI with fields to add keys

**Comment by kushthedude** [comment]
I will be working on it . @uds5501 want to join ?

**Comment by uds5501** [comment]
@kushthedude Sure, we can handle the frontend part

**Comment by mrsaicharan1** [comment]
@uds5501 Let's try to finish this asap. I'll work on the server part of this and we can collaborate to implement this.

**Comment by kushthedude** [comment]
@mrsaicharan1 i think its already done

**Comment by uds5501** [comment]
@mrsaicharan1 sure.

@kushthedude nope.
