### ISSUE TITLE
Don't show "Save as Draft" in Wizard once event is published

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2865]
Once an event is published the option "Saved as Draft" is very confusing. Clicking it will result in unpublishing the event. Don't show the option "Save as Draft" once the event is published. Only show the option "Save as Draft" if an event is in the stage "Unpublished.

![Screenshot from 2019-05-06 01-08-16](https://user-images.githubusercontent.com/1583873/57197770-fd326e00-6f9d-11e9-8846-e6d0d991969f.png)

**Comment by uds5501** [comment]
Working on it

**Comment by kushthedude** [comment]
@CosmicCoder96 The PR merged above only removes the button from `Basic-Details` button is still present in other wizards .

**Comment by CosmicCoder96** [comment]
@kushthedude please remove it from other places in a separate PR. Just mark
it as a follow up to this one.

**Comment by kushthedude** [comment]
@CosmicCoder96 Already made a PR please review it 😄
