### ISSUE TITLE
Preview Button uses link to last Discount Ticket Link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2867]
The preview link on the organizer page uses a link to the last configured Discount Code Ticket Link instead of the plain link.

E.g. it uses
https://eventyay.com/e/39a15c6e?code=openxlab

Instead it should use 
https://eventyay.com/e/39a15c6e

![Screenshot from 2019-05-06 23-31-40](https://user-images.githubusercontent.com/1583873/57236267-3da1f280-7057-11e9-9ada-65d3f96c518f.png)

**Comment by kushthedude** [comment]
On It

**Comment by shreyanshdwivedi** [comment]
@kushthedude any update on this?

**Comment by shreyanshdwivedi** [comment]
@mariobehling I'm unable to reproduce on my local.
@uds5501 @mrsaicharan1 please check if you can reproduce this on your local?

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi Can't reproduce this. Works fine locally.

**Comment by kushthedude** [comment]
@shreyanshdwivedi Use a Discount Code in public page of event and than use
previewbutton for the event , you will se the error

**Comment by shreyanshdwivedi** [comment]
@kushthedude please elaborate the steps

**Comment by kushthedude** [comment]
- Create a discount code for the event
- Apply the discount code on tickets.
- go to manage events and click on preview .
- you will see the discount code is still applied .

Mind if i takeover i have made some change in local if you say so
@shreyanshdwivedi 😅

**Comment by shreyanshdwivedi** [comment]
@kushthedude please go ahead
