### ISSUE TITLE
Discount Of Other Event is getting applied on some different event

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2869]
**Describe the bug**

Discount Of Other Event is getting applied on some different event

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Create a Discount for some `X` Event'
2. Apply it on some `Y` Event
3. See error

**Expected behaviour**

Error should be given `Discount Not Valid`
**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/57300843-3f21f800-70f5-11e9-8622-f17d3a1b70e1.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 73.0

**Comment by uds5501** [comment]
@kushthedude Working on it? If not, i may have found a solution :sweat_smile:

**Comment by kushthedude** [comment]
Go on
