### ISSUE TITLE
Tax and License is Choose or not show error bug

### ISSUE THREAD

**Issue by kokoye2007** [fossasia/open-event-frontend#2875]
**Requirement popup**

**To Reproduce**
1.Basic Details page
2. Edit and Add info 
3. when click "Next" or "Publish" button  
4. Tax 779 not found 
5. License of Event Data & Content is use or not, not found 

![Screenshot from 2019-05-08 18-05-49](https://user-images.githubusercontent.com/3091754/57373184-c5097600-71bd-11e9-89c8-5814d5088be9.png)

**Comment by kushthedude** [comment]
Not Reproducible !
