### ISSUE TITLE
Add Tooltip for Event Bar for Mobile View 

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2877]
**Is your feature request related to a problem? Please describe.**

There is no description for `Event Bar` in mobile view, We only get to see `Icons` which are not clear about the appearance or functionality

**Describe the solution you'd like**

Add Tooltip

#### Screenshot
<img width="1440" alt="Screenshot 2019-05-08 at 11 01 41 PM" src="https://user-images.githubusercontent.com/44091822/57395267-47f1f700-71e5-11e9-9c3f-5b451ee98e9c.png">

**Comment by mohitm15** [comment]
@kushthedude not a prior work as the icons used are standard icons which makes them self descriptive.
What's your views @CosmicCoder96 ?

**Comment by kushthedude** [comment]
Already discussed
