### ISSUE TITLE
'Publishing Event' again throws error

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2880]
**Describe the bug**

`Publishing Event` throws `Unexpected Error`

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Event/View'
2. Click on 'Publish , Unpublish'
3. See error

**Expected behaviour**

Fix the error

**Screenshots**

<a href="https://imgflip.com/gif/30jvjw"><img src="https://i.imgflip.com/30jvjw.gif" title="made at imgflip.com"/></a>
**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari
 - Version: 23.0.2

**Comment by kushthedude** [comment]
@uds5501 Is it reproducible to UBUNTU ?

**Comment by uds5501** [comment]
@kushthedude No

**Comment by kushthedude** [comment]
Did you see gif?

**Comment by kushthedude** [comment]
@CosmicCoder96 Can you please check it out on safari ?

**Comment by kushthedude** [comment]
@ritikamotwani @uds5501 This was solved by recently merged PR of @iamareebjamal Regarding updation of dependencies, No need to keep it open now
