### ISSUE TITLE
Addition of CODE OF CONDUCT

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2884]
Recently i came across many open source organisation such as ‘Pallet’ , ‘Swift’ , ‘Fox Dev ‘ .
All of the repo had a ‘COC’ file .
I propose to add a similar but more reliable COC for our repos .
All the views are welcome here

**Comment by kushthedude** [comment]
@CosmicCoder96 @iamareebjamal @mariobehling ,
I think we should add a covenant based COC file in our repositories . 
Please give your valuable opinions.

**Comment by mariobehling** [comment]
FOSSASIA has a code of conduct. We should not keep a CoC in the repos. This has been discussed before at other times. Please separate politics and code. Thanks.
