### ISSUE TITLE
Missing currencies corresponding to countries in drop-down

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2891]
**Describe the bug**

Some of the currencies are missing in the dropdown corresponding to the countries under the ticket section.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create event'
2. Click on 'ticket section
3. Compare both drop-downs

**Expected behaviour**

Add missing currencies

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser :chrome
 - Version :71.394

**Comment by ritikamotwani** [comment]
Opened without checking the documentation of PayPal and stripe.
