### ISSUE TITLE
Dummy Button under `Tickets/Orders`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2893]
**Describe the bug**

`Resend Confirmation` is a dummy button associated with no action.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Tickets/Order'.
2. Click on 'Mail Icon'.
3. See error.

**Expected behaviour**

Create an action associated with `Confirmation.

**Screenshots**

<img width="1170" alt="Screenshot 2019-05-12 at 2 53 51 AM" src="https://user-images.githubusercontent.com/44091822/57575092-f1ddb780-7461-11e9-905d-871245b06f2c.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0.5

**Additional context**

Will work on it

**Comment by Anupam-dagar** [comment]
Due to inactivity, I would like to take this up.

**Comment by Anupam-dagar** [comment]
@kushthedude can you point out to the original confirmation which is sent on order?

**Comment by shreyanshdwivedi** [comment]
@kushthedude I think that button is removed from the table. Please check and close this issue

**Comment by uds5501** [comment]
@kushthedude I will take care of this one.
