### ISSUE TITLE
Missing popup message/tool-tip in toggle eye

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2896]
**Describe the bug**

Since toggle eye icon is implemented but still the icon is very confusing, so added the missing tooltip just like  <b> implemented in gmail </b>

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'log in'
2. Click on 'toggle eye'
3. See ambiguity

**Expected behaviour**

A tooltip like in Gmail should be implemented 

**Screenshots**

Gmail implementation snapshot
![Screenshot 2019-05-12 05:02:12](https://user-images.githubusercontent.com/35539313/57575970-36258380-7473-11e9-8d6b-736ce07bc458.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser CHROME
 - Version 71.0394

**Additional context**

working on it

**Comment by CosmicCoder96** [comment]
don;t want it, it's not aesthetic.
