### ISSUE TITLE
Add a simple user profile page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#29]
![screen shot 2017-05-08 at 9 22 48 pm](https://cloud.githubusercontent.com/assets/2404372/25812658/9fa58476-3434-11e7-8ee2-2de4865f3473.png)

Add a simple user profile page located at `/profile`.

- Should contain the image upload component (already present in the project.)
- Should contain the rich text editor component for the Details section
- Should contain form validation on submit
- Let the whole profile page be inside a component just like login form. So that we get scopped jquery selection capabilities and we can use the `FormMixin`. (See reference below).

**References:**
- [`app/components/forms/login-form.js`](https://github.com/fossasia/open-event-frontend/blob/development/app/components/forms/login-form.js) - for validation. (Note `FormMixin` and `getValidationRules`)
- [`app/templates/components/forms/login-form.hbs`](https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/forms/login-form.hbs) - for form submit. Note `{{action 'submit' on='submit'}}`
- [`app/templates/components/forms/wizard/basic-details-step.hbs:L77`](https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/forms/wizard/basic-details-step.hbs#L77) - for image upload component
- [`app/templates/components/forms/wizard/basic-details-step.hbs:L72`](https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/forms/wizard/basic-details-step.hbs#L72) - for rich text editor component
- https://semantic-ui.com/collections/form.html
- https://semantic-ui.com/collections/grid.html

**Comment by CosmicCoder96** [comment]
@niranjan94 I would like to start to work on this.
