### ISSUE TITLE
Admin Mail Logs page at shows error  

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2905]
Mail Logs page at https://eventyay.com/admin/reports/system-logs/mail-logs displays error messages when sorting. It also shows more than 10 messages even though 10 is set as default.

![Screenshot from 2019-05-13 10-20-26](https://user-images.githubusercontent.com/1583873/57606244-c72a5680-7568-11e9-9b6b-beb92ffbdea4.png)

**Comment by uds5501** [comment]
Will have a look at it

**Comment by CosmicCoder96** [comment]
Was due to legacy data, cleared now.
