### ISSUE TITLE
Only allow "Publish Event" If the Event has Relevant Info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2920]
A user should always be able to save a draft with basic info. However in order to publish an event the following info should be required:
* Name of Event
* Location
* Dates
* At least one Ticket exists

Show an error message if the event does not have sufficient data to get published.

Please delete the option to show events from other platforms using a URL for now

**Comment by shreyanshdwivedi** [comment]
on it

**Comment by uds5501** [comment]
@shreyanshdwivedi should I handle the server part of this issue?

**Comment by iamareebjamal** [comment]
Is the ticketing condition necessary? By default, it is allowed that the ticketing system be disabled

**Comment by mariobehling** [comment]
@iamareebjamal Our experience is that some spammers used this options. There are ways to deter them differently, but that requires more work and the benefit is small. So, for now, we should disable the option to switch off the ticketing system.

**Comment by mariobehling** [comment]
This is also related to this issue: https://github.com/fossasia/open-event-frontend/issues/2482

**Comment by shreyanshdwivedi** [comment]
@uds5501 actually there is not much to do in front-end for this issue, so I'll handle the server part too. 😅

**Comment by uds5501** [comment]
@shreyanshdwivedi Sure

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 please review the PR opened for this issue and reply to this comment https://github.com/fossasia/open-event-frontend/pull/2926#issuecomment-493275005

**Comment by shreyanshdwivedi** [comment]
This issue requires server side implementation. Please transfer it to serve @CosmicCoder96

**Comment by iamareebjamal** [comment]
It also requires frontend part, so instead, open a server issue in parallel to this

**Comment by uds5501** [comment]
I will break this in some sub-issues which can be worked upon immediately.
