### ISSUE TITLE
Tables resulting in internal scroll bars and mobile view loosing table headers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2927]
Internal scroll bars should be avoided. Please implement tables in a way that there is no scroll bar. Also ensure mobile views show table headers e.g. on https://eventyay.com/events/live

![Screenshot from 2019-05-15 23-17-21](https://user-images.githubusercontent.com/1583873/57811140-c7457480-7769-11e9-9d3c-4397d074ac72.png)

![Screenshot from 2019-05-15 23-31-53](https://user-images.githubusercontent.com/1583873/57811146-cb719200-7769-11e9-9f82-6cfcbe4d922e.png)

**Comment by kushthedude** [comment]
@CosmicCoder96 Regarding this, as we are using `ember table` and I think there is no way to customize the width of columns

**Comment by kushthedude** [comment]
Working on it

**Comment by CosmicCoder96** [comment]
@kushthedude Check out the components for table cells, inside ui-table, there are template files.

**Comment by kushthedude** [comment]
@CosmicCoder96 What i was planning to do here was ,`In Manage Events ` we have shifted the `Cell Action` column beneath the Event Name , I was planning to do such thing for `Admins/Events` too , What you say about it ? And regarding the `Loose Table Headers` , I have something which can partially solves it .

**Comment by kushthedude** [comment]
@CosmicCoder96 @niranjan94 Since the loose headers are solved , And for Events Table Scroll, In Mobile View, I was thinking to implement a `Card Stack` View for events in devices with less screen size, So that user don't need to scroll the complete table for details as done in EventBrite , Should I proceed with the following?

**Comment by niranjan94** [comment]
@kushthedude not right now. This is not a priority. There are other more important bugs pending fixing. And moreover, You already have 5 PRs open as of now. Please work on getting those merged before taking up any new issues.
