### ISSUE TITLE
Create an app section for the Attendee and Organizer app on the front page and mobile app pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2929]
Please create sections for the mobile attendee app and organizer app on the start page.

Also create a landing page for the apps:
a) at /mobile-app for the attendee app (e.g. compare to https://www.eventbrite.com/eventbriteapp/) and b) at /organizer-app for the organizer app (e.g. compare to https://www.eventbrite.com/l/Organizer-check-in-app/)

**Comment by kushthedude** [comment]
On it

**Comment by uds5501** [comment]
@kushthedude still on it?

**Comment by kushthedude** [comment]
Yeah
