### ISSUE TITLE
Event Editing Buggy, Date Errors, Deleted Tickets Suddenly available again

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2933]
The editing of events is still buggy. Error messages appear and suddenly the error is gone. A common error when changing the date/time is that other fields are changed suddenly as well. Also the event sometimes cannot be saved. A message appears something like "start date should be before ticket sale ends". The dates are set in a logic way, but errors still stay. Another issue is that deleted tickets suddenly appear again and at reload disappear.

It is difficult to pin point issues as they seem to appear and disappear randomly.

![Screenshot from 2019-05-17 12-34-31](https://user-images.githubusercontent.com/1583873/57922837-f3afdc80-78a0-11e9-8bb6-75678bdb1c64.png)

A number of these tickets above had been deleted long ago. After reload they disappeared again.

**Comment by CosmicCoder96** [comment]
Was fixed when validations were removed.
