### ISSUE TITLE
Events Dashboard showing URL in ticket field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2934]
There should not be a URL in the ticket field.

![Screenshot from 2019-05-17 12-45-38](https://user-images.githubusercontent.com/1583873/57923165-c879bd00-78a1-11e9-80cc-ecc20ce7e11a.png)

**Comment by shreyanshdwivedi** [comment]
On it

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi just reverting #2937 will do.
