### ISSUE TITLE
Download Tickets has file name "Tickets" instead of Event Name with details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2936]
The file download at "Download Tickets" should have the file name as follows:
* [EventName]_Tickets_[OrderNumber].pdf

![Screenshot from 2019-05-17 12-54-37](https://user-images.githubusercontent.com/1583873/57923637-235fe400-78a3-11e9-91b0-9f317a47c214.png)

**Comment by pradeepgangwar** [comment]
There is one more problem here. When using Firefox download tickets does not work. I ordered a ticket but was not able to download ticket in my local development environment.

I will try fixing this.
