### ISSUE TITLE
Organizer Dashboard Ticket Section: Date Column missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2938]
It is important for organizers to view tickets according to the date. The Date Column in the Orders and Attendees table is missing though.

E.g. here: https://eventyay.com/events/39a15c6e/tickets/orders/completed

![Screenshot from 2019-05-17 13-35-59](https://user-images.githubusercontent.com/1583873/57925548-e3036480-78a8-11e9-9cc7-ad58d6e0dd40.png)

**Comment by shreyanshdwivedi** [comment]
We haven't found any way to store completed date and time of tickets. Till it is resolved, addition of Date and Time column will be of no use. 
You can see `Invalid date` below tickets.

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi #2935 is resolved now.

**Comment by shreyanshdwivedi** [comment]
I'll open a PR today itself.
