### ISSUE TITLE
Orders: Buyer info is missing after successful order

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2945]
![image](https://user-images.githubusercontent.com/17252805/57965612-21685480-7979-11e9-97df-6c68c7d6e7f6.png)

**Comment by uds5501** [comment]
@CosmicCoder96 This issue is simple. This happens because the user has no name. and we are using the logged in user as the ticket buyer. 
Also related : #2700 
Current workaround could be that the user who bought the ticket saves a name in his profile. In the meanwhile we investigate further
