### ISSUE TITLE
Orders Page: Move Actions to first column below existing info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2949]
The actions column of the Orders Page cannot be sorted and it is not required that it has its own column. Please 
* move it to the front row
* below the existing info
* increase the size of the icons
* make it in horizontal order

![Screenshot from 2019-05-18 16-20-07](https://user-images.githubusercontent.com/1583873/57971047-36e57a80-7989-11e9-83d7-c37d035f5c9c.png)

**Comment by uds5501** [comment]
@mariobehling On it
