### ISSUE TITLE
Event Organizer Orders Page: Expired Orders Showing up as Placed Orders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2951]
Placed Orders are orders that are paid through offline methods. If an event has cheque payment for example an order can be made with a choice "placed order". The user can then pay it offline, at the event or transfer it outside of the system. 

Currently orders are showing up in events that are expired and are not placed. 

Pending orders should expire and just get move to the category "Expired" after 72 hours. Expired orders should not show up as finished "placed" orders.

![Screenshot from 2019-05-18 18-39-05](https://user-images.githubusercontent.com/1583873/57972559-a9138a80-799c-11e9-9fa0-2b33aa25239a.png)

**Comment by shreyanshdwivedi** [comment]
On it

**Comment by shreyanshdwivedi** [comment]
Just to clarify. Currently we are labeling all the orders with `paymentMode` as `bank`, `cheque`, `onsite` or `free` tickets as `Completed` tickets instantaneously. Here's what I'm planning to implementing - 
 - Free orders will be labelled as `Completed` at the time of order
 - Orders with payment mode `bank`, `cheque`, `onsite` will be labeled as `Placed`
 - Orders with stripe/paypal as payment options will be labeled as `Pending` and will be labeled as `Expired` after 72 hours if payment is not done till then. If payment is successful within this span of 72 hours, it'll be labeled as `Completed`. 
@mariobehling is this what you expect?

**Comment by uds5501** [comment]
@shreyanshdwivedi Actually I was going to apply these changes in #2852 as @kushthedude  is a little busy. I think that this PR requirements will be covered in covered in that issue itself. As far as the expiry time is concerned, I made a scheduled task with specs of 24 hours. Maybe changing the duration would solve that too?

**Comment by shreyanshdwivedi** [comment]
Yeah. I was looking into it and found out that scheduled task is already there with a period of 1 day. Also, it was not much of the change so I made it locally. If you allow, I can push it in 5 minutes :sweat_smile:

**Comment by uds5501** [comment]
Oh, in that case sure, go ahead @shreyanshdwivedi
