### ISSUE TITLE
Create Session and Create Speakers Form have unlabeled input fields

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2952]
There are unlabeled input fields in the create sessions and create speakers form.

![Screenshot from 2019-05-18 19-30-32](https://user-images.githubusercontent.com/1583873/57973083-88026800-79a3-11e9-941e-2fe96126b963.png)

**Comment by uds5501** [comment]
Looking into it

**Comment by uds5501** [comment]
@mariobehling Could you send a screen shot of custom registration form of the event?

**Comment by kushthedude** [comment]
@mariobehling @uds5501 To check the `unlabelled input field` , I enabled to collect all fields data and i cant see any unlabelled field in it .
<img width="699" alt="Screenshot 2019-05-19 at 4 45 59 PM" src="https://user-images.githubusercontent.com/44091822/57981483-ab85eb00-7a55-11e9-8bd6-d8e114e6988d.png">
<img width="654" alt="Screenshot 2019-05-19 at 4 46 07 PM" src="https://user-images.githubusercontent.com/44091822/57981485-b2acf900-7a55-11e9-9963-199a63533989.png">

**Comment by uds5501** [comment]
@shreyanshdwivedi can you recreate this issue?

**Comment by mariobehling** [comment]
The screenshot is in the issue. Please activate all input fields in the final wizard step and see if you can recreate this.

**Comment by kushthedude** [comment]
@mariobehling i did the same and posted the ss above , all the fields have an input label

**Comment by CosmicCoder96** [comment]
@mariobehling Seems like this is a legacy data issue, which event was this?

**Comment by CosmicCoder96** [comment]
Fixed now.
