### ISSUE TITLE
Implement a tick box for organizers/admin to override Email requirement

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2953]
When a speaker registers they have to enter an email. It must be possible to override this requirement for organizers/admins, e.g. if a VIP speaker does not want to sign up himself. Please implement a small tick box below the Email Field as follows. Only show this option for organizers/admins (not for speaker who submit this through the online form):
* [ ] Do not require email for this speaker.

![Screenshot from 2019-05-18 19-29-21](https://user-images.githubusercontent.com/1583873/57973138-53db7700-79a4-11e9-9e88-5e8cb5522b24.png)

**Comment by mohitm15** [comment]
@mariobehling on it

**Comment by kushthedude** [comment]
@mohitm15 Status ?

**Comment by shreyanshdwivedi** [comment]
Taking this up due to inactivity

**Comment by kushthedude** [comment]
@shreyanshdwivedi If you have not done much on it , I wanted to take it 😅

**Comment by shreyanshdwivedi** [comment]
@kushthedude sure. Please go ahead :)

**Comment by shreyanshdwivedi** [comment]
@kushthedude any update?

**Comment by kushthedude** [comment]
Will be pushing PR soon

**Comment by Anupam-dagar** [comment]
@kushthedude @shreyanshdwivedi I would like to take this up.

**Comment by kushthedude** [comment]
@Anupam-dagar I will be pushing PR in an hour for it

**Comment by kushthedude** [comment]
@Anupam-dagar You can look into #3022 , For issues assigned to me I have PR's already opened 😅

**Comment by kushthedude** [comment]
@shreyanshdwivedi @Anupam-dagar I implemented the following feature on FE , but saw if Email is not sent to the Server , The server sends an `Unprocessable Entity` , If you want to do the server side changes please do them .

**Comment by shreyanshdwivedi** [comment]
@kushthedude I'll take a closer look on server

**Comment by kushthedude** [comment]
@shreyanshdwivedi that’d be great👍

**Comment by kushthedude** [comment]
@shreyanshdwivedi Did you check for the server ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude was waiting for the FE PR. Will check this today only
However, I guess email is a required attribute so it is expected error. Still will try to get more info

**Comment by shreyanshdwivedi** [comment]
@kushthedude speaker has required and non-nullable field `email` which is obviously raising the error you encountered. I'm not able to think of a way to encounter this.
I've a work-around though - Before creating the speaker object, we can check if the person creating it is organizer, we'll update the null email of the speaker to that of organizer's email. This will also give us a way to find out if speaker was added by admin or not.
@uds5501 @mrsaicharan1 we need your views too

**Comment by kushthedude** [comment]
@shreyanshdwivedi , I can think why its non-nullable , As if the session of the speaker gets rejected or accepted , It needs to be informed , What I can do is pass a dummy email from FE ?
@uds5501 ?

**Comment by shreyanshdwivedi** [comment]
As I suggested above, instead of dummy email we should add email of the organizer who added the speaker. @kushthedude

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 @niranjan94 should we proceed this way?

**Comment by shreyanshdwivedi** [comment]
@kushthedude we discussed this is meeting and we can proceed by adding organizers email

**Comment by kushthedude** [comment]
@shreyanshdwivedi Thanks for confirming

**Comment by uds5501** [comment]
@kushthedude are you working on it?

**Comment by kushthedude** [comment]
I think I told you about it yesterday @uds5501

**Comment by shreyanshdwivedi** [comment]
As @kushthedude mentioned in his last PR that this issue can be worked upon, I'll be working on this since the corresponding server PR is already merged
