### ISSUE TITLE
Add a "Order Form" Builder to collect User/Attendee/Byuer Info in Wizard Step 2

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2956]
Many event management have an Order Form. Please implement the same in Wizard Step 2 when users create an event.

Please compare the form builder of other systems e.g. here:
* https://www.eventbrite.com/support/articles/en_US/How_To/how-to-collect-information-from-all-event-attendees
* https://www.eventbrite.com/support/articles/en_US/How_To/how-to-create-custom-questions-for-attendees
* https://www.youtube.com/watch?v=WMBs0RihvuY

**Comment by uds5501** [comment]
@mariobehling We have a customizable order form, right? Should the addition of new fields and custom form be placed in that only?

**Comment by mariobehling** [comment]
@uds5501 There is no form builder for - ticket buyers - yet. The form we have at checkout is only covering basic data.

**Comment by kushthedude** [comment]
@uds5501 Can I take FE implementation ?

**Comment by uds5501** [comment]
@kushthedude I was kind of hoping to take this one myself :sweat_smile:

**Comment by mariobehling** [comment]
@uds5501 Please also check out how other e.g. eventbrite are showing the information that is collected in those add on forms and implement it in Open Event. Thank you!

**Comment by iamareebjamal** [comment]
Completed
