### ISSUE TITLE
Implement changing of submissions as bulk similar to Gmail

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2957]
Gmail has a feature to change emails in bulk. Please implement the same for sessions on the left hand side of the table.

![Screenshot from 2019-05-19 17-15-56](https://user-images.githubusercontent.com/1583873/57984206-d2462080-7a59-11e9-8b46-d7d5d3a8b7d9.png)

Gmail Bulk changes:

![Screenshot from 2019-05-19 17-16-47](https://user-images.githubusercontent.com/1583873/57984216-ea1da480-7a59-11e9-86ac-4a9ca8b0d13f.png)

**Comment by shreyanshdwivedi** [comment]
Will work on it

**Comment by shreyanshdwivedi** [comment]
@mariobehling just to clarify. Here is what I'm planning to do. I'll add a checkbox which on being clicked will show the action buttons beside the checkbox in horizontal position and if a user applies any action, it'll be applied for all the sessions. 
@uds5501 @kushthedude can you please suggest a good position for the checkbox? I don't find any appropriate place design wise.

**Comment by kushthedude** [comment]
@shreyanshdwivedi As far as I can see , the session tab is already to much congested , What you can do is provide a `List Icon` near search bar which on click will show a `Dropdown` with `Select` and `Select All` after one of them is selected , You can make `Checkbox` appear adjacent to `Action Buttons`

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 as we are going to switch to ember-table, it'll be better to wait till it is finalized

**Comment by mariobehling** [comment]
As we have quick way now to change the state on the page itself, we can defer this enhancement. Therefore closing this issue.
