### ISSUE TITLE
Redesign Sessions Page and Add Lock/Unlock Column

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2958]
Please redesign the sessions page as follows:
* Add a button in front for bulk changes
* Take out "short abstract" column
* Move the actions icons below "Title" and increase the size
* Add a column "Track"
* Add a column "Type" e.g. to distinguish workshops and talks
* Add column with an icon to lock/unlock a session (this feature will lock a session and associated speaker which will prevent her/him from further editing a session)

![Screenshot from 2019-05-19 17-18-19](https://user-images.githubusercontent.com/1583873/57984401-c65b5e00-7a5b-11e9-9845-32696617cb78.png)

**Comment by shreyanshdwivedi** [comment]
As i am working on implementation of bulk changes, I'll take this up too

**Comment by shreyanshdwivedi** [comment]
I'm opening a sub-issue on server for implementing `locking a session` feature. It'll involve adding a new attribute `isLocked` to session which will be initially set to false. And handling a PATCH request to update it.
@mariobehling can I proceed?
