### ISSUE TITLE
Research Rating Systems and Implement Ratings of Sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2959]
Systems such as papercall.io provide a rating system. Please research how other systems implement ratings of sessions and propose and implement a rating of sessions.

![Screenshot from 2019-05-19 17-26-11](https://user-images.githubusercontent.com/1583873/57984422-f3a80c00-7a5b-11e9-8448-fe37e2a55771.png)

**Comment by mrsaicharan1** [comment]
I'll be working on this.

**Comment by shreyanshdwivedi** [comment]
@mrsaicharan1 I'll like to work on this alongside you. I think we are trying to give admin/organizer the functionality to rate a session here. Right?
I'm opening a sub-issue on server to add a new field `rating` in `session schema`.

**Comment by kushthedude** [comment]
@shreyanshdwivedi @mrsaicharan1 As the `Rating System` has to be included , Have you guys planned a roadmap ` How are we going to implement it` ? I have some idea for it , As we developed a similar sort of thing for our gymkhana

**Comment by shreyanshdwivedi** [comment]
The final structure which is expected from this issue - 
we should rather try an option where we give any role that has the right to rate
   - the option to choose any star from 1 to 5

Also then we can have two more column showing
   - average rating
   - number of people who rated

Columns - `| Rate session | Avg Rating | No. of people rated |`

**Comment by mariobehling** [comment]
Closing this. We can follow up on next steps here https://github.com/fossasia/open-event-frontend/issues/3202
