### ISSUE TITLE
Front Page: Upcoming Events/Call for Speakers - only show up to 12 events and limit to events with pics and online payments

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2965]
The front page often shows events that are not relevant and even test events that are empty. Please change the front page listing as follows. 

In the section Upcoming Events and Call for Speakers:
a) only show up to 12 events per section
b) only show events that:
* Have a picture
* Have online payments
* Sold at least 5 paid tickets processed through online payment

![Screenshot from 2019-05-20 10-11-58](https://user-images.githubusercontent.com/1583873/58006431-5c3cca80-7ae8-11e9-8c99-f0d0d8bdba25.png)

**Comment by uds5501** [comment]
@CosmicCoder96 Taking over.

**Comment by uds5501** [comment]
@CosmicCoder96 This issue will be requiring too many additional calls for different elements of event proxy. Do we need to take it as a priority right now?

**Comment by CosmicCoder96** [comment]
No not a priority.  I have something else in mind, filtering which is
already there already makes the api call really slow for some reason. We
need to take a different approach to decrease load times on front page.
Let’s discuss it in the next meeting.

**Comment by uds5501** [comment]
@CosmicCoder96 Sure.

**Comment by mariobehling** [comment]
Closing this in favor of https://github.com/fossasia/open-event-frontend/issues/3658
