### ISSUE TITLE
Public Event Page should show beginning and end date if event is over several days

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2966]
If an event is taking place over several days the event only shows the beginning date. Please show beginning and end date if the event is happening over several days.

![Screenshot from 2019-05-20 10-28-30](https://user-images.githubusercontent.com/1583873/58007271-37e1ed80-7aea-11e9-87a3-745c2a6f85f7.png)

**Comment by kushthedude** [comment]
Lookin on it

**Comment by prateekj117** [comment]
@kushthedude Still on it? If not, I would like to take this up.

**Comment by kushthedude** [comment]
@prateekj117 Working on it

**Comment by mohitm15** [comment]
@kushthedude I think its similar to #2650

**Comment by kushthedude** [comment]
@mohitm15 both are different
