### ISSUE TITLE
Start Page Events should show City and Country

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2967]
If a street address is defined the events on the start page do not show the city and country of an event. Expected is: Show city and country.

![Screenshot from 2019-05-20 10-46-46](https://user-images.githubusercontent.com/1583873/58008453-b93a7f80-7aec-11e9-8f22-ca844b4870f4.png)

**Comment by CosmicCoder96** [comment]
@mariobehling What about the street address? Should it still be there if city and country is shown?
