### ISSUE TITLE
Create UI for Teams Tab within Event Dashboard [UI-only]

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2968]
Parent #2960 

Design a UI for the teams Tab, without making any changes to the existing manage roles section.

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 can I take this up?

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi Will start working on it next week, app is still not stable enough for these refactors.

**Comment by mariobehling** [comment]
Closing this as UI changes are taken care of in other issues.
