### ISSUE TITLE
Front page: Show Most Used Event Cities in "Locations" Bottom Menu area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2970]
The locations menu is currently empty. Please show the most active event cities here automatically.

![Screenshot from 2019-05-20 12-39-37](https://user-images.githubusercontent.com/1583873/58015831-84cebf80-7afc-11e9-8f00-bb136b24741f.png)

**Comment by prateekj117** [comment]
@mariobehling On it.

**Comment by prateekj117** [comment]
@mariobehling @CosmicCoder96 So, after working on the server PR for some time, I realized that the 'location_name' column in events table is saving the whole address, while the 'searchable_location_name' is saving nothing. So, there is no way to return most-used-locations, and also no way to extract city-name from the address. Also, we need a new model on the server to solve this issue. I had a conversation with @iamareebjamal regarding this, and there is no solution for it as of now.

**Comment by CosmicCoder96** [comment]
> while the 'searchable_location_name' is saving nothing. So, there is no way to return most-used-locations

I don't understand what you mean by now way, if searchable location is not being populated then it needs to : #3150

**Comment by CosmicCoder96** [comment]
Event locations are fully implemented now, both on FE, Server.
