### ISSUE TITLE
Call for Speakers does not store text and dates correctly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2972]
Creating a call for speakers does not work properly. The text and the dates are not stored correctly. Trying several times will finally store the correct value, but it does not always work right away.

![Screenshot from 2019-05-20 14-44-32](https://user-images.githubusercontent.com/1583873/58022585-0da22700-7b0e-11e9-9947-d1119a2a477c.png)

**Comment by prateekj117** [comment]
@mariobehling On it.

**Comment by prateekj117** [comment]
@mariobehling I cannot replicate this error locally. It's saving the `start_at` and `ends_at` in UTC. And no error in storing the text as well. @uds5501 @mrsaicharan1 @shreyanshdwivedi Can you guys please check locally as well and let me know.

**Comment by shreyanshdwivedi** [comment]
@prateekj117 any update?

**Comment by prateekj117** [comment]
@CosmicCoder96 Was this also fixed after removing validations or not?

**Comment by shreyanshdwivedi** [comment]
@prateekj117 if you are willing to work on it, you can proceed.

**Comment by prateekj117** [comment]
@shreyanshdwivedi I already have taken some issues, so I would be working on then rn.

**Comment by uds5501** [comment]
@CosmicCoder96 I think this is working fine now.  Please take a look.

**Comment by kushthedude** [comment]
> @CosmicCoder96 I think this is working fine now. Please take a look.

@uds5501 
Happens due to the removed validations, As soon as we change the start time or date, the End date is reset automatically.
