### ISSUE TITLE
After adding Personal Details to Call for Speakers Pop up for Session Details does not show up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2973]
Users are left clueless what to do after they add their personal details in a call for speakers. Expected is, that the pop up opens with the info "Please add your session details".

At least the below pop up should open, but it does not.

![Screenshot from 2019-05-20 14-47-36](https://user-images.githubusercontent.com/1583873/58022818-94ef9a80-7b0e-11e9-9d2b-8d1029105020.png)

**Comment by uds5501** [comment]
@mariobehling will be taking this one!

**Comment by kushthedude** [comment]
@uds5501 May i take this one as you have some issues to work on ?

**Comment by uds5501** [comment]
@kushthedude Already started the work :sweat_smile:

**Comment by kushthedude** [comment]
Thats Great !!

**Comment by uds5501** [comment]
@CosmicCoder96 @mariobehling Suppose a user successfully enters the speaker details, what exactly do we want the behaviour to be after that?
Another modal popping up saying, 'please enter session details' and pointing to the submit proposal button?
