### ISSUE TITLE
Cannot change event cause of Ticket Sales End Message

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2974]
At times a ticket sales ends error message comes up, which sometimes suddenly disappears. In any case just leave it to the organizers when they want to sell a ticket (even if the event has ended). Get rid of the ticket sales end error, please.

![Screenshot from 2019-05-20 15-01-36](https://user-images.githubusercontent.com/1583873/58023498-375c4d80-7b10-11e9-979f-666434887229.png)

**Comment by uds5501** [comment]
@CosmicCoder96 Can we auto update the ticket sales-end date as we change the dates of events? or should we remove the checks entirely?

**Comment by CosmicCoder96** [comment]
@uds5501 Remove any and all checks from both FE + server for now.

**Comment by uds5501** [comment]
@CosmicCoder96 Alright, I will make it work!

**Comment by uds5501** [comment]
@CosmicCoder96 This can be closed now

**Comment by CosmicCoder96** [comment]
Fixed in https://github.com/fossasia/open-event-server/pull/5941
