### ISSUE TITLE
Notification Messages should be Paginated and Page should have "Mark All as Read" button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2976]
Notification Messages in the "All" tab are currently not paginated. This could result in superlong pages that crash the browser and system, if users have thousands of messages e.g. from ticket sales. Please implement paginated pages and a button "mark all as read".

![Screenshot from 2019-05-20 15-17-45](https://user-images.githubusercontent.com/1583873/58024608-dda95280-7b12-11e9-8e32-860886a1437c.png)

**Comment by CosmicCoder96** [comment]
@mariobehling Will an infinity loading style like facebook notifications do?

**Comment by kushthedude** [comment]
@CosmicCoder96 Can I implement Pagination ?
