### ISSUE TITLE
Wizard Step 3: Speakers Form Resort and Re-add fields

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2977]
Speakers form elements are resorted and some are missing. Please add them.

Please ensure the following form elements are available in this order

- Name *		
- Email *		
- Photo		
- Organisation		
- Position
- Address <-
- Country		
- City		
- Short biography		
- Long biography		
- Speaking experience		
- Sponsorship required		
- Gender		
- Where did you heard about our event?		
- Mobile		
- Website		
- Facebook		
- Twitter		
- Github		
- Linkedin
- Instagram <-

![Screenshot from 2019-05-20 15-48-09](https://user-images.githubusercontent.com/1583873/58026405-b3599400-7b16-11e9-8ec0-3af7fbec7989.png)

**Comment by uds5501** [comment]
@mariobehling While I work on #2978 I will take this one too!

**Comment by mariobehling** [comment]
Added a screenshot. Please see the details.

**Comment by CosmicCoder96** [comment]
@uds5501 @mariobehling Nothing to do codewise, it will already be sorted for new events generated using the new system, we can just manually edit database for the important events on old system.

**Comment by uds5501** [comment]
@CosmicCoder96 In that case please take care of it!

**Comment by CosmicCoder96** [comment]
@mariobehling @uds5501 Some of the missing fields were never created in the new system, so some of them from list don't exist. I will be taking this one as the approach would have to be legacy data compatible to tackle this. More discussion might be needed.
