### ISSUE TITLE
Wizard Step 3: Session Details not as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2978]
Please re-add speaker details and sort as follows in the speakers form:

- Title *		
- Subtitle		
- Short abstract		
- Long abstract		
- Comments		
- Track *		
- Session type		
- Level		
- Language		
- Slides		
- Video		
- Audio

![Screenshot from 2019-05-20 15-47-15](https://user-images.githubusercontent.com/1583873/58026428-c79d9100-7b16-11e9-8a6c-f676630e22d5.png)

**Comment by uds5501** [comment]
@mariobehling Taking this

**Comment by CosmicCoder96** [comment]
@uds5501 @mariobehling Nothing to do codewise, it will already be sorted for new events generated using the new system, we can just manually edit database for the important events on old system.
