### ISSUE TITLE
Cannot place order after refactor 

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#2994]
Received this:
{"errors": [{"status": 403, "source": {"pointer": ""}, "title": "Access Forbidden", "detail": "You cannot update a non-pending order"}], "jsonapi": {"version": "1.0"}}

@shreyanshdwivedi Fix this and test with free and paid orders both locally. Then test with orders of payment through check for both guest and non-guest accounts.

**Comment by shreyanshdwivedi** [comment]
On it
