### ISSUE TITLE
my-tickets: no tickets shown in upcoming open list

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#2995]
**Describe the bug**

Previously, we were using `placed` status for pending tickets but now we have changed it to `pending` status. This needs to be updated as follows - 
 - Completed and Placed tickets must be placed in the upcoming completed list
 - Pending tickets must be in the upcoming open list

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `My Tickets > Upcoming`
2. Click on `Open`
3. See error

**Expected behaviour**

Pending tickets should be shown in upcoming open list

![Screenshot_2019-05-24 Open Upcoming My Tickets Open Event](https://user-images.githubusercontent.com/25428397/58306654-cbccf580-7e19-11e9-9aa9-4c621c2f2459.png)

**Additional context**

Working on it

**Comment by CosmicCoder96** [comment]
Fixed in https://github.com/fossasia/open-event-frontend/pull/2998
