### ISSUE TITLE
Pending order page doesn't load properly

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#2997]
**Describe the bug**

The pending order page doesn't load properly.

**Expected behaviour**

It should load all the elements without any error

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/58309019-ac859680-7e20-11e9-8cd2-ecd06c09e8a1.png)

**Additional context**

On it with @mrsaicharan1

**Comment by uds5501** [comment]
@CosmicCoder96 suggested priority : Urgent

**Comment by CosmicCoder96** [comment]
Fixed in https://github.com/fossasia/open-event-frontend/pull/2998
