### ISSUE TITLE
Add a small button on the top which toggles left side rail on event description page.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#30]
The left side rail on the event description page hides from the screen and is not visible in case of mobile screens( < 768px ).

Current behaviour : 
![mobile](https://cloud.githubusercontent.com/assets/17925669/25833843/dc232630-3491-11e7-810a-59eaa1ad0906.png)

Expected behaviour : 
![mobile4](https://cloud.githubusercontent.com/assets/17925669/25834147/90ffeaec-3493-11e7-827a-addf91a9896b.png)

Above picture shows the sample thing we want to do. Add a small button at the page wherever suitable which acts as a dropdown to the menu on the event description page.

**Comment by niranjan94** [comment]
Don't keep this on the navbar. Keep it just below the event image. 
Provide a screenshot here to see how it looks and we can discuss on it further.

**Comment by CosmicCoder96** [comment]
@niranjan94 
Few things I wanted to ask:

- The CSS changes (media queries) I write will be specific to this page. Yes/no
- The basic approach being, at a particular width, hide the `rail` and make a `button` appear below the event image clicking on which the `rail` appears as a sort of pop up. If not, please suggest the best approach. Thank you.

**Comment by CosmicCoder96** [comment]
@niranjan94 
This is a _very_ rough draft of what I am trying to do. Using mobile hidden for the left rail and mobile only for the small icon button with the button generating a modal. Please share your views. Thank you.
![image](https://cloud.githubusercontent.com/assets/17252805/26009953/a80e4788-3768-11e7-94a0-a49f15b67189.png)

![image](https://cloud.githubusercontent.com/assets/17252805/26009969/b5e74e7c-3768-11e7-9f66-118b5b8d9038.png)

**Comment by niranjan94** [comment]
@CosmicCoder96 . Mmm... Actually ... let's do something else first. 
These rails seem to be doing more good than bad. 

So, lets start by 
- Removing `ui container` from `public-event` div (thereby making it full width)
- And making the `#public-event-content` div as a simple, very normal 3 column grid stackable grid.
- Now, in mobile the side menu would automatically get stacked on top of the content. All you have to do is, hide it and use a button to show it.

Makes sense ?

**Comment by CosmicCoder96** [comment]
@niranjan94 I made those changes, the grid disappeared for some reason. I will try to work it out that way, thanks

**Comment by CosmicCoder96** [comment]
![giphy](https://cloud.githubusercontent.com/assets/17252805/26023693/a83cc384-37df-11e7-856f-b2de25bd704a.gif)
proposed UI mockup @niranjan94
