### ISSUE TITLE
Tax is not shown on the pending page

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3008]
**Describe the bug**
Whenever we try to place an order pertaining to a certain event which has tax associated with it, the tax is not being shown on the pending page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any event with tax
2. Click on 'Order now'
3. See Error

**Expected behaviour**
The correct amount must be shown.
**Screenshots**
<img width="1242" alt="Screenshot 2019-05-24 at 5 38 12 PM" src="https://user-images.githubusercontent.com/25197147/58359841-11ee7d00-7e4b-11e9-819b-ed3ec0034fe0.png">

**Additional context**
Working on this.

**Comment by kushthedude** [comment]
@mrsaicharan1 This follow the `International Guidelines` if you amount gets a decimal place less than 0.5 , It will rounded to the the corresponding number and in case of greater than 0.5 it will get rounded to next integer , 
See this i have made `Tax = 2.5 % `
<img width="900" alt="Screenshot 2019-05-25 at 5 31 17 AM" src="https://user-images.githubusercontent.com/44091822/58361792-b1912700-7eae-11e9-8d61-90bc33e84545.png">
