### ISSUE TITLE
Transfer the ownership of your events to another organizer.

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3012]
We are implementing feature to provide ability to a user to delete his/her account. If the user is associated with any event, he/she must be given choice to transfer the events to other organizers associated with the event. (Just like in GitHub)

![github](https://user-images.githubusercontent.com/25428397/58374541-ad701280-7f5d-11e9-82fd-33afed63c980.png)

**Additional context**
Server issue: https://github.com/fossasia/open-event-server/issues/5890

**Comment by kushthedude** [comment]
@shreyanshdwivedi Can i take this ?

**Comment by shreyanshdwivedi** [comment]
I'm working on it @kushthedude 
Will be pushing the PR soon

**Comment by mariobehling** [comment]
Please change the role of the event creator (organizer) to "event owner" to make the roles in the system clearer as well.

**Comment by shreyanshdwivedi** [comment]
@mariobehling I'll add a role as `event_owner` on server and make it the default role of user creating event

**Comment by prateekj117** [comment]
@shreyanshdwivedi May I work on adding the new role `event_owner` and changing the default role to be `event_owner`.

**Comment by shreyanshdwivedi** [comment]
@prateekj117 actually I have already started working on it. Will be opening a PR soon
