### ISSUE TITLE
Call for Speakers page Error

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3016]
**Describe the bug**
The cfs event has an error when its trying to be accessed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any event with Call for Speakers.
2. Click on **Call for Speakers.**
3. See error

**Expected behaviour**
The CFS page must open as usual

**Error log**

`Error while processing route: public.cfs.index – "undefined is not an object (evaluating 'transition.params['public.cfs']')" (1)
`
`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'transition.params['public.cfs']')`

**Desktop (please complete the following information):**
 - MacOS
 - Browser [Safari]

**Additional context**
Working on this.

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 @niranjan94 What are we using     
`let hash = transition.params['public.cfs'].speaker_call_hash` for in CFS?

In `app/routes/public/cfs/index.js`

**Comment by kushthedude** [comment]
@mrsaicharan1 Are you on it ?

**Comment by mrsaicharan1** [comment]
Yup.

**Comment by kushthedude** [comment]
Cool , Go on :)

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi @uds5501  What are we using     
`let hash = transition.params['public.cfs'].speaker_call_hash` for in CFS?

**Comment by mrsaicharan1** [comment]
@CosmicCoder96    ` const hash = transition.params['public.cfs'].speaker_call_hash;`
Can you tell me what the hash is used for?
