### ISSUE TITLE
Switch from ember-model-tables to Ember tables

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#3018]
Ember-model-tables are quite rigid, as even the querying is handled by them. We have over customised and tweaked them to make sorting, and searching work. The future updates may or may not be compatible with our custom changes. Also as the app grows we need more flexibility while querying the API.

Reference:
https://opensource.addepar.com/ember-table/latest/docs/

The reactor will be one table at a time and will open sub-issues for each of them to retain stability within the app.

**Comment by onechiporenko** [comment]
Hi, @CosmicCoder96. I glad that you have used `ember-models-table` and I'm interesting which  difficulties you get while working with it. It's sad that you are going to switch table-component and I want to understand what was going wrong and improve `models-table` to make it better/user friendly/easy to use etc. Anyway good luck to you with your awesome project!

**Comment by iamareebjamal** [comment]
Completed in https://github.com/fossasia/open-event-frontend/pull/5379
