### ISSUE TITLE
Create modal for add role in events overview

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#302]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/27362495-65b64e96-564c-11e7-93b1-a5558650c7d1.png)

**Comment by CosmicCoder96** [comment]
@niranjan94 This will be implemented similar to the taxModal, without bubbling up the actions because it has form validation? Please let me know

**Comment by niranjan94** [comment]
Even with validation, you can bubble things up. Form submit action won't actually fire unless validation passes right. If used correctly, `if (this.$('.ui.form').form('is valid')) {` is not needed and actions can be bubbled up

**Comment by CosmicCoder96** [comment]
@niranjan94 On modals, we are not using the form submit button to submit form data, 
rather the buttons outside the form tag, hence `if (this.$('.ui.form').form('is valid')) {` was used, so what would be the right approach?
