### ISSUE TITLE
Failing Build of Development Branch

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3022]
After the integration of `Live Reload ` in the app according to PR #3007 , Some test are failing . 
<img width="1000" alt="Screenshot 2019-05-28 at 7 50 30 AM" src="https://user-images.githubusercontent.com/44091822/58446239-9b3cd280-811d-11e9-9323-2bfcaec58b55.png">

**Comment by CosmicCoder96** [comment]
it hasn't really been affected by livereload, other PRs are also randomly failing. @niranjan94 Can you help with this? I am not sure what's causing random TimeOuts on acceptance tests which requires login.

**Comment by kushthedude** [comment]
Sure

**Comment by kushthedude** [comment]
@CosmicCoder96 I checked it out , Its very random, Two of my PR's were failing `Travis due to acceptance test which required login` , but as soon as I rebased them `Travis Build Passed` , 
Similarly in our `Development Branch` yesterday after you merged PR related to `Live reload` the build failed and after a new commit today `Build is Passing`

**Comment by niranjan94** [comment]
@CosmicCoder96 will take a look at this locally later tonight (IST)

**Comment by mrsaicharan1** [comment]
What was the reason for this?

**Comment by kushthedude** [comment]
@mrsaicharan1 TBH , Still not known ,Failing was 'random' but the issue could be with `Assert(login)` as all the failing test cases were related to with `Login`

**Comment by kushthedude** [comment]
@niranjan94 I did gather some SS of random build failures in PR's
### 1-:

<img width="1440" alt="Screenshot 2019-06-05 at 5 10 31 PM" src="https://user-images.githubusercontent.com/44091822/59079132-db5f3a80-88ff-11e9-99da-7556713e12aa.png">

### 2 -:
<img width="1440" alt="Screenshot 2019-06-07 at 8 41 23 AM" src="https://user-images.githubusercontent.com/44091822/59079187-182b3180-8900-11e9-829d-1c4ebe7875cf.png">

### 3 -:
```
not ok 1124 Chrome 74.0 - [4647 ms] - Acceptance | login: logout at /logout
    ---
        actual: >
            /login
        expected: >
            /
        stack: >
                at Object._callee4$ (http://localhost:7357/assets/tests.js:774:24)
                at tryCatch (http://localhost:7357/assets/vendor.js:10750:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:10984:22)
                at Generator.prototype.<computed> [as next] (http://localhost:7357/assets/vendor.js:10802:21)
                at asyncGeneratorStep (http://localhost:7357/assets/tests.js:668:105)
                at _next (http://localhost:7357/assets/tests.js:670:196)
        negative: >
            false
```
