### ISSUE TITLE
Event Scheduler not working

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#3025]
**Describe the bug**

On putting any session on the table, their is a network error, apparently due to session id not being captured

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Scheduler'
2. Put any session on the scheduler
3. See error

**Expected behaviour**

This error shouldn't occur

**Screenshots**

![image](https://user-images.githubusercontent.com/21087061/58452085-af8bca00-8133-11e9-905a-b1625e02208e.png)

**Additional context**

Looking into it

**Comment by niranjan94** [comment]
@uds5501 always add the stacktrace as plaintext with all bug reports. If it a network request, also add information on the payload that was sent to the server and the response. (from the browser's dev tools)

**Comment by uds5501** [comment]
This is the stack trace :
![Screenshot from 2019-05-28 10-50-51](https://user-images.githubusercontent.com/21087061/58452867-95072000-8136-11e9-89f6-754ac524cd49.png)
Apparently the errors is that we aren't able to capture the session Id properly

**Comment by CosmicCoder96** [comment]
@uds5501 Check what changed in the scheduler in the refactor upgrade, this
was working before.

**Comment by uds5501** [comment]
@CosmicCoder96 I restored it to the version before the refactor. Apparently, the error existed there too. The changes which took place where only using ES5 getters.

**Comment by uds5501** [comment]
Update: The problem lies in `this.updateSession(start, end, resourceId, $(ui.helper).data('serverId'));` in the drop action. `$(ui.helper).data('serverId')` isn't fetching anything.

@niranjan94 @CosmicCoder96

**Comment by kushthedude** [comment]
@uds5501 AFAIK i did highlight the type error on the server channel , but during that time, i dont know why did we ignore it?

**Comment by uds5501** [comment]
@kushthedude
point 1 - Server Channel. It's clearly a frontend issue.
point 2 - Too many issues at a time and not reported on github itself (AFAIK)
point 3 - Triage would be way more helpful right now :)

**Comment by CosmicCoder96** [comment]
@uds5501 I was able to fix this, but it's not the ideal solution -- more of a workaround. Using global Jquery selectors insteadd of importing it fixes this. After dependency upgrades, something about the way Jquery is injected in the app has changed. Not sure which one caused this yet, but working on it.

Reference: https://github.com/emberjs/ember-jquery/issues/8
