### ISSUE TITLE
Existing users are required to confirm account again and receive error page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3026]
Existing users and admins are required to confirm their account again.

![Screenshot from 2019-05-28 09-49-58](https://user-images.githubusercontent.com/1583873/58460555-3342b800-812e-11e9-819b-4175fa81bbd2.png)

When user receives a confirmation link and clicks on it s/he receives an error page.

![Screenshot from 2019-05-28 09-38-15](https://user-images.githubusercontent.com/1583873/58460546-2cb44080-812e-11e9-95eb-ee96ae845a2f.png)

**Comment by uds5501** [comment]
@CosmicCoder96 This is happening to me at the local level too.

The verification link is supposed to be of this format, if I am correct, `http://localhost:4200/verify?token=WyJhYmNAYWJjLmNvbSIsICJDM0I3MkEiXS5aTHBmVXJObTFuUzU3Tzk0V2RqWmZVMnIwamM%3D`

but it's showing the same error link

**Comment by uds5501** [comment]
@CosmicCoder96 Pushing the solution for the verification page error. I can't recreate this recurring verification request though

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 Is this happening on production?I can confirm that it works locally
