### ISSUE TITLE
Mark Ticket as "Checked In" on my ticket page ones it is checked in

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3027]
There is no way to see if a ticket is checked in or not. Please show tickets as status "Checked In" on the my ticket page: https://eventyay.com/my-tickets/

![Screenshot from 2019-05-28 11-48-31](https://user-images.githubusercontent.com/1583873/58469164-4611b880-813f-11e9-9eee-1441bb6bbcef.png)

**Comment by uds5501** [comment]
@mariobehling will take a look

**Comment by uds5501** [comment]
@mariobehling shall I have a look?

**Comment by shreyanshdwivedi** [comment]
Will work on it
