### ISSUE TITLE
Cannot Edit Event "Object Not Found" error message on wizard step 1

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3033]
On the event wizard step 1 I receive an error "Object Not Found". Even if I don't change anything I am not able to edit the event.

![Screenshot from 2019-05-29 08-16-38](https://user-images.githubusercontent.com/1583873/58534273-17e9b280-81eb-11e9-864d-359c623a9de3.png)

**Comment by CosmicCoder96** [comment]
Resolved in #3034
