### ISSUE TITLE
Sessions not listed under Speaker on Public Page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3043]
**Describe the bug**

`Session` of the Speaker are not getting listed under `Its Heading` on `Public Pages`

**To Reproduce**

Steps to reproduce the behaviour:

- Create an `Speaker and Session` 
- Check on `Event Public Page` under `Speaker Sub-Heading`
- See Error

**Expected behaviour**

Proper Listing should be their

**Screenshots**

<img width="1264" alt="Screenshot 2019-05-31 at 10 17 32 AM" src="https://user-images.githubusercontent.com/44091822/58682216-5323e700-838d-11e9-90b2-c95ce5b669df.png">

**Additional context**

On It

**Comment by shreyanshdwivedi** [comment]
@kushthedude any update on this?

**Comment by kushthedude** [comment]
Will push the commits , as it is occuring in some case , so i need to check for some more use case

**Comment by kushthedude** [comment]
@shreyanshdwivedi I made the changes on my local , But the issue is the `Details Column` sometimes open and sometimes not,Can you confirm me this please ?

**Comment by uds5501** [comment]
@kushthedude only confirmed or accepted speakers will be listed. Can you confirm that it is happening in these cases or not after the schedule has been published for the event

**Comment by kushthedude** [comment]
> @kushthedude only confirmed or accepted speakers will be listed. Can you confirm that it is happening in these cases or not after the schedule has been published for the event

Checked that , All sessions were confirmed and schedule was published

**Comment by kushthedude** [comment]
@uds5501 Actually before this we need to solve the issue in speaker tab #3075 , Session Listing is no good if the accordion is not opening for any of the speakers
