### ISSUE TITLE
Events: events/list & events/view render the same view

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#305]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behaviour**
Currently the events/view & events/list render the same view, i.e events/list. This is happening due to the using multiple dynamic routing.
```
this.route('events', function() {
  this.route('view', { path: '/:event_id' }, function() {
    ...
  }
  this.route('list', { path: '/:event_state' });
  }
```

**Steps to reproduce**
- Open https://open-event-frontend.herokuapp.com/events/live & https://open-event-frontend.herokuapp.com/events/963d3ba5

Both the routes load the same template.

@niranjan94 Please guide

**Comment by niranjan94** [comment]
This is completely expected. The template will be shared. but once we start pulling in data from the server, the data returned by the model will change.

**Comment by niranjan94** [comment]
Yes. This. I faced a similar problem in another project. lemme first see if that fix could work here too.

**Comment by niranjan94** [comment]
@geekyd works beautifully :) 

```js
  beforeModel(transition) {
    const eventState = transition.params[transition.targetName].event_state;
    if (!['live', 'draft', 'past'].includes(eventState)) {
      this.replaceWith('events.view', eventState);
    }
  },
```

In `routes/events/list.js` solves it.

**Comment by niranjan94** [comment]
But for this to work, `this.route('list', { path: '/:event_state' });` should be after the `events.view` definition in `router.js`. That's how ember router resolves routes.

**Comment by geekyd** [comment]
Okay I will test this locally & send a PR for this. Thanks :)
