### ISSUE TITLE
Links to privacy policy and terms page is not working

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3051]
**Describe the bug**
Please add a privacy policy and terms&conditons pages. Currently, the URL: https://eventyay.com/privacy-policy/ and https://eventyay.com/terms/ is redirecting to a Error 404 page

**Additional context**
Based on the mobile meeting discussion yesterday: https://docs.google.com/document/d/169tq2sr7lF_RnWnXA7hGVEIhQsrHT9tQjB32hHdlUL8/edit

**Comment by shreyanshdwivedi** [comment]
@anhanh11001 do you have any policy/terms and condition draft currently?

**Comment by anhanh11001** [comment]
I don't. @mariobehling do we have the drafts before?

**Comment by kushthedude** [comment]
@shreyanshdwivedi Do we need them ? I have the ss of legacy pages , Can implement them

**Comment by kushthedude** [comment]
@CosmicCoder96 @mariobehling Can static pages be fine for now ? As i created for `Cookie Policy` ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude if it is discussed in the meeting, I think it is intended to be implemented. And static pages should be fine in this case

**Comment by kushthedude** [comment]
@anhanh11001 Do we need page for `Cookie Policy` too ?

**Comment by anhanh11001** [comment]
For the frontend, I don't know. But for the mobile apps, it is not needed because I think cookie is only for the web. The problems were that these redirect to no where, and it could risk the app from being uninstalled in the play store, that what I heard

<img src="https://i.ibb.co/F8zjRF7/61645483-1124715231063224-12504548174200832-n.jpg" width="300">           <img src="https://i.ibb.co/QpZ5mT8/61704242-2339466773001358-974399350702604288-n.jpg" width="300">

**Comment by kushthedude** [comment]
@shreyanshdwivedi @anhanh11001 Taking this on PRIORITY ,

**Comment by kushthedude** [comment]
@anhanh11001 Refer to #3054 , And it may be closed

**Comment by anhanh11001** [comment]
@kushthedude but #3054 is also closed and I'm not sure if the problem is fixed now

**Comment by kushthedude** [comment]
@anhanh11001 Actually the following can be added whenever the admin wants by going to `Admin/Pages` in the WebApp

**Comment by anhanh11001** [comment]
So by admin you means Mario or someone?

**Comment by kushthedude** [comment]
Yes

**Comment by anhanh11001** [comment]
@mariobehling sir please take a look. So the admin can add the privacy/terms page by themselves. So can you get anyone in the admin team to do it?

**Comment by anhanh11001** [comment]
@mariobehling Here is the issue I mentioned, it was closed but it wasn't fixed. I think you (the admin or someone with authorities) can add the privacy/terms pages

**Comment by kushthedude** [comment]
@iamareebjamal Do we need to reopen the PR too ?

**Comment by iamareebjamal** [comment]
@CosmicCoder96 Please complete this on eventyay.com

**Comment by kushthedude** [comment]
Added on the `eventyay.com` 
![image](https://user-images.githubusercontent.com/44091822/60005044-64f66280-968b-11e9-895f-6893c3d3d818.png)

**Comment by iamareebjamal** [comment]
@kushthedude It's blank and URL contains capital letters

**Comment by kushthedude** [comment]
I didn’t check them , sorry for ignorance

**Comment by CosmicCoder96** [comment]
[https://eventyay.com/privacy-policy](https://eventyay.com/privacy-policy)
[https://eventyay.com/terms](https://eventyay.com/terms)

Both seem to be working, remove the links @anhanh11001 added have a trailing slash on them which is not required. It may be closed.

**Comment by iamareebjamal** [comment]
Weren't working when I checked. However, why a trailing slash breaks the URL? Please open an issue to fix that

**Comment by iamareebjamal** [comment]
Also, the title of the pages is always `Pages`, bad for SEO. Please open an issue to fix that as well
