### ISSUE TITLE
Map is not working in some event

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3052]
**Describe the bug**
In some events, map displayed in the main page doesn't show any particular location. Example attached below

**Screenshots**
<a href="https://ibb.co/dmN8cvf"><img src="https://i.ibb.co/CPjRtyw/fadsf.png" alt="fadsf" border="0"></a>

**Comment by shreyanshdwivedi** [comment]
@anhanh11001 maybe the location is mentioned by user manually and google map doesn't find such location. Can you check if such location exists?

**Comment by anhanh11001** [comment]
@shreyanshdwivedi I'll check it again, but initially, the location "Enschede, Netherlands" do exist

**Comment by anhanh11001** [comment]
Ex: https://eventyay.com/e/5f6d3feb this is not working as well, and it shows a gray screen. I'm not sure if this is because of Google Map API or our implementation

**Comment by kushthedude** [comment]
@anhanh11001 AFAIK, The following is `neither the API error now implementation` , Case could be this when the `Organizer` entered the location , Without the map rendering the location he clicked `Publish` , If you are the owner please try once again

**Comment by anhanh11001** [comment]
Yes, that's probably the case, when I edit the event and let the image render, it shows the image properly now.

**Comment by anhanh11001** [comment]
So I will still open this issue as this is still somewhat a problem if anyone has idea to improve this. Otherwise, let me know and I'll close this issue

**Comment by kushthedude** [comment]
@anhanh11001 Actually the scene is due to connection speed or whatever, until the image loads on map , The location coordinates are not setted properly on ` Ember-G-Map API`  we are using , So it may sometimes cause the bug .  Please reopen if you face anymore issue . Thanks
