### ISSUE TITLE
Ability to provide donation ticket

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3057]
Describe the feature
Related server issue https://github.com/fossasia/open-event-server/issues/5991

Our system requires the option of adding a donation ticket which users can purchase for a specific event.

Additional context
Working on it.

**Comment by mariobehling** [comment]
> Our system requires the option of adding NGO events. When an event is categorised as an NGO event, it should have the feature of selling only free tickets.

No, this is not correct. And this is not a requirement.

The only requirement is "donation ticket". Please also stop using "NGO" events. This term is misleading.

**Comment by mariobehling** [comment]
Also, we don't know what is your exact idea. The way you formulate it, is unclear. Keep things simple. We only need an option donation tickets.
