### ISSUE TITLE
Speaker Image not visible on Session Public Page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3061]
**Describe the bug**

Speaker Image not visible on Session Public Page

**To Reproduce**

Steps to reproduce the behaviour:

- Add a speaker image with a session associated with it.
- Go to `Event Public Page` and check the `Image` under `Sessions Tab`

**Expected behaviour**

Show `Speaker Image` .

**Screenshots**

<img width="1440" alt="Screenshot 2019-06-04 at 2 14 47 PM" src="https://user-images.githubusercontent.com/44091822/58865988-33662900-86d5-11e9-883f-0ec49b187a7c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 23.0.3

**Additional context**

On It

**Comment by Anupam-dagar** [comment]
I would like to take this up as the issue creator currently has 2 other issues assigned.

**Comment by kushthedude** [comment]
Feel free to work upon @Anupam-dagar
