### ISSUE TITLE
Events Dashboard: Clicking on Past, Draft Tab etc. not working as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3064]
Clicking on the tabs e.g. Past only results in a delayed action and it is very slow.

![Screenshot from 2019-06-04 15-27-45](https://user-images.githubusercontent.com/1583873/58882867-93f96400-86dd-11e9-9edc-e5845b84e05f.png)

**Comment by kushthedude** [comment]
@CosmicCoder96 I think its related to the #2726 , As we had the discussion regarding the loader appearance during switching of tabs

**Comment by CosmicCoder96** [comment]
To be tackled with #3018

**Comment by CosmicCoder96** [comment]
Resolved in #3018
