### ISSUE TITLE
Time-Zone error in Sessions tab of eventyay

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3071]
Time Stored in Submission Date for Eventyay is not storing correct time according to the setted time-zone , On the other hand `Last Modified` is storing data correctly . 

#### Screenshot :
<img width="1440" alt="Screenshot 2019-06-05 at 12 22 43 PM" src="https://user-images.githubusercontent.com/44091822/58936291-06754d00-878d-11e9-8727-f4e92a1787ac.png">

**Comment by kushthedude** [comment]
@Anupam-dagar Interested in it ?

**Comment by Anupam-dagar** [comment]
@kushthedude sure I would like to take this up. Thanks :D
