### ISSUE TITLE
Attendee Checkin/Checkout returns 422

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3082]
**Describe the bug**

Attendee Checkin/Checkout returns 422

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to `Tickets/Attendee`
2. Click on `Checkin/Checkout` more than once
3. See error

**Expected behaviour**

Proper Message should be displayed

**Screenshots**

<img width="1440" alt="Screenshot 2019-06-07 at 3 55 40 PM" src="https://user-images.githubusercontent.com/44091822/59098016-bb01a100-893c-11e9-81c5-fda8b6625077.png">

**Desktop (please complete the following information):**

 - OS: MacOS/Ubuntu
 - Browser Chrome
 - Version 73.0.4

**Additional context**

Needs more info

**Comment by kushthedude** [comment]
@shreyanshdwivedi @uds5501 Is it reproducible ?

**Comment by uds5501** [comment]
@kushthedude it's working fine on my local system.

**Comment by kushthedude** [comment]
@uds5501 Actually tried , On both Mac and Ubuntu and was reproducible to both , I will still check once more

**Comment by prateekj117** [comment]
@kushthedude working fine in my local as well.

**Comment by Anupam-dagar** [comment]
I am able to reproduce it, the issue can be elaborated as the user can be checked in or checkout out, but the page need a refresh to do it in subsequent turns. Attaching a GIF for the same.

**Comment by kushthedude** [comment]
@Anupam-dagar Facing same on my local !

**Comment by kushthedude** [comment]
@Anupam-dagar Would you like to take it ?

**Comment by Anupam-dagar** [comment]
@kushthedude yes, I'll take this up.
