### ISSUE TITLE
Most "Past Sessions" are missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3084]
Past sessions are missing: https://eventyay.com/my-sessions/past

![Screenshot from 2019-06-07 16-09-26](https://user-images.githubusercontent.com/1583873/59110154-bfc75480-893e-11e9-87d7-fa664cb79749.png)

**Comment by Anupam-dagar** [comment]
I would like to take this up.

**Comment by kushthedude** [comment]
I would like to fix the following
