### ISSUE TITLE
Better Implementation of Mobile Apps Pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3086]
Please make an enhanced version of the mobile apps pages. Compare below.

Attendee App

- Eventyay: https://eventyay.com/attendee-app
- Eventbrite: https://www.eventbrite.com/eventbriteapp/

Organizer App
- Eventyay: https://eventyay.com/organizer-app
- Eventbrite: https://www.eventbrite.com/l/Organizer-check-in-app/

**Comment by NamanZelawat** [comment]
I would like to work on this issue.

**Comment by snitin315** [comment]
I would like to work on this issue.

**Comment by mariobehling** [comment]
Already resolved as part of another issue.
