### ISSUE TITLE
Adding the option of invoice monitoring & payment reminders (Admin)

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3095]
**Describe the feature**
**Parent issue**
Related server issue https://github.com/fossasia/open-event-server/issues/6021
The FE requires an option in the admin dashboard to customise emails for payment reminders, frequency of payment reminders and related features.

Reference:
https://www.eventbrite.com/support/articles/en_US/Troubleshooting/understanding-eventbrite-fee-invoices?lg=en_US

Workflow:
The implementation will follow that of Eventbrite's.
1. Invoices are due 30 days from the date they're issued[Default set to the first of the month]
2. Initially, the frequency of reminders will be constant. Variable frequencies can be implemented in following PRs.
3. Fees are decided by admin users[Ticket fees already implemented]
4. If invoice is not paid, account gets suspended

**Additional Info**
Working on it.

<img width="955" alt="Screenshot 2019-06-11 at 11 20 30 AM" src="https://user-images.githubusercontent.com/25197147/59289270-3fa13780-8c3b-11e9-902b-37089dc4f3ff.png">

**Comment by mariobehling** [comment]
Closing in favor of https://github.com/fossasia/open-event-frontend/issues/4954
