### ISSUE TITLE
Fix and improve event filters / browse events search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3098]
The page https://eventyay.com/explore offers different ways to search for events. Please simplify the search options as follows:
* Add options show "All Categories" and "All Event Types"
* provide a tick box for filters
* move date filters to first position
* add filter option for Call for Speakers "Open", "Closed" and "Not Available"
* add filter option "Free" or "Paid"

![Screenshot from 2019-06-10 15-20-13](https://user-images.githubusercontent.com/1583873/59199211-b4219b00-8b95-11e9-848a-bedaec54a332.png)

**Comment by kushthedude** [comment]
On it

**Comment by kushthedude** [comment]
@mariobehling Can you please clarify the following, If we need a tickbox to `Show or Hide Filter Section` or the way we are selecting filters

> provide a tick box for filters

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 All parts of this issue has been completed and merged. This issue can be closed now.
