### ISSUE TITLE
Call for Speakers Section direct Event Links to "Call for Speakers" page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3099]
On the front page in the call for speakers section please direct the listed events in that section directly to the "Call for Speakers" page of the event.

![Screenshot from 2019-06-10 16-00-42](https://user-images.githubusercontent.com/1583873/59200739-2d6ebd00-8b99-11e9-9daf-f50e62f03b0d.png)

**Comment by shreyanshdwivedi** [comment]
I'll work on this
