### ISSUE TITLE
Add twitter URL Trimming , Which is going 422 in CFS

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3106]
Currently, when you enter a `Twitter URL` of your profile in CFS, The system expects pattern with `Complete HTTPS Protocol` which makes it throw `422` , Enable trimming in `Twitter URL` so that it's comfortable to use.

**Comment by Anupam-dagar** [comment]
I'll take this up.

**Comment by kushthedude** [comment]
@Anupam-dagar Already did changes pushing in a minute
