### ISSUE TITLE
Admin Area: Add Test Email Settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3108]
We need to be able to test the email settings. Please add an option to send a test email into the admin section in https://eventyay.com/admin/settings.

Create a test email in the system that will get send out.

![Screenshot from 2019-06-11 09-14-33](https://user-images.githubusercontent.com/1583873/59251155-68203600-8c29-11e9-9730-e5616e902fbf.png)

**Comment by prateekj117** [comment]
@mariobehling On it.

**Comment by kushthedude** [comment]
@prateekj117 I think @CosmicCoder96 assigned himself on it
