### ISSUE TITLE
Event Dashboard: Filter Options not working under `tickets/orders`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3110]
#### Description:- 
`Filter Options` given under `Tickets/Orders` are just dummy buttons without any action associated with them.
Fix the following by defining `Filter Options`

#### Screenshot :- 
![image](https://user-images.githubusercontent.com/44091822/59266675-d1259f00-8c65-11e9-8dc0-661b62570c1c.png)

**Comment by CosmicCoder96** [comment]
Fixed with orders table refactor
