### ISSUE TITLE
Front Page: Featured Event not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3113]
Adding OpenTechSummit China as a featured event does not make the event show up on the front page.

![Screenshot from 2019-06-11 21-59-54](https://user-images.githubusercontent.com/1583873/59302514-6b9cd700-8c94-11e9-82fb-ba37ed5963cf.png)

![Screenshot from 2019-06-11 22-01-27](https://user-images.githubusercontent.com/1583873/59302557-81120100-8c94-11e9-96d2-54c671113d75.png)

**Comment by shreyanshdwivedi** [comment]
Will take a look

**Comment by shreyanshdwivedi** [comment]
I'm unable to reproduce it on my local. 
@uds5501 @mrsaicharan1 @kushthedude can you guys please confirm?

**Comment by uds5501** [comment]
@shreyanshdwivedi Is it a pagination error?

**Comment by kushthedude** [comment]
> @shreyanshdwivedi Is it a pagination error?

 Can't be , And not only `Featured` ,I cant see Open Event China on `Upcoming Events` too , I think bymistake it has been made private

**Comment by shreyanshdwivedi** [comment]
I tried it with more than 10 events on local. It worked well
However will check there is any limit in no. of featured events

**Comment by uds5501** [comment]
> > @shreyanshdwivedi Is it a pagination error?
> 
> Can't be , And not only `Featured` ,I cant see Open Event China on `Upcoming Events` too , I think bymistake it has been made private

This seems to be most probable reason @mariobehling

**Comment by uds5501** [comment]
@mariobehling @CosmicCoder96 This issue can be closed if it's confirmed that OpenTechSummit China is a privately listed event, that's the only reason why it might not be showing up on the index page.
Otherwise, one can always find them listed on `explore` tab, on which, it is listed.
