### ISSUE TITLE
Move Profile info the menu "Settings" as the first tab and merge it with "contact info"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3114]
Profile is currently its own page/area. This is not necessary. Please
* Move it into the settings area. 
* Merge it with contact info
* Add it as the first tab user the tab name "User Details"

Compare: https://eventyay.com/settings/contact-info and https://eventyay.com/profile

Additionally change "Email-Preferences" to "Email Preferences" in the menu.

![Screenshot from 2019-06-11 22-30-49](https://user-images.githubusercontent.com/1583873/59304527-bb7d9d00-8c98-11e9-93f6-901743bc7135.png)

**Comment by mrsaicharan1** [comment]
I'd like to take this.

**Comment by mrsaicharan1** [comment]
Will be dividing this into two PRs! Would be easier that way :)
1. Moving profile from its own page area to settings module
2. Merging Contact info with profile
