### ISSUE TITLE
Wizard Step 1: Company data should be possible to be added without ticking "Send Tax Invoice"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3115]
The tax invoice data of a registered company can only be added if the field "Send Tax Invoice.." is ticked. Expected: It should be possible to enter the data even if the field is not ticked.

![Screenshot from 2019-06-11 22-41-02](https://user-images.githubusercontent.com/1583873/59305336-5aef5f80-8c9a-11e9-88c2-f68b72f968ca.png)

**Comment by shreyanshdwivedi** [comment]
On it

**Comment by mariobehling** [comment]
PR has been reverted. Please provide a new solution.

**Comment by shreyanshdwivedi** [comment]
@mariobehling the PR isn't reverted. Instead the PR opened by @kushthedude  reverting my PR was closed.

**Comment by prateekj117** [comment]
I guess this issue is solved. We should close this one.
