### ISSUE TITLE
Rename "Settings" to "Account"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3119]
Please rename "Settings" to "Account" in the settings tab and the drop-down menu.

Reason: We are storing more info than just "settings" in that area. Therefore "Account" is a more appropriate name.

**Comment by prateekj117** [comment]
On it.

**Comment by uds5501** [comment]
@prateekj117 Let me take this one while you are working on #3117. Thanks

**Comment by prateekj117** [comment]
@uds5501 Let's keep this issue open for newbies.

**Comment by uds5501** [comment]
@prateekj117 not really, it's in milestone 3 so I'll get it done :sweat_smile:
