### ISSUE TITLE
Admin: Add "Billing" Subtab in Admin Settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3126]
Invoices for events (not for ticket buyers!) need to have an Invoice Address of the Eventyay Platform provider (FOSSASIA). We can keep this information in the settings under the subtab "Billing". Please:
1. Add the subtab billing next to the tab "ticket fees" (https://eventyay.com/admin/settings/ticket-fees)
2. Create a heading "Invoice Handling" and provide fields for:
  * Invoice sent out - Dropdown - : First Day of Month, Second Day of Month, Third Day of Month
  * Timezone for sent outs: [Timezone here]
  * Invoice Format [Format Options here] (please resarch how to do it)
3. Create a heading "Invoice Contact" and provide fields for: 
  * Logo (enable image upload here), 
  * Contact Name, 
  * Phone, 
  * Email*, 
  * Country*, 
  * Tax ID, 
  * Registered Entity or Company,
  * Business Address*, 
  * City*, 
  * ZIP Code*, 
  * Additional Info, 
  * Comments

![Screenshot from 2019-06-12 10-46-57](https://user-images.githubusercontent.com/1583873/59337740-73df2b80-8d01-11e9-9f91-272404a5afc1.png)

**Comment by shreyanshdwivedi** [comment]
On it

**Comment by kushthedude** [comment]
@shreyanshdwivedi this will also need changes in server side if we are providing this info

**Comment by shreyanshdwivedi** [comment]
@kushthedude as this issue is labelled in Milestone 4, I'll open sub issues and work on it

**Comment by kushthedude** [comment]
@shreyanshdwivedi Since you are already implementing some functionalities , Can i divide it into some sub-issues and work on them ?

**Comment by shreyanshdwivedi** [comment]
@kushthedude I think you're already working on Captcha thing which is in Milestone 3. I'll suggest you to give that issue priority as this issue is in Milestone 4

**Comment by mrsaicharan1** [comment]
@CosmicCoder96 In which model should "Invoice Contact", timezone, invoice sent out date etc.  be going into? Do we require a new model for it?

**Comment by mrsaicharan1** [comment]
Will keep the invoice formats as a sub-issue to this to make it simpler for implementing it.

**Comment by uds5501** [comment]
Implementing  user's billing information under this parent issue itself.

**Comment by mariobehling** [comment]
Still missing:

* Invoice Format [Format Options here] (please resarch how to do it)
* Logo (enable image upload here),

**Comment by mariobehling** [comment]
Closing in favor of https://github.com/fossasia/open-event-frontend/issues/4958
