### ISSUE TITLE
Admin: User filters not using all column content

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3127]
User filters does not use the content of all columns, e.g. a search with "Gmail" does not yield any result. Expected: It should show all results of users using Gmail. Also add filter for other columns like event etc.

Compare: https://eventyay.com/admin/users/all

![Screenshot from 2019-06-12 12-32-44](https://user-images.githubusercontent.com/1583873/59344431-5f556000-8d0e-11e9-830f-782e358732fd.png)

**Comment by uds5501** [comment]
taking a look at it

**Comment by uds5501** [comment]
@CosmicCoder96 @shreyanshdwivedi After the migration to the new tables, this functionality would be affected, right?

**Comment by CosmicCoder96** [comment]
Fixed with admin wizard refactor of tables.
