### ISSUE TITLE
Billing: Add monthly billing email for event organizers to list of emails

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3130]
Currently there is no billing email for event organizers. Please add a billing email to the system and add it in the list of emails at https://eventyay.com/admin/messages/list

Only send the email to users who need to pay anything.

![Screenshot from 2019-06-12 14-11-08](https://user-images.githubusercontent.com/1583873/59350729-21ac0380-8d1d-11e9-9e2f-02f0fc9b2904.png)

**Comment by uds5501** [comment]
On it

**Comment by mrsaicharan1** [comment]
@uds5501 Post the screenshot of the billing email template here as well.
