### ISSUE TITLE
List Events Invoices, Provide Filters and Actions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3132]
Please improve the invoice section as follows:

* Change https://eventyay.com/admin/sales/status to https://eventyay.com/admin/sales/invoices
* Provide filters, e.g. for date and names
* Provide actions to change status, e.g. from paid to unpaid or processing

![Screenshot from 2019-06-12 14-57-14](https://user-images.githubusercontent.com/1583873/59353411-34293b80-8d23-11e9-944a-288f71572dec.png)

**Comment by kushthedude** [comment]
Will look into it

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 How can I see invoices in this section? I did some orders but the invoices section is still empty.

**Comment by uds5501** [comment]
@mrsaicharan1 @Anupam-dagar can I help with a sub-issue or two?

**Comment by mariobehling** [comment]
Closing in favor of https://github.com/fossasia/open-event-frontend/issues/4954
