### ISSUE TITLE
Filter removal from explore page in mobile devices

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#3136]
This is a sub issue of #3122 focussing on:
- Toggle Filters for the mobile view as done in Event Brite.

**Comment by kushthedude** [comment]
@uds5501 Change the issue description, We don't need to hide filters, We need a toggle as Eventbrite as done to show/hide filters

**Comment by kushthedude** [comment]
@uds5501 Change the issue description, We don't need to hide filters, We need a toggle as Eventbrite as done to show/hide filters 
![image](https://user-images.githubusercontent.com/44091822/59426791-b59dce00-8df6-11e9-90ff-8ebeba86fd8a.png)
 
Please try to implement `Map Section` as done eventbrite, If not possible we can leave the following for the later, As for hide/unhide Map Toggle would look very odd

**Comment by uds5501** [comment]
> @uds5501 Change the issue description, We don't need to hide filters, We need a toggle as Eventbrite as done to show/hide filters

It is to be done in just mobile screens, correct?
As for the map view, i think I will be leaving that for now.

**Comment by kushthedude** [comment]
Yes for just mobile devices

**Comment by kushthedude** [comment]
@uds5501 But as Eventbrite shows a completely different window, On clicking of more filters, I think such component is not provided by `Semantic UI`, So I would suggest if you can have a `Side Bar` toggle, just as we have for `Login Buttons` in mobile view

**Comment by uds5501** [comment]
@kushthedude I am not so sure If the complete makeover would be suggested when things are working fine :sweat_smile: . I guess we should ask @CosmicCoder96 for his views on the suggested UI and if the connected PR would work fine or not
