### ISSUE TITLE
Verified User marked as Unverified and requested to validate email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3138]
A verified user is getting a request to verify.

> Your account is unverified. Please verify by clicking on the confirmation link that has been emailed to you.
Did not get the email? Please click here to resend the confirmation mail.

![Screenshot from 2019-06-13 10-05-32](https://user-images.githubusercontent.com/1583873/59414978-ee23b480-8dc2-11e9-9d04-cf332d5b4e52.png)

**Comment by kushthedude** [comment]
@mariobehling It would be great, If you could tell the exact routes you visited when you got the following message, As the following issue is still open in https://github.com/fossasia/open-event-frontend/issues/3026, else  I am still trying if I find the cause of the error
