### ISSUE TITLE
Send only completed/placed order notifications

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#3154]
**Describe the bug**

Ticket cancellation notifications are being sent while only completed/placed order ticket-holders must receive the notification regarding their order status.

**Screenshots**

![Screenshot-from-2019-06-17-14-09-56](https://user-images.githubusercontent.com/21087061/59614622-c1fb9100-913e-11e9-9867-466e9361fa03.png)

**Comment by uds5501** [comment]
@CosmicCoder96 Please add it to milestone 4

**Comment by mariobehling** [comment]
On second thoughts, while we don't want to tell people that tickets they did not order were canceled, the actual thing we want is to tell people, that "orders have expired". Please rather change the message for ticket orders that were completed to:

"Thank you for your interest in the [event name here]. Your order order has expired. Visit the [event name here] order page <with a link to the page> to order available tickets."

Furthermore, we should have a notification with the same message, when a user has an open order. Please activate this option by default. Compare to https://github.com/fossasia/open-event-frontend/issues/3155

**Comment by uds5501** [comment]
@CosmicCoder96 @mrsaicharan1 @shreyanshdwivedi as discussed on the gitter channel, I don't think this issue is of relevance  anymore.
So, should I close it?

**Comment by mrsaicharan1** [comment]
Please re-open if error is reproducable.
