### ISSUE TITLE
Implement Refund Functionality and Policy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3157]
Research Refund processes and functionalities and open issues for specific areas.

* [ ] Refund Policy in Wizard Step 1 for paid and donation tickets
![Screenshot from 2019-06-18 17-19-41](https://user-images.githubusercontent.com/1583873/59706374-a5279200-9200-11e9-80f0-eac1c36b3d08.png)
* [ ] Show Refund Policy during Check out similar to Eventbrite
* [ ] Show Refund Policy on Public Event Page
<img width="724" alt="refund_policy_on_event_listing" src="https://user-images.githubusercontent.com/1583873/59706520-e91a9700-9200-11e9-87e2-7e4f5995bccc.png">
* [ ] Implement Refund Actions and Process for Organizers
<img width="854" alt="refund_order_quick_actions" src="https://user-images.githubusercontent.com/1583873/59706550-f6d01c80-9200-11e9-9027-1022062f1e4f.png">

Compare to:
* https://www.eventbrite.com/support/articles/en_US/How_To/can-i-get-a-refund?lg=en_US
* https://www.eventbrite.com/support/articles/en_US/How_To/how-to-refund-an-order?lg=en_US

**Comment by kushthedude** [comment]
Looking into it

**Comment by kushthedude** [comment]
Server Side Issue : https://github.com/fossasia/open-event-server/issues/6065

**Comment by mariobehling** [comment]
As parts of this have been implemented and other related issues are open closing this.
