### ISSUE TITLE
Event maps showing wrong location

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3159]
When people create a new event, they usually have a wrong map location.

![Screenshot from 2019-06-19 10-53-45](https://user-images.githubusercontent.com/1583873/59751349-a4cedb80-9280-11e9-97ef-8881720ad31a.png)

**Comment by kushthedude** [comment]
@CosmicCoder96 @mariobehling Please see this https://github.com/fossasia/open-event-frontend/issues/3052#issuecomment-499836852
