### ISSUE TITLE
Move registration time limit to admin settings and set standard to 15 minutes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3161]
Organizers should not have an option to set a time limit on the registration. Please move the time limit to https://eventyay.com/admin/settings and set the standard to 15 minutes. Apply the time limit for all events.

* Keep it out of wizard step 2
* Keep it out of event order forms e.g. here: https://eventyay.com/events/a315169f/tickets/order-form

![58038155-d3a44580-7b4c-11e9-8b24-89fc7c5dfd7c](https://user-images.githubusercontent.com/1583873/59804647-4260f400-92ef-11e9-86ea-f697f2ee7080.png)

**Comment by kushthedude** [comment]
On it

**Comment by kushthedude** [comment]
On it
