### ISSUE TITLE
Deleted orders not visible to admin

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3168]
**Describe the bug**

When an organizer deletes an order, it is invisible to admin too

**Expected behaviour**

The deleted order should not be visible to organizer but it should be visible to admin

**Additional context**

Up for grabs

**Comment by kushthedude** [comment]
@shreyanshdwivedi How we are planning to do it , Adding a new tab just for order would seem bad , Any idea  or suggestion?

**Comment by mrsaicharan1** [comment]
<img width="509" alt="Screenshot 2019-06-21 at 6 35 55 PM" src="https://user-images.githubusercontent.com/25197147/59924491-76edc080-9453-11e9-9146-35a43b123f56.png">
Adding a new tab for deleted orders and including them in the `all` tab is all that is required.

**Comment by kushthedude** [comment]
> <img alt="Screenshot 2019-06-21 at 6 35 55 PM" width="509" src="https://user-images.githubusercontent.com/25197147/59924491-76edc080-9453-11e9-9146-35a43b123f56.png">
> 
> Adding a new tab for `deleted` orders and including them in the `all` tab is all that is required.

So we will just add an order tab, Without relating any order to its corresponding event , And showing orders of all events at once? @mrsaicharan1 Don't you think it is not proper solution?

**Comment by mrsaicharan1** [comment]
> > <img alt="Screenshot 2019-06-21 at 6 35 55 PM" width="509" src="https://user-images.githubusercontent.com/25197147/59924491-76edc080-9453-11e9-9146-35a43b123f56.png">
> > Adding a new tab for `deleted` orders and including them in the `all` tab is all that is required.
> 
> So we will just add an order tab, Without relating any order to its corresponding event , And showing orders of all events at once? @mrsaicharan1 Don't you think it is not proper solution?

Admin will always be able to see all orders related to all events. And yeah, if you would've observed closely, to view a list of orders on the admin side, you have to select the event prior to that. Please try to explore a little more. 
<img width="509" alt="Screenshot 2019-06-21 at 6 35 55 PM" src="https://user-images.githubusercontent.com/25197147/59956143-1a6abf80-94ac-11e9-8664-1b656dc053af.png">

**Comment by uds5501** [comment]
@mrsaicharan1 I will be taking a look at this one today.

**Comment by iamareebjamal** [comment]
Deleting orders is a mistake. Adds too much complexity. Order can be cancelled, so no use of deleting. Hence, the issue is obsolete. We'll prevent deleting order in future as well
