### ISSUE TITLE
Show Sales "Events by Location" according to City only

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3172]
On the Sales "events by location" page only show the city as a location (https://eventyay.com/admin/sales/locations).

![Screenshot from 2019-06-22 20-12-50](https://user-images.githubusercontent.com/1583873/59967463-66f4e000-952a-11e9-8120-f9f086bfb852.png)

**Comment by prateekj117** [comment]
@mariobehling On it.

**Comment by kushthedude** [comment]
> @mariobehling On it.

@prateekj117 I request you to please refrain from pushing the PR for the following, PR is #3014, is almost done, It will be merged in a day , After the pagination is done you can just change the value of a column for the following

**Comment by CosmicCoder96** [comment]
@kushthedude in that case, just do it in PR#3014 itself, thanks!

**Comment by kushthedude** [comment]
Cool ,

**Comment by mariobehling** [comment]
Closing this as we need to approach this differently with online events as another option now.
