### ISSUE TITLE
Rename and Enhance "Admin Sales Fees" 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3173]
1. Please rename fees in admin sales section to "revenue" (https://eventyay.com/admin/sales/fees).
2. Enhance section as follows:
* Implement information as a table 
   * with sortable columns similar to other tables in the admin area
![Screenshot from 2019-06-22 20-22-35](https://user-images.githubusercontent.com/1583873/59967530-91936880-952b-11e9-8840-aca968f20ed9.png) include
   * a search bar
   * event date
   * organizers

**Comment by kushthedude** [comment]
Can be done after merging #3014 or will create merge conflicts .

**Comment by Anupam-dagar** [comment]
@CosmicCoder96 I guess this also needs to be converted to ember table so that search and sort can be implemented in it. Can you confirm? Currently the table is using normal html table syntax.

**Comment by kushthedude** [comment]
This can be managed in #2794

**Comment by mariobehling** [comment]
Already resolved.
