### ISSUE TITLE
Event Dashboard : Include the presence of custom attendee form in Event Checklist

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3175]
**Is your feature request related to a problem? Please describe.**

Event Checklist shows no details about custom attendee form.

**Describe the solution you'd like**

Add details about it

**Additional context**

![image](https://user-images.githubusercontent.com/44091822/59970592-1dd37900-9588-11e9-8b3b-52f2ecb1f9cd.png)

**Comment by uds5501** [comment]
@kushthedude can I take care of this one ?

**Comment by kushthedude** [comment]
> @kushthedude can I take care of this one ?

Sure

**Comment by kushthedude** [comment]
@uds5501 Are you working on it? , Or should I push the changes ?

**Comment by uds5501** [comment]
@kushthedude I am on it, will push it tonight itself.
