### ISSUE TITLE
Attendee Form: Make gender field a dropdown instead of textbox

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3176]
**Describe the bug**

`Gender Field` is currently a textbox in `Attendee Form`.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'Gender Field'
2. See error

**Expected behaviour**

 Please make it a dropdown as done in `Speaker Form`
**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/59970620-96d2d080-9588-11e9-8de7-bef2bd098504.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 24

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prateekj117** [comment]
@kushthedude On it.

**Comment by kushthedude** [comment]
@prateekj almost done the following , Can you please take some else?
