### ISSUE TITLE
Admin: undefined route in `Admin/User'

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3181]
**Describe the bug**

No route is defined for `Accounts Link` in `Admin/Users`

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Admin/Users'
2. Scroll down to 'User Links'
3. See error

**Expected behaviour**

Define the route properly so that admin can see user details

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/60015821-08527200-96a2-11e9-9c10-082fa4b66255.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 24.2

**Comment by prateekj117** [comment]
Can I take this?

**Comment by kushthedude** [comment]
@prateekj117 Be my guest !

**Comment by kushthedude** [comment]
But I am seriously confused at one point, The following route error can be easily removed with changing route name, As we have recently merged `Contact-Info` with ` Profile` but do we need to show this information for every to admin? Isn't it a breach to their private details like `Phone Numer`? @prateekj117 What do you say?
@shreyanshdwivedi @uds5501 Please give your thoughts too.

**Comment by uds5501** [comment]
@kushthedude Yes we do need to show the information. The user is admin after all so he must have an access to all this information.
