### ISSUE TITLE
Event Wizard: Transition between various steps not working as expected

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3187]
**Describe the bug**

The transition between steps of `Event Wizard` is not working smoothly.

**To Reproduce**

Steps to reproduce the behaviour:

- Go to `Edit Event`.
- Go to `Session and Speaker Step`.
- Go to `Sponsor Step` 
- Go back to `Session and Speaker Step`, See Error

**Expected behaviour**

The transition should be smooth, It may happen if the user has left some information in `Sponsor Step`

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/60036258-6d22c200-96cc-11e9-85c2-95951e6f0521.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser Chrome
 - Version 73.0.4

**Comment by uds5501** [comment]
I will take a look at this one.

**Comment by uds5501** [comment]
@CosmicCoder96 @niranjan94 
I took a look at this issue and seems like this is happening similar to the error here : emberjs/data#3077 . 
To try and see if it happens only with our `getOrCreate` method or if it can be recreated using other methods.

I tried using 

```
    data.speakersCall = await data.event.get('speakersCall');;
```
and could still face this error.

I maybe looking at the wrong thing during the debugging, maybe the error wasn't caused by this but please do take a look.

**Comment by niranjan94** [comment]
It is you must use set ... so use set and see. 

```js
data.set('speakersCall', await data.event.get('speakersCall'))
```

**Comment by kushthedude** [comment]
> It says _you must use set_ ... so use set and see.
> 
> ```js
> data.set('speakersCall', await data.event.get('speakersCall'))
> ```

@niranjan94 It was of no good after this now getting 
![image](https://user-images.githubusercontent.com/44091822/60357145-7a9fbb00-99f0-11e9-8541-edee621015ec.png)

**Comment by uds5501** [comment]
> It says _you must use set_ ... so use set and see.
> 
> ```js
> data.set('speakersCall', await data.event.get('speakersCall'))
> ```

I tried that too, faced the same error as @kushthedude . Didn't understand where the `call` object came into picture

**Comment by kushthedude** [comment]
@uds5501 I found the getOrCreate method , Its an custom function defined here 
```js
getOrCreate(event, relationship, modelName) {
    return new RSVP.Promise(resolve => {
      event
        .get(relationship)
        .then(relationshipRecord => {
          resolve(relationshipRecord);
        })
        .catch(() => {
          let record = this.store.createRecord(modelName);
          record.set('event', event);
          event.set(relationship, record);
          resolve(record);
        });
    });
  },
```

**Comment by uds5501** [comment]
> @uds5501 I found the getOrCreate method , Its an custom function defined here
> 
> ```js
> getOrCreate(event, relationship, modelName) {
>     return new RSVP.Promise(resolve => {
>       event
>         .get(relationship)
>         .then(relationshipRecord => {
>           resolve(relationshipRecord);
>         })
>         .catch(() => {
>           let record = this.store.createRecord(modelName);
>           record.set('event', event);
>           event.set(relationship, record);
>           resolve(record);
>         });
>     });
>   },
> ```

Yes, I found it too, in the EventMixin . May help in understanding what's going on

**Comment by uds5501** [comment]
@kushthedude @shreyanshdwivedi 
 I couldn't replicate this error in our test deployment: https://open-event-fe.netlify.com/

Could you please check if you could replicate it there.

**Comment by kushthedude** [comment]
> @kushthedude @shreyanshdwivedi
> I couldn't replicate this error in our test deployment: https://open-event-fe.netlify.com/
> 
> Could you please check if you could replicate it there.

Not Reproducible on event-yay too

**Comment by uds5501** [comment]
Not reproduce able on deployements
