### ISSUE TITLE
Event Dashboard: Attendee Form Missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3188]
A button to edit the "Attendee Form" is missing in the event box. Please add it.

![Screenshot from 2019-06-24 18-36-41](https://user-images.githubusercontent.com/1583873/60036324-430ed700-96af-11e9-8b6f-525d0c7a3672.png)

**Comment by kushthedude** [comment]
Duplicate of #3175

**Comment by uds5501** [comment]
Closed in #3191
