### ISSUE TITLE
Unexpected error when clicking on session and speaker from other tabs while editing event.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#3192]
**Describe the bug**

An unexpected error occurs while in edit view of event, first click on attendee form tab then on session and speakers to see the error.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'edit event'
2. Click on session and speakers
3. Click on attendee form
4. Click again on session and speakers
5. See error

**Expected behaviour**

There shouldn't be any unexpected error.

**Screenshots**

![Screenshot from 2019-06-24 23-10-32](https://user-images.githubusercontent.com/21174572/60039978-95fb8500-96d5-11e9-8654-2fdf318b0a46.png)

**Comment by uds5501** [comment]
@Anupam-dagar I tried traiging the issue and it showed the following behaviour.

Click any tab (Basic Details, Attendee, Sponsorship) causes this error to happen. Please update the description.

**Comment by Anupam-dagar** [comment]
@uds5501 I guess I'll close this issue then, it's duplicate of https://github.com/fossasia/open-event-frontend/issues/3187
