### ISSUE TITLE
Add required columns to 'Manage Events/Sessions' for rating

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3195]
Sub-issue of https://github.com/fossasia/open-event-frontend/issues/2959

We give any role that has the right to rate
   - the option to choose any star from 1 to 5

Also then we can have two more column showing
   - average rating
   - number of people who rated

Columns Required - `| Rate session | Avg Rating | No. of people rated |`

**Additional Context**
On it

**Comment by kushthedude** [comment]
@shreyanshdwivedi I suggest you take this following feature on hold, Ember-Table refactor for `Manage-Events` will be ready in 2-3 days, I don't think we should at least, for now, make a change in manage-events model table, What you say ?

**Comment by shreyanshdwivedi** [comment]
If @CosmicCoder96 feels the same, I can put a hold on it.

**Comment by CosmicCoder96** [comment]
@shreyanshdwivedi If you are creating a separate cell component, then you can just go ahead, I am using the existing cell-components.
