### ISSUE TITLE
Admin/Users {{#link-to}} doesn't transition to route

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#3196]
**Describe the bug**
{{#link-to}} doesn't transition to route in Admin/Users

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'admin/users/{user_id}/account'. 
2. Click on 'Applications'
3. See error

**Expected behaviour**
{{#link-to}} should transition to route in Admin/Users

**Screenshots**
![Screenshot from 2019-06-26 00-42-07](https://user-images.githubusercontent.com/31065687/60126437-9e25f400-97ab-11e9-9452-de1851e5f434.png)

**Additional Context**
Open for all.

**Comment by prateekj117** [comment]
@CosmicCoder96 When clicked on icon, console shows that model described might be null or empty, though when I checked it wasn't.
![Screenshot from 2019-06-26 01-18-09](https://user-images.githubusercontent.com/31065687/60128452-56ee3200-97b0-11e9-8b5a-c4f58799d9e3.png)

**Comment by mrsaicharan1** [comment]
Will have a look

**Comment by shreyanshdwivedi** [comment]
@prateekj117 @mrsaicharan1  this issue is non-existent. Please check and inform so that issue can be closed

**Comment by uds5501** [comment]
@shreyanshdwivedi It is existent on my system

**Comment by mrsaicharan1** [comment]
@prateekj117 There is no such thing as `Applications` in Admin/Users. Could you please tell me where this is persistent?

**Comment by prateekj117** [comment]
Go to `/admin/users/{user_id}/account`

**Comment by mrsaicharan1** [comment]
@prateekj117 Gotcha. I will solve this but please change the issue reproduction info.
