### ISSUE TITLE
Empty UI segment in Admin/Users Profile

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#3197]
**Describe the bug**
Empty UI segment in Admin/Users Profile

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'admin/users/{user_id}/account/profile'
2. See error

**Expected behaviour**
Should not be empty. It should show users info.

**Screenshots**
![Screenshot from 2019-06-26 01-11-24](https://user-images.githubusercontent.com/31065687/60128226-c283cf80-97af-11e9-8126-546dacc582a7.png)

**Additional context**
Open for anyone to take up.

**Comment by shreyanshdwivedi** [comment]
Will take a look

**Comment by shreyanshdwivedi** [comment]
@prateekj117 when you fixed the `app/controllers/admin/users.js` according to this comment - https://github.com/fossasia/open-event-frontend/pull/3193#pullrequestreview-253790501, you fixed this issue. Can you please check on your `route-admin-accounts` branch if this issue exists?

**Comment by prateekj117** [comment]
@shreyanshdwivedi No, it's still there.

**Comment by shreyanshdwivedi** [comment]
Weird!!. I check after pulling your PR. It worked
@uds5501 @mrsaicharan1 @kushthedude can you guys please check?

**Comment by kushthedude** [comment]
closed this in #3222
