### ISSUE TITLE
CI: All tests related to login are failing again

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3201]
All Tests related to Log-In/Log-Out are failing again.
Reference #3200 , #3182

**Comment by niranjan94** [comment]
@kushthedude this not really a useful issue to open. Please do some research. And post your finding and possible causes along with this issue.

**Comment by niranjan94** [comment]
And I don't see any CI fails on the development branch. So, could you clarify what you mean ?

**Comment by kushthedude** [comment]
The upcoming PRs are getting a acceptance test failure , Happened with two
of my PRs had to rebase them or needed to push a test commit so that CI
gets passed , I have mentioned the reference PRs in which the following is
failing
@niranjan94

**Comment by niranjan94** [comment]
@kushthedude again you're only telling `"The upcoming PRs are getting a acceptance test failure"`. 

But what is required from you (as a contributor) is information such as:

- failed test cases
- if you were able to reproduce it locally
- If you have any theories as to why it could occur.
- Possible fixes

**Comment by kushthedude** [comment]
> @kushthedude again you're only telling `"The upcoming PRs are getting a acceptance test failure"`.
> 
> But what is required from you (as a GSoC student) is information such as:
> 
> * failed test cases
> * if you were able to reproduce it locally
> * If you have any theories as to why it could occur.
> * Possible fixes

@niranjan94, At that time all the tests related to login/logout were failing, Problem was CI was not able to assert login and expected and actual URL were diverting, Right now I don't see any such failures now, Could be an issue with CI at that time, I will close the issue might be it was a temporary bug.
Next Time I will post complete stack-trace if I encounter any of such bugs.

PS: I didn't make to GSoC 😅
