### ISSUE TITLE
Add detailed rating info to overview session table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3202]
The overview session table already has columns for ratings. Please add an (i) icon in the rows Avg ratings and Number of Ratings. On scroll over on these icons show:
* on avg ratings - the distribution of ratings e.g. 1 star - 3, 2 star - 0, 3 star - 4 etc.
* Number of ratings: The names of who gave how many stars

![Screenshot_2019-06-26 Session Sessions Order Events Open Event(1)](https://user-images.githubusercontent.com/25428397/60202135-93c93000-9867-11e9-81bc-64aad925bc63.png)

The final structure which is expected from this issue -
* [x] the option to choose any star from 1 to 5
* * [ ] Also then we can have two more column showing
  * [ ] average rating
  * [ ] number of people who rated
* [ ] Columns - | Rate session | Avg Rating | No. of people rated |

Compare -

https://blog.papercall.io/ratings-changes-2847518c95cf
https://papercall.zendesk.com/hc/en-us/articles/216407887-Inviting-Co-Organizers
https://vimeo.com/174958216

**Comment by shreyanshdwivedi** [comment]
Can be worked upon after https://github.com/fossasia/open-event-frontend/issues/3195 is completed

**Comment by amreshk005** [comment]
@mariobehling @shreyanshdwivedi can I work on this issue? if it's still open.

**Comment by iamareebjamal** [comment]
Why mark it as bug @kushthedude ?

**Comment by kushthedude** [comment]
> Why mark it as bug @kushthedude ?

Oh I misunderstood the issue, actually the rating column is misbehaving too. Also, what is the use of such rating where the attendees cant rate the session?

**Comment by iamareebjamal** [comment]
I don't know but you marked a bunch of enahncements and features from 3 months ago as bugs

**Comment by kushthedude** [comment]
I was just exploring the old issues and also closed some of them which are
either solved or not getting experienced

**Comment by palakshivlani-11** [comment]
I want to take up this issue.

**Comment by ranjitkshah** [comment]
@maze-runnar Please check Is it already done or not?

**Comment by maze-runnar** [comment]
> @maze-runnar Please check Is it already done or not?

Yes it is.
