### ISSUE TITLE
Donation Ticket: Ticket Min and Max quantity changing with Min and Max Price of Ticket

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3206]
**Describe the bug**

Ticket Min and Max quantity changing with Min and Max Price of Ticket

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Event Wizard'
2. Create a 'Donation Ticket'
3. Change min and max price
4. See the min and max buying quantity of ticket
5. See error

**Expected behaviour**

This should not be happening 

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/60274060-06441980-9915-11e9-9c1a-8600bab59e14.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 73.0

**Comment by mrsaicharan1** [comment]
@kushthedude Please follow up on the latest PRs. https://github.com/fossasia/open-event-frontend/pull/3194 fixes this too.
