### ISSUE TITLE
Add event owner at relevant places

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3225]
**Is your feature request related to a problem? Please describe.**

This is a follow-up issue of https://github.com/fossasia/open-event-server/issues/6001
A new role - `owner` is being introduced. The code should be refactored at relevant positions to accommodate the change

Please report any bug related to this feature here.

**Additional context**

On it

**Comment by kushthedude** [comment]
@shreyanshdwivedi Have you made a note of the errors which are incurring in the FE due to the introduction of a new role, If yes can you please state all those places too?

**Comment by shreyanshdwivedi** [comment]
@kushthedude this issue is to report any discrepancies observed by you, me, @uds5501, @mrsaicharan or any of us.
@uds5501 can you comment the issue you found here, please?

**Comment by kushthedude** [comment]
@shreyanshdwivedi, The things I noticed rn, 
- In `Manage Events` Table, Roles are not getting rendered.
- Since you have introduced a new role, For all the old events make the `Organiser` to `Event Owner`

**Comment by shreyanshdwivedi** [comment]
@uds5501 reported the issue you mentioned on my server PR @kushthedude. Thanks for commenting here 
I've made changes locally. Will push it soon

**Comment by shreyanshdwivedi** [comment]
I don't think any bug related to event owner is found till now. @uds5501 @mrsaicharan1 @kushthedude can u guys confirm this?
I'll close the issue once confirmed maybe

**Comment by uds5501** [comment]
@shreyanshdwivedi I couldn't find any after the one I reported earlier.

**Comment by mrsaicharan1** [comment]
If any issue comes up, please reopen
