### ISSUE TITLE
Event Dashboard: Remove the `Order Form` from `Event/Tickets` as we already have an `Attendee Form`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3227]
**Is your feature request related to a problem? Please describe.**

As we have already added `Attendee Form` in our `Event Wizard`, I think there is no use of `Order Form` in the `Ticket Dashboard`.

**Describe the solution you'd like**

Remove the `Order Form` from `Event/Tickets` as we already have an `Attendee Form`

**Additional context**

Will do if found required

**Comment by kushthedude** [comment]
@uds5501 @shreyanshdwivedi Do you find it valid?

**Comment by uds5501** [comment]
@kushthedude to be honest, there is no harm in keeping it either. 
@CosmicCoder96 @niranjan94 your views?

**Comment by kushthedude** [comment]
> @CosmicCoder96 @niranjan94 your views?

?

**Comment by kushthedude** [comment]
@CosmicCoder96 @niranjan94 ?

**Comment by kushthedude** [comment]
@uds5501 Since it has been added to a milestone-7, So we can remove it or if you say have it discussed in meetings .

**Comment by shreyanshdwivedi** [comment]
I think we should discuss it in the meeting this weekend

**Comment by uds5501** [comment]
@kushthedude can I take this one if you are working on something else?

**Comment by kushthedude** [comment]
Pushing it
