### ISSUE TITLE
Orders: Sorting of Date Incorrect

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3232]
Sorting according to dates in "Orders" table does not work. It does not sort it according to date and time.

![Screenshot from 2019-07-03 22-07-41](https://user-images.githubusercontent.com/1583873/60621814-fe85e880-9dde-11e9-8557-8488bb085bc2.png)

**Comment by mrsaicharan1** [comment]
Would like to work on this.

**Comment by CosmicCoder96** [comment]
@mrsaicharan1 I will take care of this one in ember tables PR.

**Comment by mrsaicharan1** [comment]
Yeah sure
