### ISSUE TITLE
Make Orders and Attendee View in Ticket Tab Logical

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3233]
The orders and attendee tab show "All" orders immediately. This is not necessary as the organizer usually cares less about expired tickets. They want to see the orders that are completed and placed.

Therefore change the orders and attendee tab as follows:
* Show "Completed" in front
* Move "All" to the last place
* Take out "Pending" from the organizer view. It is not relevant for them.

![Screenshot from 2019-07-03 22-19-48](https://user-images.githubusercontent.com/1583873/60622966-d51a8c00-9de1-11e9-8c0b-bab8edc5d89a.png)

**Comment by shreyanshdwivedi** [comment]
On it
