### ISSUE TITLE
Expired Orders showing up as Placed in My Tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3234]
Expired Orders are showing up as Placed in My Tickets and when clicking on them they show up as paid with Paypal.

![Screenshot from 2019-07-03 22-00-32](https://user-images.githubusercontent.com/1583873/60624811-8c190680-9de6-11e9-8bc5-c06098543de0.png)

![Screenshot from 2019-07-03 22-27-20](https://user-images.githubusercontent.com/1583873/60624816-90452400-9de6-11e9-9e82-290168646036.png)

**Comment by kushthedude** [comment]
Will look into it

**Comment by kushthedude** [comment]
@shreyanshdwivedi Can you look on it, Since you will be migrating the labels task to the server , I hope it can be solved during the following .

**Comment by shreyanshdwivedi** [comment]
@kushthedude I'll be working on adding checks on status of order and that too on server. I don't think this issue is related to server.

**Comment by kushthedude** [comment]
@shreyanshdwivedi @uds5501 @mrsaicharan1 I tried to place 6-7 orders with PayPal, And for my goodness, none of them changed to `Placed`, Initially, they were `Pending` and then they changed the status to `expired`.
There is no chance for `Online Order` to go to Placed, AFAIK `Placed` is only used for tickets with offline payment.
Any Idea?

**Comment by uds5501** [comment]
Fixed on db level
