### ISSUE TITLE
Show appropriate error when order has free tickets(unverified user)

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3278]
**Describe the bug**
When an unverified user orders a free ticket, the server side works fine but the error message on FE is irrelevant. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Order a free ticket from any event with a new email(unauthenticated)
2. The order does not go through(expected) but error message should be appropriate

**Expected behaviour**
Should show up as unverified user cannot order free tickets

**Comment by shreyanshdwivedi** [comment]
Will work on it

**Comment by iharshit009** [comment]
should i take this issue?

**Comment by mrsaicharan1** [comment]
Go ahead

**Comment by GautamGottipati** [comment]
Can I take this issue if no one is working on it?

**Comment by prateekj117** [comment]
@GautamGottipati Go ahead.

**Comment by GautamGottipati** [comment]
I am new to this community and open-source, can I get some help like which file to hunt, to resolve this issue.

**Comment by creatorpiyush** [comment]
Can I take this issue if no one is working on it?

**Comment by iamareebjamal** [comment]
Yes

**Comment by RohitSharma3012** [comment]
If this task is free can I join the work ?

**Comment by iamareebjamal** [comment]
This is now fixed in #4569 and details of issue are mentioned in #4543
