### ISSUE TITLE
Account Section : Billing Info updation gives multiple notification on success or error

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3279]
#### Description: 

Fill up the `Billing Info` in the `Accounts Section` and submit, See multiple notifications for a single click

**Expected behaviour**

Single notification for the single key press

**Screenshots**

<img width="1440" alt="Screenshot 2019-07-14 at 11 59 56 AM" src="https://user-images.githubusercontent.com/44091822/61180169-e6f4fe00-a62f-11e9-9a69-d7f117eb12b9.png">

**Comment by shreyanshdwivedi** [comment]
@kushthedude can you open a PR for this is it is still reproducible?

**Comment by kushthedude** [comment]
> @kushthedude can you open a PR for this is it is still reproducible?

Still reproducible but can't get the exact culprit
