### ISSUE TITLE
Implement payment workflow for event invoice

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3284]
**Is your feature request related to a problem? Please describe.**
The last step in the event invoice workflow is payment functionality. As soon as the event invoice is calculated & made available to the organizer, the payment option will enable the organizer to pay the platform fees.

**Describe the solution you'd like**
The workflow will be similar to that of placing an order.

**Comment by CosmicCoder96** [comment]
Finished.
