### ISSUE TITLE
Compulsory phone number when updating profile details

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-frontend#3289]
**Describe the bug**
Phone number is set as a compulsory field when updating profile details.

**Screenshot**
![Compulsory phone number](https://user-images.githubusercontent.com/35566748/61408095-e5ac2580-a8fc-11e9-9a07-5c825df3c231.png)

**Comment by shreyanshdwivedi** [comment]
On it

**Comment by Hsuya1100** [comment]
can I work on this issue

**Comment by mrsaicharan1** [comment]
@Hsuya1100 Go ahead.

**Comment by Parth910** [comment]
@ShridharGoel  we have to set this field compulsory or remove compulsory field?

**Comment by ShridharGoel** [comment]
@Parth910 This field should not be compulsory.

**Comment by Parth910** [comment]
@ShridharGoel  Ok, Thanks

**Comment by mrsaicharan1** [comment]
Fixes in #3378
