### ISSUE TITLE
Rename `Organised By` to `Owned By` on Event Public Page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3290]
Rename `Organised By` to `Owned By` on Event Public Page

#### Screenshot :

![image](https://user-images.githubusercontent.com/44091822/61454526-c5bd4600-a97e-11e9-801b-da1ba539908c.png)

**Comment by NickSneo** [comment]
Hey, I am new to Open Source World, I want to take this issue as my first Contribution. Please guide and help in fixing this issue

**Comment by kushthedude** [comment]
> Hey, I am new to Open Source World, I want to take this issue as my first Contribution. Please guide and help in fixing this issue

@NickSneo Get familiar with codebase, read the ReadMe file and make a PR, It is just a typo which you have to solve, Can be a perfect issue for you.
