### ISSUE TITLE
Broken thumbnails being shown for event images

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#3298]
**Describe the bug**

Broken thumbnail images (fallback images) are being shown in order-cards and index page. Instead of broken images, the actual event logo and picture should be shown

See the screenshots : 
![image](https://user-images.githubusercontent.com/21087061/61574062-bea94b80-aad6-11e9-9f21-949dbbb29e28.png)
![image](https://user-images.githubusercontent.com/21087061/61574068-d41e7580-aad6-11e9-8f9d-002f8d82b0f5.png)
### Assigned images :
![image](https://user-images.githubusercontent.com/21087061/61574072-e1d3fb00-aad6-11e9-9db9-c4f9a37bfab2.png)

**Comment by kushthedude** [comment]
#### Stack-Trace :

![image](https://user-images.githubusercontent.com/44091822/61574089-4d1dcd00-aad7-11e9-8c5e-d45f443c47d3.png)
  @uds5501 See it , Might be the server issue !

**Comment by prateekj117** [comment]
@kushthedude Paste the networks tab request and response to the API request of images.

**Comment by kushthedude** [comment]
> @kushthedude Paste the networks tab request and response to the API request of images.

Nothing on networks or console @prateekj117

**Comment by prateekj117** [comment]
@uds5501 Not facing this issue. The server response seems alright as well. My both backend and frontend are updated.

![Screenshot from 2019-07-20 10-44-09](https://user-images.githubusercontent.com/31065687/61574298-658fe680-aadb-11e9-93a9-b85cba968921.png)

**Comment by uds5501** [comment]
@prateekj117 @mrsaicharan1 I am facing this issue after starting celery on my system, can you please let me know if it is reproducible after this?

**Comment by CosmicCoder96** [comment]
reopen , if it reoccurs.
