### ISSUE TITLE
Change endpoint for discount code and access code.

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#3299]
Frontend issue for https://github.com/fossasia/open-event-server/issues/6027

**Describe the bug**
Change endpoint for retrieving discount code using event_id as in https://github.com/fossasia/open-event-server/pull/6208. 

**Expected behaviour**
Discount code and access code logic should work properly.

**Comment by prateekj117** [comment]
@mariobehling @uds5501 Please add the tag of high priority and add it to this week milestone.

**Comment by kushthedude** [comment]
Please refer to `Gitter Conversation`.

**Comment by prateekj117** [comment]
@CosmicCoder96 The access-code changes were not done in the previous PR. When entering the Promotional Code, it checks for both the access-codes and discount-codes. Working on the access-code part.
