### ISSUE TITLE
Index Page: Add a condition for display of `Show More Call of Speakers`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3309]
**Is your feature request related to a problem? Please describe.**

No, Displaying of the following `hyperlink` should be when the number of `CFS` is greater than some specific integer

**Describe the solution you'd like**

Add a Logical Condition check for the following.

#### Screenshot: 

Since only 1 CFS is there, The page still shows `Show More Call of Speaker`
![image](https://user-images.githubusercontent.com/44091822/61992924-621fd080-b082-11e9-89db-4104d960bc54.png)

**Comment by mrsaicharan1** [comment]
@kushthedude Can I take this?

**Comment by kushthedude** [comment]
Sure

**Comment by maze-runnar** [comment]
I am working on it .

**Comment by maze-runnar** [comment]
@kushthedude i want to use following helper for application of greater than with if

> <script><br/>
>   Handlebars.registerHelper({ <br/>
>       gt: function (v1, v2) { <br/>
>           return v1 > v2;<br/>
>       },    <br/>
>   });<br/>
> </script>
> 

where i should keep this fuction ?

**Comment by maze-runnar** [comment]
if there is any other way to use greater than ( > ) with if statement , please help me with it !

**Comment by maze-runnar** [comment]
@kushthedude  @uds5501 please help me with this ?

**Comment by kushthedude** [comment]
Implement a computed function in controller.
