### ISSUE TITLE
Integrate PayPal component for Event Invoice Billing

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3313]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
*sub issue*
As soon as the event invoice payment has been authorized & becomes successful, the user must be redirected to the route where he can view the confirmed payment for the invoice.

**Comment by shreyanshdwivedi** [comment]
I'll open a PR for completed payment page by tonight as review page is merged now. @mrsaicharan1 then you can move forward to integrate payment gateway

**Comment by mrsaicharan1** [comment]
Yeah! Will do that right away.
