### ISSUE TITLE
Discunt codes are not working

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3318]
![Screenshot from 2019-07-29 13-08-16](https://user-images.githubusercontent.com/27783786/62030114-fc5a5280-b201-11e9-951e-fbf82fd67316.png)
![Screenshot from 2019-07-29 13-08-06](https://user-images.githubusercontent.com/27783786/62030116-fc5a5280-b201-11e9-9113-f4fc93614f34.png)

**Comment by prateekj117** [comment]
@liveHarshit That's due to #3299
