### ISSUE TITLE
Unable to create paid ticket with price less than 1 (money unit)

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3322]
**Describe the bug**
Unable to create paid ticket like 0.3USD, 0.5 EUR. The minimum amount is 1USD(..)

**Screenshots**
<img src="https://i.ibb.co/x85CrRw/Capture.png" alt="Capture" border="0">

**Comment by kushthedude** [comment]
@anhanh11001 Are decimal prices of tickets been observed on any other platform ?

**Comment by shreyanshdwivedi** [comment]
@anhanh11001 I agree to @kushthedude 
I don't think we need this

**Comment by mrsaicharan1** [comment]
@anhanh11001 I'll fix this but I believe this is a server side related fix.
