### ISSUE TITLE
Remove add icon from discount code page under tickets to maintain uniformity

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#333]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Everywhere in the app for creating any item, we are using only text starting with "create" but in discount code page under the tickets tab, there is an additional add icon along with the text on "Create a discount" button.
 
![selection_073](https://user-images.githubusercontent.com/12701036/27492149-c1e2c1be-5862-11e7-8cc5-40a43fe55995.png)
 
**Expected behavior:**
Remove the add icon from the "Create a discount" button to maintain consistency

**Steps to reproduce:**
Check "Create a discount" button under discount codes in tickets tab.

**Comment by sumedh123** [comment]
@harshitagupta30 Please close this one.
