### ISSUE TITLE
Implement refresh token based authentication

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3353]
API: https://api.eventyay.com
API Docs - https://root-m29xfdiov.now.sh/

Add a check box - `Remember Me`

If the user checks it, they will not be logged out from the site. All needed info on how to implement it is present in Authentication Section of the API doc above. If any doubt, ask me.

**Comment by uds5501** [comment]
Will take a look into it

**Comment by PragatiVerma18** [comment]
I wish to work on this issue. May I?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by snitin315** [comment]
@iamareebjamal the `API Docs` link is broken .
![Screenshot from 2020-01-19 20-14-08](https://user-images.githubusercontent.com/46647141/72682911-693b0f00-3af8-11ea-8cc5-ce45221a93d1.png)

**Comment by iamareebjamal** [comment]
https://api.eventyay.com

**Comment by shivamsingh-07** [comment]
@iamareebjamal  Is this open and can I work on it ?

**Comment by serverwentdown** [comment]
Bump. The lack of refresh tokens causes presenters and viewers to get logged out immediately after the token expires, interrupting their session.
