### ISSUE TITLE
Wrong included tax information

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3357]
Tax details from API: https://open-event-api-dev.herokuapp.com/v1/events/bb9f5cc4/tax
On frontend: https://open-event-fe.netlify.com/e/bb9f5cc4

Tax should calculate in decimal. Like 90.90+9.10

**Comment by kushthedude** [comment]
@liveHarshit That was because we used an integer for ticket price and tax before, I will fix it

**Comment by shreyanshdwivedi** [comment]
@kushthedude if you are busy somewhere, I would like to take this up

**Comment by kushthedude** [comment]
Sure

**Comment by shreyanshdwivedi** [comment]
This can be fixed once https://github.com/fossasia/open-event-server/pull/6366 is merged

**Comment by iamareebjamal** [comment]
Fixed in #4427 and #4428
