### ISSUE TITLE
Enable stripe in dev instance

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3366]
Not able to configure stripe for debug server

**Comment by shreyanshdwivedi** [comment]
@liveHarshit are you on local dev instance?
If yes, you need to enable stripe on `Settings` > `Payment Gateways` > `Enable Stripe`

**Comment by liveHarshit** [comment]
> @liveHarshit are you on local dev instance?
> If yes, you need to enable stripe on `Settings` > `Payment Gateways` > `Enable Stripe`

I haven't set it locally. And how can I check with the Android locally? It needs to create an event first on the API.

**Comment by CosmicCoder96** [comment]
Done, and entered key values too.

**Comment by liveHarshit** [comment]
@iamareebjamal @CosmicCoder96 Please suggest me how to create an event with stripe payment option in dev instance:
![image](https://user-images.githubusercontent.com/27783786/62760748-554ba580-baa2-11e9-8448-f38b8f954ecc.png)

**Comment by tech-and-avinash** [comment]
Same here. even after saving the test keys and enabling not showing in the frontend
