### ISSUE TITLE
Add input also at selecting quantity of tickets

### ISSUE THREAD

**Issue by Parth910** [fossasia/open-event-frontend#3375]
When we select no. of tickets at registration of event there is a dropdown for quantity. sometimes it is frustrating when there is large no of tickets

**solution**
we can add input option also so, that user can manually add a number of tickets

**screenshot**
![rsz_1screenshot_from_2019-08-11_16-39-45](https://user-images.githubusercontent.com/31615065/62833133-2c204600-bc57-11e9-8c44-285699137abd.png)

**Comment by kushthedude** [comment]
@Parth910 The pattern is standard and making it an input field has a lot of consequences, And the number of tickets buyable at a time is also decided by the organiser. Many events do provide their email address for bulk orders, No one makes the bulk order without discussing with event owner. Thanks.
