### ISSUE TITLE
Guest Order: Not responding page after going back from guest order form

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3376]
**Describe the bug**

Not responding page after going back from the guest order form

**To Reproduce**

Steps to reproduce the behaviour:

1.)  Logout of your account, Make a guest order with an ID already registered.
2.) When prompted to enter the password, Try to go back and see a non-responding page.
3.) See error

**Expected behaviour**

The page should be responding with no email.

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/62833685-7659f500-bc60-11e9-8374-ef2a063f60ac.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 74.3.0

**Comment by mariobehling** [comment]
Implementation has changed. Does not seem to be an issue anymore. Therefore closing it. Thanks!
