### ISSUE TITLE
Sessions showing wrong date and time

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-frontend#3377]
**Describe the bug**

Session scheduled at 7 PM, 11 Aug is showing as 12:30 AM, 12 Aug in the `Sessions` section while in the `Schedule` it's shown correctly.

This seems to be due to the unnecessary addition of 05:30 in the time.

**Comment by shreyanshdwivedi** [comment]
I also faced this. Will take a look at this today

**Comment by Anupam-dagar** [comment]
This is difficult to resolve unless the scheduler issue is resolved. Also as per my findings, I was not able to find a root cause in frontend. @shreyanshdwivedi can you take a look at it once.

**Comment by kushthedude** [comment]
Succeded by #3659
