### ISSUE TITLE
UI button overflow in attendees tab under tickets tab.

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#338]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently, the UI buttons, completed, placed, pending etc are overflowing on tablet portrait and small tablet landscape devices
![selection_083](https://user-images.githubusercontent.com/12701036/27505896-16fb73b0-58c9-11e7-852c-ac85a87b2b9f.png)
![selection_084](https://user-images.githubusercontent.com/12701036/27505897-17054886-58c9-11e7-988f-22b24ea22148.png)

**Expected behavior:**
It should not overflow on any of the device.

**Steps to reproduce:**
Check attendees tab under tickets page on tablet devices.

I would like to work on this.

**Comment by geekyd** [comment]
@harshitagupta30 This won't we required as we will be using tabbed-navigation instead of buttons in https://github.com/fossasia/open-event-frontend/pull/312

**Comment by harshitagupta30** [comment]
@geekyd Thanks. I am closing this then. :+1:
