### ISSUE TITLE
Admin Settings: Missing info where Captcha is used

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3390]
The admin settings page at https://eventyay.com/admin/settings contains the option to switch on Captcha. The info on where the Captcha feature is used is missing. Please add a table with the page and functionality that uses the Captcha feature below the config option.

![Screenshot from 2019-08-13 11-23-38](https://user-images.githubusercontent.com/1583873/62933604-e08aab00-bdc2-11e9-8439-8f52b713f744.png)

**Comment by maze-runnar** [comment]
@mariobehling  can you please describe this issue more clearly ?
"Please add a table with the page and functionality that uses the Captcha feature below the config option" . What this line exactly means ?
