### ISSUE TITLE
Admin Area: Addition of Test Client Id in stripe

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3391]
Addition of field for `Stripe_Test_Client_ID` as referred in https://github.com/fossasia/open-event-server/issues/6345

**Comment by shreyanshdwivedi** [comment]
If you're on server issue, I would like to take this

**Comment by kushthedude** [comment]
> If you're on server issue, I would like to take this

Both done will push the FE change too.
