### ISSUE TITLE
Order Form: Optimise Omise Icon for Proper UI

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3395]
Omise image is clearly a lot bigger than it should be supposed to. Refactor it accordingly.
![image](https://user-images.githubusercontent.com/44091822/62950327-6b8c9500-be05-11e9-8a8e-fd51b063c4ca.png)

**Comment by NamanZelawat** [comment]
I would like to work on it.

**Comment by kushthedude** [comment]
Go on

**Comment by NamanZelawat** [comment]
ok

**Comment by NamanZelawat** [comment]
@kushthedude  how can I create a dummy database to access the payment method section as ticketing is not enabled in the cloned repo.

**Comment by kushthedude** [comment]
> @kushthedude how can I create a dummy database to access the payment method section as ticketing is not enabled in the cloned repo.

Set up `Open Event Server`, since the Heroku Deployment won't give you access to omise

**Comment by NamanZelawat** [comment]
yes, I am running an open event server parallel with the ember serve but I don't know how to operate open event server can you suggest how can I get familiar with open event server.

**Comment by kushthedude** [comment]
> @kushthedude yes, I am running an open event server parallel with the ember serve but I don't know how to operate open event server can you suggest how can I get familiar with open event server.

Read the `ReadMe` and if you set up `Open Event Sever` properly, You must have created a database for local usage stated under step-3 and a super-admin stated under step-4

**Comment by NamanZelawat** [comment]
okay, thanks for help.

**Comment by vishakhanihore** [comment]
@kushthedude @CosmicCoder96 Can I work on this issue?
