### ISSUE TITLE
Call for Speakers not issued in Eventyay

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3398]
**Describe the bug**
While my event is shown in Eventyay  Call for Speakers list, when I clicking on it, an error showing "Call for Speakers has not been issued yet". It is still working fine in other clients (Android app)

**To Reproduce**
Try my event here https://eventyay.com/e/e0eedcbd in the main page

**Screenshots**
<img src="https://i.ibb.co/ZWzHZ9k/68628688-817210238673756-4387082610648547328-n.png" alt="68628688-817210238673756-4387082610648547328-n" border="0">
<img src="https://i.ibb.co/4SfCK2h/call-for-speaker-1.png" alt="call-for-speaker-1" border="0">

**Desktop (please complete the following information):**
Chrome

**Comment by kushthedude** [comment]
Not Reproducible in Current version. Please feel free to reopen if you experience the same again. Thanks
