### ISSUE TITLE
Empty refund policy page

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3399]
**Describe the bug**
Refund policy page is empty

**Screenshots**
<img src="https://i.ibb.co/KbgPq9J/67884228-437081670225819-6367273713351524352-n-1.png" alt="67884228-437081670225819-6367273713351524352-n-1" border="0">

**Comment by kushthedude** [comment]
@anhanh11001 This also needs to be filled up by @mariobehling under `Admin/Pages`.

**Comment by mariobehling** [comment]
This needs to be taken care of by content managers not by developers.
