### ISSUE TITLE
Add Settings > Contact Info Page

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#34]
<img width="1680" alt="screen shot 2017-05-10 at 9 51 56 am" src="https://cloud.githubusercontent.com/assets/2404372/25883204/5418a898-3566-11e7-9cc3-e12040cf70f3.png">

- A contact info page located at `/settings/contact-info/`.
- Use a tab navigation layout instead of the existing side-bar style layout.
- The tab navigation should be common to all the other pages `password`, `email preferences`, `applications`. (Only a contact-info page is required in this issue. But ensure the tab navigation will be common to other pages when they are implemented in the future)
- Should contain form validation on submit
- Let the whole form inside a component just like login form. So that we get scoped jquery selection capabilities and we can use the `FormMixin`. (See reference below).

**References:**
- [`app/components/forms/login-form.js`](https://github.com/fossasia/open-event-frontend/blob/development/app/components/forms/login-form.js) - for validation. (Note `FormMixin` and `getValidationRules`)
- [`app/templates/components/forms/login-form.hbs`](https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/forms/login-form.hbs) - for form submit. Note `{{action 'submit' on='submit'}}`
- https://semantic-ui.com/modules/tab.html
- https://semantic-ui.com/collections/form.html
- https://semantic-ui.com/collections/grid.html

**Comment by sumedh123** [comment]
@niranjan94 I'll take this up.

**Comment by geekyd** [comment]
@sumedh123 Have you started working on this issue?

**Comment by sumedh123** [comment]
@geekyd Yes.

**Comment by geekyd** [comment]
Okay :+1:

**Comment by sumedh123** [comment]
@niranjan94 Seems good?
![contact](https://cloud.githubusercontent.com/assets/17925669/26041008/84ca09ac-3947-11e7-83e4-faade75658d1.png)

**Comment by niranjan94** [comment]
@sumedh123 looks good. Please make a PR. 

No need for other pages now. I'll open proper issues for each of them outlining specific requirements.
