### ISSUE TITLE
Sometimes, eventyay page doesn't show anything but error message

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3405]
**Describe the bug**
Sometimes, when going to eventyay.com, I got this error. It is occasional, not really often. If I open an icognito or another browser then the page is working normally

**Screenshots**
<img src="https://i.ibb.co/BNpKnJn/image.png" alt="image" border="0">

**Desktop (please complete the following information):**
Chrome

**Comment by kushthedude** [comment]
Duplicate of #3262
