### ISSUE TITLE
Attendee List: Only render required fields and some of the fields are not rendering.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3406]
Since we are rendering all fields in `attendee list` due to this many incomplete fields are getting shown.
Also, some of the select fields are not getting rendered fix them.
![image](https://user-images.githubusercontent.com/44091822/62997638-9834c100-be86-11e9-8f14-08f151d12738.png)

**Comment by iharshit009** [comment]
I would Like to take on this Issue...

**Comment by kushthedude** [comment]
> I would Like to take on this Issue...
> It would be a request if you kindly provide me the steps to follow to make a PR (as I am new and would be my first PR).

Read Fossasia's Best Practices and see the PRs made

**Comment by Hudda** [comment]
@kushthedude I would like to work on this.

**Comment by kushthedude** [comment]
Go on

**Comment by akshat0047** [comment]
I would like to work on this issue @kushthedude @prateekj117

**Comment by kushthedude** [comment]
Go on, make sure you check the closed pr.
