### ISSUE TITLE
Event invoices are not fetched properly in /review route

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3411]
**Describe the bug**

Currently, we use filter to get a particular event invoice. Also we are not redirecting request from review to paid even if it is paid

```
let filterOptions = [
      {
        name : 'identifier',
        op   : 'eq',
        val  : params.invoice_identifier
      }
    ];
```

**Expected behaviour**

We can use proper GET API to fetch invoice

**Additional context**

On it

**Comment by mrsaicharan1** [comment]
@shreyanshdwivedi I've already fixed this in my payment PR.
