### ISSUE TITLE
Decimal discount code is being rounded off on events/tickets/discount-codes

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3417]
**Describe the bug**

If we set a decimal discount code on `events/<identifier>/tickets/discount-codes` it is being rounded off to integer value.
I set the discount to 10.5% but it is showing 11%

![Screenshot_2019-08-15 Discount codes Tickets taxCalculation Events Open Event](https://user-images.githubusercontent.com/25428397/63090223-3d7b9200-bf78-11e9-8a72-73e8c7b0ac36.png)

**Expected behaviour**

Show exactly same discount code

**Comment by prateekj117** [comment]
@shreyanshdwivedi Is it client-side or happening on server?

**Comment by shreyanshdwivedi** [comment]
It is client side. I think I'll take a look for the reason and fix it

**Comment by Anupam-dagar** [comment]
@shreyanshdwivedi so the input isn't accepting decimal values as valid value. See below.
![Screenshot from 2019-08-17 14-18-18](https://user-images.githubusercontent.com/21174572/63209067-e3a2d580-c0f9-11e9-8071-21c9102bff50.png)
