### ISSUE TITLE
Unable to add line breaks in event description

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-frontend#3419]
**Describe the bug**
Adding line breaks in event description doesn't work. It still appears in the same line in the event page.

**To Reproduce**
Try adding multiple paragraphs in event description.

**Comment by Dishebh** [comment]
Is the issue valid? Unable to reproduce it.

**Comment by iamareebjamal** [comment]
What did you to reproduce it? And please either close your PRs or complete them before working on other issues

**Comment by Dishebh** [comment]
> What did you to reproduce it? And please either close your PRs or complete them before working on other issues

Roger.

**Comment by iamareebjamal** [comment]
Roger
What did you do to reproduce it?

**Comment by Dishebh** [comment]
> Roger
> What did you do to reproduce it?

Created an event and added some paragraphs in event description.They were still distinguishable even after saving it.

**Comment by iamareebjamal** [comment]
>  It still appears in the same line in the event page.

Show the screenshot of event page

**Comment by Dishebh** [comment]
> > It still appears in the same line in the event page.
> 
> Show the screenshot of event page

![Screenshot from 2020-03-20 22-37-18](https://user-images.githubusercontent.com/43489708/77188105-804bac80-6afb-11ea-8b0b-dd20e5381c64.png)

**Comment by iamareebjamal** [comment]
Fixed in #5193 
Duplicates: #4542 #5178
