### ISSUE TITLE
Donation Ticket: Messed up `Ticket Price`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3427]
**Describe the bug**

Messed up `Ticket Price` associated with donation ticket.

**To Reproduce**

Steps to reproduce the behaviour:

1. Enter a `Donation Ticket` price greater than the `Max Value`.
2. Now change the donation price of the ticket within the limits.
3. Place the order and see the `Order Value`

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/63169929-a1c05380-c055-11e9-96b8-7ca62871ebb8.png)

**Comment by may55** [comment]
@kushthedude  Can I work on this?

**Comment by kushthedude** [comment]
@may55 Thats not a good first issue, also I dont think you will be able to solve it. Please start with some beginner issues so that you may get the gist of workflow

**Comment by may55** [comment]
@kushthedude Okay! Thanks

**Comment by iamareebjamal** [comment]
This is now fixed as new Order API has been integrated in the website with no calculation made on frontend, as it should have been
