### ISSUE TITLE
jpeg format is not supported for speaker image

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3434]

**Comment by DaKeiser** [comment]
Hey @liveHarshit can you tell me the steps to reproduce. I think it seems to be working.

**Comment by liveHarshit** [comment]
> Hey @liveHarshit can you tell me the steps to reproduce. I think it seems to be working.

Try to add a speaker in your event with a jpeg format image.

**Comment by DaKeiser** [comment]
@liveHarshit I don't think I'm facing that issue. I have replaced a jpeg with a jpeg

![issue](https://user-images.githubusercontent.com/42712983/67633054-1541d500-f8d1-11e9-9172-ef660f2ea06d.gif)

**Comment by snitin315** [comment]
I think this one is fixed in #3770

**Comment by kushthedude** [comment]
Fixed in #3770
