### ISSUE TITLE
Schedule is not updating with event's time

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3435]
**Describe the bug**
The schedule is not updating when event time is edited.

![image](https://user-images.githubusercontent.com/27783786/63212816-6db56300-c127-11e9-955e-8ef48456bd61.png)
![image](https://user-images.githubusercontent.com/27783786/63212820-786ff800-c127-11e9-92b9-2f4f0bd0f9b6.png)

**Comment by mrsaicharan1** [comment]
It won't update because the scheduler time is independent and it won't be altered automatically. Organisers would have to reschedule it manually. This is not a bug. @uds5501 @shreyanshdwivedi do you agree?

**Comment by uds5501** [comment]
@mrsaicharan1 No, it's not.

**Comment by liveHarshit** [comment]
> Organisers would have to reschedule it manually.

How organizer cut the UI into the half after changing time, if there is no session in the remaining time.

**Comment by liveHarshit** [comment]
It's a bug IMO. The schedule should update according to event time if there is no session.

**Comment by liveHarshit** [comment]
@CosmicCoder96 Your opinion?
