### ISSUE TITLE
Sessions Table: Refreshing table after an action leads to discrepancies [Events/Session]

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3436]
**Describe the bug**

When a user removes a rating on session page (event overview > sessions), refresh it and then move to 'Manage Events', data is missing in the table

**To Reproduce**
Steps to reproduce the behaviour:
- Visit the `Events/Sessions` Page.
- Refresh the page on `Sessions Table`, Unexpected `NavBar` Appears.
- Pagination and sort filter don't even work on the table.

**Expected behaviour**

The data shouldn't be missing in the Manage Events table

**Screenshots**

https://drive.google.com/file/d/1H5VSQvCbVoxuY-BxnBERnZ9lC5CFSRLR/view?usp=sharing

**Comment by kushthedude** [comment]
@CosmicCoder96 These are the list of bugs associated with the current sessions table.

**Comment by shreyanshdwivedi** [comment]
@kushthedude is the new session table even merged to production?

**Comment by kushthedude** [comment]
> @kushthedude is the new session table even merged to production?

@shreyanshdwivedi , I didnt check the issue opened by @shridhargoel was in regards of eventyay or local.
BTW the edits I made are getting faced on local.

**Comment by shreyanshdwivedi** [comment]
Why did u edit the issue title? What bug? 
The earlier title was way more clear about the issue faced.
Also please involve into more discussion before closing the issue. I'm opening the issue reported by @ShridharGoel as it isn't related to this issue. This issue is faced on local and too after performing an action and moving to a new table. Please revert the title back to what it was for clarity

**Comment by kushthedude** [comment]
Session acceptance is not working and all the details enlisted in the issue
description are very well reproducible with current implementation, also
the sort headers are dummy .

**Comment by shreyanshdwivedi** [comment]
@kushthedude please let me know if you understand that the session table itself isn't buggy and let's avoid creating any sort of confusion for now.
- Session acceptance is working perfectly fine on local. Checked just now
- Session rating working fine.
- Data missing appears as soon as `All` is clicked (as happens in few other tables too)
- The only bug which we faced is the one mentioned in this issue's description.
Do you agree with the above-mentioned points? @uds5501 @mrsaicharan1 @kushthedude

**Comment by uds5501** [comment]
> * Session acceptance is working perfectly fine on local. Checked just now
> * Session rating working fine.

I can confirm this @shreyanshdwivedi 

> * Data missing appears as soon as `All` is clicked (as happens in few other tables too)

You are right here, I have been working with even-invoice tables and can see this issue popping up there.
