### ISSUE TITLE
non-restoring of state of checkboxes when returning from different routes

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#344]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
check boxes returned to their default state when we returned back to current route from some other route.

**Expected behavior:**
check boxes should be restore the changes when returned from some other route.

I think it should be done by defining a simple service that holds state for the checkboxes, and then inject it into the routable component.

**Comment by anu-007** [comment]
@niranjan94 please guide.thanks!!

**Comment by niranjan94** [comment]
For which checkbox?

**Comment by anu-007** [comment]
there are a number of checkboxes in the project like `/admin/modules` etc.

**Comment by niranjan94** [comment]
All that would be taken care when we start using the API to get and save data.
