### ISSUE TITLE
Not able to sign up while registering a free ticket from new email

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3440]
**Describe the bug**
Not able to sign up while registering a free ticket from the new email. It directly throws an error instead of opening a signup page and send a verification email.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/a8b7e1b2
2. Try to register a free ticket with a new email
3. See error
4. Related issue with android: https://github.com/fossasia/open-event-attendee-android/issues/2286

**Comment by mrsaicharan1** [comment]
This is not a front-end issue. In addition, this is expected.
Please check it @CosmicCoder96 @uds5501 @shreyanshdwivedi

**Comment by liveHarshit** [comment]
@mrsaicharan1 Actually it's a bug either frontend side or server-side. Attendees are reporting it to me. Please do not close all issue without any feedback. What if you share your event link and a new user is trying to register for a ticket. Test it.

**Comment by shreyanshdwivedi** [comment]
@liveHarshit this is an intended feature to avoid spam. It was well discussed and then implemented.

**Comment by liveHarshit** [comment]
> @liveHarshit this is an intended feature to avoid spam. It was well discussed and then implemented.

You are not getting the issue. The error is displaying without sign up. User should redirect to the sign up.

**Comment by mrsaicharan1** [comment]
@liveharshit I've discussed this issue with @CosmicCoder96, @uds5501,
@shreyanshdwivedi and @anupamdagar in our previous meeting while we were
running the issues down(was a part of a subissue). I believe that feedback
is enough.

**Comment by shreyanshdwivedi** [comment]
@liveHarshit this is more of a feature request than a bug I suppose. We will definitely consider this but it cannot be of priority rn. We are working to make system stable currently

**Comment by liveHarshit** [comment]
> @liveHarshit this is more of a feature request than a bug I suppose. We will definitely consider this but it cannot be of priority rn. We are working to make system stable currently

Yes, that is a point :+1:
