### ISSUE TITLE
Not able to load all sessions (Organizer View) 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#3441]
Organizer was not able to view all submitted sessions. The system only display the first page. When try to view the second page, it kept loading without result 
![Screenshot from 2019-08-18 17-00-17](https://user-images.githubusercontent.com/1658742/63226472-01476c00-c1da-11e9-8247-1c4bfe351009.png)

**To Reproduce**
Steps to reproduce the behaviour:
Go to Event Dashboard > Sessions > Next Page

Test on Ubuntu, chrome

**Comment by shreyanshdwivedi** [comment]
@CosmicCoder96 I think once the ember tables are pushed to production, this issue will be solved automatically as the session table is refactored now.

**Comment by kushthedude** [comment]
Solved with Ember Tables
