### ISSUE TITLE
Integrate order calculation API to FE

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3442]
**Is your feature request related to a problem? Please describe.**

Currently, we are implementing a new API on the server to handle tax and discount calculation for an order. Once it is merged on the server, FE should be changed accordingly
Server PR - https://github.com/fossasia/open-event-server/pull/6366

**Describe the solution you'd like**

When user selects tickets and applies discount code (or not) and hit `Order Now` button, the data should be sent to `/orders/calculate-amount` to fetch calculated response and use it to display on FE

**Additional context**

Will start working on it

**Comment by mariobehling** [comment]
Implemented during orders rewrite.
