### ISSUE TITLE
Sessions not appearing in scheduler

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#3450]
**Describe the bug**

Currently after publishing the schedule on scheduling a session in scheduler, the session can no longer be seen in the scheduler and under the publish schedule button. Also this allows scheduling a new session at the same time and same venue as the previous session.
On clicking any button in the menu navbar i.e speaker or session, the sessions appear under the publish schedule button before the route gets changed.

**Expected behaviour**

The scheduler should show accepted sessions and scheduled sessions at anytime.

## GIF

![scheduler](https://user-images.githubusercontent.com/21174572/63339406-6cbc4580-c362-11e9-844b-29a6a305022c.gif)

**Comment by kushthedude** [comment]
@Anupam-dagar I was not able to reproduce the same .

**Comment by iamareebjamal** [comment]
Not reproducible
