### ISSUE TITLE
Event Dashboard: overlapping columns in `Tickets/Attendees`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3477]
**Describe the bug**

Overlapping columns in `Tickets/Attendees`

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Events/Ticket/Attendee'
2. Try to resize
3. See error

**Screenshots**

<img width="1013" alt="Screenshot 2019-08-25 at 10 26 34 PM" src="https://user-images.githubusercontent.com/44091822/63653206-6c1f1700-c787-11e9-90b9-ae6e6df55430.png">

**Comment by amreshk005** [comment]
@kushthedude may I take this issue??

**Comment by kushthedude** [comment]
Go on
