### ISSUE TITLE
Ticket Dashboard: Overlapping columns in `Tickets/Discount-Codes`

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3478]
**Describe the bug**

Overlapping columns in `Tickets/Discount-Codes`

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Events/Ticket/Discount-Codes'
2. Try to resize
3. See error

**Screenshots**

<img width="916" alt="Screenshot 2019-08-25 at 10 34 27 PM" src="https://user-images.githubusercontent.com/44091822/63653300-860d2980-c788-11e9-82d9-b8f6d666f566.png">

**Comment by IshaGupta18** [comment]
I can take a shot at it!

**Comment by kushthedude** [comment]
@IshaGupta18 Go ahead

**Comment by saksham2410** [comment]
@IshaGupta18 Any progress ?

**Comment by IshaGupta18** [comment]
Yes, I am working on it, if I am unable to solve it, I'll let you know.

**Comment by kayyjayy007** [comment]
I want to work on this issue
