### ISSUE TITLE
Tests are failing for the application

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#348]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Tests are failing for the application after recent commits. 

**Expected behavior:**
All tests must pass for the application.

Test for the PR:
https://www.codacy.com/app/fossasia/open-event-frontend/pullRequest?prid=723449

Tests after merge:
https://travis-ci.org/fossasia/open-event-frontend/builds/246608437?utm_source=github_status&utm_medium=notification

**Comment by niranjan94** [comment]
No need to revert. Fix the tests and make a PR
