### ISSUE TITLE
Speakers Table: Show `sort action` buttons in Speakers Table

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3483]
**Is your feature request related to a problem? Please describe.**

No, Add sort buttons in `Name` and `Email` column of `Speakers Table`.

### Expected
<img width="1095" alt="Screenshot 2019-08-27 at 4 07 18 AM" src="https://user-images.githubusercontent.com/44091822/63728132-390c7e80-c880-11e9-92ad-ef3be6a97186.png">

### Actual
<img width="1067" alt="Screenshot 2019-08-27 at 4 07 57 AM" src="https://user-images.githubusercontent.com/44091822/63728142-475a9a80-c880-11e9-8300-829b8a2b39dd.png">

**Additional context**

Only for **BEGINNERS**

**Comment by imskr** [comment]
I want to work on this issue!

**Comment by kushthedude** [comment]
> I want to work on this issue!

Go ahead

**Comment by IshaGupta18** [comment]
I would like to work on this one @kushthedude ! Can you guide me to the link of the file?

**Comment by imskr** [comment]
@IshaGupta18 It's already taken by me! Please look at another issue.

**Comment by IshaGupta18** [comment]
@imskr alright, I actually did write a comment to claim it, but apparently it didn't get submitted, go ahead with this one!

**Comment by saksham2410** [comment]
As there is no PR for about a week, I am claiming it.

**Comment by IshaGupta18** [comment]
I think it would be good to ask @imskr if he is working on it or not, if he isn't, then only you should claim it.

**Comment by imskr** [comment]
@saksham2410 I'm working on it. Waiting for 15th sept to make PR as for codeheat

**Comment by shreyanshdwivedi** [comment]
@imskr you don't need to wait for 15th Sept to make your contributions counted in CodeHeat. We'll make sure that all the contributions made since beginning of Sept is counted.
Please make a PR asap and if you are busy then let others try

**Comment by Hardik500** [comment]
I would like to work on it if there is no problem

**Comment by shreyanshdwivedi** [comment]
@Hardik500 please proceed

**Comment by amreshk005** [comment]
@Hardik500 are you working on it? if not can I take this issue

**Comment by Hardik500** [comment]
Sorry I wasn't able to get the time for this issue.
@amreshk005 you can go for it.
