### ISSUE TITLE
Admin: Add option to add/edit Google map keys/secret

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3484]
The admin settings page currently does not have an option to add or change the map keys. Please add this option here: https://eventyay.com/admin/settings

**Comment by kushthedude** [comment]
On it

**Comment by kushthedude** [comment]
@CosmicCoder96 Please transfer it to `Server`.

**Comment by CosmicCoder96** [comment]
@kushthedude why transfer? This will certainly require changes on FE too.
Create a new issue on server ?

**Comment by mariobehling** [comment]
This is also a potential security risk as someone else could be able to get the key. This key needs to be implemented on the server side. Could you open an issue, please?

**Comment by iamareebjamal** [comment]
Frontend Google Map keys will always be accessible to the client. They are completely secure to be included in frontend. In fact, the JS library of Google Maps requires accessing the key to download JavaScript. Instead, the Google Map API key should be restricted to eventyay.com to secure it.

**Comment by kushthedude** [comment]
> Map

@iamareebjamal Currently, keys are retrieved from `.env`, We would need a field in the server at least to store them.

**Comment by iamareebjamal** [comment]
And how are you going to use them in frontend to load the Maps SDK?

**Comment by iamareebjamal** [comment]
And once it is loaded on frontend, anyone can see it. So there's no security aspect here. Just the convenience to be able to change the key, which will require changes on how to load the Map SDK on frontend. Please detail how will you do it?

**Comment by CosmicCoder96** [comment]
Obsolete now as we are shifting away from Google Maps
