### ISSUE TITLE
Admin Area: Sessions with same event not rendering event name

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3494]
**Describe the bug**

Sessions with same event not rendering event name

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'admin/session'
2. See error

**Expected behaviour**

Solve the bug

**Screenshots**

<img width="1440" alt="Screenshot 2019-08-30 at 11 29 55 AM" src="https://user-images.githubusercontent.com/44091822/63996569-ab4bc000-cb19-11e9-9dfa-cd1d328a1dd5.png">

**Comment by kushthedude** [comment]
cc: @CosmicCoder96

**Comment by diegofreemind** [comment]
@kushthedude this should be visible in the first column? (like 'Fisrt Event')

**Comment by kushthedude** [comment]
Yes

**Comment by ridhishjain** [comment]
@kushthedude, as there is no-one assigned to this issue. I would like to work on this.
Can you assign it to me?

**Comment by kushthedude** [comment]
> @kushthedude, as there is no-one assigned to this issue. I would like to work on this.
> Can you assign it to me?

Go Ahead.

**Comment by ridhishjain** [comment]
@kushthedude I am having problem creating sessions for the dummy events I have created
![Screenshot (36)](https://user-images.githubusercontent.com/45514905/70116522-fa5d4000-1688-11ea-839c-ddb7ceaee938.png)
How to submit sessions?? and make them confirm?

**Comment by ridhishjain** [comment]
@kushthedude are you talking about this bug?
![Screenshot (38)_LI](https://user-images.githubusercontent.com/45514905/70118571-57a7c000-168e-11ea-8f52-7e399277b7b2.jpg)

the sessions are of the same event and yet event name is not rendered

**Comment by ridhishjain** [comment]
@kushthedude

**Comment by mariobehling** [comment]
As implementation has changed this does not seem to appear anymore.
