### ISSUE TITLE
Event Dashboard: Does not show "Owner" and all "organizers" etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3496]
The event dashboard should show the "Owner" and all other roles. Currently only some invited users are shown.

![Screenshot from 2019-08-30 12-15-38](https://user-images.githubusercontent.com/1583873/64013384-f799fe80-cb1f-11e9-8cf3-83133f80e0a8.png)

**Comment by shreyanshdwivedi** [comment]
I think this section only shows the users invited and who accepted the invitation. 
And the owner might not be showing because it may be an event before the refactor. The Role Invite table might not be included in the refactor because this is the only place where it is rendered.

**Comment by iamareebjamal** [comment]
Verified what was mentioned above. This is the drawback of DB driven approach where everything in API is a row in a database and every field is a column. It should have been properly migrated when the feature was implemented, but now nothing can be done. Events prior to the migration won't show owner, events after the migration will
