### ISSUE TITLE
Admin: Live Events not showing up as Featured when option is chosen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3497]
Some events are not showing up as featured event though option is chosen. Compare: https://eventyay.com/admin/events/live?per_page=100

![Screenshot from 2019-08-30 12-33-34](https://user-images.githubusercontent.com/1583873/64014530-a6d7d500-cb22-11e9-9fd1-46499725f08b.png)

**Comment by Anupam-dagar** [comment]
I will take this up

**Comment by iamareebjamal** [comment]
Fixed in #4653
