### ISSUE TITLE
Inviting a second "Owner" breaks ownership

### ISSUE THREAD

**Issue by fcartegnie** [fossasia/open-event-frontend#3498]
**Describe the bug**

If you invite a second owner, you lose partial ownership

**To Reproduce**
- Invite a member as "Owner"
- The other member accepts the invite, and has full access
- Go back to manage event, you own event dissapeared from your listing
- Access by url, the edit is available

Meanwhile, access is not totally lost as through the URL you can access edit
https://eventyay.com/events/$ID/edit/basic-details

but settings/dashboard are 404
https://eventyay.com/events/$ID/settings

**Comment by shreyanshdwivedi** [comment]
@fcartegnie the `owner` role is meant to be exclusive to 1 user only. An event can have only one owner. However, you can invite users to be organizers, co-organizers, etc.
Please check out https://blog.fossasia.org/allowing-event-owner-to-transfer-an-event-in-eventyay/ for more info on ownership of the event.

**Comment by shreyanshdwivedi** [comment]
> Meanwhile, access is not totally lost as through the URL you can access edit
> https://eventyay.com/events/$ID/edit/basic-details
> 
> but settings/dashboard are 404
> https://eventyay.com/events/$ID/settings

But thanks for reporting this security bug. We'll take a look at this
