### ISSUE TITLE
Event Dashboard: Events are getting sorted by `ID` not their name.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3499]
**Describe the bug**

In `Manage Events` and `Admin/Events` , Events are getting sorted by `ID` not their `Name`.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Manage Events or Admin/Events'
2. Sort using `Name`
3. See error

**Expected behaviour**

Sorting should be done by `Name`

**Screenshots**

<img width="1440" alt="Screenshot 2019-08-31 at 10 27 13 AM" src="https://user-images.githubusercontent.com/44091822/64059419-edd4d180-cbd9-11e9-88fd-dc8b876d8120.png">

**Comment by ani-sha** [comment]
Can I work on this issue? @kushthedude

**Comment by kushthedude** [comment]
@ani-sha Sure, Go ahead.

**Comment by cnebs** [comment]
Could I help with this?

**Comment by cnebs** [comment]
@kushthedude

**Comment by JoaoJesus94** [comment]
Hey, can I help with this issue? Can do it in a couple of minutes
