### ISSUE TITLE
Unpaid Placed Order: Payment area shows "paid with Paypal"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3505]
Placed orders are orders that could be e.g. paid onsite. The final order page should show "To be paid onsite" or "to be paid by wire transfer" etc. (whatever method was chosen). Currently it shows Paypal as a payment method used on the order page even though Paypal was not used.

![Screenshot from 2019-09-03 03-05-52](https://user-images.githubusercontent.com/1583873/64137318-c52a2300-cdf7-11e9-9d65-a1a1d0be6f81.png)

**Comment by kushthedude** [comment]
@CosmicCoder96 @mariobehling This is very ambiguous, can you see `subtotal` and `quantity` is 0 while there is an `Order Amount` ! Also the order link is not protected, I am able to access this.

<img width="1233" alt="Screenshot 2019-09-03 at 10 35 09 AM" src="https://user-images.githubusercontent.com/44091822/64145463-87002400-ce36-11e9-8a0a-dedaeaa74b70.png">
Also, Can this be anyway related to #3234 which was fixed on `DB level` ?

**Comment by adrijshikhar** [comment]
@mariobehling I would like to work on this.

**Comment by iamareebjamal** [comment]
Great, just 130 more issues for you to write this comment. Or you can actually work on some issue and send a PR

**Comment by Haider8** [comment]
@iamareebjamal I think this issue doesn't exist anymore. Please take a look

![onsite-placed-order](https://user-images.githubusercontent.com/43299408/89068575-27383300-d38f-11ea-9125-6fed6e74edb4.gif)

**Comment by iamareebjamal** [comment]
Thanks
