### ISSUE TITLE
The sidebar is not sticky and the images on speakers page are all of different sizes.

### ISSUE THREAD

**Issue by PragatiVerma18** [fossasia/open-event-frontend#3510]
**Is your feature request related to a problem? Please describe.**
The sidebar on the speakers and session page is not visible throughout the page. It disappears in the middle and suddenly appears at the end of the page. Also, the images of speakers are all in uneven sizes and some of them do not have captions and others have which makes it look odd.

**Describe the solution you'd like**

I would like to make the sidebar sticky at the side area and also change the image sizes to a suitable size along with a proper space for captions included.
**Describe alternatives you've considered**

**Additional context**

Here are the screenshots that can provide a better outlook of the problem:
![issue2](https://user-images.githubusercontent.com/42115530/64476187-830f3180-d1a9-11e9-87f9-90d384c8afcb.JPG)
![issue3](https://user-images.githubusercontent.com/42115530/64476197-a3d78700-d1a9-11e9-9f08-fc89381e5142.JPG)

**Comment by kushthedude** [comment]
Some don't have caption because the latter has not entered the following detail. Also restricting images to a default size may pixelate some, That's why they should appear in natural pixels so that they can be clear in all resolutions. Regarding the sidebar, we already have some bugs and high priority issues, So we can look upon UI later on. Thanks

**Comment by CosmicCoder96** [comment]
Issue with sidebar is valid, please work on that @PragatiVerma18 if you are interested.

**Comment by PragatiVerma18** [comment]
Okay, I would be working on that. Thank you.

**Comment by maze-runnar** [comment]
@kushthedude  if no one is working  on it , can i go ahead with this issue ?

**Comment by kushthedude** [comment]
Sure but refrain from using custom css

**Comment by maze-runnar** [comment]
Ok

**Comment by maze-runnar** [comment]
@kushthedude Sticky means , side bar should move side by side with scroll  or it should be fixed at top , i just get confused :smile:

**Comment by kushthedude** [comment]
Side bar should always be stick to top.

**Comment by maze-runnar** [comment]
Ok

**Comment by iamareebjamal** [comment]
> Sure but refrain from using custom css

Why? How else can it be done? Magic? Custom CSS is not voodoo. CSS is CSS. Custom or not. The packages you use also use CSS you know

**Comment by kushthedude** [comment]
If we can achieve the similar stuff using semantic ui classes then it must
be preferred before going to custom css. If css is last resort then it
should be fine.

**Comment by iamareebjamal** [comment]
https://semantic-ui.com/modules/sticky.html

This requires JS and hence will be reset on rerender. My solution is pure CSS hence better
