### ISSUE TITLE
The table with ticket details is not responsive in phone.

### ISSUE THREAD

**Issue by PragatiVerma18** [fossasia/open-event-frontend#3511]
**Is your feature request related to a problem? Please describe.**
The table with ticket details on the events page is not responsive in mobile phone view and there is an overflow on the x-axis of the entire page on the phone due to same reason.

**Describe the solution you'd like**

I would like to use bootstrap or Bulma to make the tables more responsive and better looking.

**Describe alternatives you've considered**

**Additional context**

![issue1](https://user-images.githubusercontent.com/42115530/64476312-ed74a180-d1aa-11e9-97a5-160d3d219356.JPG)

Please assign me the task to implement this. Thank you.

**Comment by kushthedude** [comment]
No, We are using `Ember` and for the `UI and Container` purposes we are using `Semantic UI` which is way better than `BootStrap`, Also the following issue is on phones with small screen sizes. If you can fix it with some `UI Classes` please proceed

**Comment by PragatiVerma18** [comment]
Okay!! I would be working on it.

**Comment by maze-runnar** [comment]
I am taking this issue .

**Comment by Shiwali735** [comment]
i wanna work on this issue, please assign this to me and i am new to this repo so guide me through.

**Comment by iamareebjamal** [comment]
We don't have the bandwidth to guide individual people on how to solve an issue. Simply speaking, if we could so that, why wouldn't we already solve the issue ourselves. And we don't assign issues. If you think you can solve an issue, comment and claim and send a PR

**Comment by Shiwali735** [comment]
Ok, sir thank you
