### ISSUE TITLE
Call for Speakers: Instead of "Add Session Details" there should be only "Add Session"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3513]
It could be confusing to show add session details. The button is actually to add an entirely new session. Therefore please change "Add Session Details" to "Add Session" in Call for Speakers.

![Screenshot from 2019-09-08 01-35-04](https://user-images.githubusercontent.com/1583873/64481276-2deb1400-d1d9-11e9-9fa6-008e80dcaa20.png)

**Comment by skarthikeyan96** [comment]
I would like to work on the bug. @mariobehling

**Comment by prateekj117** [comment]
@skarthikeyan96 Go ahead.

**Comment by shreyanshdwivedi** [comment]
@skarthikeyan96 are you still working on this? If you need any help, feel free to ping us here

**Comment by skarthikeyan96** [comment]
@shreyanshdwivedi I am working on it. I will raise the PR by end of the day

**Comment by amreshk005** [comment]
@skarthikeyan96 are you working on this if not can I take it?

**Comment by siriuswapnil** [comment]
@shreyanshdwivedi is this issue still open? I would like to work on it.

**Comment by shreyanshdwivedi** [comment]
@siriusswapnil I think someone opened a PR for this issue. You can checkout other issues

**Comment by siriuswapnil** [comment]
@shreyanshdwivedi okay. Will do
