### ISSUE TITLE
Call for Speakers: Show existing sessions and info on page instead of on popup

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3514]
If user has not submitted a session or speaker details it currently shows "Submit Proposal". This is correct.

If a user has already submitted speaker and session info, please show the info on the page itself instead of on the popup.

Integrate the popup content in the page.
![Screenshot from 2019-09-08 01-35-04](https://user-images.githubusercontent.com/1583873/64481290-7f939e80-d1d9-11e9-8dd0-66aed2594910.png)

**Comment by asha15** [comment]
@mariobehling  Shall i work on this?
