### ISSUE TITLE
Wizard Step 1/Order Page: Make Billing Info either Mandatory or Optional and change fields

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3518]
The billing info is always collected even if the organizer does not want to collect this information. Also there are some discrepancies of the fields and collection data. Therefore please change the following:
1. In Wizard step 1: Add a button "Require billing info from ticket buyer." to enable the organizer to make this optional
![Screenshot from 2019-09-10 20-24-29](https://user-images.githubusercontent.com/1583873/64640011-61ac8080-d409-11e9-836f-42f80c61970f.png)
2. In the order page do the following
  a) Only make billing info required if the organizer chose "Require billing info.." (in Wizard). If billing info is required always show the fields. If the organizer did not require it, show it as an option using a tick box. -> So, if the organizer does not require it, the user can still add the billing info optionally. The user should tick a box in that case to display the billing option.
  b) In the billing info section itself add field to enter a "Name". Make this field required.
  c) Make "Company" optional.

![Screenshot from 2019-09-10 20-27-58](https://user-images.githubusercontent.com/1583873/64646761-f74f0c80-d417-11e9-83d1-3c2f4be6baa6.png)

**Comment by kushthedude** [comment]
Will take look into it

**Comment by auge8472** [comment]
Distinguish private persons and companies in the section for billing informations. There are countries where it is not common for private persons to be forced to give a Tax ID to pay an order and additionally they have no Company name and ID at all.

**Comment by kushthedude** [comment]
Frontend PR is ready for the same, hope it will be closed by weekend.
