### ISSUE TITLE
Add payment method SEPA Bank Transfer

### ISSUE THREAD

**Issue by auge8472** [fossasia/open-event-frontend#3519]
Currently only the payment methods credit cards and PayPal are available (dependig what event organisers selects). In Europe it's common to pay with bank transfers via the [SEPA system](https://en.wikipedia.org/wiki/Single_Euro_Payments_Area).

Please add this payment method.

**Comment by mariobehling** [comment]
Duplicate.

**Comment by auge8472** [comment]
I'm not addicted to my own ticket, when the work gets done at another place, so might it be. But to call it a "duplicate" of whatever, even it is 14 months older than [the only other one](https://github.com/fossasia/open-event-frontend/issues/5717) that [I can find](https://github.com/fossasia/open-event-frontend/issues?q=is%3Aissue+SEPA+) (opened by @mariobehling who closed *this* issue) is an *at least* "interesting" interpretation.
