### ISSUE TITLE
Frontend check for min order and max order in ticketing system

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#3521]
**Describe the bug**
Their should be a frontend side check of minimum order and maximum order in ticketing system while creating any event

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'create an event'
2. fill the info
3. Add a ticketing system 
4. Minimum order value has no check of less than 1 and max order doesn't has check of greater than min order

**Expected behaviour**
it should be corrected

**Screenshots**
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/20026440/64926570-84c99c80-d81c-11e9-8640-83d09423feea.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [ safari]

**Additional context**
I am taking this issue

**Comment by codedsun** [comment]
@shreyanshdwivedi Shall i proceed?

**Comment by shreyanshdwivedi** [comment]
@codedsun I think the issue is valid. Just one question, were you able to create event with this faulty min and max numbers or server returned proper error message?

**Comment by codedsun** [comment]
server returned msg, but we should not be hitting the server when client side can handle this.

**Comment by codedsun** [comment]
@shreyanshdwivedi Also, can we have issues to beautify or improve the website UI?

**Comment by shreyanshdwivedi** [comment]
>server returned msg, but we should not be hitting the server when client side can handle this.

Agreed. Pls proceed

>@shreyanshdwivedi Also, can we have issues to beautify or improve the website UI?

Currently, we are focusing on solving bugs only. The UI comes later. Please find out bugs and fix them for now

**Comment by codedsun** [comment]
@shreyanshdwivedi Please help me regarding to how to add a check for maximum order value >= minOrder value. I am not able to understand the validation rule placed here 

```
ticketMaxOrder: {
          identifier : 'ticket_max_order',
          rules      : [
            {
              type   : 'empty',
              prompt : this.l10n.t('Maximum tickets per order required')
            },
            {
              type   : 'number',
              prompt : this.l10n.t('Invalid number')
            },
            {
              type   : 'integer[1..]',
              prompt : this.l10n.t('Maximum tickets per order should be greater than Ticket Minimum Order')
            }
          ]
        },
```

**Comment by codedsun** [comment]
@shreyanshdwivedi @kushthedude Any inputs?

**Comment by shreyanshdwivedi** [comment]
@codedsun I think the best place to add the check will be where we are getting data to create the event. Add a check just before hitting server. There are many checks implemented similarly. 
Validation rules will not be helpful as you are using two different entities here.

**Comment by codedsun** [comment]
@shreyanshdwivedi @CosmicCoder96 I added a custom check
```  
window.$.fn.form.settings.rules.checkMaxMin = () => {
     return this.get('data.ticket.minOrder') <= this.get('data.ticket.maxOrder');
    };
```
and added to the rule of ticketMaxOrder, but it's not working..Tell me where I am wrong

**Comment by codedsun** [comment]
@kushthedude please help!

**Comment by kushthedude** [comment]
Why not open a PR and move the discussion there ?

**Comment by snitin315** [comment]
Working on it.

**Comment by snitin315** [comment]
`minPrice` and `maxPrice` Validation is not working as well will fix that too.
