### ISSUE TITLE
Admin Messages: Options not saved

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3524]
Changing options in https://eventyay.com/admin/messages/list to which mails should be delivered does not work. When the admin changes the options a message "Object saved" appears. When the user reloads the page, it shows that the options were not saved.

![Screenshot from 2019-09-17 09-05-09](https://user-images.githubusercontent.com/1583873/65020760-15dc6880-d92e-11e9-9a59-64c97a74f1be.png)

**Comment by Dilshaad21** [comment]
@mariobehling can I take this issue

**Comment by vandanmshah** [comment]
@kushthedude Is anyone is working on it? If no then I would like to pick it up..

Thanks...
