### ISSUE TITLE
Nav Bar: Profile Tab not working in mobile view

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3526]
**Describe the bug**

Profile Tab is not working in Mobile Row
**To Reproduce**
Steps to reproduce the behaviour:- 
- Open eventyay on mobile.
- Login and try to open profile tab through mobile side menu.

**Expected behaviour**

Link the tab properly

**Additional context**

Only for beginners

**Comment by BhuwanChandra** [comment]
@kushthedude Sir, I would like to work on this issue.

**Comment by kushthedude** [comment]
@BhuwanChandra Please Go ahead

**Comment by BhuwanChandra** [comment]
@kushthedude Sir, I have installed the project locally on my machine but it looks like all the things are working fine on mobile view or I am not able to get the exact problem. Can you please help me to understand the problem.

**Comment by kushthedude** [comment]
Read the issue description

**Comment by Ritesh-Ag** [comment]
Sir, can you please explain the which mobile side menu are you referring to?

**Comment by kushthedude** [comment]
@Ritesh-Ag @BhuwanChandra 
<img width="701" alt="Screenshot 2019-09-20 at 4 19 17 PM" src="https://user-images.githubusercontent.com/44091822/65321675-72f04c80-dbc2-11e9-9420-08bdc2c262b8.png">
Please refer to this
--

**Comment by BhuwanChandra** [comment]
@kushthedude Sir, Is the problem related to not hiding of sidebar itself on clicking on any link of the sidebar?

**Comment by Reetam-Nandi** [comment]
@kushthedude @BhuwanChandra Can I claim this?

**Comment by kushthedude** [comment]
Go ahead

**Comment by uds5501** [comment]
@Reetam-Nandi For any doubts, hit us up on the gitter channel.

**Comment by vandanmshah** [comment]
@kushthedude Is anyone is working on it? If no then I would like to pick it up..

Thanks..

**Comment by soumyajit4419** [comment]
I want to work on this issue

**Comment by uds5501** [comment]
@soumyajit4419 @vandanmshah there is already a PR opened for this.
