### ISSUE TITLE
Stripe not working on Development Instance 

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3527]
**Describe the bug**

Stripe is not working on development or testing instance

**To Reproduce**

Steps to reproduce the behaviour:

- Enter Stripe Test Keys and check.

**Expected behaviour**

Fix up Stripe

**Additional context**

It must be due to some keys related issue as some test fields were introduced newly and a thorough testing was not done

**Comment by shreyanshdwivedi** [comment]
@kushthedude this is duplicate of https://github.com/fossasia/open-event-frontend/issues/3459
Why did you open a new issue?

**Comment by kushthedude** [comment]
> @kushthedude this is duplicate of #3459
> Why did you open a new issue?

I tried switching the Stripe from test to production, This was not also working.Anyway, It can be handled in #3459

**Comment by kushthedude** [comment]
Duplicate of #3459
