### ISSUE TITLE
Admin Settings: Improve RegEx for API & FE URL in FE Settings

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3528]
- Current RegEx implemented in `Admin/Settings` Form doesn't support `localhost` URL, which makes testing of some APIs difficult.
- Improve `RegEx` so that `localhost` or `127.0.0.1/xyz` may be supported.

**Comment by SuperGops7** [comment]
Can I work on this?

**Comment by kushthedude** [comment]
Go On

**Comment by Reetam-Nandi** [comment]
Can I claim this?

**Comment by uds5501** [comment]
Considering that the claim has been inactive for 2 days, @Reetam-Nandi you can start off on this one. Do ping for any help / concern
