### ISSUE TITLE
Ember tables: Add a delay for search query network request trigger

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#3532]
Currently, each keystroke triggers a new query while searching on the table as the query param is directly bound to it, instead update the query param after a certain delay of 1 or 2 seconds.

**Comment by SuperGops7** [comment]
Can I work on this issue?

**Comment by TomerPacific** [comment]
@CosmicCoder96 , still relevant?

**Comment by Nikhil-Vats** [comment]
@CosmicCoder96 Can I work on this?

**Comment by maze-runnar** [comment]
@kushthedude i was just watching this issue . I found that 

> _addPropertyObserver() {
>     run.debounce(this, this._loadData, this.debounceDataLoadTime);
>   },

is not workin perhaps , i have changed the value of  _**this.debounceDataLoadTime**_ but that does not made any difference .(open-event/app/components/ui-table-server.js) . please help me if i am missing something .

**Comment by maze-runnar** [comment]
@iamareebjamal can you please clear my doubt , described above .

**Comment by iamareebjamal** [comment]
Try making debounceValue to 20000, so you can confirm it is not changing anything

**Comment by maze-runnar** [comment]
i made it 20000 too ,but it doesn't make a difference .

**Comment by kushthedude** [comment]
Try using setTimeout before the following. We just need a delay before
calling the search function.

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
can you please tell me in which function to use setTimeOut ?

**Comment by iamareebjamal** [comment]
There's already debounce function there, no use of setTimeout

**Comment by maze-runnar** [comment]
Why the debounce is not working then?

**Comment by iamareebjamal** [comment]
That, you need to debug and find out. Welcome to software development

**Comment by maze-runnar** [comment]
Thanks :smile:

**Comment by maze-runnar** [comment]
@kushthedude  i have used this condition that if search parameter is greater than 2 then search will occur , it will give user time to search and table will not be appear/disapper after each keystroke.

```
applySearchFilters(options, params, searchField) {
    searchField = kebabCase(searchField);
    if(params.search.length >2){
      if (params.search) {
        options.pushObject({
          name : searchField,
          op   : 'ilike',
          val  : `%${params.search}%`
        });
      }
  }

```

**Comment by maze-runnar** [comment]
I have tried "settimeout"  too but it is returning OOPs :smile: 
![Screenshot from 2019-11-17 23-29-21](https://user-images.githubusercontent.com/56407566/69012185-0793e280-0999-11ea-86e1-a7962a264101.png)

**Comment by maze-runnar** [comment]
> @kushthedude i have used this condition that if search parameter is greater than 2 then search will occur , it will give user time to search and table will not be appear/disapper after each keystroke.
> 
> ```
> applySearchFilters(options, params, searchField) {
>     searchField = kebabCase(searchField);
>     if(params.search.length >2){
>       if (params.search) {
>         options.pushObject({
>           name : searchField,
>           op   : 'ilike',
>           val  : `%${params.search}%`
>         });
>       }
>   }
> ```

@kushthedude  please check if it fine, so that i can proceed with it .
