### ISSUE TITLE
ReadME: Remove `CodeCov` Badge

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3537]
Since the `CodeCov` always show `unknown`, Please remove the badge from the `ReadME` file, As it looks odd.

**Comment by tmwlsh** [comment]
@kushthedude can i do this?

**Comment by kushthedude** [comment]
Sure

**Comment by shiv-1998** [comment]
Hey! since no PR had been raised I thought of giving it a try..

**Comment by nishantwrp** [comment]
@kushthedude I'd like to work on this issue!

**Comment by kushthedude** [comment]
Go on

**Comment by kushthedude** [comment]
https://github.com/fossasia/open-event-frontend/pull/3546#issuecomment-537827419
