### ISSUE TITLE
Make API_URL configurable

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3542]
Currently, once the project is built (into docker image per se), there is no way to change the API URL. It is not intuitive to rebuild the entire image or project just to change the API URL.

Also, building the frontend image takes more resources than building server image. It can take up to 4-6 GB RAM!

Make it so that API_URL can be changed at runtime. This is important so that the same image can be used by multiple API instances. We need other environment variables to be configurable as well, but API_URL will do for now. 
This is a priority for stage builds so that we can test server and frontend before deploying to production.

Doing so may break the way things usually are done in ember, but it is the sanest way to do things. The entire point of environment variables and sharable docker image breaks if it cannot be used by other instances than api.eventyay.com

**Comment by sharmaaditya570191** [comment]
Hi @iamareebjamal I would like to take this up. Could you please guide me how to get started on this?

**Comment by iamareebjamal** [comment]
It's not that simple. It's more about making changes in the JS environment handling than docker. It's not a beginner-friendly issue, so, in order for you to take it up, you need to understand the problem by building the image and seeing the current implementation and understanding what can be done. There is little to guide in this issue, because if we knew exactly what should be done, we would have done it by now considering it is a high priority issue

**Comment by sharmaaditya570191** [comment]
Thanks @iamareebjamal . I will try finding the solution by building the docker image.

**Comment by kushthedude** [comment]
I will take a look
