### ISSUE TITLE
Quick Filter triggers a Get Request with empty values 

### ISSUE THREAD

**Issue by Batey96** [fossasia/open-event-frontend#3547]
**Describe the bug**

When the search button on the homepage gets clicked with empty search event and search location,a request is made to the server.
**To Reproduce**
Mouse focus on the event input and location input tabs without typing anything,click the search button and view the search bar
**Expected behaviour**
No search should be triggered with empty event names and Location.

**Screenshots**
![Screenshot from 2019-10-05 16-46-54](https://user-images.githubusercontent.com/24868289/66257348-d7e59e00-e78f-11e9-99d9-5eef6a40d22d.png)

**Comment by mariobehling** [comment]
Thanks, this is very important and a valid issue. It should be addressed within this issue https://github.com/fossasia/open-event-frontend/issues/4994
