### ISSUE TITLE
Public Page: Add `:` between TimeZone Details and also add UTC

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3559]
**Is your feature request related to a problem? Please describe.**

Currently, we are showing timezone as `0530` without any prefix nor `:` between the digits, which may be confusing.

**Describe the solution you'd like**

Add the prefix `UTC` and also add `:` to distinguish between hours and minutes.

**Screenshot**

<img width="803" alt="Screenshot 2019-10-16 at 3 16 39 AM" src="https://user-images.githubusercontent.com/44091822/66872445-ad7fb600-efc3-11e9-9e18-5177837281a8.png">

**Additional context**

Open for all.

**Comment by nik72619c** [comment]
I'd work on this one

**Comment by kushthedude** [comment]
> I'd work on this one

Please proceed

**Comment by invisiblegeek1** [comment]
I will do this one

**Comment by nik72619c** [comment]
could you please write how would the above date look like exactly ?

**Comment by nik72619c** [comment]
Him could you please help me with the file to make the changes ?

**Comment by Semicolon10** [comment]
May I start on working this

**Comment by DaKeiser** [comment]
Can I take this isssue ?

**Comment by kushthedude** [comment]
@nik72619c any progress

**Comment by DaKeiser** [comment]
@kushthedude why can't we have IST/some other timezone name instead of having **+5:30 UTC** thing. Adding a **+5:30 UTC** makes it look a bit clumsier

![issue](https://user-images.githubusercontent.com/42712983/67438045-0e386f80-f610-11e9-88a3-5ccb07a80483.jpg)

I have tried both the methods as shown in the screenshot above and I personally find IST/ any other timezone depiction better than explicitly mentioning +5:30 UTC / anything else

**Comment by DaKeiser** [comment]
The below screenshot is the solution you are trying to ask for 

![issue](https://user-images.githubusercontent.com/42712983/67500633-9e25fa00-f6a0-11e9-8bf7-9774defd7aa2.png)

This is the solution I think would look better

![issue2](https://user-images.githubusercontent.com/42712983/67501231-8e5ae580-f6a1-11e9-8722-24e851db0472.png)

If you approve I can send the PR for any one of the change right away. Thanks

**Comment by DaKeiser** [comment]
@kushthedude can I send a PR now ?

**Comment by geetchoudhary** [comment]
@nik72619c, are you still working on this?
If not @DaKeiser, you can proceed with your PR.

**Comment by damn-dvlpr** [comment]
@kushthedude Sir, Is this issue closed or can i start working upon it?

**Comment by DaKeiser** [comment]
@damn-dvlpr I have already sent a PR. Waiting for a review

**Comment by ketul08** [comment]
@kushthedude  can i work on it ?

**Comment by geetchoudhary** [comment]
> @kushthedude can i work on it ?

This issue has been assigned to someone else, you can look for other issues to solve.

**Comment by DaKeiser** [comment]
@geetchoudhary I have submitted the PR long ago. Can you look into it? Thanks :)

**Comment by kushthedude** [comment]
I know your PR is long due, Actually we are facing some issues in Time
Widgets recently, Hence I have not reviewed it. Once, the issue is solved
be assure it will be moved forward. In the meantime you may contribute to
other issues.
Thanks for the wait.

**Comment by iamareebjamal** [comment]
Why add UTC when the time is shown in event timezone? Makes no sense

**Comment by snitin315** [comment]
Fixed in #3611
