### ISSUE TITLE
Correct the ui pop alignment in the /events/<event_id>

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#356]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Current : 
![event_sponsorpopup](https://user-images.githubusercontent.com/17925669/27531634-ff2622ae-5a7a-11e7-8dd1-ed7f25045eef.png)

Expected : 
For the other pages we have ui-popup to the left. So to maintain it across all, it should align left.

**Comment by sumedh123** [comment]
Working on this.

**Comment by anu-007** [comment]
@sumedh123 it is already done, please check PR https://github.com/fossasia/open-event-frontend/pull/347
