### ISSUE TITLE
Switch to OpenStreetMaps or MapBox depending on the key provided at runtime

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3564]
Maps functionality should work with OSM or MapBox depending on the key provided at runtime. 

Parent Issue: #3563 
See Also: #591

**Comment by kushthedude** [comment]
@iamareebjamal I was thinking to implement a toggle for the following in the Admin panel. How does that sound?

**Comment by iamareebjamal** [comment]
First fields need to be added in settings and a field to select which one is enabled

**Comment by kushthedude** [comment]
Yes, thats what I am thinking in place of checking the key provided at
runtime.

**Comment by iamareebjamal** [comment]
environment variables as they are used right now

**Comment by TeAmP0is0N** [comment]
Below you can see the whole code required to create a map, position it, place a marker and create a popup with the office address.
```bash
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
</head>
<body>
  <div id="mapDiv" style="width: 800px; height: 500px"></div>
  <script>
    // position we will use later
    var lat = 40.73;
    var lon = -74.00;
    // initialize map
    map = L.map('mapDiv').setView([lat, lon], 13);
   // set map tiles source
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
      maxZoom: 18,
    }).addTo(map);

    // add marker to the map
    marker = L.marker([lat, lon]).addTo(map);

    // add popup to the marker
    marker.bindPopup("<b>ACME CO.</b><br />This st. 48<br />New York").openPopup();
  </script>
</body>
</html>
```
I used the (Leaflet library)[https://leafletjs.com/] to handle map displaying. In the example above, in the head section, I used the hosted version of the CSS and JS files, but you can download it on your server and host locally. In the body section, you can see the div element of id “mapDiv” which is configured to be 800 pixels wide and 500 pixels high. 
The rest of the magic is simply placed in the script. At first, we are setting the latitude and longitude of the point we want to put the marker on (and this will be also the center of our map). Next, we are creating the map, which will be placed in our “mapDiv” element, centered on the position we have chosen and zoomed to level 13. You can change the zoom level to better fit your needs.
The important thing is the map source configuration. There are various map sources you can use, but in this example, I want to keep things straight so I simply configured OpenStreetMap tiles as the source. Please note that you have to keep copyright information in such a case.
We almost finished. Now we can place the marker on the map (on the latitude and longitude configured before). As the last step, we are placing the popup with the information about our company.

**Comment by kushthedude** [comment]
Please check how to use with Ember the above code is crude html and ajax.
Also we are not using any external script in our complete web app.

**Comment by TeAmP0is0N** [comment]
@kushthedude so, we can't use any external library. ie. leaflet?

**Comment by iamareebjamal** [comment]
We can, but we don't need interactive maps, just a static map with a marker. If it can be done without an entire library, it'd be preferred.

**Comment by prateekj117** [comment]
@TeAmP0is0N You working on this?

**Comment by kushthedude** [comment]
I dont think he is.

**Comment by TeAmP0is0N** [comment]
@prateekj117 I am trying but I am not able. If you want to solve this issue, then you can.

**Comment by kushthedude** [comment]
@prateekj117 Are you still working on it?

**Comment by kushthedude** [comment]
@iamareebjamal For the current version I am thinking to remove the `ember-g-map` and use Open Street Map for the current version. Later we can restore google map with much lighter add-on than `ember-g
-map`as it is  a bulky, verbose wrapper that reimplements the entire Google Maps API.

**Comment by iamareebjamal** [comment]
Sure, I agree, see which is better OSM or MapBox

**Comment by iamareebjamal** [comment]
https://miguelcobain.github.io/ember-leaflet/docs/adding-layers

Supports both OSM and MapBox. MapBox WebGL is cheaper than layers aproach, but OSM is free. So, better option is to go for leaflet first and and MapBox WebGL if it is not enough

**Comment by prateekj117** [comment]
@kushthedude Sure. Go ahead.

**Comment by kushthedude** [comment]
Above package is quite heavy, was looking for some other alternatives.

**Comment by iamareebjamal** [comment]
How did you find out it's "quite heavy"? What is its size? Leaflet is the easiest way to use OSM. And we need this issue solved ASAP. Use this and then iterate to improve the solution.

**Comment by mariobehling** [comment]
Closing this in favor of more detailed new issues.
