### ISSUE TITLE
 unresponsive ticket type buttons on create event page

### ISSUE THREAD

**Issue by Batey96** [fossasia/open-event-frontend#3566]
**Describe the bug**

The ticket type buttons on the the create event page do not align properly on mobile devices.
We could either manage the space and fit all the buttons or present them as modalized options or stack them.In any case.

**Screenshot**
![unresponsivetick](https://user-images.githubusercontent.com/24868289/67146325-e3ea5900-f281-11e9-9967-aa92e88cfb30.png)

@CosmicCoder96  @kushthedude  if this really looks like an issue to you,can i start working on it?

**Comment by kushthedude** [comment]
Fitting button in one line would make UI too ugly.
Also to display each ticket in a row just for a screen size for <468px would result in too much space utilisation. Hence the current look is fine IMO.
Also, we have quite a lot of issues to solve before getting to such minor UI makeovers.
Thanks
