### ISSUE TITLE
start date and time should be "before" end date and time

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3568]
** start date and time should be "before" end date and time **
At first entering end date before start date it is showing error correctly but after correcting it , it is not removing that warning and warning is "start date and time should be after date and time" while it should be "

> end date and time should be after date and time

".
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "https://eventyay.com/"
2. Click on 'create event'
3. Scroll down to 'start and end date' input box

**Expected behaviour**
It should show warning
>  "end date and time should be after date and time"

**Screenshots**

**Desktop (please complete the following information):**

![Screenshot from 2019-10-22 12-12-13](https://user-images.githubusercontent.com/56407566/67265173-b80de400-f4ca-11e9-95c1-064607ad451b.png)

**Smartphone (please complete the following information):**
 -every device
**Additional context**
_### if you think this as a issue , i start work on this ._

**Comment by kushthedude** [comment]
@maze-runnar Please give proper steps to reproduce. I am not able to reproduce this behaviour.

**Comment by SundaramDubey** [comment]
Go on create event then fill start and end dates first time wrong means start time  > end time then it shows up the message "start date and time should be "after" end date and time " while it should be "start date and time should be "before" end date and time " and then fill start and end time correctly but it still shows invalid date in time section of ends .

**Comment by maze-runnar** [comment]
Go on create event then fill start and end dates first time wrong means start time > end time then it shows up the message "start date and time should be "after" end date and time " while it should be "start date and time should be "before" end date and time " and then fill start and end time correctly but it still shows invalid date in time section of ends .

**Comment by kushthedude** [comment]
> Go on create event then fill start and end dates first time wrong means start time > end time then it shows up the message "start date and time should be "after" end date and time " while it should be "start date and time should be "before" end date and time " and then fill start and end time correctly but it still shows invalid date in time section of ends .

Hmm Error message is incorrect, But the error disappears when I set the right time. So you just need to change the error message .

**Comment by kushthedude** [comment]
Definitely, go ahead :+1:
