### ISSUE TITLE
Date and location section of search for events is not appearing in mobile view .

### ISSUE THREAD

**Issue by SundaramDubey** [fossasia/open-event-frontend#3572]
**Date and location section of search for events is not appearing in mobile view .**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to main page in mobile view and full screen pc then you can see it like below .

![Screenshot from 2019-10-24 13-16-21](https://user-images.githubusercontent.com/43514004/67464841-aca0f100-f661-11e9-8ed4-56cb39f367b7.png)
![Screenshot from 2019-10-24 13-16-34](https://user-images.githubusercontent.com/43514004/67464842-aca0f100-f661-11e9-8c6d-713fefff1aaf.png)
Additional text :
I want to work on this issue.

**Comment by kushthedude** [comment]
https://github.com/fossasia/open-event-frontend/issues/2247#issuecomment-469095512
