### ISSUE TITLE
Send test email box is not properly showing in mobile view

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3574]
**Describe the bug**
Send test email is not responsive
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://localhost:4200/admin/settings'
2. Click on 'Send Test Email '
3. the input box is not correctly showing for moble device .

**Expected behaviour**
Email box should be responsive for mobile device also .

**Screenshots**
![Screenshot from 2019-10-25 08-58-16](https://user-images.githubusercontent.com/43514004/67541486-bfb9cc80-f706-11e9-8f09-f640adaef527.png)
![Screenshot from 2019-10-25 09-06-42](https://user-images.githubusercontent.com/43514004/67541498-c9433480-f706-11e9-976b-9e3a2e8656f2.png)

**Additional context**
I am working on this .

**Comment by kushthedude** [comment]
Closed by mistake. Go ahead

**Comment by maze-runnar** [comment]
ok
