### ISSUE TITLE
Use toggle switch instead of a button in show map

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3577]
**Use toggle switch instead of a button in show map**
I want to use a toggle swictch instead of show/hide map button in mobile view  .
![Screenshot from 2019-10-26 14-16-55](https://user-images.githubusercontent.com/56407566/67616954-dc83fc00-f7fb-11e9-8c7a-48f3d594587b.png)

**Additional context**
I want to work on this if you say so.

**Comment by maze-runnar** [comment]
@uds5501  can i go ahead with this ?

**Comment by maze-runnar** [comment]
@kushthedude  @uds5501  can i go ahead with this ?

**Comment by mariobehling** [comment]
Current implementation is sufficient. We can think this through later again maybe, but right now we should focus on more major issues. Therefore closing it.

**Comment by maze-runnar** [comment]
I am understanding what you are saying But @mariobehling i have already implemented it and it's working fine . Beside this the name of the action name is toggle map that's why i think it should be a toggle switch .
And i have already fix this -
![Webp net-gifmaker](https://user-images.githubusercontent.com/56407566/67733661-053b0a00-fa25-11e9-82f9-d3cfab34bd77.gif)

**Comment by kushthedude** [comment]
Button looks a lot great than toggle. No need for the change.
