### ISSUE TITLE
Rename google plus entry to google groups from admin social link page

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3584]
Remove google plus entry from admin/content/social link page.
![Screenshot from 2019-10-30 10-00-11](https://user-images.githubusercontent.com/56407566/67937204-25202880-fbf3-11e9-90a3-d7e92acb3bd1.png)

**Additional context**
If this is necessary , i am working on this.

**Comment by kushthedude** [comment]
Renaming it to `Google Groups` will make sense imo

**Comment by maze-runnar** [comment]
> Renaming it to `Google Groups` will make sense imo

Thanks sir , it means that i have to change google plus entry to google groups.
