### ISSUE TITLE
Call for Speakers: Does not show all form fields in Speaker and Session page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3585]
In the wizard it is possible to enable/disable form fields for speakers and sessions. The form does not actually show the fields that are enabled in the speakers and session form.

Here is the wizard form. A lot of form fields are enabled, e.g. Github. But: They dont show up in the form of the speaker.

![Screenshot from 2019-10-31 11-19-33](https://user-images.githubusercontent.com/1583873/67938763-6eab4c00-fbd0-11e9-9150-a7262570fa86.png)

Here is the speaker form. Many of the above enabled form fields don't show up.
![Screenshot from 2019-10-31 11-22-24](https://user-images.githubusercontent.com/1583873/67938948-d1044c80-fbd0-11e9-99da-caad09b4eae1.png)

The session form is also missing a lot of form elements.
![Screenshot from 2019-10-31 11-22-59](https://user-images.githubusercontent.com/1583873/67938968-dbbee180-fbd0-11e9-9f31-b35149ff5f23.png)

**Comment by kushthedude** [comment]
Checking it, As the CFS issues were solved way back but by seeing the order of fields in session form, I think the issue is related to legacy.
@mariobehling Can you please the event name ?

**Comment by mariobehling** [comment]
It is not related to legacy. The event was setup as a fresh event. Please try testing it.

**Comment by mariobehling** [comment]
Also, save the event and edit it. There is also the questions if editing event is possible and if the fields change accordingly.

**Comment by kushthedude** [comment]
I got the issue for rendering, but in session the fields are jumbled which
will have to be fixed manually as it was earlier for OTS Thailand.

**Comment by prateekj117** [comment]
@mariobehling Looking into it.

**Comment by mariobehling** [comment]
When a new speaker submits speaker info for the first time, it still does not show all the fields. Please test with an event that shows all fields (enable all fields in wizard step 4 and test it please).
Compare https://eventyay.com/e/a74665c3/cfs/new-speaker

**Comment by iamareebjamal** [comment]
@mariobehling This fix has not been deployed yet. You can try it out on the dev instance

**Comment by kushthedude** [comment]
@iamareebjamal the session issue is still not solved

**Comment by prateekj117** [comment]
@kushthedude Can you please provide screenshots, I will have a look at it right away.

**Comment by iamareebjamal** [comment]
@kushthedude Which fields are missing?

I can see comment, level, session type, short abstract, slide, title and track enabled. All of which are present in the form

**Comment by kushthedude** [comment]
> @kushthedude Which fields are missing?
> 
> I can see comment, level, session type, short abstract, slide, title and track enabled. All of which are present in the form

https://github.com/fossasia/open-event-server/issues/6273

**Comment by kushthedude** [comment]
The order and the issue which I told you earlier to fix the order manually .

**Comment by prateekj117** [comment]
@kushthedude So unordered, not missing, right?

**Comment by kushthedude** [comment]
Yup.

**Comment by prateekj117** [comment]
@iamareebjamal Ya, they are unordered. I will see if I am able to find the bug causing it.

**Comment by kushthedude** [comment]
Actually there is no bug for this, all the new events getting created are
with correct order in fields.
I have mentioned a link to issue where this was occurring before and it was
solved by manually correcting the order in DB

**Comment by prateekj117** [comment]
It was happening at my local machine as well. There must be a reason that they are rendered unordered. @iamareebjamal Need your insight.

**Comment by iamareebjamal** [comment]
Because there is no order defined in the backend, so they are returned in the order of IDs. That is another issue and should be solved by allowing the admin to reorder the fields. Fixing it in the DB is a workaround. Let's create another issue for that
