### ISSUE TITLE
Ticket Dashboard: Table CSS Overflow on Small Device Screens

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3589]
**Describe the bug**

Table CSS Overflow on Small Device Screens.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Event/{event.id}/tickets'
2. See the screen with device `width < 690px`
3. See error

**Expected behaviour**

Fix the CSS Overflow

**Screenshots**

<img width="549" alt="Screenshot 2019-11-03 at 5 38 13 PM" src="https://user-images.githubusercontent.com/44091822/68084808-bd6f1500-fe60-11e9-97e5-4ad65db9fa12.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 8 & old
 - Browser: All

**Comment by snitin315** [comment]
@kushthedude I would like to work on this issue.

**Comment by kushthedude** [comment]
Sure, go ahead

**Comment by snitin315** [comment]
I have fixed it by setting the css overflow property to scroll.
![Screenshot from 2019-11-03 22-16-23](https://user-images.githubusercontent.com/46647141/68088713-b4456e80-fe87-11e9-9a2d-10418ef5f4c9.png)
![Screenshot from 2019-11-03 22-16-34](https://user-images.githubusercontent.com/46647141/68088715-bc9da980-fe87-11e9-811c-0bb75aedf6ef.png)
