### ISSUE TITLE
Add a sub route create-session under events/<events-id>/sessions/

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#359]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/20153241/27537467-ace6bf78-5a91-11e7-8e03-ddbfb58395da.png)

create `events/<event-id>/sessions/create` UI and form validation.

**Comment by anu-007** [comment]
I like to work on this.

**Comment by niranjan94** [comment]
@anu-007 the entire form (this and the speaker from) should be dynamically generated with each form field customizable by the organizer. This first requires the API design from the backend. So, on hold until then.

**Comment by geekyd** [comment]
Closing this via #770
