### ISSUE TITLE
Event Dashboard: Weird vertical displacement on Unpublishing Event

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3592]
**Is your feature request related to a problem? Please describe.**

 Weird vertical displacement on `Unpublishing Event`

**Describe the solution you'd like**

Fix the displacement of the page .

**Comment by maze-runnar** [comment]
@kushthedude  i want to work on this .

**Comment by kushthedude** [comment]
Sure go ahead

**Comment by maze-runnar** [comment]
i have find the reason , 
![Screenshot from 2019-11-04 11-47-07](https://user-images.githubusercontent.com/56407566/68102469-eb079d00-fef8-11e9-9459-d64935ca1ba8.png)
but i need some help . why it is there ?

**Comment by maze-runnar** [comment]
> {{#if (or (eq session.currentRouteName 'events.view.index') (eq session.currentRouteName 'events.view.export'))}}

Same problem is in export tab also . 
THis is showing an extra div while {{unverified-user-message}} is not present there .

**Comment by maze-runnar** [comment]
So i added a condition to check if {{unverified-user-message}} is present or not .
