### ISSUE TITLE
Improvements in Add New Custom Form Widget

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#3598]
**Describe the bug**
`Add Custom Field` Widget needs some improvements:
 - Add another Custom Field Button Available even when Session and Speakers are 
   turned off.
 - When clicked, there is no way to delete the row/field if someone doesn't 	 
   want to add a custom field. And when sessions and speakers are enabled, and 
   someone clicked the `Add Custom Field` button, but don't want to submit a 
   custom field, the system does not `Save Draft` or `Publish` an event and 
   throws an error that `Field cannot be null`, which again makes it important 
   to maybe have a simple button to add/cancel a field.  
 - `true` printed above every custom field row widget.
 - Make `form` field as a dropdown with three options:
	- Session
    - Speaker
	- Attendee

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event. 
2. Go to Sessions and Speakers Step.
3. Test the Custom Fields button for the above-mentioned bugs.

**Expected behaviour**
Add Custom Field widget should work properly.

**Screenshots**
![Screenshot from 2019-11-04 03-57-08](https://user-images.githubusercontent.com/31065687/68093019-3ac57480-feb7-11e9-841f-90254d249e6c.png)

**Additional context**
Up for grabs.

**Comment by kushthedude** [comment]
@prateekj117 Except for the UI enhancements, Is the custom form feature working as expected?

**Comment by prateekj117** [comment]
@kushthedude Not sure. Will test that. Add urgent as well as we are planning for the next release soon. We should atleast solve the display of `true` before the release.

**Comment by kushthedude** [comment]
Ohh, custom widget will be released in next release too 😩

**Comment by prateekj117** [comment]
Not sure. @iamareebjamal Need your insight. I was thinking to atleast solve the obvious errors before the release.

**Comment by kushthedude** [comment]
> Not sure. @iamareebjamal Need your insight. I was thinking to atleast solve the obvious errors before the release.

We cant make next release until its properly tested or another idea is to comment the widget for now just for this release and make it usable until next release.
@iamareebjamal ?

**Comment by iamareebjamal** [comment]
Hide it for now

**Comment by iamareebjamal** [comment]
And the same approach should be followed in future. Hidden in prod and visible in dev until completely tested and ready

**Comment by iamareebjamal** [comment]
The old component was too complicated and a new simpler component is now used.
