### ISSUE TITLE
Scroll does not reset on route change

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#360]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The scroll does not reset when changing the routes

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12807846/27562672-3794b914-5aeb-11e7-9a17-f70093d65fac.gif)

**Expected behavior:**
The scroll must reset when the route is changed.

**Comment by niranjan94** [comment]
@geekyd lets use this https://github.com/dollarshaveclub/ember-router-scroll as it preserves scroll on pressing back (needed). And also allows us to override scroll to top behaviour on a per-route basis.

**Comment by geekyd** [comment]
@niranjan94 Okay. So we need to preserve the scroll for all the pages?

**Comment by niranjan94** [comment]
Not preserve scroll. We need the scroll reset on page transition. But on pressing back, the old scroll state on the old page to be preserved. The plugin handles that for us.
