### ISSUE TITLE
Cluttered footer

### ISSUE THREAD

**Issue by damn-dvlpr** [fossasia/open-event-frontend#3604]
**Describe the bug**
This is not particularly a bug, but an UI enhancement.

The footer looks very cluttered as of now, both in desktop and mobile view.

**Comment by damn-dvlpr** [comment]
I would like to work upon this.

**Comment by kushthedude** [comment]
Can you be a little more specific ?

**Comment by damn-dvlpr** [comment]
The footer looks very big, we can clean it up a little up by diving the Categories section into 2 or more columns.

**Comment by kushthedude** [comment]
The footer seems nice with 4 column layout, Can you please give what you
proposing since making it two column will make it look overcluttered and
ugly.

**Comment by mariobehling** [comment]
Improving this is relevant. However right now we need to focus our developer resources on high priority issues. We will have to come back to design questions another time and right now we are not able to solve issues like that. Thank you. Closing it therefore.
