### ISSUE TITLE
Manage Event Dashboard : css overflow of search-box on small screen devices

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3605]
**Describe the bug**

There is css-overflow of search-box on small screen devices in manage event dashboard .
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Manage events section  under profile tabs.
![Screenshot from 2019-11-05 20-18-40](https://user-images.githubusercontent.com/46647141/68217944-825c1580-0009-11ea-825d-1537bbbe91d0.png)
'
2. Click on 'Manage Events'
3. Now inspect in responsive mode for small screens

**Screenshots**
![Screenshot from 2019-11-05 20-21-37](https://user-images.githubusercontent.com/46647141/68218178-e979ca00-0009-11ea-84d4-fa791bdd324a.png)

**Additional context**
Up for grabs.

**Comment by kushthedude** [comment]
Fix it in #3593

**Comment by snitin315** [comment]
> Fix it in #3593

@kushthedude  can you point me to the corresponding file??

**Comment by kushthedude** [comment]
Fixed in #3593
