### ISSUE TITLE
Automate test account creation in tests

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3609]
@iamareebjamal All the tests related to `Login` are failing again, I have restarted the build for development branch if it doesn't correct up. I will open an issue and debug it.
PS: The following failure has no related to this PR, Hence it's safe to merge.

_Originally posted by @kushthedude in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550061511_

Steps taken to fix it?

_Originally posted by @iamareebjamal in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550960161_

> Steps taken to fix it?

Creation of test account which was removed in db

_Originally posted by @kushthedude in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550962644_

Automate that in the tests please. Create an issue and a PR

_Originally posted by @iamareebjamal in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550965509_

What about the solution I told in gitter?

_Originally posted by @kushthedude in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550965955_

No, that is overkill

_Originally posted by @iamareebjamal in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550966361_

What should be the solutions , create an account and delete it after and
then create a new in script ?

_Originally posted by @kushthedude in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550967006_

No, try to login, and if it fails, create a new account

_Originally posted by @iamareebjamal in https://github.com/fossasia/open-event-frontend/pull/3606#issuecomment-550968263_

**Comment by AhwiniMirajkar** [comment]
I want to work on this
