### ISSUE TITLE
Search box is not looking normal

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3612]
**Describe the bug**
Search box is looking weird .
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://localhost:4200/events/195ea1ec/tickets/add-order'
2. See error
![Screenshot from 2019-11-01 17-56-48](https://user-images.githubusercontent.com/56407566/68481572-98faaa80-025d-11ea-8426-4d295ea1caa0.png)
![Screenshot from 2019-11-01 17-56-45](https://user-images.githubusercontent.com/56407566/68481646-c6dfef00-025d-11ea-96cd-a8776c4acf1b.png)
 it should be somewhat like this -
![Screenshot from 2019-11-01 17-56-56](https://user-images.githubusercontent.com/56407566/68481713-f68ef700-025d-11ea-87e9-af5e606aa768.png)

**Additional context**
I am working on this .

**Comment by kushthedude** [comment]
To solve overflow, we have done this. Also, no issue in the first one since on small screens it would be difficult to touch on the following.

**Comment by maze-runnar** [comment]
So it should be modified in 3rd image . take a look at 3rd image please.

**Comment by maze-runnar** [comment]
3rd image is from the same website from another webpage .and both are Looking differ that's why i think one of these should be change

**Comment by kushthedude** [comment]
Its due to space constraint and class differences .

**Comment by kushthedude** [comment]
Improving this is relevant. However, right now we need to focus our developer resources on high priority issues. We will have to come back to design questions another time and right now we are not able to solve issues like that. Thank you. Closing it, therefore.

**Comment by prateekj117** [comment]
@kushthedude If the issue is relevant, don't close it. Just mark it with low priority.

**Comment by kushthedude** [comment]
https://github.com/fossasia/open-event-frontend/issues/3604#issuecomment-550680096

**Comment by maze-runnar** [comment]
I will get back to it later :smile:
