### ISSUE TITLE
Vulnerability : Cookie No HttpOnly Flag

### ISSUE THREAD

**Issue by Rajchowdhury420** [fossasia/open-event-frontend#3613]
**Description of The Bug**
A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [BlackArch Linux ]
 - Browser [chrome]
 - Version [71]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rajchowdhury420** [comment]
@mariobehling @CosmicCoder96 Please Review

**Comment by kushthedude** [comment]
@iamareebjamal ?

**Comment by iamareebjamal** [comment]
> A cookie has been set without the HttpOnly flag

No indication which cookie. Do we have to guess it now?

> If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. 

If a malicious script is run on `this page` - which page?  
If a malicious script is run, it'll simply get the tokens stored in localstorage and send to its server. JWT tokens used for auth are being stored in local storage, not cookies

> If this is a session cookie then session hijacking may be possible.

Exactly, you haven't even told the name of the cookie you are mentioning and are speculating `if this is session cookie`

No session cookie is being used by the site right now. Tell the name of the cookie in the issue, we aren't telepathics

**Comment by iamareebjamal** [comment]
Will reopen if required info is added

**Comment by kushthedude** [comment]
> Will reopen if required info is added

Closing for now. Thanks
