### ISSUE TITLE
Event card should respond to hover

### ISSUE THREAD

**Issue by SimranArora123** [fossasia/open-event-frontend#3616]
I would like to share my idea of adding animation i.e **the event card should respond to hover**
for example in the gif shown below we can replace the arrow with some text which will describe the events .

![GIF-191110_122208-1](https://user-images.githubusercontent.com/52946773/68540483-dfb0e780-03b8-11ea-97ef-56a459fc483c.gif)

**Comment by prateekj117** [comment]
@SimranArora123 This seems like a good idea. Though we have some other important bugs in the system right now. Meanwhile, if you like you can go ahead with this issue. @iamareebjamal Can you mark this with appropriate tags?

**Comment by SimranArora123** [comment]
> 
> 
> @SimranArora123 This seems like a good idea. Though we have some other important bugs in the system right now. Meanwhile, if you like you can go ahead with this issue. @iamareebjamal Can you mark this with appropriate tags?

Okay i will work on this.

**Comment by iamareebjamal** [comment]
Hi, this is not relevant right now. There are other UI bugs we'd like to focus on before enhancements. Moreover, for design changes, we need to take opinions of other team members. So, it'd be great if you take up issues right now rather than enhancements
