### ISSUE TITLE
Spacing between the text in event card

### ISSUE THREAD

**Issue by SimranArora123** [fossasia/open-event-frontend#3617]
In the event card there is **less spacing** between the last line (hashtag) and the boundary.
![Screenshot (142)](https://user-images.githubusercontent.com/52946773/68542045-b3ec2c80-03cd-11ea-8170-f6bca639b2f4.png)

**Additional context**
I will work on this issue.

**Comment by kushthedude** [comment]
Improving this is relevant. However, right now we need to focus our developer resources on high priority issues. We will have to come back to design questions another time and right now we are not able to solve issues like that. Thank you. Closing it, therefore.
