### ISSUE TITLE
Migrate to ES6 syntax for the webapp

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3618]
We have already introduced ES6 in various places in our app.

It would be great if we could completely migrate our app to ES6 syntax during code heat.

**Point to remember:**
- Before making any PR for the migration, Each and Every functionality for the following component should be tested as we have less coverage for code. We need to make sure no functionality break during the following.

**Comment by maze-runnar** [comment]
@kushthedude  @mariobehling  i am working on migrating all the modals to ES6 , is it ok ?

**Comment by kushthedude** [comment]
Go one by one, its not that easy you think. There are many dependency which
dont use ES6 Syntax and that is why the complete transition was done during
out summers. There are also many depreciations and other stuff which needs
to be handled out before jumping to ES6. Also, not to talk about the
warning encountered in Travis CI. Also this migration must also ensure if
anything is not broken in webapp as we dont have much of tests written for
many functionalities.

**Comment by kushthedude** [comment]
A rather better approach will be handling the migration while solving a bug
related to same, as you did in case of image cropper.

**Comment by maze-runnar** [comment]
Ok , i will do one by one at the time of solving bug related to that .

**Comment by iamareebjamal** [comment]
Already done AFAIK
