### ISSUE TITLE
Some things are not visible on small screen

### ISSUE THREAD

**Issue by SimranArora123** [fossasia/open-event-frontend#3620]
There are two things which are not visible on small screen:
1. The heading **"EVENTYAY"** on the top-left side is not visible.(nav bar)
2. The **"ENTER LOCATION"** and **"ALL DATE"** input boxes are missing.

![Screenshot_20191110-184310_Samsung Internet](https://user-images.githubusercontent.com/52946773/68544577-b0b36980-03ea-11ea-8d97-983f14d64f6e.jpg)

**Comment by kushthedude** [comment]
> 1. The heading **"EVENTYAY"** on the top-left side is not visible.(nav bar)

Hmm, We need to remove `Open Event` and replace it.

Regarding the second point which you said, its not needed right now its a design choice we opted for the present

**Comment by SimranArora123** [comment]
> 
> 
> > 1. The heading **"EVENTYAY"** on the top-left side is not visible.(nav bar)
> 
> Hmm, We need to remove `Open Event` and replace it.
> 
> Regarding the second point which you said, its not needed right now its a design choice we opted for the present

@kushthedude what should we  write in the place of open event?

**Comment by kushthedude** [comment]
See how it is done in wide screen, we should display application baje e
entered in settings.

**Comment by himanshu010** [comment]
I will work on this issue

**Comment by ABHIJITBURMAN** [comment]
if this issue is still open can i take it?

**Comment by himanshu010** [comment]
> 
> 
> if this issue is still open can i take it?

@ABHIJITBURMAN this issue has two parts, the second one is not resolved yet and you can take it.

**Comment by ABHIJITBURMAN** [comment]
@himanshu010 ok

**Comment by ABHIJITBURMAN** [comment]
@himanshu010 2nd part means loaction and date input box?

**Comment by himanshu010** [comment]
yess

**Comment by Aaryan-kapur** [comment]
Hey can i take this up!?

**Comment by snitin315** [comment]
@himanshu010  , If you approve I would like to work on this issue.
