### ISSUE TITLE
Problem in the size of table in small screen

### ISSUE THREAD

**Issue by SimranArora123** [fossasia/open-event-frontend#3622]
In the column (subtotal) the information are not inside the box
![Screenshot_20191111-233745_Samsung Internet](https://user-images.githubusercontent.com/52946773/68610508-ed13c200-04dd-11ea-9ae4-ea039ab1216f.jpg)

i will work on this issue.

**Comment by maze-runnar** [comment]
Duplicate #3511

**Comment by snitin315** [comment]
> I think it's a Duplicate of #3511

Fix it in #3583

**Comment by uds5501** [comment]
Closing as duplicate of #3511. @SimranArora123 if you find any new issue please feel free to report it!
