### ISSUE TITLE
There is css-overflow of subtotal tab on small screen devices in tickets 

### ISSUE THREAD

**Issue by himanshu010** [fossasia/open-event-frontend#3625]
**Describe the bug**

There is css-overflow of subtotal tab on small screen devices in tickets .

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Homepage'
2. Click on 'any of the ticket'
3. Scroll down to 'tickets section'
4. Now inspect in responsive mode for small screens
5. See error

**Expected behaviour**

The table should have a scroll property on overflow
**Screenshots**

![Screenshot (33)](https://user-images.githubusercontent.com/43860289/68989753-f8197a00-0870-11ea-8595-42fc95b58ebe.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser : Firefox
 - Version : 70.0.1 (64-bit)

**Additional context**

I will work on this issue

**Comment by snitin315** [comment]
Duplicate #3511

**Comment by himanshu010** [comment]
> 
> 
> I Think it's a Duplicate of #3511 .

yess you are right.
Closing it as duplicate of #3511
