### ISSUE TITLE
Server error when getting a list of event invoices

### ISSUE THREAD

**Issue by sharmaaditya570191** [fossasia/open-event-frontend#3627]
**Describe the bug**
Server returns 500 internal server error if we try to access event invoices under Account-->Billing Info.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Account after logging in from your account.
2. Click on Billing Info tab.
3. Go to Invoices tab.

**Expected behaviour**
A list of event invoices if they exist otherwise a message displaying "No event invoices yet."

**Screenshots**
![Screenshot from 2019-11-16 21-14-47](https://user-images.githubusercontent.com/42587159/68995797-b65ff200-08b7-11ea-9f2c-3d8a2c7f4cce.png)

**Desktop**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**
I want to work on this issue.

**Comment by sharmaaditya570191** [comment]
Hi @iamareebjamal . Could you please tell how to resolve this?

**Comment by iamareebjamal** [comment]
By debugging the server

**Comment by kushthedude** [comment]
Not Reproducible on local neither production. Please feel free to re-open if you experience the following. 
Thanks
