### ISSUE TITLE
Organizer app landing page: The image in the organizer app landing app is too large

### ISSUE THREAD

**Issue by nishantwrp** [fossasia/open-event-frontend#3631]
**Describe the bug**

Image used in the `Organizer App` Landing is much larger than it should be. 

**Screenshots**

![Screenshot_20191116_231105](https://user-images.githubusercontent.com/36989112/68997193-a4874a80-08c9-11ea-8751-2f49799d6627.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser : Firefox

**Comment by snitin315** [comment]
I guess `display: flex , align-items: center` will make it look better,

**Comment by snitin315** [comment]
@nishantwrp  , can I work on this issue?

**Comment by nishantwrp** [comment]
@snitin315 Sure!

**Comment by kushthedude** [comment]
Not Required as of current scope. Thanks please look into other bugs .
