### ISSUE TITLE
Use route based chunking to reduce JS

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3634]
Right now, megabytes of unneeded JS are loaded for the user to access eventyay.com

For a user to see the landing page with few images and cards of events, 6-8 MB of JS is not needed. Every 3rd party library and component with Admin Panel code is loaded for a single read only page.

Bundles should be split by route and only loaded on the routes where they are needed

**Comment by snitin315** [comment]
I @iamareebjamal  , can I work on this issue??

**Comment by iamareebjamal** [comment]
Yes

**Comment by kushthedude** [comment]
Isnt it same as #2849 ?

**Comment by iamareebjamal** [comment]
No, that's about calling external services. You may not remove JS and still not call any external services

**Comment by durgesh077** [comment]
@iamareebjamal  I want to work on this . Please assign this project to me .

**Comment by minhho89** [comment]
At `homepage`:
`vendor.js` took 6.02s (2.3MB)
`open-event-frontend.js` took  3.87s (664kb only but took a long time)
Should concentrate to solve these 2 first
![Image](https://github.com/fossasia/open-event-frontend/assets/61931543/3b7eba5c-accd-4ff1-99f5-e7eb374a59f2)

**Comment by cweitat** [comment]
Due to ember old version; fix is to remove upgrade ember / remove packages which is not possible
https://github.com/ember-learn/ember-website/issues/394
