### ISSUE TITLE
"Passwords do not match" displayed when no password is entered

### ISSUE THREAD

**Issue by sharmaaditya570191** [fossasia/open-event-frontend#3638]
**Describe the bug**
"Passwords do not match" is displayed for Re-enter password field when no password is entered on **Register** page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Register page.
2. See error

**Expected behaviour**
Live check of re-enter password field should be done only if password field is not empty.

**Screenshots**
![Screenshot from 2019-11-16 17-20-45](https://user-images.githubusercontent.com/42587159/69005352-0cc84180-0947-11ea-9a91-1800b1ba717c.png)

**Desktop:**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 70.0.1

**Additional context**  
I want to work on this.

**Comment by maze-runnar** [comment]
@sharmaaditya570191 i didn't find it .
![Screenshot from 2019-11-17 14-51-56](https://user-images.githubusercontent.com/56407566/69005563-e22bb800-0949-11ea-8f8c-52fbd65db2e8.png)

**Comment by maze-runnar** [comment]
I think first you entered any password then erase it that't why it is showing password didn't match .

**Comment by sharmaaditya570191** [comment]
Hi @maze-runnar . Yes this was the case but as I have deleted both it should update.

**Comment by maze-runnar** [comment]
You will find this pattern on every page. IMO this is not a bug .

**Comment by sharmaaditya570191** [comment]
Ok @maze-runnar then I should close the issue.Thanks for your input.
