### ISSUE TITLE
Changing date of ticket sales results in date change of ticket bought

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3647]
Please try this:
1. Change the end of sales date of tickets
2. Observe the date tickets have been bought in "Orders" and "Attendees"
Result the date will change to the date when you changed the ticket sales date.

Expected: The attendees/orders list should always show the date orders were made.

![Screenshot from 2019-11-22 06-01-21](https://user-images.githubusercontent.com/1583873/69380634-d6dfe000-0ced-11ea-8f2d-3c0e0b462c8e.png)

**Comment by sharmaaditya570191** [comment]
Hi @mariobehling . I am unable to reproduce the error on my system.In the process I get the following error on clicking view button to view the event I created. Could you please guide me on this?
![Screenshot from 2019-11-22 20-48-38](https://user-images.githubusercontent.com/42587159/69437020-80fc4e00-0d68-11ea-9fb0-206b574b4874.png)
![Screenshot from 2019-11-22 20-48-54](https://user-images.githubusercontent.com/42587159/69437105-a25d3a00-0d68-11ea-94be-bb812342df26.png)

**Comment by maze-runnar** [comment]
@mariobehling  @kushthedude  i want to work on this . 
![Screenshot from 2019-11-24 11-04-10](https://user-images.githubusercontent.com/56407566/69490221-96799100-0eaa-11ea-8180-b23b1699389c.png)
Order section is showing time correctly . Do i only need to change attendee page?
![Screenshot from 2019-11-24 11-08-05](https://user-images.githubusercontent.com/56407566/69490246-d9d3ff80-0eaa-11ea-91b4-5cb4d558c29b.png)

**Comment by maze-runnar** [comment]
working on it .
