### ISSUE TITLE
bug:browser back button not working when user is not logged in and hits create event button

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#365]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
when user is not logged in and hits create event button then it redirects to login route and when we hit browser back button in this route nothing happens

**Expected behavior:**
on hitting back button from login route user must be redirected to home page.

**Comment by anu-007** [comment]
i like to work on this

**Comment by niranjan94** [comment]
Please propose your solution before you work on this.

**Comment by anu-007** [comment]
replacing anchor tag of the button with link-to helper will work here.

**Comment by niranjan94** [comment]
Have you tried it?

**Comment by anu-007** [comment]
yes I tried it locally and it worked well

**Comment by niranjan94** [comment]
Cool. Then make a PR

**Comment by anu-007** [comment]
also, there are two create event button one in the navbar and other in the welcome header these buttons have some inline css i find the scss file for welcome header but there no scss file present for navbar so should i create one or i have other solution as mainly the inline css  is transforming the text to uppercase should i use nested helper as
 ```         
 {{#link-to 'create' class='ui blue button'}}
     {{UpperCase (t 'Create Event')}}
 {{/link-to}}
```

**Comment by niranjan94** [comment]
I think there is a scss file for nav bar. If not, create it.
