### ISSUE TITLE
A proper regex for passwords

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3651]
Go to "https://open-event-fe.netlify.com/account/password"
Reset the password , now there is only a single restriction that the password length should be greater than 8 . I think there should be a proper regex for that .   
It is not showing any error for setting "////////" as a password .
![Screenshot from 2019-11-23 12-26-44](https://user-images.githubusercontent.com/56407566/69474883-8dc28580-0dec-11ea-934b-7be620c8f920.png)

**Additional context**
I want to work on this.

**Comment by kushthedude** [comment]
8 char password is currently appreciable. We can take a look at the following afterwards where we can judge the password quality also. 
However, right now we need to focus our developer resources on high priority issues. We will have to come back to question another time and right now we are not able to solve issues like that. Thank you. Closing it, therefore.

**Comment by maze-runnar** [comment]
Can you please suggest me any of the  currently opened issue , i should work on . I really want to resolve them .please !

**Comment by kushthedude** [comment]
There are many issues with label bug
