### ISSUE TITLE
Admin: Change Tab Sorting of "Events"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3657]
In the admin panel the standard tab shows "All Events" as the first standard tab. Please change the tab sorting at https://eventyay.com/admin/events/live as follows:
* Live Events
* Draft
* Past
* All Events
* Deleted Events
* Import

![Screenshot from 2019-11-25 13-19-25](https://user-images.githubusercontent.com/1583873/69514483-73241400-0f86-11ea-9336-c638778bdd66.png)

**Comment by AuraOfDivinity** [comment]
I'd like to take on this issue!

**Comment by mariobehling** [comment]
Please go ahead.

**Comment by ShubhamChaudharyy** [comment]
I am unable to access that page @mariobehling  sir!!

**Comment by kushthedude** [comment]
@AuraOfDivinity Since a `high priority` issue, I will be working on it, please take a look at other bugs and issues so that you may get a GIST of EventYay and its workflow. Then you are free to work upon any of the `high priority labelled` bug.
Wish to see more contributions coming from you. Thanks
