### ISSUE TITLE
Show only "Promoted to Front Page" posts on Front Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3658]
The front page sometimes shows events that are of less relevance and have incomplete information. We already show "Featured Events" on top of the page. Featured events are controlled through the admin interface. Please implement an additional button on the admin UI "Promote to Front" page at https://eventyay.com/admin/events/live to show events in the section "Upcoming Events"

![Screenshot from 2019-11-25 14-19-00](https://user-images.githubusercontent.com/1583873/69517064-9488fe00-0f8e-11ea-8501-36c1d21309c8.png)

![Screenshot from 2019-11-25 14-15-58](https://user-images.githubusercontent.com/1583873/69517071-981c8500-0f8e-11ea-865a-56d42d82ca14.png)

**Comment by Sahastracookcoder1** [comment]
I would like to work on this issue.. please

**Comment by kushthedude** [comment]
go ahead

**Comment by kushthedude** [comment]
@mariobehling As I can get from issue, We need to enable `Promote to Front Page` and those events should appear before the other events but in same `Upcoming Events Section` ?

**Comment by snitin315** [comment]
@mariobehling I am talking this issue.

**Comment by uds5501** [comment]
@maze-runnar I'd recommend you to try and collaborate with @snitin315 on this one.
One of you can finish off the backend implementation and the other can take care of frontend ones. (You can use the featured event Pull Requests as a reference)

**Comment by maze-runnar** [comment]
thanks @uds5501 , i would like to work on frontend part .

**Comment by kushthedude** [comment]
@maze-runnar Any progress on this issue?

**Comment by maze-runnar** [comment]
@kushthedude i was  pfeety much involved involved in 'my session rendering multiple time' issue . if you please take a look at their it would be great . and i will satrt work on it too. Please give me some time .

**Comment by kushthedude** [comment]
@maze-runnar @snitin315 I am taking the issue, if you guys have not done much in here .

**Comment by snitin315** [comment]
@kushthedude sure 👍
