### ISSUE TITLE
Sessions & Speakers: TimeZone issues in Speaker and Session Proposals and Session Scheduler.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3659]
TimeZone issues in Speaker and Session Proposals and Session Scheduler.

Preceded by #3582.

The FOSSASIA page shows the event starts at 4pm. The event time in the wizard is: Start 9AM. I am using a browser in Germany.

Expected: Event time should show correct local time.
![Screenshot from 2019-10-30 12-35-15](https://user-images.githubusercontent.com/1583873/67855112-1f9ee180-fb12-11e9-838d-e483ca401950.png)

Wizard time of the same event:
![Screenshot from 2019-10-30 12-38-25](https://user-images.githubusercontent.com/1583873/67855207-45c48180-fb12-11e9-8d38-b247fb4c06a4.png)

**Comment by kushthedude** [comment]
Will be taking look upon it.

**Comment by abhichou4** [comment]
I would like to work on this @kushthedude @iamareebjamal 
But when I tried adding sessions and speakers to my event, no 'Call for Speakers' is added. 

 #h3 What I did

**Comment by abhichou4** [comment]
I would like to work on this @kushthedude @iamareebjamal 
I tried reproducing the issue, but I get this error instead. I can't figure out what's wrong. 

**Steps I did**
1. `ember server` 
2. Made an event and enabled Sessions & Speakers. 

**Expected**
Sessions, Speakers, Call for events on the event page

**Error** 
![error](https://user-images.githubusercontent.com/39547012/72819408-37aa7b00-3c93-11ea-9abb-d3aa67377a13.png)

**Comment by mariobehling** [comment]
Seems it has been solved already. Closing it therefore.
