### ISSUE TITLE
Cropper resizes images before sending to server

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3663]
Event Wizard cropper resizes the image to 300px before sending to the server.

It should send original size image instead

**Comment by paras151** [comment]
Can you add some images to illustrate this issue.

**Comment by iamareebjamal** [comment]
No

**Comment by maze-runnar** [comment]
@iamareebjamal  i want to work on this .

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by kushthedude** [comment]
> It should send original size image instead

@iamareebjamal What if the user uploads a too heavy image ? Loading the webpage will result in a decade then .

**Comment by maze-runnar** [comment]
But the maximum image size is 10mb .

**Comment by kushthedude** [comment]
Cool

**Comment by iamareebjamal** [comment]
Cap the max dimensions to 3000px

**Comment by maze-runnar** [comment]
Ok

**Comment by maze-runnar** [comment]
@iamareebjamal  please take  a look at this .

**Comment by maze-runnar** [comment]
it states that If you're scaling or rotating your image, some degradation is expected and is unavoidable.
By default CroppieJS will save your cropped image at the viewport size.
For your large 1920x1080 images, your viewport size is (probably) smaller than the original image size so Croppie is reducing the pixel density of your exported images. Less pixels == less quality.

**Comment by maze-runnar** [comment]
So should i increase the value of port-size ?

**Comment by iamareebjamal** [comment]
No, the answer is wrong

**Comment by maze-runnar** [comment]
when increases port size image quality increased -
![Screenshot from 2019-12-01 21-29-25](https://user-images.githubusercontent.com/56407566/69916528-12af3e00-1482-11ea-9207-00605b0d32a2.png)
otherwise -
![Screenshot from 2019-12-01 21-32-14](https://user-images.githubusercontent.com/56407566/69916568-8cdfc280-1482-11ea-8f97-fb4a9369683b.png)

**Comment by iamareebjamal** [comment]
Paste the dimensions of the image sent to server

**Comment by iamareebjamal** [comment]
And no, viewport size won't be increased

**Comment by maze-runnar** [comment]
from the discussion https://github.com/Foliotek/Croppie/issues/438 i have tried following two methods but not working at-all .
And also "Improve cropping quality after scale down" https://github.com/Foliotek/Croppie/issues/94 in croppie is still open .

 ```
 cropImage() {
      this.$('img').croppie('result', 'base64', (3000,1500), 'jpeg', 1).then(result => {
        if (this.onImageCrop) {
          this.onImageCrop(result);
        }
      });
```
this is also not working and not this too -

```
 cropImage() {
      this.$('img').croppie('result', 'canvas' / 'rawcanvas', 'original',  'jpeg', 1).then(result => {
        if (this.onImageCrop) {
          this.onImageCrop(result);
        }
      });
```

**Comment by maze-runnar** [comment]
```
onVisible() {
    let viewport = {};
    let factor = 1000;
    const aspectRatio = this.getWithDefault('aspectRatio', [1.5, 1]);
    viewport.width = aspectRatio[0] * factor;
    viewport.height = aspectRatio[1] * factor;
    viewport.type = 'square';
    this.$('.content').css('height', '300px');
    this.$('img').croppie({
      customClass : 'croppie',
      viewport,
      boundary    : {
        height: 250
      }
    });
  },
```
for above -
![Screenshot from 2019-12-01 22-45-00](https://user-images.githubusercontent.com/56407566/69917453-4d1dd880-148c-11ea-93ab-1eba009addc6.png)

**Comment by iamareebjamal** [comment]
Send a PR and we'll see
