### ISSUE TITLE
Frontend sends is_ticketing_enabled=false even when ticketing is enabled

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3664]
Same for is_map_shown.

When creating an event, if the user enters ticket information, is_ticketing_enabled is turned to true by frontend. This toggling is redundant as there is no switch for the admin to turn off ticketing per event on the event wizard. So, either add a toggle on frontend and map it to `is_ticketing_enabled` which allows the admin to toggle ticketing on or off. Or remove this parameter from the schema in the server and let server decide if it should be on or off.

~~Similarly, the case with is_map_shown. There is no toggle for it and frontend tries to be smart about it on event creation and sets it to true if location info is added. Please don't do implicit things when there is no control over the field. This field is redundant as well. If there is location info in the server, it means that the map is to be shown. So, either remove this field from the schema or add a toggle in event wizard to show or hide the map.~~
Edit: This toggle is present on the wizard but hidden until `Enter Address` is clicked on.

Programs hiding controls and trying to be smart about it are very annoying. Every controllable field should either be editable by a human, or should be decided by server and removed from schema and not be controllable by anyone. Frontend should not try to make decisions for the server or humans

**Comment by iamareebjamal** [comment]
@kushthedude @prateekj117 Please handle this one ASAP

**Comment by kushthedude** [comment]
> should

@iamareebjamal Regarding the `ticketing_is_enabled` is decided by the admin in the settings. And for the `ticketing_is_enabled(Event Schema)` there used to be a toggle for that which was removed in this https://github.com/fossasia/open-event-frontend/issues/2482 . I think there was no corresponding server change after this issue was resolved.

**Comment by kushthedude** [comment]
So it would be better if we remove the field from schema , What you say ?

**Comment by iamareebjamal** [comment]
Yes. But removing it from schema will break frontend currently, instead it should be made read only and sent from the server depending on whether there are tickets associated with the event or not

**Comment by iamareebjamal** [comment]
Also, the toggle for show map on the page needs to be shown always to the user

**Comment by prateekj117** [comment]
We have two server PR's active for the check to be implemented on the server. [#6545](https://github.com/fossasia/open-event-server/pull/6545) and [#6555](https://github.com/fossasia/open-event-server/pull/6555).

**Comment by prateekj117** [comment]
I think it's better to remove the field altogether. It would just require a small change in frontend as well.

**Comment by iamareebjamal** [comment]
OK

**Comment by prateekj117** [comment]
@iamareebjamal Ok, taking it up.

**Comment by iamareebjamal** [comment]
You can take up the stripe auth one and continue on order API

**Comment by prateekj117** [comment]
Ok.
