### ISSUE TITLE
ReadME: Use consistent netlify badge for ReadME

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3668]
**Is your feature request related to a problem? Please describe.**
Current Netlify Badge is too much different from other badges we are using in readME. Please pick a appropriate badge of netlify from shields.io and replace the same

**Comment by ABHIJITBURMAN** [comment]
@kushthedude can i work on this issue?

**Comment by kushthedude** [comment]
@ABHIJITBURMAN As a PR is already filed by @mohitm15, I suggest you look into some another `Beginner Friendly Issue`. 
Thanks for contributing to FOSSASIA.

**Comment by snitin315** [comment]
@kushthedude  the issue seems to be inactive from a long time . I will like to take up this issue.

**Comment by kushthedude** [comment]
> @kushthedude the issue seems to be inactive from a long time . I will like to take up this issue.

Sure, Please use a badge of shields.io and you can find the project-id in current netlify-badge 👍
