### ISSUE TITLE
Wizard: Speaker's Call Field empty when editing even though field was formerly filled in - also results in error message

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3669]
In Wizard step 4 I regularly experience that the "Speaker's Call" field is empty when editing an existing Call for Speakers even though field was formerly filled in. When saving "publish" the system shows an error message. Trying to close and go to the wizard step 4 again results in the showing up of the text again (at times).

![Screenshot from 2019-11-28 11-41-16](https://user-images.githubusercontent.com/1583873/69799843-5bda6600-11d4-11ea-9e90-62f23d1a9318.png)
![Screenshot from 2019-11-28 11-40-56](https://user-images.githubusercontent.com/1583873/69799845-5c72fc80-11d4-11ea-874e-a86e011ef703.png)

**Comment by maze-runnar** [comment]
This issue is fixed now I guess. I have tested it, working fine

**Comment by iamareebjamal** [comment]
Issue was non-consistent. So will wait for @mariobehling to confirm and close
