### ISSUE TITLE
Change user loading method

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3677]
Follow this guide to change user loading method to promise/async approach:

https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md

**Comment by iamareebjamal** [comment]
sessionAuthenticated called before user is loaded is a root of most bugs in in fastboot

**Comment by ayushiitr2901** [comment]
Can I work on this issue?

**Comment by mariobehling** [comment]
Unfortunately we don't have the resources to run people through the steps to solve an issue. We have the chat channel where you can chat with others and there are sites like Stackoverflow. Please only claim an issue if you can actually work on the issue. Thanks.
