### ISSUE TITLE
Event still live even if unpublished

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3678]
If an event is published and then unpublished back into draft mode it still stays live. Compare: https://eventyay.com/e/a315169f

![Screenshot from 2019-12-01 15-46-13](https://user-images.githubusercontent.com/1583873/69915667-f85d6c00-1451-11ea-9596-173ac14c9bd9.png)

**Comment by maze-runnar** [comment]
But the user won't able to get this link after unpublishing the event any-way , only creator can get . 
I am  suggesting  that unpublishing the event option should be like that once the creator unpublish the event(before the end date) then for publishing it again he have to talk to admin .

**Comment by kushthedude** [comment]
@prateekj117 @iamareebjamal I am not able to reproduce, As soon as event is unpublished it immediately goes into the draft state and is taken away from public pages. Can you guys please verify ?

**Comment by maze-runnar** [comment]
@kushthedude  , this issue basically states that  after unpublishing the event should not be visible at this link https://eventyay.com/e/a315169f too .

**Comment by kushthedude** [comment]
I cant see the event at this link, gives out 404

**Comment by iamareebjamal** [comment]
Yup, @mariobehling it's 404

**Comment by maze-runnar** [comment]
after unpublishing only the creator of event can see that event using the link

**Comment by kushthedude** [comment]
What is the issue in that then?

**Comment by maze-runnar** [comment]
I think nothing :smile:
