### ISSUE TITLE
Switching from one profile tab to another the filled data is getting empty.

### ISSUE THREAD

**Issue by khansultan1** [fossasia/open-event-frontend#3679]
**Describe the bug**
When you filled your data in the profile section and switch from one tab to another the filled data is getting empty

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Account'
2. Click on 'Profile tab or default is profile'
3. fill the profile details
4. switch the tab to billing info 
5. click to profile again 
6. see the data is getting blank

**Expected behaviour**
the filled data should not be blank it will help the user to fill all the details at once and will save the cost of the API as well.

**Screenshots**

<img width="947" alt="screenshot-3" src="https://user-images.githubusercontent.com/6906715/69954870-6d41ac00-150d-11ea-8a5e-5ea99dd83761.png">
<img width="950" alt="screenshot 1" src="https://user-images.githubusercontent.com/6906715/69954871-6dda4280-150d-11ea-85b8-6efc2071c0ed.png">
<img width="947" alt="screenshot-2" src="https://user-images.githubusercontent.com/6906715/69954872-6dda4280-150d-11ea-9470-58777f622225.png">

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maze-runnar** [comment]
i think you are not clicking on update changes button , it's working fine for me .

**Comment by khansultan1** [comment]
yes if you click on the update button it is working but it should auto-save when I switch to the different tab. hope will give a better user experience.

**Comment by Jaideep-97** [comment]
I would like to work on this issue

**Comment by kushthedude** [comment]
We have a lot of issues right now rather than working on very fine details of UX. We can definitely come back to this once we get a stable system. 
Thanks.

**Comment by mariobehling** [comment]
For now we request the user to use the save button to ensure any changes are saved. Not considering this a bug at the moment. It could be a feature request, but is out of scope at the moment. Closing this therefore.
