### ISSUE TITLE
Remove Settings as a Service and load it only there where it is needed

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3684]
We already had a long conversation about why `settings` should not be globally injected, As it is fetched at every page where it is not needed too.

**Comment by amanbora** [comment]
I would like to work on this issue

**Comment by kushthedude** [comment]
Go ahead

**Comment by amanbora** [comment]
@kushthedude where are the services injected? I'm unable locate them

**Comment by amanbora** [comment]
@kushthedude where are the services injected? I'm unable to locate them.

**Comment by kushthedude** [comment]
Please read more about ember and it's services. You will get the answer.

**Comment by amanbora** [comment]
Ok will get on it.

**Comment by amanbora** [comment]
Ok got it, so do you want me to inject `Services` in the components required or in the `initializer`?

**Comment by amanbora** [comment]
And what actually does the `Setting Service` does?

**Comment by kushthedude** [comment]
Please explore the project more with claiming good first issues before
moving into high priority. It makes no sense if you dont know the use cases
of app and directly jump into solving a major issue.

**Comment by mariobehling** [comment]
We will take care of this in the next version of the project.
