### ISSUE TITLE
When signing up, it is possible to order 0 tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3686]
The flow is like that
1. User filled in email
2. System asked to verify email first
3. After verification, user was proceeded to the payment page, but payment didnt show up
4. User ordered 1 ticket

Result: In organizer ticket overview it shows up as Quantity 0 tickets bought.

![Screenshot from 2019-12-06 09-14-38](https://user-images.githubusercontent.com/1583873/70307194-e8a2a680-1808-11ea-9d26-28b8aff1a02e.png)

**Comment by milekag01** [comment]
@ mariobehling I would like to work on this issue.

**Comment by codedsun** [comment]
Go on

**Comment by amanbora** [comment]
Is this issue available? I would like to work on this.

**Comment by snitin315** [comment]
> Is this issue available? I would like to work on this.

Go Ahead.

**Comment by Harshmaster** [comment]
is this available ?? i would like to work on it .

**Comment by Harshmaster** [comment]
@snitin315

**Comment by amanbora** [comment]
I'm not receiving the verification mail, I'm running on localhost

**Comment by amanbora** [comment]
@Harshmaster I'm working on this issue right now, you can look into other issues :)
