### ISSUE TITLE
Tickets Organizer Page: Ticket with same ID listed 2 times

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3687]
Either there is a ticket listed twice or two tickets have the same ID. This bug appears on the organizer ticketing page.

![Screenshot from 2019-12-06 09-22-48](https://user-images.githubusercontent.com/1583873/70307881-61eec900-180a-11ea-8115-ad2cf9620721.png)

**Comment by kushthedude** [comment]
@mariobehling This behaviour is seen in `Tickets Page` and it indicates that `Order #XYZ` has two tickets associated with it and as you can see both the tickets have different `Ticket Buyer Name` .
Also, two tickets have the same order ID hence they are listed as-is.

cc: @iamareebjamal Please verify and close the issue.

**Comment by iamareebjamal** [comment]
Yes, this is Order ID, not Ticket ID
