### ISSUE TITLE
Order Dashboard: Removing Billing Info if not filled from the Order Dashboard

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3689]
**Describe the bug**

`Order Dashboard` still shows the section for `Billing Info` even if it's not required. Please amend it with the latest behaviour.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a paid order without filling billing info
2. See the order
3. See error

**Expected behaviour**

The section should be not shown.

**Screenshots**

<img width="767" alt="Screenshot 2019-12-06 at 10 45 28 PM" src="https://user-images.githubusercontent.com/44091822/70341970-21c72f00-187a-11ea-85b5-2cbd8b976447.png">

**Comment by maze-runnar** [comment]
@kushthedude i want to work on this .

**Comment by kushthedude** [comment]
Go ahead
