### ISSUE TITLE
Buying Ticket with Credit Card with insufficient funds yields "Unexpected Error"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3691]
When a user buys a ticket with insufficient funds on their credit card, the error message that comes up is "Unexpected Error". Instead the correct error should appear. Please implement the correct error messages of failed stripe payments.

**Comment by kushthedude** [comment]
@iamareebjamal What should be the different error cases, As for every failed payment we here on frontend shows the `Unexpected Error` rather than the actual `Error Description` from the server .

**Comment by iamareebjamal** [comment]
Then show the error description from server

**Comment by codedsun** [comment]
How can I reproduce this issue ?
