### ISSUE TITLE
Pagination is broken in Message list of Admin panel

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#3693]
**Describe the bug**
The pagination is currently broken for the messages section in admin panel. The website says it's showing all the items but the API returns only 20 items and per single hit, if no filters(page[size], page[number]) are given.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Messages section in the admin panel

**Expected behavior**
It should work properly

**Screenshots**

![](https://user-images.githubusercontent.com/20026440/70394816-891de400-1a1e-11ea-8e75-4134d0faf1b8.png)

**Additional context**

**Comment by kushthedude** [comment]
Please provide Screenshots while reporting the issues.

**Comment by codedsun** [comment]
@kushthedude Ok, but you can reproduce the behavior by going to that section.

**Comment by kushthedude** [comment]
I am Afk, thats why asked for a gif or image illustration.

**Comment by codedsun** [comment]
@kushthedude have added when you commented to do so. Thanks

**Comment by maze-runnar** [comment]
fixed https://github.com/fossasia/open-event-frontend/pull/6254
