### ISSUE TITLE
Add workbox caching and cache settings for 15 minutes

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3699]
https://developers.google.com/web/tools/workbox/

Settings is fetched again and again even when it changes rarely. Cache settings for 15 minutes using workbox. Invalidate the cache on auth changes

**Comment by kushthedude** [comment]
@iamareebjamal Shouldn't removing setting as a service fix this ? We will load settings only where it's used ? Or if we use workbox then there is no need to remove setting as a service since the it will be fetched from the cache ?

**Comment by iamareebjamal** [comment]
Both options work. Why not do both

**Comment by iamareebjamal** [comment]
Settings and other stuff is now cached using a manual cache, but it is cumbersome to maintain and doesn't work on all stuff like events, so please use conditional workbox cache for any request with public=true and cache=true. Use stale while revalidate

Cache HTML, CSS and JS with common recipes as well

**Comment by shlokjjw** [comment]
Is this issue still open?

**Comment by cweitat** [comment]
Caching done by Cloudflare, need not double caching
