### ISSUE TITLE
My Sessions: Shows past sessions in unscheduled session of past event in tab "Upcoming"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3702]
My Sessions: Shows past sessions in unscheduled session of past event in tab "Upcoming"
The private link is at https://eventyay.com/my-sessions/upcoming.
Furthermore the sessions shows up 4 x times.

EXPECTED: Even though the session is unscheduled, the system should take the time of the overall event. If the event is past the unscheduled session should also show up in the "past tab".

![Screenshot from 2019-12-15 18-30-13](https://user-images.githubusercontent.com/1583873/70866393-64b78f80-1f69-11ea-8ee4-bde168726c05.png)

**Comment by kushthedude** [comment]
@mariobehling What about having a tab for `Unscheduled`, It would make more sense as showing sessions with time & date = null in upcoming and past doesn't seem nice ?

**Comment by maze-runnar** [comment]
@kushthedude while working on my-session showing multiple times issue , i solved this . Can i open a PR for it ,
Implementation is as @mariobehling has said.when session is unscheduled, the system should take the time of the overall event. If event is past , session is also past.

**Comment by kushthedude** [comment]
Sure

**Comment by kushthedude** [comment]
Remember dont use an conditional in template, query should not return those
sessions .

**Comment by maze-runnar** [comment]
ok, i will keep that in mind .

**Comment by maze-runnar** [comment]
actually making changes in `open-event-frontend/app/routes/my-sessions/list.js`  .
