### ISSUE TITLE
Remove/Replace abandoned add-ons getting used in our repository.

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3704]
Currently, There are many abandoned add-ons getting used in our app.

Some of which are causing trouble while reading the `browser logs` due to the depreciated usage of codes.

There are other alternatives easily available for such addons.
Some of the abandoned add-ons are : ember-g-map, ember-cli-geo

This need not be done immediately but will be a longterm benefit.

**Comment by mariobehling** [comment]
Thanks! A number of add-ons have been removed. If there are any specific add-ons left over, please open a dedicated issue.
