### ISSUE TITLE
Add Session: "end of sentence.\nStart of sentence" converted to <sentence.Start> link

### ISSUE THREAD

**Issue by juhp** [fossasia/open-event-frontend#3706]
**Describe the bug**
When submitting a session newlines are stripped and this can result in `some.word` links getting created...

**To Reproduce**
Steps to reproduce the behaviour:
1. CFP -> Submit Proposal -> Add Session
2. Enter Short Abstract with sentences split with a newline:

```
Here is my abstract.
It will be an interesting talk.
```

3. Press Submit
4. In the browser the text is reformatted into a single paragraph sentence with a link [abstract.It](abstract.It).

**Expected behaviour**
Newlines should be replaced with a space (or not stripped).

`Here is my abstract. It will be an interesting talk.`

**Screenshots**
Sorry didn't take screenshot but I think this is quite easy to reproduce.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: firefox
 - Version: 71.0

**Additional context**
I worked around it by just re-editing the text...

**Comment by kushthedude** [comment]
Hello @juhp , Actually this is expected behaviour as some short abstract can contain multiple paragraphs which will be easy to read for the organiser. You can always strip the newline by adding the space in the text editor.
If you need any more support, please feel free to ping us. 
Thank You
