### ISSUE TITLE
Tax not added or calculated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3710]
There is an option to add tax on top or include it in the ticket price. The option is no longer working in wizard step 1.

I added the tax in the ticket price manually: https://eventyay.com/e/fb25b5fd

Details can be added in wizard step 1.
![Screenshot from 2019-12-21 01-12-18](https://user-images.githubusercontent.com/1583873/71299775-94163400-238f-11ea-8ba1-ccb31d89a809.png)

No tax is added or visible in the order form.
![Screenshot from 2019-12-21 01-16-08](https://user-images.githubusercontent.com/1583873/71299765-852f8180-238f-11ea-8b6f-ec270b685d1c.png)

**Comment by kushthedude** [comment]
@mariobehling Did you add tax through `Editing the event` after the event was created ?

**Comment by maze-runnar** [comment]
![Screenshot from 2019-12-21 18-57-14](https://user-images.githubusercontent.com/56407566/71308526-c1acbd00-2423-11ea-9473-1b3233ccfb14.png)
aftr saving and publishing once , when i again come to wizard page then tax info (previosly saved) is not visible

**Comment by maze-runnar** [comment]
![Screenshot from 2019-12-21 20-54-02](https://user-images.githubusercontent.com/56407566/71309957-35ef5c80-2434-11ea-9f83-d7e0d9823c85.png)
@mariobehling @kushthedude  i think it's not calculating , it's showing  always value "0" for
`{{format-number (sub ticket.ticketPriceWithTax ticket.price)}}`

**Comment by kushthedude** [comment]
> ![Screenshot from 2019-12-21 20-54-02](https://user-images.githubusercontent.com/56407566/71309957-35ef5c80-2434-11ea-9f83-d7e0d9823c85.png)
> @mariobehling @kushthedude i think it's not calculating , it's showing always value "0" for
> `{{format-number (sub ticket.ticketPriceWithTax ticket.price)}}`

This screenshot is for a different case, Although the issue is when you enable taxing while editing it does not work.

**Comment by maze-runnar** [comment]
@kushthedude , if we are adding the tax info at the time of creating an event then , we can later edit it succesfully but can't add any kind of tax info later. This is happening here exactly. can there be a problem in tax-modal or editing implementation?

**Comment by iamareebjamal** [comment]
Fixed
