### ISSUE TITLE
Sales Dashboard: Tax & Statuses of order not changing

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3711]
**Describe the bug**

Tax & Statuses of order not changing in the `Event Sales Dashboard`

**To Reproduce**

Steps to reproduce the behaviour:

1. Make any Placed Order
2. Convert it into Completed
3. See the Sales Dashboard

**Expected behaviour**

Correct changes and updated amounts must be shown.

**Screenshots**

<img width="1080" alt="Screenshot 2019-12-21 at 8 47 14 AM" src="https://user-images.githubusercontent.com/44091822/71302220-b5e2db80-23ce-11ea-8e35-1aea4a884b96.png">

**Comment by Gaurav-Punjabi** [comment]
Can I work on this issue?

**Comment by kushthedude** [comment]
Go ahead

**Comment by snitin315** [comment]
@Gaurav-Punjabi are you working on this issue? If not can I take up this issue?

**Comment by maze-runnar** [comment]
@kushthedude on ordering ticket it showing expired :confused: everytime
![Screenshot from 2019-12-30 22-33-52](https://user-images.githubusercontent.com/56407566/71592060-c1639e80-2b54-11ea-9340-64c536e75185.png)

**Comment by kushthedude** [comment]
> @kushthedude on ordering ticket it showing expired 😕 everytime
> ![Screenshot from 2019-12-30 22-33-52](https://user-images.githubusercontent.com/56407566/71592060-c1639e80-2b54-11ea-9340-64c536e75185.png)

@maze-runnar Can you please elaborate a little ?

**Comment by maze-runnar** [comment]
@kushthedude ordering a ticket for any event, it is directly showing expired . I think it's broken . I was trying to look at the above issue when i faced this issue .

**Comment by kushthedude** [comment]
Open the issue on server with priority and also attach the stacktrace and
error shown in network tab.

**Comment by maze-runnar** [comment]
@kushthedude it's working fine i think , 
First i make a complete order then the dashboard looks like -
![Screenshot from 2020-01-01 18-55-33](https://user-images.githubusercontent.com/56407566/71641895-d6613e80-2cc8-11ea-8652-3747267243e4.png)
then i cancelled the order and dashboard also updates values -
![Screenshot from 2020-01-01 18-59-36](https://user-images.githubusercontent.com/56407566/71641904-f2fd7680-2cc8-11ea-96c0-489155181396.png)
Just needed a page refresh : The values in first table updates automatically without refresh (going back after ticket cancellation),but second table value updates on page refresh

**Comment by maze-runnar** [comment]
If you are talking about different case , please let me know

**Comment by maze-runnar** [comment]
@kushthedude , please clear my doubts here ! So i would know it is valid to work or not. As i am not able to reproduce. https://github.com/fossasia/open-event-frontend/issues/3711#issuecomment-570053653

**Comment by maze-runnar** [comment]
@kushthedude i want to work on this, please take a look here too.

**Comment by iamareebjamal** [comment]
Working fine as mentioned above
