### ISSUE TITLE
Upgrade to octane and convert to glimmer components

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3714]
Use https://github.com/ember-cli/ember-cli-update and codemods to update to latest version of ember, changing to octane mode and new template syntax (glimmer) as well

- [x] Upgrade to Ember 3.15.2
- [ ] Convert to Glimmer Components

**Comment by kushthedude** [comment]
That will require a lot of changes, I suggest this change after we have overcome the `Priority: high` issues. Also, We have not also completed our migration to 3.10, As there is still depreciated code style and ES5 syntax in the app. Also, not to mention the abandoned packages which are still present in app too.
Hence labelling it as `later`.

**Comment by iamareebjamal** [comment]
In history of everything, there has never been a time in the timeline of a software project where all high priority bugs were solved. Neither is this long term, nor for later. Anyone who wants to upgrade it can do it. Yes, it will take a lot of code changes, does it matter?

**Comment by kushthedude** [comment]
Atleast we must complete the migration and remove the depreciations of code
style which were introduced in ember 3.10 and ES6 .

**Comment by iamareebjamal** [comment]
Will be automatically done through codemods

**Comment by codedsun** [comment]
@iamareebjamal I am new, is it for begginers?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
@kushthedude This is not something to be done in long term. It is to be done ASAP to start using octane and to evaluate the use of ember. If you don't want to do it, fine. But please, don't change the priority.

**Comment by kushthedude** [comment]
I just changed it to important for long-term, not to be done later.

**Comment by maze-runnar** [comment]
We have done this at almost every place. So it is kind of complete
