### ISSUE TITLE
Order Summary: There is no definition for `Pending` and `Cancelled` Orders

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3717]
**Describe the bug**

Order Summary: There is no definition for `Pending` and `Cancelled` Orders

**To Reproduce**

Steps to reproduce the behaviour:

1. Create any `Pending` or `Cancelled Order`
2. See the dashboard of order

**Expected behaviour**

Have the values for `Pending` & `Cancelled` orders with proper definitions.

**Screenshots**

<img width="1362" alt="Screenshot 2019-12-07 at 5 12 50 PM" src="https://user-images.githubusercontent.com/44091822/71335013-8ebf1200-2566-11ea-933b-eaa61f4479bf.png">

The above order is cancelled getting shown as **PLACED**

**Comment by maze-runnar** [comment]
@kushthedude i can see the definition for pending if it's same you want to say .
![Screenshot from 2019-12-23 21-45-04](https://user-images.githubusercontent.com/56407566/71368281-8bab3c80-25cd-11ea-9f51-5c3026ac7361.png)
