### ISSUE TITLE
Make the table of switches center aligned for mobile on /edit/sessions-speakers

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#372]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://user-images.githubusercontent.com/17252805/27613354-bd036014-5bb8-11e7-9185-5667fda92414.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/17252805/27613368-d1edcc6c-5bb8-11e7-9eac-f6bae0041c32.png)

**Comment by CosmicCoder96** [comment]
@niranjan94 Also, I am proposing this, 
![image](https://user-images.githubusercontent.com/17252805/27613080-3902cee0-5bb7-11e7-97ff-33552df31a46.png)
It makes more clear to the user this way  by adding labels at each row (for mobile only) 
And I will be converting the inputs into checkboxes, if I shouldn't be doing any of those above two things, please let me know, else I will be proceeding with these.

**Comment by geekyd** [comment]
> It makes more clear to the user this way by adding labels at each row (for mobile only)

Can you please elaborate?

**Comment by geekyd** [comment]
> It makes more clear to the user this way by adding labels at each row (for mobile only)

This will be good!
