### ISSUE TITLE
Session Speaker Form: `Sponsorship Required` should be a checkbox field

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3725]
**Describe the bug**

`Sponsorship Required` should be a drop-down field rather than `Text Input`.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'CFS Form'
2. Click on 'Sponsorship Required`
3. See error

**Expected behaviour**

`Sponsorship Required` should be a drop-down field with option:
- Yes
- No

**Screenshots**

![image](https://user-images.githubusercontent.com/44091822/71450171-601d8300-2782-11ea-9fa7-d685abe43714.png)

**Comment by kushthedude** [comment]
@iamareebjamal Does the options: `Yes or No` are suffice?

**Comment by iamareebjamal** [comment]
Should be a checkbox

**Comment by kushthedude** [comment]
Cool.

**Comment by kushthedude** [comment]
@maze-runnar Want to try this, It might be a good issue for getting in a bit depth of the `Open-Event`

**Comment by maze-runnar** [comment]
thanks @kushthedude ,  i want to try this .

**Comment by maze-runnar** [comment]
@kushthedude i am getting trouble in finding file for    **allFields.speaker** 
`{{#each allFields.speaker as |field|}}`     in  app/templates/components/forms/session-speaker-form.hbs
please help me with this .

**Comment by maze-runnar** [comment]
![Screenshot from 2019-12-27 20-38-52](https://user-images.githubusercontent.com/56407566/71521994-efdd4180-28e8-11ea-84da-f3848c6e4316.png)
after this what i should do next  regarding action ?

**Comment by mariobehling** [comment]
I think for now we can give the people the option to fill in details what they require. Therefore closing this.
