### ISSUE TITLE
Author name missing after proposal submission

### ISSUE THREAD

**Issue by Shaurya1234** [fossasia/open-event-frontend#3730]
**Describe the bug**
Initially, I could see my name as author after submission of proposal and the proposal was also in my session list. But due to unknown reason the proposal has been removed from my session.
On some investigation i found that the author name is missing in the session.

**Expected behaviour**

![image](https://user-images.githubusercontent.com/24893975/71539326-adefe200-2960-11ea-844c-3c89005ec67d.png)
This is one of the other proposals. My name is clearly visible

**Screenshots**

![image](https://user-images.githubusercontent.com/24893975/71539332-da0b6300-2960-11ea-9213-406275f311fa.png)
Here it can be seen the author name is missing and hence this proposal is also missing from 'My Session.'

**Desktop (please complete the following information):**
 - OS: [ Ubuntu]
 - Browser [chrome]

**Comment by kushthedude** [comment]
@Shaurya1234 Can you share the `edit speaker` and `edit session`, and check if all details are filled up or not? Please hide any sensitive info before sharing.

**Comment by Shaurya1234** [comment]
Hi @kushthedude , as you can see edit speaker option is not available. Also as you can see my name from the session speaker is missing as i have mentioned earlier. Edit session button is available(1st screenshot) and all the details are there (2nd screenshot).
![image](https://user-images.githubusercontent.com/24893975/71543002-c5948e00-2993-11ea-979d-18ae0cf56532.png)


![image](https://user-images.githubusercontent.com/24893975/71543007-d5ac6d80-2993-11ea-99c6-2b70c70680e2.png)

**Comment by kushthedude** [comment]
@Shaurya1234 Please try once again, I hope the following issue has been solved with recent bug fixtures related to CFS.
Please feel free to ping us if by any chance you face it again
