### ISSUE TITLE
Unable to submit call for proposal Open Tech Summit Day Thailand

### ISSUE THREAD

**Issue by Shaurya1234** [fossasia/open-event-frontend#3731]
**Describe the bug**
On submission of proposal an error pops up 'Oops something went wrong.' On further analysis, i found the POST Request to API https://api.eventyay.com/v1/sessions returned a 422 response.
As per HTTP, 422 Unprocessable Entity response status code indicates that the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions.
Please see the screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/b97c6882/cfs'
2. Click on 'Submit Proposal'. Speaker profile should be completed previously
3. Fill relevant details
4. On Submit, error pops up Oops something went wrong

**Expected behaviour**
Should be able to successfully submit the proposal

**Screenshots**

![image](https://user-images.githubusercontent.com/24893975/71539535-82bac200-2963-11ea-910c-33f66849d0b1.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu (Linux OS)]
 - Browser [chrome]

**Comment by kushthedude** [comment]
@Shaurya1234 Thanks for reporting this.
