### ISSUE TITLE
Event Creation: Call for Speaker is Broken

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3733]
**Describe the bug**

Call for Speaker is Broken.

**To Reproduce**

Steps to reproduce the behaviour:

- Create a Event.
- Fill up CFS with custom fields.
- Try to submit and see `undefined e.error` on console.

**Expected behaviour**

Fix up the CFS before the new release with hotfix for #3731

**Comment by iamareebjamal** [comment]
Is this now fixed?

**Comment by kushthedude** [comment]
Nope, It is caused because of migration of Session form to ES6 but I forgot
to migrate the Mixins before it. I will fix it by evening and we can make a
release tonight.
