### ISSUE TITLE
Add social media icon

### ISSUE THREAD

**Issue by Rishi007-web** [fossasia/open-event-frontend#3744]
Add a social media icon in the side navbar or in the navbar which helps new visitors to access Github profile easily and others as well.
Now, all social media links in the footer section. So, all new visitors cannot see social media profiles.
If we will make it on the top, it helps new visitors and it also good for this project as well.

I would like to work on this issue.

**Comment by kushthedude** [comment]
Social Media Profiles should be in footer only
