### ISSUE TITLE
Update the name of Allahabad

### ISSUE THREAD

**Issue by Dishebh** [fossasia/open-event-frontend#3747]
**Describe the bug**

Change the name of Allahabad to Prayagraj
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [website](https://eventyay.com)
3. Scroll down to the footer section.
4. See bug under the location column  

**Screenshots**

![Screenshot from 2019-12-30 13-53-17](https://user-images.githubusercontent.com/43489708/71573823-c51f0300-2b0b-11ea-8397-14459ae83d0f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by kushthedude** [comment]
It is based on user filled location.
