### ISSUE TITLE
Nearby events in footer is not working

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3751]
Nearby events in footer is not working .

**proposed change**
remove this section from the footer for the time 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
i want to work on this .

**Comment by kushthedude** [comment]
It is working, See on eventyay.com

**Comment by maze-runnar** [comment]
@kushthedude it's not working on eventyay too https://www.youtube.com/watch?v=_e24N7OXXyU

**Comment by kushthedude** [comment]
Oh sorry, A issue is already opened for this.

**Comment by maze-runnar** [comment]
@kushthedude the issue that is opened is #2232 , I saw there a huge discussion over this . So this section should be removed for the time from footer or not ?
