### ISSUE TITLE
Submitted sessions/proposals are missing under eventyay my sessions

### ISSUE THREAD

**Issue by dilum1995** [fossasia/open-event-frontend#3767]
**Describe the bug**

Some of the submitted sessions(pending state) are missing once navigated to the My Sessions --> upcoming sessions. 

I submitted 3 sessions/talk proposals for FOSSASIA Summit 2020 and all three were displaying in the My Sessions --> upcoming sessions as pending sessions. After this evening it only shows one session in My Sessions. **Two of the sessions which were there previously are missing now.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/my-sessions/upcoming'

**Screenshots**

<img width="1680" alt="Screen Shot 2020-01-05 at 2 41 56 AM" src="https://user-images.githubusercontent.com/23298579/71772079-062f7100-2f6b-11ea-892d-de2f63befeee.png">

**Expected behaviour**

It should display all the sessions that I submitted under My Sessions.

**Additional context**

I did not perform any delete/remove operation for my sessions before this issue occurs.
The last operation I performed in the eventyay platform is **edit speaker** operation for a particular session.

**Comment by kushthedude** [comment]
@dilum1995 Can you please check if the sessions were actually submitted? 
- Go to event page->Call For Speaker-> Your Submitted Sessions will be listed over there.

**Comment by dilum1995** [comment]
@kushthedude,

Yes, I checked previously and all three sessions were there.

But yesterday it was only one session displaying here --> **event page->Call For Speaker-> Your Submitted Sessions**.

Today after clearing my cache and hard reloading. It is displaying two events now but still one is missing.

<img width="1680" alt="Screen Shot 2020-01-05 at 11 48 42 PM" src="https://user-images.githubusercontent.com/23298579/71784157-3e3fbe00-3016-11ea-83c4-76cf5d08744a.png">

**Comment by dilum1995** [comment]
@kushthedude 

Here's a screenshot of Event --> Call for speakers FYR

<img width="1680" alt="Screen Shot 2020-01-06 at 12 05 40 AM" src="https://user-images.githubusercontent.com/23298579/71784310-59abc880-3018-11ea-8da5-e93ff394d6d3.png">

**Comment by kushthedude** [comment]
Hey @dilum1995 , I tried making multiple sessions for different events but I was not able to replicate any error of this kind.
The sessions which were visible on `Event -> CFS` were only getting shown at My Sessions.
I suggest you to please try re-submitting the session and if you encounter any error, Please follow-up here.
Thanks.
