### ISSUE TITLE
Error in uploading user profile image

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#3769]
**Describe the bug**
The image upload for user is not working on eventyay.com as well on dev branch

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to account section
2. Upload a `jpeg` image
First time the error is shown, file not supported.
Repeat the process, the error is not shown and you can click on save changes 

**Expected behaviour**
The error should be shown again if I am uploading the jpeg image

**Additional context**
@kushthedude @maze-runnar - Please verify

**Comment by kushthedude** [comment]
Does the error also occur on updating the profile pic too? If yes, can you
please retry and share the error message?

**Comment by maze-runnar** [comment]
@codedsun @kushthedude please take a look at this - https://youtu.be/G2k3jGE2pew
It's working fine .

**Comment by codedsun** [comment]
@kushthedude @maze-runnar In this video your jpeg image is accepted, see this

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20026440/71783936-a93bc580-3013-11ea-95f4-e971ec49b8e2.gif)

**Comment by maze-runnar** [comment]
@codedsun  is right , for some jpeg images it's showing error message "File type not supported".

**Comment by maze-runnar** [comment]
![Screenshot from 2020-01-06 00-09-30](https://user-images.githubusercontent.com/56407566/71784374-f4a4a280-3018-11ea-892d-3839122672f5.png)

**Comment by codedsun** [comment]
@maze-runnar Also, for that image repeat the same process to upload, the error message is also not coming up

**Comment by kushthedude** [comment]
@maze-runnar @codedsun Can you please upload the jpeg not getting accepted or send me on gitter ?

**Comment by maze-runnar** [comment]
@kushthedude i have tried for this `Jpeg` image 
![rdj](https://user-images.githubusercontent.com/56407566/71792682-aff02a00-305f-11ea-8f79-fa5051ba307a.jpeg)

**Comment by maze-runnar** [comment]
> @maze-runnar Also, for that image repeat the same process to upload, the error message is also not coming up

yes, the error message is not coming up and image is also not uploading .
