### ISSUE TITLE
Speaker submission/Session submission - same form areas differ: Implement abstraction layer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3775]
![Screenshot from 2020-01-08 18-42-11](https://user-images.githubusercontent.com/1583873/71980654-9f4dd880-3246-11ea-88aa-5907f50d29fe.png)

The form "add a session" has the option to expand it below and add speaker details as well. The form "add a speaker" has the option to add session details below. These exact same features are implemented differently. Code is duplicate and the forms don't behave in the same way.

Expected: Forms should be identical as it is the exact same feature. Please implement an abstraction layer and ensure form elements are always the same.

**Comment by Bhanu-mbvg** [comment]
Hey, can I work on this issue?
