### ISSUE TITLE
Organizer cannot add more than one anonymous speaker or even submit a session for own name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3776]
If an organizer tries to create a session or speaker without an email or using his/her own email the submission form simply shows "error". It is not possible to submit a session actually.

![Screenshot from 2020-01-08 18-42-11](https://user-images.githubusercontent.com/1583873/71981510-8f36f880-3248-11ea-8893-6dac62c95f3e.png)

**Comment by kushthedude** [comment]
It should have been solved with the new release.
Please re-open if still exists on production.
