### ISSUE TITLE
Organizer Edit Speakers Form: Fields Missing and Fields are randomized

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3777]
If an organizer tries to edit the speakers form, some fields are missing, e.g. the speakers profile. Also form elements are randomized and listed in a chaotic way.

![Screenshot from 2020-01-08 19-00-12](https://user-images.githubusercontent.com/1583873/71981794-1d12e380-3249-11ea-9eda-89e8e1070ac7.png)

**Comment by mariobehling** [comment]
Here is a proposed order for the speaker form:

- Name
- Email
- Position
- Organisation
- Address
- City		
- Country
- Mobile	number	
- Gender
- Short Biography
- Long Biography
- Speaking Experience
- Photo
- Website
- GitHub
- Facebook	
- Instagram
- Linkedin
- Twitter
- Heard From
- Sponsorship Required

**Comment by iamareebjamal** [comment]
More discussion in #3585 and #3778

**Comment by mariobehling** [comment]
Here is the proposed order for the session form:

- Title
- Subtitle		
- Track		
- Session Type
- Short Abstract	
- Long Abstract	
- Language	
- Level		
- Slides		
- Audio
- Video
- Comments

Please note it should be:
* Comments, not "Comment"
* Slides, not "Slide".
