### ISSUE TITLE
Speaker Form: Profile and other form elements disappear when editing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3778]
When a speaker tries to edit the speaker profile form, form elements disappear and the form is chaotically ordered. Disappearing form element is for example "speakers bio".

E.g. tried to do it in the CFS of India Delhiday. https://eventyay.com/e/423d0650/cfs

**Comment by kushthedude** [comment]
@iamareebjamal When can we introduce the indexing of fields as there are no record of order of fields in db ?

**Comment by iamareebjamal** [comment]
As I asked previously in an older issue, first it needs to be defined that what should be the order of the fields?, and then how should existing fields be treated. Everything else can only be done afterwards.

**Comment by kushthedude** [comment]
> As I asked previously in an older issue, first it needs to be defined that what should be the order of the fields?, and then how should existing fields be treated. Everything else can only be done afterwards.

These should be the orders - 
**For Session Form**
<img width="219" alt="Screenshot 2020-01-09 at 2 17 02 AM" src="https://user-images.githubusercontent.com/44091822/72014603-32f2c980-3286-11ea-9740-8d64ff65cb05.png">

**For Speaker Form**
<img width="266" alt="Screenshot 2020-01-09 at 2 17 11 AM" src="https://user-images.githubusercontent.com/44091822/72014628-3f772200-3286-11ea-9a8c-90e87a1ac452.png">
Linkedin & Instagram after GitHub ID.

**Comment by iamareebjamal** [comment]
OK, then why can't they be sorted on frontend if there does not need to be a dynamic order?

**Comment by kushthedude** [comment]
Yes, this can be done making a property for orders

**Comment by kushthedude** [comment]
@mariobehling Can you please check again the missing fields issue ? IMO it was solved a week ago in https://github.com/fossasia/open-event-frontend/pull/3759

**Comment by iamareebjamal** [comment]
More discussion in #3585 and #3777
