### ISSUE TITLE
Add modal for create Page in admin/content/pages (UI only)

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#378]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/27694099-d09f07c6-5d08-11e7-9272-35a5a618b889.png)

**Comment by niranjan94** [comment]
No modal needed for this. We will use the existing form.
