### ISSUE TITLE
Attendee Form: Make country as a dropdown

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3780]
**Describe the bug**

Currently, Country Dropdown is unavailable in Attendee Form and is a text field.

**Expected behaviour**

Make appropriate changes and convert it into the dropdown with flags.

**Comment by snitin315** [comment]
Can you point to the corresponding file?

**Comment by kushthedude** [comment]
You will find the form in templates.

**Comment by SARTHAK1SINGH** [comment]
@kushthedude i would like to work on this issue. could you please assign me this.

**Comment by kushthedude** [comment]
We dont work here with assignment, if you want to work drop in a comment.
Mentor will give you the green sign if there is no one else working on it
already or has abondoned it.

**Comment by SARTHAK1SINGH** [comment]
@snitin315  Are you still working on it or i give it a try.

**Comment by snitin315** [comment]
> @snitin315 Are you still working on it or i give it a try.

You can work on this issue

**Comment by kushthedude** [comment]
> Can you point to the corresponding file?

@snitin315 @SARTHAK1SINGH The actual file to be changed is here
https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/forms/orders/order-form.hbs

**Comment by snitin315** [comment]
@kushthedude I encountered something strange which I wasn't able to figure out while solving the issue ,

## Case 1: 
 When I added the `country dropdown` inside the `gender if block` the country field was broken. following are some respective screenshots -
**Code**
![Screenshot from 2020-01-12 19-23-37](https://user-images.githubusercontent.com/46647141/72219899-21a10a00-3571-11ea-9230-e0afd39d791f.png)
**broken country field(rendering both text and dropdown)**
![Screenshot from 2020-01-12 19-17-05](https://user-images.githubusercontent.com/46647141/72219878-ee5e7b00-3570-11ea-93b2-5782f49666c2.png)
**Also the gender field value was not saved like this issue(#3307 )**
![Screenshot from 2020-01-12 19-17-33](https://user-images.githubusercontent.com/46647141/72219881-f0283e80-3570-11ea-8862-1f0fceb97793.png)

## Case 2:
 When I added the `country dropdown` inside the `field.isLongText if block` the country field was not broken but the the gender field value was not saved like this issue(#3307 ). Respective screenshots -
**Code**
![Screenshot from 2020-01-12 19-31-20](https://user-images.githubusercontent.com/46647141/72220043-ab050c00-3572-11ea-9f1e-0b7d340394c0.png)
**Country Dropdown**
![Screenshot from 2020-01-12 19-34-33](https://user-images.githubusercontent.com/46647141/72220045-afc9c000-3572-11ea-81c0-138ec1cfeea0.png)
**Empty gender field(Male was selected)**
![Screenshot from 2020-01-12 19-34-51](https://user-images.githubusercontent.com/46647141/72220050-b35d4700-3572-11ea-8abc-7bf77212cd05.png)

## Case 3:
When I added both `country dropdown` and `gender dropdown` inside the `field.isLongText if block` .
Gender field got broken
Respective screenshots -
**Code**
![Screenshot from 2020-01-12 19-41-44](https://user-images.githubusercontent.com/46647141/72220155-ccb2c300-3573-11ea-925e-19059e37511a.png)
**Broken Gender Field**
![Screenshot from 2020-01-12 19-42-53](https://user-images.githubusercontent.com/46647141/72220156-d1777700-3573-11ea-944d-2615089dc956.png)

## However everything worked out correctly in CASE 3 with one additioal change of `params[0] === 'select'` in  `is-input-field.js` : 

![Screenshot from 2020-01-12 19-47-28](https://user-images.githubusercontent.com/46647141/72220237-a9d4de80-3574-11ea-81b1-1c18474536af.png)

![Screenshot from 2020-01-12 19-48-59](https://user-images.githubusercontent.com/46647141/72220239-ab9ea200-3574-11ea-93f5-6aa2c9368c03.png)

![Screenshot from 2020-01-12 19-50-42](https://user-images.githubusercontent.com/46647141/72220264-e0125e00-3574-11ea-9f8a-ff99925c56f3.png)

**But I am afraid that this addition change in `is-input-field.js` will broke gender field in other forms. Which I haven't yet tested**

**Comment by kushthedude** [comment]
Check how the country field dropdown is implemented in Speaker-Session Form. You will get a GIST of what you need to do here.

> When I added both `country dropdown` and `gender dropdown` inside the `field.isLongText if block` .

Makes no sense, None of them is Long Text field.


> When I added the `country dropdown` inside the `field.isLongText if block` the country field was not broken but the the gender field value was not saved like this issue

Again makes no sense reason above.



> When I added the `country dropdown` inside the `gender if block` the country field was broken. following are some respective screenshots -

Is country == gender ?

**Comment by maze-runnar** [comment]
> @kushthedude I encountered something strange which I wasn't able to figure out while solving the issue ,
> 
> ## Case 1:
> When I added the `country dropdown` inside the `gender if block` the country field was broken. following are some respective screenshots -
> **Code**
> ![Screenshot from 2020-01-12 19-23-37](https://user-images.githubusercontent.com/46647141/72219899-21a10a00-3571-11ea-9230-e0afd39d791f.png)
> **broken country field(rendering both text and dropdown)**
> ![Screenshot from 2020-01-12 19-17-05](https://user-images.githubusercontent.com/46647141/72219878-ee5e7b00-3570-11ea-93b2-5782f49666c2.png)
> **Also the gender field value was not saved like this issue(#3307 )**
> ![Screenshot from 2020-01-12 19-17-33](https://user-images.githubusercontent.com/46647141/72219881-f0283e80-3570-11ea-8862-1f0fceb97793.png)

@kushthedude @snitin315 i think the gender field implementation is wrong in the attendee form, i have worked recently with speaker form so i figure out some differences:
- `{{input type="hidden" id=(if field.isRequired (concat 'speaker_' field.fieldIdentifier '_required') (concat 'speaker_' field.fieldIdentifier)) value=data.speaker.gender}}` this line is missing in attendee form for both gender and country.

- in` {{#ui-dropdown class='search selection' selected=data.speaker.gender onChange=(action (mut data.speaker.gender)) as |execute mapper|}} ` there is no attribute is like `name` or `id` that's why validation won't work for gender field.
- @snitin315 country field is rendering twice as there is no block like :
             `{{#if (eq field.type 'select')}}
                {{/if}}`

**Comment by kushthedude** [comment]
Country is rendering single time only in attendee?
Regarding the point of validation you mentioned, yes that's correct it should be done correctly as you did recently

**Comment by maze-runnar** [comment]
> Country is rendering single time only in attendee?
@kushthedude in my opinion ,as there is not any `{{#if (eq field.type 'select')}} {{/if}} block`  and as country field was previosly rendering as text , by adding drop-down we don't remove the existing text-field rendering for country. We are just adding a new drop-down so it is rendering both, drop-down and text field.

**Comment by kushthedude** [comment]
Once you make country a dropdown, it wont be regarded as a text field. Hence no issue of double rendering

**Comment by maze-runnar** [comment]
@kushthedude  on making country a required field it's not even rendering.
![Screenshot from 2020-01-15 12-44-33](https://user-images.githubusercontent.com/56407566/72413034-df581280-3794-11ea-8f89-17ca3c6cbca6.png)

**Comment by maze-runnar** [comment]
and Also in order-form.js there is no field for gender as for country:
```
country: {
          identifier : 'country',
          rules      : [
            {
              type   : 'empty',
              prompt : this.l10n.t('Please enter your country')
            }
          ]
        },
```

**Comment by maze-runnar** [comment]
made everything workable -
![Screenshot from 2020-01-15 15-25-55](https://user-images.githubusercontent.com/56407566/72424061-61ebcc80-37ab-11ea-9e69-ff7c08b7c09d.png)
but i don't know why fields value is not there is attendees info section while i made only country section as like gender , but gender value was not showing there, even before i made changes:
![Screenshot from 2020-01-15 15-14-28](https://user-images.githubusercontent.com/56407566/72424178-9069a780-37ab-11ea-9329-5bec70cc4898.png)

**Comment by maze-runnar** [comment]
@snitin315 @kushthedude can i create a PR for this, i will leave the vallidation part if @snitin315 will say as he has opened a seperate issue for that, @snitin315 please confirm.

**Comment by snitin315** [comment]
@maze-runner you can make the PR with validation as well.

**Comment by maze-runnar** [comment]
> @Maze-runner you can make the PR with validation as well.

thanks @snitin315
