### ISSUE TITLE
Editing a Speaker as an Organizer results in disappearing Linkedin link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3789]
The Linkedin link disappears and has to be re-entered if a user or organizer edits a speaker.

![Screenshot from 2020-01-11 08-44-51](https://user-images.githubusercontent.com/1583873/72198076-aba48200-344e-11ea-8565-a4d49463f21b.png)

**Comment by maze-runnar** [comment]
@kushthedude i want to work on this .

**Comment by kushthedude** [comment]
Did you reproduce on local?

**Comment by maze-runnar** [comment]
yes, it's an valid issue , but more than that i have a doubt, it's not saving the linkedin url , not only editing but when registering new-speaker.
![Screenshot from 2020-01-16 12-30-10](https://user-images.githubusercontent.com/56407566/72501118-0a596980-385c-11ea-9bb7-8b092fdca997.png)
Entered all four (github, facebook, twitter ,linkedin ) but showing only 3 .
