### ISSUE TITLE
If two speakers are assigned to a session and one speaker is unassigned, the session does not appear anymore and the remaining speaker is deleted from the event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3790]
If two speakers are assigned to a session and one speaker is unassigned, the session does not appear anymore and the remaining speaker is deleted from the event. The session still shows up in the speaker overview, but the session is no longer present in the session overview.

![Screenshot from 2020-01-11 08-46-54](https://user-images.githubusercontent.com/1583873/72198160-4ac97980-344f-11ea-81d2-aeeb03105c02.png)

Interestingly, the session actually shows up with the speaker that was unassigned and it is also still listed on the public page.

![Screenshot from 2020-01-11 08-52-59](https://user-images.githubusercontent.com/1583873/72198186-c9261b80-344f-11ea-8f14-911707cc580c.png)

It is possible that the session then reappears again, but it is not editable in a normal, does not get saved or some other problem appears.

In that case it is not possible to add one speaker and delete another speaker. It is sometimes possible to do this in one step, save it and then do another step.

**Comment by AyanChoudhary** [comment]
I would like to work on this issue

**Comment by snitin315** [comment]
Please claim one issue at a time.

**Comment by maze-runnar** [comment]
this issue is solved now. It is not present in the system at this time.
