### ISSUE TITLE
Ranking list of talks by rating 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#3795]
Presently the list of talks are not ranked based on the internal rating. https://eventyay.com/e/a74665c3/sessions/s/all

Having highest quality talks on the top will attract more audience.

**Comment by abhiandthetruth** [comment]
i am working on this issue

**Comment by kushthedude** [comment]
Can not be worked until https://github.com/fossasia/open-event-frontend/issues/2959 is fixed and implemented correctly !
