### ISSUE TITLE
Required field quantity of tickets not checked in the create event page if more than one ticket category is involved

### ISSUE THREAD

**Issue by abhiandthetruth** [fossasia/open-event-frontend#3797]
**Describe the bug**
During event creation if you have more than one category of tickets (eg. 'economy' and 'reserved') of any type(free or paid). Only the quantity of the first ticket is validated others are not.

**To Reproduce**
1. Login and go to the create event page.
2. Fill all the required details except ticket details.
2. Add a type(paid or free) of ticket(the validity of this ticket is checked).
3. Add another type(paid or free) of ticket and don't fill in the quantity of this one.
4. Publish the event.
5. The event is published successfully.

**Expected behavior**
The page should prompt the user to enter the quantity.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.117 (Official Build) (64-bit)

i want to work on this issue.

**Comment by kushthedude** [comment]
@iamareebjamal Same is the case with **Ticket Price Fields**.
@codedsun Can you please open a server issue to enforce the checks on the following quantities?

@abhiandthetruth Thank you for reporting the issue!

**Comment by kushthedude** [comment]
Same is the case with Ticket Price Field

**Comment by abhiandthetruth** [comment]
I have identified the problem. The problem is with the semantic ui. The identifier mentioned in the validation rule is limited to one element. Whenever a ticket is added the name of the input is the same 'ticket_quantity' for all tickets. When the ui checks for validation it stops at the first match of the identifier and validates it. [See here](https://github.com/Semantic-Org/Semantic-UI/issues/2688)

I am trying to change the name of fields to 'ticket_quantity_[index]' and add another rule for it whenever a new ticket is created with the corresponding identifier.

Any Suggestions?

**Comment by mariobehling** [comment]
Resolved mostly in different PRs.
