### ISSUE TITLE
Events Listing > Live Events (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#38]
![screen shot 2017-05-11 at 8 08 17 pm](https://cloud.githubusercontent.com/assets/2404372/25955005/98c9bf34-3685-11e7-89a2-9df64e5d699c.png)

- Live events listing page located at `/events/live`
- Tabs - Live, Draft, Past, Import
    - Tabs should be common to future pages `/events/draft`, `/events/past` etc. (Clue: Make use of `events.hbs` for this.)
    - Current page should be highlighted in the tab. (Checkout `{{#link-to}} {{/link-to}}` helper of ember.)
- A basic table. No sorting/searching features necessary now. Table should be a component so that it can be re-used for the other pages.
- Dummy data to be used. Checkout https://open-event-dev.herokuapp.com to see what data is being displayed how. 
- **Bonus: _(Need not be done in this issue)_** Auto redirect `/events` to `/events/live`

**Comment by CosmicCoder96** [comment]
@niranjan94 I would like to work on this.
