### ISSUE TITLE
Promotional Code empty still calls server

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#3815]
**Describe the bug**
The Apply promo code section while ordering tickets for an event hits the API even when the promocode text field is empty.

**To Reproduce**
1. Open the page for ordering ticket
2. Click on apply promocode
3. Click on tick without entering any value -Hits the API

**Expected behaviour**
Shouldn't hit api and should be handled client side.

**Screenshots**

![image](https://user-images.githubusercontent.com/20026440/72640934-eea2b000-398e-11ea-9753-9a6eff420a3b.png)

**Comment by maze-runnar** [comment]
@codesun , i want to work on this.

**Comment by maze-runnar** [comment]
@codedsun so it should validate from client side when promotion code field is empty?

**Comment by maze-runnar** [comment]
@codedsun , what about this solution - 
make the submit promotional code button dissappear when there is not any promotionalCode,and i made frontend validation working too - 
![Screenshot from 2020-01-18 14-42-45](https://user-images.githubusercontent.com/56407566/72661501-d10e2e80-3a00-11ea-9d9e-de38482245c2.png)

![Screenshot from 2020-01-18 14-38-57](https://user-images.githubusercontent.com/56407566/72661462-652bc600-3a00-11ea-8e0b-bd56962efe6d.png)
![Screenshot from 2020-01-18 14-39-02](https://user-images.githubusercontent.com/56407566/72661463-65c45c80-3a00-11ea-8ee3-8391b98ae966.png)

**Comment by codedsun** [comment]
> make the submit promotional code button dissappear when there is not any promotionalCode

See how it's working for other input fields. This also looks good to me.

**Comment by maze-runnar** [comment]
> > make the submit promotional code button dissappear when there is not any promotionalCode
> 
> See how it's working for other input fields. This also looks good to me.

@codedsun can you please make me clear , what you mean by other input fields here?

**Comment by codedsun** [comment]
@maze-runnar - I meant that refer to the other input fields used in the project for taking reference. Rest it also looks good to me.
