### ISSUE TITLE
unable to order ticket

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3817]
**Describe the bug**

 Unable to order ticket for any event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Any event
2. Click on 'Order Now'
3. See error

**Screenshots**
I Found theese two errors

![Screenshot from 2020-01-18 13-26-14](https://user-images.githubusercontent.com/46647141/72660661-9a331b00-39f6-11ea-8108-c677bf23d263.png)

![Screenshot from 2020-01-18 13-26-39](https://user-images.githubusercontent.com/46647141/72660665-a3bc8300-39f6-11ea-89ad-85a0150bee84.png)

**Additional context**
Please verify this by reproducing

**Comment by maze-runnar** [comment]
Not a valid issue , i am able to order tickets , 
![Screenshot from 2020-01-18 14-24-51](https://user-images.githubusercontent.com/56407566/72661311-53e1ba00-39fe-11ea-9d21-04b6df5e99e1.png)

**Comment by snitin315** [comment]
@maze-runner Thanks for confirming.
