### ISSUE TITLE
Forward, previous button loaders don't appear quick enough in the edit event wizard

### ISSUE THREAD

**Issue by abhiandthetruth** [fossasia/open-event-frontend#3821]
**Describe the bug**

In the edit event wizard after the forward button is clicked the loader takes quite a while to appear. This may lead user to click the button multiple times and thus the user receives the confirmation message multiple times

**To Reproduce**
1. Create an event and go to the Attendee form
2. Fill it and click forward.

**Comment by kushthedude** [comment]
That's the loading time, What can be done in this situation ?

**Comment by abhiandthetruth** [comment]
I don't know sir but this sure creates a lot of confusion for the users. I will like to find why does the loader take so much time to load(when it's sole purpose is to indicate loading) in the attendees form while it works fine in the sponsors form.

**Comment by kushthedude** [comment]
It takes more time in session/speaker form too, that is because for these
forms it has to query more data like each field associated with its
required and mandatory fields.

**Comment by abhiandthetruth** [comment]
In my opinion there should be an indication to the user if it happens like to wait or something because he will end up hitting the button twice in most cases. Shall I work to do something or if the behaviour is  acceptable should I close th issue?

**Comment by kushthedude** [comment]
How will he hit the button twice, when we have a loader getting appeared.
The issue would have been valid when there was nothing going on while
loading=true

**Comment by abhiandthetruth** [comment]
Sorry but the loader wasn't appearing( at least in my system) that's why i
created the issue. Looks like it was system specific then. Thanks for your
time.
