### ISSUE TITLE
Access Code: Ticket does not show up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3827]
The access code function is to enable ticket buyers to see hidden ticket (which is configured in the tickets wizard step 1). Currently adding an access code does not show the hidden ticket, when using the access code link.

![Screenshot from 2020-01-21 07-57-37](https://user-images.githubusercontent.com/1583873/72782595-6dfce180-3c24-11ea-9a93-20db8b976548.png)

**Comment by maze-runnar** [comment]
@mariobehling @kushthedude working on it.

**Comment by maze-runnar** [comment]
I think ,  this is not a valid issue . It is working correctly as it is supposed to.
https://youtu.be/JU4IkxlTDAI
@mariobehling @kushthedude @snitin315 please varify?

**Comment by snitin315** [comment]
@maze-runnar  It is a valid Issue.

**Comment by maze-runnar** [comment]
@snitin315 did you saw the video? Did you reproduce the same issue using same steps ?

**Comment by snitin315** [comment]
## First I created a hidden ticket as you can see here -
![Screenshot from 2020-01-21 20-28-57](https://user-images.githubusercontent.com/46647141/72816411-198e4c00-3c8e-11ea-90cd-798275db00cc.png)


## Then I created an access code for the same -
![Screenshot from 2020-01-21 20-37-09](https://user-images.githubusercontent.com/46647141/72816217-d3d18380-3c8d-11ea-897c-56f6844f224a.png)

## Still the Hidden ticket was not showing using the access code link.
![Screenshot from 2020-01-21 20-30-10](https://user-images.githubusercontent.com/46647141/72816296-ecda3480-3c8d-11ea-84dc-bf2515b9ddc3.png)

**Link to event** - [https://open-event-fe.netlify.com/e/643c10fb](https://open-event-fe.netlify.com/e/643c10fb)

**Access Code link** - [https://open-event-fe.netlify.com/e/643c10fb?access_code=test](https://open-event-fe.netlify.com/e/643c10fb?access_code=test)

**Comment by maze-runnar** [comment]
@snitin315 , i think you should enter the `access_code`(test) in `Enter Prootional code` section , please try this once and tell again .

**Comment by snitin315** [comment]
@maze-runnar  I did appplied access_code `test` in `Promotional code`  it showed me an error `Invalid Promotional Code` As it was supposed to produce. 

The I created a discount code `discount` and entered it in the Promotional Code and it was the applied.
![Screenshot from 2020-01-21 21-06-02](https://user-images.githubusercontent.com/46647141/72818949-5ceab980-3c92-11ea-8306-988e589533dc.png)

**Comment by snitin315** [comment]
@maze-runnar you can verify yourself for this event here [https://open-event-fe.netlify.com/e/643c10fb](https://open-event-fe.netlify.com/e/643c10fb)
Access Code = `test`
Discount Code = `discount`

**Comment by snitin315** [comment]
Can you share link for your event as well?

**Comment by kushthedude** [comment]
No issues there was a bug in URL creator. Taken care !
