### ISSUE TITLE
Deleting Events in Admin Panel does not delete them. They still show up in the live events in the admin panel

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3834]
Deleting Events in Admin Panel does not delete them. They still show up in the live events in the admin panel.

![Screenshot from 2020-01-22 16-16-30](https://user-images.githubusercontent.com/1583873/72906511-a25ec380-3d32-11ea-9f7d-12b728059ec1.png)

**Comment by kushthedude** [comment]
Breaking into two issues:
- Super Admin should be able to delete any event.
- A reload of table action should be sent after deletion.
