### ISSUE TITLE
Integrate with embroider and enable code splitting

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3837]
https://github.com/embroider-build/embroider

https://github.com/embroider-build/embroider/tree/master/packages/router

- [x] Bower components ~~with fastbootShim transform~~ need to be replaced

Parent: #3634

**Comment by kushthedude** [comment]
Is it in production now ? It is still experimental .

**Comment by iamareebjamal** [comment]
Yes, still if the app builds, it doesn't matter

**Comment by Krish-bhardwaj** [comment]
I am interested to fix this issue. I request you to allow me to fix it. can you assign me this issue

**Comment by cweitat** [comment]
[em](https://github.com/embroider-build/embroider) requires node 16 and above now
