### ISSUE TITLE
bug: Able to save event without selecting a payment method for Donation Ticket

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3850]
**Describe the bug**

Currently user is able to save the event without selecting a payment method for Donation ticket.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event.
2. Add a donation ticket
3. Save event.

**Expected behaviour**

User must have to select a payment option in order to save a donation ticket.

**Additional context**

I will work on this issue.

**Comment by kushthedude** [comment]
Fixed in https://github.com/fossasia/open-event-server/pull/6789
