### ISSUE TITLE
Location-Input Form: Make country as dropdown.

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3853]
**Describe the bug**
Make country as a `dropdown` instead of `text` in `location-input` form in `basic-details-steps` of `wizard` 

**Screenshots**

![Screenshot from 2020-01-26 12-54-49](https://user-images.githubusercontent.com/46647141/73132053-a2650900-403b-11ea-819d-46d987ccfb79.png)

**Additional context**

Working on it.

**Comment by kushthedude** [comment]
Once we get an map API Provider it will be fixed
