### ISSUE TITLE
Editing the tax info is not working in wizard 

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3869]
**Describe the bug**
Editing the tax info is not working in wizard . If user has not initially created any tax information, then he would not be able to add it.

If organizer adds tax info when creating the event and later editing , this is working . But can't add tax info later after event is published and if no tax info was assed at that time.
**Additional context**
Working on it.

**Comment by kushthedude** [comment]
Duplicate of #3710
