### ISSUE TITLE
Missing password validation in forgot password window

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#3876]
**Describe the bug**

In forgot password window , validation is missing while setting new password. Also it lacks toggle icon.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'forgot password'
2. Click on 'link sent to your mail'
3. Type invalid password 

**Expected behaviour**

Have validations similar to sign up and login.

**Screenshots**

![Screenshot 2020-01-27 19:09:10](https://user-images.githubusercontent.com/35539313/73190567-332b0a00-414c-11ea-9ae3-60b80d3a9bc4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Browser :  chrome
 - Version : 79.0.3945.88 (Official Build) (64-bit)

**Additional context**

Working on it.

**Comment by Rohithgilla12** [comment]
Can I take it up?

**Comment by mohitm15** [comment]
> Can I take it up?

I had already worked on it.

**Comment by bosecodes** [comment]
Is this issue solved? I can work on it otherwise

**Comment by mohitm15** [comment]
PR under review. Look for other issue

**Comment by snitin315** [comment]
@mohitm15 are you still working on it,? Your PR is not updated from a long time.?

**Comment by snitin315** [comment]
Looking into it.
