### ISSUE TITLE
bug: use eventyay is hardcoded in footer.

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3913]
**Expected behaviour**
Eventyay shoul be replaced with `{{settings.appname}}` So that footer shows `Open Event` or `Eventyay` accordingly.

**Screenshots**
![Screenshot from 2020-01-30 20-06-49](https://user-images.githubusercontent.com/46647141/73459159-5a781600-439c-11ea-955d-046a0cd8ac96.png)

![Screenshot from 2020-01-30 20-05-16](https://user-images.githubusercontent.com/46647141/73459186-6532ab00-439c-11ea-98f3-00f6bc0a2232.png)

**Comment by amanbora** [comment]
I would like to work on this issue, is it available ?

**Comment by snitin315** [comment]
@amanbora  I have already made PR for this issue. You can check on some other issues.
