### ISSUE TITLE
Remove awaits in loop

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3916]
https://eslint.org/docs/rules/no-await-in-loop

**Comment by kushthedude** [comment]
@iamareebjamal There are places, where we can't remove the async-await wrap like :
```js
  async saveForms(data) {
    for (const customForm of data.customForms ? data.customForms.toArray() : []) {
      await customForm.save();
    }
    return data;
  },
```
```js
          .catch(async e => {
            for (const attendee of attendees ? attendees.toArray() : []) {
              await attendee.destroyRecord();
            }
```
It should be disabled or should we disable the rule to specific files ?

**Comment by gittysachin** [comment]
Hi @iamareebjamal, Hi @kushthedude 
I would like to work on this issue.

**Comment by iamareebjamal** [comment]
```js
  async saveForms(data) {
    await Promise.all((data.customForms ? data.customForms.toArray() : []).map(form => form.save()))
    return data;
  },
```

```js
          .catch(async e => {
			await Promise.all((attendees ? attendees.toArray() : []).map(attendee => attendee.destroyRecord()))
  		  })
```

Besides all these changes will be handled by server in near future, looping to make requests is a poor pattern

**Comment by maze-runnar** [comment]
@iamareebjamal @kushthedude can i work on this?

**Comment by kushthedude** [comment]
Before getting started,keep in mine there are places where we need await so
you may need to modify the code to ensure async-await are intact

**Comment by gittysachin** [comment]
> @iamareebjamal @kushthedude can i work on this?

I'm working on this issue. You can please check on some other issues.
