### ISSUE TITLE
Add model for create page at admin/content/pages

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-frontend#393]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

<img width="1253" alt="screen shot 2017-07-01 at 12 53 15 pm" src="https://user-images.githubusercontent.com/12716067/27760103-e1de495c-5e5c-11e7-9ef6-3ca3404707c5.png">

I will be working on this

**Comment by niranjan94** [comment]
@utkarshnath I'm not sure why you don't follow other issues and PRs on this project. This same issue has been opened before and was closed. See https://github.com/fossasia/open-event-frontend/issues/378
