### ISSUE TITLE
Remove duplicated imports and Apply no-relative-imports

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3940]
There have been a bunch of warnings while running the app due to the following.
References :
https://eslint.org/docs/rules/no-duplicate-imports
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-relative-parent-imports.md

**Comment by snitin315** [comment]
I will work on this issue.

**Comment by snitin315** [comment]
@kushthedude there are 3 options for relative-imports -

>-  Move the file to be in a sibling folder (or higher) of the dependency.
>-  Pass the dependency as an argument at runtime (dependency injection)
>-  Make the dependency a package so it's globally available to all files in your project

Which one should be done?

**Comment by iamareebjamal** [comment]
Fixed in #4096
