### ISSUE TITLE
Can't update CFS dates after event has been created

### ISSUE THREAD

**Issue by mrsaicharan1** [fossasia/open-event-frontend#3941]
**Describe the bug**
Not able to update CFS dates for any event. 
`Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined`

**Expected behavior**
The details must be updated

**Additional Details**
Working on it

**Comment by kushthedude** [comment]
Will be fixed by https://github.com/fossasia/open-event-frontend/pull/3891
