### ISSUE TITLE
Remove bower

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#3957]
Bower is deprecated and holding us back from using embroider. Use yarn to pull in the packages instead of bower

Parent: #3837 

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by maze-runnar** [comment]
working on it.

**Comment by maze-runnar** [comment]
@iamareebjamal , i am following this blog. is it correct?

**Comment by maze-runnar** [comment]
@iamareebjamal , i have followed the steps of this blog ,https://itnext.io/bower-to-yarn-migration-simple-steps-2a5ad0c43281. But i am not able to understand what after this. Where to make changes?

**Comment by iamareebjamal** [comment]
Search `bower` in the repo. Stop when no references are found

**Comment by kushthedude** [comment]
> > Tel laga lo dabar ka. Naam mita to bower ka

🔥

**Comment by Dishebh** [comment]
@iamareebjamal if it is up for grabs, can I take it?

**Comment by iamareebjamal** [comment]
Yes
