### ISSUE TITLE
Add a Component if no entry found in a route 

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#396]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
currently, there is no message showing nothing to displayed or no events found for -
`my-sessions/`  ,  `my-sessions/past`  when there are no session proposal for upcoming or past events
and on the home page under upcoming events when there are no upcoming events
![image](https://user-images.githubusercontent.com/20153241/27763528-bc65d64a-5ea2-11e7-8827-feb852b5bfb7.png)

**Expected behavior:**
there should be a proper message showing if there is any entry found in a route or not
![image](https://user-images.githubusercontent.com/20153241/27763533-d775a73a-5ea2-11e7-8ed0-0be4b93b5d84.png)

**Comment by anu-007** [comment]
Approach: I think we should define a component which shows an appropriate message and in the templates, we can check the length of the model returned by the model hook and according to it using (if {{model.length}} is 0){{component}} helper we can render our new component and using computed property we can display a meaningful sentence.

@niranjan94  please check if the issue is valid and approach is correct or I simply use if else statement to show different messages.thanks !!

**Comment by harshitagupta30** [comment]
@niranjan94 @anu-007 I will work on this
