### ISSUE TITLE
Public Page: Speaker Section is broken

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3986]
Speaker Section on production is too much buggy, I don't know why is that. If that is due to upgradation of some dependency or anything else.

**Comment by kushthedude** [comment]
@iamareebjamal There is need for hotfix, some dependency upgrade or might be infinityloader is broke on speaker page.

**Comment by iamareebjamal** [comment]
It is broken when going from event page to speaker page. Revert infinity loader for now

**Comment by iamareebjamal** [comment]
Broke means without any money

**Comment by kushthedude** [comment]
I did test the loader yesterday, it was working perfectly on summit 2020. It is due to some dependency upgrade which has broken it. 
What do you say I can debug it till tomorrow and let know which PR broke it?

**Comment by kushthedude** [comment]
Fixed in #3987
