### ISSUE TITLE
bug: Possible to add speaker without any information.

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3996]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to event-dashboard -> speaker
2. Click on add speaker
3. add speaker without any details

**Expected behaviour**
At least name should be required to add a speaker.

**Screenshots**
![issue](https://user-images.githubusercontent.com/46647141/73719019-1d1cdb00-4744-11ea-90fd-d742233dc36f.PNG)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**

Please verify if this issue is valid.

**Comment by kushthedude** [comment]
Did you even refresh the page after changing tab, As the empty record is still in your cache?

**Comment by kushthedude** [comment]
Also, You won't be able to submit the form without adding necessary speaker details, Necessary server & frontend checks are already inforced for same. It is mainly because you clicked on `Add Speaker` and jumped to Speaker Tab.

**Comment by snitin315** [comment]
Yes you are right . Having trouble with internet connection as well.

**Comment by kushthedude** [comment]
There is an issue with Ember Table or it's implementation in our application, which once solved will also remove this behaviour.
