### ISSUE TITLE
Delete Event should be under settings page

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3997]
We already have an Event Settings Sub-tab in the Events View. 

It would be better to move the functionality of Delete Event from Nav-Bar to the Event Settings Page with a proper description like loss of data, sessions, speakers info.

**Comment by kushthedude** [comment]
cc: @iamareebjamal If this would be a valid enhancement

**Comment by snitin315** [comment]
@kushthedude Sometihng like this?

![Screenshot from 2020-02-07 17-52-51](https://user-images.githubusercontent.com/46647141/74029454-bf51f280-49d2-11ea-8fc4-f3c87c2063cf.png)

**Comment by kushthedude** [comment]
Yes something like this, but can we get alignment like in the github settings?

**Comment by snitin315** [comment]
Yes its possible to have alignment like this. 

![Screenshot from 2020-02-07 17-58-14](https://user-images.githubusercontent.com/46647141/74029813-8bc39800-49d3-11ea-9760-849784cb0d02.png)

**Comment by kushthedude** [comment]
It will be appreciated then👍
