### ISSUE TITLE
Deleting/Restoring an event hangs the frontend

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3998]
Deleting/Restoring event makes the frontend hang and the request is not processed by the server. Ultimately, the Server needs to be restarted to fix the issue.

<img width="1119" alt="Screenshot 2020-02-04 at 12 09 20 PM" src="https://user-images.githubusercontent.com/44091822/73720141-48ed9000-4747-11ea-8649-e9a937d9d702.png">

**Comment by kushthedude** [comment]
@iamareebjamal I have not been able to debug this, server sends no response or the FE is not able to analyse the response.
Most probably this is happening after https://github.com/fossasia/open-event-frontend/pull/3980 . Please check if you can debug it.

**Comment by iamareebjamal** [comment]
If you can remove the serialization logic and it works, then it is because of the PR, if not. It isn't. This release constituted of 1 year worth of dependency upgrades, so some bugs were expected. Of course, testing was not done carefully on staging before making it live due to lack of resources

**Comment by kushthedude** [comment]
> If you can remove the serialization logic and it works, then it is because of the PR, if not. It isn't. This release constituted of 1 year worth of dependency upgrades, so some bugs were expected. Of course, testing was not done carefully on staging before making it live due to lack of resources

Nope even not working before serialization, Some dependency upgrade might be.
