### ISSUE TITLE
Event Speaker Images are not in Shape and Cut Off on Public Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3999]
This issue covers the public image display of speakers, e.g. see here https://eventyay.com/e/b97c6882

Speakers images are showing increased width instead of having the same width to height. When you download the image it is showing correctly though. But: On the html display in the browser the image is wider and it is partly cut off.

![Screenshot from 2020-02-04 12-08-19](https://user-images.githubusercontent.com/1583873/73739898-691d4f00-4747-11ea-988a-3a9e449633f1.png)

Compare to uploaded image
![Screenshot from 2020-02-04 12-07-46](https://user-images.githubusercontent.com/1583873/73739909-70dcf380-4747-11ea-916f-cccc361cffd8.png)

**Comment by mohitm15** [comment]
May I take up this issue?

**Comment by iamareebjamal** [comment]
@mariobehling An issue was raised to make the images squared. Since the previously uploaded images were not of 1:1 aspect ratio, it was made to be center cropped on frontend. Newly uploaded photos will be 1:1

**Comment by mohitm15** [comment]
@mariobehling  how to reproduce on local machine?

**Comment by snitin315** [comment]
> @mariobehling how to reproduce on local machine?

add speakers to your event.

**Comment by mohitm15** [comment]
Add infinitely many time to load after details for speaker, SEE

![screencapture-localhost-4200-events-2a67a7bf-speakers-create-2020-02-09-10_59_52](https://user-images.githubusercontent.com/35539313/74096908-208cd980-4b2b-11ea-95fe-5b1086a9bfec.png)

**Comment by Haider8** [comment]
@iamareebjamal Can I work on this issue

**Comment by Haider8** [comment]
There will be issue in showing older images. For example, if I set `.thumbnail-square` CSS to `min-height: 100%` rather than `height: 300px`

![speaker-images](https://user-images.githubusercontent.com/43299408/89545505-11a88a80-d821-11ea-9708-6fe7ae453079.png)

**Comment by iamareebjamal** [comment]
Yes, that's what I wrote earlier. Please move to a different issue

**Comment by hpdang** [comment]
We can't do anything for the old events, close for now. It wont happen in newly created events.
