### ISSUE TITLE
Speaker name too close to picture and text cannot be selected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4000]
The design of the speakers has been changed and
* now the name of the speakers is very close to the images. 
* Also the text and session name in the expanded speaker section cannot be selected anymore.
* The session used to link to the extended session description on the "sessions page". It is not linked now.

![Screenshot from 2020-02-04 12-12-21](https://user-images.githubusercontent.com/1583873/73740151-e6e15a80-4747-11ea-9b17-92b53224cdbc.png)

Compare https://eventyay.com/e/b97c6882

**Comment by mohitm15** [comment]
May I take up this issue?

**Comment by snitin315** [comment]
@mohitm15 Go Ahead.

**Comment by mohitm15** [comment]
@snitin315 ok

**Comment by mohitm15** [comment]
@snitin315 I am unable to find the corresponding stylesheet although I inspected through browser, should I use br in hbs file.

**Comment by snitin315** [comment]
@mohitm15 Refer [#3819 ](https://github.com/fossasia/open-event-frontend/pull/3819)

**Comment by adrijshikhar** [comment]
@mohitm15 are you still on the issue?

**Comment by mohitm15** [comment]
@adrijshikhar Yes

**Comment by ashutoshgoswami05** [comment]
i am a beginner margin-top:0.5rem works on  @snitin315

**Comment by snitin315** [comment]
Why not open a PR and move the discussion there?

**Comment by ParvathiRajpal** [comment]
May I know whether the issue is still open or has anyone fixed it?

**Comment by iamareebjamal** [comment]
Still open

**Comment by ParvathiRajpal** [comment]
okay..thanks

**Comment by Anurag-Srivastava-21** [comment]
can i fix it ?

**Comment by ParvathiRajpal** [comment]
> can i fix it ?

Sorry I am still working on this issue.

**Comment by iamareebjamal** [comment]
It's been 17 days, @Anurag-Srivastava-21 you can go ahead

**Comment by iamareebjamal** [comment]
3rd point continuing in #4832
