### ISSUE TITLE
Forget Password: Don't open it in new tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4003]
Clicking forget password opens the next page in a new window. Expected: Open it in the same window.

![Screenshot from 2020-02-05 02-59-30](https://user-images.githubusercontent.com/1583873/73804347-cc4cc700-47c3-11ea-82ca-b05d9473936a.png)

**Comment by kushthedude** [comment]
Solving this issue will result in https://github.com/fossasia/open-event-frontend/issues/2753. What we can do is send a `refreshAction` as soon as forgot password is clicked.

**Comment by codewithrikon** [comment]
I can fix it

**Comment by kushthedude** [comment]
Go ahead.

**Comment by AyanChoudhary** [comment]
@codewithrikon are you still working on this? If not I would like to do this.

**Comment by snitin315** [comment]
@AyanChoudhary Therre is No sign of work done , you can go ahead with this.

**Comment by AyanChoudhary** [comment]
Can you help me with reproducing this error? I am not able to find the guest order form.

**Comment by snitin315** [comment]
1. Got to  Login 
2. Click on forgot password

**Comment by AyanChoudhary** [comment]
It opens in the same window. Is this error browser specific?

**Comment by kushthedude** [comment]
Without login, order tickets in the popup click forgot password.

**Comment by AyanChoudhary** [comment]
Did that. But the effect is the same. No new window appears.

**Comment by AyanChoudhary** [comment]
The issue is still there but surprisingly it wasn't coming up in my firefox, but is there in chrome

**Comment by Haider8** [comment]
@iamareebjamal After removing target blank the window freezes because of `.ui.dimmer` css which sets the background color to `rgba(0, 0, 0, 0.85)` but I couldn't figure out why it's happening. Can you please take a look at it.

**Comment by iamareebjamal** [comment]
This seems like a bug in semantic UI. Move to another issue

**Comment by iamareebjamal** [comment]
Focus on newly opened issues

**Comment by SubhradeepSS** [comment]
@iamareebjamal the issue is still open for codeheat? i guess it is fixed because the forgot password is not opening on new window.
