### ISSUE TITLE
Ticket buyer: Choosing Ticket holder same as ticket buyer makes the text light gray and hard to read

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4004]
Ticket buyer: Choosing Ticket holder same as ticket buyer makes the text light gray and hard to read.

![Screenshot from 2020-02-05 02-52-51](https://user-images.githubusercontent.com/1583873/73804373-e25a8780-47c3-11ea-8d4a-1f4fd615c8b9.png)

**Comment by abhiandthetruth** [comment]
I will be working on it.

**Comment by mariobehling** [comment]
Please claim only one issue at a time.

**Comment by abhiandthetruth** [comment]
ok sir.

**Comment by maze-runnar** [comment]
on oi.

**Comment by kushthedude** [comment]
@mariobehling The following is disabled as you chose `Ticket holder to be same as buyer` once you will uncheck the box it will become normal. Also changing it to regular textbox will not make sense since it's a disabled field.

**Comment by maze-runnar** [comment]
@kushthedude, i had made the field readonly , that will not disable and user also will not able to override
