### ISSUE TITLE
Page causes error when trying to edit my session through edit link

### ISSUE THREAD

**Issue by marcoag** [fossasia/open-event-frontend#4007]
**Describe the bug**
I'm trying to access to edit my session through the edit link:

https://eventyay.com/events/b97c6882/sessions/edit/6064

I get the following Error "the page you're trying to access has caused an error..."

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the link when logged in with a certain user

**Expected behaviour**
Either show me the edit session page or a request for permissions (if I don't have permissions)

**Screenshots**
![DeepinScreenshot_select-area_20200205123533](https://user-images.githubusercontent.com/3855564/73822562-567f4480-4831-11ea-9bd1-9cde32385b5c.png)

**Desktop (please complete the following information):**
 - OS: ubuntu bionic desktop
 - Browser firefox
 - Version 72.0.2

**Additional context**
The event I'm trying to edit is: https://eventyay.com/e/b97c6882 
and the talk is AI one listed here: https://eventyay.com/e/b97c6882/sessions/s/all

**Comment by kushthedude** [comment]
@marcoag Can you please try again and share the network tab error with us ?

**Comment by kushthedude** [comment]
You are accessing the wrong link https://eventyay.com/events/b97c6882/sessions/edit/6064 . The link should be https://eventyay.com/e/b97c6882/cfs/edit/6064 . Can you please tell which button redirected you to above link ?

**Comment by maze-runnar** [comment]
![Screenshot from 2020-02-05 23-15-02](https://user-images.githubusercontent.com/56407566/73867887-746a9a80-486d-11ea-92a1-342e35b6eedf.png)
![Screenshot from 2020-02-05 23-15-08](https://user-images.githubusercontent.com/56407566/73867891-76345e00-486d-11ea-9462-b6ad9c592a49.png)

**Comment by maze-runnar** [comment]
code for both links page are same , just implemented at different place.

**Comment by maze-runnar** [comment]
@kushthedude i have changed 
```@action
  editSession(session_id, event_id) {
    this.transitionToRoute('public.cfs.edit-session', event_id, session_id);
  }
```
 so now every session edit will redirect to  https://eventyay.com/e/b97c6882/cfs/edit/6064 type of url.
Should I create a PR?

**Comment by kushthedude** [comment]
Why to redirect both same? The issue is purely different from which you
mentioned.

**Comment by kushthedude** [comment]
@marcoag The link which you tried to access is limited to event organiser/co-organiser, If you were trying to edit the session using the following link then the error must have thrown. Also, please use the link I mentioned above or you may edit session by going to Public Event CFS Page, there you will see the name of your session.
Please confirm, if the link which you mentioned above is the redirection from the public page or my session route else it is not a valid issue.
Thanks!
