### ISSUE TITLE
In session speaker form add a new session should be checkbox 

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#4027]
**Describe the bug**
In session speaker form add a new session should be checkbox . Because once selecting a radio-button it is not possible to un-select it . So it should be checkbox as implemented in add a new speaker field.
In Add a newSession -
![Screenshot from 2020-02-08 12-13-20](https://user-images.githubusercontent.com/56407566/74080678-b9105480-4a6c-11ea-86d6-8df2d7539876.png)
In add a new Speaker -
![Screenshot from 2020-02-08 12-12-26](https://user-images.githubusercontent.com/56407566/74080675-b7469100-4a6c-11ea-916e-630746e3a703.png)

**Additional context**
working on it.

**Comment by Dishebh** [comment]
@maze-runnar can I take the issue?

**Comment by iamareebjamal** [comment]
You haven't even finished https://github.com/fossasia/open-event-frontend/pull/4235
