### ISSUE TITLE
Billing Info form: FE check not working for Company field

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4030]
**Describe the bug**

- FE check not working for company field
- `Tax ID or business ID` field not  marked as `*`

**Screenshots**
![Screenshot from 2020-02-08 18-10-46](https://user-images.githubusercontent.com/46647141/74085394-91d27b00-4a9e-11ea-95b7-62d2bec6a498.png)

**Additional context**

Up For Grabs

**Comment by aknrg77** [comment]
On it

**Comment by Artistic18** [comment]
Is this issue still open?

**Comment by Dishebh** [comment]
@snitin315 if it is up for grabs, can I take it?

**Comment by snitin315** [comment]
Sure, Go ahead.
