### ISSUE TITLE
Can't get to the footer in browse events.

### ISSUE THREAD

**Issue by Chaitanyassr** [fossasia/open-event-frontend#4034]
**Describe the bug**
Can't get to the footer of the browse events(page). As soon as i reach to the bottom, new event start loading(within a second) which makes it difficult to be at the bottom of the page. So a person cant access the bottom links on footer because of this problem.

**To Reproduce**
1. Click on - browse events
2. Scroll down to reach the bottom
4. you will see that you are unable to stay at the bottom and this makes it difficult to access bottom links.

**Expected behavior**
I want it to not to load new events when reached the end of the page.It can load the new event when a person is not at the full bottom or when the footer is half visible. 

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser [e.g. Firefox]

**Comment by Dishebh** [comment]
@Chaitanyassr shall I try implementing the pages section just above footer, that shows the page wise results of the events happened / happening?

**Comment by iamareebjamal** [comment]
This is invalid issue

**Comment by iamareebjamal** [comment]
Pick any other page which does not have infinite loading to see the footer

**Comment by Dishebh** [comment]
> Pick any other page which does not have infinite loading to see the footer

For better UX, shouldn't the user be able to see the footer on each page (conveniently)?

**Comment by iamareebjamal** [comment]
Show me one site with infinite loader where footer is visible

**Comment by Dishebh** [comment]
> Show me one site with infinite loader where footer is visible

Maybe try avoiding infinite loader, and implement something like which google search has...?

**Comment by iamareebjamal** [comment]
Nope
