### ISSUE TITLE
Accounts Section: Improve layout for Danger Zone

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#4037]
Currently, UI for Danger-Zone in `Accounts Section` is too poor.
Please take reference from how the layout is implemented in `Events/Settings` Section, and do the same.

#### Expected : 
<img width="1230" alt="Screenshot 2020-02-09 at 10 58 52 AM" src="https://user-images.githubusercontent.com/44091822/74101880-58644300-4b64-11ea-8524-f15f6c98cb2f.png">

**Comment by snitin315** [comment]
On it.

**Comment by kushthedude** [comment]
> On it.

Take the reference from above image and corresponding PR.

**Comment by snitin315** [comment]
@kushthedude Current mobile view of event settings page is like below.

![Screenshot from 2020-02-10 14-53-34](https://user-images.githubusercontent.com/46647141/74137066-2c54ca80-4c15-11ea-8a9f-a2a46cc1c44f.png)

## Should we keep it this way? or we can do something like below -

![Screenshot from 2020-02-08 17-11-48](https://user-images.githubusercontent.com/46647141/74137166-57d7b500-4c15-11ea-9fa2-c1560d3b882f.png)

**Comment by kushthedude** [comment]
Make the changes in account section and then we can see the same for the
settings if looks good.

**Comment by snitin315** [comment]
For Danger Zone it's will be like below -

![Screenshot from 2020-02-10 14-57-35](https://user-images.githubusercontent.com/46647141/74137517-fa903380-4c15-11ea-8803-d22e06002e2e.png)



![Screenshot from 2020-02-10 14-57-51](https://user-images.githubusercontent.com/46647141/74137449-d7fe1a80-4c15-11ea-8144-5e28c3a5b42a.png)
