### ISSUE TITLE
cancelled oreder's attendees are not showing in table

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#4048]
**Describe the bug**
cancelled oreder's attendees are not showing in table. Completed, expired are showing correctly but cancelled attendees are not showing correctly.
![Screenshot from 2020-02-10 22-01-35](https://user-images.githubusercontent.com/56407566/74169330-27157100-4c51-11ea-8002-ad0bd3a7b879.png)
![Screenshot from 2020-02-10 22-01-44](https://user-images.githubusercontent.com/56407566/74169527-76f43800-4c51-11ea-9f73-4c888a46b460.png)

**Additional context**
Working on it.

**Comment by maze-runnar** [comment]
@kushthedude , i think this can be a server side issue.

**Comment by maze-runnar** [comment]
@kushthedude attendee has not any status named `cancelled` . SO what i should do?

**Comment by maze-runnar** [comment]
@kushthedude i think this can be a server side issue, there could be not any field for attendee like cancelled as  - 
```
else if (params.attendees_status === 'all') {
      filterOptions = [];
    }
```
there is no filter so it should return all attendees , but still not showing cancelled orders attendees.

**Comment by maze-runnar** [comment]
@kushthedude Here cancelled orders attendee are not showing in all section too , I think cancelled section should be removed ?

![Screenshot from 2020-02-10 23-47-46](https://user-images.githubusercontent.com/56407566/74177555-f7ba3080-4c5f-11ea-950f-72e506e2a476.png)

**Comment by maze-runnar** [comment]
@iamareebjamal please help me here in this issue.

**Comment by iamareebjamal** [comment]
What's the problem

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-frontend/issues/4048#issuecomment-584258374
https://github.com/fossasia/open-event-frontend/issues/4048#issuecomment-584263026

**Comment by iamareebjamal** [comment]
I can't understand those comments. That's why asked to explain

**Comment by maze-runnar** [comment]
> I can't understand those comments. That's why asked to explain

```
else if (params.attendees_status === 'all') {
      filterOptions = [];
    }
```
the above piece of code in routes is for returning all type of attendees for any order for an event. But what we get in return is only attendees of status - `expired, completed, placed, checkedin, checkedout` not `cancelled`. There is not any provision for attendees like `cancelled attendee`.

**Comment by maze-runnar** [comment]
I think `cancelled tab` should be removed from 
![](https://user-images.githubusercontent.com/56407566/74169527-76f43800-4c51-11ea-9f73-4c888a46b460.png)

**Comment by iamareebjamal** [comment]
Attendees are not cancelled. Orders are. And yes, there is cancelled state of an order

**Comment by maze-runnar** [comment]
> Attendees are not cancelled

Exactly, so what should i do here?

**Comment by iamareebjamal** [comment]
There's no reason to say exactly. Attendees are neither expired, completed, placed. Orders are

**Comment by maze-runnar** [comment]
But the cancelled orders are returning correctly in attendees section but not the cancelled orders, with same code as for completed and expired.
