### ISSUE TITLE
Email Verification mail not received

### ISSUE THREAD

**Issue by amanbora** [fossasia/open-event-frontend#4068]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Login
2. Enter credentials
3. Click on 'Send confirmation mail'

**Expected behaviour**

Mail received which redirects to the site

**Screenshots**
Click on the link

<img width="1388" alt="Screenshot 2020-02-12 at 11 37 18 PM" src="https://user-images.githubusercontent.com/33185170/74363495-ab522a80-4df0-11ea-84aa-6c48ab00a871.png">

**Comment by iamareebjamal** [comment]
On which site did you try it?

**Comment by Dishebh** [comment]
Is this issue valid?

**Comment by amanbora** [comment]
@iamareebjamal https://open-event-fe.netlify.com/  . Sorry for late response

**Comment by snitin315** [comment]
This issue is fixed.
