### ISSUE TITLE
Convert project to typescript

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4070]
Steps:

Current Focus:
- [ ] New classes should target typescript
- [ ] Conversion of utils, helpers and lastly models in typescript

Long Term focus (PRs not required now):

- [ ] Convert existing components and routes when working on them heavily
- [ ] Remove remaining part of JS

https://ember-cli-typescript.com/versions/master/docs/ts-guide/using-ts-effectively
https://v4.chriskrycho.com/typing-your-ember.html

**Comment by mariobehling** [comment]
Typescript support has been added and we will expand on this.
