### ISSUE TITLE
Restore Import Events section

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#4075]
Import Events API is functional, we should now restore the FE support for import events section too.
Also convert the table to Ember-Table

**Comment by kushthedude** [comment]
@iamareebjamal I had some doubts regarding current importing/exporting API:
- Is it correct to import only speakers without their status like confirmed, accepted etc?
- Tickets are not getting imported from the zip.
- If we make the tickets import work, should all the current ticket holders be imported too?
- Event Export should be in `.zip` format rather than a folder?
- Should `Call For Speakers` open/close time be imported too?

**Comment by iamareebjamal** [comment]
> If we make the tickets import work, should all the current ticket holders be imported too?

The point of import export is to clone an event. Not clone orders. 

> Event Export should be in .zip format rather than a folder?

It is

**Comment by kushthedude** [comment]
> > Event Export should be in .zip format rather than a folder?
> 
> It is

A folder is getting exported.
<img width="298" alt="Screenshot 2020-02-13 at 12 05 28 PM" src="https://user-images.githubusercontent.com/44091822/74407947-251dfe80-4e59-11ea-9d46-c7ef0612dc13.png">

**Comment by iamareebjamal** [comment]
Yes, the download is zip, that's what matters, you can't download a folder

**Comment by kushthedude** [comment]
> @iamareebjamal I had some doubts regarding current importing/exporting API:
> 
> * Is it correct to import only speakers without their status like confirmed, accepted etc?
> * Tickets are not getting imported from the zip.
> * Should `Call For Speakers` open/close time be imported too?

What about these? If the goal is to clone, then all these stuff should get imported too?

**Comment by iamareebjamal** [comment]
Yes
