### ISSUE TITLE
Transfer Ownership : Confirmation should be case sensitive

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4084]
**Describe the bug**

The confirmation for transfer event is not case sensitive.

![Screenshot from 2020-02-14 18-04-30](https://user-images.githubusercontent.com/46647141/74532313-eec5a980-4f54-11ea-9ebd-13a71d70d63e.png)

![Screenshot from 2020-02-14 18-06-11](https://user-images.githubusercontent.com/46647141/74532320-f1280380-4f54-11ea-873a-10ed87182c4d.png)

**Additional context**

If this is a valid issue, I will work on it.

**Comment by snitin315** [comment]
@iamareebjamal @kushthedude Is this issue valid or this was done intentionally before?

**Comment by kushthedude** [comment]
Make event confirmation dialogue case sensitive too

**Comment by snitin315** [comment]
And delete event too?
