### ISSUE TITLE
Same file present with two extensions utils/dictionary/filters.{js, ts}

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4088]
`filters.js` should be removed.

**Screenshots**

![Screenshot from 2020-02-15 06-51-37](https://user-images.githubusercontent.com/46647141/74579377-0e45ec00-4fc0-11ea-8781-a59466a9cc70.png)

![Screenshot from 2020-02-15 06-55-01](https://user-images.githubusercontent.com/46647141/74579387-21f15280-4fc0-11ea-93d1-a609384bb740.png)

**Additional context**

I will work on it if valid.

**Comment by iamareebjamal** [comment]
Delete filters.ts
