### ISSUE TITLE
Remove all sequentially awaited code

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4099]
After removing await from loops, it is time to remove all sequentially awaited code unless result of one call depends on the next. 

If there are 4 requests and each take 5 seconds, they can be completed in 5 seconds, but right now they are taking 20 seconds. It's like deliberately making the site slow. Try to reduce multiple awaits in any function to a single await unless the result of an await is required below

Reference: #4093

**Comment by Vansh1067** [comment]
i want to do this

**Comment by iamareebjamal** [comment]
Go ahead
