### ISSUE TITLE
Use semantic image headers to display logo and event name in events table

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#41]
- https://semantic-ui.com/elements/header.html
- As a result Image and name will be in a single column instead of two
- The logo need not be big

**Comment by CosmicCoder96** [comment]
@niranjan94 
Default header: How does this look
![image](https://cloud.githubusercontent.com/assets/17252805/25999268/15578092-3742-11e7-8c7a-3cf1f4a645f3.png)

**Comment by niranjan94** [comment]
@CosmicCoder96 the text is too big and bold. What you can do is, instead of using a `h`eader tag, use a div. That would fix the text size. Then add class `weight-400` which would fix the boldness and make the event name look like the rest.

**Comment by CosmicCoder96** [comment]
@niranjan94 had already tried it, was about to post. Again two approaches which is better in your opinion
This is the large header class with 400-weight(Logo is bigger)
![image](https://cloud.githubusercontent.com/assets/17252805/25999850/4b6ad272-3744-11e7-9d92-c066798ab11c.png)
And this is the  default header class with 400-weight

**Comment by niranjan94** [comment]
The second one. We don't want a large event name.
