### ISSUE TITLE
Asking to complete login Form

### ISSUE THREAD

**Issue by amanbora** [fossasia/open-event-frontend#4101]
**Describe the bug**

Login form is asking for credentials when requested for new user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Login Page'
2. Click on 'New to site? Create Account '
3. See error

**Expected behaviour**

Login Credentials shouldn’t be asked in case of new user.

**Screenshots**

<img width="390" alt="Screenshot 2020-02-17 at 10 48 26 AM" src="https://user-images.githubusercontent.com/33185170/74625811-991b1800-5173-11ea-8e00-877bffb5acb4.png">

**Comment by snitin315** [comment]
Why a new user will be on a login page instead of sign up?

**Comment by amanbora** [comment]
@snitin315 the sign-up page is requested from login page. You can see there is link for sign-up.

**Comment by amanbora** [comment]
@snitin315 according to you there shouldn’t be 'create account' link on login page ?

**Comment by snitin315** [comment]
I mean why will a new user will enter credential in login form. 
Also this is a front-end check , you don't know if the email is nee or already registered until a POST request is sent to server.

**Comment by amanbora** [comment]
Yes I think you are right. Will close it.
