### ISSUE TITLE
bug: https://open-event-fe.netlify.com NOT FOUND

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4102]
**Describe the bug**

Front end deployment is showing NOT FOUND error.

![Screenshot from 2020-02-17 14-06-57](https://user-images.githubusercontent.com/46647141/74636812-c628f400-518e-11ea-84ef-3aaefc70e2f5.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [https://open-event-fe.netlify.com](https://open-event-fe.netlify.com)

**Comment by snitin315** [comment]
Srever responded with a status code 404
![Screenshot from 2020-02-17 14-08-30](https://user-images.githubusercontent.com/46647141/74636970-143df780-518f-11ea-8a53-b7025675b18e.png)

**Comment by iamareebjamal** [comment]
Our free build minutes exceeded the free plan

**Comment by iamareebjamal** [comment]
https://open-event.netlify.com/

**Comment by snitin315** [comment]
> https://open-event.netlify.com/

Temporary or permanent?

**Comment by iamareebjamal** [comment]
Till we run out of build minutes again

**Comment by snitin315** [comment]
Then I think this Needs to be updated in documentation as well.
