### ISSUE TITLE
url segment in export section of an event is overflowing

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#4104]
**Describe the bug**
url segment in export section of an event is overflowing

![Screenshot from 2020-02-17 17-35-43](https://user-images.githubusercontent.com/56407566/74652503-2c703f80-51ac-11ea-87c5-6d9d778dcc5c.png)
![Screenshot from 2020-02-17 17-36-02](https://user-images.githubusercontent.com/56407566/74652510-2e3a0300-51ac-11ea-9482-ac578e36e306.png)

**Expected behaviour**
![Screenshot from 2020-02-17 17-37-35](https://user-images.githubusercontent.com/56407566/74652544-3b56f200-51ac-11ea-9413-376533986fd0.png)

![Screenshot from 2020-02-17 17-37-41](https://user-images.githubusercontent.com/56407566/74652546-3d20b580-51ac-11ea-9701-2b120a85b874.png)

**Additional context**

Working on it.

**Comment by snitin315** [comment]
Was it fixed ???

**Comment by iamareebjamal** [comment]
No

**Comment by Elgayar** [comment]
I would like to work on this issue.

**Comment by iamareebjamal** [comment]
Go ahead
