### ISSUE TITLE
number of revision is showing hardcoded `coming soon`

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#4107]
**Describe the bug**
This feature is not completely available for roll out so it would pointless to diplay a dummy `no of revisions` as always `coming soon` so should be removed from the table (by comment out)
![Screenshot from 2020-02-17 19-02-13](https://user-images.githubusercontent.com/56407566/74658334-0cdf1400-51b8-11ea-9128-b22705b8e312.png)

**Additional context**
working on it.

**Comment by kushthedude** [comment]
Who told this is available to roll out.
