### ISSUE TITLE
Move to Zeit Now from Netlify for PR Deployments

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#4115]
> Netlify provides only 300 free build minutes per month. I thought they reduced to 5000(which is still less). In 1 day only, we had 16 build, averaging 6 minutes which is honestly not that much. But we anyway used 96 (~100) build minutes, so that limit will exceed within 3 days in a month. So, please create an issue to move to Zeit now for PR deploy previews and dev hosting

**Comment by Dishebh** [comment]
@kushthedude is the issue still valid?

**Comment by iamareebjamal** [comment]
Done
