### ISSUE TITLE
Implement alternative to in-page event burger menu icon on mobile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4117]
Currently on event pages the menu of the event info is converted to a burger menu for n mobile views.

This is the second burger menu and users have to click to see Options. 

Please implement a better alternative with an in page menu that can be accessed without additional clicks.

![Screenshot_20200219_110702_com android chrome](https://user-images.githubusercontent.com/1583873/74798501-e41a6400-5308-11ea-89cd-0c854e7a1001.jpg)

**Comment by maze-runnar** [comment]
@mariobehling  any thoughts about this alternative  -
![Screenshot from 2020-02-19 17-29-55](https://user-images.githubusercontent.com/56407566/74832540-8ce2b680-533d-11ea-8331-33694a558424.png)

**Comment by maze-runnar** [comment]
@kushthedude is this kind of alternative will be good or not? Adding icons in top menu and adding pop-up info to them.

![Screenshot from 2020-02-19 18-03-39](https://user-images.githubusercontent.com/56407566/74835109-b05c3000-5342-11ea-9d76-4a997c8811b8.png)

**Comment by kushthedude** [comment]
Doesnt match our styling

**Comment by maze-runnar** [comment]
> Doesnt match our styling

https://github.com/fossasia/open-event-frontend/issues/4117#issuecomment-588188709
i am saying like this one.

**Comment by maze-runnar** [comment]
> ![Screenshot from 2020-02-19 18-03-39](https://user-images.githubusercontent.com/56407566/74835109-b05c3000-5342-11ea-9d76-4a997c8811b8.png)

this was just like an example.

**Comment by maze-runnar** [comment]
@kushthedude please tell if it is ok to create a PR for this issue or not With these changes ?

**Comment by kushthedude** [comment]
Use tabbed navigation and check how it looks

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
![Screenshot from 2020-02-19 22-11-34](https://user-images.githubusercontent.com/56407566/74854108-deeb0280-5364-11ea-9c16-b7e1d8cb8205.png)
![Screenshot from 2020-02-19 22-11-41](https://user-images.githubusercontent.com/56407566/74854120-e1e5f300-5364-11ea-8918-328ef218bc43.png)

**Comment by maze-runnar** [comment]
@kushthedude is it ok?

**Comment by maze-runnar** [comment]
@kushthedude tabbed navigation is looking cool but @mariobehling has stated in issue "Please implement a better alternative with an in page menu that can be accessed without additional clicks." 
 That is souding confusing with this implementation.

**Comment by kushthedude** [comment]
https://semantic-ui.com/collections/menu.html . See pop-up menu in here. Default tab should show current location and pop-up should contain other locations

**Comment by maze-runnar** [comment]
> https://semantic-ui.com/collections/menu.html . See pop-up menu in here. Default tab should show current location and pop-up should contain other locations

that is not looking good and also need a click too for mobile view, tabbed navigation is better than that, and as it is everywhere used in the application.

**Comment by maze-runnar** [comment]
And also sometimes popup doesn't work and needs a page refresh.

**Comment by maze-runnar** [comment]
> that is not looking good and also need a click too for mobile view, tabbed navigation is better than that, and as it is everywhere used in the application.

> And also sometimes popup doesn't work and needs a page refresh.

@kushthedude, what i should do next??

**Comment by maze-runnar** [comment]
> Use tabbed navigation and check how it looks
I think this is better..

**Comment by daretobedifferent18** [comment]
I am working on it

**Comment by daretobedifferent18** [comment]
I am working on this.

**Comment by maze-runnar** [comment]
fixed in https://github.com/fossasia/open-event-frontend/pull/5998
