### ISSUE TITLE
Email Confirmation: Client thinks it's a phishing link

### ISSUE THREAD

**Issue by xobs** [fossasia/open-event-frontend#4124]
**Describe the bug**
In order to verify an account, the system sends out a confirmation email with a link.  The user is supposed to click this link in order to match the address with the account.  However, the text of the link and the actual link itself do not match, and the actual link goes to a different domain from the originating address.

**To Reproduce**
Steps to reproduce the behaviour:
1. Receive a confirmation email
2. Compare the URL embedded in the email with the originating domain

**Expected behaviour**
The text of the link and the href of the link should match.  At the very least, the domain on the link should match the sender's origin domain.

**Screenshots**

![image](https://user-images.githubusercontent.com/238325/74902708-d1c02900-53e1-11ea-947e-5d56563d080e.png)

**Desktop (please complete the following information):**
 - Email client: eM Client

**Additional context**
Copying the text of the URL rather than the href works just fine.

**Comment by iamareebjamal** [comment]
Same as https://github.com/fossasia/open-event-server/issues/6654

@mariobehling Need to change the sendgrid setting of tracking https://sendgrid.com/docs/ui/account-and-settings/tracking/

**Comment by iamareebjamal** [comment]
Have disabled click tracking
