### ISSUE TITLE
Docker Image is failing

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#4126]
Docker Image is failing to build. 
cc: @iamareebjamal
<img width="772" alt="Screenshot 2020-02-20 at 9 31 55 PM" src="https://user-images.githubusercontent.com/44091822/74954024-75ccc300-5428-11ea-94ca-c13e2ede4524.png">

**Comment by iamareebjamal** [comment]
Random errors in npm registry. Not our fault
