### ISSUE TITLE
Ticket Dashboard: can drag and interchange columns of  Attendees table

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4127]
**Describe the bug**

Able to drag and interchange columns of  Attendees table.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Event Dashboard > Tickets > Attendees
2. Try to drag and interchange columns
3. See error

**Expected behaviour**

Columns Should be fix

**Screenshots**

![captured](https://user-images.githubusercontent.com/46647141/74957312-61d79000-542d-11ea-8887-576a2441f7aa.gif)

**Desktop (please complete the following information):**
 - OS - Kali Linux
 - Browser chrome

**Additional context**

Is this issue valid??

**Comment by kushthedude** [comment]
Not an issue, rather should be viewed as an feature columns can be interchanges for better viewing experience.
