### ISSUE TITLE
Scheduler: Implement scroll bar to always show "calendar"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4166]
Currently if a user scrolls events on the left hand side, the calendar on the right will disappear. It is difficult to drag and drop a session from the left into the main calendar view therefore. Please implement a scroll bar view on the left to keep the calendar showing at all times in the scheduler.

![Screenshot from 2020-03-02 16-44-56](https://user-images.githubusercontent.com/1583873/75692132-5db93700-5ca5-11ea-8fef-def5201741bd.png)

**Comment by amanbora** [comment]
I would like to work on this issue for gsoc 2020

**Comment by snitin315** [comment]
You can work on this issue but not for GSOC 2020.

**Comment by amanbora** [comment]
@snitin315 which issues are available for gsoc 2020 ?

**Comment by snitin315** [comment]
Have you even checked the official gsoc website?

**Comment by amanbora** [comment]
@snitin315 yes

**Comment by snitin315** [comment]
Did you find fossasia on the organisations list?

**Comment by amanbora** [comment]
@snitin315 no 😅. Sorry my bad
I would still try to work on this issue tho

**Comment by snitin315** [comment]
Go ahead

**Comment by ShubhamChaudharyy** [comment]
can i take up this issue? @amanbora if you are not working on this!

**Comment by amanbora** [comment]
@ShubhamChaudharyy go ahead
