### ISSUE TITLE
Scheduler: Making lots of edits results in loss of scheduled sessions in calendar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4168]
When adding a lot of sessions quickly at one point there is a reload and a lot of sessions are suddenly not scheduled anymore.

Even adding only one session into the schedule sometimes is not stored.

![Screenshot from 2020-03-02 17-17-15](https://user-images.githubusercontent.com/1583873/75695074-d0c4ac80-5ca9-11ea-85b3-7e03d93ad51f.png)

**Comment by sandeepbise** [comment]
I will fix this bug can i do this one?

**Comment by iamareebjamal** [comment]
It's advanced
