### ISSUE TITLE
Scheduler: Sessions disappear

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4171]
Sessions disappear when the page is reopened or refreshed, e.g. all Blockchain sessions in the FOSSASIA Summit event are not showing up on the scheduler or on the left-side "to be scheduled" sidebar of the scheduler.

![Screenshot from 2020-03-02 20-55-49](https://user-images.githubusercontent.com/1583873/75712569-6d964280-5cc8-11ea-8f87-db8ecff670c2.png)

**Comment by iamareebjamal** [comment]
32 sessions got assigned a starts_at but no ends_at, hence they disappeared from both unscheduled and scheduled sessions. Reason X why allowing arbitrary PATCHes from client side is a bad idea. Anyway, unscheduled sessions should show sessions with either starts_at or ends_at null till it is known why they were assigned null ends at. This way at least they can be recheduled
