### ISSUE TITLE
Integrate ember-cli-babel-polyfills

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4181]
ember-cli-babel is not including polyfills for latest features like Promise.allSettled. This is breaking the app on browsers like Safari 12.

Integrate https://github.com/pzuraq/ember-cli-babel-polyfills to solve the issue

**Comment by Dishebh** [comment]
@iamareebjamal can I work on this one?

**Comment by iamareebjamal** [comment]
Yes

**Comment by Dishebh** [comment]
How do I test my localhost on cross browser platforms?

**Comment by iamareebjamal** [comment]
Send the PR

**Comment by iamareebjamal** [comment]
Superseded
