### ISSUE TITLE
Add test for ember data query which broke on 3.16.2

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4192]
Ember Data query function broke on 3.16.2, so add a test which breaks the build on broken dependency

**Comment by kushthedude** [comment]
Won't this be covered in the infinityLoader test? Only infinityLoader is broke with the data 3.16+

**Comment by iamareebjamal** [comment]
https://github.com/iamareebjamal/ember-data-bug

**Comment by maze-runnar** [comment]
not needed.
