### ISSUE TITLE
Add events listing > Import Page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#42]
<img width="1680" alt="screen shot 2017-05-12 at 6 04 14 pm" src="https://cloud.githubusercontent.com/assets/2404372/25998428/81b1a212-373e-11e7-85c5-536d86cb12b9.png">

- Located at `/events/import`
- Should have two different components as indicated.
- The table need not have any filtering, pagination and search capability and UI now. Those will be implemented later in a different manner.
- Dummy data can be used now.

**Comment by geekyd** [comment]
@niranjan94 Closing this, I referenced wring issue on the PR. Sorry about that. This was solved in #44.

**Comment by niranjan94** [comment]
Thanks @geekyd
