### ISSUE TITLE
Event Overview/Admin Overview: Enable "Open in Tab" on buttons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4212]
Currently the buttons to view, edit or delete an event on the overview pages of organizers or admins only permit to do the action. It is not possible to open the actual links in a tab. Please change this behavior as it would make things much easier for organizers/admins.

Compare: https://eventyay.com/events/live
![Screenshot from 2020-03-10 11-36-39](https://user-images.githubusercontent.com/1583873/76304697-198cee80-62c4-11ea-93f5-767ec3e6f981.png)

**Comment by iamareebjamal** [comment]
View, Edit Links can be added since they are being taken to a new page, but unfortunately not delete link
