### ISSUE TITLE
Organizer Event Ticket Order Overview: Search not working, Date Sorting according to day instead of day, month, year

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4237]
On the Organizer Event Ticket Order Overview page:
* the search not working
* the Date Sorting according is according to day instead of day, month, year. This means currently e.g. 18th February is in front of 15th of March.

![Screenshot from 2020-03-17 19-14-08](https://user-images.githubusercontent.com/1583873/76851193-d4e4f280-6883-11ea-85e3-c4d66968a687.png)

**Comment by BLasan** [comment]
@mariobehling Can I work on this?

**Comment by iamareebjamal** [comment]
Yes

**Comment by BLasan** [comment]
@mariobehling Can you put the url?

**Comment by iamareebjamal** [comment]
You'll have to create an event and see the event management section

**Comment by ruhci28** [comment]
Hii @iamareebjamal the searchbar seems to be working fine . what is the issue with search bar .

**Comment by iamareebjamal** [comment]
Where are you checking the search bar?

**Comment by maze-runnar** [comment]
> On the Organizer Event Ticket Order Overview page:
> 
> * the search not working

Actually, the search is working, rather than it's searching by identifier not by name.

**Comment by maze-runnar** [comment]
` const searchField = 'identifier';`

@iamareebjamal how can I use here  `const searchField = 'user.name';` something like this. As it is giving error.

**Comment by iamareebjamal** [comment]
What's the error

**Comment by maze-runnar** [comment]
When entering text in input box, it shows some thing went wrong and on console it shows ember data error. And also you have told me previously that user.name this kind of nesting is not supported in backend

**Comment by iamareebjamal** [comment]
Yes, it needs to have custom nested format to search for user name. Check how is it possible in ember tables

**Comment by iamareebjamal** [comment]
@maze-runnar Now you know how it is to be done, so please take this up

**Comment by maze-runnar** [comment]
on adding any of other field here `const searchField = 'identifier';` instead of identifier it throws error. 
for example - `const searchField='completedAt'` it shows error 404.

**Comment by maze-runnar** [comment]
I have also added following in models/order.js and added email in routes to search by email but again 404.
```
Email: computed('user.email', function() {
    return this.user.get('email');
  }),
```

**Comment by iamareebjamal** [comment]
Why do you want to search via completedAt? Makes no sense. 

About searching via email, as discussed last time, to search through related relationships, you need to create the filter like `{ has : { user : { email ... } }`. applySearchFilter function just adds scalar search fields. You have to add custom logic to add search filters for this table

Call me if you have doubts

**Comment by hpdang** [comment]
Can we simplify this date sorting? One click latest order goes on the topic and vice versa. Currently we have to click twice in order to get to the latest order? @mariobehling @iamareebjamal

**Comment by maze-runnar** [comment]
@hpdang we can do it like, latest orders will on the top when first it loads and then sorting work in usual way?

**Comment by iamareebjamal** [comment]
Yes
