### ISSUE TITLE
Public Schedule: Times of sessions are displayed wrongly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4238]
The session times are displayed wrongly even though I am in the same time zone of the event.

![Screenshot from 2020-03-18 10-30-03](https://user-images.githubusercontent.com/1583873/76919368-9ee75300-6903-11ea-8727-4cb2cd9988fc.png)

**Comment by BLasan** [comment]
@mariobehling  Can I work on this?

**Comment by iamareebjamal** [comment]
Yes

**Comment by BLasan** [comment]
I cannot find any issues with dates. The time zones are within the braces

![Screenshot from 2020-04-03 13-12-49](https://user-images.githubusercontent.com/43112139/78336525-1cba8800-75ad-11ea-85b4-4f67f3095f75.png)

**Comment by iamareebjamal** [comment]
Because you are in India and the event timezone is in India as well. Change the event timezone to Singapore

**Comment by iamareebjamal** [comment]
And your screenshot is of event card and issue is about sessions

**Comment by sandeepbise** [comment]
can i solve this one?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by dev-sankhadip** [comment]
Hi @iamareebjamal i want to work on this. Although i didn't get this issue correctly, can you please describe?

**Comment by iamareebjamal** [comment]
The session time set by the organizer is different from the one displayed in session list

**Comment by iamareebjamal** [comment]
Still not fixed in expanded view
