### ISSUE TITLE
Right align the ticket price, quantities of tickets in the tickets' subroutes.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#429]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![left-aligned](https://user-images.githubusercontent.com/17925669/27925343-07fb94f2-62a2-11e7-8145-0c27e8a1ab16.png)
![left-aligned2](https://user-images.githubusercontent.com/17925669/27925345-09ab0616-62a2-11e7-807d-c6b91843a1f0.png)

**Expected:**
1) Right align the ticket prices and quantity of tickets in table to maintain uniformity in all routes.
2) Reduce the space between "US"and "$" present in some subroutes of 'tickets'.

**Comment by sumedh123** [comment]
Working on this.

**Comment by niranjan94** [comment]
@sumedh123 please work on currently open PRs before picking up new issues.
