### ISSUE TITLE
Restore rounded corners

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4306]
https://github.com/fossasia/open-event-theme/commit/0206df77b4d535b35a8fd4ddbabdb0f36adb0d12

There's a lot of research on why rounded corners are better in UI. Flat design with square corners makes Open Event look unfinished and drab. Not to say that a lack of theme color is not helping. Hence, I think rounded corners should be restored. Except Microsoft's UI, which is still not a golden standard, I have seen no site which uses sharp corners. 

https://designmodo.com/rounded-corners/
https://uxmovement.com/thinking/why-rounded-corners-are-easier-on-the-eyes/
https://uxplanet.org/rounded-or-sharp-corner-buttons-def3977ed7c4
https://medium.com/@gotoxplore/rounded-or-square-corners-for-better-user-experience-28af389bf979

![](https://miro.medium.com/max/700/1*jRuAfqzE8HcX2oZtVqTExw.png)

First button does not even look like a button, and looks unfinished

If someone has strong opinions on this, let's discuss

PS: Even Microsoft: https://github.com/microsoft/microsoft-ui-xaml/issues/524#issuecomment-497356510
https://github.com/mrlacey/microsoft-ui-xaml-specs/blob/RoundedCornerVisualizations/active/RoundedCorner/ImageFiles/index.md

**Comment by snitin315** [comment]
+1 for round corners. I will work on this one.

**Comment by iamareebjamal** [comment]
Any updates @snitin315 ?

**Comment by snitin315** [comment]
i will make PR today.

**Comment by kushthedude** [comment]
Updating to semantic UI 3.0.4 should make corners round. Deploy preview of https://github.com/fossasia/open-event-frontend/pull/3872 had rounded corners for buttons.

**Comment by iamareebjamal** [comment]
That's because it breaks the project, not fixes the rounded corner thing. Proper fix is to revert this commit https://github.com/fossasia/open-event-theme/commit/0206df77b4d535b35a8fd4ddbabdb0f36adb0d12

**Comment by AdityaKG-169** [comment]
As I see this issue is still open and is not assigned to anyone, can I work on this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by Deeksha2501** [comment]
Yes , rounded corners are better
I want to work on this issue

**Comment by iamareebjamal** [comment]
@AdityaKG-169 asked first, so maybe if he can't do it, you may take it up

**Comment by Deeksha2501** [comment]
@AdityaKG-169 ok :)

**Comment by Deeksha2501** [comment]
@iamareebjamal 0k :)

**Comment by Deeksha2501** [comment]
@AdityaKG-169 Any updates?

**Comment by dsnehasish74** [comment]
I am a beginer . can I work on it????

**Comment by iamareebjamal** [comment]
@Deeksha2501 You can work on the issue

**Comment by Deeksha2501** [comment]
Thank you! I will start doing it!!!

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by iamareebjamal** [comment]
@Deeksha2501 Any progress?

**Comment by naman360** [comment]
[https://github.com/fossasia/open-event-theme/pull/11](https://github.com/fossasia/open-event-theme/pull/11)
Where are the changes need to be done then?

**Comment by iamareebjamal** [comment]
Use `0.2.1-rounded` version of `@open-event/theme`

**Comment by icoderharshit** [comment]
has this issue been resolved ? or can I work upon it, making it look more appealing.

**Comment by Deeksha2501** [comment]
@iamareebjamal I am getting an error, 
I was not able to run the code in my local machinery , maybe some version mismatch

**Comment by naman360** [comment]
@iamareebjamal so should I start working now on this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by naman360** [comment]
Does `site.overrides` file needs to be changed?

**Comment by iamareebjamal** [comment]
No

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-frontend/issues/4306#issuecomment-626326188

**Comment by naman360** [comment]
Do I need to `gulp build` too?

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-frontend/issues/4306#issuecomment-626598447

**Comment by naman360** [comment]
Okay creating a PR
