### ISSUE TITLE
Moving forward with CSS framework

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4327]
Unfortunately, like most of the stack chosen for the project rewrite, Semantic-UI has been deprecated as well. A fork with name fomantic UI lives on, but all package maintainers are dropping support for semantic UI anyway and there is no semantic-UI-ember package. Right now, we don't have enough resources to do a whole rewrite of the UI of the application, but we can't continue to choke on unmaintained projects, and thus need to plan on what should be done forward. I am against the component framework centric options like semantic-ui-ember, or similarly materialize-react because 

1. They always lag behind the UI framework
2. You have no option on how to migrate when they get deprecated
3. You can't use them if you switch the component framework. For eg, you can't use materialize if you switch from react to vue, or vuetify if you switch from vue to react
4. There is no option on how to use them with purely server side rendering in non-node environments
5. Hard for designers to use them in prototyping tools

Even bootstrap would have been a better solution for us because at least it is not deprecated. I like utility first approach of [tailwind CSS](https://tailwindcss.com/), and it is also framework agnostic so if we switch from ember in future, we won't have to do a lot of rewrite. However, there is a drawback there are no readymade components and we don't have a design guideline of our own. If we had a designer on board, we could have enjoyed a much more professional and unique UI for Open Event which was framework agnostic. Maybe in coming months, we'll have someone on board who is a good enough designer and then we can take up this decision. Second option would be to replicate v1 design in tailwind, which is still better than v2 IMO, and then take it from there, as incremental improvements in tailwind are much easier than in let's say semantic or bootstrap. Tailwind is widely adopted by vue, react, laravel, elixir/phoenix community and very popular unlike semantic UI at the time of its adoption by open event. And I think it is with bootstrap/material design in terms of popularity and it being utility first means that it is used by many more people who implement custom design on their sites and don't use bootstrap and material design. Nevertheless, we should choose one of the popular options only because we don't want to get stuck with unmaintained libraries like we have in past

Nevertheless, once I discuss things with org admins on what to do with design, we can finalize this

**Comment by kushthedude** [comment]
I really like the tailwind approach. But don't you think we should more rely on any frontend framework, we can give [bulma](https://bulma.io) a try. 
Designing all the CSS component will need a team of great designers which we rather lack in community.

**Comment by iamareebjamal** [comment]
I like bulma as well. The problem with bulma is same as with semantic UI. It can stop being maintained anytime. So I would be comfortable going forward with a CSS framework which is extremely popular like bootstrap, material, or any other. Bulma is great because it looks refreshingly different from bootstrap default theme but it's nothing which can't be done by changing some bootstrap defaults to make it look like that. I agree with the amount of work tailwind will take. That is why this is a decision that will be acted upon in a few months, not recently.

Right now, we can just add our suggestions as to which one will be better and also more themeable option so people and we as well can create themes fitting their choice. The choice of semantic UI was made for its themeability, but all we actually did was to remove the rounded corners. And also, if something is unmaintained, it doesn't make it any better that they have themeability. 

It may also happen that fomantic UI works with our setup and we can have some changes in workflow to make it supported with other components and improve design bit by bit. That will take considerably less amount of work on our part. 

But right now, I am stuck with updating to semantic UI 2.4.2, which was upgraded but the dist folder wasn't updated, after updating it, the whole layout breaks apart, but it is working fine with default 2.4.2, so I don't understand the issue. Each week there is some blockers I have to face with the compatibility of the stack. This week it is storybook integration with ember and semantic UI.
