### ISSUE TITLE
Open event and create event text looks small in mobile view

### ISSUE THREAD

**Issue by nlok5923** [fossasia/open-event-frontend#4367]
**Is your feature request related to a problem? Please describe.**
when opening website in mobile the "create event" and "open event" text looks very small.

**Describe the solution you'd like**
a slight increase in font size of those text.

**Describe alternatives you've considered**
increase font size
**Additional context**
![Screenshot_20200508-232701_2](https://user-images.githubusercontent.com/56120084/81434681-6867d080-911b-11ea-9991-c39ee7d48a39.png)

can I work on this issue 
please let me know.

**Comment by snitin315** [comment]
Not a priority

**Comment by kushthedude** [comment]
They are quite visible in any mobile device but we can come later on such UI Tweaks once we have solved major bugs in our project.
Thanks!
