### ISSUE TITLE
Admin not able to edit or delete events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4383]
![Screenshot from 2020-05-17 16-55-36](https://user-images.githubusercontent.com/1583873/82152097-66121e80-985f-11ea-9118-1abd62ce7884.png)

There are test events on the system that clutter the front page. Admins are not able anymore to delete these events, e.g. https://eventyay.com/admin/events/live?search=vit%20tbi%20demo

**Comment by iamareebjamal** [comment]
I can't find the event now and strange because not reproducible locally for other events. Will diagnose more
