### ISSUE TITLE
Enabling Show more Options in Discount Code creation lags

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4398]
1. Go to `http://localhost:4200/events/<event_id>/tickets/discount-codes/create`
2. Click on `Show more Options`
3. Wait for 5 seconds
4. Options show up

Expected:
There should be no delay at all

**Comment by CosmicCoder96** [comment]
can't seem to reproduce it, it's happening almost instantaneously. Tried with empty events, and heavily populated events, is there anything else required to reproduce it?

**Comment by iamareebjamal** [comment]
Just noticed it happens only when DevTools are open. Not a high priority but still curious why?

**Comment by iamareebjamal** [comment]
Bug in Ember Core. Can't do anything about it
