### ISSUE TITLE
[Enhancement] Add specific error in Registration validation

### ISSUE THREAD

**Issue by sparsh-99** [fossasia/open-event-frontend#4399]
**Is your feature request related to a problem? Please describe.**

To reproduce the error:
1. Type any random email without any '@' or '.com/.in etc'
2. Password should be of 8 characters.
3. When you submit, it will show 'Unexpected Error Occurred'

But doesn't show which type of error or which important thing I missed in which specific input. 

![Screenshot (466)](https://user-images.githubusercontent.com/56729873/82730419-13cc7400-9d1d-11ea-88ae-1e1dfcec6fbf.png)

**Describe the solution you'd like**

I suggest that after any validation error, Error should be focussed on that input and error message  reason should be specific.

**Comment by g4rry420** [comment]
Hello @sparsh-99  Can I work on this issue ?

**Comment by sparsh-99** [comment]
@g4rry420 Sure! Go ahead

**Comment by g4rry420** [comment]
@sparsh-99 Questions: The error you are proposing , is it showing on the login  or registration page ? Because I reproduce the same situation you asked above, registration is doing well but the Login page is showing error.

**Comment by sparsh-99** [comment]
Yes, Login page

**Comment by himanshuvarandani** [comment]
Hello @sparsh-99 can I work on thus issue?

**Comment by sparsh-99** [comment]
Sure @himanshuvarandani , go ahead!!
