### ISSUE TITLE
Replace Promise.allSettled by RSVP.allSettled

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4401]
Promise.allSettled is not polyfilled, replace with RSVP.allSettled

Parent: #4181

**Comment by mohak852** [comment]
Sir, I have submitted pull requested for this You can check that

**Comment by EmperorYP7** [comment]
Sir, do review my pull request. I'll be glad to have your guidance on this.

**Comment by Rachit420** [comment]
I am new to github and want to contribute. Can i work on this issue?

**Comment by manutvikash** [comment]
I am new to github can I work in this ?
