### ISSUE TITLE
Event export page GET URL is surrounded by an unnecessary extra box

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#4407]
![image](https://user-images.githubusercontent.com/17252805/82867001-00c1cb80-9ef8-11ea-8c2f-335f6e614c9c.png)

**Comment by codeboy5** [comment]
Can I take this up ?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by sparsh-99** [comment]
I want to work on the issue

**Comment by sparsh-99** [comment]
@CosmicCoder96 Where I can find this issue? In which folder as it a long codebase!

**Comment by Harshad-droid** [comment]
Hi, I want to work on this issue. Can I take this up?

**Comment by partha0047** [comment]
I want to work on this issue

**Comment by amit2699** [comment]
@iamareebjamal  I want to work on this issue

**Comment by prateekj117** [comment]
@amit2699 Go ahead.

**Comment by amit2699** [comment]
Thanks a lot for letting me work on this

**Comment by ShreyanshSrivastava** [comment]
I have solved the issue and created the corresponding pull request, please review it.

**Comment by prateekj117** [comment]
@shreyanshdwivedi You should always ask to work on an issue first. An open source workflow cannot ever sustain for a project where no one knows who is working on what. Plus the main reason behind asking before working is to make sure no two developers are working on the same issue thus saving developer time.

**Comment by amit2699** [comment]
Can I do some enhancement in the Fossasia's Eventyay website ???

**Comment by ShreyanshSrivastava** [comment]
> @shreyanshdwivedi You should always ask to work on an issue first. An open-source workflow cannot ever sustain a project where no one knows who is working on what. Plus the main reason behind asking before working is to make sure no two developers are working on the same issue thus saving developer time.
I regret for this and will keep in mind from the next time.
