### ISSUE TITLE
Unable to display/pull out event's location from Google map 

### ISSUE THREAD

**Issue by edenyay** [fossasia/open-event-frontend#4447]
**Describe the bug**
Unable to display/pull out event/venue's location from Google map when creating an event 

**Expected behaviour**
event/venue's location automatically popped up

**Screenshots**

![Screen Shot 2020-06-07 at 10 13 30](https://user-images.githubusercontent.com/32028823/83959532-19db5c80-a8a8-11ea-8965-25674ef93381.png)
![Screen Shot 2020-06-07 at 10 12 48](https://user-images.githubusercontent.com/32028823/83959533-1ba52000-a8a8-11ea-9607-fcab9d28bc12.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome

**Comment by mariobehling** [comment]
Parts of this issue have been solved. Other parts will be solved as we transition to open street map.
