### ISSUE TITLE
Non-uniform buttons across the application

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#445]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The button sizes are not uniform in the application. 
![screen shot 2017-07-08 at 7 31 58 am](https://user-images.githubusercontent.com/12807846/27981811-fefc36d6-63af-11e7-8a15-a2ed65100199.png)
![screen shot 2017-07-08 at 7 32 29 am](https://user-images.githubusercontent.com/12807846/27981812-ff1a8550-63af-11e7-9bb5-1f9ed2c5e0e2.png)

**Expected behavior:**
All the buttons must be of same size and uniform in design.

**Comment by niranjan94** [comment]
@geekyd I don't feel this is a valid issue. Buttons are elements that can change across the site depending on where and how they are used. It's not always possible to ensure the same size and type of buttons. And even if we did, it wouldn't look very good. Best we can do is, ensure we follow a proper color scheme for buttons and I believe that was already done in a previous issue. 

We have higher priority issues and PRs pending at this point than this.
