### ISSUE TITLE
Adding slider to play the series of photos

### ISSUE THREAD

**Issue by Ritwik880** [fossasia/open-event-frontend#4463]
**Is your feature request related to a problem? Please describe.**
To make a page look more organized  sliders can continuously run or play the series of photos without the need to click anything on the part of the site visitor. This website design tool helps to create an organized and more interactive page.

**Describe the solution you'd like**
One of the functions of sliders is to create pages that appeal visually and spark the interest of the website visitors. By displaying beautiful pictures on your sliders, there’s a better likelihood that your site visitors stick around to browse through the site and read more information about your

**Comment by iamareebjamal** [comment]
Is this a copypasta?

**Comment by Ritwik880** [comment]
No, absolutely not.

**Comment by snitin315** [comment]
>> No, absolutely not.

>To make a page look more organized – especially with a large number of media – sliders can continuously run or play the series of photos without the need to click anything on the part of the site visitor.

https://t3terminal.com/blog/enrich-your-website-with-multipurpose-typo3-sliders/

>One of the functions of sliders is to create pages that appeal visually and spark the interest of the website visitors. By displaying beautiful pictures on your sliders, there’s a better likelihood that your site visitors stick around to browse through the site and read more information about your

https://www.google.com/amp/s/avengering.com/en/using-the-slider-yes-no/amp/

**Comment by iamareebjamal** [comment]
Closing as irrelevant to the project
