### ISSUE TITLE
No margin between the Unpublish and Copy button on Event Overview Page

### ISSUE THREAD

**Issue by ShreyanshSrivastava** [fossasia/open-event-frontend#4468]
**Describe the bug**
There is no margin between the Unpublish and Copy button on Event Overview Page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to manage or create an event.
2. Scroll down to the bottom and publish your event.
3. You will be directed towards the event overview page.
4. In the top-right section, on that page, you will be able to see these buttons.

**Expected behavior**
There should be some margin between the unpublish and copy button

**Screenshots**
          
![bug](https://user-images.githubusercontent.com/62847072/84641922-657dae00-af19-11ea-8ce3-2aa946b03483.png)

**Desktop (please complete the following information):**
 - Applicable for all desktop views

**Comment by ShreyanshSrivastava** [comment]
I want to work on this issue.

**Comment by snitin315** [comment]
I think this is intentional.

**Comment by ShreyanshSrivastava** [comment]
Can somebody confirm this, please!?

**Comment by iamareebjamal** [comment]
No, this bugged me a lot. Please fix this

**Comment by ShreyanshSrivastava** [comment]
I have linked a pull request which seems to solve the issue, I request to review it.
