### ISSUE TITLE
Counting error with the price of donation ticket

### ISSUE THREAD

**Issue by edenyay** [fossasia/open-event-frontend#4475]
**Describe the bug**
There has been some error when we set the price for donation ticket. Sometimes it works, some time it just doesn't. Need to change the numbers up and down a few times. 

**Expected behaviour**
Able to set prices donation ticket normally (as long as min price is smaller than max price)

**Screenshots**
![Screen Shot 2020-06-17 at 16 02 03](https://user-images.githubusercontent.com/32028823/84878502-1ddf5980-b0b4-11ea-9499-3b370feedef0.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS 10.14]
 - Browser [Chrome]

**Comment by khushishikhu** [comment]
may i work on this issue?

**Comment by khushishikhu** [comment]
@edenyay may i work on this issue

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by edenyay** [comment]
@iamareebjamal i tested with a new event, and it seems to me the issue has been fixed. The pricing (min-max) boxes still appear in red color for some reason, but other than that I was able to save/publish the event.

**Comment by iamareebjamal** [comment]
Hi @edenyay, can you please check on https://open-event-frontend-git-fork-maze-runnar-donation.eventyay.vercel.app/ 

Is the issue same as production or solved completely?
