### ISSUE TITLE
notification box is not disappeared by its own after giving wrong input until we press OK.

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#4483]
**Describe the bug**

**To Reproduce**
1. Go to 'https://open-event-frontend.now.sh/'
2. Click on 'Enter Location'
3. Enter the wrong 'Location'
4. Then notification box comes and it will not disappear although we move on
until we press 'OK' it will not disappear by its own
5

. See error

**Expected behavior**
Notification box should be disappeared when the user move o next step

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by himanshujaidka** [comment]
![Screenshot (696)](https://user-images.githubusercontent.com/58654018/85232608-c0356f00-b41d-11ea-87e1-779922d76cc1.png)

**Comment by kushthedude** [comment]
That is not a notification box, it is google-maps API warning box as the keys are not configured & site is unable to list the location.
