### ISSUE TITLE
Tax Information Country Field offers Autofill of other information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4504]
The country field in the tax info offer overlapping auto complete info, if this info is saved in the browser. Expected: The field should not allow autocompletion of data other than the country name.

![Screenshot from 2020-06-29 23-39-21](https://user-images.githubusercontent.com/1583873/86058969-1def3a00-ba62-11ea-9d7c-5c9da6dca138.png)

**Comment by ShreyanshSrivastava** [comment]
I want to work on this issue

**Comment by snitin315** [comment]
go ahead

**Comment by ShreyanshSrivastava** [comment]
I have opened a PR please review it.
