### ISSUE TITLE
Tax information pop up in Wizard step 1 showing up towards bottom of screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4505]
The tax pop up in the wizard step on should show up more towards the top of the screen and it should have a "close" x icon on its top right.

![Screenshot from 2020-06-29 23-39-21](https://user-images.githubusercontent.com/1583873/86059088-5c84f480-ba62-11ea-8ea4-08af90c97aa1.png)

**Comment by ShreyanshSrivastava** [comment]
I don't think we will need a close button at the top right because the cancel button is already serving the purpose of it. Tax pop up is an issue on which I want to work on.

**Comment by maze-runnar** [comment]
@ShreyanshSrivastava please claim one issue at a time and complete that before claiming the next.
