### ISSUE TITLE
Wizard Step 4 Sessions and Speakers: Customize Speaker Form Left Column Text Disappeared

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4506]
The text in the left column of the customize speaker form is no longer visible.

![Screenshot from 2020-06-29 23-45-45](https://user-images.githubusercontent.com/1583873/86059399-f51b7480-ba62-11ea-8092-ed9595bf7b39.png)

**Comment by mariobehling** [comment]
This does not seem to happen at all events, but for example for the OpenTechSummit Thailand: https://eventyay.com/events/026ad713/edit/sessions-speakers

**Comment by iamareebjamal** [comment]
Found the cause. Fixing

**Comment by iamareebjamal** [comment]
Deployed
