### ISSUE TITLE
Unable to Setup project on Local System.

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [fossasia/open-event-frontend#4513]
What i did.
installed ember CLI.
Yarn install.

What now i am facing...
Steps to reproduce the behaviour:
When i execute yarn or yarn install this error throws up.
when comes to (5/5) refreshing packages...

![Screenshot (205)](https://user-images.githubusercontent.com/43263087/86250566-5f045d00-bbce-11ea-9611-83b28eb81a4d.png)
![Screenshot (206)](https://user-images.githubusercontent.com/43263087/86250624-717e9680-bbce-11ea-80d5-094b2769f29b.png)
![Screenshot (207)](https://user-images.githubusercontent.com/43263087/86250635-76434a80-bbce-11ea-9312-f51b86b274ff.png)
![Screenshot (208)](https://user-images.githubusercontent.com/43263087/86250647-7b07fe80-bbce-11ea-965b-56f3b129c332.png)

**Really wanted to contribute to this project**

**Comment by iamareebjamal** [comment]
Install python and node 12, or easiest - Use Linux instead of Windows

**Comment by ShubhamChaudharyy** [comment]
will node v14.4.0 throw err?

**Comment by ShreyanshSrivastava** [comment]
> will node v14.4.0 throw err?

Yes, it will show an error. You can use v12.13.0, it worked for me.

**Comment by kushthedude** [comment]
Try the above-mentioned steps & let us know if it still fails.
Thanks
