### ISSUE TITLE
No custom form data showing on attendee ticket holder's information

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#4519]
**Describe the bug**

No custom form data showing on attendee ticket holder's information

**To Reproduce**
Steps to reproduce the behaviour:
1. Create event with custom forms
2. Complete order for that event by filling in custom form
3. Scroll down to 'Ticket Holder's Information'
4. See error in custom form field

**Expected behaviour**

It should show us filled custom form data

**Screenshots**

![Screenshot_Custom_Form](https://user-images.githubusercontent.com/43299408/86408480-b55bc380-bcd4-11ea-85e4-8d5922b8a1a5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Will work on this.

**Comment by iamareebjamal** [comment]
Please add a screenshot as well

**Comment by anilmaurya61** [comment]
i wanna work on this issue. Please assign this to me and since i'm new to this repo so please guide me through.
