### ISSUE TITLE
[discussion/feature request] Break out event wizard into more steps

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-frontend#452]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Currently the form at the first step of event creation wizard contains ticket, organizer info (I couldn't find it on nextgen.eventyay.com), and many other extra info, which makes the form too long for the first step and affects user experience.

Here's a suggestion to break the event creation flow for better UX:
- Basic event details
- Organiser + social links
- Sponsors
- Tickets
- Session-speakers

Please consider this whenever this falls on your timeline.

**Comment by CosmicCoder96** [comment]
@niranjan94 Your views?

**Comment by niranjan94** [comment]
This was a discussion that also took place last year. The wizard initially actually had 5 stages (if I remember it right). But later we came to what we have now. 

But, we do have to re-think it at some point, but now wouldn't be the time for it IMO. Let's get it to working stage. Until then, I'll mark it as `on-hold` and close the issue. it could be opened later.

**Comment by CosmicCoder96** [comment]
> mark it as on-hold and close the issue

Can be reopened later. Not likely to be relevant in near future.
