### ISSUE TITLE
Possible to publish events without ticket and minimum requirements through Event Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4525]
There are events that dont have a ticket, but they get published to the front page, e.g. https://eventyay.com/e/b303a673 (I added a ticket and unpublished it). I wonder how this happens as the wizard will show an error message, that an event cannot be published without a ticket.

However, there is a "Publish" option on the event dashboard. It is possible to publish an event here without a ticket or other minimum requirements.

Expected: It should not be possible to publish an event on the event dashboard, if minimum requirements are not met.

![Screenshot from 2020-07-04 14-05-26](https://user-images.githubusercontent.com/1583873/86512147-ba696180-bdff-11ea-9116-31796d176ba8.png)

**Comment by iamareebjamal** [comment]
I think they add a ticket and then remove it.

**Comment by Haider8** [comment]
@iamareebjamal I want to work on this issue

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by iamareebjamal** [comment]
But first work on pending featured event PR. Call for speaker section is also missing in that
