### ISSUE TITLE
Start Page not scrollable on mobile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4526]
The start page is not scrollable on Android mobile v10 chrome.

This happens once the event search bar loads.

![Screenshot_20200704_163111_com android chrome](https://user-images.githubusercontent.com/1583873/86514749-37063b00-be14-11ea-8c13-8b8bee3f24bd.jpg)

**Comment by mariobehling** [comment]
After further testing it turns out none of the pages is scrollable.

**Comment by Haider8** [comment]
Also not working on Firefox

**Comment by iamareebjamal** [comment]
@Haider8 Please use git bisect to find since when did this problem start

**Comment by iamareebjamal** [comment]
Bug added here: https://github.com/fossasia/open-event-frontend/commit/68c699679643f25dfd7f161fa37398db037f3822

https://github.com/fossasia/open-event-frontend/pull/4354

**Comment by iamareebjamal** [comment]
Root cause of problem: https://github.com/Semantic-Org/Semantic-UI/issues/6449

**Comment by Haider8** [comment]
Okay. How to fix it now? Fomantic UI?

**Comment by iamareebjamal** [comment]
I have fixed it

**Comment by iamareebjamal** [comment]
For modals we need a workaround but for now, I am going to merge #4538. Please test after merging and report any issues so we can fix it or revert it
