### ISSUE TITLE
Unable to complete a ticket order using discount code 

### ISSUE THREAD

**Issue by edenyay** [fossasia/open-event-frontend#4529]
**Describe the bug**
Event link: https://eventyay.com/e/643cfffb
Discount code: FOSSASIA 
The error appears at the last step of the payment process.
Screenshot of the error

![Screen Shot 2020-07-05 at 23 07 05](https://user-images.githubusercontent.com/32028823/86561244-6b036c80-bf8a-11ea-87ee-692c53efa4b6.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14
 - Browser Chrome

**Comment by iamareebjamal** [comment]
Deployed
