### ISSUE TITLE
Unable to apply discount code for more than 1 ticket

### ISSUE THREAD

**Issue by edenyay** [fossasia/open-event-frontend#4530]
**Describe the bug**
Event link: https://eventyay.com/e/643cfffb
Discount code: FOSSASIA (set to 10 times use)
Cannot select more than 1 discounted ticket even though the number of discount had been set to 10.
Screenshot of the error

![Screen Shot 2020-07-05 at 23 11 22](https://user-images.githubusercontent.com/32028823/86561525-08f73700-bf8b-11ea-98dc-a8cd0ac6e3bf.png)

**Desktop**
OS: Mac OS 10.14
Browser Chrome

**Comment by iamareebjamal** [comment]
Max ticket quantity per order is set to 1 (Show more options in Discount Code detail page)

**Comment by edenyay** [comment]
> Max ticket quantity per order is set to 1 (Show more options in Discount Code detail page)

ah totally forgot about this. Thanks Areeb!
