### ISSUE TITLE
Text Formatting Error: Code of Conduct

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4541]
This feature is not related to a problem. It means to create convenience for event organizers. 
When organizers **Edit Basic Details** of an event, they can add a Code of Conduct, however it is not possible to do any formatting. 

![Screenshot from 2020-07-11 08-35-08](https://user-images.githubusercontent.com/1658742/87218351-1416e200-c352-11ea-992f-90e73b35a142.png)

### Describe the solution you'd like
Simple text formatting is enable.

**Comment by mariobehling** [comment]
Furthermore it should be possible here to add a link into the box where users can find more info.

**Comment by maze-runnar** [comment]
@iamareebjamal , Editing is working fine for me. No such problem as mentioned in the issue.
![Screenshot from 2020-09-07 15-18-41](https://user-images.githubusercontent.com/56407566/92374566-896a1d80-f11d-11ea-9b4b-b5e5ca56e423.png)
