### ISSUE TITLE
Text Formatting Errors: Event Description Field

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4542]
**Describe the bug**
This bug is related to text formatting under event description field. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Edit Event' on 'https://eventyay.com/e/8fa7fd14'
2. Click on 'Basic Details'
3. Scroll down to 'Description'
4. When copy and paste text from another source or even type in the text, often it caused formatting errors. For example, two screenshots below showed one in editing mode and one in live event. 

![Screenshot from 2020-07-11 08-54-22](https://user-images.githubusercontent.com/1658742/87219028-44fa1580-c358-11ea-97d4-cac75e0a7604.png)
![Screenshot from 2020-07-11 08-54-36](https://user-images.githubusercontent.com/1658742/87219032-47f50600-c358-11ea-9f27-90aa180437be.png)

**Expected behaviour**
One of the first thing that organizers do is to fill in the event description. It should be easy for them. Is is possible to implement HTML or markdown formatting?

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Google Chrome

**Comment by hpdang** [comment]
Similar ticket https://github.com/fossasia/open-event-frontend/issues/4541

**Comment by vinay-code123** [comment]
i will like to do

**Comment by maze-runnar** [comment]
the above-mentioned formatting error is due to there is no line break option in the text editor. @iamareebjamal  should I add a line break option in the editor?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
But please focus on only high priority bugs so that we can move forward with current milestone and come back later to old milestones.

**Comment by maze-runnar** [comment]
Which issue next?

**Comment by iamareebjamal** [comment]
You can add delete option in this. Button is already added by me. Only action needs to be added. With a confirmation dialog https://github.com/fossasia/open-event-frontend/issues/4596

**Comment by mariobehling** [comment]
Unfortunately this is not yet working as expected. Line breaks often are not working.

**Comment by shivalikadevi** [comment]
I want to work in this  by adding span class and removing the break line from it.
