### ISSUE TITLE
Order A Free Ticket: Confusing buying process

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4543]
**The system required users to log-in before they can place a free order, the following scenarios currently exist** 

### Registered Email 
- Users log-in with a register email, system asks them to fill in a password or request a new password. After user log-in, they can place the order. This seems to be ok. 
- Users type in a wrong email that is already in the system, it is not possible to edit email in the email field. Users would need to refresh the page, select a ticket again to fill in the new email.

### Unregistered Email 
- Users try to log-in with an unregistered email, system shows two error messages 1) First a red message at the bottom right of the page within seconds saying "unverified user can't place an order", this message quickly disappears, user would need to scroll up to the top of the page when 2) the second message shows up asking to user to verify the account via email. It is unclear how both messages are related to this order. 
![Screenshot from 2020-07-11 09-48-22](https://user-images.githubusercontent.com/1658742/87219491-ed5da900-c35b-11ea-8537-68f087778c89.png)

### Desired Fixes
- Users are able to edit email field when they make a typo mistake
- For unregistered account, a message appear in the central of the page _"To place a ticket order, please verify by clicking on the confirmation link that has been sent to your email. Did not get the email? Please click here to resend"_

**Comment by hpdang** [comment]
@iamareebjamal is there any progress here Areeb?

**Comment by iamareebjamal** [comment]
Yes I'm currently working on it. Will be completed in an hour or so

**Comment by Sinha-09** [comment]
is it still open?

**Comment by iamareebjamal** [comment]
What does it look like?
