### ISSUE TITLE
Unable to Pay: Paypal integration does not seem to work

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4544]
### Unable to Pay for a donation/paid ticket with Paypal

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/8fa7fd14'
2. Click on 'Donation Ticket'
3. Fill in all details and select Paypal 
4. The system is unable to connect to Paypal, See screenshot

![eventyay-paypal-error](https://user-images.githubusercontent.com/1658742/87220220-4c262100-c362-11ea-9ff9-f17ebb374b0a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome and Chromium

**Comment by iamareebjamal** [comment]
Fixed on server and cause of the issue linked
