### ISSUE TITLE
Missing notification emails after an order was made

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4545]
Once an order was made successfully, buyer did not receive a notification email. Organizer also did not receive a notification email that a new order has been received. 

**To Reproduce**
1. Go to 'https://eventyay.com/e/8fa7fd14'
2. Order a free ticket 
3. Check email, no notification. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome and chromium

**Comment by iamareebjamal** [comment]
Discussed this before with Mario. There is no bug from our end, GMail is blocking emails with PDF attachments https://app.sendgrid.com/suppressions/blocks

Since we don't get a callback about email delivery being successful or not, should we remove attachments from order emails?
