### ISSUE TITLE
Event Creation: form filling error 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4546]
This is a minor error happened during the event creation process

**To reproduce**
1. Go to 'Edit Event' on 'https://eventyay.com/e/8fa7fd14'
2. Click on 'Basic Details'
3. Scroll down to 'Event Topic' 

**Selection was made and reflected on the live page**
![Screenshot from 2020-07-11 12-19-26](https://user-images.githubusercontent.com/1658742/87222089-23595800-c371-11ea-9f0e-84f01275a9ba.png)

**But it did not show on the field in the next visit** 
![Screenshot from 2020-07-11 08-53-05](https://user-images.githubusercontent.com/1658742/87222121-76cba600-c371-11ea-8ae6-3f4ab6ec30e3.png)

### Desired Fixes
- The event topic field is saved
- Possibility to leave this field blank
- Possibility to insert a custom topic

**Comment by lopeselio** [comment]
Can I work on this @mariobehling ?

**Comment by iamareebjamal** [comment]
One developer is already working on it, You can take other issues

**Comment by iamareebjamal** [comment]
Happens only with names with `&` in it. Seems like a library issue, which isn't maintained anymore

**Comment by iamareebjamal** [comment]
It is an issue with the library, it does not generate proper key for values with spaces it seems. I don't think fixing and maintaining a dead library is a good choice. @Haider8 Please use https://ember-power-select.com/ for just event sub topics and topics for now
