### ISSUE TITLE
Icons of social media services are no longer on public event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4551]
Social Media Services used to have a logo icon on public event pages. They are no longer there, e.g. https://eventyay.com/e/45da88b7/

![Screenshot from 2020-07-13 11-19-10](https://user-images.githubusercontent.com/1583873/87287871-e9b45880-c4fa-11ea-9e40-4bea5899628a.png)

**Comment by Haider8** [comment]
@iamareebjamal Can I work on this
