### ISSUE TITLE
View action for speaker not working in dashboard

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#4559]
**Describe the bug**

View action is taking us to edit but it should take us to view like for sessions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event first
2. Then create speaker and session for that event
3. Now go to event overview page (e.g http://localhost:4200/events/e1e58b51)
4. Click on `Speakers` tab
5. Now click on `View` in `Actions` column. See the bug

**Expected behaviour**

It should take us to View page like for sessions.

**Screenshots**

![View Speaker Action](https://i.imgur.com/rCDXc87.png "View Speaker Action")

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Firefox

**Additional context**

Will work on this

**Comment by daretobedifferent18** [comment]
I want to work on this issue.

**Comment by daretobedifferent18** [comment]
@Haider8 There is actually no view page for speaker that exists so do I have transit to same page for speaker view action as for session view page?

**Comment by iamareebjamal** [comment]
It needs to be created
