### ISSUE TITLE
Feature: Custom form info for sessions and speakers

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#4560]
**Is your feature request related to a problem? Please describe.**

Right now we are not showing complex custom form info for speakers and sessions. So, it should be shown.

![Session Details](https://i.imgur.com/P8PUzoM.png "No custom form info for session")

**Describe the solution you'd like**

Show custom form info for both session and speaker details

**Describe alternatives you've considered**

**Additional context**

Will work on this

**Comment by mariobehling** [comment]
Closing this in favor of https://github.com/fossasia/open-event-frontend/issues/5100
