### ISSUE TITLE
Footer Pages not showing up on Admin Content Area and Not editable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4564]
On the footer of eventyay.com there are pages for terms and references, contact, refund policy etc. These pages should show up on the content area of admins here https://eventyay.com/admin/content/pages, but they are not available here anymore.

Please show the pages here and make them editable.
![Screenshot from 2020-07-15 10-30-31](https://user-images.githubusercontent.com/1583873/87522984-98d16b00-c686-11ea-8596-647da458aba4.png)

**Comment by akash-arelli** [comment]
@mariobehling  I would like work on this issue. I am a beginner. Please guide me through.

**Comment by iamareebjamal** [comment]
This is not a beginner level bug
