### ISSUE TITLE
Organizer receiving session proposal that was deleted should show message "deleted"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4567]
![Screenshot from 2020-07-16 09-55-09](https://user-images.githubusercontent.com/1583873/87643556-4dcd5b80-c74b-11ea-905c-f06702660287.png)

Steps:
1. An organizer receives an email "New Session Proposal"
2. The organizer clicks on the link, e.g. https://eventyay.com/events/5ac8e4d9/sessions/6259
3. The organizer logs into the system
4. Bug A: The organizer is directed to the front page.
5. The organizer clicks again on the link provided and the page shows the same content as https://eventyay.com/events/5ac8e4d9/sessions/all

Probably the speaker withdrew or deleted their session. Expected: Show a page with the message "Session was withdrawn."

**Comment by maze-runnar** [comment]
As now sessions have their own page and they will redirect organizer to that page and he will see withdrawn status their. And redirection is also working.
![Screenshot from 2021-07-02 18-35-33](https://user-images.githubusercontent.com/56407566/124278915-7c169780-db64-11eb-998d-2cfefda52297.png)
