### ISSUE TITLE
Editing Call for Speakers Date and Time results in null/invalid field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4574]
Editing an existing event date/time call for speakers on wizard step 4 results in an invalid field and cannot be saved, e.g. here https://eventyay.com/events/5ac8e4d9/edit/sessions-speakers

![Screenshot from 2020-07-17 23-12-58](https://user-images.githubusercontent.com/1583873/87831204-13ff7080-c883-11ea-82f8-e0690d58049b.png)

**Comment by Haider8** [comment]
@iamareebjamal I couldn't see the issue. Can you please take a look at it

![edit-speaker-session-datetime](https://user-images.githubusercontent.com/43299408/87854501-1e2b7880-c930-11ea-9fc7-ec3cc9f8509c.gif)

**Comment by iamareebjamal** [comment]
Can't reproduce it myself as well. Please move on to next issue

**Comment by mariobehling** [comment]
Save the event and go back to the form afterwards, please. Also try as an admin on this event: https://eventyay.com/events/5ac8e4d9/edit/sessions-speakers
