### ISSUE TITLE
Email and Password submitted as GET query params in fastboot

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4580]
In fastboot mode, before the hydration happens(which, it being ember, takes multiple seconds), if user submits email and password in login form, the page reloads with email and password as query parameters as form submission happens with those 2 fields. This is a severe issue. The login button and form should 

- [ ] Change to at least POST, so that fields are not sent in the URL
- [ ] The login button should be disabled till content hydration completes

**Comment by SubhradeepSS** [comment]
@iamareebjamal I want to work on this issue, but I am not able to find the login form mentioned in the issue description. Can you please tell me in which folder the login form is present in the repo?

**Comment by iamareebjamal** [comment]
Fastboot is disabled so now, this is not needed
