### ISSUE TITLE
Session Form: There is no must for "Track" to be required (wizard step 4)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4584]
The session forms always show "track" to be required, but some events dont even have tracks. Tracks could be required by the organizer, but they should not be required by the system.

![Screenshot from 2020-07-20 19-58-05](https://user-images.githubusercontent.com/1583873/87970094-8b234780-cac3-11ea-8416-d26d517663b6.png)

**Comment by iamareebjamal** [comment]
This is strange because I couldn't find any event without tracks with sessions enabled. If this is indeed intended to be optional, it'll need changes in backend as well because currently it assumes session to always have a track and might break some things when making it optional

**Comment by mariobehling** [comment]
Yes, this is the case because most of the events on the platform using the session form are run by us and these events are bigger. However, a lot of smaller events dont have tracks. Maybe if changes take a lot of time, do other issues first that have a larger impact to improve the system. But, ultimately "tracks" should not be required.
