### ISSUE TITLE
Submitted Sessions showing up 4 times in "My Sessions"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4588]
Sessions that are submitted show up four times in the my sessions tab at https://eventyay.com/my-sessions/upcoming

Expected:
* Sessions should only show up once
* The session tab should list the name of the session and provide a) the link to the session form as of now and b) to the event page

![Screenshot from 2020-07-20 20-56-50](https://user-images.githubusercontent.com/1583873/87975268-adb95e80-cacb-11ea-9ea4-1df0ce386a2d.png)

**Comment by iamareebjamal** [comment]
Same as #3703

**Comment by mariobehling** [comment]
ahh ok.
