### ISSUE TITLE
My Events: If user bought several tickets the event shows up several times in "My Events" - Expected Ticket Info should show up and Tickets should be Grouped

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4589]
My Events: If user bought several tickets the event shows up several times in "My Events" (https://eventyay.com/my-tickets/ or https://eventyay.com/my-tickets/past) - Expected:
1. On the ticket box/tab on the overview page, the ticket info itself should show up including info on ticket holder and ticket type (including the link to the ticket)
2. Tickets should be grouped within the same event tab (including links to the tickets)
3. A link to the event page should be included instead of linking the entire event area to the ticket
4. Just as of now, the info if an attendee is checked in etc. should show up for each ticket.

![Screenshot from 2020-07-20 20-59-54](https://user-images.githubusercontent.com/1583873/87975852-75fee680-cacc-11ea-84d0-535951d6d306.png)

**Comment by maze-runnar** [comment]
looking into it.

**Comment by iamareebjamal** [comment]
Please fix pending PRs first

**Comment by maze-runnar** [comment]
if the tickets would be grouped in a manner described. How the cancel order will work?

**Comment by maze-runnar** [comment]
@mariobehling grouping of tickets by order is already implemented. So the events are showing number of time orders has been made.
![Screenshot from 2021-07-02 18-41-38](https://user-images.githubusercontent.com/56407566/124279604-563dc280-db65-11eb-8b56-cfafbb256866.png)

Also https://github.com/fossasia/open-event-frontend/issues/4589#issuecomment-757417128.
