### ISSUE TITLE
Change color of copy button from black to blue

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-frontend#459]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![screenshot 11](https://user-images.githubusercontent.com/12716067/28087508-5273b724-66a0-11e7-829f-9f63c2c2753f.png)

for uniformity button color should be blue according to #273

I'll be working on this

**Comment by niranjan94** [comment]
@utkarshnath this is intentional. Copy is neither a positive action nor a negative one. This stays black (neutral) like dismiss buttons.

**Comment by utkarshnath** [comment]
@niranjan94 and what about the black Close button used in models, like in `add-user-role-modal`
