### ISSUE TITLE
Organizer Sessions Tab: View and edit option directing to "my-sessions/..."

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4590]
The view and edit options on the "sessions tab" of organizers direct to a link "my-sessions...". Expected: The link structure to view and edit sessions as an organizer should be in the structure of https://eventyay.com/events/[event-ID]/sessions/[session-ID]

![Screenshot from 2020-07-20 21-08-42](https://user-images.githubusercontent.com/1583873/87976618-b743c600-cacd-11ea-9fb2-fd889417e9c2.png)

**Comment by iamareebjamal** [comment]
Edit option leads to `https://eventyay.com/events/<event_id>/sessions/edit/<session_id>` but view option indeed leads to my-sessions. Should the my-session URL be changed to https://eventyay.com/events/[event-ID]/sessions/[session-ID] for user/speaker as well? If not, same view will be shown at 2 different URLs, leading to maintainence issues

**Comment by mariobehling** [comment]
> Should the my-session URL be changed to [https://eventyay.com/events/[event-ID]/sessions/[session-ID]](https://eventyay.com/events/%5Bevent-ID%5D/sessions/%5Bsession-ID%5D) for user/speaker as well? If not, same view will be shown at 2 different URLs, leading to maintainence issues

Yes, agree. I understand that you want to change the personal URL as well for maintenance issues. I think it would be more suitable than the current version, cause an organizer should not have a session of a speaker of an event under the "my sessions" URL.

And we need to consider this even further, cause the edit sessions form also show up in a URL related to the CfS, e.g. https://eventyay.com/e/0917096d/cfs/edit/6255 vs. the session edit form of the organizer: https://eventyay.com/events/0917096d/sessions/edit/6255

The difference is: The organizer has the option to add a speaker though. We also need the "invite option" for a second and third speaker back (we took it out as it was buggy). So, except for this feature the forms are different.

![Screenshot from 2020-07-20 21-24-38](https://user-images.githubusercontent.com/1583873/87980944-b4989f00-cad4-11ea-88a7-4bdbda8127d2.png)

What is the best thing to do?

**Comment by iamareebjamal** [comment]
I think we keep all URLs for organizer same as most of the things are same and use CFS URL for speaker edit as it is a different view even if most things are same. This will mean that speakers will not be able to see the admin view even if there's a bug in the UI.

So, for organizers - https://eventyay.com/events/0917096d/sessions/edit/6255
For users - https://eventyay.com/e/0917096d/cfs/edit/session/6255

This way we have ensured that all `events/*` URLs are for organizers/admin only. But we should definitely use same URL for my session edit and CFS edit as they are exactly same

**Comment by iamareebjamal** [comment]
@Haider8 View Session URL - /e/<event_id>/sessions<session_id>
