### ISSUE TITLE
Organizer Sessions Tab: Locked Session can be edited, if speaker uses "edit" link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4591]
Organizers have the option to lock sessions, so the speaker does not do further edits, e.g. change the topic of an event. Editing is nevertheless still possible if the speaker remembers the link to edit a session.

Below session is locked, but can be edited through the "edit" link.

![Screenshot from 2020-07-20 21-18-34](https://user-images.githubusercontent.com/1583873/87977196-a182d080-cace-11ea-8e49-829cb701c05e.png)

**Comment by iamareebjamal** [comment]
Need to diagnose if this is allowed on server as well. If not, then it is purely a frontend issue. Or else, it needs to be fixed on server

**Comment by mariobehling** [comment]
I tried it again with different accounts. It seems it is working. Not sure, why it worked before. Maybe I was trying with two admin accounts.

**Comment by iamareebjamal** [comment]
Yes, admin is allowed to edit it anyway. Maybe we need an indicator in UI if something is being edited as an admin
