### ISSUE TITLE
Event Dashboard: Show "View" instead of "Preview" for Live Events, Delete "Copy" Feature

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4592]
The event dashboard shows "Preview" for live events. Expected:
* Show "View"
* Open event link in new tab
* Only show "Preview" for unpublished events

Furthermore, we have a lot of features in the system. To keep the system more simple, for now:
* comment out the feature "Copy an Event" from the top right dashboard.
(We could come back later to this feature, but for now we dont have resources to test and maintain it.)

![Screenshot from 2020-07-20 21-24-38](https://user-images.githubusercontent.com/1583873/87977975-eb1feb00-cacf-11ea-9894-14410f9fdbe2.png)

**Comment by snitin315** [comment]
Taking this up.
