### ISSUE TITLE
Attendee Form: Editing the form sometimes suddenly shows field of organizer custom forms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4597]
Attendee Form: Editing the form sometimes suddenly shows field of organizer custom forms, e.g. compare https://eventyay.com/events/a2b1a68e/edit/attendee

![Screenshot from 2020-07-21 16-46-10](https://user-images.githubusercontent.com/1583873/88069434-bc5a5100-cb71-11ea-8df7-b31e391574e1.png)

**Comment by iamareebjamal** [comment]
I don't understand "Organizer Custom Form", did you mean "Speaker Custom Form"?

**Comment by mariobehling** [comment]
> I don't understand "Organizer Custom Form", did you mean "Speaker Custom Form"?

Yes, sorry. You are right. 

The forms of wizard step 4, suddenly shows up as part of the form in wizard step 2.
