### ISSUE TITLE
Implement tickets API for public/index

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#460]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Implement tickets API for the public/index route

Reference: https://open-event-api.herokuapp.com/#tickets

**Comment by CosmicCoder96** [comment]
on hold only until the migration is fixed , right now error 500 is there on tickets route.
