### ISSUE TITLE
Session Status Change: Send Status Change with Email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4604]
When the status of submissions is changed by organizers or speakers themselves, e.g. from Pending to Accepted, the organizer should have the option to send speakers an automated email about the status change. There should be a pop up when the organizer selects "Send Email" with two sections a) the standard section as below and b) with a field where the organizer could add additional information. 

In this email add the organizer email in CC, but also provide a tick box "Organizer in CC", with the tick box pre-selected. So, the organizer would have to tick off if he/she does not want to receive the email in CC.

Further Development in Future:
In future we should also have an option for the organizer to add an "Reply to" address. 

The emails are developed here: https://docs.google.com/document/d/1TgkU_Wvm-849z-CjubD-AvDVhmgfotB-agoP5NWusEQ/edit#

Pending (Speaker submitted session)
From: no-reply@eventyay.com
CC: organizer email
Subject: Your Speaker Submission for [Event Name] titled [Session Name]
Text:
Hello,

This is an automatic message from eventyay.com. We have received your submission [Session Name] for [Event Name] on [Event Date]. 

Your proposal will be reviewed by the event organizers and review team.

The current status of your session is now “Pending”. You can also check the status of your submission on the session page [link to session page]. You need to be logged in to view it.

In case organizers have additional information for you, you can find it below this message.

More details about the event are on the event page at [Link to public Event Page].

Thank you.

https://eventyay.com

===============================
Message from the Organizers

[Message from Organizers here or leave it empty if no message was added]
===============================

Accepted (Organizer has accepted the session.) 
From: no-reply@eventyay.com
CC: organizer email
Subject: Accepted! Congratulations Your Submission for [Event Name] titled [Session Name] Has Been Accepted

Text:
Hello,

This is an automatic message from eventyay.com. 

Your session status for the submission [Session Name] for [Event Name] was changed to “Accepted”. Congratulations!

Your proposal will be scheduled by the event organizers and review team. Please (re)confirm your participation with the organizers of the event, if required.

You can also check the status and details of your submission on the session page [link to session page]. You need to be logged in to view it.

In case organizers have additional information for you, you can find it below this message.

More details about the event are on the event page at [Link to public Event Page].

Thank you.

https://eventyay.com

===============================
MESSAGE FROM ORGANIZERS

[Message from Organizers here or leave it empty if no message was added]
===============================

Rejected: (Session rejected by organizer.)
From: no-reply@eventyay.com
CC: organizer email
Subject: Not Accepted. Your Submission for [Event Name] titled [Session Name] Was Not Accepted
Text:
Hello,

This is an automatic message from eventyay.com. 

Unfortunately your submission [Session Name] for [Event Name] was not accepted. Your session status was changed to “Rejected”.

The status change was done by event organizers. If there are questions about this change please contact the organizers.

You can also check the status and details of your submission on the session page [link to session page]. You need to be logged in to view it.

In case organizers have additional information for you, you can find it below this message.

More details about the event are on the event page at [Link to public Event Page].

Thank you.

https://eventyay.com

===============================
MESSAGE FROM ORGANIZERS

[Message from Organizers here or leave it empty if no message was added]
===============================

Confirmed (Organizers confirmed the session of the speakers.)
From: no-reply@eventyay.com
CC: organizer email
Subject: Confirmed! Congratulations Your Submission for [Event Name] titled [Session Name] Has Been Confirmed
Text:
Hello,

This is an automatic message from eventyay.com. 

Your session status for the submission [Session Name] for [Event Name] was changed to “Confirmed”. Congratulations!

Your proposal will be scheduled by the event organizers and review team. Please inform the event organizers in case there are any changes to your participation.

You can always check the status and details of your submission on the session page [link to session page]. You need to be logged in to view it.

In case organizers have additional information for you, you can find it below this message.

More details about the event are on the event page at [Link to public Event Page].

Thank you.

https://eventyay.com

===============================
MESSAGE FROM ORGANIZERS

[Message from Organizers here or leave it empty if no message was added]
===============================

Canceled (Organizers cancel the speaker session for some reason.)
From: no-reply@eventyay.com
CC: organizer email
Subject: Canceled! Your Submission for [Event Name] titled [Session Name] Was Canceled
Text:
Hello,

This is an automatic message from eventyay.com. Your session status for the submission [Session Name] for [Event Name] was changed to “Canceled”.

The status change was done by event organizers. If there are questions about this change please contact the organizers.

You can also check the status and details of your submission on the session page [link to session page]. You need to be logged in to view it.

In case organizers have additional information for you, you can find it below this message.

More details about the event are on the event page at [Link to public Event Page].

Thank you.

https://eventyay.com

===============================
MESSAGE FROM ORGANIZERS

[Message from Organizers here or leave it empty if no message was added]
===============================
Withdrawn
From: no-reply@eventyay.com
CC: organizer email
Subject: Withdrawn. Your Submission for [Event Name] titled [Session Name] Has Been Withdrawn
Text:
Hello,

This is an automatic message from eventyay.com. Your session status for the submission [Session Name] for [Event Name] was changed to “Withdrawn”.

The status change was done by event organizers or by yourself. If there are questions about this please contact the organizers.

You can also check the status and details of your submission on the session page [link to session page]. You need to be logged in to view it.

In case organizers have additional information for you, you can find it below this message.

More details about the event are on the event page at [Link to public Event Page].

Thank you.

https://eventyay.com

===============================
MESSAGE FROM ORGANIZERS

[Message from Organizers here or leave it empty if no message was added]
===============================

**Comment by edenyay** [comment]
hi @mariobehling, follow up on the issue with discussed during open-event meeting, I've tried out papercall.io. And the flow as below:

1. Organizer's dashboard where they can change the status of the session - the TWO far end buttons: to notify a specific speaker or notify all speakers whose sessions accepted. 

![Screen Shot 2020-08-04 at 15 00 51](https://user-images.githubusercontent.com/32028823/89269401-0bb97a80-d664-11ea-9284-90e034e54d81.png)

2. When you hit either the button, the same window pops up as below
![Screen Shot 2020-08-04 at 15 00 21](https://user-images.githubusercontent.com/32028823/89269754-8d110d00-d664-11ea-9f82-deb35575b16d.png)

**Comment by mariobehling** [comment]
Ok, makes sense to do it that way. So, a good implementation would be:
a) Separate "Changing Status" and "Sending Email"
b) Implement a column for "Notify"
c) Open a pop similar to the above where organizers can change a custom message
d) Once the notification has been sent show "Sent" in the notification column and an icon or button next to it "Resend"

In further development (in separate issue) we should also
* give speakers the option to "confirm" their participation by visiting a link in the example above

**Comment by iamareebjamal** [comment]
@mariobehling There is a major blocker in terms of adding different types of emails for different state changes. @divs4debu told me about it on call. The database will need to be migrated and notification types will be needed to change and there are a lot of compatibility issues.

This is because current implementation uses `SESSION_ACCEPT_REJECT` as email key and the same is used as action in messages/mail/notification DB tables. So, this is not just a code level change but a DB level change as well. This should never have been the case, and now we can't change this without proper migrations and similar changes for other actions and then we'd need to have a discussion over whether new types of mails should be saved in DB for each session state or be grouped under `SESSION_STATE_CHANGE`. So, should we have a quick call regarding how it should be handled or should I just implement email popup with these placeholders and no saving in DB for now? The implication of just implementing email popup for now is that DB will contain no separate notification type except `SESSION_ACCEPT_REJECT` and all notifications/mails will be listed under it even though they may be due to other state changes. Later, we can rename this to `SESSION_CHANGE` but then admin won't be able to filter through specific notifications/emails and also not be able to change default messages for emails of each state change (which is still not working BTW)
