### ISSUE TITLE
Attendee Form Design Issue: "custom form" option shows up even if Feature is turned "off" + Info text unreadable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4607]
1) The attendee form in wizard step 2 can be switched on or off. 
Expected: The custom form option should only be visible if the attendee form is switched on.

 2) The text below "information about attendee form" is not readable as the grey color is to bright on many screens.

![Screenshot from 2020-07-21 16-28-59](https://user-images.githubusercontent.com/1583873/88196906-07dc3000-cc42-11ea-89cd-bb2543d8fb70.png)

**Comment by ruhci28** [comment]
Hii @mariobehling  i made the following changes .
![Screenshot 2020-07-27 at 10 02 53 PM](https://user-images.githubusercontent.com/59759735/88567371-04d3ac00-d055-11ea-98ea-48a2e3b9b555.png)
1.) I change the text color of text below Information about attendee form . 
2.) I also made the custom form field input visible when the attendee form is turn on . 
![Screenshot 2020-07-27 at 10 06 48 PM](https://user-images.githubusercontent.com/59759735/88567735-83304e00-d055-11ea-8cdc-a6b7e96ba638.png)
