### ISSUE TITLE
Call for Speakers: Only show Twitter Widget on Event Pages that are listed on the left side bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4608]
The twitter sidebar widget shows up on all kinds of pages and even on the speaker submission pages (session page and speaker page).

Expected: Only show twitter widget on the event pages linked on the left hand side, e.g.:
Show: https://eventyay.com/e/0917096d

Do not show on: 
https://eventyay.com/e/0917096d/cfs/edit/session/6255
https://eventyay.com/e/0917096d/cfs/edit/speaker/4763
https://eventyay.com/e/0917096d/cfs/new-session

![Screenshot from 2020-07-22 17-53-02](https://user-images.githubusercontent.com/1583873/88198776-58548d00-cc44-11ea-96c9-75312c976c7d.png)

**Comment by ayushsatyam146** [comment]
I would like to work on this issue @mariobehling.
Can you please explain about the twitter widget thing, It's not clear from the screenshot posted.
In the example https://eventyay.com/e/0917096d widget is on right.
From my understanding, I think that we need the twitter widget on left instead of right on the event pages.

**Comment by iamareebjamal** [comment]
No

**Comment by ayushsatyam146** [comment]
What does No mean
I can't work on this or something else

**Comment by iamareebjamal** [comment]
> I think that we need the twitter widget on left instead of right on the event pages.

No

**Comment by ayushsatyam146** [comment]
okay but can I work on this

**Comment by iamareebjamal** [comment]
Yes

**Comment by ayushsatyam146** [comment]
Thanks, also can you mention the pages where the widget is needed

**Comment by iamareebjamal** [comment]
Already mentioned in the issue

**Comment by ayushsatyam146** [comment]
Thanks, will try my best

**Comment by snitin315** [comment]
I will fix it.

**Comment by iamareebjamal** [comment]
@snitin315 Status?

**Comment by snitin315** [comment]
Wip.

**Comment by snitin315** [comment]
@iamareebjamal I am unable publish an event with speaker-and-session on.
![Screenshot at 2020-08-05 18-00-18](https://user-images.githubusercontent.com/46647141/89413042-bd7ca800-d745-11ea-8fd6-379dc0143248.png)

**Comment by iamareebjamal** [comment]
That's because the array was added in the component and tickets are being deleted in the mixin which is common to all the steps
https://github.com/fossasia/open-event-frontend/pull/4692/files#diff-fb7ee4f92b345d827ec7615d16a3c08dR235

**Comment by snitin315** [comment]
> Do not show on:
https://eventyay.com/e/0917096d/cfs/edit/session/6255
https://eventyay.com/e/0917096d/cfs/edit/speaker/4763
https://eventyay.com/e/0917096d/cfs/new-session

and 
- `/e/:id/speakers`
- `/e/:id/sessions`

**Comment by iamareebjamal** [comment]
> Expected: Only show twitter widget on the event pages linked on the left hand side, e.g.:

Sessions and Speakers page both have the left panel

**Comment by snitin315** [comment]
Cfs have the left panel too

**Comment by snitin315** [comment]
I get it.
