### ISSUE TITLE
Forms: Social Media - Only request to fill in short form, e.g. username for link specification

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4609]
Make social media links on all forms in a way that users only need to add their username or other short forms.

Relevant Forms:
* Wizard step two social links
* Attendee Forms
* Speaker submission forms
* Speaker profile form

E.g. show as follows
Twitter https://twitter.com/___________
Github https://github.com/___________
Linkedin https://www.linkedin.com/____________
Instagram https://instagram.com/______________
Facebook https://facebook.com/_______________
YouTube https://youtube.com/________________

![Screenshot from 2020-07-22 17-20-27](https://user-images.githubusercontent.com/1583873/88201787-30ffbf00-cc48-11ea-8cbb-9a693ded63af.png)

**Comment by ruhci28** [comment]
HIi @mariobehling  i want to work on this issue

**Comment by snitin315** [comment]
Go ahead.

**Comment by ruhci28** [comment]
![Screenshot 2020-07-24 at 4 00 51 PM](https://user-images.githubusercontent.com/59759735/88382924-156ef280-cdc7-11ea-87c2-ea26564c2dfc.png)
Hii @snitin315 is i am going right .?

**Comment by ruhci28** [comment]
Hii @snitin315 do I have to create an account to create an event locally

**Comment by snitin315** [comment]
> Hii @snitin315 do I have to create an account to create an event locally

Yes

**Comment by snitin315** [comment]
> ![Screenshot 2020-07-24 at 4 00 51 PM](https://user-images.githubusercontent.com/59759735/88382924-156ef280-cdc7-11ea-87c2-ea26564c2dfc.png)
> Hii @snitin315 is i am going right .?

Looks like expected behavior for basic-details step. We have separate fields for Github and etc links in attendee , speaker forms too as mentioned in Issue description.

**Comment by ruhci28** [comment]
okay I will change those to

**Comment by ruhci28** [comment]
Hii @snitin315  i created an account but the gmail validation link is not working . and the attendee , speaker form are blocked .

**Comment by ruhci28** [comment]
![Screenshot 2020-07-24 at 5 31 52 PM](https://user-images.githubusercontent.com/59759735/88389188-9af89f80-cdd3-11ea-9c45-ed704c3ccbdd.png)

**Comment by snitin315** [comment]
You need to enter required details and click on Forward (at bottom ) to move to next step.

**Comment by ruhci28** [comment]
after feeling all the details also the forward button is disable

**Comment by ruhci28** [comment]
Email verfication link is not working .

**Comment by ruhci28** [comment]
it giving response of Not found

**Comment by snitin315** [comment]
Probably you have `eventyay.com` in your verification link, try changing it to `localhost:4200`

**Comment by ruhci28** [comment]
Thanks, it worked

**Comment by ruhci28** [comment]
![Screenshot 2020-07-25 at 7 17 42 PM](https://user-images.githubusercontent.com/59759735/88458419-91db0180-ceab-11ea-93ed-715ec571580a.png)
![Screenshot 2020-07-25 at 7 08 18 PM](https://user-images.githubusercontent.com/59759735/88458422-956e8880-ceab-11ea-91cb-484b66eb1729.png)
![Screenshot 2020-07-25 at 5 59 43 PM](https://user-images.githubusercontent.com/59759735/88458458-d1095280-ceab-11ea-81c8-b5cdbde4b96e.png)
Hii @snitin315  can you please review it. The attendee form is taking social links as normal input.

**Comment by iamareebjamal** [comment]
This is not what Mario meant. He meant that twitter field should have `https://twitter.com/@` as fixed part and rest username to be filled by user. Similar with Instagram and others with fixed part of URL being already present. What possible use could we have for providing a dropdown for Instagram with option of youtube.com? That'll create even more confusion

**Comment by ruhci28** [comment]
Thansks @iamareebjamal  for the review . I will make it as expected.

**Comment by ruhci28** [comment]
can anyone help me with this
![Screenshot 2020-07-26 at 12 16 35 PM](https://user-images.githubusercontent.com/59759735/88473329-ffce0a00-cf39-11ea-9614-e7fa4b0644e2.png)

**Comment by snitin315** [comment]
This is maybe due to recent change in schema, please try rebasing your branch with `development` again.

**Comment by iamareebjamal** [comment]
You need to run `python manage.py db updgrade` for migrating the database schema

**Comment by snitin315** [comment]
From the screenshot it seems she is using hosted development api.

**Comment by iamareebjamal** [comment]
Hmm, yeah. Seems like a migration issue

**Comment by iamareebjamal** [comment]
Try now

**Comment by snitin315** [comment]
I can access this page without any errors.
 https://open-event-frontend.now.sh/admin/content

**Comment by snitin315** [comment]
Wait, I dont have an admin account still I can access that route. 

I cant access /admin
But i can acess /admin/settings

**Comment by snitin315** [comment]
The same behavior on production. Needs to fix it ASAP. 
/cc @iamareebjamal

**Comment by iamareebjamal** [comment]
It's working fine https://api.eventyay.com/v1/settings

**Comment by iamareebjamal** [comment]
You can see the page but can't make any modifications as there are server side authorization checks on place. However, raise a separate issue for this bug

**Comment by ruhci28** [comment]
> Try now

It's Working now

**Comment by ruhci28** [comment]
![Screenshot 2020-07-27 at 7 03 10 PM](https://user-images.githubusercontent.com/59759735/88547825-e1503780-d03b-11ea-829a-2bb439bb89c9.png)
Hii @iamareebjamal  and @snitin315  i think i should remove the dropdown . Can anyone suggest me how can i make this type of input without a dropdown.

**Comment by snitin315** [comment]
Please create a PR and lets move the discussion there.

**Comment by ruhci28** [comment]
okay

**Comment by mariobehling** [comment]
The recent changes resulted in only covering very few social media services. Services that were previously covered in this feature are no longer covered, e.g.

- GitHub
- Gitlab
- Vimeo
- Blog
- Flickr
- Any other major social media platform
- Custom (User should be able to add own detail here)

Please add other major services and enable the user to use "Custom".

E.g. = example. It does not mean only the mentioned services should be covered. All services that were previously covered should still be covered after the changes. Therefore reopening this issue. Thanks.

**Comment by snitin315** [comment]
I will update

**Comment by snitin315** [comment]
> enable the user to use "Custom".

Regarding `custom`, we can add an `other` option in the dropdown and allow the user to fill the corresponding URL.
