### ISSUE TITLE
Implement sponsors API for public/index

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#461]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Implement sponsors API for public/index route

Reference: https://open-event-api.herokuapp.com/#sponsors

**Comment by harshitagupta30** [comment]
Can I work on this?
