### ISSUE TITLE
Basic Event Info External Links: Simplify Form by offering dropdown options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4610]
Currently the Form for social event links in the wizard step 1 requires the user to fill the name of a social media service. 

Expected: 
1. Offer a dropdown menu of all kinds of social media services and require the user to only fill in the user name.
2. Change the name "External Event URL" to "Website"

![Screenshot from 2020-07-22 18-23-07](https://user-images.githubusercontent.com/1583873/88202232-dca90f00-cc48-11ea-98f5-bb030d81d660.png)

**Comment by ruhci28** [comment]
![Screenshot 2020-07-24 at 4 18 16 PM](https://user-images.githubusercontent.com/59759735/88384092-667fe600-cdc9-11ea-8322-fb1ff63f3e6a.png)
Hii @mariobehling  I changed the name "External Event URL" to "Website"

**Comment by snitin315** [comment]
Taking this up.

**Comment by mariobehling** [comment]
Related to https://github.com/fossasia/open-event-frontend/issues/4609
