### ISSUE TITLE
Basic Event Details: Enable option Online Events or Mixed Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4611]
With an increasing number of online events that don't have a location, we should also offer the possibility to run events without a location or event with a location and an online presence (mixed events).

Therefore please change the basic details wizard as follows:
* create 4 buttons
  * Venue
  * Online event
  * Mixed event
  * To be announced

![Screenshot from 2020-08-09 06-06-43](https://user-images.githubusercontent.com/1583873/89724913-57c04280-da09-11ea-80f3-4d99a657c210.png)

When the user clicks the buttons:
- [x] Location - keep options as is
- [x] Online event, add following and show this on the public event page:
  - [x] Show a field in section online events for "Live streaming (Optional): https://________________________"
  - [x] Show a field in section online event for "Webinar (Optional): https://____________________________"
  - [ ] Show a tick box "Details will be shared as follows (e.g. you can share links in the session info: _Add__message___here." If the user chooses this message, display this message if the user on the public event page.
- [x] Mixed event: Show both the form for Location and Online event.
- [x] To be announced: Show the message "Details to be announced." on the public event page in the respective area.

![Screenshot from 2020-07-22 18-35-27](https://user-images.githubusercontent.com/1583873/88204086-1aa73280-cc4b-11ea-9d5a-1eb34cb9aed8.png)

**Comment by Aaishpra** [comment]
@mariobehling can i work on this?

**Comment by snitin315** [comment]
Yes

**Comment by Aaishpra** [comment]
![image](https://user-images.githubusercontent.com/66299533/89099061-593aab00-d40a-11ea-8e51-4760a7ac0cd3.png)
I wanted to add the checkbox in front of the Location and Online Events field but to add it in front i will have to change the display of the labels from block to inline but i was unable to find the code in open-event-frontend.css 
@snitin315 can you help me with this
And another question if we are going to make the location field disappear when ticked off then what is the use of location  in required class.

**Comment by Aaishpra** [comment]
@snitin315 i wanted to ask if we are going to make the location field disappear then shouldn't it be removed from the required class

**Comment by snitin315** [comment]
Yes it won't be a required field then, but either of the field must be present to publish the event.

**Comment by Aaishpra** [comment]
@snitin315 
I wanted to add the checkbox in front of the location field but to do so i think i would have to change the display from flex to inline 
,but i couldn't find the css file to do so
![image](https://user-images.githubusercontent.com/66299533/89120777-88b6e980-d4d6-11ea-9ed0-48e6d9e26c25.png)
can you please try to help me by telling where would i have to add the css code to make the display inline and also to add the java code to make the fields disappear and appear (on the above mentioned conditions) .

**Comment by snitin315** [comment]
We use Ember.js, inspecting is a good idea but it wont help much in this case. Also No need to cahnge CSS.
Find the corresponding file inside templates folder and you will know what to do next.

**Comment by Aaishpra** [comment]
Sure thanks for helping out.

**Comment by Aaishpra** [comment]
@snitin315 Do we also need to provide link validations in webinar and live streaming fields under online events section

**Comment by iamareebjamal** [comment]
> Show a tick box "Details will be shared as follows (e.g. you can share links in the session info: _Add__message___here." If the user chooses this message, display this message if the user on the public event page.

I don't understand this

**Comment by mariobehling** [comment]
> > Show a tick box "Details will be shared as follows (e.g. you can share links in the session info: _Add__message___here." If the user chooses this message, display this message if the user on the public event page.
> 
> I don't understand this

Instead of the previous tickboxes, where you can add a URL. In this tickbox show something like this:
* [ ] Details will be shared later.___________________________________

In the "_________" the organizer can add some text/message.

In the final display it would show:
" Details will be shared later. [Message of organizer here]

**Comment by maze-runnar** [comment]
@iamareebjamal for online events there would be a section like this? 
![Screenshot from 2020-08-28 13-54-56](https://user-images.githubusercontent.com/56407566/91538898-24047880-e936-11ea-9516-382fd83aa1f7.png)

**Comment by iamareebjamal** [comment]
Not yet. Just simple text fields. I'm working on this one. Server part is complete. Doing the frontend part now. Please take up https://github.com/fossasia/open-event-frontend/issues/4671, or other high priority issues

**Comment by iamareebjamal** [comment]
Some points are remaining so reopening

**Comment by mariobehling** [comment]
I think it is good enough for now and we can move to other topics. Can close it.
