### ISSUE TITLE
Simplify footer and change to 4 column instead of 5 column

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4612]
The current features of the footer would need more attention and resources, while not giving a lot of benefit. There are a number of bugs in this area. But actually a simpler footer would also serve its purpose. Therefore please simplify the footer as follows:

* Change 5 columns to 4 column
* Left align columns
* Heading "Connect With Us" -> capital W in with, capital U in us
* Provide options in the admin content area for each column here https://eventyay.com/admin/content (no hardcoding of links instead give the admin the option to change it)

The intended footer content is as follows, but the links on the support site have to be created still partly.

**Use Eventyay**
How it Works -> https://support.eventyay.com
Pricing -> https://support.eventyay.com/pricing
Event Blog -> https://blog.fossasia.org/tags/open-event

**Plan Events**
Online Registration -> https://support.eventyay.com/online-registration
Sell Event Tickets -> https://support.eventyay.com/sell-tickets
Event Management Software -> https://support.eventyay.com/open-event-software

**Find Events**
Browse Local Events -> https://eventyay.com/explore
Get the Eventyay App -> https://eventyay.com/attendee-app
Organizer App -> https://eventyay.com/organizer-app

**Connect With Us**
Blog -> https://http://blog.fossasia.org/tag/open-event/
Facebook -> https://www.facebook.com/eventyay/
Twitter -> https://twitter.com/eventyay
GitHub -> https://github.com/fossasia/open-event-orga-server/
YouTube -> https://www.youtube.com/fossasiaorg

![Screenshot from 2020-07-22 19-12-08](https://user-images.githubusercontent.com/1583873/88207979-d74fc280-cc50-11ea-92bc-266851da608a.png)

**Comment by chetas411** [comment]
hey @mariobehling  Can i work on this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by chetas411** [comment]
I am getting an error with ember-cli while deploying the project locally on my pc.
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located
please help

**Comment by snitin315** [comment]
It's a warning ignore it.

**Comment by chetas411** [comment]
I run the command ember serve but it's not working it's showing building but taking very long time and still not start running on localhost

**Comment by chetas411** [comment]
Do I also  need to change the background color to the color shown in the screenshot ?
Also I am a beginner so just want to confirm that I have to work on the files named **_footer-main.hbs_** and _**footer.scss**_ to make the code changes?

**Comment by iamareebjamal** [comment]
No change in color required

**Comment by chetas411** [comment]
Ok, please confirm I have to make changes only in the files _**footer-main.hbs**_ and _**footer.scss**_ ?

**Comment by iamareebjamal** [comment]
Wherever the changes are required to make footer 4 columned

**Comment by chetas411** [comment]
I am not able to find the file that contains data which is passing in the handlebar expressions in _**footer-main*.hbs*_ file as i need to add the new content for the intended footer.

**Comment by snitin315** [comment]
You can use the GitHub search feature.

**Comment by mariobehling** [comment]
Some small items are remaining
* Left align columns
* Heading "Connect With Us" -> capital W in with, capital U in us
* Provide options in the admin content area for each column here https://eventyay.com/admin/content (no hardcoding of links instead give the admin the option to change it)

**Comment by iamareebjamal** [comment]
I think last point should be handled in #4564

**Comment by snitin315** [comment]
I agree, last point should be handled there.

**Comment by snitin315** [comment]
I will fix the alignment and here.

**Comment by chetas411** [comment]
Please review my PR to this issue:
https://github.com/fossasia/open-event-frontend/pull/4690
