### ISSUE TITLE
Ticket Order Page shows 0 Tickets bought instead of 2 Tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4613]
The order pages do not seem to show the correct numbers of tickets bought. A user who bought 2 tickets has 0 tickets showing on his order page, e.g. here https://eventyay.com/orders/89e637e6-a281-41d5-9153-6b24f7defa3b/view

![Screenshot from 2020-07-22 21-42-12](https://user-images.githubusercontent.com/1583873/88221177-5c90a280-cc64-11ea-9510-3ae5567f8da2.png)

**Comment by iamareebjamal** [comment]
![Screenshot from 2020-07-23 04-00-33](https://user-images.githubusercontent.com/3874064/88235745-1bff4c00-cc99-11ea-930e-7313fba1c4eb.png)
Showing 2 for me

**Comment by mariobehling** [comment]
Ok, I understand. Here are the steps:
1. Go to https://eventyay.com/events/5ac8e4d9/tickets/attendees/completed
2. Click on Ticket 89e637e6-a281-41d5-9153-6b24f7defa3b
3. Click "back" in browser and click on the second ticket 89e637e6-a281-41d5-9153-6b24f7defa3b
4. Click back a few times and check the tickets again -> They will show sometimes 1 ticket, 0 ticket or 2 tickets.

**Comment by maze-runnar** [comment]
Working fine for me.

**Comment by iamareebjamal** [comment]
Go back and forth a couple of times. It is a bug in ember but a bug nonetheless
