### ISSUE TITLE
Admin Social Links (System): Change Google+ Icon to Google Groups Icon and add Instagram

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4617]
1. We still use Google Groups icon on the footer links. Please change it to Google Groups and take out the "+" sign.
2. Please add Instagram as an additional social link option

Admin link for footer is: https://eventyay.com/admin/content

![Screenshot from 2020-07-23 10-02-10](https://user-images.githubusercontent.com/1583873/88264154-96e15a80-cccb-11ea-8884-8bbb366ce591.png)

![Screenshot from 2020-07-23 10-03-20](https://user-images.githubusercontent.com/1583873/88264257-c1cbae80-cccb-11ea-84a8-8822952123f3.png)

**Comment by Neilblaze** [comment]
@mariobehling Can assign me this issue please? Also, is the redirection link for Instagram social link this - `https://www.instagram.com/fossasia/` since there aren't any Eventyay instagram page?

**Comment by Neilblaze** [comment]
@mariobehling Can you assign me this issue please? Also, is the redirection link for Instagram social link this - `https://www.instagram.com/fossasia/` since there aren't any Eventyay instagram page?
