### ISSUE TITLE
Forms: Disable Browser Autofill Option for Country Fields in Forms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4618]
Several forms have a country fields. If the browser has stored data it provides autofill options. This distorts the view and functionality of the country form fields. Please deactivate autofill option in browsers for country fields in:
* [ ] Attendee form
* [ ] Billing Information of Attendees during ticket payment process
* [ ] Billing Information in Tax (Wizard Basic Details Step 1)
* [ ] Billing Info of account https://eventyay.com/account/billing/payment-info
* [ ] Speaker Submission Form in call for speakers
* [ ] Check system if there are any other country fields that need to be changed

![Screenshot from 2020-07-23 10-25-23](https://user-images.githubusercontent.com/1583873/88266233-29372d80-cccf-11ea-8312-53072dffc127.png)

**Comment by snitin315** [comment]
Taking on this.

**Comment by chetas411** [comment]
Please review my PR @mariobehling @snitin315 @iamareebjamal
