### ISSUE TITLE
Forms: Gender Fields need to be clicked twice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4619]
Gender fields in attendee form (and speakers form) need to be clicked twice before the input is accepted (at Chrome, possibly other browsers as well).

Expected: One click should be sufficient.

![Screenshot from 2020-07-23 10-33-16](https://user-images.githubusercontent.com/1583873/88266714-f0e41f00-cccf-11ea-8745-b69446699253.png)

**Comment by ruhci28** [comment]
Hii @mariobehling  can i work on this issue.?

**Comment by mariobehling** [comment]
Hi, no need to ask if no-one else is working on things. Please go ahead and make a PR for any solution. Thanks
