### ISSUE TITLE
Order Page: Card image when using Stripe Payments not showing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4620]
The should be a small card image when users pay with Stripe. It is missing.

![Screenshot from 2020-07-23 10-16-44](https://user-images.githubusercontent.com/1583873/88266863-3bfe3200-ccd0-11ea-81d0-d743fa1874be.png)

**Comment by snitin315** [comment]
I found the issue, will send a fix.

**Comment by KKVANONYMOUS** [comment]
@mariobehling I want to work on this

**Comment by KKVANONYMOUS** [comment]
@mariobehling  I was unable to reproduce the issue, since I'm new to the platform, so can you please explain me how were you able to do that?

**Comment by snitin315** [comment]
Create an event -> enable payment by stripe -> buy a ticket -> pay via stripe -> See Error
