### ISSUE TITLE
Publish/Unpublish: Show pop-up to confirm choice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4621]
Publishing or unpublishing an event is a bit step. Therefore we should have a confirmation pop-up if someone publishes or unpublishes an event on the event dashboard here:

![event-nav](https://user-images.githubusercontent.com/46647141/88275853-b09a9600-ccfb-11ea-85a7-aa26387180f5.gif)

1. If an organizer wants to publish an event here, please show a pop up with the following text:
This will publish the event and the event will be visible on the Internet. Please confirm you want to publish your event.
[Yes] [Cancel, Do Not Publish it Now]

2. If an organizer wants to unpublish an event here, show a pop up with the following text:
This will unpublish your event. It will not be accessible to the public on the Internet anymore if you continue. The data of the event will still be available on your dashboard, but tickets, call for speakers or any other features will no longer be available online. Do you want to unpublish your event now?
[Yes, Unpublish it] [Cancel]

3. Please change the button colors as follows:

- View - Green
- Unpublish - Orange
- Preview - Gray (as now)
- Publish - Green

**Comment by snitin315** [comment]
I will take this up.

**Comment by Haider8** [comment]
@snitin315 Can I please take this issue in case you haven't started working on this?

**Comment by snitin315** [comment]
Sure, go ahead :+1:

**Comment by iamareebjamal** [comment]
Colors are still not changed

**Comment by Haider8** [comment]
Will send a separate PR

**Comment by snitin315** [comment]
@Haider8 can I implement the color part? only If you haven't started working on it.

**Comment by iamareebjamal** [comment]
@snitin315 Go ahead
