### ISSUE TITLE
Tickets: Take out "Ticket Group" from Ticket Settings and add pop-up to "Hide Ticket" instead

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4623]
The ticket group option makes sense logically, but users who are new to the system do not understand it even though it is similar to Eventbrite. The ticket group option in the ticket settings allows organizers to define ticket access through a specific code.

### Please change the feature as follows:
* Take out the ticket group option UI from the ticket settings
* Add a pop-up to when the user clicks "Hide Ticket"
* The pop-up text states the following: "To sell hidden tickets you need to set up an access code under Event Dashboard > Tickets Tab > Access Code. [OK] [Cancel]"
  * If the user chooses "OK" add the tick in the tick box
  * If the user chooses "Cancel" do not add a tick in the box
* Change text "Ticket would still be available for sale to Organizers." -> "To sell hidden tickets you need to set up an access code under Event Dashboard > Tickets Tab > Access Code.".

### Test
**Please test the feature**
1. Create an event with a hidden ticket.
2. Check that the hidden ticket does not show up on the public event pages.
3. Create an access code for the hidden ticket type.
4. Apply the access code to the public event page.
5. Order a hidden ticket on the event page, where you use the access code.

**Report any issues you encounter in the process.**

![Screenshot from 2020-07-23 19-45-41](https://user-images.githubusercontent.com/1583873/88320581-10a23400-cd1e-11ea-89b2-a2acf50e1c61.png)

**Comment by ruhci28** [comment]
Hii, I want to work on this issue

**Comment by ruhci28** [comment]
HIi, using a didUpdate method on checkbox opens the pou up on every update . does anyone have better alternative of didUpdate .
