### ISSUE TITLE
Display of Error Message too Short and often not Easy to be Seen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4626]
Error Message often appear as a pop up on the bottom of the page and they disappear to fast. The user is also not able to copy error messages.

Please suggest and implement a better way for error messages, that:
* Do not disappear until the user has resolved them (if the user is able to resolve them at all)
* Do not show up as a pop up, but instead show up on the page itself where the user sees them right away (or e.g. when the error appears auto-scroll the page automatically to the error message on the page itself)

![Screenshot from 2020-07-23 20-10-56](https://user-images.githubusercontent.com/1583873/88322204-a8088680-cd20-11ea-9f21-d8bdb5234434.png)

**Comment by snitin315** [comment]
We can disable auto-hiding of these notifications by setting `closeAlert: null`, or we can increase the time duration by default it's 2.5 seconds`
https://github.com/adopted-ember-addons/ember-notify#examples

**Comment by iamareebjamal** [comment]
This should follow the UX where if a user hovers over the message, the message timer stops and message does not dismiss until the user removes the mouse from the message. Secondly, message size and position should be changed more appropriately

**Comment by ikartikgautam** [comment]
Hii, Can i take this up and fix this ? please assign it to me. Thank you

**Comment by snitin315** [comment]
Go ahead
