### ISSUE TITLE
A non admin user can see some admin pages

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4639]
**Describe the bug**

**To Reproduce**
1. Go to `/admin/settings`

**Expected behavior**

Users should not be able to see any of the admin pages. 
![Screenshot at 2020-07-26 14-58-11](https://user-images.githubusercontent.com/46647141/88475759-75dd6b80-cf50-11ea-837b-7494ae0a0b9c.png)

**Screenshots**

![Screenshot at 2020-07-26 14-55-31](https://user-images.githubusercontent.com/46647141/88475768-85f54b00-cf50-11ea-94e8-a67214d47960.png)

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**

**Comment by mariobehling** [comment]
Confirming this for the following strings:
/admin/sessions/all
/admin/content
/admin/settings

Furthermore, it is even possible for those users to perform some actions.

**Comment by iamareebjamal** [comment]
Those actions will be rejected by the server. I have verified this. If any action is being allowed, this is serious and server needs to be fixed. Please mention the actions as then only frontend fix won't be sufficient
