### ISSUE TITLE
Ticket Form: Pre-fill tickets with standard ticket data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4649]
When an organizer creates a ticket, please pre-fill the ticket form with standard content as follows:
* Free Ticket: In field ticket name "Free Ticket", in field quantity "100"
* Paid Ticket: In field ticket name "Standard Ticket", in field quantity "100"
* Donation Ticket: In field ticket name "Donation Ticket", in field quantity "100", in field minimum "1", maximum "10000"

Just as now, the fields stay editable, but we potentially increase the setup process by having some standard data pre-filled.

![Screenshot from 2020-07-28 10-55-49](https://user-images.githubusercontent.com/1583873/88642563-f1f6c100-d0c0-11ea-9986-583b5f4bd2c4.png)

**Comment by snitin315** [comment]
I will take this up.
