### ISSUE TITLE
Implement Organizer Contact Form

### ISSUE THREAD

**Issue by edenyay** [fossasia/open-event-frontend#4652]
**Is your feature request related to a problem? Please describe.**
Currently if the organizers don't publish their contact in the event listing, the attendees won't be able to contact them even after they purchase the ticket and get the confirmation email.

**Describe the solution you'd like**
Add a link into the confirmation email where attendees can reach out to organizers via a contact form (or a better way?)

**Sample way of contacting organizers from Eventbrite**

In the confirmation email (after completing an order), there is a button to contact the organizer

![Screen Shot 2020-07-28 at 19 44 57](https://user-images.githubusercontent.com/32028823/88667111-24c5a700-d10b-11ea-9400-eaeff6fccff5.png)

Then they will direct us to eventbrite login and where we can fill in a contact form

![Screen Shot 2020-07-28 at 19 45 26](https://user-images.githubusercontent.com/32028823/88667410-89810180-d10b-11ea-92d7-ab04d609984b.png)

**Comment by mariobehling** [comment]
We need to implement a form to achieve this.

@edenyay  The next question is who receives the email? Is it the organizer only or all co-organizer? How does Eventbrite handle this?

**Comment by mariobehling** [comment]
Also: Does the organizer have the option to answer from within the system or simply replies by email in Eventbrite? How should we do this? It is better to handle less communication through our platform and rather use standard emails.

E.g. maybe instead of a form we could also consider providing a custom temporary email address for each event. Emails to this email address would then be forwarded to the organizer of an event. Theoretically we could also provide a message board (similar to Airbnb), but better if all users use their own email system instead as it is less error-prone (we dont need to worry about too many errors on our side).

**Comment by edenyay** [comment]
> @edenyay The next question is who receives the email? Is it the organizer only or all co-organizer? How does Eventbrite handle this?

After sending the form. there was a notice saying that organizers will reply in some days. Then I logged back to organizer account of that event (like 10 mins after), no notification popped up. Not sure if we need to wait for 24 hrs or something. Will update on this. 

![Screen Shot 2020-08-03 at 11 09 02](https://user-images.githubusercontent.com/32028823/89145188-329b8200-d57a-11ea-89e1-6f3ee909b60f.png)

**Comment by edenyay** [comment]
@mariobehling as the organizer, I receive an no-reply email within in like 10 minutes from eventbrite containing the email of the attendee (as they have provided that into the contact form earlier). And this is the end of eventbrite's role. The organizers can choose to contact the attendees directly or to ignore it. Not sure if co-organizer also receives same email. More tests need to be done to confirm this. 

![Screen Shot 2020-08-03 at 16 24 13](https://user-images.githubusercontent.com/32028823/89168109-8de36980-d5a6-11ea-9fc3-76f77924d900.png)

**Comment by mariobehling** [comment]
A contact form would be a good idea now. As we are starting to charge for the event we need attendees to be able to contact organizers through a form. So, at least after we have the invoicing system live we should provide a way to contact organizers.

**Comment by mariobehling** [comment]
So, here is a way, we could implement it:

- [ ] Add a button “Contact Organizers” next to “Refund button” below ticketing (only viewable by logged in users)
- [ ] Provide a contact form (dedicated page, pop-up or other suitable option / only viewable by logged in users)
- [ ] Send an email 
  - [ ] to the owner and all organizers of the event 
     - [ ] show all emails in “To” field, so the organizers can see who received the email
     - [ ] define user (sender) email as a reply, so a response does not go to the eventyay email
  - [ ] Show “eventyay” as the the sender (do not show the emails of the organizers in email header), use “no-reply” address and start email as follows: “Hello, you have contacted the organisers of the event {event name}. Below you find a copy of your email. Organisers have received your message and will follow up with you. This is a system message. Please do not reply to this message. Replies are not monitored. Thank you.”
- [ ] After sending show a message to the sender “Your message was sent to the organizers of this event. You should receive a copy of the message to your email inbox. The organizers will contact you by email.”

**Comment by mariobehling** [comment]
Closing this in favor of a new issue with a more concise description.
