### ISSUE TITLE
Front Page: Call for speakers not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4657]
Events with an open call for speakers are not showing up on the front page. Right now the Nextcloud event should be showing up here for example.

![Screenshot from 2020-07-29 11-34-43](https://user-images.githubusercontent.com/1583873/88783814-8f202b00-d18f-11ea-8b7c-711e5b781adc.png)

This is similar to https://github.com/fossasia/open-event-frontend/issues/4481

**Comment by iamareebjamal** [comment]
Same as #4481, will be fixed in #4653

**Comment by Haider8** [comment]
Yes, both Nextcloud Conference 2020 and OpenTechSummit Thailand are visible after #4653 fix.
