### ISSUE TITLE
Basic Details Wizard Step 1: Change "Name" to "Event Name", change "Owner..." to "Organizer..."

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4660]
1. Change "Name" to "Event Name" in the wizard form (step 1).

![Screenshot from 2020-07-29 23-18-40](https://user-images.githubusercontent.com/1583873/88854740-08506a00-d1f2-11ea-88a1-4adff33018c2.png)

2. Change Owner
a) Add owner information to -> Add Organizer or Group Information
b) Owner Name to -> Organizer or Group Name
c) Owner Description to -> About the Organizer or Group

![Screenshot from 2020-07-29 23-35-18](https://user-images.githubusercontent.com/1583873/88856223-6716e300-d1f4-11ea-86b5-0b8e474a6c0f.png)

**Comment by snitin315** [comment]
Taking on this.
