### ISSUE TITLE
Create "Organizer/Group Profiles" Feature

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4662]
For future features like recurring events it is important to keep the set up process simple. A feature that can help here is the "Group Profile" feature. An group page needs to provide the feature "follow group" and show events on the group page.

Please provide the option of group features as follows:

**1. Private Pages**
- [x] Add "Group" in the dropdown menu above "Manage Events" using the slug /orgs/
- [x] Show two tabs
- [x] Following /orgs/following
- [x] Organizations at /orgs/my-orgs
- [x] Show the button on top right "Create Group"
- [x] Implement the feature "Create a New Group" (which slug should that be?)
![Screenshot from 2020-07-29 23-52-28](https://user-images.githubusercontent.com/1583873/88857467-9cbccb80-d1f6-11ea-8e5d-7f47f431a00d.png)

**2. Public Pages**
Provide a public "Group" page at `/[groupname]` with the following fields:
 - [x] Organizer or Group Name
 - [x] Organizer/Group Logo
 - [x] About the Organizer or Group
 - [x] Organizer/Group Image (similar to meetup on to be shown on top of organizer page)
 - [x] Website
 - [x] Social Media
 - [x] Follow
 - [ ] Contact (when clicking the contact form opens, for logged in users only)
 - [x] Show list of upcoming and past events with image and link to it
- [x] Show an "Edit Button" for org owners directing to an edit form at `/[groupname]/edit`

-  [x] **Team page**
~~Open question is how to implement the team permissions? Also in comparison to team permissions of an event?~~ Done

![Screenshot from 2020-07-30 00-04-19](https://user-images.githubusercontent.com/1583873/88858410-3df85180-d1f8-11ea-9a18-7d1e235ec32a.png)

Related to https://github.com/fossasia/open-event-frontend/issues/5041

**Comment by maze-runnar** [comment]
I was thinking the same

**Comment by MeghalBisht** [comment]
@mariobehling What is meant by contact form? Do we need contact link and email option similar to exhibitors? Or something as a contact organizer when ordering tickets.
