### ISSUE TITLE
Payment Form: Billing Information Correct Sorting, do not make required and fix Country dropdown

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4670]
The payment form in the Billing Information tab (https://eventyay.com/account/billing/payment-info) needs to be fixed:
* [x] Add a helper text above the form as follows: "The information you provide here will be added to your invoices. Please ensure you have the correct information added here as it is not possible to regenerate invoices with different information at a later time."
* [x] Correct Form Sorting as follows
  - Payment Information
  - Company
  - Contact Name
  - Phone
  - Address
  - Zip Code
  - City
  - State
  - Country
  - Tax ID or Business ID
  - Additional Information
* [x] Do not make fields required in this form (let the users decide what they need)
* [ ] Fix Country dropdown. It automatically shows data saved in the browsers instead of using the dropdown country option

![Screenshot from 2020-07-30 10-25-29](https://user-images.githubusercontent.com/1583873/88901228-d4f0f800-d250-11ea-8ba8-36f41ba0394a.png)

**Comment by Raunaksingh100** [comment]
can i work on this issue???? @mariobehling

**Comment by sarthakhanda** [comment]
please me to work on this issue!

**Comment by sarthakhanda** [comment]
please allow me to work on this issue!

**Comment by snitin315** [comment]
Go Ahead

**Comment by amit2699** [comment]
Can I work on this as well.....

**Comment by snitin315** [comment]
No, it will lead to duplucate work. Please check on some other issues.

**Comment by amit2699** [comment]
Okay sure No problem

**Comment by sarthakhanda** [comment]
- [ ] Do not make fields required in this form (let the users decide what they need)
- [ ] Fix Country dropdown. It automatically shows data saved in the browsers instead of using the dropdown country option

not sure how to fix these two. Any suggestions? @snitin315

**Comment by snitin315** [comment]
First try to complete the first two items in the list and create PR. Then we can discuss more.

**Comment by sarthakhanda** [comment]
@mariobehling @snitin315 I've linked a PR regarding this issue. Please review it so i can proceed to the remaining issues.

**Comment by snitin315** [comment]
Github has a nice feature to link PRs to issues. Please use it.
