### ISSUE TITLE
Wizard: Simplify UX by separating step 1 into two steps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4671]
The wizard step one has increase complexity over time. A number of fields are not necessary to publish an event. We can simplify the user experience by adding a step 2 and moving some of the form elements to step 2. Please implement it as follows:

* Add a step two with the heading "Additional Info and Settings"
* Move the following fields to step 2:
  * Links and Social Media
  * Listing Privacy
  * Add Code of Conduct
  * License of Event Data and Content

![Screenshot from 2020-07-30 16-03-00](https://user-images.githubusercontent.com/1583873/88932285-29f73300-d27e-11ea-8d71-c1c20f19df86.png)

**Comment by himanshujaidka** [comment]
It is beginner-friendly issue to

**Comment by himanshujaidka** [comment]
I'm working on it

**Comment by himanshujaidka** [comment]
I have created new option but how to link it with the main form? @mariobehling
