### ISSUE TITLE
Ticket Forms (Basic Details): All tickets are expanded when user edits "Basic Details"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4672]
When editing an event all ticket types are expanded. Expected: Tickets should only be expanded if the user clicks the settings symbol to expand them. And tickets should also be expanded when they are created, but they should not be expanded when the user revisits the wizard to edit details.

Follow up to https://github.com/fossasia/open-event-frontend/issues/4624

![Screenshot from 2020-07-30 16-02-27](https://user-images.githubusercontent.com/1583873/88932352-3ed3c680-d27e-11ea-8c53-ae0bf1dd2938.png)

**Comment by himanshujaidka** [comment]
Assign this issue to me @mariobehling

**Comment by mariobehling** [comment]
Go ahead. Simply make a PR when ready. We dont have a dedicated policy assigning issues to new devs.

**Comment by himanshujaidka** [comment]
ok @mariobehling
