### ISSUE TITLE
Wizard: Make Event Saving, Draft Mode, Publishing Clearer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4673]
**1. When event is created and still unpublished (Draft Mode)**
* _Requirement_ for saving a draft is only
  1. to have an event name
* show buttons:
  * Discard (only when event was never saved - when creating the event: It does not save the event and discards any data that was entered. After that direct user back to dashboard of all events. If user has saved an event previously, there is no "Discard" possible anymore, then show "Cancel" and send user back to specific event dashboard.)
  * Cancel (cancels changes of the wizard step and exists to event dashboard)
  * Save/Previous (except for first step)
  * Save/Next (saves changes and goes to the next step, except for last step)
  * Save (saves draft and exits wizard to dashboard)
* below the above option show another section with two buttons
  * Show a horizontal line with 100% width of the page
  * Show the text "This event is currently not published. It is in draft mode and it is not visible publicly."
  * Preview (open in new tab)
  * Publish (opens a pop up - same as "Publish" on the dashboard / afterwards exits to event dashboard). Please show this button as "gray" as long as the event does not have the minimum data listed necessary for publishing an event.

![Screenshot from 2020-07-30 18-16-43](https://user-images.githubusercontent.com/1583873/88947873-78fa9380-d291-11ea-835b-54dcaee5d322.png)

**2. After an event is published already (Live Event)**
* _Requirement_ for an event to be publishable is, that it has
  1. A name
  2. A location or online event link
  3. A ticket
* below the above savings/next/previous options show another section with two buttons
  * Show the text "This event is published. Any changes you make will appear on your live event."
  * View (open in new tab)
  * Unpublish (opens a pop up - same as "Unpublish" on the dashboard / afterwards exits to event dashboard)

![Screenshot from 2020-07-30 18-23-19](https://user-images.githubusercontent.com/1583873/88948192-e9a1b000-d291-11ea-8d4b-5a1f6ff928d9.png)

**3. Top menu "Wizard Steps"**

When a user clicks a top wizard menu item the following action should take place:
* Cancel changes of the current tab and load the menu tab

![Screenshot from 2020-07-30 19-24-21](https://user-images.githubusercontent.com/1583873/88954380-9718c180-d29a-11ea-947c-ed60dc6ffda6.png)

**Comment by maze-runnar** [comment]
working on it.

**Comment by maze-runnar** [comment]
@mariobehling , state of event is set to draft by default so how to implement` discard.` How to know event was never saved, because it's state is already set to draft

**Comment by mariobehling** [comment]
As long as an event is not saved in the first step of the wizard, the event is not saved and therefore any information entered can be discarded. Pressing discarded in that case will bring the user back to the event dashboard.

**Comment by mariobehling** [comment]
I updated the description as follows

  * Discard (only when event was never saved - when creating the event: It does not save the event and discards any data that was entered. After that direct user back to dashboard of all events. If user has saved an event previously, there is no "Discard" possible anymore, then show "Cancel" and send user back to specific event dashboard.)

**Comment by iamareebjamal** [comment]
@maze-runnar If `event.id` is null, the event is not saved
