### ISSUE TITLE
Edit Session Option for Speakers missing from Session Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4684]
On the session page the "Edit Session" option should be available when a speaker visits their session page, e.g. compare https://eventyay.com/e/1442/sessions/6255

![Screenshot from 2020-07-31 08-27-10](https://user-images.githubusercontent.com/1583873/89007660-73d92b00-d309-11ea-8294-822fd7a9cd33.png)

**Comment by Haider8** [comment]
@iamareebjamal Can I work on this

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
The session is locked. That's why it is uneditable
