### ISSUE TITLE
Standardize URLs and edit URLs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4685]
URLs are not well standardized in the system. Many system show a "node" and provide an option to edit a node by attaching `/edit`.

Please implement the same for URLs in the system such as
* Organizer session change https://eventyay.com/events/0917096d/sessions/edit/6255 to https://eventyay.com/events/0917096d/sessions/6255/edit
* Speaker session change https://eventyay.com/e/0917096d/cfs/edit/session/6255 to https://eventyay.com/e/0917096d/cfs/session/6255/edit
* Wizard e.g. change https://eventyay.com/events/5ac8e4d9/edit/basic-details to https://eventyay.com/events/5ac8e4d9/basic-details/edit
* check any other editing fields and change them accordingly

**Comment by divs4debu** [comment]
working on it

**Comment by divs4debu** [comment]
I have completed for sessions end point. Currently working for basic-details.

**Comment by iamareebjamal** [comment]
eventyay.com/events/5ac8e4d9/edit/basic-details to eventyay.com/events/5ac8e4d9/basic-details/edit will require major architectural changes as each section is nested under edit route and has specific code calls under this route. Is this change very necessary @mariobehling ?

**Comment by mariobehling** [comment]
Ok, lets move it to lower priority and discuss this later. It was just confusing to me to see different structures like sessions/edit/6255 and cfs/edit/session/6255. I dont understand why similar functionality has a different URL structure.

**Comment by mariobehling** [comment]
But it seems @divs4debu is able to make this work. So, please proceed as you see fit.
