### ISSUE TITLE
Change tests from assert.ok to specific test cases

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4689]
assert.ok is not fit for any checking except those returning booleans, it was copy-pasted without checking actual use cases. When a test fails, it is important to know what was expected and what was actual value, but assert.ok tells you:

Expected: true
Actual: false

🤷 

Replace assert.ok with specific methods like `assert.dom(element).includesText` which will tell what the actual value and expected value was if a test fails

**Comment by divs4debu** [comment]
@iamareebjamal  can i work on this issue

**Comment by iamareebjamal** [comment]
Go ahead. See this for reference https://github.com/fossasia/open-event-frontend/pull/4686/files#diff-27a6a4f44820c18fbe4f53e645a5a20fR15
