### ISSUE TITLE
Admin: Make Events Sortable According to Featured and Promoted Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4696]
In the admin section at https://eventyay.com/admin/events/ events cannot be sorted according to featured and promoted events. Please implement this.

![Screenshot from 2020-08-01 13-05-04](https://user-images.githubusercontent.com/1583873/89100548-0c4dd900-d3f8-11ea-99f9-56b806649571.png)

**Comment by maze-runnar** [comment]
taking it up.
