### ISSUE TITLE
Front Page: Standardize Logic and Admin Control to list events (promoted, featured, cfs etc.) on start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4697]
We have tried different ways to control events automatically that we want to show up on the front page. It is time to standardize a logic how events show up on the front page.

**1. Featured Events**

This is easy. Any event that is switched to "Featured Event" by admins is listed here.

**2. Upcoming Events**

Cat a)
* [x] up to 21 events should be listed here
* [x] admins should have the option to move any event without restrictions to the top of this line by switching events to "Promoted Events" in the event admin panel
 * [x] promoted events should always show up on the top of "Upcoming Events"

Cat b)
* [ ] other than that there are the following requirements for events to show up here (if they are not promoted). The event should have
  * [x] location or online link and a date
  * [ ] tickets
    * [ ] Once tickets are sold out the event should not be promoted to the front page anymore
    * [x] Once the ticket sales period has ended the event should not be promoted to the front page anymore
  * [x] an event image
  * [x] an event logo
  * [x] Event Type
  * [x] Event Topic
  * [x] Event Sub-topic
  * [ ] a Twitter link added
 
**3. Call for Speakers**

* [ ] Up to 12 events should be listed here and there should be a "more link" below to show more events on the cfs page if there are more events
* [x] Events listed here have a
  * [x] Call for Speakers
  * [x] Everything that is in "Cat b" of Upcoming events

**4. Admin Section**

* [ ] In https://eventyay.com/admin/settings add a sub tab "Front Page"
* [ ] Show 3 sections: Featured Events, Upcoming Events, Call for Speakers
* [ ] Below each section list the requirements to be listed in the section (as listed above)

![Screenshot from 2020-09-03 19-41-29](https://user-images.githubusercontent.com/1583873/92149018-b1a40480-ee1d-11ea-97b5-eb7a6fbc8b4e.png)

**Comment by maze-runnar** [comment]
I am taking this one.

**Comment by iamareebjamal** [comment]
This is not as high priority, please pick a bug from scheduler milestone

**Comment by mariobehling** [comment]
This has been mostly solved and we can follow up on other areas later. Thank you!
