### ISSUE TITLE
Reminder Email: Implement email to finish creation of an event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4702]
Add an email and notification to remind organizers to finish their event setup. Eventbrite has a similar feature to compare.

Subject of Email: 
`Your event [Event Name] has not been published`

Text: 

```
Hello!

This is an automatic email about your event setup of [Event Name].

The event you created under the name [Event Name] has not been published yet.

You can still finish setting up your event and control your event settings through the dashboard here: 
[Link to event dashboard]

If you have questions about creating events, please check out more FAQs and our documentation at https://support.eventyay.com

Best Regards,

Your Eventyay Team

https://eventyay.com
```

![Screenshot from 2020-08-02 14-12-07](https://user-images.githubusercontent.com/1583873/89122814-c57ce380-d4ca-11ea-89f0-e2ca1449b0ca.png)

**Comment by snitin315** [comment]
It shoupd be transferred to server repo.

**Comment by ArunTeltia** [comment]
How to reproduce this error ?

**Comment by snitin315** [comment]
Its not an error. Its a feature you have to implement it.

**Comment by ArunTeltia** [comment]
oh okay so can i use nodemailer for adding this feature to send the message to the organizer who haven't finish thier setup?

**Comment by snitin315** [comment]
Not actually, see how other mails are sent. (in open-event-server repository)

**Comment by ArunTeltia** [comment]
Okay
