### ISSUE TITLE
Publish/Unpublish: Colors not as before after update to fomantic UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4711]
Publish/Unpublish: Colors not as before after update to fomantic UI. The colors are expected as below and implemented in PR https://github.com/fossasia/open-event-frontend/pull/4668

![Screenshot at 2020-07-30 10-29-16](https://user-images.githubusercontent.com/46647141/88882955-a70bb380-d250-11ea-9614-3d4a762c289d.png)

![Screenshot at 2020-07-30 10-29-03](https://user-images.githubusercontent.com/46647141/88882963-aecb5800-d250-11ea-9f68-a910a126bf69.png)

**Comment by snitin315** [comment]
I will take a look at this.

**Comment by snitin315** [comment]
It's not due to fomantic UI update. This bug was introduced in #4674 .

Sending a fix.
