### ISSUE TITLE
Wizard Step 3 and Step 4: Not possible to save draft

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4712]
The wizard in step 3 and 4 cannot save the event as expected.

In step 3 e.g. https://eventyay.com/events/921345bd/edit/sponsors is shows "Fill in required fields", whereas the option to use the form is switched off (but it was switched on and off before).

In step 4 there is not event an error message, but pressing "Save Draft" does not result in any action, e.g. at https://eventyay.com/events/921345bd/edit/sessions-speakers

Topic related to https://github.com/fossasia/open-event-frontend/issues/4673

![Screenshot from 2020-08-05 12-19-04](https://user-images.githubusercontent.com/1583873/89401892-4e3b8f80-d716-11ea-88be-5a887d35797a.png)

**Comment by maze-runnar** [comment]
working on it.
