### ISSUE TITLE
Cropper modal in event-create wizard is not correctly positioned

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#4716]
**Describe the bug**
Cropper modal in event-create wizard is not correctly positioned

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/create
2. Click on select event image
3. See error

![Screenshot from 2020-08-05 23-19-24](https://user-images.githubusercontent.com/56407566/89446424-237f2480-d772-11ea-99d2-5bb8dda9ff6e.png)
![Screenshot from 2020-08-05 23-19-29](https://user-images.githubusercontent.com/56407566/89446434-267a1500-d772-11ea-9807-b0522bd9d3d6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I will work on it.

**Comment by maze-runnar** [comment]
This was issue with fomantic, As project is switched back to semantic this is solved.

**Comment by iamareebjamal** [comment]
There are still other places where modals don't display correctly on screen

**Comment by maze-runnar** [comment]
the problem arises on account section of user because, <Widgets::Forms::ImageUpload> is set in 3 wide field.
If we move this field to center, or go more column then cropper is correctly positioned

**Comment by sansyrox** [comment]
@iamareebjamal @maze-runnar , do we still have this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by sansyrox** [comment]
![Screenshot 2020-10-08 at 9 03 20 PM](https://user-images.githubusercontent.com/29942790/95480619-b5d9b980-09a9-11eb-8fbc-508d4d8caa2d.png)

Is it a browser-specific or an os dependent behavior? As it's working correctly on Chrome OSX.

**Comment by iamareebjamal** [comment]
This is the file picker. Issue is about cropper dialog

**Comment by sansyrox** [comment]
Ah. Sorry, my bad. Cropper dialog is also working fine for me though.

![Screenshot 2020-10-08 at 9 26 47 PM](https://user-images.githubusercontent.com/29942790/95483607-14ecfd80-09ad-11eb-9570-1a9e7753f00d.png)
