### ISSUE TITLE
Front Page: Question Marks instead of Location Search Box 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4717]
The front page shows questions marks at the area of the location search box for events.

This could have happened after the update to fomantic or after deactivating Google Maps APIs that might still have been active in the system.

As this is right in the middle of the front page, we should try to get this issue resolved asap.

![Screenshot from 2020-08-05 22-47-37](https://user-images.githubusercontent.com/1583873/89462933-748d1980-d76e-11ea-85f3-b9425767e86b.png)

**Comment by iamareebjamal** [comment]
This happened previously as well and also doesn't happen always

**Comment by maze-runnar** [comment]
@iamareebjamal the PlacesAutocomplete is not working at the time, so can we make this field as a  normal Input field instead of `<Widgets::Forms::PlacesAutocomplete/>`  this issue will also resolve permanently.

**Comment by iamareebjamal** [comment]
Yes
