### ISSUE TITLE
improper alignment in attendees,order and overview routes on mobile view

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#472]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

the content is left aligned on mobile view
![image](https://user-images.githubusercontent.com/20153241/28226777-f51cf6b0-68f4-11e7-958d-b746a9a307dc.png)
![image](https://user-images.githubusercontent.com/20153241/28226808-11e8af6e-68f5-11e7-9b8f-b5e8c1beeb8a.png)

**Expected behavior:**

they should be centered aligned like access code route
![image](https://user-images.githubusercontent.com/20153241/28226907-6c2fce3a-68f5-11e7-9659-5496b91372e6.png)

**Comment by niranjan94** [comment]
@anu-007 please don't centre align like this. Just keep things aligned to the left.

**Comment by anu-007** [comment]
should I close this issue or left align access codes ??

**Comment by niranjan94** [comment]
- I mean the header text. (keep it left aligned)
- The button, make it full width

**Comment by anu-007** [comment]
ok got it.thanks !!
