### ISSUE TITLE
Scheduler: Display timezone on public event schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4734]
With the move to online events and people joining an event in different timezones displaying the timezone would be super helpful. Therefore, please:

1. Implement timezone info on top right on the public event pages.
2. In a second step add a drop down menu to change the timezone and display the correct event time and date in the timezone choosen by the user.

**Comment by tasneemkoushar** [comment]
May I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by tasneemkoushar** [comment]
Thank you, I will start working on it.

**Comment by maze-runnar** [comment]
@tasneemkoushar are u still working on it?

**Comment by tasneemkoushar** [comment]
> @tasneemkoushar are u still working on it?

I am on it, and I need a little help.

**Comment by tasneemkoushar** [comment]
> @tasneemkoushar are u still working on it?

During installation, just before launching the project on my local server 4200, the process stucks and page loads and say "build fail".
