### ISSUE TITLE
Pricing Page: Create a pricing page with info in the central column

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4741]
As the service gets more reliable we will be able to cover our cost through pro-features that users would like to pay for. Therefore please implement a pricing page at /pricing

Relevant examples of pricing pages are https://www.eventbrite.co.uk/organizer/pricing/ and https://www.papercall.io/pricing.

* [x] Change the pricing link on the footer to the page.
![Screenshot from 2020-09-03 18-43-45](https://user-images.githubusercontent.com/1583873/92143338-700f5b80-ee15-11ea-830d-9d3d0880f6dd.png)

* [ ] On the top menu add the menu item "Pricing" behind the "Browse Events" link **but** only show it for non-logged in users. For logged in users do not show the "Pricing" tab. It is sufficient to have it in the footer for them.
![Screenshot from 2020-09-03 18-54-58](https://user-images.githubusercontent.com/1583873/92144445-042df280-ee17-11ea-8ada-bf910f3de623.png)

* [x] Add the following to the Page Content

  * [ ] Pricing (header)
![Screenshot from 2020-09-03 18-41-58](https://user-images.githubusercontent.com/1583873/92143204-33dbfb00-ee15-11ea-94af-04912772ac59.png)

  * [x] Find the plan that's right for you.
![Screenshot from 2020-08-11 15-32-54](https://user-images.githubusercontent.com/1583873/89904213-ef2fbc00-dbe8-11ea-967b-a6db290ab994.png)

  * [x] Add table similar to Eventbrite. Use the details as provided in the spreadsheet here: https://docs.google.com/spreadsheets/d/1WTgOEtqmeGl-p2HCsBBNKJWC8Z_owwN8hpNoggezL4Y/edit?usp=sharing

**Comment by srijanandi** [comment]
I want to contribute in this issue!

**Comment by mariobehling** [comment]
Thanks for adding the pricing table! Please also complete the remaining parts of this issue including link on footer, header, tagline, link for not logged in users on top menu bar.

The table has a variance in the thickness of the table lines. Please make it even as well. See below.

![Screenshot from 2020-09-03 18-47-04](https://user-images.githubusercontent.com/1583873/92143859-25421380-ee16-11ea-9801-b8c82ea88a7f.png)

**Comment by maze-runnar** [comment]
> The table has a variance in the thickness of the table lines. Please make it even as well. See below.

I have uses default Semantic UI table, no extra css. This is from their side.

**Comment by mariobehling** [comment]
Thanks for the update to the pricing page. I see that you added the page title and heading "Pricing" on the image instead of in the code. Please correct this and implement the heading in the code similar to the public event pages. As a matter of fact you could just copy code from elsewhere to achieve this. Thank you.

**Comment by maze-runnar** [comment]
@mariobehling this has been done https://github.com/fossasia/open-event-frontend/pull/5152
