### ISSUE TITLE
Sessions are not properly displayed on scheduler and program

### ISSUE THREAD

**Issue by kootox** [fossasia/open-event-frontend#4760]
**Describe the bug**
The sessions are not properly displayed on scheduler and program, probably due to non ISO dates

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/16fa59c7/schedule, the sessions are fucked up and do not display at the proper time
2. In the js console you can see "Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release."
3. Go to https://eventyay.com/e/16fa59c7/sessions/all to see the sessions proper time (shifted 2 hours, probably GMT/CEST conversion problem)

**Expected behaviour**
All session properly displayed at the right place in the scheduler and program

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser : Firefox 79.0 or Chromium 84.0.4147.105

**Comment by iamareebjamal** [comment]
The time saved for session "Gérez vous cours à distance et vos Webinars avec Big Blue Button" is `2020-09-22T10:30:00+00:00` which in Paris time is `2020-09-22T12:30:00+02:00` so it is correctly shown in the sessions screen

![image](https://user-images.githubusercontent.com/3874064/90134628-145e2f00-dd8f-11ea-8f09-aca9377267b1.png)

But it is incorrectly shown in scheduler (hence the confusion) and also it is incorrectly shown in expanded session (shown in local timezone)

![image](https://user-images.githubusercontent.com/3874064/90134729-41aadd00-dd8f-11ea-90ea-30b98b7bfa95.png)

**Comment by kootox** [comment]
So there is a huge mixup because in scheduler (i don't know how to schedule manually otherwise), I put it at 10h30 (local time)

**Comment by iamareebjamal** [comment]
Yes, I'll be fixing it today hopefully to remove all inconsistencies

**Comment by kootox** [comment]
thank you very much

**Comment by iamareebjamal** [comment]
The issue started in #4554 when ember-source was upgraded from 3.19.0 to 3.20.0

There is no mention of any breaking change in their docs so I don't know how things keep breaking on each ember upgrade.

Will revert for now and diagnose more closely why it broke

**Comment by iamareebjamal** [comment]
Actually, with ember-source, jquery got updated to 3.15.0 in the above commit, which contains the following breaking change - https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

In fullcalendar, they were using unclosed HTML tags which are now unsupported in jquery 3.5.0, this caused the error in #4729 and fixed in #4757 

So, reverting jquery to 3.14.1 and removing the patch as well as it is not needed now.

**Comment by iamareebjamal** [comment]
Scheduler and timezone issue in scheduler is now fixed. Will be deployed in an hour or so. The session timing in expanded view will be fixed soon. It is tracked in #4238

**Comment by iamareebjamal** [comment]
Deployed. Please check @kootox

**Comment by kootox** [comment]
Everything is back to normal and working fine. Lots of thanks
