### ISSUE TITLE
Correct reference to ticketNumber in create access code form

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-frontend#477]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Steps to reproduce:**
incorrect reference to `ticketNumber`  in `templates/components/forms/events/views/create-access-code.hbs`

**Comment by niranjan94** [comment]
@utkarshnath could you please tell what the error is more clearly ?

**Comment by utkarshnath** [comment]
currently number of access tickets is referenced via `ticketsNumber` whereas it should have been `data.ticketsNumber` because we are getting this from model as `{{forms/events/view/create-access-code data=model}}`
