### ISSUE TITLE
comma need to added

### ISSUE THREAD

**Issue by supermario123789** [fossasia/open-event-frontend#4776]
**Describe the bug**
just need to add comma in it pz see in the screenshot given below

**Screenshots**
![l](https://user-images.githubusercontent.com/69764410/90339868-a37a7980-e011-11ea-91bd-65ca90ad89b3.png)

**Additional context**
I fixed this issue and  make a pr for this 
@mariobehling  @iamareebjamal plz review on this 
@prateekj117

**Comment by supermario123789** [comment]
### I already create a pr for this

**Comment by iamareebjamal** [comment]
No
