### ISSUE TITLE
Order amount not changing on selecting tickets

### ISSUE THREAD

**Issue by mishari** [fossasia/open-event-frontend#4777]
After selecting ticket, not being able to press the "order" button feels like a bug. There's no way of knowing what one has to do to order

If registration is required, then the order box shouldn't be displayed, or there should be text under the box that says "please login before ordering"

**Comment by mishari** [comment]
Can you please check here:

https://eventyay.com/e/8ccaf0b0

![image](https://user-images.githubusercontent.com/503018/90356390-985b3400-e079-11ea-8227-92c3927fb36e.png)

The price doesn't update and I cannot click "order now"

**Comment by iamareebjamal** [comment]
Yes there seems to be an issue for this event. Thanks for reporting. We'll take a look

**Comment by iamareebjamal** [comment]
Deployed. Please check @mishari

**Comment by mariobehling** [comment]
Works for me. Thanks for reporting!
