### ISSUE TITLE
The Date of the event  is overlapping to navbar in mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/open-event-frontend#4781]
**Describe the bug**
The date of the Event is overlapping to Nav bar and user Cannot read the date of the event properly

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/d414fc2c'
2. changed to mobile view  'iphone5/se and galaxy fold'
3. See error.

### Screenshots for desktop 
![now open event](https://user-images.githubusercontent.com/65535360/90363711-c728d880-e080-11ea-844e-15bca24ad0f9.PNG)

### screenshot for galaxy fold and iphone 5/se for the bug ---
![now event](https://user-images.githubusercontent.com/65535360/90363949-21c23480-e081-11ea-9582-bfa9cdae6aea.PNG)
### saturday ,july25th 2020 missing in mobile view but visible in desktop view 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone5/se , galaxy fold]
 - Browser [e.g. stock browser,]

**Additional context**
@iamareebjamal plz reviews on this issue

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by Raunaksingh100** [comment]
@iamareebjamal  Thanks
can i use margin:bottom with the media query to fixed that bug 
### LIke margin-bottom: -20px;
using the margin in negative is this Good or Bad plz reply

**Comment by Raunaksingh100** [comment]
@iamareebjamal can you tell me what is wrong in my pr ??

**Comment by iamareebjamal** [comment]
Told already
