### ISSUE TITLE
Add range position to the date and time inputs in sessions and speakers

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#479]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Value of date and time which are passed are also shown.
![validationdate](https://user-images.githubusercontent.com/17925669/28237072-9af7acce-6954-11e7-903d-2452f0da59f5.png)
![validationtime](https://user-images.githubusercontent.com/17925669/28237073-9b9aa136-6954-11e7-8d9b-fdf278aac490.png)

Expected:
The input should not show the previous values before the call for speakers is started.

**Comment by sumedh123** [comment]
Working on this.

**Comment by niranjan94** [comment]
@sumedh123 don't close without adding a comment that says why it was closed.
