### ISSUE TITLE
Organizer: Session List Page - Type column showing date instead of type

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4801]
The type column shows the submission date instead of the session type. If no type is present it should be empty, e.g. here https://eventyay.com/events/16fa59c7/sessions/all

![Screenshot from 2020-08-19 01-00-59](https://user-images.githubusercontent.com/1583873/90573879-ce9ecd80-e1b7-11ea-8d06-b0e19a29fc50.png)

**Comment by iamareebjamal** [comment]
Showing type for me
![image](https://user-images.githubusercontent.com/3874064/90578382-d2931580-e1e0-11ea-8bcc-3f88d0b887c3.png)

**Comment by mariobehling** [comment]
It seems "track" was not loaded and then the submission column loaded twice and type moved one row. Cannot replicate it now even though the screenshot shows the issue appeared. Closing it therefore.
