### ISSUE TITLE
Public Event Page missing web link icon, e.g. globe or similar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4802]
Each link on the right side bar of an event has an icon. If there is no social media icon an event should have a link icon or globe icon, e.g. check https://eventyay.com/e/16fa59c7

![Screenshot from 2020-08-19 01-10-18](https://user-images.githubusercontent.com/1583873/90574321-ec206700-e1b8-11ea-9a3f-6e04974a0124.png)

**Comment by snitin315** [comment]
I will fix it.
