### ISSUE TITLE
Organizer Speaker List Page - Unswitching "Featured" Speaker not unselecting button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4803]
When an organizer "unswitches" the featured speaker button the button does "not" actually unswitch (even though the action is executed). It shows unswitched though when the page is refreshed, e.g. check at https://eventyay.com/events/16fa59c7/speakers/all?per_page=25

![Screenshot from 2020-08-19 01-14-02](https://user-images.githubusercontent.com/1583873/90574567-8ed8e580-e1b9-11ea-82bd-041d70b32337.png)

**Comment by iamareebjamal** [comment]
Duplicate of #4873
