### ISSUE TITLE
Public Event Page Scheduler: Sessions - On scroll over show additional event information, basic speaker info and link to speaker profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4805]
Scrolling over a session to show additional event information on the public schedule is present in the website generated version. Please implement the same.

Show
* additional event information
* basic speaker info and 
* link to speaker profile

![Screenshot from 2020-08-19 01-24-50](https://user-images.githubusercontent.com/1583873/90575103-f93e5580-e1ba-11ea-8e8e-fddf0b2e05e8.png)

**Comment by iamareebjamal** [comment]
I went back to 1 year ago's commit and it still doesn't show any additional information on hover. Also, no such code is present in the repo. What was the implementation like? When was this possible?

**Comment by mariobehling** [comment]
Sorry, I was mistaken. This feature is already working on the speakers page, but it is not working here. I changed the issue description and lowered the priority.

**Comment by maze-runnar** [comment]
where these addition informations are actually needed, on schedule page in calender view?

**Comment by iamareebjamal** [comment]
Yes, but please finish https://github.com/fossasia/open-event-frontend/issues/4832 and https://github.com/fossasia/open-event-frontend/issues/4852 before as they are more high priority

**Comment by maze-runnar** [comment]
> Show
> 
> * additional event information
> * basic speaker info and
> * link to speaker profile

@mariobehling  showing this much info will cause this problem and will need a lot fixing I guess. I think you should narrow down the info numbers.
![Screenshot from 2020-08-26 17-40-53](https://user-images.githubusercontent.com/56407566/91302018-71140d80-e7c3-11ea-8cd9-ae03ef910c6a.png)

**Comment by iamareebjamal** [comment]
This is to be shown on hover. But the priority of this issue is way less than others in the list

**Comment by mariobehling** [comment]
As we changed the design of the menu I am closing this. We can follow up on this area later elsewhere.
