### ISSUE TITLE
Public Event Schedule: Avoid in page scroll bar of schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4806]
The schedule currently uses an inpage scroll bar. Instead of a scroll bar please extend the height of the page, e.g. here https://eventyay.com/e/16fa59c7/schedule

![Screenshot from 2020-08-19 01-28-47](https://user-images.githubusercontent.com/1583873/90575335-7669ca80-e1bb-11ea-89c5-ca20f1427e6e.png)

**Comment by iamareebjamal** [comment]
The calendar will have to have a static height or the scrollbar will never show. For eg, here - https://eventyay.com/events/b548bcfc/scheduler which will make it difficult to schedule events from unscheduled box

So we can increase the height but not make it expanded always

**Comment by shantanumallik** [comment]
@mariobehling @iamareebjamal Is this issue available to work on? I’d like to work on it.

**Comment by maze-runnar** [comment]
@shantanumallik please claim one issue at a time. This is an urgent issue so I am taking it up.

**Comment by shantanumallik** [comment]
@maze-runnar okay. Go ahead. This seems like a pretty easy fix though. Maybe something on the lines of expanding the calendar on hover to view in full size. This will eliminate the scrollbar issue without having the static height problem as @iamareebjamal pointed out.
