### ISSUE TITLE
Scheduler: Implement schedule page and subviews tracks and rooms in list view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4807]
The website generator offers a schedule view with the subpages "tracks" and "rooms", e.g. https://sched.eventyay.com/FOSSASIASummit/schedule.html. Please implement something similar as sorting options/views as follows:

* [x] Schedule view is same as now here e.g. https://eventyay.com/e/8fa7fd14/schedule **_DONE ALREADY_**
* [ ] Tracks view - all sessions are sorted in list view according to date, time and track -> There needs to be a sorting option according to "Tracks"
* [ ] Rooms view - all sessions are sorted in list view according to date, time and room -> There needs to be a sorting option "Rooms"

![Screenshot from 2020-11-25 12-19-44](https://user-images.githubusercontent.com/1583873/100221245-b3f79580-2f18-11eb-8351-3002202ad4b7.png)

**Comment by maze-runnar** [comment]
@iamareebjamal if rooms and track filter is implemented on session page, then is this issue really needed? Why there is a need of separate rooms page, if session can show tracks?

**Comment by iamareebjamal** [comment]
Yes, this is what we discussed in the meeting if you remember. Single page will display all data by default sorted by time, and there'll be an option to group by room and track on the same page

**Comment by iamareebjamal** [comment]
Filtering by track and room is different than group by feature. See the difference in schedule, track and room page in the link attached to the issue to get the difference

**Comment by maze-runnar** [comment]
> Filtering by track and room is different than group by feature. See the difference in schedule, track and room page in the link attached to the issue to get the difference

so in group by it will take all events-sesssons that are going to held in same room and group them together?
But is there any feature available on server side?

**Comment by iamareebjamal** [comment]
Just using `sort` in API can make this work. Think

**Comment by maze-runnar** [comment]
on which page it would be implemented?

**Comment by maze-runnar** [comment]
And still confused about this part.
> so in group by it will take all events-sesssons that are going to held in same room and group them together?

**Comment by maze-runnar** [comment]
> Filtering by track and room is different than group by feature. See the difference in schedule, track and room page in the link attached to the issue to get the difference

I have seen it, and I get the difference but still a little confusion. Aren't we implementing same thing again and again? means there is still filter by room & tracks on those pages too .

**Comment by iamareebjamal** [comment]
Filter and grouping is different. Call me in the morning. You need to look closely what's the difference in Room, Schedule and Track pages
