### ISSUE TITLE
Public Speaker Page: Speaker who does Not have session in speaker list

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4813]
The last speaker on the event list does not have a session and schedule information. As there is no session there is not a session that is accepted or confirmed (maybe there was one before and he has withdrawn?). 

Expected: The speaker should not show up on the speakers page without an accepted or confirmed session.

Compare to https://eventyay.com/e/16fa59c7/speakers

![Screenshot from 2020-08-19 09-15-26](https://user-images.githubusercontent.com/1583873/90604523-417e6780-e1fd-11ea-8eba-af65adb9b1c9.png)

**Comment by snitin315** [comment]
Taking this up.
