### ISSUE TITLE
Organizers View: Speakers and Session Page Names Inconsistent and Accepted Session info missing in table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4814]
* Organizers speakers page not showing "session info" on the Accepted Session of Berengère Mathieu on https://eventyay.com/events/16fa59c7/speakers/all
* And it shows Bérangère Mathieu on https://eventyay.com/events/16fa59c7/sessions/all but Berengère Mathieu on https://eventyay.com/events/16fa59c7/speakers/all - There is a difference in the second letter "e" in Berengère

![Screenshot from 2020-08-19 09-32-21](https://user-images.githubusercontent.com/1583873/90605765-1563e600-e1ff-11ea-896a-66bb1ce40060.png)

**Comment by iamareebjamal** [comment]
These are 2 different speakers. The one with accepted session is on page 2

**Comment by mariobehling** [comment]
Thanks for identifying this. Very confusing.
