### ISSUE TITLE
Public Session Page: Speaker Name Not Shown in Overview Mode

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4815]
In the overview mode, where the sessions are not expanded the speaker names are not shown. Please show the speaker name here as well.

Compare here https://eventyay.com/e/16fa59c7/sessions/all

![Screenshot from 2020-08-19 09-37-03](https://user-images.githubusercontent.com/1583873/90606050-8f946a80-e1ff-11ea-9765-c58e64464bd5.png)

Expected similar to website generator.

![Screenshot from 2020-08-20 20-43-26](https://user-images.githubusercontent.com/1583873/90811999-dbd9ca80-e325-11ea-8873-c130c6a42ca5.png)

**Comment by snitin315** [comment]
Taking this up.
