### ISSUE TITLE
Public Event Page Sponsor Listing - Show logos in same size and open in new tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4816]
On the public event pages logos are currently adjusted to the same width. Some logos are optimized to width, others are optimized to height and even other logos are optimized to squares. 

Expected is that
* logos are portrayed in the same combined dimensions of Width x Height. 
* and that sponsor links open in new tabs

Compare: https://eventyay.com/e/16fa59c7

![Screenshot from 2020-08-19 12-35-36](https://user-images.githubusercontent.com/1583873/90625061-4cdf8c00-e219-11ea-90e0-0c2f55822320.png)

**Comment by snitin315** [comment]
Taking this up.

**Comment by mariobehling** [comment]
Cannot verify that this issue has been solved as outlined in the issue. Therefore reopening it.

**Comment by ShreyanshSrivastava** [comment]
@mariobehling Sir this issue seemed to be already solved, you can close this one.
