### ISSUE TITLE
Event Dashboard: Sponsor Box - Sorting not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4817]
The sponsor box show different sponsors and the option to sort them alphabetically. The page refreshes when the user resorts sponsors, but the sponsors do not get actually get sorted.

Compare https://eventyay.com/events/16fa59c7

![Screenshot from 2020-08-19 12-55-39](https://user-images.githubusercontent.com/1583873/90626481-4fdb7c00-e21b-11ea-8149-866cd46b213e.png)

**Comment by blossom2017** [comment]
Can I work on this?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by blossom2017** [comment]
I tried but couldn't get much clue. I will not be able to work on it.

**Comment by AdityaArunSharma** [comment]
The link that you have provided shows this
![Screenshot from 2020-09-09 01-06-56](https://user-images.githubusercontent.com/54372877/92520263-f32b1a00-f238-11ea-9ee2-964e93387d63.png)

Is this issue still open? Can I work on it?

**Comment by mariobehling** [comment]
The issue is still open. The link is just a sample event where only admins have access to. You need to create your own event to test it.

**Comment by namanjain007** [comment]
The compare link provided is not working .

**Comment by namanjain007** [comment]
Please tell how to reproduce the bug .

**Comment by mariobehling** [comment]
Has been fixed in the meantime.
