### ISSUE TITLE
Organizer Event Dashboard: Apps Box Set Link to Website Generator and Android Apps in Stores

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4818]
The apps box currently has dead links on the organizer's event dashboard and simply providing buttons with links here does not seem suitable as the user needs more details. Therefore please redesign the box and change content as follows:

* in box create section "**Organizer Android App**" 
  * include images with links to the app in Play store and Fdroid
  * add descriptive text as follows "Organizers can scan in ticket holders at location based events using the ticket QR code with the Eventyay app. You can download it on the Play store or Fdroid." (again add links in the text itself)
  * add phone icon or another relevant icon to the design
* in box create section "**Event Site Generator (Experimental)**"
  * include link to generator using https://open-event-wsgen.herokuapp.com
  * add text as follows "Create your self-hosted static event site without the need of a database using our website generator and simply upload the folder to a server, Github or Gitlab pages. Then direct your domain to it. Your event website is now ready! To get it working you need to copy the link to the event API from the events export page and fill it into the event site generator form. This service is experimental." 
  * add the link to the "export page" (e.g. https://eventyay.com/events/16fa59c7/export) into the above text.
  * add global web icon or another relevant icon to the design

![Screenshot from 2020-08-19 12-59-33](https://user-images.githubusercontent.com/1583873/90629222-49e79a00-e21f-11ea-8ca3-9ddbd33a48e0.png)

**Comment by dsnehasish74** [comment]
I would love to work on it  can you please assign this to me?????

**Comment by iamareebjamal** [comment]
Please send a PR

**Comment by dsnehasish74** [comment]
ok I am sending

**Comment by dsnehasish74** [comment]
Can you help me on this after installing it in my local machine I tried to login but my email is not getting verified if click on the link to confirm my email it shows not found ...... plz help me with that without it how can I go to my desired page 
![Screenshot (291)](https://user-images.githubusercontent.com/58779604/95007256-3d7e9b80-062b-11eb-9d12-16c8451597b7.png)

**Comment by iamareebjamal** [comment]
Change to URL to localhost:4200

**Comment by mariobehling** [comment]
Part of this have been solved. I will open a more specific issue on other changes required.
