### ISSUE TITLE
Call for Speakers Page: both button says edit speaker details

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#4820]
**Describe the bug**

Both buttons say `Edit Speaker Details`
**To Reproduce**
1. Go to call for speakers page
2. See error

**Expected behaviour**

one button should be `Edit session details`
**Screenshots**

![Screenshot at 2020-08-20 14-13-53](https://user-images.githubusercontent.com/46647141/90748307-a3b79500-e2ef-11ea-960a-e16cdd39952f.png)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

**Comment by snitin315** [comment]
Oh, both buttons correspond to different speakers.

**Comment by snitin315** [comment]
Then we should display the speaker's name on button.

**Comment by mariobehling** [comment]
Actually only the user account of the specific speaker should have access to their own "speaker details". So, only show one speaker detail button, but only show the button of the specific account.

Except maybe for organizers and admins?

In any case speaker A should not be able to edit information of speaker B.

**Comment by bsanket16** [comment]
I would like to work on this issue.

**Comment by snitin315** [comment]
Go Ahead.

**Comment by daretobedifferent18** [comment]
@snitin315 I am not able see this problem at all

**Comment by daretobedifferent18** [comment]
This seems to be fixed.
