### ISSUE TITLE
Link sessions in speaker list to sessions page

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4832]
The session used to link to the extended session description on the "sessions page". It is not linked now.

Parent Issue: #4000

**Comment by mariobehling** [comment]
The implementation does not work for anonymous users. The linked page should be available openly on the web (without options to edit session details). Please give permissions to view this page for everyone. Therefore opening the issue.

Compare event here: https://eventyay.com/e/8fa7fd14/speakers and click on sessions without being logged in.

**Comment by iamareebjamal** [comment]
Remaining issue opened in #5055 and fixed in #5070
