### ISSUE TITLE
Organizer Session Notifications: Message Box if Off-Screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4837]
When an organizer tries to send a notification email to a speaker the message is off-screen in some resolutions and cannot be accessed fully or scrolled to the right position.

![Screenshot from 2020-08-21 16-40-35](https://user-images.githubusercontent.com/1583873/90902788-48f46b00-e3cd-11ea-9c22-c45818c8434d.png)

**Comment by raghavchugh21** [comment]
Starting my work on the issue, kindly share the acceptance tests.

**Comment by iamareebjamal** [comment]
There are none
