### ISSUE TITLE
Organizer Session Page Table: Distribute Columns more evenly and correct time info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4838]
The organizer session page table (e.g. https://eventyay.com/events/16fa59c7/sessions/all) has its rows distributed in a way that squeezes some while others have too much space. Please change as follows:
* Make columns distribute more evenly to fit the content, e.g. extend the date/time columns and reduce the width of the "lock" and "notify" column
* Also reduce the spacing between the "title" and the buttons below the title text

The date/time column shows 24 hour times, but it also shows "AM/PM", e.g. 16:05 PM. 
* Take out AM/PM if the format is 24 hours.

![Screenshot from 2020-08-21 16-44-37](https://user-images.githubusercontent.com/1583873/90903292-054e3100-e3ce-11ea-979d-9b895c886c4b.png)

**Comment by VipulKhandelwal1999** [comment]
Starting my work on the issue, kindly share the acceptance tests.

**Comment by iamareebjamal** [comment]
There are none

**Comment by VipulKhandelwal1999** [comment]
Sir, Then why this issue is still open.

**Comment by iamareebjamal** [comment]
Because it isn't solved

**Comment by VipulKhandelwal1999** [comment]
Ok Sir Thanks For Your Your Response.

**Comment by Himanshunitrr** [comment]
I will like to work on it.

**Comment by Himanshunitrr** [comment]
Where can be the relevant files for (https://github.com/fossasia/open-event-frontend/issues/4838) be found sir?

**Comment by snitin315** [comment]
@Himanshunitrr see past PRs.

**Comment by sachinchauhan2889** [comment]
i am working on this issue

**Comment by sachinchauhan2889** [comment]
@mariobehling  @iamareebjamal  @snitin315  please have a look at PR. Please review it.
