### ISSUE TITLE
Public Event Pages: Organizer Menu Item does not go to "Organizer Section"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4849]
The organizer menu item should specifically link to "Organized by.." section on the public event page. Currently it directs to "#owner", e.g. https://eventyay.com/e/16fa59c7#owner, but this does not scroll the page to the "organizer section". It should rather use the tag "#organizer" instead of "#owner" anyways.

![Screenshot from 2020-08-23 20-55-46](https://user-images.githubusercontent.com/1583873/90986478-68cd8f80-e583-11ea-899e-38a72beb417e.png)

**Comment by shantanumallik** [comment]
@mariobehling May I work on this issue?

**Comment by snitin315** [comment]
Yes go ahead.

**Comment by iamareebjamal** [comment]
Sponsors section and othere are not linked. And the linked sections don't work from other URLs so reopening

**Comment by shantanumallik** [comment]
This is possibly due to the sponsors section being added at a later date. I am looking into this issue and will push a fix shortly.

**Comment by shantanumallik** [comment]
I have updated the code to incorporate all the modifications that were made between PR generation and merge. All the errors seem to have been resolved.  Yet, the issue with the anchor tags not working when coming from other URLs remains. This has to do with the way ember handles anchor tags when transitioning from one view to another. This is a pertaining issue in the production version of the code as well. 

After much research, I have not been able to find a definitive answer that solves this issue. I have figured out a few "hacky" methods to explicitly pass the scroll target as a parameter when the view changes and then access the said parameters and explicitly scroll to the target div after the view has been rendered. I am working on making this fix. I'd appreciate your views on this @iamareebjamal .

Thanks!

**Comment by iamareebjamal** [comment]
I'll search what's the better option

**Comment by shantanumallik** [comment]
@iamareebjamal Do you have any update on which way is better to proceed with?

**Comment by iamareebjamal** [comment]
Does `href-to` works in this case?

**Comment by shantanumallik** [comment]
@iamareebjamal it doesn't. Any anchor tag added to href-to is simply ignored.
