### ISSUE TITLE
Scheduler/Sessions/Tracks Page: Add Overview of tracks and rooms and make them into filters

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4852]
The generated website schedule has a rooms and tracks list on the right sidebar, which can also be used as filters, e.g. here http://2019.fossasia.org/event/schedule.html.

Step 1:
Firstly implement such an overview on the schedule and sessions/tracks page on the right side bar. 
Take out the links and twitter badge on these pages from the sidebar.

Step 2:
In a second step implement the rooms and tracks as filters just like the generated website.

![Screenshot from 2020-08-24 00-34-00](https://user-images.githubusercontent.com/1583873/90990445-c8d32e80-e5a1-11ea-9df7-251c3c8e141b.png)

**Comment by raghavchugh21** [comment]
I'll work on this issue

**Comment by raghavchugh21** [comment]
can I work on this issue?

**Comment by maze-runnar** [comment]
Do i have to remove existing all right section?

**Comment by mariobehling** [comment]
@maze-runnar Just follow this order:
* event links
* tracks
* rooms
* twitter
