### ISSUE TITLE
Wizard 1 Basic Event Details/Public Page: Event logo from Form not displayed on event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4857]
In the create event wizard step 1 an event logo can be added. However, the logo is not shown anywhere.

Please add the logo on top of the event page in front of the event description as in the example below.

Compare live site https://eventyay.com/e/8fa7fd14 to the below image.

![Screenshot from 2020-08-24 12-06-23](https://user-images.githubusercontent.com/1583873/91033023-0c11b980-e603-11ea-814a-046e13772024.png)

**Comment by kejriwalShivam** [comment]
I would like to work on this issue @mariobehling

**Comment by iamareebjamal** [comment]
Go ahead
