### ISSUE TITLE
Public Page: Avoid Linebreaks in date/time and event title

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4858]
The event date/time sometimes has line breaks even if there is still sufficient space. Please avoid line breaks if there is enough space.

![Screenshot from 2020-08-24 12-15-20](https://user-images.githubusercontent.com/1583873/91033428-a245df80-e603-11ea-969d-760a8720e097.png)

**Comment by 1209simran** [comment]
May I work on this issue?

**Comment by snitin315** [comment]
Go ahead
