### ISSUE TITLE
Public Speakers and Schedule Page: No Lazy Loading, it Slows Down Users Too Much

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4866]
Public speakers page and schedule pages should have not lazy loading as it slows down the usage of the site too much, e.g. compare here https://eventyay.com/e/8fa7fd14/speakers

**Comment by iamareebjamal** [comment]
It will slow down even more if lazy loading is removed. Last time it crashed the server every time the speaker page was loaded: https://github.com/fossasia/open-event-frontend/issues/3650

It is a trade-off, I'll look into if there is any way to improve user experience but realistically, we can't remove lazy loading. I'll check how many items can we load in one go, but that is a trade-off as well, right now we're loading 6 items, so a lot more loads happen but the time in loading is less, if we  load 20 at a time, then it'll take less loads but more time to load the items

**Comment by mariobehling** [comment]
20 items sounds good. You are right, we need to find a trade-off, but at one point we would also upgrade the server.

**Comment by iamareebjamal** [comment]
It's not just a problem of the server spec, for huge events, the response becomes like 1-2 MB which takes some time to transfer. If we need to really load it all at once, we can make a mechanism that caches the response for some time like 10 minutes. That will solve the time and load issue but I think the UX can be improved a lot so loading everything at once won't be necessary.

You'd notice that filtering and loading sessions is very fast, takes 200-400 ms. So users don't feel any problem. We just have to get sessions which are accepted or confirmed. For speakers, we have to get speakers who have any session which is confirmed or accepted, which is a lot more complicated query as it involves a join. Now imagine that for every speaker, so it takes >1 second to load more speakers and users notice.

Also, in sessions page, we load speakers and track, 2 related items. In speakers page, we load speakers->sessions->track,microlocation. That's 3 indirections which is a lot more slower. So, if we do this that only speakers are loaded and sessions, track, microlocation are loaded for the speaker when a user clicks on the speaker to expand it, it might get faster as well. We'll need to see which is the contributing factor to slowness, filtering confirmed and accepted sessions or including sessions, track and microlocation. It'll need more time and analysis

**Comment by joeytwiddle** [comment]
I think we can improve this by simply changing the `{300}` to `{900}` on this page (in two places):

https://github.com/fossasia/open-event-frontend/blob/development/app/templates/public/sessions.hbs

Currently it waits until the user is near the bottom of the list to start loading more entries.

With a higher number, it will start loading new entries in the background, while the user is still reading.

(This should mean that users won't see the loading spinner so often while they are scrolling down and browsing. But it still won't solve the use case when the user wants to immediately scroll to the bottom end of the list.)

Please reopen if you agree!

**Comment by iamareebjamal** [comment]
We tried in the past but didn't notice considerable difference. But doesn't hurt to try again

**Comment by maze-runnar** [comment]
It is faster using `@triggerOffset={{1000}}.`
