### ISSUE TITLE
Implement event copyright API for public/index

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#487]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/28261128-952ecb3a-6afb-11e7-8b0b-053e5786e59a.png)

**Comment by niranjan94** [comment]
Add this as an `include` directive to the events route itself. We will be displaying this in all public event pages
