### ISSUE TITLE
Switch buttons no longer working as expected anywhere

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4873]
The switch buttons do not work in any area as expected. They cannot be moved.

![Screenshot from 2020-08-25 13-37-28](https://user-images.githubusercontent.com/1583873/91169806-3bdec100-e6d8-11ea-971a-38dd82c34084.png)

**Comment by mariobehling** [comment]
And they all appear switched on when loading second, third etc. page of a table list page.

... even if they are not really switched on.

![Screenshot from 2020-08-25 13-39-40](https://user-images.githubusercontent.com/1583873/91170004-8bbd8800-e6d8-11ea-8a5c-0b6f76744290.png)

**Comment by iamareebjamal** [comment]
Problem happening since https://github.com/fossasia/open-event-frontend/pull/4746
