### ISSUE TITLE
Schedule Calendar View: Changing Timezone can Result in Disappearing Sessions from Schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4876]
If a user changes the timezone to a time that is not covered in the original calendar time the sessions disappear from the calendar view.

Compare https://eventyay.com/e/16fa59c7/schedule

![Screenshot from 2020-08-25 16-12-23](https://user-images.githubusercontent.com/1583873/91185337-fe852e00-e6ed-11ea-880e-63fee1c3ba63.png)

**Comment by iamareebjamal** [comment]
Yes, the scheduler implementation is buggy. I couldn't find a way to re-render the calendar on change of timezone. Will look again if it is possible or there is another workaround

**Comment by maze-runnar** [comment]
is it fixed? working correctly on my local.

**Comment by iamareebjamal** [comment]
No it isn't fixe
