### ISSUE TITLE
Implement users API for '/profile' route

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#488]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend.

**Comment by sumedh123** [comment]
Would like to work on this.

**Comment by geekyd** [comment]
@sumedh123 The settings route has four sub-routes, this can be divided into 4 sub-issues for progressing faster.

@niranjan94 Please guide.

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 Need some guidance here. I am implementing API for the route 'settings/contact-info'. It has email and phone field. But I am not seeing any model for it. Please correct me if I am wrong. Please guide.

**Comment by CosmicCoder96** [comment]
@sumedh123 first, please split this issue. Make this only for profile. Rest I have replied to your messages on chat :)

**Comment by niranjan94** [comment]
@sumedh123 @CosmicCoder96 please keep important conversations regarding specific issues on the issue/pr itself instead of gitter. 

And @sumedh123 you would have to use current `user` model since the email and phone number pertain to the current user.

**Comment by niranjan94** [comment]
And please open sub-issues for each part of it. 
- Each section of the settings route would be a separate issue.
- Profile would be a separate issue. 

And work on one issue at a time.

**Comment by geekyd** [comment]
@sumedh123 I have created separate issues for settings route, please change this issue to profiles route.

**Comment by geekyd** [comment]
@niranjan94 @sumedh123 @CosmicCoder96 Working on this.
