### ISSUE TITLE
Organizer Event Dashboard: Add column "Tickets"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4884]
On the organizer dashboard at https://eventyay.com/events a column "Tickets" would be useful to enable organizers to get a good overview of the current state of the event. Implement this on all filter pages - live, past, draft.

Therefore, please add a ticket column with information on the number of tickets sold and the list of different tickets.
Add the column in between "Roles" and "Sessions".

* [ ] Show overall number of all tickets sold
* [ ] Show ticket category and the number of tickets sold in each category
* [ ] Make the table sortable according to the overall number of sold tickets

![Screenshot from 2020-08-27 13-45-21](https://user-images.githubusercontent.com/1583873/91442364-08d03500-e872-11ea-8503-79ed6092f58e.png)

**Comment by git-anurag-hub** [comment]
Can you explain more about what should be under the "Tickets" section. Like how much details about what.

**Comment by iamareebjamal** [comment]
I think the issue is pretty clear

> Therefore, please add a ticket column with information on the number of tickets sold and the list of different tickets.

**Comment by maze-runnar** [comment]
taking this up.

**Comment by maze-runnar** [comment]
I am on it

**Comment by iamareebjamal** [comment]
@maze-runnar This issue is neither high priority, nor in the current milestone. Please read meeting notes again

**Comment by Draco9421** [comment]
I am working on it
