### ISSUE TITLE
Organizer Manage Event Overview Dashboard: Link logo and event name to specific event dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4885]
The manage event dashboard has a nice table. 

* On the table please link the logo and event name to the specific event dashboard (of the event itself).
* Slightly increase the space between the logo and event name
* Slightly decrease the space between the event name and the below buttons

![Screenshot from 2020-08-27 16-29-57](https://user-images.githubusercontent.com/1583873/91455746-c4996080-e882-11ea-8f29-029f410cfa4e.png)

**Comment by snitin315** [comment]
I will take this up.

**Comment by mariobehling** [comment]
Thanks. Added some more small details FYI.
