### ISSUE TITLE
Public Event Page: Add menu tab "Sponsors"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4888]
If an organizer has activated "Sponsors" in the event creation wizard and added sponsors, please show a tab "Sponsors" on the left hand-side of the public page.

1. Implement the sponsors menu tab above the menu item "Organizers".
2. Change the heading of the "Sponsors" section to match the heading level and style of "Organizers".

![Screenshot from 2020-08-27 19-04-10](https://user-images.githubusercontent.com/1583873/91472917-71caa380-e898-11ea-9681-958e2e3db511.png)

**Comment by mariobehling** [comment]
We now have "Supported By" and "Sponsors". Only need "Supported By"

![Screenshot from 2020-08-29 10-28-04](https://user-images.githubusercontent.com/1583873/91632635-78653200-e9e2-11ea-8c29-c7f4680a3e11.png)

**Comment by indavarapuaneesh** [comment]
can I look into this issue?

**Comment by snitin315** [comment]
Yes

**Comment by indavarapuaneesh** [comment]
> Yes

can you review it and give it feedback?

**Comment by indavarapuaneesh** [comment]
@snitin315  can review it and give feedback?

**Comment by mariobehling** [comment]
Still need to remove the sponsor heading.

![Screenshot from 2020-09-10 18-24-44](https://user-images.githubusercontent.com/1583873/92762478-ede1e280-f392-11ea-9d71-e0a6bcb56179.png)
