### ISSUE TITLE
Payment Gateway Monitoring: Propose and Implement Solution

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4897]
Issues with payment gateways often go unnoticed until we receive an email from a partner that has problems. For example the Paypal SDK has issues every other months. As the number of payments increase this could have a large effect. Therefore please propose and implement a monitoring process.

Possible solutions:
* [ ] Automatic orders tests
* [ ] Automatic emails to system admins stating the numbers of sales, e.g. in the current hour, current day, week
* [ ] A box on the admin dashboard showing the development of sales through a graph separated by payment gateway
* [ ] An automatic notification email if sales suddenly drop
* [ ] Any other ideas?

**Comment by iamareebjamal** [comment]
Linked https://github.com/fossasia/open-event-server/issues/6872

**Comment by ath34-tech** [comment]
hey, can you share link of payment stuff code files, I am unable to find them , I want to take a look at them.
Thank you!
