### ISSUE TITLE
Organizer: Unable to cancel a confirmed session

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4898]
**Describe the bug**
Organizer is unable to cancel a confirmed session. There are two issues:
- Interface issue: Cancel option is unseen
- Functional issue: When click on "Cancel", the system showed an error message "unexpected error has occurred" 

**Screenshots**
![session-cancel](https://user-images.githubusercontent.com/1658742/91520364-68bbef80-e8f5-11ea-8bdb-9ee71e413281.png)

**Comment by iamareebjamal** [comment]
I clicked on it and it got canceled. Please recheck

**Comment by hpdang** [comment]
this is related to role permissions of organizer team: event owner, organizer, coorganizer, moderator. I am added this to the next milestone.

**Comment by Himanshunitrr** [comment]
I will like to work on this issue. Please guide me.

**Comment by mariobehling** [comment]
Issue seems to be resolved.
