### ISSUE TITLE
Public Event Page: Enhance filter feature 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4899]
Go to session tab on this public page https://eventyay.com/e/8fa7fd14/sessions?track=Projects%20%26%20People and select a filter 

**Filter mode is not so visible**
After I selected a filter, after few seconds I already forgot that the filter was on and which filter I have selected. Highlighted grey color is not catchy to human eyes. The clear filter icon looks too prominent and negative. If we must use an icon, I suggest something like [this](https://commons.wikimedia.org/wiki/File:Toicon-icon-lines-and-angles-filter.svg 
)

![filter](https://user-images.githubusercontent.com/1658742/91522744-4927c580-e8fb-11ea-940f-a04382dc16ca.png)

**Proposed solution: Simple fix**
Change the highlighted color to a stronger color 

OR 

**Alternative solution**
I think we can follow this example from Sched. Users can see in the central, which filter is on and how to clear it

![Screenshot from 2020-08-28 06-24-18](https://user-images.githubusercontent.com/1658742/91521604-54c5bd00-e8f8-11ea-90b5-671ad0052163.png)

**Comment by iamareebjamal** [comment]
@maze-runnar Please change the minus icon to grey. And increase opacity of selected filter from 0.05 to 0.1 and similarly of hover opacity as well

**Comment by hpdang** [comment]
https://icon-library.com/icon/clear-filter-icon-4.html
