### ISSUE TITLE
Interface error when organizer uploads speaker's image

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#4917]
**Describe the bug**
Interface error when organizer uploads speaker's image

**To Reproduce**
- Event organizer goes to an existing session and adds additional speakers into the session e.g. https://eventyay.com/events/8fa7fd14/sessions/6275/edit
- Upload the speaker's photo

**Screenshots**
![Screenshot from 2020-08-29 15-50-23](https://user-images.githubusercontent.com/1658742/91652792-bb82dc00-ea9a-11ea-8854-3a6fe2b6e281.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome

**Comment by HADES-01** [comment]
@mariobehling I would love to work on this issue. Please assign it to me.
