### ISSUE TITLE
Wizard Step 2: Add to event checklist on dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4936]
The wizard step 2 is not yet part of the event checklist box on the specific event dashboard.

Please add it here with info 

* Additional Information
  * Links, social media, privacy, code of conduct

![Screenshot from 2020-09-02 04-17-36](https://user-images.githubusercontent.com/1583873/91924716-bbb9ec00-ecd3-11ea-959c-49979f6c36fd.png)

Related to forms but could also go into the dashboard milestone. Change milestone as it seems appropriate if needed. Thanks.

**Comment by snitin315** [comment]
I will add it.
