### ISSUE TITLE
Footer - Pricing Link Not Found

### ISSUE THREAD

**Issue by bsanket16** [fossasia/open-event-frontend#4937]
The pricing link under 'use open event' section in the footer is not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://support.eventyay.com/pricing/'
2. Click on 'pricing tab'
3. File not found error

**Expected behaviour**

Either the link should be removed or we can redirect to homepage.
If we have the pricing page update the link. 

**Screenshots**

![screencapture-support-eventyay-pricing-2020-09-02-13_26_29](https://user-images.githubusercontent.com/66514052/91954826-f8133980-ed1f-11ea-8db4-cf3e53dde701.png)

**Additional context**

This is my first time here. I would like to work on this. Any help/suggestion is appreciated.

**Comment by mariobehling** [comment]
There is already a PR for pricing https://github.com/fossasia/open-event-frontend/pull/4919
