### ISSUE TITLE
Restructure headings within events landing page

### ISSUE THREAD

**Issue by AemieJ** [fossasia/open-event-frontend#4944]
**Is your feature request related to a problem? Please describe.**
In the events landing page, when I am scrolling through it I can't locate the main headings on those pages. At a point, I saw 3 cards in a row, then 2 cards, and then 1 and thought it was a bug however there was a new main heading separating them. It is really hard to locate it and I think we need better segregation for the main headings on the main landing event page.

**Describe the solution you'd like**
I would want a proper visible separation between the separate heading based events. If I as a user would scroll through the page, I want to be able to locate that this particular set of events are under a speaker or upcoming events. The main headings should be visible enough and should fit in with the minimal design of the eventyay landing page.

**Describe alternatives you've considered**
Text-align center each main heading with a larger font-size so that it creates proper visibility of the section. Also, including the segregation of sections and yet matching with the minimal design of the eventyay website, we could include a border on the top and bottom. The alternative I am trying to provide is showcased within the **Additional context**.

**Additional context**
![segregation-eventyay](https://user-images.githubusercontent.com/44139348/92014743-587c9800-ed6d-11ea-91bd-13e07c160793.png)

**Comment by Creatoon** [comment]
hey @AemieJ, I want to work on this issue, please guide me the link of the landing page so I can understand it better.

thank you

**Comment by Creatoon** [comment]
ok @AemieJ mam no problem, I saw the open issue with no PR attached that's why I started looking to solve it. please go on with your PR. 
thank you

**Comment by mariobehling** [comment]
Actually the question if this change is require or not is unclear. The most important information on the page are actually the events themselves. The headings are just additional information. We dont necessarily need them to stand out. Right now the design of the page seems ok. There are a number of more essential design changes that are needed. Issues have been opened for them. We need to focus on issues that impact the functionality and overall usage of the site. To change other design elements - we need to come back to this at a later time and discuss this from the perspective of the design of the entire site. Therefore I am closing this issue.
