### ISSUE TITLE
LinkInput crashing after recent changes

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4947]
1. Open extra details in Event Dashboard
2. Social Link component won't be rendered
3. See errors in console

**Comment by iamareebjamal** [comment]
The component should be refactored to computed properties instead of observers in future

**Comment by snitin315** [comment]
> Open extra details in Event Dashboard

I can't find the `extra details` section in the Event Dashboard, can you please share the URL?

**Comment by iamareebjamal** [comment]
Second step in event wizard
