### ISSUE TITLE
Refactor LinkInput to computed properties

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4949]
The component should be refactored to computed properties instead of observers in future

_Originally posted by @iamareebjamal in https://github.com/fossasia/open-event-frontend/issues/4947#issuecomment-686262194_

**Comment by jeetintyagi** [comment]
@iamareebjamal you mean '**@computed**' instead of **@observes** from _'@ember/object'_
correct me if i am wrong.

**Comment by iamareebjamal** [comment]
Progress here - https://github.com/fossasia/open-event-frontend/pull/5373

**Comment by skyRocket23** [comment]
.

**Comment by cweitat** [comment]
Transitioning to vue so not needed
