### ISSUE TITLE
Footer section renders in the middle of the page on lower versions IE

### ISSUE THREAD

**Issue by bsanket16** [fossasia/open-event-frontend#4951]
**Describe the bug**
I believe, IE (Internet Explorer) fails to recognize HTML5 tags.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/' on IE 11, 10, 9, 8
2. See bug

**Expected behaviour**
Footer should render at the bottom

**Screenshots**
![IE-Support-open-event](https://user-images.githubusercontent.com/66514052/92088444-848a2e80-edea-11ea-96ce-aca0f3d675e6.gif)

**Desktop**
 - OS: Windows
 - Browser IE 11, 10, 9

**Additional context**
I am new here and would like to start with this issue, any help/suggestion is appreciated.

**Comment by snitin315** [comment]
Internet Explorer is officially dead.
