### ISSUE TITLE
Invoices/Sales Admin Overview: Implement subtabs and add info about invoice status

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4954]
The admin overview on the system sales need to be improved to ensure a smooth sales and invoicing process that can be taken care of by sales staff. Therefore:

* [ ] Separate the admin/sales tab into 2 subtabs - Orders and Invoices
* [ ] Move the sidebar table "Invoices" (https://eventyay.com/admin/sales/invoices) to its dedicated tab
* [ ] Make table sortable according to each column
* [ ] Enhance the Invoice table and implement missing tabs as follows. Show:
  * [ ] Invoice # (show with download link of Invoice PDF)
  * [ ] Invoice Date
  * [ ] Event
  * [ ] Dates
  * [ ] Amount
  * [ ] Organizer/Email (Show Names and Emails here)
  * [ ] Invoice Sent (Show dates invoice was sent out and also the dates if it was sent out several times)
  * [ ] Status (Unpaid, Overdue, Paid, Failed, Refunding, Refunded, Request Cancelled - Enable Admin to change the state; "Request Cancelled" means there was no invoice paid and the platform cancelled the request to pay the invoice)
  * [ ] Notify button (opening a pop-up with email options depending on state)
  * [ ] Resend Invoice button

Compare https://eventyay.com/admin/sales

![Screenshot from 2020-09-03 11-50-56](https://user-images.githubusercontent.com/1583873/92100210-c95a9900-eddb-11ea-8c25-052f2f5d657e.png)

**Comment by maze-runnar** [comment]
>  Notify button (opening a pop-up with email options depending on state)

what is notify actually ?

**Comment by iamareebjamal** [comment]
Like this https://github.com/fossasia/open-event-frontend/issues/4604
