### ISSUE TITLE
Wizard Step 2: Implement a Refund Text Box and add info on public event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4957]
There are potentially a number of ways we can implement a refund. For now the easiest way is to:
* add a text box where the user can add information for a refund policy in Wizard Step 2 (above privacy).

![Screenshot from 2020-09-03 16-56-43](https://user-images.githubusercontent.com/1583873/92131697-91b51680-ee06-11ea-8f43-b5cade655ea7.png)

In Wizard step 2 add a helper text icon here, that shows the following info:
* "Refunds to be processed by the organizer through payment provider. Refund payments to attendees cannot be made on the eventyay platform. Please go to your payment provider, make a refund and mark the ticket as refunded in the eventyay platform."

On the public event page
* add a link that opens a pop up with the text. 
* add the small link "Refund Policy" right below the bottom right of the ticket sales box
![Screenshot from 2020-09-03 15-37-49](https://user-images.githubusercontent.com/1583873/92122400-aa6bff00-edfb-11ea-99e0-edc433b9ee72.png)

Future implementations can be done as outlined in https://github.com/fossasia/open-event-frontend/issues/3157

**Comment by snitin315** [comment]
Working on it.

**Comment by iamareebjamal** [comment]
Please complete the previous work from past milestones first. Or else they'll be dragged along the week.
