### ISSUE TITLE
System Invoice Information of Platform needs Logo Option

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4958]
Please add options for the invoice format to the admin section as follows

* Logo (enable image upload here)
* Show Logo on invoices send to event organizers

Compare https://eventyay.com/admin/settings/billing

![Screenshot from 2020-09-03 15-54-38](https://user-images.githubusercontent.com/1583873/92124254-d4262580-edfd-11ea-86b4-4aed76bd7062.png)

**Comment by maze-runnar** [comment]
> Invoice Format [Format Options here]

what exactly this means by format options?

**Comment by mariobehling** [comment]
> > Invoice Format [Format Options here]
> 
> what exactly this means by format options?

Please let the admin in the system define the starting number or type of the invoice number. Create a field that comes before the number, e.g. 

Invoice Format [OT2020-]00001
(Where OT2020- is the format entered by the admin.
