### ISSUE TITLE
Organizer Invoice Tab: In overview table add Invoice date and Pay with Paypal or Credit Card (Stripe)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4959]
In the organizer invoice tab we need to have additional options:
* [x] Change main tab name from "Billing Info" to "Billing"
* [x] On Invoice Page implement filters: Unpaid, Overdue, Paid, Failed, Refunding, Refunded
* [x] For the invoice use company data provided in payment info
* [x] In invoice # column provide the invoices as downloadable PDF 
* [x] Add a column "Date" after "Event Name"
* [x] Make table sortable according to Invoice ID, Event Name, Date
* [x] Add a Paypal Pay button and a Credit Card (Pay with Stripe Button) in the actions column
* [x] Once the invoice has been paid update the status to "Paid" 

compare https://eventyay.com/account/billing/
![Screenshot from 2020-09-03 15-59-27](https://user-images.githubusercontent.com/1583873/92125441-5531ec80-edff-11ea-9e84-f708297901d9.png)

**Comment by maze-runnar** [comment]
working on it.

**Comment by maze-runnar** [comment]
@iamareebjamal are Unpaid, Overdue, Paid, Failed, Refunding, Refunded these status are available on server side?

**Comment by iamareebjamal** [comment]
No

**Comment by maze-runnar** [comment]
> No

So can I work on this issue right now or not.

**Comment by iamareebjamal** [comment]
You can, you'll need to add those states in the server. It is part of the same issue

**Comment by iamareebjamal** [comment]
All points have been completed, so closing
