### ISSUE TITLE
Social System Links functionality URL and Form bugs after Recent Changes in Admin Section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4960]
Recently the social system links functionality was updated and now there are issues with each form field:
* Every field now requires a URL even though the URL field is already preceding
* blogs.fossasia.org should not be there as this is the admin should be able to add any domain here. So only show https:// or http:// as an option
* Please also add https://www.patreon.com as an option

Compare https://eventyay.com/admin/content
![Screenshot from 2020-09-03 18-25-10](https://user-images.githubusercontent.com/1583873/92141798-3a697300-ee13-11ea-96c6-e6023bd09f25.png)

**Comment by snitin315** [comment]
PR here #4955

**Comment by iamareebjamal** [comment]
@snitin315 That fix should not be needed at all. The changes in LinkInput component should be backward compatible and thus the new prefix mode should only be applied selectively in the places it is required. Not everywhere else. I am reverting the PRs for now. Please propose a backward compatible solution which only works on opt-in basis

**Comment by mariobehling** [comment]
Related to PR https://github.com/fossasia/open-event-frontend/pull/5000

The problem is that these changes always have some influence on areas that are not mentioned in the PR. I am no longer able to nullify (delete) admin social links at https://eventyay.com/admin/content, e.g. cannot delete the facebook link.
