### ISSUE TITLE
Footer: Fix links in Footer Column "Plan Events"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4961]
Please change the links in the footer column plan events as follows:

- Online Registration -> http://support.eventyay.com/event-setup/How-can-I-create-an-event.html
- Sell Event Tickets -> http://support.eventyay.com/event-setup/How-to-sell-tickets.html
- Event Management Software -> http://support.eventyay.com/

**Comment by Neilblaze** [comment]
Please assign me this issue @mariobehling !
