### ISSUE TITLE
Admin: Provide Option "Not to show on Frontpage"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4963]
We already have the option to promote an event to the top on the listing of the front page. We also need the option to not show an event on the frontpage, if there is a reason for this.

Therefore:
* [ ] on the table at https://eventyay.com/admin/events/live implement an additional column on the very right with a slider option "Not on Frontpage".
* [ ] If this option is chosen the options "Featured" and "Promoted" should be deactivated automatically for this event.
* [ ] Also change "Featured Event" to "Featured" and "Promoted Event" to "Promoted"
![Screenshot from 2020-09-03 19-49-58](https://user-images.githubusercontent.com/1583873/92149985-0ac06800-ee1f-11ea-89d4-b02dde48154b.png)

**Comment by surajat17** [comment]
i am new to open source community can i work on this?

**Comment by mariobehling** [comment]
Thank you! Events that are listed in the section "Call for Speakers" seem to show up still even though the option is activated. Therefore reopening the issue.
