### ISSUE TITLE
Browse Events: Map not displayed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4971]
There is an error loading the map on browse events.

Compare https://eventyay.com/explore

![Screenshot from 2020-09-04 06-24-30](https://user-images.githubusercontent.com/1583873/92199434-76362400-ee77-11ea-8aff-6568ca384537.png)

**Comment by iamareebjamal** [comment]
This is Google Maps which we are not using right now. And there is no alternative to a location picker. So only urgent solution can be to remove it

**Comment by mariobehling** [comment]
Understood. I would say, then we have it rather removed. Agree.

**Comment by snitin315** [comment]
I will send a PR 👍🏻

**Comment by iamareebjamal** [comment]
I'm half done

**Comment by snitin315** [comment]
Then go ahead 👍🏻
