### ISSUE TITLE
Footer: Open Internal Links in same tab and change text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4972]
Internal links on the footer are opening a new tab. Expected: They should open in the same tab:

Column 1
* Pricing -> link to /pricing

Column 3
* Browse Local Events -> Browse Events
* Get the eventyay App -> Attendee App
* Organizer App -> Organizer App

![Screenshot from 2020-09-04 06-29-01](https://user-images.githubusercontent.com/1583873/92199862-91556380-ee78-11ea-8c64-b513a4615202.png)

**Comment by snitin315** [comment]
I will fix it.
