### ISSUE TITLE
Grey colour visible in the below of the event in mobile view 

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/open-event-frontend#4975]
**Describe the bug**
The white space or grey colour  visible in the below of the event  and this bug only visible in the mobile view see in the screenshot given  below for the better understanding 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/19128bdf'
2. Click on 'inspect element '
3. See error

**Screenshots**
![open event front](https://user-images.githubusercontent.com/65535360/92204810-f2ddf800-eea1-11ea-8514-285dbba218ee.PNG)

**Smartphone (please complete the following information):**
 - Device: [e.g. moto g4, iPhone6/7/8]
 - Browser [e.g. stock browser]

**Additional context**
i am working on this issue

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by amanprateek123** [comment]
@Raunaksingh100  You should change the height of image to 100%. I think , it will solve the UI disturbance. You can check it by increase the height in the inspection mode.

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100  We can change the height of image to 100%(only in mobile version using media query or other). I think , it will solve the UI disturbance. You can check it by increase the height in the inspection mode.
> ![Screenshot from 2020-09-07 13-13-43](https://user-images.githubusercontent.com/42955585/92361411-f96fa800-f10b-11ea-8496-26aefb4f5505.png)
> 
No,,
I fixed with this method  but the mentor says it's take so, many of media queries to fixed this simple issue ,

So , I fixed with margin-bottom 
Read the conversation in my pr

**Comment by Raunaksingh100** [comment]
@amanprateek123 i know this bug is fixed  by this method, i am  just discussing this issue with mentor and i forget to update pr 
here my pr  #4976

**Comment by amanprateek123** [comment]
@Raunaksingh100 ok great.Sorry for misunderstanding. Can you please suggest me some issues in this project?

**Comment by mariobehling** [comment]
Such a line is also present on other sites, e.g. eventbrite, but in green here on some pages. I dont think this is a bug. It might be even nice to have this at some point on the desktop page. Right now this seems to be a small thing compared to other issues maintainers need to review and as mentioned it does not seem like a bug really. Would be great if you could help to solve issues opened by maintainers as a priority. Closing this issue therefore. Hope you continue to contribute. Thanks!
