### ISSUE TITLE
Speaker Profile Image vs. User Profile Image Should be Different

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4978]
Currently when a user submits a speaker profile for an event the system uses the account profile image. In an earlier version this was different. A speaker profile can be different from the user account profile image (even though it could be the same, it does not have to be).

Reasoning: There are different kinds of events, some formal, some less formal. A speaker might want to submit different images for different events. Therefore the account profile image could be used or another image. 

Therefore:
* [ ] Do not use the account profile image for a speaker profile (in the future we can provide options to choose from a speaker gallery, but for now we want to keep it simple)
* [ ] Provide the option to upload the speaker image as of now, but do not store the image as an account user profile image
* [ ] Ensure that the same speaker can have a different image for each event
* [ ] Ensure account profile image and the image of an event are different

![Screenshot from 2020-09-04 08-20-57](https://user-images.githubusercontent.com/1583873/92206988-bce04a00-ee88-11ea-80cc-ec6ea8d8fa55.png)

**Comment by iamareebjamal** [comment]
AFAIK all of this is still true, we just choose the speaker image to be account image as default. Speakers can still edit it and it is different for all event. If there is a need to remove the account photo as the default image, it can be done but it'll be much worse user experience in my opinion.

**Comment by mariobehling** [comment]
Ahh ok. So, I misunderstood the way it works. All good then. Thank you!
