### ISSUE TITLE
Search: Show Event Name Box as standard search box instead of location box and provide filter option for online, location based and mixed event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4993]
Currently the standard search box for events on https://eventyay.com/explore is "location". Expected: Standard Search box should be for event name.

Please implement:
* [ ] Show a standard search box "Event Name" above the filter box (instead of Location)
* [ ] Provide an option to choose between "Mixed Event", "Online", "Location based" and  similar to areas like `> Date`
* [ ] When location based event is chosen provide an option to enter a certain location (as of now)
* [ ] Finally standardize width of left sidebar to match width of the left public event pages sidebar, e.g. compare https://eventyay.com/e/8fa7fd14

![Screenshot from 2020-09-05 10-22-07](https://user-images.githubusercontent.com/1583873/92301250-50d21480-ef62-11ea-8026-f4924348bd21.png)

**Comment by Creatoon** [comment]
@mariobehling  hello sir , i wanna work on this bug , please guide me how can i reach this.

thank you

**Comment by iamareebjamal** [comment]
Please take one bug at a time and only those which you think you can solve

**Comment by Creatoon** [comment]
Yes sir,  I want to work on this issue only. 
May I?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mariobehling** [comment]
For the box "Mixed Events", "Online" and "Location" you can define a menu item "Setting" and make it similar to the areas like `> Date`.

When the user clicks "Location" there should be a box to enter a location and filter the location according to the location entered, e.g. Singapore (similar to the custom date option functionality).

![Screenshot from 2020-11-12 14-12-33](https://user-images.githubusercontent.com/1583873/98944682-b22ddb00-24f1-11eb-8efc-d8d75d1c0558.png)

**Comment by sachinchauhan2889** [comment]
taking this up

**Comment by mariobehling** [comment]
@sachinchauhan2889 Thank you for the improvements. The search filters are still inconsistent and it should also be possible to tick all options for online, location, and mixed events in this filter (if the user wants to search across all setting types which is the default search as well). I opened an issue here with more details. Would be great if you continue on this https://github.com/fossasia/open-event-frontend/issues/5921
