### ISSUE TITLE
Frontpage Search: Show search results on separate page and simplify start page search box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4994]
The start page search currently filters results in the featured event area. 

Expected is:
* When performing the search, open results in the search page at https://eventyay.com/explore

Furthermore simplify the start page search:
* Only show search box for "Event Name" and "Search"
* Do not show location box
* Do not show date filter on front page

![Screenshot from 2020-09-05 10-35-39](https://user-images.githubusercontent.com/1583873/92301411-10739600-ef64-11ea-996d-6329855ee86f.png)

**Comment by Creatoon** [comment]
hey @mariobehling can i work on this , if so then please guide me how do i gonna reach this?

**Comment by iamareebjamal** [comment]
Unfortunately, we don't have the bandwidth to guide on how to solve a particular bug. If we did, we would have done it ourselves

**Comment by NirmalKumarJoshi** [comment]
Hey @mariobehling Please assign this to me. I would like to work on it :)

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by hritikk7** [comment]
hello @mariobehling and @iamareebjamal can i work on this??

**Comment by iamareebjamal** [comment]
Yes

**Comment by hritikk7** [comment]
i think i've resolved the issue you can verify in the ss 
![capture2 0](https://user-images.githubusercontent.com/54003516/92960638-996e5e00-f48b-11ea-8962-2c95b9ba1b09.png)

**Comment by iamareebjamal** [comment]
Not really. Please read all the points in the issue description again carefully

**Comment by hritikk7** [comment]
can you plss clarify what is lacking

**Comment by iamareebjamal** [comment]
The first point itself

**Comment by JainJai2305** [comment]
Hi, allow me to work on this issue

**Comment by iamareebjamal** [comment]
Don't spam on issues. Take one issue at a time
