### ISSUE TITLE
Footer: Change Event Blog URL 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4995]
Change Footer "Event Blog" entry to:
* "Event Blog" -> "Blog"
* URL: https://blog.eventyay.com

![Screenshot from 2020-09-05 13-33-59](https://user-images.githubusercontent.com/1583873/92304268-ba5f1c80-ef7c-11ea-843f-1b0cc6a8bc7c.png)

**Comment by AbhipsaGuru1012** [comment]
@mariobehling Hi, can I work on this issue?

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by AbhipsaGuru1012** [comment]
Thank you. One quick question- do I need to make changes in the footer-main.hbs (https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/footer-main.hbs) file only?
