### ISSUE TITLE
Schedule: Calendar View Errors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4996]
After the last update the calendar reloads nicely on timezone changes. There are few issues with the display though.

* On two day events, it only displays one date as "day", "day"
* The first day does not display the view of sessions below each other
![Screenshot from 2020-09-05 14-21-18](https://user-images.githubusercontent.com/1583873/92304992-52f89b00-ef83-11ea-8887-7eac16693e81.png)
* Loading another view is not persistent, e.g. if a user chooses two day view and then switches the timezone, the display will move back to one day view

**Comment by iamareebjamal** [comment]
That is not day switcher, it's view switcher. Day switcher is on left. First view is timeline view, second is default (resource agenda), then it's multi-day view and week view

**Comment by mariobehling** [comment]
Ok, I got confused, because there is a 2 x day.

It is more logic in the "schedule".

![Screenshot from 2020-09-05 16-51-01](https://user-images.githubusercontent.com/1583873/92307634-09ff1180-ef98-11ea-9ee7-add6ca3acb97.png)

I also see that switching the days with the buttons on the left results in the second day starting at 0:00

![Screenshot from 2020-09-05 16-49-30](https://user-images.githubusercontent.com/1583873/92307647-1daa7800-ef98-11ea-82b2-7174d0f59f67.png)

I wonder what is the best solution to all this. Possibly we could require an organizer to define start and end times for each day. Let's talk about it in the weekly meeting.

**Comment by mariobehling** [comment]
Ok, I got confused, because there is a 2 x day.

It is more logic in the "schedule".

![Screenshot from 2020-09-05 16-51-01](https://user-images.githubusercontent.com/1583873/92307634-09ff1180-ef98-11ea-9ee7-add6ca3acb97.png)

I also see that switching the days with the buttons on the left results in the second day starting at 0:00

![Screenshot from 2020-09-05 16-49-30](https://user-images.githubusercontent.com/1583873/92307647-1daa7800-ef98-11ea-82b2-7174d0f59f67.png)

I wonder what is the best solution to all this. Possibly we could require an organizer to define start and end times for each day. Let's talk about it in the weekly meeting.

**Comment by maze-runnar** [comment]
@iamareebjamal what remaining in this issue?
