### ISSUE TITLE
Public Schedule: Ensure time are in correct position in different screen resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5003]
The time is not displayed correctly in different screen resolutions.

![Screenshot from 2020-09-07 19-16-49](https://user-images.githubusercontent.com/1583873/92408888-183b6200-f13f-11ea-9513-8cb656c966cc.png)

Follow up to https://github.com/fossasia/open-event-frontend/pull/5002#issuecomment-688445164

**Comment by iamareebjamal** [comment]
Fixing it
