### ISSUE TITLE
Schedule display handles timezones inconsistently

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-frontend#5006]
**Describe the bug**
When viewing an event schedule with the local timezone selected, times inside the event boxes are in local time, while times to the left of the event boxes are in the event's timezone.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/8fa7fd14/schedule?date=2020-09-09
2. Click on the timezone pulldown to select a different timezone. In this case, "Asia/Singapore (Local)" instead of "US/Eastern (Event)".
3. Scroll down to "Why Database Projects Can't Leave Licenses Alone"
4. See that the time inside the event box is "01:30 am / 10-09-2020 (+08)" as expected for the selected timezone while the time to the left of the event box is "13:30 - 14:10" which is in fact the time in EDT (i.e. the preferred timezone for the event).

**Expected behaviour**
Both times (indeed all times) should be in the selected timezone.

Note that this does create a slightly odd consequence in that the converted date+time in this case is on September 10 despite being in the September 9 "day" of the schedule. This need not be fixed; we all know how events are scheduled (or at least were pre-covid-19), no-one is going to be unduly confused by this.

**Screenshots**
![13 30_vs_1 30](https://user-images.githubusercontent.com/646827/92434116-99433980-f1d1-11ea-9368-4c40017544cc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop Linux
 - Browser +Firefox 80.0.1 (64 bit)

**Comment by iamareebjamal** [comment]
Hi, we have reverted back to remove the timing on left. We'll be implementing it correctly shortly. Revert should be live on production within an hour

**Comment by rolandturner** [comment]
OK, that's working, thanks,

**Comment by iamareebjamal** [comment]
This was resolved but vertical timeline was reverted, so reopening that issue and closing this one
