### ISSUE TITLE
Organizer Events Dashboard: Add status "Withdrawn" into sessions and speakers column in table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5010]
On the events dashboard at https://eventyay.com/events/live in the speakers and sessions column the status "Withdrawn" and "Canceled" are missing. Please add them. Ensure it is also working on the other tabs like Draft etc.

![Screenshot from 2020-09-08 08-53-20](https://user-images.githubusercontent.com/1583873/92442960-0f837400-f1b1-11ea-816f-d2728dbdf0a4.png)

**Comment by iamareebjamal** [comment]
Canceled is missing as well

**Comment by AbhipsaGuru1012** [comment]
@iamareebjamal Hi, can I work on this issue?

**Comment by iamareebjamal** [comment]
Yes, go ahead

**Comment by AbhipsaGuru1012** [comment]
@iamareebjamal should I add the withdrawn and canceled status to https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/ui-table/cell/cell-sessions-dashboard.hbs and https://github.com/fossasia/open-event-frontend/blob/development/app/templates/components/ui-table/cell/cell-speakers-dashboard.hbs files?

**Comment by iamareebjamal** [comment]
If that solves the issue, yes
