### ISSUE TITLE
Wizard Form: Simplify design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5013]
Please simplify the design of the wizard as follows:

Wizard Step 1
* Simplify page by taking out 4 horizontal lines as shown below

![screencapture-open-event-frontend-git-fork-iamareebjamal-online-events-eventyay-vercel-app-create-2020-09-08-10_07_32](https://user-images.githubusercontent.com/1583873/92453237-4bbdd100-f1bf-11ea-886a-eabe65245ac1.png)

Wizard Step 3
* Add Custom Form Field - demote from heading to standard text. This should not be a heading.

![Screenshot from 2020-09-08 10-37-59](https://user-images.githubusercontent.com/1583873/92453310-65f7af00-f1bf-11ea-9c6d-1e8b805577c9.png)

Wizard Step 5
* "Customize registration form" rename to -> "Customize submission forms"
* Add Custom Form Field - demote from heading to standard text. This should not be a heading.

![Screenshot from 2020-09-08 10-39-11](https://user-images.githubusercontent.com/1583873/92453471-96d7e400-f1bf-11ea-8680-d323e218d291.png)

**Comment by amanprateek123** [comment]
@mariobehling  I want to work on this issue. Please assign this issue to me.Also, as I am new to this repo, please guide me through.

**Comment by snitin315** [comment]
@amanprateek123 Go ahead, you can find corresponding files in the `app/templates/components/forms/wizard` folder.

**Comment by amanprateek123** [comment]
Thank You @snitin315. First, I will familiar with the code and then update you soon!

**Comment by amanprateek123** [comment]
@mariobehling @snitin315  I did the given changes. But, please tell me that how can I see the Wizard 3 and Wizard 5 UI's as forward button is disabled and i couldn't enable it .

**Comment by snitin315** [comment]
Please fill the required fields in form to enable the forward button.

**Comment by amanprateek123** [comment]
@snitin315 Yes, I tried. But, there is a condition that I have to verify my email. and the verification link is not working.

**Comment by snitin315** [comment]
Replace domain name with `localhost:4200` in verfication link

**Comment by amanprateek123** [comment]
I did all the changes. Thanks for your help @snitin315 . Now,Can I make a PR for this issue?

**Comment by snitin315** [comment]
Yes

**Comment by amanprateek123** [comment]
@snitin Is there any template for the PR of @Fossasia?

**Comment by snitin315** [comment]
You will see the template while creating the PR.

**Comment by ashish009kum** [comment]
can i apply for this issue
@mariobehling , @snitin315

**Comment by maze-runnar** [comment]
@ashish009kum go ahead, you will get help from above comments. app/templates/components/forms/wizard

**Comment by suyash-patil** [comment]
> Replace domain name with `localhost:4200` in verfication link

@snitin315: Can we include this to documentation? I would like to work on this.

**Comment by terminator0309** [comment]
is this issue still open..?

**Comment by terminator0309** [comment]
wizard 3 and 5 are not fixed, i want work on this issue... i am new to all this open source so this might be a good start for me :)

**Comment by terminator0309** [comment]
![image](https://user-images.githubusercontent.com/57085155/96360060-f5856b80-1136-11eb-8431-4bf5266b8776.png)

is that ok.

**Comment by terminator0309** [comment]
![image](https://user-images.githubusercontent.com/57085155/96360174-3e89ef80-1138-11eb-8369-287d1b4b5605.png)
and this.

**Comment by terminator0309** [comment]
@snitin315
