### ISSUE TITLE
Wizard Step 1: Move and simplify "Event Types"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5014]
In Wizard Step 1 please

1. Move "Event Types" right below "Event Name" and above "Venue/Location".
![Screenshot from 2020-09-08 11-00-27](https://user-images.githubusercontent.com/1583873/92455949-98ef7200-f1c2-11ea-9e02-1eb2b8e484c6.png)

2. Simplify the forms by moving them next to each other. There is also no need to have a box description outside of the box.
![Screenshot from 2020-09-08 10-54-31](https://user-images.githubusercontent.com/1583873/92456057-b91f3100-f1c2-11ea-9827-e09617986ead.png)

**Comment by Raunaksingh100** [comment]
@mariobehling can you provide the link of this page??

**Comment by terminator0309** [comment]
i want to work on this enhancement ... 
I am new to open source projects and this issue looks fair to get started

**Comment by daretobedifferent18** [comment]
I am working on this issue.
