### ISSUE TITLE
For online only events, use local timezone by default when displaying schedule

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-frontend#5015]
**Is your feature request related to a problem? Please describe.**
At present it's necessary for the user to change timezones to view the schedule in their local timezone. This makes sense for in-person only events (because the user is presumably planning to travel to the venue, in which case they'll be scheduling in the venue's local timezone), some sort of sense for hybrids (because it's not clear what the default should be), but no sense at all for online-only events because the user is presumably planning to attend while still in their current timezone (indeed, their current location).

**Describe the solution you'd like**
When the schedule for an online-only event is displayed (e.g. https://eventyay.com/e/8fa7fd14/schedule?date=2020-09-09), the timezone should default to whatever timezone is appropriate for the detected user location. Note that location and timezone detection are already implemented, the only change that I'm proposing is that the latter be selected automatically for online-only events, rather than requiring the user to change it.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by iamareebjamal** [comment]
This is now implemented and will be deployed in an hour, but you'll have to first mark the event online or mixed using the new option in the event wizard.

![image](https://user-images.githubusercontent.com/3874064/92582088-265bc080-f2ae-11ea-8a34-4a5751da8c7b.png)
