### ISSUE TITLE
Wizard Step 1 / Public Event Page: Description Cannot add Links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5017]
For spam reasons I think we did not support links in the event description previously. However, it turns out that it is important for events to be able to add links into the description.

Therefore please provide the option to add links and linkify them in the public event page.

![Screenshot from 2020-09-08 12-10-00](https://user-images.githubusercontent.com/1583873/92463701-71050c00-f1cc-11ea-9aa7-88f39f94a26e.png)

**Comment by maze-runnar** [comment]
working on it.
