### ISSUE TITLE
Implement sessions API for public event page at public/sessions

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#502]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/28346561-5df5f29c-6c4f-11e7-9942-bffcf3c53746.png)

**Comment by utkarshnath** [comment]
I'll work on this

**Comment by geekyd** [comment]
@utkarshnath Please, go ahead! 👍
