### ISSUE TITLE
Add Gitter and Telegram to footer and admin pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5022]
Add Telegram and Gitter.im to footer and admin pages here https://eventyay.com/admin/content

![Screenshot from 2020-09-09 08-56-38](https://user-images.githubusercontent.com/1583873/92565115-7ae54880-f27a-11ea-891f-617034898cb3.png)

**Comment by jyotiranjankalta81** [comment]
please give me this project i can do it.

**Comment by maze-runnar** [comment]
we dont assign issues, just claim one and try to solve it.

**Comment by progmatic-99** [comment]
The telegram link should point to the fossasia group or eventyay ??

**Comment by iamareebjamal** [comment]
eventyay

**Comment by gupta-piyush19** [comment]
@iamareebjamal I want to add this feature, please allow me to do and also please provide the link where the telegram icon would redirect.

**Comment by iamareebjamal** [comment]
https://t.me/eventyay

**Comment by gupta-piyush19** [comment]
> 
> 
> https://t.me/eventyay

I think this link is not working, please do check if there is any error from my side or the link is broken.

**Comment by iamareebjamal** [comment]
It's working

**Comment by dsnehasish74** [comment]
What should be the link for Gitter.im

**Comment by snitin315** [comment]
> What should be the link for Gitter.im

The links shouldn't be hardcoded and should be created, edited, updated by the admin only. 

>Add Telegram and Gitter.im to footer and admin pages here https://eventyay.com/admin/content

**Comment by snitin315** [comment]
For more information, you can see how the Patreon link was added ->

https://github.com/fossasia/open-event-frontend/pull/4974
fossasia/open-event-server#7243

**Comment by mariobehling** [comment]
Thanks. There is still a small issue though. As soon as I enter the link "https://" switches to "https". So, the links do not work due to missing "://".

**Comment by mariobehling** [comment]
![Screenshot from 2020-09-17 08-00-42](https://user-images.githubusercontent.com/1583873/93426360-28c8a680-f8bc-11ea-9a4a-f36a7ecec03a.png)

**Comment by iamareebjamal** [comment]
This is a bug in LinkInput again. It's become too complex to track changes. Will reimplement it soon. Making it normal input for now
