### ISSUE TITLE
Refund Policy: Only show if organizer has defined refund policy and don't prefill

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5036]
1. Refund policy should not be prefilled in the wizard step 2. There should be no entry "All sales are final. No refunds shall be issued in any case."

2. The refund button on the public ticket payment form should only appear if the organizer has filled in info.

![Screenshot from 2020-09-09 20-55-07](https://user-images.githubusercontent.com/1583873/92641282-cb8e8d00-f2de-11ea-9cbf-d2282b6b70a6.png)

**Comment by iamareebjamal** [comment]
Fixed
