### ISSUE TITLE
Admin: Add Action Column to send Password Reset and Activation link to users

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5037]
Sometimes users contact us and say, they have not received the account verification or password reset link. 

Therefore on https://eventyay.com/admin/users/ please implement the following:
* add a column "Actions" with
  * a button to send a password reset email to the user
  * Only for Unverified Users show a button to resend the "Verification Email"

![Screenshot from 2020-09-09 22-31-12](https://user-images.githubusercontent.com/1583873/92650384-b6205f80-f2ec-11ea-81da-73a9795c0cc7.png)

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by MeghalBisht** [comment]
Solved in #7043
