### ISSUE TITLE
Implement user API on settings/contact info

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#504]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-07-19 14-07-15](https://user-images.githubusercontent.com/12807846/28358196-979f7bbc-6c8b-11e7-967a-51d7d1e36633.png)

**Comment by sumedh123** [comment]
I ll take this up

**Comment by sumedh123** [comment]
@niranjan94 Is the 'contact' attribute in the user model same as phone of the user?

**Comment by niranjan94** [comment]
Yes
