### ISSUE TITLE
Show prefix from start in LinkInput

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#5042]
The prefix remains to be `https://` for a predefined link until I start typing in the field. For example, for instagram it will be `https://` but when I start typing it becomes `https://instagram.com/`

It should be `https://instagram.com/` since the beginning.

_Originally posted by @iamareebjamal in https://github.com/fossasia/open-event-frontend/pull/5038#issuecomment-690411983_

**Comment by snitin315** [comment]
This is probably because we are using `observers`

**Comment by iamareebjamal** [comment]
Then the same function can be called on init. But let's move on. Enough time has been spent since last week on just 2 issues

**Comment by daretobedifferent18** [comment]
This issue will be solved after #5709

**Comment by daretobedifferent18** [comment]
@iamareebjamal pls close this issue, no more an issue
