### ISSUE TITLE
Wizard Step 1/Public Event Page: Switched off map option still visiblta

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5043]
The map for a location is still visible even if the option has been deactivated. Please do not show the map when deactivated in the location view.
![Screenshot from 2020-09-10 18-19-05](https://user-images.githubusercontent.com/1583873/92761590-233a0080-f392-11ea-8ecd-b36f44cb55ea.png)

![Screenshot from 2020-09-10 18-16-24](https://user-images.githubusercontent.com/1583873/92761419-f5ed5280-f391-11ea-87de-32826a793b11.png)

**Comment by iamareebjamal** [comment]
We discussed previously to remove this option in the future to reduce the complexity. Is it needed?
