### ISSUE TITLE
Implement user API on settings/password

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#505]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-07-19 14-08-50](https://user-images.githubusercontent.com/12807846/28358245-ce81c7de-6c8b-11e7-9181-aacd261c8a32.png)

**Comment by utkarshnath** [comment]
I'll work on this

**Comment by niranjan94** [comment]
@utkarshnath we don't have a password reset endpoint yet.

**Comment by geekyd** [comment]
@sumedh123 Please take this up. Please check  fossasia/open-event-orga-server#4267

**Comment by sumedh123** [comment]
@geekyd Okay I ll take this up.

**Comment by sumedh123** [comment]
@geekyd We misunderstood here. It's not the update password API. It's the forgot password one which is present at the login page in which we have to send two requests. One to send email, and second to update.

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 This one is on hold untill we have endpoint for resetting the password.

**Comment by sumedh123** [comment]
@niranjan94 The server has created a separate endpoint for this one. Its not JSON API spec type. It's ```application/json``` type. But, it requires JWT token for authorization. Shall I get that by the loader method itself and then do the request to change the password? Or can we get the currnet users auth token by any other workaround?

**Comment by niranjan94** [comment]
@sumedh123 just use the loader. It will take care of adding the correct header.
