### ISSUE TITLE
Sessions: Do not allow "Withdraw" session after session was held or when session is locked

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5051]
Sessions can be withdrawn after session was held or when session is locked.

Compare https://eventyay.com/e/8fa7fd14/session/6262
![Screenshot from 2020-09-11 15-35-44](https://user-images.githubusercontent.com/1583873/92932039-a320a300-f444-11ea-86ea-1b960ed6b347.png)

**Comment by iamareebjamal** [comment]
We discussed that we were still to allow edits after the session was held and to only prevent editing if session was locked?

**Comment by anjali1102** [comment]
Claiming this issue
