### ISSUE TITLE
Public Session Page: Show social links, embed youtube or other video, add link to slides

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5054]
The public session page should show the following additional items similar to generated website: http://2019.fossasia.org/event/schedule.html#5227

* social links
* embed video, e.g. youtube
* link to slides

Example for a session page: https://eventyay.com/e/8fa7fd14/session/6258

![Screenshot from 2020-09-11 16-09-12](https://user-images.githubusercontent.com/1583873/92936104-fd703280-f449-11ea-8c66-86110323f1e9.png)

**Comment by gr8geek** [comment]
@mariobehling  can I takeup this issue
