### ISSUE TITLE
Implement email notification API on settings/email-preferences

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#506]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-07-19 14-09-59](https://user-images.githubusercontent.com/12807846/28358290-f84200d4-6c8b-11e7-85e8-6d111ab057a3.png)

**Comment by sumedh123** [comment]
@geekyd Do we have an endpoint for this?

**Comment by geekyd** [comment]
We need to implement the email notifications API
https://open-event-api.herokuapp.com/#email-notifications

**Comment by sumedh123** [comment]
@niranjan94 @geekyd Untill my other PR is on hold, can I take this up?

**Comment by geekyd** [comment]
Which PR are we talking about here?

**Comment by sumedh123** [comment]
@geekyd Implementing API for settings/contact-info. The email field has to set editable so as to update the user info. Once the server people get it done, I can continue on that one.

**Comment by geekyd** [comment]
Thanks for explaining. Please proceed :+1:

**Comment by sumedh123** [comment]
@geekyd Please close this issue. The PR regarding this issue is merged. Thanks.
