### ISSUE TITLE
Pricing: Link Missing on Menu on Mobile Views

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5063]
On mobile view there is no pricing in the menu for anonymous users.

![Screenshot from 2020-09-13 13-03-37](https://user-images.githubusercontent.com/1583873/93016471-b442ee80-f5c1-11ea-97e3-035a1b77ce43.png)

**Comment by sarthakhanda** [comment]
Please allow me to work on this issue!

**Comment by maze-runnar** [comment]
Go ahead
