### ISSUE TITLE
Sidebar overlaps landing page.

### ISSUE THREAD

**Issue by sarthakhanda** [fossasia/open-event-frontend#5067]
**Describe the bug**

When I restore down the window & open the side-bar, it appears like this:
![bug1](https://user-images.githubusercontent.com/71185918/93082375-766fc400-f6ae-11ea-92ac-5bb5b55f526e.jpg)

but when i maximize the window it appears like this:
![bug2](https://user-images.githubusercontent.com/71185918/93082434-8daeb180-f6ae-11ea-867d-8f2e0ceaeceb.jpg) 

The sidebar stays in view & the landing page moves out of the frame.

**Expected behaviour**

The sidebar should collapse on its own or one can add a close button (X) to close it.
(because we only have the hamburger menu to open & close it)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox.

**Comment by mariobehling** [comment]
You are testing the mobile version when you start in the small resolution. If you load the site in a standard resolution for desktop browsers it will be fine. Therefore closing it.
