### ISSUE TITLE
Privacy popup links to not-existing page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5071]
1. The privacy pop-up should stay there until a user clicks it to go away.
2. The link on the policy should direct to /privacy.

![Screenshot from 2020-09-15 10-19-17](https://user-images.githubusercontent.com/1583873/93184788-f5abd900-f73c-11ea-8694-d007f786fc0f.png)

**Comment by iamareebjamal** [comment]
Duplicate of https://github.com/fossasia/open-event-frontend/issues/5028?
