### ISSUE TITLE
Feature: Add to Calendar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5072]
Please add the feature 
- [x] "Add to Calendar" to the system
- [x] Position it above the event links on the right hand side of a public event page
- [x] Also include a time in date box as below in the example

- [x] Google Calendar
- [x] iCal
- [ ] Yahoo
- [ ] Outlook

Compare: https://eventyay.com/e/16fa59c7

![Screenshot from 2020-09-15 12-04-12](https://user-images.githubusercontent.com/1583873/93197303-bfc22100-f74b-11ea-9c8e-5b7e51a98045.png)

This can be done in a similar fashion as below.

![Screenshot from 2020-09-15 12-02-40](https://user-images.githubusercontent.com/1583873/93197307-c05ab780-f74b-11ea-8527-4cb703d739d9.png)

**Comment by gr8geek** [comment]
@mariobehling  can i take up this issue and contribute
I

**Comment by praveenalpha** [comment]
i want to fix this issue......

**Comment by iamareebjamal** [comment]
Reference https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/google.md

**Comment by iamareebjamal** [comment]
Other calendars left

**Comment by akash2408** [comment]
iam working on it

**Comment by akash2408** [comment]
is there something wrong in my yahoo and icloud urls that i provided earlier in PR?

**Comment by mariobehling** [comment]
Please also add the `.ics` for the ical calendar.

**Comment by iamareebjamal** [comment]
@akash2408 Yes

**Comment by iamareebjamal** [comment]
@mariobehling There is `.ics` already. Which browser did you test it on? Maybe it is truncating the filename. I'd need to test it more. If confirmed, I'll remove the event name from the ICS file

**Comment by akash2408** [comment]
> @akash2408 Yes

can u tell me whats wrong is it not adding the events correctly or something else?

**Comment by iamareebjamal** [comment]
Yes, it is throwing error. Read the comments on the PR again. There is even an screenshot

**Comment by akash2408** [comment]
> Yes, it is throwing error. Read the comments on the PR again. There is even an screenshot

thanks. i just see that outlook is throwing error in some events. but yahoo is working fine. i think so

**Comment by codedsun** [comment]
Taking this up!
