### ISSUE TITLE
Admin: Sort users according to signup date and ensure search for names and emails works

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5081]
On https://eventyay.com/admin/users/all please implement the following:
* sort users according to signup date with the last signups on the top
* ensure search works for 
  * names
  * email addresses

![Screenshot from 2020-09-17 12-51-51](https://user-images.githubusercontent.com/1583873/93461277-d51e8300-f8e4-11ea-9911-cd14657c6c10.png)

**Comment by 2580ayush2580** [comment]
Sir, I want to work on this.
