### ISSUE TITLE
System Content: Standardize Pages - Terms, Privacy etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5094]
Our system pages should be improved. Please change the pages 
* [ ] Pricing
* [ ] Contact
* [ ] Terms and Conditions
* [ ] Refund Policy
* [ ] Privacy
* [ ] Attendee App
* [ ] Organizer App

as follows:
* [ ] make all pages into a central content column
* [ ] show the page title over a header similar to the below image
* [ ] use the same header for all pages except the mobile pages. Use the source image for the background here: https://pixabay.com/photos/startup-meeting-brainstorming-594090/ 
* [ ] use the following linked image for Attendee and Organizer App page: https://pixabay.com/photos/office-meeting-business-partners-336368/
* [ ] add a gray overlay over the image similar to the public event pages using html (do not change the source image)
![Screenshot from 2020-09-19 02-04-21](https://user-images.githubusercontent.com/1583873/93654180-8542d780-fa1c-11ea-80e5-71c8e710551b.png)
* [ ] add a full-width gray bottom bar above the footer on each page with the text "Still have questions? [Visit our FAQ](https://support.eventyay.com) to find answers." Ensure you include the link.
![Screenshot from 2020-09-19 02-06-43](https://user-images.githubusercontent.com/1583873/93654329-2336a200-fa1d-11ea-8bbe-a49785877957.png)

**Comment by chetas411** [comment]
Do you mean to wrap up all the content including the header into a container element in all the pages from the first point given in the description?
