### ISSUE TITLE
Wizard Step 1: Ticket box - take out "Settings"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5095]
The word "Settings" is not needed in the ticket box. Please take out it and move the below content up.

![Screenshot from 2020-09-19 14-50-11](https://user-images.githubusercontent.com/1583873/93667602-8a893c00-fa87-11ea-8896-b44e382d7364.png)

**Comment by deytulsi18** [comment]
I want to solve this isssue.

**Comment by deytulsi18** [comment]
please guide me this is my first issue.

**Comment by maze-runnar** [comment]
@deytulsi18  go to `app/templates/component/forms/wizard/basic-details.hbs` and delete the word sentence.

**Comment by deytulsi18** [comment]
@maze-runnar did not get what you are saying to me.
can you please tell it again.

**Comment by deytulsi18** [comment]
@iamareebjamal can you suggest me a first-timer issue for me to solve.

**Comment by maze-runnar** [comment]
@deytulsi18 https://github.com/fossasia/open-event-frontend/issues/5094, this is a good and easy issue, and give you a better idea too how to work with project.

**Comment by deytulsi18** [comment]
@maze-runnar 
Ok I'll try my best.
Thank you
