### ISSUE TITLE
Session/Speaker: Distinguish Private and Public Info Pages/Views and Separate Them

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5100]
In previous iterations we focused on the views of the public information of sessions and speakers, e.g. shown on the schedule and public session page. However, the speaker can enter much more information than should be publicly available in their call for speakers response. 

Right now we do not show to the speaker which information is public or privately shown to the review team. We also do not have a page to show the session and speaker information which includes the private info. It is only possible to see the private info
if the speaker or organizer/reviewer edits sessions/speakers info.

Therefore we need to change and tweak a number of things in different areas. (Please open sub-issues where necessary)
1. In the wizard step 5 session and speaker forms please add a column "Show Public" to display a field publicly. If this is chosen show the field on the public session or speaker page. In a first step we could simply decide which info is public or private by default show the info "public" or "private" instead of a switch button.
2. Session View page and Session Edit page are confusing - we added the same functionality under different URLs, e.g. compare https://eventyay.com/e/598/cfs/session/5057/edit and https://eventyay.com/events/3689bc98/sessions/5057/edit. Whereas we only have one (public) page to view the session page here https://eventyay.com/e/3689bc98/session/5057 without showing the private form fields. What to do?
* We need to distinguish public and private pages and views. 
  * Public page view is on a page for attendees of an event. It only includes essential information and fields marked as "public" in the wizard.
  * Private page view is a page for speakers and organizers/reviewers. It includes all submitted information.
* Where to put private vs. public view page and which one can be edited?
  * Public pages are part of an event and can continue to stay on pages such as this one here https://eventyay.com/e/3689bc98/session/5057. These pages should not have an edit or withdraw button. They are just there to show information to attendees.
  * Private pages as in the above case the private submission page should be here as in this example https://eventyay.com/events/3689bc98/sessions/5057/ They should include an edit and withdraw button 
  * In the above example the editable version would be available here https://eventyay.com/events/3689bc98/sessions/5057/edit
* When a user submits a session to the call for speakers, session page and speaker page should be created according to the event. They should not follow the cfs slug. Speaker and organizers can both edit the session. Once marked as "Locked" only the organizer can edit it.

Compare:
* Private session page - Access by speaker and organizers
/events/[event-number]/sessions/[session-number]/
/events/[event-number]/sessions/[session-number]/edit
* Public - Public Access
eventyay.com/e/[event-number]/session/[session-number]
(no edit page)

See below: We need one more column "public" in the forms. Public links are shown on the public speaker info. Non-public are only shown to organizers.
![Screenshot from 2020-11-01 05-46-36](https://user-images.githubusercontent.com/1583873/97795369-adba1600-1c05-11eb-8387-ba18897fc15d.png)

The following fields need to be public always:
* [ ] Name
* [ ] Short bio
* [ ] Title
* [ ] Short Abstract

The info that a field is "public" should be shown on the call for speakers in brakets, e.g. _(public)_

**Comment by maze-runnar** [comment]
looking into this

**Comment by maze-runnar** [comment]
@iamareebjamal I have added a isPublic field in custom form. Is there a way to use that on session page?

**Comment by iamareebjamal** [comment]
If you've added it in model, then you need to modify the API as such that only public custom form fields are returned when requested from non organiser user

**Comment by maze-runnar** [comment]
but how to return that custom-form in sessions?

**Comment by iamareebjamal** [comment]
Will think of it, first implement model changes and migration in server

**Comment by mariobehling** [comment]
It seems the point number 2 is not yet taken care. If you need some insights why the current implementation is a problem, maybe we schedule a call.

**Comment by iamareebjamal** [comment]
Yes, I forgot to reopen after merging the PRs. The issue is only 1/3 complete

**Comment by mariobehling** [comment]
Public vs. private session page still needs to be implemented.

**Comment by mariobehling** [comment]
Unfortunately this issue has not been solved. As I have already reopened it before it seems it is not clear enough. Therefore I created a new issue with only the remaining parts open. Please follow up here asap. So, we do not loose the train of thought: https://github.com/fossasia/open-event-frontend/issues/6222
