### ISSUE TITLE
Video Tab: Implement Feature "Add Jitsi Room" to Microlocations

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5101]
Organizers should have two options to add a video room 
a) add a room manually anywhere on the Internet
b) add a Jitsi room with a button.

According to the Jitsi documentation here https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe the following should be possible.

Open question is: In order to restrict access to rooms we could also add rooms into an 100% iframe on eventyay.com and restrict access to account/ticket holders.

Please implement the option to automatically create a Jitsi room as follows on the video tab:
- Microlocation: add a button "Add Jitsi Room" and autofill other columns
- Video Room: After user has pushed "Add Jitsi Room" automatically create a virtual room at https://meet.jit.si/eventyay/[eventID-room-name]
- Pin: Automatically create a room password and add info here
- Additional Information: Automatically add Jitsi dial-in numbers etc. into this column
- Stream: Apart from the existing public stream URL, also show a field for the Streamkey here, that organizers can enter and pass on the stream key to Jitsi to enable the feature "Stream to Youtube" 
- In field "Additional Information" add: In order to stream a Jitsi Session the moderator in the session needs to start the stream.

Other features:
* Mute all participants in room when they join
* remove the "Embed Jitsi Meet Conference"
* Hide "Invite More People" using HIDE_INVITE_MORE_HEADER (Reference https://github.com/jitsi/jitsi-meet/pull/7021)
* Hide "not secure icon"

![Screenshot from 2020-09-19 14-16-04](https://user-images.githubusercontent.com/1583873/93666971-bbb33d80-fa82-11ea-816a-0306769e2648.png)

**Comment by iamareebjamal** [comment]
Assuming this in the implementation: A room can have a single video stream linked. But a video stream can be linked to several rooms
