### ISSUE TITLE
Search: Explore filters not working

### ISSUE THREAD

**Issue by ShubhankarKG** [fossasia/open-event-frontend#5104]
**Describe the bug**
The filters for the explore events isn't working as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/explore'
2. Click on any filter.
3. See error

**Expected behaviour**

Events are filtered as per selected filters.

**Screenshots**

![Screenshot from 2020-09-20 17-03-32](https://user-images.githubusercontent.com/50791000/93710321-56834900-fb63-11ea-8ced-3385c504e8a9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox

**Additional context**

I'd like to work on this one :)

**Comment by HADES-01** [comment]
@mariobehling Would love to fix this bug. Please assign it to me.

**Comment by ShreyanshSrivastava** [comment]
Event explore filters are working fine on localhost:4200/explore but I don't know why it is not working on the actual site of eventyay.
If someone can shed some light over this issue as why this might be happening it will be great to start then.

**Comment by iamareebjamal** [comment]
solved
