### ISSUE TITLE
Adding page size to index page for displaying complete list of event

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#511]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently, the events index page doesn't display the complete set of published events due to lack of defined page size.

**Expected behavior:**
It should display all the events published events.

**Comment by niranjan94** [comment]
This isn't a valid solution. If there are a 1000 live events, we don't want
to display all of them in the front page. If we do, it'll be too much of a
network usage. Instead, what we should be doing is display some, Let's say
top 10 (ordered by the closet start time) and then keep loading more as the
user scrolls down. (something like an infinity scroll) or show pagination
bar at the bottom and let the users traverse the pages.

The order of the top events could be based on popularity, views, rating etc
in future.

**Comment by niranjan94** [comment]
See how eventbrite and other event websites do and propose an
idea/implementation please.

**Comment by niranjan94** [comment]
@harshitagupta30 what's the update on this ?

**Comment by harshitagupta30** [comment]
@niranjan94 Is is possible to use some plugin here for infinite scroll or pagination?
https://github.com/hhff/ember-infinity
https://github.com/hhff/ember-infinity

**Comment by niranjan94** [comment]
No @harshitagupta30. Keep it very simple. Please see how eventbrite does it like said before and see if we can have something similar here.

**Comment by harshitagupta30** [comment]
@niranjan94 I saw how eventbrite is opening. They are showing some 15 popular events and have a see more button which links to explore route and displays all event. Do you want the same thing i.e. redirecting to explore?

**Comment by ritikamotwani** [comment]
@pradeepgangwar @srv-twry @mayank8318 the start page is now linked to the explore route to find more events. If any more implementation is needed this issue can be reopened.
