### ISSUE TITLE
Frontpage: Limit display of events based on the public ticket availability

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5110]
Do not show ticket on start page if an event does not have a public ticket available and does not show a public ticket because it:
- [x] does not have any available ticket on the start page and restricts remaining tickets with “access code”
- [x] limit sales time of ticket and no longer has a ticket on the public page
- [ ] limits the number of tickets and therefore no longer has a ticket on the public page

A possibility that was discussed to implement this was:
* using a cron job that caches the result and updates the start page regularly
* possibly add an option to switch off the cache to test the system

Please also do the following:
* List all start page restrictions in a subtab on the Admin Settings page here https://eventyay.com/admin/settings -> in https://eventyay.com/admin/settings/frontpage

Related to:
https://github.com/fossasia/open-event-frontend/issues/4963
https://github.com/fossasia/open-event-frontend/issues/4994

**Comment by thrishik7** [comment]
@mariobehling  Can I work on this?

**Comment by maze-runnar** [comment]
> Do not show ticket on start page if an event does not have a public ticket available.

@iamareebjamal is it not to show an event on start page if an event does not have a public ticket?

**Comment by iamareebjamal** [comment]
Yes

**Comment by maze-runnar** [comment]
>  limit sales time of ticket and no longer has a ticket on the public page.

@iamareebjamal  it means that if the sales time of the ticket is passed it should not show on the start page?

**Comment by iamareebjamal** [comment]
Yes

**Comment by maze-runnar** [comment]
>  limits the number of tickets and therefore no longer has a ticket on the public page

what it exactly means?

**Comment by iamareebjamal** [comment]
If there are 10 tickets and all of them are sold
