### ISSUE TITLE
Online Event: Webinar URL results in "not a valid URL" when copying link from browser including https/https

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5115]
If an organizer adds a webinar URL and tries to save the event it will show "Not a valid URL".

Compare: https://eventyay.com/events/56caaccd/edit/basic-details

![Screenshot from 2020-09-21 19-09-45](https://user-images.githubusercontent.com/1583873/93798539-265ca880-fc3e-11ea-98ab-7fe5608e0a82.png)

**Comment by iamareebjamal** [comment]
Please try again, I could add it

**Comment by mariobehling** [comment]
Trying to add one here: https://eventyay.com/events/cf7e2dde/edit/basic-details

![Screenshot from 2020-09-22 07-24-00](https://user-images.githubusercontent.com/1583873/93846543-a3226d80-fca4-11ea-82dd-9305a58b3f00.png)

**Comment by iamareebjamal** [comment]
Worked

**Comment by mariobehling** [comment]
Ok, but the point is, it does not work for me, e.g. here https://eventyay.com/events/a8ee39a0/edit/basic-details#

I think it should work for all users.

**Comment by iamareebjamal** [comment]
I don't think it is a user based problem. Can you check that there are no spaces in the URL
