### ISSUE TITLE
Cannot Save Event Error "Tickets are required" even though ticket is there

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5117]
Cannot save existing published event as I receive the error message "cannot save event without ticket" even though there is a ticket added. 

Compare https://eventyay.com/events/921345bd/edit/basic-details 

![Screenshot from 2020-09-21 19-32-27](https://user-images.githubusercontent.com/1583873/93800920-8ef95480-fc41-11ea-94af-59d72c71fe8c.png)

**Comment by iamareebjamal** [comment]
I can save it. When does the error show up?
