### ISSUE TITLE
Organizer Invoice Generation HTML to PDF template

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5120]
We need to generate a PDF invoice using an html template. Please see the following that we can use as a basis: https://s3-eu-west-1.amazonaws.com/htmlpdfapi.production/free_html5_invoice_templates/example1.zip

* Use system fonts
* Use system website name

Use the following fields:
* Product: {Event Name}
* Description: Plan: {Plan e.g. Early Access Plan}, Ticket Sales Period: {1st Month - Last Day Month}, Sales {Amount Earned}
* Fees: {Fees owed}
* Tax: {Tax} _(currently show NA)_
* A finance charge of 5% will be made on unpaid balances after 30 days.

No need for:
* Qty
* Price
![Screenshot from 2020-09-22 09-18-12](https://user-images.githubusercontent.com/1583873/93853676-93ab2080-fcb4-11ea-9842-863c0f180196.png)

**Comment by iamareebjamal** [comment]
@mariobehling Please check if this is fine

![I3a6171bb-1](https://user-images.githubusercontent.com/3874064/93962839-59f01d80-fd79-11ea-93b1-dc054aa68f7b.png)

**Comment by mariobehling** [comment]
There is a difference between the invoice email and the actual invoice. Therefore the text does not need to be part of the invoice itself.

* No need to the text above the table
* No need for "Sales" column
* Description column should include "Amount Earned:..."
  * In dont understand what is Gross Revenue and Net Revenue in our system
  * Why does Net revenue has the format xxxx.xxx? I also see this appearing on some events now. Why do we calculate more than 2 digits behind the dot? Where does this calculation come from?
* Even if tax is 0 please show S$0.00

**Comment by iamareebjamal** [comment]
Gross Revenue is total amount earned. Net revenue is `gross - fee`

> Why do we calculate more than 2 digits behind the dot? Where does this calculation come from?

It reports as much digits as it needs to precisely show the sum of all amounts, I'll round it to 2 digits

**Comment by mariobehling** [comment]
Ok, then please only show "Gross Revenue" but instead use "Amount Earned:.." and the fee is shown in the "Fees" column.

**Comment by mariobehling** [comment]
According to what I see after checking other services in detail, they usually give 30 days as a due date. So, we should also follow that. Therefore please change due date to 30 days.

**Comment by mariobehling** [comment]
I just added payment info into my account at https://eventyay.com/account/billing/payment-info
We also need to show a tax ID for the consumer/organizer as required by tax offices in many countries.

**Comment by iamareebjamal** [comment]
PL

**Comment by mariobehling** [comment]
Here is the invoice format that we can use for now. It is inspired by others:
202009U-00001
Invoice Format: YYYYMMU-Running-Invoice-Number

![Screenshot from 2020-09-23 13-03-11](https://user-images.githubusercontent.com/1583873/94005109-0f34cc80-fd9e-11ea-9420-25f3d3a09405.png)

**Comment by iamareebjamal** [comment]
@mariobehling Showing the auto incrementing ID in PDF will not be possible as we only get the new ID once we save the invoice in the database, and we don't want to save the invoice in database before generating PDF, because if due to any error, the PDF is not generated, then the invoice will be in an inconsistent state. We can use a randomly generated identifier instead of running invoice number

**Comment by mariobehling** [comment]
The problem is that most companies are required by law to have invoices that increment. That means in their books they need to have an invoice xxx001, xxx002, xxx003 etc. and it is not possible that they skip invoice xxx002. How to deal with that?

**Comment by iamareebjamal** [comment]
Will think of something. Implementing other things for now so that this does not block other progress

**Comment by iamareebjamal** [comment]
Even with DB autoincrementing keys, it may skip a number due to rollback of transactions, so I'm not sure how they implement it. Will search about it.

**Comment by mariobehling** [comment]
Rollback meaning e.g. if we have to reimburse or revert a transaction?

In such a case a new invoice would have to be created which would be negative. Not sure if that is what you mean.

**Comment by iamareebjamal** [comment]
No, I meant if there was a DB transaction error (technical), databases are rolled back to revert the changes made, this can lead to skipped numbers

**Comment by iamareebjamal** [comment]
Reference on why it is complex to reliably generate unique incrementing numbers without a gap in a multi process environment: https://stackoverflow.com/questions/31751744/spring-jpa-with-hibernate-fiscal-sequence-generation

**Comment by iamareebjamal** [comment]
This is final PDF:
![202009U-4d0f9362-1](https://user-images.githubusercontent.com/3874064/94087254-ed355b80-fe2a-11ea-9484-a5c662a91f6e.png)

**Comment by iamareebjamal** [comment]
Merged as PR was getting large. Please reopen if more changes are required
