### ISSUE TITLE
Public Event Page Menu: Moving to Sponsors, Organizers etc. requires two clicks

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5123]
To get to sections on the same page that are listed on the menu requires two clicks, e.g. sponsors or organizers.

Compare https://eventyay.com/e/16fa59c7

![Screenshot from 2020-09-23 00-38-17](https://user-images.githubusercontent.com/1583873/93944537-4b801280-fd35-11ea-8aea-c8253a3f1ed0.png)

**Comment by thrishik7** [comment]
@mariobehling  Can I work on this ?

**Comment by mariobehling** [comment]
Please go ahead. We need this as a priority now.

**Comment by daretobedifferent18** [comment]
I am working on this issue.

**Comment by iamareebjamal** [comment]
The problem has been fixed completely now
