### ISSUE TITLE
Missing 'empty' rule in repeat password validation on settings/password route

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#513]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Missing 'empty' rule in repeat password validation

**Expected behavior:**
there should be a validation for an empty field

**Comment by niranjan94** [comment]
Why is this a bug? It anyway checks and matches with the password field right.? So it wouldn't matter if it is empty or not.
