### ISSUE TITLE
Invoice should always show two digits for cent

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5130]
The invoices currently show currencies like 234.5 instead of 234.50. Please show two digits for e.g. Cents.

This will become more complicated as some currencies do not have Cents. But this is a first step to cover some main currencies.

![Screenshot from 2020-09-24 09-12-54](https://user-images.githubusercontent.com/1583873/94112971-7b6b0b00-fe46-11ea-9ee8-926b0490ea25.png)

**Comment by iamareebjamal** [comment]
![image](https://user-images.githubusercontent.com/3874064/94144940-6e263e80-fe8f-11ea-8d7e-e0a95648083b.png)
