### ISSUE TITLE
Event Dashboard Info Box: Enhance it and fix issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5131]
The event dashboard needs some enhancements and fixes. Please change as follows:

* Delete row "number of revisions"
* Depending on event show
   * either "Location" - and show the address
   * "Online Event" - and show the links
   * "Location: To be announced" or 
   * show both "Location" and "Online Event" rows for "Mixed Events" including data
* Fix social media names to start with a capital, e.g. Twitter instead of twitter
  * fix it on the infobox
  * also fix it on the public event page (which is the same cause) compare to https://eventyay.com/e/0917096d
* Change "External Event URL" to "Event Site"

![Screenshot from 2020-09-24 19-07-33](https://user-images.githubusercontent.com/1583873/94177229-84d19300-fe99-11ea-852d-fc6acd04fcc5.png)

![Screenshot from 2020-09-24 10-14-41](https://user-images.githubusercontent.com/1583873/94119492-47e0ae80-fe4f-11ea-8b1a-8381e5c4597b.png)

**Comment by Raunaksingh100** [comment]
can i work on this issue

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mariobehling** [comment]
Thanks! I added some more details to the description in the issue.

**Comment by AbhipsaGuru1012** [comment]
@iamareebjamal Hi, are there any files with social media links? If yes please share those

**Comment by iamareebjamal** [comment]
There is no need for that

**Comment by Soumi150** [comment]
The location part seems to have been fixed already. I would like to work on rest of the issue.

**Comment by sachinchauhan2889** [comment]
Working on this

**Comment by Raunaksingh100** [comment]
@mariobehling can you tell why is no codeheat label for this ?

**Comment by jasssingh2345** [comment]
I will fixed last points of this issue @mariobehling @iamareebjamal can you add the codeheat label for this 

This is my first codeheat label issue

**Comment by mariobehling** [comment]
Mostly fixed. Thanks!
