### ISSUE TITLE
Unable to delete draft event without orders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5133]
As an organizer or admin I am not able to delete an event. Error messages:
* unexpected error or
* event is associated with orders and cannot be deleted (there is one expired order)

Compare: https://eventyay.com/events/5c97f24f/settings
![Screenshot from 2020-09-24 11-07-36](https://user-images.githubusercontent.com/1583873/94125194-58485780-fe56-11ea-8ae8-dfbe88231645.png)

**Comment by harshfulzele987** [comment]
Interested, please help me to understand these bug???

**Comment by iamskab** [comment]
Willing to work on this bug !
@mariobehling  Kindly assign me so that others can understand i'm working on this .

**Comment by iamareebjamal** [comment]
They can see your comment. Please go ahead

**Comment by maze-runnar** [comment]
it's working at the time. Not able to reproduce.

**Comment by iamareebjamal** [comment]
Did you create an order for an event and then tried deleting it after 15 minutes? The issue says there's an expired order associated with the event

**Comment by maze-runnar** [comment]
yes i have tried with expired order too

**Comment by iamareebjamal** [comment]
@mariobehling I was able to delete the linked event as well

**Comment by maze-runnar** [comment]
@mariobehling confirm here please.

**Comment by mariobehling** [comment]
Ok, hope the error is gone. As the screenshot shows it was there before.
