### ISSUE TITLE
Public Event Page: Social Links are Indented differently

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5140]
Please change the display of the social links text so that all links indent in the same way.

Compare https://eventyay.com/e/0917096d
![Screenshot from 2020-09-24 20-12-35](https://user-images.githubusercontent.com/1583873/94183437-b864eb00-fea2-11ea-9ad7-7318cd12df71.png)

**Comment by ShreyanshSrivastava** [comment]
Hello Sir, I want to work on this issue.
