### ISSUE TITLE
Wizard Step 1: Map not loading, Address field issues, public page only shows address in one line

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5143]
The wizard step 1 location field has a few issues.
* Map is no longer loading even if enable
* Reset Map link deletes all data in address fields
* After saving and editing the form and reopening it the address fields only show up in the address line but on expansion they do not show up in the dedicated fields (stress, city, postcode, country)
* As a result the address on the public page also shows up in one line instead of different lines for name, street, city, country

Please fix these issues as part of moving the implementation to OpenStreetMap/Mapbox.
Take out the Google map code from the project and ensure there are no console errors.

![Screenshot from 2020-09-25 04-52-46](https://user-images.githubusercontent.com/1583873/94221542-9cd20280-feeb-11ea-9f4a-c4da6c4b418d.png)
![Screenshot from 2020-09-25 04-51-43](https://user-images.githubusercontent.com/1583873/94221549-9e9bc600-feeb-11ea-8aa7-12b5bac5fe07.png)

![Screenshot from 2020-09-25 04-57-48](https://user-images.githubusercontent.com/1583873/94221595-b8d5a400-feeb-11ea-8524-437b88ed6245.png)

**Comment by iamareebjamal** [comment]
We are not storing street, city, state country separately and making them separate will require great schema changes and the search will be complicated as well

Easier would be do store them comma separated and show each comma separated string in a new line

**Comment by mariobehling** [comment]
Ok, I see. Yes with comma could be the way to go.

I just remember that it used to work that way, but might have been in version 1.

In any case the data disappears at certain actions and this should not happen.

**Comment by himanshujaidka** [comment]
for the map what we have to add so that it will load fast?

**Comment by avanisingh0105** [comment]
is this issue resolved ?

**Comment by avanisingh0105** [comment]
@mariobehling

**Comment by iamareebjamal** [comment]
Green means issue is open and not resolved

**Comment by maze-runnar** [comment]
> After saving and editing the form and reopening it the address fields only show up in the address line but on expansion they do not show up in the dedicated fields (stress, city, postcode, country)

@iamareebjamal can we create separate fields for each on server side?  I have been trying several methods but it's not working.

**Comment by iamareebjamal** [comment]
It is possible but will complicate search and other stuff needlessly and break compatibility. Will discuss in meeting later. Right now, focus on integrating OSM and Mapbox so this might not even be needed

**Comment by maze-runnar** [comment]
ok
