### ISSUE TITLE
Invoices: Add invoice and reminder emails to platform

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5147]
Please add the [invoice email templates here](https://docs.google.com/document/d/1kokiTbAwpcpPkJLJrBOnRUS3mPLwPNH5RqMoZo5usms/edit#) to the system and send them automatically on the desired day to the "owner" of an event as follows:

- Invoice Email on 1st of each month (as defined in https://eventyay.com/admin/settings/billing)
- Invoice Reminder Email after 14 days
- Invoice Reminder Email after 27 days	
- Invoice Past Due Date after 30 days	

For admins:
* In BCC send the email to the admin email of the platform
* Ensure they are visible at: https://eventyay.com/admin/messages/list

**Comment by iamareebjamal** [comment]
Did not add these in eventyay.com/admin/messages/list as:
- The page/setting does not work. We do not use the subject/bodies from here
- Will need a migration strategy, thus this must be handled in notifications milestone

BCC implementation is still left because there is no admin email setting and previously there was no BCC functionality in the platform, so that'll take some extra implementation

**Comment by iamareebjamal** [comment]
Last point left so reopening

**Comment by vj-codes** [comment]
@iamareebjamal is the last point only left or more? I would like to work on this

**Comment by iamareebjamal** [comment]
2 points are left https://github.com/fossasia/open-event-frontend/issues/5147#issuecomment-699798106

However, they are a bit complicated. You can work on them if you want to but they are not beginner-friendly

**Comment by sb39** [comment]
@iamareebjamal I want to take this up

**Comment by iamareebjamal** [comment]
Please read above comment

**Comment by sb39** [comment]
@iamareebjamal I am ok with it not being a beginner-friendly, can I take this up

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mariobehling** [comment]
We can follow up in remaining parts in a dedicated message/notification issue combining several similar issues.
