### ISSUE TITLE
Admin: By default sort users by last date joined with the most recent users showing up on top 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5157]
In https://eventyay.com/admin/users please
* sort according to the most recent user on the top (member since).
* show 50 users per page by default

Compare: https://eventyay.com/admin/users/all?sort_by=created-at&sort_dir=ASC

![Screenshot from 2020-09-26 10-45-17](https://user-images.githubusercontent.com/1583873/94336768-ce2ef900-ffe5-11ea-81ed-e4f516358468.png)

**Comment by mayank0811** [comment]
I want to work on this issue.

**Comment by Raunaksingh100** [comment]
go ahead !!

**Comment by mayank0811** [comment]
I cannot access admin webpages due to lack of permission. 
Also, does the sorting needs to be done in front-end or back-end?

**Comment by iamareebjamal** [comment]
You need to deploy the server locally and create a local super admin user

**Comment by pc-beast** [comment]
i would like to work on this issue

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-frontend/pull/5653#issuecomment-727718728

https://github.com/fossasia/open-event-frontend/pull/5653#issuecomment-873000810
