### ISSUE TITLE
Public Event Page: Display Info for online, mixed etc. on header

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5161]
The header of events is currently only showing info related to locations. When the organizer chooses online, mixed, or to be announced the header shows a location icon but nothing else. Therefore please implement the following on the public event page header, when the organizer chooses:
* Online Event show "Online Event"
* Mixed Event show the info "In-Person Event and Online Event" + show the address of the event
* To be announced show "Location to be announced" 

![Screenshot from 2020-09-27 14-04-42](https://user-images.githubusercontent.com/1583873/94364705-af0a9700-00cb-11eb-819e-c8cf4d5c94a1.png)

**Comment by HADES-01** [comment]
@mariobehling I would love to work this issue. Assign it to me.

**Comment by mariobehling** [comment]
Go ahead!

**Comment by HADES-01** [comment]
@mariobehling Do you think I should create a helper function or just include the logic in the template ?

**Comment by iamareebjamal** [comment]
Create a computed property
