### ISSUE TITLE
Admin: Sales Dashboard Not Showing Events that are Selling Tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5163]
The Admin Sales dashboards are not showing events that are selling tickets and which have generated sales.

Expected: 
* All events should actually show up. 
* Events that have not made a sale should show up with 0, but events that have made sales should show up accordingly.
* Latest events (with a newer date) should be on top of the list.
* The columns should be sortable where possible

Compare: https://eventyay.com/admin/sales

![Screenshot from 2020-09-27 20-36-20](https://user-images.githubusercontent.com/1583873/94372861-81404500-0101-11eb-8875-bcbff4cbb997.png)

**Comment by maze-runnar** [comment]
@iamareebjamal is this feature need to add in the backend too?

**Comment by iamareebjamal** [comment]
We need to make it a table and show events by descending date

**Comment by ruhci28** [comment]
Hii @iamareebjamal I want to work on this

**Comment by iamareebjamal** [comment]
@ruhci28 It is a bit involved and urgent so @maze-runnar would be working on it if you haven't started working on it?

**Comment by maze-runnar** [comment]
@iamareebjamal after applying sort this is returning only one event, why? without sort it's returning all events.
```
async model() {
    const some = await this.store.query('admin-sales-by-event',{sort:'name'});
    return some;
  }
```
![Screenshot from 2020-10-05 16-11-46](https://user-images.githubusercontent.com/56407566/95070338-9a5e7c80-0725-11eb-8890-905923798b93.png)

**Comment by maze-runnar** [comment]
And does this table needs to be changed like 
![scrnli_10_5_2020_4-15-23 PM](https://user-images.githubusercontent.com/56407566/95070612-00e39a80-0726-11eb-99d7-ba933e069bb9.png)

**Comment by iamareebjamal** [comment]
> And does this table needs to be changed like

Yes

**Comment by iamareebjamal** [comment]
> after applying sort this is returning only one event, why? without sort it's returning all events.

Please write the API URL being sent to the server so I can debug

**Comment by maze-runnar** [comment]
> > after applying sort this is returning only one event, why? without sort it's returning all events.
> 
> Please write the API URL being sent to the server so I can debug

http://127.0.0.1:5000//v1/admin/sales/by-events?sort=name

**Comment by iamareebjamal** [comment]
I'm getting multiple events using the same URL

**Comment by iamareebjamal** [comment]
@maze-runnar Please rebase server, I have fixed the API
