### ISSUE TITLE
Event Dashboard and Event Admin Dashboard: Sort Events according to Dates by Default

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5175]
To speed up organizers and admins usage of the platform please change the dashboard sorting:
* By default sort table according to oldest date first compare: https://eventyay.com/events/live?sort_by=starts-at&sort_dir=DSC
* Also sort in the same way on the admin dashboard: https://eventyay.com/admin/events/live?sort_by=starts-at&sort_dir=DSC

![Screenshot from 2020-09-29 11-55-17](https://user-images.githubusercontent.com/1583873/94545887-6d095e80-024d-11eb-83bc-7b0c2999c090.png)

**Comment by sahilsaha7773** [comment]
I want to work on this

**Comment by pc-beast** [comment]
I would like to take over the issue if @sahilsaha7773 is not working on it.

**Comment by iamareebjamal** [comment]
No, please go ahead
