### ISSUE TITLE
Attendee Page: Initializing Tickets showing up in "Completed List"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5176]
On the attendee page of events initializing tickets are showing up in the "Completed" List

Compare: https://eventyay.com/events/0917096d/tickets/attendees/completed

![Screenshot from 2020-09-29 13-22-08](https://user-images.githubusercontent.com/1583873/94552441-2b7db100-0257-11eb-9f44-acaf20927b9d.png)

**Comment by ArunTeltia** [comment]
I am working on this

**Comment by sachinchauhan2889** [comment]
i want to work on this issue

**Comment by sachinchauhan2889** [comment]
@mariobehling @iamareebjamal i tried to regenerate this error on eventyay.com and on local host both but error is not regenerated. __Initializing tickets__ are not showing under __completed__ list tab. __Initializing__ tickets are listing under __all__ tab. Could you please tell how to regenerate this error. And __pending__ tab is not available. this is a new issue. 
![01](https://user-images.githubusercontent.com/72552281/95583914-7e771580-0a5a-11eb-90c2-2cd0efe52557.png)
![02](https://user-images.githubusercontent.com/72552281/95583921-8040d900-0a5a-11eb-9376-3677304827fb.png)

**Comment by maze-runnar** [comment]
```
filterOptions = [
        {
          name : 'order',
          op   : 'has',
          val  : {
            name : 'status',
            op   : 'eq',
            val  : 'completed'
          }
        }
      ];

```

even after applying this the table in completed section showing initialize.
@iamareebjamal this is happening when Ordering more than one tickets at a time, then some of it's tickets go to initialized state, but 

 val  : {
            name : 'status',
            op   : 'ne',
            val  : 'initialized'
          }

from here they don't filter, so value coming is correct , but what's showing is not correct.

**Comment by maze-runnar** [comment]
> ```
> filterOptions = [
>         {
>           name : 'order',
>           op   : 'has',
>           val  : {
>             name : 'status',
>             op   : 'eq',
>             val  : 'completed'
>           }
>         }
>       ];
> ```
> 
> even after applying this the table in completed section showing initialize.
> @iamareebjamal this is happening when Ordering more than one tickets at a time, then some of it's tickets go to initialized state, but
> 
> ```
>  val  : {
>             name : 'status',
>             op   : 'ne',
>             val  : 'initialized'
>           }
> ```
> 
> from here they don't filter, so value coming is correct , but what's showing is not correct.

@iamareebjamal, what is wrong here?

**Comment by maze-runnar** [comment]
![captured (3)](https://user-images.githubusercontent.com/56407566/98458856-ee440180-21ba-11eb-9dfe-9d11efbc5264.gif)

**Comment by maze-runnar** [comment]
on clicking on the order link and then going back shows `initializing`. One solution for this is that open `orders/f5c16a44-8692-441f-9bb4-602cc2a41e18/view` in new tab. @iamareebjamal ?

**Comment by iamareebjamal** [comment]
That's not a solution, that's a workaround. Why is it even happening is the question. Is it problem in our our logic, ember-has-many-query, ember-table, ember-data or ember itself

**Comment by maze-runnar** [comment]
ok, trying to find

**Comment by iamareebjamal** [comment]
One way of finding is logging the model we are returning. Does it contain initializing orders second time? If so, it is not a problem in ember or ember-table but in ember-data or  ember-has-many-query

**Comment by maze-runnar** [comment]
> Does it contain initializing orders second time?
Yes it does in second time -  
 
![Screenshot from 2020-11-08 13-29-54](https://user-images.githubusercontent.com/56407566/98460037-9ad7b080-21c6-11eb-890e-63cd2a32a6a9.png)

**Comment by iamareebjamal** [comment]
It's most likely an error in ember-has-many-query. We need to find out an alternative because it does not work on Ember Data 3.16+ as well

**Comment by maze-runnar** [comment]
it is also giving a warning, what it means- 
`You requested a record of type 'order' with id '14645' but the adapter returned a payload with primary data having an id of 'b1459a24-f5eb-43c6-8151-9acb6d928cae'. Use 'store.findRecord()' when the requested id is the same as the one returned by the adapter. In other cases use 'store.queryRecord()' instead.`

**Comment by iamareebjamal** [comment]
Yes, but that warning is of order detail page, not list page

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
> It's most likely an error in ember-has-many-query. We need to find out an alternative because it does not work on Ember Data 3.16+ as well

So what needs to be done for now with this issue? Would it be solve with alternate of ember-has-many-query or opening in new tab for now?

**Comment by iamareebjamal** [comment]
> We need to find out an alternative because it does not work on Ember Data 3.16+ as well

**Comment by iamareebjamal** [comment]
@maze-runnar Please read https://emberigniter.com/adding-query-parameters-hasmany-relationship/

**Comment by mariobehling** [comment]
The remaining part of this issue is related to ember JS. Therefore I am closing it.
