### ISSUE TITLE
Failing to add a url to a sponsor

### ISSUE THREAD

**Issue by datapythonista** [fossasia/open-event-frontend#5179]
I'm adding a url to a sponsor in https://eventyay.com/events/<event-id>/edit/sponsors and the error "Not a valid url" is returned, and saving fails. I tried with different urls, including https://eventyay.com

Thanks!

**Comment by iamareebjamal** [comment]
![Test-Event-Events-eventyay-Googl](https://user-images.githubusercontent.com/3874064/94582715-31e14c80-029a-11eb-8cce-2bd229095192.gif)

Hi, I tried adding the URL successfully. Do you type the URLs or copy-paste? I tried both with and without `https://` 

Can you add some screenshots or a video?

**Comment by iamareebjamal** [comment]
As the https:// part is already a prefix, please ensure you are not typing `https://` in the field itself. When you paste the URL in the field, it is taken care of automatically

**Comment by datapythonista** [comment]
![Screenshot at 2020-09-29 17-02-43](https://user-images.githubusercontent.com/10058240/94583935-eddc5080-0275-11eb-8f0d-9c2cf904ef2b.png)

Now I'm having a different error. I do have a ticket created, and several orders.

**Comment by iamareebjamal** [comment]
Thank you. Let me check

**Comment by iamareebjamal** [comment]
The above PR has most probably fixed the error, so can you please try https://open-event-frontend-h0ws9ciu8.vercel.app/ and check if you are still getting error while saving sponsors

**Comment by datapythonista** [comment]
When are the PRs you're merging being released? Our event is on Thursday, but I'll give it a try again once released.

**Comment by iamareebjamal** [comment]
They're released about 15 minutes after merging, so this one is already live. The above URL I gave was also linked to production instance with the new changes so that could be used to test changes as well
