### ISSUE TITLE
Wizard Step 1: Event Subtopics "&" showing up as html format

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5180]
The event topics using "&" do not show up properly in wizard step 1.

![Screenshot from 2020-09-29 16-56-15](https://user-images.githubusercontent.com/1583873/94575745-d8b2f200-0274-11eb-8479-ebab18805b42.png)

**Comment by iamareebjamal** [comment]
This is actually what is saved in the database and can be edited in admin section https://open-event-frontend-h0ws9ciu8.vercel.app/admin/content/events

**Comment by mariobehling** [comment]
What do you mean?

The issue is that the drop down menu shows "&amp;" instead of &.

**Comment by iamareebjamal** [comment]
Yes, this is because it is written like that only

https://eventyay.com/admin/content/events

Select `Event SubTopic` "Business & Professional" and you'll find `Startups &amp; Small Business` written there. It can be edited from there

**Comment by iamareebjamal** [comment]
Fixed using the above link
