### ISSUE TITLE
Unable to add an order manually

### ISSUE THREAD

**Issue by datapythonista** [fossasia/open-event-frontend#5184]
**Describe the bug**
I'm trying to add an order manually, but something is wrong with the screen, and I can't select a quantity or click on continue.

**To Reproduce**
1. Go to the management of my event
2. Click on adding an order and go to [this screen](https://eventyay.com/events/c8e221c2/tickets/add-order)
3. Unable to continue

**Screenshots**

![Screenshot at 2020-09-29 15-19-38](https://user-images.githubusercontent.com/10058240/94584587-bf12aa00-0276-11eb-8e73-69f35785e3e9.png)

**Comment by daretobedifferent18** [comment]
I want to work on this issue

**Comment by Raunaksingh100** [comment]
> I want to work on this issue

Go ahead !!

**Comment by daretobedifferent18** [comment]
Could you pls help me how to login in as a admin locally?

**Comment by iamareebjamal** [comment]
Deploy the server locally

**Comment by daretobedifferent18** [comment]
I have deployed it locally. But then if I am logging in 
where will  I get page that is shown in issue description ?

**Comment by iamareebjamal** [comment]
Create an event and go to manage event section.

**Comment by Soumi150** [comment]
@iamareebjamal  do l need to sign up on the open-event website after locally deploying it on my system ?

**Comment by iamareebjamal** [comment]
yes

**Comment by Soumi150** [comment]
How to do email confirmation for open-event? The confirmation link sent in mail displays "not found" when clicked .

**Comment by iamareebjamal** [comment]
Replace URL host to localhost:4200

**Comment by daretobedifferent18** [comment]
![Screenshot from 2020-10-11 15-24-14](https://user-images.githubusercontent.com/71120226/95675569-dc7c3800-0bd5-11eb-9551-672950650215.png)
@iamareebjamal  I found the file.
I think the bug for this issue is in this file where each loop is written.
because if I manually write range 1 -10 its is working correct but not working with this.record.minOrder ...
Could you please help me where this.record is pointing to?

**Comment by iamareebjamal** [comment]
You have to use ticketlist component here. It has proper logic
