### ISSUE TITLE
Create Event: After Step 1 it "Next" jumps to Step 3

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5187]
When an organizer creates an event after the wizard step 1 the wizard jumps to step 3. Expected: After step 1 it should go to "Additional Information" step 2.

![Screenshot from 2020-09-29 18-39-54](https://user-images.githubusercontent.com/1583873/94587767-5978ea80-0283-11eb-97bb-b3f233036b08.png)

**Comment by maze-runnar** [comment]
it's working OK for me

**Comment by iamareebjamal** [comment]
Check while creating event, it jumps

**Comment by Himanshunitrr** [comment]
Yes, and sometimes it lands on the same page.

**Comment by mariobehling** [comment]
Trying with another account it redirects me to the frontpage. Needs to solved urgently.

**Comment by Himanshunitrr** [comment]
Will like to work on it.

**Comment by Himanshunitrr** [comment]
I am getting familiar with the source code. It will be very helpful if you can tell me the relevant files to save time.
