### ISSUE TITLE
Wizard Step 1: Adding date/time and then changing the timezone will change the date/time after saving event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5188]
If the user is in a certain timezone and then enters date/time information in wizard step 1, the date/time does not get stored as entered. After the event is saved the date/time changes if the user is in a different timezone than the event they store.

![Screenshot from 2020-09-29 18-46-01](https://user-images.githubusercontent.com/1583873/94588479-3c90e700-0284-11eb-9aed-6a9deced21c6.png)

**Comment by maze-runnar** [comment]
Actually it's taking time as current timezone and showing as real timezone.
For example - If I entered time 2:30 pm and selected UTC timezone. then it will show time 2:30 - (UTC +5:30) 9:AM

**Comment by maze-runnar** [comment]
Means it's showing timezone of selected time in your timezone's time.

**Comment by iamareebjamal** [comment]
Yes, that is wrong and needs to be fixed

**Comment by maze-runnar** [comment]
time is in Sat Oct 03 2020 01:30:00 GMT+0530 format on adding time of 8:pm in UTC. How to change it?

**Comment by iamareebjamal** [comment]
Using moment

**Comment by maze-runnar** [comment]
spend a lot of time, but still the same. But I have a doubt If we are changing the timezone and time both then it's not updating time. it's showing correctly. But if we previously selected IST, then changed the timezone to UTC. without updating time, then it's the time will update accordingly, but if we change time to then nothing changed.

**Comment by iamareebjamal** [comment]
OK, move on to next issue please. This is complex and needs prior knowledge about timezone. I'll explain in weekend

**Comment by siddhantvirus** [comment]
I want to take up this issue and before I do I want to clarify something : 


1)You want to take the event time in UTC +0  and ask for the user to enter their local timezone.

or 

2)  You want to accept the event time in the time zone the user specifies and then convert it to UTC +0 equivalent.

**Comment by iamareebjamal** [comment]
If someone picked 22 September 9:00 AM while timezone is selected, or after they change the timezone, the time is set correctly. If someone changes the timezone after selecting the time, the time remains in the wrong timezone. The goal is to have the final time 22 September 9:00 AM in the selected timezone. Hopefully, that clears the bug
