### ISSUE TITLE
buttons on event/<event-id>/speakers misaligned on mobile view

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#519]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://user-images.githubusercontent.com/20153241/28425688-b61a1896-6d8e-11e7-8a5b-a3ea53c98802.png)

**Expected behavior:**

these buttons should be aligned properly taking full width on mobile view

**Comment by harshitagupta30** [comment]
@anu-007 I am working on this :)

**Comment by anu-007** [comment]
@harshitagupta30 sure, go ahead.
