### ISSUE TITLE
Tickets: Prevent deletion of tickets with sales

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5195]
Formerly it was not possible to delete tickets that had sales already. Currently there is nothing preventing organizers from deleting those tickets types in the wizard step 1 though.

The feature should again work like that:
* tickets that had sales should get an error message "Tickets that had sales cannot be deleted."
* it should not be possible to reduce the number of tickets below the number of tickets that were sold. So, e.g. if 3 tickets were sold, the organizer should only be able to set the tickets to min. 3 (which means no more tickets would be available and the ticket would no longer show up on the public event page)

Compare: https://eventyay.com/events/a315169f/tickets

![Screenshot from 2020-09-30 00-17-29](https://user-images.githubusercontent.com/1583873/94622377-606b2180-02b2-11eb-96da-753af1b37412.png)

**Comment by BLasan** [comment]
@mariobehling Can I work on this?

**Comment by Raunaksingh100** [comment]
@BLasan go ahead!!

**Comment by aman-jaglan** [comment]
I'm working on this

**Comment by Raunaksingh100** [comment]
> I'm working on this

No it lead to duplicate work

**Comment by snitin315** [comment]
Its been 4 days he can work on it.

**Comment by aman-jaglan** [comment]
speak only when you confirm about things @Raunaksingh100

**Comment by Raunaksingh100** [comment]
> speak only when you confirm about things @Raunaksingh100 

Y first Improve your coummication skills 
Thanks

**Comment by aman-jaglan** [comment]
i'll show you my communication skills and background also if you drop your number @Raunaksingh100

**Comment by iamareebjamal** [comment]
Keep the conversation on topic

**Comment by Draco9421** [comment]
How can I publish an event it always ask me to confirm my email, but as I clicked on the email it sent it says NOT FOUND ?

**Comment by iamareebjamal** [comment]
Paste the confirmation link here

**Comment by maze-runnar** [comment]
@iamareebjamal I am using the condition `(ticket.attendees.toArray()).length > 0` for checking if it has sales, but in first attempt `(ticket.attendees.toArray()).length;` it always return 0, then return currect value.

**Comment by iamareebjamal** [comment]
This needs to be fixed on server, not frontend

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
I am working  on it on server-side, And I am not getting this -

```
if data.get('tickets', None):  is always returning None in  open-event-server/app/api/events.py
  ```

is there anything that need to be change in model?

**Comment by iamareebjamal** [comment]
Why will you get tickets in data? Override `before_delete_object` and check if ticket has any completed/placed orders

**Comment by maze-runnar** [comment]
Added this in /open-event-server/app/api/tickets.py but not working - 
```
class TicketDetail(ResourceDetail):
    """
    Ticket Resource
    """
    def before_delete_object(self, ticket, view_kwargs):
        """
        method to check for proper permissions for deleting
        :param order:
        :param view_kwargs:
        :return:
        """
        
        if not has_access('is_coorganizer', event_id=ticket.event_id):
            raise ForbiddenError({'source': ''}, 'Access Forbidden')
        elif (ticket.get('has_order_tickets')):
            raise ConflictError(
                {'source': ''}, 'You cannot delete a ticket that has sales.'
```

**Comment by iamareebjamal** [comment]
Where is the get function? This is not ember JS, it is python

**Comment by maze-runnar** [comment]
```
def before_delete_object(self, ticket, view_kwargs):
        if not has_access('is_coorganizer', event_id=ticket.event_id):
            raise ForbiddenError({'source': ''}, 'Access Forbidden')
        elif (ticket.has_order_tickets):
            raise ConflictError(
                {'source': ''}, 'You cannot delete a ticket that has sales.'
            )
```
this is not working too. even if I am using ` if True:  raise ForbiddenError({'source': ''}, 'Access Forbidden')`, it made no effect.

**Comment by iamareebjamal** [comment]
It may be so that before_delete_object is not being called because ticket is soft deleted. Try before_update_object

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
how it will keep track of deleted ticket, added this ```
if (ticket.has_order_tickets):
                raise UnprocessableEntityError(
                    {'event_id': ticket.event.id},
                    "Don't delete a ticket that has sales",
```
             

to  before_update_object . But it checks if existing ticket has sales or not. How to check for deleted tickets?

**Comment by iamareebjamal** [comment]
I don't understand. I'll call you soon to understand

**Comment by Draco9421** [comment]
I can't find a way to pass this.totalOrder value from event.view.ticket->index.hbs to publish-bar.hbs can you help me on that ?
