### ISSUE TITLE
Organizer Session Section: Changing Speaker of Sessions results in "Unexpected Error"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5198]
When are user tries to change the speaker of a session to another speaker they get 'unexpected error occured' 
https://eventyay.com/events/0917096d/sessions/6364/edit

**Comment by maze-runnar** [comment]
actually, it supports only one operation at a time. Means can't select two speakers at once, can't do deletion and selection of other speakers at the same time. 
You have to delete speaker and save it, then again click on edit and add a speaker. 
@iamareebjamal what can be done here?

**Comment by iamareebjamal** [comment]
It should handle this by batching operations

**Comment by maze-runnar** [comment]
how to use batch operation here - 
```
this.model.speaker.deleteRecord();
      this.model.session.save()
        .then(() => {
          this.notify.success(this.l10n.t('Your session has been saved'),
```

**Comment by iamareebjamal** [comment]
We need to saved deleted and added speakers in a list and then when `save` is pressed, we add or delete the records. Check deletedTickets implementation in event wizard

**Comment by maze-runnar** [comment]
@iamareebjamal it's working on my development server.

**Comment by maze-runnar** [comment]
Added two spekers and it's working -
![Screenshot from 2020-10-13 15-03-50](https://user-images.githubusercontent.com/56407566/95843468-5db60500-0d65-11eb-9f8c-1ae598ee66da.png)

**Comment by iamareebjamal** [comment]
OK, then it's purely a server issue

**Comment by iamareebjamal** [comment]
@maze-runnar Please check if you are getting an error on applying the migration in https://github.com/fossasia/open-event-server/pull/7353

**Comment by maze-runnar** [comment]
bo I am not getting any error on applying migration.
