### ISSUE TITLE
Continuous Test of Website Availability and Speed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5201]
Please propose and implement a way to continuously test the availability and speed of the website and to send out automated emails based on pre-set parameters.

**Comment by ricknjacky** [comment]
Hi @mariobehling there are various ways out there to do the tasks mentioned above; Can you elaborate a bit more on this? Where is the enhancement expected and how you want it to be implemented. New to the organisation, so if you could help me a bit.
