### ISSUE TITLE
While creating an event the number of tickets can be set to a negative number.

### ISSUE THREAD

**Issue by Himanshunitrr** [fossasia/open-event-frontend#5207]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
Create an event and while typing the numbers of ticket (only by typing) set it to say -1.

**Expected behaviour**

It should be greater thatn 0

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Himanshunitrr** [comment]
I will also like to work on this issue.

**Comment by mariobehling** [comment]
It is a good issue to start working on the system, but for maintainers it is low priority as negative values will result in an error message when you try to save it. So, it does not impact the functioning of the system. However, would be great if you resolve this issue. Thank you!

**Comment by mariobehling** [comment]
Closing it as it results in an error message anyways.
