### ISSUE TITLE
While creating an event and choosing sessions and speakers one can set Microlocations or Virtual Online Rooms to negative numbers

### ISSUE THREAD

**Issue by Himanshunitrr** [fossasia/open-event-frontend#5208]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
While creating an event when you will  be choosing Microlocations or Virtual Online Rooms. It can be set to negative number.

**Expected behaviour**

It should be greater than 0.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Himanshunitrr** [comment]
I will like to work on this issue

**Comment by mariobehling** [comment]
It is possible that a room is in the basement or even below. Therefore negative numbers are possible and can indicate a floor name. Hence closing this issue.
