### ISSUE TITLE
Sponsors level can also be a negative number. 

### ISSUE THREAD

**Issue by Himanshunitrr** [fossasia/open-event-frontend#5209]
**Describe the bug**

While creating an event one can make the level of sponsors to be a negative number
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Himanshunitrr** [comment]
I think that no where is the magnitude of number is being checked. I will like to work on this issue.

**Comment by mariobehling** [comment]
Thanks. This could be slightly confusing to the user, but it does not impact the usage of the system. Therefore I added priority low as the maintainers focus mainly on high priority issues. Maybe also check out those high priority issues. Thank you.
