### ISSUE TITLE
Invoice: Adjust invoice handling UI and Invoice Numbering

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5211]
Please make changes to the invoice as follows:

* Make invoice ID from 202010OU-1 to -> 202010OU-000001
* Instead of the download icon make the invoice ID into a link and open the linked PDF in a new window
* Take out the logo of the event from the event name column in table (accounting should be plain)
* Change Date to -> "Invoice Date"
* Add column "Due Date"
* It seems status "Due" and "Upcoming" are the same. Otherwise I am not clear what "Upcoming" means.
* Switch the tabs "Payment Info" and "Invoices", so the invoices show up on top and as the first thing when accessing the billing tab

_Question_: After payment on Paypal are users redirected back to the invoice overview page? Does the "Review and Pay" button disappear and status changes to "Paid"? How to test this?

**Comment by iamareebjamal** [comment]
@mariobehling Currently it is `202010U-1` (`YYYYMMU-#ID`), not (`YYYYMMOU-#ID`) according to https://github.com/fossasia/open-event-frontend/issues/5120#issuecomment-697295034

So should it be `202010OU-000001` or `202010U-000001`

**Comment by mariobehling** [comment]
Both are fine.
