### ISSUE TITLE
Invoice: When user is not logged in to see invoice error page shows up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5212]
When a user accesses the link to pay their invoice and the user is not logged in an error page shows up, that looks like the system has a problem stating "The page you were trying to access has caused an error.".

Expected: A message like "Please login to access this page." should appear instead with a link to the login page. After the login the user should be directed to the invoice page they tried to access.

![Screenshot from 2020-10-01 02-47-20](https://user-images.githubusercontent.com/1583873/94755993-9386e100-0396-11eb-800b-dd44f9fa2dec.png)

**Comment by himanshujaidka** [comment]
I am workin on that

**Comment by Raunaksingh100** [comment]
@himanshujaidka go ahead!!

**Comment by himanshujaidka** [comment]
@Raunaksingh100 pls tell me where is the file ?

**Comment by vj-codes** [comment]
I would like to work on this

**Comment by vj-codes** [comment]
@mariobehling hey I found the file to be edited for this issue ,  after the message is edited I have to replace the home button by login button and then how do I direct the user to invoice page again? Any hints 👀 
Also is this a codeheat issue?

**Comment by iamareebjamal** [comment]
See create.js route

**Comment by iamareebjamal** [comment]
@vj-codes Status? Please take one issue at a time. If you want to take up another issue, please comment on the older issue that it is free to be taken up by others. As it is high priority, we want to reduce contention over these issues so they are solved ASAP. Hence, if no codeheat participant has taken them up, we solve them ourselves. Thus, it should be very clear if a high priority issue is taken up and is the only issue being worked on by the participant. And if it is indeed being worked upon, and not just claimed

**Comment by himanshujaidka** [comment]
@iamareebjamal I am working on that and hope so today I’ll make pr

**Comment by iamareebjamal** [comment]
@vj-codes had commented first so let her tell if she has already worked on it or not

**Comment by himanshujaidka** [comment]
> I am workin on that
Okay sir

**Comment by vj-codes** [comment]
@iamareebjamal it's available from others then, sorry wasn't aware about the rules :)
