### ISSUE TITLE
Invoice Review Page: Change button from Print to "Download"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5213]
The button on the review invoice page says "Print Invoice". The action of the button is to download the invoice though. It does not open the printer dialogue. Therefore please change it to "Download Invoice" and change the icon to show a download icon instead.

![Screenshot from 2020-10-01 03-33-27](https://user-images.githubusercontent.com/1583873/94756206-1c058180-0397-11eb-83ba-ef3e56a502cb.png)

**Comment by aman-jaglan** [comment]
I m working on it

**Comment by naman360** [comment]
Can I work on it?

**Comment by Raunaksingh100** [comment]
> Can I work on it?

no it lead to duplicate work

**Comment by snitin315** [comment]
>no it lead to duplicate work because i already fixed and create a pr for this plz find some other issue

@aman-jaglan commented first and it's been only few hours so you should ask him before working on it and creating a PR.

**Comment by Raunaksingh100** [comment]
> >no it lead to duplicate work because i already fixed and create a pr for this plz find some other issue
> 
> @aman-jaglan commented first and it's been only few hours so you should ask him before working on it and creating a PR.

@snitin315 I commented first but I accidentally deleted my comment then @aman-jaglan add the comment
