### ISSUE TITLE
Update all messages for hindi language

### ISSUE THREAD

**Issue by vj-codes** [fossasia/open-event-frontend#5217]
**Is your feature request related to a problem? Please describe.**
Currently in [this file](https://github.com/fossasia/open-event-server/blob/development/app/translations/hi/LC_MESSAGES/messages.po) only some messages are translated from english to hindi .
Example messages after line [239 onwards](https://github.com/fossasia/open-event-server/blob/development/app/translations/hi/LC_MESSAGES/messages.po#L239)

**Describe the solution you'd like**
Update all translations and remove errors if required

Note: I would like to work on this , if it's approved

**Comment by vj-codes** [comment]
@iamareebjamal hey so should I update the translations in this repo ?

**Comment by Siddhant-K-code** [comment]
@mariobehling can i work on this ?

**Comment by mariobehling** [comment]
Thanks for this. For more translations we recommend to contribute through weblate. https://hosted.weblate.org/projects/open-event/ Please help us to make this more international. Thank you!
