### ISSUE TITLE
The Save as draft button overlapping in mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/open-event-frontend#5218]
**Describe the bug**
The save button is overlapping on the mobile view see in the screenshot for the better understanding

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/create'
2. Click on 'inspect elment'
3. Scroll down to 'see save as draft button'

**Screenshots**
![1](https://user-images.githubusercontent.com/65535360/94795319-d24e8280-03fa-11eb-9b67-79fe5f5f3bd4.PNG)

**Smartphone (please complete the following information):**

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by mariobehling** [comment]
Thanks for testing this and any improvement is welcome. For codeheat we focus on issues opened by maintainers. A list is here https://github.com/fossasia/open-event-frontend/issues?q=is%3Aissue+is%3Aopen+label%3Acodeheat Thank you!

**Comment by swapnalshahil** [comment]
I guess this issue is solved ..?

**Comment by maze-runnar** [comment]
fixed so closing
![Screenshot from 2021-01-14 14-21-31](https://user-images.githubusercontent.com/56407566/104566645-dc2b8700-5673-11eb-9419-9cfb1ccb9210.png)
