### ISSUE TITLE
Invoice: Complete data on PDF invoice 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5224]
Please complete the data set fields on the PDF invoice as follows:

Organizer
- [x] add field contact name e.g. Ms. Kathy Adriano
- [x] add tax ID for organizer

Supplier
- [x] Add contact name

Both Supplier and Organizer area:
- [x] Add line breaks for address e.g.:
 12 Eu Tong Sen Street #08-169
 Singapore 059819
 Singapore

**Comment by iamareebjamal** [comment]
Tax ID is already there (Tax Info field)

**Comment by iamareebjamal** [comment]
Contact name for organizer is there if they have saved it in their profile.
For admin, contact name should be displayed above company name or below?

**Comment by mariobehling** [comment]
> For admin, contact name should be displayed above company name or below?

Below company name.

**Comment by mariobehling** [comment]
> Tax ID is already there (Tax Info field)

Tax ID of the organizer (not the supplier. The supplier ones I saw already)

**Comment by iamareebjamal** [comment]
That is added to PDF if the organizer has filled in the tax info, else omitted

**Comment by iamareebjamal** [comment]
Please check the PDF now
