### ISSUE TITLE
error when the number of minimum tickets is less than maximum. No error when maximum is less than minimum.

### ISSUE THREAD

**Issue by ritvikkhanijo** [fossasia/open-event-frontend#5235]
**Describe the bug**
On creating a new event, when the number of tickets per order is less than maximum tickets, an error is shown, the error being "Minimum order should not be greater than maximum". Also, when we increase the number of minimum tickets, we can somehow end up having more minimum tickets than maximum tickets with no error.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Go to https://eventyay.com/create.
2. Click on free ticket in the ticketing system.
3. increase minimum ticket by 1 (ie : 2) and reduce maximum ticket by 1 (ie: 9).
4. See error(1)
5. Now keep increasing the minimum ticket number till it becomes more than the maximum ticket number.
6. there will be no error(2).

**Expected behaviour**
1. In the first case there should be no error since the minimum ticket number is less than the maximum ticket number.
2. In the second case the error should be prompted since the minimum ticket number is greater than maximum ticket number. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by mariobehling** [comment]
When the user clicks outside of the form area the behavior seems to go back to what is expected. However, the behavior should just work as expected when the numbers are changed.

![Screenshot from 2020-10-04 19-55-33](https://user-images.githubusercontent.com/1583873/95023137-970eb680-067b-11eb-8248-5e066d0b5a53.png)

**Comment by Soumi150** [comment]
I want to work on this issue.

**Comment by Soumi150** [comment]
This issue seems to be fixed. @mariobehling and @iamareebjamal ,Please review this.
