### ISSUE TITLE
Frontpage: Event Filter not working reliably

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5239]
Only events that fulfill certain criteria are shown on the front page. However, this filter does not seem to work reliably. As sometimes all kinds of events are showing up on the front page. After a refresh the filter is applied though.

It is difficult to replicated this issue as it appears without any obvious reason. A guess is that the connection is slow? Not sure.

![Screenshot from 2020-10-04 20-50-31](https://user-images.githubusercontent.com/1583873/95024471-72b6d800-0683-11eb-829d-0801eae2726e.png)

**Comment by iamareebjamal** [comment]
Fastboot is disabled now so it should be reliable now. Please reopen if experienced again
