### ISSUE TITLE
Search field on frontpage confusing due to Wrong text

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#5240]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'eventyay home page"
![Screenshot (91)_LI](https://user-images.githubusercontent.com/58654018/95050633-886ee080-0709-11eb-92ea-df0076f3f566.jpg)

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Soumi150** [comment]
I would like to work on this issue.

**Comment by mariobehling** [comment]
This issue will be part of a larger change of the search area. We will probably get rid of the entire field and simplify the search. Therefore tackling this issue separately from other search related issues is probably difficult and out of context.

**Comment by mariobehling** [comment]
I tried to make the issue title more clear. It is not perfect, but let's try to make the issue as clear as possible in the title already. Thank you.

**Comment by himanshujaidka** [comment]
okay @mariobehling
