### ISSUE TITLE
Implement Image Size API to admin/settings/images

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#525]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Create image size model
- Implement image size api to admin/settings/images route

**Comment by CosmicCoder96** [comment]
on hold until PR #523 is merged to create setting model.
