### ISSUE TITLE
Admin Sales Page: Provide buttons, filters and date selection

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5256]
The admin sales page (https://eventyay.com/admin/sales) now shows events and their sales data. However, it is difficult to identify relevant events. Admins need to click through different pages to see which events are selling tickets. Also all events are listed by default - live, draft, past events, which possibly creates a load on the server.

Please enhance the usability therefore as follows:
1. Show buttons:
Events with
* Paid tickets (default view)
* Sold Tickets
* Free Tickets
* All Ticket Types

2. Dropdown filter:
Events with 
* [ ] Live Events (pre-selected default view)
* [ ] Draft Events
* [ ] Past Events

3. Add a filter to choose a date period to show events from/to date

4. Enable sorting for each category (completed, placed, pending orders) according to:
* number of tickets sold
* sales number

5. Add column "Organizer" behind "event date" (maybe reduce width of "Ticket" columns for each category to fit in the "Organizer" column). Show owners and organizers in the organizer column.

![Screenshot from 2020-10-06 15-55-56](https://user-images.githubusercontent.com/1583873/95211265-a4977e00-07ec-11eb-9983-0fb4f3fc2f94.png)

**Comment by DhairyaBahl** [comment]
I would like to work on this issue. Kindly assign this issue to me .

Thanks :)

**Comment by iamareebjamal** [comment]
It is possible to filter across Live, Past, Draft Events and to filter across starts-at, but not possible to sort through tickets sold or sales because they are not properties of event but a summarized computation of related data - sum(event->orders.amount) and sum(event->ticket_holders) and even more difficult because they are filtered across order status as well

**Comment by maze-runnar** [comment]
working on this.

**Comment by maze-runnar** [comment]
there is no `event : belongsTo('event')` in `admin-sales-by-event`. How to get all that info from event?

**Comment by iamareebjamal** [comment]
Most filtering like that will happen on server so need to add that functionality to server first
