### ISSUE TITLE
Unable to proceed PAYPAL payment 

### ISSUE THREAD

**Issue by bellaphan** [fossasia/open-event-frontend#5258]
When I try to make a payment using Paypal and want to proceed to checkout, then this occur 

<img width="1417" alt="Screen Shot 2020-10-07 at 12 07 38 am" src="https://user-images.githubusercontent.com/50802607/95236841-a8012880-0831-11eb-9723-bba297bdeed4.png">

<img width="1417" alt="Screen Shot 2020-10-07 at 12 07 10 am" src="https://user-images.githubusercontent.com/50802607/95236829-a5063800-0831-11eb-8535-034c3402fb97.png">

**Comment by maze-runnar** [comment]
@bellaphan, it's working fine-
![Screenshot from 2020-10-07 12-21-29](https://user-images.githubusercontent.com/56407566/95297252-bd10a280-0897-11eb-863d-c33cbca24b6c.png)

**Comment by iamareebjamal** [comment]
@bellaphan Can you please paste the URL of the order?

**Comment by maze-runnar** [comment]
@bellaphan has not cleared this issue yet or order url, And I am not able to reproduce.
