### ISSUE TITLE
Implement Pages API to admin/content/pages

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#526]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Create pages model
- Implement Pages API to admin/content/pages

**Comment by anu-007** [comment]
@geekyd I would like to work on this.

**Comment by anu-007** [comment]
currently there is no data present so I tried to create some dummy data for this but since it requires admin permission i get an error of
 ```     
            "status": 403,
            "title": "Access Forbidden",
            "detail": "Admin access is required" 
```
how do i proceed with this.thanks !!

**Comment by harshitagupta30** [comment]
I will be working on this.

**Comment by harshitagupta30** [comment]
@niranjan94 I am facing the same issue regarding the admin access as mentioned by anu how should I proceed?

**Comment by niranjan94** [comment]
Deploy your own version of the server either locally or remotely and use that. You'll have full permissions there. (easy one click deploy to heroku available)

**Comment by harshitagupta30** [comment]
This issue is on hold till https://github.com/fossasia/open-event-orga-server/issues/4251 Also there is a confusion about whether to add menu or not in the API which has not been confirmed by Niranjan. All the work has been done expect the menu thing. Will send the PR as soon as the above thing sort out.

**Comment by geekyd** [comment]
@harshitagupta30 Please check https://github.com/fossasia/open-event-orga-server/issues/4303 & https://github.com/fossasia/open-event-orga-server/issues/4251 Please proceed with this issue. Thanks
