### ISSUE TITLE
Organizer Invitations directs to "Register" instead of "Login" for Existing Accounts and then directs to Start Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5260]
When an event owner invites another organizer and the organizer is not logged in the following happens: The organizer clicks the link and is directed to a sign up page. There is an option "Login instead". It this option is chosen and the user logs in, the user is directed to the start page.

Expected: The invited user (organizer) should be directed to the login page, if the account of the user with the invited email already exists. If the account does not exist the user should be directed to the registration page.

After logging in or registering the user should be directed to the event dashboard that he/she was invited to.

Note: If the user has to register, it should not be necessary to confirm the email after registration, cause the user has already received an email and clicked a link. So, we can immediately add the user to the group of "verified users" in this case.

![Screenshot from 2020-10-07 12-48-09](https://user-images.githubusercontent.com/1583873/95322236-796c6780-089c-11eb-9cbe-3245b7120189.png)

**Comment by HeroicHitesh** [comment]
@mariobehling I am working on it, assign it to me.

**Comment by snitin315** [comment]
@HeroicHitesh feel free to send a PR.

**Comment by HeroicHitesh** [comment]
@mariobehling @snitin315 Which property is used to check if the invited user is already a user of the platform or not? I am able to change the route but unable to figure out which property contains this value. Can you tell me that property name or is there API documentation for the platform which I can refer, so that I can use that property name as a condition to switch routes between login and register?

**Comment by iamareebjamal** [comment]
There is no such property because the user hasn't been logged in the system yet

**Comment by HeroicHitesh** [comment]
So on what basis will we direct the user to the login or register page while he clicks on the invite link?

**Comment by iamareebjamal** [comment]
That is the part of the problem. How will you detect that?

**Comment by HeroicHitesh** [comment]
I was going through the API docs and thought [this endpoint](https://api.eventyay.com/#users-get-user-details-for-an-access-code) can be useful. If I am going right, we can pass the payload i.e., token taken from URL of invite link as access_code to this endpoint and in the response, I was hoping to get such property. But if there is no such property, I think we can directly compare the email_id in response to null. If the response sends null in email_id, it will mean that the user should see the register screen else login screen.
Am I going right? or is there any issue in this approach?

**Comment by HeroicHitesh** [comment]
I had 2 major doubts about this approach
1. Is the access_code same as this token we receive in the invite URL or something entirely different?
2. Is it compulsory to provide a role like `marketer` as shown in the API doc example, if yes, what role will we pass for users with no other roles?

**Comment by iamareebjamal** [comment]
No, access code is a different thing

**Comment by aman-jaglan** [comment]
can i work on this issue ?

**Comment by HeroicHitesh** [comment]
@aman-jaglan I am working on this. Also, what you changed in your PR is not correct. We need to switch between Login and Register based on a condition i.e., if the user is already registered or not.

**Comment by aman-jaglan** [comment]
okk brother @HeroicHitesh

**Comment by Adityachaturvedi2906** [comment]
Hey! this issue seems interesting, Can I work on this? Please guide me further on the same
