### ISSUE TITLE
Event Roles: Only one invite at a time possible 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5261]
In the event team tab it is possible to invite other oganizers. However it is only possible to invite one other user at a time. Another invite only works after refreshing the page.

![Screenshot from 2020-10-07 13-00-19](https://user-images.githubusercontent.com/1583873/95322791-57bfb000-089d-11eb-83e4-ae56bcfd2cf3.png)

**Comment by siddhantvirus** [comment]
@mariobehling can the backend accept more than one invite at a time in the same request ? 
Because making relevant changes in the frontend won't be of any use without that

**Comment by iamareebjamal** [comment]
It's not about invites being in the same request

**Comment by maze-runnar** [comment]
looking into it.

**Comment by maze-runnar** [comment]
can we just reload the page on every invite send, it would solve the issue?

**Comment by iamareebjamal** [comment]
Why, why can't we send multiple invites on same page. That's a workaround, not a fix

**Comment by iamareebjamal** [comment]
No, this shouldn't be the case here. After being sent, the model must be set to the initial state

**Comment by maze-runnar** [comment]
In second attempt showing this error - 

`{"errors": [{"status": 422, "source": {"pointer": "/data/relationships/role"}, "title": "Unprocessable Entity", "detail": "A valid relationship with role resource is required"}], "jsonapi": {"version": "1.0"}}`

**Comment by maze-runnar** [comment]
We can edit as many invites in one go, but even not possible to send a new invite after editing any invite.

**Comment by iamareebjamal** [comment]
That is not a technical limitation. But a result of poor coding. Let's schedule a work session tomorrow or on Wednesday and solve the speaker and this issue

**Comment by maze-runnar** [comment]
ok, tomorrow at 10 a.m.?

**Comment by iamareebjamal** [comment]
OK
