### ISSUE TITLE
Wizard Step 1: Should not be possible to save when Stripe is ticked without Stripe connected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5262]
The Stripe payment in wizard step 1 can be activated and the event can then be saved. This should not be possible as the user has not connected to the Stripe gateway. It should only be possible to save the event with Stripe ticked on if the user has connected to their Stripe account.

Expected: 
* [ ] Show an error message "You need to connect to your Stripe account, if you choose Stripe as a payment gateway."
* [ ] While solving this, please also get rid of the empty line between "Yes accept..." and "Stripe accepts Visa..."

![Screenshot from 2020-10-07 13-07-58](https://user-images.githubusercontent.com/1583873/95323947-44154900-089f-11eb-9bcf-ced01e78cf79.png)

**Comment by Hackerbone** [comment]
How do I replicate this bug in the website
