### ISSUE TITLE
Wizard Step 1: After Stripe connection Error Message "Authorization Code Required"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5263]
When adding Stripe and connecting it to an event as an organizer (not owner) there is an error message "Authorization Code Required", when the user tries to save the event.

Reloading the page resolves the error and the user can now save the event (even though actually the Stripe connection is saved already).

It is difficult to replicate the error and it is unclear what leads to the error specifically.

![Screenshot from 2020-10-07 13-07-58](https://user-images.githubusercontent.com/1583873/95325150-103b2300-08a1-11eb-8b84-86f4f8dc7d3f.png)

**Comment by maze-runnar** [comment]
@iamareebjamal is it a server issue?

**Comment by iamareebjamal** [comment]
Not likely. It would always throw if it was server error

**Comment by maze-runnar** [comment]
`Authorization Code Required` this error message is not present in frontend. 
![scrnli_10_27_2020_9-16-03 PM](https://user-images.githubusercontent.com/56407566/97326102-a90a0080-1899-11eb-9779-f44e4710c6c2.png)

**Comment by maze-runnar** [comment]
```
this.set('data.event.stripeAuthorization', this.store.createRecord('stripe-authorization', {
            stripeAuthCode       : authorization.authorizationCode,
            stripePublishableKey : ENV.environment === 'development' || ENV.environment === 'test' ? this.settings.stripeTestPublishableKey : this.settings.stripePublishableKey
          }));

```

the error is because when we first time set the authCode, it is not there.But after refreshing page it is there. So then it works

**Comment by iamareebjamal** [comment]
But why? It only happens sometimes

**Comment by maze-runnar** [comment]
I didn't get it yet though.

**Comment by maze-runnar** [comment]
![captured (1)](https://user-images.githubusercontent.com/56407566/99048191-3ef09b80-25bb-11eb-935b-a5804234bf52.gif)

**Comment by maze-runnar** [comment]
@iamareebjamal it is connected successfully in testing mode.  here is the working https://youtu.be/9p5QeGejs98, and it's working fine.

**Comment by iamareebjamal** [comment]
Yes, it does not happen always

**Comment by maze-runnar** [comment]
@iamareebjamal when trying to connect stripe as an `organizer`, it giving `{"errors": [{"status": 404, "source": {"parameter": "event_id"}, "title": "Object not found", "detail": "StripeAuthorization: 3 not found"}], "jsonapi": {"version": "1.0"}}` .

**Comment by maze-runnar** [comment]
Now another case, if the event is not published, there is no error in connection of stripe by organizer too.

**Comment by maze-runnar** [comment]
IF an owner has published an event, and then an organizer tries to edit stripe then it is giving an error. But if again organizer unpublish the event and then edit the stripe connection it is working correctly and then he can publish the event. And after the organizer has published the event he can edit the stripe connection in the published state too without any error.

**Comment by maze-runnar** [comment]
@iamareebjamal is all the above consequence related to server and permissions?

**Comment by iamareebjamal** [comment]
No, both server and frontend

**Comment by maze-runnar** [comment]
After editing event one time events, moved from organizer to owner section.
![scrnli_11_17_2020_11-46-05 AM](https://user-images.githubusercontent.com/56407566/99353441-81232100-28ca-11eb-833d-d725b5ef5741.png)
![scrnli_11_17_2020_11-44-31 AM](https://user-images.githubusercontent.com/56407566/99353443-83857b00-28ca-11eb-84df-795d522be6d7.png)

**Comment by maze-runnar** [comment]
@MeghalBisht please test this if it's still happening.

**Comment by mariobehling** [comment]
Not happening at the moment. Therefore closing it.
