### ISSUE TITLE
Wizard Step 5: Preselect "Public Option" for Call for Speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5272]
For the buttons for call for speaker there are only two options - public or private. The option "public" should be pre-selected.

![Screenshot from 2020-10-08 20-44-35](https://user-images.githubusercontent.com/1583873/95500548-3ba83580-09a7-11eb-8c1b-69d4e5970d34.png)

**Comment by Nanak360** [comment]
@mariobehling I would love to work on it. Would you please kindly assign me?

**Comment by Nanak360** [comment]
I guess I fixed the bug but I would like to see it myself before making a pull request.
Can someone please tell me how do I reproduce this bug? I cannot even log in or create a new account in my Local build.

**Comment by iamareebjamal** [comment]
What's the error you're getting?

**Comment by Nanak360** [comment]
I have made the necessary changes but I'm unable to see those changes. 
What I want is to recreate the scenario so that I can see if the changes are alright or not.
Would you let me know how can I do so?

**Comment by iamareebjamal** [comment]
How are you unable to see those changes?

**Comment by maze-runnar** [comment]
working fine. I am not able to reproduce, tried much time.
![captured (2)](https://user-images.githubusercontent.com/56407566/95648010-b54c3a80-0af1-11eb-8040-e93eb7ea51b2.gif)

**Comment by iamareebjamal** [comment]
You must be talking about #5271, not this issue

**Comment by maze-runnar** [comment]
ok

**Comment by sansyrox** [comment]
@iamareebjamal @maze-runnar , I believe this issue has been resolved? 
<img width="1288" alt="Screenshot 2020-10-26 at 6 03 47 PM" src="https://user-images.githubusercontent.com/29942790/97172822-9a4a1d80-17b5-11eb-803b-884344d73fe7.png">

**Comment by iamareebjamal** [comment]
Thanks @sansyrox
