### ISSUE TITLE
Attendee Page: Pending tickets tab is not showing in attendee page of events

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#5276]
**Describe the bug**

On the _attendees_ page of _events_,  __pending__ tickets  tab is not showing. _Pending_ tab contain list of pending tickets.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to _'www.eventyay.com'_ or _localhost:4200_
2. Login with your account
3. Go to _manage events_.
4. Go to _events dashboard_(if you are not having any event, create an event)
5. Go to _tickets_ tab
6. Go to _attendees_ tab
7. see error

**Expected behaviour**

_Pending_ tab must be shown on _attendees_ page of _events_ dashboard page.

**Desktop**
 - OS: Ubuntu 20.04.01 LTS
 - Browser: Chrome
 - Version: 86.0.4240.75 (Official Build) (64-bit)

**Additional context**

I have shared screenshot shared by @mariobehling on 29 september 2020 on issue #5176 which is showing pending tab but now _pending_ tab is not shown on _attendees_ page of _events dashboard_ page. I  have attached a fresh screenshot of page which is not showing pending tab. 
compare: https://eventyay.com/events/74b5de56/tickets/attendees/completed

**Screenshots**

![02](https://user-images.githubusercontent.com/72552281/95611911-1affde80-0a80-11eb-8d7c-94eb48000941.png)
![03](https://user-images.githubusercontent.com/72552281/95611917-1cc9a200-0a80-11eb-9ed6-72b21c8dd787.png)

**Comment by sachinchauhan2889** [comment]
I am working on this issue

**Comment by iamareebjamal** [comment]
I can see pending tab 
![image](https://user-images.githubusercontent.com/3874064/95641587-ec562800-0ac0-11eb-8e17-3d964db2d716.png)

**Comment by sachinchauhan2889** [comment]
@iamareebjamal sir, why this is not showing in chrome browser of ubuntu 20.04.01 LTS.

**Comment by sachinchauhan2889** [comment]
@iamareebjamal @mariobehling i have checked on ubuntu chrome, ubuntu firefox, windows chrome, edge, android chrome. but i am not able to see pending tab anywhere. @iamareebjamal please use any of above lisited browser at windows or ubuntu and see the error.
![android](https://user-images.githubusercontent.com/72552281/95646139-19b3cd80-0ae3-11eb-9d95-86b47291ce9c.png)
![Edge](https://user-images.githubusercontent.com/72552281/95646141-1c162780-0ae3-11eb-93e0-7d03f3e49450.png)
![ubuntu chrome](https://user-images.githubusercontent.com/72552281/95646142-1d475480-0ae3-11eb-93d0-17cacda7fe25.png)
![ubuntu Mozilla](https://user-images.githubusercontent.com/72552281/95646147-1e788180-0ae3-11eb-851d-f6842f5a804d.png)
![windows chrome](https://user-images.githubusercontent.com/72552281/95646148-1fa9ae80-0ae3-11eb-9ba6-39b9644a6539.png)

**Comment by iamareebjamal** [comment]
This is because it is only shown for admins
