### ISSUE TITLE
Ticket Order: User able to add invalid email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5277]
A user could get a ticket and add an invalid email. Compare at https://eventyay.com/orders/d2b49133-ddc1-4f77-865e-f12cb8e24108/view

Expected:
* User should only be able to add valid emails
* Question: For the first ticket should we limit this and only allow the user to use their confirmed email for free tickets? How do other systems like eventbrite do it?

![Screenshot from 2020-10-09 21-44-14](https://user-images.githubusercontent.com/1583873/95625398-b9884180-0a78-11eb-82b1-a1c31ba30e22.png)

**Comment by iamareebjamal** [comment]
> only allow the user to use their confirmed email for free tickets?

This is the only way to ensure correct email. Because the email entered above by the user is a valid email address, it just doesn't exist

**Comment by iamareebjamal** [comment]
Eventbrite lets you order even free tickets on invalid emails

**Comment by maze-runnar** [comment]
can we use https://sendgrid.com/solutions/email-api/email-address-validation-api/ or https://mailboxlayer.com/ like service to validate an email address? But most of the sites don't validate emails in this way. They just let the user enter invalid email with correct format.

**Comment by hardhikgupta** [comment]
I want to work on this issue.

**Comment by akashprasher** [comment]
We can solve this issue by allowing users to get a ticket only if a user is logged-in. For logging a user requires to validate the email and we can collect that email from user details while getting a ticket. Otherwise checking the format of email can't solve this issue.

**Comment by akashprasher** [comment]
Let the email be the same as the user email(logged). If a user wants to use another email instead of default we can verify it. Just like an OTP system. We can provide an edit icon if the user wants to use another email otherwise, it stays at default.

**Comment by akashprasher** [comment]
**Just Like this**

![image](https://user-images.githubusercontent.com/42891970/97666158-1341c180-1aa3-11eb-9f78-29a8140071e6.png)

**Comment by mariobehling** [comment]
Of course OTP implmentation would be nice, but it is out of scope at the moment as this would mean we have to implement a gateway or take care of it ourselves.

For now, it would be nice if it is verified that the field has a real email. In the example it is not a real email name.something@gmail - is missing the .com for example. So, this is the issue to solve here. Thanks

**Comment by aryamanprince** [comment]
Can i work on it if no one is working?
I think it would be handy to use regular expressions to compare email entered with valid email address and hence we can validate email addresses.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by aryamanprince** [comment]
![Screenshot from 2020-11-16 09-32-13](https://user-images.githubusercontent.com/57310026/99211930-9aa36a80-27ef-11eb-8aa7-ec811cc9ad3d.png)

you want a check at this location?
if you could tell me working directory it will be highly helpful..

**Comment by RahulBansal123** [comment]
can i work on this?

**Comment by aryamanprince** [comment]
i am currently working on it

**Comment by RahulBansal123** [comment]
any updates?

**Comment by daretobedifferent18** [comment]
I am working on it.

**Comment by aryamanprince** [comment]
what is this attitude @daretobedifferent18 when i mentioned i was working how can you take up an issue? really disgusting.
