### ISSUE TITLE
Implement Ticket Fees API to admin/settings/ticket-fees

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#528]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Create ticket fees model
- Implement Ticket Fees API to admin/settings/ticket-fees

**Comment by CosmicCoder96** [comment]
on hold until PR #523 is merged to create setting model. Please choose the other issues to work on  for a short while

**Comment by CosmicCoder96** [comment]
on-hold until issue https://github.com/fossasia/open-event-orga-server/issues/4139 is resolved.
