### ISSUE TITLE
Implement Settings API to /admin/settings/payment-gateway

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#529]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Implement the settings API to /admin/settings/payment-gateway

**Comment by CosmicCoder96** [comment]
on hold until PR #523 is merged to create setting model. Please choose the other issues to work on  for a short while
