### ISSUE TITLE
Video: Autogenerate underlying Jitsi Room and Phone numbers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5299]
There is a way to autogenerate a Jitsi room with "additional information" such as phone numbers. An example of an implementation is available in the calendar chrome plugin at https://github.com/jitsi/jidesha.

Please implement this in a way that such "Additional Information" is added automatically into the field "Additional Information".

![Screenshot from 2020-10-13 10-49-11](https://user-images.githubusercontent.com/1583873/95838201-c9867680-0d41-11eb-95a9-fa3deca779d4.png)

**Comment by iamareebjamal** [comment]
https://jitsi.org/api/

**Comment by utkarsh147-del** [comment]
I want to work on this issue.Please give this work to me and a chance for contribution
