### ISSUE TITLE
Create ticketing component (Functional UI) 

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#53]
<img width="1074" alt="screen shot 2017-05-16 at 6 30 49 pm" src="https://cloud.githubusercontent.com/assets/2404372/26107134/df25d36c-3a65-11e7-9fbe-68bbc82b17c1.png">

- A ticket component shown at `/e/<event_identifier>`. (Visit eventyay.com to see current implementation)
- The tickets should be passed in from `app/controllers/public/index` just like how speakers are. (Dummy data can be used.)
- The sub-total and total should update on change of ticket quantity. (quantity can be a parameter on the dummy ticket object for now)
- Promo code support not required now. 
- The order now button should be clickable only if any ticket's quantity is more than zero.

**Comment by geekyd** [comment]
@niranjan94 I would like to work on this, please assign this to me.
