### ISSUE TITLE
Speaker Notification: HTML code in message and pop up not entirely visible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5308]
The pop up notification box has some issues:
1. There is html code on the bottom of the message
2. The pop up is partly hidden
* behind an area that should be below on top and bottom
* buttons are hidden
* top area is hidden

Compare https://eventyay.com/events/5ac8e4d9/sessions/all
![Screenshot from 2020-10-14 08-22-29](https://user-images.githubusercontent.com/1583873/95951462-c0a3ac80-0df6-11eb-8636-b72539e1dfc1.png)

**Comment by pavnesh2019** [comment]
what are steps to reproduce this issue?

**Comment by iamareebjamal** [comment]
> There is html code on the bottom of the message  

That is not an issue. Links are shown this way only. Link won't be shown if this is removed

For popup being hidden, we can make the size of the message textarea small, which will in turn hide some of the message

**Comment by iamareebjamal** [comment]
One part is still unsolved
