### ISSUE TITLE
Speaker Notification: Show Email address

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5309]
For the speaker notification, please show
* The name and email address of the speaker above the subject in a non-editable way.
* Show it similar to how it is shown in email programs
* If there are several speakers of a session show several speakers
* Ensure several speakers receive the notification if there are 
* Also show a CC box for the organizer to add any other relevant emails

![Screenshot from 2020-10-14 08-27-25](https://user-images.githubusercontent.com/1583873/95951651-1d06cc00-0df7-11eb-91f3-1b01f10c9ddc.png)

**Comment by sachinchauhan2889** [comment]
i am working on this

**Comment by rutujak24** [comment]
Can I please take this issue?

**Comment by daretobedifferent18** [comment]
I am working on this issue. @mariobehling can you please tell me where can I see emails programs as you mentioned, so that I could proceed accordingly.
