### ISSUE TITLE
Sponsors Table: Search feature is not working in sponsors table in events overview page

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#5329]
**Describe the bug**

Event Overview Page: searching on sponsors in sponsors table is not working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'overview of events'
2. try searching for any sponsor in sponsor table.
3. See error

**Expected behaviour**

search button must work.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version:  86.0.4240.75 (Official Build) (64-bit)

#### Link
/events/:event_Id
https://eventyay.com/events/74b5de56?search=After

**Screenshots**

![new issue today](https://user-images.githubusercontent.com/72552281/96288395-fc11c700-1000-11eb-8b2c-f2a982e525cc.png)

**Comment by Optider** [comment]
@mariobehling @Orbiter @felixonmars Please let me know **shall I work on this**? Codeheat **label** is missing...

**Comment by garvitchittora** [comment]
@sachinchauhan2889 @mariobehling @Orbiter @felixonmars can I work on it?

**Comment by mariobehling** [comment]
I am unclear if we need a search feature for sponsors at this point of time. Maybe we just take out the search option here.
