### ISSUE TITLE
Organizer: Adding speaker without email results in sessions added to "my sessions" from organizer him/herself

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5342]
If an organizer adds a speaker "without email" the overview page shows the email of the organizer and sessions show up under "my sessions".

![Screenshot from 2020-10-21 14-26-34](https://user-images.githubusercontent.com/1583873/96719341-8ebbb880-13a9-11eb-8135-6586b939f021.png)

**Comment by maze-runnar** [comment]
working on it

**Comment by mariobehling** [comment]
This issue is still there just as before. Sessions still show up in https://eventyay.com/my-sessions/upcoming
Reproduce:
* Create an event
* Add sessions and speakers without email to your account and set them to accepted
* Go to https://eventyay.com/my-sessions/upcoming

Part of this issue is that these sessions are associated with the email of the event owner, if the owner does not add an email. Expected: The email field should be blank if the event owner uses the option to add sessions and speakers him or herself. 

![Screenshot from 2020-11-15 10-19-18](https://user-images.githubusercontent.com/1583873/99181099-9febb100-272c-11eb-9f6d-3e85bc1f0e92.png)
