### ISSUE TITLE
Public Schedule: Color area "jump difference" when extending area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5343]
On the public schedules, if the user expands a session the color area "jumps" a bit. The size of the color area before and after the expansion is different. Expected: Area should always be the same.

Compare https://eventyay.com/e/8fa7fd14/schedule

![Screenshot from 2020-10-21 16-11-42](https://user-images.githubusercontent.com/1583873/96732283-70a98480-13b8-11eb-8926-7c0f62557fd9.png)

**Comment by sachinchauhan2889** [comment]
Working on this issue

**Comment by Abhijay007** [comment]
can I work on this issue

**Comment by sachinchauhan2889** [comment]
> can I work on this issue
> 

I am working on this issue
