### ISSUE TITLE
Wizard Step 1: Organizer Info Links are not saved

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5344]
Links added to the organizer info get deleted on saving the event.

![Screenshot from 2020-10-21 16-18-48](https://user-images.githubusercontent.com/1583873/96732992-40161a80-13b9-11eb-9d1b-14ce3bd11438.png)

**Comment by anjali1102** [comment]
Assigned me

**Comment by maze-runnar** [comment]
@anjali1102 just claim the issue and move on to work.

**Comment by Abhijay007** [comment]
Can you please share some more details about it like a link to the page or where it is in the codebase?

**Comment by iamareebjamal** [comment]
Event creation wizard

**Comment by spy-1234** [comment]
Assigned me the task

**Comment by maze-runnar** [comment]
@spy-1234 can't you see the above comment. https://github.com/fossasia/open-event-frontend/issues/5344#issuecomment-714605514 
we don't assign issues , claim it and put your work. And if other has already claimed it, move to other issue

**Comment by Bucky25** [comment]
@mariobehling  can u please elaborate about that issue as i am adding link is successfully showing and opening on local machine .

**Comment by maze-runnar** [comment]
Add link to a text, it's not working after saving.

**Comment by Bucky25** [comment]
![Screenshot from 2020-10-28 16-11-33](https://user-images.githubusercontent.com/65112369/97425704-75ca7e80-1938-11eb-975c-73b1c997e6a2.png)
i have added these two links and are working fine so where's the bug can any body guide me

**Comment by maze-runnar** [comment]
you can't add a link like [this](https://en.wikipedia.org/wiki/The_Shawshank_Redemption). Means adding link to a text.
