### ISSUE TITLE
Footer/Internationalization: Show languages dropdown as written in their original way

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5347]
In the footer we have a language dropdown that shows all languages in English. Expected is that languages show up as they are written in their own language, e.g. German should be Deutsch, Vietnamese should be Tiếng Việt etc.
![Screenshot from 2020-10-21 19-32-24](https://user-images.githubusercontent.com/1583873/96756660-a8262a00-13d4-11eb-9c94-7035dbff0a06.png)

**Comment by FlashV998** [comment]
I want to work on this issue

**Comment by pc-beast** [comment]
I am working on this issue. Feel free to drop the PR if I haven't already : )

**Comment by mariobehling** [comment]
Unfortunately spelling is wrong in several languages. Also capital/non caps is not following any standard and languages are not sorted in any logical way. You could compare how this work e.g. on eventbrite, Wikipedia etc. For the sorting I also recommend we follow Wikipedia.

**Comment by Soumi150** [comment]
I am working on this.
