### ISSUE TITLE
Weblate Integration: Failed Connection

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5348]
The connection with weblate is failing. We now have a few German events that are interested to use the system. It would be helpful if we could have more translation here for example. We are able to engage some translators. Being able to use weblate would be a great advantage.

The error on weblate is:
> fatal: could not read Username for 'https://github.com': terminal prompts disabled (128)

https://hosted.weblate.org/projects/open-event/frontend/#repository

**Comment by iamareebjamal** [comment]
Fixed
