### ISSUE TITLE
Public Event Page: Free Tickets - Show "Free" instead of $0.00

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5364]
In the column "Price" and "Subtotal" for free tickets show "Free" instead of $0.00.

![Screenshot from 2020-10-23 12-19-03](https://user-images.githubusercontent.com/1583873/96992333-09134680-152a-11eb-8aa9-568534feb250.png)

**Comment by Abhijay007** [comment]
Sir, can you tell me the location of the file where this code is written in the codebase.

**Comment by iamareebjamal** [comment]
Please explore the website and codebase. You'll know where it is from

**Comment by Draco9421** [comment]
He there
I have changed the column "Price" and "Subtotal" for free tickets to show "Free" instead of $0.00.

**Comment by Draco9421** [comment]
Is this issue is already solved ?

**Comment by iamareebjamal** [comment]
No

**Comment by ShreyanshSrivastava** [comment]
As there is no sign of work from 3-4 days, I would like to work on this issue
