### ISSUE TITLE
Add public event Call for Speakers page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#54]
<img width="1680" alt="screen shot 2017-05-16 at 6 40 41 pm" src="https://cloud.githubusercontent.com/assets/2404372/26107533/40afccd6-3a67-11e7-8d50-a0aed44cf8d0.png">

- Located at `/events/<event_identifier/cfs` - route already exisits
- Should be a separate call for speakers component.
- Should support two states. (Call for speakers open and closed)
- Dummy data to be used
- The submit proposal button need not do anything

**Comment by CosmicCoder96** [comment]
@niranjan94 I would like to work on this.
