### ISSUE TITLE
Sessions/Speakers: Call for Speakers - Public Page vs. User Page

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5408]
This issue has a low priority 

1. Describe the problem: this is not a problem, it is rather a question

* Public page before user log-in, submitted session always shows No Session which is a bit confusing for the public
![Screenshot from 2020-10-28 22-58-58](https://user-images.githubusercontent.com/1658742/97501587-cd391080-1971-11eb-8bac-bb9a90c887be.png)

* User Log-In - this page is nice for users as they can see that they already submitted something 
![Screenshot from 2020-10-28 22-59-45](https://user-images.githubusercontent.com/1658742/97501580-cb6f4d00-1971-11eb-84e7-8f103983ae94.png)

2. Solution
Can submitted session only show when a user login

**Comment by iamareebjamal** [comment]
Yes we only show the submitted session of a particular user so it can only be shown to logged in user. For unauthenticated users, we can show, 'Login to submit sessions' instead of 'No sessions have been submitted'

**Comment by hpdang** [comment]
Yes **Login to show your submitted session** is much better than the current text. Please proceed with that if it does not take too much time to change. Thank you @iamareebjamal

**Comment by mariobehling** [comment]
We need to consider logic:
If a speaker has not submitted sessions, then showing the message "Login to show your submitted sessions" does not make sense. It should be clear to a speaker and public that they can only see submitted sessions if they are logged in.

Therefore yes, @iamareebjamal only this message makes sense:
* 'Login to submit sessions'
