### ISSUE TITLE
Sessions/Speakers: Enable 'Add a speaker' feature for speakers

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5409]
It looks like the 'Add a speaker' feature is only enabled for organizers. Is it possible to enable it for the proposal submitter so they can add additional speakers

**Comment by mariobehling** [comment]
It is possible, but what is the best way to implement this? Please provide examples and screenshot of other systems.

**Comment by mariobehling** [comment]
Dupllicate
