### ISSUE TITLE
Dates not translated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5412]
It seems dates are not translatable? While most things seem to be translated well, dates always show up in English. Please make date strings translatable, e.g. days of the week.

![Screenshot from 2020-10-28 23-32-51](https://user-images.githubusercontent.com/1583873/97503865-20ad5d80-1976-11eb-9a65-93dbf7d802d5.png)

**Comment by iamareebjamal** [comment]
I'm not sure how that'll work. Dates are generated dynamically from timestamps using moment. Most of our translation is based on static strings here defined in https://github.com/fossasia/open-event-frontend/blob/development/translations/messages.pot. It won't be as simple
