### ISSUE TITLE
Redirect user to the event they started to get a ticket after after completing the registration and logging in for the first time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5413]
Currently when an unregistered user tries to get a free ticket they are required to go through the registration process. When they finished the process they are finally able to get a ticket. However, it would be better if they would be directed to the event itself after finally logging in for the first time (after the registration). 

There please implement the following:
If a user register when they try to get a ticket of an event. Run the registration process as is and at their first login direct them to the event page where they tried to get the ticket.

**Comment by hpdang** [comment]
Yes, can we have the same flow for Speakers. Currently after a new user sign up to submit a session, user will be directed to **eventyay.com** page rather than a particular event itself.

**Comment by suryasiriki4** [comment]
@mariobehling Hi, l am a beginner in opensource, but I think I am good in web development. I understood what was the requirement. Can I start working on this? Any suggestions would be highly appreciated. Thank you.

**Comment by iamareebjamal** [comment]
This is now fixed in #5431
