### ISSUE TITLE
Team Page: Enable Organizer to resend invitation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5416]
* On the team page of an event please enable the organizer to resend an invitation. 
* Add a button "Resend invitation" if the user has not accepted the invitation yet.

![Screenshot from 2020-10-29 11-46-19](https://user-images.githubusercontent.com/1583873/97559151-5a657f00-19dd-11eb-8e64-a98b73364f44.png)

**Comment by Kunal-2001** [comment]
Can I try to work on this ??

**Comment by ayushontop** [comment]
I wanna work on this issue , I am relatively new but I think I can do this .

**Comment by ayushontop** [comment]
should I add a button to resend email ? Or you have any idea?

**Comment by Gautam-Arora24** [comment]
Working on this issue

**Comment by daretobedifferent18** [comment]
I am working on it

**Comment by Afzal-Ind** [comment]
Hi, @mariobehling in order to resend an invitation, how can we add this feature? I think this should be produced by the server's side first. Any hint. Thanks.

**Comment by Afzal-Ind** [comment]
Hi @mariobehling . Currently working here. Could you tell me which action allows to re-invite the organizer? Any hint.
