### ISSUE TITLE
Account Registration: Get rid of intermediate step after account registration and login new user right away

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5433]
When a user registers an account, they have to enter email and password. Right after they register they receive a screen "You have been registered successfully, login...". Instead after a user registers they should be logged into their newly created account right away.

![Screenshot from 2020-10-30 19-43-28](https://user-images.githubusercontent.com/1583873/97745026-86215b80-1ae8-11eb-8b05-ecd9f834c549.png)

**Comment by suryasiriki4** [comment]
Hi @mariobehling, I want to do this, please assign me the task. thank you.

**Comment by maze-runnar** [comment]
@iamareebjamal is this need to be solve on server too?

**Comment by iamareebjamal** [comment]
No

**Comment by Yash-R** [comment]
done please check the PR
