### ISSUE TITLE
Speaker: Deleting Speaker from Dashboard does not remove the deleted speaker from the page

### ISSUE THREAD

**Issue by daretobedifferent18** [fossasia/open-event-frontend#5435]
**Describe the bug**

On deleting the speaker from dashboard, the deleted speaker is still shown unless we manually reload the page.

**To Reproduce**
1. Go to Manage Event and then Speaker
2. Click on delete option of any speaker

**Expected behavior**

On deleting the speaker the page should show same behavior as on deleting the session i.e the speaker should be removed without reloading the page manually.

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by daretobedifferent18** [comment]
@mariobehling @iamareebjamal  can you please validate or approve this issue.

**Comment by akash2408** [comment]
iam working on it
