### ISSUE TITLE
Country Field in Billing Information: Only show country dropdown, do not automatically fill in random info - only country

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5438]
* [ ] Fix Country dropdown. It automatically shows data saved in the browsers instead of using the dropdown country option

Expected: Only show country options. Do not show other possible data saved in the browser.

![Screenshot from 2020-07-30 10-25-29](https://user-images.githubusercontent.com/1583873/88901228-d4f0f800-d250-11ea-8ba8-36f41ba0394a.png)

**Comment by Soumi150** [comment]
I am working on this.

**Comment by ankingcodes** [comment]
Working on this.

**Comment by Soumi150** [comment]
@ankingcodes are you still working on this or I can pick this up ?

**Comment by daretobedifferent18** [comment]
I am working on this
