### ISSUE TITLE
Ticket box on public event page: When cost is 0 do not show $ sign as countries use different currencies

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5442]
Using a $ sign is not always suitable as countries use different currencies. When events offer free tickets only and no payment method has been chosen a dollar sign shows up before 0.00. 

Expected: do not show as dollar sign when event orders are zero.

Compare https://eventyay.com/e/1f720482
![Screenshot from 2020-11-01 23-28-58](https://user-images.githubusercontent.com/1583873/97817081-51ed9c80-1c9a-11eb-81ee-8565b4bb15aa.png)

**Comment by Soumi150** [comment]
Working on this.

**Comment by daretobedifferent18** [comment]
> Working on this.

I am already working on this

**Comment by daretobedifferent18** [comment]
> Working on this.

I am already working on this issue
