### ISSUE TITLE
Public Speaker Page/Organizer Speaker Page: Make Speakers Sortable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5443]
Currently there is no option to control the order of speakers on the public page. Sometimes important speakers are listed at the end of the speakers list. This is not good. We need a way to sort speakers. Therefore please implement the following:
* On the organizer speakers page provide the option to change the order of speakers. Use the same up and down arrow feature that is available on the ticket list.
* On the feature speaker list and public speaker page of an event show the speakers in the same orders as on the organizer speakers page.

Speakers on the organizer speakers page
![Screenshot from 2020-11-01 23-33-48](https://user-images.githubusercontent.com/1583873/97817195-17383400-1c9b-11eb-980b-013e580c61fc.png)

Public speakers view
![Screenshot from 2020-11-01 23-25-59](https://user-images.githubusercontent.com/1583873/97817201-1d2e1500-1c9b-11eb-84e4-b103c4c14f29.png)

**Comment by Samridhi-98** [comment]
I would like to work on this issue please assign me.

**Comment by Samridhi-98** [comment]
working on this issue.

**Comment by Samridhi-98** [comment]
@mariobehling, I currently use Windows 10 and I am getting this error: gettext is not recognized as an internal or external command. I tried to install gettext without any success. I also tried this for installing gettext  https://mlocati.github.io/articles/gettext-iconv-windows.html
Still getting this error: gettext is not recognized as an internal or external command.
Please suggest a way to fix this issue.
