### ISSUE TITLE
Logged in user logged out when verification link is used

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5444]
At the following flow the logged in user is logged out of the account when a verification link is used. Expected: User should stay logged in if it is the same user account that is using the verification link.

1. New unregistered User gets a ticket
2. User enters email and password.
3. User orders ticket. (user is now logged in)
4. User received welcome/verification mail and ticket mail
5. User clicks on verification link
6. Page opens - user verifies
At the same time the user gets logged out, but should not be logged out.

**Comment by Yash-R** [comment]
it think it's working completely fine when user order ticket, user just get the mail to see that ticket not a verification mail.

**Comment by maze-runnar** [comment]
I followed the steps, but it's working fine. Means ticket link is good, and verification link is not logging out.
![Screenshot from 2020-11-06 18-37-22](https://user-images.githubusercontent.com/56407566/98369674-4fef5900-205f-11eb-8181-4ccc4567916f.png)

**Comment by namanjain007** [comment]
Actually after ordering a ticket from unregistered account just asks for email and not password. 
![Screenshot from 2020-11-08 12-43-42](https://user-images.githubusercontent.com/31573807/98459402-885a7880-21c0-11eb-9173-a9b5d1f5bc3d.png)
![Screenshot from 2020-11-08 12-44-08](https://user-images.githubusercontent.com/31573807/98459404-8d1f2c80-21c0-11eb-9b6d-ed5bb99458b3.png)
User gets logged in directly.
![Screenshot from 2020-11-08 12-45-05](https://user-images.githubusercontent.com/31573807/98459422-ae801880-21c0-11eb-9158-1e77de132d10.png)
After successfully verifying the email ,  redirect link does not logs out .
![Screenshot from 2020-11-08 12-46-03](https://user-images.githubusercontent.com/31573807/98459435-c6f03300-21c0-11eb-9b0b-22f0906d762e.png)

**Comment by iamareebjamal** [comment]
You seem to be a dozen commit behind development

**Comment by namanjain007** [comment]
> You seem to be a dozen commit behind development

okay thanks.

**Comment by namanjain007** [comment]
Yes, the verification link after redirection does not logs out .

**Comment by iamareebjamal** [comment]
Unless it has been 24 hours since previous login, the user should be logged out. 

@mariobehling Can you please recheck, it seems to be working fine

**Comment by maze-runnar** [comment]
@mariobehling can you please confirm here?

**Comment by iamareebjamal** [comment]
Will reopen when confirmed
