### ISSUE TITLE
Orders Page: Deleted tickets still counting in number of ticket sales

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5450]
If an organizer has deleted tickets they should not count anymore to the number of sold tickets/orders or appear in the download CSV/PDF. 

Currently deleted tickets do not show up in the list of orders/tickets anymore, which is correct. However:
1: on the overview page they are still counted
2: They show up in the CSV/PDF of orders and tickets, that organizers can download.

Compare: https://eventyay.com/events/1f720482/tickets (only accessible for admins)
![Screenshot from 2020-11-02 13-13-31](https://user-images.githubusercontent.com/1583873/97867069-6cad2900-1d0d-11eb-8394-4d7a4d4ac0fc.png)

**Comment by maze-runnar** [comment]
on it

**Comment by maze-runnar** [comment]
@iamareebjamal I think this issue is related to issue that A organizer can delete tickets that has sales at the time.If organizer won;t be aable to delete ticket that has sales, then there will be no problem like this. Am I correct?

**Comment by maze-runnar** [comment]
And it is not count expired order sales So implementation is correct. Just need to restrict deletion of ticket that has sales. https://github.com/fossasia/open-event-frontend/issues/5195

**Comment by iamareebjamal** [comment]
Yes, but they should still not show up in CSV as having no sales as well.

**Comment by maze-runnar** [comment]
the organizer export that pdf/CSV that shows orders & attendees. So how a ticket that is deleted and bought can appear there. Because that is restricted. So if there is an order for a ticket that can't be deleted and if there is no order the ticket won't show up in pdf/CSV. And if there is no order and ticket deleted there is no issue because it's not there.

**Comment by iamareebjamal** [comment]
OK, I understand now
