### ISSUE TITLE
Fix issue with brackets and commas across platform

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5452]
We have a number of places where there is no space in front of a bracket, e.g. as in "User(Email)", "Sales($) etc., or other places where there is a space in front of a comma, e.g. "Hello ," or no space after a comma, e.g. "organizer,co-organizer" etc.

- Please find all places where there is no space in front of a bracket and add a space. Expected is "User (Email)"
- Find all places where there is a space in front of a comma and where there is no space after a comma and fix them. Expected is, e.g. "organizer, co-organizer"
- Ensure that changes do not impact functionality of the system

![Screenshot from 2020-11-02 13-53-26](https://user-images.githubusercontent.com/1583873/97870461-4d18ff00-1d13-11eb-840c-06a5ebff63f0.png)

**Comment by ishikalohia** [comment]
Working on this.

**Comment by Subham142** [comment]
@ishikalohia  are you still working on it?

**Comment by Subham142** [comment]
@mariobehling just wanted to confirm the changes want are limited to the UI part or we can check the js code also for the space  and commas?

**Comment by iamareebjamal** [comment]
JS is used to create the site's UI. UI === JS

**Comment by Chadha93** [comment]
Still need time as newer commit causes conflict. I upstream updated it and trying to add more Fix in PR
