### ISSUE TITLE
Organizers Ticket/Order Page: Do not show $ or other currency for any 0.00 amount

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5453]
A number of places show a $ sign at places where the amount is 0.00, e.g. tickets or orders that are 0.00.

1. If any value is 0.00 please do not show the $ sign in the orders/tickets section and subpages of an event
2. Check any other places in the system, e.g. admin area to fix this - do not show any currency anywhere on the system if an amount is 0.00.

![Screenshot from 2020-11-02 13-58-42](https://user-images.githubusercontent.com/1583873/97870940-024bb700-1d14-11eb-8908-88208211672a.png)

**Comment by daretobedifferent18** [comment]
@mariobehling can I do fix this issue in same PR #5447 bcz the issue #5442 is similar to this issue.
If you say I can mention this issue in that PR #5447 only?

**Comment by iamareebjamal** [comment]
Yes, please do it in the same PR

**Comment by daretobedifferent18** [comment]
@mariobehling this issue is being resolved by me with PR #5447 You can close this issue.
