### ISSUE TITLE
Sponsors: Organizers wants to have bigger logos for main sponsors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5455]
In our sponsors section we need an option to have a two column sponsor section with bigger logos. There could be a tick box "Large Image" to achieve this.

Question: Do we need an option in the sponsor form to show that large logos are in a two column area? Or can we do it in a way that if there are two large logos a third logo simply moves to the next line?

Compare: https://eventyay.com/e/1f720482

![Screenshot from 2020-11-02 14-26-10](https://user-images.githubusercontent.com/1583873/97873375-d0d4ea80-1d17-11eb-9beb-e93b9a909f0e.png)

Large tickbox could be added

![Screenshot from 2020-11-02 14-17-13](https://user-images.githubusercontent.com/1583873/97873531-12659580-1d18-11eb-9c0a-cef2dbb328e2.png)

**Comment by maze-runnar** [comment]
Using a checkbox for a big image and a small image in a single row can mess up the layout. Instead allowing two logos in a row is a better option.

**Comment by mariobehling** [comment]
Yes, I agree, but we need two logos in a row for top sponsors and three logos for other sponsors. How to achieve this in the sponsorship form? What is the easiest way?

**Comment by maze-runnar** [comment]
What is level in sponsor section? Can we classify based on it, means the min the level, the highr priority.
![scrnli_11_2_2020_8-55-59 PM](https://user-images.githubusercontent.com/56407566/97885777-d3523700-1d4d-11eb-9829-6af56026813a.png)

**Comment by maze-runnar** [comment]
we can add a checkbox which will fill the type box with input "Golden Sponsor" (read-only), and then can achieve 2 in a row.

**Comment by mariobehling** [comment]
Some events do not have Gold sponsor. Every event has their own types and definitions, but here is a way it could work:

On the top of the sponsorship step please provide a form to define level, types, columns and a plus sign to add one more level.

1. The structure of the row should be as follows:
Level [number here] | Type [text field] | Columns [dropdown number here - 1, 2, 3] | [+]
* Please implement firstly options for
   * 1 column with very large logo
   * 2 columns with large logo
   * 3 columns with normal sized logo

2. For the sponsor form itself, please take out "Type" and make "Level" into a dropdown menu that depends on what is filled in at the structure above in 1.

**Comment by iamareebjamal** [comment]
We can just do this, if there are two sponsors, show them in 2 column. If there is one, we only show in 1. If there are 3 or more, we show in column with next moving on to next line. This can be done without any backend or DB changes easily with flexbox CSS

**Comment by mariobehling** [comment]
@iamareebjamal Well, this is the way it is right now or what is the difference? Basically the organizers are requesting to have sponsors who pay more for their sponsorship in a larger size.

**Comment by iamareebjamal** [comment]
Then, can we use the level to make the size larger? I'm afraid that we increase the complexity and it can be done in an easier way. We can use levels in this way - any sponsor who's paying more has different level than others. Right now, we use level for order. The sponsors with lower level appear in the above row and with increasing level, it is shown below each row. Now, we can use the same level for controlling the size of the icons.

As the level grows, the size becomes smaller. If someone wants to keep the size same, they can keep the level same and we order according to the type that appears first in the sponsor section of the even wizard. 

This solves the problem of size using the existing level which makes sense and also allows for same size of sponsors if someone wants it (which I don't know why they would if they are separating the sponsors by levels in the first place)

**Comment by mariobehling** [comment]
@iamareebjamal Ok, sounds good and then we come back to the sponsor tab in future, cause I wish it would be a bit simpler from a user perspective. However, anything we change could add complexity as you correctly say.

**Comment by namanjain007** [comment]
@iamareebjamal  the algorithm to compute the level of a sponser has to depend on the cost invested . If in future , another sponser comes with some arbitrary cost , then level should be according to already present . So I think ratios of cost(i)/sum could be taken right ?

**Comment by iamareebjamal** [comment]
It's not that complicated. Just show smaller icons for sponsors with lower levels. No need for a formula or a research paper

**Comment by codedsun** [comment]
@iamareebjamal - What should be the size of image level wise?

**Comment by iamareebjamal** [comment]
@mariobehling Previously (v1), level was proportional to the size of sponsor. Bigger level -> bigger sponsor. But now it is being used in an opposite manner. Level 1 means bigger and Level 5 means smaller. So I'm going with current logic because even the display order is this way in the current site
