### ISSUE TITLE
Login Box: Show info message when page directs to login page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5456]
If a user wants to perform different actions, they need to login. However, there is no message usually like "You need to login to perform this action." 

Please identify different cases when the login page shows up and add a message for the user, e.g.
* User verified by clicking verification link show "Thank you for verifying your email address. Please login to continue."
* User clicks "Create Event", but is not logged in show "Please login to create an event. If you have not registered yet, please create an account first. Thank you!"
* What other actions require a user to login? Please add cases and messages.

![Screenshot from 2020-11-02 14-36-43](https://user-images.githubusercontent.com/1583873/97874647-9704e380-1d19-11eb-9ad4-07ccdb52ae79.png)

**Comment by Uyadav207** [comment]
Working on It.

**Comment by silenteyesoncode** [comment]
Like to work on it

**Comment by namanjain007** [comment]
can I work upon it ?

**Comment by Draco9421** [comment]
can I work on this

**Comment by Draco9421** [comment]
I am working on it.

**Comment by Gumanpratapsingh** [comment]
I am trying it.
