### ISSUE TITLE
Event Dashboard: Fix and Enhance Sponsorbox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5462]
The sponsorbox has a few issues. Please change as follows:
* Delete the column "Options" and distribute the other rows in a nice way (all the buttons of options direct to the same area anyways, so no need anymore)
* Rename button "Add Sponsors" to "Edit"
* keep a space to the box edge for the previous / next buttons on the bottom of the box
* check how to make the style suitable, maybe the table should not be 100% of the box width?

![Screenshot from 2020-11-02 23-08-22](https://user-images.githubusercontent.com/1583873/97925071-0b16aa00-1d61-11eb-8397-96f1af956204.png)

**Comment by Tushardeepak** [comment]
I am working on this

**Comment by ayushontop** [comment]
I am working on this

**Comment by ayushontop** [comment]
I am working on this
