### ISSUE TITLE
Event Dashboard: Adding content of boxes results in large empty areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5463]
The way boxes are placed on the events dashboard results in large empty spaces once a box gets larger. Please change the boxes in a way that they are placed below each other without white spaces.

![Screenshot from 2020-11-02 15-48-36](https://user-images.githubusercontent.com/1583873/97935540-30171700-1d79-11eb-94ce-5df84a38e429.png)

**Comment by sachinchauhan2889** [comment]
I am working on this issue
