### ISSUE TITLE
Reorder event dashboard boxes and rename them

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5468]
Reorder event dashboard boxes and rename them as below.

Please make the box order as follows:

Event Checklist - Overview
Sponsors - Tickets
Apps - Team Members

![Screenshot from 2020-11-03 11-58-40](https://user-images.githubusercontent.com/1583873/97977230-2b2f8300-1dcc-11eb-957b-396aa4bccc8c.png)

**Comment by carrycooldude** [comment]
I want to work on this issue @mariobehling
