### ISSUE TITLE
Event Dashboard: Unwanted Line Break in longer Event Titles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5474]
There is an unneeded line break in longer event titles on the event dashboard. Expected line breaks should only happen to prevent the title to overlap other areas.
![Screenshot from 2020-11-03 20-02-25](https://user-images.githubusercontent.com/1583873/98029393-b5e5a180-1e0f-11eb-9576-1f789dd92ad9.png)

**Comment by Gautam-Arora24** [comment]
May I work on this issue?

**Comment by mariobehling** [comment]
No need to ask. Just claim it and go ahead solving it.
