### ISSUE TITLE
Integrate Project with Big Blue Button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5475]
Offering integrated video features is a must for an event platform these days. There are two good options Jitsi and Big Blue Button. BBB has more moderation features which are important for conference events.

Please propose and implement ways to integrate BBB and open relevant sub issues on frontend and server project. Specifically we need the following:
* Integration with eventyay rooms = BBB rooms
* Integration with eventyay sessions = BBB session rooms (if chosen by organizer)
* Access Control/Permissions integration with event team, e.g. allow organizers to control moderation features
* Access Control/Permissions integration with ticket holders to join a BBB event
* Access to recorded sessions by BBB through eventyay UI 

There is a demo server on https://demo.bigbluebutton.org/
API documentation: https://docs.bigbluebutton.org/dev/api.html

**Comment by anjali1102** [comment]
Is this issue beginner friendly?

**Comment by iamareebjamal** [comment]
No
