### ISSUE TITLE
Event Dashboard: Provide feature to directly generate web app from dashboard through an API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5476]
On the event dashboard in the apps section implement the following feature:
* When the user clicks "Generate Web App" fill in all data and execute the website generator at https://open-event-wsgen.herokuapp.com
* Open the page of the website generator in a new tab 
* Implement a missing API connection (if any) in https://github.com/fossasia/open-event-wsgen

**Comment by djcruz93** [comment]
I would like to work on this, claiming it.

**Comment by iamareebjamal** [comment]
Deployed dev branch. Should work now

**Comment by mariobehling** [comment]
ok, thanks. Process works now, but sites do not get build due to error. Already opened another issue.
