### ISSUE TITLE
Date and Time translations using AM/PM

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5491]
Date and time are translated as they use AM/PM which is not used in other languages. Propose and implement a solution or translation across languages e.g. using 24h clock in other languages.

![Screenshot from 2020-11-05 01-17-43](https://user-images.githubusercontent.com/1583873/98181993-f115cc80-1f04-11eb-9883-12f7787437ba.png)

There are different time formats on the calendar page for example, e.g. https://eventyay.com/e/1f720482/calendar
![Screenshot from 2020-11-05 12-28-11](https://user-images.githubusercontent.com/1583873/98235714-7e3b3e80-1f62-11eb-96f5-142c1f1de4be.png)

**Comment by Siddhant-K-code** [comment]
We Can Functionality Like this : 
![image](https://user-images.githubusercontent.com/55068936/98271866-68576900-1fb6-11eb-825e-4d7448f05a44.png)

All Times will be With respect to `UTC`

using: https://www.timeanddate.com/worldclock/

**Comment by iamareebjamal** [comment]
No

**Comment by Siddhant-K-code** [comment]
> No

then ?

**Comment by iamareebjamal** [comment]
Propose and implement a solution or translation across languages e.g. using 24h clock in other languages.

**Comment by Soumi150** [comment]
Do you mean 10 am will be 10 heures in French and so on ?

**Comment by iamareebjamal** [comment]
No

**Comment by Soumi150** [comment]
Working on this.

**Comment by daretobedifferent18** [comment]
I am working on this
