### ISSUE TITLE
Implement sponsors API on events/<event-id> route

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-frontend#550]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/20153241/28520352-cb465b16-708c-11e7-86ad-86fb940a6f18.png)

**Comment by niranjan94** [comment]
On hold until ember model table is made compatible with the api. @geekyd
any eta on that?

**Comment by geekyd** [comment]
@niranjan94 I will start the work on that and try to finish it ASAP.
