### ISSUE TITLE
Public Event Pages: Standardize width of sidebar and make it same as the footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5511]
On the public event pages the sidebar spacing is different to the footer left and right spacing. The frontpage has the same left and right spacing as the footer.

Expected is: that on the public event pages the left and right space needs to be same as on the footer. The central content column needs to have the same width as the central area of the footer.

![Screenshot from 2020-11-06 17-11-29](https://user-images.githubusercontent.com/1583873/98389426-52988100-2054-11eb-92b0-03d85ab8605d.png)

**Comment by sachinchauhan2889** [comment]
I am working on this issue

**Comment by mariobehling** [comment]
Thanks, please also take care of the right side and fix the subpages too.

**Comment by anjali1102** [comment]
Is this issue resolved?

**Comment by sachinchauhan2889** [comment]
@anjali1102 i have opened a PR. I am working on this.
