### ISSUE TITLE
Update notification messages for verifying account and show "full access" notification on frontpage 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5516]
Please change notification messages as follows and change functionality as follows:
![Screenshot from 2020-11-07 07-18-51](https://user-images.githubusercontent.com/1583873/98433685-85309100-20c9-11eb-8eac-f411cf5e4bbe.png)

* [x] "Account unverified" notification
  - original notification
Your account is unverified. Please verify it by clicking on the confirmation link that has been emailed to you.
  - change to ->
Your account functionality is limited. To get full access to all features you need to verify your email by clicking on the confirmation link that has been emailed to you.

![Screenshot from 2020-11-07 07-21-48](https://user-images.githubusercontent.com/1583873/98433954-a1cdc880-20cb-11eb-969f-80ada1b1afb1.png)

* [x] "full access" notification
  - original notification
Thank you, your email has been verified successfully!
  - change to ->
Thank you, your email has been verified successfully! You now have full access to all features.
* [ ] Instead of showing the "Full access - Thank you..." on a white page, show the front page with the message on top

**Comment by sachinchauhan2889** [comment]
I am working on this

**Comment by Subham142** [comment]
@sachinchauhan2889  I'll be more than happy to take on this  bug if you choose to abandon it ,till then please carry on your work

**Comment by sachinchauhan2889** [comment]
@Subham142 let me try this issue. If i will unable  to solve this, i will definitely leave this and forward this issue to you.

**Comment by krishna9304** [comment]
Can i work on this issue?

**Comment by Raunaksingh100** [comment]
> Can i work on this issue?

There is already pr for this plz find some other issues

**Comment by sachinchauhan2889** [comment]
@iamareebjamal @mariobehling sir, my PR solves first two points. Can you please explain 3rd point.
- Are you want full access message on front index page.
Or
-  you want front page template in place of white space at verify route.
