### ISSUE TITLE
Implement Notifications API 

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#552]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Create notifications model
- Implement Notifications API 

@sumedh123 @anu-007 You can take this up until #551 is resolved.

**Comment by sumedh123** [comment]
@geekyd @anu-007 I ll take this up.

**Comment by sumedh123** [comment]
@niranjan94 Is there something wrong on server side. I am getting 500 on the routes on which api is implemented. Is this related to health check issue?

**Comment by niranjan94** [comment]
@sumedh123 which url ?

**Comment by sumedh123** [comment]
@niranjan94 Its fine now. I dont know why but something caused all the api implemented urls to give 500.

**Comment by sumedh123** [comment]
@niranjan94 @geekyd This is on hold until the server resolves https://github.com/fossasia/open-event-orga-server/issues/4178
