### ISSUE TITLE
Team Page : Empty email fields

### ISSUE THREAD

**Issue by Gautam-Arora24** [fossasia/open-event-frontend#5526]
**Bug**
Whenever an organiser tries to add people with empty input fields, the frontend shows the empty fields after submission.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Events Section
2. Create an Event
3.  Go to teams section
4. Add people with empty fields
5) See the bug

**Expected behaviour**
When an owner tries to add another organizer without providing an email it should not be possible submit the form. The form should just show "field required" or similar error message.

**Screenshot**
![Screenshot 2020-11-08 at 1 41 21 PM](https://user-images.githubusercontent.com/53913514/98460206-20a82b80-21c8-11eb-9fad-bb03eecf7c46.png)

**Comment by mariobehling** [comment]
What do you mean with empty fields? Please give an example. An email with an empty field?

**Comment by Gautam-Arora24** [comment]
What I mean with empty field is when a user tries to add people in the Team section without providing the details, instead of not submitting the form the frontend is showing the above image

**Comment by Gautam-Arora24** [comment]
Empty field here just means that clicking Add People button without providing the details

**Comment by mariobehling** [comment]
Ok, I updated the expected behavior.

**Comment by sachinchauhan2889** [comment]
working on this.

**Comment by aravind-korada** [comment]
@mariobehling if the issue fixed?
I am not able to reproduce this.

**Comment by Soumi150** [comment]
Working on this.

**Comment by Draco9421** [comment]
I couldn't reproduce this bug.

**Comment by daretobedifferent18** [comment]
I am working on this issue
