### ISSUE TITLE
Implement API on explore route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#553]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Work to be done:
- Integrate event-type, event-topic, event-subtopic API to side bar
- Implement event search using filters

@anu-007 You can take it up until #551 is resolved

**Comment by CosmicCoder96** [comment]
@niranjan94 I have implemented the API for event-type, event-topics and event-subTopics, can the filtering be handled in a separate issue ?

**Comment by niranjan94** [comment]
Okay sure
