### ISSUE TITLE
Wizard Step 3: Attendee Custom Question moving to different position

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5537]
The attendee custom question is moving to a different position when the organizer revisits the wizard step 3. Expected: It should stay at the end of the list.

![Screenshot from 2020-11-09 11-46-45](https://user-images.githubusercontent.com/1583873/98532024-6d037200-2281-11eb-91ed-eaf41b30daa0.png)

**Comment by maze-runnar** [comment]
on it

**Comment by maze-runnar** [comment]
@iamareebjamal  I think it is rearranging on server?

**Comment by iamareebjamal** [comment]
Frontend should sort it and always display custom fields on bottom

**Comment by maze-runnar** [comment]
ok
