### ISSUE TITLE
Admin Pages: Enable admin to ultimately delete events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5539]
In the event database there are a number of events that cannot be edited as migrations might not have worked well. Some of these events clutter up some tables as their data is inconsistent, e.g. on the sales page an event schedule in 2107.

Please enable admins to delete these events on the page https://eventyay.com/admin/events/deleted. In the action buttons list add a delete button to ultimately delete an event from the "deleted list".

![Screenshot from 2020-11-09 17-30-23](https://user-images.githubusercontent.com/1583873/98568340-452c0280-22b1-11eb-9c0d-45cc2f765358.png)

**Comment by PratishShrivastava** [comment]
Can I work on this issue. @mariobehling

**Comment by Raunaksingh100** [comment]
> Can I work on this issue. @mariobehling

Go ahead!!
