### ISSUE TITLE
Admin Pages: Change "Member Since" to date

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5542]
The column "member since" shows x days ago instead of a date. Please change the column to show a date on https://eventyay.com/admin/users/

![Screenshot from 2020-11-09 18-01-41](https://user-images.githubusercontent.com/1583873/98572347-d0a79280-22b5-11eb-8d59-91dcd7e7224d.png)

**Comment by codedsun** [comment]
Taking this up!
