### ISSUE TITLE
Organizer: Attendee and Order Overview fix search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5548]
The search on the organizer and attendee forms do not show results properly, e.g. First, Last name and email are not showing the relevant results.

Please ensure the search shows relevant results.

![Screenshot from 2020-11-09 22-58-37](https://user-images.githubusercontent.com/1583873/98601428-54c24000-22df-11eb-8efc-5ad0b27d1505.png)

**Comment by Soumi150** [comment]
Taking this up.
