### ISSUE TITLE
Improper Alignment of Order Now alert box

### ISSUE THREAD

**Issue by Saumyachitransh01** [fossasia/open-event-frontend#5551]
**Describe the bug**

Proper Alignment of alert box

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Eventyay platform' and make sure you're not logged in.
2. Click on any featured event
3. Scroll down and place order 
4. See error: Inappropriate alignment of alert box

**Expected behaviour**

The contents of the alert box should be properly aligned and presentable.
**Screenshots**

![Screenshot from 2020-11-10 12-24-52](https://user-images.githubusercontent.com/55341933/98640518-29c40480-2350-11eb-8e6f-3982d986dbb9.png)
![Screenshot from 2020-11-10 12-14-14](https://user-images.githubusercontent.com/55341933/98640521-2af53180-2350-11eb-9805-ffe8fe37ccff.png)

**Comment by mariobehling** [comment]
Thanks! Please also:
* [ ] Reduce the size of the box
* [ ] Increase spacing of squeezed text (gray and black text is very close without any spacing)

**Comment by sachinchauhan2889** [comment]
working on this
