### ISSUE TITLE
Event Export: Zip export download link not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5555]
After generating a zip file the download on the website is not working. The user receives an automated email with a download link, which is working. However, on the website itself there is an empty error message box and nothing happens.

Reproduce:
1. Create an event with details
2. Go to "Export" and export an event
3. Click Download button.

![Screenshot from 2020-11-10 10-32-40](https://user-images.githubusercontent.com/1583873/98656052-815a7400-2340-11eb-862e-26dc79071ef7.png)

**Comment by Draco9421** [comment]
I am working on this.

**Comment by Draco9421** [comment]
@mariobehling It is always giving "Event export failed" error whenever I click on the start buttton. Can you help me to pass through it.
