### ISSUE TITLE
Implement Api integration for Speakers call in public/cfs

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-frontend#556]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

I'll work on this

**Comment by niranjan94** [comment]
@utkarshnath after https://github.com/fossasia/open-event-frontend/pull/532

**Comment by utkarshnath** [comment]
@niranjan94 I have already solved most parts of this issue, I'll continue on this after #532

**Comment by sumedh123** [comment]
@utkarshnath Are you working on this one?

**Comment by harshitagupta30** [comment]
@sumedh123 If he is not working may a send the PR as I have already started working on this and I mentioned it in my scrum as well. :)

**Comment by sumedh123** [comment]
@niranjan94 Shall we wait for utkarshnath's input? or let @harshitagupta30 proceed?

**Comment by niranjan94** [comment]
@harshitagupta30 please send a PR
