### ISSUE TITLE
Tab "Email" Implement Organizer Message and Email/Ticket PDF as Feature "Customize your order confirmation"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5560]
We need a way to allow organizers to share a message with ticket buyers right at the end of the order process, in the ticket email send to ticket buyers and in the ticket PDF. Custom Emails should be configurable through a tab on the Dashboard menu of events. Therefore please implement:

1. A tab "Custom Emails" on the organizer top menu of events behind the item "Tickets"
![Screenshot from 2020-11-22 03-11-22](https://user-images.githubusercontent.com/1583873/99892012-812b7400-2c70-11eb-8b37-7bac8751cde2.png)

* [ ] a) On the page add a section heading: Customize Order Page
  * [ ] with message "After registering for your event, attendees will see a message on their order page. Here you can add special instructions or other useful information.
* [ ] b) Section: Customize Email and Ticket PDF
  * [ ] with message "Your attendees will also receive an email after registration, confirming their order. Add important instructions or other useful information for attendees here that you want to include in the ticket email and ticket PDF.

2. Add a **"customize a message on the order page"** (the page where the user can download the tickets and invoice)
  * [ ] a) Please add a box "Organizer Message" above the box "Attendee Information"
  * [ ] b) Only add the box if the organizer has actually included this information
  * [ ] c) Ensure it works on mobile view as well
![Screenshot from 2020-11-10 13-53-11](https://user-images.githubusercontent.com/1583873/98678052-41a28500-235e-11eb-8399-474f14c81919.png)

3. Show the **customized message on the ticket email and order PDF**
  * [ ] a) Include the message in the ticket email below the final greetings as follows
  * [ ] b) But: Only show the message in the email if the organizer has actually configured a message (do not show a message if the organizer has not configured it)
  * [ ] c) Include the info on the ticket PDF.

`Below you find a message from the organizer.`

`---------------------------------------------------------------------------------------`
`[Message from organizer here]`

`----------------------------------------------------------------------------------------`

**LINKS**
Compare: https://www.eventbrite.com/support/articles/en_US/How_To/how-to-create-custom-order-confirmations

![Screenshot from 2020-11-10 16-25-58](https://user-images.githubusercontent.com/1583873/98694196-75d37100-2371-11eb-8a4e-1fa7ba7e8b98.png)

**Comment by Saumyachitransh01** [comment]
Working on this

**Comment by Saumyachitransh01** [comment]
Does it require altering open-event-server too?

**Comment by iamareebjamal** [comment]
Yes

**Comment by daretobedifferent18** [comment]
I am working on it

**Comment by mariobehling** [comment]
The full feature is currently out of scope. Therefore closing it.
