### ISSUE TITLE
Mobile View: Footer use same width as above tiles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5563]
The footer on the mobile view should have the same spacing to the left and right as the above area - with the tiles.

![Screenshot_20201110_192659_com android chrome](https://user-images.githubusercontent.com/1583873/98715854-fbafe600-238a-11eb-846e-e094f1a739b9.jpg)

**Comment by Raunaksingh100** [comment]
Working on this issue

**Comment by Raunaksingh100** [comment]
I am working on this issue.
