### ISSUE TITLE
Mobile View Top Menu: Move Burger Menu and Substitute Create Event with Login

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5564]
Please do the following changes for the mobile view:
* Move burger menu to top right
* Instead of "Create Event" show "Login" if user is not logged in

![Screenshot_20201110_193452_com android chrome](https://user-images.githubusercontent.com/1583873/98716518-fd2dde00-238b-11eb-9e1c-1d9c1aa1e389.jpg)

**Comment by Raunaksingh100** [comment]
Working on this issue

**Comment by sachinchauhan2889** [comment]
working on this
