### ISSUE TITLE
Mobile View: Order Page Issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5566]
The mobile view order page has a few issues. Please fix them:
* Event Information box is missing
* Order summary table should also be a table in mobile view as well
* Buttons "Tickets" and "Invoice should have some spacing in between and some more spacing to the text

![Screenshot from 2020-11-10 19-50-59](https://user-images.githubusercontent.com/1583873/98718083-3ebf8880-238e-11eb-86b0-98723ae53ed2.png)

**Comment by sachinchauhan2889** [comment]
@iamareebjamal @mariobehling issue solved in #5561 . You can close this issue
