### ISSUE TITLE
Replace link-input with link-field and social-link-field

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#5570]
Replace all link-input component calls with link-field and social-link-field and then remove the component and all segmented link shenanigans from the project

**Comment by sachinchauhan2889** [comment]
working on this.

**Comment by Saumyachitransh01** [comment]
There's only 1 file consisting of link-input. 

![Screenshot from 2020-11-11 17-39-39](https://user-images.githubusercontent.com/55341933/98810390-2f4f4680-2445-11eb-819b-57068b549ddc.png)

So only this needs to be changed?

**Comment by snitin315** [comment]
Nope, its a test.

**Comment by snitin315** [comment]
See https://github.com/fossasia/open-event-frontend/search?q=LinkInput

**Comment by Saumyachitransh01** [comment]
Okay thanks

**Comment by daretobedifferent18** [comment]
I am working on it

**Comment by daretobedifferent18** [comment]
I am working on this

**Comment by daretobedifferent18** [comment]
I am working on this
