### ISSUE TITLE
Improve Site Speed: Remove unused JavaScript

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5573]
According to the Google Page Speed test https://developers.google.com/speed/pagespeed/insights/?url=eventyay.com removing unused JavaScript could improve the site speed by over 3 seconds. Please improve the speed by implementing the recommended changes as outlined in this article https://web.dev/unused-javascript/.

![Screenshot from 2020-11-11 10-40-27](https://user-images.githubusercontent.com/1583873/98795519-97346b80-240a-11eb-8cc0-ad26760ee5d6.png)

**Comment by iamareebjamal** [comment]
Same problem as #5575

**Comment by imrajat7** [comment]
@mariobehling @iamareebjamal can i work on it ?

**Comment by iamareebjamal** [comment]
You can try

**Comment by codergiri12** [comment]
hello @iamareebjamal  I am new to this can you plz explain me what exactly to do in this issue ??

**Comment by Raunaksingh100** [comment]
> hello @iamareebjamal  I am new to this can you plz explain me what exactly to do in this issue ??

Read the issue description.
