### ISSUE TITLE
Improve Speed: Eliminate render-blocking resources

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5574]
According to the Google Page Speed test https://developers.google.com/speed/pagespeed/insights/?url=eventyay.com eliminating render-blocking resources oould improve the speed by 2 seconds. Please improve the speed by implementing the recommended changes as outlined in this article https://web.dev/render-blocking-resources/.

![Screenshot from 2020-11-11 10-45-14](https://user-images.githubusercontent.com/1583873/98796076-46714280-240b-11eb-9872-18d8d83867aa.png)

**Comment by iamareebjamal** [comment]
Same problem as #5575. And even worse part is that we have an SPA, so everything is loaded through JS, so we have little control over deferring the render blocking resources. 
If we could use rollup or webpack (like in React or Vue), it would have been somewhat doable, but still not as flexible as a handwritten server side rendered page. But we can't even do the webpack thing, cause ember...

**Comment by iamareebjamal** [comment]
And also, we have a JS rendered site, so there is no render to be blocked anyway. It's just a blank page. This is also only applicable generally for sites which are rendered on servers like https://www.newsgallery.com/
