### ISSUE TITLE
Improve Speed: Remove unused CSS

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5575]
According to the Google Page Speed test https://developers.google.com/speed/pagespeed/insights/?url=eventyay.com removing unused CSS could improve the speed by 2 seconds. Please improve the speed by implementing the recommended changes as outlined in this article https://web.dev/unused-css-rules.

![Screenshot from 2020-11-11 10-49-55](https://user-images.githubusercontent.com/1583873/98796437-a962d980-240b-11eb-9c4a-b03bb0be35c1.png)

**Comment by iamareebjamal** [comment]
Unfortunately that can't be done with ember. Ember bundles the entire application in a single JS file. So someone loading just a frontend page with a single line of JS or CSS will receive JS and CSS of every page and component. That can't be solved until we move to embroider (next generation ember bundler) which I try every month and is not ready yet, I tried just this morning.

**Comment by Raunaksingh100** [comment]
#  I am working on this issue plz don't make pr for this

**Comment by Raunaksingh100** [comment]
@iamareebjamal @mariobehling i found this files for unused css
![123](https://user-images.githubusercontent.com/65535360/98905120-e220b280-24e0-11eb-9543-92af7b15d4b4.PNG)

**Comment by swaaz** [comment]
@Raunaksingh100 @mariobehling Is this till open? because I am interested to work

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100 @mariobehling Is this till open? because I am interested to work

Go ahead !!

**Comment by naveen8801** [comment]
is this issue open ?? , can i work on it ?

**Comment by naveen8801** [comment]
@Raunaksingh100 @mariobehling  is this issue still open , i wanna work on it .
