### ISSUE TITLE
Improve Site Speed: Minify CSS

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5577]
According to the Google Page Speed test https://developers.google.com/speed/pagespeed/insights/?url=eventyay.com minifying CSS could improve the speed by 1.2 seconds. Please improve the speed by implementing the recommended changes as outlined in this article https://web.dev/unminified-css/

![Screenshot from 2020-11-11 10-54-40](https://user-images.githubusercontent.com/1583873/98797212-943a7a80-240c-11eb-98a1-8272f5a7ad1b.png)

**Comment by iamareebjamal** [comment]
That's probably wrong metric because our css is already minified but I'll check why is it showing it as unminified.

**Comment by mariobehling** [comment]
Ok, I see - this seems to be about the mobile page.

**Comment by iamareebjamal** [comment]
We don't bundle mobile and desktop CSS differently so that shouldn't be the case. The CSS is minified, maybe it's misreporting about sourcemaps which I have removed, but nothing else to be done
