### ISSUE TITLE
Call for Speakers: Event Showing Up on Frontpage even though CfS is deactivated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5578]
An event is listed in the section "Call for Speakers" on the front page even though the CfS of that event is deactivated. However, the event has speakers and sessions.

![Screenshot from 2020-11-11 11-05-06](https://user-images.githubusercontent.com/1583873/98798307-08c1e900-240e-11eb-93f8-83a49422b7c0.png)

**Comment by maze-runnar** [comment]
on it
