### ISSUE TITLE
Improve Site Speed: Reduce number of events on front page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5579]
The frontpage has a nice number of events. Unfortunately the front page is still relatively slow. Therefore please reduce the number of events shown on the front page as follows: 

- Featured Events: 6
- Upcoming Events: 12
- Call for Speakers: 6

Ensure to show a link "More events" at the end of a section if there are more events available in the category.

**Comment by sachinchauhan2889** [comment]
Working on this

**Comment by mariobehling** [comment]
Please check: There are differences loading the mobile and the desktop versions as well. Especially the mobile version has a lot of ways to be improved.

**Comment by cggvuhh** [comment]
@sachinchauhan2889 are you working on this issue ??

**Comment by sachinchauhan2889** [comment]
@cggvuhh yes
