### ISSUE TITLE
Orders/Tickets: Show different time to local event time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5590]
Generated tickets do not show the correct local time. Maybe they show GMT or it is unclear what time they show.

Download tickets through: https://eventyay.com/events/1f720482/tickets/orders/completed

![Screenshot from 2020-11-12 14-24-26](https://user-images.githubusercontent.com/1583873/98945490-dd64fa00-24f2-11eb-8d5b-508c7bc7f457.png)

Correct would be 1:30 PM to 5:00 PM
https://eventyay.com/e/1f720482

**Comment by mariobehling** [comment]
If possible show the timezone e.g. CET and make the date format in the way like Thursday, 19 Nov. 2020.

**Comment by iamareebjamal** [comment]
@mariobehling We're using this format `March 19, 2020 06:30 AM` on server everywhere

**Comment by mariobehling** [comment]
@iamareebjamal also good. Thank you!
