### ISSUE TITLE
Attendee Custom Form: No error message on some fields and changed order on live form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5602]
The attendee form has a few issues:
1. If a user does not enter required information some form fields do not show the red required field, e.g. Company, but also check all other fields, please.
![Screenshot from 2020-11-13 12-11-17](https://user-images.githubusercontent.com/1583873/99066628-8e2dd080-25a9-11eb-9896-8e1c05e61638.png)
2. The order of standard fields and custom form fields is changed, e.g. "Company" suddenly appears in between custom questions. (Please also test this with all other fields).
![Screenshot from 2020-11-13 12-09-54](https://user-images.githubusercontent.com/1583873/99066702-aa317200-25a9-11eb-9c88-350ef774bd2f.png)

**Comment by sachinchauhan2889** [comment]
Working on this

**Comment by Saumyachitransh01** [comment]
Working on this
