### ISSUE TITLE
Order Pages: Get rid of unsed spaces between boxes in templates of the order process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5603]
The order process has a number of templates that show spaces that are not fulfilling any needs between the boxes. Please take out those spaces in particular below the order summary. Check all pages in the order process and ensure the space do not appear anymore.

![Screenshot from 2020-11-13 13-21-35](https://user-images.githubusercontent.com/1583873/99071941-62afe380-25b3-11eb-839e-fe82c8453882.png)

**Comment by sachinchauhan2889** [comment]
Working on this. Please don't send pr
