### ISSUE TITLE
Country List in Forms show historic countries that do not exist today

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5604]
Please update the country list used in forms to only show countries that exist today.

Part of the issue is, that you research the list of countries that exist today or find a library that is up to date.

![Screenshot from 2020-11-13 13-25-13](https://user-images.githubusercontent.com/1583873/99072172-ccc88880-25b3-11eb-876a-457d42321fd3.png)

**Comment by sachinchauhan2889** [comment]
working on this

**Comment by iamareebjamal** [comment]
None
