### ISSUE TITLE
Order Forms: Acknowledgement text and button not suitable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5608]
Order only contains free tickets: 
* Text: Change text: By clicking "Pay Now", I acknowledge that I have read and that I agree with all the terms of services and privacy policy of Open Event. -> By clicking "Order Now", I acknowledge that I have read and that I agree with the [terms of services](https://eventyay.com/terms) and [privacy policy](https://eventyay.com/privacy-policy) on this website.
* add internal link to policies
* Button: Show "Order Now"

Order contains paid tickets (but it could additionally contain free tickets): 
* Text: By clicking "Pay Now", I acknowledge that I have read and that I agree with all the terms of services and privacy policy of Open Event. -> By clicking "Proceed to Checkout", I acknowledge that I have read and that I agree with the [terms of services](https://eventyay.com/terms) and [privacy policy](https://eventyay.com/privacy-policy) on this website.
* add internal link to policies
* Show Button "Proceed to Checkout"

![Screenshot from 2020-11-13 12-10-20](https://user-images.githubusercontent.com/1583873/99079718-99d8c180-25c0-11eb-9b7e-b5994552924e.png)

**Comment by sachinchauhan2889** [comment]
Taking this up

**Comment by Afzal-Ind** [comment]
@mariobehling Hi, could you take me through this link? Thanks.

**Comment by sachinchauhan2889** [comment]
@Afzal-Ind i am already working on this

**Comment by Afzal-Ind** [comment]
@sachinchauhan2889 Hi, I can see your comment. Keep it up. BTW no one is assigned yet. @iamareebjamal Hi, Could you help me get into this code? Thanks.

**Comment by iamareebjamal** [comment]
We don't assign external contributors

**Comment by Afzal-Ind** [comment]
> We don't assign external contributors

Fine Sir, I got you. But could you provide me with the link?

**Comment by Saumyachitransh01** [comment]
I'm taking this. @sachinchauhan2889 you're commenting on every issue consequently. So please submit your PR and leave the rest to the mentors.
