### ISSUE TITLE
Order Page and Ticket PDF Download: Show Location, Online Event, Mixed Event or To be Announced info correctly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5614]
On the order page there is currently only an "At" info for location based events. 
![Screenshot from 2020-11-13 22-02-15](https://user-images.githubusercontent.com/1583873/99121555-e3df9880-25fc-11eb-9693-bf960ddfb6c1.png)

Also on the ticket PDF the info is only available for location events or "none" is shown.
![Screenshot from 2020-11-13 22-09-46](https://user-images.githubusercontent.com/1583873/99121603-f78aff00-25fc-11eb-8187-b76c056d35a3.png)

Please update the area to show the information according to the event setting as follows:

* When an event has a location, show "At" and the location behind.
* When an event is an online event show "Online Event"
* When the event is a mixed event show "Event taking place online and at [location here]."
* When an event location or online details are "to be announced" show: "Location or online event details to be announced".

**Comment by sachinchauhan2889** [comment]
Working on this

**Comment by iamareebjamal** [comment]
Server Issue
