### ISSUE TITLE
Order Checkout Page: Move Paypal and "Pay Now" button below first right hand side box and expand 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5615]
The Paypal and Pay Now (Stripe) button are below the left hand box. 

Please change the location and design as follows:
1. Move the buttons below the first right hand box to the same location where the "Ticket Download" and "Invoice Download" are positioned on the completed order page.
2. Make the buttons to the same width as the box and increase the height a bit (but make it somewhat fit into the design still. Please experiment to make it look nicely.)
3. Ensure there are no white spaces (the completed order page does not have spaces between boxes, which is the way it should be).

Payment page
![Screenshot from 2020-11-13 22-17-45](https://user-images.githubusercontent.com/1583873/99122935-83058f80-25ff-11eb-8680-8a37cdc81e5a.png)

Completed order page
![Screenshot from 2020-11-13 22-29-04](https://user-images.githubusercontent.com/1583873/99123014-acbeb680-25ff-11eb-9309-2a0ec6b010ee.png)

**Comment by MeghalBisht** [comment]
I'm working on it, allow me a day to revert. Thanks
