### ISSUE TITLE
Order Page and Completed Order Page: Change "Go to event"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5616]
Event payment page and completed order page have a link "Go to event". Please change it as follows:

1. On event payment page, do not show "Go to event" anymore and delete the area where the links wha located. Basically, do not show an empty space there.

2. On the completed order page enhance it as follows:
    * add a website icon in front of text
    * Change "Go to event" to "Go to event page"

Order Page

![Screenshot from 2020-11-13 22-17-45](https://user-images.githubusercontent.com/1583873/99123522-9d8c3880-2600-11eb-93c3-1e0bc3a107ce.png)

Completed Order Page

![Screenshot from 2020-11-13 22-29-04](https://user-images.githubusercontent.com/1583873/99123520-9b29de80-2600-11eb-8c2e-7ea8249690ce.png)

**Comment by daretobedifferent18** [comment]
I am working on this issue
