### ISSUE TITLE
Replace momentjs by dayjs

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#5619]
Moment JS has stopped being maintained and is huge in comparison to alternatives (70 KB vs 2 KB). Even though date-fns would be a good choice considering it is tree shakable, but dayjs uses same API as moment and is just 2 KB so it will be easier to migrate to. It also uses modern browser data for timezone and such which makes it obsolete to bundle that data with JS, and most of our users use modern browsers.

Move to dayjs and remove moment from project. Ensure all components remain functional. Especially the date time pickers of event creation and schedule/session/event timings throughout the site

**Comment by codedsun** [comment]
Taking this up!

**Comment by iamareebjamal** [comment]
This is a huge task. Let other codeheat people take this up. There are many issues in server and you are more comfortable in server as well, whereas no codeheat participant is. So, it'd be better to take up server issues for now

**Comment by Soumi150** [comment]
I am working on this.

**Comment by RajSrinivasJena** [comment]
Can I Work on it ?

**Comment by Soumi150** [comment]
@RajSrinivasJena  I am already working on it.

**Comment by rithgan** [comment]
Can i work on this if no is assigned yet?
