### ISSUE TITLE
Investigate why application.hbs is not rendered while loading

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#5622]
Ember Routes have `model` hook which blocks rendering while it resolves. This gives ember apps the classic blank look the users stare at waiting while the API calls are happening. `application.hbs` is the main skeleton of an ember app which is shown first and `loading.hbs` is shown inside when the route is being loaded.

So, this is the order of things displaying and loading:

```
-> model hook in `application.js` starts processing
   -> model hook in `application.js` resolves
    -> `application.hbs` UI is shown to the user
    -> model hook in `index.js` starts processing
    -> `loading.hbs` is shown to the user
       -> model hook in `index.js` resolves
        -> `index.hbs` is shown in place of `loading.hbs` to the users
```

If there is no model hook in application.js, `application.hbs` with `loading.hbs` should be shown immediately to the user while `index.js` model resolves. See this for reference https://library-app.firebaseapp.com/libraries (code: https://github.com/zoltan-nz/library-app). Header, Footer and loader is immediately shown to the users. Compare it to https://open-event-frontend-36k6neerc.vercel.app/ :turtle: :snail: :sleeping: 

So, the first goal is to remove all processing/loading in `application.js` model hook. But even when I replaced all the API calls with dummy data, it was a blank screen instead of header, footer and `loading.hbs` being shown like in the link above. Investigate why is it different for open event and the site linked above

**Comment by cweitat** [comment]
Possible reason where frontend was checking if user was authenticated to had the perms before displaying the data

**Comment by cweitat** [comment]
Should not spend time fixing this as this is not affecting operations and focus on migration
