### ISSUE TITLE
Complete Order Page: Implement Per Ticket Download

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5623]
The complete order page currently shows a button "Download Tickets" for all tickets in an order. This is useful for many cases. However it might be difficult if e.g. a company representative gets tickets for a number of people and then wants to send them their specific ticket or if we want to share rights to access (permissions to) a specific ticket to another account in future.

Therefore please implement a per ticket download additionally to the "Download Tickets" (which downloads all tickets of an order).

Implement this as follows:
* In the "Order Summary SUCCESS" box add a column "Download Tickets" on the very right of the table
* Show a button Download for each ticket (If there are several tickets sold, we need several download buttons)
* Each download button should consist of two areas
  * a) an icon "Ticket" and 
   * b) the name of the ticket holder. 
* If there is more than one ticket in the ticket type then show several buttons with a Ticket icon and the name of the ticket holder. Example: The quantity of tickets sold is - two "Community Tickets", then show two Download buttons with a `Ticket icon and the name of the ticket holder`.
* Finally change the existing "Download Tickets" button to "All Tickets"

![Screenshot from 2020-11-13 22-29-04](https://user-images.githubusercontent.com/1583873/99123014-acbeb680-25ff-11eb-9309-2a0ec6b010ee.png)

**Comment by iamareebjamal** [comment]
Blocked on https://github.com/fossasia/open-event-server/issues/7397

**Comment by mariobehling** [comment]
**To be tested:** 
* When resolving resolving this issue, please check if the attendee information for different tickets and attendees shows up correctly here in the box "Ticket Holder's Information".

**Comment by daretobedifferent18** [comment]
I am working on this.

**Comment by daretobedifferent18** [comment]
I am working on this now
