### ISSUE TITLE
Order Page and Complete Order Page: Choose better icon for "Ticket Buyer Information"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5624]
The ticket buyer information uses the same icon as the ticket holder's information. Please find and implement a better suited different icon, maybe something related to money or payment?

![Screenshot from 2020-11-13 22-29-04](https://user-images.githubusercontent.com/1583873/99123014-acbeb680-25ff-11eb-9309-2a0ec6b010ee.png)

**Comment by MeghalBisht** [comment]
Taking this up, will update by today

**Comment by Saumyachitransh01** [comment]
If this isn't resolved yet. Can I submit my PR now?

**Comment by MeghalBisht** [comment]
> If this isn't resolved yet. Can I submit my PR now?

PR is still open for this issue, waiting for response from the moderators
