### ISSUE TITLE
Order Process Pages: Choose better icon for "Acknowledgement"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5629]
The icon for acknowledgement is the same as for ticket holder. Please find a better icon for acknowledgement in the order process form sepcifically.

![Screenshot_20201114-181302](https://user-images.githubusercontent.com/72552281/99147286-cadef200-26a5-11eb-9476-78dc1a932c50.png)
 Add this icon on order form also.

**Comment by Raunaksingh100** [comment]
#  I am working on this plz don't make pr for this
