### ISSUE TITLE
Organizer Ticket Sales Overview: Fix Sales Calculation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5631]
The calculation of the sales on past events is wrong. The numbers do not add up correctly and the sales have many number after the dot.

Even though events are old I assume that the calculation needs to be fixed as the same error could appear on new events. 

Please compare (access for admins only) https://eventyay.com/events/3689bc98/tickets

![Screenshot from 2020-11-15 04-17-31](https://user-images.githubusercontent.com/1583873/99162096-f1c71380-26f9-11eb-9e9a-2102ef6766e3.png)

**Comment by iamareebjamal** [comment]
We need to fix the formatting but the amount is correct

```
select sum(amount) from orders where event_id = 598 and status = 'completed';                                                                                                                                                     
+--------------------+
| sum                |
|--------------------|
| 14768.899999999998 |
+--------------------+
```
