### ISSUE TITLE
Completed Order Page: Change Invoice Icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5632]
Please use the linked icon for the Invoice button on the completed order page: https://fontawesome.com/icons/file-invoice?style=solid

![Screenshot from 2020-11-13 22-29-04](https://user-images.githubusercontent.com/1583873/99162119-423e7100-26fa-11eb-89b3-65a6bb0f1296.png)

**Comment by Gautam-Arora24** [comment]
Working on this

**Comment by Raunaksingh100** [comment]
@Gautam-Arora24 are you working on this if not can i fixed this issue.

**Comment by Gautam-Arora24** [comment]
@Raunaksingh100 I am working on this
