### ISSUE TITLE
Spam User: Not able to delete the account

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5633]
Sometimes some accounts make the effort to go through the entire process and create a spam entry, but it currently fails to delete these accounts right after an event was deleted.

Steps to take:
1. Delete an event that is associated with an event.
2. The event is moved to "Deleted Events" (but probably still associated with that account email)"
3. Try to delete the spam user, e.g. bakerwagon@gmail.com
- Error

When we delete an event, the deleted event should probably also be disassociated with an account. Maybe use an association "oldaccountemail.deletedevent"? Or some similar solution, because we still want to be able to re-instate the event in case it was deleted by error or someone hacked the account.

**Comment by iamareebjamal** [comment]
I don't think the event should be disassociated with the account because then it'll be impossible to know which user it was associated with. The failure to delete user is probably a logical error. If the event associated with the account has been deleted, it should be possible to delete it
