### ISSUE TITLE
Footer "Connect with us": Add icon and option for Weblate

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5635]
Please add another option to add a link to Weblate to the Footer. 

The link we want to use is https://hosted.weblate.org/engage/open-event/, but it should be configurable just like the other options in this footer area.

![Screenshot from 2020-11-15 11-17-07](https://user-images.githubusercontent.com/1583873/99182286-628b2180-2734-11eb-83a5-e84430febe46.png)

**Comment by sachinchauhan2889** [comment]
Taking this up

**Comment by snitin315** [comment]
@sachinchauhan2889 for reference you can check https://github.com/fossasia/open-event-frontend/pull/4974 & https://github.com/fossasia/open-event-server/pull/7243

**Comment by sachinchauhan2889** [comment]
@snitin315 thank you so much for references.
