### ISSUE TITLE
Ticket Invoice: Implement better design and add missing information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5636]
The ticket invoice is very basic and can be improved a lot. We already have an invoice for event owners. Therefore:
* Reuse the event owner template and implement it for ticket buyers. 
* Ensure to test this with the full information, e.g. in Wizard step 1 organizers have the option to enter company and tax information. Show this information on the ticket invoice

**Comment by daretobedifferent18** [comment]
I am working on this issue.

**Comment by sachinchauhan2889** [comment]
@mariobehling sir, do you mean 
- event owner invoice by this https://github.com/fossasia/open-event-server/blob/49d8f4da213708338654a780d1abb23981c56318/app/templates/pdf/event_invoice.html
- ticket invoice by this https://github.com/fossasia/open-event-server/blob/49d8f4da213708338654a780d1abb23981c56318/app/templates/pdf/order_invoice.html

**Comment by sachinchauhan2889** [comment]
> @mariobehling sir, do you mean
> 
> * event owner invoice by this https://github.com/fossasia/open-event-server/blob/49d8f4da213708338654a780d1abb23981c56318/app/templates/pdf/event_invoice.html
> * ticket invoice by this https://github.com/fossasia/open-event-server/blob/49d8f4da213708338654a780d1abb23981c56318/app/templates/pdf/order_invoice.

@iamareebjamal sir.

**Comment by iamareebjamal** [comment]
Yes

**Comment by sachinchauhan2889** [comment]
Taking it

**Comment by Creatoon** [comment]
@sachinchauhan2889 are you still working on this?

**Comment by sachinchauhan2889** [comment]
No
