### ISSUE TITLE
Joining the Organisation

### ISSUE THREAD

**Issue by akshatsood2249** [fossasia/open-event-frontend#5640]
I visited the homepage, it says you have to contribute to projects in order to join FOSS-ASIA. But recently I got to know about four to five people who are a member of FOSS-ASIA but have no prior activity before joining, is this via any sort of event or what? can someone please explain to me

**Comment by iamareebjamal** [comment]
Please use chat channel for questions, issue section is solely for code related bugs and feature discussion https://gitter.im/fossasia/open-event-frontend
