### ISSUE TITLE
Frontpage Tags not directing to filtered search page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5642]
Frontpage tags are currently not directing to any filtered search result. 

![Screenshot from 2020-11-15 14-22-28](https://user-images.githubusercontent.com/1583873/99186073-03d2a180-274e-11eb-8cf0-76e315b500fa.png)

**Comment by Gautam-Arora24** [comment]
Where should these tags redirect a user?

**Comment by iamareebjamal** [comment]
Issue Title: Frontpage Tags not directing **to filtered search page**
Issue Body: Frontpage tags are currently not directing to **any filtered search result**.

**Comment by madhur1846** [comment]
@mariobehling sir i am new to open source can you tell me more about this issue? (describe)

**Comment by RahulBansal123** [comment]
can i work on this?

**Comment by madhur1846** [comment]
> can i work on this?

Working on it

**Comment by Srijita007** [comment]
I want to work on this. Can i work on this issue?

**Comment by daretobedifferent18** [comment]
working on it
