### ISSUE TITLE
change the billing information icon which save as ticket icon 

### ISSUE THREAD

**Issue by cggvuhh** [fossasia/open-event-frontend#5645]
**Describe the bug**
change the icon of the billing information which is similar to ticket icon see in the screenshot for the better understanding.

**Screenshots**
![before](https://user-images.githubusercontent.com/68186540/99189762-d1926580-2788-11eb-9bfe-b06ccf582412.PNG)

**Comment by Raunaksingh100** [comment]
i am working on this
