### ISSUE TITLE
Pricing Page: Make it translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5647]
Make the pricing page part of the system and translatable. Compare: https://eventyay.com/pricing

![Screenshot from 2020-11-15 17-00-01](https://user-images.githubusercontent.com/1583873/99189927-050ec900-2764-11eb-93da-a442e24ec76d.png)

**Comment by RajSrinivasJena** [comment]
@mariobehling can I work on this ?
