### ISSUE TITLE
Wizard Step 1: Standardize spacing between sections

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5654]
There are different section on the wizard. The spacing is different between each section of the wizard and currently some sections are squeezed together very much. Please standardize the spacing between form topic sections in the wizard, e.g. date/time and description below etc. Ensure sections have some spacing in between.

![Screenshot from 2020-11-16 05-37-55](https://user-images.githubusercontent.com/1583873/99213625-5e134700-27ce-11eb-8399-ea0f002a97f3.png)

**Comment by Raunaksingh100** [comment]
I am working on this issue plz don't make pr for this thanks.
