### ISSUE TITLE
Mobile Event Page: Logo, Date, title not fully visible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5666]
Please implement a better handling of intro data on the top area on mobile pages.
![Screenshot_20201117_061533_com android chrome](https://user-images.githubusercontent.com/1583873/99349623-badd3300-289c-11eb-8354-ead551e4aaaf.jpg)

**Comment by purnima143** [comment]
@mariobehling  May I work on this?

**Comment by Raunaksingh100** [comment]
> @mariobehling  May I work on this?

Go ahead!!

**Comment by raj-singh-coder** [comment]
@mariobehling can I work on this issue to resolve it?
