### ISSUE TITLE
Organizer Orders Overview Page showing Given Name instead of Full Name, Also shows date 2 times on table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5668]
Please change the order page as follows:
* In the first column show full name instead of given name only
* take out the date and time in the first column (we already have it in the second column)

![Screenshot from 2020-11-17 10-21-33](https://user-images.githubusercontent.com/1583873/99371420-2afcb080-28bf-11eb-99cf-8f3b5c9abc9a.png)

**Comment by sachinchauhan2889** [comment]
taking this up
