### ISSUE TITLE
Organizers Attendees Overview Page: Adjust first column and move date

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5669]
Please change the organizer attendees overview page as follows:
* from the first column take out the emails "by someemail@gmailliosomething.com"
* move "Date and Time" from first column to its own column
* create a column for "Date and Time" between ticket name and ticket price
* take out the xx days ago

![Screenshot from 2020-11-17 10-33-44](https://user-images.githubusercontent.com/1583873/99372657-c4789200-28c0-11eb-8fde-0ffb715ca2b2.png)

**Comment by sachinchauhan2889** [comment]
taking this up
