### ISSUE TITLE
Wizard Step 1: Match color of activated "Event Types" boxes to other boxes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5675]
The event types boxes have a black color line when they are activated, while other boxes have a blue color.

Please match the event types boxes colors and style with the other boxes. While the timezone box has a blue line around the entire form area, the event types box only has a black line around the top area. Please change this.

Compare timezone
![Screenshot from 2020-11-17 15-12-28](https://user-images.githubusercontent.com/1583873/99400851-c4d85380-28e7-11eb-90c9-4af5888a9914.png)

Event types
![Screenshot from 2020-11-17 15-13-03](https://user-images.githubusercontent.com/1583873/99400845-c3a72680-28e7-11eb-9e44-3b7d8300b242.png)

**Comment by Alok-Singh-ops** [comment]
i wanna work on this issue. Please assgin this to me and since i am new to repo guide me

**Comment by iamareebjamal** [comment]
We don't assign issues and we don't have the bandwidth to guide individual contributors.

**Comment by iamareebjamal** [comment]
Copying message from pull request for contributors:

"That's a different component from semantic UI component because semantic UI component does not work with items with & in them. We'll have issues like #4546 if we revert to semantic UI dropdown"

**Comment by daretobedifferent18** [comment]
I am working on this

**Comment by daretobedifferent18** [comment]
@mariobehling we can't change it, we have limited options with which we can manipulate in PowerSelect Component.
every border in PowerSelect is linked with each other so changing any one will lead to change in border of entire component
