### ISSUE TITLE
Registration deadline not working

### ISSUE THREAD

**Issue by Saumyachitransh01** [fossasia/open-event-frontend#5692]
**Describe the bug**

Registration deadline not working
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to eventyay.com
2. Click on any event and place order
3. After 15 minutes of registration process, the clock shows 59:59 

**Expected behaviour**
It should show an alert message that order is cancelled
**Screenshots**

![Screenshot from 2020-11-19 12-43-20](https://user-images.githubusercontent.com/55341933/99650775-d81c2800-2a7b-11eb-9f22-07b7a844b65c.png)

**Comment by sachinchauhan2889** [comment]
Taking it up

**Comment by daretobedifferent18** [comment]
> Taking it up

I am already working on this bro pls can you take another one
