### ISSUE TITLE
Payment method icon need to change which is same as Ticket icon

### ISSUE THREAD

**Issue by cggvuhh** [fossasia/open-event-frontend#5693]
**Describe the bug**
The payment method icons need to change which is similar to ticket icon see in the screenshot for the better understanding

**Screenshots**
![1](https://user-images.githubusercontent.com/68186540/99661233-8e3a3e80-2a89-11eb-93a3-fa21f8f2672b.PNG)

**Comment by Raunaksingh100** [comment]
i am working on this issue can you provide
