### ISSUE TITLE
Wizard Step 5: Session Types appear like time instead of duration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5699]
In Wizard Step 5 the session tyes appear like time instead of duration. Please change this as follows:
* Change "Session Types" to -> "Session Types (duration, max. duration 24 hours)"
* The dropdown menu shows duration like times, e.g.. 23:00, it there a clearer way to show that this is about duration and not time of the day?

![Screenshot from 2020-11-20 15-39-23](https://user-images.githubusercontent.com/1583873/99813081-88a32e00-2b47-11eb-9761-900f9b688970.png)

**Comment by MeghalBisht** [comment]
Looking into this!

**Comment by MeghalBisht** [comment]
Can we change the dropdown to 2 inputs (type number) where the user can enter hours and mins himself. (as shown in the image below) as currently to choose 24 hours timing the user has to choose 00:00 which is not very clear.

![2020-11-21 (2)](https://user-images.githubusercontent.com/61330148/99871748-fbbdaa80-2c02-11eb-8b20-c61c22568599.png)

**Comment by mariobehling** [comment]
I am not sure, if this slows down the user if we have two fields. Could we change the format instead from e.g. 03:45 to 3.45 using a full stop and no leading 0 here?
