### ISSUE TITLE
Footer: Expand area below last footer line

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5705]
To make scrolling down and accessing the language switcher more comfortable, please expand the area below the last text and button line.

Try out maybe 30-40 px and see how it looks and feels.

![Screenshot from 2020-11-21 06-33-08](https://user-images.githubusercontent.com/1583873/99868556-c2b21580-2bc3-11eb-9197-a13cd203c2e7.png)

**Comment by Raunaksingh100** [comment]
I am working on this issue
