### ISSUE TITLE
Replace the <br> tags in 'event roles' and 'sytem-roles' with hidden dividers.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#571]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
There are <br> tags in code at event-roles.hbs and system-roles.hbs.

Expected:
We have a better way to do it by using hidden dividers in the semantic ui.

**Comment by sumedh123** [comment]
Working on this.

**Comment by niranjan94** [comment]
@sumedh123 is this really a priority right now ? It would better if you take up other things.
