### ISSUE TITLE
Event Dashboard: Sponsors box - number not correct

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5712]
The sponsors box on the event dashboard shows by default the number 10, but actually even if 10 is displayed it show 11. Expected: Whatever number to display is chosen, the number of sponsors should show up correctly in the box.

![Screenshot from 2020-11-22 11-08-09](https://user-images.githubusercontent.com/1583873/99900960-64646000-2cb3-11eb-919f-1cbb8ba47a7e.png)

**Comment by anjali1102** [comment]
@mariobehling  taking up this issue
