### ISSUE TITLE
Payment Gateways: Implement Sepa Direct using Stripe

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5717]
Stripe offers the Sepa Direct debit feature as described here https://stripe.com/docs/payments/sepa-debit. Singapore is eligible to use this feature. Please implement it a) for ticket buyers and b) for invoicing of organizers.

**Comment by saquib678** [comment]
Can I contribute to this issue?

**Comment by codedsun** [comment]
@saquib678 This has already been taken
