### ISSUE TITLE
Top Menu: Log out menu icon disappears in other languages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5721]
The logout icon disappears in other languages if the word is longer in some languages and depending on the resolution. Please ensure the icon shows up as normal even if the word is longer.

Question: How and where does the design needs to be changed to ensure this does not happen at other places?

![Screenshot from 2020-11-23 10-56-46](https://user-images.githubusercontent.com/1583873/99949158-e075ab00-2d7a-11eb-9746-f4144f141f9b.png)
![Screenshot from 2020-11-23 10-56-17](https://user-images.githubusercontent.com/1583873/99949164-e1a6d800-2d7a-11eb-8e36-9cf13ec0ce61.png)

**Comment by sachinchauhan2889** [comment]
taking it

**Comment by haritiwari4** [comment]
I want to work on this. ... please assign it to me ...
I am going to work on it

**Comment by aryamanprince** [comment]
I have sent a pr if this works fine please review.
