### ISSUE TITLE
Timezone Display shows numbers instead of timezone name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5749]
Some events display the timezone while others display e.g. (+08). Please change the implementation in a way that it always displays timezones correctly in all areas including on:
* Frontpage
* Events Dashboard
* Specific event dashboard
* Public event pages
* Admin pages

![Screenshot from 2020-11-25 09-30-27](https://user-images.githubusercontent.com/1583873/100202598-d16d3500-2f01-11eb-945e-2e809556476e.png)l a
![Screenshot from 2020-11-25 09-29-50](https://user-images.githubusercontent.com/1583873/100202599-d16d3500-2f01-11eb-92a4-9f9379d7d5bc.png)

![Screenshot from 2020-11-25 09-30-49](https://user-images.githubusercontent.com/1583873/100202594-d03c0800-2f01-11eb-96a8-2fd4fbac9a00.png)

![Screenshot from 2020-11-25 09-31-42](https://user-images.githubusercontent.com/1583873/100202591-ce724480-2f01-11eb-9c8e-f8b5813e0e0f.png)

**Comment by sachinchauhan2889** [comment]
taking it

**Comment by daretobedifferent18** [comment]
I am working on it.
