### ISSUE TITLE
Discount Codes: Simplify Form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5750]
Please simplify the discount of events as follows:

- Pre-fill "Number of discounted tickets" with "10"
- Change "Valid from" to "Discount valid from"
- Change "Expires on" to "Discount expires on"
- Show time in the same line with dates
- Show timezone of the event in the same way as in the wizard
- Take out "Show more options" switch and always show below option
- Take out "Status" and always make the status active

![Screenshot from 2020-11-25 11-30-48](https://user-images.githubusercontent.com/1583873/100216900-21082c80-2f13-11eb-9e38-d8c4a931c6a5.png)

**Comment by daretobedifferent18** [comment]
I am working on it.
