### ISSUE TITLE
Search Page: Reduce width of left side menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5754]
Please reduce the width of the left side menu on the search/explore page to match the left side menu of event pages. 

Compare
![Screenshot from 2020-11-25 16-02-21](https://user-images.githubusercontent.com/1583873/100245178-0b592e00-2f38-11eb-8b9a-0cac7bf6784a.png)

![Screenshot from 2020-11-25 16-05-51](https://user-images.githubusercontent.com/1583873/100245232-1ad87700-2f38-11eb-8eda-75bee9a2cd13.png)

![Screenshot from 2020-11-25 16-06-49](https://user-images.githubusercontent.com/1583873/100245390-49eee880-2f38-11eb-86b8-d6bf00ca9fd9.png)

**Comment by sachinchauhan2889** [comment]
Taking it up
