### ISSUE TITLE
Search Page: Add search filter "Images" to the left side menu and enable Image and Logo by default

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5756]
Please add filters for logo and image into the left side bar of the search page as follows:
* Add filter option "Images"
* Add filters "Image" and "Logo" as filter options (enabled means the search only shows outputs of events with images and logos)
* Enable "Image" and "Logo" by default

Also
* Additionally change the filter "Event Call for Speakers" to "Call for Speakers"

![Screenshot from 2020-11-25 16-26-48](https://user-images.githubusercontent.com/1583873/100248548-ea92d780-2f3b-11eb-9d3e-ea0bcff62229.png)

**Comment by MeghalBisht** [comment]
taking this up

**Comment by MeghalBisht** [comment]
Just wanted to confirm, we want to filter as shown in the image below?
![2020-11-26](https://user-images.githubusercontent.com/61330148/100284248-ec3cb980-2f94-11eb-9416-456dc4aef095.png)

**Comment by mariobehling** [comment]
@MeghalBisht Yes, correct. Thank you!
