### ISSUE TITLE
Discount Code: Take out feature "Set min/max quantity to purchase per order"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5759]
Looking at other event ticketing systems the feature "Set min/max quantity to purchase per order" does not seem to be available. We needed the feature in the past, but there are also other ways to get this kind of functionality as an organizer.

In order to simplify discount codes therefore, please take out this functionality from the form and allow users to order an unlimited number of discount tickets by default.

![Screen Shot 2020-11-26 at 00 03 54](https://user-images.githubusercontent.com/71120226/100268954-cfe05300-2f7b-11eb-8c0b-f628ca1efed5.png)

**Comment by JohnWesleyK** [comment]
I'd like to work on this

**Comment by daretobedifferent18** [comment]
I can work on this with the same PR #5758

**Comment by iamareebjamal** [comment]
Yes, please go ahead

**Comment by daretobedifferent18** [comment]
> allow users to order an unlimited number of discount tickets by default.

@iamareebjamal here I think it should also be always less then-No of the discount tickets provided?

**Comment by daretobedifferent18** [comment]
@iamareebjamal Pls close this issue.

**Comment by iamareebjamal** [comment]
Fixed in #5758
