### ISSUE TITLE
Schedule: Implement "Add to calendar" for a complete schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5760]
We already have the feature "Add to calendar" for the event times. Please also implement "Add to calendar" for events that have a dedicated schedule with sessions.

If the event has sessions with a schedule show two buttons instead of one in the "Add to Calendar" area on the right hand side:
1. On the left show a button with a calendar icon and "Event" (which is using the current implementation) as follows: 📅 Add Event
2. One the right show a button with a calendar icon and "Sessions" as follows: 📅 Add Sessions

Note: If the event does not have sessions, please show only one large button.

![Screenshot from 2020-11-25 20-37-35](https://user-images.githubusercontent.com/1583873/100274054-1626b980-2f5e-11eb-9032-1890e6b04bbe.png)

**Comment by iamareebjamal** [comment]
For implementers:

Without sessions (current): https://api.eventyay.com/v1/events/3689bc98.ics
With sessions: https://api.eventyay.com/v1/events/3689bc98.ics?include_sessions

**Comment by Draco9421** [comment]
i am working on it
