### ISSUE TITLE
Implement Feature "Synced Calendars" 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5761]
The calendar feature is currently working like an export calendar. This cannot be updated in case dates and times change. Therefore please implement the feature "synced calendars". Also keep the export option for the calendar as ics.

Only implement this feature after issue https://github.com/fossasia/open-event-frontend/issues/5760 has been resolved.

Compare how this feature is handled for example here https://ocs2020.sched.com/mobile-site

![Screenshot from 2020-11-25 19-01-10](https://user-images.githubusercontent.com/1583873/100273298-d7dcca80-2f5c-11eb-8beb-c67eb00de07a.png)

**Comment by iamareebjamal** [comment]
Eg: https://calendar.google.com/calendar/u/0/r?cid=http://api.eventyay.com/v1/events/3689bc98.ics?include_sessions
