### ISSUE TITLE
Schedule: Show date and time in left column

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5762]
Please change the schedule view as follows:
* Show Date and time in a column on the left 
   * Compare to website generator pages (ensure left column text is aligned with right column text)
   * Also compare to sched.com schedules e.g. https://ocs2020.sched.com/

When changing this feature please ensure that the design is consistent, e.g. pictures of speakers and names of speakers should be aligned.

![Screenshot from 2020-11-25 20-53-14](https://user-images.githubusercontent.com/1583873/100275464-42433a00-2f60-11eb-89f7-0bdc1f9e4918.png)

**Comment by daretobedifferent18** [comment]
I am working on it.
