### ISSUE TITLE
Creating session is not working just after session is deleted

### ISSUE THREAD

**Issue by nikolaytoplev** [fossasia/open-event-frontend#5765]
**Describe the bug**

If you click "Create Session" button just after deleting any session, you will get error page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to session listing tab
![image](https://user-images.githubusercontent.com/71332959/100277664-ddf79900-2fa6-11eb-85b5-cfb7979284b6.png)

2. Click delete button on any session and confirm deleting
3. Click "Create Session" button
4. Will see error page
![image](https://user-images.githubusercontent.com/71332959/100277973-6aa25700-2fa7-11eb-9e10-58f4c893f0e6.png)

and the following is console errors
![image](https://user-images.githubusercontent.com/71332959/100278078-9b828c00-2fa7-11eb-9b8a-7cb3181fb258.png)

**Desktop**
 - OS: Window 7 64bit
 - Browser: Chrome
 - Version: 87

**Comment by daretobedifferent18** [comment]
@mariobehling it working fine with me, I have checked on both local updated branch and event on official https://open-event-frontend.now.sh/, no error is giving, Pls let me know

**Comment by nikolaytoplev** [comment]
@daretobedifferent18 Did you follow the steps described in report correctly?
I am still getting the same errors on https://open-event-frontend.now.sh/.
![image](https://user-images.githubusercontent.com/71332959/100347890-73d40800-3029-11eb-8c42-caa7814572ec.png)

**Comment by daretobedifferent18** [comment]
Yes I tried again with proper steps and I am getting no error.

**Comment by maze-runnar** [comment]
@iamareebjamal I am not getting any error too. It's working fine.
