### ISSUE TITLE
Video: Implement an "Event Video Room" for events without lots of sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5769]
In our project we often focus on complex events with a lot of sessions. However there are also many events that only have one session and one room. Currently those events have to fill in a lot of details before they can use our new video feature. How can we make it easier for an event that does not have a lot of sessions?

My idea is we add a default "Event Video Room" in wizard step 1. This video room can then also show up in the video tab. Contrary to the session rooms and other microlocations organizers do not have to fill in tons of info now.

Please implement the details as follows:

1. On Wizard step 1 for Online and Mixed Event change 
       * "Webinar" to "Event Video Room"
       * add option to add "Jitsi Room" similar as in Video tab to the right of the form box for the video room link
       * add comment "Recommended for events without separate sessions."
       * move "Event Video Room" above "Live Stream URL"
       * change light gray color of text in front of boxes (Event Video Room and Live Stream URL) to black as other text

![Screenshot from 2020-11-26 00-36-20](https://user-images.githubusercontent.com/1583873/100292109-e092c800-2f7f-11eb-88bf-db50e9259328.png)

2. On public event page change "Webinar URL" to "Event Video Room"
       * for anonymous users and users without a ticket show text "The video room will be accessible for registered ticket holders of this event."
       * for ticket holders of this event show "Event Video Room: [Join Video Room]"
3. On event video tab if the user has filled in the information for "Event Video Room" in wizard step 1, show the room "Event Video Room" in the list.

**Comment by iamareebjamal** [comment]
For 3rd point, showing it in the list will be difficult as it is not linked to a microlocation, we can show it as a special item on top of the list

**Comment by mariobehling** [comment]
Yes, sounds good. Thanks.
