### ISSUE TITLE
Schedule: Add Date above sessions of the same date

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5773]
As you can see in the below screenshot the website generator has a heading above sessions of one date. Please implement the same in the eventyay version.

Add dates above sessions in the "by time" view. Do not show it when sessions are sorted by title.

![Screenshot from 2020-11-25 20-53-14](https://user-images.githubusercontent.com/1583873/100275464-42433a00-2f60-11eb-89f7-0bdc1f9e4918.png)

**Comment by daretobedifferent18** [comment]
I am working on it

**Comment by daretobedifferent18** [comment]
working on it
