### ISSUE TITLE
Schedule: Not needed comma if no position filled in by speaker

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5774]
On the schedule a comma and space show up even though they are not required. This happens if the speaker has not filled in a position. Expected no comma and space should show up if the speaker has not filled in a position. Equally if the speaker has not filled in a company no comma and space should show up.

Compare https://eventyay.com/e/3dbaaa50/schedule

![Screenshot from 2020-11-26 12-51-11](https://user-images.githubusercontent.com/1583873/100347884-634e6e00-2fe6-11eb-881d-1995adc460e5.png)

**Comment by Gautam-Arora24** [comment]
Working on this

**Comment by aryancse123** [comment]
Working on this bug
