### ISSUE TITLE
Wizard Step 1: Deleting Webinar URL results in error "not valid URL"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5779]
It seems it is not possible to delete a webinar or live stream URL. When an organizer tries to delete it and hits "Save" an error message "Not a valid URL" shows up.

Expected: It should be possible to delete these URLS as the field is not required.

Compare https://eventyay.com/events/fa96ae2c/edit/basic-details

![Screenshot from 2020-11-27 00-31-25](https://user-images.githubusercontent.com/1583873/100397081-434f9680-3048-11eb-83ff-b2c6e06bf62e.png)

**Comment by maze-runnar** [comment]
looking into it
