### ISSUE TITLE
Organizers Orders Dashboard: Show 0.00 instead of 0 for Sales

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5780]
Sales in orders should show 0.00 instead of 0 if the income of sales has been zero.

![Screenshot from 2020-11-27 09-38-57](https://user-images.githubusercontent.com/1583873/100428706-98b19500-3094-11eb-8a72-b04f4f1459ea.png)

**Comment by MeghalBisht** [comment]
working on it

**Comment by daretobedifferent18** [comment]
Go ahead
