### ISSUE TITLE
Organizer Orders Overview: Paid Donation Tickets show up as zero

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5781]
Paid donation tickets do not show up on the orders overview page. The calculation of tickets sales works correctly. However the donation tickets show 0 in the table.

Compare https://eventyay.com/events/3dbaaa50/tickets

![Screenshot from 2020-11-27 12-14-13](https://user-images.githubusercontent.com/1583873/100443610-51360380-30aa-11eb-820d-7135e9fb0c7f.png)

**Comment by sachinchauhan2889** [comment]
looking into this
