### ISSUE TITLE
Public Schedule: Move session description display to "expanded area"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5783]
The session description currently shows up already in the default view. Please move the description to the expanded area as in the website generator.

Compare https://eventyay.com/e/1f720482/schedule
![Screenshot from 2020-11-27 16-18-48](https://user-images.githubusercontent.com/1583873/100463530-48562980-30cc-11eb-8cb2-f25992265dc3.png)

Compare Website Generator
![Screenshot from 2020-11-27 16-12-28](https://user-images.githubusercontent.com/1583873/100463449-22c92000-30cc-11eb-86f0-613d94221705.png)

**Comment by sachinchauhan2889** [comment]
Taking it up
