### ISSUE TITLE
Public Schedule Page: Make Social Links into Icons and Moce Date/Time, Social Icons and Links to Top Right Menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5785]
Date/time, social links and web links are currently below the tracks and session filters, which is not perfect. Also design can be made more clearer. Please change this as follows:
1. Move date/time, social links, web links to top right side area (but not the twitter box itself) on schedule pages
2. Change social links into square boxes similar to sched (compare https://ocs2020.sched.com/). Also ensure it works if we have many social links, e.g. if there are too many that do not fit on one line it should go over two lines.
3. Keep website links as is 
4. Also test this works well on mobile

Current implementation, e.g. here https://eventyay.com/e/1f720482/schedule
![Screenshot from 2020-11-27 17-57-01](https://user-images.githubusercontent.com/1583873/100471555-cde0d600-30da-11eb-8ffd-c12b6b1c8e6a.png)

Compare to sched
![Screenshot from 2020-11-27 17-55-41](https://user-images.githubusercontent.com/1583873/100471556-ce796c80-30da-11eb-88be-4fe30df7d64b.png)

**Comment by sachinchauhan2889** [comment]
taking it up
