### ISSUE TITLE
Public Schedule: Enhance Session Tile Area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5787]
The session tile has some issues and some items look a bit out of place, especially when there are several speakers. Therefore please make the following changes:

- Move track above "microlocation" on the right-hand side of the session info
- In front of track use a track icon
- Reduce the indent of the right-hand side area a bit to show longer text without line break
- Align speaker image and speaker name properly (currently not aligned)
- Ensure speaker images and speaker names are nicely portrayed even when there are several speakers
- Ensure it works on mobile as well

Compare https://eventyay.com/e/8fa7fd14/schedule
![Screenshot from 2020-11-27 19-01-11](https://user-images.githubusercontent.com/1583873/100475597-d4278000-30e3-11eb-99c4-bf4d9ad03b1d.png)

![Screenshot from 2020-11-27 19-09-07](https://user-images.githubusercontent.com/1583873/100475689-0e911d00-30e4-11eb-9920-10d56fe5d200.png)

An example of a track icon
![Screenshot from 2020-11-27 18-06-25](https://user-images.githubusercontent.com/1583873/100475876-7cd5df80-30e4-11eb-9f65-e704b92bee96.png)

**Comment by daretobedifferent18** [comment]
working on it.
