### ISSUE TITLE
My Schedule Page: Show two areas a) My Speaker Sessions b) My Schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5788]
On the my schedule page there should be two areas. Please implement them as follows:
1. My Speaker Sessions
2. My Schedule

Style-wise please use the existing styles of session tiles.

Below an example of "My Speaker Sessions"

![Screenshot from 2020-11-27 19-22-41](https://user-images.githubusercontent.com/1583873/100476472-f5896b80-30e5-11eb-82ab-bfced5168905.png)

Below is an example of "My Schedule". 

![Screenshot from 2020-11-27 19-21-38](https://user-images.githubusercontent.com/1583873/100476437-d8549d00-30e5-11eb-8780-33b39278165d.png)

**Comment by iamareebjamal** [comment]
What's the difference? Is `My Speaker Sessions` sessions of the logged in users? And `My schedule` the sessions which the user set as favourites?

**Comment by mariobehling** [comment]
My speaker sessions are the sessions in that event that the user is giving him/herself.
My schedule shows all sessions that the user has chosen to attend (but does not give a talk his/herself).
