### ISSUE TITLE
My Schedule Page: Show Personal Profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5789]
How to show the personal profiles and what options do we need?

1. Please show the personal profile of attendees on the my schedule page. 
2. The personal profile is stored here https://eventyay.com/account/profile. Please add a switch on this page to show or not to show the profile publicly.
![Screenshot from 2020-11-27 19-31-03](https://user-images.githubusercontent.com/1583873/100476952-42ba0d00-30e7-11eb-9ddd-dc14106500cd.png)
3. Speakers can have a dedicated speaker profile that they add when they fill in the details for the event. Below the personal profile please show the speaker profile as stored in the speaker submissions. Speakers do not have the option to make speaker profiles public or private as organizers are taking care of that.

![Screenshot from 2020-11-27 19-32-53](https://user-images.githubusercontent.com/1583873/100476989-5bc2be00-30e7-11eb-91db-f1110d832555.png)

**Comment by iamareebjamal** [comment]
> Below the personal profile please show the speaker profile as stored in the speaker submissions

All the speaker profiles linked to a user?

**Comment by mariobehling** [comment]
I thought they usually would be linked to the speaker submitting a session. Exception is if the speaker profile is added by an organizer.

**Comment by iamareebjamal** [comment]
Yes, was just clarifying that you meant to show all the speaker profiles submitted by the user
