### ISSUE TITLE
Unable to do a successful yarn install

### ISSUE THREAD

**Issue by sansyrox** [fossasia/open-event-frontend#5790]
**Describe the bug**
When I do a yarn install, I am getting the following error. `paypal checkout` library is giving an error log.

```
. [Bundler][BABEL] Note: The code generator has deoptimised the styling of /Users/sanskar/Desktop/open-event-frontend/node_modules/paypal-checkout/dist/checkout.lib.js as it exceeds the max of 500KB.
ENOENT: no such file or directory, scandir '/var/folders/lw/c2m0klj136df8qccj96fz7580000gn/T/broccoli-63530oDIg4yO066Y9/out-943-broccoli_merge_trees/assets/locales'

```

**To Reproduce**
Steps to reproduce the behaviour:
1.  Clone the repo
2. `yarn install`
**Expected behaviour**
Yarn install should work

**Desktop (please complete the following information):**
 - OS: OSX 
 - Browser Chrome

**Comment by iamareebjamal** [comment]
Please use gitter channel for questions. You have missed a step in the setup process, see the video. And this is not yarn install step, it is yarn start
