### ISSUE TITLE
Team box and page: Show "organizer" with first letter in capital

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5793]
The "organizer" role is not starting with a capital in contrast to the Owner role. Please standardize this and show "Organizer" with a capital too on the event dashboard team box and teams page.

![Screenshot from 2020-11-27 21-02-03](https://user-images.githubusercontent.com/1583873/100481408-5029c400-30f4-11eb-8164-837cf4d5e446.png)
![Screenshot from 2020-11-27 21-01-37](https://user-images.githubusercontent.com/1583873/100481413-515af100-30f4-11eb-9642-37d027fcf209.png)

**Comment by iamareebjamal** [comment]
It's actually opposite, all roles are lowercase in database, only `Owner` is with capital `O`. God knows why? As roles are keywords, they should not be capitalized. Frontend should map the keyword with display name and show that instead.

So, please create a migration in database to change `Owner` to `owner` and change for new role creations as well. And then display proper names in frontend by mapping keywords to display names

**Comment by nlok5923** [comment]
@mariobehling please can i work on it.

**Comment by iamareebjamal** [comment]
Go ahead, just claim an issue and start working on it. If no one is working on it currently, you can always work on it without asking

**Comment by gunjan543** [comment]
I want to work on this

**Comment by inayahassan23** [comment]
i would like to work
