### ISSUE TITLE
Teams Permission Page: Make all areas translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5794]
Seems like the teams permission page of events is not fully translatable yet.

![Screenshot from 2020-11-27 21-02-49](https://user-images.githubusercontent.com/1583873/100481476-75b6cd80-30f4-11eb-8c24-e7e8df4c49bb.png)

**Comment by MeghalBisht** [comment]
working on this

**Comment by SushantAA** [comment]
In  the PR it has no Reviewers :upside_down_face:
