### ISSUE TITLE
Change general-date helper timezone argument

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#5795]
Current general date helper takes timezone as a positional argument, which was chosen to ensure devs pass event timezone always because they didn't in moment format and it displayed wrong time.

But as it is being used in other places where event timezone does not make much sense, like in event sales or order time, it requires empty string to be passed as timezone, which is ugly and unnecessary as it occurs before the format, it cannot be left as is.

Please change timezone to keyword argument, like `{{general-date date tz=timezone}}`

Which will be optional, so invocation without timezone will look like `{{general-date date}}`

**Comment by daretobedifferent18** [comment]
working on it.
