### ISSUE TITLE
Change general-date helper format argument

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#5796]
Most of the formats passed to general-date are now standardized. There is no need to pass big repeated formats, it there are 3-4 of those. So, format argument should accept certain keywords and resolve them to formats, like `{{general-date date 'dd MM YYYY HH:mm (z)'}}` should be treated same as ``{{general-date date 'date-time-long'}}``

This will also make changing specific formats easier in future.

If the passed in format is not a known keyword, it'll be treated as literal format. And format will be optional, with the most used format being the default

**Comment by daretobedifferent18** [comment]
Working on it

**Comment by daretobedifferent18** [comment]
working on it
