### ISSUE TITLE
Public Schedule: Enhance Speaker Display

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5797]
The speaker display is a bit mixed up. Please change the speaker display as follows, also ensure it works on mobile views:

See current display.

![Screenshot from 2020-11-27 21-21-07](https://user-images.githubusercontent.com/1583873/100482308-4e153480-30f7-11eb-8489-da67a0eef1bc.png)

Change to a display like the following. Also test it with several speakers.

![Screenshot from 2020-11-27 21-21-07a](https://user-images.githubusercontent.com/1583873/100482306-4a81ad80-30f7-11eb-840e-3236ce84f933.png)

**Comment by Vishuanttal1** [comment]
Hey i can do it please assign to me and i'm new to repo please guide me through

**Comment by iamareebjamal** [comment]
We don't have the bandwidth to guide individual contributors, and we don't assign issues to external contributors
