### ISSUE TITLE
Improve UI and avoid overflow of tweets on event page.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#58]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![overflow-issue](https://cloud.githubusercontent.com/assets/17925669/26219368/596d0470-3c2c-11e7-8a1b-c60fc65cd78e.png)
![center](https://cloud.githubusercontent.com/assets/17925669/26219469/bb8ea5be-3c2c-11e7-8846-80e3a5429d8b.png)

**Expected behavior:**

1) The tweets should be visible thoroughly.
2) For medium screen sizes, the images of speakers are not centered.

**Comment by niranjan94** [comment]
@CosmicCoder96 

for medium sized screens, show two images per row
