### ISSUE TITLE
Organizer Orders Page: Instead of showing currency with Sales($) show it with the number

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5801]
1. If there are sales show the currency with the number e.g. $ 1453.88 on the tickets/orders overview page of events instead of putting it next to "Sales".
2. Also in the table, we do not need to have the currency in the table heading. Instead add the currency in front of the number. Take out currency from "Total Sales". Add the currency into the table below.

![Screenshot from 2020-11-28 01-08-19](https://user-images.githubusercontent.com/1583873/100489738-7bbda600-3116-11eb-8fde-1f03909e9e46.png)

**Comment by daretobedifferent18** [comment]
working on it.
