### ISSUE TITLE
Search: Allow search of "Past" events and add the option "Past" into the filters

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5802]
The search only seems to allow searching future events. Please add the option "Past" as a filter.

![Screenshot from 2020-11-28 01-18-13](https://user-images.githubusercontent.com/1583873/100489922-b8d66800-3117-11eb-8015-352f86899e45.png)

**Comment by Vishuanttal1** [comment]
Hey please i wanna work on this feature. please assign this to me and as i'm new so please guide me through

**Comment by daretobedifferent18** [comment]
Go ahead :+1:

**Comment by sachinchauhan2889** [comment]
taking this up

**Comment by MeghalBisht** [comment]
> taking this up
I have a PR opened for this, can you see it once?
