### ISSUE TITLE
Implement formatting localized currency correctly in different languages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5807]
Currencies are formatted differently in different countries and languages. Some background information is here for example https://polaris.shopify.com/foundations/formatting-localized-currency

For a user that does not pay attention in German e.g. 12.50 EUR could mean 1250 Euro as twelve Euro and fifty Cents is written as 12,50 EUR in German and French.

Is there a suitable library that we could use?

Please implement this for all currencies.

**Comment by iamareebjamal** [comment]
`(1234.56).toLocaleString("de", {style: "currency", currency: "EUR", minimumFractionDigits: 2})`
"1.234,56 €"

(1234.56).toLocaleString("en-US", {style: "currency", currency: "EUR", minimumFractionDigits: 2})
"€1,234.56"

**Comment by daretobedifferent18** [comment]
working on it

**Comment by daretobedifferent18** [comment]
@iamareebjamal we can also use Intl.NumberFormat
```javascript
const number = 123456.789;

new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(number);
// expected output: "123.456,79 €"

// the Japanese yen doesn't use a minor unit
new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(number);
// expected output: "￥123,457"

// limit to three significant digits
new Intl.NumberFormat('en-IN', { maximumSignificantDigits: 3 }).format(number);
// expected output: "1,23,000"
```
Pls let me know by which approach I should go

**Comment by iamareebjamal** [comment]
It's the same thing, go with anyone which has more browser support

**Comment by daretobedifferent18** [comment]
@iamareebjamal what I found is using navigator.language but it always give en-US to get locale from browser

**Comment by iamareebjamal** [comment]
If you change your browser settings, it will change

**Comment by iamareebjamal** [comment]
You can also check `Intl.NumberFormat().resolvedOptions().locale`

**Comment by daretobedifferent18** [comment]
> You can also check `Intl.NumberFormat().resolvedOptions().locale`

@iamareebjamal 
I have tried with this, it is also giving en-US so I have a question, changing browser setting may result in diff result but then if I implement this approach then do user also have to change their browserLanguage setting or it will work fine for them?

**Comment by iamareebjamal** [comment]
Yes, it depends on browser language. Use this approach - Use detected locale using resolved options, if it is en-US, then map l10n detected locale to valid locale like de to de-DE

**Comment by iamareebjamal** [comment]
Follow up in remaining places
