### ISSUE TITLE
Language Dropdown Menu: Sort according to locale and increase height

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5808]
The language menu has a confusing sorting order, e.g. Hindi is on the top even though it would be sorted under H in Latin alphabets or further down when sorting according to characters.

Please sort languages according to locales. More background info is here https://u.uniface.info/docs/0907/uniface/proc/lists/localBasedSorting.htm

Also increase the height of the dropdown a bit to make it easier to use. The user should require less need for scrolling. Ensure it works on mobiles.

![Screenshot from 2020-11-28 09-10-19](https://user-images.githubusercontent.com/1583873/100497327-13dd7e80-315b-11eb-8464-737466f2c3d2.png)

**Comment by iamareebjamal** [comment]
That's Bangla, not Hindi. Hindi is below French in correct position. We have used Wikipedia sorting order as requested by you previously https://www.wikipedia.org

/

**Comment by mariobehling** [comment]
Ok, I was confused, cause Bahasa Indonesia is somewhere in the middle. So, it seems it is sorted according to "I" like Indonesia. Wikipedia also changed their way in the meantime and does not seem to be as consistent as before anymore. So, I am wondering if there is a more standard way.

**Comment by AdityaArunSharma** [comment]
@mariobehling is this still open? Can it be assigned to me?
