### ISSUE TITLE
Enhance Location and Map Feature by Switching to OSM and Mapbox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5810]
Maps are shown using Google Maps currently. As we are trying to get away from Google as a proprietary map tool that collects data of our users we need OpenStreetMap and Mapbox as alternatives. Please implement these services and switch to OpenStreetMaps or MapBox depending on the key provided at runtime.

The following flow is implemented and should work after the map has been changed:
A) For the Organizer and Attendees
1. User add an address
2. User can preview the map location and adjust it if if necessary
3. User saves the changes
4. Map and address is displayed on the public event page + Map and address is displayed on search pages

B) For Admins
1. Admin adds a key of OSM and Mapbox into the settings page of the admin area
2. Saves the details
3. System uses map solution as provided by admin

Please see the following link for relevant documentation: https://miguelcobain.github.io/ember-leaflet/docs/adding-layers
The outlined solution supports both OSM and MapBox. MapBox WebGL is cheaper than layers approach, but OSM is free. So, the better option is to go for leaflet first and add MapBox WebGL as an additional more powerful solution.

Therefore please implement maps and locations as follows:
- [ ] for user maps in "Create Event" - Wizard step 1, see https://eventyay.com/create
- [ ] show OSM/mapbox for locations on public event pages, e.g. https://eventyay.com/e/fa96ae2c
- [ ] show OSM/mapbox on search pages that use a location, see https://eventyay.com/explore
- [ ] provide an option to add a key for the service in the admin page at https://eventyay.com/admin/settings

As part of this issue 
* [ ] please take out the Google map code from the project and ensure there are no console errors.
* [ ] Where necessary open issues and make changes on the open event server.

![Screenshot from 2020-11-28 12-29-42](https://user-images.githubusercontent.com/1583873/100514486-69bf2000-3175-11eb-98a5-1a0d1c35086f.png)

**Comment by iamareebjamal** [comment]
More info: #591 and #3564

**Comment by iamareebjamal** [comment]
For now, we will implement switching according to environment variables in frontend because it is easier to implement than to do in settings and this is how it is currently done for Google Maps. Also, it is needed at build time of the frontend app to inject in config. Later, we can make it switchable through server by exploring a solution

**Comment by maze-runnar** [comment]
>  we will implement switching according to environment variables in frontend

I am not understanding it.

**Comment by iamareebjamal** [comment]
First, just implement OSM

**Comment by maze-runnar** [comment]
ok

**Comment by mariobehling** [comment]
Google maps is still there. Compare https://eventyay.com/e/fa96ae2c

Therefore re-opening it.
