### ISSUE TITLE
Public Schedule: Expanded session info - add position and organization, hide top profile icon and details on top when expanded

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5817]
Some information is repeated in expanded sessions. The website generator hides some info on expanding sessions. Please implement something similar on the frontend. Compare http://2019.fossasia.org/event/schedule.html

Make changes as follows:
* When session is expanded hide profile image, name, designation and org on the top area
* Leave session info on top area as is
* On the expanded area show position and organization below the speaker name without brackets

Compare https://eventyay.com/e/8fa7fd14/schedule
![Screenshot from 2020-11-29 00-56-08](https://user-images.githubusercontent.com/1583873/100528559-a1ae7d80-31de-11eb-9b85-7483c4d12388.png)

**Comment by daretobedifferent18** [comment]
working on it
