### ISSUE TITLE
Public Schedule: Show "Download Slides/Link to Slides" button instead of link on expanded session

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5818]
The expanded session currently shows a link to slides if they have been added. Please change the feature as follows:
1. If the speaker uploaded slides show a button "Download Slides". Also include an icon in the download button.
2. If the speaker has only linked to the slides show a button "Link to Slides". Also include a link icon as part of the button.

Compare https://eventyay.com/e/8fa7fd14/schedule
![Screenshot from 2020-11-29 01-05-47](https://user-images.githubusercontent.com/1583873/100528772-92303400-31e0-11eb-951e-038ab7694cc2.png)

**Comment by daretobedifferent18** [comment]
working on it

**Comment by daretobedifferent18** [comment]
@mariobehling actually this link is been added in short Abstract and not in Slide url

**Comment by mariobehling** [comment]
@daretobedifferent18 You are right, but this session has both a) the link in the description and b) the slide itself. There is a button on the session page itself. See here https://eventyay.com/e/8fa7fd14/session/6341

This button needs to be shown on the overview sessions page as well and moved to a more prominent place. I think a good position would be on top as in the below screenshot.

![Screenshot from 2020-11-29 01-05-47](https://user-images.githubusercontent.com/1583873/100539893-e0255600-3239-11eb-962e-f4e320da4f82.png)

**Comment by daretobedifferent18** [comment]
Ok I got it.
