### ISSUE TITLE
Speakers Form/Public Schedule: Implement option to add several files for slides

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5820]
The speakers form currently has the option to upload or link one slide. Organizer feedback is that speakers in some events have several files to share. Therefore please implement the option to add or link several files and provide a field to indicate some details about the file or link.

Implement this as follows:
* Show a field to add a "Name" and field to add a link or upload a file in the speakers form (similar to now)
* In the public schedule show a download button with a dropdown function that displays the slide files or links

![Screenshot from 2020-11-29 10-08-17](https://user-images.githubusercontent.com/1583873/100537910-abf76880-322c-11eb-8f2e-582ccb112143.png)

**Comment by yash345-spec** [comment]
hey , i wanna assign on this work.  i wanna do this.
