### ISSUE TITLE
Public Schedule: Implement search feature

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5822]
The public schedule does not have a search feature yet. Please add a search box to the right of the sort by menu item. Implement a search feature using pattern matching. Search across name, title, description, track, room, company, position.

![Screenshot from 2020-11-29 10-54-49](https://user-images.githubusercontent.com/1583873/100538817-3c847780-3232-11eb-8514-7337dff6451c.png)

**Comment by maze-runnar** [comment]
on it
