### ISSUE TITLE
Sponsor logos disappear 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5827]
I added 24 logos into [techcul eventyay page](https://eventyay.com/events/ae73f280). It showed 24 logos in the sponsor section of the overview page, but when I clicked Edit, it only showed 15 logos in the edit page and 15 logos on the main eventyay page. Please compare below 

**1. Sponsor section in the Overview tab**

- 24 logos
- Compare https://eventyay.com/events/ae73f280

**2. Edit sponsor page**

- 15 logos
- Compare https://eventyay.com/events/ae73f280/edit/sponsors

![Screenshot from 2020-11-29 21-53-57](https://user-images.githubusercontent.com/1658742/100553348-e0e7d780-328d-11eb-9c50-ae48a918ae65.png)

**3. Event main page**

- 15 logos
- Compare https://eventyay.com/e/ae73f280:

![Screenshot from 2020-11-29 21-53-27](https://user-images.githubusercontent.com/1658742/100553349-e1806e00-328d-11eb-9ae2-40128d8987db.png)

**Desktop**
 - OS: Ubuntu 18.04, Chrome

**Comment by daretobedifferent18** [comment]
working on it
