### ISSUE TITLE
Attendee Form: Implement "Short Answer" and "Paragraph"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5832]
Currently the attendee form has an option "text" as field option. Please separate this functionality into two options:
* Short Answer which should show a online field to enter information
* Paragraph which should show a text box to enter information in several lines (similar to Google Forms)

![Screenshot from 2020-11-30 10-41-11](https://user-images.githubusercontent.com/1583873/100593780-1675da80-32f9-11eb-8b8a-d11105149827.png)

**Comment by davedevelopers** [comment]
I want to add this feature

**Comment by SARTHAK1SINGH** [comment]
I would like to work on this issue.

**Comment by SARTHAK1SINGH** [comment]
I am working on it.

**Comment by gunjan543** [comment]
I want to work on this issue

**Comment by mharshita** [comment]
Working on this...
