### ISSUE TITLE
Speaker Edit Form: Organizer is unable to edit speaker info 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5841]
Log in as organizer to edit speaker info, an error message appeared. 

**To Reproduce**
1. Go to 'https://eventyay.com/events/ae73f280/speakers/4998/edit'
2. Add position data
3. Click save
4. See error > bottom right 

![Screenshot from 2020-11-30 21-57-14](https://user-images.githubusercontent.com/1658742/100664275-aba7bc00-3357-11eb-80ec-b9ab389cf70a.png)

**Comment by maze-runnar** [comment]
will be fixed by https://github.com/fossasia/open-event-server/pull/7469

**Comment by hpdang** [comment]
@maze-runnar any update on this one?

**Comment by maze-runnar** [comment]
there is only one thing remaining in pr that is because of that change is not working as expected, so @iamareebjamal is testing it.

**Comment by hpdang** [comment]
This worked for me now. Thanks @maze-runnar @iamareebjamal :+1:
