### ISSUE TITLE
Event Dashboard: Reduce max height of sponsor logos to 40px

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5844]
Max with and height of sponsor logos is 80px at the moment. Please reduce max height of a sponsor logo to 40px to make the usage of space on the dashboard more efficient.

Please take care not to scale a logo out of proportion.

![Screenshot from 2020-12-01 12-17-00](https://user-images.githubusercontent.com/1583873/100734191-8eaecf80-33cf-11eb-98b1-dd1c2a91b39b.png)

**Comment by parmeshwar1807** [comment]
can I take up this issue?

**Comment by mariobehling** [comment]
Yes, go ahead.

**Comment by ksraj123** [comment]
This is how the event dashboard looks to me, can't find the tabular paginated sponsor's section anywhere as in the image you shared. Also, the dimensions for the images for me is 250px by 250px. I am development branch.

Did the image you shared meant to show what this should look like?

<img width="1759" alt="Screenshot 2020-12-02 at 1 31 54 AM" src="https://user-images.githubusercontent.com/39027928/100790758-4975b680-343e-11eb-8311-a30018e5d95a.png">

Thanks

**Comment by sachinchauhan2889** [comment]
> This is how the event dashboard looks to me, can't find the tabular paginated sponsor's section anywhere as in the image you shared. Also, the dimensions for the images for me is 250px by 250px. I am development branch.
> 
> Did the image you shared meant to show what this should look like?
> 
> <img alt="Screenshot 2020-12-02 at 1 31 54 AM" width="1759" src="https://user-images.githubusercontent.com/39027928/100790758-4975b680-343e-11eb-8311-a30018e5d95a.png">
> 
> Thanks

this is not event dashboard. 

for event dashboard
creat a event then
click on __manage events__ in drop down at right top of front page.
then click on event dashboard button.

url will be localhost:4200/events/:event_id

**Comment by gunjan543** [comment]
I wanted to work on this issue , and while going through the code I realised logo images have height 250 and not 80, please guide me if I am wrong.

**Comment by iamareebjamal** [comment]
Logo images can have any height and width

**Comment by gunjan543** [comment]
> Logo images can have any height and width

![Screenshot from 2020-12-03 09-42-18](https://user-images.githubusercontent.com/52042648/101012988-a336c780-3589-11eb-9d2f-09cdf0860ee7.png)
I wanted to ask that in this code snippet from oven-event frontend project , there is 250px height and width , and in the issue it is specified 80px,so am I proceeding in wrong direction?

**Comment by iamareebjamal** [comment]
Issue is about organizer section, not public event page

**Comment by gunjan543** [comment]
okay! Thankyou for helping me out

**Comment by SARTHAK1SINGH** [comment]
I would like to work on this issue.

**Comment by mariobehling** [comment]
https://github.com/fossasia/open-event-frontend/pull/5898#issuecomment-739323550
