### ISSUE TITLE
One-click event sign up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5850]
For free events platforms such as meetup have a nice feature which could be described as one-click signup. When a user receives an email for a new event they can simply click on "Sign up" or "Yes". Then they are directed to the sign up page and simply click "Confirm" and they are registered.

Please implement this as follows:
* In ticket options add "Registration" as an additional option (apart from free, donation, paid tickets)
* When the user chooses "Registration" open a pop up "If you choose this option other ticket options will not be available. Do you want to proceed? Yes / Cancel"
* On the event page provide a registration button instead of ticket options with a number drop-down.
* If the organizer has requested additional information in the form direct the user to the attendee form
* If the organizer has not requested information in an attendee form directly register the attendee with their information (email/name) in the system.

**Comment by vennelakoilada362** [comment]
i want to work on this issue, please assign it to me
i want to contribute in the issue and guide me

**Comment by mariobehling** [comment]
Issues with the outcome so far below. Please resolve them.

- Paid registration is missing payment options
- Instead of "ticket" in the UI it should show "Registration"
