### ISSUE TITLE
Preselect "Ticket holder" same as "Ticket Buyer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5851]
Always preselect "Ticket holder is the same as ticket buyer." by default, but keep functionality as is. So, the ticket buyer can untick the box if they want.

![Screenshot from 2020-12-01 20-43-03](https://user-images.githubusercontent.com/1583873/100788997-259e7a80-3416-11eb-93ee-2ea1c5cbe372.png)

**Comment by MeghalBisht** [comment]
working on this

**Comment by mariobehling** [comment]
In the past I think we discussed to disable this feature for first time ticket buyers, but use this option for all others. As this feature has been reverted for now I am re-opening it.
