### ISSUE TITLE
Order Success Page: Change "Download Tickets" to "All Tickets" and use download icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5852]
On the order success page we have two buttons a) Download Ticket and b) "Download Tickets". This issue is about the button "Download Tickets". Please change the button to "All Tickets" and use a download icon for this specific button.

![Screenshot from 2020-12-01 20-57-25](https://user-images.githubusercontent.com/1583873/100790469-246e4d00-3418-11eb-89ed-24ea9afc4016.png)

**Comment by Raunaksingh100** [comment]
I am working on this issue plz don't make pr for this
THANKS

**Comment by ksraj123** [comment]
@Raunaksingh100 Sorry, did not see your comment, opened a PR for this. Feel free to close my PR if this is already solved. Thanks

**Comment by Raunaksingh100** [comment]
I am working on this issue plz don't make pr for this.
