### ISSUE TITLE
Attendee form questions have different order on wizard and live page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5853]
The attendee form during the order that attendees have to fill should have the some order of questions as the list of attendees on the wizard. See in the below example how the company is in between the custom questions for example.

![Screenshot from 2020-12-01 21-12-26](https://user-images.githubusercontent.com/1583873/100791996-49fc5600-341a-11eb-9667-68cb88b3ffb8.png)

![Screenshot from 2020-12-01 21-11-56](https://user-images.githubusercontent.com/1583873/100791999-4b2d8300-341a-11eb-8bc0-86e0522ceb7a.png)

**Comment by maze-runnar** [comment]
looking into it
