### ISSUE TITLE
Speaker and Attendee Forms: Change "Company" field to "Organisation"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5854]
In the Speaker and Attendee Forms please change "Company" field to "Organisation". Please ensure this shows up in the same way:
* on the wizard
* on the public speaker form
* on the attendee form during the order process

**Comment by MeghalBisht** [comment]
Company field or Organization field?
![2020-12-02](https://user-images.githubusercontent.com/61330148/100793645-7c21ae00-3442-11eb-9a93-bee352e459d2.png)

**Comment by mariobehling** [comment]
Good find! Please change fields in attendee and speaker form to be the same. I think in that case "Organisation" looks good too.
Thanks!

**Comment by mahir29** [comment]
I'll give this a shot. It would be a first PR for me, so I'll first familiarize myself with the general code!
