### ISSUE TITLE
Make Access Form similar to Discount Form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5857]
The discount form was simplified recently. Please simplify the access form in the same way.

Compare discount form
![Screenshot from 2020-12-01 21-33-12](https://user-images.githubusercontent.com/1583873/100795318-27b90700-341f-11eb-98d2-0ec64bbcd659.png)

**Comment by HashirGJ8842** [comment]
I would like to be assigned this issue!

**Comment by gunjan543** [comment]
> The discount form was simplified recently. Please simplify the access form in the same way.
> 
> Compare discount form
> ![Screenshot from 2020-12-01 21-33-12](https://user-images.githubusercontent.com/1583873/100795318-27b90700-341f-11eb-98d2-0ec64bbcd659.png)

I would like to work on this issue

**Comment by gunjan543** [comment]
I would like to work on this issue

**Comment by mariobehling** [comment]
Hello, we are not assigning outside contributors, but you can work together on the issue and create a PR that would count for both in a contest like Codeheat. Thank you for your interest!

**Comment by sayak2k1maruti** [comment]
Sir, I hope I have solved this issue . So I just made a pull request. This is my very first pull request in this repository. Please review and accept it.

**Comment by Saumyachitransh01** [comment]
Taking this up!
