### ISSUE TITLE
Expired Order Page: "Go to event" link missing on right hand side box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5863]
On expired order page the "Go to event" link is missing on right hand side box.

Please add this part of the box.

![Screenshot from 2020-12-02 14-07-21](https://user-images.githubusercontent.com/1583873/100876603-e456ab00-34a7-11eb-9f5f-ee0d40e1831e.png)

**Comment by MeghalBisht** [comment]
working on this
