### ISSUE TITLE
Virtual Events: Configure BBB room default behavior

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5865]
We need to control how virtual rooms are set up by default and offer some configuration options for organizers. Organizer should be able to control the room settings from the "Video" tab. Please implement the setting as below

Provide the option for organizers to configure the rooms
* Mute users when they join - by default users are muted
* Allow any user to start this meeting - by default off (only presenters and moderators can start the meeting)

Always off and cannot be configured by event organizers
- Require moderator approval before joining
- All users join as moderators

**Comment by iamareebjamal** [comment]
This can only be done in BBB, I imagine?

**Comment by mariobehling** [comment]
Correct, there is a room setting.

![Screenshot from 2020-12-02 15-30-54](https://user-images.githubusercontent.com/1583873/100902337-14607700-34c5-11eb-9a7b-58f89e0b9f11.png)

**Comment by mariobehling** [comment]
Some of these things are available also with the integration of BBB, e.g. in Moodle:
https://docs.moodle.org/310/en/BigBlueButtonBN

**Comment by mariobehling** [comment]
Some more links that could be relevant:
* https://pypi.org/project/bigbluebutton/
* https://github.com/alexsanderp/scalelite-flask-api
