### ISSUE TITLE
Public Event Page: Event Site listed twice and Wizard does not list Event Site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5877]
The public event page here https://eventyay.com/e/3dbaaa50 lists "Event Site" two times, but in the wizard of the event it is unclear where "Event Site" is listed. It only shows one of the links. Both areas "Social Media" and "Extra Links" show the option "Website". 

Probably for the moment "Event Site" should be listed within "Social Links" as it has a dropdown menu.

![Screenshot from 2020-12-02 23-03-51](https://user-images.githubusercontent.com/1583873/100937348-31ac3a00-34f3-11eb-80c8-93f2c199f4b6.png)
![Screenshot from 2020-12-02 23-02-46](https://user-images.githubusercontent.com/1583873/100937356-32dd6700-34f3-11eb-88ba-f5deafdeb365.png)

**Comment by iamareebjamal** [comment]
That's because we removed event site from the wizard. Because that's a separate field than custom links dicided to only show custom links. And this event must have been created before we removed this from wizard. Should we hide the event site from public pages as well?

**Comment by mariobehling** [comment]
Ok, so the question is, where does "Event Site" show up in the wizard now? It seems the implementation is not fully logic yet. Maybe we should have something like:
1. Social Links with dropdown menu (currently this part also shows "Website")
2. Web Links with dropdown menu (to have some predefined links like Event Site, Website, Blog)
3. Extra Links with text field (anything that does not fit into the above)

**Comment by mariobehling** [comment]
On live site, we now have a button "Event Site", but on the wizard there is no way to add an "Event Site" entry anymore. Also compare here https://eventyay.com/events/ae73f280/edit/other-details

**Comment by palakshivlani-11** [comment]
I wanna take up this issue

**Comment by iamareebjamal** [comment]
Yes, because we discussed and decided to remove event site from wizard

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-frontend/issues/5116#issuecomment-723430646

**Comment by maze-runnar** [comment]
this issue is no more relavant. 
![Screenshot from 2021-05-31 20-55-40](https://user-images.githubusercontent.com/56407566/120214855-a7028880-c252-11eb-9d43-bfbde55a1bf3.png)
