### ISSUE TITLE
Removed event organizer still receives email when participants sign up

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5881]
**Describe the bug**
As describe on the tittle. I was added as an organizer of one event for testing, then the owner removed my organizer access. I could not access the organizing page anymore. However I still received email every time when someone bought a ticket for that event. 

**To Reproduce**
Test event I mentioned https://eventyay.com/e/3dbaaa50

**Expected behaviour**
Removed organizer should not receive ticket purchasing email. 

**Desktop**
- Ubuntu 18.04

**Comment by iamareebjamal** [comment]
Root issue: https://github.com/fossasia/open-event-server/issues/7235

**Comment by maze-runnar** [comment]
how to remove organizer from an event. 
![Screenshot from 2020-12-29 09-16-03](https://user-images.githubusercontent.com/56407566/103257267-8342ca00-49b6-11eb-8a3e-0f2304f90f76.png)

**Comment by iamareebjamal** [comment]
Add the feature to do this

**Comment by maze-runnar** [comment]
> I was added as an organizer of one event for testing, then the owner removed my organizer access. 

then how this was possible. As mentioned in issue?

**Comment by maze-runnar** [comment]
```
errors: Array(1)
0:
detail: "You cannot delete an accepted role invite."
source: {pointer: "/data/status"}
status: 409
title: "Conflict"
```

**Comment by iamareebjamal** [comment]
That feature was removed because it was removing a role invite, which changes nothing as the error message shows above. You have to remove the role instead
