### ISSUE TITLE
Organizer is unable to Add/Create a Speaker 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5883]
**Describe the bug**
This bug is related to an organizer feature. When the event organizer added a new speaker and saved. The page froze, kept loading. 

**To Reproduce**
1. Go to 'speaker create form' https://eventyay.com/events/ae73f280/speakers/create
2. Enter the details
3. Save

![Screenshot from 2020-12-03 09-32-42](https://user-images.githubusercontent.com/1658742/100985135-e3775500-354b-11eb-8ef1-d31aaadb64ad.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04, Chrome

**Comment by iamareebjamal** [comment]
Speaker with email 'example@gmail.com' already exists in this event

The form should show the error from the API and unfreeze the form

**Comment by hpdang** [comment]
Areeb, if I chose Email is on required, the same thing happened, kept loading, then froze 

![Screenshot from 2020-12-03 11-35-06](https://user-images.githubusercontent.com/1658742/100998325-a74bf080-355b-11eb-8083-e762a8e40fee.png)

**Comment by iamareebjamal** [comment]
Yes, reproduced
