### ISSUE TITLE
Removed speaker still appears in the session summary 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5884]
**Describe the bug**
This bug is related to an organizer feature. When organizer removed a speaker from a session, and even deleted this speakers in the system. The speaker name still appeared in the 'Sessions' tab

**To Reproduce**
1. Go to 'Edit Session' https://eventyay.com/events/ae73f280/sessions/6531/edit
2. Remove one speak 'Hangying Li'
3. Go to 'Sessions' tab https://eventyay.com/events/ae73f280/sessions/all?search=culture
4. See Hangying Li is still there on the list. See and compare two screenshots below

![Screenshot from 2020-12-03 09-51-46](https://user-images.githubusercontent.com/1658742/100987175-7618f380-354e-11eb-8c04-c67fe4bf21b1.png)
![Screenshot from 2020-12-03 09-52-11](https://user-images.githubusercontent.com/1658742/100987181-787b4d80-354e-11eb-8844-4f8a60368e41.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04, Chrome

**Comment by ksraj123** [comment]
Looking into this.

**Comment by hpdang** [comment]
@iamareebjamal it does not seem to appear anymore on my side. @ksraj123 did you see find something

**Comment by hpdang** [comment]
I close it as it is not there anymore
