### ISSUE TITLE
Event Dashboard: Date end time of an event is wrong (showing start time)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5886]
The date end time of an event actually shows the start time on the event dashboard.

![Screenshot from 2020-12-03 11-56-13](https://user-images.githubusercontent.com/1583873/101000818-ab2d4200-355e-11eb-97a0-3f48a18c034e.png)

**Comment by SARTHAK1SINGH** [comment]
I am working on this issue.
