### ISSUE TITLE
Public Schedule Mobile View: Move date and filters up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5893]
Event date and filters are not accessible as they are on the bottom on the mobile View. Please move them to the top and display tracks and rooms next to each other.

![Screenshot_20201203_163827_com android chrome](https://user-images.githubusercontent.com/1583873/101052599-1db21800-3587-11eb-9959-ecac703baa78.jpg)

**Comment by MeghalBisht** [comment]
working on it
