### ISSUE TITLE
Public Schedule Mobile View: change in page menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5899]
The in-page menu has a burger menu that is the same as the top burger menu. It should be different.

Please implement a kind of drop-down button with an icon for each menu item and a down arrow. Take inspiration from GitHub as in below screenshot, e.g. see the button "development". In contrast to Github make the menu into a dropdown menu instead of a pop-up menu.

![Screenshot_20201204_081234_com android chrome](https://user-images.githubusercontent.com/1583873/101133622-5d214880-3609-11eb-9fb0-dd07b35708ff.jpg)
![Screenshot_20201204_081437_com android chrome](https://user-images.githubusercontent.com/1583873/101133624-60b4cf80-3609-11eb-914a-e1c15a5b1d9a.jpg)

**Comment by MeghalBisht** [comment]
working on this

**Comment by MeghalBisht** [comment]
@mariobehling is this the expected result?

![2020-12-04 (3)](https://user-images.githubusercontent.com/61330148/101153823-e86efe00-364a-11eb-960b-f71c0ea03fad.png)

**Comment by mariobehling** [comment]
@MeghalBisht The dropdown should get expanded by the icon on the right hand side.

![101153823-e86efe00-364a-11eb-960b-f71c0ea03fad](https://user-images.githubusercontent.com/1583873/101236482-df753f80-36d1-11eb-9791-bf5dec64426a.png)

So, if the user is on the page "info", then show info. If the user wants to go to ticket, scroll to Tickets and collapse the menu.

![101153823-e86efe00-364a-11eb-960b-f71c0ea03fad](https://user-images.githubusercontent.com/1583873/101236568-a4274080-36d2-11eb-9cc1-a41eeb6c5993.png)
