### ISSUE TITLE
Public Speakers Page and Featured Speakers Design Issue and Comma

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5901]
The speakers page and the featured speakers area on event start pages show the speakers name and below info with too much spacing. It seems like the style is also used somewhere else and when it is changed somewhere the text is also displayed differently here. Also other previous issues are back, e.g. there is a comma on another line.

Please fix the following on the speakers area on the event page and speakers page.
1. Reduce the spacing above and below the speakers name and organization/position (but do not make it 0, adjust it so it looks good)
2. Change the org/position font to black and not bold
3. Add a comma after position, e.g. System Administrator, Red Hat
4. Get rid of empty lines with a comma

compare below empty line with comma https://eventyay.com/e/ae73f280
![Screenshot from 2020-12-04 10-14-00](https://user-images.githubusercontent.com/1583873/101146733-a8445700-361b-11eb-9926-d57aad66fba3.png)
![Screenshot from 2020-12-04 10-11-48](https://user-images.githubusercontent.com/1583873/101146742-a9758400-361b-11eb-9a69-6148394f70f4.png)

**Comment by daretobedifferent18** [comment]
working on it
