### ISSUE TITLE
Overlapping issue in Speaker and Session Pages

### ISSUE THREAD

**Issue by MeghalBisht** [fossasia/open-event-frontend#5907]
**Describe the bug**

In Session and Speakers page, the links(canceled, withdrawn etc) are disabled due to the overlapping div tag as shown in the image below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'manage events'
2. Click on 'event dashboard'
3. Got to speakers/sessions tab.
4. Reduce the viewport width and try to click the links

**Expected behaviour**

Overlapping of tags should be fixed

**Screenshots**

![2020-12-04 (5)](https://user-images.githubusercontent.com/61330148/101185276-ac9e5d80-3677-11eb-84aa-567b7ebacd52.png)

**Comment by kenkirito** [comment]
please assign me
