### ISSUE TITLE
Public Event Pages: Reduce empty space on right sidebar between date area and tracks if no links are specified

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5908]
If there are no social or other weblinks specified there is an empty space between the two side bar widgets that is larger than it should be. Please reduce the white space between the widgets.

![Screenshot from 2020-12-04 17-29-54](https://user-images.githubusercontent.com/1583873/101190315-7c939200-3658-11eb-933e-0ca71d865652.png)

**Comment by yukti72** [comment]
I am a beginner here and i would love to contribute to fixing with bug. Hope its fine with you.

**Comment by yukti72** [comment]
I expect a little help in finding the location in fixing this out. Please could provide me with help?

**Comment by MeghalBisht** [comment]
@iamareebjamal  Please close this, issue solved in #5896 
![2020-12-18](https://user-images.githubusercontent.com/61330148/102606383-ab2b6580-414c-11eb-8563-770674672f60.png)

**Comment by MeghalBisht** [comment]
@iamareebjamal  Please close this, issue solved in #5896 
![2020-12-18](https://user-images.githubusercontent.com/61330148/102606496-d44bf600-414c-11eb-8d9e-b5804e94e9a2.png)
