### ISSUE TITLE
Video: Enable Rich text and links in "Additional Information"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5909]
Event organizers would like to add rich text and links into the area "Additional Information". Please enable rich text in that field in the video tab and show this accordingly on the schedule.

![Screenshot from 2020-12-04 18-40-47](https://user-images.githubusercontent.com/1583873/101196006-80c3ad80-3660-11eb-9bae-d0f69866d136.png)

**Comment by khushi935** [comment]
I would like to work on this issue .Can you suggest me ways to get started ?

**Comment by parmeshwar1807** [comment]
I want to take up this issue.
