### ISSUE TITLE
Public Schedule: Line break before "Join Video" reducing button size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5913]
Some session headings, specifically in non Latin alphabets reduce the "Join Video" button in the schedule.

Compare https://eventyay.com/e/cf877702/schedule

![Screenshot from 2020-12-05 08-33-15](https://user-images.githubusercontent.com/1583873/101236871-cb7f0d00-36d4-11eb-96a4-17b829abc6d3.png)

**Comment by ksraj123** [comment]
I can't see the join now button in any of the sessions. Am I on the right page? Please share suggestions. Thanks

<img width="1755" alt="Screenshot 2020-12-05 at 2 25 18 PM" src="https://user-images.githubusercontent.com/39027928/101238368-c25a6400-3705-11eb-92f1-6606ab89f7d8.png">

**Comment by iamareebjamal** [comment]
You need to buy a ticket to see the button
