### ISSUE TITLE
Ticket: If an event has only free and donation tickets do not show "promotional code" and other details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5914]
Please change the public ticket info as follows:
1. If an event has only free and donation tickets do not show "promotional code". (Also reduce the spacing between "Total" and "Order now" then)
2. If an event has only free tickets and no other tickets do not show the credit card icons neither.
3. Also ensure this works on mobile views.

![Screenshot from 2020-12-05 08-38-48](https://user-images.githubusercontent.com/1583873/101236989-9cb56680-36d5-11eb-96b8-2d90172a1e84.png)

**Comment by daretobedifferent18** [comment]
working on it

**Comment by inayahassan23** [comment]
i am working on this how to make a pull request?? @daretobedifferent18  @mariobehling plzz tell
