### ISSUE TITLE
Tickets: fix mobile ticket view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5915]
![Screenshot_20201205_084459_com android chrome](https://user-images.githubusercontent.com/1583873/101237084-61fffe00-36d6-11eb-8752-0090b996938a.jpg)

**Comment by daretobedifferent18** [comment]
@mariobehling can u pls tell m what to improve?

**Comment by mariobehling** [comment]
Match left and right side. In the example screenshot it would be:

- Type -> Free Ticket
- Price -> Free
- Quantity -> 1 (dropdown)
- Subtotal -> Free

**Comment by usama-t** [comment]
I would like to work on that.

**Comment by SARTHAK1SINGH** [comment]
I am working on it.

**Comment by mharshita** [comment]
Working on this

**Comment by SARTHAK1SINGH** [comment]
> Working on this

Already working on it.

**Comment by mariobehling** [comment]
Also compare how others have implemented a mobile sales page, e.g. Eventbrite
![Screenshot_20201219_205445_com android chrome](https://user-images.githubusercontent.com/1583873/102698314-bbbb0900-423c-11eb-90e4-86f1d67fc230.jpg)

**Comment by missmahi55** [comment]
@mariobehling please assign me
