### ISSUE TITLE
Mobile schedule: Fix details and standardize "Join Video" button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5917]
Please enhance the following:
- [ ] Reduce space below speaker
- [x] Standardize "Join Video" button, keep icon on the left (experiment to make it look good and display it in the same way in all sessions)
- [x] Always align "Join Video" button to the top right in all sessions (as you can see in below screenshot it moved down a bit)

![Screenshot_20201204_230621_com android chrome](https://user-images.githubusercontent.com/1583873/101237765-a17d1900-36db-11eb-8d96-35b29a152ede.jpg)

**Comment by iamareebjamal** [comment]
It's not hardcoded I believe, it's the session type

**Comment by mariobehling** [comment]
Yes, I got confused, because they use the track "Presentations" instead of a theme track. I took it out.

**Comment by ranjitkshah** [comment]
I think it's looking fine now or need any style changes? @mariobehling 
![image](https://user-images.githubusercontent.com/61561415/103463711-53981700-4d54-11eb-9ab9-8a9aba9b84db.png)

**Comment by iamareebjamal** [comment]
See the unchecked point
