### ISSUE TITLE
Mobile schedule: Fix menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5919]
**Current State:**
![Screenshot_20201204_230526_com android chrome](https://user-images.githubusercontent.com/1583873/101238106-2b2de600-36de-11eb-8637-7c46f38eadb4.jpg)

Please change it as follows:
**1. Version with not expanded search**
   1. Move the menu as follows
   2. Reduce the space to the schedule (also ensure there is not too much space if there are tracks)

![101238106-2b2de600-36de-11eb-8637-7c46f38eadb4](https://user-images.githubusercontent.com/1583873/101238448-9e385c00-36e0-11eb-9f6a-83ad640c5143.jpg)

**2. When the user clicks the search button, expand the search bar as in the below screenshot.**

![101238106-2b2de600-36de-11eb-8637-7c46f38eadb4-a](https://user-images.githubusercontent.com/1583873/101238471-d0e25480-36e0-11eb-9994-14942ecef405.jpg)

**Comment by SiddheshShinde-tech** [comment]
I m working on this :)

**Comment by SiddheshShinde-tech** [comment]
![Screenshot (268)](https://user-images.githubusercontent.com/62283380/101260226-61a64800-3754-11eb-89ea-504d24c4d7f6.png)

Schedule button not present in the Menu, therefore unable to work.
Please look into it.

**Comment by iamareebjamal** [comment]
You need to publish the schedule

**Comment by SiddheshShinde-tech** [comment]
> 
> 
> You need to publish the schedule

@iamareebjamal I didn't get it. Can you please elaborate it in detail ?

**Comment by iamareebjamal** [comment]
Please get to know the system before trying to solve the issue

**Comment by SiddheshShinde-tech** [comment]
@iamareebjamal I went through the readme file of the project and installed it accordingly, but the project is different on my local server than that of the actual website. It would be very helpful if you can guide me for the same ....

On my local server 

![Screenshot (270)](https://user-images.githubusercontent.com/62283380/101261547-3a547880-375e-11eb-92fd-bfc65167ce96.png)

On https://open-event-frontend.now.sh/

![Screenshot (269)](https://user-images.githubusercontent.com/62283380/101261554-4c361b80-375e-11eb-9841-1428eb61c1ad.png)

**Comment by iamareebjamal** [comment]
Change API_HOST in .env to https://api.eventyay.com

**Comment by aman-jaglan** [comment]
i m working on this

**Comment by Deepak-032** [comment]
I want to work on this issue. Please assign this to me.

**Comment by Deepak-032** [comment]
Please tell me the page on which you want to have the changes, I am unable to find it on the website.
