### ISSUE TITLE
Search: Fix and Enhance filter options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5921]
The filters are not consistent, e.g. it is currently not possible to choose all location types at the same time even though this is the default search behavior. Therefore please make the filter display and search functionality consistent and allow searching of past events as well. 

Please change the filters as follows and make the below options the standard search setting:
- Rename "Event Location Type" to "Setting"
  - Tick all boxes Online, Location, Mixed - by default
- If user only ticks online show all online events already even if no event name has been specified
- Date 
   - Change "All dates" filter to actually display "All dates" including past dates and move it to the end of the search filter area
   - Implement filter "Past" and "All Upcoming"
   - By default tick "All Upcoming" and when ticking "All Upcoming" tick "Today" and all other future filters (except custom dates)
   - Show "Past" at the end of the widget before "All dates"
- Categories - leave it as is to "All Categories"
- Event Types - leave it as is to "All Types"
- Ticket Type - tick Free and Paid by default
- Event Call For Speakers rename it to "Call for Speakers"
- By default tick "Open" only
- Finally change "Clear Filters" to "Default Filters" and reset filters to the standard search filter config when the user clicks it

Furthermoe
* Ensure that the search as above works in the same way from the start page as well the explore page
- The search from the start page should always use the standard search parameters for now

![Screenshot from 2020-12-05 13-30-59](https://user-images.githubusercontent.com/1583873/101243160-9091cf00-36fe-11eb-94b8-0bcaa121c987.png)

**Comment by iamareebjamal** [comment]
@mariobehling Online + Location is already = Mixed, so it'll make it complicated  to allow selecting all options and there will be no better user experience because Mixed already handles the above case

**Comment by mariobehling** [comment]
@mariobehling Well, this definition is different to the definition I had in mind: There is a case where the user is specifically looking for an event that is run as an in-person event as well as an online event. This is in contrast to an event that is run as a location based event. And it is different to an event that is run as a pure online event.

**Comment by iamareebjamal** [comment]
OK, yes, I understand now :+1:

**Comment by mariobehling** [comment]
I am closing this issue as the search has already been improved substantially and additional changes seem out of scope currently.
