### ISSUE TITLE
Front Page: Add info about Online event and fix/enhance date/time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5926]
The front page nicely displays locations of events. At the same place there should be
* the info "Online Event" if the event is not location based and 
* "Online Event and at [address here]" if it is a mixed event

Furthermore the tile needs to be enhanced in regards to the date to
* show long date type for the event 
* show both start and end time of event (as many events go over several days now)

![Screenshot from 2020-12-06 01-03-57](https://user-images.githubusercontent.com/1583873/101268059-9f5c9e00-375f-11eb-93ba-c951fee26898.png)

**Comment by MeghalBisht** [comment]
working on this
