### ISSUE TITLE
Front Page: Move Search Function to Top Bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5927]
Please move the search feature to the top bar and substitute "Browse Events" with "Search Events". Implement it as follows:
* Implement the search in the place of "Browse Events" 
* Use a similar style and show "Search Events"
* Expand the search box similar to GitHub when the user enters something
* Delete the main search bar below the header
* Show the top search bar on the same pages as Browse Events at the moments (do not change anything here)

![Screenshot from 2020-12-06 01-51-47](https://user-images.githubusercontent.com/1583873/101268670-480dfc00-3766-11eb-81b7-78ee1e75aefc.png)

**Comment by Yougendernith** [comment]
I'll work on this issue

**Comment by palakshivlani-11** [comment]
I want to work on this issue.

**Comment by Tushar11Raj** [comment]
@mariobehling I would like to work on this issue. Please assign.

**Comment by Utkarshn10** [comment]
Working on this!!

**Comment by Vivek-R-Pawar** [comment]
I'll work on this!
