### ISSUE TITLE
Chore: Use API test server for test frontend deployment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5928]
In our documentation it is written:

> The development branch of open-event-frontend gets deployed at https://open-event-frontend.now.sh/ It consumes the API exposed by development branch of open event server, hosted at https://open-event-api-dev.herokuapp.com

However as a matter of fact the frontend uses the API of the actual eventyay service. Please direct the frontend to use the API on Heroku as mentioned in the documentation.

**Comment by iamareebjamal** [comment]
We use it for PR deployment which is useful with production API. https://fossasia.github.io/open-event-frontend/ is using dev API server and can be mentioned in the docs

**Comment by mariobehling** [comment]
What are the limits of https://fossasia.github.io/open-event-frontend/ ? It seems some things like search and changing languages do not work.
