### ISSUE TITLE
Implement social-links & copyright API to /edit/basic-details & create route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#593]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
 

Parent Issue #462

**Comment by CosmicCoder96** [comment]
@geekyd Any progress on this ?

**Comment by geekyd** [comment]
@CosmicCoder96 Yeah will send a PR soon.
