### ISSUE TITLE
Logo is overlapping with the navbar in custom view

### ISSUE THREAD

**Issue by ssdn-867** [fossasia/open-event-frontend#5934]
Real Behavior

In the mobile view logo is getting overlapped with the navbar

Expected Behavior
Logo should not overlap with navbar

Steps to reproduce it

Open the website and view it in 500X883 screen dimension

Screenshot of Issue

![image](https://user-images.githubusercontent.com/66898317/101280272-340ddd00-37ee-11eb-9a92-9f465ac29af2.png)

**Comment by arhamathar** [comment]
Assign this to me.

**Comment by RasshiBhatia** [comment]
Plz assign me .

**Comment by Ak-panchal** [comment]
plz, assign me.

**Comment by Optider** [comment]
Assign me.

**Comment by ssdn-867** [comment]
@RasshiBhatia @Ak-panchal @Optider sorry for replying late.You all can submit a pull request and also I am not a maintainer of this project.If that request solves the issue than that will get merge by the maintainer.

**Comment by Optider** [comment]
I am working on it.

**Comment by SARTHAK1SINGH** [comment]
working on it.
