### ISSUE TITLE
Schedule and After-Event Video: Add video button to schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5939]
For live video event rooms there is a button on the event schedule "Join Video". 
* This button should disappear after an event, but organizers can add a video of the event (already available in the session form options)
* If there is a video after the event available, please add a button "Watch Video" with a video icon in the same place. 
* Link to the specific session page - directly to the area of the video
* Please ensure this also works if there is a "Download Slides" button

Compare https://eventyay.com/e/cf877702/schedule

![Screenshot from 2020-12-06 23-35-08](https://user-images.githubusercontent.com/1583873/101295112-ddb79300-381b-11eb-8193-f810f6b51171.png)

Compare https://eventyay.com/e/1f720482/schedule

![Screenshot from 2020-12-06 23-27-25](https://user-images.githubusercontent.com/1583873/101295021-42262280-381b-11eb-89aa-7abaaadea30a.png)

**Comment by vennelakoilada362** [comment]
i want to work on this issue, please assign it to me and guide me
