### ISSUE TITLE
Implement Dashboard Box "Sessions and Speakers"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5940]
The event dashboard does not have a dedicated box for sessions and speakers. Please implement a box.

In the box show info about
* number of speakers and include overview of pending, accepted etc. (all states)
* sessions and include an overview of pending, accepted etc. (all states)
* tracks, microlocations/rooms and session types
* when Call for speaker starts and ends

![Screenshot from 2020-12-07 02-49-33](https://user-images.githubusercontent.com/1583873/101300743-df428480-3836-11eb-87eb-ddd98541da58.png)

**Comment by palakshivlani-11** [comment]
I would like to take up this issue.
