### ISSUE TITLE
Cursor changed to indexer while hover on choose language button as well as social icon do not appear.

### ISSUE THREAD

**Issue by nlok5923** [fossasia/open-event-frontend#5941]
**Describe the bug** 
 While hovering on language selector button cursor changed to indexer. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to footer 
2. hover on language selector
3. See error

**Expected behaviour**
Cursor should get changed to hand pointer
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kenkirito** [comment]
working on it
