### ISSUE TITLE
Organizer: Attendee Overview - Sorting is not possible 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5948]
This is related to an organizer feature. In the Attendee overview page, organizer is not able to perform any sorting like date, ticket name, ticket price. Please implement sorting for **Date**, **Ticket Name** and **Ticket Price**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ['Attendee Over page](https://eventyay.com/events/ae73f280/tickets/attendees/completed?search=)'
2. Click on 'Date'
3. Sorting is not possible. As an organizer I want to see the latest attendees. 

![Screenshot from 2020-12-07 14-49-49](https://user-images.githubusercontent.com/1658742/101358776-9ec92200-389b-11eb-8547-8488237764d4.png)

**Comment by hpdang** [comment]
@mariobehling @iamareebjamal does it make sense to sort 3 entries: Date, Ticket Name and Ticket Price?

**Comment by Parthkhandelwal0** [comment]
currently working on this

**Comment by Parthkhandelwal0** [comment]
hey @hpdang! the link you posted isn't working is there something i am missing?

**Comment by MeghalBisht** [comment]
@Parthkhandelwal0 You need to create an event to access the attendee page

**Comment by mariobehling** [comment]
Date and Time sorting unfortunately does not work as expected. Sorting is not correct here. Therefore reopening it.
![Screenshot from 2020-12-22 16-54-29](https://user-images.githubusercontent.com/1583873/102907702-b8ab5d00-4476-11eb-8b4b-abf651cb256a.png)

**Comment by iamareebjamal** [comment]
@mariobehling Can you please share the event link? I cannot reproduce

**Comment by mariobehling** [comment]
Working now as expected.
