### ISSUE TITLE
Unnecessary Senetary logger on browser Web developer console

### ISSUE THREAD

**Issue by daretobedifferent18** [fossasia/open-event-frontend#5950]
**Describe the bug**

Getting Senetary loggers on console pannel

**To Reproduce**
1. Go to https://eventyay.com
2. Open Web Developer console.
3. See the error

**Expected behavior**

Unnecessary console.log shouldn't be there.
Also, some data is also getting rendered which shouldn't be like id etc.

**Screenshots**

![Screenshot from 2020-12-07 22-00-43](https://user-images.githubusercontent.com/71120226/101377359-bb834b00-38d7-11eb-8547-1c1651f46a76.png)

**Desktop (please complete the following information):**
- All

**Smartphone (please complete the following information):**
- All

**Comment by iamareebjamal** [comment]
It's Sentry, not Sanitary. And it's not unnecessary
