### ISSUE TITLE
Fonts: Change light gray font to dark gray across app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5951]
There are a number of places with light gray color. This is often difficult to see, especially if it is not bold. However, there is no point of making more and more text bold. 

Please change light gray color to a dark gray that is easier to read.

**Comment by nlok5923** [comment]
Working on it sir.

**Comment by jaiswalrobin** [comment]
Please assign it to me

**Comment by spy-1234** [comment]
Sir, I want to working on the issue.

**Comment by yukti72** [comment]
Is this issue still open?

**Comment by Radhika14soni** [comment]
Is this issue still open?

**Comment by mariobehling** [comment]
A number of areas are still light gray, e.g.:
* my tickets
* my sessions
* headings in invoices

![Screenshot from 2020-12-23 09-38-19](https://user-images.githubusercontent.com/1583873/102977106-d1615480-4502-11eb-97b2-f1d08e8928ad.png)
![Screenshot from 2020-12-23 09-37-24](https://user-images.githubusercontent.com/1583873/102977116-d4f4db80-4502-11eb-86df-f1b6b36f0ec0.png)
![Screenshot from 2020-12-23 09-33-36](https://user-images.githubusercontent.com/1583873/102977117-d4f4db80-4502-11eb-9aac-85da51dd8f69.png)

**Comment by Tanishka-Spontom** [comment]
Is this issue still open?

**Comment by Tanishka-Bansal** [comment]
Is this issue still open?
