### ISSUE TITLE
Virtual Events: Organizer Video Room tab long URLs overlapping column

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5962]
On the video room tab long URLs are overlapping the next column. Please show a URL and if it is too long add "...".

![Screenshot from 2020-12-08 15-12-35](https://user-images.githubusercontent.com/1583873/101494703-f5039700-3967-11eb-8b6b-fc3e046db2e2.png)

**Comment by takshch** [comment]
@mariobehling Can i get this issue? Is anyone is working on this?

**Comment by mariobehling** [comment]
Closing this in favor of https://github.com/fossasia/open-event-frontend/issues/6005
