### ISSUE TITLE
Speakers Page: User able to add speakers with all empty fields.

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#5963]
**Describe the bug**

When organizer come back to speakers list without saving speaker, that unsaved speaker is shown in list of speakers. 
it get disappear when user refresh page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event
2. Go to  event dashboard.
2. Click on speakers tab.
3. click on add speaker tab.
4. leave form empty.
5. click on speakers tab again(form must be empty and do not save speaker).
6. see that that speaker with all empty fields is present in list of all speakers.
7. it will disappear when you refresh page.

**Expected behaviour**

that unsaved speaker must not listed in all speakers list.

**Screenshots**

![new issue today](https://user-images.githubusercontent.com/72552281/101497264-cc43c780-3990-11eb-98e0-60a06aa91a2a.png)

**Desktop (please complete the following information):**
all
**Smartphone (please complete the following information):**
all

**Additional context**

issue is same as #5526 

while solving you can refer #5584

**Comment by kenkirito** [comment]
working on it

**Comment by aman-jaglan** [comment]
i m working on this
