### ISSUE TITLE
Public Event Sidebar Dates Scrumbled

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5966]
There is an issue with the date/time of the event in the sidebar. It has an unidentifiable time and date.

Compare https://eventyay.com/e/d55cc647
![Screenshot from 2020-12-09 01-52-37](https://user-images.githubusercontent.com/1583873/101559412-5efc5a80-39c1-11eb-8d4c-f4088032f58d.png)

**Comment by maze-runnar** [comment]
looking into it
