### ISSUE TITLE
Schedule: Time stamp error 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#5967]
**Describe the bug**
This is related to an organizer feature. While scheduling sessions, organizer was unable to adjust the duration of the the last session and it also showed the wrong timing. In the example below, the event ends at 22:30, the last session shows 23:15. 

![Screenshot from 2020-12-09 02-53-03](https://user-images.githubusercontent.com/1658742/101564351-4729d400-39cb-11eb-8528-26ecffb76433.png)

**To Reproduce**
1. Go to 'https://eventyay.com/events/52c477a1/scheduler'
2. Try to schedule a session for the last 15 mins
3. See error
4. The time format is not consistent 21:30 vs. 9:30 

**Desktop (please complete the following information):**
 - Ubuntu 18.04, Chrome

**Comment by iamareebjamal** [comment]
@daretobedifferent18 Please check

**Comment by daretobedifferent18** [comment]
@iamareebjamal @hpdang What I get from checking it is the issue is with timeformat that is showing 24 hr clock on left side and 12 hr clock on sessions. Isn't ?

**Comment by iamareebjamal** [comment]
Yes, it should be 24hr here

**Comment by iamareebjamal** [comment]
Main issue is wrong time display and inability to adjust the timing

**Comment by hpdang** [comment]
Yes, the core is the wrong time display. This event ends at 22:30 but it shows 11:15 in the last session. And I didn't manage to adjust this session to 20 min which means it should end at 22:30.

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by aditya1abhinav** [comment]
I am working on this project!
