### ISSUE TITLE
npm ERR! A complete log of this run can be found in

### ISSUE THREAD

**Issue by yukti72** [fossasia/open-event-frontend#5972]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'git bash'
2. Click on 'npm start'
3. Scroll down 

**Expected behaviour**

I have looked over many ways to resolve this but the issue keeps on persisting.

**Screenshots**

<img width="960" alt="Annotation 2020-12-09 203901" src="https://user-images.githubusercontent.com/64638327/101647731-15624d00-3a5f-11eb-9d6e-34fdf90ff65c.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by iamareebjamal** [comment]
The docs don't mention `npm start` anywhere
