### ISSUE TITLE
Event Dashboard not loading all events reliably

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5982]
The dashboard listing all events does not show events when the user clicks around the system elsewhere and the returns. Difficult to reproduce it but then suddenly it disappears again.

![Screenshot from 2020-12-10 17-39-37](https://user-images.githubusercontent.com/1583873/101801646-dd1a4780-3b0e-11eb-9924-10ab9be00b5a.png)

**Comment by iamareebjamal** [comment]
Root cause same as #5176

**Comment by aditya1abhinav** [comment]
@mariobehling assign me for this issue.

**Comment by aditya1abhinav** [comment]
I will work in this issue.

**Comment by aditya1abhinav** [comment]
on*

**Comment by aditya1abhinav** [comment]
I am working on this project!

**Comment by daretobedifferent18** [comment]
@iamareebjamal @mariobehling I was looking for the solution to this problem and was not able to get to know why is this bug coming.
After working on it, I think the error was produced for me and this is the error msg I got
![Screenshot from 2020-12-23 18-59-17](https://user-images.githubusercontent.com/71120226/103000507-35ab0500-4551-11eb-977b-01424af70a7b.png)

**Comment by iamareebjamal** [comment]
Error fixed
