### ISSUE TITLE
Virtual Events: Organizer Video Page - Move add room button and enhance design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5983]
We now have the new feature of event rooms. For the organizer it is a bit difficult to grasp what is the difference between the two tables on the video tab for organizers. Therefore please enhance the area:
* Change the upper table color to distinguish it to the second table
* Move the "Add Room" button to the right of the search bar 
* Move "show xx entries" a bit closer to the second table. Currently it looks like it belongs to the upper table
* Check if it makes sense to separate the tables a bit more by adding some space below the first table or propose another change that achieves the same goal

![Screenshot from 2020-12-10 17-45-02](https://user-images.githubusercontent.com/1583873/101802368-a42ea280-3b0f-11eb-8536-d9eb65025d15.png)

**Comment by daretobedifferent18** [comment]
Taking this up

**Comment by rghvmaheshwari** [comment]
Hey! can I work on this issue
