### ISSUE TITLE
Getting Page not found error when i generate the link after putting my web page ready

### ISSUE THREAD

**Issue by Jyotsna1006** [fossasia/open-event-frontend#5996]
**link not found 404 error**
<!-- not able to host my web page using github --

**Desktop 
 - OS: [windows]
 - Browser [chrome]
check my page @Jyotsna1006

**Comment by iamareebjamal** [comment]
Probably the first issue I saw where the issue body is smaller than the title. You conveniently ignored the issue template which asks you to fill in reproduction steps. I don't understand the issue
