### ISSUE TITLE
Vertical event card UI distorted

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#6003]
![image](https://user-images.githubusercontent.com/3874064/101945987-93b42000-3c14-11eb-8008-73d57957bf9e.png)

**Comment by iamareebjamal** [comment]
@MeghalBisht Please take a look

**Comment by MeghalBisht** [comment]
> @MeghalBisht Please take a look

This happened because of the height changes done in #5933. I will correct this
