### ISSUE TITLE
Virtual Events: Further enhance design and in page details of organizer video tab page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6005]
Please change the organizer video tab details as follows:

**Tables**

* Match the width of both tables to the width of the box "This feature is still in alpha stage"

**Table Headings**

* Rename Video Room -> Video Source URL
* Rename Link -> Join Video
* Rename heading "Pin" to "Room Password" on both tables
* Rename heading "Pin" to "Room Password" on the specific session video page
* Ensure that "Pin" is also showing up as "Room Password" on the public event page for ticket holders

**Table Columns and Content**

* Extend colum Event/Microlocation and make video room  URL column smaller a bit
* Change URL in Video room URL to display only a limited number of characters that fit onto one line without https, e.g. meet.jit.si/eventyay/a315169f-stream...
* In the link column implement a box of the link that is not editable similar to the "copy link box" of the Call for Speakers using a _gray_ button. Keep the link "linkified" and open the link in a new tab
![Screenshot from 2020-12-11 20-56-27](https://user-images.githubusercontent.com/1583873/101949987-c2220300-3bf4-11eb-83fb-eea17445dabf.png)
* Reduce the width of the column "Link" a bit and expand the column "Additional Information" in exchange a bit

**Comment by daretobedifferent18** [comment]
@iamareebjamal Pls could you add codeheat label
