### ISSUE TITLE
Virtual Events: Before an event has started automatically redirect users from video rooms streaming page after a short testing time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6010]
After users got a ticket for a virtual event they already see the link "Join Event". So, all users can immediately use the video link. This could be good for testing, but it can also drain our resources for video that we provide. What options are there to control the access to the virtual event rooms? What is a good option?

I could imagine the following: Before an event has started the user sees the "Join Video" button and clicks on it. The video room opens and a message appears "Your event has not started yet. You can test the event room as it is configured by the event organizer for 5 minutes. After that your connection to the event room will close automatically. Event rooms open by default 1 hour before the start of the event."

For organizers this feature should always work though. They should be able to visit their event room always.

**Comment by iamareebjamal** [comment]
This can work on Jitsi but not on Big Blue Button. Because we direct to BBB and lose control to close connection or do anything else

**Comment by mariobehling** [comment]
Closing this for now. We need to find a solution to this later.
