### ISSUE TITLE
Organizer Menu Bar: Simplify Settings and merge Export Page Areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6011]
We already have a lot of features, but some features are not so regularly used and can move a bit to the back. This includes the "Export" feature, which also needs to be tested more in detail. 

To simplify this please **merge the Export and Settings page** as follows:
* On the settings page implement a left side menu similar to the menu on the tickets tab with
   * **Export** - Simply move the content of the export page to the subpage here and use the URL `/settings/export` and delete the export page and menu item in the event menu

compare screenshot
![Screenshot from 2020-12-12 14-38-02](https://user-images.githubusercontent.com/1583873/101985332-a74c9e80-3c87-11eb-9f19-2d73d5d6c65c.png)

   * **Options** - Show the heading "Danger Zone" here and add the current info of the settings page using the URL `/settings/options`

Also check how Github is doing it in Repository Settings if you need to understand more details about this approach.

Compare left side bar in tickets tab
![Screenshot from 2020-12-12 14-26-57](https://user-images.githubusercontent.com/1583873/101985303-7a988700-3c87-11eb-89cb-861fd1348b6a.png)

**Comment by Afzal-Ind** [comment]
Working on this...

**Comment by Afzal-Ind** [comment]
Unable to resolve this. Someone else can take up this.

**Comment by abishekvashok** [comment]
Claiming this up

**Comment by Afzal-Ind** [comment]
>any updates?

Yes almost resolved after trying over and over again. Please see the screenshot.

**Comment by Afzal-Ind** [comment]
@mariobehling plz review it.

**Comment by abishekvashok** [comment]
Cool
