### ISSUE TITLE
Export Page: Error while fetching export JSON from server

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#6015]
**Describe the bug**

At export page of event dashboard, export JSON fetching always fails.

**To Reproduce**
Steps to reproduce the behaviour:
1.create event.
2. Go to event Dashboard.
3  press export tab.

**Expected behaviour**

export JSON fetching should not fail.

**Screenshots**

![export error](https://user-images.githubusercontent.com/72552281/101994605-a2203b80-3ce9-11eb-935d-ad5ca4785a06.png)

![export console](https://user-images.githubusercontent.com/72552281/101994634-dac01500-3ce9-11eb-8382-423eb4174452.png)

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Comment by Creatoon** [comment]
@sachinchauhan2889 I think the reason for this error is: the event is not created or published yet means the JSON file is not yet saved in the database, if you will publish the event, then it will fetch the JSON file.

**Comment by sachinchauhan2889** [comment]
> @sachinchauhan2889 I think the reason for this error is: the event is not created or published yet means the JSON file is not yet saved in the database, if you will publish the event, then it will fetch the JSON file.


Great, i got it. You are right.
