### ISSUE TITLE
Wizard Step 1: Event Start Date Limit not needed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6021]
In the wizard step 1 there is a start date limit, that the start of the event has to be before the current date. But, actually there are use cases where the event should start before the current date, e.g. when the user wants to change the end date of an event after it has started. Then the user will receive the error message "event start date should be before current date". 

Considering this use case, please take out the requirement that the start date of an event has to be before the current date.

![Screenshot from 2020-12-14 10-47-07](https://user-images.githubusercontent.com/1583873/102066451-22ce5d00-3dfa-11eb-8f39-2000e3f8cd4d.png)

**Comment by akash2408** [comment]
iam doing it
