### ISSUE TITLE
New Event form - Next button not working

### ISSUE THREAD

**Issue by SingingApple** [fossasia/open-event-frontend#6027]
**Describe the bug**
When trying to create a new event, as soon as the editing addition info page arrives; the next button stops to work and an error _Not a valid URL_ appears.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Create Event -> Basic Details -> Addition Info'
2. Click on 'Next'
3. Scroll down to 'bottom'

**Expected behaviour**
Upon clicking on "next" it should lead to the next page i.e Attendee Form.

**Screenshots**
![Screenshot from 2020-12-14 22-58-16](https://user-images.githubusercontent.com/39864404/102114364-1b419f00-3e60-11eb-8016-7bf14e5e00c6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 83.0

**Comment by MeghalBisht** [comment]
Probably in the "Links and social media" you did not enter a valid URL and instead entered a random string

**Comment by Harshit564** [comment]
It's working fine for me

**Comment by SingingApple** [comment]
@MeghalBisht yes, it was a thing with Link and Social media. It wasn't highlighting the field so I was unable to identify the mistake.
