### ISSUE TITLE
Event Dashboard: Only show Sessions and Speakers Box if options are active

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6033]
If sessions and speakers data is not activated and filled in the "Sessions and Speakers" box should not be there on the event dashboard.

![Screenshot from 2020-12-15 10-10-02](https://user-images.githubusercontent.com/1583873/102195600-13651780-3ebf-11eb-81a0-d7ea818f5476.png)

**Comment by imbhavesh28** [comment]
Sir @mariobehling, Can you explain in another way? I didn't get the issue!

**Comment by Afzal-Ind** [comment]
@imbhavesh28 see the PR, already created. Look for another issue.

**Comment by imbhavesh28** [comment]
> @imbhavesh28 see the PR, already created. Look for another issue.

Okay, @Afzal-Ind. Thank's for reminding me!
