### ISSUE TITLE
Frontpage Search/Event Category: Search term should not get added to event categories

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6034]
There are event categories/tags available on the bottom of each event card. If the user has done a search on the system before, the search term is always added as "filter". Tags on event categories should always link to the same standard page and they should not have a filter added.

![Screenshot from 2020-12-15 10-43-12](https://user-images.githubusercontent.com/1583873/102198676-f599b180-3ec2-11eb-986b-7e27e608e24a.png)

**Comment by imbhavesh28** [comment]
Can, I solve this issue @mariobehling?

**Comment by imbhavesh28** [comment]
@mariobehling Do, I need to add a filter to this website?

**Comment by sachinchauhan2889** [comment]
looking into this

**Comment by Afzal-Ind** [comment]
> looking into this

Hi! Can I change here`<a href="#" role="button" {{action 'clearFilter' 'category'}}><i class="icon close"></i></a>` into '{{action 'clearFilter' 'category'}}'? Thanks.
