### ISSUE TITLE
delete option not working in attendee form

### ISSUE THREAD

**Issue by ranjitkshah** [fossasia/open-event-frontend#6046]
**Describe the bug**
   Delete option not working in custom fields of attendee form after saving it reappears see the below video for more refrence

**To Reproduce**
1. create an event
2. turn on the attendee form
3. add custom field save it
4. now delete that field after refreshing it reappears

**Expected behavior**
it should be deleted

**video**
https://www.loom.com/share/003e8b37e8214c85b325c38c81ba3cc1

**Comment by daretobedifferent18** [comment]
working on it

**Comment by maze-runnar** [comment]
@daretobedifferent18 , here is a think -I think it's a pattern in wizard steps.
When user delete a ticket and refresh then ticket are not deleted.
in 2nd step when user delete link ,and refresh link is not deleted.
So until user doesn't hit save it should not complete delete process.

**Comment by maze-runnar** [comment]
@iamareebjamal is it really an issues?
