### ISSUE TITLE
Virtual Events: Adjust URLs on Video Tab Overview Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6056]
The video overview page has two columns with links. Please change these columns as follows:

1. Video Source URL: Unlinkify the URL. Reason: We do not really want to direct the user (organizer) to another website or easily enable them to share the source URL by copying the link. We just want to inform them here which service they are using. If they really want to get the entire link they can visit the edit page of the stream.

2. Join Video URL
 * Place the link in a box, but do not make the box and button area use more space than the current implementation. Reason: It is clearer that the "Copy" button is related to the URL and that this is a unit if the URL is boxed. Furthermore the user can inspect the complete URL by moving back and forth in the box. If the user has to copy the URL first and enter it elsewhere it brings the attention away. Showcasing that we integrate video systems nicely in our system by visualizing the URL is a feature that we can show off to expert users. For normal users it does not disturb them neither as at the same time the URL does not take up too much space, because it is boxed.
 * Do not make the URL blue anymore to reduce focus on the link.
 * Change the color of the Copy button from black to gray to not have it stand out so much
 * Behind the current "Copy" button add an arrow button as below that directs the user to the link

Arrow button
![Screenshot from 2020-12-17 04-00-15](https://user-images.githubusercontent.com/1583873/102438385-7f10c700-401c-11eb-9604-5142e69d29dc.png)

![Screenshot from 2020-12-16 12-51-40](https://user-images.githubusercontent.com/1583873/102437949-ae730400-401b-11eb-850c-f28c14a30cf1.png)

**Comment by daretobedifferent18** [comment]
working on it
