### ISSUE TITLE
Roles section overlaps with the Ticket section 

### ISSUE THREAD

**Issue by indexoutofboundsexceptionn** [fossasia/open-event-frontend#6057]
**Describe the bug**
In the users event section there are few columns named as name, date, roles, tickets and etc. If the email addresses mentioned under the roles section are long they will overlap with the tickets section. 

**To Reproduce**
1. Click on 'Combo box near the singed in users email address'
2. Click on 'Manage Events'
3. See error

**Expected behavior**
Email address should not overlap with the tickets section. Should use proper overflow style.

**Screenshots**

![image](https://user-images.githubusercontent.com/75955821/102463742-857d5e00-4071-11eb-9196-85671d58f2d5.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version :  87.0.4280.88 (Official Build) (64-bit)

**Comment by AamirAlam** [comment]
Hello, I would like to work on it

**Comment by Creatoon** [comment]
working on it.

**Comment by Creatoon** [comment]
@mariobehling @iamareebjamal please review PR #6078 , and tell me if there is any mistake,  so that I can improve it.
