### ISSUE TITLE
Virtual Events: Propose and Implement Access Control and Moderator Roles for Jitsi on Open Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6059]
The standard use case of many Jitsi installations is that only certain authenticated users can start a conference. Once started everyone then can join the conference without further authentication, This is a possible option to use on eventyay. However we definitely need access control for users, e.g. ticket holders, joining a session as well.

How to implement this? Please direct to relevant documentation and resources and propose and implement a solution. If changes in Jitsi are needed and a plugin needs to be developed for this please outline ideas and requirements.

Ressources:
* Start and participation only for registered users - In this case, each participant needs a user account in your UCS environment to participate in a Jitsi video conference. This setting is useful if the system is accessible from the Internet, but should only be used by clearly defined users, for example if confidential topics are involved. → For this use case, disable the “Enable Guest Access” in the app settings of Jitsi Meet. https://www.univention.com/blog-en/2020/05/jitsi-meet-and-the-ucs-identity-management/
* https://github.com/jitsi/jicofo
* https://community.jitsi.org/t/prosody-admin-web-with-jitsi/33012

**Comment by surender534** [comment]
I want to work on this issues
