### ISSUE TITLE
Virtual Events Video Tab: Add helper information on page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6062]
Please add helper information on the video tab page to guide users as follows. On the table heading and on the video edit page:
* Microlocations add an (i) icon. When the user scrolls over it show the info "You need to add rooms into the wizard first before they show up here."
* Video Source URL add an (i) icon. When the user scrolls over it show the info "This column shows the original link of the video. We do not recommend to share this link as users can access it without loggin into eventyay.com."
* "Join Video" add an (i) icon. When the user scrolls over it show the info "You can share the links in this columns with attendees of an event. On event or schedule schedule pages attendees of your event will see a Join Video button. These buttons will direct to the links shown here. Only organizers and registered ticket holders will be able to access these links."
* "Room Password" add an (i) icon. When the user scrolls over it show the info "The room password field can be used to communicate a password which is necessary to access online video rooms for example for external video services such a Zoom, Teams and Webex. The need for a password entry depends on the configuration of your video channel. The integrated Big Blue Button video solution in eventyay.com does not need a password as only ticket holders are able to access it. The difference between the password and PIN is that the password option is used for online access while PINs are used to access video rooms through the telephone."
* "Additional Information" add an (i) icon. When the user scrolls over it show the info "Additional Information fields can be used to share information such as phone access, PINs and other video room specific information."

**Comment by Afzal-Ind** [comment]
Working on this.

**Comment by mariobehling** [comment]
Thanks. Please add the info 1. directly on the video tab overview page and 2. on the video create/edit page.

**Comment by Afzal-Ind** [comment]
>add the info 1. directly on the video tab overview page and 2. on the video create/edit page.

Please add a screen shot here to have a vivid info. Thanks

**Comment by iamareebjamal** [comment]
Please explore the features first

**Comment by nlok5923** [comment]
looking into this.

**Comment by Afzal-Ind** [comment]
> looking into this.

Hi, I'm working here.

**Comment by nlok5923** [comment]
Sorry, @Afzal-Ind i created a pr didn't see that you are working here.

**Comment by Afzal-Ind** [comment]
>i created a pr didn't see that you are working here.

It's not good thing for our community. I already mentioned above.
