### ISSUE TITLE
Video Rooms Edit Page: Room Information and alternative field in BBB integration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6063]
There used to be a room name drop down field on the video room edit page. This drop down field disappeared. 
* Instead of getting rid of this area entirely the field should still show the name of the room currently being edited.

Furthermore in the Big Blue Button option of the page there should be a field with information in the area Video Source URL. Please show this as follows:
* Instead of "Video Source URL" show "Video Source" and in the field show "Auto-Generated Big Blue Button Video Room"

![Screenshot from 2020-12-17 18-45-14](https://user-images.githubusercontent.com/1583873/102523770-4adaec00-4098-11eb-80a5-0072f1020cd1.png)

**Comment by iamareebjamal** [comment]
Currently, we were matching the video name to microlocation name/event name. If we allow it to be editable, we won't be able to do that now. So, for example, if someone creates a video for Main Hall, the default name would be Main Hall, but if the user switches to Exhibition, we won't be able to change the room name to the new one because of potential information loss. Is this expected?

**Comment by mariobehling** [comment]
Well, I think we need to talk this through as I do not know all the different options to change room and stream names, but in any case the user should visually see here which room they are assigning an "online video room/channel" to. There does not need to be an option to change the room that is matched to a specific video stream here. We do not need a drop down menu of different rooms, but users need to see the room name that they match here with a video stream.

**Comment by iamareebjamal** [comment]
It is already present for microlocation video room
![image](https://user-images.githubusercontent.com/3874064/102553174-74236880-40e8-11eb-81ec-522ab4c771a6.png)

The above screenshot is most likely of event video room

**Comment by mariobehling** [comment]
Ahh ok, then it only remains to be added to "Event Video Room".

**Comment by mariobehling** [comment]
Ok, thanks for clarifying. I am closing this issue here in favor of https://github.com/fossasia/open-event-frontend/issues/6068
