### ISSUE TITLE
Video Room Edit Form: Show Room without dropdown or Event Video Room, Show video source option for BBB

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6068]
On the specific video room edit online form please change as follows:
* Room name drop down field on the video room edit page of **microlocations**: Do not offer the option of a room drop-down. Instead only show the current room that is being edited.
* Room name drop down field on the video room edit page of **event video room**: Show the field "Event Video Room" in the same place
* Furthermore in the Big Blue Button option of the pages there should be a field with information in the area Video Source URL. Please show this as follows: Instead of "Video Source URL" show "Video Source" and in the field show "Auto-Generated Big Blue Button Video Room"

![Screenshot from 2020-12-17 18-45-14](https://user-images.githubusercontent.com/1583873/102523770-4adaec00-4098-11eb-80a5-0072f1020cd1.png)

**Comment by mharshita** [comment]
Working on it

**Comment by Afzal-Ind** [comment]
Could I collaborate here to try to fix**event video room** and **BBB**? Thanks.

**Comment by Afzal-Ind** [comment]
> * Room name drop down field on the video room edit page of **event video room**: Show the field "Event Video Room" in the same place

Hi, @iamareebjamal, do we need add another field  **Event Video Room**? If yes, what contents should be placed in that field? Thanks.

**Comment by iamareebjamal** [comment]
No

**Comment by Afzal-Ind** [comment]
> No

So, I think we have to add **event video room** field in the place of Room name drop down field? Isn't that?

**Comment by Afzal-Ind** [comment]
> Could I collaborate here to try to fix **event video room** and **BBB**?

Can't make it BBB integration now. Someone else can work on this.

**Comment by mharshita** [comment]
> > Could I collaborate here to try to fix **event video room** and **BBB**?
> 
> Can't make it BBB integration now. Someone else can work on this.

Already working on this

**Comment by sneha281** [comment]
Can I fix this @mariobehling ?Thanks.
