### ISSUE TITLE
Wizard Step 1: Change between location, online etc. moves to top of page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6070]
When an organizer creates an event and clicks on the different options like location, online, mixed etc. the page moves to the top. Expected: The page should not move at all.

![Screenshot from 2020-12-18 14-03-35](https://user-images.githubusercontent.com/1583873/102617818-0acc4580-413a-11eb-8fd8-7e899ed4b75e.png)

**Comment by MeghalBisht** [comment]
working on it
