### ISSUE TITLE
Public Events Page Sidebar Link Widget: Show Extra Links in boxes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6080]
The sidebar widget for social links already has nice boxes with icons. Please change the extra links (defined in wizard step 2) to display the text in a square box as well, e.g. Blog to show up with text "Blog" in a square box.

Also propose a way how a text area should be displayed that is too long, e.g. shortened with dots... or make the font smaller? What is the best option?

![Screenshot from 2020-12-18 23-31-02](https://user-images.githubusercontent.com/1583873/102667439-adf87b80-4189-11eb-8004-a88dc5901bf9.png)

**Comment by nlok5923** [comment]
Working on it sir.

**Comment by sneha281** [comment]
Can I do this @nlok5923

**Comment by nlok5923** [comment]
Hi @sneha281 there's already a pr for this issue you may search another one.
