### ISSUE TITLE
Public Schedule: Only show days with sessions scheduled

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6092]
For events that take place over several days please only show days that have sessions scheduled. Please take care that the scheduler used to put the sessions into the day used by the organizer is not changed.

e.g. compare https://eventyay.com/e/ae73f280/schedule

![Screenshot from 2020-12-20 00-58-38](https://user-images.githubusercontent.com/1583873/102702089-00f03280-425f-11eb-8b3e-fac1c196e8d2.png)

**Comment by nlok5923** [comment]
Working on it sir.

**Comment by Afzal-Ind** [comment]
Could I collaborate here to try to fix?

**Comment by Afzal-Ind** [comment]
> Could I collaborate here to try to fix?

@nlok5923

**Comment by nlok5923** [comment]
Sure @Afzal-Ind

**Comment by Afzal-Ind** [comment]
Hi, I think we need to change this code by adding if statement `  get allDates() {
    const arr = [];
    const difference = (this.model.event.endsAt).diff(this.model.event.startsAt, 'days');
    for (let i = 0; i <= Math.abs(difference); i++) {
      arr.push(moment.tz(this.model.event.startsAt, this.timezone).add(i, 'days').toISOString());
    }
    return arr;`
Did u try this? Thanks.

**Comment by sneha281** [comment]
Can I fix this @Afzal-Ind

**Comment by Afzal-Ind** [comment]
Anyone can try this since we're also working on it.

**Comment by Draco9421** [comment]
I am working on this one.
