### ISSUE TITLE
Schedule page: Sessions which are not during event duration are shown

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#6103]
**Describe the bug**

we create an event and schedule sessions for it. Suppose we have some sessions at last day. now we reduce the duration of event. Suppose we reduce it by one day. The sessions which are present at last date is still shown in schedule page of public event page. Even we can't change the schedule of that sessions from scheduler as scheduler is not showing that last day.

**To Reproduce**
Steps to reproduce the behaviour:
1. create an event.
2. schedule some sessions on last day of event.
3. now reduce duration of event by one day.
4. See error at schedule page. That sessions are still present in schedule page. Even we can't reschedule that sessions from scheduler.

**Expected behaviour**

these sessions must not seen there or we must have access to reschedule them.

**Screenshots**

![new issue](https://user-images.githubusercontent.com/72552281/102808862-08424800-43e7-11eb-9e96-29e160cfe1fc.png)

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Additional context**
compare 
https://eventyay.com/e/6c27e14a/schedule

**Comment by mariobehling** [comment]
I think this case is too complicated to be solved codewise. We could show an error or warning message, but then there are a lot of places where we could show an error message. The basic solution would be that an organizer temporarily changes the event dates and reschedules those sessions. We need to outline this issue in the user documentation. Therefore I am closing this. This is an error created by users, but users are also able to solve it themselves.
