### ISSUE TITLE
Teams: Editing of Team Members Email should not be possible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6110]
The editing of email addresses of existing team members should not be possible on the teams page. When an organizer changes an email it also gets saved even if the organizer clicks "Cancel".

![Screenshot from 2020-12-22 10-33-02](https://user-images.githubusercontent.com/1583873/102873466-7582c700-4441-11eb-87a3-585e2ef168e7.png)

**Comment by Soumi150** [comment]
Working on this.

**Comment by Afzal-Ind** [comment]
Could I collaborate here? working.

**Comment by Soumi150** [comment]
@Afzal-Ind you can take this up.

**Comment by Afzal-Ind** [comment]
> The editing of email addresses of existing team members should not be possible on the teams page. 

@mariobehling Should I remove edit option for existing team members? Thanks.

**Comment by Afzal-Ind** [comment]
>When an organizer changes an email it also gets saved even if the organizer clicks "Cancel".

@iamareebjamal @mariobehling when I refresh the page, it undoes the changes.

**Comment by afzal442** [comment]
@iamareebjamal Any hint? Any reference? Thanks.

**Comment by iamareebjamal** [comment]
Check old PRs where empty role invites were fixed

**Comment by afzal442** [comment]
> Check old PRs where empty role invites were fixed

Thanks, looking into this.

**Comment by afzal442** [comment]
@iamareebjamal Sir, could I remove edit options for role-invite? Thanks.

**Comment by iamareebjamal** [comment]
I think so

**Comment by afzal442** [comment]
> I think so

I was also thinking this way while observing this issue over and over again. So for now, I draft a PR for this.
