### ISSUE TITLE
Organizer Attendee Overview Page: Implement Sorting with Latest Orders On Top of Table

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6111]
The sorting of attendees on the attendee page is unclear. Please show the latest orders on top of the table by default.

Also ensure that ticket name sorting icon is on the same line as the text in the table heading.

![Screenshot from 2020-12-22 16-55-02](https://user-images.githubusercontent.com/1583873/102907532-78e47580-4476-11eb-8f0c-e63da06d0163.png)

**Comment by mharshita** [comment]
Working on it

**Comment by rithgan** [comment]
I can work on this issue

**Comment by daretobedifferent18** [comment]
@mariobehling also currenlty also date and time is not sorted properly.
![Screenshot from 2020-12-23 18-14-50](https://user-images.githubusercontent.com/71120226/102997710-bebf3d80-454b-11eb-84ad-bdb158df5225.png)

**Comment by Creatoon** [comment]
@daretobedifferent18 Check-In button is also covering emails , We should add a "word-break" class on the email cell.
