### ISSUE TITLE
Public Event Sidebar: Do not display icons in left menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6118]
The desktop page has a lot of UI icons and elements already. We need to ensure the UI is not overloaded. Therefore please do not show icons on the desktop side, but leave the icons on the mobile view.

![Screenshot from 2020-12-23 09-27-22](https://user-images.githubusercontent.com/1583873/102978709-374edb80-4505-11eb-9c93-1b36a24a55fb.png)

**Comment by MeghalBisht** [comment]
Following up
