### ISSUE TITLE
Standard Search only searches for name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6119]
The standard search only searches for the name of an event. Is uses the parameter as in the example: https://eventyay.com/explore?event_name=summit

Expected is that the search is performed across all parameters, e.g. if someone searches for a speaker name all events with that speaker should show up.

**Comment by Creatoon** [comment]
working on it.

**Comment by iamareebjamal** [comment]
Will be implemented once search backend is switched to redisearch, not solvable now

**Comment by Creatoon** [comment]
@iamareebjamal Ok sir , thanks for this information
