### ISSUE TITLE
Mobile Screens: Show Twitter Area as Collapsible/Extendable Area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6121]
On mobile pages the Twitter area is diverting the attention of the user a bit. On the other hand the Twitter area potentially provides important updates for attendees of an event. Moving the Twitter area to the bottom of the page is not suitable as there are areas which load on scrolling. The best solution for now seems to be therefore as follows:
* change the Twitter area into a collapsible/extendable area with a triangle arrow in front. Show it like that: `▶ Recent Tweets`
* make the area collapsed by default
* when expanded show a down arrow: `▼ Recent Tweets`

![Screenshot from 2020-12-23 10-51-56](https://user-images.githubusercontent.com/1583873/102984398-d1b31d00-450d-11eb-847b-bcad9c595a36.png)

**Comment by chelsi-001011** [comment]
Is this issue open to work upon? I want to take it up.
