### ISSUE TITLE
Mobile Views: Make Event Dropdown Menu Stay on Top When user Scrolls Down Further

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6122]
Many pages have this feature where a special menu stays on top of the page when a user scrolls down. Please implement the same thing for the drop-down event menu on public event pages.

When the user scrolls down keep the menu on top of the screen. When the user reaches the area "Tickets" show the menu item "Tickets" in the menu and so forth. Implement this on all public event pages for the mobile view.

![Screenshot from 2020-12-23 11-03-47](https://user-images.githubusercontent.com/1583873/102985052-d4624200-450e-11eb-885f-1f2121e7e396.png)

**Comment by ranjitkshah** [comment]
working on it

**Comment by daretobedifferent18** [comment]
@mariobehling could you pls tell any one page where this type feature is already present. I am unable to find it

**Comment by mariobehling** [comment]
This is not implemented on our app yet.

**Comment by FlashV998** [comment]
I am working on it ,feel free to drop PR if I won't

**Comment by chait04** [comment]
is this feature is only for mobile view

**Comment by tanay123456789** [comment]
working on this

**Comment by tanay123456789** [comment]
any other person can take this issue

**Comment by Deepak-032** [comment]
I want to work on this issue. Please assign this to me!!

**Comment by Deepak-032** [comment]
I'm working on this issue..
