### ISSUE TITLE
Ticket Order for Free Tickets not Possible on Some Events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6128]
Ticket order of free tickets on https://eventyay.com/e/2daa7007 is not possible for my account.

Please see screenshot below.

![Screenshot from 2020-12-24 05-42-09](https://user-images.githubusercontent.com/1583873/103061236-032df600-45ab-11eb-9576-28887508d989.png)

**Comment by mariobehling** [comment]
Also not possible for paid tickets.

![Screenshot from 2020-12-24 05-45-09](https://user-images.githubusercontent.com/1583873/103061305-3a9ca280-45ab-11eb-9f94-429f4e7a31af.png)

**Comment by iamareebjamal** [comment]
"Missing required fields ['age_group', 'gender', 'job_title']"

But the attendee fields are not enabled and not required

**Comment by maze-runnar** [comment]
it's higly unlikely because i thought some how it happened that field was not included but required. so i tried `{{# if field.isRequired}}{{field.fieldIdentifier}}{{/if}}` but the fields are not actually there they are not included not required somehow.

**Comment by iamareebjamal** [comment]
Server issue, not frontend

**Comment by maze-runnar** [comment]
I have tried 2nd method too. But it's working fine in that case too.
created an event -> enabled attendee form -> make some fields required -> saved event -> editing attendee form in wizard again -> disabeld it -> ordering ticket -> working fine .

**Comment by iamareebjamal** [comment]
Checking what's the issue

**Comment by iamareebjamal** [comment]
It is the second case, some fields were made required and form was disabled but fields remained required.
