### ISSUE TITLE
Ticket Buying Process: User suddenly redirected to Expired Ticket Page even though User has abandoned process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6129]
When a user starts the ticket buying process the system keep it active for 15 minutes. After that it shows "Expired". When the user moves on to other places on the platform and abandons the ticket process and the speaker is on a completely different page, suddenly the "Expired Page" shows up completely out of contest.

Expected; A user should only be redirected to the "Expired Page" if they are on the ticket order page and has not bought a ticket within 15 minutes.

![Screenshot from 2020-12-24 05-57-23](https://user-images.githubusercontent.com/1583873/103062072-7b95b680-45ad-11eb-9b1e-491dcb206ae8.png)

**Comment by maze-runnar** [comment]
looking into it

**Comment by iamareebjamal** [comment]
setTimeout should be cancelled on component unload

**Comment by maze-runnar** [comment]
ok
