### ISSUE TITLE
Virtual Events: Implement a different slide-in/out button for video sidebar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6131]
Please implement a slide button in a more similar way to Gmail in style and position (next to screen edge), but make the slider button square with rounded corners. Also change the X closing button to an inverse < slider button.

Compare
![Screenshot from 2020-12-24 10-34-22](https://user-images.githubusercontent.com/1583873/103080017-48671d80-45d5-11eb-8faa-55426d603d5d.png)

![Screenshot from 2020-12-08 15-05-35](https://user-images.githubusercontent.com/1583873/101494060-27f95b00-3967-11eb-9849-20d65034bd62.png)

**Comment by nlok5923** [comment]
Working on it
