### ISSUE TITLE
Team Page: Organizer/Owner is  not able to edit role-invite

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#6132]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'team tab of event'
2. Try to edit the a role-invite.
3. See error

**Expected behaviour**

role-invite should be edit

**Screenshots**

![team issue](https://user-images.githubusercontent.com/72552281/103084331-bd9e1700-4604-11eb-8962-dbe5a1734206.png)

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Additional context**

**Comment by afzal442** [comment]
Hi, I think we need to disable the edit part of email address as per previous issue. Thanks.

**Comment by sachinchauhan2889** [comment]
> Hi, I think we need to disable the edit part of email address as per previous issue. Thanks.

you are talking about #6110. I think you haven't read that issue carefully. we need to disable editing of email of existing team member i.e. the member who accepted role invite must be non-editable.

**Comment by iamareebjamal** [comment]
Backend has removed the feature of editing role invite. It makes no sense. After accepting an invite, editing it makes no change. And before accepting, people can just delete and resend the invite

**Comment by iamareebjamal** [comment]
Relevant: https://github.com/fossasia/open-event-server/issues/7235
