### ISSUE TITLE
Virtual Event: Streamline Participation and In-App Experience in Online Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6135]
What is the easiest way to create a full online event experience with schedule, speaker and event information pages? We already have these pages, but they are not included in the "video app experience" yet. We probably do not want to start replicating the pages. So, what is the easiest way to include these pages without getting into loops and confusing users?

Here is an approach. For the online event experience with the iframe and videos, we can include the event pages such as the speaker page and make it accessible from the UI, but we need to limit the access to the eventyay area to make the experience consistent. 

So, basically when the user is within the iframe, the user is participating in the event. When the user is outside of the iframe he/she is just viewing the event (but not participating!). 

Therefore we need to make the following changes:
1. When the user clicks on a session "Join Video" change the implementation to open the link in the same tab and show a loading icon and the message _"Joining Event"_
2. After the user joined the event the user has access to the event information through the sidebar and can access different pages. The user is now participating in the event itself and accesses all info through the "app UI". This should work as follows:
  * Open all external links in a new tab (let's just implement this across eventyay by default)
  * Change the top bar as follows: When the user clicks the "eventyay" logo they leave the app and go to the frontpage
3. From the event name on the left side iframe sidebar direct to the info page of the event with the sidebar instead of opening a new tab.
4. When no schedule is available also do not show the button on the sidebar.

![Screenshot from 2020-12-24 11-04-26](https://user-images.githubusercontent.com/1583873/103085623-81f25580-45e2-11eb-9351-a06447103a87.png)

**Comment by iamareebjamal** [comment]
We cannot show jitsi/BBB and the site itself in the iframe. Only one of them can be part of an iframe

**Comment by mariobehling** [comment]
Yes, true, but it does not have to be an iframe by itself. The question is how to get the UI experience for the user.
