### ISSUE TITLE
My Ticket Page: Add links and additional data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6138]
On the my ticket page the tickets are missing some data and links. Please add the following:

Show all basic data
* from to time and date
* Online event or location or both for mixed events

Add links
* Link event name to event page
* Order number of order

Compare https://eventyay.com/my-tickets

![Screenshot from 2020-12-24 16-06-13](https://user-images.githubusercontent.com/1583873/103095923-8dee0f80-4602-11eb-9fa2-80d3d23658c3.png)

**Comment by Soumi150** [comment]
Working on this.
