### ISSUE TITLE
Need Adjustment in elements while seeing in mobile view

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#6146]
![Screenshot (111)](https://user-images.githubusercontent.com/58654018/103147749-3ffe1680-477e-11eb-925e-4312af8532cb.png)
**Describe the bug**

There should be a gap between these three buttons or need proper alignment

**Screenshots**

**Comment by himanshujaidka** [comment]
Working...

**Comment by afzal442** [comment]
Taking up this.

**Comment by himanshujaidka** [comment]
> Taking up this.

FIFO, I think that u should know 🙄

**Comment by afzal442** [comment]
@iamareebjamal Could I create a PR for this to enhance other things left as well?

**Comment by afzal442** [comment]
@iamareebjamal sir u can close my PR if you have reviewed since it has resolved the same. Thanks.
