### ISSUE TITLE
My Tickets Page: Standardize Views similar to Frontpage and Add Ticket Names and Numbers in Order

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6148]
The my tickets page is now more similar to the frontpage. However colors and line spaces are different for no apparent reason. Therefore please change the following:
* Make font style and colors for all cards same as on frontpage (but keep full width for cards)
* Make spacing same as on frontpage (except for first line in order to keep the card height)
* Show number of tickets and ticket names of the order, e,g. 1 x Community Ticket, 2 x Workshop Tickets etc. Compare to eventbrite. How are they doing it? Propose and implement a suitable style.

![Screenshot from 2020-12-26 19-07-23](https://user-images.githubusercontent.com/1583873/103157118-152cb600-47b0-11eb-8735-f342dbf0ba67.png)

**Comment by chinmaym07** [comment]
Hey @mariobehling  can i work on this issue .?

**Comment by himanshujaidka** [comment]
I am working

**Comment by himanshujaidka** [comment]
@mariobehling sir 
we have to make the both frontpage and ticket page the same? means in terms of font and color?

**Comment by maze-runnar** [comment]
> Show number of tickets and ticket names of the order, e,g. 1 x Community Ticket, 2 x Workshop Tickets etc. Compare to eventbrite. How are they doing it? Propose and implement a suitable style.

eventbrite shows number of attendeed with the ticket- 

![Screenshot from 2020-12-28 09-58-33](https://user-images.githubusercontent.com/56407566/103189599-685b5180-48f3-11eb-808a-52450157d9ab.png)

**Comment by himanshujaidka** [comment]
> > Show number of tickets and ticket names of the order, e,g. 1 x Community Ticket, 2 x Workshop Tickets etc. Compare to eventbrite. How are they doing it? Propose and implement a suitable style.
> 
> eventbrite shows number of attendeed with the ticket-
> 
> ![Screenshot from 2020-12-28 09-58-33](https://user-images.githubusercontent.com/56407566/103189599-685b5180-48f3-11eb-808a-52450157d9ab.png)

are You working on this?

**Comment by maze-runnar** [comment]
no you are.

**Comment by himanshujaidka** [comment]
> no you are.

if u r interested then we should collaborate

**Comment by himanshujaidka** [comment]
> no, you are. I was just clarifying how things are supposed to be done.And this is a high priority so try to complete is asap.

pls give your gitter id

**Comment by Naman-1234** [comment]
@himanshujaidka  I would like to collaborate on this if you want

**Comment by himanshujaidka** [comment]
> @himanshujaidka I would like to collaborate on this if you want

provide your gitter id
