### ISSUE TITLE
Wizard Step 1: Ticket Error for "Ticket End Date" even though end date is before Event End

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6150]
Adding new tickets for an event here https://eventyay.com/events/fa96ae2c/edit/basic-details with the following dates of the event and end of ticket sales is not possible due to error message as below. Expected: It should be possible to sell tickets until the event ends.
Event End Date: 03-21-2021 23:59
Ticket End Date: 03-21-2021 23:00

Error Message:
* Ticket end date cannot be greater than event end date

Even if the end date was wrong the message should say something like:
* End of ticket sales date of [ticket names of erroneous tickets] cannot be after end of event date.

Screenshot
![Screenshot from 2020-12-26 22-03-39](https://user-images.githubusercontent.com/1583873/103159169-457f4f00-47c6-11eb-9051-02b4dc2d425a.png)

**Comment by nlok5923** [comment]
Working on it

**Comment by maze-runnar** [comment]
@mariobehling it's working. As far the error message is concern, changing it.
https://user-images.githubusercontent.com/56407566/103163013-1d233f00-481e-11eb-9f2a-6d6af1550ec7.mp4

**Comment by iamareebjamal** [comment]
@maze-runnar Change timezone to something else in all time related issues to reproduce them

**Comment by MeghalBisht** [comment]
I cannot reproduce the above error but I can **add a ticket end date after the event end date.**
Steps -
1. add a ticket with a date less than event end date 
2. save & go to next step
3. click previous
4. change the ticket end date to a date longer than the event date
5. save the event again

Expected : the check for ticket date longer than event date should be performed every time someone edits the wizard step 1. 

Currently :
![2020-12-27 (1)](https://user-images.githubusercontent.com/61330148/103165061-1d7d0380-4839-11eb-87d0-6cd174c41fce.png)

**Comment by mariobehling** [comment]
Issue is still there

**Comment by mariobehling** [comment]
![Screenshot from 2021-01-07 10-23-38](https://user-images.githubusercontent.com/1583873/103875280-833b7c00-50d2-11eb-9e4c-f653ba376e82.png)
![Screenshot from 2021-01-07 10-23-24](https://user-images.githubusercontent.com/1583873/103875284-846ca900-50d2-11eb-8a1c-62aea401712a.png)
![Screenshot from 2021-01-07 10-25-20](https://user-images.githubusercontent.com/1583873/103875392-a8c88580-50d2-11eb-85d4-565aa24861bb.png)

**Comment by iamareebjamal** [comment]
Similar: #6259
