### ISSUE TITLE
Need little enhancement in mobile view

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#6154]
**Describe the bug**

The font is not responsive in mobile view

**Screenshots**

![Screenshot (113)_LI](https://user-images.githubusercontent.com/58654018/103170672-0e637900-486c-11eb-8894-b6157026f00d.jpg)

**Comment by himanshujaidka** [comment]
@mariobehling I think it is the same as 6148 issue

**Comment by akshatsaxena11** [comment]
Can I work on this one..?

**Comment by Creatoon** [comment]
working on this

**Comment by Creatoon** [comment]
@himanshujaidka In the development code , it is working just fine , page is responsive.

**Comment by Soumi150** [comment]
Working on this.
