### ISSUE TITLE
Mobile View: Search bar needs adjustment

### ISSUE THREAD

**Issue by afzal442** [fossasia/open-event-frontend#6157]
**Describe the bug**

The search bar currently doesn't cover the whole area of nav.

**Expected behaviour**

The search bar should cover the area of navigation.
**Screenshots**

![c2](https://user-images.githubusercontent.com/11625672/103200772-43c3a180-4914-11eb-83ef-b3403bb3109f.JPG)

**Comment by afzal442** [comment]
@mariobehling plz verify this issue. Thanks.

**Comment by robin025** [comment]
can i work on this..!!

**Comment by afzal442** [comment]
> can i work on this..!!

I think this issue first needs to be verified and then later you can try. So, for now, explore other issues.

**Comment by akshatsaxena11** [comment]
Please...Can I work on this one....!!

**Comment by afzal442** [comment]
See above comment. Thanks.

**Comment by mariobehling** [comment]
No need.
