### ISSUE TITLE
Incorrect filter for fetching events in index route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#616]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The current filter only shows the events which are not yet started, but not the ongoing events.

**Expected behavior:**
Ongoing events must be fetched and shown on the index route

@fossasia/open-event-frontend 
I would suggest that we should have different columns to differentiate the events
- Ongoing events
- Upcomming events
- Call for speakers

**Comment by niranjan94** [comment]
@geekyd stick the same implementation at eventyay.com.

- First section shows both live and upcoming. (Live first). 
- And call for speakers section.

This is inline with other event websites such as eventbrite
