### ISSUE TITLE
Event page: enhancement in additional info icon.

### ISSUE THREAD

**Issue by nlok5923** [fossasia/open-event-frontend#6165]
**Describe the bug**
Addition info icon in the event page should not be bigger then the font size.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any event page

**Expected behaviour**

Additional info icon will look good if it is circular as well as same size as of font.

**Screenshots**

![image](https://user-images.githubusercontent.com/56120084/103260916-77aacf80-49c5-11eb-8f3e-96c16b15730a.png)

**Desktop (please complete the following information):**
all
**Smartphone (please complete the following information):**
all

**Additional context**

This circular icon will look good:
![image](https://user-images.githubusercontent.com/56120084/103260963-b5a7f380-49c5-11eb-9722-7fb2b141c7c3.png)

**Comment by nlok5923** [comment]
i would like to work on it if it is valid.

**Comment by Bhavik-Ardeshna** [comment]
I would like to work on this issue...

**Comment by YashV1729** [comment]
Is it solved? I would also like to give it a try in resolving this issue.

**Comment by Draco9421** [comment]
working on it
