### ISSUE TITLE
Virtual Events: Add "Join Event" button for Online and Mixed Events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6170]
Please implement the following
* Add a "Join Event" button next to the "Join Video" button on the right side bar and on the bottom area of public event pages. 
* Direct the ticket holder to the public event page with the event side panel expanded.
* Also show the button for not-logged in users or users without a ticket, but for them when they click on it display a pop-up "You need to login or get a ticket for this event before you can join it online. [Ok]"
* Instead of the "Join Event" button show a button "Active" when the user is on a page with the side panel active already. When the user clicks the button "Active" expand the side panel if it is not expanded.

Requirement for the Join Event button to appear:
* There must be at least one video room defined

![Screenshot from 2020-12-30 08-22-48](https://user-images.githubusercontent.com/1583873/103336491-a03fd180-4a78-11eb-986c-936a6a3bb1c2.png)

**Comment by HyperHarshad27** [comment]
May I do this?

**Comment by iamareebjamal** [comment]
What's the difference between Join Video and Join Event

**Comment by mariobehling** [comment]
Join Video directs to the Event Video Room itself, if it is configured. If it is not configured there would not be a "Join Video" button on the event pages.

Join Event shows up if the user has either or both added an Event Video Room and Session Video Rooms. Join Event directs to the event main page but includes the right side panel. It means the user is now actively participating in an event. (We can use this at a later time for statistics, but this is out of scope for now.)

**Comment by mariobehling** [comment]
Sorry, I meant left-side panel.

**Comment by himanshujaidka** [comment]
Working

**Comment by himanshujaidka** [comment]
@iamareebjamal sir, I got the logic but I need little help, that I want to know the name of the function that should be called after implementation of my logic

**Comment by iamareebjamal** [comment]
Working
