### ISSUE TITLE
Virtual Event: Do not show sidebar panel after user has left the event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6171]
When the user is on an event with the sidebar active and clicks on the top left logo "eventyay" they are leaving the event. When the user goes back to the event page afterwards it would be expected that the user has to join the event again by clicking on the "Join Video" or "Join Event" button. This means when the user visits the event page again (after leaving it) to some other outside event areas there should not be a side panel.

Currently, there is a side panel even after the user has left the event and then returns to the event pages. The event pages should only have the panel after the user clicks again "Join Video" or "Join Event".

**Comment by afzal442** [comment]
@mariobehling when the user clicks on close tab on side panel, it needs to redirect the page to event page. Hence closing the side panel. Isn't that?? Thanks.
