### ISSUE TITLE
Virtual Events: Open "Join video" in same tab for "in-house" streams

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6172]
Please implement the following for "Join Video" links:
* Open "Join Video" in the same tab for streams "in-house" streams with our side panel. Show external streams in another tab.

Implement this in the following places:
1. On the right sidebar "Join Video" link
2. For the "Join Video" links in the schedule

**Comment by afzal442** [comment]
Taking up this.

**Comment by afzal442** [comment]
@mariobehling do you mean external streams for links in the schedule??

**Comment by iamareebjamal** [comment]
> do you mean external streams are for links in the schedule

I don't even know what your question is

**Comment by afzal442** [comment]
Actually I confused between external streams and inhouse streams! Plz elaborate.

**Comment by iamareebjamal** [comment]
Video Streams with jitsi or BBB channel are integrated streams, otherwise it is external stream

**Comment by afzal442** [comment]
unable to fetch it for now. anybody can try this since it is a priority high issue.
