### ISSUE TITLE
Virtual Events: Implement Zoom in iframe

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6174]
Zoom is currently not implemented to be used in an iframe. Please implement this feature.

An example of where this is implement is Wordpress. A plugin is here https://wordpress.org/plugins/video-conferencing-with-zoom-api/

Another relevant article could be this one here https://kloudless.com/blog/the-quarantine-chronicles-embedding-zoom-video-on-a-web-server/

**Comment by inomag** [comment]
Hi there, can I work on this ?

**Comment by Sayantani-sunshine** [comment]
Hello...Is this issue open?

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?
