### ISSUE TITLE
Virtual Events: Add option to include MS Teams in an iframe

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6175]
It is possible to embed MS Teams on a website. Please add the option to include it in our solution as an iframe.

**Comment by ShubhamPatel33** [comment]
Hello sir i would like to take this issue.

**Comment by avanisingh0105** [comment]
i am willing to know - what is the need of embedding ms teams/zoom iframe explicitly, if the virtual event were to be happen on ms teams/zoom then wouldn't the join video link be already  redirecting to ms teams/zoom???
#6175 #6174
