### ISSUE TITLE
ticket sometimes doesn't appear in my-ticket section

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#6185]
**Describe the bug**

ticket sometimes doesn't appear in my-ticket section
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to my-tickets
2. refresh page
3. tickets are disappeared
**Expected behaviour**
they should show tickets

**Screenshots**
before refresh - 
![Screenshot from 2020-12-31 11-25-54](https://user-images.githubusercontent.com/56407566/103396757-fa18c800-4b5a-11eb-857d-abbbabe7104a.png)
after refresh or even sometimes without refresh tickets don't appear at all
![Screenshot from 2020-12-31 11-23-58](https://user-images.githubusercontent.com/56407566/103396759-fc7b2200-4b5a-11eb-8e9e-321121cbf22c.png)

**Comment by iamareebjamal** [comment]
Same is happening in all lists. Like Manage Events, Manage Sessions, etc

**Comment by sachinchauhan2889** [comment]
when this occur, console shows this. 
![issue new](https://user-images.githubusercontent.com/72552281/103398585-5d0e5d00-4b63-11eb-9751-fd5dd7df9301.png)

**Comment by mariobehling** [comment]
Thanks, I am experiencing this regularly too on different lists.

**Comment by maze-runnar** [comment]
@iamareebjamal i guess the problem is with `store        : this.authManager.currentUser`. it is used at 3 places(my-sessions, my-tickets and notifications) and all of them are not working.

**Comment by iamareebjamal** [comment]
I suspected this as well. However, `this.authManager.currentUser` is not undefined

**Comment by iamareebjamal** [comment]
For quick solution, disable caching user and see if it fixes it

**Comment by maze-runnar** [comment]
it worked.

> For quick solution, disable caching user and see if it fixes it

**Comment by maze-runnar** [comment]
so should i create a PR with this quick solution or there would be any alternate?

**Comment by iamareebjamal** [comment]
Yes, please create a PR and later I'll think of a better way to cache the user

**Comment by maze-runnar** [comment]
ok
