### ISSUE TITLE
Video Tab: Icons disaligned when event or video room has a long name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6187]
In the video tab overview first column the icons are disaligned when an event or video room name has a longer name. Please ensure the icons stay aligned.

![Screenshot from 2020-12-31 09-08-26](https://user-images.githubusercontent.com/1583873/103401316-98e7f900-4b48-11eb-8534-cff9dc6d85cd.png)

**Comment by afzal442** [comment]
looking into this.

**Comment by ritik307** [comment]
@afzal442 you still working on it? If not would start looking into this.

**Comment by mariobehling** [comment]
The icons are still not fitting into the design. As far as I see there are two options a) break any text that appears in front of the icons or b) position the icons right below the event or room name in the first row. @iamareebjamal What do you recommend?

![Screenshot from 2021-01-08 16-52-13](https://user-images.githubusercontent.com/1583873/104035469-7605b680-51d2-11eb-8dde-f6417a52a560.png)

**Comment by mariobehling** [comment]
The icon area seems to be even more buggy now. Clicking on the edit icon shortly shows up the "Add Video" icon and switching back and forth between pages also suddenly only shows the add video icon.

![Screenshot from 2021-01-08 17-33-41](https://user-images.githubusercontent.com/1583873/104040463-f549b900-51d7-11eb-84a3-388e72c08c2d.png)

**Comment by iamareebjamal** [comment]
The above issue is a different one

**Comment by mariobehling** [comment]
Ok, understand, but it appeared for me only after the last change and the question is how much smaller should we make issues that address a certain area? We need this video columns to work smoothly. It does not make sense to address challenges in the same area in one way and then in another way. These kind of issues are just too tiny. I think the problem is in this area is already apparent and if one dev could solve it together it would be good.

**Comment by iamareebjamal** [comment]
This issue is much bigger and unrelated to the icons, because it is present in all the tables of the system. Moving back and forth breaks the table everywhere, not just here https://github.com/fossasia/open-event-frontend/issues/5176

So, even if we want to, we cannot fix it in the same PR as the icon one, and then, even the icon bug won't get resolved, because then the linked issue would be much bigger and much harder to solve

**Comment by mariobehling** [comment]
Yes, that is a big problem.

**Comment by afzal442** [comment]
In this case my solution would be better if u consider the icons position right below the event or room name in the first row. Thanks.

**Comment by afzal442** [comment]
Oops sorry for that.
