### ISSUE TITLE
Virtual Event Side Panel: Footer overlaps it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6188]
The footer on the schedule, speaker etc. page overlaps the virtual event side panel. Please fix it.

![Screenshot from 2020-12-31 09-00-41](https://user-images.githubusercontent.com/1583873/103401517-6a1e5280-4b49-11eb-8eef-76011f3c0a48.png)

**Comment by ranjitkshah** [comment]
working...
