### ISSUE TITLE
Grammatical errors in documentation file

### ISSUE THREAD

**Issue by suyash-ag09** [fossasia/open-event-frontend#619]
**I'm submitting a ...**  (check one with "x")
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
There are certain grammatical mistakes in the documentation file

**Steps to reproduce:**
Simple grammatical changes have to be made.

**Comment by geekyd** [comment]
Closing via #610
