### ISSUE TITLE
Organizer Video Tab: Ember Errors and Column Inconsistencies 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6190]
The organizer video tab still has some issues. Please resolve them:

* Clicking on the table heading, e.g. in the video source URL area results in an ember error and moves the "Additional Information" content to the "Password" column
* The column Video Source URL still shows "https". Please take it out and reduce a bit the width of URL box in column Video Source URL (We need the feature to enable organizers to see the source, but we do not want to have it very big and prominent).

![Screenshot from 2020-12-31 09-47-19](https://user-images.githubusercontent.com/1583873/103402635-c2575380-4b4d-11eb-9a48-07c0566612a7.png)

**Comment by maze-runnar** [comment]
this kind of error is at most of places in tables.

**Comment by maze-runnar** [comment]
looking into this.

**Comment by maze-runnar** [comment]
here is how `state` column is changing  in admin event section or events/live of user: 

- first click on header of roles column, `state` column changes to some <ember:xyz>
![Screenshot from 2021-01-08 16-10-11](https://user-images.githubusercontent.com/56407566/104006225-363bd080-51cc-11eb-9fe1-88835a9d41a7.png)

- second click on header of `roles` column again  `state` changes to normal
![Screenshot from 2021-01-08 16-10-19](https://user-images.githubusercontent.com/56407566/104006396-726f3100-51cc-11eb-8535-a93992c22db9.png)

- third click on header of `startsAt` column and state is changed to date 
![Screenshot from 2021-01-08 16-10-24](https://user-images.githubusercontent.com/56407566/104006489-916dc300-51cc-11eb-80b3-6c4e17029a98.png)

**Comment by iamareebjamal** [comment]
Look at the click handlers of the headers and what they are doing

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
I just changed ```
 <t.head
        @sortFunction={{null}}
        @columns={{this.columns}}
        @enableReorder={{true}}
        @sorts={{this.sorts}}
        @onUpdateSorts={{action (mut this.sorts)}} as |h|>
```

to 
```
 <t.head
        @columns={{this.columns}}
     as |h|>
```

for testing only, but it has no effect. Header is still showing same behaviour
