### ISSUE TITLE
Mobile View: Avoid bottom scroll bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6194]
In mobile view a numbers of pages have a bottom scroll bar. Please test this with an actual phone. It doesn't always show up on a browser.

![Screenshot_20201231_210317_com android chrome](https://user-images.githubusercontent.com/1583873/103424542-3b39c800-4bad-11eb-9ddd-b1c189c007d7.jpg)

**Comment by Creatoon** [comment]
working on it

**Comment by ARKEOLOGIST** [comment]
@mariobehling Is it possible to mention some of the pages which have it? I'll have a look.

**Comment by Creatoon** [comment]
@mariobehling please review it
