### ISSUE TITLE
Wizard Step 4 and Video: Extend sponsorship wizard step 4 with options for exhibitors, video and slides

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6199]
As we are progressing with online events we can now extend the sponsorship wizard step 4 to include options for exhibitors (that either are also sponsors or which are not sponsors) and prepare for video rooms. Therefore please implement the following:

Sponsorship Wizard Step 4: Implement the outlined changes and add options:
* Rename Sponsorship wizard step to "Sponsors and Exhibitors" in all areas including the wizard itself and the event dashboard
* Add Form element with the option a) sponsor and exhibitor (pre-selected), b) sponsor, c) exhibitor. 
   * If a partner has been selected as sponsor show them in the sponsors list on the public event page
   * If a partner has only be listed as an exhibitor do not show them in the sponsors list (and only show them on "Exhibition Page" as below)
* Add form field "Location" where organizers can enter a location info as text for in-person events, e.g. a booth location
* Add option to add a slide deck into the wizard for each sponsor or exhibitor

Exhibition Page
* Create a new page "Exhibition" that is listed on public event pages on the left side menu. On this page list all exhibitors with their logo, name, link, description, a link to a slide deck and video room if video room is added (as outlined below)
* In the list only show "Location" column if this is a location based or mixed event
* Only show the exhibition page if at least one exhibitor is activated

Organizer Video Page
* On the video tab page add a third section "Exhibition Rooms" below the two existing sections and list all exhibitors here (just like we list rooms as microlocations above)
* If an exhibition room was defined show the link "Join Video" on the exhibitors list on the newly created exhibition page.
* On the side panel for online event add a button "Exhibition" next to schedule that links to the "Exhibition" page.

When making these changes, please consider that in future we would probably want to enable sponsors to add this information themselves after they bought a sponsorship option. We still need to develop the concept how this should work exactly.

**Comment by himanshujaidka** [comment]
Working

**Comment by Jahnavi-Jonnalagadda** [comment]
@himanshujaidka, are you done working on this?

**Comment by himanshujaidka** [comment]
> @himanshujaidka, are you done working on this?

Would you like to collaborate?

**Comment by Jahnavi-Jonnalagadda** [comment]
There is another issue I've chosen which is in sync with this and have to be resolved after this issue is resolved. So would like to know when you will be able to complete this

**Comment by himanshujaidka** [comment]
> Working

drop this issue because it needs changes at server side
