### ISSUE TITLE
Implement "Exhibitions & Sponsoring" Page for Sponsors and Exhibitors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6206]
At the moment only organizers are able to change the listing information of sponsors and exhibitors. Please add an email field for each sponsor or exhibitor to the wizard step 4 and the option to invite a sponsor/exhibitor to edit this entry. Please further implement:
* Show the entries for a sponsor in the drop-down menu under a link "Exhibitions & Sponsoring". Add the link below "My Sessions".
* Create a dedicated page with a table where the sponsor/exhibitor participates or participated in. Include all relevant details of the event and the info if this is an exhibition participation, sponsorship or both
* Create a subpage with the options to edit the information of the company. Some fields should not be editable here by the sponsors/exhibitors themselves (only by organizers) specifically: Level and Type.

Following issue https://github.com/fossasia/open-event-frontend/issues/6199

![Screenshot from 2021-01-01 17-22-01](https://user-images.githubusercontent.com/1583873/103442522-34678f80-4c57-11eb-9a08-4bc45c0cb27a.png)

**Comment by Manish-bat** [comment]
i wanna work on this issue.Please assign this to me and since in new to this to me and sice i am new to this repo .
So Please guide me through!

**Comment by Manish-bat** [comment]
There is no one.

**Comment by mariobehling** [comment]
As the implementation of sponsors has changed we will need this feature handled in a different way. I will open an issue about this later.
