### ISSUE TITLE
Event Roles: Implement Role "Moderator" for events with focus on online events/video rooms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6208]
Please implement the role moderator for events. For the moment we focus on online events. The goal is to enable moderators to see the different event rooms in the same way as event organizers. To make this work we need the following:

1. Add option to invite moderators to the team page and on the team sub page add a column "Moderators" and the info about the role permissions.
2. Show moderators who accept invite the event listing on the "Manage Events" dashboard without the Tickets Column
3. Show them an events dashboard with the following boxes 
  a) Events checklist (without links access to wizard)
  b) Overview box
  c) Sessions and Speakers box. 
  d) Team Members without Edit button. Do not show any other boxes. 
4. On the events pages do not show an option to edit, publish or unpublish the event.
5. Show them the tab "Video" (do not show any other tab except Overview and Video). On the video tab only show items as follows:
  a) No option to edit, publish or unpublish the event
  b) There should not be an option to add a room or to delete or edit a room
6. Add the role "Moderator" to in-house event rooms (Jitsi and BBB). (Consider that in future we might have to limit the moderator role to specific rooms or sessions possibly when implementing this).
7. Ensure that upgrading of a moderator to the Co-organizer role and vice versa works.

![Screenshot from 2021-01-01 17-46-27](https://user-images.githubusercontent.com/1583873/103442929-983f8780-4c5a-11eb-978d-1aaf74177d3d.png)

**Comment by Creatoon** [comment]
Working
