### ISSUE TITLE
event: save as draft shows unexpected error

### ISSUE THREAD

**Issue by ranjitkshah** [fossasia/open-event-frontend#6210]
**Describe the bug**
shows unexpected behaviour ( all required fields are filled ) please see the video
https://www.loom.com/share/475a4bb3abcd4c5c925ee6db2af44b23

**Expected behaviour**
it should save the event as a draft

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iamareebjamal** [comment]
Same as #6218
