### ISSUE TITLE
If the field will not be empty then why there is on-off button

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#6214]
**Describe the bug**

The on-off switch should not be there if the field is mandatory

**Screenshots**

![Screenshot (118)](https://user-images.githubusercontent.com/58654018/103453270-39cbe500-4cfe-11eb-8d33-ba4005410b06.png)

**Comment by maze-runnar** [comment]
the error is not due to this page. Please recheck, There were many unexpected errors in wizard since 2 days.

**Comment by maze-runnar** [comment]
closing it for now, reopen if reproduced. https://github.com/fossasia/open-event-server/pull/7561

**Comment by himanshujaidka** [comment]
> the error is not due to this page. Please recheck, There were many unexpected errors in wizard since 2 days.

No, no my point is different, I am saying that if a user is not able to skip that page i.e. session and speakers then why there is an on-off slide button

**Comment by himanshujaidka** [comment]
@iamareebjamal sir, any updates about this issue?

**Comment by Pihu1998** [comment]
Can I work on this issue please ?

**Comment by himanshujaidka** [comment]
> Can I work on this issue please ?

i am working if it is not done then I’ll tell you

**Comment by himanshujaidka** [comment]
@iamareebjamal sir, what to do with this, whether make this field compulsory or not?

**Comment by iamareebjamal** [comment]
no

**Comment by himanshujaidka** [comment]
okay

**Comment by mariobehling** [comment]
I do not understand the issue. The toggle is there are intended. If the toggle is not working as expected or gives an error please report the issue accordingly. As I do not see what is the issue here I am closing this.
