### ISSUE TITLE
Top Menu Bar: Hide search box on wizard pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6220]
The search box on the top menu should be hidden on wizard pages. Please change it.

![Screenshot from 2021-01-03 01-53-20](https://user-images.githubusercontent.com/1583873/103469564-a5499d00-4d66-11eb-8bab-f837aaab2f6d.png)

**Comment by afzal442** [comment]
Looking into this.

**Comment by afzal442** [comment]
@iamareebjamal should I take out search bar from side bar?? thanks.

**Comment by iamareebjamal** [comment]
Which side bar?

**Comment by afzal442** [comment]
> Which side bar?

I mean on nav bar, there is side bar.

**Comment by iamareebjamal** [comment]
I don't understand anything you're saying

**Comment by afzal442** [comment]
so then, should I remove search bar from top menu?

**Comment by iamareebjamal** [comment]
What does the issue say?

**Comment by afzal442** [comment]
Got it. Thanks Sir. Working.

**Comment by Draco9421** [comment]
can I work on it.
