### ISSUE TITLE
Fix Session Table Columns for Small Resolutions and Larger Fonts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6221]
If a user has browser options that show the font as larger in many resolutions the table on the sessions page is distorted a bit. Also if the user has a small resolution this can happen. Please help to make the table work in more resolutions. In your changes improve the following:

* Make the status button on the left, e.g. "Confirmed" into one line
* Make "Lock Box" square and avoid that it touches the right side of the table
* Ensure Lock Session heading is in one line
* Ensure table borders/spacing between columns is same everywhere (it looks different on some columns)
* Ensure dates/times always fit into one row
* Increase width of speakers columns a bit to also show slightly longer speaker names in one row
* Get rid of the internal scroll bar on the bottom of the table in some resolutions and when fonts are larger
* Improve anything else that could distort the view

![Screenshot from 2021-01-03 11-11-35](https://user-images.githubusercontent.com/1583873/103476450-0fd5f980-4db6-11eb-8725-4e5477afe0c9.png)

![Screenshot from 2021-01-03 11-13-48](https://user-images.githubusercontent.com/1583873/103476451-12385380-4db6-11eb-8286-367feeeef1d3.png)

**Comment by amitsin6h** [comment]
Working on this

**Comment by afzal442** [comment]
@amitsin6h Need collaboration!

**Comment by impaaras** [comment]
can i work on this

**Comment by ritik307** [comment]
@mariobehling  I have some ideas on how to fix this issue. can I work on it?

**Comment by Creatoon** [comment]
@iamareebjamal @mariobehling Sir , please review this PR
