### ISSUE TITLE
Separate Private and Public Speaker and Session Info into two separate pages for Organizers/Speakers vs. Public

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6222]
The current implementation of the speakers and session info is confusing. As an organizer it is unclear if information is public or if the organizer is viewing personal speaker or session information. 

The user interface of public pages should be incorporated into the public event pages. Private pages are part of the organizer interface. Therefore the content areas should be clearly separated as follows:

1. There should be no edit or status change option on public pages.

2. **Session Pages** - The session pages should have the information in this URL structure
* Public for attendees (with only public info):
/e/[event-number]/session/[session-number]
* Private - Access for speakers and organizer (with complete info)
/events/[event-number]/sessions/[session-number]/
/events/[event-number]/sessions/[session-number]/edit

3. **Speaker Pages** - The speaker pages should have the information in this URL structure
* Public for attendees (with only public info): 
/e/[event-number]/speaker/[session-number]
* Private - Access for speakers and organizer (with complete info)
/events/[event-number]/speaker/[speaker-number]

**Comment by mariobehling** [comment]
As an admin compare for example this page https://eventyay.com/events/ae73f280/speakers/5016/edit and this page https://eventyay.com/e/ae73f280/cfs/speaker/5016/edit. Why does the page with the public event heading even exist? Private and public features should be strictly separated.

![Screenshot from 2021-01-03 12-15-44](https://user-images.githubusercontent.com/1583873/103477263-6b57b580-4dbd-11eb-8614-d3ff3b0896a5.png)

**Comment by mariobehling** [comment]
Basically, in the initial idea we wanted to have a dedicated page for the speaker to see and edit their info for a specific event. At that time we did not have a dedicated page for the organizer neither. Well, it does not make sense to have two different pages for the speaker and organizer view. The organizer and speaker should see the same "private" information. 

But the speaker should not see the top menu part, that an organizer sees.

![Screenshot from 2021-01-03 12-25-01](https://user-images.githubusercontent.com/1583873/103477393-d8b81600-4dbe-11eb-8607-f66e6528a84f.png)

If they could see some basic event info on the top it might be a nice thing, but they should have the same slug as the organizer to edit their session. It should be same as Google docs where users always have the same URL no matter what is their role.

**Comment by mariobehling** [comment]
Part of the confusion steers from the fact that the view icon on the sessions overview page is linked to the public session page. After the changes just implemented with the public vs. private information this icon should probably link to a private overview page.

![Screenshot from 2021-01-03 12-33-36](https://user-images.githubusercontent.com/1583873/103477562-63e5db80-4dc0-11eb-974f-5236a2278dca.png)

So, we have a few contradicting things here, that we need to change and standardize.

**Comment by sachinchauhan2889** [comment]
looking into this.

**Comment by mariobehling** [comment]
@sachinchauhan2889 Thanks for the PR about the abstraction layer! 

Now here we need a page a) for the sessions and b) for the speakers info. These "View" pages should be accessible from the organizer overview area through the view icon.

These pages should show all private and public data of a session/speaker.

![Screenshot from 2021-01-04 12-30-15](https://user-images.githubusercontent.com/1583873/103531054-e33ee200-4e88-11eb-8e8f-d023271c185a.png)
