### ISSUE TITLE
Hide "Create Event" on Wizard Pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6227]
The wizard pages are already creating an event. So there is no need to show "Create Event" on the right area in the top menu bar on the wizard pages.

![Screenshot from 2021-01-03 19-45-41](https://user-images.githubusercontent.com/42090582/103481015-11c3ab00-4dfe-11eb-917b-71fa7382467b.png)

**Comment by ranjitkshah** [comment]
working

**Comment by ranjitkshah** [comment]
Its already resolved working fine @mariobehling 
![image](https://user-images.githubusercontent.com/61561415/103489664-0db67e00-4e3c-11eb-93b2-aa4f38b82ba7.png)
