### ISSUE TITLE
Video Panel Button: Further Enhance Design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6231]
Please change the button on the side panel in a way so it looks more in sync with the platform as follows:
- position it so it looks like in the middle of the top bar.
- Change button to: width: 32px, height: 50px
- move the "eventyay" text to the right, so buttons do not overlap the text (also increase the area to the right side border, so it looks like positioned in the middle of the area even if the button is not there)
- move the event name on the side panel itself a slight bit up
- on other pages these kind of buttons sometimes pop out a bit as an effect. Please implement such an effect every 30 seconds

![Screenshot from 2021-01-04 13-58-23](https://user-images.githubusercontent.com/1583873/103538145-f86e3d80-4e95-11eb-8cf1-fe978c9fbfe5.png)

![Screenshot from 2021-01-04 13-58-41](https://user-images.githubusercontent.com/1583873/103538144-f73d1080-4e95-11eb-8a87-fa1ccece43b2.png)

**Comment by afzal442** [comment]
@Draco9421

**Comment by JagjiwanChimkar** [comment]
Can I work on this? Please assign this issue to me.

**Comment by sakshi006** [comment]
Can I work on this issue?

**Comment by Bhavik-Ardeshna** [comment]
Can I work on this issue

**Comment by serverwentdown** [comment]
Actually, I recommend moving the sidebar button to the bottom left and instead of just an arrow, have some text (like "Event Rooms" or something like that) to explain what the arrow is.
