### ISSUE TITLE
Improve menu-bar icon

### ISSUE THREAD

**Issue by 2580ayush2580** [fossasia/open-event-frontend#6248]
**Is your feature request related to a problem? Please describe.**

![f1](https://user-images.githubusercontent.com/56980422/103762353-2c846280-503e-11eb-961a-c26f930b0230.png)
**Describe the solution you'd like**

I think we should add a cross icon when the menu bar is open as shown in the image.

![f2](https://user-images.githubusercontent.com/56980422/103762393-3908bb00-503e-11eb-8d2e-e569ad20fc92.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by afzal442** [comment]
Plz refer your gmail account.

**Comment by 2580ayush2580** [comment]
2580ayush2580@gmail.com

**Comment by 2580ayush2580** [comment]
2580ayush2580@gmail.com

**Comment by afzal442** [comment]
Nope your gmail app

**Comment by 2580ayush2580** [comment]
okay thank you much

**Comment by afzal442** [comment]
Hey did u register for today's event ie codeheat AMA??

**Comment by naveen8801** [comment]
@2580ayush2580  can i work on this ?
