### ISSUE TITLE
Menu-bar has no close button available

### ISSUE THREAD

**Issue by 2580ayush2580** [fossasia/open-event-frontend#6249]
**Is your feature request related to a problem? Please describe.**

When I opened the menu bar and scroll down the content of right side and then I tried to close the menu bar then I have no option available to close the menubar.

![f3](https://user-images.githubusercontent.com/56980422/103764823-2f815200-5042-11eb-9ba1-918288679913.png)
**Describe the solution you'd like**

I think we should add a close button in the menubar.

**Describe alternatives you've considered**

**Additional context**

**Comment by Shubham-kumar799** [comment]
How about closing the menu bar when you click anywhere on the screen other than the menu. This can be done using javascript and css. I would like to work on this .  Can i go ahead?

**Comment by MeghalBisht** [comment]
If you click somewhere outside the menu it will close.

**Comment by 2580ayush2580** [comment]
When I scroll down to the Footer section of the website. 
If I click on the right side then it will not close the menu bar.

![f4](https://user-images.githubusercontent.com/56980422/103780104-8e52c580-505a-11eb-8d9e-a0f11f8345dd.png)

![f5](https://user-images.githubusercontent.com/56980422/103780848-8e06fa00-505b-11eb-9ef0-8abb96e59106.png)

As shown in the image if I tried to close the menu-bar by clicking the right side of the webpage
It will open the event page.
So I think we should add a close button in menu-bar.

**Comment by Creatoon** [comment]
@2580ayush2580 You can simply swipe the menu to the left,  it will close automatically

**Comment by 2580ayush2580** [comment]
@Creatoon Thank you so much.
