### ISSUE TITLE
Call for Speakers: Display wrong end date

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6259]
Organizers set CFS ends on 31 January 2021. On the page, it displayed 1 February 2021: https://eventyay.com/e/fa96ae2c/cfs 
![Screenshot from 2021-01-06 23-16-45](https://user-images.githubusercontent.com/1658742/103825628-78063300-5075-11eb-95f6-f98840488912.png)

**Comment by maze-runnar** [comment]
looking into it

**Comment by maze-runnar** [comment]
@iamareebjamal I have tried to add time for speakersCall in timezoneObserver but this return undefined - 
```
console.log(event.speakersCall.endsAt);
    console.log(event.speakersCall.startsAt);
```

timezoneObserver: observer('data.event.timezone', function() {
    const { event } = this.data;
    console.log(event);
    const { oldTimezone } = this;
    this.oldTimezone = this.data.event.timezone;
    if (!oldTimezone || !this.oldTimezone || oldTimezone === this.oldTimezone) {return}
    if (event.startsAt) {
      event.startsAt = moment.tz(event.startsAt.clone().tz(oldTimezone).format('YYYY-MM-DDTHH:mm:ss.SSS'), moment.ISO_8601, this.data.event.timezone);
    }
    if (event.endsAt) {
      event.endsAt = moment.tz(event.endsAt.clone().tz(oldTimezone).format('YYYY-MM-DDTHH:mm:ss.SSS'), moment.ISO_8601, this.data.event.timezone);
    }

    if (event?.speakersCall?.startsAt) {
      event.speakersCall.startsAt = moment.tz(event.speakersCall.startsAt.clone().tz(oldTimezone).format('YYYY-MM-DDTHH:mm:ss.SSS'), moment.ISO_8601, this.data.event.timezone);
    }
    
    console.log(event.speakersCall.endsAt);
    console.log(event.speakersCall.startsAt);
  }),

**Comment by iamareebjamal** [comment]
Use event.get

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
it's returning proxy -- 
![Screenshot from 2021-01-07 11-13-12](https://user-images.githubusercontent.com/56407566/103855769-5dfe3c00-50d9-11eb-9812-7784bf1b2906.png)

**Comment by iamareebjamal** [comment]
await it

**Comment by maze-runnar** [comment]
await event.get('speakersCall') this is returning a class.
but await event.get('speakersCall').get('startsAt') or event.'speakersCall.get('startsAt') is returning undefined (while it's not undefined)

**Comment by iamareebjamal** [comment]
event.get('speakersCall.startsAt')

And is startsAt set?

**Comment by maze-runnar** [comment]
> And is startsAt set?

yes

**Comment by maze-runnar** [comment]
> event.get('speakersCall.startsAt')

this is also giving `undefined` 😟.

**Comment by iamareebjamal** [comment]
> await event.get('speakersCall') this is returning a class

Call .startsAt on this class and see

**Comment by iamareebjamal** [comment]
Also, it doesn't need to be added in observer because you can't change the timezone on that page. You just need to set the time with event timezone, currently, it is taking local timezone

**Comment by maze-runnar** [comment]
i'm trying to add this change in basic-detail-step observer.

**Comment by iamareebjamal** [comment]
OK, but then there needs to be a better solution, because we cannot change everything this way. What if someone scheduled 5 sessions in IST and then changed timezone to SGT? There needs to be a better way
