### ISSUE TITLE
Virtual Events: Changing and Creating a BBB video room results in errors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6263]
The Codeheat video event room was set to Jitsi. Changing it to Big Blue Button results in error message "ID field". Then deleting it and trying to set it again results in error "already exists" even though there is no room showing up.

Compare https://eventyay.com/events/a315169f/video/all

![Screenshot from 2021-01-07 02-53-41](https://user-images.githubusercontent.com/1583873/103841394-cc201000-5093-11eb-9ffe-89fa916085a1.png)
![Screenshot from 2021-01-07 02-53-00](https://user-images.githubusercontent.com/1583873/103841397-cd513d00-5093-11eb-948b-7aaf509ebb2d.png)

**Comment by iamareebjamal** [comment]
I could delete it and set new one up but looking into ID issue
