### ISSUE TITLE
Windows-10 users face local Setup/Installation.

### ISSUE THREAD

**Issue by JagjiwanChimkar** [fossasia/open-event-frontend#6265]
**Is your feature request related to a problem? Please describe.**
   For Beginners, Windows-10 users face local Setup/Installation.
   Windows-10 users need to use WSL(Windows Subsystem for Linux) for Local.
   Which is currently not present in the guide for local installation.

**Describe the solution you'd like**
Add below point in the local installation guide (local.md file)
* For Windows-10 Users:- Use WSL(Windows Subsystem for Linux) **
Also, provide a link to redirect for WSL Setup.

**Comment by iamareebjamal** [comment]
We encourage people to use Linux instead
