### ISSUE TITLE
Ticket Sales: Confusing Sold Out Message Instead of Showing "Sold Out"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6269]
There is a sold out message when people try to buy a ticket that is sold it. Expected is, that the ticket would not be "bookable" instead there should be a message "Sold Out" in the area drop-down of the ticket number.

For the sold out message itself, if it is displayed anywhere it should show "Ticket [ticket name] sold out." instead of ticket 1865 sold out.

![Screenshot from 2021-01-07 10-16-42](https://user-images.githubusercontent.com/1583873/103875935-520f7b80-50d3-11eb-9839-05280a498a9d.png)

**Comment by SARTHAK1SINGH** [comment]
Working on it.

**Comment by MeghalBisht** [comment]
> For the sold out message itself, if it is displayed anywhere it should show "Ticket [ticket name] sold out." instead of ticket 1865 sold out.
 
> ![Screenshot from 2021-01-07 10-16-42](https://user-images.githubusercontent.com/1583873/103875935-520f7b80-50d3-11eb-9839-05280a498a9d.png)

**Comment by SARTHAK1SINGH** [comment]
@MeghalBisht I already commented I am working on it. But still, you made a pull request. I solved it but now all my work has gone to waste. Please don't do this again 🙏.

**Comment by iamareebjamal** [comment]
Send a PR @SARTHAK1SINGH We'll merge yours instead. But don't wait too long

**Comment by MeghalBisht** [comment]
Hi, @SARTHAK1SINGH in that case, please send your PR and I'll close mine. 👍🏻

**Comment by SARTHAK1SINGH** [comment]
It's ok @MeghalBisht  go for it. I started working on another issue 👍

**Comment by iamareebjamal** [comment]
> I solved it but now all my work has gone to waste

We don't want this to happen. Please send a PR

**Comment by SARTHAK1SINGH** [comment]
@iamareebjamal  My changes were similar to Meghal. So now I started working on the new issue. Next time I'll try to make PR as soon as possible 👍 .

**Comment by Creatoon** [comment]
> > For the sold out message itself, if it is displayed anywhere it should show "Ticket [ticket name] sold out." instead of ticket 1865 sold out.
> 
> ![ss99](https://user-images.githubusercontent.com/61330148/103943867-d0fac780-5158-11eb-982f-4d4ac962e5b8.jpeg)

Only "SOLD OUT" would be nice to show, as i think alerting user with long messasge like this is not cool, what do you think.

**Comment by iamareebjamal** [comment]
Read the issue properly
