### ISSUE TITLE
Virtual Events: Avoid scroll bar in video meetings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6270]
Video meetings have a scroll bar, which does not appear if we use Jitsi or BBB outside of eventyay.

![Screenshot from 2021-01-07 15-53-23](https://user-images.githubusercontent.com/1583873/103906774-aaa93d80-5100-11eb-9e53-c3d884b1db63.png)

**Comment by ksraj123** [comment]
Yeah, I noticed this issue too. 

Looking into this. Thanks

**Comment by ashwinsabu** [comment]
Looking into this.
