### ISSUE TITLE
Access and Discount Code Page: Record in not unloading.

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#6273]
**Describe the bug**

Record created while creating new discount and access code is not unloading while exiting the page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Discount page or Access Page'
2. Click on 'create new discount code'
3. come back to discount page without saving form.

**Expected behaviour**

record must unload on exiting.

**Screenshots**

![newwww issue](https://user-images.githubusercontent.com/72552281/103988432-231d0680-51b4-11eb-8972-b50302370a10.png)

**Additional context**

**Comment by sachinchauhan2889** [comment]
looking into this

**Comment by iamareebjamal** [comment]
This happens everywhere, not just here
