### ISSUE TITLE
Access Code Functionality Not Working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6274]
The access code functionality is not working and has a number of issues:
1. "Hidden Tickets" do not get saved in the wizard Compare https://eventyay.com/events/5ac8e4d9/edit/basic-details
![Screenshot from 2021-01-08 11-16-28](https://user-images.githubusercontent.com/1583873/104003746-21971280-51a3-11eb-9bfd-828294c9795e.png)
2. The old previous UI of the access code appears at times when creating an access code. (Please check in the code as this cannot be replicated always. Ensure the old previous interface is deleted from the code.)
![Screenshot from 2021-01-08 11-18-35](https://user-images.githubusercontent.com/1583873/104004152-b4d04800-51a3-11eb-9eb1-443001e44985.png)

**Comment by mariobehling** [comment]
Regarding point 2: It might be that I was trying this out while I was showcasing the feature and it was being deployed at the same time. However, point 1 is valid. I was not able to create access code tickets.

**Comment by iamareebjamal** [comment]
That PR was only about making the form same as Discount code form. It does not fix the access code (hidden ticket) feature in event basic detail. So, should this issue be taken up urgently?

Summary: Access Codes were broken and form was not similar to Discount Code Form. Now, Access Codes are still broken but form is similar to Discount Code Form

**Comment by SARTHAK1SINGH** [comment]
working on it.

**Comment by iamareebjamal** [comment]
Remaining: https://github.com/fossasia/open-event-frontend/pull/6281#pullrequestreview-564814917

**Comment by maze-runnar** [comment]
this is completed, the only remaining part was done in https://github.com/fossasia/open-event-frontend/pull/7368/
