### ISSUE TITLE
Organizer Menu Tab: Change Order

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6277]
A number of users gave feedback about the logic of the organizer menu tab order. Please change the order of the menu tab to the following order: Overview, Tickets, Speakers, Sessions, Scheduler, Video, Team, Settings

![Screenshot from 2021-01-08 17-01-24](https://user-images.githubusercontent.com/1583873/104036001-28d61480-51d3-11eb-8c7f-5d3f11cc6721.png)

**Comment by afzal442** [comment]
Looking into this.

**Comment by afzal442** [comment]
Solved. Just PR is left.
