### ISSUE TITLE
Wizard Step 5: Standardize Microlocations or Virtual Online Rooms Requirement

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6286]
Currently the wizard step 5 requires a room. However it only becomes apparent when the user tries to save the event. An error message appears then.

As a matter of fact a room is required for the scheduler, but it could possibly also be added at a later time. Therefore please take out the "Microlocations or Virtual Online Rooms" as a required field and ensure it is not required when the user saves the event.

![Screenshot from 2021-01-10 05-28-44](https://user-images.githubusercontent.com/1583873/104114472-2247ba00-5305-11eb-83b5-d17debe1ffe6.png)

**Comment by Draco9421** [comment]
can I work on this.

**Comment by mariobehling** [comment]
@mayan-sharma mentioned:

> Microlocation name was removed as required field from the frontend but backend /v1/microlocations still requires the data/attributes/name and thus gives a code 422 while saving the event.
> But if we make the 'data/attributes/name' as nullable in the backend, the Microlocations model still requires name field as non-nullable.

**Comment by mariobehling** [comment]
Closing it after clarification of @iamareebjamal 

> Yes, name is a required field for microlocation and is to remain so. There is no point in having a microlocation without a name. The issue is not about server, it's about frontend not allowing to save form without adding a microlocation, that should be possible. But it should still be impossible to add a microlocation without a name and save the form, so no server change is required. name should remain non-nullable and required field
