### ISSUE TITLE
Not able to create a speaker due to Error "Field may not be null"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6287]
Trying to create a speaker on next months Codeheat event shows an error message "Field may not be null" even though I filled in all fields.

Compare
https://eventyay.com/events/f4fc71b8/speakers/create

![Screenshot from 2021-01-10 05-38-24](https://user-images.githubusercontent.com/1583873/104114569-26280c00-5306-11eb-8581-1a56d44c823c.png)

**Comment by maze-runnar** [comment]
this is showing due to session field. If session field is not selected it is showing null error.

**Comment by iamareebjamal** [comment]
Sessions are relationship and not a field, so it is not possible for sessions to throw this error

**Comment by iamareebjamal** [comment]
Even though new session proposal is not chosen or any existing session is chosen, it is trying to save session with null title, hence the error

**Comment by maze-runnar** [comment]
in the session the title is causing error
