### ISSUE TITLE
Wizard Step 1: Calculation of min/max price for donation tickets not correct resulting in error message

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6288]
The minimum/maximum calculation is wrong, e.g. min 11 and max 1000 shows error messages on both fields. It seems the logic follows the digits, e.g. 11 and 2000 is working fine.

![Screenshot from 2021-01-10 06-16-17](https://user-images.githubusercontent.com/1583873/104115069-88cfd680-530b-11eb-9355-8e4687ac4d60.png)

**Comment by Soumi150** [comment]
Working on this.
