### ISSUE TITLE
Public Event Page: Link event logo and text to event start page top

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6292]
Please implement the following: Link event logo and text on all event pages to event start page top.

![Screenshot from 2021-01-10 14-25-37](https://user-images.githubusercontent.com/1583873/104124235-04537700-5350-11eb-989a-50e53316c43e.png)

**Comment by nlok5923** [comment]
Working on it.

**Comment by Soumi150** [comment]
Working on this.

**Comment by Soumi150** [comment]
Sir, Please elaborate what is meant by text on event pages.
