### ISSUE TITLE
Speaker CfS Submission: Redirect speaker to private "view" page of session instead of public session page after editing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6293]
A session and speaker view page for organizers have been implemented here https://github.com/fossasia/open-event-frontend/pull/6234

We need the same kind of page for speakers for sessions submitted to the CfS.

After a speaker adds a session they are currently being directed to the future public page of their session. Instead expected is:
1. After a speaker submits a session they should be redirected to a page with all the info they entered. This page should be very plain UI (same as implemented [here](https://github.com/fossasia/open-event-frontend/pull/6234) and it should not be publicly visible.
2. The page URL should be as follows `https://eventyay.com/e/[event ID]/cfs/session/[Session ID]/`. An example would be https://eventyay.com/e/fa96ae2c/cfs/session/6612/
3. On the top add a menu with two links:
a) My Sessions
b) [Event Name] Call for Speakers 
4. Below show the following buttons:
Edit, Edit Speaker Details, Withdraw
5. The current public pages shows an option for speakers to withdraw. The withdraw button here opens a pop-up to reconfirm the speaker wants to withdraw. Please show this pop up here.

![Screenshot from 2021-01-15 11-47-49](https://user-images.githubusercontent.com/1583873/104716093-b495f680-5727-11eb-9cf2-3f6bc1e86953.png)

**Comment by 17sushmita** [comment]
Working on this
