### ISSUE TITLE
Wizard Step 2: Social Links option for "Event Site" missing and "Website" box missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6298]
In wizard step 2 and on the public event site the social links implementation does not work as expected. Please fix the following:
* The dropdown menu misses the option "Event Site" 
![Screenshot from 2021-01-10 17-43-45](https://user-images.githubusercontent.com/1583873/104129207-15aa7c80-536c-11eb-8cc5-97cf8f2b4a8c.png)
* Event Site should show up as a box on the public page
* The dropdown menu options of social links are not sorted alphabetically, but they should be.
* The social links menu has the option "Website" but it does not show up as a box as expected on the public event site
![Screenshot from 2021-01-10 17-43-23](https://user-images.githubusercontent.com/1583873/104129198-0c211480-536c-11eb-9214-cc27c32cb6d6.png)

Compare:
https://eventyay.com/e/fa96ae2c

**Comment by ranjitkshah** [comment]
> * The social links menu has the option "Website" but it does not show up as a box as expected on the public event site

#6082

**Comment by Soumi150** [comment]
Working on rest of the points.

**Comment by iamareebjamal** [comment]
As discussed previously in #5877, event site was from the wizard. Because that's a separate field than custom links decided to only show custom links. 

https://github.com/fossasia/open-event-frontend/issues/5116#issuecomment-723430646

**Comment by akash2408** [comment]
what is remaining in this issue? can anyone tell?

**Comment by tanay123456789** [comment]
Is there any more issues in it then let me know.
