### ISSUE TITLE
Implementing sessions layout for public events(UI)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#63]
- [x] feature request

Currently the sessions layout is missing from the public events. Add sessions to the public events as shown in the screenshot.
![screenshot from 2017-05-20 15-19-10](https://cloud.githubusercontent.com/assets/12807846/26274790/b5fd8edc-3d6f-11e7-8477-52112bab30f3.png)

@niranjan94 I will be working on this.

**Comment by niranjan94** [comment]
@geekyd 

**Requirements:**

- Each session in a component
- Session List will be a component
- The date from the speaker object can be converted to human readable format using [`ember-moment`](https://github.com/stefanpenner/ember-moment) helpers already included in the project.
- Sessions to be displayed in chronological order
- Filtering by session type need not be done now and can be done in a seperate PR. Your choice. No compulsion.
- For speaker information either `longBiography` or `shortBiography` or `speakingExperience` might be available in the API. Display only one of what is available in the order of preference. `shortBiography` > `longBiography` > `speakingExperience`.
- sessions array (with dummy sessions data) in the session controller. The following can be a session object. You don't have to cover all the fields in the dummy object. Just use the one's you'd be using in the UI for now.

	```js
	{
	  "id": 0,
	  "longAbstract": "string",
	  "session_type": {
	    "length": "11:00",
	    "id": 0,
	    "name": "string"
	  },
	  "shortAbstract": "string",
	  "speakers": [
	    {
	      "shortBiography": "string",
	      "id": 0,
	      "city": "string",
	      "name": "string",
	      "speakingExperience": "string",
	      "organisation": "string",
	      "longBiography": "string",
	      "photo": {
	      	    "iconImageUrl": "http://website.com/item.ext",
	      		"originalImageUrl": "http://website.com/item.ext",
	      		"smallImageUrl": "http://website.com/item.ext",
	      		"thumbnailImageUrl: "http://website.com/item.ext"
	      }
	    }
	  ],
	  "subtitle": "string",
	  "language": "German",
	  "title": "string",
	  "track": {
	    "color": "green",
	    "fontColor": "green",
	    "id": 0,
	    "name": "string"
	  },
	  "startAt": new Date(),
	  "endAt": new Date(),
	  "state": "pending",
	  "microlocation": {
	    "id": 0,
	    "name": "string"
	  },
	  "videos": [
	  	"http://website.com/item.ext"
	  ],
	  "audio": [
	  	"http://website.com/item.ext"
	  ],
	  "slides": [
	  	"http://website.com/item.ext"
	  ],
	  "signupUrl": "http://website.com"
	}
	```
