### ISSUE TITLE
Public Event Pages: Create a Page for Sponsors/Exhibitors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6301]
Sponsors and exhibitors are now only listed on overview pages or planned to be listed on overview pages. Implement this after https://github.com/fossasia/open-event-frontend/issues/6199.

Please implement a dedicated page for sponsors or exhibitors as follows:
* Implement sponsors or exhibitors at the URL scheme such as `eventyay.com/e/[eventID]/[sponsor or exhibitor name]`
* Implement a page that brings all the information added about the partner in the wizard together. Compare to this page of another event here for example https://www.univention-summit.de/sponsor/agorum/

![Screenshot from 2021-01-10 22-09-20](https://user-images.githubusercontent.com/1583873/104135522-5668bc80-5391-11eb-9965-e36a8b99a9e7.png)

**Comment by CadencePrestissimo** [comment]
Can I work on this ?

**Comment by Jahnavi-Jonnalagadda** [comment]
@mariobehling, Issue 6199 is still active, can we still implement this issue?

**Comment by aryangulati** [comment]
Can you assign me this issue @mariobehling
