### ISSUE TITLE
Wizard Step 1: Tax information country field opens without reason

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6302]
In Wizard step 1 on opening additional tax and information the pop up immediately jumps to the country and opens the dropdown list. Expected: The dropdown list should only open if the user clicks in the field.

![Screenshot from 2021-01-11 00-18-38](https://user-images.githubusercontent.com/1583873/104138320-a6e91580-53a3-11eb-9753-e5f8bc61f5a2.png)

**Comment by nlok5923** [comment]
Working on it.

**Comment by maze-runnar** [comment]
on it
