### ISSUE TITLE
Order Process: Add Info Box "Organizer Information"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6303]
In wizard step 1 an organizer has an option to add company. If an organizer adds the info, then show the company info in a box during the ordering process on the right hand side.

1. Add the info box below "Where and When" during ordering
2. Add the info box above "Payee Information" on the order page
3. If the organizer has not added that info then do not show the box

![Screenshot from 2021-01-11 00-29-05](https://user-images.githubusercontent.com/1583873/104138421-45757680-53a4-11eb-8029-7acfd110b39d.png)
![Screenshot from 2021-01-11 00-30-20](https://user-images.githubusercontent.com/1583873/104138423-47d7d080-53a4-11eb-81e5-76cf3d3d79b6.png)

**Comment by Soumi150** [comment]
Working on this.

**Comment by mariobehling** [comment]
Actually the business information that should appear here are added in the wizard step 1 tax information pop up.

![Screenshot from 2021-01-13 01-44-19](https://user-images.githubusercontent.com/1583873/104391782-f3b62300-5540-11eb-8b29-6c2764bd8cef.png)

**Comment by Creatoon** [comment]
> Actually the business information that should appear here are added in the wizard step 1 tax information pop up.
> 
> ![Screenshot from 2021-01-13 01-44-19](https://user-images.githubusercontent.com/1583873/104391782-f3b62300-5540-11eb-8b29-6c2764bd8cef.png)

yes sir , from here i am getting the buisness details
