### ISSUE TITLE
Wizard Step 1: Donation Ticket cannot be moved up or down in ticket list

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6304]
Donation tickets cannot be moved in wizard step 1.

Compare https://eventyay.com/events/5ac8e4d9/edit/basic-details

![Screenshot from 2021-01-11 00-48-05](https://user-images.githubusercontent.com/1583873/104138798-cf264380-53a6-11eb-9dd2-e7ae1483fae8.png)

**Comment by maze-runnar** [comment]
working for me
![captured](https://user-images.githubusercontent.com/56407566/104146749-c870ee00-53f1-11eb-9dcc-13c4942b6c8e.gif)

**Comment by Saumyachitransh01** [comment]
Taking this

**Comment by Creatoon** [comment]
it is working just fine.

**Comment by iamareebjamal** [comment]
The error is coming up in moveTicket function

Cannot read property set of undefined

**Comment by maze-runnar** [comment]
ok
