### ISSUE TITLE
Public Page: Ticket box alignment issue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6305]
If there is tax or an error message below the box of a donation ticket, the content in the first and last columns of the ticket row moves down. Expected: It should stay aligned.

compare https://eventyay.com/e/5ac8e4d9

![Screenshot from 2021-01-11 01-23-14](https://user-images.githubusercontent.com/1583873/104139449-e582ce00-53ab-11eb-80d9-aa0b4977f44f.png)

**Comment by Creatoon** [comment]
@mariobehling Sir after fixing,

![Screenshot_2021-01-11 OpenTechSummit Europe eventyay(1)](https://user-images.githubusercontent.com/65965202/104143355-19c6b080-53e5-11eb-8ef2-118c99a356d8.png)
