### ISSUE TITLE
Admin: Past Events show 505

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6306]
Past events and other filters on the events admin section are not showing up.

Compare https://eventyay.com/admin/events/past

![Screenshot from 2021-01-11 01-47-33](https://user-images.githubusercontent.com/1583873/104139962-0ef12900-53af-11eb-96dc-17e3f621b262.png)

**Comment by maze-runnar** [comment]
I found no issue-
![Screenshot from 2021-01-11 09-34-31](https://user-images.githubusercontent.com/56407566/104146310-4502cd00-53f0-11eb-9ecf-460bb4ba291e.png)

**Comment by iamareebjamal** [comment]
This is an issue in api.eventyay.com

**Comment by mariobehling** [comment]
Past events works now, but other filter pages are still showing the error.
