### ISSUE TITLE
Virtual Events: Enhance "Join Event" functionality and side panel style

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6322]
We can further improve the online event experience according to some user feedback. Please make the following changes:

* Make side panel event name into a link and take out external link icon
* Move right-side bar "Join Event" button above date on the right side bar to the top position
* Make "Join Event" button on right side bar full width of the side bar (similar to tweet area), make it into blue color to be more visible and increase the font size
* Take out "Join Video" button from right-side bar. It is sufficient to have it on the bottom and we have the "Join Event" button now here.
* If the attendee already participates in the event (meaning they already have the side-panel as part of their UI), but the panel is minimized the button "Join Event" should always expand the side panel

![Screenshot from 2021-01-11 22-52-49](https://user-images.githubusercontent.com/1583873/104242968-2c320000-5460-11eb-900a-d2e683adeecd.png)

**Comment by nlok5923** [comment]
Working on it

**Comment by nlok5923** [comment]
on it.

**Comment by Jahnavi-Jonnalagadda** [comment]
@mariobehling, Will work on this issue.

**Comment by MeghalBisht** [comment]
taking this up!

**Comment by iamareebjamal** [comment]
Remaining: If the attendee already participates in the event (meaning they already have the side-panel as part of their UI), but the panel is minimized the button "Join Event" should always expand the side panel
