### ISSUE TITLE
Limit Time of Event Duration to Maximum 20 days to limit spam events 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6323]
There are several spam events that try to use the service to promote their own courses. They post an event duration that is several years. To limit these usages please implement a maximum event duration of 20 days.

![Screenshot from 2021-01-12 01-09-32](https://user-images.githubusercontent.com/1583873/104252766-21349b00-5473-11eb-8bbd-ea75906be82a.png)

**Comment by Creatoon** [comment]
working

**Comment by iamareebjamal** [comment]
This needs server change first

**Comment by Creatoon** [comment]
> This needs server change first

Sir if we try to achieve this by adding a validate,  for ex - if differnce bw days is 20 then it will pass,if not an error will be generated,  
Will it work?

**Comment by iamareebjamal** [comment]
Frontend check remaining
