### ISSUE TITLE
Implement Mark Accounts as Spam

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6325]
Currently accounts that are associated with events cannot even be deleted by an admin, e.g. the account rahulroy5679909@gmail.com and creatoranita@gmail.com created a lot of spam events. Actually if we could delete these accounts they could re-register again. 

A better way would be to enable the admin to make accounts as spam accounts and prevent them from logging in again.

Please implement the option to make accounts as spam accounts and add a tab to view spam accounts in the admin UI at https://eventyay.com/admin/users/all

**Comment by maze-runnar** [comment]
so there would be a column added is_blocked in user table?
