### ISSUE TITLE
Events Dashboard: Add URL box with copy feature and fix width issue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6330]
The events dashboard content table on https://eventyay.com/events/live is not using the space well. On the right hand side there is space left in the table. The columns event name, date and tickets could be larger. Also a URL box similar to the video URL box would be useful. Therefore please change it as follows:
* Distribute the column width more efficiently so content does not break and use the full width of the area
* Add a public URL box with copy and forward button same as on the video tab of events

![Screenshot from 2021-01-12 09-56-40](https://user-images.githubusercontent.com/1583873/104292416-1e5e9800-54bd-11eb-9f19-9f4cb98268e6.png)

![Screenshot from 2021-01-12 10-01-40](https://user-images.githubusercontent.com/1583873/104292462-2e767780-54bd-11eb-9903-eb14133dc41d.png)

**Comment by nlok5923** [comment]
working on it.

**Comment by himanshujaidka** [comment]
@nlok5923 Are you workin on this?

**Comment by nlok5923** [comment]
@himanshujaidka u can work on it.

**Comment by himanshujaidka** [comment]
> @himanshujaidka u can work on it.

I am already workin on another, I saw your comment before that's why I am asking
