### ISSUE TITLE
Specific Event Dashboard: Add URL Box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6331]
The event dashboard shows a URL to the public page of the event. Please make change this to a box similar to the video URL box on the video tab.

![Screenshot from 2021-01-12 10-19-22](https://user-images.githubusercontent.com/1583873/104295037-43a0d580-54c0-11eb-90a9-bf5a10d932fa.png)

![Screenshot from 2021-01-12 10-01-40](https://user-images.githubusercontent.com/1583873/104295041-44396c00-54c0-11eb-84d2-6ca1e2e33496.png)

**Comment by Creatoon** [comment]
Working
