### ISSUE TITLE
Virtual Events: Move Big Blue Button minimize button to avoid overlap

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6333]
The eventyay sidepanel button is overlapping with the Big Blue Button side panel button when both are minimized. Please move the BBB sidepanel button further down below eventyay button using CSS.

![Screenshot from 2021-01-11 22-44-51](https://user-images.githubusercontent.com/1583873/104299270-4e119e00-54c5-11eb-8aa9-9e09b989d6d9.png)

**Comment by nlok5923** [comment]
on it.

**Comment by iamareebjamal** [comment]
That's not possible. External CSS (controlled by us) does not influence CSS in iframe. If we do it using JS, it messes up the UI of other elements of BBB, like the speaker indicator which is positioned according to the chat button

Simplest thing would be to move the side panel button below

**Comment by nlok5923** [comment]
Working on it

**Comment by afzal442** [comment]
Yes @nlok5923 . Sir has suggested in above comment.

**Comment by nlok5923** [comment]
Sir i am not able to access the BBB room it says:
![image](https://user-images.githubusercontent.com/56120084/104311986-f80c1d00-54fb-11eb-9f9f-b91f69cf717b.png)

**Comment by afzal442** [comment]
@nlok5923 Could I try this? Thanks.

**Comment by mariobehling** [comment]
> That's not possible. External CSS (controlled by us) does not influence CSS in iframe. If we do it using JS, it messes up the UI of other elements of BBB, like the speaker indicator which is positioned according to the chat button
> 
> Simplest thing would be to move the side panel button below

Ok, so, looks like moving the icon a bit would fit as well.

![Screenshot from 2021-01-12 16-23-13](https://user-images.githubusercontent.com/1583873/104334497-baef5d00-54f2-11eb-8b7b-a7cd6cc23304.png)

When you do this, please also change the position and area of the "eventyay" name on the top left back to its previous stage. This was changed here in this PR https://github.com/fossasia/open-event-frontend/pull/6236

**Comment by afzal442** [comment]
Working on it....

**Comment by afzal442** [comment]
Sorry, I think @nlok5923 was trying. I haven't got any reply. Will you work on it?

**Comment by nlok5923** [comment]
> @nlok5923 Could I try this? Thanks.

ok @afzal442 you can take this.

**Comment by afzal442** [comment]
@mariobehling plz also add a codeheat label here. Thanks.
