### ISSUE TITLE
Wizard Step 1: Dropdown event types etc. are not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6338]
The dropdown menus on the top of the event wizard step 1 are not translatable.

![Screenshot from 2021-01-12 19-00-04](https://user-images.githubusercontent.com/1583873/104354256-3bb95380-5509-11eb-95de-1f1b9fcb6631.png)

**Comment by nlok5923** [comment]
Working on it.

**Comment by himanshujaidka** [comment]
> Working on it.

What is meant by translatable?

**Comment by nlok5923** [comment]
on it
