### ISSUE TITLE
Wizard Step 1: Settings Location, Online etc. menu not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6339]
Please make the settings menu for location, online etc. translatable.

![Screenshot from 2021-01-12 19-13-33](https://user-images.githubusercontent.com/1583873/104355046-62c45500-550a-11eb-9862-8287447379e9.png)

**Comment by afzal442** [comment]
working...

**Comment by mariobehling** [comment]
Seems it is now already added.

**Comment by mariobehling** [comment]
After checking again, the fields are not translatable yet. Therefore re-opening it.
