### ISSUE TITLE
Wizard Step 2: Make license names in dropdown and info links translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6340]
The licenses in the wizard step 2 dropdown and info box are not translatable.

![Screenshot from 2021-01-12 19-19-01](https://user-images.githubusercontent.com/1583873/104355688-5096e680-550b-11eb-8425-07def1db59e9.png)

**Comment by nlok5923** [comment]
working on it.

**Comment by himanshujaidka** [comment]
Working
