### ISSUE TITLE
On Wizard Attendee Form, Speaker and Session Forms: Many fields are not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6345]
Please make all form elements including text and other form fields translatable on attendee, speaker and session forms.

![Screenshot from 2021-01-13 00-00-54](https://user-images.githubusercontent.com/1583873/104385292-438ded80-5533-11eb-896a-31623e39dec1.png)
![Screenshot from 2021-01-13 00-00-31](https://user-images.githubusercontent.com/1583873/104385296-4688de00-5533-11eb-92e4-1e54b5d5e555.png)

**Comment by nlok5923** [comment]
Working on it

**Comment by Saumyachitransh01** [comment]
Taking this

**Comment by chetas411** [comment]
Working on this one!

**Comment by chetas411** [comment]
@mariobehling  for this issue some translations are missing but how to view changes in localhost if I make changes in .po files .
I have read that .po files are compiled to .mo files but  how to check that in localhost on my machine?
