### ISSUE TITLE
Public Event Page: Make content on ticket box and "Join Event" button translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6346]
Not all the content on the ticket box and neither the "Join Event" button are translatable on the public event page.

![Screenshot from 2021-01-13 00-11-52](https://user-images.githubusercontent.com/1583873/104385810-2f96bb80-5534-11eb-94fd-4f4c9e872f1b.png)
![Screenshot from 2021-01-13 00-11-28](https://user-images.githubusercontent.com/1583873/104385811-302f5200-5534-11eb-8866-5dbfacf3f8d9.png)
![Screenshot from 2021-01-13 00-12-00](https://user-images.githubusercontent.com/1583873/104385814-3291ac00-5534-11eb-9209-9ceae71acd4a.png)

**Comment by Soumi150** [comment]
Working on this.

**Comment by aarushi31** [comment]
Working

**Comment by chetas411** [comment]
@mariobehling This translation is working fine here 

![Codeheat Ask Me Anything - February Edition _ eventyay - Google Chrome 25-01-2021 18_53_44_LI](https://user-images.githubusercontent.com/65273718/105711744-f8b2a380-5f3e-11eb-8157-1660a96e783f.jpg)

**Comment by akash2408** [comment]
working on it

**Comment by rajpratyush** [comment]
i am working on this

**Comment by mariobehling** [comment]
This has been solved in the meantime. Therefore closing it.
