### ISSUE TITLE
Wizard Step 1: Countries and Payment details are not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6347]
Please enable the translations of countries and content in the payment section of Wizard step 1.

![Screenshot from 2021-01-12 23-32-56](https://user-images.githubusercontent.com/1583873/104385872-51903e00-5534-11eb-8d85-dbd18d8bd3f5.png)

![Screenshot from 2021-01-12 23-34-20](https://user-images.githubusercontent.com/1583873/104385884-5654f200-5534-11eb-99b0-e63fd4fc8978.png)

**Comment by Naman-1234** [comment]
Working on it
