### ISSUE TITLE
Licenses in Wizard Step 2 on dropdown and popup are not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6349]
Please make the license info translatable.

![Screenshot from 2021-01-12 19-19-01](https://user-images.githubusercontent.com/1583873/104386604-cf087e00-5535-11eb-8d70-d6e720b26882.png)
![Screenshot from 2021-01-12 19-15-20](https://user-images.githubusercontent.com/1583873/104386609-d16ad800-5535-11eb-9545-f051f504b611.png)

**Comment by iamareebjamal** [comment]
Duplicate of #6340
