### ISSUE TITLE
Frontpage Header text no longer translatable and moved down

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6350]
After the recent changes the frontpage header text is no longer translatable. As it now uses two lines of text the "Create Event" button also moved down which makes the area look unnatural.

- [x] Please enable translations and
- [ ] move the text and button up a bit.

![Screenshot from 2021-01-13 00-28-09](https://user-images.githubusercontent.com/1583873/104386963-708fcf80-5536-11eb-808f-7e8aafb8b41a.png)

**Comment by Subham142** [comment]
Working on it

**Comment by aarushi31** [comment]
Working on the issue.

**Comment by Subham142** [comment]
@aarushi31  I'm working on this , can you let me try . I'll be happy to  refer you if i couldn't do it

**Comment by aarushi31** [comment]
No problem. Go ahead.

**Comment by himanshujaidka** [comment]
> @aarushi31 I'm working on this , can you let me try . I'll be happy to refer you if i couldn't do it

still working?

**Comment by Subham142** [comment]
I'm having a lot of network issue today 
@aarushi31  you can work on it  otherwise @himanshujaidka  you can take it

**Comment by himanshujaidka** [comment]
Working

**Comment by himanshujaidka** [comment]
@iamareebjamal sir, pls add a code heat label, my pr is ready

**Comment by mariobehling** [comment]
Translations are already working after recent changes. Only position changes are needed now.

**Comment by himanshujaidka** [comment]
> Translations are already working after recent changes. Only position changes are needed now.

okay
