### ISSUE TITLE
Implement Event statistics API on event overview page

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#636]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
![image](https://user-images.githubusercontent.com/17252805/29056035-e0474e52-7c1d-11e7-9414-ee141d025594.png)

**Comment by geekyd** [comment]
@CosmicCoder96 Why is this on hold?

**Comment by CosmicCoder96** [comment]
@geekyd I had asked the query about the statistics not having any relationship with the events yet the URL is <event identifier>/statisitic. So what would be the correct way to fetch them. @niranjan94

**Comment by geekyd** [comment]
@CosmicCoder96 This endpoint mentioned in the docs `/v1/events/{event_identifier}/general-statistics`, is it missing something?

**Comment by CosmicCoder96** [comment]
@geekyd The relationship

**Comment by niranjan94** [comment]
@CosmicCoder96 @geekyd use the normalize functions in the event serializers to manually add a relationship link.

**Comment by niranjan94** [comment]
https://emberigniter.com/custom-relationship-links-json-api/
