### ISSUE TITLE
Translations are not done properly

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#6363]
![Screenshot (142)](https://user-images.githubusercontent.com/58654018/104596846-90400880-569a-11eb-827c-bd3cda4bd076.png)
**Describe the bug**

Translations should be done properly

**Comment by mariobehling** [comment]
For translations please refer to https://hosted.weblate.org/projects/open-event/frontend/ and add or improve translations here, please.

**Comment by himanshujaidka** [comment]
> For translations please refer to https://hosted.weblate.org/projects/open-event/frontend/ and add or improve translations here, please.

okay
