### ISSUE TITLE
Virtual Events Sidebar: Only provide option to view sidebar for attendees with tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6364]
When an anonymous users accesses a "Join Video" link they will get a pop up to login or to get a ticket. If the user presses "Cancel" the event page and the side panel  will show up even for anonymous users. Users using the "Join Event" link see another message and do not have the option "Cancel".

Expected is: 
* That only the event page would be visible without the side panel. 
* The pop up message, buttons and design should be same for both "Join Event" and "Join Video" link.

Example https://eventyay.com/e/f4fc71b8?side_panel=true&video_dialog=true

![Screenshot from 2021-01-14 14-35-43](https://user-images.githubusercontent.com/1583873/104597928-39c0d300-5676-11eb-9220-04249e539883.png)

![Screenshot from 2021-01-14 14-36-00](https://user-images.githubusercontent.com/1583873/104597935-3d545a00-5676-11eb-9776-84ae06d76932.png)

**Comment by afzal442** [comment]
Looking into this

**Comment by afzal442** [comment]
@mariobehling I am not able find `cancel` button while trying to join event. Thanks
