### ISSUE TITLE
Team Member: Fix button text and enable translation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6365]
When an organizer wants to add a team member the button is wrong. Furthermore roles, e.g. here "organizer" is not translatable and on the overview page "Owner" must be translatable.

Expected: Instead of "Add Role" or "Edit Role" show "Add Team Member" or "Edit Team Member".

![Screenshot from 2021-01-14 16-46-40](https://user-images.githubusercontent.com/1583873/104614369-7990b600-5688-11eb-85bc-4066ef45f4a9.png)

**Comment by afzal442** [comment]
Working...

**Comment by mariobehling** [comment]
Please only claim one issue at a time and do not comment on each single issue. Please follow our best practices https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by afzal442** [comment]
@mariobehling I have already mentioned on that issue that I am able to reproduce. So I think that comment makes sense. BTW thanks for the reminder.

**Comment by prateekshourya29** [comment]
Can I work on this? I'm new here and this issue doesn't seem to be an urgent one. I can work on this and it'll help me understand code base too.

**Comment by afzal442** [comment]
Hello @prateekshourya29 I can understand you. But just wait for a couple of hours. Then you can happily take up this and explore things.

**Comment by prateekshourya29** [comment]
@afzal442 i think you have to update translation files also.
