### ISSUE TITLE
Role invite results in display in 404 page not found

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6371]
Inviting a new organizer results in 404.

![Screenshot from 2021-01-14 20-09-04](https://user-images.githubusercontent.com/1583873/104636917-5e33a400-56a4-11eb-8a69-725e385d86cf.png)

**Comment by iamareebjamal** [comment]
@mariobehling Can you please paste the link?

**Comment by mariobehling** [comment]
http://url4008.eventyay.com/ls/click?upn=letbyYeOYcaRfmQNy3p4YdEx9WvL4QEw8rstrdNBjCvrIaTrcnjLjtSboAgOHQPzoNdP2z73UGHzTjQXQK-2FSMmYn9tlyP5aVaaIFX5Y5oF-2BuVhCoo-2FvW30Xw6YaICIY95Ixot1hihJJr1oOLk5ETjw-3D-3DU_gj_L5p4admKt6-2BbeUGbM2E1Z8qA1MCfUiREVGwAzMSYYpEqhPhTnD-2FyPrsDcSieTsmQ7QxCh-2BUzDs-2BhlV36f4JbaWqQU6sFHorCNY-2FgXwlLWMRLDVJ-2Bywu3lglP0LEMvJnmsxoRpRboWIwgEypoRYHkmv2ciJsjKpCHecA0fTgZLGN-2Bp4XJk7F484Fe3h-2FaB7nR6CvqlPQoPiev7tctGnef0-2FCHkIAlHtL5f0-2Bm1h3wBcw-3D

**Comment by mariobehling** [comment]
I also see that this is http instead of https.

**Comment by mariobehling** [comment]
![Screenshot from 2021-01-14 20-54-47](https://user-images.githubusercontent.com/1583873/104642018-c38a9380-56aa-11eb-8322-309d394896f1.png)

**Comment by iamareebjamal** [comment]
Are you logged in with mb@mariobehling.de ID?

**Comment by iamareebjamal** [comment]
OK, so the issue is:

Event is draft, so you cannot access /e/ID route, but your invite is at that route as well, so it cannot be accepted till you visit that route.

What should we do here? Should we make role invite a top level route like /role-invite/ID instead of /e/ID/role-invites?

**Comment by mariobehling** [comment]
> What should we do here? Should we make role invite a top level route like /role-invite/ID instead of /e/ID/role-invites?

Yes, that sounds perfect.

**Comment by maze-runnar** [comment]
I am getting error on sending role-invite 
![Screenshot from 2021-01-15 13-10-01](https://user-images.githubusercontent.com/56407566/104695653-1a3bb000-5733-11eb-90b9-caa405e00b5f.png)

**Comment by iamareebjamal** [comment]
As always with any server error, try on local machine and find what's the error

**Comment by maze-runnar** [comment]
it's working fine with local server.

**Comment by iamareebjamal** [comment]
Cool, then continue with fix

**Comment by maze-runnar** [comment]
I am confused, a lot confused, about this issue and ticket-up down too. I will ask it in technical meeting.

**Comment by iamareebjamal** [comment]
OK
