### ISSUE TITLE
Organizer Session Overview Page and Speaker Overview Page: Link speaker photo and speaker or session name to view page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6376]
Please link the left hand rows for name or title on the following organizer pages to the session view or the speaker view page:
* The image/speaker name on the speaker overview page should link to the speaker view page
* The session title should link to the session view page

Speaker overview page
![Screenshot from 2021-01-14 23-22-38](https://user-images.githubusercontent.com/1583873/104656338-6c42ee00-56bf-11eb-8506-3d7a40e023cd.png)

Session overview page
![Screenshot from 2021-01-14 23-19-54](https://user-images.githubusercontent.com/1583873/104656188-2be37000-56bf-11eb-8072-b62423da840f.png)

**Comment by nlok5923** [comment]
Working on it.

**Comment by afzal442** [comment]
Working on it.
