### ISSUE TITLE
Attendee Form: Implement "Photo & video & text consent" in attendee form with tickbox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6377]
As there are many online events nowadays, which are recorded, we need an option to announce that events are recorded when people order a ticket.

This means that people **must** accept that an event is recorded, photos are taken or text is copied in order to complete the order. Therefore please implement this as a field for the attendee form as follows:
* Add option "Photo & video & text consent" into the attendee form
* Only permit option to be "Required" in the form (so when an organizer chooses the option, it must be "required")
* On the order form of attendees show the following text with a tickbox, that the ticket buyer must accept.
   * "I agree that the event organizer is allowed to take photo, video and/or audio recordings of me or my profile and also texts created by me in the chats which might be published on the event organizer's websites and/or social media channels."
* If the ticket buyer does not tick the box, show an error message: "In order to complete the order process you need to agree to the Photo & video & text consent."

![Screenshot from 2021-01-15 00-25-08](https://user-images.githubusercontent.com/1583873/104661131-2c343900-56c8-11eb-9cb4-a565bd6d6dc4.png)

**Comment by ranjitkshah** [comment]
@iamareebjamal, not getting `acceptVideoRecording` field from backend
![image](https://user-images.githubusercontent.com/61561415/104829399-63a60f80-5899-11eb-9ff7-b0007e73246d.png)

**Comment by ranjitkshah** [comment]
working
