### ISSUE TITLE
Cookie Consent box is not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6378]
Please make the consent box on top of the website translatable.

![Screenshot from 2021-01-15 00-27-05](https://user-images.githubusercontent.com/1583873/104661312-9220c080-56c8-11eb-913a-be0686407d0d.png)

**Comment by iamareebjamal** [comment]
It is dynamic text which can be changed here https://eventyay.com/admin/settings
Hence, not translatable.

It can be made translatable but then it won't be dynamic.

**Comment by iamareebjamal** [comment]
Made static and translatable
