### ISSUE TITLE
Attendee Form: Add user content to receive email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6379]
Many organizers would like to be officially permitted to stay in touch with attendees. Therefore please add the following options to the attendee form:

For the agreement of a participant to receive emails after the event implement 
* the text "We would like to share information with you after the event by email for example through personal emails by our team, newsletters or other electronic communications. You can drop out of this agreement at any time. Do you agree to receive electronic mail?"
* a switch button to accept this. This switch button should have set "Yes" by default (on the right) and "No" to the left.
* If the organizer makes the agreement of the participant required and the participant switches the button to "No", then show an error message "You need to agree to the condition of the organizer to receive emails in order to continue the order process."
* If the user does not agree, the user should not be able to continue the order process

![Screenshot from 2021-01-15 00-25-08](https://user-images.githubusercontent.com/1583873/104662862-fb560300-56cb-11eb-967d-6c054cb24a76.png)

**Comment by MeghalBisht** [comment]
Taking this up!
