### ISSUE TITLE
Integrate API at the events/<event_id>/speakers route.

### ISSUE THREAD

**Issue by lunaticmonk** [fossasia/open-event-frontend#638]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
![event-speakers-api](https://user-images.githubusercontent.com/17925669/29059833-db7fb000-7c34-11e7-97d6-2a53170dfc08.png)

View, Edit, Delete actions to be dealt in separate issue.

**Comment by sumedh123** [comment]
Working on this one.

**Comment by ritikamotwani** [comment]
I would like to work on this.
