### ISSUE TITLE
Public Event Page: Enhance location/online information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6385]
On public event pages of mixed events, please change the following:
* Instead of "In-Person Event and Online Event ..[Address]" show "Online and In-Person Event at [Address]"

![Screenshot from 2021-01-15 12-05-43](https://user-images.githubusercontent.com/1583873/104718079-9aa9e300-572a-11eb-955c-07cee0788d6b.png)

**Comment by himanshujaidka** [comment]
Working

**Comment by mariobehling** [comment]
@himanshujaidka This does not work out with the way you claim issues. Please only claim one issue at a time and work on a PR until it is ready and merged. More and more open PRs and WIP PRs block the progress of the project. Please follow best practices https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

We cannot accept your claim to work on this issue here and other issues until your open PRs are finalized. Please refrain from adding more "working" comments.

**Comment by himanshujaidka** [comment]
> @himanshujaidka This does not work out with the way you claim issues. Please only claim one issue at a time and work on a PR until it is ready and merged. More and more open PRs and WIP PRs block the progress of the project. Please follow best practices https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/
> 
> We cannot accept your claim to work on this issue here and other issues until your open PRs are finalized. Please refrain from adding more "working" comments.

ok, sir leaving this issue, but I am working on other open pr's also

**Comment by nlok5923** [comment]
taking this up.
