### ISSUE TITLE
Change "Mixed" to "Hybrid" Events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6394]
It is now common to call mixed online and offline events "Hybrid Events". Therefore in wizard step 1 and other places please rename "Mixed" to "Hybrid".

![Screenshot from 2021-01-16 13-53-02](https://user-images.githubusercontent.com/1583873/104812430-5f7ae300-5802-11eb-8bc7-6bdd6ee9e607.png)

**Comment by nlok5923** [comment]
On it
