### ISSUE TITLE
Event Dashboard Overview Box: Fix location and online info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6396]
The dashboard shows "location" in the first line event for online and hybrid events. Please change this as follows. On the right-hand side show:
1. If the event is location based only show same as now.
2. If the event is online only show "Online evevent"
3. If the event is a hybrid event show "Online and in-person event at [address]."
4. If the event is "To be announced" show "To be announced".
![Screenshot from 2021-01-16 14-28-13](https://user-images.githubusercontent.com/1583873/104813225-1cbc0980-5808-11eb-9a84-17594be24a52.png)

**Comment by afzal442** [comment]
working

**Comment by afzal442** [comment]
I have been also trying. I will be leaving this issue within 2 hrs from now if I am not, so someone else can work on this. Thanks

**Comment by iamareebjamal** [comment]
Please only comment when you have at least reproduced the bug

**Comment by Sloth-Panda** [comment]
@mariobehling Do I always need to ask in an issue page and after getting assigned I work on that issue or if I directly solve the issue and send a pr that too is okay???

**Comment by mariobehling** [comment]
This area does not appear translatable. It should be possible to translate this text. Therefore reopening it.
