### ISSUE TITLE
Search box in mobile View not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6399]
The top search bar is not working in mobile view. Please also change the following
* The magnifying glass icon should always stay where it is before the use clicks on it
* Tipping on the magnifying glass icon should result in the search being performed
* When the user clicks on the search area the keyboard should open automatically
* There should be no x icon. If the user clicks outside of the search field the search should be automatically deactivated

Please compare the search functionality of the Google search box. Implement the same functionality and behavior for the search box on eventyay.

![Screenshot_20210117_013114_com android chrome](https://user-images.githubusercontent.com/1583873/104827971-a0a3df00-5864-11eb-9cb6-c9b4fa34e041.jpg)

**Comment by terminator0309** [comment]
Trying this one... Feel free to drop your PR if one anyone else want to :)
