### ISSUE TITLE
Attendee Form: Add Instagram and Linkedin

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6402]
Instagram and Linkedin are missing as standard options on the atteendee form in the wizard. Please add them in the custom form section "Information to Collect".

![Screenshot from 2021-01-17 17-58-29](https://user-images.githubusercontent.com/1583873/104850162-c4f7ce00-58ed-11eb-8817-9e511ff6d522.png)

**Comment by Naman-1234** [comment]
Working on it

**Comment by afzal442** [comment]
Looking into this.

**Comment by Naman-1234** [comment]
@afzal442  I am already working on it,So pls look into another one.

**Comment by afzal442** [comment]
Alright! U can.

**Comment by afzal442** [comment]
Working on it.
