### ISSUE TITLE
Public Event Page: Custom link boxes on right side bar are a bit out of place and distorted spacing of widgets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6403]
Link boxes of custom links are a bit out of place and spacing with above and below section is not standardized.

Please adjust as follows
* make sure the spacing between buttons is equal and also works if buttons are moved to the next row in small resolutions
* ensure the widget have the the same spacing between each other
   * menu link box
   * date/time 
   * "add to calendar" 
   * icon boxes 
   * tweet box
   * tracks/rooms
   * sessions

When you solve it, please also 
* check that is works in different languages 
* works in the mobile view.

Compare https://eventyay.com/e/3dbaaa50/schedule

**Mobile view**
![Screenshot from 2021-01-17 21-44-00](https://user-images.githubusercontent.com/1583873/104855481-50cd2280-590d-11eb-80b1-0cb712193a37.png)
<br>
<br>
**Desktop Browser**
<br>
![Screenshot from 2021-01-17 21-37-18](https://user-images.githubusercontent.com/1583873/104855304-42323b80-590c-11eb-8e35-c80d2dfcd60b.png)

**Comment by Naman-1234** [comment]
Working on it.
