### ISSUE TITLE
Order form: Filling in shipping address and hitting enter results in reloading the page and all fields reset

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6404]
When a user orders a ticket where they have to fill in address fields, e.g. shipping address and then the user hits enter, the page reloads and all fields are reset.

Compare https://eventyay.com/e/19128bdf

![Screenshot from 2021-01-17 23-48-21](https://user-images.githubusercontent.com/1583873/104858355-b675da80-591e-11eb-9a71-fb7a1139ffce.png)

**Comment by afzal442** [comment]
looking into it
