### ISSUE TITLE
Order Form:

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6405]
When a user orders a ticket and does not choose the payment provider and then clicks "Proceed", the page scrolls up to the top and the erroneous area is out of sight of the user. Expected: The page should scroll up to the first point of an erroneous area. In this case it should not scroll at all in simply show the error message that already appears.

![Screenshot from 2021-01-17 23-51-15](https://user-images.githubusercontent.com/1583873/104858422-3c922100-591f-11eb-8bbf-c9634eeba9a6.png)

**Comment by anurawat01** [comment]
@mariobehling I will love to work on this?
Can you please assign it to me?

**Comment by Aiswarika** [comment]
Can i take this up?

**Comment by anurawat01** [comment]
@Aiswarika 
Same question I did ask but I got this in reply 😅 from github bot. I am also working on it.
We don't assign issues to external contributors. Please comment that you're working on the issue after checking that no one else is, and then send a pull request for it. Thank You!
