### ISSUE TITLE
Order Form Stripe Payment: Increase button size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6406]
The order button of the stripe button is not prominent enough. Please increase the size of the "Pay Now" button to the entire width of the sidebar.

Compare https://eventyay.com/e/19128bdf

![Screenshot from 2021-01-17 23-57-17](https://user-images.githubusercontent.com/1583873/104858504-0b662080-5920-11eb-88f5-5da53d9a655d.png)

**Comment by afzal442** [comment]
Working.
