### ISSUE TITLE
Order Page: Fix wrong download option, billing icon and text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6407]
Please change the order page as follows:

1. There is a non-functional download link for a ticket, that has not been paid for yet on the "Payment Page" of the order. The download link should only be at the final page (after the payment)
2. Please change "YOUR ORDER HAS BEEN PLACED SUCCESSFULLY. YOU CAN PAY FOR YOUR ORDER TO GET TICKETS." -> "YOUR ORDER HAS BEEN PLACED. PLEASE PAY FOR YOUR TICKETS TO COMPLETE THE ORDER NOW."
compare https://eventyay.com/e/19128bdf
![Screenshot from 2021-01-18 00-02-16](https://user-images.githubusercontent.com/1583873/104858674-487ee280-5921-11eb-99ef-821d27644e9c.png)

3. The billing information has the same ticket icon as other areas. Please find a suitable icon e.g. for address.
![Screenshot from 2021-01-18 00-04-28](https://user-images.githubusercontent.com/1583873/104858750-c04d0d00-5921-11eb-83cc-1eb7856f7684.png)

**Comment by Rishikakanojia** [comment]
I want to work on this issue.
