### ISSUE TITLE
Paypal Payment not working Pop up closes without any action

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6412]
Paypal payment is not possible on this event https://eventyay.com/e/19128bdf. The paypal payment box simply closes when trying to make a payment.

![Screenshot from 2021-01-18 05-05-17](https://user-images.githubusercontent.com/1583873/104871354-2306ce80-594b-11eb-863f-f9069accd20e.png)

**Comment by mariobehling** [comment]
An issue here could be that the event charges in INR and the account I used is not based in India.
https://developer.paypal.com/docs/location/india/domestic-and-crossborder/

> PayPal currently supports Indian Rupee (INR) as transaction currency only for checkouts by consumers in India with Indian PayPal accounts. A consumer with PayPal account issued outside of India will be unable to transact in INR via PayPal. Merchants and partners are advised that they present product prices to Indian consumers in INR and to consumers outside India in currencies like USD, EUR, GBP, AUD, etc. This presentation strategy is critical to provide the optimum user experience in consumer flows and reduce declines on the account.
> To present the currency code correctly, the merchant or partner can implement a currency switch. Some examples of how a merchant or partner can implement this currency switch include:
> Providing a currency drop-down menu to the consumer to select the transaction currency of choice.
> Note: International consumers should NOT be presented INR as a currency choice. Indian consumers should be presented INR only.
> Detecting the IP address of the consumer, and presenting the appropriate currency code to the consumer.
Presenting the currency code based on the shipping address.
Any other method that identifies the consumer's country and presents the appropriate currency.

**Comment by iamareebjamal** [comment]
![image](https://user-images.githubusercontent.com/3874064/104886355-9c281500-598f-11eb-93f2-d3dcba602753.png)

Yes, that's the case

**Comment by iamareebjamal** [comment]
Once I switched PayPal account to my email, it worked, so it is related to merchant account being in wrong country

**Comment by iamareebjamal** [comment]
https://www.paypal-community.com/t5/REST-APIs/CURRENCY-NOT-ALLOWED-INR/td-p/2276511
