### ISSUE TITLE
My tickets page: Canceling ticket results in unexpected error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6413]
When canceling a ticket directly from the my tickets page, there is an error message "Unexpected Error". Then the ticket stays as is. Clicking on the order shows "Ticket Canceled". 

However on the my tickets page should now show up in a tab "Canceled tickets" under "upcoming events". And if the event is in the past it should show up under "Canceled" for past events.

Now: If the user refreshes the my tickets page the canceled ticket is back and not canceled anymore. Also the order page no longer shows canceled.

![Screenshot from 2021-01-18 07-07-52](https://user-images.githubusercontent.com/1583873/104878457-48e89f00-595c-11eb-90dd-4bab25820ed0.png)

![Screenshot from 2021-01-18 07-13-14](https://user-images.githubusercontent.com/1583873/104878678-a8df4580-595c-11eb-97a2-2c5d83348fc6.png)

**Comment by shivamsingh-07** [comment]
@mariobehling Can I work on this issue? If I got stuck or need any help I'll let you know.

**Comment by shivamsingh-07** [comment]
On clicking Cancel Ticket button, it is calling API with PATCH request which is giving a "403 Access Forbidden" error. But I think it should be calling API with DELETE request according to [API docs](https://api.eventyay.com/#orders-order-detail-patch).

![](https://user-images.githubusercontent.com/61000207/104923793-926bd500-59c2-11eb-8331-b1b46a29acba.png)

Correct me If I'm wrong. Also I can't figure out, how this API is being called ?

**Comment by shivamsingh-07** [comment]
After trying to reproduce the same bug on the development server, I got no errors. I think this might be a [server](https://github.com/fossasia/open-event-server) side issue.

![Screenshot](https://user-images.githubusercontent.com/61000207/104934078-b84ba680-59cf-11eb-8c56-835260a6ff20.png)

**Comment by iamareebjamal** [comment]
Fixed by https://github.com/fossasia/open-event-server/pull/7667
