### ISSUE TITLE
Virtual Events: Implement video tab on/off switch similar to wizard switches and show pop-up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6416]
The video event feature should be available for up to 25 people free of charge. Some online events might not want the video feature and they have the option to add details elsewhere. Organizers should therefore be able to switch the feature on and off. 

Before we implement details of the invoice process, we need to give organizers the option to actually do switch the feature on and off and provide information about the functionality and costs to users. 

Therefore please implement the following
* Add a switch button to switch the feature on and off similar to the wizard e.g. the attendee form
* When the user switches the feature on, show a pop up with the following text 
   * "The video room feature is available free of charge for events with up to 25 tickets. For events with more than 25 ticket registrations a one-time charge of 2 USD (or 2 Euro for Euro events) will be added per ticket. This fee will be charged monthly for any new registrations only. It is non-refundable in case ticket holders cancel their registration or if the feature is switched off at a later time. By activating this feature you agree to pay the one-time fee per ticket. Do you want to activate this feature now and agree to pay the additional ticket fee per ticket if the number of your tickets is above 25 tickets?"
   * Yes -> "Yes - activate video rooms now. I agree to pay the fees." / No -> "No, do not activate it."
* When an organizer switches off the feature show this 
    * "If you switch off the feature, video rooms will no longer be available for ticket holders. Data you entered will no longer be visible for your attendees and speakers. Fees for ticket holders you might have paid already will not be refunded. Do you really want to switch off this video feature?
    * "Switch off."-> switches it off. "Continue using video rooms." -> leaves them on as is.
* Do not delete any video room data when the user switches it off. Simply deactivate the UI.

![Screenshot from 2021-01-18 17-11-46](https://user-images.githubusercontent.com/1583873/104939102-49128a00-59b0-11eb-857a-d24c9cdf3905.png)

![Screenshot from 2021-01-18 13-49-08](https://user-images.githubusercontent.com/1583873/104917634-f5924300-5993-11eb-998c-eb18f23214db.png)

**Comment by Keshav04042001** [comment]
Oky sir,i got it.
I'll fix this, going through the codebase

**Comment by akash2408** [comment]
working on it
