### ISSUE TITLE
Public Event Page: Large space above ticket box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6428]
The public ticket page of an event shows a large space above the ticket box. The space does not exist in the rich text editor of the description. Possibly it is caused by invisible tags?

![Screenshot from 2021-01-19 17-52-11](https://user-images.githubusercontent.com/1583873/105066698-58143d80-5a7f-11eb-81e0-06dbee260b01.png)

**Comment by himanshujaidka** [comment]
Looking into it

**Comment by himanshujaidka** [comment]
![Screenshot (147)](https://user-images.githubusercontent.com/58654018/105073288-dfc47100-5aac-11eb-9386-5941c01c3b38.png)
@mariobehling It seems to work fine

**Comment by iamareebjamal** [comment]
@mariobehling Event Link?

**Comment by iamareebjamal** [comment]
Not reproducible for me

**Comment by iamareebjamal** [comment]
We need to truncate leading newlines/breaks in the rich text editor
