### ISSUE TITLE
After Order Message: Show message with line breaks on order page and in email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6429]
The after order message in wizard step 1 shows line breaks, but on the final order page and in the attendee mail the order message does not have line breaks. Please ensure the after order message shows up in the same way with line breaks as set in the wizard.

![Screenshot from 2021-01-19 18-20-01](https://user-images.githubusercontent.com/1583873/105070167-31f09c80-5a83-11eb-8898-0d1d65e97551.png)

![Screenshot from 2021-01-19 18-22-05](https://user-images.githubusercontent.com/1583873/105070263-4cc31100-5a83-11eb-9afa-e826fdae0c7b.png)

**Comment by nlok5923** [comment]
On it.

**Comment by himanshu007-creator** [comment]
i would like to work on this issue.

**Comment by SARTHAK1SINGH** [comment]
@mariobehling can we use rich text editor?

**Comment by iamareebjamal** [comment]
The issue is about displaying the message, how will you solve it by using a rich text editor?

**Comment by alkatrivedi** [comment]
Working
