### ISSUE TITLE
Scrollbar needed in filter categories

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/open-event-frontend#6431]
When a user wants to apply or see the filter details then the user has to move the main scroll-bar.

I think the scroll-bar should be there for scrolling the filters. 

![Screenshot (146)](https://user-images.githubusercontent.com/58654018/105072968-67f64680-5aac-11eb-8b47-0306ed487f97.png)

**Comment by Naman-1234** [comment]
Working on it

**Comment by mariobehling** [comment]
Not needed as people can already scroll the entire page.

**Comment by himanshujaidka** [comment]
> Not needed as people can already scroll the entire page.

but when there will be a lot of events and the user wants to match some event details then I think it may be caused some difficulty to cross-check the event details and filters
