### ISSUE TITLE
Draft Event: Settings Tab: Error - Could not fetch from the server

### ISSUE THREAD

**Issue by MeghalBisht** [fossasia/open-event-frontend#6436]
**Describe the bug**

After creating an event and marking it as draft. When "Settings Tab" is navigated.
Error occurs : Could not fetch from the server

**To Reproduce**
Steps to reproduce the behaviour:
1. Create event and mark it as draft
2. Go to "Manage Event"
3. Go to "Draft Event"
4. Navigate to the "Settings Tab"
5. Error occurs

**Screenshots**

![Capture](https://user-images.githubusercontent.com/61330148/105089477-32108c80-5ac3-11eb-87dc-c32d6ebcfc54.PNG)

**Desktop & Smartphones (please complete the following information):**
ALL

**Comment by afzal442** [comment]
I think this was an Export page's issue from beginning. You can find this issue without drafting it.

**Comment by g4rry420** [comment]
```
    def after_get_object(self, event, view_kwargs):
        if event and event.state == Event.State.DRAFT:
            if not is_logged_in() or not has_access('is_coorganizer', event_id=event.id):
                raise ObjectNotFound({'parameter': '{id}'}, "Event: not found")
```
This error is because of this code in the backend in the `api/events.py` in `EventDetail` class. I am not sure why this is written. If somebody else can reflect on this about why is this code written ?

**Comment by mariobehling** [comment]
@g4rry420 Thank you for the comment. We are now looking into details. Cheers!

**Comment by klsingh016** [comment]
can i work on ?
