### ISSUE TITLE
Implement attendees API on tickets/attendees

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#644]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/29119841-5897cc94-7d25-11e7-8f33-8f9d6efc0ad1.png)

**Comment by CosmicCoder96** [comment]
On hold until orders api is completed.

**Comment by geekyd** [comment]
@CosmicCoder96 Is this on hold till https://github.com/fossasia/open-event-orga-server/issues/4265 is resolved?

**Comment by CosmicCoder96** [comment]
@geekyd This. https://github.com/fossasia/open-event-orga-server/issues/4264
