### ISSUE TITLE
Event Calendar Sharing Feature: Add event link, event description and organizer message

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6446]
The share event calendar does not have a link to the public event page. Also the organizer message is missing. 

Please implement the following

1. For online events in the "Location" field additionally add the URL to the public eventyay page 
2. In the description:
    a) On top add "Join the event at {eventyay link to public event page}" e.g. "Join the event at https://eventyay.com/e/f4fc71b8"
    b) Add a section heading "Event Description" and show the event description below
    c) Add a section heading "Organizer Message" and show the text including line breaks below
3. Test the outcome on different platforms, ics etc. e.g. on Gmail.
4. Ensure that everything is translatable.

![Screenshot from 2021-01-20 23-57-10](https://user-images.githubusercontent.com/1583873/105251417-bc1c2c00-5b7b-11eb-91dc-cb1f77d3667d.png)

**Comment by Mr-codehunter** [comment]
please assign me to solve the this issue.
--
 Deepak Kumar

**Comment by Mr-codehunter** [comment]
On Thu 21 Jan, 2021, 10:39 AM github-actions[bot], <notifications@github.com>
wrote:

> We don't assign issues to external contributors. Please comment that
> you're working on the issue after checking that no one else is, and then
> send a pull request for it. Thank You!
>
Ok firstly i will check the issue and the send a pull request.

--
 Deepak kumar

**Comment by Draco9421** [comment]
can I work on it ?
