### ISSUE TITLE
Attendee Form: Simplify form, fix order, show helper text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6454]
The attendee form in the wizard and public form are not ordered in the same way. Instead of alphabetical order they should be ordered according to content logic. Furthermore the implementation of address fields in Home Address, Billing Address, Shipping Address, Work Address is not complete as it is missing city, country etc. and it would be helpful if the helper text was visible in the wizard itself.

Therefore please change the following:
1. Hide the following address options but keep the standard form field "Address". For now we will not use the address options such as:
* Home Address
* Billing Address
* Shipping Address
* Work Address
2. Change the field "Address" to "Address (Street, Building, Number etc.)"
3. Change the order of the fields to the following:
- Job Title
- Phone
- Work Phone
- Age Group
- Gender
- Organisation
- Tax Business Info
- Address (Street, Building, Number etc.)
- City
- State
- Country
- Website
- Blog
- LinkedIn
- Twitter
- GitHub
- Facebook
- Instagram
- Email consent
- Partner contact consent
- Photo & video & text consent
4. Increase the width of the table and include the "Helper Text" below each option (in the same cell)
5. Ensure the order on the public form page of attendees is the same as in the wizard
6. Fix the display of the form type column - show "switch" for switches instead of "checkbox"

![Screenshot from 2021-01-21 12-01-19](https://user-images.githubusercontent.com/1583873/105352107-c6770e00-5bed-11eb-8157-63e89ae0228b.png)

**Comment by Soumi150** [comment]
Working on this.

**Comment by MeghalBisht** [comment]
1. Hide the following address options but keep the standard form field "Address". For now we will not use the address options such as:
> 
> * Home Address
> * Billing Address
> * Shipping Address
> * Work Address

@iamareebjamal These fields need to be removed from the server as well?

**Comment by iamareebjamal** [comment]
No, just remove from the frontend fields

**Comment by MeghalBisht** [comment]
> 1. Increase the width of the table and include the "Helper Text" below each option (in the same cell)

What is meant by the "Helper Text"?
