### ISSUE TITLE
Admin: Move "Social Media" tokens and account info to dedicate admin tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6459]
On the admin page at https://eventyay.com/admin/settings we have a number of social media accounts listed. The page is a bit long now. Please move the accounts to a dedicated tab and the URL https://eventyay.com/admin/settings/social-media

![Screenshot from 2021-01-21 16-03-03](https://user-images.githubusercontent.com/1583873/105369040-70f92c00-5c02-11eb-91d4-583ca70325ab.png)
![Screenshot from 2021-01-21 16-02-39](https://user-images.githubusercontent.com/1583873/105369045-722a5900-5c02-11eb-8d2c-ea3e6460966b.png)

**Comment by SheldonnC** [comment]
Sir may I work on this issue?

**Comment by afzal442** [comment]
@iamareebjamal sir how to access admin page??

**Comment by iamareebjamal** [comment]
By setting up server locally
