### ISSUE TITLE
Cookie Policy: Internationalization

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6460]
The cookie policy should be available in different languages. 

Therefore please 
* implement language tabs or a similar way on the cookie policy box in the admin menu (https://eventyay.com/admin/settings), where we can add the translation.
* implement support to show the required translation that a users has chosen when the cookie policy is shown.

![Screenshot from 2021-01-21 16-06-49](https://user-images.githubusercontent.com/1583873/105369718-1ad8b880-5c03-11eb-92b8-2e13e505722f.png)

**Comment by meprogemur** [comment]
I'm working on this.

**Comment by meprogemur** [comment]
@mariobehling I'm unable to see the cookie policy page, can you help?
<img width="746" alt="foss" src="https://user-images.githubusercontent.com/59791758/110204322-6506b800-7e98-11eb-87d5-51429bfe1dc7.png">

**Comment by HarryHuy** [comment]
@meprogemur Are you using local server with your self-created admin account?

**Comment by tanay123456789** [comment]
working on this

**Comment by tanay123456789** [comment]
There was something wrong that I did to the previous PR that's why I closed that one and created a new one

**Comment by tanay123456789** [comment]
ANY OTHER PERSON CAN TAKE THIS ISSUE

**Comment by maze-runnar** [comment]
@MeghalBisht please look into it, if we can solve this soon and close this.

**Comment by MeghalBisht** [comment]
Currently we don't have this feature. Not sure how this would be done. Not a priority at the moment as well

**Comment by maze-runnar** [comment]
cool 👍🏻

**Comment by mariobehling** [comment]
This has been solved.
