### ISSUE TITLE
Speaker Edit Form: Gender field entry disappears.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6461]
In the CfS speaker details the entry for the field "Gender" regularly disappears after some time and the speaker has to enter the Gender again. 

When the user fills in the field and saves it, it is there. Also when the user enters the form again it is still there. However, a few minutes later or when the user has a new session a few hours later and opens the edit speaker form page again the field entry is gone.

Please ensure the "Gender" field entry is stored properly.

![Screenshot from 2021-01-21 16-18-06](https://user-images.githubusercontent.com/1583873/105371088-8c653680-5c04-11eb-889d-d93cd11fe835.png)

**Comment by mariobehling** [comment]
Issue still happening. Sometimes the gender fields disappears, sometimes it stays. Then the "view" page also shows some cryptic info, e.g. here "Female" was filled in and the view page shows "st1407".

Compare https://eventyay.com/events/fa96ae2c/speaker/5138

![Screenshot from 2021-01-29 23-14-46](https://user-images.githubusercontent.com/1583873/106332959-03936e00-6288-11eb-9016-7598fb61ccac.png)

**Comment by iamareebjamal** [comment]
Value stored in backend is st1407
![image](https://user-images.githubusercontent.com/3874064/106334187-26d21380-62b0-11eb-8098-9eb1b7ae5631.png)

Any chance the user used API to store the info and not frontend? Gender is simple text field, anything can be stored in it
