### ISSUE TITLE
CfS: Session and Speaker view pages link to sessions or speakers page respectively and add spacing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6469]
The Cfs session view pages and speaker view page already list the speaker or sessions respectively. 

1. Please link them to the CfS view page instead of only displaying the name of the session or speaker.
2. Increase the white space below the bottom of the form on the view page.
3. Increase the white space below the bottom on the form on the edit page of sessions and speakers.

![Screenshot from 2021-01-23 19-59-16](https://user-images.githubusercontent.com/1583873/105611501-1274af00-5db6-11eb-8256-102e331b2463.png)

![Screenshot from 2021-01-23 19-58-47](https://user-images.githubusercontent.com/1583873/105611503-130d4580-5db6-11eb-9aab-95f628b058c4.png)

**Comment by afzal442** [comment]
looking into this

**Comment by afzal442** [comment]
@iamareebjamal sir, in the list is first one about linking name of the session or speaker of overview page to the CfS view page??
