### ISSUE TITLE
Sign up: Show "Thank you/Info" message and redirect to the previous page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6471]
After signup there is no message what happened for the user and what they have to do next. Therefore please implement the following after the signup process to enter email and password:
1. Show a popup "Thank you for signing up on eventyay.com. We have sent an email with a verification link to you. Please go to your email account and verify your email to get full access to the system. We are logging you into your newly created account now, but your account functionalities are limited until your email is verified. Please press "Ok" to be redirected to the previous page." [OK]
2. When the user presses "Ok" redirect the user to the page they visited before they signed up, e.g. Call for speakers of an event, Frontpage, Public event page of a specific event.
3. Do not offer the option to click the "not verified" message away. The message should always be visible unless the account is verified.
![Screenshot from 2021-01-23 23-03-35](https://user-images.githubusercontent.com/1583873/105615440-00543a00-5dd1-11eb-91df-c1bdbd8034b5.png)

**Comment by Naman-1234** [comment]
Working on it

**Comment by Draco9421** [comment]
can I work on it.

**Comment by Naman-1234** [comment]
@Draco9421 , I am working on this, So pls find another issue to work on

**Comment by Draco9421** [comment]
> @Draco9421 , I am working on this, So pls find another issue to work on

Ohk bro no problem.

**Comment by Draco9421** [comment]
@ranjitkshah are you working on this issue ?

**Comment by leoshrey** [comment]
Hi, As I can see this issue is open from 9 days. So, if no one is working on this issue then I would like to proceed for the same.

**Comment by iamareebjamal** [comment]
A draft PR is created for this
