### ISSUE TITLE
Discount and Access Code: Make URL into a URL box and change the "actions icons" from vertical to horizontal

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6472]
To improve the access and discount code overview please change the following:
1. Make the URL into a URL box like on the video area 
2. Change the "actions icons" from vertical to horizontal.

![Screenshot from 2021-01-23 23-52-13](https://user-images.githubusercontent.com/1583873/105616329-64c5c800-5dd6-11eb-8378-4d2473168617.png)

**Comment by afzal442** [comment]
Working on this
