### ISSUE TITLE
Discount and Access Code: Create a CSV code upload option and option to delete all unused discount codes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6473]
A request by users with a lot of discount codes was to
1. provide an option to upload a list with many CSV codes. 
2. provide an option to upload a CSV and update existing codes
3. If something goes wrong here users also want to be able to delete unused discount codes. 
4. And to check which codes have been used please test that the codes show up in the orders and tickets CSV that organizers can download.
5. To be able to access the upload/update functionality with a CVS list via REST-API. The goal is to have the possibility to update the list when new discount codes are created on an external service. (Use case is this: A company has a list of customers and each one gets a discount code. After some time they get additional new customers. They want to be able to update the list of discount codes and add new codes for new customers automatically).

Compare this functionality to https://www.eventbrite.com/support/articles/en_US/How_To/can-i-upload-a-list-of-discount-or-access-codes?lg=en_US

![Screenshot from 2021-01-23 13-34-15](https://user-images.githubusercontent.com/1583873/105616410-f33a4980-5dd6-11eb-9b9e-3f8a6499c024.png)

**Comment by iamareebjamal** [comment]
> To be able to access the upload/update functionality with a CVS list via REST-API

When they have access to REST API, they can already create discount codes dynamically, without a new API which handles CSV files, which would be less robust and more error prone

**Comment by mariobehling** [comment]
To clarify this with our partner, updating the codes via the REST API would then work as follows:

1. Delete complete code list via the REST API (as a kind of loop over all codes)
2. Add new code via the REST API for discount code XYZ to ticket type ABCD

This means that there would be no CSV upload via the REST API, but "known" methods such as Delete and Create that can be used.

But we would still have restrictions in regards to which codes can be deleted, I think. So, it will not be possible to delete codes that were already used in the event, right?

**Comment by iamareebjamal** [comment]
If new codes are to be added, there is no need to delete complete code list, just add new codes using the API

Currently, there is no restriction on preventing deletion of used discount codes. Should this be added to the existing API such that any discount code which was used in an order cannot be deleted, or a new API should be created just for this use case to delete all discount codes which are not used.

**Comment by iamareebjamal** [comment]
To delete all unused discount codes in an event, send a `DELETE` request to `{{server}}/v1/events/{{id}}/discount-codes/delete-unused`
