### ISSUE TITLE
Discount/Access Code: Implement "Start now" and "When sales end" by default

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6476]
Many organizers only want a simple way to create discount and access code and choose the dates of validity. Therefore please implement the dates for codes to be valid as below "Start now" and "When sales end" by default.

![Screenshot from 2021-01-24 11-57-11](https://user-images.githubusercontent.com/1583873/105628149-73929600-5e3b-11eb-8aee-10804d833fcf.png)

**Comment by maze-runnar** [comment]
on it

**Comment by maze-runnar** [comment]
it is already set to start now and end date of event.
![Screenshot from 2021-01-26 11-05-51](https://user-images.githubusercontent.com/56407566/105804757-99987180-5fc6-11eb-8deb-a0e3c5ed04cd.png)

**Comment by iamareebjamal** [comment]
This is static, we want an option so that even if we change the event dates, it stays till the end

**Comment by maze-runnar** [comment]
ok

**Comment by maze-runnar** [comment]
so working would like, if a user selects option of while sales end for any access code/discount code then it's value would be changed whenever event.endsAt would changes?

**Comment by iamareebjamal** [comment]
No, no need of changing value. It should just work till the end of the event

**Comment by maze-runnar** [comment]
the frontend PR was complete, it was not merged due to some reason, so the issue is technically closed. if anyone can test that PR and merge that?
