### ISSUE TITLE
Speakers Form: Only show desired languages as an option

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6484]
The CfS offers all languages, but organizers usually only want a few languages, e.g. in countries where two languages are used or International events that take place in a mixture English and French for example.

Please propose and implement a way to only show the appropriate languages in the session form.

![Screenshot from 2021-01-25 19-20-50](https://user-images.githubusercontent.com/1583873/105752742-f9036c80-5f47-11eb-9f03-9e06375be869.png)

![Screenshot from 2021-01-25 19-21-12](https://user-images.githubusercontent.com/1583873/105752739-f86ad600-5f47-11eb-85cd-bfbd30238c23.png)

**Comment by SAEb-ai** [comment]
@mariobehling Can you please provide me the link of the sessions form in this repo??

**Comment by iamareebjamal** [comment]
@mariobehling What should be the appropriate languages?

**Comment by helenvarley** [comment]
hi, i don't know if this is the right place to ask, but i'm evaluating ticketing systems at the moment & need something that supoprts multiple languages. i couldn't find it in the FAQs for Eventyay, so am wondering if this is something that is still in development? thanks.

**Comment by mariobehling** [comment]
I am closing this issue as it is currently out of scope.
