### ISSUE TITLE
Virtual Events: Hide "Embed" option on Jitsi Calls

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6487]
The embed option in Jitsi is a feature that we do not really want here as it would allow others to embed a call elsewhere. Please try to hid the functionality. Can this be achieved even without having access to Jitsi itself, e.g. with CSS?

![Screenshot from 2021-01-25 22-52-36](https://user-images.githubusercontent.com/1583873/105771470-e47f9e00-5f60-11eb-976a-708c328c2c1e.png)

**Comment by Creatoon** [comment]
Working.
