### ISSUE TITLE
Orders Page: Add ticket cancellation box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6489]
Please add a box on the bottom of order pages as follows:
* Heading (gray same as attendee info box): Ticket cancellation
* Text: You can cancel this order with the button below. This will void all tickets in this order.
* Add button "Cancel Order" 

![Screenshot from 2021-01-26 02-38-25](https://user-images.githubusercontent.com/1583873/105787892-acd41e80-5f7f-11eb-8385-cc5e9b4f9619.png)

![Screenshot from 2021-01-26 01-36-33](https://user-images.githubusercontent.com/1583873/105787641-2ddee600-5f7f-11eb-9959-c9cf0788626e.png)

**Comment by maze-runnar** [comment]
on it
