### ISSUE TITLE
CfS: Add option to invite another speaker by email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6490]
Currently the option to add more speakers to a session is missing. Only the organizer can do this at the moment. 

On the bottom of a session form please add the option to "Invite additional speaker by email". This should work as follows:
1. The speaker of a session adds an email to the form
2. The additional speaker receives and email "{Name of first speaker] has invited you to a session submission titled {name of session} on {event name} on {app name}. You can accept this invitation at the following link {link here}. Users without an account need to register first before being able to accept invites."
  * [ ] If the user is already registered and logged in to eventyay direct the user to the "Create Speaker Profile" page.
  * [ ] If the user is not yet registered display the message "You need to register or login to {app name} before you can accept this invitation. You are now being directed to the registration page." After registration direct the speaker to the "Create Speaker Profile" page.
  * [ ] If the user is registered but not logged in, show "You need to login to accept this invitation." then direct the user to the login page. After loggin in direct the user to the "Create Speaker Profile" page.
3. After the speaker profile is created show the link of the session the speaker was invited to and allow editing of the session by the additional speaker.
4. If the speaker does not create the speaker profile and visits the CfS page, show the session name that the speaker was invited to, but do not provide it as a link. Instead show a message "You need to create a speaker profile first before you can edit or create sessions."

**Comment by Draco9421** [comment]
can I work on it.

**Comment by mariobehling** [comment]
There is still an old PR from you that is not finished. What do you need in order finish it? Please follow up in the PR or gitter chat.

**Comment by Draco9421** [comment]
> There is still an old PR from you that is not finished. What do you need in order finish it? Please follow up in the PR or gitter chat.

ok

**Comment by iamareebjamal** [comment]
> ok, I will sea into that first.

:ocean:

**Comment by nishihere19** [comment]
Can I work on the issue? Also, correct me if I am wrong, we need the invite option below the ticket ordering section right?
