### ISSUE TITLE
Ticket Invoice: Do not show Organizer Message in invoice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6493]
The ticket invoice should not show the organizer message. It is an invoice and should only show relevant invoice information.

![Screenshot from 2021-01-26 07-26-34](https://user-images.githubusercontent.com/1583873/105808490-1700b980-5fa8-11eb-9ed9-59f884648bab.png)

**Comment by Draco9421** [comment]
Is this issue is solved ?
