### ISSUE TITLE
My tickets: Sort ticket list by event date

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6498]
The tickets in the my tickets page are not sorted according to date. Please sort them by date with the oldest events first (closest to the current date).

![Screenshot from 2021-01-26 23-42-14](https://user-images.githubusercontent.com/1583873/105916400-211aca80-6031-11eb-9c17-a4aee5515ee6.png)

**Comment by Soumi150** [comment]
Working on this.
