### ISSUE TITLE
Order cancellation email: Wrong text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6499]
The order cancellation email states that a ticket has been "cancelled by the organizer" even if the user has cancelled it her/himself.

Please change the email as follows:

=========================================================

Subject: Your order for {event name} has been cancelled ({order number})

Hello,

Your order {order number} for {event name} has been cancelled.

The information about your cancelled order is here: {link to order}

If you have not done this cancellation by yourself, please check with the owner of the order or the organizer of the event for more information about the cancellation.

To contact event organizers please use the contact form on the event page here: {link to event page}

You need to login to access the form.

Best regards,

eventyay Team

--
Login to manage your orders at https://eventyay.com 

================================================
![Screenshot from 2021-01-26 23-51-17](https://user-images.githubusercontent.com/1583873/105916638-81aa0780-6031-11eb-8f64-864b011f9ea2.png)

**Comment by iamvaishnav** [comment]
Working on it

**Comment by maze-runnar** [comment]
this should be only when user canceled ticket or any of user/organizer cancels the order. 
```
Hello,

Your order {order number} for {event name} has been cancelled.

```
