### ISSUE TITLE
CSS: Overflow of order now button in ticket component on small screens

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#65]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26285507/d51809d4-3e7b-11e7-9704-6133dad41672.png)

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26285510/e38d6a40-3e7b-11e7-96e2-a38ee8e63a3b.png)
**Steps to reproduce:**

View the ticketing  section of events in mobile portrait mode.

**Comment by geekyd** [comment]
Closing this. This was solved in #66
