### ISSUE TITLE
Online Event Sidebar: Align text and buttons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6510]
The text and buttons on the online event sidebar are not aligned. Please align them according to the "video box". At the same time avoid that the minimize arrow button [<] does not overlap any text.

![Screenshot from 2021-01-28 16-00-00](https://user-images.githubusercontent.com/1583873/106157066-98ac3f00-6182-11eb-95bb-3404a1071f63.png)

**Comment by Creatoon** [comment]
working

**Comment by ranjitkshah** [comment]
> working

@Creatoon 🙁

**Comment by Creatoon** [comment]
> > working
> 
> @Creatoon slightly_frowning_face

ok now your pr is showing up, previously not, go on
