### ISSUE TITLE
Create Event : Field may not be null error while creating event.

### ISSUE THREAD

**Issue by aditee-singh** [fossasia/open-event-frontend#6512]
**Describe the bug**

I have filled all the required fields but on pressing next I get 'Field may not be null' error. Screenshots for the same are attached below. Also, my e-mail is not verified. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Create Event'
2. Fill the required fields 
3. Scroll down to bottom
4. Press Next

**Expected behaviour**

It should take you to the next page
**Screenshots**

![Screenshot from 2021-01-28 23-27-20](https://user-images.githubusercontent.com/61141867/106179802-8c93a200-61c1-11eb-8bec-95a692220eeb.png)
![Screenshot from 2021-01-28 23-27-49](https://user-images.githubusercontent.com/61141867/106179859-9cab8180-61c1-11eb-9cc2-f132532d96bd.png)
![WhatsApp Image 2021-01-28 at 11 39 33 PM](https://user-images.githubusercontent.com/61141867/106180290-1fccd780-61c2-11eb-8223-9697f64f7055.jpeg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Chrome

**Comment by pushpak25w** [comment]
This bug was not reproduced for me.
