### ISSUE TITLE
Organizer Session Page: Changing Status results in disappearing sessions and required manual reload

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6516]
When an organizer accepts sessions they disappear from the list and the organizer needs to refresh the page without certain filters in order for sessions to become visible again.

![Screenshot from 2021-01-29 00-28-37](https://user-images.githubusercontent.com/1583873/106211470-26128200-61c9-11eb-947a-b3f70c688b91.png)

**Comment by iamareebjamal** [comment]
If you are on pending page and change session to accepted, it won't be visible in pending page
