### ISSUE TITLE
Organizer Speaker/Session Page: Colors of status badge differ

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6521]
The colors of the status badges e.g. "Accepted" differ between the speaker overview page and the session overview page of organizers.

Please use the same colors everyhwere.

![Screenshot from 2021-01-29 06-58-43](https://user-images.githubusercontent.com/1583873/106237723-a9e76100-61ff-11eb-9360-c635cd199a70.png)
![Screenshot from 2021-01-29 06-58-26](https://user-images.githubusercontent.com/1583873/106237727-ab188e00-61ff-11eb-885b-9f358301c6ac.png)
![Screenshot from 2021-01-29 06-58-00](https://user-images.githubusercontent.com/1583873/106237728-abb12480-61ff-11eb-82d0-0759dc28a334.png)

**Comment by Naman-1234** [comment]
Working on it.

**Comment by Naman-1234** [comment]
@mariobehling  Sir sorry for disturbance but could you please provide the link for same.

**Comment by afzal442** [comment]
@Naman-1234 Steps to reproduce: First create a session, then add a speaker there. Then make sure you click on accepted button on session overview page. After that, you can see that speaker on speaker overview page as rejected or accepted depending upon your cgoice.

**Comment by Naman-1234** [comment]
@afzal442  , Thank you so much for guiding me.

**Comment by afzal442** [comment]
@Naman-1234 R u able to find that??

**Comment by afzal442** [comment]
> @Naman-1234 R u able to find that??

@akash2408 I was waiting for this comment. I already had the solution. Thanks.

**Comment by Naman-1234** [comment]
@afzal442 , Yeah I fixed it now, Was about to Push them right now but then someone has already done a PR, So I didn't do the PR.

**Comment by afzal442** [comment]
@Naman-1234 this platform is for collaborative team work and at the same time it is contest for us.

**Comment by Creatoon** [comment]
Working
