### ISSUE TITLE
Organizer Session Overview: Re-add rating columns to all session tables

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6523]
The organizer session overview page does not have the column for ratings anymore. Please re-add rating columns to all session tables and ensure the feature works.

The feature was originally implemented here https://github.com/fossasia/open-event-frontend/pull/3198

![Screenshot_2019-08-01 Confirmed Sessions AddOwnerEvent Events Open Event](https://user-images.githubusercontent.com/25428397/62270681-358a0100-b454-11e9-8e1f-5db8c9181ec5.png)

**Comment by afzal442** [comment]
Looking into it. Once I m done. I will share a screenshot here.

**Comment by afzal442** [comment]
@mariobehling sir I think rating column is already there.

**Comment by afzal442** [comment]
@mariobehling sir 'sortby' is not working.
