### ISSUE TITLE
Verification Link Signup issue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6529]
Several speakers are reporting a sign up issue and get browser errors as below.

![0135e749-6c0d-4a99-b0ab-465f331036da](https://user-images.githubusercontent.com/1583873/106306486-6ec84a80-625e-11eb-8ff6-ca565e344e8f.jpeg)
![photo4944972002129717599](https://user-images.githubusercontent.com/1583873/106306494-6f60e100-625e-11eb-8652-804ffb2e8708.jpg)

**Comment by iamareebjamal** [comment]
Fixed
