### ISSUE TITLE
Sesssion notification Emails: Adjust info in "From" field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6531]
The from field in the notification emails currently shows "Some Name emailaddress@emaildomain.com". Please change it to "`Some Name <emailaddress@emaildomain.com>`".

![Screenshot from 2021-01-29 19-39-09](https://user-images.githubusercontent.com/1583873/106314384-f5365980-6269-11eb-8f55-253673362941.png)

**Comment by himanshujaidka** [comment]
I think the both the cases are same?

**Comment by mariobehling** [comment]
Ok, it was not showing because of Markdown conversion. Now showing the desired version.

**Comment by himanshujaidka** [comment]
Working
