### ISSUE TITLE
Public Speaker Page: Lazy Loading of speakers very slow

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6533]
On the Public Speaker Page the lazy loading of speakers can be very slow taking more than a minute event or even sometimes the loading never stops and continues for ever without showing images. Please check and ensure the loading happens faster.

Compare https://eventyay.com/e/fa96ae2c/speakers

![Screenshot from 2021-01-29 20-17-29](https://user-images.githubusercontent.com/1583873/106317863-367d3800-626f-11eb-8c48-170a026d9f95.png)

**Comment by mariobehling** [comment]
As a matter of fact the page currently does not load more than 24 speakers in total.

**Comment by iamareebjamal** [comment]
There are only 24 accepted/confirmed speakers

**Comment by mariobehling** [comment]
There is a continuous loading icon. Then this is the issue.

**Comment by iamareebjamal** [comment]
Loading indicator issue is fixed. Slow loading remaining and not an easy issue to fix

**Comment by iamareebjamal** [comment]
Previously, we were loading 9 speakers instead of 21, then it showed more loading states than currently. Now, we are loading 21, which is much more data and thus even if it requires less loading, it takes more time. It is a tradeoff, so what should be done?
