### ISSUE TITLE
Public Event Page: Left Sidebar not longer moving down on scroll down

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6534]
One of the recent changes changed the behavior of the left sidebar. The left sidebar used to move down when the user scrolls down the page. This behavior disappeared. Please re-instate this sidebar behavior.

Compare https://eventyay.com/e/fa96ae2c/

![Screenshot from 2021-01-29 20-50-07](https://user-images.githubusercontent.com/1583873/106320876-c1f8c800-6273-11eb-809d-49f35c13bc48.png)

**Comment by amnindersingh12** [comment]
Greetings sir, I am working on this issue.

**Comment by dhruvin1831** [comment]
@iamareebjamal @mariobehling  I have found the bug and a possible solution, the sticky element is sticking to its nearest ancestor that has a scrolling mechanism. Overflowing of a parent container is inhibiting the sticky behavior of the sidebar. 

I am a beginner and want to start with this.

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by JatinAgrawal94** [comment]
Is this issue Still open ? As the sidebar is working perfectly file on the website.

**Comment by dhruvin1831** [comment]
@mariobehling The sidebar is now working fine. I test the issues raised in pr #6623.

![Screenshot 2021-03-10 015838](https://user-images.githubusercontent.com/70140023/110533956-8ab7e980-8144-11eb-944c-d47596e95a9f.jpg)
