### ISSUE TITLE
Organizer Session/Speaker Page: Make buttons and title into a link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6541]
The action buttons and titles are not links. This means the organizer cannot simply open them in a new tab. Please change them into links. The titles should link to the organizer "view" page.

Please also make the speaker image into a link to the speaker "View" page for the organizer.

![Screenshot from 2021-01-30 10-30-26](https://user-images.githubusercontent.com/1583873/106352835-76333680-62e6-11eb-8f7d-3256532f491e.png)
![Screenshot from 2021-01-30 10-30-00](https://user-images.githubusercontent.com/1583873/106352837-77646380-62e6-11eb-98d0-5b8b6b0d0d5c.png)

**Comment by afzal442** [comment]
Working

**Comment by afzal442** [comment]
@mariobehling sir, I tried it out with various ways but failed to make speaker image into a link to the speaker "View" page. Thanks

**Comment by afzal442** [comment]
Everything else works fine
