### ISSUE TITLE
Organizer Area: Speaker View Page shows links even if field was left empty

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6546]
There are social media links showing up on the speaker view pages accessible by organizers. If speakers leave the field empty these links show up even though they should not show up.

![Screenshot from 2021-01-30 17-23-54](https://user-images.githubusercontent.com/1583873/106361871-10fc3700-6320-11eb-9f3b-991747708bdf.png)

**Comment by Creatoon** [comment]
@mariobehling Sir not reproducable

![Screenshot_2021-01-30 Aayush Dubey Brom Bones Events Open Event](https://user-images.githubusercontent.com/65965202/106364477-43745700-6355-11eb-830c-f988fbfc154c.png)
