### ISSUE TITLE
Organizer Speaker Overview Page: Add filter "Without Session"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6549]
In the system it is possible to submit a speaker profile, but not submit a session. These speakers without session are difficult to isolate as there is no filter. 

1. Please add a **filter "Without Session"** in the menu of organizer speaker overview pages therefore.

![Screenshot from 2021-01-30 20-16-06](https://user-images.githubusercontent.com/1583873/106365867-9b509500-6338-11eb-8f8a-4769ba357f83.png)

2. Also add this filter to the **dashboard** session box and calculate all speakers on the dashboard including the speakers without session.

![Screenshot from 2021-01-30 20-16-24](https://user-images.githubusercontent.com/1583873/106365840-765c2200-6338-11eb-8fae-932dd00c57ad.png)

**Comment by Creatoon** [comment]
Working.

**Comment by Atri22** [comment]
can I work with this

**Comment by maze-runnar** [comment]
looking into it
