### ISSUE TITLE
Public Event Page: Speaker images not using content area fully

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6554]
The speaker images in the content area of the public event page and the speaker page are not fully using the content area. The result is that there is a blank area to the right of the speaker area in the content area.

Please increase the size of the speaker images proportionally so they the speaker images fill the space of the middle area on both the public event page (for featured speakers) and the speaker page.

![Screenshot from 2021-01-31 00-35-10](https://user-images.githubusercontent.com/1583873/106370727-2e032b00-635d-11eb-865a-0b0c99024ea0.png)

**Comment by nlok5923** [comment]
On it.

**Comment by Naman-1234** [comment]
Working on it.

**Comment by akash2408** [comment]
can i work on it ?

**Comment by Naman-1234** [comment]
@akash2408  , I am already working on it, So pls find another find another issue.

**Comment by akash2408** [comment]
> @akash2408 , I am already working on it, So pls find another find another issue.
@Naman-1234 Please take one issue and solve it.
Don't claim each and every issue.

**Comment by Naman-1234** [comment]
@akash2408  , I have left off and commented the same on the previous issue, as the issue was not reproducing in my laptop, and currently working on this one only,

**Comment by akash2408** [comment]
Ohk thanks
