### ISSUE TITLE
Create Event Page: Placeholder for Event Header Image and Event Logo not vertically centred.

### ISSUE THREAD

**Issue by kross9924** [fossasia/open-event-frontend#6561]
Placeholders for both event header image and event logo are not vertically centred. 
@mariobehling @iamareebjamal Is it intentional or an Issue? 

![Screenshot from 2021-01-31 18-42-36](https://user-images.githubusercontent.com/47144465/106385200-fe9ffd00-63f4-11eb-9819-b7059169a84c.png)

**Comment by Kunal-2001** [comment]
@kross9924 There is a icon above both the placeholders. Not sure why it's not showing for you

**Comment by iamareebjamal** [comment]
Yup

![image](https://user-images.githubusercontent.com/3874064/106577002-d682dc00-6563-11eb-8fbf-2a4f86cd77af.png)
