### ISSUE TITLE
Button Alignment Issue

### ISSUE THREAD

**Issue by ritik307** [fossasia/open-event-frontend#6587]
**Description**

There is no space between the `Ticketing System` Field and the buttons below it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://localhost:4200'
2. Click on `CREATE EVENT`
3. Scroll down to `Ticketing System`

**Expected behaviour**

There should a proper margin between the `Ticketing System` area and its corresponding buttons.

**Screenshots**

![open-event-issue](https://user-images.githubusercontent.com/22374829/106633850-32ba2000-65a5-11eb-8722-665ab7134a00.PNG)

**Comment by leoshrey** [comment]
yes, I also think there should be some margin between these two, @mariobehling what do you think?

**Comment by faraz16iqbal** [comment]
Can I work on this issue?

**Comment by afzal442** [comment]
Working

**Comment by tanay123456789** [comment]
working on this issue.

**Comment by ritik307** [comment]
@afzal442 good to hear that

**Comment by leoshrey** [comment]
Can I work on it if no one is doing ?

**Comment by kenkirito** [comment]
can i work on this

**Comment by ritik307** [comment]
@afzal442 is already working on this issue

**Comment by Akashrajpoots14** [comment]
I want to work on this issue
