### ISSUE TITLE
Public Speaker's Page: Change speakers list from 3 column to 4 column layout

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6594]
The public speakers page has a 3 column layout. Speakers are also prominent enough if we have a 4 column layout similar to the reorder page of speakers. Please change the layout on the public speakers page to 4 column, e.g. here https://eventyay.com/e/fa96ae2c/speakers (but leave it at 3 columns on the event start page for now). Adjust the size of images and area as needed.

![Screenshot from 2021-02-03 11-13-14](https://user-images.githubusercontent.com/1583873/106732609-308dab00-6611-11eb-946e-2b7a54ab3c66.png)

**Comment by afzal442** [comment]
Looking into it

**Comment by afzal442** [comment]
I wonder if you need like this as a screenshot below
![c1](https://user-images.githubusercontent.com/11625672/106745460-238bae80-6647-11eb-8528-2b6dc5a5cfeb.JPG)

@mariobehling sir plz tell. Thanks

**Comment by iamareebjamal** [comment]
Please show right side panel as well in the screenshot

**Comment by afzal442** [comment]
Thanks Sir, have a look
![c2](https://user-images.githubusercontent.com/11625672/106749613-c1ce4300-664c-11eb-842b-dd97ff0e8216.JPG)

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by mariobehling** [comment]
We will work on design in the next version more in detail. Therefore closing it.
