### ISSUE TITLE
Back to top button for quick navigate to top

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/open-event-frontend#6595]
**Is your feature request related to a problem? Please describe.**
we can add Back to top button for quick navigate to top and this button help to quick navigate to top especially in desktop. You can add here the Back to top button see in the screenshot for the better understanding.

**Additional context**
![12](https://user-images.githubusercontent.com/65535360/106737452-b246fe00-663c-11eb-866b-a6d895e6111b.PNG)

**Comment by kenkirito** [comment]
can i work on this

**Comment by rijusougata13** [comment]
can you assign me ?

**Comment by kenkirito** [comment]
Working on issue

**Comment by preeti13456** [comment]
Working on it. Can you please tell me where to do the required changes?

**Comment by SuryanshShahi** [comment]
Hi , I would like to work on this issue, but i'm unable to find that "index.html" file can you please help me out reaching to it.

**Comment by mehakkkk** [comment]
Hello, I have been through the code and I am willing to work on the issue

**Comment by mariobehling** [comment]
Expected would be and arrow up button that scrolls the page to the top. Please compare for example to https://2019.fossasia.org/

![Screenshot from 2021-02-28 18-44-30](https://user-images.githubusercontent.com/1583873/109428011-4bc3be80-79f5-11eb-8eb3-bdac045fd210.png)

**Comment by sambit-sankalp** [comment]
Working on this issue

**Comment by mariobehling** [comment]
We will implement this in the next version of the platform. Therefore I am closing it here for now.
