### ISSUE TITLE
Bug in hCaptcha regarding verification

### ISSUE THREAD

**Issue by Samridhi-98** [fossasia/open-event-frontend#6601]
### Describe the bug

While the human verification process in **hCaptcha** there is a bug regarding the selection of extra images of the not specified type. 

### To Reproduce
1. Go to https://eventyay.com/register
2. Click on the 'I am Human' checkbox, select all the required images with 1-2 extra images(different type). 
3. Click on the check button to verify as a Human.
4. It will generate a successful human verification message. 

### Expected behavior

**hCaptcha** should not produce successful verification as a human for extra or invalid input selections.

### Step 1: 
![step1](https://user-images.githubusercontent.com/54466041/106896552-bac03700-6717-11eb-9e99-e27d5a114338.PNG)

### Step 2:
![step2](https://user-images.githubusercontent.com/54466041/106896586-c7448f80-6717-11eb-90d0-9ad04c423174.PNG)

**Comment by iamareebjamal** [comment]
Please raise this issue with hcaptcha https://www.hcaptcha.com/reporting-bugs
