### ISSUE TITLE
Organizer Dashboard: Menu and spacing to screen edge issue

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6603]
A recent change resulted in an issue with the heading and spacing of areas. They are no longer spaced well to the edge of the screen. Please reinstate the previous design.

Now

![Screenshot from 2021-02-04 17-15-20](https://user-images.githubusercontent.com/1583873/106922077-f43f7500-670c-11eb-9b60-04b5c96caabe.png)

Before

![Screenshot from 2021-02-04 17-16-30](https://user-images.githubusercontent.com/1583873/106922076-f3a6de80-670c-11eb-8999-e34f57ac3134.png)

**Comment by afzal442** [comment]
looking into it

**Comment by afzal442** [comment]
@mariobehling sir, I observed this issue. It is due to adding new style after fixing left side bar movement.
