### ISSUE TITLE
Organizer: Not able to create a speaker and session at the same time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6617]
As an organizer I am not able to create a speaker and session at the same time. It results in Unexpected Error.

Compare https://eventyay.com/events/fa96ae2c/speakers/create

![Screenshot from 2021-02-05 15-30-54](https://user-images.githubusercontent.com/1583873/107046897-742a1580-67c7-11eb-8504-2839e6172f45.png)

**Comment by mariobehling** [comment]
The issue seems to be that the speaker cannot be created.

![Screenshot from 2021-02-05 15-33-59](https://user-images.githubusercontent.com/1583873/107047011-9f146980-67c7-11eb-8c38-d58ac528b364.png)

Still seems to be same issue as it was here https://github.com/fossasia/open-event-frontend/issues/6613

**Comment by iamareebjamal** [comment]
Reverted https://github.com/fossasia/open-event-server/pull/7711
