### ISSUE TITLE
Organizer Session/Speaker Page: Form elements missing for Create Speaker/Session

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6627]
When there is no session or speaker yet at all, there is no way for the organizer to create one as form elements do not show up.

Compare https://eventyay.com/events/bf972bef/sessions/create
![Screenshot from 2021-02-07 11-50-01](https://user-images.githubusercontent.com/1583873/107144338-d6575780-693a-11eb-8731-10dc28bd5da2.png)
![Screenshot from 2021-02-07 11-49-27](https://user-images.githubusercontent.com/1583873/107144340-d7888480-693a-11eb-9536-5d3679628ba9.png)

**Comment by mariobehling** [comment]
Ok, after I switch on "Call for Speakers" it works. But, when I reload the Wizard with the Call for Speakers, now the CfS is switched off even though I just switched it on. It does not seem to be a caching issue as it is persistent even with hard reload.

**Comment by maze-runnar** [comment]
on it

**Comment by maze-runnar** [comment]
-  https://github.com/fossasia/open-event-frontend/issues/5768#issuecomment-734097652

Sessions and speakers forms are not showing fields because the fields are not saved. When the below are of form is not loading and it is saved then the session and speaker forms are showing no field.

**Comment by iamareebjamal** [comment]
In that case, please show a message in the form section "Please enable session/speaker form to create a session/speaker"
