### ISSUE TITLE
Public Event Page: Spacing above date widget area too large

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6628]
The space above the date widget area on public event pages is too big.

This was just solved a few days ago and now the issue is back. It must be a recently merged PR.

Expected: 
1. The space between the "Join Event" and the date should be the same as with areas below.
2. The space should be consistent no matter if the date has two or three lines. 

![Screenshot from 2021-02-07 10-47-33](https://user-images.githubusercontent.com/1583873/107144694-2e8f5900-693d-11eb-8e98-098b3ab04c1e.png)

**Comment by afzal442** [comment]
Looking into this

**Comment by afzal442** [comment]
@mariobehling  sir, plz have a look
![c1](https://user-images.githubusercontent.com/11625672/107148851-7a60f300-697b-11eb-83f8-45e589207f00.JPG)

**Comment by iamareebjamal** [comment]
Send PR
