### ISSUE TITLE
Virtual Event Side Panel: Minimize Button overlaps text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6629]
The minimize side panel button overlaps the date and speakers button. Please ensure the right side of the date does not overlap.

![Screenshot from 2021-02-07 12-14-44](https://user-images.githubusercontent.com/1583873/107144866-58954b00-693e-11eb-84fd-2527723ae132.png)

**Comment by astromanish** [comment]
Can I work on it?

**Comment by astromanish** [comment]
@mariobehling Sir can you please provide ways to reproduce such a situation.

**Comment by afzal442** [comment]
@mariobehling sir plz have a look if you need like this as below

![c1](https://user-images.githubusercontent.com/11625672/107603503-f6488d00-6c52-11eb-8fe5-957a629124b2.jpg)
