### ISSUE TITLE
Public Schedule: Clicking "Join Event" on session expands session and forwards

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6630]
The "Join Video" button on a public schedule first expands the session and then directs the user to the video. This is a bit confusing. Expected: Do not expand the area when the user clicks on "Join Video". (But still expand if the user clicks elsewhere in the area).

![Screenshot from 2021-02-07 12-23-17](https://user-images.githubusercontent.com/1583873/107145095-af4f5480-693f-11eb-951c-c56aca9fee80.png)

**Comment by Naman-1234** [comment]
Working on this

**Comment by FlashV998** [comment]
@mariobehling can you tell me how to regenerate this ? i mean how to get to the public schedule

**Comment by mariobehling** [comment]
Closing this in favor https://github.com/fossasia/open-event-frontend/issues/6695
