### ISSUE TITLE
Very slow response, possible cross-origin problem

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-frontend#6632]
**Describe the bug**
Delays during event signup are intermittently very long (tens of seconds, minutes). I did capture a screenshot of a console log suggesting that there's a cross-origin problem, but it's not clear how this could have occured.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to eventyay.com
2. Click on FOSSASIA 2021 Summit
3. Beside Community Ticket set Quantity to 1
4. Click Order Now
5. Notice that blue bar moves very slowly and form does not appear.
6. Check console to see error message

Sometimes the registration form appears, but completing and clicking Order Now leads to the same problem.

**Expected behaviour**
Presentation of form to register, or results of registration.

**Screenshots**
![Screenshot from 2021-02-07 21-04-45](https://user-images.githubusercontent.com/646827/107148183-e861e600-698c-11eb-8b35-21c9671e0473.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 85.0 (64 bit)

**Comment by maze-runnar** [comment]
not able to reproduce any such issue on firefox.
