### ISSUE TITLE
Session Info Form: Add options for links to sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6634]
The session info form already has a number of fields. However there are no options to add social links and a website. 

1. Similarly to speakers  please add options for the following links:

- Website
- GitHub
- Gitlab
- Facebook
- Twitter
- Instagram
- Linkedin

2. On the form add the form fields above the "comment" form field.
3. On the session area in the schedule show these links as an icon.

![Screenshot from 2021-02-07 17-11-44](https://user-images.githubusercontent.com/1583873/107152343-b2f6d180-6967-11eb-86c9-fe9db6c42ee0.png)

**Comment by Creatoon** [comment]
working

**Comment by Creatoon** [comment]
@iamareebjamal sir speaker details form also not have gitlab option, should i also add this in speaker form.

**Comment by Creatoon** [comment]
Working

**Comment by MeghalBisht** [comment]
on it.
