### ISSUE TITLE
Public Schedule: All button only shows first day of event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6636]
On a public schedule if the user presses "All" the schedule will only show the first day of the event.

Compare https://eventyay.com/e/fa96ae2c/schedule

![Screenshot from 2021-02-08 05-39-11](https://user-images.githubusercontent.com/1583873/107176598-203e4d00-69d0-11eb-920a-cb83e56d6fcc.png)

**Comment by maze-runnar** [comment]
on this

**Comment by maze-runnar** [comment]
on clicking all the page is showing all sessions of event, just the buttons dissappeared.

**Comment by iamareebjamal** [comment]
Yes
