### ISSUE TITLE
Extra social link button

### ISSUE THREAD

**Issue by Artistic18** [fossasia/open-event-frontend#6643]
**Describe the bug**
Extra social media link button with no information and does not link to any social media platform. It appears only if we go back to home page and again go to the event page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to eventyay.com
2. Click on FOSSASIA 2021 Summit
3. Go back to the previous page by clicking the back button on browser.
4. Go to FOSSASIA 2021 Summit again.
5. Check the social media button list.

**Expected behaviour**
The extra button should not appear.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/16490253/107266044-fdad4200-6a6a-11eb-901b-99b6d95f6f69.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0 (64 bit)

**Comment by mariobehling** [comment]
This can happen when the organizer deletes an entry and the cache still has the box stored for a few minutes. It should not persist permanently. It if it is still there please try Ctr + Shift + R. If it did not go away please reopen that issue here.
