### ISSUE TITLE
inconsistency in view for mobile

### ISSUE THREAD

**Issue by AJOO7** [fossasia/open-event-frontend#6644]
when u tryto create a event  on a mobile screen then the buttons as shown in scrnshoot which were of minimal size extend  horizontally.[
![issue2](https://user-images.githubusercontent.com/67185443/107266931-3699e680-6a6c-11eb-91be-9d0e799cfc51.PNG)
![issue1](https://user-images.githubusercontent.com/67185443/107266953-3d285e00-6a6c-11eb-9cbc-7f7ee6b10381.PNG)

](url)

**Comment by Naman-1234** [comment]
@AJOO7 , Can you please provide the solution you want , I mean do you want them in a row, only smaller or something else?

**Comment by AJOO7** [comment]
@Naman-1234 it should remain the same size as the size is very optimal on bigger screens

**Comment by Naman-1234** [comment]
Ok, Working on this one.

**Comment by mariobehling** [comment]
Design can be improved but this is ok for the moment and out of scope as we focus on other areas. Thanks.
