### ISSUE TITLE
Improve Organizer Exhibitor Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6649]
Please also implement the following in the organizer exhibitor page:
1. Extra Links (e.g. exhibitors said they would like to add a blog or newsletter)
2. Change the "State" to work similarly to the session state: In the overview add move the column to the very left front. Do not show the "State" in the edit form of the exhibition
![Screenshot from 2021-02-09 01-52-54](https://user-images.githubusercontent.com/1583873/107300432-cdb96b00-6a79-11eb-83eb-10f01b122e1c.png)
3. Add an "Contact Exhibitor" into the exhibitor form where the exhibitor can either add a link to a contact form or an email.
4. Add an option "Join Exhibitor Video" in the exhibitor form where the organizer can choose to add a video to the exhibitor page or not.
5. Add buttons for 3) and 4) below the social links and above the slides:
 * Button 1 "Contact Exhibitor" (in red) 
 * Button 2 "Join Exhibitor Video" (in green)
 * Only make both buttons work if users are logged in and have a ticket. Otherwise show a pop up "You need to be logged in and get a ticket in order to access these links."
![Screenshot from 2021-02-09 02-25-47](https://user-images.githubusercontent.com/1583873/107303057-a0bb8700-6a7e-11eb-8ffa-894d550909a7.png)

**Comment by MeghalBisht** [comment]
Point 1 left
