### ISSUE TITLE
Organizer Message: Linkify URL on Order Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6659]
The organizer message on the order page does not show links as clickable links. Please make them clickable.

Compare https://eventyay.com/orders/15e6aa99-d1a4-4cd9-9115-1ccbdb618c7c/view

![Screenshot from 2021-02-10 16-43-04](https://user-images.githubusercontent.com/1583873/107533539-5392fe80-6bbf-11eb-8e7b-0a799cceb2bc.png)

**Comment by Deek9399** [comment]
Is this a good first issue/beginner friendly? I would like to work on it.

**Comment by roshnaeem** [comment]
@mariobehling can you please share the link of order page?

**Comment by roshnaeem** [comment]
@mariobehling,  i can't login or register to the page. Is there some issue going on?
