### ISSUE TITLE
[Parent Issue]Implement filter in explore route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#666]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Implement event filtration using the side bar in explore route

**Comment by harshitagupta30** [comment]
can I work on this?

**Comment by geekyd** [comment]
Sure go ahead :)

**Comment by niranjan94** [comment]
@harshitagupta30 whats the progress on this ? I see no discussion or any PR .. Please ensure you open a PR today.

**Comment by niranjan94** [comment]
@harshitagupta30 please work on this first instead of all the other smaller issues you have been working on.

**Comment by harshitagupta30** [comment]
@niranjan94 I'll send the pr for this today.

**Comment by CosmicCoder96** [comment]
making this a parent issue, since date range filters may require some extra time to develop.

**Comment by harsh-98** [comment]
@CosmicCoder96 this issue has been solved. Can I close it?

**Comment by ritikamotwani** [comment]
@CosmicCoder96 the date rangle and the location filters have been implemented by PRs: https://github.com/fossasia/open-event-frontend/pull/1420 and https://github.com/fossasia/open-event-frontend/pull/1396.
Can this issue be closed now?

**Comment by sk9331657** [comment]
@CosmicCoder96 @ritikamotwani  Is this issue still open??

**Comment by ritikamotwani** [comment]
@sk9331657 this issue has been solved.
