### ISSUE TITLE
Organizer Sessions Page: Speaker Email "Notify" Message

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6661]
Please resolve the following for the notficiation email of speakers 
- If there are more organizers, it does not show all reply-to addresses. Expected: The user should be able to use the mouse to move the text to the right in the same line.
- If an organizer gets deleted from an event, the organizer still shows up as a reply-to address even though the organizer was already deleted.

![Screenshot from 2021-02-10 16-56-20](https://user-images.githubusercontent.com/1583873/107535780-5b53a280-6bc1-11eb-8176-832f2813ab6c.png)

**Comment by igarg2001** [comment]
Please assign me this issue
