### ISSUE TITLE
unable to check-In/Out attendee

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#6679]
**Describe the bug**

when i was solving issue of check-in management milestone of support.eventyay project
and try to check-in the attendee but, when i
click on check in :- An unexpected error has occurred. 
this is what happens and when i refresh this it's shows error.
![photo_2021-02-12_12-37-55](https://user-images.githubusercontent.com/71969867/107739728-8cea7c00-6d2f-11eb-9bea-e4a966f9ddf7.jpg)

 @iamareebjamal

**Comment by iamdevvalecha** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/71969867/108075640-99a10400-7090-11eb-9210-034bd30c887b.png)

Error while attendee checking IN/OUT Error: Attempted to handle event `becameError` on <attendee:22964> while in state root.loaded.updated.uncommitted.
@iamareebjamal

**Comment by Adityachaturvedi2906** [comment]
Hey! this issue seems interesting, Can I work on this? please guide me further on the same

**Comment by MeghalBisht** [comment]
@Adityachaturvedi2906  Send a PR if you know the solution. There is no need to ask and comment on every issue.
