### ISSUE TITLE
Exhibition: Implement reorder feature

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6681]
The exhibition sorting is currently in random order. Please implement a sorting mechanism similar to the reorder speakers functionality.

![Screenshot from 2021-02-12 16-45-51](https://user-images.githubusercontent.com/1583873/107790624-43ac2380-6d53-11eb-88e3-edb39fa0552c.png)

**Comment by maze-runnar** [comment]
looking into this.

**Comment by subodhk01** [comment]
@mariobehling Can I work on this issue?

**Comment by maze-runnar** [comment]
@subodhk01 pick another please.
