### ISSUE TITLE
Organizer Speaker Info: Only allow one email address of "event owner" in the Reply-to email

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6686]
The reply-to field in the speaker notification emails has one field. Currently all organizers are filled in. However Sendgrid only support one emails. Therefore please only keep the event owner in this email reply-to field.

![Screenshot from 2021-02-13 06-38-13](https://user-images.githubusercontent.com/1583873/107842880-d89c3480-6dc6-11eb-824e-9394b9b7f94d.png)

**Comment by PrithvirajMajumder** [comment]
can i work on this ?

**Comment by mariobehling** [comment]
As a matter of fact, there is an issue that only one person can be in the reply-to area due to limits of Sendgrid. Therefore please change to one email allowed in the reply-to address only.

**Comment by mariobehling** [comment]
As this issue description was specified and the issue now blocks all speaker emails from getting sent out it has become an urgent priority issue.

**Comment by mariobehling** [comment]
Email in reply-to still shows all organizers in frontend even though only "event owner"receives it now.
