### ISSUE TITLE
My Schedule: Enable user to get personal schedule added to calendar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6694]
Instead of the overall calendar users should have the option to only save their personal "my schedule" to their calendar. We already have the my schedule feature upcoming. Please add the option to "add it to the calendar".

**Comment by sakshi-1604** [comment]
I am on it

**Comment by ranjitkshah** [comment]
on it

**Comment by iamareebjamal** [comment]
@Tlazypanda need to implement server part for this
