### ISSUE TITLE
UI for schedule in events/{event_id}/schedule route

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#670]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
![image](https://user-images.githubusercontent.com/12701036/29229080-1bfd994a-7efa-11e7-8395-5b1e7695ddc8.png)

I will work on this

**Comment by ParthS007** [comment]
@geekyd @CosmicCoder96 Is the issue still active ? I want to work on this issue

**Comment by geekyd** [comment]
@ParthS007 Yes please go ahead with this

**Comment by sk9331657** [comment]
@geekyd  @srv-twry  I want to work on it. Can you suggest what should be present in UI??

**Comment by CosmicCoder96** [comment]
@sk9331657 The schedule is complete now, this issue is no longer valid.
