### ISSUE TITLE
CfS: Private submission feature no longer working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6707]
The private submission feature in call for speakers is no longer working. The buttons do not show up to submit a proposal and speaker profile.

![Screenshot from 2021-02-15 11-40-12](https://user-images.githubusercontent.com/1583873/107936278-bea75100-6f82-11eb-94da-8cb43a839371.png)

![Screenshot from 2021-02-15 11-43-18](https://user-images.githubusercontent.com/1583873/107936492-04fcb000-6f83-11eb-8a5a-409940b87109.png)

**Comment by subodhk01** [comment]
Looking into it

**Comment by subodhk01** [comment]
@mariobehling Can you elaborate more on the issue, coz everything related to CfS seems to be working fine with me.

<img width="677" alt="Screenshot 2021-02-15 at 10 13 34 PM" src="https://user-images.githubusercontent.com/19875783/107973270-0e196b80-6fdb-11eb-9044-82600bab386f.png">

**Comment by maze-runnar** [comment]
it's working as expected, as far I have chacked.
