### ISSUE TITLE
Integrate order statistics API on tickets route

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#671]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

https://user-images.githubusercontent.com/13910561/29230756-f5dabe20-7f01-11e7-8c5f-58ee69c38e65.png

Will work on this.

**Comment by harshitagupta30** [comment]
On wait till the https://github.com/fossasia/open-event-orga-server/pull/4297 is merged. Will send PR asap after it gets merged.

**Comment by geekyd** [comment]
@harshitagupta30 Please check https://github.com/fossasia/open-event-orga-server/pull/4297
