### ISSUE TITLE
Scheduler: Decrease the height of the left side bar for unscheduled sessions and rename to "Not Yet Scheduled"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6711]
The left side bar of the scheduler page is extending beyond the bottom of the calendar area of the scheduler. Please change the following to improve the area:
* Match the height of the left side bar with the bottom of the calendar area of the scheduler
* Rename "Unscheduled Sessions" to "Not Yet Scheduled Sessions"

Compare https://eventyay.com/events/fa96ae2c/scheduler

![Screenshot from 2021-02-15 13-30-58](https://user-images.githubusercontent.com/1583873/107947308-81e35600-6f92-11eb-8d3a-83fb193582e5.png)

**Comment by nlok5923** [comment]
On it

**Comment by Naman-1234** [comment]
Working on it.

**Comment by subodhk01** [comment]
@mariobehling Can I work on this issue?

**Comment by Naman-1234** [comment]
@subodhk01 , I am already working on this, So pls find another issue.

**Comment by Naman-1234** [comment]
@mariobehling , Sir sorry to disturb you but may you please help me in reproducing issue, I have been trying to reproduce it but didn't get anything. I opened your mentioned url (https://eventyay.com/events/fa96ae2c/scheduler) but it gives the following error on both local as well as real website. Please guide me if and where I am going wrong or is this issue related to server. Screenshots are given below:

Screenshot of website:
![Screenshot (977)](https://user-images.githubusercontent.com/63748249/107982489-293fa780-6fea-11eb-9541-9777cb083b80.png)


Screenshot on localhost:
![Screenshot (978)](https://user-images.githubusercontent.com/63748249/107982536-3bb9e100-6fea-11eb-8a9d-abb722bfa54d.png)

**Comment by iamareebjamal** [comment]
You don't have access to other's events. Create your own

**Comment by Naman-1234** [comment]
Ok sir.

**Comment by mariobehling** [comment]
The first PR now did not solve the issue entirely as there is a scroll bar even if there are no sessions in the list.

![Screenshot from 2021-03-04 19-15-24](https://user-images.githubusercontent.com/1583873/110009928-fc93cb80-7d1d-11eb-8828-0d73a4192ef3.png)

**Comment by Naman-1234** [comment]
Working on that.

**Comment by Naman-1234** [comment]
@mariobehling, @maze-runnar   Sir, sorry to disturb you, But could you please tell me how can I add unscheduled sessions in my event. In this way, I will be able to perform the tests before submitting a PR.

**Comment by Naman-1234** [comment]
@iamareebjamal  and @mariobehling, Sir I am leaving this issue Reason being If I solve this issue As I did before then that navbar will come and you have , I also tried some other approaches like giving height to the unscheduled-session box both in px and '%', but that solutions are distorting other portions in mobile view.

**Comment by iamareebjamal** [comment]
I recommend taking up another issue. There are 100s of them. This is neither high priority, nor we have the bandwidth or time to have a detailed discussion on this. Please move on

**Comment by mariobehling** [comment]
I am closing this as we can take it up in the next version of the platform.
