### ISSUE TITLE
Schedule: Add list and calendar button to schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6713]
The system has two ways to display the schedule a) as a list and b) as a calendar.

Therefore please add a calendar button and a list button for the two different views directly next to the "Schedule" heading.

Compare
* Schedule https://eventyay.com/e/8fa7fd14/schedule
* Calendar https://eventyay.com/e/8fa7fd14/calendar

**Comment by MeghalBisht** [comment]
on it.

**Comment by MageshSundarG** [comment]
Assign to me
