### ISSUE TITLE
CfS: "Edit Speaker Details" button not available after CfS is closed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6715]
After the CfS is closed on the CfS site the "Edit Speaker Details" button is no longer available. Expected: For speaker that are already in the system the button should still be available.

Compare https://eventyay.com/e/fa96ae2c/cfs
![Screenshot from 2021-02-15 15-47-17](https://user-images.githubusercontent.com/1583873/107960796-5b7ae600-6fa5-11eb-88d8-9eb019698fc3.png)

**Comment by rajatgupta24** [comment]
Hi sir, 
I would like to work on this but I'm new here so can you please guide me how to get started on this.

**Comment by rudrani1964** [comment]
Hi @mariobehling  can work on this issue?
