### ISSUE TITLE
Admin: Add Groups Tab in Menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6717]
We now have the groups feature but an admin does not have any way to control the feature. Please add a page with a table for admins and add a menu item behind "Users". The tables should have the following columns:

- Groups with buttons View, Edit, Delete
- Owner
- Number of events
- Created
- Public URL

Add two sub tabs:
- Live
- Deleted

![Screenshot from 2021-02-15 17-40-07](https://user-images.githubusercontent.com/1583873/107973117-19f23700-6fb5-11eb-8ffa-d79972750b8c.png)

**Comment by sakshi-1604** [comment]
I am on it

**Comment by rudrani1964** [comment]
Hey @mariobehling I would like to work on this, can you assign this to me?

**Comment by rudrani1964** [comment]
Even I'm quite new here, please guide me to get  started with this.

**Comment by iamareebjamal** [comment]
Stop spamming. We don't have the bandwidth to guide contributors. Please only comment if you know how to fix the issue

**Comment by g4rry420** [comment]
Can I work on this issue ?
