### ISSUE TITLE
Public Schedule: Using any filter resets the timezone choice of the user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6722]
If the user sets a certain timezone the choice will be reverted to the event timezone when a filter is added, e.g. a track or day.

Compare https://eventyay.com/e/8fa7fd14/schedule

![Screenshot from 2021-02-15 23-08-54](https://user-images.githubusercontent.com/1583873/107997404-f80fa900-6fe2-11eb-80ce-2c006d89bcb0.png)

**Comment by sakshi-1604** [comment]
I am on it

**Comment by preeti13456** [comment]
I have found one solution but don't know where to do the changes. Can you please provide some guidance regarding same?

**Comment by sachinchauhan2889** [comment]
looking into this
