### ISSUE TITLE
Public Event Page: Standardize headings, add spacing and add button to view more speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6737]
The headings on the public event page and a few other things should be standardized and the style improved. Therefore please change the following:

1. Change the headings on the public event pages as follows
- Tickets -> H2
- Featured Speaker -> H2
- Sponsors, e.g. Silver Sponsor -> H3
- Getting Here -> H2
- Address -> H2

2. Add spacing above H2 headings, maybe around 40px.
3. Add a blue button below the featured speaker area "More Speakers" and link it to the speakers page. Show this button only if more than the featured speakers are on the speakers page.

**Comment by sakshi-1604** [comment]
Working on it

**Comment by Sayantani-sunshine** [comment]
Is the issue open?

**Comment by ankitashaw514** [comment]
can i work on this?
