### ISSUE TITLE
Display wrong timezone

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6747]
Organizer chose **GMT+9** as the timezone for this event https://eventyay.com/events/75ac7f83

Public page shows **(-09)** https://eventyay.com/e/75ac7f83

The CFS also shows timezone as **(-09)**
![Screenshot from 2021-02-17 21-33-05](https://user-images.githubusercontent.com/1658742/108268506-e528e000-716c-11eb-94c9-27de02746b74.png)

**Comment by OmkarPh** [comment]
May I try to look into this

**Comment by iamareebjamal** [comment]
Caused by https://github.com/moment/moment-timezone/issues/167

**Comment by iamareebjamal** [comment]
This answer shows that it is expected outcome because of how the standard is defined. Thus, if someone wants +9 as offset, they should use a proper timezone of that country or Etc/GMT-9

https://stackoverflow.com/questions/23640227/how-does-gmt-ids-work-in-java-timezone/23643847#23643847
