### ISSUE TITLE
Organizer Exhibitors Overview Table: Increase "Description" column width and clear html tags

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6749]
Please change the organizer exhibitors overview table as follows: 
1. Decrease the width of the columns "State" and "Logo" and increase column "Description".
2. Do not show HTML code in overview table in description column.

![Screenshot from 2021-02-18 00-18-51](https://user-images.githubusercontent.com/1583873/108280782-f8dd4200-717e-11eb-96a5-d56bce69c70d.png)

**Comment by Sayantani-sunshine** [comment]
Hello...Is this issue open?
