### ISSUE TITLE
Public Schedule: Add dropdown filter for session type

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6752]
The public schedule view would benefit if users could choose session types, e.g. some users might be looking for workshops in a schedule. Therefore below the "Rooms" filter please provide a dropdown list with a tickbox for session types. So, the idea is that a user could tick the different workshop session types that are available at an event.

![Screenshot from 2021-02-18 10-58-17](https://user-images.githubusercontent.com/1583873/108340265-acbeeb80-71d8-11eb-8554-4c813d3487ed.png)

**Comment by Sayantani-sunshine** [comment]
Hello.Can you kindly tell me what exactly do I have to do?
I am a first timer.And I am interested to contribute in open source.

**Comment by MeghalBisht** [comment]
Multiple session types can be ticked at once?

**Comment by iamareebjamal** [comment]
No

**Comment by MeghalBisht** [comment]
OK so can the dropdown & checkbox be omitted as LinkTo component can be directly used to query just like room & track?

**Comment by iamareebjamal** [comment]
By checkbox, it means that active session type filter should have a check sign on it in the dropdown
