### ISSUE TITLE
Public Speakers Page: Add search box to search for a speaker name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6753]
Please add a search box "search speakers" on top of the public speakers list of events and search speaker names.

![Screenshot from 2021-02-18 11-06-23](https://user-images.githubusercontent.com/1583873/108341121-a2e9b800-71d9-11eb-8c4f-f4d12e527bc2.png)

**Comment by 17sushmita** [comment]
looking into this

**Comment by srishty-07** [comment]
Hi. I'd Like to work on this issue.

**Comment by tamanna-verma** [comment]
Hi , I would like to work on it
