### ISSUE TITLE
Mobile schedule page: schedule cut off

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6761]
The schedule info is partly cut off on mobile pages. Please center the mobile schedule info and ensure it is visible.

![Screenshot_20210218_221326_com android chrome](https://user-images.githubusercontent.com/1583873/108422501-ecb4bb80-7236-11eb-97c9-2071cc855390.jpg)

**Comment by Aanandgupta** [comment]
Working on it

**Comment by iamvedant** [comment]
Can you please tell exactly where is this happening. I am unable to find this page.

**Comment by mariobehling** [comment]
Please test it on this page on a mobile https://eventyay.com/e/fa96ae2c/schedule

**Comment by Anmollenka** [comment]
Working on this.
