### ISSUE TITLE
Public Event Page: Right hand side

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6764]
On the right hand side of public event pages all widgets below the join event button are slightly indented. Make all widgets areas the same width as the blue join event button.

![Screenshot_20210218_222254_com android chrome](https://user-images.githubusercontent.com/1583873/108423888-bc6e1c80-7238-11eb-8a03-5173e972faa9.jpg)

**Comment by Naman-1234** [comment]
Working on it.

**Comment by sakshi-1604** [comment]
Are this changes okay?
![2021-02-20 (9)](https://user-images.githubusercontent.com/65847879/108586952-4d4b1200-7377-11eb-8cb7-c1ed2bba5c32.png)
![2021-02-20 (11)](https://user-images.githubusercontent.com/65847879/108587148-03166080-7378-11eb-8e01-3c5fba784b1c.png)

**Comment by sakshi-1604** [comment]
Are this changes okay?
![2021-02-20 (9)](https://user-images.githubusercontent.com/65847879/108589574-f3e9df80-7384-11eb-94b6-8d9981a1843c.png)
![2021-02-20 (11)](https://user-images.githubusercontent.com/65847879/108589594-0ebc5400-7385-11eb-8923-72a352b89a6d.png)

**Comment by Naman-1234** [comment]
@sakshi-1604  I have already linked PR associated with this issue, So you can find another issue.

**Comment by sakshi-1604** [comment]
@Naman-1234 ok
