### ISSUE TITLE
Session Calendar for Virtual Events: Add link to online room in location field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6766]
In the session calendar for online events add the link to the online video room into the location field, e.g. "Workshop Room https://eventyay.com/e/fa96ae2c/video/fossasia-summit-2021/186"

![Screenshot from 2021-02-18 23-57-51](https://user-images.githubusercontent.com/1583873/108432979-897e5580-7245-11eb-8013-a47fa658bd29.png)

**Comment by iamareebjamal** [comment]
Then it'll be visible to even those who do not have event tickets

**Comment by mariobehling** [comment]
No, then people who are not logged in will see this message.

![Screenshot from 2021-02-19 04-52-39](https://user-images.githubusercontent.com/1583873/108455340-58fee180-726e-11eb-8dda-54713d9270c6.png)

We already implemented that.

**Comment by sachinchauhan2889** [comment]
looking into this
