### ISSUE TITLE
Exhibitors Pages Images very large

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6767]
The exhibitors page images on the overview page and the exhibitor page itself are very large. Expected is that they are scaled down according to the size required. For example the Mace image on the FOSSASIA page is 7 MB!

Please scale the images automatically after upload by the user to a sufficient size for the specific area.

Compare https://eventyay.com/e/fa96ae2c/exhibition

![Screenshot from 2021-02-19 00-08-57](https://user-images.githubusercontent.com/1583873/108433860-fb0ad380-7246-11eb-8c2e-917bbac8926f.png)

**Comment by sakshi-1604** [comment]
working on it .

**Comment by maze-runnar** [comment]
on it
