### ISSUE TITLE
Exhibitor Page in the Organizer view: Search feature broke the service

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6768]
When an organizer used the search box in the exhibitor page, it broke the service, see error message below

Go here https://eventyay.com/events/fa96ae2c/exhibitors/list

### Enter something in the search box
![Screenshot from 2021-02-19 12-42-21](https://user-images.githubusercontent.com/1658742/108521410-fc321400-72cb-11eb-849d-cf15fb09c4f5.png)

### Error message

![Screenshot from 2021-02-19 12-41-28](https://user-images.githubusercontent.com/1658742/108500565-41484d00-72b0-11eb-9e80-6ba05e51ebb2.png)

**Comment by Naman-1234** [comment]
@hpdang  Have u created this event first, Because I have been through this error as you don't have access to other events. You have to create event first.

**Comment by hpdang** [comment]
@Naman-1234 this is an organizer bug, only organizer can access the exhibitor page. I updated the issue, hope it is a bit easier to understand now.
