### ISSUE TITLE
Public Schedule: Not yet scheduled speakers show up with "invalid date"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6774]
Not yet scheduled speakers should show up with the date "Not yet scheduled" instead of "invalid date".

Compare https://eventyay.com/e/fa96ae2c/schedule?search=daimler

![Screenshot from 2021-02-20 11-10-04](https://user-images.githubusercontent.com/1583873/108592080-613d4680-736c-11eb-81fb-080cd49edf24.png)

**Comment by sakshi-1604** [comment]
working on it
