### ISSUE TITLE
User cannot join video event in Firefox Icognito and Chromium Standard more

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6780]
Message in browser as follows:
1. Chromium: video.eventyay.com refused to connect. 88.0.4324.150 (Official Build) for Linux Mint (64-bit)
2. Firefox as below. Link to "More info" in Firefox https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct
FX version 85.0.1 (64-bit)

![eventyay_fossasia](https://user-images.githubusercontent.com/1583873/108602512-919fd780-73a2-11eb-98bb-a3a4ac60f2c6.png)
![eventyay2](https://user-images.githubusercontent.com/1583873/108602515-92386e00-73a2-11eb-9a2b-ffb05181984d.png)
![eventyay (1)](https://user-images.githubusercontent.com/1583873/108602516-92d10480-73a2-11eb-8034-5ece363aaa5a.png)

**Linux Mint 20.1 Cinnamon**
- 4.8.6
- 5.9.16-050916-generic
- AMD Ryzen 5 4500U with Radeon Graphics × 6

**Comment by iamareebjamal** [comment]
Cannot reproduce on Chromium or Firefox
