### ISSUE TITLE
Access Forbidden Message

### ISSUE THREAD

**Issue by scvthorsten** [fossasia/open-event-frontend#6783]
it seems eventyay has a short session timeout.  when performing an update e.g. speaker / session after 5 minutes of waiting time results in an error "Oops something went wrong. Please try again" in the browser.

XHR6614	Other6614	 2 requests      800 B transferred     190 B resources
{,…}
errors: [{status: 403, source: {pointer: "/relationships/microlocation"}, title: "Access Forbidden",…}]
jsonapi: {version: "1.0"}

attached .har showing the network log.

[eventyay.com - admin-access-required error.zip](https://github.com/fossasia/open-event-frontend/files/6017695/eventyay.com.-.admin-access-required.error.zip)

**Comment by maze-runnar** [comment]
> it seems eventyay has a short session timeout. when performing an update e.g. speaker / session after 5 minutes of waiting time results in an error "Oops something went wrong. Please try again" in the browser.
> 
> XHR6614 Other6614 2 requests 800 B transferred 190 B resources
> {,…}
> errors: [{status: 403, source: {pointer: "/relationships/microlocation"}, title: "Access Forbidden",…}]
> jsonapi: {version: "1.0"}
> 
> attached .har showing the network log.
> 
> [eventyay.com - admin-access-required error.zip](https://github.com/fossasia/open-event-frontend/files/6017695/eventyay.com.-.admin-access-required.error.zip)

can you please provide specific link or any screenshot.

**Comment by mariobehling** [comment]
This is related to the server setup and we will add this to our list of issues regarding the server configuration. Thank you!
