### ISSUE TITLE
Frontend check fails

### ISSUE THREAD

**Issue by Aanandgupta** [fossasia/open-event-frontend#6786]
**Describe the bug**

while we are logging in or signing up if we don't pass all front end checks we get err msg and red-bordered boxes but let's say we passed all check after the button is enabled we put wrong credentials we don't see red-bordered boxes and err msgs
**To Reproduce**
1. Go to 'signup'
2. Click on 'put valid credentials'
3. After btn is enable put wrong credentials
4. No err 
5. It would be better user experience if we still see the err messages as before

**Expected behaviour**

It would be better user experience if we still see the err messages as before.

In the below image you will notice that different passwords are their still we are not getting any err msg and lsignup button is enabled
**Screenshots**

![Screenshot (151)_LI](https://user-images.githubusercontent.com/71023799/108634278-e6c11380-749e-11eb-911a-dd94c5782c7a.jpg)

**Comment by maze-runnar** [comment]
> In the below image you will notice that different passwords are their still we are not getting any err msg and lsignup button is enabled

 you will get error msg, once move out of input box.
![Screenshot from 2021-02-22 08-27-27](https://user-images.githubusercontent.com/56407566/108651528-f7e24280-74e7-11eb-9cf0-209afd17f9bc.png)

**Comment by Aanandgupta** [comment]
> > In the below image you will notice that different passwords are their still we are not getting any err msg and lsignup button is enabled
> 
> you will get error msg, once move out of input box.
> ![Screenshot from 2021-02-22 08-27-27](https://user-images.githubusercontent.com/56407566/108651528-f7e24280-74e7-11eb-9cf0-209afd17f9bc.png)

Hii @maze-runnar  yes I notice that its working this way

**Comment by maze-runnar** [comment]
> Hii @maze-runnar yes I notice that its working this way

this is not an issue then I guess.
