### ISSUE TITLE
 captcha check not available some time creating a blockage

### ISSUE THREAD

**Issue by Aanandgupta** [fossasia/open-event-frontend#6787]
**Describe the bug**

Some time while signing up captcha is not available so signup button is not active any how same goes for reset pasword
![Screenshot (152)](https://user-images.githubusercontent.com/71023799/108634707-da3dba80-74a0-11eb-9eac-e146cd2fb48c.png)

**Comment by mariobehling** [comment]
Does page refresh solve it for you?

**Comment by Aanandgupta** [comment]
> Does page refresh solve it for you?

Yes refreshing the page solves it but I think it would be better if we don't need to do that

**Comment by maze-runnar** [comment]
looking into it
