### ISSUE TITLE
Virtual Exhibition: Add a "< previous | next >" option into the right sidebar of individual exhibitor pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6792]
Virtual exhibition pages just appear very static. How can we improve the experience nevertheless a bit and provide the user an experience to click through the exhibition easily? One idea is to have a previous / next option. Therefore please implement:
* add previous / next buttons or text fields into the side bar of individual exhibitor pages below "Add to Calendar"
* follow the order of exhibitors from the exhibition front page
* when the last exhibitor is reached in the line simply start with the first exhibitor when the user clicks "next"
![Screenshot from 2021-02-22 18-12-20](https://user-images.githubusercontent.com/1583873/108744295-12450c00-753a-11eb-923f-71ae5b453425.png)

**Comment by Aiswarika** [comment]
Can  I work on this issue?

**Comment by mariobehling** [comment]
Yes, please go ahead and make a PR in the upcoming days if you want to claim this issue.
