### ISSUE TITLE
Public Schedule: Add full screen option to Calendar View

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6812]
The calendar view is often very condensed. Please add a full screen view to the calendar view of schedules. Add an icon on the top right next to the timezone dropdown.

![Screenshot from 2021-02-24 05-59-17](https://user-images.githubusercontent.com/1583873/108949994-b9729200-7665-11eb-89a1-1b91c3d5fdf6.png)

**Comment by rohank2502** [comment]
Hey !! Rohan, Here I am new to this community. I will like to work on this issue under your guidance !!

**Comment by iamdevvalecha** [comment]
started working on it

**Comment by rohank2502** [comment]
> started working on it

Ok thanks
