### ISSUE TITLE
Profile Image: If user has no profile image use Gravatar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6813]
Many users already have Gravatar. Please use a gravatar if the user has no profile image to display on attendee lists and other places.

**Comment by Yousufkhan1** [comment]
if u want i can?

**Comment by iamdevvalecha** [comment]
starting this issue.

**Comment by tanay123456789** [comment]
working on this issue

**Comment by tanay123456789** [comment]
work done.
