### ISSUE TITLE
Schedule: Add number badge and sort by popularity

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6814]
As attendees now have the possibility to add a session to their schedule please show a badge with the number of attendees to the right of the tick icon and enable sort by popularity on the dropdown menu.

![Screenshot from 2021-02-24 06-19-40](https://user-images.githubusercontent.com/1583873/108951627-9c8b8e00-7668-11eb-826c-15c0d4a585f9.png)

**Comment by prateekj117** [comment]
@iamareebjamal Taking this up.
