### ISSUE TITLE
Schedule: Selecting/Unselecting sessions for "My Schedule" no longer possible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6818]
Selecting sessions for My Schedule is not possible. Nothing happens when clicking it.

Compare https://eventyay.com/e/fa96ae2c/schedule

![Screenshot from 2021-02-24 14-37-07](https://user-images.githubusercontent.com/1583873/109008690-eba7e200-76ad-11eb-8adc-e5e1ff05a545.png)

**Comment by maze-runnar** [comment]
on it.

**Comment by hpdang** [comment]
Adding a screenshot also from my side that shows this error 

![Screenshot from 2021-02-24 14-28-29](https://user-images.githubusercontent.com/1658742/109118950-4f7cea00-7744-11eb-9e1a-ea64ba61c8a9.png)
