### ISSUE TITLE
Create Event Wizzard: Cannot enter date and time properly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#682]
When I enter a date and then try to enter a time there are all kinds of issues, e.g. when I enter it by typing it in. Then I move on and suddenly the date show "Invalid". Also time shows "Invalid date". Please check and test this thoroughly and fix it.

![screenshot from 2017-08-13 15-36-41](https://user-images.githubusercontent.com/1583873/29250135-6d1c0980-803d-11e7-90b1-c65a9ccdfe4e.png)

**Comment by anshulwadhawan** [comment]
I am willing to work on it.
But to access the create event url,i need to login and when i proceed to register,i get "an unexpected error occured".How should i proceed ?
@mariobehling Please help sir.
![issue](https://user-images.githubusercontent.com/25061477/31112467-89019108-a831-11e7-8b19-acb54cb603a2.png)

**Comment by niranjan94** [comment]
@anshulwadhawan please use the dev server
https://open-event-frontend.herokuapp.com
