### ISSUE TITLE
Public Schedule: Add clear all filters icon next to sort order and change minus icon to clear filter icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6821]
Our clear filter icon is confusing for people. Users overwhelmingly report they do not understand that the minus icon is a clear filter icon. Secondly we do not have one place to clear all filters everywhere. Therefore please change the public schedule page as follows:
1. Add a clear filter icon that is similar as below next to the sorting option. This clear filter option should clear all filters of the entire page no matter what filter it is.
![Screenshot from 2021-02-24 21-00-30](https://user-images.githubusercontent.com/1583873/109058503-5b848f80-76e3-11eb-82a4-700984e62a94.png)
2. Change the clear filter minus sign to a clear filter icon that is similar as below.

![Screenshot from 2021-02-24 20-55-33](https://user-images.githubusercontent.com/1583873/109058302-21b38900-76e3-11eb-99fa-afa031235abf.png)

**Comment by hpdang** [comment]
@sachinchauhan2889 I'm thinking if it is possible to use two icons: 

1) Normal Filter (without the X): when there is no active filter

2) Clear Filter: when filter(s) is selected

**Comment by sachinchauhan2889** [comment]
> @sachinchauhan2889 I'm thinking if it is possible to use two icons:
> 
> 1. Normal Filter (without the X): when there is no active filter
> 2. Clear Filter: when filter(s) is selected
> 
> Does it make sense?


Yes it can be easily implemented. Should i create PR for this?

**Comment by iamareebjamal** [comment]
Yes
