### ISSUE TITLE
Virtual Events: Change sidepanel from buttons to text with icons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6826]
The sidepanel UI for virtual events is not clear for users. People do not understand that the boxes are video rooms. We can follow other existing solutions more closely.

Please change the side panel as follows:
* Instead of buttons show the sidepanel items as a list with icons on the left and the menu item next to it similar to the screenshot below
* Order the menu points as follows
   - Schedule
   - Speakers
   - Exhibition
   - Chat
   - Video Rooms
* Similar to the screenshot show "Video Rooms" as a heading and show video rooms below
* Find a suitable smaller design for the video rooms where you possibly show a small box on the left with letter and the video room name on the right next to it (or maybe inside the box as well?). In any case the video rooms should be a menu point below the heading "Video Rooms"

![Screenshot from 2021-02-25 09-36-48](https://user-images.githubusercontent.com/1583873/109146288-eefda500-7763-11eb-9771-9b25cb3a6c17.png)

**Comment by maze-runnar** [comment]
is this ok?
![Screenshot from 2021-02-27 14-45-17](https://user-images.githubusercontent.com/56407566/109383133-7258fb00-790a-11eb-9f29-c870aa5edab0.png)

**Comment by mariobehling** [comment]
Please stick to the previous color profile, keep icons on the left and ensure video rooms are not too small font.

**Comment by maze-runnar** [comment]
![Screenshot from 2021-03-02 00-57-32](https://user-images.githubusercontent.com/56407566/109548161-4d26e100-7af2-11eb-8e7b-b14dfb861ad3.png)
