### ISSUE TITLE
List of bugs on Wizzard step 1

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#685]
* Width of wizzard is very large: Decrease the width similar to previous implementation
![screenshot from 2017-08-13 15-56-14](https://user-images.githubusercontent.com/1583873/29250265-0092f2ee-8040-11e7-9e26-c4a421f30a47.png)
* Standard view of map is world view. Why? Please compare to previous implementation that is actually showing the location more closely
![screenshot from 2017-08-13 15-53-36](https://user-images.githubusercontent.com/1583873/29250257-abad8eb0-803f-11e7-8317-5ff6d307c25d.png)
* Editing options are outside of text box. This is not following standard user experience. Please insert editing top of the actual box similar to previous implementation
![screenshot from 2017-08-13 15-54-37](https://user-images.githubusercontent.com/1583873/29250260-dadfa358-803f-11e7-8fd8-4ec52d3f9fc8.png)
* Position event images below each other
   * First event logo
   * Second event image
![screenshot from 2017-08-13 15-58-01](https://user-images.githubusercontent.com/1583873/29250278-4ee63e06-8040-11e7-98b4-e720939e3957.png)
* A number of topics and subtopics are missing
* Dropdown show only a short list of options and user has to scroll again. Why. Please compare to previous solution and increase numbers of options shown.
![screenshot from 2017-08-13 15-52-09](https://user-images.githubusercontent.com/1583873/29250248-7801ffe2-803f-11e7-8829-826c468f2a7a.png)

**Comment by geekyd** [comment]
Will be resolved in https://github.com/fossasia/open-event-frontend/pull/661

**Comment by geekyd** [comment]
Closing via #661
