### ISSUE TITLE
Public Schedule: Date filters text not in middle, get rid of empty space

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6852]
1. After the filter was implemented a few days ago the height of the buttons changed and the text is no longer in the middle on the second line of filters.
![Screenshot from 2021-02-27 14-20-36](https://user-images.githubusercontent.com/1583873/109388381-ff01ba00-7906-11eb-87b6-4166c09d13ad.png)

2. There is also an issue with the spacing in some resolutions. Basically we want the dropdown etc. to be right-aligned. However in some resolutions there is space on the first and second line and the clear filter icon moves to the third line. How can this be handled better to ensure we keep the filters to be two lines whenever possible.

Compare https://eventyay.com/e/fa96ae2c/schedule
![Screenshot from 2021-02-27 14-16-35](https://user-images.githubusercontent.com/1583873/109388326-a8947b80-7906-11eb-8605-11765704d338.png)

**Comment by Naman-1234** [comment]
Does this look okay sir?
![Screenshot (1032)](https://user-images.githubusercontent.com/63748249/109388939-16a16880-7930-11eb-975c-027f58905659.png)

**Comment by mariobehling** [comment]
No

**Comment by Naman-1234** [comment]
Sir can you please elaborate a little more about  this issue, Like what are the additional changes required along with the changes done in screenshot?

**Comment by Naman-1234** [comment]
@MeghalBisht  Mam, I was working on it as I was constantly in touch with the maintainer, So shouldn't you wait for some time. i even half solved that issue and was asking Mr. Mario Behling Sir what more changes he wants. So Mam close your Pr and let me work on this one. What do you think about this Sir @mariobehling  Sir.

**Comment by mariobehling** [comment]
@Naman-1234 Please finish existing PRs before taking up new issues. It would also be good if you could join the regular meetings of that Areeb announces on the chat channel. We are trying to align the work on different issues in a collaborative way and we will be able to avoid overlap. Basically it is difficult to define a hard rule here. Meghal made a PR first and there was not a PR from you yet. On the other hand you claimed it first. So, honestly this is just a very small issue and we should not take too much time on discussing it. The other issue that is still open from your side is also very small and still not solved. So, maybe focus on one thing at a time. Thank you.

**Comment by Naman-1234** [comment]
Ok sir, No problem. Actually, I took this issue because I thought that work in other Pr is finished and Only needs reviewing.  Thanks for the help.
