### ISSUE TITLE
Make background of content surrounding area gray

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#686]
Please make the background of the content surrounding area gray similar to previous implementation.

![screenshot from 2017-08-13 16-05-41](https://user-images.githubusercontent.com/1583873/29250348-5949e298-8041-11e7-96e5-fcc7624ec8e7.png)

![screenshot from 2017-08-13 16-05-23](https://user-images.githubusercontent.com/1583873/29250352-5e2bb89a-8041-11e7-9b68-1bf7a83a1b3a.png)

**Comment by akshitahluwalia** [comment]
I would like to work on this issue. Please assignit to me.

**Comment by akshitahluwalia** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-theme

**Comment by geekyd** [comment]
@akshitahluwalia Please check https://github.com/fossasia/open-event-theme/issues/7
