### ISSUE TITLE
Virtual Event: Renaming event video room does not rename video room on sidepanel

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6865]
The issue is similar to https://github.com/fossasia/open-event-frontend/issues/6859. The video room seems to be created on the server with an initial name. If it is changed it does not change everywhere. Should we maybe rethink this and use a room ID in order to not confuse the video room "microlocation" and the server video room name? It seems like devs are confused about it.

![Screenshot from 2021-03-01 16-59-18](https://user-images.githubusercontent.com/1583873/109523859-1e881680-7ab0-11eb-81ec-d792c86ced3e.png)

![Screenshot from 2021-03-01 17-07-56](https://user-images.githubusercontent.com/1583873/109524349-b0901f00-7ab0-11eb-9982-a7289955b549.png)

**Comment by MeghalBisht** [comment]
fixed #6964
