### ISSUE TITLE
Virtual Event Sidepanel: Third video room with youtube link not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6867]
Adding an additional video room with a youtube link the video room does not show up. Accessing the video room from the organizer page shows up, but then the video does not autoplay.

Compare https://eventyay.com/events/fa96ae2c/video/all

![Screenshot from 2021-03-01 18-09-29](https://user-images.githubusercontent.com/1583873/109532689-a7578000-7ab9-11eb-908b-d795f821bf86.png)

Compare https://eventyay.com/e/fa96ae2c?side_panel=true

![Screenshot from 2021-03-01 18-12-45](https://user-images.githubusercontent.com/1583873/109532765-bdfdd700-7ab9-11eb-9abe-73d5603b827b.png)

**Comment by iamareebjamal** [comment]
We're only showing those microlocations which have some accepted/confirmed sessions

**Comment by mariobehling** [comment]
Ok, understand. Then this is related to https://github.com/fossasia/open-event-frontend/issues/6866

We realized that we need discussion and support rooms without a schedule. We could add "discussion" over the entire day into the schedule, but adding more rooms results in a huge calendar schedule then. It would not make sense then.

![Screenshot from 2021-03-01 20-23-40](https://user-images.githubusercontent.com/1583873/109547828-2786e100-7acc-11eb-95e0-5894b600ff78.png)

**Comment by mariobehling** [comment]
However, the point about the video autoplaying is valid. I cannot get it to autoplay. The button in the form is switched off always after I save it as switched on.

![Screenshot from 2021-03-01 20-29-31](https://user-images.githubusercontent.com/1583873/109548471-f955d100-7acc-11eb-80bc-77f5790f6ac0.png)

**Comment by iamareebjamal** [comment]
Seems it was created before autoplay switcher feature and thus couldn't be saved with extra JSON, fixed now after switching video channel to jitsi and then back to YouTube

**Comment by mariobehling** [comment]
Just created it a few hours ago, but it is working now. Thank you. Will continue to observe the feature.
