### ISSUE TITLE
Instead of "my events" dashboard shows "all existing events of everyone"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#687]
Test page on https://nextgen.eventyay.com/events/live should show only the events of the user. Instead it shows all events.

![screenshot from 2017-08-13 16-07-21](https://user-images.githubusercontent.com/1583873/29250375-cdc3745e-8041-11e7-8ef2-4ddee1894e4f.png)

**Comment by niranjan94** [comment]
@mariobehling this is pending #4326 from the server. Not a bug. Just pending implementation.
