### ISSUE TITLE
Virtual Event: YouTube and Vimeo provide option for looping a video

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6882]
Currently a video that is displayed only runs one time. There are many use cases where we want the video to run in a loop. Similarly to the autostart for Youtube and Vimeo please implement the option for the organizer to "loop" a video.

The documentation for **vimeo** is here https://vimeo.zendesk.com/hc/en-us/articles/115004485728-Autoplaying-and-looping-embedded-videos

The the documentation of **Youtube** as an example below.

In the case of a single video player, a setting of 1 causes the player to play the initial video again and again. In the case of a playlist player (or custom player), the player plays the entire playlist and then starts again at the first video.

Supported values are 0 and 1, and the default value is 0.

Note: This parameter has limited support in IFrame embeds. To loop a single video, set the loop parameter value to 1 and set the playlist parameter value to the same video ID already specified in the Player API URL:

https://www.youtube.com/embed/VIDEO_ID?playlist=VIDEO_ID&loop=1

More details at https://developers.google.com/youtube/player_parameters

**Comment by mariobehling** [comment]
Please also implement the option in the form to switch it on/off similarly to autoplay.

![Screenshot from 2021-03-03 20-21-05](https://user-images.githubusercontent.com/1583873/109860131-1077f880-7c5e-11eb-83dc-c2daf558f11c.png)

**Comment by MeghalBisht** [comment]
Done already #6899
