### ISSUE TITLE
New Registration: Suddenly shows error and example.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6885]
When registering a new account the email field suddenly shows an example.com email address and error message. It seems like the account was registered nevertheless. 

![Screenshot from 2021-03-02 09-12-09](https://user-images.githubusercontent.com/1583873/109618220-90f00980-7b37-11eb-9bc9-50c39e2e09fe.png)

**Comment by mariobehling** [comment]
Additionally the account is set to verified without verification apparently.

**Comment by mariobehling** [comment]
I was using an incognito browser window.

**Comment by mariobehling** [comment]
It could be a permissions conflict, because the speaker was already added into the system as a speaker with the same email. However, the speaker did not have a registration in the system. So, when the speaker registered with the email a) the system said "the email already exists in the system" and b) the system said "The email is not yet registered". So, it displayed an error and "example@example.com" in the email box.

**Comment by mariobehling** [comment]
And even after the speaker registers these speakers are not able to login to the event and participate in the virtual event sessions.

**Comment by sahil-pal** [comment]
@mariobehling please give the opportunity to resolve this bug, I can perform the work asap
