### ISSUE TITLE
Couldn't edit My Session on 19-Feb-2021 (but works fine today, 2-Mar-2021)

### ISSUE THREAD

**Issue by maltman23** [fossasia/open-event-frontend#6888]
**Describe the bug**
On 19-Feb-2021, while logged into my account on Eventyay for FOSSASIA Summit 2021, I couldn't edit My Session (Learn to Solder with ArduTouch music synthesizer kit and make music, sound, and noise!).  When I tried I got an error message:  "Oops, something went wrong".
Today, 2-Mar-2021, it works fine:  I could make edits to My Session without a problem.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using Firefox (latest version on Windows 10 with all the latest updates), go to:
https://eventyay.com/e/fa96ae2c
2. Log in
3. Click on:  Mitch  -->  My Sessions
4. Click on:  the title of my workshop (which is the only session that is listed:  "Learn to Solder with ArduTouch music synthesizer kit and make music, sound, and noise!"
5. Click on:  Edit Session
6. Make edits
7. Click on:  Submit
8. The site reports back:  "Oops, something went wrong", and the edits weren't saved.

**Expected behaviour**
After clicking the Submit button I expected my edits to show up.

**Screenshots**
Unfortunately, I don't have a screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10 with all of the latest updates as of 19-Feb-2021 -- Version:  20H2 (OS Build 19042.804)
 - Browser:  Firefox, the latest with all of the latest updates as of 19-Feb-2021
 - Version:  Firefox V86.0 (64-bit)
 - Laptop:  Lenovo ThinkPad T450s with all of the latest udpates

**Additional context**
I tried to reproduce the error today (2-Mar-2021), but today it worked fine.

**Comment by mariobehling** [comment]
Thanks we are investigating. It might have been related to another issue on the server backend that we just fixed.

**Comment by iamareebjamal** [comment]
Was fixed in https://github.com/fossasia/open-event-server/pull/7761, https://github.com/fossasia/open-event-server/pull/7750, https://github.com/fossasia/open-event-frontend/pull/6727

**Comment by mariobehling** [comment]
Thanks @iamareebjamal for fixing it! 
Thanks @maltman23 for reporting and confirming the issue. Overall the systems is getting more stable but there are always glitches. We appreciate reports about any issue. Cheers!

**Comment by maltman23** [comment]
Glad to be of assistance.  Cool that you fixed it before I even reported it.  :)

Cheers,
Mitch

________________________________
