### ISSUE TITLE
Make email in order form uneditable

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#6892]
Email is disabled in order form if user email is set, however, if you autofill in chrome, it is still overridden and when user tries to submit the order, it saves user's email as the one in form, which may result in an error.

1. If user email exists, the form field should be disabled and uneditable
2. Even if it somehow gets filled, it should not be saved as user's email if user's email already exists

**Comment by mariobehling** [comment]
It seems like this issue resulted in an error message "Oops something went wrong" when the user clicked check out. Depending on how this gets solved a proper error message would be suitable and the user should be warned about the error right in the order step instead of being able to proceed.
