### ISSUE TITLE
Width of content area larger than expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#690]
Please match the width and - color of heading - of the content area to the previous implementation.

Content Area Width not as expected:
![screenshot from 2017-08-13 16-16-31](https://user-images.githubusercontent.com/1583873/29250449-e30f79c4-8042-11e7-8933-1b5d63df987d.png)

As before:
![screenshot from 2017-08-13 16-18-22](https://user-images.githubusercontent.com/1583873/29250462-1558e6e0-8043-11e7-8027-ead034093083.png)

**Comment by ms10398** [comment]
Is it still open can i work on it

**Comment by luanmillnitz** [comment]
It's still wrong?

**Comment by CosmicCoder96** [comment]
Resolved in #890
