### ISSUE TITLE
Account Profile Image shows broken image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6902]
The account profile image shows a broken image, e.g. on the Hong Phucs and Mario's account. And, it does not show up anymore on the top right account profile icon.

Compare https://eventyay.com/account/profile

![Screenshot from 2021-03-03 23-10-10](https://user-images.githubusercontent.com/1583873/109882983-044e6400-7c7b-11eb-9f35-1bf8bb5ca5bd.png)

**Comment by iamareebjamal** [comment]
Don't know how it changed to nonexistent image, but I have now set the avatar and original image URL to the image present in the system

**Comment by mariobehling** [comment]
Perfect. This solves the issue. Thanks.

**Comment by mariobehling** [comment]
Happening again since a few hours ago.

**Comment by maze-runnar** [comment]
not happening, reopen if happen again.
