### ISSUE TITLE
Public Speakers Page: Session links missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6904]
On the public speakers page if the user clicks on a speaker they will see the profile. Below the profile the sessions should be listed. They are missing on the speakers page (even though some are initially shown, but as soon as the user scrolls down they disappear). 

On the event start page there is a section "Feature Speakers". Here the sessions are listed as expected. On the speakers page it should work in the same way.

Compare https://eventyay.com/e/fa96ae2c/speakers
![Screenshot from 2021-03-04 14-27-00](https://user-images.githubusercontent.com/1583873/109970939-eeca5000-7cf5-11eb-9545-bd2c14315d5a.png)

**Comment by tanay123456789** [comment]
I will work on this issue.
