### ISSUE TITLE
MY TICKETS: the order id and address of event part merges and conflict.

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#6908]
**Describe the bug**
the order id and address of event part merges and conflict.

Steps to reproduce the behaviour:
1. Go to eventyay.com
2. Click on eventyay.com/my-tickets/upcoming/completed
See error

**Screenshots**
![Screenshot from 2021-03-05 01-31-55](https://user-images.githubusercontent.com/71969867/110023274-fec44d00-7d52-11eb-91e8-7299841bbbb5.png)
![Screenshot from 2021-03-05 01-31-55](https://user-images.githubusercontent.com/71969867/110024061-ea348480-7d53-11eb-8ecd-b71d905815e3.png)

**Desktop (please complete the following information):**
 - OS: linux kernal(ubuntu 20.04 LTS
 - Browser  chrome

**Comment by iamdevvalecha** [comment]
@iamareebjamal @mariobehling

**Comment by ranjitkshah** [comment]
#6154

**Comment by afzal442** [comment]
@iamdevvalecha It happened due to recent changes done in the font size.

**Comment by iamdevvalecha** [comment]
> @iamdevvalecha It has happened due to recent changes done in the font size.

okay

**Comment by AbhiSahane0** [comment]
Can I do This sir plzz

**Comment by kapilchauhan8102** [comment]
I'm working on this.

**Comment by iamdevvalecha** [comment]
@kapilchauhan8102 thanks.
