### ISSUE TITLE
Video-room page: Error while creating event video room.

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#6913]
**Describe the bug**

When user try to create video-room or edit existing video-room, after form submitting when page re-direct to video-room list, video-room is not shown there. we need to refresh page to see video-room.
(issue discussed in meeting.)

Screenshot from meeting notes:
![1](https://user-images.githubusercontent.com/72552281/110074574-70c68180-7da7-11eb-8812-1f6108b3e45a.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'video-room creation form'
2. create video-room and sees error.

**Screenshots**

https://user-images.githubusercontent.com/72552281/110077441-21368480-7dac-11eb-99e9-1e74e035c6e9.mp4

**Comment by iamdevvalecha** [comment]
@sachinchauhan2889 on it.

**Comment by iamdevvalecha** [comment]
@sachinchauhan2889 @mariobehling unable to reproduce this error locally.
https://user-images.githubusercontent.com/71969867/118700498-5d687580-b830-11eb-942f-14184a10c8aa.mp4
