### ISSUE TITLE
Public event info page with lots of bugs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#692]
Testing an event e.g. https://nextgen.eventyay.com/e/de88e486/schedule

The event site itself has lot of bugs. Here are a few:
* Position the event title and main info and ensure it is using a reasonable width
Wrong:
![screenshot from 2017-08-13 16-36-41](https://user-images.githubusercontent.com/1583873/29250604-b300430a-8045-11e7-91a3-bfcc3eac5621.png)
Correct (as previous implementation)
![screenshot from 2017-08-13 16-36-28](https://user-images.githubusercontent.com/1583873/29250606-bc2ff4d4-8045-11e7-88b4-f8fff83f7874.png)
* Menu items are shown even if content of this items is not available, e.g. there is a "Speakers" tab but no speakers
* Clicking on a tab does not change the color of the tab, e.g. click on "Tickets" and it moves to "Tickets" but the gray tab stays with "Info"
* Schedule page does not show a schedule
* Speakers are not showing up
![screenshot from 2017-08-13 16-30-36](https://user-images.githubusercontent.com/1583873/29250572-c2399c14-8044-11e7-9247-f76d3713903c.png)
* Clicking on "https://nextgen.eventyay.com/e/de88e486#getting-here" from the Call for Speakers page does not direct the user exactly to "Getting There"
* Address should be next to map and in smaller font e.g. H4
![screenshot from 2017-08-13 16-29-51](https://user-images.githubusercontent.com/1583873/29250567-b045b812-8044-11e7-9ec2-2113c5f60dd8.png)
* Make "Order Now" button green
![screenshot from 2017-08-13 16-32-44](https://user-images.githubusercontent.com/1583873/29250585-0cc67f18-8045-11e7-8222-de8c1ae6f944.png)
* Use small icons for licenses instead of big ones
![screenshot from 2017-08-13 16-33-30](https://user-images.githubusercontent.com/1583873/29250589-31693e64-8045-11e7-9738-3aecc0c5a906.png)

**Comment by AvaniVerma** [comment]
May I work on this?

**Comment by AvaniVerma** [comment]
Hello @mariobehling, may I work  on this ?

**Comment by sumedh123** [comment]
@AvaniVerma Please proceed. Try solving the width of the event name problem first since the left side bar issue will be solved in https://github.com/fossasia/open-event-frontend/issues/650. Also for changing the 'Order now' button's color, we need some input's here from @geekyd @niranjan94 .

**Comment by mbad0la** [comment]
Hi @mariobehling

It seems someone is already working on this issue (from the conversation history), but if there is something to take up, let me know :)

**Comment by mariobehling** [comment]
Should be solved in Nextgen version. Therefore closing it here.
