### ISSUE TITLE
Event Organizer Feature: Add additional Data into the Sessions CSV file 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6924]
Event organizer can currently download all sessions as a CSV file. Please add two more columns into the existing CSV File 
- Speaker Email (Next To Session Speaker Column)
- Schedule of the session (Date/Time)

**Comment by hpdang** [comment]
Has the change been deployed @iamareebjamal? Haven't changed yet for me

**Comment by iamareebjamal** [comment]
Not deployed yet. Will be Live in 15 minutes
