### ISSUE TITLE
Cookies Error? Unable to access Eventyay.com from a browser that previously logged in 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6925]
**Describe the bug**
Unable to access Eventyay.com from a browser that previously logged in. It just showed a white page. After remove Eventyay.com from Cookies list of Chrome. It worked again.

![Screenshot from 2021-03-05 19-12-31](https://user-images.githubusercontent.com/1658742/110197506-411d8500-7e4c-11eb-8bd3-e851f339b980.png)

**Desktop (please complete the following information):**
- Ubuntu 18.04
- Chrome Version 89.0.4389.72 (Official Build) (64-bit)

**Comment by mariobehling** [comment]
Yes, this is an update and cookie issue. Right now this is the solution to solve.
