### ISSUE TITLE
Schedule: Using the popularity sort feature sessions appearing twice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6927]
In the schedule using the popularity sort feature sometimes sessions appear twice.

Compare https://eventyay.com/e/fa96ae2c/schedule?sessionType=Lightning%20talk%205min&sort=-favourite-count

![Screenshot from 2021-03-06 08-26-39](https://user-images.githubusercontent.com/1583873/110198885-e557f980-7e55-11eb-8bfb-4eed76ae1d8e.png)

**Comment by maze-runnar** [comment]
I think this has nothing to do with sort by popularity. It can appear with any sort.

**Comment by maze-runnar** [comment]
When loading 6 sessions per page, the repeated sessions are different - 
![Screenshot from 2021-04-02 15-02-01](https://user-images.githubusercontent.com/56407566/113406667-82607080-93c9-11eb-9e1e-afaf035f4540.png)
![Screenshot from 2021-04-02 15-02-00](https://user-images.githubusercontent.com/56407566/113406670-842a3400-93c9-11eb-9a28-f36c390086b2.png)


when loading 10 sessions per page the repeated sessions are different - 
![Screenshot from 2021-04-02 15-02-28](https://user-images.githubusercontent.com/56407566/113411629-e851f580-93d3-11eb-9fe2-70c8ef4bbd64.png)

This is a problem of frontend or server?
