### ISSUE TITLE
My tickets page does not show tickets, but shows lots of events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#693]
E.g. https://nextgen.eventyay.com/my-tickets

Shows events, that were never booked and simply link to the event page instead of showing tickets of the user. Seems like everything is wrong on this page.

Wrong:
![screenshot from 2017-08-13 16-40-03](https://user-images.githubusercontent.com/1583873/29250638-496cd04c-8046-11e7-9f46-8af2ceccb350.png)

Correct: There are currently no upcoming events booked.
![screenshot from 2017-08-13 16-42-22](https://user-images.githubusercontent.com/1583873/29250647-6e08a5fc-8046-11e7-9710-a3370cbae9e5.png)

**Comment by niranjan94** [comment]
@mariobehling this is pending #4324 from the server. Not a bug.
