### ISSUE TITLE
Schedule: Make track, session room and date clickable and direct respected filter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6932]
On the public schedule on the session area please make the track, session room and date clickable and direct the user to the respective filter for the item.
![Screenshot from 2021-03-07 08-32-54](https://user-images.githubusercontent.com/1583873/110236025-ea8b7600-7f33-11eb-8a24-273a31735c2e.png)

**Comment by MeghalBisht** [comment]
working on this.
