### ISSUE TITLE
Exhibition: Increase logo size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6933]
The logo size is way too small on exhibition pages. Please increase the logo, e.g. similar to the sponsor logo sizes on the event front page.

Compare https://eventyay.com/e/fa96ae2c/exhibition/36

![Screenshot from 2021-03-07 11-37-31](https://user-images.githubusercontent.com/1583873/110236990-a4391580-7f39-11eb-892d-3b9c10e9d5f6.png)

**Comment by Naman-1234** [comment]
Working on it.
