### ISSUE TITLE
Problem typing in dialogue box

### ISSUE THREAD

**Issue by mishari** [fossasia/open-event-frontend#6943]
When creating an event, type in the description box, when the spacebar is pressed, the cursor jumps to the beginning of the line.

Bug present on Firefox 86.0, not Chrome, not Safari

**Comment by HimanshunVIDIA** [comment]
I want to fix the issue so please assign me this project

**Comment by HimanshunVIDIA** [comment]
i am working on this issue

**Comment by DantrazTrev** [comment]
@HimanshunVIDIA are you still working on this?

**Comment by iamdevvalecha** [comment]
@DantrazTrev i don't think so , you can start working.
