### ISSUE TITLE
Exhibition: Change position exhibition video and add heading above contact

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6946]
Please make the following improvements to the exhibitor page:

1. The exhibitor video feature works nicely but people have to scroll down before they can see the button. 
* Therefore please change the button right below the top image and add a kind of gray bar right below the image as shown below.
* Rename "Join Exhibitor Video" -> "Join Exhibitor Video Room"
* Please ensure this area only shows up if the video room for an exhibitor is activated.

2. Secondly please add a heading above the "contact area". The heading should be "Get in touch".

![Screenshot from 2021-03-08 11-42-05](https://user-images.githubusercontent.com/1583873/110312235-1cb8d880-8005-11eb-9adb-b0b25758a7c5.png)

**Comment by maze-runnar** [comment]
on this

**Comment by mariobehling** [comment]
Just like all other areas the "Get in touch" heading should only show up if there is actually a button "contact" or "email". Reopening this issue as it is not implemented in that way.

![Screenshot from 2021-03-09 11-21-01](https://user-images.githubusercontent.com/1583873/110456320-b8ac1800-80c9-11eb-98b0-965d8819f0bd.png)
