### ISSUE TITLE
User/attendee image shows up as broken

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6947]
The image of one of the users/speakers is broken. Expected would be either the user has a working image or the user shows up with an anonymous image. Compare https://eventyay.com/e/fa96ae2c/session/6613

![Screenshot from 2021-03-08 12-40-19](https://user-images.githubusercontent.com/1583873/110316894-a8cdfe80-800b-11eb-9fc6-07cfc3e306fe.png)

**Comment by rkpawar0995** [comment]
I think the expected image is not in current place or path must be change. check src/ %path%/

**Comment by iamareebjamal** [comment]
They have used API to set a facebook photo as their profile picture and it has expired `https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/1506069_10206682139874099_3032200382883718790_n.jpg?oh=952c478a40cd035bc3c1014be1f4d7e4&oe=5A9341BF`

**Comment by iamareebjamal** [comment]
I've reset it now
