### ISSUE TITLE
Settings application not working at all

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#695]
Settings applications seems to be implemented as a dummy page. It is not working at all.

![screenshot from 2017-08-13 16-57-40](https://user-images.githubusercontent.com/1583873/29250770-97e58f3c-8048-11e7-8e39-4561ca692cb7.png)

**Comment by niranjan94** [comment]
No API endpoint available yet. Pending implementation.

**Comment by harsh-98** [comment]
@niranjan i am working on this issue, the links that are to be provided are of the user or of the events.

**Comment by bhaveshAn** [comment]
Hi @niranjan94 , Is the connect here means account is sync with open event or just adding values for social links 
Because for adding social links it has been implemented.
https://github.com/fossasia/open-event-server/issues/4652#issuecomment-387840593
Thanks.

**Comment by niranjan94** [comment]
@bhaveshAn connect means, linking their social account with their open event account via OAuth. So, here, connect should start an OAuth flow. The OAuth flow needs to be taken care of on the server side. 

1. FE sends a request to BE to start the flow.
2. BE returns a URL to redirect user to as the response. FE redirects the user to that specific URL (which would be the third-party app's OAuth connect url)
3. User authenticates with the third party app and that app calls our BE callback URL. 
4. BE gets all the data it needs. Persists it. And redirects the user to an FE url
5. And we show appropriate success/failure messages.

**Comment by iamareebjamal** [comment]
Fixed already. Another issue is open for OAuth integrations
