### ISSUE TITLE
Some links are not getting linkified

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6950]
Usually links a linkified. However, http://foo.onion links are not getting linkified. See https://eventyay.com/e/fa96ae2c/session/6707 for example.

**Comment by maze-runnar** [comment]
figuring out why it's not working.

**Comment by maze-runnar** [comment]
It's working in event-descritpion ("description": "<a href=\"https://alpha.onion\" rel=\"nofollow\" target=\"_blank\">https://alpha.onion</a>")section, but not working in session-secion. And it's the request payload which is going as `comments:"https://alpha.com"`.

**Comment by maze-runnar** [comment]
in the session section - 
```
"short-abstract":"<a rel=\"nofollow\" target=\"_blank\" href=\"https://alpha.com\">https://alpha.com<br><br></a>https://dsddsd.onion"

```
