### ISSUE TITLE
Session Forms: Provide dropdown field for levels

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6959]
Please change the functionality of the session form "Level" field as follows:
* Change field into a dropdown field with the options: Beginner, Intermediate, Advanced, Expert

On the schedule page add a widget "Level" as follow:
* Show a heading "Level" if any session in the event has a level
* Similarly to "Rooms" show filter options of the levels. Only show a level if a session in a specific level exists.

![Screenshot from 2021-03-09 10-49-48](https://user-images.githubusercontent.com/1583873/110452159-33beff80-80c5-11eb-9f08-54d3c81aea7d.png)

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by Dikshapurswani** [comment]
@mariobehling I would like to work on the issue. Shall I proceed?

**Comment by afzal442** [comment]
@adilshehzad786

**Comment by adilshehzad786** [comment]
> @adilshehzad786

Thanks, @afzal442 for this opportunity.

**Comment by afzal442** [comment]
Adil, also make sure nobody is working on it!

**Comment by techpkd123** [comment]
Can i work upon this issue @afzal442 ?

**Comment by adilshehzad786** [comment]
> Adil, make sure nobody is working on it and hasn't made PR! And also see if the first taker has gone inactive or not for a longer period of time so u can work on it. Till then explore it well.

Yeah i am exploring this task and also starting my working on it .

**Comment by adilshehzad786** [comment]
> Can i work upon this issue @adillshehzad786?

@techpkd123 Yes, you can if you have expertise with NodeJS

**Comment by iamareebjamal** [comment]
No node JS experience is required to wor in this project

**Comment by iamdevvalecha** [comment]
i am starting working on this issue.please don't make any pr.

**Comment by kapilchauhan8102** [comment]
if anyone is not working on this issue, i am start working on it.

**Comment by raj-ship-it** [comment]
i am working on this issue
