### ISSUE TITLE
Admin dashboard missing substantial information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#696]
Admin dashboard is missing lots of info of the previous implementation.

![screenshot from 2017-08-13 17-00-55](https://user-images.githubusercontent.com/1583873/29250788-0e46572e-8049-11e7-8f66-17036db9f4d2.png)

**Comment by ritikamotwani** [comment]
This issue is solved by PRs: https://github.com/fossasia/open-event-frontend/pull/1232,  https://github.com/fossasia/open-event-server/pull/5247.
