### ISSUE TITLE
Exhibitors Page: Email and Contact button not in one line and heading not standardized

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6962]
If an exhibitor has both email and contact button they are not longer in a line. The space above "Get in touch" is different to other headings. Please standardize the space here.

Compare https://eventyay.com/e/fa96ae2c/exhibition/56
![Screenshot from 2021-03-09 16-10-08](https://user-images.githubusercontent.com/1583873/110492135-3552ec80-80f2-11eb-9e61-383e5d89e40e.png)

**Comment by afzal442** [comment]
looking into it

**Comment by afzal442** [comment]
![c2](https://user-images.githubusercontent.com/11625672/110506105-d064ba00-8124-11eb-9c05-7681e105dfd9.JPG)
