### ISSUE TITLE
Forms of Exhibitor's, Social Media Links of Events, Social Media in Speakers and Session Form: Add option for Mastadon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6963]
In the wizard step 2 there are social links options. Also exhibitors, speakers, and session forms have options for social media links. Please add "Mastadon" as an option in those forms and add the Mastadon icon to the public pages of those forms, e.g. on the exhibitor's page.

![Screenshot from 2021-03-09 16-10-08](https://user-images.githubusercontent.com/1583873/110492657-af837100-80f2-11eb-98e3-8cf3e8aabdcc.png)

**Comment by Varad-VK** [comment]
I wanna work on this issue. Please assign this to me and since i am new to this repo so please guide me through.

**Comment by kapilchauhan8102** [comment]
I am working on this...
