### ISSUE TITLE
Wizard: Remove button has no confirmation feature 'Yes/No' options to delete

### ISSUE THREAD

**Issue by afzal442** [fossasia/open-event-frontend#6968]
**Is your feature request related to a problem? Please describe.**

There is no confirmation pop-up after an organizer deletes a sponsor.
**Describe the solution you'd like**

There should be a confirmation message before deleting

**Additional context**

Screenshot
![c3](https://user-images.githubusercontent.com/11625672/110533194-bd151700-8143-11eb-8592-53939522bc1a.JPG)

Link: https://eventyay.com/events/2d1fdac1/edit/sponsors

**Comment by Varad-VK** [comment]
I wanna work on this issue. Please assign this to me and since i am new to this repo so please guide me through.
