### ISSUE TITLE
Tables: Top areas of tables using a lot of space

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#697]
Tables: Top areas of tables is using a lot of space. Please move number of items and search bar to same row as in previous implementation.

![screenshot from 2017-08-13 17-04-04](https://user-images.githubusercontent.com/1583873/29250811-724523ae-8049-11e7-860b-73d02f0eefbb.png)

Previous implementation

![screenshot from 2017-08-13 17-05-49](https://user-images.githubusercontent.com/1583873/29250821-ae85948e-8049-11e7-84c4-5d4af671f187.png)

**Comment by kaushal8298** [comment]
I would like to address this issue

**Comment by anshulwadhawan** [comment]
@mariobehling 
Is this issue open to be worked upon ?
@kaushal8298 
Are you still working on this issue ?

**Comment by niranjan94** [comment]
@anshulwadhawan you can work on this. @kaushal8298 please pick up some other issue :)

**Comment by anshulwadhawan** [comment]
@niranjan94 
Sure sir !
Please tell me where can i find these tables on the website ?

**Comment by niranjan94** [comment]
@anshulwadhawan https://github.com/fossasia/open-event-frontend/blob/development/app/templates/admin/users/list.hbs 

I suggest you first complete the Ember.js tutorial at https://guides.emberjs.com/v2.15.0/tutorial/ember-cli/ :)

**Comment by pradeepgangwar** [comment]
@niranjan94 Do I need admin rights to view the page that has been mentioned in the introduction?

**Comment by geekyd** [comment]
@pradeepgangwar The tables are implemented using ember models table. Check `ui-table` component. Have a look at `/events` route to check the UI.

**Comment by sourabh1031** [comment]
I would like to work on the issue

**Comment by sarnava1** [comment]
Is anyone still working on this issue? If not I would like to contribute @mariobehling?

**Comment by sarnava1** [comment]
@niranjan I will file a PR soon.

**Comment by niranjan94** [comment]
Sure @sarnava1

**Comment by sarnava1** [comment]
@niranjan94 presently the tables looks like this:
![openeventfrontendnow](https://user-images.githubusercontent.com/25319565/46576513-0c8e1080-c9e9-11e8-9e09-6ec75c1246b7.png)
No of items and search bar is already in the same row. Can you please guide me on what changes do I need to make? 
(please ignore the confirmation mail message at the top)

**Comment by sarnava1** [comment]
@niranjan94 @mariobehling please help me a bit in this issue as currently I cannot understand as to what I should do in this issue.

**Comment by sarnava1** [comment]
@ritikamotwani @mariobehling @CosmicCoder96 @niranjan94 @simsausaurabh  please help me as I cannot understand on what I have to do here.

**Comment by mohitm15** [comment]
@mariobehling @niranjan94 Should I take this issue

**Comment by kushthedude** [comment]
Working on it

**Comment by mohitm15** [comment]
@kushthedude needed to ask first pal

_Sent from my VIBE K6 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kushthedude** [comment]
No one is assigned an no one did some notable work and you already have
some unmerged PRs with changes requested on them .

**Comment by mohitm15** [comment]
@kushthedude so what l am waiting for confirmation to be get assigned

_Sent from my VIBE K6 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kushthedude** [comment]
@ritikamotwani The PR merged above is not the proper fix ,There is still a lot of extra space in the table areas , Respective PR just removes an additional container , and nothing else .
Please reopen the issue.

**Comment by ritikamotwani** [comment]
@kushthedude , I was about to.
You can take a look at the PR (https://github.com/fossasia/open-event-frontend/pull/3015) description it says Partially resolves.
Merging the PR closed the issue. :)

**Comment by kushthedude** [comment]
I responded too fast 😅
