### ISSUE TITLE
Virtual Events Side panel menu items moving upwards in smaller windows

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6975]
If the browser window is shorter the side panel in virtual events moves menu items upwards that overlap above items. Expected is that the items stay as expected and that video rooms create an internal scroll bar as in the previous implementation.

![Screenshot from 2021-03-10 10-16-34](https://user-images.githubusercontent.com/1583873/110606193-39324d80-818a-11eb-932a-7206f450b11f.png)

**Comment by sachinchauhan2889** [comment]
looking into this
