### ISSUE TITLE
Admin Section: Dummy content, missing features, bugs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#698]
The admin section still does not show a lot of data. It has dummy pages with lacking functionalities.
* Dummy pages
  * Sales
  * Messages
* Content cannot be sorted and is sorted to oldest date. It should show the newest date entry on top, e.g. https://nextgen.eventyay.com/admin/reports/system-logs/activity-logs
* User page:
  * Entries cannot be sorted on the table top as in previous implementation
  * Filters "Active" and "Deleted" users show the same data
![screenshot from 2017-08-13 17-16-18](https://user-images.githubusercontent.com/1583873/29250899-3c38c7dc-804b-11e7-88db-b3613795d2fd.png)
  * Lots of data is missing
![screenshot from 2017-08-13 17-11-53](https://user-images.githubusercontent.com/1583873/29250870-8a3a600e-804a-11e7-9849-27997108a9bf.png)
* Content pages are not getting data from system
![screenshot from 2017-08-13 17-14-19](https://user-images.githubusercontent.com/1583873/29250887-e46edb7c-804a-11e7-9ace-4703fd0b3555.png)
* Create Page is not possible
* System images are not working and just implemented as dummy section
![screenshot from 2017-08-13 17-15-28](https://user-images.githubusercontent.com/1583873/29250892-0b04141e-804b-11e7-9043-d64e3538ad0b.png)
* Kubernetest Logs not available
![screenshot from 2017-08-13 17-17-29](https://user-images.githubusercontent.com/1583873/29250901-54ba7e72-804b-11e7-89ea-cdedc05d5742.png)
* Currencies are not available
![screenshot from 2017-08-13 17-18-45](https://user-images.githubusercontent.com/1583873/29250906-7e06a74c-804b-11e7-9eea-64e3c476971e.png)

**Comment by niranjan94** [comment]
Server endpoints still pending for
- Logs (kubernetes, system etc)
- user roles data
- Sales
- Message

**Comment by CosmicCoder96** [comment]
Dummy sections removed, tables replaced, we no longer use Kubernetes, pages API works.
