### ISSUE TITLE
Ticket Order Email: HTML converted to text and links not displayed properly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6983]
The after event ticket email does not display web links and other html code properly in the ticket emails. 

It shows:
`Thank you for signing up for the FOSSASIA Summit 2021 on <a href="http://eventyay.com" rel="nofollow" target="_blank">eventyay.com</a>. `

![Screenshot from 2021-03-11 10-07-45](https://user-images.githubusercontent.com/1583873/110763188-e45a0a00-8251-11eb-8677-750e01596492.png)

**Comment by sachinchauhan2889** [comment]
looking into this.
