### ISSUE TITLE
Footer: All links are not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#699]
Links on footer are not working.

![screenshot from 2017-08-13 17-20-28](https://user-images.githubusercontent.com/1583873/29250926-c47a4fb2-804b-11e7-80c5-ae044d400d7d.png)

**Comment by akshitahluwalia** [comment]
@mariobehling I would like to work on this issue, please assign this issue to me.

**Comment by mittalprince** [comment]
sir, is this issue is still present?
As i have open the website link and all the footer link are working.
please reply sir 
thanks

**Comment by vaibhav16uec121** [comment]
hello sir,
sir,
The contact us in footer is not taking to the page where the user can contact you, so either a page is needed or the contact us option should be removed and same as with the help button also.
And the categories are just taking to the top of page and to the categories divisions. Lastly, there is no use of languages changer at the footer in the pages as no change is happening so its better to remove the option. Else no issue can be seen it the footer.

**Comment by sumedh123** [comment]
@vaibhav16uec121 The contact us in the footer is a dummy page that the admin of the app creates. So for now, we have put dummy content in it. It depends on the admin what he wants to add. The horizontal links in the footer can be created from ```admin/users/pages```. Hence that part is okay. Also the languages part at the footer is necessary. Our aim is to create eventyay.com. Please check the behaviour on eventyay.

**Comment by vaibhav16uec121** [comment]
@sumedh123 @mariobehling 

**Current behavior:**
In 350px width the footer does some random float of words which make a haste.
![issue 699](https://user-images.githubusercontent.com/29895469/30342134-45347196-9816-11e7-90ec-720d64307076.PNG)



**Expected behavior:**
terms & Condition should be not apart

I would like to work on this .

**Comment by sourabh1031** [comment]
Hey i would like to work on this issue.Is this still present or resolved?

**Comment by CosmicCoder96** [comment]
completed via #1459 #1304 #800
