### ISSUE TITLE
Blank/empty sessions in the schedule with random times

### ISSUE THREAD

**Issue by jj5** [fossasia/open-event-frontend#6997]
**Describe the bug**

When I open the Schedule for the FOSSASIA Summit 2021 I see blank/empty sessions at unordered/random times. (See screenshot for example.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/fa96ae2c/schedule

**Expected behaviour**

Sessions should not be empty/blank and session times should be listed chronologically.

**Screenshots**

![Screenshot_20210313_220538](https://user-images.githubusercontent.com/5469039/111032222-4471cb80-845f-11eb-956e-44fbe005ca6a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 with KDE Plasma
 - Browser: Firefox 86.0

**Additional context**

My Firefox is configured not to send the HTTP Referer header which does sometimes cause issues.

**Comment by mimidotsuser** [comment]
@jj5 are you still experiencing the issue? 
I am not able to replicate the issue on my end (_using Ubuntu 18~Gnome +Firefox-86.0b9 with `network.http.referer.defaultPolicy` set to zero)_

**Comment by maze-runnar** [comment]
this issue is already fixed : https://github.com/fossasia/open-event-frontend/pull/7734
