### ISSUE TITLE
Organizer Video Tab Edit Form Changes Video Choice Even Though User Chooses "Cancel"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6999]
In the organizer video room edit form when the user clicks on other video options a pop up message appears. If the user clicks cancel to this message the system will just work in the same way as if the user clicks ok. Expected is that the previous setup remains.

![Screenshot from 2021-03-13 23-40-38](https://user-images.githubusercontent.com/1583873/111051765-d674d680-8455-11eb-80c2-be6c538f284e.png)

**Comment by Prince-yohannan** [comment]
sir i want to work in it

**Comment by spy-1234** [comment]
Sir I want to work on this issue
