### ISSUE TITLE
Session and Exhibitor Form: Simplify Slide Form Element

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7000]
In the past we had decided to offer an option to either upload slides or link them from somewhere else. It turns out that this makes things more complicated. We cannot validate slides and link locations of slides might change.

Therefore change the slide form areas in the session form and the exhibitor form to only provide the option to upload slides.
Also change the following:
* Do not show the API link of slides anymore, instead show a more standard display with the slide name similar to other services with this feature

For existing slides that are on external pages, please use a script to download these slides and import them into the system and show them as uploaded slides.

**Comment by spy-1234** [comment]
I can solve this issue. So, please give a chance.

**Comment by kapilchauhan8102** [comment]
i am already working on it. please see another issue.

**Comment by maze-runnar** [comment]
@ranjitkshah please give it a try. leave this part for now:
 `For existing slides that are on external pages, please use a script to download these slides and import them into the system and show them as uploaded slides.`
