### ISSUE TITLE
transition for mobile screen menu

### ISSUE THREAD

**Issue by g4rry420** [fossasia/open-event-frontend#7008]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, the mobile screen menu doesn't have any transition, it just pops up. It will be nice if it comes up as a slider from the left side.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Before Solution:

[

https://user-images.githubusercontent.com/61521805/111260368-0ad3c880-85f7-11eb-8f9c-34135181d330.mp4

](url)

After Solution:

[

https://user-images.githubusercontent.com/61521805/111260394-14f5c700-85f7-11eb-8388-579ce939c087.mp4

]()

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by MeghalBisht** [comment]
Not needed
