### ISSUE TITLE
Speaker Session Form: Increase file limit to 30 MB

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7009]
File limit for slides and videos are currently 10 MB. Please increase it to 30 MB

![Screenshot from 2021-03-16 11-44-19](https://user-images.githubusercontent.com/1583873/111296754-21a50a00-864d-11eb-84ad-a0ac1d7b1059.png)

**Comment by kapilchauhan8102** [comment]
I'm working on it.
