### ISSUE TITLE
Dropdown panel too slow and too small

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#701]
![screenshot from 2017-08-13 17-22-49](https://user-images.githubusercontent.com/1583873/29250967-7e63458c-804c-11e7-8ab3-40898d361b16.png)

Please fix the following in the panel:
* Make dropdown speed immediate. No delay. It is too slow.
* Increase width to match previous implementation
* Add logout icon as in previous implementation
![screenshot from 2017-08-13 17-23-25](https://user-images.githubusercontent.com/1583873/29250972-8e909a36-804c-11e7-9e9b-f51dc676f6d1.png)

**Comment by akshitahluwalia** [comment]
I would like to work on this issue. Please assign it to me. :smile:
