### ISSUE TITLE
Social Link Fields: Overlapping of name and url boxes in wizard 2.

### ISSUE THREAD

**Issue by kapilchauhan8102** [fossasia/open-event-frontend#7011]
**Describe the bug**

Overlapping of name and url boxes in wizard 2.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to create event wizard 2.
2. Click on add social media link.
3. See error 

**Expected behaviour**

 They should not overlap.

**Screenshots**

![1](https://user-images.githubusercontent.com/80362650/111364337-1ab2e180-86b7-11eb-93a8-329726206586.png)

**Comment by kapilchauhan8102** [comment]
working.

**Comment by Bhargav644** [comment]
hello sir i want to work on it and i must fix this but i am beginner to git and github .please Help!!

**Comment by joeytwiddle** [comment]
@Bhargav644 When you are looking for help, you should ask a precise question. :-)

https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
