### ISSUE TITLE
Organizer creates session, which is then not associated with speaker account in my sessions tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7015]
When an organizer adds a session and then an existing user with the same email does not see the associated, e.g. here https://eventyay.com/events/fa96ae2c/speaker/5443.

The speaker does not see the email. Though actually it is a big strange too, that if an organizer could just add a session to another account without the other account accepting it.

How should this really work in the best way?

For the first step it would be good if the account could be associated with this, but the account should maybe get an email "you have been invited to session abc...." and accept it? or just decline it? Not sure.

**Comment by iamareebjamal** [comment]
@maze-runnar Try to reproduce

**Comment by maze-runnar** [comment]
If I am getting issue correctly, it is working fine. I have added a speaker with email `dubeysundaram057@gmail.com` when loggedin as different user. Then logged in as `dubeysundaram057@gmail.com` and seen that session in mysession section.
![Screenshot from 2021-04-02 20-25-00](https://user-images.githubusercontent.com/56407566/113426901-bb144000-93f1-11eb-981a-0308097af60f.png)
![Screenshot from 2021-04-02 20-24-56](https://user-images.githubusercontent.com/56407566/113426906-bcde0380-93f1-11eb-9e38-6742470c2338.png)
![Screenshot from 2021-04-02 20-27-06](https://user-images.githubusercontent.com/56407566/113426953-d0896a00-93f1-11eb-9935-b4112917f516.png)
