### ISSUE TITLE
Link redirect of current day results in user forward to wrong filtered page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7016]
We now have the feature that the user is directed automatically to the session of the current day if the date is within the event date. However if a user has a direct link, e.g. to https://eventyay.com/e/fa96ae2c/schedule?search=nick, then the use is instead directed to https://eventyay.com/e/fa96ae2c/schedule?date=2021-03-17&search=nick. This gets the user to the wrong page.

**Comment by sachinchauhan2889** [comment]
@mariobehling  sir i am looking into this.

Can you please tell me desired functionality.

we want current day schedule when event is running. I having doubt, when we need to show current day schedule.

1. Do we want current day schedule when someone visit [https://eventyay.com/e/fa96ae2c/schedule](url)  directly??

                                           OR

2. we want current day schedule only when user visit [https://eventyay.com/e/fa96ae2c/schedule](url), But we don't want current day schedule when user visit schedule page directly with some applied filters example:- [https://eventyay.com/e/fa96ae2c/schedule?seaarch=nick](url)

**Comment by vartikaSaxena** [comment]
Hey, @mariobehling I find this issue interesting, can I work on it?

**Comment by pranav1311** [comment]
Hey @mariobehling  i understand that the issue is that user is getting not particular date page and instead all , i can contribute and solve this issue , how can i submit proposal ?

**Comment by maze-runnar** [comment]
Couldn't find the exact way, but popping the filter would work like - 
```
if(datefilterisactive && params.search) {
   filterOptions = null;
  filteroption for searching;
}else{
  restore previous filters;
}
```

**Comment by Prince-yohannan** [comment]
hello sir can i work in it

**Comment by progmatic-99** [comment]
I am not able to reproduce this.
