### ISSUE TITLE
Wizard Step 2 not accessible for no apparent reason

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#702]
Trying to get to wizzard step 2 is not possible for no apparent reason: https://nextgen.eventyay.com/events/8b42dd86/edit/basic-details

![screenshot from 2017-08-13 17-27-54](https://user-images.githubusercontent.com/1583873/29250986-d75fa4aa-804c-11e7-9c65-38ade2fae2a6.png)

Clicking "Save Draft" neither shows any outcome, but: The draft is saved when checking draft events.

**Comment by CosmicCoder96** [comment]
Was fixed in https://github.com/fossasia/open-event-frontend/pull/661, closing this.
