### ISSUE TITLE
Registration Form missing fields

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#703]
Please implement the registration form as expected and move speaker form and session details below each other.

![screenshot from 2017-08-13 17-30-57](https://user-images.githubusercontent.com/1583873/29250998-4d78a2b8-804d-11e7-9b0b-2a1fbdb50005.png)

**Comment by vaibhav16uec121** [comment]
I would like to work on this issue. Please it to me.

**Comment by geekyd** [comment]
@vaibhav16uec121 This issue has already been resolved. 

Closing via https://github.com/fossasia/open-event-frontend/pull/613
