### ISSUE TITLE
Sessions entry clipped in Firefox for Android

### ISSUE THREAD

**Issue by mishari** [fossasia/open-event-frontend#7034]
When I go through the list of sessions in firefox for android, it's clipped on the right, scrolling is locked so I can't see the full information. I need to enable "request desktop site" in order to see the full entry".

**Comment by RiyaGupta89** [comment]
@mishari  Please share ss for describing more.

**Comment by pc-beast** [comment]
It looks duplicate of #6761 which are closed in #7467 @maze-runnar this could be closed now
