### ISSUE TITLE
Please enable persistent sessions

### ISSUE THREAD

**Issue by tillea** [fossasia/open-event-frontend#7040]
**Is your feature request related to a problem? Please describe.**
I joined FOSSASIA summit 2021 and realised that I need to login every single day.  After each fresh login I had to navigate to the place I want to view (be it my own registered events, the chat, the video stream whatever) since I was always landing on the general Eventyay landing page

**Describe the solution you'd like**
Services like Github and many others are using persistent logins where I can stay logged in even after suspending my device over several days and I'm back with all my tabs to different deep links immediately.

I would love to see this in Eventyay as well.
Kind regards, Andreas.

**Comment by iamareebjamal** [comment]
Dupllicate of #3353
