### ISSUE TITLE
Slow/unreliable BBB room entry procedure; echo test should take no more than 2.5s to start

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-frontend#7042]
**Describe the bug**
A repeated problem at FOSSASIA 2021 was that room entry was slow or outright failed.

In particular both Harish and I had trouble entering BBB for our scheduled sessions:
- In my case I was already in, but someone decided to restart BBB 4 minutes before the start of the session. Fortunately the session being a panel meant a lengthy introduction, so when I was finally successful in re-entering it was still 3-4 seconds before Hong Phuc completed the introduction.
- Harish was not so lucky, and the audience had to wait several minutes while he found a way to get in.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Eventyay, log in, select FOSSASIA 2021
2. Click on Join Live Event
3. Scroll down to and click Main Hall
4. Thumbs up/down does not appear quickly, or potentially at all.

**Expected behaviour**
4. Thumbs up/down appears reliably and **never** more than 2.5s after the user clicks Main Hall.

**Additional context**
2.5s is what Google [recommends](https://developers.google.com/speed/docs/insights/v5/about#crux) for Largest Contentful Paint (LCP), which would appear to be the relevant metric for this situation.

In addition to sorting out and fixing what's causing the delays and failures generally at present, it would appear sensible for a positive failure report to go to sentry.eventyay.com every time the thumbs-up/down fails to appear within 2.5s (perhaps 2s if we want advance warning of a potential failure), and for this to be treated as a serious failure requiring immediate attention if it happens during an event. Obviously the answer will sometimes be slow network/PC about which we can do nothing, but we shouldn't be letting it fail silently and therefore leaving participants to deal with it.

Of course, an even better option is to dispense with this procedure completely:
- We have no interest in peer-to-peer communication at all, so we should not be using ICE/STUN/TURN in the first place, just configuring specific IP addresses as part of the setup.
- People should enter rooms as viewers and speakers (with no microphone audio transmitted) immediately and the echo test procedure only offered when someone decides to unmute.

but until/unless we can get to that point, fixing the above would seem like a minimum requirement.

**Comment by iamareebjamal** [comment]
Unfortunately, all that is part of BigBlueButton, as we don't have any idea of when the echo test or thumbs up/down button is loaded, because it is loaded in an iframe as BBB URL. So, we can't alert it on sentry.

Hiding echo test by default and only showing it on unmuting is also something which can only be configured on BBB server or by modifying its code

**Comment by mariobehling** [comment]
This issue is reported and open on the BBB tracker here https://github.com/bigbluebutton/bigbluebutton/issues/8824

Therefore closing it on this tracker.
