### ISSUE TITLE
Virtual Events: Custom option switches to BBB

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7054]
When setting up video rooms the custom option switches to autogenerated BBB rooms. This happened several times when a user created an external BBB room on video.eventyay.com directly and then added this video room as a custom option.

**Comment by kaiwalyakoparkar** [comment]
Hey, I would like to work on this issue could you please tell me how can I contribute

**Comment by iamareebjamal** [comment]
First reproduce the issue
