### ISSUE TITLE
User can create group without any event

### ISSUE THREAD

**Issue by g4rry420** [fossasia/open-event-frontend#7064]
**Describe the bug**
Currently, A user can create a group without adding any event into it. I think, this is not expected behaviour of the groups. User should atleast add one event into the group.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Groups'
2. Click on 'Create Group'
3. Then enter a group name but don't add any event.
4. Click 'save'.

**Expected behaviour**
User should only able to create group if user has selected atleast 1 event.

**Screenshots**
![no_event_group](https://user-images.githubusercontent.com/61521805/112689872-3e152380-8e51-11eb-89bc-0dccf4378e04.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox, Chrome

**Comment by iamareebjamal** [comment]
Not needed
