### ISSUE TITLE
Wizzard Step 3: Publishing event not possible and no error message if sth. is missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#708]
On Wizzard Step 3, it is not possible to publish the event just created. There is no error message if a field is missing or whatsoever.

![screenshot from 2017-08-13 21-05-32](https://user-images.githubusercontent.com/1583873/29252657-48f8f774-806b-11e7-84f6-70551fba23f3.png)

**Comment by geekyd** [comment]
This was resolved after https://github.com/fossasia/open-event-orga-server/pull/4310
