### ISSUE TITLE
Wizard Step 1: Sales time not pre-filled

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#709]
Ticket sales are not pre-filled and the details are hidden if user does not expand the fields manually. Expected: As in previous version, the sales time should be pre-filled with: start immediately and end of sales at the time of the end of the event. The user should have the ability to change this then.

![screenshot from 2017-08-13 21-07-31](https://user-images.githubusercontent.com/1583873/29252674-b9fa25ec-806b-11e7-8af0-4eb9b28d2ff3.png)

**Comment by geekyd** [comment]
This will be done in https://github.com/fossasia/open-event-frontend/pull/661

**Comment by geekyd** [comment]
Closing via #661
