### ISSUE TITLE
User can see, edit and delete any event on the system on his/her own dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#710]
Any users see other events in his/her own dashboard and can do anything with the event. It is also possible to see sales, emails of speakers and anything. How is this possible?

![screenshot from 2017-08-13 21-15-47](https://user-images.githubusercontent.com/1583873/29252726-bb58d59a-806c-11e7-8756-49c87d1c18e3.png)

**Comment by niranjan94** [comment]
@mariobehling this is pending https://github.com/fossasia/open-event-orga-server/issues/4326 from the server. Not a bug. Just pending implementation.

**Comment by geekyd** [comment]
Closing this via https://github.com/fossasia/open-event-frontend/pull/733
