### ISSUE TITLE
Copy event button does not work

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#711]
The copy event button does not work.

![screenshot from 2017-08-13 21-18-32](https://user-images.githubusercontent.com/1583873/29252735-037cabc6-806d-11e7-9c7c-a429dc497101.png)

**Comment by CosmicCoder96** [comment]
Implementation pending server side.

**Comment by niranjan94** [comment]
@open-event-bot move to fossasia/open-event-orga-server
