### ISSUE TITLE
Attendee/Speaker Form: Adjust gender question to be more inclusive

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#7129]
We have a Gender question in both Attendee form and Call for speakers. Could you please add the following options into that form: 

Gender 
- [ ] Female
- [ ] Male
- [ ] Diverse / Non-binary
- [ ] Other
- [ ] Prefer not to share

**Comment by tanay123456789** [comment]
working on this issue.

**Comment by hpdang** [comment]
@tanay123456789 any updates on this?

**Comment by iamdevvalecha** [comment]
@hpdang done.

**Comment by hpdang** [comment]
Thank you :)
