### ISSUE TITLE
Speakers features and add speakers is not functional dummy 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#713]
The add speakers feature is not implemented. Adding speakers is not possible.

![screenshot from 2017-08-13 21-22-30](https://user-images.githubusercontent.com/1583873/29252767-a197e9a6-806d-11e7-88cb-9f6a459b60d9.png)

**Comment by harshitagupta30** [comment]
This will be implemented in PR #646

**Comment by CosmicCoder96** [comment]
Fixed in #1321 #1164 #1167 #1350 #1288 #1262 .
