### ISSUE TITLE
Ticketing feature seems to be mostly not implemented

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#715]
Trying out ticketing features quickly results in failures. It is not possible to use the system and from an event organizer perspective there are only dummy views.

![screenshot from 2017-08-13 21-24-57](https://user-images.githubusercontent.com/1583873/29252785-fadb8acc-806d-11e7-913a-8cfb81240ea3.png)

**Comment by CosmicCoder96** [comment]
Ticketing section is fully functional now.
