### ISSUE TITLE
Add button is align improperly in Attendee and Session & Speaker Forms.

### ISSUE THREAD

**Issue by kapilchauhan8102** [fossasia/open-event-frontend#7150]
**Describe the bug**
Add button is align improperly in attendee and session & speaker forms.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Event wizard 4'
2. Click on 'Attendee Form'
3. Scroll down to 'Add Custom Form Field'
5. Same for Session & speaker form.

**Expected behaviour**
Add button align properly.

**Screenshots**

**In attendee form**

![1](https://user-images.githubusercontent.com/80362650/115116272-5c84bf80-9fb6-11eb-8ab0-b7919c3afb27.png)

**In session &speaker form**

![2](https://user-images.githubusercontent.com/80362650/115116283-6ad2db80-9fb6-11eb-9c3c-43c4534306f0.png)

**Comment by kapilchauhan8102** [comment]
working

**Comment by faisalkhandholpur** [comment]
I wanna this issue
