### ISSUE TITLE
Improper alignment of event card 

### ISSUE THREAD

**Issue by rajatgupta24** [fossasia/open-event-frontend#7156]
**Describe the bug**

The event card is having improper alignment as the size of the image is larger than the card. 

**To Reproduce**
1. Go to 'https://eventyay.com/explore?category=Science%26 Technology'
2. Scroll down to 'events list'
3. See an error

**Expected behavior**

The image of the card should be the same size as that of the card.

**Screenshots**

![image](https://user-images.githubusercontent.com/55191777/115598844-78f76380-a2f8-11eb-9eb8-a60fe01ca94a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox

**Comment by rajatgupta24** [comment]
Hey @mariobehling, @iamareebjamal, @CosmicCoder96, can I start working on it?

**Comment by abhaysinghs772** [comment]
hey @rajatgupta24 , I am beginner and I want to work on this issue.
can I work on this issue

**Comment by faisalkhandholpur** [comment]
I am new on fossasia, and i wanna this issue please you assign me.

**Comment by sans2801** [comment]
Hello @rajatgupta24, I'd like to know if the issue is still open

**Comment by sans2801** [comment]
@rajatgupta24 @mariobehling 
![image](https://user-images.githubusercontent.com/56474333/116983141-5c3f3080-ace7-11eb-9405-ed9d2ddfaafc.png)
I've worked this out, does this solve the issue

**Comment by rajatgupta24** [comment]
Hey @sans2801, go ahead create a PR :smiley:

**Comment by sans2801** [comment]
Thank you @rajatgupta24 😃

**Comment by Abhicodes-crypto** [comment]
Hi, I am a beginner. Is this issue still open ? Can I work on this ?

**Comment by rajatgupta24** [comment]
Hey @Abhicodes-crypto, yeah sure go ahead 😄👍🏻

**Comment by salmanansari14** [comment]
Hello i'm new in open source also passionate contribution on open source organization **can i contribute on it please !_

**Comment by Abhicodes-crypto** [comment]
Hello @salmanansari14 , I'm already working on this issue.

**Comment by salmanansari14** [comment]
@Abhicodes-crypto  greate keep it up !
