### ISSUE TITLE
Inviting other users not working and dummy user filled in

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#716]
The manage user roles are not working and a dummy user shows up for no reason.

![screenshot from 2017-08-13 21-26-48](https://user-images.githubusercontent.com/1583873/29252801-35fb662c-806e-11e7-9981-a2bea9607321.png)

**Comment by Siddhinita** [comment]
@mariobehling  , Can I work on this issue?

**Comment by niranjan94** [comment]
Hi @Siddhinita ... Welcome to the project. You can first begin by setting up the project and running it locally. And then you could work on it. Though, if you're new to Ember.js, I'd recommend you start on simpler issues first. As this issue requires API integration. But if you're already familiar with Ember.js and the API, then feel free to go ahead with this issue once you have set up the project locally ! 😄

**Comment by Siddhinita** [comment]
Hi @niranjan94 , Thanks for replying.
I have set up the project offline . 
Should the dummy user be removed ? If yes I can make a PR for the same and "manage user roles" feature can be dealt with in another issue .

**Comment by niranjan94** [comment]
They should be removed and replaced with an API call instead. In the same
PR.

**Comment by Siddhinita** [comment]
Which API is to be used for loading users?

**Comment by geekyd** [comment]
@Siddhinita We are using JSON API here via ember-data. If you are familiar with ember data then check how the events are being fetched at index route. If you are not familiar with it please check the docs [here](https://emberjs.com/api/ember-data/2.14/modules/ember-data).

**Comment by geekyd** [comment]
@Siddhinita Any update on this?

**Comment by CosmicCoder96** [comment]
#802 and #783 added the required functionality. 
Closing this.
