### ISSUE TITLE
Stripe Connection Error "Account Cannot Connect to Itself"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7161]
When trying to connect Stripe to one of our own events I am getting "Account cannot connect to itself". I assume it is because we also use Stripe to pay to the platform. 

What options do we have? Is that the reason or how to handle this?

![Screenshot from 2021-04-22 20-49-52](https://user-images.githubusercontent.com/1583873/115770138-971e9b80-a3ac-11eb-9247-6f460796a187.png)

**Comment by iamareebjamal** [comment]
You need to create another stripe account (personal or otherwise) and connect that instead.
