### ISSUE TITLE
Rename Admin "video-channels" to "Video"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7183]
Please simplify the tab "video-channels" to be "Video" in the admin section of the platform.

**Comment by kapilchauhan8102** [comment]
working on this.

**Comment by tanay123456789** [comment]
work completed

**Comment by tanay123456789** [comment]
work done

**Comment by tanay123456789** [comment]
There was something wrong with my previous PR that's why I closed that one and created a new one

**Comment by faisalkhandholpur** [comment]
Please assign this issue

**Comment by tanay123456789** [comment]
@faisalkhandholpur my PR is open for that as i had fixed that issue already. Find other issue

**Comment by iamdevvalecha** [comment]
@tanay123456789 are you still working on this.

**Comment by tanay123456789** [comment]
@iamdevvalecha  yes
