### ISSUE TITLE
Event Calendar: Show event link if event is online event in "Location Field"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7184]
When I add an event calendar the “Location Field” should show the link to the event instead of “Online Event”

**Comment by faisalkhandholpur** [comment]
Sir please assign this issue to me , i can handle it.

**Comment by faisalkhandholpur** [comment]
Sir I'm not external contributors , i have also  faisalkhandholpur

**Comment by tanay123456789** [comment]
@faisalkhandholpur that's a bot saying to you not sir

**Comment by tanay123456789** [comment]
@faisalkhandholpur if you work on it then write about that you are working on this issue and after you solve that issue then open a PR for the same

**Comment by mariobehling** [comment]
The previous merged PR has some unwanted side effects. We need to test the PR with the updated server component first. Therefore I reverted the previous PR.

![Screenshot from 2021-05-10 08-15-00](https://user-images.githubusercontent.com/1583873/117614682-f4666b00-b168-11eb-852f-c511924f0c4b.png)
