### ISSUE TITLE
Honoring Areeb Jamal Sir, It's Not An Issue

### ISSUE THREAD

**Issue by Creatoon** [fossasia/open-event-frontend#7202]
The Website Should Have A tagline in the footer "Made By Areeb With Heart "

RIP Areeb Sir, No One Can Replace You.

**Comment by himanshujaidka** [comment]
very shocking :(

**Comment by iamdevvalecha** [comment]
![Screenshot from 2021-04-30 21-39-36](https://user-images.githubusercontent.com/71969867/116723115-c52f5b80-a9fc-11eb-9c7a-2516b00e7b5b.png)

**Comment by Creatoon** [comment]
@iamdevvalecha place that line on the next line
And align it center and also use heart sticker 
"Made By Areeb Jamal With ❤"

**Comment by klsingh016** [comment]
@Creatoon i can do

**Comment by Creatoon** [comment]
@klsingh016 you can see, there is already an pr attached

**Comment by klsingh016** [comment]
ok
