### ISSUE TITLE
User Cannot Change "Owner" of Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7229]
Users who try to change the owner of an event receive the following error:

> Ember Data Request POST https://api.eventyay.com/v1/role-invites returned a 409 Payload (application/vnd.api+json) [object Object]

**Comment by MeghalBisht** [comment]
This is happening when 
A sent an invite to B - Works
Invitation is in pending state as B has not accepted 
A sends invitation again to B - Fails as invite is already sent
