### ISSUE TITLE
Exhibitors Page results in 505

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7230]
Exhibitors pages do not work currently. Compare to https://eventyay.com/e/fa96ae2c/exhibition

![Screenshot from 2021-05-05 15-16-00](https://user-images.githubusercontent.com/1583873/117146747-d1c50280-adb4-11eb-86b6-4ffe9840a78e.png)

**Comment by sans2801** [comment]
Hello sir, I would like to know whether this is an issue on the flask server side

**Comment by mariobehling** [comment]
Same issue happens on organizer view https://eventyay.com/events/fa96ae2c/exhibitors.

**Comment by klsingh016** [comment]
@mariobehling @MeghalBisht work her?

**Comment by maze-runnar** [comment]
@sachinchauhan2889 @MeghalBisht 
`{"data": {"type": "exhibitor", "attributes": {"banner-url": "https://api.eventyay.com/static/media/exhibitors/1/large/NW1EbGpHVi/432c952e-79ab-4a01-bf2c-3ca704681452.jpg", "contact-email": null, "social-links": null, "slides-url": "https://api.eventyay.com/static/media/events/temp/f4b8ca2b-a053-4a67-875c-93cd0b8f1c82/bnhRSnBSQn/23c02f1b-1dca-4228-a0ba-b8afd3b21fa1.pdf", "position": 0, "thumbnail-image-url": "https://api.eventyay.com/static/media/exhibitors/1/thumbnail/UDZVNTdHNF/b44b05f1-2f08-4682-bf7d-f65c8d335a13.jpg", "status": "accepted", "contact-link": null, "description": "Free and Open source Software Developers' European Meeting is a non-commercial, volunteer-organized European event centered on free and open-source software development. It is aimed at developers and anyone interested in the free and open-source software movement", "enable-video-room": false, "logo-url": "https://api.eventyay.com/static/media/temp/images/5d7789ff-aa15-4a28-b9fc-05a8fcdb18be/eUhRVWlHS0/928c112c-17fd-4d3c-a250-94f4941fd188.png", "video-url": null, "url": "https://fosdem.org", "name": "FOSDEM"}, "id": "1", "relationships": {"event": {"links": {"self": "/v1/exhibitors/1/relationships/event", "related": "/v1/exhibitors/1/event"}}, "sessions": {"links": {"self": "/v1/exhibitors/1/relationships/sessions", "related": "/v1/exhibitors/1/sessions"}, "data": []}}, "links": {"self": "/v1/exhibitors/1"}}, "links": {"self": "/v1/exhibitors/1"}, "jsonapi": {"version": "1.0"}}`

This is the correct response in which I  can see the contact-email (or contact, as contact was renamed to contact-email) column. And in below response I am not seeing that. 

`{"banner_url": "https://api.eventyay.com/static/media/exhibitors/42/large/cnVySGtWVk/b0b21407-80ca-49c8-98a5-95a8e4196d79.jpg", "social_links": [{"link": "https://www.microsoft.com", "is_custom": false, "name": "website"}, {"link": "https://twitter.com/Azure", "is_custom": false, "name": "twitter"}, {"link": "https://github.com/Microsoft", "is_custom": false, "name": "github"}], "id": "42", "slides_url": "https://api.eventyay.com/static/media/events/temp/7170c1bd-0188-4777-8ccc-2873e10f05c0/bjJSTkFwOX/a3cff304-c3b9-4536-8337-040232b72cfd.pdf", "position": 1, "thumbnail_image_url": "https://api.eventyay.com/static/media/exhibitors/42/thumbnail/NHdXUFFnTm/8ebff0c0-941b-4bd3-b9d7-6dc3cb7d6d99.jpg", "status": "accepted", "event": {"links": {"self": "/v1/exhibitors/42/relationships/event", "related": "/v1/exhibitors/42/event"}}, "contact_link": "https://support.microsoft.com/en-sg/contactus", "description": "<p>Open. Collaborative. Flexible.</p><p>Open Source enables Microsoft products and services to bring choice, technology and community to our customers.\u00a0<a href=\"https://opensource.microsoft.com/\" rel=\"nofollow\" target=\"_blank\">https://opensource.microsoft.com/</a></p><p></p><p><strong>Meet Microsoft team here Wed 17 March at 12:00 pm (SGT)</strong></p>", "enable_video_room": true, "sessions": {"links": {"self": "/v1/exhibitors/42/relationships/sessions", "related": "/v1/exhibitors/42/sessions"}}, "logo_url": "https://api.eventyay.com/static/media/temp/images/89f0aa08-ffae-4d3c-9d72-93ba2563d226/S3phTS9Lcn/b8adc044-3d50-4b1a-894c-89fb762040c1.png", "video_url": "https://www.youtube.com/watch?v=N_799Yu3k_w", "url": "https://www.microsoft.com", "name": "Microsoft", "jsonapi": {"version": "1.0"}}`

More info In the migration revision = '6f68fb58f228'

**Comment by maze-runnar** [comment]
please check this on production server.

**Comment by maze-runnar** [comment]
`contact-email` is missing from here too, which is causing error - 
`{"banner_url": "https://api.eventyay.com/static/media/exhibitors/11/large/R3lkdUtwTS/faa36342-f2d9-46e3-b66f-8bf73a362c0f.jpg", "social_links": [{"link": "https://www.theglassroom.org", "is_custom": false, "name": "website"}, {"link": "https://twitter.com/Info_Activism", "is_custom": false, "name": "twitter"}, {"link": "https://facebook.com/Tactical.Tech", "is_custom": false, "name": "facebook"}, {"link": "https://github.com/tacticaltech", "is_custom": false, "name": "github"}, {"link": "https://youtube.com/user/TacticalTechVideos", "is_custom": false, "name": "youtube"}], "id": "11", "slides_url": "https://api.eventyay.com/static/media/events/temp/960730a3-cff1-45c9-8d31-9347aecb3205/ZGk5bW1sK0/90d58c14-a5c6-4683-ac76-c67ec6969c64.pdf", "position": 21, "thumbnail_image_url": "https://api.eventyay.com/static/media/exhibitors/11/thumbnail/cERxNWlTST/549e555c-abfe-4000-afc0-21109fa69da4.jpg", "status": "accepted", "event": {"links": {"self": "/v1/exhibitors/11/relationships/event", "related": "/v1/exhibitors/11/event"}}, "contact_link": null, "description": "<strong>Tactical Tech\u2019s newest edition of The Glass Room Community Edition explores misinformation in all its forms.<br> <br></strong>In this exhibition \u2013 aimed at young people as well as adults \u2013 we explore how social media and the web have changed the way we read information and react to it. Learn why finding \u201cfake news\u201d is not as easy as it sounds, and how the term \u201cfake news\u201d is as much a problem as the news it describes. Dive into the world of deep fakes, which are now so realistic that they are virtually impossible to detect. And find out why social media platforms are designed to keep us hooked, and how they can be used to change our minds.", "enable_video_room": true, "sessions": {"links": {"self": "/v1/exhibitors/11/relationships/sessions", "related": "/v1/exhibitors/11/sessions"}, "data": []}, "logo_url": "https://api.eventyay.com/static/media/temp/images/29b1f486-4965-4412-912b-c88b47df2705/RWxxYkJISj/a981ed4f-9159-4001-ab62-072c9dfb3e0e.png", "video_url": "https://www.youtube.com/watch?v=nl9yjjp3Zs0", "url": "https://tacticaltech.org", "name": "The Glass Room: Misinformation Edition ", "jsonapi": {"version": "1.0"}}`

**Comment by sachinchauhan2889** [comment]
@mariobehling @maze-runnar @MeghalBisht @ranjitkshah 

This issue is debuged.

- Before 15 feb:
Exhibitor have a column named contact(string type).
Users were not sure about this field. Some users fill emails in this. Those who fill emails are working fine. But others filled website or any other contact methods here.

- On 15 feb
 https://github.com/fossasia/open-event-server/pull/7745 PR changes contact(string) to contact_email(string).
After this PR all exhibitors are working fine. But in backend, contact_email is bounded with string type. Contact_email still contains emails, links and other contact methods. Everything is working fine since these all are of string type.
- On 20 april 
https://github.com/fossasia/open-event-server/pull/7911 PR changes `field type` of contact_email  from `string` to `email`.
- Now
 Exhibitors who have emails in contact_email field are loading fine. But those exhibitors who filled non-email contact info before 15 feb are not loading because now flask want them to be email.

So this is the cause of error.

**Solution is to set contact_email as null if email is not present.** 
**ways:** 

- [ ] Manually.
- [ ] Migration.

**Comment by MeghalBisht** [comment]
>  [ ] Migration 
would be a better option.

**Comment by MeghalBisht** [comment]
Solved by manually editing the production DB.

**Comment by sachinchauhan2889** [comment]
Manually done.
