### ISSUE TITLE
Verification Email is sent to SPAM 

### ISSUE THREAD

**Issue by abhaysinghs772** [fossasia/open-event-frontend#7250]
**Describe the bug**

Verification email is sent to Spam while signing up for the first time or as a new user

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/login
2. register as a new user
3. See error

**Expected behaviour**
verification email should be sent into Inbox rather then into Spam

**Screenshots**

**Desktop (please complete the following information):**
![1](https://user-images.githubusercontent.com/67998122/117512628-980b1c00-afad-11eb-9859-f7d692a6b96c.png)

![2](https://user-images.githubusercontent.com/67998122/117512659-aa855580-afad-11eb-8684-0f7ae043b302.png)

![4](https://user-images.githubusercontent.com/67998122/117513016-634b9480-afae-11eb-8586-84ba79ead2ea.png)

Desktop
 - OS: [Windows 10]
 - Browser [Chrome,]

**Comment by mariobehling** [comment]
This is out of scope. Email providers need to improve their spam filters.
