### ISSUE TITLE
Popup: show popup ui message in overview page of copy and share icon.

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#7282]
**Describe the bug**
in overview page copy and share icon should show popup ui message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'eventay.com/mange events/overview page of your event '
2. hower on 'copy and share icon'
3. See error

**Expected behaviour**
should show poupup message.

**Comment by iamdevvalecha** [comment]
The popup:-

![Screenshot from 2021-05-16 19-32-32](https://user-images.githubusercontent.com/71969867/118400038-9b716800-b67d-11eb-9cd6-f6cd34cc0178.png)

**Comment by MeghalBisht** [comment]
Which page? 
Also which copy & share icon?

**Comment by maze-runnar** [comment]
he is talking about url-box.

**Comment by MeghalBisht** [comment]
> And hover pop up is not also the expected beaviour I guess.
 
Correct. That is obvious. Therefore closing.

**Comment by iamdevvalecha** [comment]
okay thanks!
