### ISSUE TITLE
Payment Gateway: Implement Amazon Pay as it's Used World Wide

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#7292]
https://developer.amazon.com/docs/amazon-pay/intro.html
Intregate amazon pay in eventyay website so, that it gets more easier to buy tickets as it's used world wide.

**Comment by klsingh016** [comment]
can i work on this ?

**Comment by iamdevvalecha** [comment]
> can i work on this ?
please @klsingh016 stop spaming on every issue. it's a request. i told u in morning if u really wanna work please find the issue u know how to solve. otherwise it will create mess everywhere. i came to know @MeghalBisht di also told not to spam. please stop.
thank you!

**Comment by klsingh016** [comment]
oookkkayy ji

**Comment by mariobehling** [comment]
This is out of scope right now and Stripe is partnering with Amazon. So, we will be able to get support through Stripe anyways. Therefore closing it.
