### ISSUE TITLE
Subtotal not updating after changing price for supporter ticket

### ISSUE THREAD

**Issue by suyash-patil** [fossasia/open-event-frontend#7293]
**Describe the bug**
Subtotal of the Supporter Ticket not updating on changing the price. Instead one has to change quantity to 0 and then again to 1 so that it gets updated.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com
2. Go to any event.
3. Scroll down to Tickets section.
4. Set supporter ticket quantity to 1.
5. Change the Price.
6. See the bug.

**Expected behaviour**
It should automatically change to the correct price

**Screenshots**
![image](https://user-images.githubusercontent.com/66873825/118636074-eca26880-b7f1-11eb-8654-ee5477f3631c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by iamdevvalecha** [comment]
@suyash-patil what do you mean by?
5.change the price?

**Comment by suyash-patil** [comment]
![image](https://user-images.githubusercontent.com/66873825/118644674-ae11ab80-b7fb-11eb-8f8a-6c4807aaf3e4.png)

@iamdevvalecha If user changes the price of the ticket (by clicking the up/down arrow or manually) then the subtotal not gets updated.

**Comment by iamdevvalecha** [comment]
@suyash-patil i am wondering how a user can change price of the ticket 😕 ???

**Comment by suyash-patil** [comment]
@iamdevvalecha Yes, the supporter price can be changed.

**Comment by iamdevvalecha** [comment]
yes! thank you.

**Comment by suyash-patil** [comment]
https://user-images.githubusercontent.com/66873825/118701375-45ddbc80-b831-11eb-97f9-599a2ba9e8e1.mp4

Here is the reproduction of the bug.

**Comment by iamdevvalecha** [comment]
@mariobehling @SundaramDubey

**Comment by mimidotsuser** [comment]
seems  like the calculation trigger function is only called when keyup event is fired

 https://github.com/fossasia/open-event-frontend/blob/65c328b592e1edef23fc7ae9d99af37623e64a4c/app/templates/components/public/ticket-list.hbs#L47

**Comment by iamdevvalecha** [comment]
@mimidotsuser please send pr.
