### ISSUE TITLE
Video: Integrate Google meet as video channels.  

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#7295]
Google Meet In Currently Not Implemented. In Eventyay website. please  implemented this feature.
https://developers.google.com/admin-sdk/reports/v1/appendix/usage/customer/meet

**Comment by mariobehling** [comment]
It is only possible to join Google Meet events for users who have a Google account. This is different to all other services that we currently support. We want to avoid people to be locked in and already have good alternatives to Google Meet implemented. Therefore closing it.
