### ISSUE TITLE
Session: increment/decrement fav count on adding a session to schedule

### ISSUE THREAD

**Issue by iamdevvalecha** [fossasia/open-event-frontend#7299]
Error while adding session to my schedule.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'eventyay.com'
2. Click on 'any event with some schedule'
3. Click on circle icon to add session to my schedule

**Expected behaviour**
it should be updated automatically without any refresh.

**Screenshots/Screen-Record**

https://user-images.githubusercontent.com/71969867/118783967-356b2780-b8ad-11eb-9ea8-094b8f85e5d0.mp4

**Comment by MeghalBisht** [comment]
Works fine in Chrome & Firefox.
Why are you manually pressing reload?

**Comment by mimidotsuser** [comment]
@MeghalBisht  I am able to replicate this.
Marking a session schedule as favorite does not increment the count. Also applies to undo action. 

![Screenshot from 2021-05-19 21-11-46](https://user-images.githubusercontent.com/25152892/118864934-2013ee80-b8e9-11eb-96bb-41e0fa31bda7.png)

The count is tied to `favouriteCount` property of `session` model.  Favouriting a schedule is done under `UserFavouriteSession` model & route. Thus the behavior is expected

**Comment by iamdevvalecha** [comment]
@mimidotsuser i will discuss this tommorow in meeting!

**Comment by mariobehling** [comment]
This feature was not intended to work immediately. It actually works, but it only shows up a bit later on the site. This was the best implementation we could get considering we also want to have some caching. We can always improve this feature on the next version of the frontend. Fav count will actually increase, but it will not increase immediately. Therefore the feature can be considered working within the goals we have for now. So, I am closing this issue. Thanks.
