### ISSUE TITLE
Order Process: Order steps are missing tax information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7308]
When a user makes an order that has a tax, the tax amount is only shown in the first step of the order (the actual event page). Expected is that the amount is shown in the same way in consequent steps and the final order page.

Please implement it in the same way as it is on the event page. Please understand that there are two ways to add tax a) include the tax and b) add the tax on top. The organizer has the choice to control this in the wizard step 1.

**1) See original start page with tax amount**

![Screenshot from 2021-05-20 11-02-42](https://user-images.githubusercontent.com/1583873/119053518-74d96700-b9c6-11eb-8665-c1f2cb14816a.png)

**2) Tax is set in the wizard step 1**

![Screenshot from 2021-05-20 11-57-34](https://user-images.githubusercontent.com/1583873/119053427-57a49880-b9c6-11eb-9426-2a92a7042a14.png)

**3) Also implement it in the same way in consquent order pages, please.**

![Screenshot from 2021-05-20 11-04-10](https://user-images.githubusercontent.com/1583873/119053432-583d2f00-b9c6-11eb-9cd8-1826890cc031.png)
![Screenshot from 2021-05-20 11-03-27](https://user-images.githubusercontent.com/1583873/119053433-583d2f00-b9c6-11eb-845b-42a798c5e34b.png)

**Comment by iamdevvalecha** [comment]
on it.

**Comment by iamdevvalecha** [comment]
on it.
