### ISSUE TITLE
Authentication Text Interface does not matches

### ISSUE THREAD

**Issue by gauravsinhaweb** [fossasia/open-event-frontend#7330]
**Describe the bug**

Login and Register Text Interface have a different cursor property while hovering on it.

**To Reproduce**
1. Go to 'Log in'
2. Hover on 'Login Text'
3. Click on 'New to site? Create Account
4. Hover on 'Register Text'

**Expected behavior**

while hovering over 'Login' and 'Register', Text Interface should have the same CSS cursor property i.e. "cursor:  text".

**Screenshots**

![asasasa](https://user-images.githubusercontent.com/75125943/119435908-c1130700-bd38-11eb-9762-0754dabe55f3.PNG)
![ddddddd](https://user-images.githubusercontent.com/75125943/119435912-c5d7bb00-bd38-11eb-8908-8cee49ac7e68.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: 90.0.4430.212

**Comment by Priyaraj17** [comment]
Hey, Make I work on this issue?

**Comment by gauravsinhaweb** [comment]
@Priyaraj17  yes

**Comment by MeghalBisht** [comment]
Low priority
