### ISSUE TITLE
Enable moderators of an event to access the event without getting a ticket

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7334]
Currently moderators also need a ticket to access an event. In contrast speakers do not need a ticket. While others systems handle this similarly users report that this is confusing them. Therefore please change it as follows:
* When accounts are invited as moderators they do not need a ticket to access the event and video rooms
* In the email that moderators receive please add the following sentence: "Moderators will get access to the event automatically. You do not need to get an additional ticket to access the event and moderator privileges."

**Comment by maze-runnar** [comment]
As discussed permission issues are compliceated to implement right now.
