### ISSUE TITLE
Add Event "Documents" to the system

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7335]
1. Add a "Documents" item in the organizer menu behind "Chat" and in front of "Exhibitors"
![Screenshot from 2021-05-25 23-46-54](https://user-images.githubusercontent.com/1583873/119573552-b9914380-bdb4-11eb-944e-933cf690979f.png)

2. On the page show a switch on/off button to enable or disable the feature
- When enabled show a) a field to give the document a name and b) show an upload button
- Provide the option to upload as many documents as the user wants
- Show an x icon behind documents to enable the user to delete the document
3. On the finished orders page of an event show above the "Payee" box show a box "Event Documents" with the documents the organizer uploaded. Only show this box if the organizer has activated that feature and uploaded documents.
![Screenshot from 2021-05-25 23-52-55](https://user-images.githubusercontent.com/1583873/119573398-7c2cb600-bdb4-11eb-8f1b-b1237176462a.png)

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by rajdama** [comment]
Hi can you assign this to me, I can do it.

**Comment by iamdevvalecha** [comment]
@rajdama so please send pr. we don't assign issues.

**Comment by rajdama** [comment]
@iamdevvalecha ok I will send it.

**Comment by rajdama** [comment]
Can you please help me to locate this page on fossasia website.

**Comment by iamdevvalecha** [comment]
@rajdama use ember inspector.

**Comment by rajdama** [comment]
@iamdevvalecha Hey can you help me a bit as I am new to open source I am facing some issues, it would be great if you could help me.

**Comment by iamdevvalecha** [comment]
@rajdama join https://gitter.im/fossasia/open-event-frontend this channel & we have weekly meeting on tuesday you can ask doubts.

**Comment by rajdama** [comment]
Thankyou !
