### ISSUE TITLE
Add download icon on the "Downoad invoice" Button

### ISSUE THREAD

**Issue by rajkumar100** [fossasia/open-event-frontend#7339]
**Describe the bug**
there is no download icon on the "Download invoice" Button plz change to download icon see in the screesnhot.

**Screenshots**
![bug 1](https://user-images.githubusercontent.com/84830821/119616241-01988080-be1e-11eb-9231-bb139d63475a.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
@mariobehling can you plz review or  add the codeheat label for this

**Comment by Raunaksingh100** [comment]
i am working on this issue

**Comment by rajkumar100** [comment]
go ahead!

**Comment by mariobehling** [comment]
This icon was chosen in order to differ from the button with the download icon next to it. Therefore closing this.
