### ISSUE TITLE
Enable recording for previously created events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7341]
Ensure recording is enabled and possible for the following events

1. - https://eventyay.com/e/ee5ba54b
2. - https://eventyay.com/e/e5718a94
3. - https://eventyay.com/e/881164f1
4. - https://eventyay.com/e/2fde0ada
5. - https://eventyay.com/e/04e3c470
6. - https://eventyay.com/e/432b66de
7. - https://eventyay.com/e/142b6187
8. - https://eventyay.com/e/f8f498f1
9. - https://eventyay.com/e/15603d0d
10. - https://eventyay.com/e/1fcf565c
11. - https://eventyay.com/e/c5fc6d42
12. - https://eventyay.com/e/157024a9

**Comment by faisalkhandholpur** [comment]
i can handle 7341 issue so please assign me this issue

**Comment by sachinchauhan2889** [comment]
manually done.
