### ISSUE TITLE
Create BBB recordings overview for admins and enhance admin video area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7345]
* Change admin/video-channels. It should be admin/video/
* Create sub slug admin/video/channels and move current video channel info here
* Create sub slug admin/video/recordings and a table with the following overview of videos
   * Thumbnail (linking to video presentation page | Delete
   * Event Name (below icon links to a) Dashboard and b) View linking to public event page)
   * Owner (Show the event owner name and email here)
   * Length
   * Number of Participants
   * Start Time
   * End Time
   * Visibility
   * Video channel (Show the info which video channel the video is using. Right now we only offer BBB)
* When the user accesses admin/video automatically direct the user to admin/video/recordings

The above info is already available on BBB. Compare Greenlight screenshot below.

![Screenshot from 2021-05-26 19-49-50](https://user-images.githubusercontent.com/1583873/119707801-d92f7700-be5b-11eb-9819-03331d72531a.png)

**Comment by sandeep9889** [comment]
i want work on this issue

**Comment by ranjitkshah** [comment]
left:
recording delete part
