### ISSUE TITLE
Implement the tickets API on the add orders route.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#735]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
![addorder](https://user-images.githubusercontent.com/17925669/29359432-427e2724-829c-11e7-88d1-fc6ef6d78655.png)

**Comment by sumedh123** [comment]
Will be working on this.

**Comment by sumedh123** [comment]
@niranjan94 @geekyd @CosmicCoder96 The above image has a continue button which is disabled as per following condition:
```
<div class="eight wide column right aligned">
        <button class="ui blue button" disabled={{not hasTicketsInOrder}} {{action 'createOrder' paymentType}}>
          {{t 'Continue'}}
        </button>
</div>
```
What is the 'hasTicketsInOrder' condition? I did not understand it logically. In my case the button is always disabled.

**Comment by geekyd** [comment]
@sumedh123 We need to disable the continue button, if there is no order i.e the user has not entered a non zero quantity to any ticket. if total quantity is 0 then the button should be disabled. Hope this helps :)
