### ISSUE TITLE
Message when trying to create an event with a non verified account is not helpful

### ISSUE THREAD

**Issue by marcoag** [fossasia/open-event-frontend#7357]
**Describe the bug**

When creating an event with an account that has not verified the email the message shown is:
"Unknown Error has occurred."

This is very confusing for the user as it doesn't know what to do and it will think it's just the system that is not working. Instead a more informative message should be shown:

"Please confirm the verification email before creating an event"

It would even be better if an option to resend the verification email is shown, but this might be entail more work. I guess changing the message is already a first step in the right direction.

**To Reproduce**
1. Create a new Account 
2. Create a new Event 
3. Message is shown up and the user won't know what's the problem

**Expected behavior**
A more detailed message should be shown, like:
"Please confirm the verification email before creating an event"

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox
 - Version 88.0.1 (64-bit)

**Comment by anshika-web** [comment]
@marcoag can i work on this?

**Comment by marcoag** [comment]
Please go ahead, should be a fast fix ;)

**Comment by iamdevvalecha** [comment]
@marcoag it's working absolutely fine in eventyay as well as in my localhost

**Comment by iamdevvalecha** [comment]
here's the sr.
https://user-images.githubusercontent.com/71969867/120150946-4f8bfa80-c209-11eb-9a05-079bae65336f.mp4

**Comment by iamdevvalecha** [comment]
@marcoag sir,can you please attach the ss.

**Comment by iamdevvalecha** [comment]
@iamdevvalecha @marcoag can you please guide how to do this?

**Comment by anshika-web** [comment]
@marcoag @iamdevvalecha can you please guide how to do this?

**Comment by MeghalBisht** [comment]
> here's the sr.
> https://user-images.githubusercontent.com/71969867/120150946-4f8bfa80-c209-11eb-9a05-079bae65336f.mp4

The steps say to create a new event. Where did you create it? Create an event refers to publish an event.

**Comment by iamdevvalecha** [comment]
@MeghalBisht thanks, now able to reproduce.
