### ISSUE TITLE
Dropdown icon to the event creation steps to make it more user friendly

### ISSUE THREAD

**Issue by progmatic-99** [fossasia/open-event-frontend#7384]
So, right now in the event creation steps, on smaller screen sizes, it is hard to guess how to move between different steps and the dropdown is not easily recognizable.
![ss_1622637706](https://user-images.githubusercontent.com/42090582/120643668-11eed200-c494-11eb-8b4f-7610e1ed1f5c.png)

**Solution**
Add a dropdown icon, so that the UI becomes more user friendly and it is obvious that the dropdown is there.
Something like this:-
![ss_1622722492](https://user-images.githubusercontent.com/42090582/120643883-4f535f80-c494-11eb-9341-e2ec9b37e938.png)

PS:- I have a PR ready, if this is required.

**Comment by mariobehling** [comment]
Yes, please make a PR.

Also please change the box item on the lower second box from "Team" to "Team Members".

**Comment by iamdevvalecha** [comment]
@mariobehling @progmatic-99 working on this.

**Comment by progmatic-99** [comment]
@iamdevvalecha I mentioned in the issue itself, that i have a PR ready for this. :(

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?

**Comment by MeghalBisht** [comment]
> @iamdevvalecha I mentioned in the issue itself, that i have a PR ready for this. :(

@iamdevvalecha  From the next time, please only take up issues which are already occupied **after** 24 hours have passed and no update is provided by the previous commenter. I see @progmatic-99 already commented with the issue body. 😄
