### ISSUE TITLE
A star rating of a session by an organizer should be visible to the organizer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7386]
After a user added the rating the ratings of the user should be visible to the user. So the number of stars the user gave here should be highlighted. This is not yet the case.

![Screenshot from 2021-06-03 21-46-15](https://user-images.githubusercontent.com/1583873/120703218-4c1c9b80-c4b5-11eb-984e-e7b72841dab2.png)

**Comment by iamdevvalecha** [comment]
on it.

**Comment by iamdevvalecha** [comment]
@mariobehling i need more info for this issue.

**Comment by maze-runnar** [comment]
Not able to reproduce. I am seeing my given rating for any session.

**Comment by maze-runnar** [comment]
if any one reproduces this feel free to open


![Screenshot from 2021-06-16 22-05-10](https://user-images.githubusercontent.com/56407566/122259044-58f6b180-ceef-11eb-8370-d600d9a83d1b.png)
