### ISSUE TITLE
Substitute text with "eventyay" to use "[app name]"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7395]
In the process of refining the system we have created different text and we have used 'eventyay' in some strings instead of "app name" which is set in https://eventyay.com/admin/settings. Please find any reference to eventyay in the system and change it to use the "app name" set by the administrator.

Please test and ensure that the app name is shown instead of html or other code for the user.

**Comment by rajdama** [comment]
I can do it

**Comment by Abhicodes-crypto** [comment]
Hi, @mariobehling  I would like to work in this.

**Comment by iamdevvalecha** [comment]
@Abhicodes-crypto please send pr
