### ISSUE TITLE
Integrate the event copy API.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#742]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

To be done:
Implement the event copy API.

**Comment by sumedh123** [comment]
Will be working on this.

**Comment by sumedh123** [comment]
@niranjan94 For the event-copy api, we have to make a post request to the endpoint
```
/v1/events/{identifier}/copy
```
And the request body as given in docs is something like:
![event-copy](https://user-images.githubusercontent.com/17925669/29483594-2f2478f4-84c7-11e7-9ee9-59f7deff74de.png)
I am little confused that do we have to use the ember data method or the loader method. We are having the JSON formatted response. If we use the ember data method, what should be sent as the request body since the docs specify only the "data-type": "event-copy". Shall I just have an empty model?

**Comment by sumedh123** [comment]
@geekyd @CosmicCoder96 Your opinions on the above thing?

**Comment by niranjan94** [comment]
@sumedh123 the API endpoint is weird. Needs to be changed. Should be a simple `POST /v1/events/{identifier}/copy` without any body. Please open a server issue for it.
