### ISSUE TITLE
CFS: Not able to turn ON cfs for my event

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#7431]
Not able to turn ON cfs for my event

https://user-images.githubusercontent.com/72552281/121807143-939ee680-cc70-11eb-9d55-bee1a261f67f.mp4

**Comment by MeghalBisht** [comment]
It is because of the empty announcement message.

**Comment by mariobehling** [comment]
We need an error message or something to indicate this for the user.

**Comment by maze-runnar** [comment]
I think we should just add an helper text, that `you need to add announcement to enable call for speakers` something like this.
or just check is_cfs_enables https://github.com/fossasia/open-event-server/pull/7997
