### ISSUE TITLE
Only show "Level" widget if session have level option

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7434]
Currently the level widget also shows up if the level form field is not activated in the wizard. Please only show the level widget on the public event page, if levels are available.

Compare https://eventyay.com/e/82d2e0f2/schedule

![Screenshot from 2021-06-14 14-08-38](https://user-images.githubusercontent.com/1583873/121890692-e9c86400-cd1a-11eb-9dcd-69cc1150fd5b.png)

**Comment by pc-beast** [comment]
working on it.
