### ISSUE TITLE
E-mail confirmation and resend not working. I am not getting any e-mail for confirmation of my Gmail to book tickets

### ISSUE THREAD

**Issue by SnehaSah2204** [fossasia/open-event-frontend#7464]
**Describe the bug**
I am not receiving a confirmation E-mail on my registered e-mail id to.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/
2. Sign up as a new user
3. scroll down and click on an event
4. It will show - Your account functionality is limited. To get full access to all features you need to verify your email by clicking on the confirmation link that has been emailed to you.
5. error-we do not receive any email.
6. By clicking on please click here to resend the confirmation Email it says that Confirmation mail has been sent again successfully!  but still sends no E-mail.

**Expected behaviour**
It should send a confirmation e-mail to confirm the user and let the user book tickets.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SnehaSah2204** [comment]
I would like to work on this Issue.

**Comment by SahilSunda** [comment]
@SnehaSah2204 yeah go on, and if you need any help then please text me, I was also looking for some issues here but didn't get any. So if possible then please.

**Comment by MeghalBisht** [comment]
@SnehaSah2204 It works fine. Check you spam or any potential email blockers that you might have enabled.

**Comment by iamdevvalecha** [comment]
works fine check spam.

**Comment by MeghalBisht** [comment]
Closing as it is working. Reopen to continue the discussion.
