### ISSUE TITLE
Error in Readme.md

### ISSUE THREAD

**Issue by khanjasir90** [fossasia/open-event-frontend#7475]
cp .env.example .env does not work for Windows!
![1](https://user-images.githubusercontent.com/53305380/122966091-88516680-d3a6-11eb-9aa9-cbea03e9f39e.JPG)
copy .env.example .env works for Window!!!

**Comment by khanjasir90** [comment]
can i work on this fix!

**Comment by MeghalBisht** [comment]
We recommend using linux. Also, this can be easily looked up! Hence, closing
