### ISSUE TITLE
Redirect users to /create after log in

### ISSUE THREAD

**Issue by hkumar0132** [fossasia/open-event-frontend#7483]
**Is your feature request related to a problem? Please describe.**
User visits the website (eventyay.com) and clicks on `Create Event`. If they are not logged in, they are redirected to the `/login` route. After they log in, they are redirected to `/`. I think it's better if they are redirected to `/create` instead of `/` at this point.

**Describe the solution you'd like**
If the user clicked `Create Event` and they are not logged in, maintain some sort of global state to track this and when they log in, check if this state exists. If it does, redirect them to `/create`

**Additional context**
After I click login, I should be redirected to the `/create` page.
![Screenshot (356)](https://user-images.githubusercontent.com/63600554/123390221-4c8deb00-d5b8-11eb-96fb-7325c659f795.png)

**Comment by hkumar0132** [comment]
@mariobehling I would like to work on this issue if it helps improves the project.

**Comment by Shubham56-droid** [comment]
i would like to work on this issue.

**Comment by hkumar0132** [comment]
@Shubham56-droid Let me know if you are working on it or I will take it
