### ISSUE TITLE
Do not refresh if language selected is same as before

### ISSUE THREAD

**Issue by hkumar0132** [fossasia/open-event-frontend#7484]
**Is your feature request related to a problem? Please describe.**
If language is set to English and if I choose English from the dropdown, it refreshes the page and runs the `switchLanguage` function again, which is unnecessary.

**Describe the solution you'd like**
I would like to add an edge case that does not allow page refresh and return from the `switchLanguage` function if the newly selected language is the same as before.

**Additional context**
If I select English like in the below screenshot, it refreshes the page.
![Screenshot (358)](https://user-images.githubusercontent.com/63600554/123427923-d9e63500-d5e2-11eb-9ee1-97e874b32cb0.png)

**Comment by hkumar0132** [comment]
Please let me know if I can work on this issue.

**Comment by MeghalBisht** [comment]
> Please let me know if I can work on this issue.

Yes

**Comment by hkumar0132** [comment]
Thank you, working on it.

**Comment by hkumar0132** [comment]
#7496
