### ISSUE TITLE
Follow group button overlapping on event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7497]
Please move the "Follow Group" button widget to the right bottom of the sidebar for now and avoid that it overlaps with other UI elements.

![Screenshot from 2021-06-30 10-47-49](https://user-images.githubusercontent.com/1583873/123931895-39509600-d991-11eb-8f32-8800698e7223.png)

**Comment by iamdevvalecha** [comment]
on it.
