### ISSUE TITLE
Implement Orders API to orders/new route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#750]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Comment by pradeepgangwar** [comment]
I am working on this

**Comment by pradeepgangwar** [comment]
@CosmicCoder96 @niranjan94 While implementing this, I was unable to create a temporary order. I went through its implementation at eventyay and found that once we select quantity of tickets and proceed to order we are given a temporary order id and we have option to complete purchase in 10 minutes. 
However current implementation asks for city, country, zipcode, discount code etc for creating an order, but when we are on public (e/{event_identifier}) route we only have the option to select ticket quantity and proceed to checkout where we fill other details. IMO we should be able to create a ticket with pending status with relationship to tickets. Then on checkout we can complete that order if user fills in details within 10 minutes.

**Comment by CosmicCoder96** [comment]
The orders and payment integration is complete via the referenced PRs.
