### ISSUE TITLE
Simplify the admin sales page 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7539]
The sales page at https://eventyay.com/admin/sales/ has unused functionalities and pages that are not working as expected. We can simplify this as follows:

* Delete the left sidebar and its unsused pages (organizer, location, marketer, discounted events, revenue)
* To the Tickets Summary Page:
   * add column "Owner" show the name of the event owner here and link to the owner profile
   * Add column "Type" and show info if the event is on-site, online, hybrid or tbd
* Make the table columns sortable

**Comment by Deepak-032** [comment]
I am not able to access the page given in the link above. i.e. https://eventyay.com/admin/sales/

**Comment by MeghalBisht** [comment]
> I am not able to access the page given in the link above. i.e. https://eventyay.com/admin/sales/

Since you don't have admin rights on `eventyay.com` , you need to run the server locally in order to view admin pages.
