### ISSUE TITLE
Make Admin Groups page columns sortable and add column "Followers"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7541]
1. Currently the column "Owner" and "Number of Events" are not sortable on the groups admin page at https://eventyay.com/admin/groups/live. Please implement the sorting functionality.

2. Also implement a column "Followers" and show the number of followers of this group in the column.

**Comment by ranjitkshah** [comment]
looking

**Comment by sachinchauhan2889** [comment]
looking
