### ISSUE TITLE
Groups box on admin start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7542]
On the admin start page at https://eventyay.com/admin information in regards to groups is missing. Therefore please add a "Groups" box and include the following information on that page:

- Number of Groups: xx
- Number of Group Events: xx
- Number of All Followers: xx

![Screenshot from 2021-07-09 19-00-47](https://user-images.githubusercontent.com/1583873/125113049-636c2b80-e0e8-11eb-93ae-827019adb0a0.png)

**Comment by ranjitkshah** [comment]
looking
