### ISSUE TITLE
Add some space above the tickets buttons on the create event route.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#755]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![basic-details](https://user-images.githubusercontent.com/17925669/29485144-9e2cc7b0-84ea-11e7-9bad-5eedf9ea6079.png)

**Expected behavior:**
Add some space above the buttons so that they don't stick to the above section.

**Comment by sumedh123** [comment]
Working on this.

**Comment by CosmicCoder96** [comment]
Closing this as per discussion in https://github.com/fossasia/open-event-frontend/pull/725#discussion_r133110937
