### ISSUE TITLE
Groups Edit Page: Add "View" button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7586]
Add a "View" button same as on the organizer event pages to the groups edit pages on the top right. Open it on a new tab.

![Screenshot from 2021-07-20 13-32-40](https://user-images.githubusercontent.com/1583873/126317190-6af01eac-f9e5-4738-9c31-4838bf80f7e4.png)

![Screenshot from 2021-07-20 13-32-00](https://user-images.githubusercontent.com/1583873/126317210-a219a240-b61e-482f-a811-4e6631e494fc.png)

**Comment by deo002** [comment]
looking
