### ISSUE TITLE
Search: Move search field to top on search pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7587]
Please move the search field to the top of the search page, but keep it expanded on that page.

![c4](https://user-images.githubusercontent.com/11625672/102060567-5c15c580-3e18-11eb-8a45-eaf3ffb14d38.JPG)

**Comment by emily876** [comment]
Hello @mariobehling, can I work on this issue !!

**Comment by MeghalBisht** [comment]
> Hello @mariobehling, can I work on this issue !!

Yes! Feel free to open a PR

**Comment by emily876** [comment]
Thanks👍🏻

**Comment by emily876** [comment]
Hi @MeghalBisht, I'm not able to locate the file, being new to this. Is this is the path ...
app/components/tables/utilities/search-box.js
Please guide me a bit !!

**Comment by Atharvshukla** [comment]
Hello, @mariobehling @MeghalBisht   Can I work on this issue.

**Comment by Atharvshukla** [comment]
Hello @mariobehling @MeghalBisht  ,
while working on this issue I have reached to this level and brought the Search field in the desired location In the search page and also able to expand it but I am stuck on one thing that is as I have tried to make changes in the navbar file i.e all other pages also now having an extra Search field . I am attaching both the images  and I will be overwhelmed if you can guide me on this how further I can remove the extra search field and have only in the Explore page.

image 1-
![Screenshot 2021-07-27 at 12 00 40 AM](https://user-images.githubusercontent.com/38507802/127040940-7e703a66-ed43-4099-a7e8-f358604dc5cd.png)
 image 2
![Screenshot 2021-07-27 at 12 01 44 AM](https://user-images.githubusercontent.com/38507802/127041866-90ffddb9-38a3-4cf7-bb2f-b0cb01219d2a.png)

**Comment by maze-runnar** [comment]
the search field would be shifted only be on explore page, not everywhere.

**Comment by ayushcse042** [comment]
looking
