### ISSUE TITLE
Search: Add option to search for Groups

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7588]
On meetup.com a user can search either for events on the calendar or for groups.

Please implement such a search filter option on the search page https://eventyay.com/explore of eventyay as well. Enable the user to search either for events or for groups. Change the left side bar accordingly and show the date option to display all groups with e.g. past and future events etc.

Ensure that the search box adheres to the filter set when performing a new search.

![Screenshot from 2021-07-20 14-00-04](https://user-images.githubusercontent.com/1583873/126320492-dfdfe208-54ac-43ac-bb00-301b88b30e01.png)

![Screenshot from 2021-07-20 14-03-09](https://user-images.githubusercontent.com/1583873/126320596-d6937049-4801-4b6f-9b4e-cab6a2f256fb.png)

**Comment by sachinchauhan2889** [comment]
looking
