### ISSUE TITLE
session: scheduler not working for some browsers or devices

### ISSUE THREAD

**Issue by ranjitkshah** [fossasia/open-event-frontend#7616]
**Describe the bug**
scheduler not working as expected for some browsers or devices

**To Reproduce**
Steps to reproduce the behaviour:
1. create event
2. add some sessions
3. go to scheduler

**Expected behaviour**
 should show scheduler

**Screenshots**
![Screenshot from 2021-07-27 03-58-22](https://user-images.githubusercontent.com/61561415/127067453-2700e234-db0c-4408-a9a1-22385b2dcdef.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [e.g. chrome, firefox]

**Comment by mariobehling** [comment]
Not encountering this bug currently. Therefore closing this.
