### ISSUE TITLE
Getting error:

### ISSUE THREAD

**Issue by Ritwik880** [fossasia/open-event-frontend#7624]
I am trying to contribute in this repo but it is not running on my local server:

![Screenshot (343)](https://user-images.githubusercontent.com/54446880/127457236-4ce39fc4-dfca-4be2-a309-2316e34f1c54.png)

**Comment by MeghalBisht** [comment]
It is recommend to setup the project on Linux or WSL.
If you still want to work on windows then try installing `gettext` using -
 "http://gnuwin32.sourceforge.net/packages/gettext.htm"
