### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [fossasia/open-event-frontend#7661]
I would like to create a file contributing.md and add following -
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

**Comment by maze-runnar** [comment]
https://github.com/fossasia/open-event-frontend/blob/development/docs/installation/local.md

What is essential everything is already here, so no need for extra.
