### ISSUE TITLE
Team page of a group shows all owners/organizers of all teams

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7669]
Accessing a teams page of a group as as an system admin shows all owners and organizers of all groups.

Expected: A teams page of a group should only show the owners and organizers of that specific group.

![Screenshot from 2021-08-09 19-59-08](https://user-images.githubusercontent.com/1583873/128752259-081b63d4-e134-4181-80b1-997c5b2b35c7.png)

**Comment by asb404** [comment]
Hey !! Can I start working on this issue ?

**Comment by progmatic-99** [comment]
yes, go ahead.

**Comment by maze-runnar** [comment]
@mariobehling @pc-beast can you please test this once more, it should be resolved. (I have tested it, working fine)

**Comment by pc-beast** [comment]
Works fine for me too
