### ISSUE TITLE
Implement event-import API to events/import

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#767]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Comment by sainiak009** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by harsh-98** [comment]
@sainiak009 can i work on this issue and @geekyd  what should be the data in the imported file and how it should it structured

**Comment by geekyd** [comment]
@harsh-98 Sure go ahead. The format is the open event compatible format that is generated by the API server. Have a look at the samples here https://github.com/fossasia/open-event/tree/master/sample

**Comment by harsh-98** [comment]
@geekyd why are /admin/events/import and /events/import there if the code inside them is same?

**Comment by YogeshSharma0201** [comment]
working on this
