### ISSUE TITLE
Some areas are not translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7673]
Please make the following areas translatable. If Weblate shows up 100% translated, but areas are not really translated something is wrong. Compare https://hosted.weblate.org/projects/open-event/frontend/de/

1. On wizard step 1 the offline payment options.
![Screenshot from 2021-08-09 23-56-29](https://user-images.githubusercontent.com/1583873/128779795-7e23d9a4-a66d-4a1a-b08e-daec42767c4a.png)

2. On the video tab the helper text
a) below the heading
b) on the (i) icon
![Screenshot from 2021-08-09 23-57-31](https://user-images.githubusercontent.com/1583873/128779968-b70dd86c-c29c-4a73-a2dd-fadeaf0cc943.png)

3. Change "Video Room" to "Video" on the top area next to the switch

![Screenshot from 2021-08-10 00-00-00](https://user-images.githubusercontent.com/1583873/128779950-05f679e3-e765-445e-ba11-e3ec0f2870e5.png)

4. "No social links present" on the dashboard of events

![Screenshot from 2021-08-10 00-24-05](https://user-images.githubusercontent.com/1583873/128781961-c6431b12-5792-465d-8187-ab68ac480078.png)

5. On the groups edit pages
a) announce/remove event
![Screenshot from 2021-08-10 00-26-43](https://user-images.githubusercontent.com/1583873/128782108-ac4c5962-27e5-427c-9be2-7bb71abc4f4b.png)
b) Group join date
![Screenshot from 2021-08-10 00-27-41](https://user-images.githubusercontent.com/1583873/128782236-930c4e7d-4477-46c8-9140-2cf480a49304.png)
c) Settings page "About"
![Screenshot from 2021-08-10 00-38-23](https://user-images.githubusercontent.com/1583873/128783066-df37eb58-a9d6-4e19-ba6e-6d02955e13ee.png)

6. Ticket cancellation on tickets page - dialogue box

![Screenshot from 2021-08-10 15-18-15](https://user-images.githubusercontent.com/1583873/128874107-98977c8e-692e-42b3-a1f9-6389541c4fde.png)

**Comment by MeghalBisht** [comment]
Few points mentioned are already translatable, need to add translations from weblate.

**Comment by mariobehling** [comment]
> Few points mentioned are already translatable, need to add translations from weblate.

Weblate frontend shows 100% translated for German, but these areas are not translated. Not sure, how to resolve this then?

**Comment by MeghalBisht** [comment]
![Screenshot from 2021-08-11 22-50-31](https://user-images.githubusercontent.com/61330148/129074482-8c3f3ce2-cfbd-41b6-aca2-5c651e3e7219.png)

@mariobehling It is wrongly translated in weblate, can you check?

**Comment by mariobehling** [comment]
It does not matter if it is wrong or not. As you can see in the UI, there is no translation at all.

E.g.

1. See on Weblate.

![Screenshot from 2021-08-16 13-42-15](https://user-images.githubusercontent.com/1583873/129558440-49dc842f-3105-4e9e-b680-d9fd7ec652e6.png)

2. See on the wizard UI

![Screenshot from 2021-08-16 13-44-10](https://user-images.githubusercontent.com/1583873/129558560-de41efe3-efc5-4528-bb95-4ce0dd471748.png)

**Comment by mariobehling** [comment]
Thank you. Still need to follow up about a few sentences.

Incomplete sentences
* The room password field can be used to communicate a password which is necessary to access online video rooms for example for external video services such a Zoom, Teams and Webex. The need for a password entry depends on the configuration of your video channel. The integrated Big Blue Button video solution in
* to all group members now
* The feature integration is still in Alpha stage and currently your profile on the


How to handle this?
* The feature integration is still in Alpha stage and currently your profile on the + this.settings.appName + account page and on the chat are not linked and can be independently edited.

**Comment by mariobehling** [comment]
More incomplete sentences
* Refunds to be processed by the organizer through payment provider. Refund payments to attendees cannot be made on the
* platform. Please go to your payment provider, make a refund and mark the ticket as refunded in the
* Your message was sent to the organizers of this
* Call for Speakers will softly closed on

**Comment by mariobehling** [comment]
Correct is "Call for Speakers will softly close on.."

**Comment by mariobehling** [comment]
Incomplete sentence
* Die Funktionsintegration befindet sich noch in der Alpha-Phase und derzeit "
"ist Ihr Profil auf der
