### ISSUE TITLE
Group Team Page: Add option to resend invitation and to delete team member and show group owner in team table list

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7676]
1. Similar to the event organizers team page for the group team page implement the following options:
* Resend invitations
* Delete a team member

2. Also ensure that the group owner is listed in the list as the owner.

![Screenshot from 2021-08-10 00-43-47](https://user-images.githubusercontent.com/1583873/128783605-ae0f705a-c00b-4251-93d1-2662417e34de.png)

Compare event team page

![Screenshot from 2021-08-10 00-42-55](https://user-images.githubusercontent.com/1583873/128783607-0d84b7ec-fe1e-4efd-8fb2-47ece94cda64.png)

**Comment by rijusougata13** [comment]
Hi, I would like to contribute in this. I have setup my local env. Can you help me where should I look and what are files I need to look into and modify to achive this .
