### ISSUE TITLE
Groups Team Page: Add sub-page for permissions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7677]
Similarly to the event team page for the group team page add a sub page for permissions.

![Screenshot from 2021-08-10 00-59-17](https://user-images.githubusercontent.com/1583873/128784780-511a8765-86b0-42e0-8424-3165afdb2ef8.png)

**Comment by ranjitkshah** [comment]
@pc-beast please take this up

**Comment by maze-runnar** [comment]
@pc-beast?

**Comment by pc-beast** [comment]
Working on it. Will share progress in the next meet.

**Comment by maze-runnar** [comment]
Cool :+1:
