### ISSUE TITLE
Schedule Page: User not able to schedule session when Microlocation is hidden

### ISSUE THREAD

**Issue by sachinchauhan2889** [fossasia/open-event-frontend#7690]
User not able to schedule session when Microlocation is hidden

**Comment by mariobehling** [comment]
We need a pop up, when the user hides the microlocation.

On the final wizard step please add the following text.

"If you hide this microlocation you will not be able to schedule sessions in it. The location will still be available for online events without scheduled sessions, e.g. break-out or discussion rooms. Cancel / Ok"
