### ISSUE TITLE
no recieving confirmation in email

### ISSUE THREAD

**Issue by Ayush2020012016** [fossasia/open-event-frontend#7713]
![eventaya2](https://user-images.githubusercontent.com/78146753/130023788-29880b5c-87af-4054-a12d-e32f365dd3e7.png)
when I pressed button them this message is shown
![eventaya1](https://user-images.githubusercontent.com/78146753/130023844-249c9566-1ed0-49e7-ad0f-04f1938564d9.png)

but there no confirmation coming at email.

**Comment by pc-beast** [comment]
Check your spam
