### ISSUE TITLE
add gitpod integration

### ISSUE THREAD

**Issue by progmatic-99** [fossasia/open-event-frontend#7716]
https://gitpod.io

**Comment by mariobehling** [comment]
Why? What for? Please explain.

**Comment by progmatic-99** [comment]
As there are many people who are starting out in open source, and they get stuck during the project setup. If they just open the project using gitpod.io, the project will build itself. So, they can start contributing & hacking right away. Since, we get a lot of queries regarding people not being able to setup the project locally. They can use this as this does those steps automatically.
