### ISSUE TITLE
Schedule list view: duplicated, empty sessions

### ISSUE THREAD

**Issue by vbejdo** [fossasia/open-event-frontend#7721]
**Describe the bug**
List View for an event's schedule duplicates sessions or simply puts in empty slots in the schedule, some of which eventually remove themselves as the schedule fully loads; however, upon fully loading, the page often retains empty slots and duplicated sessions. Exactly _which_ sessions this occurs to does not seem to be consistent, but this behavior is easily and consistently reproduced when using List View to view a schedule. (Calendar View seems to be unaffected by this issue)

**To Reproduce**
1. Using the Practical Open Source Information event as an example, navigate directly to [https://eventyay.com/e/e7dfbfc4/schedule](https://eventyay.com/e/e7dfbfc4/schedule)
2. As the page loads, notice that empty slots and duplicated sessions get introduced into the schedule:
![image (1)](https://user-images.githubusercontent.com/89475629/130657728-3adc97ec-e7dd-4eaf-a152-b79ba761755b.png)
3. Even after the page loads fully, notice that though the amount of blank sessions is reduced, many sessions are still duplicated in the schedule:
![unnamed (1)](https://user-images.githubusercontent.com/89475629/130657929-8eabcd6f-66d6-4855-bf9e-a68f90734cee.png)

Desired functionality would simply be to show the entire schedule in chronological order as is intended with List View. Note that this schedule has multiple tracks, one of which begins at another time than the other two.

**Comment by mariobehling** [comment]
Thanks for reporting. Which browser do you use? Does it happen with all browsers?

**Comment by vbejdo** [comment]
Should have mentioned this - though I don't know the specs of the other folks that have reported this to me, I've tried Chrome (92.0.4515.131, stable) and Firefox (91.0) and it seems to occur across browsers.

**Comment by mariobehling** [comment]
So, this could be related to Emberjs and lazy loading. Though, it does not seems to happen for other events e.g. https://eventyay.com/e/fa96ae2c/schedule

Loading the entire schedule is difficult as some browsers slow down a lot when there are events with a lot of sessions like yours. Also, as we provide filter and search options which slow down the server response too much and become unusable if we display all sessions. Reloading the page gets it working, but we cannot expect users to do this.

We are investigating further.

**Comment by vbejdo** [comment]
I should note that it also seems to occur on that event as well (an event whose schedule I've never loaded up before -- perhaps confirming your suspicions?) Thanks for following up.
