### ISSUE TITLE
Enhance and Fix One click sign up (Registration)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7727]
- [x] Change "Registration for event." to "Registration"
- [x] Do not show headings "Name" and "Type"
![Screenshot from 2021-08-25 15-30-53](https://user-images.githubusercontent.com/1583873/130799621-e08e22a4-c315-40e2-a0d4-769a5fb66dd9.png)
- [x] Follow the order in the organizers wizard (e.g. free orders on top)
![Screenshot from 2021-08-25 15-29-52](https://user-images.githubusercontent.com/1583873/130799472-0de00b66-a580-4c7f-b9c4-639152411ee8.png)
- [x] Similarly to the screenshot below show the registration description
Compare 
![Screenshot from 2021-08-25 15-17-25](https://user-images.githubusercontent.com/1583873/130799111-552d8bea-4689-4dbb-b7b1-d83b77fedce1.png)
- [x] Show the actual rate or "Free"
- [x] For showing the rate display in smaller font either "including xxx Euro/USD etc. tax" or "plus xxx Euro/USD etc. tax" depending on the users choices
- [x] Show a radio button for the choice of ticket and make the entire area clickable similar to [here](https://hopin.com/events/festival-of-female-entrepreneurs-bristol-cef70572-74af-4550-a447-4b3e624c7054) 
- [x] Add a blue button "Register Now"
- [x] Make all buttons blue as in other areas of web service
![Screenshot from 2021-08-25 15-26-42](https://user-images.githubusercontent.com/1583873/130799097-809c2f8e-0461-42b2-8f46-5b67e8ed00ee.png)
- [x] Ensure that signup works for anonymous users in the same way as it works for ticket buyers (e.g. they have to sign up in the process)

**Comment by AbhishekJamhoriya** [comment]
@mariobehling can i work on this issue.
