### ISSUE TITLE
Use personal profile details and avatar as speaker details by default

### ISSUE THREAD

**Issue by jancborchardt** [fossasia/open-event-frontend#773]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently to add speaker details, you need to separately add a speaker profile and details. This is confusing since you already have a personal profile with avatar in the top right, which is not reflected in the »speakers« list of an event.

**Expected behavior:**
By default, simply take over the info from the personal profile. Editing the speaker profile per event should only be optional.

**Comment by k4ni5h** [comment]
i would like to work on this issue

**Comment by sumedh123** [comment]
@k4ni5h Please proceed.
