### ISSUE TITLE
Add option "Purchase on invoice" to Offline Purchase Methods

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7758]
Similar to the payment method "Pay by Cheque" please implement the option "Purchase on invoice". Add the option in the same way as pay by Cheque and add it to the following areas:
* wizard step 1 in the area payment options
* if option is chosen provide it in the order payment methods of tickets
* show the payment methods on the order summary pages
* show the payment methods on the invoice PDFs
* ensure that the fields are translatable

![Screenshot from 2021-09-03 15-56-11](https://user-images.githubusercontent.com/1583873/132017104-e6f936a5-ce9f-4c97-81e0-c925d3d59106.png)

**Comment by toth2000** [comment]
I would like to work on this issue.

**Comment by daretobedifferent18** [comment]
working on it

**Comment by iamdevvalecha** [comment]
on it.

**Comment by pc-beast** [comment]
![image](https://user-images.githubusercontent.com/56963647/135101577-3104b3aa-f049-4196-ad35-bc33956a79ad.png)
Swap cheque with poi
![image](https://user-images.githubusercontent.com/56963647/135101628-fd89f967-3953-4b38-b58e-a454b62575ad.png)
here too
add Purchase on invoice instead of invoice

**Comment by iamdevvalecha** [comment]
@pc-beast sure!

**Comment by pc-beast** [comment]
@iamdevvalecha update?

**Comment by iamdevvalecha** [comment]
work in progress

**Comment by iamdevvalecha** [comment]
![Screenshot from 2021-10-02 20-48-09](https://user-images.githubusercontent.com/71969867/135722664-8ddfaaa0-d432-4dc8-b8e8-4d541798f428.png)
