### ISSUE TITLE
Scheduler: Follow one structure/design and implement times on the left bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#777]
Clicking between day/3day and week shows the times of events for day display on the top row and for week display in the first column. Please follow the implementation of Google calendar and always display times in the first column.

![screenshot from 2017-08-22 18-22-01](https://user-images.githubusercontent.com/1583873/29576141-14ec7d68-8767-11e7-936a-4372f9b5db63.png)

**Comment by niranjan94** [comment]
To show rooms with sub-rooms, it is necessary to have that on the y-axis and the times on the x-axis. 

If we swap it, it wouldn't be possible to properly implement sub-rooms. There is just not enough space for it. 

It is not right to compare this with Google Calendar. Google calendar has only one point of reference. Which is date-time. Whereas we have something called as rooms/micro-locations too. So, what is possible there wouldn't always be possible here. 

And also, this scheduler is only for admins. The public view scheduler will be a totally different print-friendly implementation.

**Comment by mariobehling** [comment]
@niranjan94 I understand the idea of subrooms. However the UI is confusing as one time the time is on the top and the other time is on the left. If subroom is the problem, keep it simple and take it out for now. Right now we are focusing on a lot of additional small features while the basics don't work. We are loosing focus. Get the system working and ride along common user experience. Keep it simple for now. The project is not finished within GSoC. We had hoped to get a lot of events on board this autumn and we will not be able to do this. I need to explain a lot to people about the UI. If you keep this in the same way as what people experience elsewhere it is much easier.

Please take out subrooms for now and follow a simple approach.

**Comment by Pk13055** [comment]
@niranjan94 Can I take this up if you're not working on it?

**Comment by mohitm15** [comment]
@niranjan94 Is this issue is open to work on??

**Comment by iamareebjamal** [comment]
Changed in #1582 

I still think rooms on left hand and time on top would be a better UI. Reasons are as follows:

There are constant hours in a day. So when you switch to events, you won't see different amount of columns, just different amount of rows (rooms). Right now, every event has a different scheduler view which is difficult to grasp for a beginner.
Current view is too congested to be easy for either organizer to customize or a user to view. 
![image](https://user-images.githubusercontent.com/3874064/90061473-ce0fbe00-dd03-11ea-8429-7547d654f93b.png)
They'd much rather have constant height for rows (rooms) and same width for hours and be able to drag easily horizontally to change the timing. It also looks consistent with other organizer UIs. If it feels confusing to have 1 day/2 day/week scheduler, then that option can be removed. I don't think any organizer UI gives that option. It is still confusing and absolutely unusable in some cases
![image](https://user-images.githubusercontent.com/3874064/90061851-5b531280-dd04-11ea-9250-3be5bb354872.png)

**Comment by iamareebjamal** [comment]
The above UI was due to a bug. This has been solved a long time ago
