### ISSUE TITLE
Adding Jitsi Video not possible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7775]
Currently when the user tries to add a Jitsi room there is an error message and the room cannot be added.

![Screenshot from 2021-09-11 10-23-22](https://user-images.githubusercontent.com/1583873/132941607-9791d51f-b03b-4b94-8b42-b04e9d06a486.png)

**Comment by daretobedifferent18** [comment]
@mariobehling I have checked this and was unable to produce this error, pls could you confirm this bug still present.

**Comment by mariobehling** [comment]
It is correct. It is working again. Strange. Wonder why this error appeared.
