### ISSUE TITLE
Fix and Improve Registration Box Design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7778]
1. Get rid of brackets. They even show up when there is no description
![Screenshot from 2021-09-13 10-39-00](https://user-images.githubusercontent.com/1583873/133053831-6ecb3d79-257a-41a3-b045-7fea10307a95.png)

2. Improve the design and make it more similar to the below screenshot.
![Screenshot from 2021-08-25 15-17-25](https://user-images.githubusercontent.com/1583873/130799111-552d8bea-4689-4dbb-b7b1-d83b77fedce1.png)
* [ ] Make the cost bold, e.g. USD 10.00 
* [ ] Increase the spacing between the radio button and the text behind a bit
* [ ] Move the description with the same indent below the ticket name
* [ ] Make the radio button empty circle line less thick and use the same gray color as it is used elsewhere in the design

Compare current box design
![Screenshot from 2021-09-13 10-51-43](https://user-images.githubusercontent.com/1583873/133054008-13adab4a-9070-46cf-8508-733c2d586654.png)

**Comment by daretobedifferent18** [comment]
working on it
