### ISSUE TITLE
Attendee Checkin drop down not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7780]
The attendee checkin dropdown is not working, in particular when there is only one event day there is no menu choice.

![Screenshot from 2021-09-13 17-48-31](https://user-images.githubusercontent.com/1583873/133116167-4d72789c-d382-4d27-85ab-813db0a0c4d0.png)

This is related to the PRs https://github.com/fossasia/open-event-server/pull/8056 and https://github.com/fossasia/open-event-frontend/pull/7623

**Comment by adarsh-technocrat** [comment]
Hey @mariobehling  can I work on this issue :)

**Comment by pc-beast** [comment]
@adarsh-technocrat what is update on the issue?

**Comment by iamdevvalecha** [comment]
on it.

**Comment by maze-runnar** [comment]
@mariobehling this issue should be in past events, the event created before PR https://github.com/fossasia/open-event-frontend/pull/7623 was merged?

**Comment by mariobehling** [comment]
It seems like this is working on new events. Therefore closing it.
