### ISSUE TITLE
Create a "Group Widget" on the right side bar of events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7788]
For events that are part of a group create a widget with the following:
1. Row: Logo of group, name of group
2. Row: a blue button "Follow" and Number of followers
* There could be a gray line around the widget area or some other UI element to make it separate
* If the user has already followed that group instead of "Follow Group" show "Following"-
Example button

![Screenshot from 2021-09-14 07-26-12](https://user-images.githubusercontent.com/1583873/133201752-5a554581-5f2f-4b82-ab3f-9c1bf25f73d0.png)

**Comment by aman-singh7** [comment]
working on it.

**Comment by daretobedifferent18** [comment]
working on it

**Comment by maze-runnar** [comment]
@daretobedifferent18 are you still on it, or working on another issue?

**Comment by maze-runnar** [comment]
@mariobehling is this ok - 
![Screenshot from 2021-09-20 22-04-05](https://user-images.githubusercontent.com/56407566/134039955-e239039b-a693-4b4c-ab82-53c6fdb56ae6.png)
![Screenshot from 2021-09-20 22-04-09](https://user-images.githubusercontent.com/56407566/134039960-f69ca7bc-8d7b-4238-968d-b448b390716b.png)

**Comment by daretobedifferent18** [comment]
> @mariobehling is this ok -
> ![Screenshot from 2021-09-20 22-04-05](https://user-images.githubusercontent.com/56407566/134039955-e239039b-a693-4b4c-ab82-53c6fdb56ae6.png)
> ![Screenshot from 2021-09-20 22-04-09](https://user-images.githubusercontent.com/56407566/134039960-f69ca7bc-8d7b-4238-968d-b448b390716b.png)

Yes @maze-runnar I am working, took time to setup server project.

**Comment by maze-runnar** [comment]
ok @daretobedifferent18 , just waiting for @mariobehling to confirm if this design is ok or not.
