### ISSUE TITLE
Add app web app & android generator links to event/<id> route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#779]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend
![screenshot from 2017-08-23 10-10-25](https://user-images.githubusercontent.com/12807846/29599127-51474890-87eb-11e7-9734-8b8fa7e3da93.png)

**Comment by niranjan94** [comment]
Closing this until generators have API implemented.
