### ISSUE TITLE
make navbar sticky

### ISSUE THREAD

**Issue by khareyash05** [fossasia/open-event-frontend#7795]
Making the navbar sticky would allow easy accesibility to any page at any time 
We can make the navbar a slightly more translucent when a person scrollls downs the website

**Comment by tanay123456789** [comment]
working on it

**Comment by pc-beast** [comment]
Not Needed.

**Comment by tanay123456789** [comment]
why??

**Comment by khareyash05** [comment]
@tanay123456789 I have made the issue for myself so kindly stop working
