### ISSUE TITLE
Registration: Tax for paid tickets wrong

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7799]
Creating paid registrations works well, but if the organizer adds tax the tax shows up as 0.00. This feature works for the tickets though. Please fix this and move the tax information below the price (same as it works for tickets).

![Screenshot from 2021-09-17 11-42-02](https://user-images.githubusercontent.com/1583873/133763966-f7fb54a7-a941-42ab-b52e-5347f7331bfc.png)
![Screenshot from 2021-09-17 11-41-39](https://user-images.githubusercontent.com/1583873/133763973-cb28c50f-924e-46bd-95f1-0d5c94b0e09f.png)

**Comment by AnkitaSinghIE** [comment]
Can I go with that issue??
