### ISSUE TITLE
Prevent Ticket Types and Registrations with Orders from Deletion

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7806]
Ticket types and registrations can currently be deleted even if they have orders. Please prevent them from deletion and implement the following:
If an organizer tries to delete a ticket or registration from deletion show an error pop up: "This ticket or registration type already has orders. Therefore it cannot be deleted. Please hide this type instead by using the hide option under the settings symbol." and show an "Ok" button to close the pop up.

![Screenshot from 2021-09-19 20-02-47](https://user-images.githubusercontent.com/1583873/133937992-39148a5e-39b2-4869-9d43-72817e4a9e1d.png)

**Comment by daretobedifferent18** [comment]
working on it
