### ISSUE TITLE
Add a table with scrollbar on manage events page rather than vertical table

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#781]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently, table data on manage events page is vertical

**Expected behavior:**
We can add a table with scrollbar  and make table horizontal

**Steps to reproduce:**
Login to https://open-event-frontend.herokuapp.com/ and open manage events link

**System information:** 
Mobile phone

![issue1](https://user-images.githubusercontent.com/25428397/29599553-21bc9884-87ee-11e7-8b1e-ee4da2dcfad9.png)

**Comment by shreyanshdwivedi** [comment]
I would like to work on this issue

**Comment by k4ni5h** [comment]
What is the status of this issue ?

**Comment by sumedh123** [comment]
@geekyd This issue seems invalid. Can you close this one?
