### ISSUE TITLE
Changing tax from "included" to "on top" for ticketed events not updated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7810]
If a tax fee is changed from "Include tax" to "Add tax as a separate fee on top of the price" the actual event ticket page and price is not updated.

This problem only seems to appear for ticketed events (not for registration events)

Compare https://test.eventyay.com/e/554ef820

![Screenshot from 2021-09-19 20-49-02](https://user-images.githubusercontent.com/1583873/133939273-3cea96b8-d4b8-4ba1-bb42-aa7834c0f37e.png)
![Screenshot from 2021-09-19 20-47-27](https://user-images.githubusercontent.com/1583873/133939274-863e3842-b7ba-440f-8fe9-6698b7ea7b3a.png)

**Comment by maze-runnar** [comment]
I debugged the issue. the problem comes only when we create a tax for first time after event creation, and edit it for first time. From second time and onwards editing tax works perfectly. https://github.com/fossasia/open-event-frontend/issues/4385

**Comment by progmatic-99** [comment]
@maze-runnar So, this should be closed, or we should implement a workaround??

**Comment by maze-runnar** [comment]
I am working on its solution, but not sure will work or not.
