### ISSUE TITLE
Box to enter amount for donation registration missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7816]
When the organizer chooses the option "donation" for a registration the user will not see a box to enter an amount. Please show a box same as for "donation tickets" for the "donation registration".

**Currently there is no box to enter an amount**
![Screenshot from 2021-09-19 22-39-15](https://user-images.githubusercontent.com/1583873/133942481-f2a4a3aa-3b02-4a18-9a62-ef697665c9ef.png)

**It should look like this**

![Screenshot from 2021-09-19 22-45-14](https://user-images.githubusercontent.com/1583873/133942501-823801fe-d3d9-410e-92d7-eabf71c35daa.png)

**Also ensure the error message works if the user enters an amount that is smaller or higher than specified by the organizer. Compare below.**

![Screenshot from 2021-09-19 22-55-02](https://user-images.githubusercontent.com/1583873/133942786-7d3651ae-63c4-4750-90ca-0aaac1c00e87.png)

**Comment by daretobedifferent18** [comment]
working
