### ISSUE TITLE
Do not show Deleted Registration types on event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7822]
The registration box on the event page currently shows empty boxes for the deleted registration types. Only show boxes of active types.

![Screenshot from 2021-09-20 11-01-58](https://user-images.githubusercontent.com/1583873/133978648-f652085a-9173-4ac0-ad89-a610b5c00dbf.png)

**Comment by pc-beast** [comment]
Working on it

**Comment by pc-beast** [comment]
Couldn't reproduce. I think I am missing something here.
#### Before:
![Screenshot from 2021-09-20 22-10-41](https://user-images.githubusercontent.com/56963647/134042040-43602a7b-6c2f-4994-89e3-f14b98f4bf8f.jpg)

#### After:
![image](https://user-images.githubusercontent.com/56963647/134041747-33f7547b-35ab-454a-8b58-7079f99f2f67.png)
