### ISSUE TITLE
Tax is not showing in price

### ISSUE THREAD

**Issue by pc-beast** [fossasia/open-event-frontend#7824]
**Describe the bug**

Tax info for the price is not showing up while we buy tickets even after adding tax info in the event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new event
2. Add Paid ticket
3. Add tax info
![image](https://user-images.githubusercontent.com/56963647/134043383-ddad63de-24ba-411e-b8a2-d0c87f2102e6.png)
4. Publish the event and go to event page.
5. See error.

**Screenshots**

Expected:
![image](https://user-images.githubusercontent.com/56963647/134043572-509c53b5-5873-48ba-8e55-98d65e06168c.png)
Current:
![image](https://user-images.githubusercontent.com/56963647/134043731-2cba9feb-bfc2-4b1a-9be8-4a9dca97b5e3.png)

While updating the tax sometimes it doesn't get updated and shows error in the console. Needs info.

**Comment by daretobedifferent18** [comment]
working on it

**Comment by daretobedifferent18** [comment]
working on it

**Comment by daretobedifferent18** [comment]
@pc-beast @mariobehling this is working fine for me

**Comment by maze-runnar** [comment]
@daretobedifferent18 please try with a new event, and  add tax at the time of event creation, then again delete/add. try such edge case, and see where it fails.

**Comment by spy-1234** [comment]
Hey, I want to take the issue.
