### ISSUE TITLE
Admin Groups Page does not show Group Name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7850]
The table on the admin groups page does not display the name of groups. Please help to fix this.

The linke https://eventyay.com/admin/groups/live is only accessible for admins. You need to set up the system and access the respective area on your own setup in order to see this issue.

![Screenshot from 2021-09-24 06-22-12](https://user-images.githubusercontent.com/1583873/134617896-b4cd23b1-2ace-4fa5-97c2-b75bf52e6635.png)

**Comment by pc-beast** [comment]
Working on it
