### ISSUE TITLE
Groups admin page: Public URL fields display link to private edit URL

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7851]
The public URL field shows and links to the private URLs to edit the events of a group. Expected: Link to the public group URL.

Compare https://eventyay.com/admin/groups/live (This page is only accessible for admins. In order to view this page please set up the system on your local machine and access the respective slug there)
![Screenshot from 2021-09-24 06-28-57](https://user-images.githubusercontent.com/1583873/134618454-a806e482-a0eb-4aea-9234-eac11639e65f.png)

**Comment by daretobedifferent18** [comment]
Looking into it
