### ISSUE TITLE
Public Groups Page: Contact Organizer button not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7852]
The contact organizer button in public groups pages is not working. Nothing happens when clicking it.

Compare https://eventyay.com/g/47
![Screenshot from 2021-09-24 06-52-00](https://user-images.githubusercontent.com/1583873/134620162-198e3f96-cd17-4e77-b6d7-8ce5b2b8fdfa.png)

**Comment by progmatic-99** [comment]
This is working for me.

![ss_1632460804](https://user-images.githubusercontent.com/42090582/134622359-1822aa51-268c-4d56-b30a-052c3a02da16.png)

**Comment by mariobehling** [comment]
I am getting lots of errors and I am not able to use the contact button in both Chromium and Firefox.

![Screenshot from 2021-09-24 14-32-08](https://user-images.githubusercontent.com/1583873/134674745-1a1d4666-6c4c-432a-a2ff-1da653f778ce.png)

**Comment by mariobehling** [comment]
```
Uncaught (in promise) TypeError: this.errorHandler is undefined
    e group-view.js:134
    c polyfill.js:6473
    _invoke polyfill.js:6702
    t polyfill.js:6525
    s group-view.js:13
    l group-view.js:15

```

**Comment by progmatic-99** [comment]
clear the browser cache and delete history, then try. Maybe it will work.

**Comment by maze-runnar** [comment]
working for me too - 
![Screenshot from 2021-09-24 21-11-06](https://user-images.githubusercontent.com/56407566/134702995-04a79d49-5ec6-487a-95e7-562b2d5ca16c.png)

**Comment by pc-beast** [comment]
Works for me too

**Comment by mariobehling** [comment]
Ok, deleting cache worked for this one, but still finding similar issues with follow button. Will test more and report it. Thanks.
