### ISSUE TITLE
Direct Link to a Session does not work without log-in 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#7860]
**Describe the bug**
When I shared the direct link to the public https://eventyay.com/e/75ac7f83/session/7236 
It showed 404 errors for those who did not log in. 

![Screenshot from 2021-09-25 09-19-44](https://user-images.githubusercontent.com/1658742/134762814-becab4bd-9489-43b7-9212-a6d0765b830d.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Do not log-in
2. Go to 'https://eventyay.com/e/75ac7f83/session/7236'

**Expected behaviour**
Users should see the session details even without log-in

**Comment by maze-runnar** [comment]
looking into it
