### ISSUE TITLE
Standardize group follow/unfollow button 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7862]
Please change the group follow/unfollow button on group pages to match the design of the button on event pages. Merge the two buttons on the group page into one as on the event pages.

Currently

![Screenshot from 2021-09-25 11-37-13](https://user-images.githubusercontent.com/1583873/134766886-234ac27d-c651-4c74-9598-d469622375ea.png)

Expected

![Screenshot from 2021-09-25 11-36-33](https://user-images.githubusercontent.com/1583873/134766889-2aebf89b-8757-4807-8299-2b2fab2ef51b.png)

**Comment by progmatic-99** [comment]
on it.
