### ISSUE TITLE
Order "Company Information" box shows "Organisation" instead of "Name"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7883]
The order company information box shows the "Name" instead of "Organisation" in the left column of the box. Please correct this and show "Organisation" in all company boxes in the order process and final order page.

![Screenshot from 2021-10-04 19-11-04](https://user-images.githubusercontent.com/1583873/135897534-40eb9cfe-27c4-4d26-9938-15902c0d2985.png)

**Comment by akshitarora921** [comment]
Hi, Can I work on this?

**Comment by progmatic-99** [comment]
Yes @akshitarora921, please make a PR.

**Comment by swapnalshahil** [comment]
Will you please help me to reach the issue? I mean which part?

**Comment by iamdevvalecha** [comment]
@swapnalshahil use ember inspector.

**Comment by akshitarora921** [comment]
@iamdevvalecha  Do we need to change the variable name from registeredCompany to organization in `company-info.hbs`?
