### ISSUE TITLE
Video: Add recording column into video tables

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7893]
![Screenshot from 2021-10-06 19-02-31](https://user-images.githubusercontent.com/1583873/136251209-23dea034-421c-4224-bacc-0ebd2c17b7e8.png)

* Move Blue, Green and Red video room button directly below room name and try to reduce the width of the first column a bit
* Reduce the width of the column "Additional Info" a bit
* Create an additional column "Recordings"
* In the column "Recordings" show the following
   * Number of Participants
   * Start Time
   * End Time
   * Duration
   * View
* If there are several recordings show the information of several recordings

Note: The information about the video recordings is also displayed in the video edit page on the bottom
![Screenshot from 2021-10-06 19-01-03](https://user-images.githubusercontent.com/1583873/136251226-85155bc1-ecc1-46f2-b4a0-c7974af6d205.png)

**Comment by iamdevvalecha** [comment]
on it.

**Comment by iamdevvalecha** [comment]
@mariobehling @maze-runnar bbb key is require i think?

**Comment by progmatic-99** [comment]
making a PR

**Comment by mariobehling** [comment]
This implementation does not work yet as expected. Therefore opening it. Issue is:
1. Start and end time are always showing 12.00 / 0.00 no matter what is the correct time.
2. Length always shows "a few seconds"

Compare https://eventyay.com/events/c5cce3ed/video/all (only accessible for admins)

![Screenshot from 2021-11-17 15-14-00](https://user-images.githubusercontent.com/1583873/142217092-54bba7a5-beef-4a29-852f-cc3366457296.png)
