### ISSUE TITLE
Add sessions to events route (UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#79]
**I'm submitting a ...**  (check one with "x")
- [x] feature request

![screenshot from 2017-05-24 14-34-34](https://cloud.githubusercontent.com/assets/12807846/26395593/244e493c-408e-11e7-9f84-e53116169c05.png)

- Located at `events/<event_id>/sessions`
- Implement session-table component.

**Comment by harshitagupta30** [comment]
@niranjan94 @geekyd I am not able to create a new event and also no event exists. How can I create an event?

**Comment by niranjan94** [comment]
- You need to start by creating a `/events/<event_id>/sessions` route
- You can reach that route by clicking on any event on the home page and replacing `/e/` with `/events/` and adding `/session` at the end in the address bar

**Comment by harshitagupta30** [comment]
@niranjan94 Got it! but how can I generate a route with variable event id? Can I create using terminal using ember generate command? Under which folder will it be placed in events?

**Comment by niranjan94** [comment]
@harshitagupta30 the base route is already generated. 
You can just run `ember g route events/view/sessions`. 

Will be located inside `events/view/`

**Comment by harshitagupta30** [comment]
@niranjan94 I am not sure about in which style folder and which file should I keep the CSS related to this screen.

**Comment by niranjan94** [comment]
@harshitagupta30 I don't think you'd be needing any custom styles for this page. 

If you do need to, you can put it inside `app/styles/pages/events/sessions.scss`

**Comment by harshitagupta30** [comment]
@niranjan94 I don't what happened but whenever I am trying to go to `http://localhost:4200/events/963d3ba5/sessions` it's diverting me to `http://localhost:4200/login`
It's was running fine in afternoon.

**Comment by niranjan94** [comment]
If it redirects you to login, then please login. Your session must have expired.

**Comment by geekyd** [comment]
@harshitagupta30 
You need be logged in to access events route. That's why it is getting redirected.
