### ISSUE TITLE
Provide option to set language preference in the account profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7902]
Currently the language of the UI is based on the browser or the choice of the user made on the bottom right. Please provide an option to choose the language based on the user preference on the "Account" page.
1. Add the option to set the language below "Phone" on the account page at https://eventyay.com/account/profile
2. Set language preference in user account
3. Ensure invoices of tickets and events are created in the preferred language

![Screenshot from 2021-10-09 11-52-27](https://user-images.githubusercontent.com/1583873/136653463-c6aa91df-0685-4b63-874d-c50ed447468b.png)

**Comment by maze-runnar** [comment]
for translation reference: https://github.com/fossasia/open-event-server/pull/7416/files

but it's not working for pdf
