### ISSUE TITLE
Subtotal of orders showing 0 instead of price of registration orders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7903]
The subtotal of orders shows 0 instead of the price of registration orders. Expected: It should show the price of an order or a registration.

Compare: Try with a supporter registration here https://test.eventyay.com/e/a86f2bbb

![Screenshot from 2021-10-09 22-26-44](https://user-images.githubusercontent.com/1583873/136673036-61a9956a-c590-441c-a33a-47f3aadd1f22.png)

**Comment by mariobehling** [comment]
Seems the issue only appears with registrations, but not with ticket orders.

**Comment by maze-runnar** [comment]
@mariobehling working on my local with registration type also
![Screenshot from 2021-10-10 10-25-36](https://user-images.githubusercontent.com/56407566/136682840-d31417da-9059-4111-8237-6753cb90ac33.png)

**Comment by maze-runnar** [comment]
And I updated the branch and it got broke - 
![Screenshot from 2021-10-10 10-31-16](https://user-images.githubusercontent.com/56407566/136682953-445802f8-7b95-4d2b-b184-4ca0cdac3d21.png)

@pc-beast please check, it may be due to your PR

**Comment by maze-runnar** [comment]
update the branch, it will stop working. problem is in https://github.com/fossasia/open-event-frontend/issues/7881, I think

**Comment by pc-beast** [comment]
Working on it
