### ISSUE TITLE
Make the ticket holder information editable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7906]
Ticket holders might have filled in wrong information and if they want to correct it there is no possibility in the system. Please add an "Edit" link to the attendee order overview page on the "Ticket Holder" info box and link it to the attendee page. It should be possible for ticket holders to edit their information.

![Screenshot from 2021-10-09 23-06-51](https://user-images.githubusercontent.com/1583873/136673898-9e8bde49-cb68-49cf-9590-c6236a32e551.png)

**Comment by salmanansari14** [comment]
I wanna work on issue

**Comment by maze-runnar** [comment]
on it.

**Comment by mariobehling** [comment]
Reopening as dropdown is not yet editable.

**Comment by mariobehling** [comment]
I have tested the first PR in more detail now. Unfortunately the process is not yet ready for users.

After an order is made the user can still change data, but there is no way to save it. It lacks a save button. Also changes are not reflected on the ticket. Expected would be a button "Edit Attendee Information" and "Save". Fields should only become editable after the user has pressed "Edit". This might have to implemented in a separate page.

So, for now I am reverting this and I hope the remaining parts can be taken care of.

**Comment by ayushporwal1234** [comment]
@mariobehling sir please assigned me!! I will start my journey so this is very helpful for me. Thank you!!

**Comment by ayushporwal1234** [comment]
I am working on this.

**Comment by ayushporwal1234** [comment]
@mariobehling this issue is open right now

**Comment by Parna2000** [comment]
I am working on this issue @mariobehling

**Comment by reachaadrika** [comment]
@mariobehling @maze-runnar @pc-beast Since there is no PR on this issue,  can I take this up?

**Comment by maze-runnar** [comment]
Yes, no need to ask. If no one else working just start working and ask if stuck

**Comment by v0nser** [comment]
Hey! I wanna work on this issue.
