### ISSUE TITLE
Hide and Unhide Password Bug

### ISSUE THREAD

**Issue by manikantanynala97** [fossasia/open-event-frontend#7919]
DESCRIPTION - > 
Hey the Hide and Unhide Icon in the Password section is in the Opposite Order for Unhide Icon it is not showing the password and for the Hide Icon it is Showing the Password which is completely Opposite

HOW TO FIX THE BUG ->
1) For Unhide Icon show the Password
2) For Hide Icon Donot show the Password

![Screenshot (360)](https://user-images.githubusercontent.com/90610801/136978691-1af41420-c8c2-42e6-946d-c675e2a5cda0.png)

![Screenshot (361)](https://user-images.githubusercontent.com/90610801/136978749-3c2bc506-6378-4a41-91b0-ec37e25a0169.png)

**Comment by progmatic-99** [comment]
Working fine for me.

**Comment by sejalrai23** [comment]
I want to work on this . pleases assign me this issue

**Comment by progmatic-99** [comment]
@maze-runnar We can close this, ig.
