### ISSUE TITLE
User cannot order tickets when starting with ticket order before log in or registration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7928]
If a user starts the ticket order process a window usually appears to log them in or to let them register. Once the user has finished logging in the order page appears. BUT: There is a black overlay that prevents the user from progressing.

Steps to reproduce. Compare https://eventyay.com/e/c5cce3ed

1. Order page
![Screenshot from 2021-10-13 15-04-25](https://user-images.githubusercontent.com/1583873/137138495-07bf4899-ecb3-458c-a923-52cfc3c15669.png)

2. Login or register for platform
![Screenshot from 2021-10-13 15-04-37](https://user-images.githubusercontent.com/1583873/137138549-9e7f08f8-91de-4fca-a6d6-e36f959f1153.png)

3. Black overlay on following page
![Screenshot from 2021-10-13 15-04-42](https://user-images.githubusercontent.com/1583873/137138594-5aa29251-ad6b-4a6b-a196-90da164110d6.png)

**Comment by maze-runnar** [comment]
I have found the reason for this, creating a PR soon with solution.
