### ISSUE TITLE
Implement role invite creation,edit & delete on event overview

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#796]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/29708029-f42e9ae4-89a4-11e7-9a45-180457c1b094.png)

**Comment by geekyd** [comment]
Related issue : https://github.com/fossasia/open-event-frontend/issues/716
