### ISSUE TITLE
Implement discount-code API to tickets/discount-codes/create

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#798]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Comment by ritikamotwani** [comment]
@geekyd @CosmicCoder96 can I work on this issue?

**Comment by CosmicCoder96** [comment]
@ritikamotwani please go ahead
