### ISSUE TITLE
Make nav-bar mobile friendly

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#8]
The nav-bar right now overflows on smaller screens. Make it mobile friendly. 

**What is expected ?**
- Show only key elements on the nav-bar depending on space available
- _**Bonus points:**_ Also show an expandable side bar on mobile with options that were removed from the nav-bar

**References:**
- https://semantic-ui.com/collections/menu.html
- https://semantic-ui.com/collections/grid.html

**Comment by CosmicCoder96** [comment]
@niranjan94 working on this.

**Comment by niranjan94** [comment]
@CosmicCoder96 sure
