### ISSUE TITLE
Groups: Thumbnails are not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8005]
Thumbnails of groups and events in groups are not showing up anywhere, e.g. on frontpage, search page, my groups list page, group info pages etc.
* https://eventyay.com/my-groups/list
* https://eventyay.com/
* https://eventyay.com/my-groups/following
* https://eventyay.com/explore/groups
* https://eventyay.com/g/101

![Screenshot from 2021-10-29 13-49-08](https://user-images.githubusercontent.com/1583873/139429417-2978055b-7ada-4a04-b8f1-228c447ba12d.png)
![Screenshot from 2021-10-29 13-48-18](https://user-images.githubusercontent.com/1583873/139429420-d02ee9b3-4654-40d1-8e8a-3c071abc2a6c.png)
![Screenshot from 2021-10-29 13-48-01](https://user-images.githubusercontent.com/1583873/139429421-2222eb70-54ec-45b3-9bac-bdcb3c2daaa4.png)
![Screenshot from 2021-10-29 14-05-04](https://user-images.githubusercontent.com/1583873/139431388-9263bc84-6453-479e-9f52-5fa93a317c0f.png)

**Comment by mehulmathur16** [comment]
Hi Mario,
I want to work on this issue. Can you tell what image we want to have instead of group?
