### ISSUE TITLE
Groups: Only one group can be promoted to front page and overview pages display group events multiple times

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8007]
Only one group can be promoted to front page and overview pages (of events) display groups multiple times. They also do not show the event images.

![Screenshot from 2021-10-29 13-48-18](https://user-images.githubusercontent.com/1583873/139434569-6beab384-d8a8-488e-b6ec-96d86ce23219.png)

Compare https://eventyay.com/g/101

![Screenshot from 2021-10-29 14-29-41](https://user-images.githubusercontent.com/1583873/139434733-953e5c84-6d69-4424-b054-e6490f111b98.png)

**Comment by maze-runnar** [comment]
these are not groups, these are events that are part of that event

**Comment by maze-runnar** [comment]
![Screenshot from 2021-10-30 07-28-51](https://user-images.githubusercontent.com/56407566/139516508-4f361109-f4d9-4b27-bb4a-54ba46e69aa6.png)

**Comment by mariobehling** [comment]
As you can see in the above link this is exactly what is encountered on the live site.
1. Only one groups gets promoted.
2. Events do not show up with image on the groups page. Compare https://eventyay.com/g/101

**Comment by mariobehling** [comment]
You need to login to view the groups page.

**Comment by maze-runnar** [comment]
I don't why promoting only one group is happening on live site, because on test-eventyay, it is working correctly. so behaviour should be same.

**Comment by pc-beast** [comment]
After #8126 Promoted Groups are now visible on the front page, but event images are still not showing up sometimes.
