### ISSUE TITLE
On the schedule page, automatically jump to the current day

### ISSUE THREAD

**Issue by jancborchardt** [fossasia/open-event-frontend#801]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request

**Current behavior:**
When going to the schedule page of an event, you simply are shown the first day, even if that is long past. For example: https://eventyay.com/e/de88e486/schedule/

**Expected behavior:**
When the conference is ongoing, opening the schedule page should open the current day, ideally with a marker for the current time.

**Comment by k4ni5h** [comment]
I would like to work on this issue. Please assign.

**Comment by sainiak009** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by srv-twry** [comment]
@CosmicCoder96 @geekyd Is it issue relevant and open ? I would like to go ahead with this if it is.

**Comment by srv-twry** [comment]
@niranjan94 Can i work on this ?

**Comment by niranjan94** [comment]
@srv-twry yes you can proceed

**Comment by iamareebjamal** [comment]
Solved long ago

**Comment by mariobehling** [comment]
Reopening this as it is not working currently.
