### ISSUE TITLE
Sales admin page of eventyay not accessible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8021]
The sales admin page of eventyay gives an error message and is not accessible.

Compare https://eventyay.com/admin/sales/live

![Screenshot from 2021-11-03 14-30-37](https://user-images.githubusercontent.com/1583873/140069204-02b1b973-3e51-4df1-8bfe-ac8825209f7e.png)

https://test.eventyay.com/admin/sales/live

**Comment by maze-runnar** [comment]
![Screenshot from 2021-11-04 17-40-12](https://user-images.githubusercontent.com/56407566/140311167-20e6c6a0-ec55-4adb-86d8-47e9b4d7f093.png)

**Comment by Riya5915** [comment]
Is this a pending issue, or it's resolved?

**Comment by maze-runnar** [comment]
We are not able to figure out reason why it's happening.

**Comment by codedsun** [comment]
![image](https://user-images.githubusercontent.com/20026440/143027519-f991391f-e119-43b0-a8db-6333a5d9785c.png)

The issue is that we are getting 502 using postman @SundaramDubey @pc-beast @progmatic-99 Any ideas on what could be the issue here?

**Comment by pruthvihosmani** [comment]
Is this issue resolved??

**Comment by palakshivlani-11** [comment]
Can I pick this issue.

**Comment by JaguarsCodehub** [comment]
If no one is working on this ? Can I help in this issue.

**Comment by cweitat** [comment]
![image](https://github.com/fossasia/open-event-frontend/assets/11439477/187cde16-fb27-483c-bcbf-3c9ee4692c7d)
CORS

**Comment by lthanhhieu** [comment]
Close as duplicated with https://github.com/fossasia/open-event-server/issues/8533
The root cause of this issue is the logical in server.
