### ISSUE TITLE
Event logo cut off in events with long title or address

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8029]
When an event has a long title or address the information can result in an additional line. In this case the logo moves to the top of the information and this results in logos getting cut off  on some public pages, e.g. speaker pages compare https://eventyay.com/e/0db87d3b/speakers .

Expected is that that the logo stays on the left and the text stays visible as well.

![Screenshot from 2021-11-04 15-21-42](https://user-images.githubusercontent.com/1583873/140331257-8da17969-c953-45a7-abc9-aebcc7bd65f0.png)
![Screenshot from 2021-11-04 15-20-03](https://user-images.githubusercontent.com/1583873/140331262-602736b5-6665-4197-b1ad-12904176c863.png)
bu

**Comment by Ruchip16** [comment]
Hey @mariobehling  I would like to work on this issue

**Comment by codedsun** [comment]
@Ruchip16 - You can start working

**Comment by Ruchip16** [comment]
Yes @codedsun I am working

**Comment by Ruchip16** [comment]
![image](https://user-images.githubusercontent.com/72685035/142429888-2e846ea8-e162-46ff-85f3-be3ac86f8083.png)
@mariobehling this is how it looks now I would make a PR for the same

**Comment by Parna2000** [comment]
Hey @mariobehling I would like to work on this issue

**Comment by Ruchip16** [comment]
@Parna2000 I am glad that you are interested in contributing to Fossasia but I am working on this issue and have already changed the files locally hence would suggest you to work on some other open or unassigned issue, thanks

**Comment by pc-beast** [comment]
@Ruchip16 please raise a PR for it. It's been a long time since you claimed the issue.

**Comment by Ruchip16** [comment]
yes @pc-beast I would do it within tmr my end sem exams were going on hence I did not get time to do so but I would do it now

**Comment by Anosh21** [comment]
Hello @mariobehling  is anyone working on this ?

**Comment by progmatic-99** [comment]
@Anosh21 Go ahead, make a PR
