### ISSUE TITLE
Make speaker area mobile ready

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8039]
On event pages make speakers mobile friendly.

Compare https://eventyay.com/e/0db87d3b

![Screenshot_20211106_024137_com android chrome](https://user-images.githubusercontent.com/1583873/140593714-b7083718-84b8-4f31-b7aa-261dd72c61ab.jpg)

**Comment by maze-runnar** [comment]
![Screenshot_20211106-073208_Chrome](https://user-images.githubusercontent.com/56407566/140594161-ce2a6e4a-1470-48c4-8367-4cc0e9c8cf04.jpg)

**Comment by mariobehling** [comment]
@SundaramDubey Seems like you are testing the speaker page itself while this issue is about featured speakers on the start page as per linked shared.
