### ISSUE TITLE
Make organizer appear capital and translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8044]
When inviting team members to an event the role is named as "organizer". Expected would be "Organizer" with a capital "O". This also is not translatable. 

![Screenshot from 2021-11-06 22-51-04](https://user-images.githubusercontent.com/1583873/140624975-39e8470d-529f-4940-b79e-3567adbdf10d.png)

**Comment by Buddhad** [comment]
**I would like to work on this issue please `Assign` me.**
