### ISSUE TITLE
Sessions: Old speaker disappears from schedule when new speaker is added

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8055]
When a new speaker is added to a session the old speaker does not always show up in the scheduler. The old speaker still shows up on the list of speakers on the organizer area, but not on the scheduler itself.

One new speaker here
![Screenshot from 2021-11-09 10-29-56](https://user-images.githubusercontent.com/1583873/140898659-63383a90-81a1-4976-817a-16a0fe31df40.png)

Two speakers in the organizer overview
![Screenshot from 2021-11-09 10-29-41](https://user-images.githubusercontent.com/1583873/140898675-748f3f02-9e1d-4e7b-a1d1-4b1ac34f8f75.png)

Possibly related to https://github.com/fossasia/open-event-frontend/issues/7904

**Comment by mariobehling** [comment]
If I delete and re-add the speaker then the last added speaker shows up. Compare https://eventyay.com/e/0db87d3b/session/7402

**Comment by pc-beast** [comment]
Fixed in #8045 @mariobehling

**Comment by mariobehling** [comment]
Seems to work on test server. Therefore closing it. Thank you!
