### ISSUE TITLE
Redirect Stripe Back Button to Ticket Pending Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8060]
On the Stripe payment page there is a "Back" button. This button currently brings the ticket buyer to an "Expired" ticket page. Please change this and bring the user back to a page "Pending" and enable the user to see the information and repeat the buying process.

**Comment by codedsun** [comment]
@mariobehling This is not possible as discussion with @pc-beast

**Comment by mariobehling** [comment]
Duplicate of https://github.com/fossasia/open-event-frontend/issues/8176
