### ISSUE TITLE
Move Payment Choice to the Checkout Page for Orders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8068]
Users currently choose the payment option on the second step of orders. Please move this choice to the checkout page (step 3). Show the payment options above the "Pay Now" button.

Step 2
![Screenshot from 2021-11-11 12-32-13](https://user-images.githubusercontent.com/1583873/141291421-83a5bfa7-f570-4ce7-bebc-c01a5dfe98d1.png)

Step 3 Checkout Page
![Screenshot from 2021-11-11 12-32-39](https://user-images.githubusercontent.com/1583873/141291418-8e07b669-4a87-492c-a507-0ec815a47222.png)

**Comment by NIKU-SINGH** [comment]
Hey, I would like to work on this issue

**Comment by subhamgcon** [comment]
Hey, anyone working on this issue?

**Comment by codedsun** [comment]
@subhamgcon You can work

**Comment by subhamgcon** [comment]
> @subhamgcon You can work

Okay, Thank you!

**Comment by ayushporwal1234** [comment]
can  i work on this project

**Comment by codedsun** [comment]
It can't be moved as we create order on the click of Proceed to checkout. Need to discuss further, Also what to do in case of cheque,  invoice, onsite @mariobehling

**Comment by mariobehling** [comment]
After merging I get:

TypeError: Cannot read properties of undefined (reading 'message')


![Screenshot from 2021-12-07 17-02-56](https://user-images.githubusercontent.com/1583873/145063881-4023cbd0-52b8-4855-9de0-c071d3d15c40.png)

**Comment by mariobehling** [comment]
state-machine.js:86 TypeError: Cannot read properties of undefined (reading 'message')
    at l.<anonymous> (pending.js:287)
    at c (polyfill.js:6473)
    at Generator._invoke (polyfill.js:6702)
    at Generator.e.<computed> [as next] (polyfill.js:6525)
    at d (pending.js:13)
    at a (pending.js:15)

**Comment by progmatic-99** [comment]
This is solved.
