### ISSUE TITLE
Groups: Add follow button for not logged in users and option to log in

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8070]
Users who are not logged in should see a kind of "inactive" follow button on groups pages similar to the front page "whitened" follow button.

When the user tries to click on the button they should receive a pop up with the following text:
"You need to be logged in to follow this group. Login / Cancel"

Compare https://eventyay.com/g/40

Group page with right-side area missing "Following" button.

![Screenshot from 2021-11-11 19-50-27](https://user-images.githubusercontent.com/1583873/141353103-b27f4c12-1d83-4127-9ba9-790afd0d5790.png)

Button is visible when logged in.

![Screenshot from 2021-11-11 19-50-47](https://user-images.githubusercontent.com/1583873/141353164-d6ae521b-283a-40fe-aa53-4d27b64ff6fc.png)

"Whitened" button on frontpage for not logged in users

![Screenshot from 2021-11-11 19-55-14](https://user-images.githubusercontent.com/1583873/141353276-93a26993-ca70-4688-8104-7b10e7f16ebf.png)

**Comment by ShwetKhatri2001** [comment]
I would like to work on this issue

**Comment by progmatic-99** [comment]
Go ahead, make a PR @ShwetKhatri2001
