### ISSUE TITLE
Registration: Only show "Enter Promotional Code" when there are paid tickets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8071]
Currently if there are only free registrations there is nevertheless the option to enter a promotional code. But, registrations are already free. So, no need to for promotional codes. The promotional code option should only show up if there are paid registrations available.

![Screenshot from 2021-11-11 20-52-06](https://user-images.githubusercontent.com/1583873/141360319-52c69502-ac1c-43bf-88d0-693f31f53e17.png)

**Comment by trngapp** [comment]
I am looking into this bug , but in localhost there is no event , so how can I test the changes I make, Do I have create events by myself for testing .

**Comment by pc-beast** [comment]
Yes.

**Comment by trngapp** [comment]
@pc-beast I have done the registration in localhost and then when the verification mail comes to gmail and I click on the link it shows error , and also as I am unable to verify I could not able to create an event in my localhost , please help ..

**Comment by trngapp** [comment]
@mariobehling Please assign this task to me ....I am interested . Thanks

**Comment by pc-beast** [comment]
> @pc-beast I have done the registration in localhost and then when the verification mail comes to gmail and I click on the link it shows error , and also as I am unable to verify I could not able to create an event in my localhost , please help ..

Try changing hostname to ```http://localhost:4200``` in verification link.

**Comment by trngapp** [comment]
@pc-beast Yes It worked but after creating event it is not showing up on the landing page , though its showing up in the list of events I created ?

**Comment by KedarisettiSreeVamsi** [comment]
@trngapp It seems that if the events are featured then only they appear on the landing page but I don't know how to make them featured events
