### ISSUE TITLE
Make missing strings translatable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8080]
- On event dashboard: Team roles
- On team page of events: Team roles
- On discount and access code page: The table headings and content
- On event invoice overview showing status, e.g. "Resolved" (compare https://eventyay.com/account/billing/invoices/all)
- On event invoice details pages showing status (invoices linked from the overview page)
- On Create Event wizard step 1: Event type, topic, subtopic
- One Create Event wizard step 1: Timezone names of continents and cities
- On the event dashboard at https://eventyay.com/events/live (and past, draft page as well) in the column date the word "to"
In the column tickets a) "Sales" and the words in brackets "[]"
   * e.g. "paidRegistration", "freeRegistration", "free" etc. 
   * also the words should have a spacing in the English version "paidRegistration" -> "paid Registration"
![Screenshot from 2021-11-15 13-25-38](https://user-images.githubusercontent.com/1583873/141782330-ebe00a9f-cc4f-4a35-ad05-b9503c131d80.png)
![Screenshot from 2021-11-15 13-23-26](https://user-images.githubusercontent.com/1583873/141782332-13740da8-b968-4626-b8e3-6242e63edbff.png)
![Screenshot from 2021-11-13 18-49-52](https://user-images.githubusercontent.com/1583873/141653990-22e660ad-8e31-4108-8747-26aac294643c.png)
![Screenshot from 2021-11-13 18-45-38](https://user-images.githubusercontent.com/1583873/141653991-bd372392-7c56-48a9-9988-cab9909f4fc8.png)
![Screenshot from 2021-11-13 18-44-26](https://user-images.githubusercontent.com/1583873/141653992-dfdc9adc-13bd-4441-a9a1-fd1f89db95d9.png)
![Screenshot from 2021-11-13 18-40-09](https://user-images.githubusercontent.com/1583873/141653993-d40ec164-3152-4e00-b6f8-dc0d2856171c.png)

**Comment by progmatic-99** [comment]
working on it

**Comment by mariobehling** [comment]
Reopening as the following has not yet been solved

- On event dashboard: Team roles
- On team page of events: Team roles
- On event invoice overview showing status, e.g. "Resolved" (compare https://eventyay.com/account/billing/invoices/all)
- On event invoice details pages showing status (invoices linked from the overview page)
- On Create Event wizard step 1: Event type, topic, subtopic
- One Create Event wizard step 1: Timezone names of continents and cities

**Comment by progmatic-99** [comment]
![Screenshot 2021-11-16 at 17-30-06 Team tax-update-fix Veranstaltungen eventyay](https://user-images.githubusercontent.com/42090582/142000327-d56e0180-5c27-429b-aebf-f0aa70feca02.png)

**Comment by mariobehling** [comment]
Thank you. Remaining:
- On Create Event wizard step 1: Event type, topic, subtopic
- One Create Event wizard step 1: Timezone names of continents and cities

**Comment by progmatic-99** [comment]
Timezone couldn't be translated: 
https://stackoverflow.com/questions/41591377/moment-js-timezone-language-localization
