### ISSUE TITLE
Remove alt attribute from image in nav-bar

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#809]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screen shot 2017-08-26 at 12 06 20 pm](https://user-images.githubusercontent.com/12807846/29739295-cd5559d6-8a57-11e7-8431-e4c438b071e3.png)

**Comment by geekyd** [comment]
@niranjan94 Should we remove the alt attribute or add an onerror for the images?

**Comment by niranjan94** [comment]
Use the safe-image helper
