### ISSUE TITLE
Add tickets to event route(UI only)

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#81]
- [x] feature request

Add tickets to events route.

![screenshot from 2017-05-24 14-55-48](https://cloud.githubusercontent.com/assets/12807846/26396543/244c8b3a-4091-11e7-871b-6f16f68b83d2.png)

- Located at `events/<event_id>/tickets`
- Create a common component for orders, sales & tickets sold in completed orders

**Comment by sumedh123** [comment]
@niranjan94 Please assign.

**Comment by niranjan94** [comment]
This issue should handle:
- `events/<event_id>/tickets` (shown in screenshot)

But there are other pages too: (You don't have to create these routes for this issue. They will be separate issues.)
- `events/<event_id>/tickets/orders`
- `events/<event_id>/tickets/attendees`
- `events/<event_id>/tickets/discount-codes`
- `events/<event_id>/tickets/access-codes`
- `events/<event_id>/tickets/add-order`

So, the side vertical menu should be such that it is common to all pages.
