### ISSUE TITLE
Improve sentences in user interaction

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8107]
Please change the sentences as follows:
- Your billing details has been updated. -> Your billing details have been updated.
- zip -> ZIP
   - except when it is related to "zip file". In that case it should be "Zip file".
- An unexpected error occurred. -> Sorry, an unexpected error has occurred. Our developers will fix this.
- Starting time should be lesser than the ending time! -> The start time should be before the end time!
- Ending time should be greater than the starting time! -> The end time should be after the start time!
- Please enter name for track. -> Please enter a name for the track.
- Please enter a Private link. -> Please enter a private link.
- CFS start time should be before than event start time. -> CFS start time should be before event start time.
- Please tell us when your event starts. - When does your event start?
- Please tell us when your event ends. -> When does your event end?
- CFS end time should be before than event start time! -> CFS end time should be before event start time!
- Please give a start time. -> Please enter a start time.
- Please give an end time. -> Please enter an end time.
- Please enter name for microlocation. -> Please enter a name for a microlocation.
- Please add an announcement to enable call for speakers. -> Please add an announcement to enable the call for speakers.
- Please give a name. -> Please enter a name.
- Please give us your tax ID. -> Please enter your tax ID.
- Please give us your organisation name. -> Please enter the name of your organisation.
- Please give us your contact name. -> Please enter a contact name.
- Please give a city. -> Please enter a city.
- Please give a state. -> Please enter a state.
- Your speaker has been saved. -> The speaker has been saved.
- Announce event!! -> Announce event
- YES, accept payment by Purchase on invoice. -> YES, accept payment by purchase on invoice.
- YES, accept payment by Telegraphic Transfer (TT) / Bank Transfer. -> YES, accept payment by telegraphic transfer (TT) / bank transfer.
- Require Billing Information from Ticket Buyer. -> Require billing information from ticket buyer.

What is this?
- {{userThumbnailImg}}and {{followerCount}} others

![Screenshot from 2021-11-17 15-48-03](https://user-images.githubusercontent.com/1583873/142224397-1a95d60f-1790-4241-80e8-ee7231193561.png)

**Comment by mariobehling** [comment]
After the last translation changes, on the final order pages there is an issue with the "ticket name". It does not get filled in automatically anymore.

Could you also solve this here?

![Screenshot from 2021-11-17 18-31-34](https://user-images.githubusercontent.com/1583873/142251963-208983a3-ff89-4763-a2fc-6eaab8619672.png)

**Comment by mariobehling** [comment]
Ok, after testing with another ticket, it looks like the above comment is not related to the translations, but to data not loading reliably. I wonder what is the cause.

**Comment by progmatic-99** [comment]
@mariobehling ember-data maybe??
