### ISSUE TITLE
Follower count on event page only gets updated after refresh

### ISSUE THREAD

**Issue by pc-beast** [fossasia/open-event-frontend#8113]
**Describe the bug**
On event page there is a button to follow the group if the event is from a group event. If we hit the follow group button the follower count remains the same and text on the button also remains same. Expected is that the text on button should change to "Unfollow Group" and follower count must change.

**Screenshots**

![image](https://user-images.githubusercontent.com/56963647/142359681-44c0ea60-5ca0-4b25-97bb-4759f69c8535.png)

**Comment by Nitin443** [comment]
I want to Contribute on this issue. Please assign me this issue. Thank you

**Comment by Nitin443** [comment]
I' m working on this issue.

**Comment by ayushporwal1234** [comment]
can i work on this issuse

**Comment by mariobehling** [comment]
This is working as expected currently as our current architecture would make it difficult otherwise. Therefore closing this for now.
