### ISSUE TITLE
Upgrade node js version of the frontend project

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#8120]
**Is your feature request related to a problem? Please describe.**
Upgrade node js version of the frontend project

**Describe the solution you'd like**

- [ ] Check that dependencies don't break and are available for the latest version of the node js.

**Expected Outcome**
Make the full system working.

**Comment by khushbooag4** [comment]
Can I work on this issue

**Comment by Ruchip16** [comment]
Hey @codedsun @mariobehling can I work on this issue as I have already trying to do it locally so if everything goes fine I would make a PR for the same

**Comment by codedsun** [comment]
Yes! @Ruchip16 go on

**Comment by ratika-12** [comment]
@codedsun Hey  I am working on this. please assign me :)

**Comment by ratika-12** [comment]
hey @codedsun I am working on this issue.

**Comment by mariobehling** [comment]
We will not tackle this and rather work on the next version of the project. Therefore closing it.
