### ISSUE TITLE
Orders Pages show wrong total amount of order

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#8137]
**Describe the bug**
Buy a paid ticket and on the orders page sometimes the order amount is shown as 0. Please debug

**Screenshots**

![image](https://user-images.githubusercontent.com/20026440/143463300-5fcde091-5b47-4010-b766-6f5a25fddb63.png)

**Comment by subhamgcon** [comment]
Is this bug only appears after buying the ticket?

**Comment by khushbooag4** [comment]
Is anyone working on this issue. I want to work

**Comment by pc-beast** [comment]
Go ahead

**Comment by ayushporwal1234** [comment]
Can I fix it?

**Comment by codedsun** [comment]
@ayushporwal1234 Go ahead

**Comment by shrutijha16** [comment]
can i work on this issue ? @codedsun

**Comment by kkg2001** [comment]
I want to work on this issue

**Comment by devika-harshan** [comment]
Can I work on this issue

**Comment by Manmeet0504** [comment]
I want to work on this issue !

**Comment by pratik0oo7** [comment]
I want to work on this issue !

**Comment by VaibhavArora19** [comment]
I want to work on this issue!!

**Comment by KhushAhuja** [comment]
I am working on this.
