### ISSUE TITLE
Stripe or Paypal not working with Registration events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8168]
We have the option for ticketed events or registration events. If we choose Stripe or Paypal as a payment option for registration events it does not work.

Error message is: /data/attributes/payment-mode: insufficient data to verify stripe payment

![Screenshot from 2021-12-07 20-53-05](https://user-images.githubusercontent.com/1583873/145096936-3c0c75b5-5c15-41a2-9371-ca96358c7ce8.png)

**Comment by iamrahulrnair** [comment]
may i work on this ?

**Comment by codedsun** [comment]
@pc-beast What's the error here?

**Comment by codedsun** [comment]
@iamrahulrnair It's not a beginner friendly issue

**Comment by pc-beast** [comment]
Woks for me after #8167. Please test @progmatic-99 @codedsun

**Comment by progmatic-99** [comment]
It's working for me too @mariobehling
