### ISSUE TITLE
Card details not appearing correctly after paying using card through stripe

### ISSUE THREAD

**Issue by progmatic-99** [fossasia/open-event-frontend#8214]
Payment details are not shown correctly when paying through stripe using card, as shown below
Reference PR: [Payment Intent](https://github.com/fossasia/open-event-server/pull/8428)
![Screenshot 2021-12-21 at 16-06-58 Completed Order - dfb0cd22-3bf7-4ed5-adb6-da93229d1fa1 Orders Open Event](https://user-images.githubusercontent.com/42090582/147052890-1d67cbc9-de60-45d2-bf7f-2b2e0996e7e7.png)

**Comment by DawnArchi01** [comment]
Is this ticket open yet ?

**Comment by pc-beast** [comment]
Yes, this is open but there is already an open PR for this.
