### ISSUE TITLE
Enhance Styling of Language Button in the Footer!!

### ISSUE THREAD

**Issue by 4kashyadav** [fossasia/open-event-frontend#8236]
1.**What I want to do!**
I want to make the language list button more attractive!

2.**How it is looking now (When you hover over it)**

![Screenshot (3)](https://user-images.githubusercontent.com/78416508/148098109-6592ef6f-0714-4795-a8ce-91df4831414a.png)

3.**How it will look after my enhancement (When you hover over it)**

![Screenshot (4)](https://user-images.githubusercontent.com/78416508/148098115-10f25812-177c-4331-ba1a-fb2b7a12907e.png)

Please assign me !!

**Comment by mariobehling** [comment]
Not needed.
