### ISSUE TITLE
Cannot add speaker details on smartphone

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/open-event-frontend#8239]
**Describe the bug**

When I edit the Speaker Details on my phone, the page reloads when I add a photo of me.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/6b901f56/cfs/new-speaker
2. fill every text in
3. click on the photo upload
4. other App opens
5. choose photo
6. See page reloading, all Details lost

**Expected behaviour**

I would like the contents of the fields to still be there.

**Screenshots**

![Screenshot_20220106-134617](https://user-images.githubusercontent.com/564768/148394852-12ee31d6-2152-4d91-9e94-4120c5ca98af.png)

**Smartphone (please complete the following information):**
 - Device: Motorola
 - OS: Android
 - Browser Firefox "Fennec F-Droid"
 - Version 95.2.0

**Additional context**

I tried uploading no photo but that yielded an error.

**Comment by Saty248** [comment]
i think it is working fine...
![Screenshot 2022-01-16 125625](https://user-images.githubusercontent.com/68778874/149651206-b88f4776-6073-4781-a6d8-5d60710b352c.png)

**Comment by Saty248** [comment]
@niccokunzmann
