### ISSUE TITLE
Prevent organizer from saving event with paid tickets if no payment method has been added

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8246]
Currently a user can add a paid ticket and save and publish an event even if not payment method (Paypal, Stripe etc.) has been added. Expected: It should not be possible to save and publish an event with paid tickets if no payment method has been created.

![Screenshot from 2022-01-07 17-40-01](https://user-images.githubusercontent.com/1583873/148576669-3ee1beb7-904d-417d-a8d2-3349c1477a38.png)

**Comment by schezfaz** [comment]
hi, could I take this issue up?

**Comment by pc-beast** [comment]
Yes please go ahead.
