### ISSUE TITLE
Show complete attendee information on final order step before payment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8247]
On the final oder step before payment there is a box "Attendee Information". Currently this box only shows the name and email of the ticket holder. Expected is: If there are more details collected (phone, address etc.) this box should show all the info collected.

![Screenshot from 2022-01-07 19-31-37](https://user-images.githubusercontent.com/1583873/148590412-3ed6dcba-cd5b-4a68-a650-236ab435a353.png)

**Comment by Manmeet0504** [comment]
I am working on this issue !

**Comment by Pulkit3234** [comment]
Working on this issue.

**Comment by pc-beast** [comment]
Make links render with ```a``` tag.

**Comment by pratik0oo7** [comment]
Working on this issue.
