### ISSUE TITLE
Provide more payment gateways for Stripe payments

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8248]
Stripe currently only provides credit card payment options. Please activate other payment options available.

![Screenshot from 2022-01-07 19-36-22](https://user-images.githubusercontent.com/1583873/148590896-2fb7bd4e-8f04-4c20-bf77-5cbde6246a2b.png)

**Comment by vian9** [comment]
Hey I wanna try this issue

**Comment by shazm12** [comment]
Hey can i try to work on this issue?

**Comment by cweitat** [comment]
Additional gateways to be considered only after migration
