### ISSUE TITLE
Fix indentation and link sessions to speakers and vice versa

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8250]
On the pages where organizers can view submissions or speakers there is a field "Sessions" or "Speakers" respectively. The indentation is wrong. Please fix this. Also expected would be that the sessions (or speakers) link to the sessions view page (or speakers page) within the organizer area.

![Screenshot from 2022-01-08 12-22-21](https://user-images.githubusercontent.com/1583873/148642349-fb26b046-00fa-40a7-a1c4-7fa34dbdb30a.png)

**Comment by Neeteshking21** [comment]
Please assign it to me.

**Comment by ashwini-m-hub** [comment]
can I work on this

**Comment by progmatic-99** [comment]
@ashwini-m-hub Go ahead, make a PR

**Comment by mariobehling** [comment]
The session pages that can be viewed by the organizers link to the "private speakers CfS" page (e.g. https://eventyay.com/e/6b901f56/cfs/speaker/5983). They should be linking to the speakers pages that can be viewed by the organizer (e.g. https://eventyay.com/events/6b901f56/speaker/5983)

**Comment by progmatic-99** [comment]
@mariobehling The links of speakers on the session's page link to `https://eventyay.com/events/6b901f56/speaker/5983`
@pc-beast Can you also check ??

**Comment by progmatic-99** [comment]
Working fine after merging dev into master.
