### ISSUE TITLE
Exhibition Creation Form: optional field can't be empty 

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#8289]
**Describe the bug**
While creating an exhibitor, I can't leave the field "Contact Email" empty even though this field is optional (not required)

**To Reproduce**
1. Go to https://eventyay.com/events/6b901f56/exhibitors/create
2. Complete all the required field and leave the Contact Email field empty. 
3. See error "Contact Email invalid"

**Laptop (please complete the following information):**
- Ubuntu 20.04
- Browser: Chrome

**Comment by progmatic-99** [comment]
working on this
