### ISSUE TITLE
Change chat view on all pages to match the video page views

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8294]
If event chats are enabled they are are currently moved in to the right on video room pages. 

1. Please implement it in the same way on all other pages that are accessible from the left side panel of events.
2. If the users clicks "Chat" on the left side panel itself also open it on the right-hand side as a side panel.
3. Also show the chat icon on the bottom right to activate the event wide chat (if the organizer has enabled event-wide chat).

![Screenshot from 2022-01-23 19-05-20](https://user-images.githubusercontent.com/1583873/150691766-de38a056-7536-4b6f-8a61-6c5162a09f1b.png)

**Comment by Priiyaa** [comment]
Hi !
I would like to work on it! Can you please guide me through it a little?

**Comment by progmatic-99** [comment]
@pc-beast

**Comment by pc-beast** [comment]
> Hi ! I would like to work on it! Can you please guide me through it a little?

@Priiyaa please go ahead

**Comment by vian9** [comment]
Hey, I wanna work on this issue.

**Comment by progmatic-99** [comment]
@vian9 Make a PR
