### ISSUE TITLE
FOSSASIA Summit event page shows "9" in donation ticket field

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8296]
The donation ticket field shows a "9" in the FOSSASIA Summit. Expected: It should show the minimum donation ticket payment set by the organizer.

Compare https://eventyay.com/e/6b901f56

![Screenshot from 2022-01-23 20-54-51](https://user-images.githubusercontent.com/1583873/150695905-28eff0ea-b158-44c1-8dcf-8803ac9c4bf6.png)

**Comment by somendrakr** [comment]
hey can i work on this issue?

**Comment by pc-beast** [comment]
on it

**Comment by pratik0oo7** [comment]
i want work on this.
