### ISSUE TITLE
User verification: User did not receive a verification email

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#8313]
It looks like the system did not send a verification email to a user who signed up with email address that content a dot "." e.g. xx.xxxx@gmail.com. The user then used another email, then she received a verification email 

When I tried to resend a verification email from the admin panel, an error appeared. The error applied for all unverified emails. There are a lot of unverified user the last few weeks. Admin function to resend a verification email does not work.

**Comment by progmatic-99** [comment]
Not able to reproduce the error in the admin panel.

**Comment by mariobehling** [comment]
Seems to work fine at the moment. Therefore closing it.
