### ISSUE TITLE
Implement API functionality to buttons in admin/sessions

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#835]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/29916124-7640c04c-8e5b-11e7-970d-dd90c80e84e5.png)

**Comment by ritikamotwani** [comment]
@CosmicCoder96 can I add the functionality to the edit button?
