### ISSUE TITLE
Wrong donation amount at Order Summary

### ISSUE THREAD

**Issue by 0xBahamoot** [fossasia/open-event-frontend#8406]
**Describe the bug**
The service charge the correct donation amount but the amount at Order Summary show 0

**Expected behaviour**
- Show the correct donation amount

**Screenshots**
![Screen Shot 2022-03-02 at 5 28 43 PM](https://user-images.githubusercontent.com/42596389/156344918-f7446538-d258-4f95-ab7b-273b4f0d5572.png)

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser safari
 - Version 15.3

**Comment by Sankalpkokse** [comment]
hey @0xBahamoot  I would love to work on this bug.
if no one is assigned on this issue should I proceed.

**Comment by progmatic-99** [comment]
@Sankalpkokse Go ahead, make a PR!

**Comment by mariobehling** [comment]
This usually happens when you reload the page. There is an issue with ember that could cause this. Happy to see anyone solving this PR. You do not need to ask if you can work on it.

**Comment by mariobehling** [comment]
We covered this here already https://github.com/fossasia/open-event-frontend/issues/8137
