### ISSUE TITLE
Join Live Event button asks for logging in even though I am already logged in

### ISSUE THREAD

**Issue by progmatic-99** [fossasia/open-event-frontend#8411]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/6527cc1f' and click on `Join Live Event`
2. It shows a modal for logging even though I am already logged in

**Thing to note here:-** There are no tickets for this event.

![Screenshot 2022-03-08 at 11-39-34 Codeheat Coding Contest Ask Me Anything eventyay](https://user-images.githubusercontent.com/42090582/157177549-9a186e47-1c77-4637-b887-823d4172a9c4.png)

**Comment by progmatic-99** [comment]
cc: @mariobehling @pc-beast

**Comment by pc-beast** [comment]
Need to change the error message for events with no tickets.

**Comment by progmatic-99** [comment]
The end date for registration tickets for this event was of 2021. I changed that, now this is resolved.
