### ISSUE TITLE
Some events with speakers and schedule show never-ending loading icon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8418]
Some events with speakers and schedule show never-ending loading icon on left side panel.

Compare https://eventyay.com/e/4bf41cc4?side_panel=true

![Screenshot from 2022-03-10 12-49-58](https://user-images.githubusercontent.com/1583873/157656145-07c5f0f9-2bb3-4eed-8eea-329b21fa7777.png)

**Comment by progmatic-99** [comment]
@mariobehling Have you enabled the event chat for  this event??
