### ISSUE TITLE
Downloading Orders and Attendees as CSV or PDF not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8419]
When trying to download orders or attendees CSV or PDF the user is directed to a URL starting with "localhost" and download fails.

Compare https://eventyay.com/events/d36c125f/tickets/orders/completed

![Screenshot from 2022-03-10 15-43-12](https://user-images.githubusercontent.com/1583873/157741644-be6dde07-a8fe-4ca8-9600-837e6616e746.png)

Compare http://localhost/static/media/exports/2796/pdf//S3lNbXZxVE/82de69a4-1fc1-4953-b6e6-2d3a8b84fec9.pdf

![Screenshot from 2022-03-10 15-43-47](https://user-images.githubusercontent.com/1583873/157741658-c075ee0a-353a-4f70-ae7d-4b5f230ebe14.png)

**Comment by RahafTahayneh** [comment]
Hi, I would like to work on this issue, can you please assign it to me!

**Comment by saurabh15april** [comment]
@mariobehling it seems to be working -


https://user-images.githubusercontent.com/59115657/158002068-71d5db2c-f3b4-4a09-9fad-45d3c87c4028.mp4
