### ISSUE TITLE
Rooms without a schedule entry do not show up on sidepanel

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8421]
We have the option to not add a room that shows up on the side panel. The idea is that some rooms do not have a defined schedule, e.g. discussion rooms. Then we also hide the room from the schedule itself. However, it still shows up on the sidepanel. There is a condition to make this work. The condition is to publish a schedule even if the schedule is empty.

This is currently not working. Instead there is an eternal loading icon on the side panel.

Compare https://eventyay.com/e/d36c125f?side_panel=true

![Screenshot from 2022-03-12 10-32-57](https://user-images.githubusercontent.com/1583873/158012602-e1e3d731-680a-47a0-b24c-ce02c4c52dd3.png)

**Comment by progmatic-99** [comment]
Related to #8418 
Hence, closing this.

**Comment by mariobehling** [comment]
This is a different issue. It is not showing the rooms on the sidepanel + the loading icon. Therefore this is possibly different to the issue you are referring to @progmatic-99

**Comment by progmatic-99** [comment]
@mariobehling because the loading icon is not being removed from there, that is why other rooms are not showing.

**Comment by progmatic-99** [comment]
@mariobehling Have you enabled the event chat for  this event??

**Comment by mariobehling** [comment]
Thanks. Seems to be working now.

**Comment by mariobehling** [comment]
After merging it to Master it still does not work on the production system. Compare here https://eventyay.com/e/6b901f56?side_panel=true

Though loading icon is not there anymore, but rooms do not show up.

**Comment by mariobehling** [comment]
Rooms are missing.

![Uploading Screenshot from 2022-03-16 17-30-38.png…]()

**Comment by mariobehling** [comment]
Ok, current work around is to publish the schedule. That is good enough for now.
