### ISSUE TITLE
Not possible to open chat window on top of BBB room

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8424]
Compare https://eventyay.com/e/6b901f56/video/fossasia-summit-2022/577?side_panel=true

![Screenshot from 2022-03-12 14-13-59](https://user-images.githubusercontent.com/1583873/158019593-0d5d867f-fdab-4dff-8214-0285f0597d6e.png)

**Comment by progmatic-99** [comment]
What is the issue here? What behaviour do you want? Can you elaborate?

**Comment by mariobehling** [comment]
Click on "Chat" in the side panel or the chat icon on the bottom right. In my browser (Chromium) the chat does not open.

**Comment by progmatic-99** [comment]
@mariobehling You have not enabled the event chat for this event. Try with enabling the event chat.

**Comment by mariobehling** [comment]
> You have not enabled the event chat for this event. Try with enabling the event chat.

This comment does not make sense. The menu item "Chat" and the chat icon are visible on the screenshot. Chat is enabled, but if there is a BBB room active, it does not work.
