### ISSUE TITLE
ICS calendar Timezone ID is set to "Country" instead of "Continent/Country"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8427]
The registration confirmation generated icalendar TZID is set to "Singapore" instead of "Asia/Singapore" and triggers error on mail client.

**Comment by SiddheshKukade** [comment]
Please at least provide the steps to reproduce the bug

**Comment by mariobehling** [comment]
Get calendar ics by clicking on the option on the right side panel of an event e.g. https://eventyay.com/e/6b901f56

![Screenshot from 2022-03-18 06-55-29](https://user-images.githubusercontent.com/1583873/158945717-044f7bab-4786-494c-b8bc-d6f86a3ca275.png)

**Comment by mariobehling** [comment]
Here is a report on the Telegram user channel

> Alvin Ho:
🖼 hi guys. i was trying to replicate this problem the last week or so in thunderbird. it seems 2 b complaining abt the time zone format. Unfortunately error console is an add on product for thunderbird & i'm planning on reinstalling this partition some time soon so don't wish 2 install anything new.
hi guys. i was trying to replicate this problem the last week or so in thunderbird. it seems 2 b complaining abt the time zone format. Unfortunately error console is an add on product for thunderbird & i'm planning on reinstalling this partition some time soon so don't wish 2 install anything new.

> Alvin Ho:
apologies.. i jus looked at 1 of the mozilla help pages on error console, they say tools ➡️ developer tools ➡️ error console. Heres the content 👇🏽 its long, so apologies for including it here.

> Alvin Ho:
Calendar: Couldn't find Singapore CalTimezoneService.jsm:206
Calendar: Unknown timezone "Singapore" in "FOSSASIA Summit 2022".  Treated as 'floating' local timezone instead: Thursday, 7 April 2022 21:00
BEGIN:VCALENDAR

PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN

VERSION:2.0

BEGIN:VEVENT

UID:6b901f56

SUMMARY:FOSSASIA Summit 2022

ORGANIZER:The Summit is organized in cooperation between FOSSASIA and OpnT

 ec. FOSSASIA develops Open Source software and hardware solutions with a g

 lobal developer community from its base in Asia and organizes Open Technol

 ogy events around the year. The mission of FOSSASIA is to improve people's

  lives by sharing open technologies, knowledge and resources and building 

 a sustainable FOSS ecosystem. Projects include <a href="https://susi.ai/" 

 rel="nofollow" target="_blank">conversational AIs</a>, <a href="https://ps

 lab.io/" rel="nofollow" target="_blank">science applications</a> and <a h

 ref="https://eventyay.com/" rel="nofollow" target="_blank">event managemen

 t tools</a>. The organization supports its most promising teams through a 

 business incubator and runs coding programs and development contests like 

 <a href="https://codeheat.org/" rel="nofollow" target="_blank">Codeheat</a

 > to grow the developer community.<br><br>FOSSASIA Key Facts<br><ul><li>F

 OSSASIA is based in Singapore</li><li>Develops <a href="https://github.com

 /fossasia" rel="nofollow" target="_blank">open source projects</a> since 

 2009 with 5000+ registered developers on GitHub</li><li>Trains 3000+ devel

 opers through <a href="https://codeheat.org/" rel="nofollow" target="_blan

 k">coding programs</a> annually</li><li>Organizes dozens of meetings at d

 eveloper events, hackathons and workshops throughout Asia every year</li><

 li>Shares information with 40,000+ developers on mailing lists and social 

 media</li></ul>

DTSTART;TZID=Singapore:20220407T130000

DTEND;TZID=Singapore:20220409T180000

DESCRIPTION:<p>Join us at the FOSSASIA Virtual Summit 2022 to learn about 

 the latest development in open source technologies and to connect with dev

 elopers\, tech communities\, and companies from around the world. </p><p>

 The event will take place from Thursday\, 7th April to Saturday\, 9th Apri

 l. The FOSSASIA Summit is a unique event with a broad range of open techno

 logy topics such as web and mobile technologies\, Javascript\, Python\, cl

 oud services\, artificial intelligence\, Open Hardware and production\, pr

 ivacy\, security\, digital sovereignty\, Blockchain\, DevOps\, databases\,

  kernel and platform\, Open Source licences and compliance\, open health t

 ech and Covid-19\, Open Science\, Open Source culture and circular economy

 .</p><p>The first FOSSASIA event took place in 2009. Apart from establishe

 d open source projects the FOSSASIA Summit is a place to discover upcoming

  developers and new projects in the open tech community in particular from

  Asia. </p>

LOCATION:https://eventyay.com/e/6b901f56

URL:https://eventyay.com/e/6b901f56

END:VEVENT

END:VCALENDAR
