### ISSUE TITLE
Chat icon visible even if user has not joined event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8438]
The chat icon of an event is visible even a user has not joined an event. Expected: Only user who have a ticket and who have joined an event (through the blue join event button) should see the chat icon. This means only when the sidepanel is activated should the chat be available.

![Screenshot from 2022-03-17 14-33-35](https://user-images.githubusercontent.com/1583873/158819944-223b2cfd-43b8-4290-b165-997a926148ed.png)

**Comment by SiddheshKukade** [comment]
I am logged in But not regisgtered or joined this event

**Comment by SiddheshKukade** [comment]
![image](https://user-images.githubusercontent.com/65951872/158942105-461597ec-1f15-441a-9194-a96787204f97.png)
I am also logged but not registered but I can't  see any chat button....
