### ISSUE TITLE
Add Public Stream URL

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8465]
On wizard step 1 below “online” and text “You can add video meeting rooms or streams after you created a draft of the event.” add a form field for a Youtube or Vimeo URL. 

If the user adds a link here embed the video above the event description on the main event page.

Event wizard
![Screenshot from 2022-03-29 16-01-25](https://user-images.githubusercontent.com/1583873/160628904-a79b58cc-099a-4921-bdbf-8d3b6623c8cf.png)

**Comment by mariobehling** [comment]
Getting errors on test site, compare https://test.eventyay.com/e/a86f2bbb

![Screenshot from 2022-04-01 16-27-08](https://user-images.githubusercontent.com/1583873/161283568-8b002856-4a31-4153-969a-29949b056e33.png)


The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.
chromewebdata/:1 Refused to display 'https://www.youtube.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

**Comment by mariobehling** [comment]
The last change also has the effect to create big white spaces on a number of pages, e.g. start page and wizard pages. It also results in lines getting cut off from the event tiles on the left hand side on the start page.

![Screenshot from 2022-04-01 16-28-48](https://user-images.githubusercontent.com/1583873/161284265-095aa1f0-8324-4eb3-a453-29d9e8772bec.png)
![Screenshot from 2022-04-01 16-28-19](https://user-images.githubusercontent.com/1583873/161284269-35d9b242-e094-4c90-832d-78b60efdf699.png)

**Comment by mariobehling** [comment]
Ok, I got the issue with the embed. It is necessary to use the embed link, e.g. https://www.youtube.com/embed/dzn8ncyx-NA instead of https://www.youtube.com/watch?v=dzn8ncyx-NA. However, in other places on the system and on other systems users can simply copy the Youtube URL and get that working immediately. So, it would be best if it would work in the same way here as well.

**Comment by mariobehling** [comment]
Please position the video above the description text.

![Screenshot from 2022-04-01 16-37-57](https://user-images.githubusercontent.com/1583873/161285547-21e0b07c-30e4-4fa8-9495-d29050416f3b.png)

**Comment by mariobehling** [comment]
I also see a spacing added above event header images. Well, please check all these details in a follow-up PR.

**Comment by mariobehling** [comment]
Last PR resulted in unexpected error on the front page.

![Screenshot from 2022-04-03 12-04-44](https://user-images.githubusercontent.com/1583873/161422332-e478e67d-9130-49a5-b87d-70be4af9a2fb.png)

**Comment by mariobehling** [comment]
Also, I am no longer able to login. Giving error message too.

**Comment by pc-beast** [comment]
Not because of this PR. Its from server.

**Comment by mariobehling** [comment]
ok, thanks.

Please also add some spacing between the bottom of the video and the description text.

![Screenshot from 2022-04-03 17-31-40](https://user-images.githubusercontent.com/1583873/161435575-cb87ce6b-ef6b-4ae0-82ea-da19846753e9.png)
