### ISSUE TITLE
Provide option to autoplay and loop videos on public event pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8473]
We now have the option to add streams into public pages. Please add the option to autoplay and loop these streams.

![Screenshot from 2022-04-01 18-27-42](https://user-images.githubusercontent.com/1583873/161304394-2fb7d969-4ac9-41ea-816e-73c2d0e710d0.png)

Compare video tab where this option is already available for Youtube and Vimeo streams.

![Screenshot from 2022-04-01 18-30-53](https://user-images.githubusercontent.com/1583873/161304768-8b1c6713-22e3-41e1-bee9-9dd6ad797633.png)

**Comment by mariobehling** [comment]
It is neither working with https://www.youtube.com/watch?v=dzn8ncyx-NA nor with https://www.youtube.com/embed/dzn8ncyx-NA on the test event at https://test.eventyay.com/e/a86f2bbb Therefore reopening it.

**Comment by mariobehling** [comment]
![Screenshot from 2022-04-04 21-56-10](https://user-images.githubusercontent.com/1583873/161621767-510c87d1-f7d7-4c66-aa82-ebf36d804c44.png)

**Comment by pc-beast** [comment]
Just need to enter video-id now ```dzn8ncyx-NA``` in this case. Changed it in settings, it's working now.
https://test.eventyay.com/e/a86f2bbb

**Comment by mariobehling** [comment]
Autoplay does not work for me yet.

**Comment by progmatic-99** [comment]
After this https://github.com/fossasia/open-event-frontend/pull/8487, it's working fine.
@mariobehling
