### ISSUE TITLE
Order form: Show agreement tick boxes only once

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8535]
If a user gets several tickets of an event the agreement tick boxes (photo agreement, terms etc.) show up several times.

Make the three agreement tick box options appear only one time no matter how many tickets the user gets.

The tick boxes should appear on the bottom of the order form below all tickets.

![Screenshot from 2022-04-23 00-34-05](https://user-images.githubusercontent.com/1583873/164756855-31f1cf57-b6b1-4d27-a4f3-82207f36b313.png)

**Comment by progmatic-99** [comment]
What if some of the attendees for which the user is buying tickets, wants different permissions for the agreement boxes??

**Comment by mariobehling** [comment]
Ok, let me check how eventbrite is doing it.
