### ISSUE TITLE
Ticket order form for multiple tickets: Enable user to only enter information once

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8536]
For events that have several tickets, e.g. exhibition ticket, workshop ticket, social event ticket etc. a user has that gets several tickets needs to enter their credentials several times. Please add a tick box "Same as ticket 1", "Same as ticket 2" etc. if the event has several tickets.

Add the box below the line "Ticket Holder 2", "Ticket Holder 3" etc.

![Screenshot from 2022-04-23 00-42-21](https://user-images.githubusercontent.com/1583873/164758092-58fb0c48-56ef-4029-8fe5-4018cb72d6c5.png)

**Comment by Anup0099** [comment]
I would like to work on this issue. Please assign this issue to me. @mariobehling

**Comment by Anup0099** [comment]
I am working on this issue.

**Comment by rana-shoaib** [comment]
can I work on this issue?

**Comment by chiragjindal123** [comment]
I will do that for you. assign it to me @mariobehling

**Comment by mubasharofficial** [comment]
Hi, I want to work on this issue. Could fix this issue within  minimum time.

**Comment by UtkarshM-hub** [comment]
you can work on this issue
