### ISSUE TITLE
Add location auto complete to explore location search box

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#86]
<img width="1680" alt="screen shot 2017-05-25 at 11 30 00 pm" src="https://cloud.githubusercontent.com/assets/2404372/26463523/37000dda-41a2-11e7-895b-59f1acb65129.png">

- Located at `/explore`
- To use the `widgets/forms/location-input` component. The component has to be slightly modified to allow hiding of the 'Enter Address' button if and when needed.

**Comment by geekyd** [comment]
@niranjan94 I'm working on this.
