### ISSUE TITLE
Time format mixed up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8637]
The time format is sometimes following EU continental format mixed up with other formats in the same line, e.g. 16.30 - 4.50.

![Screenshot from 2022-10-11 13-23-35](https://user-images.githubusercontent.com/1583873/195077783-4512f5a6-e710-4415-a68e-8fdc2650d9f4.png)

**Comment by subhradwip01** [comment]
I would like to work on that problem

**Comment by Santoshkumbhkar1** [comment]
i want to work on this problem

**Comment by harshitraisahab** [comment]
@mariobehling it would easily be fixed by JavaScript please assign to me

**Comment by aniket2468** [comment]
I can fix this, please assign me this issue

**Comment by maze-runnar** [comment]
@SARTHAK1SINGH please pick this. 
cc: @mariobehling
