### ISSUE TITLE
Stripe payment not possible for some user accounts 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8649]
Test on event: https://eventyay.com/e/7cfe0771

![Screenshot from 2022-11-28 18-07-03](https://user-images.githubusercontent.com/1583873/204339731-8f3c7f97-5570-4e40-87e4-a88ec2c9ba27.png)

![photo_6064338559340492040_y](https://user-images.githubusercontent.com/1583873/204339856-78c3fa0b-0597-4314-9004-21fe4c5783f2.jpg)

Browser Console shows:

`Object { isAdapterError: true, stack: "n@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10688:19\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10692:54\nhandleResponse@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10762:26\nhandleResponse@https://eventyay.com/assets/open-event-frontend-f5067d25fd25b6bb5d8a4cce077d3985.js:45:256\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:3274:9\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10729:14\najax/</f.error/i<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:8\najax/</f.error@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:19\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:175:118\nfireWith@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:176:694\nS@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:458:468\nsend/n/<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:469:206\n", description: undefined, fileName: "https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js", lineNumber: 10688, message: "Ember Data Request GET https://api.eventyay.com/v1/events/3048/stripe-authorization returned a 500\nPayload (application/vnd.api+json)\n[object Object]", name: "Error", number: undefined, code: undefined, errors: (1) […], … }
​
__sentry_captured__: true
​
code: undefined
​
description: undefined
​
errors: Array [ {…} ]
​
fileName: "https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js"
​
isAdapterError: true
​
lineNumber: 10688
​
message: "Ember Data Request GET https://api.eventyay.com/v1/events/3048/stripe-authorization returned a 500\nPayload (application/vnd.api+json)\n[object Object]"
​
name: "Error"
​
number: undefined
​
stack: "n@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10688:19\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10692:54\nhandleResponse@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10762:26\nhandleResponse@https://eventyay.com/assets/open-event-frontend-f5067d25fd25b6bb5d8a4cce077d3985.js:45:256\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:3274:9\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10729:14\najax/</f.error/i<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:8\najax/</f.error@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:19\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:175:118\nfireWith@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:176:694\nS@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:458:468\nsend/n/<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:469:206\n"
​
<prototype>: Object { stack: "" }
[vendor-d25d2227ee34f2f621a17bdef3970eef.js:20186:36](https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js)`

It also shows:

`Object { isAdapterError: true, stack: "n@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10688:19\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10692:54\nhandleResponse@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10762:26\nhandleResponse@https://eventyay.com/assets/open-event-frontend-f5067d25fd25b6bb5d8a4cce077d3985.js:45:256\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:3274:9\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10729:14\najax/</f.error/i<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:8\najax/</f.error@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:19\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:175:118\nfireWith@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:176:694\nS@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:458:468\nsend/n/<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:469:206\n", description: undefined, fileName: "https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js", lineNumber: 10688, message: "Ember Data Request GET https://api.eventyay.com/v1/events/3048/stripe-authorization returned a 500\nPayload (application/vnd.api+json)\n[object Object]", name: "Error", number: undefined, code: undefined, errors: (1) […], … }
​
__sentry_captured__: true
​
code: undefined
​
description: undefined
​
errors: Array [ {…} ]
​
fileName: "https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js"
​
isAdapterError: true
​
lineNumber: 10688
​
message: "Ember Data Request GET https://api.eventyay.com/v1/events/3048/stripe-authorization returned a 500\nPayload (application/vnd.api+json)\n[object Object]"
​
name: "Error"
​
number: undefined
​
stack: "n@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10688:19\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10692:54\nhandleResponse@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10762:26\nhandleResponse@https://eventyay.com/assets/open-event-frontend-f5067d25fd25b6bb5d8a4cce077d3985.js:45:256\nn@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:3274:9\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10729:14\najax/</f.error/i<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:8\najax/</f.error@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:10772:19\nu@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:175:118\nfireWith@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:176:694\nS@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:458:468\nsend/n/<@https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js:469:206\n"
​
<prototype>: Object { stack: "" }
[vendor-d25d2227ee34f2f621a17bdef3970eef.js:20186:36](https://eventyay.com/assets/vendor-d25d2227ee34f2f621a17bdef3970eef.js)`

**Comment by progmatic-99** [comment]
working on this

**Comment by AnmolBansalDEV** [comment]
not able to reproduce it, as the stripe option is not showing for me. Maybe because I'm India.

**Comment by mariobehling** [comment]
The error that is showing when trying to add Stripe
> Missing url param: "client_id". (Looked for: property named "clientId".. Please try again.

https://test.eventyay.com/create
![Screenshot from 2023-05-23 10-37-33](https://github.com/fossasia/open-event-frontend/assets/1583873/d1f971ca-7f28-48ab-a5ca-eeda36636d0f)

**Comment by minhho89** [comment]
**The Stripe problem**

Stripe transactions can be successfully worked in test mode.
However, after the payment with Stripe is done, there is no change in the DB (probably from the backend side) that changes the payment's state. The payment status remains “Pending” afterward => Backend side -> @catInOrbit  will create a sub-issue for this.

Another problem in API calls in the front-end (not related directly to the above issue)
Front-end calls to v1/events/[event_id]/event-copyright which is not defined in the backend.
The correct API is  v1/events/[event_id] only. event-copyright is a field inside the JSON response from this call.
=> Frontend side -> @lequoctrung-it  will create a sub-issue for this.

**Comment by catInOrbit** [comment]
Frontend api problem was because /v1/events/{event_identifier}/edit/basic-details page is making call to JSON response of API endpoints rather than the actual API as shown below. This may impact linking of stripe


![Image](https://github.com/fossasia/open-event-frontend/assets/49814026/bf4649ca-d49f-43f4-92ba-dc994c4a7c96)



![Image](https://github.com/fossasia/open-event-frontend/assets/49814026/2e3a0a71-73f0-438f-8083-a655ff1b4f05)


For backend, provided that stripe_secret_keys are configured correctly in settings table and /v1/stripe_authorization can query it up, and if users have valid stripe account set up. Then it works fine every time as shown here

https://drive.google.com/file/d/1VXMTOqidpIyBZZFoEI2_LwMXPnRcPsr5/view?usp=drive_link

The /verfiy issue above was due to dockerhub eventyay image is not up-to-date with the development branch causing stripe failure, this will be ignored

**Comment by lequoctrung-it** [comment]
The issue is tested and solved by @catInOrbit in Production environment as comment above. 

About the sub-issue copy-right @minhho89 mentioned, It should be open as another ticket because It is not a part of Stripe payment problem. The workflow to buy a ticket can get through like this [video](https://drive.google.com/file/d/1vohJAvCwMezS-AD8GzLpdibp5ATXkaB_/view?usp=sharing).

Moreover, the stripe-authorization API returned a 500 status code(trying to query not-existing item) is called duplicated, the second API is 200 OK. As my testing, It also not impact the workflow. This is also should be for another ticket to enhance performance and prevent the duplication. 

@mariobehling  @cweitat  please have a look about this and close the ticket.
