### ISSUE TITLE
Youtube link in the footer not working

### ISSUE THREAD

**Issue by ritikamotwani** [fossasia/open-event-frontend#865]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

href attribute is misspelled.

**Comment by ritikamotwani** [comment]
I would like to work on it.

**Comment by vaibhav16uec121** [comment]
i would like to work on it
