### ISSUE TITLE
Email confirmation not arriving

### ISSUE THREAD

**Issue by heliocastro** [fossasia/open-event-frontend#8659]
The registration page is requesting email confirmation.

Tried both company email and personal email, completely different email providers, it never arrived even on Spam box.

Thanks in advance

**Comment by sourav8927** [comment]
@heliocastro  i wanna work on this issue. please assign this to me and since i m new to this repo so please guide me through.

**Comment by sourav8927** [comment]
i am working on the issue !

**Comment by kartikver15gr8** [comment]
Hey @heliocastro 
Can you tell me a bit more about the issue!

**Comment by perminder-17** [comment]
unable to find the code where the changes must be done....can someone help me with this problem

**Comment by perminder-17** [comment]
i want the backend file in which i can go on with this issue...please help me where it can be

**Comment by mariobehling** [comment]
We switched the Email provider in the meantime. I hope this resolved the issue. If not please reopen the issue.
