### ISSUE TITLE
Mastodon link is wrong

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/open-event-frontend#8667]
**Describe the bug**

Mastodon is with several servers. This field forequires a URL input like `Website`.

**To Reproduce**
Steps to reproduce the behaviour:

See https://www.eventyay.com/events/4705d367/edit/other-details

**Expected behaviour**

Just a field for the URL or two: server + username

**Screenshots**

![image](https://user-images.githubusercontent.com/564768/216612518-57f631d2-6f95-494d-8d28-213f77d87f3d.png)

We need the field to be using https:// instead of https://mastodon.com/

**Desktop:**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Firefox 109

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sourav8927** [comment]
@niccokunzmann  i wanna work on this issue. please assign this to me and since i m new to this repo so please guide me through.

**Comment by sourav8927** [comment]
i  am working on this issue

**Comment by ashish07-07** [comment]
is  any one working on this issue

**Comment by perminder-17** [comment]
I am working on this issue

**Comment by lthanhhieu** [comment]
I would like to pick this ticket.
Thanks
