### ISSUE TITLE
Mobile Screen Schedule often refreshes, issues from lazy loading

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8675]
The experience of looking at schedules on mobile screens is bad since lazy loading is used, compare https://eventyay.com/e/7cfe0771/schedule.

The screens often requiring refreshing. Scrolling down suddenly skips sessions and if the user is inactive the entire schedule needs to be reloaded. 

Should the schedule of each day be fully loaded instead of lazy loading?

**Comment by Leslie-Wong-H** [comment]
Intuitive reason: 
https://github1s.com/fossasia/open-event-frontend/blob/HEAD/app/templates/public/sessions.hbs#L128-L129
In mobile view, the `ember-infinity` component somehow does not disappear when finishing fetching the exact next page. The table above gets re-rendered but does not push the extra space down but up, so InfinityLoader keeps occupying the space and fetching data until all session data is fetched. 

![test](https://github.com/fossasia/open-event-frontend/assets/27696701/9f1643d0-212c-4790-ba0e-cc9e8c905fcb)

`ember-infinity` docs says,
> Whenever the infinity-loader component is in view, we will fetch the next page for you. [source](https://github.com/ember-infinity/ember-infinity#response-meta-expectations)

**Comment by Leslie-Wong-H** [comment]
Surprisingly, they forgot to add a unique key to the for-loop rendering, a common pitfall faced by all JavaScript frameworks.

╯︿╰

https://github.com/Leslie-Wong-H/open-event-frontend/blob/311439dfff908cbe4200849a8eb91cd980b234de/app/templates/public/sessions.hbs#L89
![image](https://github.com/fossasia/open-event-frontend/assets/27696701/ae607b0c-15e7-47c8-a7e6-12ca2f396c27)

It works fine this way. PR coming soon.

**Comment by Leslie-Wong-H** [comment]
![lazyload](https://github.com/fossasia/open-event-frontend/assets/27696701/2fd1baaa-06dd-4a50-a7d4-b6d9dd0191ae)
