### ISSUE TITLE
Do not show social links on right side bar on schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8678]
The schedule page show social links. Please take out the social links on this page.

![Screenshot from 2023-05-29 15-28-00](https://github.com/fossasia/open-event-frontend/assets/1583873/bb718d3e-eea1-44fe-830f-a6c3a4af17e8)

**Comment by Nitishupkr** [comment]
Can u assign me this

**Comment by Nitishupkr** [comment]
I n working on it
