### ISSUE TITLE
On tab "past" of event management dashboard show recent events on top

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8679]
On the event management dashboard on the tab "past" sort the events with the recent events showing up on top, compare: https://eventyay.com/events/past

Do not change the order of the live and draft event tab.

![Screenshot from 2023-04-29 13-44-44](https://user-images.githubusercontent.com/1583873/235285945-3936750d-6e5f-45bd-be07-144815e1dbe5.png)

**Comment by SimardeepSingh1450** [comment]
Please assign this issue to me, so I can start working on it.

**Comment by mariobehling** [comment]
Closing as out of scope for this development cycle.
