### ISSUE TITLE
Sessions and Speakers dummy buttons

### ISSUE THREAD

**Issue by ivanborislavov** [fossasia/open-event-frontend#868]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
The Submit button in Session creator, does nothing when clicked. The Speaker creation button does nothing when clicked.

**Expected behavior:**
The buttons should work, and lead to the next page.

**Comment by Anupam-dagar** [comment]
I would like to work on it.
Can you tell me where I can find these buttons.

**Comment by ivanborislavov** [comment]
![1](https://user-images.githubusercontent.com/31080768/30250086-7953d230-9651-11e7-9852-9f687537113c.png)
 The Submit button here

![2](https://user-images.githubusercontent.com/31080768/30250090-87aa6c54-9651-11e7-891e-ff8944a37e82.jpg)
The Add a speaker button here

**Comment by geekyd** [comment]
@Anupam-dagar @ivanborislavov This will be done after merging #849

**Comment by geekyd** [comment]
Closing this via #880

**Comment by ivanborislavov** [comment]
Is the fix going to be applied to www.nextgen.eventyay.com/ ??
