### ISSUE TITLE
Add Options for Badges in Wizard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8683]
Add options for badges in the event wizard after "Attendee Form".

Provide a button "Switch on/off".

![Screenshot from 2023-04-30 21-42-26](https://user-images.githubusercontent.com/1583873/235356059-5f8ec235-51f4-4c1d-8892-b7f3dcd87b10.png)

Allow organiser to choose fields from a dropdown to show and no duplicates

- Name
- Organisation
- Position
- QR code (to show if option to be used for checkin and sharing of contact info is true)

When the user chooses "QR Code" also provide the option to include more info through a dropdown menu with tickboxes, e.g. if the user wants to include Email, Website, and Linkedin in the Barcode. On scan, .vcf contact file will be downloaded

![Screenshot from 2023-04-30 22-44-33](https://user-images.githubusercontent.com/1583873/235359354-66a6dfb3-cf3c-4c2a-8bbb-ca560b490eb3.png)

Compare: https://help.eventnook.com/en/articles/6005872-how-to-customize-event-badge

In the badge template, there are essential options to customize:
* the Badge Size, Badge Orientation, and Badge Color. 
* the fields inside the badge, such as the delegate's name, company, job title, category, QR Code
* the styling of the font such as Font Size, Alignment, Text Style (such as Upper Case, Lower Case, etc.) 
* Custom paper sizes
* As the user designs the badge, they can preview the final result of the badge.

Finally provide a button below which lets the user download a sample PDF.

> Download Example Badge

**Comment by marcoag** [comment]
There's https://github.com/fossasia/badgeyay which is also emberjs, code can be reused from that project for this.

**Comment by mariobehling** [comment]
From @lthanhhieu  
![mockup-badges-ui](https://github.com/fossasia/open-event-frontend/assets/1583873/8dbfcebd-2b81-4785-815a-9c5fbb0d73fd)

I would like to share with you the attached image, which represents the UI Mockup for ticket [#8683: Add Options for Badges in Wizard](https://github.com/fossasia/open-event-frontend/issues/8683).

Could you please to review the image and provide any feedback or requirements you may have.

Apart from that, could you kindly tell me what happens next after the badge is created? We'll send it to attendees through email, make a link for them to download, or display it someplace on the front end so they may print the badge?

**Comment by cweitat** [comment]
@lthanhhieu the template is stored at backend and retrieved to generate and compile the data into PDF which is taken via API to print as mentioned here: https://github.com/fossasia/open-event-server/issues/8955

![image](https://github.com/fossasia/open-event-frontend/assets/11439477/aa0c5e6d-2a11-4e26-afd8-71950549f0e2)
Do add the following instructions at the arrow similar to this
![image](https://github.com/fossasia/open-event-frontend/assets/11439477/c04bbf52-b2dc-4996-8e32-256e07a9e639)

**Information about Badge Creator**
This badge creator lets you position the data that is going to be printed on the badge. Do note that the image is for PREVIEW only and not going to be printed 

- as a start, page size we can go with 4x3inch and 4x6inch (and also display in mm)
- Customisable margin top left right down for each field
- No rounded corner
- Font name and font colour can be excluded
- Text alignment can be set to center
- Maximum rows should tally with the number of fields available

Do factor in if the field overflows to another line as well

![image](https://github.com/fossasia/open-event-frontend/assets/11439477/727db0e2-3db0-4d9c-9bee-78660a7c9daf)

Upload of image is to preview of how the image looks like but is not going to be printed

**Comment by cweitat** [comment]
Flow of map
![image](https://github.com/fossasia/open-event-frontend/assets/11439477/204655c2-b76e-492c-a712-7d837e0d37c2)

**Comment by lthanhhieu** [comment]
Up date meeting note for this issue:
- Fields are missed when combine 2 ticket types  Show warning for Organizer to notify that the fields are not available. Warning sample: <field_name> is not available in ticket <ticket_name>
- Only text can be printed, the background only show for reviewing.
- Generate PDF at server and send the link for user to download. (Following the ticket[: Return a PDF for badge printing from server #8955](https://github.com/fossasia/open-event-server/issues/8955))
- If organizer chooses the QR code when create badge template, that will be always show when user print the badge.
- When user selects the fields to show, keep the field same position in template.
- Adding all options from screenshot for Font Setting.
•	Each language has at least 1 font supported.
•	At least 1 font supports all languages.

**Comment by lthanhhieu** [comment]
Hi @mariobehling @cweitat 
New update for add row. We already added font and position.
Please let me know if you need to change any.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/b3c4f9c5-8218-4093-93ff-b17633264a8d)

**Comment by mariobehling** [comment]
Thank you. Looks good.

**Comment by mariobehling** [comment]
In regards to the QR code. The QR code should be in VCF card format and have the following fields
* Email
* All fields that the organizer decided to display on the badge
* Ticket ID in a custom form field

**Comment by cweitat** [comment]
@lthanhhieu previous UI was missing upload image label. do remember to add that as well

**Comment by lthanhhieu** [comment]
> @lthanhhieu previous UI was missing upload image label. do remember to add that as well
We also did it mr. @cweitat 
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/826f1f3d-febe-479d-b4a9-1a2fd81c739f)

**Comment by lthanhhieu** [comment]
From MR. @cweitat 

> in VCF, u can create custom fields
> so there should be a field named "EVENTYAY" that returns the ticket id
> that i can retrieve to do for scanning
