### ISSUE TITLE
When user loads order confirmation page after initial registration ticket info and price often disappear

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8687]
When user loads order confirmation page after initial registration ticket info and price often disappear or the line below for Ticket Type, Price, and Subtotal disappears or shows the wrong amount.

![image](https://user-images.githubusercontent.com/20026440/143463300-5fcde091-5b47-4010-b766-6f5a25fddb63.png)

**Comment by Nitishupkr** [comment]
Can u assign me this

**Comment by Nitishupkr** [comment]
I m working on it
