### ISSUE TITLE
User login not permanent even if user chooses remember me

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8689]
The remember me function usually ensures that a users stays logged in for a longer time. With eventyay users get logged out if they go offline or do not use the system for some time.

![Screenshot from 2023-05-01 23-34-19](https://user-images.githubusercontent.com/1583873/235479110-094154fb-6918-46b2-b518-5979cbf89722.png)

**Comment by thongphp** [comment]
I saw that, when I enable "Remember me" the cookie for store authentication user has period for 1 year. That's mean they can close browser (without clear cookie) and re-open browser, they will stayed logged-in during 1 year period.

`users get logged out if they go offline.` --> Could you specific more detail about this. In theory, if user don't clear browser cookie they could stay logged in.

**Comment by Tusharjain123** [comment]
Can I work on this issue?
