### ISSUE TITLE
Create ticket purchase page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#87]
![screencapture-eventyay-orders-242979c2-9453-4e69-be3f-da3b3a8824d9-1495739435778](https://cloud.githubusercontent.com/assets/2404372/26466327/09744e80-41ac-11e7-9972-5c8cf89c49c7.png)

---

- For now, can be located at `/orders/new`. (In future, it will be at `/orders/<order_identifier>`
- Form validation required
- Autofill feature not required now. Just radio button should be enough.
- 3 components
    - Order summary
    - When and where (event quick info)
    - Order form
- Payment option images -> ([Paypal Payment logo](https://eventyay.com/static/img/paypal_logo.png), [Stripe Payment logo](https://eventyay.com/static/img/stripe_logos.png))

**Comment by harshitagupta30** [comment]
Can I work on this?

**Comment by niranjan94** [comment]
Yes. After #85

**Comment by harshitagupta30** [comment]
sure! Thanks :+1: I have made changes as you suggested! Please review it and let me know I need to do any further improvements.

**Comment by harshitagupta30** [comment]
@niranjan94 Can I start working on this?

**Comment by niranjan94** [comment]
Sure @harshitagupta30

**Comment by harshitagupta30** [comment]
@niranjan94 Just wanted to confirm one thing. This will be generated using this command `ember g route orders/new` or do I need to pass the event_id as well?

**Comment by niranjan94** [comment]
@harshitagupta30 no required id for now.

**Comment by harshitagupta30** [comment]
@niranjan94 From where can I get list of all countries to add to the drop down or Do I need to write all country names?
