### ISSUE TITLE
Speaker Email does not get saved after option is made mandatory

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8701]
If an organizer enters a speaker email, the email has to be entered. After it is activated and saved the Email address is not actually saved in the system. Expected: After activating and entering the speaker email, it should be saved.

![Screenshot from 2023-05-13 14-56-50](https://github.com/fossasia/open-event-frontend/assets/1583873/75e06d46-8874-4e14-9fde-94664f5f6bb8)
![Screenshot from 2023-05-13 14-56-39](https://github.com/fossasia/open-event-frontend/assets/1583873/ef16c2cb-b372-442b-b463-d561579b89d1)

**Comment by SoumyadeepOSD** [comment]
Can I work on it?

**Comment by AnanyaJhaldiyal** [comment]
Hello, I would like to contribute.

**Comment by Zaymes** [comment]
I do not see the bug existing in the current test server. Is it already resolved or is a bug on the deployed production? Please tell me if I am missing something.
![Screenshot from 2023-05-28 17-12-56](https://github.com/fossasia/open-event-frontend/assets/28755348/ad511e04-203f-4f8e-88d1-aa420a977995)

**Comment by lthanhhieu** [comment]
I would like to pick this ticket.
Thanks
