### ISSUE TITLE
Upgrade nodejs to version 16

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8738]
Some tests are failing as node.js is not being used in version 16 at least. Please upgrade node to v16.

Compare .github/workflows/ci.yml
Also compare https://github.com/fossasia/open-event-frontend/blob/7f42040a5278e7d9deeea366509e506a8239b2f8/package.json#L169

**Comment by cweitat** [comment]
@mariobehling node cannot be v16 for now. The max would be v14.x.x as stated in the package.json. anything about that will start breaking legacy plugins

**Comment by Leslie-Wong-H** [comment]
![Screenshot_20230526_064705_com.github.android_edit_763660157448893.jpg](https://github.com/fossasia/open-event-frontend/assets/27696701/01ae8ca8-4ef9-4292-b9b7-467276dde288)

**Comment by minhho89** [comment]
The problem could be because the library `node-gyp` calls to `node-sass` which no longer supports Node v.16

**Comment by cweitat** [comment]
@minhho89 yes you are right, but this package is needed to compile the SASS so would need to find an alternative package instead but I believe that would require python to be upgraded to v3 as the current script runs with 2.8

**Comment by minhho89** [comment]
I tried add the `node-sass` and `node-gyp` directly to the `pagake.json` and it bypassed the problem.
However, after doing this, there is another problem araised  with `l10n`. 
Trying to fingure it out.

**Comment by minhho89** [comment]
> I tried add the `node-sass` and `node-gyp` directly to the `pagake.json` and it bypassed the problem. However, after doing this, there is another problem araised with `l10n`. Trying to fingure it out.

The Probelm 
```bash
ENOENT: no such file or directory, scandir '/var/folders/2z/169nvw1959q444m88mg24prc0000gn/T/broccoli-10881ZqfXS0rWIq4v/out-861-broccoli_merge_trees//var/folders/2z/169nvw1959q444m88mg24prc0000gn/T/broccoli-10881ZqfXS0rWIq4v/out-861-broccoli_merge_trees'


Stack Trace and Error Report: /var/folders/2z/169nvw1959q444m88mg24prc0000gn/T/error.dump.027ea1cdeb583673f9f08a5e2e797c1b.log
```

**Comment by cweitat** [comment]
migration to vue
