### ISSUE TITLE
Make attendee form ticket specific

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8740]
Other platforms have the option to make different forms for buyers or different tickets. This is useful when an event has different sessions or an online vs. an onsite presence option. For onsite attendees organizers might want to collect food preferences for example. This is not important for virtual attendees. Therefore we need the option to have different forms for different people. Please implement the feature and ensure all form text is translatable.

![Screenshot from 2023-05-24 11-46-46](https://github.com/fossasia/open-event-frontend/assets/1583873/5196d8f8-691d-451b-a438-2e72ba9f9017)

Below the "required form fields" section change the section "Information to Collect" to a button "add custom form". When an organizer clicks this button a "Custom Form 1" appears. Here the form should have the option to choose who to collect the info from: Buyer, Attendee (with the option for specific ticket types).

![Screenshot from 2023-05-24 11-59-15](https://github.com/fossasia/open-event-frontend/assets/1583873/9b887e1e-0975-4f73-9aa0-26e5c64bd1fd)

Below "Custom Form 1" continue to show the button "Add form". When an organizer clicks this button now "Custom Form 2" appears. Here the form "2" should have the option to choose who to collect the info from: Buyer, Attendee (with the option for specific ticket types). BUT: It should only have the options for any group that has not been used yet in "Form 1".

Edge Cases:
* Ensure the form only shows up 1 if the ticket buyer and attendee is the same person.
* If the ticket buyer gets two tickets that are linked to two different forms show the two forms to fill in.

**Comment by lthanhhieu** [comment]
Hi team,
I'm working on this.
