### ISSUE TITLE
Redesign Burger Menu for Mobile Views

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8752]
The mobile view of events is cluttered.

for a) not logged in
The standard mobile view is as follows.
![Screenshot from 2023-05-26 15-08-47](https://github.com/fossasia/open-event-frontend/assets/1583873/3df541e7-64d4-466a-9297-e13336c0aa94)
for b) logged in accounts
![Screenshot from 2023-05-26 15-15-46](https://github.com/fossasia/open-event-frontend/assets/1583873/76c69c00-5b4b-4c9e-aa6e-6ba23201734e)

Change the burger menu as follows when the user browses event pages (only!).
a) for not logged in users 
* [ ] show the event menu items in the burger menu instead of showing it in the middle of the screen. 
* [ ] so delete the current event menu view from the screen middle.
![Screenshot from 2023-05-26 15-13-49](https://github.com/fossasia/open-event-frontend/assets/1583873/5741fc5f-07a5-49c9-80d0-c8c99a6d4c50)
b) for logged in users 
* [ ] show the event menu items in the burger menu 
* [ ] also delete it from the screen middle
* [ ] show the name of the user and show the system menu items in a secondary menu list (so the user scrolls over the user name and a secondary list shows up.

**Comment by shubham-200315** [comment]
Hi! @mariobehling can I work on this issue? 
And it would be a great help if you can provide more details of exactly what menu bar and its items should look like?
