### ISSUE TITLE
Enhance the top menu bar on mobile views

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8753]
![Screenshot from 2023-05-26 15-28-25](https://github.com/fossasia/open-event-frontend/assets/1583873/2ac2971b-480a-4625-8b83-597fe45b6746)
Compare https://eventyay.com/e/7cfe0771/schedule

On the mobile view of the event pages change the top menu. Do not change it on other pages, but on the event pages show this:
* Do not show "Create Event" on top right
* Instead show "eventyay" on the top right
* Instead of showing "eventyay" on the top left show the logo of the event here. If the event does not have a logo, display "Home" here.
* On the mobile page do not show the logo on top of the image.

**Comment by Leslie-Wong-H** [comment]
It is preferred to redesign the header to be material ui-like when mobile such that it could be planned to wrap up a hybrid mobile app seamlessly to publish at F-Droid and Google Play.

**Comment by nihalmishranoob** [comment]
Could I help contribute to this?

**Comment by Leslie-Wong-H** [comment]
You are strongly welcome.

**Comment by ntthitrinh** [comment]
Hi @mariobehling,
The changes above only apply to the cases that have logged in. And if you have not logged in, then it will not change anything, right?

**Comment by mariobehling** [comment]
The changes apply to all users.

When the user clicks on "eventyay" it directs the user to the home page same as on desktop version.

**Comment by mariobehling** [comment]
When the user clicks on the event logo the user is directed to the start page of the event same as on desktop version.

**Comment by lthanhhieu** [comment]
> When the user clicks on the event logo the user is directed to the start page of the event same as on desktop version.

Hi @mariobehling ,
I am not sure that we are the same page or not. The start page event is this page right?
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/4d26f098-d0a1-4451-ab29-2a1d3a6f975b)

If not, please share me the start page you mentioned.

**Comment by mariobehling** [comment]
> > When the user clicks on the event logo the user is directed to the start page of the event same as on desktop version.
> 
> Hi @mariobehling , I am not sure that we are the same page or not. The start page event is this page right? ![image](https://user-images.githubusercontent.com/135117837/257447032-4d26f098-d0a1-4451-ab29-2a1d3a6f975b.png)
> 
> If not, please share me the start page you mentioned.

Yes, correct.

**Comment by mariobehling** [comment]
However this issue is not only about the event page, but the top menu bar should be changed on all event pages for a dedicated event. Thanks
