### ISSUE TITLE
Reduce area occupied by time and search field on schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8757]
On the mobile view the schedule page fields for time and search occupy two rows. Please reduce the required space and show both fields in one row. When the user clicks on the search field automatically expand the width of the search field to cover the entire row.

Current: **This is the current view:**
![Screenshot from 2023-05-26 17-45-12](https://github.com/fossasia/open-event-frontend/assets/1583873/800db877-ce19-441c-a828-a3194966facc)
compare https://eventyay.com/e/7cfe0771/schedule

Expected: **Both fields should be there still, but when the user clicks into the search box it should expand.**

Intended view ![Screenshot from 2023-07-03 12-40-51a](https://user-images.githubusercontent.com/1583873/250534337-f563f77c-1e89-479b-9e9b-33b812b4c664.png)

Compare the idea of an expanding search box here for example https://codepen.io/k185/pen/PQajXE

**Comment by blackmouse572** [comment]
Can I work on this?

**Comment by lthanhhieu** [comment]
Moving to #8758
