### ISSUE TITLE
Redesign Menu Area on Schedule Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8758]
The schedule page has a lot of filter options, but we also need to ensure the user can easily find the schedule itself. Therefore please redesign and reduce the number of rows used by filters on the schedule page as follows:

* Row 1: Schedule (Calendar View) [Clear Filters Icon] [Sort by]
* Row 2: [Public Schedule] [My Schedule] [My Speaker Sessions] (for logged in users)
* Row 3: [Time Zone] [Search] 
* Row 4: [All] [Date 1] [Date 2] etc.
* Row 5:  [Track] [Room] [Sessions]

![Screenshot from 2023-05-26 18-05-56](https://github.com/fossasia/open-event-frontend/assets/1583873/45ef6fa0-1ea8-4209-892e-4fa815fbae51)

Compare https://eventyay.com/e/7cfe0771/schedule

**Comment by Sarthak-Singh04** [comment]
Could you please provide me with a layout or design type that will help ensure better understanding of design.

![Screenshot_20230603-110705~2](https://github.com/fossasia/open-event-frontend/assets/106304584/f784ad89-8e37-45a5-a97d-41605f7f3cc3)


![Screenshot_20230603-110720](https://github.com/fossasia/open-event-frontend/assets/106304584/7bb86a55-54a6-43ba-b8f5-8d7781c37d39)


I think you want this type of design 🤔🤔

**Comment by cweitat** [comment]
Row 3 and 4 solving by this https://github.com/fossasia/open-event-frontend/issues/8757

**Comment by lthanhhieu** [comment]
compare with:
https://2019.fossasia.org/event/schedule.html#

**Comment by ntthitrinh** [comment]
Hi @mariobehling 
I have a question regarding Row 5. Only [track], [room], and [sessions] are mentioned above. 
However, when I checked the code, I found four dropdowns. [Track] [Room] [Session Type] [Session Level] 
Are they all arranged in a row? [Track] [Room] [Session Type] [Session Level]

![image](https://github.com/fossasia/open-event-frontend/assets/139523899/8e00129f-4f99-4107-a449-689f2e41da3e)

**Comment by mariobehling** [comment]
@ntthitrinh Yes, thanks for the clarifying questions.

> Are they all arranged in a row? [Track] [Room] [Type] [Level]

Yes, please, do that.
