### ISSUE TITLE
Great user experience

### ISSUE THREAD

**Issue by Anurag1008** [fossasia/open-event-frontend#8765]
![image](https://github.com/fossasia/open-event-frontend/assets/129081739/23ea1840-81a0-47aa-9503-f7e24bac79a6)

It will be great from user point of view if div of group center at middle.

**Comment by Sahilgupta4103** [comment]
Hey, I can help with that.
I am a 3rd-year student at graphic era university. I have been learning web development from the last 2 years. I can make it more precisely

**Comment by cweitat** [comment]
@Anurag1008 Please elaborate on your question.
