### ISSUE TITLE
Refactor: Add/replace 'Actions' heading to buttons column in all tables

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#878]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Many tables either have an empty heading or 'Action' for the column containing buttons 

**Expected behavior:**
The heading for the column containing buttons should be 'Actions' in all the tables

**Comment by ritikamotwani** [comment]
I would like to work on it .

**Comment by geekyd** [comment]
@ritikamotwani Sure go ahead.
