### ISSUE TITLE
Implement rich text links in custom forms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8783]
Currently custom forms cannot have links. Please implement rich text links.

Ensure that all text is translatable

**Comment by mariobehling** [comment]
The implementation of this issue has been misunderstood. Basically the developer has just duplicated the implementation of "paragraph". Instead here we need a way to add rich-text links, e.g. URLs to the question text itself. This is not a category of questions. Here we need the ability to have links in the questions. 

@cweitat This should not have been merged.

**Comment by mariobehling** [comment]
An example for a rich text link are the links in the consent form. How can we have those rich text links in the other question texts as well?

![Screenshot from 2023-06-26 00-21-59](https://github.com/fossasia/open-event-frontend/assets/1583873/8ecab315-94a1-42d7-980a-141d30c5dcd7)

**Comment by lthanhhieu** [comment]
Hi @mariobehling 
Below is the mock-up for rich text link as discussed. Please let me know if you have any feedback.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/b5d5114f-b196-4105-b6ff-ed586f3ee69d)

**Comment by mariobehling** [comment]
Thank you, looks good.

**Comment by mariobehling** [comment]
Unfortunately this PR still results in the same issue as the previous PR. The text is disappearing in custom forms.
a) on public order page
b) on the attendee form

Can be tested on the PRs deployment and easily be seen by starting the ticket order here for example https://open-event-frontend-git-fork-lthanhhieu-lthanhh-3e68f0-eventyay.vercel.app/e/8f889410

![Screenshot from 2023-07-16 10-28-24](https://github.com/fossasia/open-event-frontend/assets/1583873/51ed4c15-a85c-4f36-a2f5-30f27fe17fd5)

![Screenshot from 2023-07-16 10-31-36](https://github.com/fossasia/open-event-frontend/assets/1583873/58114160-2bd9-40f2-bf2c-baf0097db2f6)
