### ISSUE TITLE
Change the "age" field of the custom form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8787]
Change the age field of the custom form and display the following options:

- 18-24
- 25-34
- 35-44
- 45-54
- 55-64
- 65-74
- 75-84
- 85+
- I prefer not to say

Ensure that all text is translatable

**Comment by lthanhhieu** [comment]
Hi @mariobehling , @cweitat and @norbusan 
Add 1 option:
Under 18
