### ISSUE TITLE
Implement language form fields in the attendee form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8788]
Please implement two language form fields in the attendee form.

Question 1:
What is your native language, or what language are you most fluent in? (optional)

Question 2:
Are you fluent in any other of the following languages? (optional)

Provide the following options as answers. Allow attendees to choose multipls options as answers (e.g. two languages):

- English 
- Español 
- عرب
- 中文
- Français
- Bahasa Indonesia

Ensure that all text is translatable

**Comment by Shel-2607** [comment]
Hi! @mariobehling can I work on this issue?

**Comment by lthanhhieu** [comment]
Hi @mariobehling , @cweitat and @norbusan 
We will use checkbox for the anwsers.

**Comment by thegaro0310** [comment]
Hi @lthanhhieu and @mariobehling ,

I would love to contribute for this issue. I could help you with this

**Comment by lthanhhieu** [comment]
Hi @thegaro0310,
Thank you for helping us. We already done with it.
