### ISSUE TITLE
Make custom form question translatable by the organizer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8800]
Forms can be translated into other languages, but custom form question cannot. Therefore please add this feature to the attendee form.

* Add a button "Add translation"
* Add a dropdown menu with a list of languages when the user clicks
* After the user has chosen the language show a form field to add the question (show which languages was translated)
* When the user changes the interface language show the correct translation.

Before

![Screenshot from 2023-06-16 12-02-55](https://github.com/fossasia/open-event-frontend/assets/1583873/74c99164-f778-4509-9760-40ec848444a9)

After
![Screenshot from 2023-06-16 11-50-19](https://github.com/fossasia/open-event-frontend/assets/1583873/236fd643-4a07-4815-a088-1b22ad94c0d5)

**Comment by mariobehling** [comment]
Please ensure the questions are translatable into all system languages.

Note, some languages need to be listed as a system language also. They are not yet listed. So, also need to be added to the general language dropdown. Compare https://github.com/fossasia/open-event-frontend/issues/8845

- Arabic - عربي
- Norwegian - Bokmål
- Swedish - Svenska


![Screenshot from 2023-06-28 08-26-08](https://github.com/fossasia/open-event-frontend/assets/1583873/07aa1909-8374-4581-9d59-64dd66f50305)

**Comment by mariobehling** [comment]
There are just three languages missing from the dropdown in https://github.com/fossasia/open-event-frontend/issues/8845.

The dropdown menu in the attendee form only shows 5 languages. Expected: Show all languages of the system.

**Comment by mariobehling** [comment]
Translations of number fields currently cannot be saved.

![Screenshot from 2023-06-28 21-59-41](https://github.com/fossasia/open-event-frontend/assets/1583873/7fd6603a-4184-4722-bdb5-83210f76aed5)

**Comment by mariobehling** [comment]
Custom translations for Chinese do not show up. Tested with Simplified and Traditional Chinese.

![Screenshot from 2023-06-28 22-13-55](https://github.com/fossasia/open-event-frontend/assets/1583873/b4db3301-48e5-4635-b806-366da92bc565)

**Comment by khangon** [comment]
> Custom translations for Chinese do not show up. Tested with Simplified and Traditional Chinese.
> 
> ![Screenshot from 2023-06-28 22-13-55](https://user-images.githubusercontent.com/1583873/249600866-b4db3301-48e5-4635-b806-366da92bc565.png)
Hi @mariobehling 
Yes, I saw this bug. I will make a PR later.
