### ISSUE TITLE
Give a 'No Unread Notifications' helper text on notifications page in case of no new notifications.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#881]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://user-images.githubusercontent.com/17252805/30723269-bd2b2250-9f53-11e7-8620-a9cc5cf0a988.png)

**Expected behavior:**

- Show helper text
- Hide mark all as read button, if no notifications are there to mark as read

**Comment by ritikamotwani** [comment]
I would like to work on this.
