### ISSUE TITLE
Confirmation Order screen show questions in text only

### ISSUE THREAD

**Issue by lthanhhieu** [fossasia/open-event-frontend#8816]
**Describe the bug**
After user confirms the order, the questions that user answered displayed as text only. That should be displayed as the question type with organizer defined.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/e2d476e2-7a3c-4f0f-91f8-0f9cf158267b)

**Comment by mariobehling** [comment]
Actually for now text is sufficient. More is out of scope. Therefore unassigning and closing the issue for now.
