### ISSUE TITLE
Dropdown year should have the feature years

### ISSUE THREAD

**Issue by lthanhhieu** [fossasia/open-event-frontend#8817]
Currently, the drop down for year selection is have the range from 1930 to current year.
In that case we need user inputs the feature year, we won't able to do. Therefore, I would like to add the feature year. And the default value for this should be current year.
For example:
startYear=currentYear-100
endYear=current+100
defaultValue=currentYear

**Comment by mariobehling** [comment]
Very similar to https://github.com/fossasia/open-event-frontend/issues/8840

Closing #8840 

Feedback from users is that the year form field in the attendee form should work similar to the number field area. In the number field area a minimum number and a maximum number can be entered. Please implement the same way for the year field.

Number field with minimum and maximum.
![Screenshot from 2023-06-26 21-21-26](https://github.com/fossasia/open-event-frontend/assets/1583873/0360de51-8ad0-49eb-bd57-41b50245063a)

Year field should have the same feature with minimum and maximum year.
![Screenshot from 2023-06-26 21-21-52](https://github.com/fossasia/open-event-frontend/assets/1583873/be941313-8d67-4af4-90f8-55219fb395c8)
