### ISSUE TITLE
Unexpected error displayed when saving event in Speaker section

### ISSUE THREAD

**Issue by lthanhhieu** [fossasia/open-event-frontend#8819]
When create new event,
In speaker section, if we do not chose any kind and perform action saving the event, the unexpected error will be displayed at the right bottom corner following the image.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/61acbd49-dba1-4707-aaa6-476b0185e745)

**Comment by mariobehling** [comment]
For an unknown reason fields have to be filled in here, e.g. sessions or Call for Speakers.
