### ISSUE TITLE
Fix validations in session-speaker-form component

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#882]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Fix the validations for dropdowns in session-speaker-form component.

**Comment by akshitahluwalia** [comment]
@geekyd I would like to work on this issue. Please assign it to me. Thanks!.

**Comment by shreyanshdwivedi** [comment]
@geekyd I would love to work on this issue. Can u please assign it to me?

**Comment by k4ni5h** [comment]
What is the status of this issue?

**Comment by vaibhavsingh97** [comment]
@k4ni5h You can work on this issue

**Comment by ParthS007** [comment]
I am working on this :+1:

**Comment by geekyd** [comment]
@ParthS007 We need to add validations to the dropdowns to session-speaker-form
(https://github.com/fossasia/open-event-frontend/blob/development/app/components/forms/session-speaker-form.js)

**Comment by srv-twry** [comment]
Since a  new session-speaker form has been added by @ritikamotwani I guess we can close this. I have already added the validations on that new form.
