### ISSUE TITLE
Add session API on public/cfs/index route

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#883]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Add session API on public/cfs/index route to enable session proposal for a speaker.

**Comment by zamhaq** [comment]
@geekyd I would like to work on this.

**Comment by geekyd** [comment]
@zamhaq Sure! Please go ahead.

**Comment by zamhaq** [comment]
@geekyd could you point me to where I can get the session API? `open-event-backend` ?

**Comment by geekyd** [comment]
You can check all the APIs here https://open-event-api.herokuapp.com/ but currently the heroku build is down so please check https://api.eventyay.com/

**Comment by zamhaq** [comment]
@geekyd I am having some trouble with phantom-js setup :- 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zams/.npm/_logs/2017-09-25T17_38_37_492Z-debug.log
```
is this a known issue ?
