### ISSUE TITLE
Do not show formatting options in paragraph box in attendee form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8831]
The attendee form has an option for a paragraph box. It currently shows formatting options. Similarly to Google forms it should not show formatting options.

![Screenshot from 2023-06-26 00-47-36](https://github.com/fossasia/open-event-frontend/assets/1583873/e638c55b-b0dd-4117-9620-e1ceeef64feb)

**Comment by minhho89** [comment]
Fixed.
Remove format buttons for the Paragraph box.


![Image](https://github.com/fossasia/open-event-frontend/assets/61931543/eabc859f-3297-4c57-beb8-5ec8cee29bab)

Resolving in this [PR](https://github.com/fossasia/open-event-frontend/pull/8896)

**Comment by mariobehling** [comment]
Do not show formatting options but keep the line breaks if the user types into the box, please.

**Comment by marcoag** [comment]
> Do not show formatting options but keep the line breaks if the user types into the box, please.

Should be solved by: https://github.com/fossasia/open-event-frontend/pull/8910. Feel free to close after a quick check on the deployment.

**Comment by minhho89** [comment]
Thanks for the merge.
Tested on development branch, worked as expected.
