### ISSUE TITLE
Implement minimum and maximum for year fields in attendee form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8840]
Feedback from users is that the year form field in the attendee form should work similar to the number field area. In the number field area a minimum number and a maximum number can be entered. Please implement the same way for the year field.

Number field with minimum and maximum.
![Screenshot from 2023-06-26 21-21-26](https://github.com/fossasia/open-event-frontend/assets/1583873/0360de51-8ad0-49eb-bd57-41b50245063a)

Year field should have the same feature with minimum and maximum year.
![Screenshot from 2023-06-26 21-21-52](https://github.com/fossasia/open-event-frontend/assets/1583873/be941313-8d67-4af4-90f8-55219fb395c8)

**Comment by Leslie-Wong-H** [comment]
UI effect: 
![image](https://github.com/fossasia/open-event-frontend/assets/27696701/ed462843-a964-482c-8714-153df7dca434)

![image](https://github.com/fossasia/open-event-frontend/assets/27696701/251eb5f3-3828-4221-af64-d1e8ff903280)

**Comment by Leslie-Wong-H** [comment]
Desired Run Time pseudo UX Effect: 

![xcz](https://github.com/fossasia/open-event-frontend/assets/27696701/569bd435-ad7a-4ca1-b8c1-a1ba449224aa)

Merely generated by dummy devtools dom operation.

**Comment by mariobehling** [comment]
Similar to https://github.com/fossasia/open-event-frontend/issues/8817

Therefore closing this one.
