### ISSUE TITLE
Improve gender option question in attendee form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8842]
Change the current gender question to the following:

1. Change the question to:
* Which of these categories describe your gender identity? (check all that apply)
2. Change the options to choose from as below and change it from a dropdown to a checkbox where the user can click several options.
* Man
* Woman
* Transgender
* Non-binary
* Genderqueer
* An identity not listed here.
* I prefer not to say.

Current gender options. Please change it to multi checkbox and use the above question format.
![Screenshot from 2023-06-26 21-51-03](https://github.com/fossasia/open-event-frontend/assets/1583873/1828d87d-cc00-4a3b-8229-00fc21ee6be3)

**Comment by cweitat** [comment]
@mariobehling I think checkbox is too long. Can we have stick to dropdown?

**Comment by mariobehling** [comment]
They want checkbox, because they want to give people the option to choose multiple genders.

**Comment by lthanhhieu** [comment]
Hi @mariobehling 
I found that Gender question did not change to _**"Which of these categories describe your gender identity? (check all that apply)"**_ and found the bug 
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/b91fd591-a43d-44f8-8c2d-abd16b3a6928)
Therefore, I will reopen that ticket
