### ISSUE TITLE
Languages missing from language dropdown

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8845]
Some languages are already translated mostly, but do not appear in the dropdown menu for languages. Please add the following:
* Arabic - عربي
* Norwegian - Bokmål
* Swedish - Svenska

![Screenshot from 2023-06-27 07-26-29](https://github.com/fossasia/open-event-frontend/assets/1583873/8889368e-1ed0-47f7-89b6-4a214151ace8)

**Comment by Dvinod1** [comment]
Hi am new to this project, can I get some advice about this problem
