### ISSUE TITLE
Order form does not show enough information when user order multiple tickets.

### ISSUE THREAD

**Issue by khangon** [fossasia/open-event-frontend#8848]
Steps to reproduce:
1. Create a new event
2. Input your name and add three types of tickets: free, paid, and donation.
3. In the attendee form, add 3 custom forms corresponding to 3 types of tickets: free, paid, and donation.
Each form adds a field with the type Yes/No, include, or require.
Include the field [Have you received a Wikimedia scholarship?]
Click Next twice to move through the season and speaker screens.
Enter information, save it as a draft, and make it public.
4. Order tickets corresponding to three types of tickets: free, paid, and donation.
5. Input the full information in Registration Information.
6. Click Order Now.
7. Check the information after the order is successful.

#Actual result:
7. Information about ticket donation information is not displayed.
#Expected Result:
7. Information about ticket donation information must be displayed as free ticket, or paid ticket.

![image](https://github.com/fossasia/open-event-frontend/assets/135116292/2e074f55-2aab-4b93-b9d3-eb89a216a480)

**Comment by lthanhhieu** [comment]
fixed in other PR
