### ISSUE TITLE
Cryptic payment description transmitted to Stripe

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8870]
The payment description transmitted to Stripe should be "eventyay.com - [Event Name]". Currently a cryptic key is transmitted.

![Screenshot from 2023-06-29 19-25-53](https://github.com/fossasia/open-event-frontend/assets/1583873/b319b87c-379e-4ca8-9408-456aef21ddfe)

**Comment by catInOrbit** [comment]
Hi @mariobehling 

The cryptic key you saw is actually the ID of the stripe payment itself. Specifically it's the ID of the stripe paymentIntent object 

Every stripe transaction has an ID. When you click on any transaction in the stripe dashboard there's an ID section that shows this exact ID

![Group 1](https://github.com/fossasia/open-event-frontend/assets/49814026/30eefe5c-31c6-4c66-8439-9d62299348a3)


technically this is not a bug and doesn't impact transaction operation. It's simply having a name or description to your transaction for clarity. The original stripe design flow in system seems to use ID for transaction's description

Will look into it and rename to eventyay, but it's not a critical  bug

**Comment by mariobehling** [comment]
@catInOrbit Is it possible to make it to "Eventyay [Event Name]"? It seems like other services do this.

**Comment by catInOrbit** [comment]
@mariobehling 

Payment description with pattern Eventyay [Event Name] has been added in PR https://github.com/fossasia/open-event-server/pull/8960

Example of successful payments in dashboard:

![Screenshot_2023-07-07_14-23-31](https://github.com/fossasia/open-event-frontend/assets/49814026/bfb3ef63-1b0f-48a0-aeda-78838c56885b)
![Screenshot_2023-07-07_14-23-45](https://github.com/fossasia/open-event-frontend/assets/49814026/465cb059-0deb-431b-8342-98713142e8b6)

**Comment by mariobehling** [comment]
Solved by https://github.com/fossasia/open-event-server/pull/8960
