### ISSUE TITLE
Can't read errors related to unfilled fields in the form

### ISSUE THREAD

**Issue by marcoag** [fossasia/open-event-frontend#8878]
**Describe the bug**

When filling in the attendee form errors shown for unfilled fields are unreadable. Issues are:
1. Errors are not fitting the screen properly as words in questions are tied together by an underscore "_".
2. Errors are not using the choosen language, e.g. when the user is using Spanish, the error still quotes the English question mentioning question in English language needs to be filled in. Expected: The user should see a message in their own language including the questions from the form in their own language.

![2023-06-30_17-02](https://github.com/fossasia/open-event-frontend/assets/3855564/e6594c13-41f2-47d0-a2e3-49809ac0315f)

It also disappears too fast so I can't read much of it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/bdaa2bc5
3. Select **1 free ticket** and click on "Order Now"
4. Scroll down to bottom
5. Click on "Order Now"

**Expected behaviour**
I can read what fields I need to fill in on the error.

**Screenshots**
See explanation

**Desktop (please complete the following information):**
 - OS: arch
 - Browser: chromium
 - Version: 113.0.5672.92 (Official Build) Arch Linux (64-bit)

**Comment by lthanhhieu** [comment]
- Make the error readable
- The error should be shown for customer to read easy.

**Comment by mariobehling** [comment]
![Screenshot from 2023-08-01 10-27-59](https://github.com/fossasia/open-event-frontend/assets/1583873/378487db-c4b8-459f-abc7-bf9a3c4b0143)

After the last PR some fields are not recognized as selected.
