### ISSUE TITLE
Enable mirage for tests 

### ISSUE THREAD

**Issue by dilpreetsio** [fossasia/open-event-frontend#888]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently the tests are dependent on the api server.

**Expected behavior:**
We should implement mirage in the application instead of depending on the server.

@niranjan94 @sumedh123 @harshitagupta30 @CosmicCoder96 What do you think about this?

**Comment by iamareebjamal** [comment]
Complete AFAIK. And we'll add more if needed.
