### ISSUE TITLE
 Unable to re-add language after deleting

### ISSUE THREAD

**Issue by khangon** [fossasia/open-event-frontend#8881]
Steps to reproduce:
1. Create a new event
2. Input event name and tickets paid
3. In attendee form, Turn on Attendee Form
4. Add Custom Form Field, Add 3 languages English 日本語, Deutsch
5. Delete the  日本語 (Japanese) language field
6. CLick Add Translation, Add  日本語 (Japan) language again

#Expected Result:
6. Dropdown language shows all languages that have not been added yet

#Actual result:
6. Can't re-add 日本語 (Japanese) language, dropdown language not show  日本語 (Japanese) language
![attendee_language](https://github.com/fossasia/open-event-frontend/assets/135116292/0fe802cf-e461-4b52-a8bc-e5703236ec83)

**Comment by lthanhhieu** [comment]
Hi @khangon,
Please also check the issue:
Step 1: Click on the edit icon to edit the custom field.
Step 2: Click the delete icon.
#Expected Result:
2. The icon delete is disabled while the field is being edited.
#Actual result:
2. You are still allowed to delete custom fields.
