### ISSUE TITLE
New Texts need Translations

### ISSUE THREAD

**Issue by Bekka592** [fossasia/open-event-frontend#8883]
The new text needs to be translated to all offered languages (with priority on Spanish, Chinese, Indonesian, Arabic, and French).

In particular, the following tokens need to be translated:
* Which of these categories describe your gender identity? (check all that apply) -> here: both the string from the server and the one from the frontend
* Man
* Woman
* Transgender
* Non-binary
* Genderqueer
* An identity not listed here.
* I prefer not to say.
* New: I consent to the Wikimania
* New: the "Other" option from "What is your native language, or what language are you most fluent in?"

**Comment by mariobehling** [comment]
Gender question in the attendee form is not translated: 
Which of these categories describe your gender identity? (check all that apply) [Man, Woman, Transgender, Non-binary, Genderqueer, An identity not listed here, I prefer not to say.]

We need the translations as follows:

* Spanish
¿Cuál de estas categorías describe tu identidad de género? [ Hombre, Mujer, Transgénero, No-binario, Género-queer, Una identidad que no se liste aqui, Prefiero no indicarlo.]
* Traditional Chinese
以下哪一個類別描述了您的性別認同？ （勾選所有適用項）[男性、女性、跨性別者、非二元性別、酷兒、此處未列出的身份、不便透露。]
* Bahasa Indonesia
Manakah dari kategori berikut yang menggambarkan identitas gender anda? (centang semua yang sesuai) [Pria, Wanita, Transgender, Non-biner, Genderqueer, Identitas tidak tercantum di sini, saya memilih untuk tidak menyebutkan.]
* Laquelle de ces catégories décrit votre identité de genre ? (cochez tout ce qui s'applique) [Homme, Femme, Transgenre, Non-binaire, Genderqueer, Une identité non répertoriée ici (veuillez préciser), Je préfère ne pas dire.]
* أي من هذه الفئات تصف هويتك الجنسية؟ (حدد كل ما ينطبق) [رجل ، امرأة ، متحول جنسيًا ، غير ثنائي ، جنس ، هوية غير مدرجة هنا (يرجى ذكر ذلك)  ، أفضل عدم التصريح.]

**Comment by mariobehling** [comment]
Closing in favor of https://github.com/fossasia/open-event-frontend/issues/8914
