### ISSUE TITLE
Form answers are in English instead of the local language on the overview page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8884]
When ordering a ticket in another language the attendee form shows translated questions and answer in the correct way. On the overview page however answers to form questions are partly shown in English. Expected is that answers are also in the local language.

Compare https://eventyay.com/e/8f889410

![Screenshot from 2023-06-30 15-35-52](https://github.com/fossasia/open-event-frontend/assets/1583873/55c96a05-744a-4008-b312-58d51a68320e)

**Comment by ntthitrinh** [comment]
Hi @mariobehling,
I fixed it to show the translation of the answer.
But when I test again, I see some newly added languages have not been provided with translations for Attendee Information.
Do you want to do translations for these languages as well?
Català (Catalan)
Hrvatski (Croatian)
తెలుగు (Telugu)
Arabic - عربي
Norwegian - Bokmål
Swedish - Svenska
This will take more time to translate than expected.
