### ISSUE TITLE
Error Message Given Name required even though it is not marked as required

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8899]
If the given name or last name is not required in the attendee form it should not be necessary to fill it in.

Compare https://test.eventyay.com/e/01cb248f

![Screenshot from 2023-07-02 15-45-14](https://github.com/fossasia/open-event-frontend/assets/1583873/d3f49257-d4b0-46b0-b850-748d90f2e2c4)

**Comment by Bekka592** [comment]
I tried all kinds of different combinations, but I do not get this error message. Can you verify whether the bug still exists for you?

![Screenshot_20230704_183936](https://github.com/fossasia/open-event-frontend/assets/127369686/271fb1e9-8025-409a-a112-bcfef22b85af)

![Screenshot_20230704_183833](https://github.com/fossasia/open-event-frontend/assets/127369686/bbaacaeb-fb64-4fef-826f-88411a9217a8)

**Comment by cweitat** [comment]
Unable to reproduce
