### ISSUE TITLE
Updates to Indonesian Translation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8909]
Indonesian needs updates for the following:

- To= Sampai
- On-line = daring
- Tatap muka = Luring
- Singapore = Singapura
- In-person tiket = Tiket secara langsung
- Virtual Ticket = tiket virtual
- Penyelengara = penyelenggara

**Comment by minhho89** [comment]
There is no `In-person tiket ` in the `id.po` file. Only `In-person event` on the English side. @mariobehling Please re-confirm whether it is to update for the `In-person event`.
