### ISSUE TITLE
Update spelling and translations of attendee form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8914]
![Screenshot from 2023-07-04 07-29-20](https://github.com/fossasia/open-event-frontend/assets/1583873/1fab11e6-df4b-4cbc-811d-dd590b9e5559)
Please change the following in the attendee form
1. Consent form field -> Code of conduct consent
2. There is a space before the full stop that should not be there.
* I agree to the terms of the Universal Code of Conduct and the Friendly Space Policy . -> I agree to the terms of the Universal Code of Conduct and the Friendly Space Policy.
* I consent to the Wikimania photo policy . ->  I consent to the Wikimania photo policy.

In particular, the following tokens need to be changed/translated:
1. Translate "I consent to the Wikimania photo policy." using online translation.
2. Move the "Other" option to the bottom of the list for the question "What is your native language, or what language are you most fluent in?" and translate it using online translations
3. Add the following missing translations in the attendee form (also change it in backend):
* Which of these categories describe your gender identity? (check all that apply) [Man, Woman, Transgender, Non-binary, Genderqueer, An identity not listed here, I prefer not to say.]
* Spanish
¿Cuál de estas categorías describe tu identidad de género? [ Hombre, Mujer, Transgénero, No-binario, Género-queer, Una identidad que no se liste aqui, Prefiero no indicarlo.]
* Traditional Chinese
以下哪一個類別描述了您的性別認同？ （勾選所有適用項）[男性、女性、跨性別者、非二元性別、酷兒、此處未列出的身份、不便透露。]
* Bahasa Indonesia
Manakah dari kategori berikut yang menggambarkan identitas gender anda? (centang semua yang sesuai) [Pria, Wanita, Transgender, Non-biner, Genderqueer, Identitas tidak tercantum di sini, saya memilih untuk tidak menyebutkan.]
* Laquelle de ces catégories décrit votre identité de genre ? (cochez tout ce qui s'applique) [Homme, Femme, Transgenre, Non-binaire, Genderqueer, Une identité non répertoriée ici, Je préfère ne pas dire.]
* أي من هذه الفئات تصف هويتك الجنسية؟ (حدد كل ما ينطبق) [رجل ، امرأة ، متحول جنسيًا ، غير ثنائي ، جنس ، هوية غير مدرجة هنا (يرجى ذكر ذلك)  ، أفضل عدم التصريح.]

**Comment by Bekka592** [comment]
I implemented the "Move the 'Other' option to the bottom of the list for the question 'What is your native language, or what language are you most fluent in?'" part in [this PR](https://github.com/fossasia/open-event-frontend/pull/8915).
