### ISSUE TITLE
Change the cursor to pointer of the globe icon in the footer

### ISSUE THREAD

**Issue by jainkeval** [fossasia/open-event-frontend#892]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

When we move cursor on the **globe** icon near the language selecting menu in the footer it changes to **selection** cursor:![image](https://user-images.githubusercontent.com/26284185/31054071-31555d38-a69a-11e7-8294-9455a4ebd135.png)

**Expected behavior:**

It should remain as default **pointer** cursor:![image](https://user-images.githubusercontent.com/26284185/31054100-ed81456c-a69a-11e7-9fe4-009f619ef06c.png) when we move it on the globe icon.

![cursor_issue](https://user-images.githubusercontent.com/26284185/31054152-f747a8ba-a69b-11e7-9ed6-04e3cf56e87a.gif)

**Comment by jainkeval** [comment]
I would like to work on it

**Comment by anshulwadhawan** [comment]
@geekyd 
Is this issue open to be worked upon ?
@jainkeval 
Are you still working on this issue?

**Comment by jainkeval** [comment]
Yeah I am working

**Comment by jainkeval** [comment]
The issue is invalid, hence closing it.
