### ISSUE TITLE
Somehow the latest developmet branch `yarn start` failed to launch - 'ar' locale file not found error 

### ISSUE THREAD

**Issue by Leslie-Wong-H** [fossasia/open-event-frontend#8922]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Sync [my fork branch](https://github.com/Leslie-Wong-H/open-event-frontend/tree/development) with [fossasia/open-event-frontend](https://github.com/Leslie-Wong-H/open-event-frontend/tree/development), the latest commit hash: d4b4530ab2ae1c939566ef3add32a0ee143bbde9
2. locally, git fetch, git pull, 
3. `yarn start`
4. Failed to launch, a blank page with the following error 
![image](https://github.com/fossasia/open-event-frontend/assets/27696701/d06ca47d-eaab-410a-a8ee-cc42f8ef790b)
![image](https://github.com/fossasia/open-event-frontend/assets/27696701/6dff2a25-b30d-4ced-ac65-c3b392beeb26)

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Possible Issue & PR related: 
[Languages missing from language dropdown](https://github.com/fossasia/open-event-frontend/issues/8845)
[feature-8845: Languages missing from language dropdown](https://github.com/fossasia/open-event-frontend/pull/8865/files)
with the 'ar' keyword context.

**Comment by Blaize15** [comment]
Please follow the instructions for installing on your local machine carefully. follow the guide [https://github.com/Blaize15/open-event-frontend/blob/development/docs/installation/local.md](https://github.com/Blaize15/open-event-frontend/blob/development/docs/installation/local.md). You have skipped some step in middle.
