### ISSUE TITLE
[Integrate translation channels] Create UI

### ISSUE THREAD

**Issue by minhho89** [fossasia/open-event-frontend#8946]
Sub-task of #8763 

Creating the UI on the Front end

> Describe the solution you'd like
> ![image](https://github.com/fossasia/open-event-frontend/assets/61931543/01162eb5-d694-408c-9c7d-6441d4c3b195)
>To add a section labelled "Live Translations Channels" at the pointed section. UI to be similar to the bottom screenshot where it should be a dropdown field with all possible languages + dropdown for audio stream source (i.e. Streamyard) + text field for URL to the audio stream.

>UI to define only streamyard supported at the moment
> ![image](https://github.com/fossasia/open-event-frontend/assets/61931543/d53f6945-1051-4e5e-87b2-eb32ebe59ff7)

> Frontend UI to allow switching of languages
> ![image](https://github.com/fossasia/open-event-frontend/assets/61931543/874d9d8c-9608-4733-ae86-aaa291531739)
> Translate Icon/Text to show at end of menu link if translation exists.

> If translation exists, on hover icon, show the languages with the first choice being the defined video language. On select of other language, main video stream (Youtube) to be muted and Streamyard to be played on top of it.

**Comment by cweitat** [comment]
@minhho89 @lequoctrung-it the UI has to integrate the APIs that were created by @catInOrbit

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/fossasia/open-event-frontend/issues/8763
