### ISSUE TITLE
Convert speakers table to ember model table and integrate speaker API on it.

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#895]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![image](https://user-images.githubusercontent.com/17252805/31071722-b9e58324-a782-11e7-88cc-9b6bf11aaeae.png)

**Comment by sumedh123** [comment]
@CosmicCoder96 PR is already there: https://github.com/fossasia/open-event-frontend/pull/646

**Comment by CosmicCoder96** [comment]
@sumedh123 Apologies, it was two months old, did't notice that, will you be continuing the work on it? Anyway closing this as duplicate of #638

**Comment by sumedh123** [comment]
@CosmicCoder96 Yes, a little change needs to be done. After that its good to merge. Will do that.
