### ISSUE TITLE
Feature request: Automatic attendee check-in for virtual(online) event

### ISSUE THREAD

**Issue by sukso96100** [fossasia/open-event-frontend#8951]
**Is your feature request related to a problem? Please describe.**

Hello, I organized a virtual event using eventyay number of weeks ago. I could see some statics about registration on dashboard and attendee details of course. But after the event, I couldn't find any data about attendees who actually checked-in for the virtual event. There were manual check-in feature of course, But we didn't use that because it was virtual event: On virtual event, People join event anytime they want during event hours, and organizers can't check that everytime. 

To gather some data for check-in attendees, I researched for possible alternative sources that I was look for.
And I found, BBB raw recording contains meeting participant list. So I requested for that data on eventyay support channel. But It was refused for privacy and lack of human resource reason (which is totally understandable)

Fortunately, As we used YouTube playback for playing pre-recorded session. I could get some insights with YouTube's analytics tool. But What if there were only live sessions? Organizers won't be able to get data for checked-in attendees.

It is important to see how many of the registrants actually participate. Because the number of registrations isn't the only factor that determines the scale and success of an event. The same goes for online events.

I think this solution might solve problem for future virtual event organizers who uses eventyay.

**Describe the solution you'd like**
A simple automatic attendee check-in for virtual event.
If attendee clicks "Join live event" during event hours, Not just bring them to virtual venue, but also automatically mark them as "Checked-in" on eventyay.

**Comment by mariobehling** [comment]
Closing this issue in favor of this issue here https://github.com/fossasia/open-event-server/issues/9065 which is a simplification of this issue.
