### ISSUE TITLE
Wrong ticket price on order overview page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8969]
If a user gets a paid ticket, e.g. in-person ticket, and a virtual ticket at the same time the overview page shows a wrong total price. The total price on the order PDF is correct though.

In the following screenshot the number should be 100 USD, instead it is 2000 USD.
![Screenshot from 2023-07-17 22-58-33](https://github.com/fossasia/open-event-frontend/assets/1583873/b2890fcc-d47a-489e-b6ac-a94d9acf042f)

**Comment by ntthitrinh** [comment]
Hi @mariobehling,
When I order one paid ticket and one free ticket,
after [payment] is done.
In the view screen as above, I only see the issue order information, which is lost after reloading. (issue #8687)
The remaining 100 USD change to 2000 USD. I cannot reproduce.
Could you please provide me with the steps to reproduce this?
Thank you.

**Comment by mariobehling** [comment]
This issue appears at random. This is the problem.

**Comment by lthanhhieu** [comment]
Hi @mariobehling ,
As @ntthitrinh and you mentioned, I will keep this ticket as monitoring.
Can you share the link to the order ticket and we need the access rule to access the event for checking it. If not, I am not sure that we can fix it without information.

**Comment by mariobehling** [comment]
Please find the internal link here https://eventyay.com/orders/073586f4-6f5d-4be2-96f5-9f59365d90b0/view @lthanhhieu

**Comment by mariobehling** [comment]
Ok, so this issue has apparently been fixed by another PR in the same area. Thank you.
