### ISSUE TITLE
Badge creation in wizard misses default options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8980]
When creating a badge, the default options are missing. Expected show the default options.

Badge
* badge default size should be 4x6
* default orientation portrait
* background transparent

**Fields**:
- Sample Text: Sample Text
- Position in mm - What is the default? Make this field into a number field similar to the attendee form
![Screenshot from 2023-07-20 13-50-14](https://github.com/fossasia/open-event-frontend/assets/1583873/dd7989fa-2c1c-46f2-93e8-e9c616717805)

- Font name: Arial 
- Default size: 14 (add a dropdown similar to Google docs)
- Weight: Default, Italic, Bold, Bold Italic etc.
- Text transform: None
- Text Rotate (deg): Options are missing
- Text color: default: Black

![Screenshot from 2023-07-20 13-27-05](https://github.com/fossasia/open-event-frontend/assets/1583873/6e4c294f-ec42-4f16-99e2-cd5f2177767a)

**Comment by nnhathung** [comment]
Hi @mariobehling ,

for the weight, you mentioned it value as Italic, Bold, Bold Italic etc. 

But that values is for font style, not font weight. valid values for font weight is Thin, Light, Bold...

So should we change the name 'Weight" to "Font style"? or we add another component for "Font style" select

FYI: @lthanhhieu

**Comment by mariobehling** [comment]
@nnhathung I think each application defines this a bit different. In Inkscape this is all defined as Font Styles. So, yes, I think you are right the better term is Font Styles.

Please take into account that each font has different options. 
Compare options with Rubik
![Screenshot from 2023-07-27 15-20-38](https://github.com/fossasia/open-event-frontend/assets/1583873/c2376966-9f4c-4a2c-937b-01158d0c6331)

And compare options with Sans Serif
![Uploading Screenshot from 2023-07-27 15-23-29.png…]()

**Comment by lthanhhieu** [comment]
Hi @mariobehling, 
I will do it next week due to it will take time to change on both size: front-end and server.
