### ISSUE TITLE
Implement dedicated Rocket Chat rooms for each video room

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8987]
Currently the chat feature shows one event chat for the entire event. Implement the option to add chat rooms to each video room. Ensure this works well on mobile screens.

Background: There is already the option to have chat communication if participants use Jitsi or other interactive video options in the system. However if the room uses Youtube there is no chat option. Therefore we need this option.

On the chat configuration page create an overview showing:

* [ ] Enable event chat (which is the current chat, that should be shown under the left-hand chat tab)
* [ ] The list of rooms with the option "Enable room chat" and alternatively "Enable event chat on this room" (the latter option is simply the current implementation)

![Screenshot from 2023-07-21 19-40-26](https://github.com/fossasia/open-event-frontend/assets/1583873/f562c5a3-06f8-46bb-8ecc-2835258c06d9)
![Screenshot from 2023-07-21 19-40-08](https://github.com/fossasia/open-event-frontend/assets/1583873/f78fd0d0-558e-4145-ade3-345083b044ed)

**Comment by nnhathung** [comment]
Hi @mariobehling 
![image](https://github.com/fossasia/open-event-frontend/assets/139526485/8cb779a7-d7b5-4eb0-a7ce-bd256a266198)

 this is the UI for enable chat for specific room, do you have any feedback on this?

FYI: @lthanhhieu

**Comment by lthanhhieu** [comment]
Hi @mariobehling,
Just a concern on behavior of chat enable/disable.
Enable chat event will allow enabling room's chat and disable chat event makes room's chat disable too?
Or does it not rely on each other?

**Comment by mariobehling** [comment]
Here is an idea for a UI.

![Screenshot from 2023-07-26 09-44-57](https://github.com/fossasia/open-event-frontend/assets/1583873/b63b36e0-bcd0-49ea-92a5-832ba04a8cb9)

On the chat configuration page the organizer can choose if a room displays a dedicated event room or the global event chat.

Left is the room name. Then the organizer can select the option. Only one option can be chosen at a time.

**Comment by nnhathung** [comment]
Hi @mariobehling 
**Left is the room name. Then the organizer can select the option. Only one option can be chosen at a time.**
=> room name here you mean microlocation name or video room name? because currently event page is showing video room name.

**Comment by mariobehling** [comment]
Room name means micro location and video room. I dont know about the backend, but on the frontend microlocation and video room name are the same.

**Comment by mariobehling** [comment]
So, if unsure follow room name of microlocation.
