### ISSUE TITLE
Event Wizard: Sessions and Speakers page show session colors config in big height

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8988]
The sessions and speakers page of the wizard shows color config in bug height after recent changes.

![Screenshot from 2023-07-23 14-42-14](https://github.com/fossasia/open-event-frontend/assets/1583873/3ccc7402-01f7-485b-b29d-1ad93f5881c1)

**Comment by ntthitrinh** [comment]
Hi @mariobehling
This bug arose due to the impact code Badge (issue #8986).
So this bug will be fixed with ticket #8986.
Please help me check on issue 8986.
Thanks

**Comment by mariobehling** [comment]
Yes, correct. I am closing this as it has been fixed, but unfortunately after the fix a new issue in the same area appeared -https://github.com/fossasia/open-event-frontend/issues/9014 .
