### ISSUE TITLE
If attendee filled in ticket in non-English language ticket name and form are not visible on overview and ticket page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#8990]
If an attendee filled in ticket in non-English language ticket name, price and form are not visible on 
a) the ticket page in the table on the top
b) in the ticket name form in the middle
c) in the form area no form is visible
d) on the PDF there is no ticket name

Possibly related to https://github.com/fossasia/open-event-frontend/issues/8969

Apparently the form and ticket name are only visible in the original language used by the attendee when he/she filled in the form (here Indonesian). 
* This should be visible no matter what language people use
* The ticket PDF should always portray the ticket name and data correctly no matter what language.

![FireShot Capture 017 - Completed Order](https://github.com/fossasia/open-event-frontend/assets/1583873/3e3fc932-2b40-4222-9504-ff0f6c98a55f)

**Comment by lthanhhieu** [comment]
Hi @mariobehling 
This ticket cannot be reproducible, I will mark this ticket as monitoring. We will track this about 3 weeks. If this not reproduce, I will close that ticket.

**Comment by mariobehling** [comment]
It seems this issue was solved as part of a previous PR fix. Thank you. Closing it.
