### ISSUE TITLE
Add filtering option to the home page (UI Only)

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#9]
<img width="1680" alt="screen shot 2017-04-22 at 10 42 39 pm" src="https://cloud.githubusercontent.com/assets/2404372/25306570/67e11098-27ad-11e7-83d0-7817329bf3da.png">

We need similar filtering options on the landing page. 

**What is expected ?**
- Filtering options as a separate [component](https://guides.emberjs.com/v2.12.0/getting-started/core-concepts/#toc_components) added to the home page.
- UI Only for now. So you need not worry about filtering the data yet. 

**References:**
- https://guides.emberjs.com/v2.12.0/components/defining-a-component/
- https://semantic-ui.com/elements/input.html
- https://semantic-ui.com/collections/form.html
- https://semantic-org.github.io/Semantic-UI-Ember/#/modules/dropdown

**Comment by utkarshnath** [comment]
@niranjan94 plz assign this to me
