### ISSUE TITLE
Select Session Type button hits the browser border

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9008]
In some screen resolutions on the schedule page the button "Select Session Type" hits the browser border. The button is also wider than the buttons on the right side bar above. Expected: Button should have the same width as the buttons above and it should not hit the browser border.

Compare https://eventyay.com/e/8f889410/schedule

**Buttons on the top right.**

![Screenshot from 2023-07-27 18-08-24](https://github.com/fossasia/open-event-frontend/assets/1583873/e2b10bf7-eee5-4285-8cf0-e352f837d1df)

**The select session type button should have same width and behavior.**
![Screenshot from 2023-07-27 18-08-06](https://github.com/fossasia/open-event-frontend/assets/1583873/c7eb49d6-7898-473e-8ada-05382b2ea1a8)

**Comment by den319** [comment]
did this issue is assigned to anyone?
