### ISSUE TITLE
Cannot add rooms or microlocations

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9014]
After recent changes it is not possible to add rooms or microlocations in the final wizard step.

![Screenshot from 2023-07-31 14-23-39](https://github.com/fossasia/open-event-frontend/assets/1583873/9fb9c058-850c-4958-afda-b1345e05379f)

The previous issue here https://github.com/fossasia/open-event-frontend/issues/8988 was fixed. However, a new issue in the same area as described above appeared.

**Comment by lthanhhieu** [comment]
Hi @mariobehling 
I cannot reproduce that issue. As checking, #8988 just change the css, I'm not think that possible to impact code.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/59c23480-f36c-40e8-b4e4-49545151d9f4)

**Comment by lthanhhieu** [comment]
However, I also create the PR for this issue by adding the condition
