### ISSUE TITLE
Error when trying to export attendees

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9018]
Exporting attendees causes errors in the console. Download screen does not open. 

```
state-machine.js:86 Error while exporting TypeError: Cannot read properties of null (reading 'state')
    at attendees.js:59:1
(anonymous) @ state-machine.js:86
attendees.js:70 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at attendees.js:70:1
```

Info from Sentry: https://sentry.fossasia.org/organizations/eventyay/issues/4281/

{snip} {console.error("Error while exporting",e),n.notify.error(t.toUpperCase()+" "+n.l10n.t("Export has failed."))}).finally(function(){n.set("isL {snip}

**Download**
[error.odt](https://github.com/fossasia/open-event-frontend/files/12223059/error.odt)

"Task is going on" screen message also stops after a few times.

![Screenshot from 2023-08-01 02-20-49](https://github.com/fossasia/open-event-frontend/assets/1583873/bc6bdae8-3dd1-4e0c-bd25-cbd0af435d2a)

``

Compare https://eventyay.com/events/8f889410/tickets/attendees/completed

**Comment by mariobehling** [comment]
@lthanhhieu The PRs did not solve the issues. Please check here https://eventyay.com/events/8f889410/tickets/attendees/completed

You need to login to eventyay with your TMA email. I gave you access on the system. The order download works, but attendee download has issues.

**Comment by mariobehling** [comment]
It is probably related to this PR https://github.com/fossasia/open-event-server/pull/9005

I tested this PR on a test event but not on the Wikimania event. I guess there are some conflicts?

**Comment by lthanhhieu** [comment]
Hi @mariobehling 
I also test in live server and see that I can download attendees file without any issue.
Can we have the call to resolve that issue?

**Comment by lthanhhieu** [comment]
Close as fixed with confirmation from @mariobehling in gitter.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/1224e403-2a46-4de4-89c0-b7030ce245f8)
