### ISSUE TITLE
Fix typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by therohitramesh** [fossasia/open-event-frontend#903]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

Todo: Correct a typo in CONTRIBUTING.md

**Comment by therohitramesh** [comment]
I would like to work on this.

**Comment by niranjan94** [comment]
@therohitramesh it would be much better if you actually tell what typo it is. `Fix typo in CONTRIBUTING.md` doesn't really say anything. Its equivalent to not having an issue at all :)
