### ISSUE TITLE
Video rooms not displayed in order and other issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9053]
There is something wrong with the display of the videos channels. Compare the "Plenary" on the Wikimania event (need to get a free virtual event ticket to join the event and see the issue).

1. If the room name is long there is no spacing between the "Room Name" and the button "Languages"
2. Currently after adding translated languages the order of rooms changes (can be tested by reload). It is different than the order define in the wizard.

![Screenshot from 2023-08-11 21-30-27](https://github.com/fossasia/open-event-frontend/assets/1583873/db3b706e-b460-432d-a447-63f73fe2b933)

**Comment by cweitat** [comment]
@mariobehling the side panel is supposed to be an overlay of the video not on the same index.

**Comment by cweitat** [comment]
@mariobehling issue is dont know what filter is available.
https://test-api.eventyay.com/#microlocations-microlocations-under-an-event-get
documentation has none too

**Comment by cweitat** [comment]
@mariobehling theres nothing to do if room name is too long. Either remove the word languages or break the dropdown to 2nd line which will look inconsistent

**Comment by mariobehling** [comment]
Unfortunately this issue is back after I added an additional networking room using another video source.

![Screenshot from 2023-08-11 21-30-27](https://github.com/fossasia/open-event-frontend/assets/1583873/db3b706e-b460-432d-a447-63f73fe2b933)

**Comment by cweitat** [comment]
@mariobehling there's a very high chance that some code was reverted

**Comment by cweitat** [comment]
@mariobehling yup my code was reverted
