### ISSUE TITLE
Typo in the create session part

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-frontend#906]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
It is written Ssubtitle 
![screenshot 24](https://user-images.githubusercontent.com/22588035/31308539-ebb2b1c6-ab95-11e7-8443-6f567f84a193.png)

**Expected behavior:**
It should be Subtitle

**Steps to reproduce:**
Change the text.

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `node -v`
```

```
output of `npm ls ember-cli`
```

**Comment by geoemm** [comment]
Hello, I created a pull request that fixes this mistake. Please review.
