### ISSUE TITLE
Unable to get badge form by ticket

### ISSUE THREAD

**Issue by nnhathung** [fossasia/open-event-frontend#9061]
this API is returning error 500: https://test-api.eventyay.com/#badge-forms-get-badge-form-by-ticket-get

**Comment by lthanhhieu** [comment]
Hi @cweitat 
Could you please share me the request you used? Because I test and it worked normally.
![image](https://github.com/fossasia/open-event-frontend/assets/135117837/19f80686-9b45-4c34-890f-033917cc6c63)

**Comment by cweitat** [comment]
@shaunBoahCodes
