### ISSUE TITLE
Reduce complexity of mobile screens and minimize white spaces

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9075]
Improve mobile screens of event pages as follows:
1. Show buttons "Join Live Event" and "Add to Calendar" in one row
2. Take out event dates and times below the "Join event button"
3. Reduce the white spaces on all other mobile event pages

Improve the mobile screen of the event start page
1. Only show the social media icons and "Recent Tweets" on the mobile event start (home) page
2. Take out the date below the "Add to calendar"
3. Reduce the white spaces on the mobile event start page 

**Compare current event mobile page**

![Screenshot from 2023-08-11 00-07-58](https://github.com/fossasia/open-event-frontend/assets/1583873/95e22e37-a5df-4d81-b5db-334ee078da97)

**Expected event mobile page**

![Screenshot from 2023-08-11 00-07-58b](https://github.com/fossasia/open-event-frontend/assets/1583873/aa8dc015-6ee9-47ee-9f80-5b2124497992)

**Compare current event start page**
![Screenshot from 2023-08-11 00-25-10](https://github.com/fossasia/open-event-frontend/assets/1583873/53e1ac6a-463f-4ee7-8fd7-a97fbd60caaa)

**Expected event start page**
![Screenshot from 2023-08-11 00-25-10b](https://github.com/fossasia/open-event-frontend/assets/1583873/275891a5-0f58-478e-abc2-b61d528410b5)

**Comment by Sranjan0208** [comment]
Can I work on this issue?
