### ISSUE TITLE
On the organizer chat configuration page sort rooms according to the definition in the wizard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9087]
The chat rooms are sorted randomly on the organizer config page. Please sort them according to the defined order in the wizard.

![Screenshot from 2023-08-12 05-00-41](https://github.com/fossasia/open-event-frontend/assets/1583873/4e441638-9343-4580-810a-f5b9581d99a6)

**Comment by nnhathung** [comment]
completed with this PR https://github.com/fossasia/open-event-frontend/pull/9113
