### ISSUE TITLE
Unable to cancel order

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9106]
I am not able to cancel order "Unexpected Error" shows up.

https://eventyay.com/orders/ff06a4e4-1f97-4f4d-9591-bb8e068c884f/view

**Comment by mariobehling** [comment]
This seems to be happening with this order only.

**Comment by lthanhhieu** [comment]
Hi @mariobehling ,
I can cancel that order. I this case user found any unexpected error, I suggest to refresh the page first.
