### ISSUE TITLE
Mobile screen: Add to Calendar button changing height

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9114]
The calendar button changes the height. Possible solutions a) decrease the required spacing the button to the left and right, so the button stays longer using one line only, b) Make the blue "Join Event" button responsive as well. Goal is to keep both buttons using the same height.

![Screenshot from 2023-08-15 16-27-59](https://github.com/fossasia/open-event-frontend/assets/1583873/ce6cb20c-aeed-43a4-9065-4d058360e674)

**Comment by lthanhhieu** [comment]
Hi @mariobehling 
Could you please share me the device you are using?
