### ISSUE TITLE
Event is still saved when an invalid value is entered in "Floor" in the "Sessions & Speakers" page

### ISSUE THREAD

**Issue by khangon** [fossasia/open-event-frontend#9120]
**Describe the bug**
As the organizer, I input to the Floor fields some values that include at least a "letter" for Microlocations or Virtual Online Rooms in the Sessions, Microlocations, Session Types setting, then tap on the Save button without Error. In the Overview>Event Checklist, I selected Sessions, Tracks & Microlocations, there is no value for Floor fields.

**To Reproduce**
Steps to reproduce the behaviour:
1.	Create an Event.
2.	Input a valid value for the required fields.
3.	Turn on "Sessions & Speakers".
4.	In block "Microlocations or Virtual Online Rooms", input Room fields and Floor fields with the value including at least a "letter".
5.	Save the Event without Error.
6.	In Overview>Event Checklist, select the Sessions, Tracks & Microlocations.
7.	Observe the value in the Floor fields. 

**Expected behaviour**
All valid input values are saved, or the error message should be shown for invalid values.

**Screenshots**
![Screenshot from 2023-08-16 14-48-49](https://github.com/fossasia/open-event-frontend/assets/135116292/1211c72a-2943-4ab8-b64e-178dc1715e6a)

**Comment by mariobehling** [comment]
It is possible that there is no floor information.
