### ISSUE TITLE
Speakers getting disconnected from sessions when editing social media profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#9121]
When a speaker adds social media entries to their account they get disconnected from some sessions if they have several sessions.

![Screenshot from 2023-08-16 17-10-35](https://github.com/fossasia/open-event-frontend/assets/1583873/fb116e92-3609-438b-b40d-cee11a349cd5)

**Comment by Ainali** [comment]
To be precise, I was disconnected from all sessions except the one I was editing.
