### ISSUE TITLE
Make the dropdown menu for unread notifications look better

### ISSUE THREAD

**Issue by jainkeval** [fossasia/open-event-frontend#914]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://user-images.githubusercontent.com/26284185/31404782-a4cb432c-ae1a-11e7-975d-d7f838e723eb.png)

**Expected behavior:**

It should look better.

**Comment by stealthanthrax** [comment]
@jainkeval , i would like to work on this issue.

**Comment by sumedh123** [comment]
@stealthanthrax @jainkeval is working on this one. You can take up other issues. @jainkeval Any updates on this?
