### ISSUE TITLE
The value of the status dropdown list cannot be displayed in full

### ISSUE THREAD

**Issue by khangon** [fossasia/open-event-frontend#9140]
**Describe the bug**
As the organizer, I want update status for session, however when I open dropdown list, it cannot be displayed in full options of the last 2 elements of the session list.

**Expected behaviour**
The value of the status dropdown list must to displayed in full

**Screenshots**

![Screenshot from 2023-08-16 15-22-35](https://github.com/fossasia/open-event-frontend/assets/135116292/a4b2802d-4fd8-4baf-b981-b0952700d541)

**Comment by mariobehling** [comment]
Yes, we observed this issue before, but this might be hard to fix as the entire current implementation of those pages would have to be changed. We might be able to solve this in the next version of the UI only.
