### ISSUE TITLE
Fix alignment of menu items in dextop mode

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#919]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![screen shot 2017-10-13 at 3 24 43 am](https://user-images.githubusercontent.com/12807846/31521208-4cd9e7ec-afc6-11e7-949d-6da4fa0faa02.png)

**Expected behavior:**
The menu items should remain left aligned in desktop mode

The file to look for is https://github.com/fossasia/open-event-frontend/blob/development/app/components/tabbed-navigation.js

**Comment by iknityanand** [comment]
can i work on it ??

**Comment by geekyd** [comment]
@iknityanand There is a PR already opened for this issue #920. Please take up some other issue.
