### ISSUE TITLE
Change the cursor to default for the subheadings in footer

### ISSUE THREAD

**Issue by therohitramesh** [fossasia/open-event-frontend#921]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
When the cursor is over the "Copyright" text and all the other subheadings of the footer it becomes a **pointer**.

**Expected behavior:**
The cursor is expected to be **default** ![image](https://user-images.githubusercontent.com/20316398/31574297-1ec86d4a-b0ea-11e7-87dc-cd08f62bc250.png) as those texts are not hyperlinks.

**Comment by therohitramesh** [comment]
I would like to work on this.

**Comment by gr8shivam** [comment]
In `app/styles/partials/utils.scss`, `!important` is used which isn't recommended.  Here's the exact code:-

```
.link {
    cursor: pointer !important
}
```
