### ISSUE TITLE
Add API server links to Readme

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#926]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
There is no link/reference of the API docs in the readme

**Expected behavior:**
Add link of the API doc in the readme

**Comment by jsjqian** [comment]
I'd like to work on this issue
