### ISSUE TITLE
Make quick-filter component responsive and remove side bar search for mobile

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#93]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26495600/da3b0ab4-4241-11e7-9846-54c14034f786.png)

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26495582/c8ee65e4-4241-11e7-9b69-1a494b525200.png)

Also the `placeholder text` should be `location`, not `united states` (suggestion)
@niranjan94 On orga server, only one of the  three fields is visible on mobile screens (the main Field), Is  that the right way to go?

**Steps to reproduce:**

View it on portrait mode on mobile.
I will send a fix for it.

**Comment by niranjan94** [comment]
Yep. This is good. Also, as a part of this, can you remove search bar from the mobile side-bar ?

**Comment by CosmicCoder96** [comment]
@niranjan94 Sure, on it.
