### ISSUE TITLE
Hide Mark all as read button on notifications page, when there are no new notifications

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#934]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://user-images.githubusercontent.com/17252805/32121169-1490070e-bb79-11e7-82a8-232dcb034b0a.png)

**Comment by pradeepgangwar** [comment]
@CosmicCoder96  I have made a PR. Please review it.
