### ISSUE TITLE
Map component on public event page overflows

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#95]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

![image](https://cloud.githubusercontent.com/assets/17252805/26518384/6392d4aa-42cd-11e7-9431-f4f25355f4c2.png)

![image](https://cloud.githubusercontent.com/assets/17252805/26518397/9ad9cae0-42cd-11e7-93c3-b2b9a5888d9d.png)

The Map overflows and adress disappears with the `address` heading coming onto the map itself.

**Expected behavior:**

It should be a stackable grid so that the address does not flow in to the map component on smaller screens
![image](https://cloud.githubusercontent.com/assets/17252805/26518362/e6cd15de-42cc-11e7-96aa-aec72a749528.png)

**Steps to reproduce:**

View it on mobile(both landscape and portrait)

I will work on this.

**Comment by geekyd** [comment]
@CosmicCoder96 Please go ahead!
