### ISSUE TITLE
Increase code coverage by adding acceptance test

### ISSUE THREAD

**Issue by dilpreetsio** [fossasia/open-event-frontend#958]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
Currently the code coverage is very low. This is because of lack of tests.

**Expected behavior:**
Add tests for routes to increase code coverage

**Comment by iamareebjamal** [comment]
Too broad. It's difficult tracking parent issues. They become detached after some time. An issue for tests is already open, so closing
