### ISSUE TITLE
Add user tickets page

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#98]
<img width="1680" alt="screen shot 2017-05-28 at 10 46 10 pm" src="https://cloud.githubusercontent.com/assets/2404372/26530694/76fdfabc-43f7-11e7-9b9b-940670d52c9d.png">

---

- Located at `/my-tickets`
- Three tabs (hence three routes). But make them all use a common template since only data is gonna vary. 
    - Upcoming events - `/my-tickets`
    - Saved events - `/my-tickets/save`
    - Past events - `/my-tickets/past`
- Use the event card component (wide mode). But instead of the hashtags at the bottom, use that place to display order ID, order date and ticket name. (make it such that any data can be passed in to the component to display instead of the hashtags. Will be useful later) (ie. make data yieldable in place of the hashtag)

**Comment by CosmicCoder96** [comment]
@niranjan94 The upcoming events route is `/my-tickets` and not `/my-tickets/upcoming`?

**Comment by niranjan94** [comment]
Yep. Correct.
