### ISSUE TITLE
Installing and running Open-Event-Frontend via Docker

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#983]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

Currently, project is not have feature to install via `Docker`
**Expected behavior:**

Expected behavior would be to install and run the project via Docker
**Steps to reproduce:**

**Yes, I would like to work on this issue**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `node -v`
```

```
output of `npm ls ember-cli`
```

**Comment by simsausaurabh** [comment]
@bhaveshAn please share the status of work. If you are not working on it, then I would like to take it further.

**Comment by Kreijstal** [comment]
You can do it using https://github.com/maxlorenz/oevent-docker-compose/
