### ISSUE TITLE
Few links still serve on 'http'

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/open-event-frontend#987]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

Few of the links in the project still serve on 'http'
**Expected behavior:**

They should serve on 'https'
**Steps to reproduce:**

**Comment by geekyd** [comment]
@simsausaurabh Can you specify which links are loaded over http?

**Comment by simsausaurabh** [comment]
@geekyd yes, sure please see the files changed.
