### ISSUE TITLE
Add notifications page

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-frontend#99]
<img width="1680" alt="screen shot 2017-05-28 at 10 55 44 pm" src="https://cloud.githubusercontent.com/assets/2404372/26530765/d0f06504-43f8-11e7-94dc-7e790a2ab0f5.png">

---
- The above image is just representative. We don't want an exact clone of it since the above UI doesn't look very good.
- Unread located at `/notifications`
- All located at `notifications/all`
- The all/unread buttons should be common to both routes
- The mark all as read should only be visible on the unread page

**Comment by utkarshnath** [comment]
@niranjan94 plz assign this to me
