### ISSUE TITLE
Add instructions in documentation to run Open event frontend with open event server local deployment

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-frontend#992]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

Currently the connection to the heroku server is hard coded and there are no instructions available for new users to help them set up open event frontend with a local deployment of open event server.

**Comment by simsausaurabh** [comment]
I am working on it.

**Comment by sumedh123** [comment]
@simsausaurabh Please go ahead. Let us know if you face any problem.
