### ISSUE TITLE
Delete Kubernetes Deployment and Setup Heroku Master branch deployment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#995]
Currently we have an automatic deployment to nextgen.eventyay.com. Please switch this off and stop the engine. It is currently also not working.

In order to simplify the setup to match our current ressources, please set up a Heroku frontend deployment on https://open-event-frontend-dev.herokuapp.com.

**Comment by ParthS007** [comment]
@SaptakS  @shubham-padia  How can I help in solving this? 
Please tell me how should I proceed with this issue. Thanks
