### ISSUE TITLE
Hound CI integration

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/open-event-frontend#999]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

**Expected behavior:**

To keep a track on proper style of code.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

Hound comments on style violations in PRs, allowing us to better review and maintain a clean codebase.

Reference: https://houndci.com/
**System information:** 

```
Your operating system
```

```
output of `node -v`
```

```
output of `npm ls ember-cli`
```

**Comment by simsausaurabh** [comment]
@geekyd @parth @abishekvashok any suggestions ? If approved I would be working on this.

**Comment by abishekvashok** [comment]
Sure you can work on it @simsausaurabh

**Comment by simsausaurabh** [comment]
@abishekvashok thanks, working on it.

**Comment by CosmicCoder96** [comment]
closing this as hound ci is not required for the project. ES lint takes care of code styling on open-event-frontend. The tests will fail automatically in case the styling is not proper.
